var _ = `bulgarian`,
  _ = `%1$s% от %2$s потребителски рецензии за тази игра са положителни`,
  _ = `%1$s% от %2$s потребителски рецензии на %3$s за тази игра са положителни`,
  _ = `%1$s% отстъпка. Обикновено %2$s, намалено до %3$s.`,
  _ = `Специална цена от %1$s.`,
  _ = `Безплатно`,
  _ = `В кошницата`,
  _ = `Добавяне към кошницата`,
  _ = `Закупуване като подарък`,
  _ = `Пускане сега`,
  _ = `Добавяне към библиотеката`,
  _ = `Вписване`,
  _ = `Впишете се, за да добавите този безплатен артикул към акаунта си.`,
  _ = `Меню`,
  _ = `Най-продавани`,
  _ = `Новоиздадени`,
  _ = `На разпродажба`,
  _ = `Търсене в магазина`,
  _ = `Изчистване на търсения термин`,
  _ = `Списък с желания`,
  _ = `Кошница`,
  _ = `ВР заглавия`,
  _ = `Най-популярни връзки`,
  _ = `Начална страница на магазина`,
  _ = `Страхотно преживяване в Steam Deck`,
  _ = `Страхотни на Steam Frame`,
  _ = `Безплатни`,
  _ = `Steam диаграми`,
  _ = `Предстоящи издания`,
  _ = `Точковият магазин`,
  _ = `Подаръчни карти`,
  _ = `Новини и обновления`,
  _ = `Предпочитания`,
  _ = `Преглед`,
  _ = `Най-популярни`,
  _ = `Препоръки`,
  _ = `Категории`,
  _ = `Хардуер`,
  _ = `Начини за игра`,
  _ = `Специални секции`,
  _ = `Преглед на всички`,
  _ = `Още`,
  _ = `Меню`,
  _ = `Предпочитанията ми`,
  _ = `Списъкът ми с желания`,
  _ = `Абонаментите ми`,
  _ = `Следваните ми игри`,
  _ = `Акаунтът ми`,
  _ = `Семейството ми`,
  _ = `Наскоро прегледани`,
  _ = `Продължете оттам, докъдето сте стигнали`,
  _ = `Препоръчано за Вас`,
  _ = `От списъка Ви с желания`,
  _ = `Сваляемо съдържание за Вас`,
  _ = `За Вас`,
  _ = `Преглед на най-популярни дестинации`,
  _ = `Най-популярни дестинации`,
  _ = `Нови и тенденциозни`,
  _ = `Безплатни`,
  _ = `Най-популярни безплатни за пускане`,
  _ = `Най-продавани`,
  _ = `Новоиздадени`,
  _ = `Проучване на ново съдържание в Steam`,
  _ = `Вижте какво е в календара с издания`,
  _ = `Отстъпки и събития`,
  _ = `Всички графики и статистики`,
  _ = `Проучвайте най-популярните заглавия по седмица, месец или година.`,
  _ = `Списъкът Ви с желания`,
  _ = `%1$s отстъпки`,
  _ = `Специални събития`,
  _ = `Популярни заглавия`,
  _ = `Специални оферти`,
  _ = `Препоръки`,
  _ = `Опашка с новоиздадени`,
  _ = `Обществени препоръки`,
  _ = `Интерактивни препоръки`,
  _ = `Личният Ви календар`,
  _ = `Популярни сред приятели`,
  _ = `Steam куратори`,
  _ = `Сваляемо съдържание за Вас`,
  _ = `Опашката Ви за откриване`,
  _ = `Оставете Steam да създаде персонализиран набор от игрални препоръки за Вас`,
  _ = `Проучване на опашката ми`,
  _ = `Получавайте персонализирани препоръки от машинно самообучаващата ни се система`,
  _ = `Получавайте препоръки`,
  _ = `Проучвайте персонализиран списък от игри, които са издадени наскоро или това ще стане скоро.`,
  _ = `Проучване на календара ми`,
  _ = `НОВО`,
  _ = `Върховите Ви жанрове`,
  _ = `Върховите Ви категории`,
  _ = `Преглед на всички жанрове и тематики`,
  _ = `Разширяване`,
  _ = `Свиване`,
  _ = `Преглед на всички тагове`,
  _ = `Всички жанрове и тематики`,
  _ = `Хардуер`,
  _ = `ВР хардуер`,
  _ = `Steam Deck`,
  _ = `Steam контролер`,
  _ = `Steam машина`,
  _ = `Steam Frame`,
  _ = `Valve Index`,
  _ = `Док станция`,
  _ = `Steam хардуер`,
  _ = `Начини за пускане игри`,
  _ = `Специални секции`,
  _ = `Steam фестивал на предстоящите игри`,
  _ = `Steam наградите`,
  _ = `Steam ретроспекция`,
  _ = `Steam лаборатории`,
  _ = `Сваляемо съдържание`,
  _ = `СЪБИТИЯ ЗА РАЗПРОДАЖБИ`,
  _ = `Наскоро прегледани`,
  _ = `Популярни търсения`,
  _ = `Резултати от търсенето`,
  _ = `Върховите Ви жанрове`,
  _ = `Преглед по…`,
  _ = `Няма съответстващи артикули за текущото Ви запитване.`,
  _ = `Разширено търсене`,
  _ = `%1$s игри`,
  _ = `Търсачка`,
  _ = `Меню за магазина`,
  _ = `Включва %1$s игри`,
  _ = `В БИБЛИОТЕКАТА`,
  _ = `В СПИСЪКА С ЖЕЛАНИЯ`,
  _ = `В КОШНИЦАТА`,
  _ = `ИГНОРИРАНИ`,
  _ = `ИЗКЛЮЧЕНО ОТ ПРЕДПОЧИТАНИЯТА`,
  _ = `Категориите ми:`,
  _ = `Никакви`,
  _ = `Филтриране по категория`,
  _ = `Изчистване на филтрите за категория`,
  _ = `Добавяне на категория`,
  _ = `Премахване на категория`,
  _ = `Премахване на тази категория от този артикул.`,
  _ = `Филтриране на списъка Ви с желания до артикули в тази категория`,
  _ = `Всички`,
  _ = `Некатегоризирани`,
  _ = `Добавяне или премахване на категории`,
  _ = `Изчакване за разпродажба`,
  _ = `Списък по рождени дни`,
  _ = `Препоръчани от приятели`,
  _ = `Управление на категории за %1$s`,
  _ = `Текущи категории`,
  _ = `Търсене по име или добавяне на нова категория`,
  _ = `Добавяне на категория`,
  _ = `Другите ми категории`,
  _ = `Предложени категории`,
  _ = `Този артикул от списъка с желания е достигнал лимита от %1$s категории.`,
  _ = `Разширени…`,
  _ = `НОРМАЛНА`,
  _ = `НАЙ-НИСКА ЗА 30 ДНИ`,
  _ = `Тази игра беше с отстъпка за %1$s през последните %2$s дни`,
  _ = `Понастоящем тази игра е на най-ниската цена в рамките на изминалите %1$s дни.`,
  _ = `СЕГА`,
  _ = `Отстъпки спрямо най-ниската цена през предходните 30 дни`,
  _ = `Личният Ви календар`,
  _ = `Персонализиран за Вас списък от нови и предстоящи игри.`,
  _ = `+Още %1$s`,
  _ = `Проучете Вашия пълен персонализиран календар`,
  _ = `Проучване на още`,
  _ = `Нямаме никакви нови издания, които да Ви препоръчаме за този ден. <1>Вижте останалата част от календара си!</1>`,
  _ = `НОВО`,
  _ = `Днес`,
  _ = `dont translate`,
  _ = {
    language: _,
    review_summary_reviewrate: _,
    review_summary_reviewrate_language_specific: _,
    Discount_ARIA_Label: _,
    Discount_ARIA_Label_SpecialPrice: _,
    Price_Free: _,
    AddToCartButton_InCart: _,
    AddToCartButton_AddToCart: _,
    AddToCartButton_PurchaseAsGift: _,
    PlayGameButton_PlayNow: _,
    AddToLibraryButton: _,
    Button_SignIn: _,
    SignInToAddToLibrary_Tooltip: _,
    Menu_OpenFlyout: _,
    Menu_TopSellers: _,
    Menu_NewReleases: _,
    Menu_OnSale: _,
    Menu_SearchPlaceholder: _,
    Menu_ClearSearchTerm: _,
    Menu_Wishlist: _,
    Menu_Cart: _,
    Menu_VR: _,
    Menu_Popover_TopLinks: _,
    Menu_Popover_StoreHome: _,
    Menu_Popover_GreatonDeck: _,
    Menu_Popover_GreatonFrame: _,
    Menu_Popover_FreeToPlay: _,
    Menu_Popover_SteamCharts: _,
    Menu_Popover_Upcoming: _,
    Menu_Popover_PointsShop: _,
    Menu_Popover_GiftCards: _,
    Menu_Popover_NewsAndUpdates: _,
    Menu_Popover_Preferences: _,
    Menu_Popover_Browse: _,
    Menu_Popover_Top: _,
    Menu_Popover_Recommendations: _,
    Menu_Popover_Categories: _,
    Menu_Popover_Hardware: _,
    Menu_Popover_WaysToPlay: _,
    Menu_Popover_SpecialSections: _,
    Menu_Popover_ViewAll: _,
    Menu_Popover_More: _,
    Menu_Popover_Menu: _,
    Menu_Section_Browse_MyPreferences: _,
    Menu_Section_Browse_MyWishlist: _,
    Menu_Section_Browse_MySubscriptions: _,
    Menu_Section_Browse_MyFollowedGames: _,
    Menu_Section_Browse_MyAccount: _,
    Menu_Section_Browse_MyFamily: _,
    Menu_Section_Browse_RecentlyViewed: _,
    Menu_Section_Browse_PickUpWhereYouLeftOff: _,
    Menu_Section_Browse_Recommended: _,
    Menu_Section_Browse_FromYourWishlist: _,
    Menu_Section_Browse_DLCForYou: _,
    Menu_Section_Browse_ForYou: _,
    Menu_Section_Browse_BrowseTop: _,
    Menu_Section_Browse_Top: _,
    Menu_Section_Browse_PopularNew: _,
    Menu_Section_Browse_FreeToPlay: _,
    Menu_Section_Browse_TopFreeToPlay: _,
    Menu_Section_Browse_TopSellers: _,
    Menu_Section_Browse_NewReleases: _,
    Menu_Section_Browse_NewReleases_Desc: _,
    Menu_Section_Browse_Upcoming_Desc: _,
    Menu_Section_Browse_Discounts: _,
    Menu_Section_Browse_Charts: _,
    Menu_Section_Browse_Charts_Desc: _,
    Menu_Section_Browse_Discounts_YourWishlist: _,
    Menu_Section_Browse_Discounts_YourWishlist_Discounts: _,
    Menu_Section_Browse_Discounts_SpecialEvents: _,
    Menu_Section_Browse_Discounts_PopularTitles: _,
    Menu_Section_Browse_Discounts_SpecialOffers: _,
    Menu_Section_Recommendations: _,
    Menu_Section_Recommendations_NewReleasesQueue: _,
    Menu_Section_Recommendations_CommunityRecommendations: _,
    Menu_Section_Recommendations_InteractiveRecommender: _,
    Menu_Section_Recommendations_PersonalCalendar: _,
    Menu_Section_Recommendations_PopularAmongFriends: _,
    Menu_Section_Recommendations_SteamCurators: _,
    Menu_Section_Recommendations_DLCForYou: _,
    Menu_Section_Recommendations_DiscoveryQueue_Title: _,
    Menu_Section_Recommendations_DiscoveryQueue_Description: _,
    Menu_Section_Recommendations_DiscoveryQueue_ActionButton: _,
    Menu_Section_Recommendations_InteractiveRecommender_Description: _,
    Menu_Section_Recommendations_InteractiveRecommender_ActionButton: _,
    Menu_Section_Recommendations_PersonalCalendar_Description: _,
    Menu_Section_Recommendations_PersonalCalendar_ActionButton: _,
    Menu_Section_Recommendations_New: _,
    Menu_Section_Categories_YourTopGenres: _,
    Menu_Section_Categories_YourTopCategories: _,
    Menu_Section_Categories_ViewAll: _,
    Menu_Section_Categories_Expand: _,
    Menu_Section_Categories_Collapse: _,
    Menu_Section_Categories_ViewAllTags: _,
    Menu_Section_Categories_GenresAndThemes: _,
    Menu_Section_Hardware: _,
    Menu_Section_Hardware_VRHardware: _,
    Menu_Section_Hardware_SteamDeck: _,
    Menu_Section_Hardware_SteamController: _,
    Menu_Section_Hardware_SteamMachine: _,
    Menu_Section_Hardware_SteamFrame: _,
    Menu_Section_Hardware_ValveIndex: _,
    Menu_Section_Hardware_SteamDeckDock: _,
    Menu_Section_Hardware_Family: _,
    Menu_Section_WaysToPlay: _,
    Menu_Section_SpecialSections: _,
    Menu_Section_SpecialSections_NextFest: _,
    Menu_Section_SpecialSections_SteamAwards: _,
    Menu_Section_SpecialSections_SteamReplay: _,
    Menu_Section_SpecialSections_SteamLabs: _,
    Menu_Section_SpecialSections_DLCForYou: _,
    Menu_Section_SpecialSections_SaleEvents: _,
    Menu_SearchBar_RecentlyViewed: _,
    Menu_SearchBar_PopularSearches: _,
    Menu_SearchBar_SearchResults: _,
    Menu_SearchBar_YourTopGenres: _,
    Menu_SearchBar_BrowseBy: _,
    Menu_SearchBar_NoMatches: _,
    Menu_SearchBar_AdvancedSearch: _,
    Menu_SearchBar_CategoryGameCount: _,
    Menu_Search: _,
    Menu_Label: _,
    Menu_IncludesXGames: _,
    ItemFlag_InLibrary: _,
    ItemFlag_OnWishlist: _,
    ItemFlag_InCart: _,
    ItemFlag_Ignored: _,
    ItemFlag_ExcludedByPreferences: _,
    Wishlist_Controls_Categories_Header: _,
    Wishlist_Categories_None: _,
    Wishlist_Gamepad_Filter_Category: _,
    Wishlist_Gamepad_Filter_Clear_Category: _,
    Wishlist_Gamepad_Add_Category: _,
    Wishlist_Gamepad_Removecategory: _,
    Wishlist_Controls_Categories_Remove_Tooltip: _,
    Wishlist_Controls_Categories_Filter_Tooltip: _,
    Wishlist_Controls_Categories_All: _,
    Wishlist_Controls_Categories_Uncategorized: _,
    Wishlist_Controls_Categories_Manage: _,
    Wishlist_Categories_Suggested_Discount: _,
    Wishlist_Categories_Suggested_Birthday: _,
    Wishlist_Categories_Suggested_Recommended: _,
    Wishlist_Controls_Categories_Manageitem: _,
    Wishlist_Controls_Categories_Header_Current: _,
    Wishlist_Categories_Dialog_Search: _,
    Wishlist_Categories_Dialog_Add: _,
    Wishlist_Controls_Categories_Header_Other: _,
    Wishlist_Controls_Categories_Header_Suggested: _,
    Wishlist_Categories_Max_Per_App_Reached: _,
    Wishlist_Categories_Dialog_Advanced: _,
    Price_History_Normal_Price: _,
    Price_History_Recent_Low_Price: _,
    Price_History_Recent_Low_Price_Ttip: _,
    Price_History_Current_Low_Price_Ttip: _,
    Price_History_Current_Price: _,
    Price_History_Lowest_Previous_30: _,
    PersonalCalendar_Title: _,
    PersonalCalendar_Subtitle: _,
    PersonalCalendar_More: _,
    PersonalCalendar_Full: _,
    PersonalCalendar_Explore: _,
    PersonalCalendar_EmptyDay: _,
    NewBadge: _,
    Time_Today: _,
    store_ui_dummy: _,
  };
export {
  _ as AddToCartButton_AddToCart,
  _ as AddToCartButton_InCart,
  _ as AddToCartButton_PurchaseAsGift,
  _ as AddToLibraryButton,
  _ as Button_SignIn,
  _ as Discount_ARIA_Label,
  _ as Discount_ARIA_Label_SpecialPrice,
  _ as ItemFlag_ExcludedByPreferences,
  _ as ItemFlag_Ignored,
  _ as ItemFlag_InCart,
  _ as ItemFlag_InLibrary,
  _ as ItemFlag_OnWishlist,
  _ as Menu_Cart,
  _ as Menu_ClearSearchTerm,
  _ as Menu_IncludesXGames,
  _ as Menu_Label,
  _ as Menu_NewReleases,
  _ as Menu_OnSale,
  _ as Menu_OpenFlyout,
  _ as Menu_Popover_Browse,
  _ as Menu_Popover_Categories,
  _ as Menu_Popover_FreeToPlay,
  _ as Menu_Popover_GiftCards,
  _ as Menu_Popover_GreatonDeck,
  _ as Menu_Popover_GreatonFrame,
  _ as Menu_Popover_Hardware,
  _ as Menu_Popover_Menu,
  _ as Menu_Popover_More,
  _ as Menu_Popover_NewsAndUpdates,
  _ as Menu_Popover_PointsShop,
  _ as Menu_Popover_Preferences,
  _ as Menu_Popover_Recommendations,
  _ as Menu_Popover_SpecialSections,
  _ as Menu_Popover_SteamCharts,
  _ as Menu_Popover_StoreHome,
  _ as Menu_Popover_Top,
  _ as Menu_Popover_TopLinks,
  _ as Menu_Popover_Upcoming,
  _ as Menu_Popover_ViewAll,
  _ as Menu_Popover_WaysToPlay,
  _ as Menu_Search,
  _ as Menu_SearchBar_AdvancedSearch,
  _ as Menu_SearchBar_BrowseBy,
  _ as Menu_SearchBar_CategoryGameCount,
  _ as Menu_SearchBar_NoMatches,
  _ as Menu_SearchBar_PopularSearches,
  _ as Menu_SearchBar_RecentlyViewed,
  _ as Menu_SearchBar_SearchResults,
  _ as Menu_SearchBar_YourTopGenres,
  _ as Menu_SearchPlaceholder,
  _ as Menu_Section_Browse_BrowseTop,
  _ as Menu_Section_Browse_Charts,
  _ as Menu_Section_Browse_Charts_Desc,
  _ as Menu_Section_Browse_DLCForYou,
  _ as Menu_Section_Browse_Discounts,
  _ as Menu_Section_Browse_Discounts_PopularTitles,
  _ as Menu_Section_Browse_Discounts_SpecialEvents,
  _ as Menu_Section_Browse_Discounts_SpecialOffers,
  _ as Menu_Section_Browse_Discounts_YourWishlist,
  _ as Menu_Section_Browse_Discounts_YourWishlist_Discounts,
  _ as Menu_Section_Browse_ForYou,
  _ as Menu_Section_Browse_FreeToPlay,
  _ as Menu_Section_Browse_FromYourWishlist,
  _ as Menu_Section_Browse_MyAccount,
  _ as Menu_Section_Browse_MyFamily,
  _ as Menu_Section_Browse_MyFollowedGames,
  _ as Menu_Section_Browse_MyPreferences,
  _ as Menu_Section_Browse_MySubscriptions,
  _ as Menu_Section_Browse_MyWishlist,
  _ as Menu_Section_Browse_NewReleases,
  _ as Menu_Section_Browse_NewReleases_Desc,
  _ as Menu_Section_Browse_PickUpWhereYouLeftOff,
  _ as Menu_Section_Browse_PopularNew,
  _ as Menu_Section_Browse_RecentlyViewed,
  _ as Menu_Section_Browse_Recommended,
  _ as Menu_Section_Browse_Top,
  _ as Menu_Section_Browse_TopFreeToPlay,
  _ as Menu_Section_Browse_TopSellers,
  _ as Menu_Section_Browse_Upcoming_Desc,
  _ as Menu_Section_Categories_Collapse,
  _ as Menu_Section_Categories_Expand,
  _ as Menu_Section_Categories_GenresAndThemes,
  _ as Menu_Section_Categories_ViewAll,
  _ as Menu_Section_Categories_ViewAllTags,
  _ as Menu_Section_Categories_YourTopCategories,
  _ as Menu_Section_Categories_YourTopGenres,
  _ as Menu_Section_Hardware,
  _ as Menu_Section_Hardware_Family,
  _ as Menu_Section_Hardware_SteamController,
  _ as Menu_Section_Hardware_SteamDeck,
  _ as Menu_Section_Hardware_SteamDeckDock,
  _ as Menu_Section_Hardware_SteamFrame,
  _ as Menu_Section_Hardware_SteamMachine,
  _ as Menu_Section_Hardware_VRHardware,
  _ as Menu_Section_Hardware_ValveIndex,
  _ as Menu_Section_Recommendations,
  _ as Menu_Section_Recommendations_CommunityRecommendations,
  _ as Menu_Section_Recommendations_DLCForYou,
  _ as Menu_Section_Recommendations_DiscoveryQueue_ActionButton,
  _ as Menu_Section_Recommendations_DiscoveryQueue_Description,
  _ as Menu_Section_Recommendations_DiscoveryQueue_Title,
  _ as Menu_Section_Recommendations_InteractiveRecommender,
  _ as Menu_Section_Recommendations_InteractiveRecommender_ActionButton,
  _ as Menu_Section_Recommendations_InteractiveRecommender_Description,
  _ as Menu_Section_Recommendations_New,
  _ as Menu_Section_Recommendations_NewReleasesQueue,
  _ as Menu_Section_Recommendations_PersonalCalendar,
  _ as Menu_Section_Recommendations_PersonalCalendar_ActionButton,
  _ as Menu_Section_Recommendations_PersonalCalendar_Description,
  _ as Menu_Section_Recommendations_PopularAmongFriends,
  _ as Menu_Section_Recommendations_SteamCurators,
  _ as Menu_Section_SpecialSections,
  _ as Menu_Section_SpecialSections_DLCForYou,
  _ as Menu_Section_SpecialSections_NextFest,
  _ as Menu_Section_SpecialSections_SaleEvents,
  _ as Menu_Section_SpecialSections_SteamAwards,
  _ as Menu_Section_SpecialSections_SteamLabs,
  _ as Menu_Section_SpecialSections_SteamReplay,
  _ as Menu_Section_WaysToPlay,
  _ as Menu_TopSellers,
  _ as Menu_VR,
  _ as Menu_Wishlist,
  _ as NewBadge,
  _ as PersonalCalendar_EmptyDay,
  _ as PersonalCalendar_Explore,
  _ as PersonalCalendar_Full,
  _ as PersonalCalendar_More,
  _ as PersonalCalendar_Subtitle,
  _ as PersonalCalendar_Title,
  _ as PlayGameButton_PlayNow,
  _ as Price_Free,
  _ as Price_History_Current_Low_Price_Ttip,
  _ as Price_History_Current_Price,
  _ as Price_History_Lowest_Previous_30,
  _ as Price_History_Normal_Price,
  _ as Price_History_Recent_Low_Price,
  _ as Price_History_Recent_Low_Price_Ttip,
  _ as SignInToAddToLibrary_Tooltip,
  _ as Time_Today,
  _ as Wishlist_Categories_Dialog_Add,
  _ as Wishlist_Categories_Dialog_Advanced,
  _ as Wishlist_Categories_Dialog_Search,
  _ as Wishlist_Categories_Max_Per_App_Reached,
  _ as Wishlist_Categories_None,
  _ as Wishlist_Categories_Suggested_Birthday,
  _ as Wishlist_Categories_Suggested_Discount,
  _ as Wishlist_Categories_Suggested_Recommended,
  _ as Wishlist_Controls_Categories_All,
  _ as Wishlist_Controls_Categories_Filter_Tooltip,
  _ as Wishlist_Controls_Categories_Header,
  _ as Wishlist_Controls_Categories_Header_Current,
  _ as Wishlist_Controls_Categories_Header_Other,
  _ as Wishlist_Controls_Categories_Header_Suggested,
  _ as Wishlist_Controls_Categories_Manage,
  _ as Wishlist_Controls_Categories_Manageitem,
  _ as Wishlist_Controls_Categories_Remove_Tooltip,
  _ as Wishlist_Controls_Categories_Uncategorized,
  _ as Wishlist_Gamepad_Add_Category,
  _ as Wishlist_Gamepad_Filter_Category,
  _ as Wishlist_Gamepad_Filter_Clear_Category,
  _ as Wishlist_Gamepad_Removecategory,
  _ as default,
  _ as language,
  _ as review_summary_reviewrate,
  _ as review_summary_reviewrate_language_specific,
  _ as store_ui_dummy,
};
