var _ = `german`,
  _ = `%1$s % der %2$s Nutzerrezensionen für dieses Spiel sind positiv.`,
  _ = `%1$s % der %2$s Nutzerrezensionen für dieses Spiel auf %3$s sind positiv.`,
  _ = `%1$s % Rabatt. Regulärer Preis %2$s reduziert auf %3$s.`,
  _ = `Sonderpreis ist %1$s`,
  _ = `Kostenlos`,
  _ = `Im Warenkorb`,
  _ = `In den Warenkorb`,
  _ = `Als Geschenk kaufen`,
  _ = `Jetzt spielen`,
  _ = `Zur Bibliothek hinzufügen`,
  _ = `Anmelden`,
  _ = `Melden Sie sich an, um diesen kostenlosen Inhalt Ihrem Account hinzuzufügen.`,
  _ = `Menü`,
  _ = `Topseller`,
  _ = `Neuerscheinungen`,
  _ = `Im Angebot`,
  _ = `Im Shop suchen`,
  _ = `Suchbegriff löschen`,
  _ = `Wunschliste`,
  _ = `Warenkorb`,
  _ = `VR-Titel`,
  _ = `Toplinks`,
  _ = `Shop-Startseite`,
  _ = `Für das Steam Deck optimierte Spiele`,
  _ = `Für Steam Frame optimierte Spiele`,
  _ = `Kostenlos spielbar`,
  _ = `Steam-Statistiken`,
  _ = `Bevorstehende Veröffentlichungen`,
  _ = `Punkteshop`,
  _ = `Geschenkkarten`,
  _ = `Neuigkeiten & Updates`,
  _ = `Einstellungen`,
  _ = `Durchstöbern`,
  _ = `Oben`,
  _ = `Empfehlungen`,
  _ = `Kategorien`,
  _ = `Hardware`,
  _ = `Spielmöglichkeiten`,
  _ = `Angebotsbereiche`,
  _ = `Alle anzeigen`,
  _ = `Weitere`,
  _ = `Menü`,
  _ = `Meine Einstellungen`,
  _ = `Meine Wunschliste`,
  _ = `Meine Abonnements`,
  _ = `Gefolgte Spiele`,
  _ = `Mein Account`,
  _ = `Meine Familie`,
  _ = `Zuletzt angesehen`,
  _ = `Dort fortsetzen, wo Sie zuletzt aufgehört haben`,
  _ = `Für Sie empfohlen`,
  _ = `Von Ihrer Wunschliste`,
  _ = `Zusatzinhalte für Sie`,
  _ = `Für Sie`,
  _ = `Meistbesuchte Inhalte durchsuchen`,
  _ = `Meistbesuchte Inhalte`,
  _ = `Neu und angesagt`,
  _ = `Kostenlos spielbar`,
  _ = `Die besten kostenlos spielbaren Titel`,
  _ = `Topseller`,
  _ = `Neuerscheinungen`,
  _ = `Neue Inhalte auf Steam entdecken`,
  _ = `Veröffentlichungskalender anzeigen`,
  _ = `Rabatte und Events`,
  _ = `Alle Statistiken`,
  _ = `Top-Titel basierend auf Woche, Monat oder Jahr suchen`,
  _ = `Ihre Wunschliste`,
  _ = `%1$s Rabatte`,
  _ = `Sonderevents`,
  _ = `Beliebte Titel`,
  _ = `Sonderangebote`,
  _ = `Empfehlungen`,
  _ = `Liste der Neuerscheinungen`,
  _ = `In aller Munde`,
  _ = `Interaktiver Empfehlungsgeber`,
  _ = `Ihr persönlicher Kalender`,
  _ = `Beliebt bei Freunden`,
  _ = `Steam-Kuratoren`,
  _ = `Zusatzinhalte für Sie`,
  _ = `Ihre Entdeckungsliste`,
  _ = `Lassen Sie Steam eine speziell für Sie kuratierte Liste von empfohlenen Spielen zusammenstellen.`,
  _ = `Spiele in meiner Liste entdecken`,
  _ = `Erkunden Sie personalisierte Empfehlungen unseres Systems für maschinelles Lernen.`,
  _ = `Empfehlungen anzeigen`,
  _ = `Stöbern Sie in einer auf Sie individuell angepassten Liste mit kürzlich veröffentlichten oder bald verfügbaren Spielen.`,
  _ = `In meinem Kalender stöbern`,
  _ = `NEU`,
  _ = `Ihre Top-Genres`,
  _ = `Ihre Top-Kategorien`,
  _ = `Alle Genres und Themen anzeigen`,
  _ = `Erweitern`,
  _ = `Reduzieren`,
  _ = `Alle Tags anzeigen`,
  _ = `Alle Genres und Themen`,
  _ = `Hardware`,
  _ = `VR-Hardware`,
  _ = `Steam Deck`,
  _ = `Steam Controller`,
  _ = `Steam Machine`,
  _ = `Steam Frame`,
  _ = `Valve Index`,
  _ = `Dockingstation`,
  _ = `Steam Hardware`,
  _ = `Spielmöglichkeiten`,
  _ = `Besondere Bereiche`,
  _ = `Steam-Spielevorschau`,
  _ = `Die Steam Awards`,
  _ = `Steam-Rückblick`,
  _ = `Steam Laboratorien`,
  _ = `Zusatzinhalt`,
  _ = `RABATTAKTIONEN`,
  _ = `Zuletzt angesehen`,
  _ = `Beliebte Suchanfragen`,
  _ = `Suchergebnisse`,
  _ = `Ihre Top-Genres`,
  _ = `Durchsuchen nach\xA0…`,
  _ = `Keine Suchergebnisse entsprechen dieser Anfrage.`,
  _ = `Erweiterte Suche`,
  _ = `%1$s Spiele`,
  _ = `Suchen`,
  _ = `Shop-Menü`,
  _ = `Enthält %1$s Spiele`,
  _ = `IN IHRER BIBLIOTHEK`,
  _ = `AUF IHRER WUNSCHLISTE`,
  _ = `IM WARENKORB`,
  _ = `IGNORIERT`,
  _ = `DURCH EINSTELLUNGEN NICHT ANGEZEIGT`,
  _ = `Meine Kategorien:`,
  _ = `Keine Auswahl`,
  _ = `Nach Kategorie filtern`,
  _ = `Kategoriefilter zurücksetzen`,
  _ = `Kategorie hinzufügen`,
  _ = `Kategorie entfernen`,
  _ = `Kategorie für diesen Artikel entfernen`,
  _ = `Wunschliste nach Artikeln dieser Kategorie filtern`,
  _ = `Alle`,
  _ = `Nicht kategorisiert`,
  _ = `Kategorien hinzufügen oder entfernen`,
  _ = `Auf Rabattaktion warten`,
  _ = `Geburtstagswunschliste`,
  _ = `Von Freunden empfohlen`,
  _ = `Kategorien für %1$s verwalten`,
  _ = `Aktuelle Kategorien`,
  _ = `Nach Namen suchen oder eine Kategorie hinzufügen`,
  _ = `Kategorie hinzufügen`,
  _ = `Meine anderen Kategorien`,
  _ = `Empfohlene Kategorien`,
  _ = `Dieser Wunschlistenartikel hat das Limit von %1$s Kategorien erreicht.`,
  _ = `Erweitert\xA0…`,
  _ = `STANDARD`,
  _ = `30-TAGE-TIEF`,
  _ = `Auf dieses Spiel wurde in den vergangenen %2$s Tagen folgender Rabatt gewährt: %1$s.`,
  _ = `Dieses Spiel wird derzeit zum niedrigsten Preis innerhalb der letzten %1$s Tage angeboten.`,
  _ = `AKTUELL`,
  _ = `Rabatt basiert auf dem niedrigsten Preis der letzten 30 Tage`,
  _ = `Ihr persönlicher Kalender`,
  _ = `Eine für Sie personalisierte Liste von neuen oder bald verfügbaren Spielen.`,
  _ = `+%1$s weitere`,
  _ = `Vollständigen persönlichen Kalender anzeigen`,
  _ = `Mehr entdecken`,
  _ = `Für das ausgewählte Datum liegen keine Neuerscheinungen vor, die wir empfehlen können. <1>Schauen Sie sich den Rest Ihres Kalenders an</1>`,
  _ = `NEU`,
  _ = `Heute`,
  _ = `dont translate`,
  _ = {
    language: _,
    review_summary_reviewrate: _,
    review_summary_reviewrate_language_specific: _,
    Discount_ARIA_Label: _,
    Discount_ARIA_Label_SpecialPrice: _,
    Price_Free: _,
    AddToCartButton_InCart: _,
    AddToCartButton_AddToCart: _,
    AddToCartButton_PurchaseAsGift: _,
    PlayGameButton_PlayNow: _,
    AddToLibraryButton: _,
    Button_SignIn: _,
    SignInToAddToLibrary_Tooltip: _,
    Menu_OpenFlyout: _,
    Menu_TopSellers: _,
    Menu_NewReleases: _,
    Menu_OnSale: _,
    Menu_SearchPlaceholder: _,
    Menu_ClearSearchTerm: _,
    Menu_Wishlist: _,
    Menu_Cart: _,
    Menu_VR: _,
    Menu_Popover_TopLinks: _,
    Menu_Popover_StoreHome: _,
    Menu_Popover_GreatonDeck: _,
    Menu_Popover_GreatonFrame: _,
    Menu_Popover_FreeToPlay: _,
    Menu_Popover_SteamCharts: _,
    Menu_Popover_Upcoming: _,
    Menu_Popover_PointsShop: _,
    Menu_Popover_GiftCards: _,
    Menu_Popover_NewsAndUpdates: _,
    Menu_Popover_Preferences: _,
    Menu_Popover_Browse: _,
    Menu_Popover_Top: _,
    Menu_Popover_Recommendations: _,
    Menu_Popover_Categories: _,
    Menu_Popover_Hardware: _,
    Menu_Popover_WaysToPlay: _,
    Menu_Popover_SpecialSections: _,
    Menu_Popover_ViewAll: _,
    Menu_Popover_More: _,
    Menu_Popover_Menu: _,
    Menu_Section_Browse_MyPreferences: _,
    Menu_Section_Browse_MyWishlist: _,
    Menu_Section_Browse_MySubscriptions: _,
    Menu_Section_Browse_MyFollowedGames: _,
    Menu_Section_Browse_MyAccount: _,
    Menu_Section_Browse_MyFamily: _,
    Menu_Section_Browse_RecentlyViewed: _,
    Menu_Section_Browse_PickUpWhereYouLeftOff: _,
    Menu_Section_Browse_Recommended: _,
    Menu_Section_Browse_FromYourWishlist: _,
    Menu_Section_Browse_DLCForYou: _,
    Menu_Section_Browse_ForYou: _,
    Menu_Section_Browse_BrowseTop: _,
    Menu_Section_Browse_Top: _,
    Menu_Section_Browse_PopularNew: _,
    Menu_Section_Browse_FreeToPlay: _,
    Menu_Section_Browse_TopFreeToPlay: _,
    Menu_Section_Browse_TopSellers: _,
    Menu_Section_Browse_NewReleases: _,
    Menu_Section_Browse_NewReleases_Desc: _,
    Menu_Section_Browse_Upcoming_Desc: _,
    Menu_Section_Browse_Discounts: _,
    Menu_Section_Browse_Charts: _,
    Menu_Section_Browse_Charts_Desc: _,
    Menu_Section_Browse_Discounts_YourWishlist: _,
    Menu_Section_Browse_Discounts_YourWishlist_Discounts: _,
    Menu_Section_Browse_Discounts_SpecialEvents: _,
    Menu_Section_Browse_Discounts_PopularTitles: _,
    Menu_Section_Browse_Discounts_SpecialOffers: _,
    Menu_Section_Recommendations: _,
    Menu_Section_Recommendations_NewReleasesQueue: _,
    Menu_Section_Recommendations_CommunityRecommendations: _,
    Menu_Section_Recommendations_InteractiveRecommender: _,
    Menu_Section_Recommendations_PersonalCalendar: _,
    Menu_Section_Recommendations_PopularAmongFriends: _,
    Menu_Section_Recommendations_SteamCurators: _,
    Menu_Section_Recommendations_DLCForYou: _,
    Menu_Section_Recommendations_DiscoveryQueue_Title: _,
    Menu_Section_Recommendations_DiscoveryQueue_Description: _,
    Menu_Section_Recommendations_DiscoveryQueue_ActionButton: _,
    Menu_Section_Recommendations_InteractiveRecommender_Description: _,
    Menu_Section_Recommendations_InteractiveRecommender_ActionButton: _,
    Menu_Section_Recommendations_PersonalCalendar_Description: _,
    Menu_Section_Recommendations_PersonalCalendar_ActionButton: _,
    Menu_Section_Recommendations_New: `NEU`,
    Menu_Section_Categories_YourTopGenres: _,
    Menu_Section_Categories_YourTopCategories: _,
    Menu_Section_Categories_ViewAll: _,
    Menu_Section_Categories_Expand: _,
    Menu_Section_Categories_Collapse: _,
    Menu_Section_Categories_ViewAllTags: _,
    Menu_Section_Categories_GenresAndThemes: _,
    Menu_Section_Hardware: _,
    Menu_Section_Hardware_VRHardware: _,
    Menu_Section_Hardware_SteamDeck: _,
    Menu_Section_Hardware_SteamController: _,
    Menu_Section_Hardware_SteamMachine: _,
    Menu_Section_Hardware_SteamFrame: _,
    Menu_Section_Hardware_ValveIndex: _,
    Menu_Section_Hardware_SteamDeckDock: _,
    Menu_Section_Hardware_Family: _,
    Menu_Section_WaysToPlay: _,
    Menu_Section_SpecialSections: _,
    Menu_Section_SpecialSections_NextFest: _,
    Menu_Section_SpecialSections_SteamAwards: _,
    Menu_Section_SpecialSections_SteamReplay: _,
    Menu_Section_SpecialSections_SteamLabs: _,
    Menu_Section_SpecialSections_DLCForYou: _,
    Menu_Section_SpecialSections_SaleEvents: _,
    Menu_SearchBar_RecentlyViewed: _,
    Menu_SearchBar_PopularSearches: _,
    Menu_SearchBar_SearchResults: _,
    Menu_SearchBar_YourTopGenres: _,
    Menu_SearchBar_BrowseBy: _,
    Menu_SearchBar_NoMatches: _,
    Menu_SearchBar_AdvancedSearch: _,
    Menu_SearchBar_CategoryGameCount: _,
    Menu_Search: _,
    Menu_Label: _,
    Menu_IncludesXGames: _,
    ItemFlag_InLibrary: _,
    ItemFlag_OnWishlist: _,
    ItemFlag_InCart: _,
    ItemFlag_Ignored: _,
    ItemFlag_ExcludedByPreferences: _,
    Wishlist_Controls_Categories_Header: _,
    Wishlist_Categories_None: _,
    Wishlist_Gamepad_Filter_Category: _,
    Wishlist_Gamepad_Filter_Clear_Category: _,
    Wishlist_Gamepad_Add_Category: _,
    Wishlist_Gamepad_Removecategory: _,
    Wishlist_Controls_Categories_Remove_Tooltip: _,
    Wishlist_Controls_Categories_Filter_Tooltip: _,
    Wishlist_Controls_Categories_All: _,
    Wishlist_Controls_Categories_Uncategorized: _,
    Wishlist_Controls_Categories_Manage: _,
    Wishlist_Categories_Suggested_Discount: _,
    Wishlist_Categories_Suggested_Birthday: _,
    Wishlist_Categories_Suggested_Recommended: _,
    Wishlist_Controls_Categories_Manageitem: _,
    Wishlist_Controls_Categories_Header_Current: _,
    Wishlist_Categories_Dialog_Search: _,
    Wishlist_Categories_Dialog_Add: _,
    Wishlist_Controls_Categories_Header_Other: _,
    Wishlist_Controls_Categories_Header_Suggested: _,
    Wishlist_Categories_Max_Per_App_Reached: _,
    Wishlist_Categories_Dialog_Advanced: _,
    Price_History_Normal_Price: _,
    Price_History_Recent_Low_Price: _,
    Price_History_Recent_Low_Price_Ttip: _,
    Price_History_Current_Low_Price_Ttip: _,
    Price_History_Current_Price: _,
    Price_History_Lowest_Previous_30: _,
    PersonalCalendar_Title: _,
    PersonalCalendar_Subtitle: _,
    PersonalCalendar_More: _,
    PersonalCalendar_Full: _,
    PersonalCalendar_Explore: _,
    PersonalCalendar_EmptyDay: _,
    NewBadge: `NEU`,
    Time_Today: _,
    store_ui_dummy: _,
  };
export {
  _ as AddToCartButton_AddToCart,
  _ as AddToCartButton_InCart,
  _ as AddToCartButton_PurchaseAsGift,
  _ as AddToLibraryButton,
  _ as Button_SignIn,
  _ as Discount_ARIA_Label,
  _ as Discount_ARIA_Label_SpecialPrice,
  _ as ItemFlag_ExcludedByPreferences,
  _ as ItemFlag_Ignored,
  _ as ItemFlag_InCart,
  _ as ItemFlag_InLibrary,
  _ as ItemFlag_OnWishlist,
  _ as Menu_Cart,
  _ as Menu_ClearSearchTerm,
  _ as Menu_IncludesXGames,
  _ as Menu_Label,
  _ as Menu_NewReleases,
  _ as Menu_OnSale,
  _ as Menu_OpenFlyout,
  _ as Menu_Popover_Browse,
  _ as Menu_Popover_Categories,
  _ as Menu_Popover_FreeToPlay,
  _ as Menu_Popover_GiftCards,
  _ as Menu_Popover_GreatonDeck,
  _ as Menu_Popover_GreatonFrame,
  _ as Menu_Popover_Hardware,
  _ as Menu_Popover_Menu,
  _ as Menu_Popover_More,
  _ as Menu_Popover_NewsAndUpdates,
  _ as Menu_Popover_PointsShop,
  _ as Menu_Popover_Preferences,
  _ as Menu_Popover_Recommendations,
  _ as Menu_Popover_SpecialSections,
  _ as Menu_Popover_SteamCharts,
  _ as Menu_Popover_StoreHome,
  _ as Menu_Popover_Top,
  _ as Menu_Popover_TopLinks,
  _ as Menu_Popover_Upcoming,
  _ as Menu_Popover_ViewAll,
  _ as Menu_Popover_WaysToPlay,
  _ as Menu_Search,
  _ as Menu_SearchBar_AdvancedSearch,
  _ as Menu_SearchBar_BrowseBy,
  _ as Menu_SearchBar_CategoryGameCount,
  _ as Menu_SearchBar_NoMatches,
  _ as Menu_SearchBar_PopularSearches,
  _ as Menu_SearchBar_RecentlyViewed,
  _ as Menu_SearchBar_SearchResults,
  _ as Menu_SearchBar_YourTopGenres,
  _ as Menu_SearchPlaceholder,
  _ as Menu_Section_Browse_BrowseTop,
  _ as Menu_Section_Browse_Charts,
  _ as Menu_Section_Browse_Charts_Desc,
  _ as Menu_Section_Browse_DLCForYou,
  _ as Menu_Section_Browse_Discounts,
  _ as Menu_Section_Browse_Discounts_PopularTitles,
  _ as Menu_Section_Browse_Discounts_SpecialEvents,
  _ as Menu_Section_Browse_Discounts_SpecialOffers,
  _ as Menu_Section_Browse_Discounts_YourWishlist,
  _ as Menu_Section_Browse_Discounts_YourWishlist_Discounts,
  _ as Menu_Section_Browse_ForYou,
  _ as Menu_Section_Browse_FreeToPlay,
  _ as Menu_Section_Browse_FromYourWishlist,
  _ as Menu_Section_Browse_MyAccount,
  _ as Menu_Section_Browse_MyFamily,
  _ as Menu_Section_Browse_MyFollowedGames,
  _ as Menu_Section_Browse_MyPreferences,
  _ as Menu_Section_Browse_MySubscriptions,
  _ as Menu_Section_Browse_MyWishlist,
  _ as Menu_Section_Browse_NewReleases,
  _ as Menu_Section_Browse_NewReleases_Desc,
  _ as Menu_Section_Browse_PickUpWhereYouLeftOff,
  _ as Menu_Section_Browse_PopularNew,
  _ as Menu_Section_Browse_RecentlyViewed,
  _ as Menu_Section_Browse_Recommended,
  _ as Menu_Section_Browse_Top,
  _ as Menu_Section_Browse_TopFreeToPlay,
  _ as Menu_Section_Browse_TopSellers,
  _ as Menu_Section_Browse_Upcoming_Desc,
  _ as Menu_Section_Categories_Collapse,
  _ as Menu_Section_Categories_Expand,
  _ as Menu_Section_Categories_GenresAndThemes,
  _ as Menu_Section_Categories_ViewAll,
  _ as Menu_Section_Categories_ViewAllTags,
  _ as Menu_Section_Categories_YourTopCategories,
  _ as Menu_Section_Categories_YourTopGenres,
  _ as Menu_Section_Hardware,
  _ as Menu_Section_Hardware_Family,
  _ as Menu_Section_Hardware_SteamController,
  _ as Menu_Section_Hardware_SteamDeck,
  _ as Menu_Section_Hardware_SteamDeckDock,
  _ as Menu_Section_Hardware_SteamFrame,
  _ as Menu_Section_Hardware_SteamMachine,
  _ as Menu_Section_Hardware_VRHardware,
  _ as Menu_Section_Hardware_ValveIndex,
  _ as Menu_Section_Recommendations,
  _ as Menu_Section_Recommendations_CommunityRecommendations,
  _ as Menu_Section_Recommendations_DLCForYou,
  _ as Menu_Section_Recommendations_DiscoveryQueue_ActionButton,
  _ as Menu_Section_Recommendations_DiscoveryQueue_Description,
  _ as Menu_Section_Recommendations_DiscoveryQueue_Title,
  _ as Menu_Section_Recommendations_InteractiveRecommender,
  _ as Menu_Section_Recommendations_InteractiveRecommender_ActionButton,
  _ as Menu_Section_Recommendations_InteractiveRecommender_Description,
  _ as Menu_Section_Recommendations_New,
  _ as Menu_Section_Recommendations_NewReleasesQueue,
  _ as Menu_Section_Recommendations_PersonalCalendar,
  _ as Menu_Section_Recommendations_PersonalCalendar_ActionButton,
  _ as Menu_Section_Recommendations_PersonalCalendar_Description,
  _ as Menu_Section_Recommendations_PopularAmongFriends,
  _ as Menu_Section_Recommendations_SteamCurators,
  _ as Menu_Section_SpecialSections,
  _ as Menu_Section_SpecialSections_DLCForYou,
  _ as Menu_Section_SpecialSections_NextFest,
  _ as Menu_Section_SpecialSections_SaleEvents,
  _ as Menu_Section_SpecialSections_SteamAwards,
  _ as Menu_Section_SpecialSections_SteamLabs,
  _ as Menu_Section_SpecialSections_SteamReplay,
  _ as Menu_Section_WaysToPlay,
  _ as Menu_TopSellers,
  _ as Menu_VR,
  _ as Menu_Wishlist,
  _ as NewBadge,
  _ as PersonalCalendar_EmptyDay,
  _ as PersonalCalendar_Explore,
  _ as PersonalCalendar_Full,
  _ as PersonalCalendar_More,
  _ as PersonalCalendar_Subtitle,
  _ as PersonalCalendar_Title,
  _ as PlayGameButton_PlayNow,
  _ as Price_Free,
  _ as Price_History_Current_Low_Price_Ttip,
  _ as Price_History_Current_Price,
  _ as Price_History_Lowest_Previous_30,
  _ as Price_History_Normal_Price,
  _ as Price_History_Recent_Low_Price,
  _ as Price_History_Recent_Low_Price_Ttip,
  _ as SignInToAddToLibrary_Tooltip,
  _ as Time_Today,
  _ as Wishlist_Categories_Dialog_Add,
  _ as Wishlist_Categories_Dialog_Advanced,
  _ as Wishlist_Categories_Dialog_Search,
  _ as Wishlist_Categories_Max_Per_App_Reached,
  _ as Wishlist_Categories_None,
  _ as Wishlist_Categories_Suggested_Birthday,
  _ as Wishlist_Categories_Suggested_Discount,
  _ as Wishlist_Categories_Suggested_Recommended,
  _ as Wishlist_Controls_Categories_All,
  _ as Wishlist_Controls_Categories_Filter_Tooltip,
  _ as Wishlist_Controls_Categories_Header,
  _ as Wishlist_Controls_Categories_Header_Current,
  _ as Wishlist_Controls_Categories_Header_Other,
  _ as Wishlist_Controls_Categories_Header_Suggested,
  _ as Wishlist_Controls_Categories_Manage,
  _ as Wishlist_Controls_Categories_Manageitem,
  _ as Wishlist_Controls_Categories_Remove_Tooltip,
  _ as Wishlist_Controls_Categories_Uncategorized,
  _ as Wishlist_Gamepad_Add_Category,
  _ as Wishlist_Gamepad_Filter_Category,
  _ as Wishlist_Gamepad_Filter_Clear_Category,
  _ as Wishlist_Gamepad_Removecategory,
  _ as default,
  _ as language,
  _ as review_summary_reviewrate,
  _ as review_summary_reviewrate_language_specific,
  _ as store_ui_dummy,
};
