var _ = `Semua Bundel yang Berisi:`,
  _ = `Urutkan Berdasarkan:`,
  _ = `Populer`,
  _ = `Harga`,
  _ = `Diskon Bundel`,
  _ = `Nama`,
  _ = `Direkomendasikan`,
  _ = `Bundel lengkapmu`,
  _ = `Semua konten di bundel ini ada di perpustakaanmu`,
  _ = `Bundel Lengkapi Set`,
  _ = `Beli produk yang belum ada di perpustakaanmu untuk melengkapi bundel`,
  _ = `Bundel Beli Bersamaan`,
  _ = `Mencakup semua item dalam satu bundel; harus dibeli sebagai satu set lengkap`,
  _ = `© %1$s Valve Corporation. Hak cipta dilindungi Undang-Undang. Semua merek dagang merupakan hak pemilik dari negara AS dan negara lainnya.`,
  _ = `Semua harga sudah termasuk PPN jika berlaku.`,
  _ = `Kebijakan Privasi`,
  _ = `Legal`,
  _ = `Aksesibilitas`,
  _ = `Perjanjian Pelanggan Steam`,
  _ = `Pengembalian Dana`,
  _ = `Cookie`,
  _ = `Tentang Valve`,
  _ = `Solusi Bisnis`,
  _ = `Daur Ulang`,
  _ = `Steamworks`,
  _ = `Source Engine`,
  _ = `Karir`,
  _ = `Kartu Hadiah`,
  _ = `Distribusi Steam`,
  _ = `Bantuan`,
  _ = `Wishlist %1$s`,
  _ = `WISHLIST %1$s`,
  _ = `Keranjang (%1$s)`,
  _ = `Lihat Keranjang`,
  _ = `Wishlist (%1$s)`,
  _ = `Opsi`,
  _ = `Urutan berdasarkan: %1$s`,
  _ = `Buat tautan untuk dibagikan`,
  _ = `Rankingmu`,
  _ = `Ranking Mereka`,
  _ = `Terlaris`,
  _ = `Tanggal Rilis`,
  _ = `Tanggal Ditambahkan`,
  _ = `Skor Ulasan`,
  _ = `Harga`,
  _ = `Nama`,
  _ = `Diskon`,
  _ = `Tautan yang Dapat Dibagikan`,
  _ = `Hapus semua tautan`,
  _ = `Tautan Dihapus!`,
  _ = `Gagal membuat tautan yang dapat dibagikan (eror %1$s)`,
  _ = `Siapa pun yang mendapatkan tautan ini akan dapat melihat wishlist dan filtermu saat ini, terlepas dari pengaturan visibilitas profilmu. Mereka tidak akan dapat mengubah filter.`,
  _ = `Lihat`,
  _ = `Perluas`,
  _ = `Ringkas`,
  _ = `Platform`,
  _ = `OS mana pun`,
  _ = `macOS`,
  _ = `SteamOS + Linux`,
  _ = `Jenis`,
  _ = `Game`,
  _ = `Software`,
  _ = `DLC`,
  _ = `Video`,
  _ = `Harga`,
  _ = `Diskon`,
  _ = `Semua item dalam daftar`,
  _ = `Semua dengan diskon`,
  _ = `%1$s% atau lebih`,
  _ = `Harga Berapa pun`,
  _ = `Di Bawah %1$s`,
  _ = `Gratis`,
  _ = `Yang Dikecualikan`,
  _ = `Item Terkait`,
  _ = `Akses Dini`,
  _ = `Game ini masih dalam tahap Akses Dini`,
  _ = `Pra-rilis`,
  _ = `Hanya VR`,
  _ = `Demo Tersedia`,
  _ = `Filter wishlist ke item dengan demo`,
  _ = `Kompatibilitas Steam Deck`,
  _ = `Terverifikasi`,
  _ = `Dapat Dimainkan`,
  _ = `Tag`,
  _ = `Filter wishlist ke item dengan tag ini`,
  _ = `Tag Pengguna:`,
  _ = `%1$s: %2$s`,
  _ = `Kategori`,
  _ = `Kategori:`,
  _ = `<1>Kategori:</1> <2>%1$s</2>`,
  _ = `Tambahkan kategori`,
  _ = `Pengelolaan Kategori Lanjutan`,
  _ = `PILIH KATEGORI UNTUK DIEDIT`,
  _ = `NAMA KATEGORI`,
  _ = `Namai Ulang`,
  _ = `Kamu sudah memiliki kategori dengan nama tersebut`,
  _ = `Terjadi kesalahan saat mengganti nama kategori ini (kode: %1$s)`,
  _ = `Tidak ada item wishlist yang cocok dengan pencarianmu.`,
  _ = `Semua`,
  _ = `Tidak ada`,
  _ = `Menampilkan %1$s dari %2$s item pertama. Lakukan pencarian untuk mempersempit daftar.`,
  _ = `%1$s item tidak dapat diperbarui`,
  _ = `%1$s item tidak dapat diperbarui`,
  _ = `Tertunda`,
  _ = `Penambahan: %1$s`,
  _ = `Penghapusan: %1$s`,
  _ = `Pulihkan`,
  _ = `Terapkan Perubahan`,
  _ = `TAMBAHKAN/HAPUS KATEGORI`,
  _ = `%1$s ITEM`,
  _ = `%1$s ITEM`,
  _ = `Hasil Pencarian:`,
  _ = `%1$s item dengan nama yang mengandung "%2$s"`,
  _ = `%1$s item dengan nama yang mengandung "%2$s"`,
  _ = `%1$s item dengan kategori %2$s`,
  _ = `%1$s item dengan kategori %2$s`,
  _ = `%1$s item dengan kategori yang mengandung "%2$s"`,
  _ = `%1$s item dengan kategori yang mengandung "%2$s"`,
  _ = `%1$s item dengan tag %2$s`,
  _ = `%1$s item dengan tag %2$s`,
  _ = `%1$s item dengan tag yang mengandung "%2$s"`,
  _ = `%1$s item dengan tag yang mengandung "%2$s"`,
  _ = `Cari berdasarkan nama atau tag`,
  _ = `Cari berdasarkan nama, tag, atau kategori`,
  _ = `Ulasan Umum:`,
  _ = `Ulasan dalam %1$s:`,
  _ = `Tanggal Rilis:`,
  _ = `Ditambahkan pada %1$s`,
  _ = `hapus`,
  _ = `Hapus item ini dari Wishlist`,
  _ = `(item yang tidak tersedia)`,
  _ = `Item ini tidak tersedia di wilayahmu.`,
  _ = `Item ini sudah tidak tersedia lagi.`,
  _ = `Konten dewasa tidak diizinkan di negaramu untuk pengguna di bawah 18 tahun. Valve perlu memverifikasi bahwa kamu berusia 18 tahun atau lebih sebelum kamu dapat mengakses konten dewasa.`,
  _ = `Berdasarkan Undang-Undang Keamanan Daring Britania Raya, Valve harus memverifikasikan bahwa kamu berumur 18, atau lebih, sebelum dapat mengakses konten seksual dewasa.`,
  _ = `Tambahkan kartu kredit`,
  _ = `Wishlist-mu kosong.`,
  _ = `Isi wishlist dengan menelusuri toko dan menggunakan tombol “Tambahkan ke wishlist-mu”.`,
  _ = `Pelajari lebih lanjut tentang Wishlist Steam`,
  _ = `Login untuk melihat wishlist-mu`,
  _ = `Wishlist ini kosong.`,
  _ = `Tidak ada item yang cocok.`,
  _ = `Terdapat %1$s item dalam wishlist ini, tapi tidak ada satu pun yang cocok dengan filter wishlist dan/atau preferensi tokomu.`,
  _ = `Terdapat %1$s item dalam wishlist ini, tapi tidak ada satu pun yang cocok dengan filter wishlist dan/atau <1>preferensi tokomu</1>.`,
  _ = `Urutkan ulang`,
  _ = `Batalkan Menyusun Ulang`,
  _ = `Tempatkan di Sini`,
  _ = `Opsi`,
  _ = `Hapus`,
  _ = `Kunjungi Halaman Toko`,
  _ = `Wishlist - Eror`,
  _ = `Eror`,
  _ = `Eror tidak diketahui`,
  _ = `Profil tidak ditemukan`,
  _ = `Gagal memuat wishlist untuk pengguna.`,
  _ = `Tautan berbagi wishlist ini tidak valid atau sudah kedaluwarsa.`,
  _ = `Pemberitahuan Game di Wishlist`,
  _ = `Akun milik %1$s`,
  _ = `Akun - Eror`,
  _ = `Akun`,
  _ = `Beranda`,
  _ = `Rincian Akun`,
  _ = `Preferensi toko`,
  _ = `Preferensi Bahasa`,
  _ = `Pengaturan Pemberitahuan`,
  _ = `Perangkat`,
  _ = `Keamanan & Perangkat`,
  _ = `Perangkat yang Diotorisasi (Video)`,
  _ = `Perangkat Game Seluler`,
  _ = `Playtest`,
  _ = `Pengelolaan Keluarga`,
  _ = `Data & Penelusuran`,
  _ = `VR`,
  _ = `Kompatibel dengan Deck`,
  _ = `Permainan Lokal (Frame)`,
  _ = `Beranda Toko`,
  _ = `Kategori`,
  _ = `Cari di Steam`,
  _ = `Gagal memuat data akses terbatas.`,
  _ = `Undangan Steam Playtest`,
  _ = `Terima Undangan`,
  _ = `Tolak Undangan`,
  _ = `Kamu telah diundang untuk bergabung ke sebuah Steam Playtest!`,
  _ = `Kamu diundang ke sebuah Peluncuran Terbatas!`,
  _ = `%1$s mengundangmu untuk bergabung dalam Steam Playtest!`,
  _ = `%1$s mengundangmu ke sebuah Peluncuran Terbatas!`,
  _ = `Tidak ada undangan Steam Playtest atau Peluncuran Terbatas yang menunggu respons.`,
  _ = `Selamat datang di Uji Game! %1$s sekarang dapat diinstal ke Perpustakaanmu.`,
  _ = `Selamat datang di Peluncuran Terbatas! %1$s sekarang dapat diinstal ke Perpustakaanmu.`,
  _ = `Selamat datang di Uji Game! %1$s saat ini tidak aktif. Nantikan rencana perilisan mendatang dari pengembang.`,
  _ = `Lihat Perpustakaan`,
  _ = `Apa itu Steam Playtest?`,
  _ = `Steam Playtest digunakan untuk membantu menguji game yang masih dalam pengembangan. Menerima undangan atau memiliki akses yang diberikan oleh pengembang akan menambahkan game ke perpustakaanmu secara otomatis.`,
  _ = `Silakan merujuk ke informasi dari pengembang mengenai sifat masing-masing uji game. Steam Playtest tidak memberikan garansi akses ke game-nya ketika game dirilis.`,
  _ = `Undangan Steam Playtest yang Diabaikan`,
  _ = `Kamu telah menolak undangan Uji Game atau Peluncuran Terbatas untuk game-game berikut. Kamu tidak akan menerima undangan lagi sampai kamu menghapus game-game tersebut dari daftar ini.`,
  _ = `Hapus`,
  _ = `Batal`,
  _ = `Kirim`,
  _ = `Ini adalah undangan terakhirmu yang tersedia untuk Uji Game ini.`,
  _ = `Ini adalah undangan terakhirmu yang tersedia untuk Peluncuran Terbatas ini.`,
  _ = `Mengirim undangan ke:`,
  _ = `Mengundang %1$s...`,
  _ = `%1$s telah diundang! Undangan akan muncul di pemberitahuan %2$s mereka.`,
  _ = `%1$s tidak bisa diundang. Mereka mungkin sudah diundang atau game tidak tersedia di wilayah mereka.`,
  _ = `Riwayat Undangan Terkirim`,
  _ = `Undangan Uji Game dan Peluncuran Terbatas yang kamu kirim ke temanmu`,
  _ = `Mengundang %1$s ke %2$s`,
  _ = `Partisipasi Steam Playtest`,
  _ = `Kamu belum bergabung di Steam Playtest atau Peluncuran Terbatas yang sedang berlangsung.`,
  _ = `Kamu memiliki undangan yang tersedia`,
  _ = `Kamu memiliki %1$s undangan yang tersedia`,
  _ = `Kamu memiliki %1$s undangan yang tersedia`,
  _ = `Kamu dapat memberikan akses Uji Game ini ke temanmu dengan mengundang mereka.`,
  _ = `Jumlah undangan yang tersedia dapat berubah dengan bertambahnya pemain yang bergabung.`,
  _ = `Info lebih lanjut seperti jadwal dan konten dapat ditemukan di %1$s atau %2$s.`,
  _ = `halaman toko`,
  _ = `portal berita`,
  _ = `Uji Game ini sedang tidak aktif.`,
  _ = `Kamu telah menghabiskan undangan untuk teman`,
  _ = `Undang Teman`,
  _ = `Pilih Penerima Undangan`,
  _ = `Cari berdasarkan nama teman...`,
  _ = `Gagal memuat teman.`,
  _ = `Beberapa teman tidak dapat diundang karena kamu belum berteman setidaknya selama 30 hari, mereka sudah mendapatkan akses ke game, atau mereka tidak memenuhi syarat.`,
  _ = `Beberapa teman tidak dapat diundang karena mereka sudah mendapatkan akses ke game atau tidak memenuhi syarat.`,
  _ = `Peluncuran Terbatas`,
  _ = `Kamu dapat memberikan akses Peluncuran Terbatas ini ke temanmu dengan mengundang mereka.`,
  _ = `%1$s memberikan akses ke lebih banyak pengguna selama awal periode Peluncuran Terbatas. Info lebih lanjut dapat ditemukan di %2$s atau %3$s.`,
  _ = `Apa itu Peluncuran Terbatas?`,
  _ = `Peluncuran Terbatas digunakan oleh beberapa game F2P untuk secara perlahan meningkatkan jumlah pemain selama fase peluncuran awal game. Dengan menerima undangan atau mendapatkan akses dari pengembang, game akan ditambahkan ke perpustakaanmu sehingga kamu dapat segera memainkannya.`,
  _ = `Peta Situs Toko Steam`,
  _ = `Beranda Toko`,
  _ = `Akun Saya`,
  _ = `Rincian Akun Saya`,
  _ = `Preferensi Toko Saya`,
  _ = `Pengelolaan Keluarga`,
  _ = `Keamanan & Perangkat`,
  _ = `Preferensi Bahasa`,
  _ = `Cookie & Penelusuran`,
  _ = `Pengaturan Pemberitahuan`,
  _ = `Keranjang`,
  _ = `Keranjang (%1$s)`,
  _ = `Wishlist`,
  _ = `Wishlist (%1$s)`,
  _ = `Game & Software yang Diikuti`,
  _ = `Game & Software yang Diikuti (%1$s)`,
  _ = `Grafik dan Daftar`,
  _ = `Terlaris`,
  _ = `Sering Dimainkan`,
  _ = `Rilisan Terbaru`,
  _ = `Rilisan Mendatang`,
  _ = `F2P`,
  _ = `Grafik Steam`,
  _ = `Sedang Didiskon`,
  _ = `Rekomendasi`,
  _ = `Daftar Temuan`,
  _ = `Daftar Rilisan Terbaru`,
  _ = `Rekomendasi Komunitas`,
  _ = `Pemberi Rekomendasi Interaktif`,
  _ = `Populer di Kalangan Teman`,
  _ = `Kurator Steam`,
  _ = `DLC Untukmu`,
  _ = `Hardware`,
  _ = `Steam Deck`,
  _ = `Dock Steam Deck`,
  _ = `Hardware VR`,
  _ = `Game VR`,
  _ = `Game yang Kompatibel dengan Deck`,
  _ = `Game Ramah Kontroler`,
  _ = `Cara Bermain`,
  _ = `Berita & Pembaruan`,
  _ = `Game yang Baru Diperbarui`,
  _ = `Game-mu yang Baru Diperbarui`,
  _ = `Event Mendatangmu`,
  _ = `Berita yang Difiturkan`,
  _ = `Berita & Pembaruan Resmi Steam`,
  _ = `Promo & Event`,
  _ = `Penawaran Spesial`,
  _ = `Event Diskon`,
  _ = `Steam Replay`,
  _ = `Steam Next Fest`,
  _ = `Penghargaan Steam`,
  _ = `Bagian Spesial`,
  _ = `Toko Poin Steam`,
  _ = `Kartu Hadiah`,
  _ = `Genre`,
  _ = `Tema`,
  _ = `Kamu terlalu banyak mengajukan permintaan baru-baru ini. Mohon tunggu dan coba lagi nanti.`,
  _ = `Diskusi Umum`,
  _ = `Postingan yang Dilaporkan`,
  _ = `Diskusi Workshop`,
  _ = `Pertukaran`,
  _ = `Event & Pengumuman`,
  _ = `Pemberi Rekomendasi Interaktif`,
  _ = `Pemain Sepertimu Menyukainya...`,
  _ = `Telusuri rekomendasi yang dibuat khusus untukmu oleh sistem pembelajaran mesin kami berdasarkan perbandingan riwayat gameplay-mu di Steam dengan jutaan pemain lainnya. Sesuaikan hasil menggunakan penggeser dan filter, lalu simpan pengaturanmu agar Steam mengingat apa yang kamu cari.`,
  _ = `Waktu Bermain yang Relevan`,
  _ = `%1$s game`,
  _ = `%1$s game teratas`,
  _ = `game terkini`,
  _ = `%1$s jam`,
  _ = `Total %1$s jam`,
  _ = `terakhir dimainkan %1$s`,
  _ = `terakhir dimainkan > 10 tahun lalu`,
  _ = `Termasuk`,
  _ = `Kecualikan`,
  _ = `Ukur berdasarkan popularitas`,
  _ = `populer`,
  _ = `niche`,
  _ = `Filter berdasarkan usia`,
  _ = `terlama`,
  _ = `terbaru`,
  _ = `Sepanjang Waktu`,
  _ = `5 tahun`,
  _ = `3 tahun`,
  _ = `2 tahun`,
  _ = `1 tahun`,
  _ = `6 bulan`,
  _ = `Rekomendasi Untukmu`,
  _ = `Dirilis pada %1$s`,
  _ = `Dalam Wishlist`,
  _ = `Masuk Keranjang`,
  _ = `Tambahkan ke Wishlist`,
  _ = `F2P`,
  _ = `Masukkan nama tag`,
  _ = `Tambahkan Filter Tag`,
  _ = `Tambahkan Pengecualian Tag`,
  _ = `Kecualikan Game Yang Sudah Di-wishlist`,
  _ = `Hanya Game Yang Didiskon`,
  _ = `Dirilis Bulan Lalu`,
  _ = `Dirilis dalam 7 Hari Terakhir`,
  _ = `Mendatang`,
  _ = `Kalender Pribadimu`,
  _ = `Daftar berisi %1$s game untukmu yang baru saja dirilis atau yang segera hadir`,
  _ = `Pemilih Tag`,
  _ = `Filter berdasarkan tag...`,
  _ = `Sembunyikan Game yang Dimiliki`,
  _ = `Game yang dirilis dari Akses Dini masih akan ditampilkan`,
  _ = `Sembunyikan Game Akses Dini`,
  _ = `Tampilkan Hanya Game dalam Wishlist`,
  _ = `Jumlah Game`,
  _ = `Kalender Ringkas`,
  _ = `Penimpaan Opsional`,
  _ = `ID Akun`,
  _ = `Lihat semua (%1$s)`,
  _ = `Login untuk melihat rekomendasi yang dipersonalisasikan untukmu.`,
  _ = `Perluas semua`,
  _ = `Eksperimen Steam Lab #16 | <1>Pelajari lebih lanjut dan berikan masukan</1>`,
  _ = `Game dalam Wishlist`,
  _ = `Tampilkan`,
  _ = `Sembunyikan`,
  _ = `Spesifik`,
  _ = `Terlalu banyak game dalam wishlist, dinonaktifkan`,
  _ = `Gagal memuat Kalender, silakan coba lagi`,
  _ = `Daftar Bundel %1$s`,
  _ = `Daftar Bundel`,
  _ = `Semua bundel yang berisi game %1$s.`,
  _ = `Terverifikasi Steam Deck`,
  _ = `%1$s Terverifikasi Steam Deck`,
  _ = `Situs Eror`,
  _ = `UPS, MAAF!`,
  _ = `Terjadi kesalahan saat memproses permintaanmu.`,
  _ = `Jumlah slot harus lebih besar dari 0.`,
  _ = `Domain email sudah digunakan untuk saluran lain.`,
  _ = `Gagal menambahkan saluran.`,
  _ = `Domain email tidak boleh kosong.`,
  _ = `Domain email tidak valid.`,
  _ = `Akun sudah ada di saluran pers.`,
  _ = `Gagal menambahkan akun ke saluran pers.`,
  _ = `Domain email`,
  _ = `Jumlah slot`,
  _ = `Tambahkan`,
  _ = `Tambahkan saluran:`,
  _ = `%1$s, %2$s/%3$s slot digunakan`,
  _ = `Tampilkan riwayat`,
  _ = `Riwayat %1$s`,
  _ = `Key pers diberikan kepada %1$s oleh %2$s`,
  _ = `Key pers ditarik dari %1$s oleh %2$s`,
  _ = `Saluran pers yang dibuat oleh %1$s`,
  _ = `Saluran pers yang diperbarui oleh %1$s`,
  _ = `Domain email diatur ke %1$s`,
  _ = `Jumlah slot diatur ke %1$s`,
  _ = `Saluran pers yang dihapus oleh %1$s`,
  _ = `Saluran pers yang dipulihkan oleh %1$s`,
  _ = `Media pers dimasukkan ke tahap pra-produksi oleh %1$s`,
  _ = `Perubahan dari tahap pra-produksi diterapkan oleh %1$s`,
  _ = `Pengguna %1$s siap untuk ditambahkan oleh %2$s`,
  _ = `Pengguna %1$s siap untuk dihapus oleh %2$s`,
  _ = `bantuan`,
  _ = `Penerima`,
  _ = `Diberikan pada`,
  _ = `Apakah admin grup?`,
  _ = `ID Steam untuk ditambahkan`,
  _ = `OK`,
  _ = `Batal`,
  _ = `Ya`,
  _ = `Tidak`,
  _ = `Semua`,
  _ = `Aktif`,
  _ = `Dihapus`,
  _ = `Kosong`,
  _ = `Tidak ada admin di saluran ini`,
  _ = `Saluran pers:`,
  _ = `Kode teman:`,
  _ = `Berikan key persmu: `,
  _ = `Berikan key persmu?`,
  _ = `Riwayat saluran`,
  _ = `Tambahkan anggota`,
  _ = `Tampilkan riwayat`,
  _ = `Akun`,
  _ = `Trailer tidak ditemukan`,
  _ = `Trailer`,
  _ = `Trailer mini`,
  _ = `Terjadi kesalahan saat menyimpan pengaturan pemberitahuan`,
  _ = `Terjadi kesalahan saat memuat pengaturan pemberitahuan`,
  _ = `Tautan untuk berhenti berlangganan ini tidak valid atau kedaluwarsa. Silakan login dan buka <1>Pengaturan Pemberitahuan</1>`,
  _ = `Umpan akan secara otomatis diaktifkan jika Pemberitahuan Desktop Client atau Aplikasi Seluler diaktifkan.`,
  _ = `Hanya beri tahu %1$s tentang kategori-kategori wishlist ini`,
  _ = `Penaksir FPS`,
  _ = `Pilih Aplikasi dan konfigurasi PC untuk mendapatkan grafik Penaksir FPS, berdasarkan FPS pengguna Steam lain`,
  _ = `CPU`,
  _ = `RAM Sistem`,
  _ = `GPU`,
  _ = `Hardware Tersimpan`,
  _ = `Tidak ada hardware tersimpan.`,
  _ = `Pilih dari daftar hardware untuk melihat perkiraan FPS.`,
  _ = `<Tidak Ada yang Dipilih>`,
  _ = `Tambahkan hardware yang kamu gunakan jika kamu melihat ini dari dalam Steam Client.`,
  _ = `Tambahkan Hardware Tersimpan`,
  _ = `Tambahkan Hardware Tersimpan (tidak ada di client)`,
  _ = `Jika kamu ingin berkontribusi untuk data anonim tentang Pengukur FPS dan menjadikannya menjadi lebih berguna bagi orang lain, kamu dapat mengunjungi preferensimu dengan mengeklik tautan di bawah dan memilih untuk ikut serta di bagian Pengumpulan Data.`,
  _ = `Preferensi`,
  _ = `FPS`,
  _ = `Cari Game`,
  _ = `Pilih CPU`,
  _ = `Pilih GPU`,
  _ = `Jumlah entri game pelatihan yang coock`,
  _ = `Jumlah entri CPU pelatihan yang coock`,
  _ = `Jumlah entri GPU pelatihan yang coock`,
  _ = `Tidak diketahui`,
  _ = `Kirim Kartu Hadiah`,
  _ = ``,
  _ = {
    BundleList_SubTitle: _,
    BundleList_SortBy: _,
    BundleList_SortBy_Popular: _,
    BundleList_SortBy_Price: _,
    BundleList_SortBy_Discount: _,
    BundleList_SortBy_Name: _,
    BundleList_SortBy_Recommend: _,
    BundleList_AllInLibrary: _,
    BundleList_AllInLibrarySubtitle: _,
    BundleList_CompleteTheSet: _,
    BundleList_CompleteTheSetSubtitle: _,
    BundleList_MustPurchaseAsSet: _,
    BundleList_MustPurchaseAsSetSubtitle: _,
    footer_legal_notice: _,
    footer_vat_included: _,
    footer_privacy_policy: _,
    footer_legal: _,
    footer_accessibility: _,
    footer_ssa: _,
    footer_refunds: _,
    footer_cookies: _,
    footer_about_valve: _,
    footer_business_solutions: _,
    footer_recycling: _,
    footer_steamworks: _,
    footer_source_engine: _,
    footer_jobs: _,
    footer_walletcode: _,
    footer_steam_distribution: _,
    footer_nav_help_support: _,
    wishlist_title: _,
    wishlist_header: _,
    cart_count: _,
    cart_view_cart: _,
    wishlist_count: _,
    wishlist_options_button: _,
    wishlist_sortby_button: _,
    wishlist_share_tooltip: _,
    wishlist_controls_sortby_order: _,
    wishlist_controls_sortby_their_order: _,
    wishlist_controls_sortby_topsellers: _,
    wishlist_controls_sortby_releasedate: _,
    wishlist_controls_sortby_dateadded: _,
    wishlist_controls_sortby_reviews: _,
    wishlist_controls_sortby_price: _,
    wishlist_controls_sortby_name: _,
    wishlist_controls_sortby_discount: _,
    wishlist_controls_share_dialog_title: _,
    wishlist_controls_share_revokeall: _,
    wishlist_controls_share_revokeall_success: _,
    wishlist_controls_share_generation_failure: _,
    wishlist_controls_share_description: _,
    wishlist_controls_options_category_view: _,
    wishlist_controls_options_view_expanded: _,
    wishlist_controls_options_view_compact: _,
    wishlist_controls_options_category_platform: _,
    wishlist_controls_options_platform_all: _,
    wishlist_controls_options_platform_mac: _,
    wishlist_controls_options_platform_linux: _,
    wishlist_controls_options_category_type: _,
    wishlist_controls_options_type_game: _,
    wishlist_controls_options_type_application: _,
    wishlist_controls_options_type_dlc: `DLC`,
    wishlist_controls_options_type_video: _,
    wishlist_controls_options_category_price: _,
    wishlist_controls_options_category_discount: _,
    wishlist_controls_options_discount_all: _,
    wishlist_controls_options_discount_any: _,
    wishlist_controls_options_discount_or_more: _,
    wishlist_controls_options_price_any: _,
    wishlist_controls_options_price_max_price: _,
    wishlist_controls_options_price_free: _,
    wishlist_controls_options_category_exclude: _,
    wishlist_controls_options_category_related: _,
    genre_early_access: _,
    wishlist_controls_early_access_tooltip: _,
    category_prerelease: _,
    wishlist_controls_options_exclude_vr: _,
    wishlist_controls_demo_available: _,
    wishlist_controls_demo_available_tooltip: _,
    wishlist_controls_options_category_deck: _,
    wishlist_controls_options_deck_verified: _,
    wishlist_controls_options_deck_playable: _,
    wishlist_controls_options_category_tag: `Tag`,
    wishlist_controls_tag_description: _,
    wishlist_controls_tags_header: _,
    wishlist_controls_filter_tag_label: _,
    wishlist_controls_options_category_category: _,
    wishlist_controls_categories_header_anonymous: _,
    wishlist_controls_categories_multiselect_label: _,
    wishlist_controls_categories_add: _,
    wishlist_categories_advanced_title: _,
    wishlist_categories_advanced_select: _,
    wishlist_categories_advanced_rename_label: _,
    wishlist_categories_advanced_rename_save: _,
    wishlist_categories_advanced_rename_duplicate: _,
    wishlist_categories_advanced_rename_failed: _,
    wishlist_categories_advanced_no_items: _,
    wishlist_categories_advanced_select_all: _,
    wishlist_categories_advanced_select_none: _,
    wishlist_categories_advanced_showing: _,
    wishlist_categories_advanced_failed_items: _,
    wishlist_categories_advanced_failed_items_Plural: _,
    wishlist_categories_advanced_pending: _,
    wishlist_categories_advanced_pending_adds: _,
    wishlist_categories_advanced_pending_removals: _,
    wishlist_categories_advanced_revert: _,
    wishlist_categories_advanced_apply: _,
    wishlist_categories_advanced_addremove_title: _,
    wishlist_displayed_item_count: _,
    wishlist_displayed_item_count_Plural: _,
    wishlist_filter_results: _,
    wishlist_filter_matches_items: _,
    wishlist_filter_matches_items_Plural: _,
    wishlist_filter_matches_category: _,
    wishlist_filter_matches_category_Plural: _,
    wishlist_filter_matches_categories: _,
    wishlist_filter_matches_categories_Plural: _,
    wishlist_filter_matches_tag: _,
    wishlist_filter_matches_tag_Plural: _,
    wishlist_filter_matches_tags: _,
    wishlist_filter_matches_tags_Plural: _,
    wishlist_search: _,
    wishlist_search_all: _,
    wishlist_item_overallreviews: _,
    wishlist_item_languagespecific_reviews: _,
    wishlist_item_releasedate: _,
    wishlist_item_addedon_date: _,
    wishlist_item_remove: _,
    wishlist_item_remove_tooltip: _,
    wishlist_item_unavailable_title: _,
    wishlist_item_unavailable_region: _,
    wishlist_item_unavailable_retired: _,
    mature_content_requires_creditcard: _,
    mature_content_requires_creditcard_gb: _,
    wishlist_item_add_credit_card: _,
    wishlist_your_wishlist_empty: _,
    wishlist_browse_the_store: _,
    wishlist_learn_more_button: _,
    wishlist_sign_in_to_see_your_wishlist: _,
    wishlist_others_wishlist_empty: _,
    wishlist_no_items_matching_filters: _,
    wishlist_x_items_on_wishlist_but_none_match: _,
    wishlist_x_items_on_wishlist_but_none_match_prefs: _,
    wishlist_gamepaddragdrop_reorderaction: _,
    wishlist_gamepaddragdrop_cancelreorder: _,
    wishlist_gamepaddragdrop_commitreorder: _,
    wishlist_gamepad_options: _,
    wishlist_gamepad_options_remove: _,
    wishlist_gamepad_visitstore: _,
    wishlist_errorpage_title: _,
    errorpage_error: _,
    errorpage_unknownerror: _,
    wishlist_error_profilenotfound: _,
    wishlist_error_wishlistunavailable: _,
    wishlist_error_invalidsharetoken: _,
    wishlist_filters_notification: _,
    youraccount_users_account: _,
    youraccount_errorpage_title: _,
    youraccount_account: _,
    m_home: _,
    global_menu_account_details: _,
    global_menu_account_preferences: _,
    global_menu_account_language_preferences: _,
    global_menu_account_notification_settings: _,
    global_menu_account_hardware_used: _,
    global_menu_account_security_devices: _,
    global_menu_account_video_authorized_devices: _,
    global_menu_account_mobile_game_devices: _,
    global_menu_account_gated_access_games: _,
    accountpreferences_familymanagement_header: _,
    CookiePreferences: _,
    global_menu_vr: `VR`,
    global_menu_greatondeck: _,
    global_menu_localplayonframe: _,
    store_tab_foryou_store_home: _,
    browse_categories: _,
    m_search_steam: _,
    playteststatus_error_dataunavailable: _,
    playtestinvites_title: _,
    playtestinvites_accept: _,
    playtestinvites_reject: _,
    playtestinvites_invitedescription_fromapp2: _,
    playtestinvites_invitedescription_fromapp_limitedlaunch: _,
    playtestinvites_invitedescription_fromuser2: _,
    playtestinvites_invitedescription_fromuser_limitedlaunch: _,
    playtestinvites_noinvites: _,
    playtestinvites_welcome: _,
    playtestinvites_welcome_limitedlaunch: _,
    playtestinvites_welcome_notplayable: _,
    playtestinvites_viewlibrary: _,
    playtestinvites_desc_title: _,
    playtestinvites_desc1: _,
    playtestinvites_desc2: _,
    playtestinvites_ignored_title: _,
    playtestinvites_ignored_desc: _,
    playtestinvites_ignored_remove: _,
    playtestinvites_sendinvite_cancel: _,
    playtestinvites_sendinvite_send: _,
    playtestinvites_sendinvite_lastinvite: _,
    playtestinvites_sendinvite_lastinvite_limitedlaunch: _,
    playtestinvites_sendinvite_confirm_desc: _,
    playtestinvites_sendinvite_pending: _,
    playtestinvites_sendinvite_success: _,
    playtestinvites_sendinvite_failure: _,
    playtestinvitehistory_title: _,
    playtestinvitehistory_desc: _,
    playtestinvitehistory_invite_detail: _,
    playteststatus_title: _,
    playteststatus_none: _,
    playteststatus_invites_available: _,
    playteststatus_invite_count: _,
    playteststatus_invite_count_plural: _,
    playteststatus_invite_count_tooltip: _,
    playteststatus_invite_count_tooltip2: _,
    playteststatus_details_moreinfo: _,
    playteststatus_details_moreinfo_storepage: _,
    playteststatus_details_moreinfo_newshub: _,
    playteststatus_details_notplayable: _,
    playteststatus_details_allinvitesused: _,
    playteststatus_invitefriends: _,
    playteststatus_invitefrienddialog_header: _,
    playteststatus_invitefrienddialog_search_placeholder: _,
    playteststatus_invitefrienddialog_loadingerror: _,
    playteststatus_invitefrienddialog_ineligiblefriends: _,
    playteststatus_invitefrienddialog_ineligiblefriends_purchaser: _,
    gatedaccess_limitedlaunch_badge: _,
    gatedaccess_limitedlaunch_invite_count_tooltip: _,
    gatedaccess_limitedlaunch_details_moreinfo: _,
    gatedaccess_limitedlaunch_desc_title: _,
    gatedaccess_limitedlaunch_desc: _,
    sitemap_title: _,
    sitemap_home: _,
    sitemap_section_account: _,
    sitemap_section_account_account_details: _,
    sitemap_section_account_store_preferences: _,
    sitemap_section_account_family_management: _,
    sitemap_section_account_security_and_devices: _,
    sitemap_section_account_language_preferences: _,
    sitemap_section_account_cookes_and_browsing: _,
    sitemap_section_account_notification_settings: _,
    sitemap_section_account_cart: _,
    sitemap_section_account_cart_with_count: _,
    sitemap_section_account_wishlist: _,
    sitemap_section_account_wishlist_with_count: _,
    sitemap_section_account_followed_games: _,
    sitemap_section_account_followed_games_with_count: _,
    sitemap_section_chartsandlists: _,
    sitemap_section_chartsandlists_top_sellers: _,
    sitemap_section_chartsandlists_most_played: _,
    sitemap_section_chartsandlists_new_releases: _,
    sitemap_section_chartsandlists_upcoming_releases: _,
    sitemap_section_chartsandlists_free_to_play: `F2P`,
    sitemap_section_chartsandlists_steam_charts: _,
    sitemap_section_chartsandlists_on_sale_now: _,
    sitemap_section_recommendations: _,
    sitemap_section_recommendations_discovery_queue: _,
    sitemap_section_recommendations_new_releases_queue: _,
    sitemap_section_recommendations_community_recommendations: _,
    sitemap_section_recommendations_interactive_recommender: _,
    sitemap_section_recommendations_popular_among_friends: _,
    sitemap_section_recommendations_steam_curators: _,
    sitemap_section_recommendations_dlc_for_you: _,
    sitemap_section_hardware: _,
    sitemap_section_hardware_steam_deck: _,
    sitemap_section_hardware_steam_deck_dock: _,
    sitemap_section_hardware_vr_hardware: _,
    sitemap_section_hardware_vr_games: _,
    sitemap_section_hardware_great_on_deck: _,
    sitemap_section_hardware_controller_friendly: _,
    sitemap_section_waystoplay: _,
    sitemap_section_newsupdates: _,
    sitemap_section_newsupdates_recently_updated: _,
    sitemap_section_newsupdates_your_recently_updated: _,
    sitemap_section_newsupdates_your_upcoming_events: _,
    sitemap_section_newsupdates_featured_news: _,
    sitemap_section_newsupdates_steam_official_news: _,
    sitemap_section_promosandevents: _,
    sitemap_section_promosandevents_special_offers: _,
    sitemap_section_promosandevents_sale_events: _,
    sitemap_section_promosandevents_steam_replay: _,
    sitemap_section_promosandevents_steam_next_fest: _,
    sitemap_section_promosandevents_steam_awards: _,
    sitemap_section_specialsections: _,
    sitemap_pointsshop: _,
    sitemap_giftcards: _,
    sitemap_genres: _,
    sitemap_themes: _,
    Error_RateLimited: _,
    Discussions_ForumName_General: _,
    Discussions_ForumName_ReportedPosts: _,
    Discussions_ForumName_Workshop: _,
    Discussions_ForumName_Trading: _,
    Discussions_ForumName_Events: _,
    ir_name: _,
    ir_header: _,
    ir_body: _,
    ir_playtime_header: _,
    ir_playtime_games: _,
    ir_playtime_topgames: _,
    ir_playtime_recentgames: _,
    ir_playtime_hours: _,
    ir_playtime_hourstotal: _,
    ir_playtime_lastplayed: _,
    ir_playtime_lastplayedmax: _,
    ir_playtime_unignore: _,
    ir_playtime_ignore: _,
    ir_popularity_title: _,
    ir_popularity_popular: _,
    ir_popularity_niche: _,
    ir_recency_title: _,
    ir_recency_older: _,
    ir_recency_newer: _,
    ir_filter_age_all: _,
    ir_filter_age_60: _,
    ir_filter_age_36: _,
    ir_filter_age_24: _,
    ir_filter_age_12: _,
    ir_filter_age_6: _,
    ir_recommendations_header: _,
    ir_release_date: _,
    ir_on_wishlist: _,
    ir_add_to_cart: _,
    ir_add_to_wishlist: _,
    ir_free_to_play: `F2P`,
    ir_tag_placeholder: _,
    ir_tag_filter: _,
    ir_tag_exclude: _,
    ir_no_wishlisted: _,
    ir_discounted_only: _,
    PersonalCalendar_LastMonthGames: _,
    PersonalCalendar_LastWeekGames: _,
    PersonalCalendar_Upcoming: _,
    PersonalCalendar_Title: _,
    PersonalCalendar_Description: _,
    PersonalCalendar_TagSelector: _,
    PersonalCalendar_TagSelector_Placeholder: _,
    PersonalCalendar_HideOwned: _,
    PersonalCalendar_HideEATooltip: _,
    PersonalCalendar_HideEarlyAccess: _,
    PersonalCalendar_ShowOnlyWishlisted: _,
    PersonalCalendar_ResultCountSelector: _,
    PersonalCalendar_CompactMode: _,
    PersonalCalendar_AccountPlaceholder: _,
    PersonalCalendar_Account: _,
    PersonalCalendar_ShowMore: _,
    PersonalCalendar_LoginPrompt: _,
    PersonalCalendar_ShowAll: _,
    PersonalCalendar_SteamLabs: _,
    PersonalCalendar_Wishlisted: _,
    PersonalCalendar_WishlistShow: _,
    PersonalCalendar_WishlistHide: _,
    PersonalCalendar_WishlistOnly: _,
    PersonalCalendar_IgnoringWishlists: _,
    PersonalCalendar_Error_Backend: _,
    BundleList_Title: _,
    BundleList_Title_Fallback: _,
    BundleList_Page: _,
    Verification_DeckOnly: _,
    Verification_DeckOnly_Desc: _,
    FatalErrorPage_Title: _,
    FatalErrorPage_Header: _,
    FatalErrorPage_Message: _,
    pressoutlets_error_slots_gt_zero: _,
    pressoutlets_error_domain_used: _,
    pressoutlets_error_adding_outlet: _,
    pressoutlets_error_domain_empty: _,
    pressoutlets_error_invalid_domain: _,
    pressoutlets_error_already_owned: _,
    pressoutlets_error_generic_add_error: _,
    pressoutlets_email_domain_label: _,
    pressoutlets_slots_label: _,
    pressoutlets_button_add: _,
    pressoutlets_label_add_outlet: _,
    pressoutlets_outlet_header: _,
    pressoutlets_show_history: _,
    pressoutlets_history_title: _,
    pressoutlets_action_granted: _,
    pressoutlets_action_removed: _,
    pressoutlets_action_created: _,
    pressoutlets_action_updated: _,
    pressoutlets_action_updated_domain_changed: _,
    pressoutlets_action_updated_slots_changed: _,
    pressoutlets_action_deleted: _,
    pressoutlets_action_undeleted: _,
    pressoutlets_action_enterstaging: _,
    pressoutlets_action_exitstaging: _,
    pressoutlets_action_stagedadd: _,
    pressoutlets_action_stageddelete: _,
    pressoutlets_action_by_support: _,
    pressoutlets_header_grantee: _,
    pressoutlets_header_granted_at: _,
    pressoutlets_header_is_group_admin: _,
    pressoutlets_steamid_to_add: _,
    pressoutlets_button_ok: `OK`,
    pressoutlets_button_cancel: _,
    pressoutlets_is_group_admin: `Ya`,
    pressoutlets_is_not_group_admin: _,
    pressoutlets_filter_all: _,
    pressoutlets_filter_active: _,
    pressoutlets_filter_deleted: _,
    pressoutlets_filter_empty: _,
    pressoutlets_filter_noadmins: _,
    pressoutlets_outlet_header_prefix: _,
    pressoutlets_friendcode: _,
    pressoutlets_resign_your_key: _,
    pressoutlets_resign_your_key_title: _,
    pressoutlets_history_header: _,
    pressoutlets_button_add_member: _,
    pressoutlets_button_show_history: _,
    pressoutlets_header_account: _,
    trailerassets_invalidfile: _,
    trailerassets_trailer: _,
    trailerassets_microtrailer: _,
    account_notification_settings_error_saving: _,
    account_notification_settings_error_loading: _,
    account_notification_settings_error_invalidoptouttoken: _,
    account_notification_settings_feed_disabled: _,
    account_notification_settings_wishlist_categories_persona: _,
    framerate_title: _,
    framerate_subheader: _,
    framerate_cpu: `CPU`,
    framerate_ram: _,
    framerate_gpu: `GPU`,
    framerate_saved_hardware: _,
    framerate_saved_hardware_none: _,
    framerate_saved_hardware_select: _,
    framerate_saved_hardware_option_none: _,
    framerate_saved_add: _,
    framerate_saved_add_btn: _,
    framerate_saved_add_not_in_client_btn: _,
    framerate_opt_in_data_collection_desc: _,
    framerate_opt_in_link: _,
    framerate_fps: `FPS`,
    framerate_game_name: _,
    framerate_select_cpu: _,
    framerate_select_gpu: _,
    framerate_training_game: _,
    framerate_training_cpu: _,
    framerate_training_gpu: _,
    generic_unknown: _,
    giftcards_banner_text: _,
    empty_no_trailing_comma: ``,
  };
export {
  _ as BundleList_AllInLibrary,
  _ as BundleList_AllInLibrarySubtitle,
  _ as BundleList_CompleteTheSet,
  _ as BundleList_CompleteTheSetSubtitle,
  _ as BundleList_MustPurchaseAsSet,
  _ as BundleList_MustPurchaseAsSetSubtitle,
  _ as BundleList_Page,
  _ as BundleList_SortBy,
  _ as BundleList_SortBy_Discount,
  _ as BundleList_SortBy_Name,
  _ as BundleList_SortBy_Popular,
  _ as BundleList_SortBy_Price,
  _ as BundleList_SortBy_Recommend,
  _ as BundleList_SubTitle,
  _ as BundleList_Title,
  _ as BundleList_Title_Fallback,
  _ as CookiePreferences,
  _ as Discussions_ForumName_Events,
  _ as Discussions_ForumName_General,
  _ as Discussions_ForumName_ReportedPosts,
  _ as Discussions_ForumName_Trading,
  _ as Discussions_ForumName_Workshop,
  _ as Error_RateLimited,
  _ as FatalErrorPage_Header,
  _ as FatalErrorPage_Message,
  _ as FatalErrorPage_Title,
  _ as PersonalCalendar_Account,
  _ as PersonalCalendar_AccountPlaceholder,
  _ as PersonalCalendar_CompactMode,
  _ as PersonalCalendar_Description,
  _ as PersonalCalendar_Error_Backend,
  _ as PersonalCalendar_HideEATooltip,
  _ as PersonalCalendar_HideEarlyAccess,
  _ as PersonalCalendar_HideOwned,
  _ as PersonalCalendar_IgnoringWishlists,
  _ as PersonalCalendar_LastMonthGames,
  _ as PersonalCalendar_LastWeekGames,
  _ as PersonalCalendar_LoginPrompt,
  _ as PersonalCalendar_ResultCountSelector,
  _ as PersonalCalendar_ShowAll,
  _ as PersonalCalendar_ShowMore,
  _ as PersonalCalendar_ShowOnlyWishlisted,
  _ as PersonalCalendar_SteamLabs,
  _ as PersonalCalendar_TagSelector,
  _ as PersonalCalendar_TagSelector_Placeholder,
  _ as PersonalCalendar_Title,
  _ as PersonalCalendar_Upcoming,
  _ as PersonalCalendar_WishlistHide,
  _ as PersonalCalendar_WishlistOnly,
  _ as PersonalCalendar_WishlistShow,
  _ as PersonalCalendar_Wishlisted,
  _ as Verification_DeckOnly,
  _ as Verification_DeckOnly_Desc,
  _ as account_notification_settings_error_invalidoptouttoken,
  _ as account_notification_settings_error_loading,
  _ as account_notification_settings_error_saving,
  _ as account_notification_settings_feed_disabled,
  _ as account_notification_settings_wishlist_categories_persona,
  _ as accountpreferences_familymanagement_header,
  _ as browse_categories,
  _ as cart_count,
  _ as cart_view_cart,
  _ as category_prerelease,
  _ as default,
  _ as empty_no_trailing_comma,
  _ as errorpage_error,
  _ as errorpage_unknownerror,
  _ as footer_about_valve,
  _ as footer_accessibility,
  _ as footer_business_solutions,
  _ as footer_cookies,
  _ as footer_jobs,
  _ as footer_legal,
  _ as footer_legal_notice,
  _ as footer_nav_help_support,
  _ as footer_privacy_policy,
  _ as footer_recycling,
  _ as footer_refunds,
  _ as footer_source_engine,
  _ as footer_ssa,
  _ as footer_steam_distribution,
  _ as footer_steamworks,
  _ as footer_vat_included,
  _ as footer_walletcode,
  _ as framerate_cpu,
  _ as framerate_fps,
  _ as framerate_game_name,
  _ as framerate_gpu,
  _ as framerate_opt_in_data_collection_desc,
  _ as framerate_opt_in_link,
  _ as framerate_ram,
  _ as framerate_saved_add,
  _ as framerate_saved_add_btn,
  _ as framerate_saved_add_not_in_client_btn,
  _ as framerate_saved_hardware,
  _ as framerate_saved_hardware_none,
  _ as framerate_saved_hardware_option_none,
  _ as framerate_saved_hardware_select,
  _ as framerate_select_cpu,
  _ as framerate_select_gpu,
  _ as framerate_subheader,
  _ as framerate_title,
  _ as framerate_training_cpu,
  _ as framerate_training_game,
  _ as framerate_training_gpu,
  _ as gatedaccess_limitedlaunch_badge,
  _ as gatedaccess_limitedlaunch_desc,
  _ as gatedaccess_limitedlaunch_desc_title,
  _ as gatedaccess_limitedlaunch_details_moreinfo,
  _ as gatedaccess_limitedlaunch_invite_count_tooltip,
  _ as generic_unknown,
  _ as genre_early_access,
  _ as giftcards_banner_text,
  _ as global_menu_account_details,
  _ as global_menu_account_gated_access_games,
  _ as global_menu_account_hardware_used,
  _ as global_menu_account_language_preferences,
  _ as global_menu_account_mobile_game_devices,
  _ as global_menu_account_notification_settings,
  _ as global_menu_account_preferences,
  _ as global_menu_account_security_devices,
  _ as global_menu_account_video_authorized_devices,
  _ as global_menu_greatondeck,
  _ as global_menu_localplayonframe,
  _ as global_menu_vr,
  _ as ir_add_to_cart,
  _ as ir_add_to_wishlist,
  _ as ir_body,
  _ as ir_discounted_only,
  _ as ir_filter_age_12,
  _ as ir_filter_age_24,
  _ as ir_filter_age_36,
  _ as ir_filter_age_6,
  _ as ir_filter_age_60,
  _ as ir_filter_age_all,
  _ as ir_free_to_play,
  _ as ir_header,
  _ as ir_name,
  _ as ir_no_wishlisted,
  _ as ir_on_wishlist,
  _ as ir_playtime_games,
  _ as ir_playtime_header,
  _ as ir_playtime_hours,
  _ as ir_playtime_hourstotal,
  _ as ir_playtime_ignore,
  _ as ir_playtime_lastplayed,
  _ as ir_playtime_lastplayedmax,
  _ as ir_playtime_recentgames,
  _ as ir_playtime_topgames,
  _ as ir_playtime_unignore,
  _ as ir_popularity_niche,
  _ as ir_popularity_popular,
  _ as ir_popularity_title,
  _ as ir_recency_newer,
  _ as ir_recency_older,
  _ as ir_recency_title,
  _ as ir_recommendations_header,
  _ as ir_release_date,
  _ as ir_tag_exclude,
  _ as ir_tag_filter,
  _ as ir_tag_placeholder,
  _ as m_home,
  _ as m_search_steam,
  _ as mature_content_requires_creditcard,
  _ as mature_content_requires_creditcard_gb,
  _ as playtestinvitehistory_desc,
  _ as playtestinvitehistory_invite_detail,
  _ as playtestinvitehistory_title,
  _ as playtestinvites_accept,
  _ as playtestinvites_desc1,
  _ as playtestinvites_desc2,
  _ as playtestinvites_desc_title,
  _ as playtestinvites_ignored_desc,
  _ as playtestinvites_ignored_remove,
  _ as playtestinvites_ignored_title,
  _ as playtestinvites_invitedescription_fromapp2,
  _ as playtestinvites_invitedescription_fromapp_limitedlaunch,
  _ as playtestinvites_invitedescription_fromuser2,
  _ as playtestinvites_invitedescription_fromuser_limitedlaunch,
  _ as playtestinvites_noinvites,
  _ as playtestinvites_reject,
  _ as playtestinvites_sendinvite_cancel,
  _ as playtestinvites_sendinvite_confirm_desc,
  _ as playtestinvites_sendinvite_failure,
  _ as playtestinvites_sendinvite_lastinvite,
  _ as playtestinvites_sendinvite_lastinvite_limitedlaunch,
  _ as playtestinvites_sendinvite_pending,
  _ as playtestinvites_sendinvite_send,
  _ as playtestinvites_sendinvite_success,
  _ as playtestinvites_title,
  _ as playtestinvites_viewlibrary,
  _ as playtestinvites_welcome,
  _ as playtestinvites_welcome_limitedlaunch,
  _ as playtestinvites_welcome_notplayable,
  _ as playteststatus_details_allinvitesused,
  _ as playteststatus_details_moreinfo,
  _ as playteststatus_details_moreinfo_newshub,
  _ as playteststatus_details_moreinfo_storepage,
  _ as playteststatus_details_notplayable,
  _ as playteststatus_error_dataunavailable,
  _ as playteststatus_invite_count,
  _ as playteststatus_invite_count_plural,
  _ as playteststatus_invite_count_tooltip,
  _ as playteststatus_invite_count_tooltip2,
  _ as playteststatus_invitefrienddialog_header,
  _ as playteststatus_invitefrienddialog_ineligiblefriends,
  _ as playteststatus_invitefrienddialog_ineligiblefriends_purchaser,
  _ as playteststatus_invitefrienddialog_loadingerror,
  _ as playteststatus_invitefrienddialog_search_placeholder,
  _ as playteststatus_invitefriends,
  _ as playteststatus_invites_available,
  _ as playteststatus_none,
  _ as playteststatus_title,
  _ as pressoutlets_action_by_support,
  _ as pressoutlets_action_created,
  _ as pressoutlets_action_deleted,
  _ as pressoutlets_action_enterstaging,
  _ as pressoutlets_action_exitstaging,
  _ as pressoutlets_action_granted,
  _ as pressoutlets_action_removed,
  _ as pressoutlets_action_stagedadd,
  _ as pressoutlets_action_stageddelete,
  _ as pressoutlets_action_undeleted,
  _ as pressoutlets_action_updated,
  _ as pressoutlets_action_updated_domain_changed,
  _ as pressoutlets_action_updated_slots_changed,
  _ as pressoutlets_button_add,
  _ as pressoutlets_button_add_member,
  _ as pressoutlets_button_cancel,
  _ as pressoutlets_button_ok,
  _ as pressoutlets_button_show_history,
  _ as pressoutlets_email_domain_label,
  _ as pressoutlets_error_adding_outlet,
  _ as pressoutlets_error_already_owned,
  _ as pressoutlets_error_domain_empty,
  _ as pressoutlets_error_domain_used,
  _ as pressoutlets_error_generic_add_error,
  _ as pressoutlets_error_invalid_domain,
  _ as pressoutlets_error_slots_gt_zero,
  _ as pressoutlets_filter_active,
  _ as pressoutlets_filter_all,
  _ as pressoutlets_filter_deleted,
  _ as pressoutlets_filter_empty,
  _ as pressoutlets_filter_noadmins,
  _ as pressoutlets_friendcode,
  _ as pressoutlets_header_account,
  _ as pressoutlets_header_granted_at,
  _ as pressoutlets_header_grantee,
  _ as pressoutlets_header_is_group_admin,
  _ as pressoutlets_history_header,
  _ as pressoutlets_history_title,
  _ as pressoutlets_is_group_admin,
  _ as pressoutlets_is_not_group_admin,
  _ as pressoutlets_label_add_outlet,
  _ as pressoutlets_outlet_header,
  _ as pressoutlets_outlet_header_prefix,
  _ as pressoutlets_resign_your_key,
  _ as pressoutlets_resign_your_key_title,
  _ as pressoutlets_show_history,
  _ as pressoutlets_slots_label,
  _ as pressoutlets_steamid_to_add,
  _ as sitemap_genres,
  _ as sitemap_giftcards,
  _ as sitemap_home,
  _ as sitemap_pointsshop,
  _ as sitemap_section_account,
  _ as sitemap_section_account_account_details,
  _ as sitemap_section_account_cart,
  _ as sitemap_section_account_cart_with_count,
  _ as sitemap_section_account_cookes_and_browsing,
  _ as sitemap_section_account_family_management,
  _ as sitemap_section_account_followed_games,
  _ as sitemap_section_account_followed_games_with_count,
  _ as sitemap_section_account_language_preferences,
  _ as sitemap_section_account_notification_settings,
  _ as sitemap_section_account_security_and_devices,
  _ as sitemap_section_account_store_preferences,
  _ as sitemap_section_account_wishlist,
  _ as sitemap_section_account_wishlist_with_count,
  _ as sitemap_section_chartsandlists,
  _ as sitemap_section_chartsandlists_free_to_play,
  _ as sitemap_section_chartsandlists_most_played,
  _ as sitemap_section_chartsandlists_new_releases,
  _ as sitemap_section_chartsandlists_on_sale_now,
  _ as sitemap_section_chartsandlists_steam_charts,
  _ as sitemap_section_chartsandlists_top_sellers,
  _ as sitemap_section_chartsandlists_upcoming_releases,
  _ as sitemap_section_hardware,
  _ as sitemap_section_hardware_controller_friendly,
  _ as sitemap_section_hardware_great_on_deck,
  _ as sitemap_section_hardware_steam_deck,
  _ as sitemap_section_hardware_steam_deck_dock,
  _ as sitemap_section_hardware_vr_games,
  _ as sitemap_section_hardware_vr_hardware,
  _ as sitemap_section_newsupdates,
  _ as sitemap_section_newsupdates_featured_news,
  _ as sitemap_section_newsupdates_recently_updated,
  _ as sitemap_section_newsupdates_steam_official_news,
  _ as sitemap_section_newsupdates_your_recently_updated,
  _ as sitemap_section_newsupdates_your_upcoming_events,
  _ as sitemap_section_promosandevents,
  _ as sitemap_section_promosandevents_sale_events,
  _ as sitemap_section_promosandevents_special_offers,
  _ as sitemap_section_promosandevents_steam_awards,
  _ as sitemap_section_promosandevents_steam_next_fest,
  _ as sitemap_section_promosandevents_steam_replay,
  _ as sitemap_section_recommendations,
  _ as sitemap_section_recommendations_community_recommendations,
  _ as sitemap_section_recommendations_discovery_queue,
  _ as sitemap_section_recommendations_dlc_for_you,
  _ as sitemap_section_recommendations_interactive_recommender,
  _ as sitemap_section_recommendations_new_releases_queue,
  _ as sitemap_section_recommendations_popular_among_friends,
  _ as sitemap_section_recommendations_steam_curators,
  _ as sitemap_section_specialsections,
  _ as sitemap_section_waystoplay,
  _ as sitemap_themes,
  _ as sitemap_title,
  _ as store_tab_foryou_store_home,
  _ as trailerassets_invalidfile,
  _ as trailerassets_microtrailer,
  _ as trailerassets_trailer,
  _ as wishlist_browse_the_store,
  _ as wishlist_categories_advanced_addremove_title,
  _ as wishlist_categories_advanced_apply,
  _ as wishlist_categories_advanced_failed_items,
  _ as wishlist_categories_advanced_failed_items_Plural,
  _ as wishlist_categories_advanced_no_items,
  _ as wishlist_categories_advanced_pending,
  _ as wishlist_categories_advanced_pending_adds,
  _ as wishlist_categories_advanced_pending_removals,
  _ as wishlist_categories_advanced_rename_duplicate,
  _ as wishlist_categories_advanced_rename_failed,
  _ as wishlist_categories_advanced_rename_label,
  _ as wishlist_categories_advanced_rename_save,
  _ as wishlist_categories_advanced_revert,
  _ as wishlist_categories_advanced_select,
  _ as wishlist_categories_advanced_select_all,
  _ as wishlist_categories_advanced_select_none,
  _ as wishlist_categories_advanced_showing,
  _ as wishlist_categories_advanced_title,
  _ as wishlist_controls_categories_add,
  _ as wishlist_controls_categories_header_anonymous,
  _ as wishlist_controls_categories_multiselect_label,
  _ as wishlist_controls_demo_available,
  _ as wishlist_controls_demo_available_tooltip,
  _ as wishlist_controls_early_access_tooltip,
  _ as wishlist_controls_filter_tag_label,
  _ as wishlist_controls_options_category_category,
  _ as wishlist_controls_options_category_deck,
  _ as wishlist_controls_options_category_discount,
  _ as wishlist_controls_options_category_exclude,
  _ as wishlist_controls_options_category_platform,
  _ as wishlist_controls_options_category_price,
  _ as wishlist_controls_options_category_related,
  _ as wishlist_controls_options_category_tag,
  _ as wishlist_controls_options_category_type,
  _ as wishlist_controls_options_category_view,
  _ as wishlist_controls_options_deck_playable,
  _ as wishlist_controls_options_deck_verified,
  _ as wishlist_controls_options_discount_all,
  _ as wishlist_controls_options_discount_any,
  _ as wishlist_controls_options_discount_or_more,
  _ as wishlist_controls_options_exclude_vr,
  _ as wishlist_controls_options_platform_all,
  _ as wishlist_controls_options_platform_linux,
  _ as wishlist_controls_options_platform_mac,
  _ as wishlist_controls_options_price_any,
  _ as wishlist_controls_options_price_free,
  _ as wishlist_controls_options_price_max_price,
  _ as wishlist_controls_options_type_application,
  _ as wishlist_controls_options_type_dlc,
  _ as wishlist_controls_options_type_game,
  _ as wishlist_controls_options_type_video,
  _ as wishlist_controls_options_view_compact,
  _ as wishlist_controls_options_view_expanded,
  _ as wishlist_controls_share_description,
  _ as wishlist_controls_share_dialog_title,
  _ as wishlist_controls_share_generation_failure,
  _ as wishlist_controls_share_revokeall,
  _ as wishlist_controls_share_revokeall_success,
  _ as wishlist_controls_sortby_dateadded,
  _ as wishlist_controls_sortby_discount,
  _ as wishlist_controls_sortby_name,
  _ as wishlist_controls_sortby_order,
  _ as wishlist_controls_sortby_price,
  _ as wishlist_controls_sortby_releasedate,
  _ as wishlist_controls_sortby_reviews,
  _ as wishlist_controls_sortby_their_order,
  _ as wishlist_controls_sortby_topsellers,
  _ as wishlist_controls_tag_description,
  _ as wishlist_controls_tags_header,
  _ as wishlist_count,
  _ as wishlist_displayed_item_count,
  _ as wishlist_displayed_item_count_Plural,
  _ as wishlist_error_invalidsharetoken,
  _ as wishlist_error_profilenotfound,
  _ as wishlist_error_wishlistunavailable,
  _ as wishlist_errorpage_title,
  _ as wishlist_filter_matches_categories,
  _ as wishlist_filter_matches_categories_Plural,
  _ as wishlist_filter_matches_category,
  _ as wishlist_filter_matches_category_Plural,
  _ as wishlist_filter_matches_items,
  _ as wishlist_filter_matches_items_Plural,
  _ as wishlist_filter_matches_tag,
  _ as wishlist_filter_matches_tag_Plural,
  _ as wishlist_filter_matches_tags,
  _ as wishlist_filter_matches_tags_Plural,
  _ as wishlist_filter_results,
  _ as wishlist_filters_notification,
  _ as wishlist_gamepad_options,
  _ as wishlist_gamepad_options_remove,
  _ as wishlist_gamepad_visitstore,
  _ as wishlist_gamepaddragdrop_cancelreorder,
  _ as wishlist_gamepaddragdrop_commitreorder,
  _ as wishlist_gamepaddragdrop_reorderaction,
  _ as wishlist_header,
  _ as wishlist_item_add_credit_card,
  _ as wishlist_item_addedon_date,
  _ as wishlist_item_languagespecific_reviews,
  _ as wishlist_item_overallreviews,
  _ as wishlist_item_releasedate,
  _ as wishlist_item_remove,
  _ as wishlist_item_remove_tooltip,
  _ as wishlist_item_unavailable_region,
  _ as wishlist_item_unavailable_retired,
  _ as wishlist_item_unavailable_title,
  _ as wishlist_learn_more_button,
  _ as wishlist_no_items_matching_filters,
  _ as wishlist_options_button,
  _ as wishlist_others_wishlist_empty,
  _ as wishlist_search,
  _ as wishlist_search_all,
  _ as wishlist_share_tooltip,
  _ as wishlist_sign_in_to_see_your_wishlist,
  _ as wishlist_sortby_button,
  _ as wishlist_title,
  _ as wishlist_x_items_on_wishlist_but_none_match,
  _ as wishlist_x_items_on_wishlist_but_none_match_prefs,
  _ as wishlist_your_wishlist_empty,
  _ as youraccount_account,
  _ as youraccount_errorpage_title,
  _ as youraccount_users_account,
};
