var _ = `العربية`,
  _ = `%1$s% من مراجعات المستخدمين الـ%2$s لهذه اللعبة إيجابية`,
  _ = `%1$s% من مراجعات المستخدمين الـ%2$s في %3$s لهذه اللعبة إيجابية`,
  _ = `خصم بنسبة %1$s%. %2$s عادةً يتم تخفيضه إلى %3$s`,
  _ = `سعر خاص يبلغ %1$s`,
  _ = `مجانًا`,
  _ = `في السلة`,
  _ = `إضافة إلى السلة`,
  _ = `الشراء كهدية`,
  _ = `اللعب الآن`,
  _ = `إضافة إلى المكتبة`,
  _ = `تسجيل الدخول`,
  _ = `سجّل الدخول لإضافة هذا العنصر المجاني إلى حسابك.`,
  _ = `القائمة`,
  _ = `الأكثر مبيعًا`,
  _ = `الإصدارات الجديدة`,
  _ = `تخفيضات`,
  _ = `البحث في المتجر`,
  _ = `مسح مصطلح البحث`,
  _ = `قائمة الأمنيات`,
  _ = `السلة`,
  _ = `ألعاب VR`,
  _ = `أشهر الروابط`,
  _ = `الصفحة الرئيسية للمتجر`,
  _ = `رائعة على Deck`,
  _ = `تعمل جيدًا على Frame`,
  _ = `مجانًا`,
  _ = `مخططات Steam`,
  _ = `الإصدارات المقبلة`,
  _ = `متجر النقاط`,
  _ = `بطاقات الهدايا`,
  _ = `الأخبار والتحديثات`,
  _ = `التفضيلات`,
  _ = `تصفح`,
  _ = `الأفضل`,
  _ = `التوصيات`,
  _ = `الفئات`,
  _ = `الأجهزة`,
  _ = `طرق اللعب`,
  _ = `الأقسام الخاصة`,
  _ = `عرض الكل`,
  _ = `المزيد`,
  _ = `القائمة`,
  _ = `تفضيلاتي`,
  _ = `قائمة أمنياتي`,
  _ = `اشتراكاتي`,
  _ = `الألعاب التي أتابعها`,
  _ = `حسابي`,
  _ = `عائلتي`,
  _ = `المعروضة مؤخرًا`,
  _ = `المتابعة من حيث توقفت`,
  _ = `الموصى به لك`,
  _ = `من قائمة أمنياتك`,
  _ = `DLC مخصص لك`,
  _ = `من أجلك`,
  _ = `تصفح أفضل الوجهات`,
  _ = `أفضل الوجهات`,
  _ = `الجديد والرائج`,
  _ = `مجانًا`,
  _ = `أفضل الألعاب المجانية`,
  _ = `الأكثر مبيعًا`,
  _ = `الإصدارات الجديدة`,
  _ = `استكشِف محتوى جديد على Steam`,
  _ = `اطّلِع على المتاح في جدول الإصدارات`,
  _ = `الخصومات والأحداث`,
  _ = `جميع المخططات والإحصاءات`,
  _ = `استكشِف أفضل الألعاب حسب الأسبوع أو الشهر أو السنة`,
  _ = `قائمة أمنياتك`,
  _ = `%1$s من الخصومات`,
  _ = `الأحداث الخاصة`,
  _ = `الألعاب الشائعة`,
  _ = `العروض الخاصة`,
  _ = `التوصيات`,
  _ = `قائمة انتظار الإصدارات الجديدة`,
  _ = `توصيات المجتمع`,
  _ = `الموصي التفاعلي`,
  _ = `تقويمك الشخصي`,
  _ = `شائع بين الأصدقاء`,
  _ = `مُقيمو Steam`,
  _ = `DLC مخصص لك`,
  _ = `قائمة الاكتشاف لديك`,
  _ = `السماح لـSteam بإنشاء مجموعة مخصصة من الألعاب الموصى بها لك`,
  _ = `استكشاف قائمة الانتظار الخاصة بي`,
  _ = `تلقي توصيات مخصصة من نظام التعلم الآلي الخاص بنا`,
  _ = `تلقي التوصيات`,
  _ = `استكشِف قائمة مخصصة من الألعاب التي صدرت مؤخرًا أو ستصدر قريبًا.`,
  _ = `استكشاف جدولي`,
  _ = `جديد`,
  _ = `أكثر الأنواع المفضلة لديك`,
  _ = `أفضل فئاتك`,
  _ = `عرض جميع الأنواع والسمات`,
  _ = `إظهار المزيد`,
  _ = `إخفاء`,
  _ = `عرض جميع الوسوم`,
  _ = `جميع الأنواع والسمات`,
  _ = `الأجهزة`,
  _ = `أجهزة VR`,
  _ = `Steam Deck`,
  _ = `وحدة تحكم Steam`,
  _ = `جهاز Steam`,
  _ = `Steam Frame`,
  _ = `Valve Index`,
  _ = `قاعدة التوصيل`,
  _ = `أجهزة Steam`,
  _ = `طرق لتشغيل الألعاب`,
  _ = `الأقسام الخاصة`,
  _ = `Steam Next Fest`,
  _ = `جوائز Steam`,
  _ = `ملخص Steam السنوي`,
  _ = `مختبرات Steam`,
  _ = `DLC`,
  _ = `أحداث التخفيضات`,
  _ = `تم العرض مؤخرًا`,
  _ = `عمليات البحث الشائعة`,
  _ = `نتائج البحث`,
  _ = `أكثر الأنواع المفضلة لديك`,
  _ = `التصفح حسب...`,
  _ = `لا عناصر تُطابق بحثك.`,
  _ = `بحث متقدم`,
  _ = `%1$s من الألعاب`,
  _ = `البحث`,
  _ = `قائمة المتجر`,
  _ = `يتضمن %1$s من الألعاب`,
  _ = `في المكتبة`,
  _ = `في قائمة الأمنيات`,
  _ = `في العربة`,
  _ = `تم التجاهل`,
  _ = `مستبعدة حسب التفضيلات`,
  _ = `الفئات الخاصة بي:`,
  _ = `لا شيء`,
  _ = `تصفية حسب الفئة`,
  _ = `مسح معاملات تصفية الفئات`,
  _ = `إضافة فئة`,
  _ = `إزالة فئة`,
  _ = `إزالة هذه الفئة من هذا العنصر`,
  _ = `قم بتصفية قائمة أمنياتك لعرض العناصر في هذه الفئة`,
  _ = `الكل`,
  _ = `بلا تصنيف`,
  _ = `إضافة أو إزالة فئات`,
  _ = `في انتظار التخفيضات`,
  _ = `قائمة عيد الميلاد`,
  _ = `موصى به من الأصدقاء`,
  _ = `إدارة الفئات لـ %1$s`,
  _ = `الفئات الحالية`,
  _ = `ابحث عن طريق الاسم أو أضف فئة جديدة`,
  _ = `إضافة فئة`,
  _ = `الفئات الأخرى الخاصة بي`,
  _ = `الفئات المقترحة`,
  _ = `وصل هذا العنصر من قائمة الأمنيات إلى الحد الأقصى المسموح به وهو %1$s فئة.`,
  _ = `متقدمة...`,
  _ = `عادةً`,
  _ = `أقل سعر له خلال 30 يومًا`,
  _ = `كانت هذه اللعبة معروضة بخصم %1$s طوال %2$s من الأيام الماضية`,
  _ = `هذه اللعبة معروضة حاليًا بأقل سعر خلال %1$s من الأيام الماضية`,
  _ = `الآن`,
  _ = `يُحدد الخصم حسب أقل سعر خلال الثلاثين يومًا الماضية`,
  _ = `تقويمك الشخصي`,
  _ = `قائمة مخصصة لك بالألعاب الجديدة والقادمة`,
  _ = `+%1$s أكثر`,
  _ = `استكشف تقويمك الشخصي الكامل`,
  _ = `استكشاف المزيد`,
  _ = `ليس لدينا أي إصدارات جديدة نوصي بها لك في هذا اليوم <1>تحقق من بقية التقويم لديك!</1>`,
  _ = `الجديد`,
  _ = `اليوم`,
  _ = `dont translate`,
  _ = {
    language: _,
    review_summary_reviewrate: _,
    review_summary_reviewrate_language_specific: _,
    Discount_ARIA_Label: _,
    Discount_ARIA_Label_SpecialPrice: _,
    Price_Free: _,
    AddToCartButton_InCart: _,
    AddToCartButton_AddToCart: _,
    AddToCartButton_PurchaseAsGift: _,
    PlayGameButton_PlayNow: _,
    AddToLibraryButton: _,
    Button_SignIn: _,
    SignInToAddToLibrary_Tooltip: _,
    Menu_OpenFlyout: _,
    Menu_TopSellers: _,
    Menu_NewReleases: _,
    Menu_OnSale: _,
    Menu_SearchPlaceholder: _,
    Menu_ClearSearchTerm: _,
    Menu_Wishlist: _,
    Menu_Cart: _,
    Menu_VR: _,
    Menu_Popover_TopLinks: _,
    Menu_Popover_StoreHome: _,
    Menu_Popover_GreatonDeck: _,
    Menu_Popover_GreatonFrame: _,
    Menu_Popover_FreeToPlay: _,
    Menu_Popover_SteamCharts: _,
    Menu_Popover_Upcoming: _,
    Menu_Popover_PointsShop: _,
    Menu_Popover_GiftCards: _,
    Menu_Popover_NewsAndUpdates: _,
    Menu_Popover_Preferences: _,
    Menu_Popover_Browse: _,
    Menu_Popover_Top: _,
    Menu_Popover_Recommendations: _,
    Menu_Popover_Categories: _,
    Menu_Popover_Hardware: _,
    Menu_Popover_WaysToPlay: _,
    Menu_Popover_SpecialSections: _,
    Menu_Popover_ViewAll: _,
    Menu_Popover_More: _,
    Menu_Popover_Menu: _,
    Menu_Section_Browse_MyPreferences: _,
    Menu_Section_Browse_MyWishlist: _,
    Menu_Section_Browse_MySubscriptions: _,
    Menu_Section_Browse_MyFollowedGames: _,
    Menu_Section_Browse_MyAccount: _,
    Menu_Section_Browse_MyFamily: _,
    Menu_Section_Browse_RecentlyViewed: _,
    Menu_Section_Browse_PickUpWhereYouLeftOff: _,
    Menu_Section_Browse_Recommended: _,
    Menu_Section_Browse_FromYourWishlist: _,
    Menu_Section_Browse_DLCForYou: _,
    Menu_Section_Browse_ForYou: _,
    Menu_Section_Browse_BrowseTop: _,
    Menu_Section_Browse_Top: _,
    Menu_Section_Browse_PopularNew: _,
    Menu_Section_Browse_FreeToPlay: _,
    Menu_Section_Browse_TopFreeToPlay: _,
    Menu_Section_Browse_TopSellers: _,
    Menu_Section_Browse_NewReleases: _,
    Menu_Section_Browse_NewReleases_Desc: _,
    Menu_Section_Browse_Upcoming_Desc: _,
    Menu_Section_Browse_Discounts: _,
    Menu_Section_Browse_Charts: _,
    Menu_Section_Browse_Charts_Desc: _,
    Menu_Section_Browse_Discounts_YourWishlist: _,
    Menu_Section_Browse_Discounts_YourWishlist_Discounts: _,
    Menu_Section_Browse_Discounts_SpecialEvents: _,
    Menu_Section_Browse_Discounts_PopularTitles: _,
    Menu_Section_Browse_Discounts_SpecialOffers: _,
    Menu_Section_Recommendations: _,
    Menu_Section_Recommendations_NewReleasesQueue: _,
    Menu_Section_Recommendations_CommunityRecommendations: _,
    Menu_Section_Recommendations_InteractiveRecommender: _,
    Menu_Section_Recommendations_PersonalCalendar: _,
    Menu_Section_Recommendations_PopularAmongFriends: _,
    Menu_Section_Recommendations_SteamCurators: _,
    Menu_Section_Recommendations_DLCForYou: _,
    Menu_Section_Recommendations_DiscoveryQueue_Title: _,
    Menu_Section_Recommendations_DiscoveryQueue_Description: _,
    Menu_Section_Recommendations_DiscoveryQueue_ActionButton: _,
    Menu_Section_Recommendations_InteractiveRecommender_Description: _,
    Menu_Section_Recommendations_InteractiveRecommender_ActionButton: _,
    Menu_Section_Recommendations_PersonalCalendar_Description: _,
    Menu_Section_Recommendations_PersonalCalendar_ActionButton: _,
    Menu_Section_Recommendations_New: _,
    Menu_Section_Categories_YourTopGenres: _,
    Menu_Section_Categories_YourTopCategories: _,
    Menu_Section_Categories_ViewAll: _,
    Menu_Section_Categories_Expand: _,
    Menu_Section_Categories_Collapse: _,
    Menu_Section_Categories_ViewAllTags: _,
    Menu_Section_Categories_GenresAndThemes: _,
    Menu_Section_Hardware: _,
    Menu_Section_Hardware_VRHardware: _,
    Menu_Section_Hardware_SteamDeck: _,
    Menu_Section_Hardware_SteamController: _,
    Menu_Section_Hardware_SteamMachine: _,
    Menu_Section_Hardware_SteamFrame: _,
    Menu_Section_Hardware_ValveIndex: _,
    Menu_Section_Hardware_SteamDeckDock: _,
    Menu_Section_Hardware_Family: _,
    Menu_Section_WaysToPlay: _,
    Menu_Section_SpecialSections: _,
    Menu_Section_SpecialSections_NextFest: _,
    Menu_Section_SpecialSections_SteamAwards: _,
    Menu_Section_SpecialSections_SteamReplay: _,
    Menu_Section_SpecialSections_SteamLabs: _,
    Menu_Section_SpecialSections_DLCForYou: `DLC`,
    Menu_Section_SpecialSections_SaleEvents: _,
    Menu_SearchBar_RecentlyViewed: _,
    Menu_SearchBar_PopularSearches: _,
    Menu_SearchBar_SearchResults: _,
    Menu_SearchBar_YourTopGenres: _,
    Menu_SearchBar_BrowseBy: _,
    Menu_SearchBar_NoMatches: _,
    Menu_SearchBar_AdvancedSearch: _,
    Menu_SearchBar_CategoryGameCount: _,
    Menu_Search: _,
    Menu_Label: _,
    Menu_IncludesXGames: _,
    ItemFlag_InLibrary: _,
    ItemFlag_OnWishlist: _,
    ItemFlag_InCart: _,
    ItemFlag_Ignored: _,
    ItemFlag_ExcludedByPreferences: _,
    Wishlist_Controls_Categories_Header: _,
    Wishlist_Categories_None: _,
    Wishlist_Gamepad_Filter_Category: _,
    Wishlist_Gamepad_Filter_Clear_Category: _,
    Wishlist_Gamepad_Add_Category: _,
    Wishlist_Gamepad_Removecategory: _,
    Wishlist_Controls_Categories_Remove_Tooltip: _,
    Wishlist_Controls_Categories_Filter_Tooltip: _,
    Wishlist_Controls_Categories_All: _,
    Wishlist_Controls_Categories_Uncategorized: _,
    Wishlist_Controls_Categories_Manage: _,
    Wishlist_Categories_Suggested_Discount: _,
    Wishlist_Categories_Suggested_Birthday: _,
    Wishlist_Categories_Suggested_Recommended: _,
    Wishlist_Controls_Categories_Manageitem: _,
    Wishlist_Controls_Categories_Header_Current: _,
    Wishlist_Categories_Dialog_Search: _,
    Wishlist_Categories_Dialog_Add: _,
    Wishlist_Controls_Categories_Header_Other: _,
    Wishlist_Controls_Categories_Header_Suggested: _,
    Wishlist_Categories_Max_Per_App_Reached: _,
    Wishlist_Categories_Dialog_Advanced: _,
    Price_History_Normal_Price: _,
    Price_History_Recent_Low_Price: _,
    Price_History_Recent_Low_Price_Ttip: _,
    Price_History_Current_Low_Price_Ttip: _,
    Price_History_Current_Price: _,
    Price_History_Lowest_Previous_30: _,
    PersonalCalendar_Title: _,
    PersonalCalendar_Subtitle: _,
    PersonalCalendar_More: _,
    PersonalCalendar_Full: _,
    PersonalCalendar_Explore: _,
    PersonalCalendar_EmptyDay: _,
    NewBadge: _,
    Time_Today: _,
    store_ui_dummy: _,
  };
export {
  _ as AddToCartButton_AddToCart,
  _ as AddToCartButton_InCart,
  _ as AddToCartButton_PurchaseAsGift,
  _ as AddToLibraryButton,
  _ as Button_SignIn,
  _ as Discount_ARIA_Label,
  _ as Discount_ARIA_Label_SpecialPrice,
  _ as ItemFlag_ExcludedByPreferences,
  _ as ItemFlag_Ignored,
  _ as ItemFlag_InCart,
  _ as ItemFlag_InLibrary,
  _ as ItemFlag_OnWishlist,
  _ as Menu_Cart,
  _ as Menu_ClearSearchTerm,
  _ as Menu_IncludesXGames,
  _ as Menu_Label,
  _ as Menu_NewReleases,
  _ as Menu_OnSale,
  _ as Menu_OpenFlyout,
  _ as Menu_Popover_Browse,
  _ as Menu_Popover_Categories,
  _ as Menu_Popover_FreeToPlay,
  _ as Menu_Popover_GiftCards,
  _ as Menu_Popover_GreatonDeck,
  _ as Menu_Popover_GreatonFrame,
  _ as Menu_Popover_Hardware,
  _ as Menu_Popover_Menu,
  _ as Menu_Popover_More,
  _ as Menu_Popover_NewsAndUpdates,
  _ as Menu_Popover_PointsShop,
  _ as Menu_Popover_Preferences,
  _ as Menu_Popover_Recommendations,
  _ as Menu_Popover_SpecialSections,
  _ as Menu_Popover_SteamCharts,
  _ as Menu_Popover_StoreHome,
  _ as Menu_Popover_Top,
  _ as Menu_Popover_TopLinks,
  _ as Menu_Popover_Upcoming,
  _ as Menu_Popover_ViewAll,
  _ as Menu_Popover_WaysToPlay,
  _ as Menu_Search,
  _ as Menu_SearchBar_AdvancedSearch,
  _ as Menu_SearchBar_BrowseBy,
  _ as Menu_SearchBar_CategoryGameCount,
  _ as Menu_SearchBar_NoMatches,
  _ as Menu_SearchBar_PopularSearches,
  _ as Menu_SearchBar_RecentlyViewed,
  _ as Menu_SearchBar_SearchResults,
  _ as Menu_SearchBar_YourTopGenres,
  _ as Menu_SearchPlaceholder,
  _ as Menu_Section_Browse_BrowseTop,
  _ as Menu_Section_Browse_Charts,
  _ as Menu_Section_Browse_Charts_Desc,
  _ as Menu_Section_Browse_DLCForYou,
  _ as Menu_Section_Browse_Discounts,
  _ as Menu_Section_Browse_Discounts_PopularTitles,
  _ as Menu_Section_Browse_Discounts_SpecialEvents,
  _ as Menu_Section_Browse_Discounts_SpecialOffers,
  _ as Menu_Section_Browse_Discounts_YourWishlist,
  _ as Menu_Section_Browse_Discounts_YourWishlist_Discounts,
  _ as Menu_Section_Browse_ForYou,
  _ as Menu_Section_Browse_FreeToPlay,
  _ as Menu_Section_Browse_FromYourWishlist,
  _ as Menu_Section_Browse_MyAccount,
  _ as Menu_Section_Browse_MyFamily,
  _ as Menu_Section_Browse_MyFollowedGames,
  _ as Menu_Section_Browse_MyPreferences,
  _ as Menu_Section_Browse_MySubscriptions,
  _ as Menu_Section_Browse_MyWishlist,
  _ as Menu_Section_Browse_NewReleases,
  _ as Menu_Section_Browse_NewReleases_Desc,
  _ as Menu_Section_Browse_PickUpWhereYouLeftOff,
  _ as Menu_Section_Browse_PopularNew,
  _ as Menu_Section_Browse_RecentlyViewed,
  _ as Menu_Section_Browse_Recommended,
  _ as Menu_Section_Browse_Top,
  _ as Menu_Section_Browse_TopFreeToPlay,
  _ as Menu_Section_Browse_TopSellers,
  _ as Menu_Section_Browse_Upcoming_Desc,
  _ as Menu_Section_Categories_Collapse,
  _ as Menu_Section_Categories_Expand,
  _ as Menu_Section_Categories_GenresAndThemes,
  _ as Menu_Section_Categories_ViewAll,
  _ as Menu_Section_Categories_ViewAllTags,
  _ as Menu_Section_Categories_YourTopCategories,
  _ as Menu_Section_Categories_YourTopGenres,
  _ as Menu_Section_Hardware,
  _ as Menu_Section_Hardware_Family,
  _ as Menu_Section_Hardware_SteamController,
  _ as Menu_Section_Hardware_SteamDeck,
  _ as Menu_Section_Hardware_SteamDeckDock,
  _ as Menu_Section_Hardware_SteamFrame,
  _ as Menu_Section_Hardware_SteamMachine,
  _ as Menu_Section_Hardware_VRHardware,
  _ as Menu_Section_Hardware_ValveIndex,
  _ as Menu_Section_Recommendations,
  _ as Menu_Section_Recommendations_CommunityRecommendations,
  _ as Menu_Section_Recommendations_DLCForYou,
  _ as Menu_Section_Recommendations_DiscoveryQueue_ActionButton,
  _ as Menu_Section_Recommendations_DiscoveryQueue_Description,
  _ as Menu_Section_Recommendations_DiscoveryQueue_Title,
  _ as Menu_Section_Recommendations_InteractiveRecommender,
  _ as Menu_Section_Recommendations_InteractiveRecommender_ActionButton,
  _ as Menu_Section_Recommendations_InteractiveRecommender_Description,
  _ as Menu_Section_Recommendations_New,
  _ as Menu_Section_Recommendations_NewReleasesQueue,
  _ as Menu_Section_Recommendations_PersonalCalendar,
  _ as Menu_Section_Recommendations_PersonalCalendar_ActionButton,
  _ as Menu_Section_Recommendations_PersonalCalendar_Description,
  _ as Menu_Section_Recommendations_PopularAmongFriends,
  _ as Menu_Section_Recommendations_SteamCurators,
  _ as Menu_Section_SpecialSections,
  _ as Menu_Section_SpecialSections_DLCForYou,
  _ as Menu_Section_SpecialSections_NextFest,
  _ as Menu_Section_SpecialSections_SaleEvents,
  _ as Menu_Section_SpecialSections_SteamAwards,
  _ as Menu_Section_SpecialSections_SteamLabs,
  _ as Menu_Section_SpecialSections_SteamReplay,
  _ as Menu_Section_WaysToPlay,
  _ as Menu_TopSellers,
  _ as Menu_VR,
  _ as Menu_Wishlist,
  _ as NewBadge,
  _ as PersonalCalendar_EmptyDay,
  _ as PersonalCalendar_Explore,
  _ as PersonalCalendar_Full,
  _ as PersonalCalendar_More,
  _ as PersonalCalendar_Subtitle,
  _ as PersonalCalendar_Title,
  _ as PlayGameButton_PlayNow,
  _ as Price_Free,
  _ as Price_History_Current_Low_Price_Ttip,
  _ as Price_History_Current_Price,
  _ as Price_History_Lowest_Previous_30,
  _ as Price_History_Normal_Price,
  _ as Price_History_Recent_Low_Price,
  _ as Price_History_Recent_Low_Price_Ttip,
  _ as SignInToAddToLibrary_Tooltip,
  _ as Time_Today,
  _ as Wishlist_Categories_Dialog_Add,
  _ as Wishlist_Categories_Dialog_Advanced,
  _ as Wishlist_Categories_Dialog_Search,
  _ as Wishlist_Categories_Max_Per_App_Reached,
  _ as Wishlist_Categories_None,
  _ as Wishlist_Categories_Suggested_Birthday,
  _ as Wishlist_Categories_Suggested_Discount,
  _ as Wishlist_Categories_Suggested_Recommended,
  _ as Wishlist_Controls_Categories_All,
  _ as Wishlist_Controls_Categories_Filter_Tooltip,
  _ as Wishlist_Controls_Categories_Header,
  _ as Wishlist_Controls_Categories_Header_Current,
  _ as Wishlist_Controls_Categories_Header_Other,
  _ as Wishlist_Controls_Categories_Header_Suggested,
  _ as Wishlist_Controls_Categories_Manage,
  _ as Wishlist_Controls_Categories_Manageitem,
  _ as Wishlist_Controls_Categories_Remove_Tooltip,
  _ as Wishlist_Controls_Categories_Uncategorized,
  _ as Wishlist_Gamepad_Add_Category,
  _ as Wishlist_Gamepad_Filter_Category,
  _ as Wishlist_Gamepad_Filter_Clear_Category,
  _ as Wishlist_Gamepad_Removecategory,
  _ as default,
  _ as language,
  _ as review_summary_reviewrate,
  _ as review_summary_reviewrate_language_specific,
  _ as store_ui_dummy,
};
