var _ = `greek`,
  _ = `Το %1$s% των %2$s κριτικών από χρήστες για αυτό το παιχνίδι είναι θετικές`,
  _ = `Το %1$s% από τις %2$s κριτικές των χρηστών στα %3$s για αυτό το παιχνίδι είναι θετικές`,
  _ = `Έκπτωση %1$s%. Κανονική τιμή: %2$s. Με έκπτωση: %3$s.`,
  _ = `Ειδική τιμή: %1$s`,
  _ = `Δωρεάν`,
  _ = `Στο καλάθι`,
  _ = `Προσθήκη στο καλάθι`,
  _ = `Αγορά ως δώρο`,
  _ = `Εκκίνηση τώρα`,
  _ = `Προσθήκη στη Συλλογή`,
  _ = `Σύνδεση`,
  _ = `Συνδεθείτε για να προσθέσετε αυτό το δωρεάν αντικείμενο στον λογαριασμό σας.`,
  _ = `Μενού`,
  _ = `Κορυφαία σε πωλήσεις`,
  _ = `Νέες κυκλοφορίες`,
  _ = `Σε έκπτωση`,
  _ = `Αναζήτηση στο Κατάστημα`,
  _ = `Εκκαθάριση όρου αναζήτησης`,
  _ = `Λίστα Επιθυμιών`,
  _ = `Καλάθι`,
  _ = `Τίτλοι VR`,
  _ = `Κορυφαίοι σύνδεσμοι`,
  _ = `Αρχική σελίδα Καταστήματος`,
  _ = `Υπέροχο στο Steam Deck`,
  _ = `Υπέροχο στο Frame`,
  _ = `Δωρεάν για παίξιμο`,
  _ = `Γραφήματα Steam`,
  _ = `Επερχόμενες κυκλοφορίες`,
  _ = `Μαγαζί Πόντων`,
  _ = `Δωροκάρτες`,
  _ = `Νέα και ενημερώσεις`,
  _ = `Προτιμήσεις`,
  _ = `Περιήγηση`,
  _ = `Κορυφαία`,
  _ = `Προτάσεις`,
  _ = `Κατηγορίες`,
  _ = `Υλισμικό`,
  _ = `Τρόποι παιχνιδιού`,
  _ = `Ειδικές ενότητες`,
  _ = `Προβολή όλων`,
  _ = `Άλλα`,
  _ = `Μενού`,
  _ = `Προτιμήσεις`,
  _ = `Λίστα Επιθυμιών`,
  _ = `Συνδρομές`,
  _ = `Παιχνίδια που ακολουθώ`,
  _ = `Λογαριασμός`,
  _ = `Οικογένεια`,
  _ = `Είδατε πρόσφατα`,
  _ = `Συνεχίστε από εκεί που μείνατε`,
  _ = `Προτεινόμενα για εσάς`,
  _ = `Από τη Λίστα Επιθυμιών σας`,
  _ = `DLC για εσάς`,
  _ = `Για εσάς`,
  _ = `Περιήγηση σε κορυφαίες ενότητες`,
  _ = `Κορυφαίες ενότητες`,
  _ = `Νέα και ανερχόμενα`,
  _ = `Δωρεάν για παίξιμο`,
  _ = `Κορυφαία δωρεάν για παίξιμο`,
  _ = `Κορυφαία σε πωλήσεις`,
  _ = `Νέες κυκλοφορίες`,
  _ = `Ανακαλύψτε νέο περιεχόμενο στο Steam`,
  _ = `Δείτε το ημερολόγιο κυκλοφοριών`,
  _ = `Εκπτώσεις και συμβάντα`,
  _ = `Όλα τα γραφήματα και στατιστικά`,
  _ = `Ανακαλύψτε κορυφαίους τίτλους ανά εβδομάδα, μήνα ή έτος`,
  _ = `Η Λίστα Επιθυμιών σας`,
  _ = `%1$s εκπτώσεις`,
  _ = `Ειδικά συμβάντα`,
  _ = `Δημοφιλείς τίτλοι`,
  _ = `Ειδικές προσφορές`,
  _ = `Προτάσεις`,
  _ = `Σειρά νέων κυκλοφοριών`,
  _ = `Προτάσεις Κοινότητας`,
  _ = `Αλληλεπιδραστικός σύμβουλος`,
  _ = `Το προσωπικό σας ημερολόγιο`,
  _ = `Αρέσουν σε φίλους`,
  _ = `Επιμελητές Steam`,
  _ = `DLC για εσάς`,
  _ = `Η σειρά ανακάλυψής σας`,
  _ = `Αφήστε το Steam να δημιουργήσει ένα προσαρμοσμένο σύνολο παιχνιδιών που προτείνονται για εσάς`,
  _ = `Εξερεύνηση σειράς`,
  _ = `Λάβετε εξατομικευμένες προτάσεις από το σύστημα μηχανικής μάθησής μας`,
  _ = `Λάβετε προτάσεις`,
  _ = `Ανακαλύψτε μια εξατομικευμένη λίστα παιχνιδιών που έχουν κυκλοφορήσει πρόσφατα ή θα κυκλοφορήσουν προσεχώς.`,
  _ = `Εξερεύνηση του ημερολογίου μου`,
  _ = `ΝΕΑ`,
  _ = `Τα κορυφαία είδη σας`,
  _ = `Οι κορυφαίες κατηγορίες σας`,
  _ = `Προβολή όλων των ειδών και θεμάτων`,
  _ = `Επέκταση`,
  _ = `Σύμπτυξη`,
  _ = `Προβολή όλων των ετικετών`,
  _ = `Όλα τα είδη και θέματα`,
  _ = `Υλισμικό`,
  _ = `Υλισμικό VR`,
  _ = `Steam Deck`,
  _ = `Steam Controller`,
  _ = `Steam Machine`,
  _ = `Steam Frame`,
  _ = `Valve Index`,
  _ = `Βάση`,
  _ = `Υλισμικό Steam`,
  _ = `Τρόποι να παίξετε`,
  _ = `Ειδικές ενότητες`,
  _ = `Γιορτή Επερχόμενων Steam`,
  _ = `Βραβεία Steam`,
  _ = `Steam Replay`,
  _ = `Κέντρο Έρευνας Steam`,
  _ = `DLC`,
  _ = `ΣΥΜΒΑΝΤΑ ΕΚΠΤΩΣΕΩΝ`,
  _ = `Είδατε πρόσφατα`,
  _ = `Δημοφιλείς αναζητήσεις`,
  _ = `Αποτελέσματα αναζήτησης`,
  _ = `Τα κορυφαία είδη σας`,
  _ = `Περιήγηση ανά…`,
  _ = `Κανένα στοιχείο δεν ταιριάζει με την αναζήτησή σας.`,
  _ = `Σύνθετη αναζήτηση`,
  _ = `%1$s παιχνίδια`,
  _ = `Αναζήτηση`,
  _ = `Μενού Καταστήματος`,
  _ = `Περιλαμβάνει %1$s παιχνίδια`,
  _ = `ΣΤΗ ΣΥΛΛΟΓΗ`,
  _ = `ΣΤΗ ΛΙΣΤΑ ΕΠΙΘΥΜΙΩΝ`,
  _ = `ΣΤΟ ΚΑΛΑΘΙ`,
  _ = `ΣΕ ΑΓΝΟΗΣΗ`,
  _ = `ΕΞΑΙΡΕΘΗΚΕ ΑΠΟ ΠΡΟΤΙΜΗΣΕΙΣ`,
  _ = `Οι κατηγορίες μου:`,
  _ = `Καμία`,
  _ = `Φιλτράρισμα ανά κατηγορία`,
  _ = `Εκκαθάριση φίλτρων κατηγορίας`,
  _ = `Προσθήκη κατηγορίας`,
  _ = `Αφαίρεση κατηγορίας`,
  _ = `Αφαίρεση αυτής της κατηγορίας από αυτό το αντικείμενο`,
  _ = `Φιλτράρετε τη Λίστα Επιθυμιών σας για αντικείμενα αυτής της κατηγορίας`,
  _ = `Όλα`,
  _ = `Χωρίς κατηγορία`,
  _ = `Προσθήκη ή αφαίρεση κατηγοριών`,
  _ = `Σε αναμονή για προσφορά`,
  _ = `Λίστα γενεθλίων`,
  _ = `Προτείνονται από φίλους`,
  _ = `Διαχείριση κατηγοριών για %1$s`,
  _ = `Τρέχουσες κατηγορίες`,
  _ = `Αναζήτηση βάσει ονόματος ή προσθήκη νέας κατηγορίας`,
  _ = `Προσθήκη κατηγορίας`,
  _ = `Οι άλλες κατηγορίες μου`,
  _ = `Προτεινόμενες κατηγορίες`,
  _ = `Αυτό το αντικείμενο Λίστας Επιθυμιών έχει φτάσει το όριο των %1$s κατηγοριών.`,
  _ = `Σύνθετες...`,
  _ = `ΚΑΝΟΝΙΚΗ`,
  _ = `ΧΑΜΗΛΟΤΕΡΗ (30 ΗΜΕΡΕΣ)`,
  _ = `Αυτό το παιχνίδι ήταν σε έκπτωση (%1$s) τις τελευταίες %2$s ημέρες`,
  _ = `Η τρέχουσα τιμή για αυτό το παιχνίδι είναι η χαμηλότερη των τελευταίων %1$s ημερών.`,
  _ = `ΤΩΡΑ`,
  _ = `Έκπτωση με βάση τη χαμηλότερη τιμή τις προηγούμενες 30 ημέρες`,
  _ = `Το προσωπικό σας ημερολόγιο`,
  _ = `Μια λίστα νέων και επερχόμενων παιχνιδιών, εξατομικευμένη για εσάς`,
  _ = `+%1$s ακόμα`,
  _ = `Εξερευνήστε το πλήρες προσωπικό ημερολόγιό σας`,
  _ = `Ανακαλύψτε περισσότερα`,
  _ = `Δεν έχουμε να σας προτείνουμε καμία νέα κυκλοφορία για αυτήν την ημέρα<1>Ρίξτε μια ματιά στο υπόλοιπο ημερολόγιό σας!</1>`,
  _ = `ΝΕΟ`,
  _ = `Σήμερα`,
  _ = `dont translate`,
  _ = {
    language: _,
    review_summary_reviewrate: _,
    review_summary_reviewrate_language_specific: _,
    Discount_ARIA_Label: _,
    Discount_ARIA_Label_SpecialPrice: _,
    Price_Free: _,
    AddToCartButton_InCart: _,
    AddToCartButton_AddToCart: _,
    AddToCartButton_PurchaseAsGift: _,
    PlayGameButton_PlayNow: _,
    AddToLibraryButton: _,
    Button_SignIn: _,
    SignInToAddToLibrary_Tooltip: _,
    Menu_OpenFlyout: _,
    Menu_TopSellers: _,
    Menu_NewReleases: _,
    Menu_OnSale: _,
    Menu_SearchPlaceholder: _,
    Menu_ClearSearchTerm: _,
    Menu_Wishlist: _,
    Menu_Cart: _,
    Menu_VR: _,
    Menu_Popover_TopLinks: _,
    Menu_Popover_StoreHome: _,
    Menu_Popover_GreatonDeck: _,
    Menu_Popover_GreatonFrame: _,
    Menu_Popover_FreeToPlay: _,
    Menu_Popover_SteamCharts: _,
    Menu_Popover_Upcoming: _,
    Menu_Popover_PointsShop: _,
    Menu_Popover_GiftCards: _,
    Menu_Popover_NewsAndUpdates: _,
    Menu_Popover_Preferences: _,
    Menu_Popover_Browse: _,
    Menu_Popover_Top: _,
    Menu_Popover_Recommendations: _,
    Menu_Popover_Categories: _,
    Menu_Popover_Hardware: _,
    Menu_Popover_WaysToPlay: _,
    Menu_Popover_SpecialSections: _,
    Menu_Popover_ViewAll: _,
    Menu_Popover_More: _,
    Menu_Popover_Menu: _,
    Menu_Section_Browse_MyPreferences: _,
    Menu_Section_Browse_MyWishlist: _,
    Menu_Section_Browse_MySubscriptions: _,
    Menu_Section_Browse_MyFollowedGames: _,
    Menu_Section_Browse_MyAccount: _,
    Menu_Section_Browse_MyFamily: _,
    Menu_Section_Browse_RecentlyViewed: _,
    Menu_Section_Browse_PickUpWhereYouLeftOff: _,
    Menu_Section_Browse_Recommended: _,
    Menu_Section_Browse_FromYourWishlist: _,
    Menu_Section_Browse_DLCForYou: _,
    Menu_Section_Browse_ForYou: _,
    Menu_Section_Browse_BrowseTop: _,
    Menu_Section_Browse_Top: _,
    Menu_Section_Browse_PopularNew: _,
    Menu_Section_Browse_FreeToPlay: _,
    Menu_Section_Browse_TopFreeToPlay: _,
    Menu_Section_Browse_TopSellers: _,
    Menu_Section_Browse_NewReleases: _,
    Menu_Section_Browse_NewReleases_Desc: _,
    Menu_Section_Browse_Upcoming_Desc: _,
    Menu_Section_Browse_Discounts: _,
    Menu_Section_Browse_Charts: _,
    Menu_Section_Browse_Charts_Desc: _,
    Menu_Section_Browse_Discounts_YourWishlist: _,
    Menu_Section_Browse_Discounts_YourWishlist_Discounts: _,
    Menu_Section_Browse_Discounts_SpecialEvents: _,
    Menu_Section_Browse_Discounts_PopularTitles: _,
    Menu_Section_Browse_Discounts_SpecialOffers: _,
    Menu_Section_Recommendations: _,
    Menu_Section_Recommendations_NewReleasesQueue: _,
    Menu_Section_Recommendations_CommunityRecommendations: _,
    Menu_Section_Recommendations_InteractiveRecommender: _,
    Menu_Section_Recommendations_PersonalCalendar: _,
    Menu_Section_Recommendations_PopularAmongFriends: _,
    Menu_Section_Recommendations_SteamCurators: _,
    Menu_Section_Recommendations_DLCForYou: _,
    Menu_Section_Recommendations_DiscoveryQueue_Title: _,
    Menu_Section_Recommendations_DiscoveryQueue_Description: _,
    Menu_Section_Recommendations_DiscoveryQueue_ActionButton: _,
    Menu_Section_Recommendations_InteractiveRecommender_Description: _,
    Menu_Section_Recommendations_InteractiveRecommender_ActionButton: _,
    Menu_Section_Recommendations_PersonalCalendar_Description: _,
    Menu_Section_Recommendations_PersonalCalendar_ActionButton: _,
    Menu_Section_Recommendations_New: _,
    Menu_Section_Categories_YourTopGenres: _,
    Menu_Section_Categories_YourTopCategories: _,
    Menu_Section_Categories_ViewAll: _,
    Menu_Section_Categories_Expand: _,
    Menu_Section_Categories_Collapse: _,
    Menu_Section_Categories_ViewAllTags: _,
    Menu_Section_Categories_GenresAndThemes: _,
    Menu_Section_Hardware: _,
    Menu_Section_Hardware_VRHardware: _,
    Menu_Section_Hardware_SteamDeck: _,
    Menu_Section_Hardware_SteamController: _,
    Menu_Section_Hardware_SteamMachine: _,
    Menu_Section_Hardware_SteamFrame: _,
    Menu_Section_Hardware_ValveIndex: _,
    Menu_Section_Hardware_SteamDeckDock: _,
    Menu_Section_Hardware_Family: _,
    Menu_Section_WaysToPlay: _,
    Menu_Section_SpecialSections: _,
    Menu_Section_SpecialSections_NextFest: _,
    Menu_Section_SpecialSections_SteamAwards: _,
    Menu_Section_SpecialSections_SteamReplay: _,
    Menu_Section_SpecialSections_SteamLabs: _,
    Menu_Section_SpecialSections_DLCForYou: `DLC`,
    Menu_Section_SpecialSections_SaleEvents: _,
    Menu_SearchBar_RecentlyViewed: _,
    Menu_SearchBar_PopularSearches: _,
    Menu_SearchBar_SearchResults: _,
    Menu_SearchBar_YourTopGenres: _,
    Menu_SearchBar_BrowseBy: _,
    Menu_SearchBar_NoMatches: _,
    Menu_SearchBar_AdvancedSearch: _,
    Menu_SearchBar_CategoryGameCount: _,
    Menu_Search: _,
    Menu_Label: _,
    Menu_IncludesXGames: _,
    ItemFlag_InLibrary: _,
    ItemFlag_OnWishlist: _,
    ItemFlag_InCart: _,
    ItemFlag_Ignored: _,
    ItemFlag_ExcludedByPreferences: _,
    Wishlist_Controls_Categories_Header: _,
    Wishlist_Categories_None: _,
    Wishlist_Gamepad_Filter_Category: _,
    Wishlist_Gamepad_Filter_Clear_Category: _,
    Wishlist_Gamepad_Add_Category: _,
    Wishlist_Gamepad_Removecategory: _,
    Wishlist_Controls_Categories_Remove_Tooltip: _,
    Wishlist_Controls_Categories_Filter_Tooltip: _,
    Wishlist_Controls_Categories_All: _,
    Wishlist_Controls_Categories_Uncategorized: _,
    Wishlist_Controls_Categories_Manage: _,
    Wishlist_Categories_Suggested_Discount: _,
    Wishlist_Categories_Suggested_Birthday: _,
    Wishlist_Categories_Suggested_Recommended: _,
    Wishlist_Controls_Categories_Manageitem: _,
    Wishlist_Controls_Categories_Header_Current: _,
    Wishlist_Categories_Dialog_Search: _,
    Wishlist_Categories_Dialog_Add: _,
    Wishlist_Controls_Categories_Header_Other: _,
    Wishlist_Controls_Categories_Header_Suggested: _,
    Wishlist_Categories_Max_Per_App_Reached: _,
    Wishlist_Categories_Dialog_Advanced: _,
    Price_History_Normal_Price: _,
    Price_History_Recent_Low_Price: _,
    Price_History_Recent_Low_Price_Ttip: _,
    Price_History_Current_Low_Price_Ttip: _,
    Price_History_Current_Price: _,
    Price_History_Lowest_Previous_30: _,
    PersonalCalendar_Title: _,
    PersonalCalendar_Subtitle: _,
    PersonalCalendar_More: _,
    PersonalCalendar_Full: _,
    PersonalCalendar_Explore: _,
    PersonalCalendar_EmptyDay: _,
    NewBadge: _,
    Time_Today: _,
    store_ui_dummy: _,
  };
export {
  _ as AddToCartButton_AddToCart,
  _ as AddToCartButton_InCart,
  _ as AddToCartButton_PurchaseAsGift,
  _ as AddToLibraryButton,
  _ as Button_SignIn,
  _ as Discount_ARIA_Label,
  _ as Discount_ARIA_Label_SpecialPrice,
  _ as ItemFlag_ExcludedByPreferences,
  _ as ItemFlag_Ignored,
  _ as ItemFlag_InCart,
  _ as ItemFlag_InLibrary,
  _ as ItemFlag_OnWishlist,
  _ as Menu_Cart,
  _ as Menu_ClearSearchTerm,
  _ as Menu_IncludesXGames,
  _ as Menu_Label,
  _ as Menu_NewReleases,
  _ as Menu_OnSale,
  _ as Menu_OpenFlyout,
  _ as Menu_Popover_Browse,
  _ as Menu_Popover_Categories,
  _ as Menu_Popover_FreeToPlay,
  _ as Menu_Popover_GiftCards,
  _ as Menu_Popover_GreatonDeck,
  _ as Menu_Popover_GreatonFrame,
  _ as Menu_Popover_Hardware,
  _ as Menu_Popover_Menu,
  _ as Menu_Popover_More,
  _ as Menu_Popover_NewsAndUpdates,
  _ as Menu_Popover_PointsShop,
  _ as Menu_Popover_Preferences,
  _ as Menu_Popover_Recommendations,
  _ as Menu_Popover_SpecialSections,
  _ as Menu_Popover_SteamCharts,
  _ as Menu_Popover_StoreHome,
  _ as Menu_Popover_Top,
  _ as Menu_Popover_TopLinks,
  _ as Menu_Popover_Upcoming,
  _ as Menu_Popover_ViewAll,
  _ as Menu_Popover_WaysToPlay,
  _ as Menu_Search,
  _ as Menu_SearchBar_AdvancedSearch,
  _ as Menu_SearchBar_BrowseBy,
  _ as Menu_SearchBar_CategoryGameCount,
  _ as Menu_SearchBar_NoMatches,
  _ as Menu_SearchBar_PopularSearches,
  _ as Menu_SearchBar_RecentlyViewed,
  _ as Menu_SearchBar_SearchResults,
  _ as Menu_SearchBar_YourTopGenres,
  _ as Menu_SearchPlaceholder,
  _ as Menu_Section_Browse_BrowseTop,
  _ as Menu_Section_Browse_Charts,
  _ as Menu_Section_Browse_Charts_Desc,
  _ as Menu_Section_Browse_DLCForYou,
  _ as Menu_Section_Browse_Discounts,
  _ as Menu_Section_Browse_Discounts_PopularTitles,
  _ as Menu_Section_Browse_Discounts_SpecialEvents,
  _ as Menu_Section_Browse_Discounts_SpecialOffers,
  _ as Menu_Section_Browse_Discounts_YourWishlist,
  _ as Menu_Section_Browse_Discounts_YourWishlist_Discounts,
  _ as Menu_Section_Browse_ForYou,
  _ as Menu_Section_Browse_FreeToPlay,
  _ as Menu_Section_Browse_FromYourWishlist,
  _ as Menu_Section_Browse_MyAccount,
  _ as Menu_Section_Browse_MyFamily,
  _ as Menu_Section_Browse_MyFollowedGames,
  _ as Menu_Section_Browse_MyPreferences,
  _ as Menu_Section_Browse_MySubscriptions,
  _ as Menu_Section_Browse_MyWishlist,
  _ as Menu_Section_Browse_NewReleases,
  _ as Menu_Section_Browse_NewReleases_Desc,
  _ as Menu_Section_Browse_PickUpWhereYouLeftOff,
  _ as Menu_Section_Browse_PopularNew,
  _ as Menu_Section_Browse_RecentlyViewed,
  _ as Menu_Section_Browse_Recommended,
  _ as Menu_Section_Browse_Top,
  _ as Menu_Section_Browse_TopFreeToPlay,
  _ as Menu_Section_Browse_TopSellers,
  _ as Menu_Section_Browse_Upcoming_Desc,
  _ as Menu_Section_Categories_Collapse,
  _ as Menu_Section_Categories_Expand,
  _ as Menu_Section_Categories_GenresAndThemes,
  _ as Menu_Section_Categories_ViewAll,
  _ as Menu_Section_Categories_ViewAllTags,
  _ as Menu_Section_Categories_YourTopCategories,
  _ as Menu_Section_Categories_YourTopGenres,
  _ as Menu_Section_Hardware,
  _ as Menu_Section_Hardware_Family,
  _ as Menu_Section_Hardware_SteamController,
  _ as Menu_Section_Hardware_SteamDeck,
  _ as Menu_Section_Hardware_SteamDeckDock,
  _ as Menu_Section_Hardware_SteamFrame,
  _ as Menu_Section_Hardware_SteamMachine,
  _ as Menu_Section_Hardware_VRHardware,
  _ as Menu_Section_Hardware_ValveIndex,
  _ as Menu_Section_Recommendations,
  _ as Menu_Section_Recommendations_CommunityRecommendations,
  _ as Menu_Section_Recommendations_DLCForYou,
  _ as Menu_Section_Recommendations_DiscoveryQueue_ActionButton,
  _ as Menu_Section_Recommendations_DiscoveryQueue_Description,
  _ as Menu_Section_Recommendations_DiscoveryQueue_Title,
  _ as Menu_Section_Recommendations_InteractiveRecommender,
  _ as Menu_Section_Recommendations_InteractiveRecommender_ActionButton,
  _ as Menu_Section_Recommendations_InteractiveRecommender_Description,
  _ as Menu_Section_Recommendations_New,
  _ as Menu_Section_Recommendations_NewReleasesQueue,
  _ as Menu_Section_Recommendations_PersonalCalendar,
  _ as Menu_Section_Recommendations_PersonalCalendar_ActionButton,
  _ as Menu_Section_Recommendations_PersonalCalendar_Description,
  _ as Menu_Section_Recommendations_PopularAmongFriends,
  _ as Menu_Section_Recommendations_SteamCurators,
  _ as Menu_Section_SpecialSections,
  _ as Menu_Section_SpecialSections_DLCForYou,
  _ as Menu_Section_SpecialSections_NextFest,
  _ as Menu_Section_SpecialSections_SaleEvents,
  _ as Menu_Section_SpecialSections_SteamAwards,
  _ as Menu_Section_SpecialSections_SteamLabs,
  _ as Menu_Section_SpecialSections_SteamReplay,
  _ as Menu_Section_WaysToPlay,
  _ as Menu_TopSellers,
  _ as Menu_VR,
  _ as Menu_Wishlist,
  _ as NewBadge,
  _ as PersonalCalendar_EmptyDay,
  _ as PersonalCalendar_Explore,
  _ as PersonalCalendar_Full,
  _ as PersonalCalendar_More,
  _ as PersonalCalendar_Subtitle,
  _ as PersonalCalendar_Title,
  _ as PlayGameButton_PlayNow,
  _ as Price_Free,
  _ as Price_History_Current_Low_Price_Ttip,
  _ as Price_History_Current_Price,
  _ as Price_History_Lowest_Previous_30,
  _ as Price_History_Normal_Price,
  _ as Price_History_Recent_Low_Price,
  _ as Price_History_Recent_Low_Price_Ttip,
  _ as SignInToAddToLibrary_Tooltip,
  _ as Time_Today,
  _ as Wishlist_Categories_Dialog_Add,
  _ as Wishlist_Categories_Dialog_Advanced,
  _ as Wishlist_Categories_Dialog_Search,
  _ as Wishlist_Categories_Max_Per_App_Reached,
  _ as Wishlist_Categories_None,
  _ as Wishlist_Categories_Suggested_Birthday,
  _ as Wishlist_Categories_Suggested_Discount,
  _ as Wishlist_Categories_Suggested_Recommended,
  _ as Wishlist_Controls_Categories_All,
  _ as Wishlist_Controls_Categories_Filter_Tooltip,
  _ as Wishlist_Controls_Categories_Header,
  _ as Wishlist_Controls_Categories_Header_Current,
  _ as Wishlist_Controls_Categories_Header_Other,
  _ as Wishlist_Controls_Categories_Header_Suggested,
  _ as Wishlist_Controls_Categories_Manage,
  _ as Wishlist_Controls_Categories_Manageitem,
  _ as Wishlist_Controls_Categories_Remove_Tooltip,
  _ as Wishlist_Controls_Categories_Uncategorized,
  _ as Wishlist_Gamepad_Add_Category,
  _ as Wishlist_Gamepad_Filter_Category,
  _ as Wishlist_Gamepad_Filter_Clear_Category,
  _ as Wishlist_Gamepad_Removecategory,
  _ as default,
  _ as language,
  _ as review_summary_reviewrate,
  _ as review_summary_reviewrate_language_specific,
  _ as store_ui_dummy,
};
