var _ = `Todos los lotes que contienen:`,
  _ = `Ordenar por:`,
  _ = `Popularidad`,
  _ = `Precio`,
  _ = `Descuento del lote`,
  _ = `Nombre`,
  _ = `Recomendados`,
  _ = `Tus lotes completos`,
  _ = `Todo el contenido de estos lotes está en tu biblioteca`,
  _ = `Lotes tipo «Completar la colección»`,
  _ = `Compra los títulos que aún no están en tu biblioteca para completar el lote`,
  _ = `Lotes tipo «Debe comprarse en conjunto»`,
  _ = `Incluye todos los artículos reunidos en un solo lote y debe comprarse como un conjunto completo`,
  _ = `© %1$s Valve Corporation. Todos los derechos reservados. Todas las marcas registradas pertenecen a sus respectivos dueños en EE.\xA0UU. y otros países.`,
  _ = `Todos los precios incluyen IVA (donde sea aplicable).`,
  _ = `Política de Privacidad`,
  _ = `Información legal`,
  _ = `Accesibilidad`,
  _ = `Acuerdo de Suscriptor a Steam`,
  _ = `Reembolsos`,
  _ = `Cookies`,
  _ = `Acerca de Valve`,
  _ = `Soluciones empresariales`,
  _ = `Reciclaje`,
  _ = `Steamworks`,
  _ = `Motor Source`,
  _ = `Empleos`,
  _ = `Tarjetas regalo`,
  _ = `Distribución de Steam`,
  _ = `Soporte`,
  _ = `Lista de deseados de %1$s`,
  _ = `LISTA DE DESEADOS DE\xA0%1$s`,
  _ = `Carro (%1$s)`,
  _ = `Ver carro`,
  _ = `Lista de deseados (%1$s)`,
  _ = `Opciones`,
  _ = `Ordenar por: %1$s`,
  _ = `Crear un enlace para compartir`,
  _ = `Tu clasificación`,
  _ = `Orden de clasificación`,
  _ = `Lo más vendido`,
  _ = `Fecha de lanzamiento`,
  _ = `Fecha de adición`,
  _ = `Puntuación de reseñas`,
  _ = `Precio`,
  _ = `Nombre`,
  _ = `Descuento`,
  _ = `Enlace para compartir`,
  _ = `Anular todos los enlaces`,
  _ = `¡Enlaces anulados!`,
  _ = `No se ha podido generar el enlace para compartir (error %1$s)`,
  _ = `Cualquier persona con este enlace podrá ver tu lista de deseados con los filtros actuales, sean cuales sean los ajustes de visibilidad de tu perfil. No podrá cambiar los filtros.`,
  _ = `Vista`,
  _ = `Expandida`,
  _ = `Compacta`,
  _ = `Plataforma`,
  _ = `Cualquier SO`,
  _ = `macOS`,
  _ = `SteamOS + Linux`,
  _ = `Tipo`,
  _ = `Juegos`,
  _ = `Software`,
  _ = `DLC`,
  _ = `Vídeos`,
  _ = `Precio`,
  _ = `Descuento`,
  _ = `Todos los artículos de la lista`,
  _ = `Todos los artículos con descuento`,
  _ = `%1$s\xA0% o más`,
  _ = `Cualquier precio`,
  _ = `Por debajo de %1$s`,
  _ = `Gratuitos`,
  _ = `Excluir`,
  _ = `Artículos relacionados`,
  _ = `Acceso anticipado`,
  _ = `Este título está actualmente en acceso anticipado`,
  _ = `Prelanzamiento`,
  _ = `Solo RV`,
  _ = `Demo disponible`,
  _ = `Filtrar tu lista de deseados por artículos con demos`,
  _ = `Compatibilidad con Deck`,
  _ = `Verificados`,
  _ = `Jugables`,
  _ = `Etiqueta`,
  _ = `Filtrar tu lista de deseados por artículos con esta etiqueta`,
  _ = `Etiquetas de usuarios:`,
  _ = `%1$s: %2$s`,
  _ = `Categoría`,
  _ = `Categorías:`,
  _ = `<1>Categorías:</1> <2>%1$s</2>`,
  _ = `Añadir una categoría`,
  _ = `Gestión avanzada de categorías`,
  _ = `SELECCIONA UNA CATEGORÍA PARA EDITARLA`,
  _ = `NOMBRE DE LA CATEGORÍA`,
  _ = `Cambiar nombre`,
  _ = `Ya tienes una categoría con ese nombre`,
  _ = `Se ha producido un error al cambiar el nombre de esta categoría (código: %1$s)`,
  _ = `No hay artículos en la lista de deseados que coincidan con tu búsqueda.`,
  _ = `Todas`,
  _ = `Ninguna`,
  _ = `Mostrando los primeros %1$s de %2$s\xA0artículos. Utiliza la búsqueda para acortar la lista.`,
  _ = `No se ha podido actualizar %1$s\xA0artículo`,
  _ = `No se han podido actualizar %1$s\xA0artículos`,
  _ = `Pendiente`,
  _ = `Adiciones: %1$s`,
  _ = `Eliminaciones: %1$s`,
  _ = `Revertir`,
  _ = `Aplicar cambios`,
  _ = `AÑADIR/ELIMINAR CATEGORÍA`,
  _ = `%1$s\xA0ARTÍCULO`,
  _ = `%1$s\xA0ARTÍCULOS`,
  _ = `Resultados de búsqueda:`,
  _ = `%1$s\xA0artículo cuyo nombre contiene «%2$s»`,
  _ = `%1$s\xA0artículos con nombres que contienen «%2$s»`,
  _ = `%1$s\xA0artículo con la categoría %2$s`,
  _ = `%1$s\xA0artículos con la categoría %2$s`,
  _ = `%1$s\xA0artículo con categorías que contienen «%2$s»`,
  _ = `%1$s\xA0artículos con categorías que contienen «%2$s»`,
  _ = `%1$s\xA0artículo con la etiqueta «%2$s»`,
  _ = `%1$s\xA0artículos con la etiqueta «%2$s»`,
  _ = `%1$s\xA0artículo con etiquetas que contienen «%2$s»`,
  _ = `%1$s\xA0artículos con etiquetas que contienen «%2$s»`,
  _ = `Buscar por nombre o etiqueta`,
  _ = `Busca por nombre, etiqueta o categoría`,
  _ = `Reseñas generales:`,
  _ = `Reseñas en %1$s:`,
  _ = `Fecha de lanzamiento:`,
  _ = `Añadido el %1$s`,
  _ = `quitar`,
  _ = `Elimina este artículo de la lista de deseados`,
  _ = `(artículo no disponible)`,
  _ = `Este artículo no está disponible en tu región.`,
  _ = `Este artículo ya no está disponible.`,
  _ = `El contenido para adultos no está permitido en tu país para menores de 18\xA0años. Valve está obligada a verificar que tienes 18\xA0años o más antes de que puedas acceder a contenido para adultos.`,
  _ = `Según la Ley de Seguridad en Línea («Online Safety Act») del Reino\xA0Unido, Valve está obligada a verificar que tienes 18\xA0años o más antes de que puedas acceder a contenido sexual para adultos.`,
  _ = `Añadir tarjeta de crédito`,
  _ = `Tu lista de deseados está vacía.`,
  _ = `Llena tu lista de deseados navegando por la tienda y utilizando el botón «Añadir a tu lista de deseados».`,
  _ = `Más información acerca de las listas de deseados de Steam`,
  _ = `Inicia sesión para ver tu lista de deseados`,
  _ = `Esta lista de deseados está vacía.`,
  _ = `No coincide ningún artículo.`,
  _ = `Hay %1$s\xA0artículos en esta lista de deseados, pero ninguno coincide con los filtros de tu lista de deseados o tus preferencias de la tienda.`,
  _ = `Hay %1$s\xA0artículos en esta lista de deseados, pero ninguno coincide con los filtros de tu lista de deseados o tus <1>preferencias de la tienda</1>.`,
  _ = `Reordenar`,
  _ = `Cancelar reordenación`,
  _ = `Colocar aquí`,
  _ = `Opciones`,
  _ = `Eliminar`,
  _ = `Ver página de la tienda`,
  _ = `Lista de deseados - Error`,
  _ = `Error`,
  _ = `Error desconocido`,
  _ = `No se ha encontrado el perfil`,
  _ = `No se ha podido cargar la lista de deseados del usuario.`,
  _ = `Este enlace para compartir la lista de deseados no es válido o ha caducado.`,
  _ = `Juegos de las notificaciones de la lista de deseados`,
  _ = `Cuenta de %1$s`,
  _ = `Cuenta - Error`,
  _ = `Cuenta`,
  _ = `Inicio`,
  _ = `Detalles de la cuenta`,
  _ = `Preferencias de la tienda`,
  _ = `Preferencias de idioma`,
  _ = `Ajustes de notificaciones`,
  _ = `Dispositivos`,
  _ = `Seguridad y dispositivos`,
  _ = `Dispositivos autorizados (vídeo)`,
  _ = `Dispositivos de juego móviles`,
  _ = `Pruebas de juego`,
  _ = `Gestión de grupos familiares`,
  _ = `Datos y navegación`,
  _ = `RV`,
  _ = `Perfectos para Deck`,
  _ = `Juego nativo en Frame`,
  _ = `Página principal`,
  _ = `Categorías`,
  _ = `Buscar en Steam`,
  _ = `No fue posible cargar los datos de acceso restringido.`,
  _ = `Invitaciones a pruebas de juego de Steam`,
  _ = `Aceptar invitación`,
  _ = `Rechazar invitación`,
  _ = `¡Te han invitado a participar en una prueba de juego de Steam!`,
  _ = `¡Te han invitado a un lanzamiento limitado!`,
  _ = `¡%1$s te ha invitado a participar en una prueba de juego de Steam!`,
  _ = `¡%1$s te ha invitado a un lanzamiento limitado!`,
  _ = `No tienes invitaciones a pruebas de juego de Steam o lanzamientos limitados esperando respuesta.`,
  _ = `¡Te damos la bienvenida a la prueba de juego! Ya puedes instalar «%1$s» en la biblioteca.`,
  _ = `¡Te damos la bienvenida al lanzamiento limitado! Ya puedes instalar «%1$s» en la biblioteca.`,
  _ = `¡Te damos la bienvenida a la prueba de juego! «%1$s» no está activo actualmente. Mantente al tanto de los futuros planes de lanzamiento del desarrollador.`,
  _ = `Ver biblioteca`,
  _ = `¿Qué son las pruebas de juego de Steam?`,
  _ = `Las pruebas de juego de Steam sirven para probar juegos que aún están en desarrollo. Cuando aceptas una invitación o solicitas acceso al desarrollador y este te lo concede, el juego se añade a tu biblioteca automáticamente.`,
  _ = `Consulta la información del desarrollador acerca de cada prueba de juego. Participar en una prueba de juego de Steam no garantiza el acceso al juego cuando se lance.`,
  _ = `Invitaciones ignoradas a pruebas de juego de Steam`,
  _ = `Has rechazado las invitaciones a las pruebas de juego o los lanzamientos limitados de los siguientes títulos. No recibirás más invitaciones hasta que las elimines de esta lista.`,
  _ = `Eliminar`,
  _ = `Cancelar`,
  _ = `Enviar`,
  _ = `Esta es la última invitación disponible a esta prueba de juego.`,
  _ = `Esta es la última invitación disponible a este lanzamiento limitado.`,
  _ = `Enviando una invitación a:`,
  _ = `Invitando a %1$s...`,
  _ = `¡Has invitado a %1$s! La invitación aparecerá en sus %2$s\xA0notificaciones.`,
  _ = `No se puede invitar a %1$s. Puede que ya haya recibido una invitación o que el juego no esté disponible en su región.`,
  _ = `Historial de invitaciones enviadas`,
  _ = `Invitaciones recientes a pruebas de juego y lanzamientos limitados que enviaste a tus amigos.`,
  _ = `Invitaste a %1$s a «%2$s»`,
  _ = `Participación en pruebas de juego de Steam`,
  _ = `No te has unido a ninguna prueba de juego de Steam o lanzamiento limitado en curso.`,
  _ = `Tienes invitaciones disponibles`,
  _ = `Tienes %1$s\xA0invitación disponible`,
  _ = `Tienes %1$s\xA0invitaciones disponibles`,
  _ = `Puedes invitar a tus amigos a esta prueba de juego.`,
  _ = `El número de invitaciones disponibles puede cambiar a medida que se unan más jugadores.`,
  _ = `Es posible que haya más información, como el calendario y el contenido incluido, en la %1$s o el %2$s.`,
  _ = `página de la tienda`,
  _ = `centro de noticias`,
  _ = `Esta prueba de juego no está activa actualmente.`,
  _ = `Has utilizado todas tus invitaciones a amigos.`,
  _ = `Invitar amigos`,
  _ = `Selecciona el destinatario de la invitación`,
  _ = `Buscar por nombre de amigo...`,
  _ = `No se han podido cargar tus amigos.`,
  _ = `No puedes invitar a algunos amigos porque no han pasado 30\xA0días desde que os hicisteis amigos, ya tienen acceso al juego o no cumplen los requisitos por algún otro motivo.`,
  _ = `No puedes invitar a algunos amigos porque ya tienen acceso al juego o no cumplen los requisitos por algún otro motivo.`,
  _ = `Lanzamiento limitado`,
  _ = `Puedes invitar a tus amigos a este lanzamiento limitado.`,
  _ = `El número de jugadores de «%1$s» está aumentando poco a poco durante el lanzamiento limitado inicial. Puede que haya más detalles disponibles en la %2$s o en el %3$s.`,
  _ = `¿Qué es el lanzamiento limitado?`,
  _ = `Algunos juegos gratuitos utilizan el lanzamiento limitado para aumentar paulatinamente el número de jugadores durante el lanzamiento inicial del juego. Si aceptas una invitación o si el desarrollador aprueba tu solicitud de acceso, el juego se añadirá a tu biblioteca y podrás empezar a jugar inmediatamente.`,
  _ = `Mapa del sitio de la tienda de Steam`,
  _ = `Página principal`,
  _ = `Mi cuenta`,
  _ = `Detalles de mi cuenta`,
  _ = `Mis preferencias de la tienda`,
  _ = `Gestión de grupos familiares`,
  _ = `Seguridad y dispositivos`,
  _ = `Preferencias de idioma`,
  _ = `Cookies y navegación`,
  _ = `Ajustes de notificaciones`,
  _ = `Carro`,
  _ = `Carro (%1$s)`,
  _ = `Lista de deseados`,
  _ = `Lista de deseados (%1$s)`,
  _ = `Juegos y software que sigues`,
  _ = `Juegos y software que sigues (%1$s)`,
  _ = `Gráficos y listas`,
  _ = `Lo más vendido`,
  _ = `Lo más popular`,
  _ = `Nuevos lanzamientos`,
  _ = `Próximos lanzamientos`,
  _ = `Free to Play`,
  _ = `Gráficos de Steam`,
  _ = `En oferta`,
  _ = `Recomendaciones`,
  _ = `Descubrimientos`,
  _ = `Lista de novedades`,
  _ = `Recomendaciones de la comunidad`,
  _ = `Recomendador interactivo`,
  _ = `Populares entre tus amigos`,
  _ = `Mentores de Steam`,
  _ = `DLC que te recomendamos`,
  _ = `Hardware`,
  _ = `Steam\xA0Deck`,
  _ = `Estación de conexión de Steam\xA0Deck`,
  _ = `Hardware de RV`,
  _ = `Juegos de RV`,
  _ = `Juegos perfectos para Deck`,
  _ = `Juegos compatibles con mandos`,
  _ = `Formas de jugar`,
  _ = `Noticias y actualizaciones`,
  _ = `Juegos actualizados recientemente`,
  _ = `Juegos en tu biblioteca actualizados recientemente`,
  _ = `Tus próximos eventos`,
  _ = `Noticias destacadas`,
  _ = `Noticias y actualizaciones oficiales de Steam`,
  _ = `Promociones y eventos`,
  _ = `Ofertas especiales`,
  _ = `Eventos de rebajas`,
  _ = `Resumen del año en Steam`,
  _ = `Next\xA0Fest de Steam`,
  _ = `Los Premios\xA0Steam`,
  _ = `Secciones especiales`,
  _ = `Tienda de puntos de Steam`,
  _ = `Tarjetas regalo`,
  _ = `Géneros`,
  _ = `Temáticas`,
  _ = `Has realizado demasiadas solicitudes recientemente. Espera e inténtalo de nuevo más tarde.`,
  _ = `Discusiones generales`,
  _ = `Mensajes denunciados`,
  _ = `Discusiones del Workshop`,
  _ = `Intercambios`,
  _ = `Eventos y anuncios`,
  _ = `Recomendador interactivo`,
  _ = `A jugadores como tú les gusta...`,
  _ = `Explora las recomendaciones personalizadas que nuestro sistema de aprendizaje automático realiza para ti basándose en tu historial de juego en Steam comparándolo con millones de jugadores. Personaliza tus resultados con los controles deslizantes y los filtros, y guarda tu configuración para que Steam recuerde lo que estás buscando.`,
  _ = `Tu tiempo de juego relevante`,
  _ = `%1$s\xA0juegos`,
  _ = `los %1$s\xA0juegos más populares`,
  _ = `juegos recientes`,
  _ = `%1$s\xA0horas`,
  _ = `%1$s\xA0horas en total`,
  _ = `última sesión: %1$s`,
  _ = `última sesión: hace más de 10\xA0años`,
  _ = `Incluir`,
  _ = `Excluir`,
  _ = `Ponderados por popularidad`,
  _ = `populares`,
  _ = `nicho`,
  _ = `Filtrar por año`,
  _ = `más antiguos`,
  _ = `más nuevos`,
  _ = `Desde el principio`,
  _ = `5\xA0años`,
  _ = `3\xA0años`,
  _ = `2\xA0años`,
  _ = `1\xA0año`,
  _ = `6\xA0meses`,
  _ = `Recomendaciones para ti`,
  _ = `Publicado el %1$s`,
  _ = `En tu lista de deseados`,
  _ = `Añadir al carro`,
  _ = `Añadir a la lista de deseados`,
  _ = `Free to Play`,
  _ = `Escribe una etiqueta`,
  _ = `Añadir filtros de etiquetas`,
  _ = `Añadir exclusiones de etiquetas`,
  _ = `Excluir juegos de la lista de deseados`,
  _ = `Solo juegos con descuento`,
  _ = `Lanzados el último mes`,
  _ = `Lanzados en los últimos 7\xA0días`,
  _ = `Próximos lanzamientos`,
  _ = `Tu calendario personal`,
  _ = `Una lista personalizada de %1$s\xA0juegos que se han lanzado recientemente o que estarán disponibles pronto`,
  _ = `Selector de etiquetas`,
  _ = `Filtrar por etiqueta...`,
  _ = `Ocultar los juegos que ya tienes`,
  _ = `Los juegos que salgan del acceso anticipado seguirán mostrándose`,
  _ = `Ocultar juegos en acceso anticipado`,
  _ = `Mostrar solo los juegos de la lista de deseados`,
  _ = `Número de juegos`,
  _ = `Calendario compacto`,
  _ = `Reemplazo opcional`,
  _ = `Id. de cuenta`,
  _ = `Lista completa (%1$s)`,
  _ = `Inicia sesión para ver sugerencias personalizadas.`,
  _ = `Expandir todo`,
  _ = `Experimento núm.\xA0016 de los Laboratorios de Steam | Obtén más información y envía tus comentarios <1>aquí</1>`,
  _ = `Juegos de la lista de deseados`,
  _ = `Mostrar`,
  _ = `Ocultar`,
  _ = `Solo`,
  _ = `Desactivado (demasiados juegos en la lista de deseados)`,
  _ = `Error al cargar el calendario. Por favor, inténtalo de nuevo.`,
  _ = `Lista de lotes de «%1$s»`,
  _ = `Lista de lotes`,
  _ = `Todos los lotes que contienen el juego «%1$s».`,
  _ = `Verificado en Steam\xA0Deck`,
  _ = `«%1$s»\xA0está verificado en Steam\xA0Deck`,
  _ = `Error del sitio`,
  _ = `¡UY, LO SENTIMOS!`,
  _ = `Se ha producido un error mientras se procesaba la solicitud.`,
  _ = `El número de espacios debe ser mayor que 0.`,
  _ = `El dominio de correo electrónico ya se está utilizando para otro medio.`,
  _ = `No se pudo añadir el medio.`,
  _ = `El dominio de correo electrónico no puede estar vacío.`,
  _ = `El dominio de correo electrónico no es válido.`,
  _ = `La cuenta ya está en un medio de comunicación.`,
  _ = `No se pudo añadir la cuenta al medio de comunicación.`,
  _ = `Dominio de correo electrónico`,
  _ = `Número de espacios`,
  _ = `Añadir`,
  _ = `Añadir medio:`,
  _ = `%1$s (espacios utilizados: %2$s de %3$s)`,
  _ = `Mostrar historial`,
  _ = `Historial de %1$s`,
  _ = `Clave para la prensa otorgada a %1$s por %2$s`,
  _ = `Clave para la prensa revocada a %1$s por %2$s`,
  _ = `Medio de comunicación creado por %1$s`,
  _ = `Medio de comunicación actualizado por %1$s`,
  _ = `Dominio de correo electrónico configurado como %1$s`,
  _ = `Número de espacios establecido en %1$s`,
  _ = `Medio de comunicación eliminado por %1$s`,
  _ = `Medio de comunicación restaurado por %1$s`,
  _ = `%1$s ha preparado provisionalmente el medio de comunicación`,
  _ = `%1$s ha aplicado los cambios provisionales`,
  _ = `%2$s ha preparado la incorporación del usuario\xA0%1$s`,
  _ = `%2$s ha preparado la eliminación del usuario\xA0%1$s`,
  _ = `el Soporte`,
  _ = `Beneficiario`,
  _ = `Fecha de concesión`,
  _ = `¿Es administrador del grupo?`,
  _ = `Id. de Steam para añadir`,
  _ = `Aceptar`,
  _ = `Cancelar`,
  _ = `Sí`,
  _ = `No`,
  _ = `Todos`,
  _ = `Activos`,
  _ = `Eliminados`,
  _ = `Vacíos`,
  _ = `Sin administradores en el medio`,
  _ = `Medio de comunicación:`,
  _ = `Código de amigo:`,
  _ = `Renunciar a tu clave para la prensa: `,
  _ = `¿Realmente deseas renunciar a tu clave para la prensa?`,
  _ = `Historial de medios`,
  _ = `Añadir miembro`,
  _ = `Mostrar historial`,
  _ = `Cuenta`,
  _ = `No se ha encontrado el tráiler`,
  _ = `Tráiler`,
  _ = `Microtráiler`,
  _ = `Se produjo un error al guardar la configuración de las notificaciones`,
  _ = `Se produjo un error al cargar la configuración de las notificaciones`,
  _ = `Este enlace para cancelar la suscripción no es válido o ha caducado. Inicia sesión y visita <1>Ajustes de notificaciones</1>.`,
  _ = `La fuente se activa automáticamente si la notificación visual del cliente o la aplicación móvil están activadas.`,
  _ = `Notificar solo a %1$s sobre estas categorías de la lista de deseados`,
  _ = `Estimador de velocidad de fotogramas`,
  _ = `Selecciona una aplicación y una configuración de PC para obtener un gráfico con las velocidades de fotogramas estimadas, basadas en las velocidades de fotogramas de otros usuarios de Steam.`,
  _ = `CPU`,
  _ = `RAM del sistema`,
  _ = `GPU`,
  _ = `Hardware guardado`,
  _ = `No tienes ningún hardware guardado.`,
  _ = `Selecciona tu hardware para ver una estimación de la velocidad de fotogramas.`,
  _ = `<Ninguno seleccionado>`,
  _ = `Puedes añadir tu hardware actual si estás viendo esto desde el cliente de Steam.`,
  _ = `Añadir hardware guardado`,
  _ = `Añadir hardware guardado (fuera del cliente)`,
  _ = `Si deseas aportar datos anónimos al estimador de velocidad de fotogramas y ayudar a que sea más útil para todos, haz clic en el enlace de abajo para acceder a tus preferencias y activa la opción correspondiente en la sección «Recopilación de datos».`,
  _ = `Preferencias`,
  _ = `FPS`,
  _ = `Buscar un juego`,
  _ = `Selecciona una CPU`,
  _ = `Selecciona una GPU`,
  _ = `Número de entradas de entrenamiento para el mismo juego`,
  _ = `Número de entradas de entrenamiento para la misma CPU`,
  _ = `Número de entradas de entrenamiento para la misma GPU`,
  _ = `Desconocido`,
  _ = `Enviar una tarjeta regalo`,
  _ = ``,
  _ = {
    BundleList_SubTitle: _,
    BundleList_SortBy: _,
    BundleList_SortBy_Popular: _,
    BundleList_SortBy_Price: _,
    BundleList_SortBy_Discount: _,
    BundleList_SortBy_Name: _,
    BundleList_SortBy_Recommend: _,
    BundleList_AllInLibrary: _,
    BundleList_AllInLibrarySubtitle: _,
    BundleList_CompleteTheSet: _,
    BundleList_CompleteTheSetSubtitle: _,
    BundleList_MustPurchaseAsSet: _,
    BundleList_MustPurchaseAsSetSubtitle: _,
    footer_legal_notice: _,
    footer_vat_included: _,
    footer_privacy_policy: _,
    footer_legal: _,
    footer_accessibility: _,
    footer_ssa: _,
    footer_refunds: _,
    footer_cookies: _,
    footer_about_valve: _,
    footer_business_solutions: _,
    footer_recycling: _,
    footer_steamworks: _,
    footer_source_engine: _,
    footer_jobs: _,
    footer_walletcode: _,
    footer_steam_distribution: _,
    footer_nav_help_support: _,
    wishlist_title: _,
    wishlist_header: _,
    cart_count: _,
    cart_view_cart: _,
    wishlist_count: _,
    wishlist_options_button: _,
    wishlist_sortby_button: _,
    wishlist_share_tooltip: _,
    wishlist_controls_sortby_order: _,
    wishlist_controls_sortby_their_order: _,
    wishlist_controls_sortby_topsellers: _,
    wishlist_controls_sortby_releasedate: _,
    wishlist_controls_sortby_dateadded: _,
    wishlist_controls_sortby_reviews: _,
    wishlist_controls_sortby_price: _,
    wishlist_controls_sortby_name: _,
    wishlist_controls_sortby_discount: _,
    wishlist_controls_share_dialog_title: _,
    wishlist_controls_share_revokeall: _,
    wishlist_controls_share_revokeall_success: _,
    wishlist_controls_share_generation_failure: _,
    wishlist_controls_share_description: _,
    wishlist_controls_options_category_view: _,
    wishlist_controls_options_view_expanded: _,
    wishlist_controls_options_view_compact: _,
    wishlist_controls_options_category_platform: _,
    wishlist_controls_options_platform_all: _,
    wishlist_controls_options_platform_mac: _,
    wishlist_controls_options_platform_linux: _,
    wishlist_controls_options_category_type: _,
    wishlist_controls_options_type_game: _,
    wishlist_controls_options_type_application: _,
    wishlist_controls_options_type_dlc: `DLC`,
    wishlist_controls_options_type_video: _,
    wishlist_controls_options_category_price: _,
    wishlist_controls_options_category_discount: _,
    wishlist_controls_options_discount_all: _,
    wishlist_controls_options_discount_any: _,
    wishlist_controls_options_discount_or_more: _,
    wishlist_controls_options_price_any: _,
    wishlist_controls_options_price_max_price: _,
    wishlist_controls_options_price_free: _,
    wishlist_controls_options_category_exclude: _,
    wishlist_controls_options_category_related: _,
    genre_early_access: _,
    wishlist_controls_early_access_tooltip: _,
    category_prerelease: _,
    wishlist_controls_options_exclude_vr: _,
    wishlist_controls_demo_available: _,
    wishlist_controls_demo_available_tooltip: _,
    wishlist_controls_options_category_deck: _,
    wishlist_controls_options_deck_verified: _,
    wishlist_controls_options_deck_playable: _,
    wishlist_controls_options_category_tag: _,
    wishlist_controls_tag_description: _,
    wishlist_controls_tags_header: _,
    wishlist_controls_filter_tag_label: _,
    wishlist_controls_options_category_category: _,
    wishlist_controls_categories_header_anonymous: _,
    wishlist_controls_categories_multiselect_label: _,
    wishlist_controls_categories_add: _,
    wishlist_categories_advanced_title: _,
    wishlist_categories_advanced_select: _,
    wishlist_categories_advanced_rename_label: _,
    wishlist_categories_advanced_rename_save: _,
    wishlist_categories_advanced_rename_duplicate: _,
    wishlist_categories_advanced_rename_failed: _,
    wishlist_categories_advanced_no_items: _,
    wishlist_categories_advanced_select_all: _,
    wishlist_categories_advanced_select_none: _,
    wishlist_categories_advanced_showing: _,
    wishlist_categories_advanced_failed_items: _,
    wishlist_categories_advanced_failed_items_Plural: _,
    wishlist_categories_advanced_pending: _,
    wishlist_categories_advanced_pending_adds: _,
    wishlist_categories_advanced_pending_removals: _,
    wishlist_categories_advanced_revert: _,
    wishlist_categories_advanced_apply: _,
    wishlist_categories_advanced_addremove_title: _,
    wishlist_displayed_item_count: _,
    wishlist_displayed_item_count_Plural: _,
    wishlist_filter_results: _,
    wishlist_filter_matches_items: _,
    wishlist_filter_matches_items_Plural: _,
    wishlist_filter_matches_category: _,
    wishlist_filter_matches_category_Plural: _,
    wishlist_filter_matches_categories: _,
    wishlist_filter_matches_categories_Plural: _,
    wishlist_filter_matches_tag: _,
    wishlist_filter_matches_tag_Plural: _,
    wishlist_filter_matches_tags: _,
    wishlist_filter_matches_tags_Plural: _,
    wishlist_search: _,
    wishlist_search_all: _,
    wishlist_item_overallreviews: _,
    wishlist_item_languagespecific_reviews: _,
    wishlist_item_releasedate: _,
    wishlist_item_addedon_date: _,
    wishlist_item_remove: _,
    wishlist_item_remove_tooltip: _,
    wishlist_item_unavailable_title: _,
    wishlist_item_unavailable_region: _,
    wishlist_item_unavailable_retired: _,
    mature_content_requires_creditcard: _,
    mature_content_requires_creditcard_gb: _,
    wishlist_item_add_credit_card: _,
    wishlist_your_wishlist_empty: _,
    wishlist_browse_the_store: _,
    wishlist_learn_more_button: _,
    wishlist_sign_in_to_see_your_wishlist: _,
    wishlist_others_wishlist_empty: _,
    wishlist_no_items_matching_filters: _,
    wishlist_x_items_on_wishlist_but_none_match: _,
    wishlist_x_items_on_wishlist_but_none_match_prefs: _,
    wishlist_gamepaddragdrop_reorderaction: _,
    wishlist_gamepaddragdrop_cancelreorder: _,
    wishlist_gamepaddragdrop_commitreorder: _,
    wishlist_gamepad_options: _,
    wishlist_gamepad_options_remove: _,
    wishlist_gamepad_visitstore: _,
    wishlist_errorpage_title: _,
    errorpage_error: _,
    errorpage_unknownerror: _,
    wishlist_error_profilenotfound: _,
    wishlist_error_wishlistunavailable: _,
    wishlist_error_invalidsharetoken: _,
    wishlist_filters_notification: _,
    youraccount_users_account: _,
    youraccount_errorpage_title: _,
    youraccount_account: _,
    m_home: _,
    global_menu_account_details: _,
    global_menu_account_preferences: _,
    global_menu_account_language_preferences: _,
    global_menu_account_notification_settings: _,
    global_menu_account_hardware_used: _,
    global_menu_account_security_devices: _,
    global_menu_account_video_authorized_devices: _,
    global_menu_account_mobile_game_devices: _,
    global_menu_account_gated_access_games: _,
    accountpreferences_familymanagement_header: _,
    CookiePreferences: _,
    global_menu_vr: `RV`,
    global_menu_greatondeck: _,
    global_menu_localplayonframe: _,
    store_tab_foryou_store_home: _,
    browse_categories: _,
    m_search_steam: _,
    playteststatus_error_dataunavailable: _,
    playtestinvites_title: _,
    playtestinvites_accept: _,
    playtestinvites_reject: _,
    playtestinvites_invitedescription_fromapp2: _,
    playtestinvites_invitedescription_fromapp_limitedlaunch: _,
    playtestinvites_invitedescription_fromuser2: _,
    playtestinvites_invitedescription_fromuser_limitedlaunch: _,
    playtestinvites_noinvites: _,
    playtestinvites_welcome: _,
    playtestinvites_welcome_limitedlaunch: _,
    playtestinvites_welcome_notplayable: _,
    playtestinvites_viewlibrary: _,
    playtestinvites_desc_title: _,
    playtestinvites_desc1: _,
    playtestinvites_desc2: _,
    playtestinvites_ignored_title: _,
    playtestinvites_ignored_desc: _,
    playtestinvites_ignored_remove: _,
    playtestinvites_sendinvite_cancel: _,
    playtestinvites_sendinvite_send: _,
    playtestinvites_sendinvite_lastinvite: _,
    playtestinvites_sendinvite_lastinvite_limitedlaunch: _,
    playtestinvites_sendinvite_confirm_desc: _,
    playtestinvites_sendinvite_pending: _,
    playtestinvites_sendinvite_success: _,
    playtestinvites_sendinvite_failure: _,
    playtestinvitehistory_title: _,
    playtestinvitehistory_desc: _,
    playtestinvitehistory_invite_detail: _,
    playteststatus_title: _,
    playteststatus_none: _,
    playteststatus_invites_available: _,
    playteststatus_invite_count: _,
    playteststatus_invite_count_plural: _,
    playteststatus_invite_count_tooltip: _,
    playteststatus_invite_count_tooltip2: _,
    playteststatus_details_moreinfo: _,
    playteststatus_details_moreinfo_storepage: _,
    playteststatus_details_moreinfo_newshub: _,
    playteststatus_details_notplayable: _,
    playteststatus_details_allinvitesused: _,
    playteststatus_invitefriends: _,
    playteststatus_invitefrienddialog_header: _,
    playteststatus_invitefrienddialog_search_placeholder: _,
    playteststatus_invitefrienddialog_loadingerror: _,
    playteststatus_invitefrienddialog_ineligiblefriends: _,
    playteststatus_invitefrienddialog_ineligiblefriends_purchaser: _,
    gatedaccess_limitedlaunch_badge: _,
    gatedaccess_limitedlaunch_invite_count_tooltip: _,
    gatedaccess_limitedlaunch_details_moreinfo: _,
    gatedaccess_limitedlaunch_desc_title: _,
    gatedaccess_limitedlaunch_desc: _,
    sitemap_title: _,
    sitemap_home: _,
    sitemap_section_account: _,
    sitemap_section_account_account_details: _,
    sitemap_section_account_store_preferences: _,
    sitemap_section_account_family_management: _,
    sitemap_section_account_security_and_devices: _,
    sitemap_section_account_language_preferences: _,
    sitemap_section_account_cookes_and_browsing: _,
    sitemap_section_account_notification_settings: _,
    sitemap_section_account_cart: _,
    sitemap_section_account_cart_with_count: _,
    sitemap_section_account_wishlist: _,
    sitemap_section_account_wishlist_with_count: _,
    sitemap_section_account_followed_games: _,
    sitemap_section_account_followed_games_with_count: _,
    sitemap_section_chartsandlists: _,
    sitemap_section_chartsandlists_top_sellers: _,
    sitemap_section_chartsandlists_most_played: _,
    sitemap_section_chartsandlists_new_releases: _,
    sitemap_section_chartsandlists_upcoming_releases: _,
    sitemap_section_chartsandlists_free_to_play: _,
    sitemap_section_chartsandlists_steam_charts: _,
    sitemap_section_chartsandlists_on_sale_now: _,
    sitemap_section_recommendations: _,
    sitemap_section_recommendations_discovery_queue: _,
    sitemap_section_recommendations_new_releases_queue: _,
    sitemap_section_recommendations_community_recommendations: _,
    sitemap_section_recommendations_interactive_recommender: _,
    sitemap_section_recommendations_popular_among_friends: _,
    sitemap_section_recommendations_steam_curators: _,
    sitemap_section_recommendations_dlc_for_you: _,
    sitemap_section_hardware: _,
    sitemap_section_hardware_steam_deck: _,
    sitemap_section_hardware_steam_deck_dock: _,
    sitemap_section_hardware_vr_hardware: _,
    sitemap_section_hardware_vr_games: _,
    sitemap_section_hardware_great_on_deck: _,
    sitemap_section_hardware_controller_friendly: _,
    sitemap_section_waystoplay: _,
    sitemap_section_newsupdates: _,
    sitemap_section_newsupdates_recently_updated: _,
    sitemap_section_newsupdates_your_recently_updated: _,
    sitemap_section_newsupdates_your_upcoming_events: _,
    sitemap_section_newsupdates_featured_news: _,
    sitemap_section_newsupdates_steam_official_news: _,
    sitemap_section_promosandevents: _,
    sitemap_section_promosandevents_special_offers: _,
    sitemap_section_promosandevents_sale_events: _,
    sitemap_section_promosandevents_steam_replay: _,
    sitemap_section_promosandevents_steam_next_fest: _,
    sitemap_section_promosandevents_steam_awards: _,
    sitemap_section_specialsections: _,
    sitemap_pointsshop: _,
    sitemap_giftcards: _,
    sitemap_genres: _,
    sitemap_themes: _,
    Error_RateLimited: _,
    Discussions_ForumName_General: _,
    Discussions_ForumName_ReportedPosts: _,
    Discussions_ForumName_Workshop: _,
    Discussions_ForumName_Trading: _,
    Discussions_ForumName_Events: _,
    ir_name: _,
    ir_header: _,
    ir_body: _,
    ir_playtime_header: _,
    ir_playtime_games: _,
    ir_playtime_topgames: _,
    ir_playtime_recentgames: _,
    ir_playtime_hours: _,
    ir_playtime_hourstotal: _,
    ir_playtime_lastplayed: _,
    ir_playtime_lastplayedmax: _,
    ir_playtime_unignore: _,
    ir_playtime_ignore: _,
    ir_popularity_title: _,
    ir_popularity_popular: _,
    ir_popularity_niche: _,
    ir_recency_title: _,
    ir_recency_older: _,
    ir_recency_newer: _,
    ir_filter_age_all: _,
    ir_filter_age_60: _,
    ir_filter_age_36: _,
    ir_filter_age_24: _,
    ir_filter_age_12: _,
    ir_filter_age_6: _,
    ir_recommendations_header: _,
    ir_release_date: _,
    ir_on_wishlist: _,
    ir_add_to_cart: _,
    ir_add_to_wishlist: _,
    ir_free_to_play: _,
    ir_tag_placeholder: _,
    ir_tag_filter: _,
    ir_tag_exclude: _,
    ir_no_wishlisted: _,
    ir_discounted_only: _,
    PersonalCalendar_LastMonthGames: _,
    PersonalCalendar_LastWeekGames: _,
    PersonalCalendar_Upcoming: _,
    PersonalCalendar_Title: _,
    PersonalCalendar_Description: _,
    PersonalCalendar_TagSelector: _,
    PersonalCalendar_TagSelector_Placeholder: _,
    PersonalCalendar_HideOwned: _,
    PersonalCalendar_HideEATooltip: _,
    PersonalCalendar_HideEarlyAccess: _,
    PersonalCalendar_ShowOnlyWishlisted: _,
    PersonalCalendar_ResultCountSelector: _,
    PersonalCalendar_CompactMode: _,
    PersonalCalendar_AccountPlaceholder: _,
    PersonalCalendar_Account: _,
    PersonalCalendar_ShowMore: _,
    PersonalCalendar_LoginPrompt: _,
    PersonalCalendar_ShowAll: _,
    PersonalCalendar_SteamLabs: _,
    PersonalCalendar_Wishlisted: _,
    PersonalCalendar_WishlistShow: _,
    PersonalCalendar_WishlistHide: _,
    PersonalCalendar_WishlistOnly: _,
    PersonalCalendar_IgnoringWishlists: _,
    PersonalCalendar_Error_Backend: _,
    BundleList_Title: _,
    BundleList_Title_Fallback: _,
    BundleList_Page: _,
    Verification_DeckOnly: _,
    Verification_DeckOnly_Desc: _,
    FatalErrorPage_Title: _,
    FatalErrorPage_Header: _,
    FatalErrorPage_Message: _,
    pressoutlets_error_slots_gt_zero: _,
    pressoutlets_error_domain_used: _,
    pressoutlets_error_adding_outlet: _,
    pressoutlets_error_domain_empty: _,
    pressoutlets_error_invalid_domain: _,
    pressoutlets_error_already_owned: _,
    pressoutlets_error_generic_add_error: _,
    pressoutlets_email_domain_label: _,
    pressoutlets_slots_label: _,
    pressoutlets_button_add: _,
    pressoutlets_label_add_outlet: _,
    pressoutlets_outlet_header: _,
    pressoutlets_show_history: _,
    pressoutlets_history_title: _,
    pressoutlets_action_granted: _,
    pressoutlets_action_removed: _,
    pressoutlets_action_created: _,
    pressoutlets_action_updated: _,
    pressoutlets_action_updated_domain_changed: _,
    pressoutlets_action_updated_slots_changed: _,
    pressoutlets_action_deleted: _,
    pressoutlets_action_undeleted: _,
    pressoutlets_action_enterstaging: _,
    pressoutlets_action_exitstaging: _,
    pressoutlets_action_stagedadd: _,
    pressoutlets_action_stageddelete: _,
    pressoutlets_action_by_support: _,
    pressoutlets_header_grantee: _,
    pressoutlets_header_granted_at: _,
    pressoutlets_header_is_group_admin: _,
    pressoutlets_steamid_to_add: _,
    pressoutlets_button_ok: _,
    pressoutlets_button_cancel: _,
    pressoutlets_is_group_admin: `Sí`,
    pressoutlets_is_not_group_admin: `No`,
    pressoutlets_filter_all: _,
    pressoutlets_filter_active: _,
    pressoutlets_filter_deleted: _,
    pressoutlets_filter_empty: _,
    pressoutlets_filter_noadmins: _,
    pressoutlets_outlet_header_prefix: _,
    pressoutlets_friendcode: _,
    pressoutlets_resign_your_key: _,
    pressoutlets_resign_your_key_title: _,
    pressoutlets_history_header: _,
    pressoutlets_button_add_member: _,
    pressoutlets_button_show_history: _,
    pressoutlets_header_account: _,
    trailerassets_invalidfile: _,
    trailerassets_trailer: _,
    trailerassets_microtrailer: _,
    account_notification_settings_error_saving: _,
    account_notification_settings_error_loading: _,
    account_notification_settings_error_invalidoptouttoken: _,
    account_notification_settings_feed_disabled: _,
    account_notification_settings_wishlist_categories_persona: _,
    framerate_title: _,
    framerate_subheader: _,
    framerate_cpu: `CPU`,
    framerate_ram: _,
    framerate_gpu: `GPU`,
    framerate_saved_hardware: _,
    framerate_saved_hardware_none: _,
    framerate_saved_hardware_select: _,
    framerate_saved_hardware_option_none: _,
    framerate_saved_add: _,
    framerate_saved_add_btn: _,
    framerate_saved_add_not_in_client_btn: _,
    framerate_opt_in_data_collection_desc: _,
    framerate_opt_in_link: _,
    framerate_fps: `FPS`,
    framerate_game_name: _,
    framerate_select_cpu: _,
    framerate_select_gpu: _,
    framerate_training_game: _,
    framerate_training_cpu: _,
    framerate_training_gpu: _,
    generic_unknown: _,
    giftcards_banner_text: _,
    empty_no_trailing_comma: ``,
  };
export {
  _ as BundleList_AllInLibrary,
  _ as BundleList_AllInLibrarySubtitle,
  _ as BundleList_CompleteTheSet,
  _ as BundleList_CompleteTheSetSubtitle,
  _ as BundleList_MustPurchaseAsSet,
  _ as BundleList_MustPurchaseAsSetSubtitle,
  _ as BundleList_Page,
  _ as BundleList_SortBy,
  _ as BundleList_SortBy_Discount,
  _ as BundleList_SortBy_Name,
  _ as BundleList_SortBy_Popular,
  _ as BundleList_SortBy_Price,
  _ as BundleList_SortBy_Recommend,
  _ as BundleList_SubTitle,
  _ as BundleList_Title,
  _ as BundleList_Title_Fallback,
  _ as CookiePreferences,
  _ as Discussions_ForumName_Events,
  _ as Discussions_ForumName_General,
  _ as Discussions_ForumName_ReportedPosts,
  _ as Discussions_ForumName_Trading,
  _ as Discussions_ForumName_Workshop,
  _ as Error_RateLimited,
  _ as FatalErrorPage_Header,
  _ as FatalErrorPage_Message,
  _ as FatalErrorPage_Title,
  _ as PersonalCalendar_Account,
  _ as PersonalCalendar_AccountPlaceholder,
  _ as PersonalCalendar_CompactMode,
  _ as PersonalCalendar_Description,
  _ as PersonalCalendar_Error_Backend,
  _ as PersonalCalendar_HideEATooltip,
  _ as PersonalCalendar_HideEarlyAccess,
  _ as PersonalCalendar_HideOwned,
  _ as PersonalCalendar_IgnoringWishlists,
  _ as PersonalCalendar_LastMonthGames,
  _ as PersonalCalendar_LastWeekGames,
  _ as PersonalCalendar_LoginPrompt,
  _ as PersonalCalendar_ResultCountSelector,
  _ as PersonalCalendar_ShowAll,
  _ as PersonalCalendar_ShowMore,
  _ as PersonalCalendar_ShowOnlyWishlisted,
  _ as PersonalCalendar_SteamLabs,
  _ as PersonalCalendar_TagSelector,
  _ as PersonalCalendar_TagSelector_Placeholder,
  _ as PersonalCalendar_Title,
  _ as PersonalCalendar_Upcoming,
  _ as PersonalCalendar_WishlistHide,
  _ as PersonalCalendar_WishlistOnly,
  _ as PersonalCalendar_WishlistShow,
  _ as PersonalCalendar_Wishlisted,
  _ as Verification_DeckOnly,
  _ as Verification_DeckOnly_Desc,
  _ as account_notification_settings_error_invalidoptouttoken,
  _ as account_notification_settings_error_loading,
  _ as account_notification_settings_error_saving,
  _ as account_notification_settings_feed_disabled,
  _ as account_notification_settings_wishlist_categories_persona,
  _ as accountpreferences_familymanagement_header,
  _ as browse_categories,
  _ as cart_count,
  _ as cart_view_cart,
  _ as category_prerelease,
  _ as default,
  _ as empty_no_trailing_comma,
  _ as errorpage_error,
  _ as errorpage_unknownerror,
  _ as footer_about_valve,
  _ as footer_accessibility,
  _ as footer_business_solutions,
  _ as footer_cookies,
  _ as footer_jobs,
  _ as footer_legal,
  _ as footer_legal_notice,
  _ as footer_nav_help_support,
  _ as footer_privacy_policy,
  _ as footer_recycling,
  _ as footer_refunds,
  _ as footer_source_engine,
  _ as footer_ssa,
  _ as footer_steam_distribution,
  _ as footer_steamworks,
  _ as footer_vat_included,
  _ as footer_walletcode,
  _ as framerate_cpu,
  _ as framerate_fps,
  _ as framerate_game_name,
  _ as framerate_gpu,
  _ as framerate_opt_in_data_collection_desc,
  _ as framerate_opt_in_link,
  _ as framerate_ram,
  _ as framerate_saved_add,
  _ as framerate_saved_add_btn,
  _ as framerate_saved_add_not_in_client_btn,
  _ as framerate_saved_hardware,
  _ as framerate_saved_hardware_none,
  _ as framerate_saved_hardware_option_none,
  _ as framerate_saved_hardware_select,
  _ as framerate_select_cpu,
  _ as framerate_select_gpu,
  _ as framerate_subheader,
  _ as framerate_title,
  _ as framerate_training_cpu,
  _ as framerate_training_game,
  _ as framerate_training_gpu,
  _ as gatedaccess_limitedlaunch_badge,
  _ as gatedaccess_limitedlaunch_desc,
  _ as gatedaccess_limitedlaunch_desc_title,
  _ as gatedaccess_limitedlaunch_details_moreinfo,
  _ as gatedaccess_limitedlaunch_invite_count_tooltip,
  _ as generic_unknown,
  _ as genre_early_access,
  _ as giftcards_banner_text,
  _ as global_menu_account_details,
  _ as global_menu_account_gated_access_games,
  _ as global_menu_account_hardware_used,
  _ as global_menu_account_language_preferences,
  _ as global_menu_account_mobile_game_devices,
  _ as global_menu_account_notification_settings,
  _ as global_menu_account_preferences,
  _ as global_menu_account_security_devices,
  _ as global_menu_account_video_authorized_devices,
  _ as global_menu_greatondeck,
  _ as global_menu_localplayonframe,
  _ as global_menu_vr,
  _ as ir_add_to_cart,
  _ as ir_add_to_wishlist,
  _ as ir_body,
  _ as ir_discounted_only,
  _ as ir_filter_age_12,
  _ as ir_filter_age_24,
  _ as ir_filter_age_36,
  _ as ir_filter_age_6,
  _ as ir_filter_age_60,
  _ as ir_filter_age_all,
  _ as ir_free_to_play,
  _ as ir_header,
  _ as ir_name,
  _ as ir_no_wishlisted,
  _ as ir_on_wishlist,
  _ as ir_playtime_games,
  _ as ir_playtime_header,
  _ as ir_playtime_hours,
  _ as ir_playtime_hourstotal,
  _ as ir_playtime_ignore,
  _ as ir_playtime_lastplayed,
  _ as ir_playtime_lastplayedmax,
  _ as ir_playtime_recentgames,
  _ as ir_playtime_topgames,
  _ as ir_playtime_unignore,
  _ as ir_popularity_niche,
  _ as ir_popularity_popular,
  _ as ir_popularity_title,
  _ as ir_recency_newer,
  _ as ir_recency_older,
  _ as ir_recency_title,
  _ as ir_recommendations_header,
  _ as ir_release_date,
  _ as ir_tag_exclude,
  _ as ir_tag_filter,
  _ as ir_tag_placeholder,
  _ as m_home,
  _ as m_search_steam,
  _ as mature_content_requires_creditcard,
  _ as mature_content_requires_creditcard_gb,
  _ as playtestinvitehistory_desc,
  _ as playtestinvitehistory_invite_detail,
  _ as playtestinvitehistory_title,
  _ as playtestinvites_accept,
  _ as playtestinvites_desc1,
  _ as playtestinvites_desc2,
  _ as playtestinvites_desc_title,
  _ as playtestinvites_ignored_desc,
  _ as playtestinvites_ignored_remove,
  _ as playtestinvites_ignored_title,
  _ as playtestinvites_invitedescription_fromapp2,
  _ as playtestinvites_invitedescription_fromapp_limitedlaunch,
  _ as playtestinvites_invitedescription_fromuser2,
  _ as playtestinvites_invitedescription_fromuser_limitedlaunch,
  _ as playtestinvites_noinvites,
  _ as playtestinvites_reject,
  _ as playtestinvites_sendinvite_cancel,
  _ as playtestinvites_sendinvite_confirm_desc,
  _ as playtestinvites_sendinvite_failure,
  _ as playtestinvites_sendinvite_lastinvite,
  _ as playtestinvites_sendinvite_lastinvite_limitedlaunch,
  _ as playtestinvites_sendinvite_pending,
  _ as playtestinvites_sendinvite_send,
  _ as playtestinvites_sendinvite_success,
  _ as playtestinvites_title,
  _ as playtestinvites_viewlibrary,
  _ as playtestinvites_welcome,
  _ as playtestinvites_welcome_limitedlaunch,
  _ as playtestinvites_welcome_notplayable,
  _ as playteststatus_details_allinvitesused,
  _ as playteststatus_details_moreinfo,
  _ as playteststatus_details_moreinfo_newshub,
  _ as playteststatus_details_moreinfo_storepage,
  _ as playteststatus_details_notplayable,
  _ as playteststatus_error_dataunavailable,
  _ as playteststatus_invite_count,
  _ as playteststatus_invite_count_plural,
  _ as playteststatus_invite_count_tooltip,
  _ as playteststatus_invite_count_tooltip2,
  _ as playteststatus_invitefrienddialog_header,
  _ as playteststatus_invitefrienddialog_ineligiblefriends,
  _ as playteststatus_invitefrienddialog_ineligiblefriends_purchaser,
  _ as playteststatus_invitefrienddialog_loadingerror,
  _ as playteststatus_invitefrienddialog_search_placeholder,
  _ as playteststatus_invitefriends,
  _ as playteststatus_invites_available,
  _ as playteststatus_none,
  _ as playteststatus_title,
  _ as pressoutlets_action_by_support,
  _ as pressoutlets_action_created,
  _ as pressoutlets_action_deleted,
  _ as pressoutlets_action_enterstaging,
  _ as pressoutlets_action_exitstaging,
  _ as pressoutlets_action_granted,
  _ as pressoutlets_action_removed,
  _ as pressoutlets_action_stagedadd,
  _ as pressoutlets_action_stageddelete,
  _ as pressoutlets_action_undeleted,
  _ as pressoutlets_action_updated,
  _ as pressoutlets_action_updated_domain_changed,
  _ as pressoutlets_action_updated_slots_changed,
  _ as pressoutlets_button_add,
  _ as pressoutlets_button_add_member,
  _ as pressoutlets_button_cancel,
  _ as pressoutlets_button_ok,
  _ as pressoutlets_button_show_history,
  _ as pressoutlets_email_domain_label,
  _ as pressoutlets_error_adding_outlet,
  _ as pressoutlets_error_already_owned,
  _ as pressoutlets_error_domain_empty,
  _ as pressoutlets_error_domain_used,
  _ as pressoutlets_error_generic_add_error,
  _ as pressoutlets_error_invalid_domain,
  _ as pressoutlets_error_slots_gt_zero,
  _ as pressoutlets_filter_active,
  _ as pressoutlets_filter_all,
  _ as pressoutlets_filter_deleted,
  _ as pressoutlets_filter_empty,
  _ as pressoutlets_filter_noadmins,
  _ as pressoutlets_friendcode,
  _ as pressoutlets_header_account,
  _ as pressoutlets_header_granted_at,
  _ as pressoutlets_header_grantee,
  _ as pressoutlets_header_is_group_admin,
  _ as pressoutlets_history_header,
  _ as pressoutlets_history_title,
  _ as pressoutlets_is_group_admin,
  _ as pressoutlets_is_not_group_admin,
  _ as pressoutlets_label_add_outlet,
  _ as pressoutlets_outlet_header,
  _ as pressoutlets_outlet_header_prefix,
  _ as pressoutlets_resign_your_key,
  _ as pressoutlets_resign_your_key_title,
  _ as pressoutlets_show_history,
  _ as pressoutlets_slots_label,
  _ as pressoutlets_steamid_to_add,
  _ as sitemap_genres,
  _ as sitemap_giftcards,
  _ as sitemap_home,
  _ as sitemap_pointsshop,
  _ as sitemap_section_account,
  _ as sitemap_section_account_account_details,
  _ as sitemap_section_account_cart,
  _ as sitemap_section_account_cart_with_count,
  _ as sitemap_section_account_cookes_and_browsing,
  _ as sitemap_section_account_family_management,
  _ as sitemap_section_account_followed_games,
  _ as sitemap_section_account_followed_games_with_count,
  _ as sitemap_section_account_language_preferences,
  _ as sitemap_section_account_notification_settings,
  _ as sitemap_section_account_security_and_devices,
  _ as sitemap_section_account_store_preferences,
  _ as sitemap_section_account_wishlist,
  _ as sitemap_section_account_wishlist_with_count,
  _ as sitemap_section_chartsandlists,
  _ as sitemap_section_chartsandlists_free_to_play,
  _ as sitemap_section_chartsandlists_most_played,
  _ as sitemap_section_chartsandlists_new_releases,
  _ as sitemap_section_chartsandlists_on_sale_now,
  _ as sitemap_section_chartsandlists_steam_charts,
  _ as sitemap_section_chartsandlists_top_sellers,
  _ as sitemap_section_chartsandlists_upcoming_releases,
  _ as sitemap_section_hardware,
  _ as sitemap_section_hardware_controller_friendly,
  _ as sitemap_section_hardware_great_on_deck,
  _ as sitemap_section_hardware_steam_deck,
  _ as sitemap_section_hardware_steam_deck_dock,
  _ as sitemap_section_hardware_vr_games,
  _ as sitemap_section_hardware_vr_hardware,
  _ as sitemap_section_newsupdates,
  _ as sitemap_section_newsupdates_featured_news,
  _ as sitemap_section_newsupdates_recently_updated,
  _ as sitemap_section_newsupdates_steam_official_news,
  _ as sitemap_section_newsupdates_your_recently_updated,
  _ as sitemap_section_newsupdates_your_upcoming_events,
  _ as sitemap_section_promosandevents,
  _ as sitemap_section_promosandevents_sale_events,
  _ as sitemap_section_promosandevents_special_offers,
  _ as sitemap_section_promosandevents_steam_awards,
  _ as sitemap_section_promosandevents_steam_next_fest,
  _ as sitemap_section_promosandevents_steam_replay,
  _ as sitemap_section_recommendations,
  _ as sitemap_section_recommendations_community_recommendations,
  _ as sitemap_section_recommendations_discovery_queue,
  _ as sitemap_section_recommendations_dlc_for_you,
  _ as sitemap_section_recommendations_interactive_recommender,
  _ as sitemap_section_recommendations_new_releases_queue,
  _ as sitemap_section_recommendations_popular_among_friends,
  _ as sitemap_section_recommendations_steam_curators,
  _ as sitemap_section_specialsections,
  _ as sitemap_section_waystoplay,
  _ as sitemap_themes,
  _ as sitemap_title,
  _ as store_tab_foryou_store_home,
  _ as trailerassets_invalidfile,
  _ as trailerassets_microtrailer,
  _ as trailerassets_trailer,
  _ as wishlist_browse_the_store,
  _ as wishlist_categories_advanced_addremove_title,
  _ as wishlist_categories_advanced_apply,
  _ as wishlist_categories_advanced_failed_items,
  _ as wishlist_categories_advanced_failed_items_Plural,
  _ as wishlist_categories_advanced_no_items,
  _ as wishlist_categories_advanced_pending,
  _ as wishlist_categories_advanced_pending_adds,
  _ as wishlist_categories_advanced_pending_removals,
  _ as wishlist_categories_advanced_rename_duplicate,
  _ as wishlist_categories_advanced_rename_failed,
  _ as wishlist_categories_advanced_rename_label,
  _ as wishlist_categories_advanced_rename_save,
  _ as wishlist_categories_advanced_revert,
  _ as wishlist_categories_advanced_select,
  _ as wishlist_categories_advanced_select_all,
  _ as wishlist_categories_advanced_select_none,
  _ as wishlist_categories_advanced_showing,
  _ as wishlist_categories_advanced_title,
  _ as wishlist_controls_categories_add,
  _ as wishlist_controls_categories_header_anonymous,
  _ as wishlist_controls_categories_multiselect_label,
  _ as wishlist_controls_demo_available,
  _ as wishlist_controls_demo_available_tooltip,
  _ as wishlist_controls_early_access_tooltip,
  _ as wishlist_controls_filter_tag_label,
  _ as wishlist_controls_options_category_category,
  _ as wishlist_controls_options_category_deck,
  _ as wishlist_controls_options_category_discount,
  _ as wishlist_controls_options_category_exclude,
  _ as wishlist_controls_options_category_platform,
  _ as wishlist_controls_options_category_price,
  _ as wishlist_controls_options_category_related,
  _ as wishlist_controls_options_category_tag,
  _ as wishlist_controls_options_category_type,
  _ as wishlist_controls_options_category_view,
  _ as wishlist_controls_options_deck_playable,
  _ as wishlist_controls_options_deck_verified,
  _ as wishlist_controls_options_discount_all,
  _ as wishlist_controls_options_discount_any,
  _ as wishlist_controls_options_discount_or_more,
  _ as wishlist_controls_options_exclude_vr,
  _ as wishlist_controls_options_platform_all,
  _ as wishlist_controls_options_platform_linux,
  _ as wishlist_controls_options_platform_mac,
  _ as wishlist_controls_options_price_any,
  _ as wishlist_controls_options_price_free,
  _ as wishlist_controls_options_price_max_price,
  _ as wishlist_controls_options_type_application,
  _ as wishlist_controls_options_type_dlc,
  _ as wishlist_controls_options_type_game,
  _ as wishlist_controls_options_type_video,
  _ as wishlist_controls_options_view_compact,
  _ as wishlist_controls_options_view_expanded,
  _ as wishlist_controls_share_description,
  _ as wishlist_controls_share_dialog_title,
  _ as wishlist_controls_share_generation_failure,
  _ as wishlist_controls_share_revokeall,
  _ as wishlist_controls_share_revokeall_success,
  _ as wishlist_controls_sortby_dateadded,
  _ as wishlist_controls_sortby_discount,
  _ as wishlist_controls_sortby_name,
  _ as wishlist_controls_sortby_order,
  _ as wishlist_controls_sortby_price,
  _ as wishlist_controls_sortby_releasedate,
  _ as wishlist_controls_sortby_reviews,
  _ as wishlist_controls_sortby_their_order,
  _ as wishlist_controls_sortby_topsellers,
  _ as wishlist_controls_tag_description,
  _ as wishlist_controls_tags_header,
  _ as wishlist_count,
  _ as wishlist_displayed_item_count,
  _ as wishlist_displayed_item_count_Plural,
  _ as wishlist_error_invalidsharetoken,
  _ as wishlist_error_profilenotfound,
  _ as wishlist_error_wishlistunavailable,
  _ as wishlist_errorpage_title,
  _ as wishlist_filter_matches_categories,
  _ as wishlist_filter_matches_categories_Plural,
  _ as wishlist_filter_matches_category,
  _ as wishlist_filter_matches_category_Plural,
  _ as wishlist_filter_matches_items,
  _ as wishlist_filter_matches_items_Plural,
  _ as wishlist_filter_matches_tag,
  _ as wishlist_filter_matches_tag_Plural,
  _ as wishlist_filter_matches_tags,
  _ as wishlist_filter_matches_tags_Plural,
  _ as wishlist_filter_results,
  _ as wishlist_filters_notification,
  _ as wishlist_gamepad_options,
  _ as wishlist_gamepad_options_remove,
  _ as wishlist_gamepad_visitstore,
  _ as wishlist_gamepaddragdrop_cancelreorder,
  _ as wishlist_gamepaddragdrop_commitreorder,
  _ as wishlist_gamepaddragdrop_reorderaction,
  _ as wishlist_header,
  _ as wishlist_item_add_credit_card,
  _ as wishlist_item_addedon_date,
  _ as wishlist_item_languagespecific_reviews,
  _ as wishlist_item_overallreviews,
  _ as wishlist_item_releasedate,
  _ as wishlist_item_remove,
  _ as wishlist_item_remove_tooltip,
  _ as wishlist_item_unavailable_region,
  _ as wishlist_item_unavailable_retired,
  _ as wishlist_item_unavailable_title,
  _ as wishlist_learn_more_button,
  _ as wishlist_no_items_matching_filters,
  _ as wishlist_options_button,
  _ as wishlist_others_wishlist_empty,
  _ as wishlist_search,
  _ as wishlist_search_all,
  _ as wishlist_share_tooltip,
  _ as wishlist_sign_in_to_see_your_wishlist,
  _ as wishlist_sortby_button,
  _ as wishlist_title,
  _ as wishlist_x_items_on_wishlist_but_none_match,
  _ as wishlist_x_items_on_wishlist_but_none_match_prefs,
  _ as wishlist_your_wishlist_empty,
  _ as youraccount_account,
  _ as youraccount_errorpage_title,
  _ as youraccount_users_account,
};
