var _ = `Wszystkie zestawy zawierające:`,
  _ = `Sortuj według:`,
  _ = `Popularne`,
  _ = `Cena`,
  _ = `Zniżka na zestaw`,
  _ = `Nazwa`,
  _ = `Polecane`,
  _ = `Twoje kompletne zestawy`,
  _ = `Cała zawartość tych zestawów znajduje się w twojej bibliotece`,
  _ = `Zestawy do uzupełnienia kolekcji`,
  _ = `Zakup pozostałe tytuły, które nie znajdują się jeszcze w twojej bibliotece, by skompletować zestaw.`,
  _ = `Zestawy, gdzie wymagany jest zakup produktów razem`,
  _ = `Zawiera wszystkie produkty w ramach pojedynczego zestawu. Muszą zostać kupione jako kompletny zestaw.`,
  _ = `© %1$s Valve Corporation. Wszelkie prawa zastrzeżone. Wszystkie znaki handlowe są własnością ich prawnych właścicieli w\xA0Stanach Zjednoczonych i\xA0innych krajach.`,
  _ = `Ceny zawierają podatek VAT (jeśli ma zastosowanie).`,
  _ = `Polityka prywatności`,
  _ = `Informacje prawne`,
  _ = `Ułatwienia dostępu`,
  _ = `Umowa użytkownika Steam`,
  _ = `Zwrot pieniędzy`,
  _ = `Ciasteczka`,
  _ = `O Valve`,
  _ = `Rozwiązania biznesowe`,
  _ = `Utylizacja`,
  _ = `Steamworks`,
  _ = `Silnik Source`,
  _ = `Praca`,
  _ = `Karty podarunkowe`,
  _ = `Dystrybucja Steam`,
  _ = `Pomoc techniczna`,
  _ = `Lista życzeń użytkownika %1$s`,
  _ = `LISTA ŻYCZEŃ UŻYTKOWNIKA %1$s`,
  _ = `Koszyk (%1$s)`,
  _ = `Zobacz koszyk`,
  _ = `Lista życzeń (%1$s)`,
  _ = `Opcje`,
  _ = `Posortuj według: %1$s`,
  _ = `Utwórz link do udostępniania`,
  _ = `Twoja kolejność`,
  _ = `Kolejność użytkownika`,
  _ = `Bestsellery`,
  _ = `Data wydania`,
  _ = `Data dodania`,
  _ = `Ocena produktu`,
  _ = `Cena`,
  _ = `Nazwa`,
  _ = `Zniżka`,
  _ = `Link do udostępniania`,
  _ = `Unieważnij wszystkie linki`,
  _ = `Linki unieważnione!`,
  _ = `Nie udało się utworzyć linku do udostępniania (błąd %1$s)`,
  _ = `Każdy, kto ma ten link, będzie mógł wyświetlić twoją listę życzeń z bieżącymi filtrami, niezależnie od ustawień widoczności profilu. Nie będzie jednak mógł zmienić filtrów.`,
  _ = `Widok`,
  _ = `Rozszerzony`,
  _ = `Kompaktowy`,
  _ = `Platforma`,
  _ = `Dowolny system operacyjny`,
  _ = `macOS`,
  _ = `SteamOS + Linux`,
  _ = `Rodzaj`,
  _ = `Gry`,
  _ = `Oprogramowanie`,
  _ = `DLC`,
  _ = `Wideo`,
  _ = `Cena`,
  _ = `Zniżka`,
  _ = `Wszystkie produkty na liście`,
  _ = `Wszystkie ze zniżką`,
  _ = `%1$s% lub więcej`,
  _ = `Dowolna cena`,
  _ = `Poniżej %1$s`,
  _ = `Darmowe`,
  _ = `Wyklucz`,
  _ = `Powiązane produkty`,
  _ = `Wczesny dostęp`,
  _ = `Ten tytuł jest obecnie we wczesnym dostępie.`,
  _ = `Przedpremiera`,
  _ = `Tylko VR`,
  _ = `Dostępne demo`,
  _ = `Filtruj swoją listę życzeń do produktów z demami`,
  _ = `Zgodność ze Steam Deckiem`,
  _ = `Zweryfikowane`,
  _ = `Grywalne`,
  _ = `Tag`,
  _ = `Filtruj swoją listę życzeń do produktów z tym tagiem`,
  _ = `Tagi użytkowników:`,
  _ = `%1$s: %2$s`,
  _ = `Kategoria`,
  _ = `Kategorie:`,
  _ = `<1>Kategorie:</1> <2>%1$s</2>`,
  _ = `Dodaj kategorię`,
  _ = `Zaawansowane zarządzanie kategoriami`,
  _ = `WYBIERZ KATEGORIĘ DO EDYCJI`,
  _ = `NAZWA KATEGORII`,
  _ = `Zmień nazwę`,
  _ = `Masz już kategorię o tej nazwie`,
  _ = `Wystąpił błąd podczas zmiany nazwy tej kategorii (kod: %1$s)`,
  _ = `Brak na liście życzeń produktów pasujących do twojego wyszukiwania.`,
  _ = `Wszystkie`,
  _ = `Brak`,
  _ = `Pokazywanie pierwszych %1$s z %2$s produktów. Wyszukaj, aby zawęzić listę.`,
  _ = `Nie udało się zaktualizować produktów (%1$s)`,
  _ = `Nie udało się zaktualizować produktów (%1$s)`,
  _ = `Oczekuje`,
  _ = `Dodania: %1$s`,
  _ = `Usunięcia: %1$s`,
  _ = `Cofnij`,
  _ = `Zastosuj zmiany`,
  _ = `DODAJ/USUŃ KATEGORIĘ`,
  _ = `PRODUKTY: %1$s`,
  _ = `PRODUKTY: %1$s`,
  _ = `Wyniki wyszukiwania:`,
  _ = `Produkty, których nazwa zawiera „%2$s”: %1$s`,
  _ = `Produkty, których nazwa zawiera „%2$s”: %1$s`,
  _ = `Produkty w kategorii „%2$s”: %1$s`,
  _ = `Produkty w kategorii „%2$s”: %1$s`,
  _ = `Produkty, które mają kategorie zawierające „%2$s”: %1$s`,
  _ = `Produkty, które mają kategorie zawierające „%2$s”: %1$s`,
  _ = `Produkty z tagiem „%2$s”: %1$s`,
  _ = `Produkty z tagiem „%2$s”: %1$s`,
  _ = `Produkty z tagami zawierającymi „%2$s”: %1$s`,
  _ = `Produkty z tagami zawierającymi „%2$s”: %1$s`,
  _ = `Szukaj wg nazwy lub tagu`,
  _ = `Szukaj według nazwy, tagu lub kategorii`,
  _ = `Ogólne recenzje:`,
  _ = `Recenzje (%1$s):`,
  _ = `Data wydania:`,
  _ = `Dodano %1$s`,
  _ = `usuń`,
  _ = `Usuń ten produkt z twojej listy życzeń.`,
  _ = `(produkt niedostępny)`,
  _ = `Ten produkt nie jest dostępny w twoim regionie.`,
  _ = `Ten produkt nie jest już dostępny.`,
  _ = `Treści dla dorosłych nie są dozwolone dla użytkowników poniżej 18 roku życia w twoim kraju. Valve jest zobowiązane do zweryfikowania, że masz co najmniej 18 lat przed umożliwieniem dostępu do treści dla dorosłych.`,
  _ = `Zgodnie z Brytyjską Ustawą o Bezpieczeństwie w Sieci (UK Online Safety Act) Valve jest zobowiązane do weryfikacji, czy masz co najmniej 18 lat przed umożliwieniem dostępu do treści seksualnych dla dorosłych.`,
  _ = `Dodaj kartę kredytową`,
  _ = `Twoja lista życzeń jest pusta.`,
  _ = `Zapełnij swoją listę życzeń, przeglądając sklep i korzystając z przycisku „Dodaj do listy życzeń”.`,
  _ = `Dowiedz się więcej o listach życzeń na Steam`,
  _ = `Zaloguj się, aby zobaczyć swoją listę życzeń.`,
  _ = `Ta lista życzeń jest pusta.`,
  _ = `Brak pasujących produktów.`,
  _ = `Na tej liście życzeń znajdują się produkty (%1$s), ale żaden z nich nie pasuje do twoich filtrów listy życzeń i/lub preferencji sklepu.`,
  _ = `Na tej liście życzeń znajdują się produkty (%1$s), ale żaden z nich nie pasuje do twoich filtrów listy życzeń i/lub <1>preferencji sklepu</1>.`,
  _ = `Zmień kolejność`,
  _ = `Anuluj zmianę kolejności`,
  _ = `Umieść tutaj`,
  _ = `Opcje`,
  _ = `Usuń`,
  _ = `Odwiedź stronę w sklepie`,
  _ = `Lista życzeń – błąd`,
  _ = `Błąd`,
  _ = `Nieznany błąd`,
  _ = `Nie znaleziono profilu`,
  _ = `Nie udało się wczytać listy życzeń użytkownika.`,
  _ = `Ten link do udostępnienia listy życzeń jest nieprawidłowy lub wygasł.`,
  _ = `Gry wysyłające powiadomienia listy życzeń`,
  _ = `Konto użytkownika %1$s`,
  _ = `Konto – błąd`,
  _ = `Konto`,
  _ = `Strona główna`,
  _ = `Szczegóły konta`,
  _ = `Preferencje sklepu`,
  _ = `Preferencje językowe`,
  _ = `Ustawienia powiadomień`,
  _ = `Urządzenia`,
  _ = `Bezpieczeństwo i urządzenia`,
  _ = `Autoryzowane urządzenia (wideo)`,
  _ = `Urządzenia mobilne do gry`,
  _ = `Playtesty`,
  _ = `Zarządzanie rodzinne`,
  _ = `Dane i przeglądanie`,
  _ = `VR`,
  _ = `Świetne na Decku`,
  _ = `Gra lokalna (Steam Frame)`,
  _ = `Strona główna sklepu`,
  _ = `Kategorie`,
  _ = `Przeszukaj Steam`,
  _ = `Nie udało się wczytać danych ograniczonego dostępu.`,
  _ = `Zaproszenia do Steam Playtest`,
  _ = `Zaakceptuj zaproszenie`,
  _ = `Odrzuć zaproszenie`,
  _ = `Zaproszono cię do dołączenia do Steam Playtest!`,
  _ = `Zaproszono cię do ograniczonego wydania!`,
  _ = `%1$s zaprasza cię do dołączenia do Steam Playtest!`,
  _ = `%1$s zaprasza cię do ograniczonego wydania!`,
  _ = `Nie masz żadnych zaproszeń do Steam Playtest ani ogranicznego wydania oczekujących twojej odpowiedzi.`,
  _ = `Witamy w playteście! Możesz już zainstalować %1$s z poziomu swojej biblioteki.`,
  _ = `Witamy w ograniczonym wydaniu! Możesz już zainstalować %1$s z poziomu swojej biblioteki.`,
  _ = `Witaj w playteście! Produkt %1$s nie jest obecnie aktywny. Obserwuj plany producentów na nadchodzącą premierę.`,
  _ = `Wyświetl bibliotekę`,
  _ = `Czym jest funkcja Steam Playtest?`,
  _ = `Zadaniem playtestów Steam jest pomoc w testowaniu gier, które są nadal rozwijane. Zaakceptowanie zaproszenia lub udzielenie dostępu przez producenta spowoduje automatyczne dodanie gry do biblioteki.`,
  _ = `Odwołaj się do informacji podanych przez producenta co do charakteru danego playtestu. Dostęp do funkcji Steam Playtest nie gwarantuje dostępu do gry po jej wydaniu.`,
  _ = `Zignorowane zaproszenia do Steam Playtest`,
  _ = `Odrzuciłeś zaproszenia do playtestów Steam lub ograniczonego wydania dla następujących gier. Nie otrzymasz więcej zaproszeń, dopóki nie usuniesz ich z tej listy.`,
  _ = `Usuń`,
  _ = `Anuluj`,
  _ = `Wyślij`,
  _ = `To twoje ostatnie dostępne zaproszenie do tego playtestu.`,
  _ = `To twoje ostatnie dostępne zaproszenie do tego ograniczonego wydania.`,
  _ = `Wysyłanie zaproszenia do:`,
  _ = `Zapraszanie użytkownika %1$s…`,
  _ = `Użytkownik %1$s został zaproszony! Zaproszenie pojawi się w jego %2$s powiadomieniach.`,
  _ = `Nie można zaprosić użytkownika %1$s. Możliwe, że został już zaproszony lub gra może nie być dostępna w jego regionie.`,
  _ = `Historia wysłanych zaproszeń`,
  _ = `Niedawne zaproszenia do playtestów i ograniczonych wydań wysłane przez ciebie do znajomych.`,
  _ = `Zaproszono użytkownika %1$s do playtestu gry %2$s`,
  _ = `Udział w Steam Playtest`,
  _ = `Nie dołączono do żadnego aktywnego playtestu ani ograniczonego wydania.`,
  _ = `Masz dostępne zaproszenia`,
  _ = `Masz dostępne zaproszenia: %1$s`,
  _ = `Masz dostępne zaproszenia: %1$s`,
  _ = `Możesz przyznać dostęp do tego playtestu swoim znajomym, zapraszając ich.`,
  _ = `Liczba dostępnych zaproszeń może ulec zmianie w miarę dołączania większej liczby graczy.`,
  _ = `Więcej szczegółów takich jak harmonogram i dołączona zawartość można znaleźć w %1$s lub na %2$s.`,
  _ = `stronie w sklepie`,
  _ = `centrum aktualności`,
  _ = `Ten Playtest nie jest obecnie aktywny.`,
  _ = `Wszystkie zaproszenia dla znajomych zostały zużyte`,
  _ = `Zaproś znajomych`,
  _ = `Wybierz odbiorcę zaproszenia`,
  _ = `Szukaj według pseudonimu znajomego…`,
  _ = `Nie udało się wczytać znajomych.`,
  _ = `Niektórych znajomych nie można zaprosić, ponieważ nie jesteście znajomymi więcej niż 30 dni, mają już dostęp do gry lub nie spełniają warunków udziału z innych powodów.`,
  _ = `Niektórych znajomych nie można zaprosić, ponieważ mają już dostęp do gry lub nie spełniają warunków udziału z innych powodów.`,
  _ = `Ograniczone wydanie`,
  _ = `Możesz przyznać dostęp do tego ograniczonego wydania swoim znajomym, zapraszając ich.`,
  _ = `%1$s powoli zwiększa liczbę graczy w trakcie wstępnego ograniczonego wydania. Więcej szczegółów znajdziesz na %2$s lub w %3$s.`,
  _ = `Czym jest ograniczone wydanie?`,
  _ = `Ograniczone wydanie jest wykorzystywane przez niektóre darmowe gry do powolnego zwiększania liczby graczy przy pierwotnej premierze gry. Przyjęcie zaproszenia lub uzyskanie dostępu po przesłaniu prośby do producenta doda grę do twojej biblioteki i pozwoli ci natychmiast grać.`,
  _ = `Mapa stron w Sklepie Steam`,
  _ = `Strona główna sklepu`,
  _ = `Moje konto`,
  _ = `Szczegóły mojego konta`,
  _ = `Moje preferencje sklepu`,
  _ = `Zarządzanie rodzinne`,
  _ = `Bezpieczeństwo i urządzenia`,
  _ = `Preferencje językowe`,
  _ = `Ciasteczka i przeglądanie`,
  _ = `Ustawienia powiadomień`,
  _ = `Koszyk`,
  _ = `Koszyk (%1$s)`,
  _ = `Lista życzeń`,
  _ = `Lista życzeń (%1$s)`,
  _ = `Obserwowane gry i programy`,
  _ = `Obserwowane gry i programy (%1$s)`,
  _ = `Notowania i listy`,
  _ = `Bestsellery`,
  _ = `Najczęściej grane`,
  _ = `Nowe tytuły`,
  _ = `Nadchodzące tytuły`,
  _ = `Free to Play`,
  _ = `Notowania Steam`,
  _ = `Na wyprzedaży`,
  _ = `Polecane`,
  _ = `Kolejka odkryć`,
  _ = `Kolejka nowych tytułów`,
  _ = `Rekomendacje społeczności`,
  _ = `Interaktywny doradca`,
  _ = `Popularne wśród znajomych`,
  _ = `Kuratorzy Steam`,
  _ = `DLC dla ciebie`,
  _ = `Sprzęt`,
  _ = `Steam Deck`,
  _ = `Stacja dokująca Steam Decka`,
  _ = `Sprzęt VR`,
  _ = `Gry VR`,
  _ = `Gry świetne na Decku`,
  _ = `Gry przyjazne kontrolerom`,
  _ = `Sposoby rozgrywki`,
  _ = `Aktualności`,
  _ = `Ostatnio zaktualizowane gry`,
  _ = `Twoje niedawno zaktualizowane gry`,
  _ = `Twoje nadchodzące wydarzenia`,
  _ = `Wyróżnione aktualności`,
  _ = `Oficjalne aktualności i aktualizacje Steam`,
  _ = `Promocje i wydarzenia`,
  _ = `Oferty specjalne`,
  _ = `Wydarzenia wyprzedażowe`,
  _ = `Podsumowanie\xA0roku na Steam`,
  _ = `Festiwal Steam Next`,
  _ = `Nagrody Steam`,
  _ = `Sekcje specjalne`,
  _ = `Sklep punktów Steam`,
  _ = `Karty podarunkowe`,
  _ = `Gatunki`,
  _ = `Motywy`,
  _ = `Dokonano zbyt wielu żądań. Poczekaj i spróbuj ponownie później.`,
  _ = `Dyskusje ogólne`,
  _ = `Zgłoszone posty`,
  _ = `Dyskusje warsztatu`,
  _ = `Wymiana`,
  _ = `Wydarzenia i ogłoszenia`,
  _ = `Interaktywny doradca`,
  _ = `Gracze tacy jak ty uwielbiają…`,
  _ = `Odkryj spersonalizowane rekomendacje od naszego systemu nauczania maszynowego, który opiera się na twojej historii rozgrywek na Steam w porównaniu do milionów innych graczy. Dostosuj swoje wyniki za pomocą suwaków i filtrów, a następnie zapisz swoje ustawienia, by Steam pamiętał, czego szukasz.`,
  _ = `Czas spędzony w grze`,
  _ = `Gry: %1$s`,
  _ = `%1$s najdłużej granych`,
  _ = `niedawne gry`,
  _ = `%1$s godz.`,
  _ = `%1$s godz. łącznie`,
  _ = `ostatnio grano %1$s`,
  _ = `ostatnio grano ponad 10 lat temu`,
  _ = `Zawieraj`,
  _ = `Wyklucz`,
  _ = `Waga wg popularności`,
  _ = `popularne`,
  _ = `niszowe`,
  _ = `Filtruj według wieku`,
  _ = `starsze`,
  _ = `nowsze`,
  _ = `Wszystko`,
  _ = `5 lat`,
  _ = `3 lata`,
  _ = `2 lata`,
  _ = `1\xA0rok`,
  _ = `6 miesięcy`,
  _ = `Rekomendacje dla ciebie`,
  _ = `Data wydania: %1$s`,
  _ = `Na liście życzeń`,
  _ = `Dodaj do koszyka`,
  _ = `Dodaj do listy życzeń`,
  _ = `Free to Play`,
  _ = `Wpisz nazwę tagu`,
  _ = `Dodaj filtry tagów`,
  _ = `Dodaj wykluczenia tagów`,
  _ = `Wyklucz gry z listy życzeń`,
  _ = `Tylko gry ze zniżką`,
  _ = `Wydane w ciągu ostatniego miesiąca`,
  _ = `Wydane w ciągu ostatnich 7 dni`,
  _ = `Nadchodzące`,
  _ = `Twój osobisty kalendarz`,
  _ = `Spersonalizowana lista %1$s gier, które zostały wydane w ostatnim czasie lub zostaną wydane wkrótce.`,
  _ = `Selektor tagów`,
  _ = `Filtruj według tagu…`,
  _ = `Ukryj posiadane gry`,
  _ = `Gry wychodzące z wczesnego dostępu nadal będą wyświetlane`,
  _ = `Ukryj gry ze wczesnym dostępem`,
  _ = `Pokaż tylko gry z listy życzeń`,
  _ = `Liczba gier`,
  _ = `Kalendarz kompaktowy`,
  _ = `Opcjonalne obejście`,
  _ = `ID konta`,
  _ = `Zobacz wszystkie %1$s`,
  _ = `Zaloguj się, by zobaczyć spersonalizowane sugestie.`,
  _ = `Rozwiń wszystkie`,
  _ = `Eksperyment nr 16 laboratoriów Steam | <1>Dowiedz się więcej i podziel się opinią.</1>`,
  _ = `Gry na liście życzeń`,
  _ = `Wyświetl`,
  _ = `Ukryj`,
  _ = `Tylko na liście życzeń`,
  _ = `Zbyt wiele gier na liście życzeń. Funkcja wyłączona.`,
  _ = `Błąd podczas ładowania kalendarza. Spróbuj ponownie.`,
  _ = `Lista zestawów produktu %1$s`,
  _ = `Lista zestawów`,
  _ = `Wszystkie zestawy zawierające grę %1$s.`,
  _ = `Zweryfikowane na Steam Decku`,
  _ = `Gra %1$s jest zweryfikowana na Steam Decku.`,
  _ = `Błąd strony`,
  _ = `UPS, PRZEPRASZAMY!`,
  _ = `Wystąpił błąd podczas przetwarzania twojego żądania.`,
  _ = `Liczba miejsc musi być większa niż 0.`,
  _ = `Domena e-mail jest już używana przez inną agencję.`,
  _ = `Nie udało się dodać agencji.`,
  _ = `Domena e-mail nie może być pusta.`,
  _ = `Nieprawidłowa domena email.`,
  _ = `Konto jest już przypisane do agencji prasowej.`,
  _ = `Nie udało się dodać konta do agencji prasowej.`,
  _ = `Domena e-mail`,
  _ = `Liczba miejsc`,
  _ = `Dodaj`,
  _ = `Dodaj agencję:`,
  _ = `%1$s, użyto %2$s/%3$s miejsc`,
  _ = `Pokaż historię`,
  _ = `Historia dla: %1$s`,
  _ = `Klucz prasowy przyznany dla: %1$s przez: %2$s`,
  _ = `Klucz prasowy wycofany dla: %1$s przez: %2$s`,
  _ = `Klucz prasowy utworzony przez: %1$s`,
  _ = `Agencja prasowa zaktualizowana przez: %1$s`,
  _ = `Domena e-mail ustawiona na: %1$s`,
  _ = `Liczba miejsc ustawiona na: %1$s`,
  _ = `Agencja prasowa usunięta przez: %1$s`,
  _ = `Agencja prasowa przywrócona przez: %1$s`,
  _ = `Zmiany dla agencji prasowej zostały zaplanowane przez: %1$s`,
  _ = `Zaplanowane zmiany zostały zastosowane przez: %1$s`,
  _ = `Użytkownik %1$s jest zaplanowany do dodania przez: %2$s`,
  _ = `Użytkownik %1$s jest zaplanowany do usunięcia przez: %2$s`,
  _ = `pomoc techniczna`,
  _ = `Odbiorca`,
  _ = `Przyznano:`,
  _ = `Jest administratorem grupy?`,
  _ = `ID Steam do dodania`,
  _ = `OK`,
  _ = `Anuluj`,
  _ = `Tak`,
  _ = `Nie`,
  _ = `Wszystkie`,
  _ = `Aktywne`,
  _ = `Usunięte`,
  _ = `Puste`,
  _ = `Brak administratorów w agencji`,
  _ = `Agencja prasowa:`,
  _ = `Kod znajomego:`,
  _ = `Zrezygnuj z klucza prasowego: `,
  _ = `Czy naprawdę chcesz zrezygnować z klucza prasowego?`,
  _ = `Historia agencji`,
  _ = `Dodaj członka`,
  _ = `Pokaż historię`,
  _ = `Konto`,
  _ = `Nie znaleziono zwiastuna`,
  _ = `Zwiastun`,
  _ = `Mikrozwiastun`,
  _ = `Wystąpił błąd podczas zapisywania twoich ustawień powiadomień.`,
  _ = `Wystąpił błąd podczas wczytywania twoich ustawień powiadomień.`,
  _ = `Ten link do rezygnacji z subskrypcji jest nieprawidłowy lub wygasł. Zaloguj się i przejdź do menu <1>Ustawienia powiadomień</1>`,
  _ = `Kanał jest automatycznie włączony, jeśli wybrano wyskakujące powiadomienie w kliencie lub aplikację mobilną.`,
  _ = `Powiadamiaj użytkownika %1$s tylko o tych kategoriach listy życzeń`,
  _ = `Estymator liczby klatek na sekundę`,
  _ = `Wybierz aplikację oraz konfigurację PC, aby uzyskać wykres szacowanej liczby klatek na sekundę na podstawie częstotliwości klatek innych użytkowników Steam`,
  _ = `CPU`,
  _ = `RAM`,
  _ = `GPU`,
  _ = `Twój zapisany sprzęt`,
  _ = `Nie masz zapisanego sprzętu.`,
  _ = `Wybierz pozycję ze swojego sprzętu, aby zobaczyć szacowaną liczbę klatek na sekundę.`,
  _ = `<Nic nie wybrano>`,
  _ = `Możesz dodać swój bieżący sprzęt, jeśli używasz tej funkcji w kliencie Steam.`,
  _ = `Dodaj zapisany sprzęt`,
  _ = `Dodaj zapisany sprzęt (nie w kliencie)`,
  _ = `Jeśli chcesz udostępniać zanonimizowane dane dla estymatora częstotliwości klatek i pomóc uczynić go bardziej pomocnym dla wszystkich, możesz odwiedzić swoje preferencje, klikając poniższy link i przystąpić do udostępniania w sekcji zbierania danych.`,
  _ = `Preferencje`,
  _ = `FPS`,
  _ = `Wyszukaj grę`,
  _ = `Wybierz CPU`,
  _ = `Wybierz GPU`,
  _ = `Liczba pasujących egzemplarzy gry użytych do uczenia maszynowego`,
  _ = `Liczba pasujących egzemplarzy CPU użytych do uczenia maszynowego`,
  _ = `Liczba pasujących egzemplarzy GPU użytych do uczenia maszynowego`,
  _ = `Nieznane`,
  _ = `Wyślij kartę podarunkową`,
  _ = ``,
  _ = {
    BundleList_SubTitle: _,
    BundleList_SortBy: _,
    BundleList_SortBy_Popular: _,
    BundleList_SortBy_Price: _,
    BundleList_SortBy_Discount: _,
    BundleList_SortBy_Name: _,
    BundleList_SortBy_Recommend: _,
    BundleList_AllInLibrary: _,
    BundleList_AllInLibrarySubtitle: _,
    BundleList_CompleteTheSet: _,
    BundleList_CompleteTheSetSubtitle: _,
    BundleList_MustPurchaseAsSet: _,
    BundleList_MustPurchaseAsSetSubtitle: _,
    footer_legal_notice: _,
    footer_vat_included: _,
    footer_privacy_policy: _,
    footer_legal: _,
    footer_accessibility: _,
    footer_ssa: _,
    footer_refunds: _,
    footer_cookies: _,
    footer_about_valve: _,
    footer_business_solutions: _,
    footer_recycling: _,
    footer_steamworks: _,
    footer_source_engine: _,
    footer_jobs: _,
    footer_walletcode: _,
    footer_steam_distribution: _,
    footer_nav_help_support: _,
    wishlist_title: _,
    wishlist_header: _,
    cart_count: _,
    cart_view_cart: _,
    wishlist_count: _,
    wishlist_options_button: _,
    wishlist_sortby_button: _,
    wishlist_share_tooltip: _,
    wishlist_controls_sortby_order: _,
    wishlist_controls_sortby_their_order: _,
    wishlist_controls_sortby_topsellers: _,
    wishlist_controls_sortby_releasedate: _,
    wishlist_controls_sortby_dateadded: _,
    wishlist_controls_sortby_reviews: _,
    wishlist_controls_sortby_price: _,
    wishlist_controls_sortby_name: _,
    wishlist_controls_sortby_discount: _,
    wishlist_controls_share_dialog_title: _,
    wishlist_controls_share_revokeall: _,
    wishlist_controls_share_revokeall_success: _,
    wishlist_controls_share_generation_failure: _,
    wishlist_controls_share_description: _,
    wishlist_controls_options_category_view: _,
    wishlist_controls_options_view_expanded: _,
    wishlist_controls_options_view_compact: _,
    wishlist_controls_options_category_platform: _,
    wishlist_controls_options_platform_all: _,
    wishlist_controls_options_platform_mac: _,
    wishlist_controls_options_platform_linux: _,
    wishlist_controls_options_category_type: _,
    wishlist_controls_options_type_game: `Gry`,
    wishlist_controls_options_type_application: _,
    wishlist_controls_options_type_dlc: `DLC`,
    wishlist_controls_options_type_video: _,
    wishlist_controls_options_category_price: _,
    wishlist_controls_options_category_discount: _,
    wishlist_controls_options_discount_all: _,
    wishlist_controls_options_discount_any: _,
    wishlist_controls_options_discount_or_more: _,
    wishlist_controls_options_price_any: _,
    wishlist_controls_options_price_max_price: _,
    wishlist_controls_options_price_free: _,
    wishlist_controls_options_category_exclude: _,
    wishlist_controls_options_category_related: _,
    genre_early_access: _,
    wishlist_controls_early_access_tooltip: _,
    category_prerelease: _,
    wishlist_controls_options_exclude_vr: _,
    wishlist_controls_demo_available: _,
    wishlist_controls_demo_available_tooltip: _,
    wishlist_controls_options_category_deck: _,
    wishlist_controls_options_deck_verified: _,
    wishlist_controls_options_deck_playable: _,
    wishlist_controls_options_category_tag: `Tag`,
    wishlist_controls_tag_description: _,
    wishlist_controls_tags_header: _,
    wishlist_controls_filter_tag_label: _,
    wishlist_controls_options_category_category: _,
    wishlist_controls_categories_header_anonymous: _,
    wishlist_controls_categories_multiselect_label: _,
    wishlist_controls_categories_add: _,
    wishlist_categories_advanced_title: _,
    wishlist_categories_advanced_select: _,
    wishlist_categories_advanced_rename_label: _,
    wishlist_categories_advanced_rename_save: _,
    wishlist_categories_advanced_rename_duplicate: _,
    wishlist_categories_advanced_rename_failed: _,
    wishlist_categories_advanced_no_items: _,
    wishlist_categories_advanced_select_all: _,
    wishlist_categories_advanced_select_none: _,
    wishlist_categories_advanced_showing: _,
    wishlist_categories_advanced_failed_items: _,
    wishlist_categories_advanced_failed_items_Plural: _,
    wishlist_categories_advanced_pending: _,
    wishlist_categories_advanced_pending_adds: _,
    wishlist_categories_advanced_pending_removals: _,
    wishlist_categories_advanced_revert: _,
    wishlist_categories_advanced_apply: _,
    wishlist_categories_advanced_addremove_title: _,
    wishlist_displayed_item_count: _,
    wishlist_displayed_item_count_Plural: _,
    wishlist_filter_results: _,
    wishlist_filter_matches_items: _,
    wishlist_filter_matches_items_Plural: _,
    wishlist_filter_matches_category: _,
    wishlist_filter_matches_category_Plural: _,
    wishlist_filter_matches_categories: _,
    wishlist_filter_matches_categories_Plural: _,
    wishlist_filter_matches_tag: _,
    wishlist_filter_matches_tag_Plural: _,
    wishlist_filter_matches_tags: _,
    wishlist_filter_matches_tags_Plural: _,
    wishlist_search: _,
    wishlist_search_all: _,
    wishlist_item_overallreviews: _,
    wishlist_item_languagespecific_reviews: _,
    wishlist_item_releasedate: _,
    wishlist_item_addedon_date: _,
    wishlist_item_remove: _,
    wishlist_item_remove_tooltip: _,
    wishlist_item_unavailable_title: _,
    wishlist_item_unavailable_region: _,
    wishlist_item_unavailable_retired: _,
    mature_content_requires_creditcard: _,
    mature_content_requires_creditcard_gb: _,
    wishlist_item_add_credit_card: _,
    wishlist_your_wishlist_empty: _,
    wishlist_browse_the_store: _,
    wishlist_learn_more_button: _,
    wishlist_sign_in_to_see_your_wishlist: _,
    wishlist_others_wishlist_empty: _,
    wishlist_no_items_matching_filters: _,
    wishlist_x_items_on_wishlist_but_none_match: _,
    wishlist_x_items_on_wishlist_but_none_match_prefs: _,
    wishlist_gamepaddragdrop_reorderaction: _,
    wishlist_gamepaddragdrop_cancelreorder: _,
    wishlist_gamepaddragdrop_commitreorder: _,
    wishlist_gamepad_options: _,
    wishlist_gamepad_options_remove: _,
    wishlist_gamepad_visitstore: _,
    wishlist_errorpage_title: _,
    errorpage_error: _,
    errorpage_unknownerror: _,
    wishlist_error_profilenotfound: _,
    wishlist_error_wishlistunavailable: _,
    wishlist_error_invalidsharetoken: _,
    wishlist_filters_notification: _,
    youraccount_users_account: _,
    youraccount_errorpage_title: _,
    youraccount_account: _,
    m_home: _,
    global_menu_account_details: _,
    global_menu_account_preferences: _,
    global_menu_account_language_preferences: _,
    global_menu_account_notification_settings: _,
    global_menu_account_hardware_used: _,
    global_menu_account_security_devices: _,
    global_menu_account_video_authorized_devices: _,
    global_menu_account_mobile_game_devices: _,
    global_menu_account_gated_access_games: _,
    accountpreferences_familymanagement_header: _,
    CookiePreferences: _,
    global_menu_vr: `VR`,
    global_menu_greatondeck: _,
    global_menu_localplayonframe: _,
    store_tab_foryou_store_home: _,
    browse_categories: _,
    m_search_steam: _,
    playteststatus_error_dataunavailable: _,
    playtestinvites_title: _,
    playtestinvites_accept: _,
    playtestinvites_reject: _,
    playtestinvites_invitedescription_fromapp2: _,
    playtestinvites_invitedescription_fromapp_limitedlaunch: _,
    playtestinvites_invitedescription_fromuser2: _,
    playtestinvites_invitedescription_fromuser_limitedlaunch: _,
    playtestinvites_noinvites: _,
    playtestinvites_welcome: _,
    playtestinvites_welcome_limitedlaunch: _,
    playtestinvites_welcome_notplayable: _,
    playtestinvites_viewlibrary: _,
    playtestinvites_desc_title: _,
    playtestinvites_desc1: _,
    playtestinvites_desc2: _,
    playtestinvites_ignored_title: _,
    playtestinvites_ignored_desc: _,
    playtestinvites_ignored_remove: _,
    playtestinvites_sendinvite_cancel: _,
    playtestinvites_sendinvite_send: _,
    playtestinvites_sendinvite_lastinvite: _,
    playtestinvites_sendinvite_lastinvite_limitedlaunch: _,
    playtestinvites_sendinvite_confirm_desc: _,
    playtestinvites_sendinvite_pending: _,
    playtestinvites_sendinvite_success: _,
    playtestinvites_sendinvite_failure: _,
    playtestinvitehistory_title: _,
    playtestinvitehistory_desc: _,
    playtestinvitehistory_invite_detail: _,
    playteststatus_title: _,
    playteststatus_none: _,
    playteststatus_invites_available: _,
    playteststatus_invite_count: _,
    playteststatus_invite_count_plural: _,
    playteststatus_invite_count_tooltip: _,
    playteststatus_invite_count_tooltip2: _,
    playteststatus_details_moreinfo: _,
    playteststatus_details_moreinfo_storepage: _,
    playteststatus_details_moreinfo_newshub: _,
    playteststatus_details_notplayable: _,
    playteststatus_details_allinvitesused: _,
    playteststatus_invitefriends: _,
    playteststatus_invitefrienddialog_header: _,
    playteststatus_invitefrienddialog_search_placeholder: _,
    playteststatus_invitefrienddialog_loadingerror: _,
    playteststatus_invitefrienddialog_ineligiblefriends: _,
    playteststatus_invitefrienddialog_ineligiblefriends_purchaser: _,
    gatedaccess_limitedlaunch_badge: _,
    gatedaccess_limitedlaunch_invite_count_tooltip: _,
    gatedaccess_limitedlaunch_details_moreinfo: _,
    gatedaccess_limitedlaunch_desc_title: _,
    gatedaccess_limitedlaunch_desc: _,
    sitemap_title: _,
    sitemap_home: _,
    sitemap_section_account: _,
    sitemap_section_account_account_details: _,
    sitemap_section_account_store_preferences: _,
    sitemap_section_account_family_management: _,
    sitemap_section_account_security_and_devices: _,
    sitemap_section_account_language_preferences: _,
    sitemap_section_account_cookes_and_browsing: _,
    sitemap_section_account_notification_settings: _,
    sitemap_section_account_cart: _,
    sitemap_section_account_cart_with_count: _,
    sitemap_section_account_wishlist: _,
    sitemap_section_account_wishlist_with_count: _,
    sitemap_section_account_followed_games: _,
    sitemap_section_account_followed_games_with_count: _,
    sitemap_section_chartsandlists: _,
    sitemap_section_chartsandlists_top_sellers: _,
    sitemap_section_chartsandlists_most_played: _,
    sitemap_section_chartsandlists_new_releases: _,
    sitemap_section_chartsandlists_upcoming_releases: _,
    sitemap_section_chartsandlists_free_to_play: _,
    sitemap_section_chartsandlists_steam_charts: _,
    sitemap_section_chartsandlists_on_sale_now: _,
    sitemap_section_recommendations: _,
    sitemap_section_recommendations_discovery_queue: _,
    sitemap_section_recommendations_new_releases_queue: _,
    sitemap_section_recommendations_community_recommendations: _,
    sitemap_section_recommendations_interactive_recommender: _,
    sitemap_section_recommendations_popular_among_friends: _,
    sitemap_section_recommendations_steam_curators: _,
    sitemap_section_recommendations_dlc_for_you: _,
    sitemap_section_hardware: _,
    sitemap_section_hardware_steam_deck: _,
    sitemap_section_hardware_steam_deck_dock: _,
    sitemap_section_hardware_vr_hardware: _,
    sitemap_section_hardware_vr_games: _,
    sitemap_section_hardware_great_on_deck: _,
    sitemap_section_hardware_controller_friendly: _,
    sitemap_section_waystoplay: _,
    sitemap_section_newsupdates: _,
    sitemap_section_newsupdates_recently_updated: _,
    sitemap_section_newsupdates_your_recently_updated: _,
    sitemap_section_newsupdates_your_upcoming_events: _,
    sitemap_section_newsupdates_featured_news: _,
    sitemap_section_newsupdates_steam_official_news: _,
    sitemap_section_promosandevents: _,
    sitemap_section_promosandevents_special_offers: _,
    sitemap_section_promosandevents_sale_events: _,
    sitemap_section_promosandevents_steam_replay: _,
    sitemap_section_promosandevents_steam_next_fest: _,
    sitemap_section_promosandevents_steam_awards: _,
    sitemap_section_specialsections: _,
    sitemap_pointsshop: _,
    sitemap_giftcards: _,
    sitemap_genres: _,
    sitemap_themes: _,
    Error_RateLimited: _,
    Discussions_ForumName_General: _,
    Discussions_ForumName_ReportedPosts: _,
    Discussions_ForumName_Workshop: _,
    Discussions_ForumName_Trading: _,
    Discussions_ForumName_Events: _,
    ir_name: _,
    ir_header: _,
    ir_body: _,
    ir_playtime_header: _,
    ir_playtime_games: _,
    ir_playtime_topgames: _,
    ir_playtime_recentgames: _,
    ir_playtime_hours: _,
    ir_playtime_hourstotal: _,
    ir_playtime_lastplayed: _,
    ir_playtime_lastplayedmax: _,
    ir_playtime_unignore: _,
    ir_playtime_ignore: _,
    ir_popularity_title: _,
    ir_popularity_popular: _,
    ir_popularity_niche: _,
    ir_recency_title: _,
    ir_recency_older: _,
    ir_recency_newer: _,
    ir_filter_age_all: _,
    ir_filter_age_60: _,
    ir_filter_age_36: _,
    ir_filter_age_24: _,
    ir_filter_age_12: _,
    ir_filter_age_6: _,
    ir_recommendations_header: _,
    ir_release_date: _,
    ir_on_wishlist: _,
    ir_add_to_cart: _,
    ir_add_to_wishlist: _,
    ir_free_to_play: _,
    ir_tag_placeholder: _,
    ir_tag_filter: _,
    ir_tag_exclude: _,
    ir_no_wishlisted: _,
    ir_discounted_only: _,
    PersonalCalendar_LastMonthGames: _,
    PersonalCalendar_LastWeekGames: _,
    PersonalCalendar_Upcoming: _,
    PersonalCalendar_Title: _,
    PersonalCalendar_Description: _,
    PersonalCalendar_TagSelector: _,
    PersonalCalendar_TagSelector_Placeholder: _,
    PersonalCalendar_HideOwned: _,
    PersonalCalendar_HideEATooltip: _,
    PersonalCalendar_HideEarlyAccess: _,
    PersonalCalendar_ShowOnlyWishlisted: _,
    PersonalCalendar_ResultCountSelector: _,
    PersonalCalendar_CompactMode: _,
    PersonalCalendar_AccountPlaceholder: _,
    PersonalCalendar_Account: _,
    PersonalCalendar_ShowMore: _,
    PersonalCalendar_LoginPrompt: _,
    PersonalCalendar_ShowAll: _,
    PersonalCalendar_SteamLabs: _,
    PersonalCalendar_Wishlisted: _,
    PersonalCalendar_WishlistShow: _,
    PersonalCalendar_WishlistHide: _,
    PersonalCalendar_WishlistOnly: _,
    PersonalCalendar_IgnoringWishlists: _,
    PersonalCalendar_Error_Backend: _,
    BundleList_Title: _,
    BundleList_Title_Fallback: _,
    BundleList_Page: _,
    Verification_DeckOnly: _,
    Verification_DeckOnly_Desc: _,
    FatalErrorPage_Title: _,
    FatalErrorPage_Header: _,
    FatalErrorPage_Message: _,
    pressoutlets_error_slots_gt_zero: _,
    pressoutlets_error_domain_used: _,
    pressoutlets_error_adding_outlet: _,
    pressoutlets_error_domain_empty: _,
    pressoutlets_error_invalid_domain: _,
    pressoutlets_error_already_owned: _,
    pressoutlets_error_generic_add_error: _,
    pressoutlets_email_domain_label: _,
    pressoutlets_slots_label: _,
    pressoutlets_button_add: _,
    pressoutlets_label_add_outlet: _,
    pressoutlets_outlet_header: _,
    pressoutlets_show_history: _,
    pressoutlets_history_title: _,
    pressoutlets_action_granted: _,
    pressoutlets_action_removed: _,
    pressoutlets_action_created: _,
    pressoutlets_action_updated: _,
    pressoutlets_action_updated_domain_changed: _,
    pressoutlets_action_updated_slots_changed: _,
    pressoutlets_action_deleted: _,
    pressoutlets_action_undeleted: _,
    pressoutlets_action_enterstaging: _,
    pressoutlets_action_exitstaging: _,
    pressoutlets_action_stagedadd: _,
    pressoutlets_action_stageddelete: _,
    pressoutlets_action_by_support: _,
    pressoutlets_header_grantee: _,
    pressoutlets_header_granted_at: _,
    pressoutlets_header_is_group_admin: _,
    pressoutlets_steamid_to_add: _,
    pressoutlets_button_ok: `OK`,
    pressoutlets_button_cancel: _,
    pressoutlets_is_group_admin: `Tak`,
    pressoutlets_is_not_group_admin: `Nie`,
    pressoutlets_filter_all: _,
    pressoutlets_filter_active: _,
    pressoutlets_filter_deleted: _,
    pressoutlets_filter_empty: _,
    pressoutlets_filter_noadmins: _,
    pressoutlets_outlet_header_prefix: _,
    pressoutlets_friendcode: _,
    pressoutlets_resign_your_key: _,
    pressoutlets_resign_your_key_title: _,
    pressoutlets_history_header: _,
    pressoutlets_button_add_member: _,
    pressoutlets_button_show_history: _,
    pressoutlets_header_account: _,
    trailerassets_invalidfile: _,
    trailerassets_trailer: _,
    trailerassets_microtrailer: _,
    account_notification_settings_error_saving: _,
    account_notification_settings_error_loading: _,
    account_notification_settings_error_invalidoptouttoken: _,
    account_notification_settings_feed_disabled: _,
    account_notification_settings_wishlist_categories_persona: _,
    framerate_title: _,
    framerate_subheader: _,
    framerate_cpu: `CPU`,
    framerate_ram: `RAM`,
    framerate_gpu: `GPU`,
    framerate_saved_hardware: _,
    framerate_saved_hardware_none: _,
    framerate_saved_hardware_select: _,
    framerate_saved_hardware_option_none: _,
    framerate_saved_add: _,
    framerate_saved_add_btn: _,
    framerate_saved_add_not_in_client_btn: _,
    framerate_opt_in_data_collection_desc: _,
    framerate_opt_in_link: _,
    framerate_fps: `FPS`,
    framerate_game_name: _,
    framerate_select_cpu: _,
    framerate_select_gpu: _,
    framerate_training_game: _,
    framerate_training_cpu: _,
    framerate_training_gpu: _,
    generic_unknown: _,
    giftcards_banner_text: _,
    empty_no_trailing_comma: ``,
  };
export {
  _ as BundleList_AllInLibrary,
  _ as BundleList_AllInLibrarySubtitle,
  _ as BundleList_CompleteTheSet,
  _ as BundleList_CompleteTheSetSubtitle,
  _ as BundleList_MustPurchaseAsSet,
  _ as BundleList_MustPurchaseAsSetSubtitle,
  _ as BundleList_Page,
  _ as BundleList_SortBy,
  _ as BundleList_SortBy_Discount,
  _ as BundleList_SortBy_Name,
  _ as BundleList_SortBy_Popular,
  _ as BundleList_SortBy_Price,
  _ as BundleList_SortBy_Recommend,
  _ as BundleList_SubTitle,
  _ as BundleList_Title,
  _ as BundleList_Title_Fallback,
  _ as CookiePreferences,
  _ as Discussions_ForumName_Events,
  _ as Discussions_ForumName_General,
  _ as Discussions_ForumName_ReportedPosts,
  _ as Discussions_ForumName_Trading,
  _ as Discussions_ForumName_Workshop,
  _ as Error_RateLimited,
  _ as FatalErrorPage_Header,
  _ as FatalErrorPage_Message,
  _ as FatalErrorPage_Title,
  _ as PersonalCalendar_Account,
  _ as PersonalCalendar_AccountPlaceholder,
  _ as PersonalCalendar_CompactMode,
  _ as PersonalCalendar_Description,
  _ as PersonalCalendar_Error_Backend,
  _ as PersonalCalendar_HideEATooltip,
  _ as PersonalCalendar_HideEarlyAccess,
  _ as PersonalCalendar_HideOwned,
  _ as PersonalCalendar_IgnoringWishlists,
  _ as PersonalCalendar_LastMonthGames,
  _ as PersonalCalendar_LastWeekGames,
  _ as PersonalCalendar_LoginPrompt,
  _ as PersonalCalendar_ResultCountSelector,
  _ as PersonalCalendar_ShowAll,
  _ as PersonalCalendar_ShowMore,
  _ as PersonalCalendar_ShowOnlyWishlisted,
  _ as PersonalCalendar_SteamLabs,
  _ as PersonalCalendar_TagSelector,
  _ as PersonalCalendar_TagSelector_Placeholder,
  _ as PersonalCalendar_Title,
  _ as PersonalCalendar_Upcoming,
  _ as PersonalCalendar_WishlistHide,
  _ as PersonalCalendar_WishlistOnly,
  _ as PersonalCalendar_WishlistShow,
  _ as PersonalCalendar_Wishlisted,
  _ as Verification_DeckOnly,
  _ as Verification_DeckOnly_Desc,
  _ as account_notification_settings_error_invalidoptouttoken,
  _ as account_notification_settings_error_loading,
  _ as account_notification_settings_error_saving,
  _ as account_notification_settings_feed_disabled,
  _ as account_notification_settings_wishlist_categories_persona,
  _ as accountpreferences_familymanagement_header,
  _ as browse_categories,
  _ as cart_count,
  _ as cart_view_cart,
  _ as category_prerelease,
  _ as default,
  _ as empty_no_trailing_comma,
  _ as errorpage_error,
  _ as errorpage_unknownerror,
  _ as footer_about_valve,
  _ as footer_accessibility,
  _ as footer_business_solutions,
  _ as footer_cookies,
  _ as footer_jobs,
  _ as footer_legal,
  _ as footer_legal_notice,
  _ as footer_nav_help_support,
  _ as footer_privacy_policy,
  _ as footer_recycling,
  _ as footer_refunds,
  _ as footer_source_engine,
  _ as footer_ssa,
  _ as footer_steam_distribution,
  _ as footer_steamworks,
  _ as footer_vat_included,
  _ as footer_walletcode,
  _ as framerate_cpu,
  _ as framerate_fps,
  _ as framerate_game_name,
  _ as framerate_gpu,
  _ as framerate_opt_in_data_collection_desc,
  _ as framerate_opt_in_link,
  _ as framerate_ram,
  _ as framerate_saved_add,
  _ as framerate_saved_add_btn,
  _ as framerate_saved_add_not_in_client_btn,
  _ as framerate_saved_hardware,
  _ as framerate_saved_hardware_none,
  _ as framerate_saved_hardware_option_none,
  _ as framerate_saved_hardware_select,
  _ as framerate_select_cpu,
  _ as framerate_select_gpu,
  _ as framerate_subheader,
  _ as framerate_title,
  _ as framerate_training_cpu,
  _ as framerate_training_game,
  _ as framerate_training_gpu,
  _ as gatedaccess_limitedlaunch_badge,
  _ as gatedaccess_limitedlaunch_desc,
  _ as gatedaccess_limitedlaunch_desc_title,
  _ as gatedaccess_limitedlaunch_details_moreinfo,
  _ as gatedaccess_limitedlaunch_invite_count_tooltip,
  _ as generic_unknown,
  _ as genre_early_access,
  _ as giftcards_banner_text,
  _ as global_menu_account_details,
  _ as global_menu_account_gated_access_games,
  _ as global_menu_account_hardware_used,
  _ as global_menu_account_language_preferences,
  _ as global_menu_account_mobile_game_devices,
  _ as global_menu_account_notification_settings,
  _ as global_menu_account_preferences,
  _ as global_menu_account_security_devices,
  _ as global_menu_account_video_authorized_devices,
  _ as global_menu_greatondeck,
  _ as global_menu_localplayonframe,
  _ as global_menu_vr,
  _ as ir_add_to_cart,
  _ as ir_add_to_wishlist,
  _ as ir_body,
  _ as ir_discounted_only,
  _ as ir_filter_age_12,
  _ as ir_filter_age_24,
  _ as ir_filter_age_36,
  _ as ir_filter_age_6,
  _ as ir_filter_age_60,
  _ as ir_filter_age_all,
  _ as ir_free_to_play,
  _ as ir_header,
  _ as ir_name,
  _ as ir_no_wishlisted,
  _ as ir_on_wishlist,
  _ as ir_playtime_games,
  _ as ir_playtime_header,
  _ as ir_playtime_hours,
  _ as ir_playtime_hourstotal,
  _ as ir_playtime_ignore,
  _ as ir_playtime_lastplayed,
  _ as ir_playtime_lastplayedmax,
  _ as ir_playtime_recentgames,
  _ as ir_playtime_topgames,
  _ as ir_playtime_unignore,
  _ as ir_popularity_niche,
  _ as ir_popularity_popular,
  _ as ir_popularity_title,
  _ as ir_recency_newer,
  _ as ir_recency_older,
  _ as ir_recency_title,
  _ as ir_recommendations_header,
  _ as ir_release_date,
  _ as ir_tag_exclude,
  _ as ir_tag_filter,
  _ as ir_tag_placeholder,
  _ as m_home,
  _ as m_search_steam,
  _ as mature_content_requires_creditcard,
  _ as mature_content_requires_creditcard_gb,
  _ as playtestinvitehistory_desc,
  _ as playtestinvitehistory_invite_detail,
  _ as playtestinvitehistory_title,
  _ as playtestinvites_accept,
  _ as playtestinvites_desc1,
  _ as playtestinvites_desc2,
  _ as playtestinvites_desc_title,
  _ as playtestinvites_ignored_desc,
  _ as playtestinvites_ignored_remove,
  _ as playtestinvites_ignored_title,
  _ as playtestinvites_invitedescription_fromapp2,
  _ as playtestinvites_invitedescription_fromapp_limitedlaunch,
  _ as playtestinvites_invitedescription_fromuser2,
  _ as playtestinvites_invitedescription_fromuser_limitedlaunch,
  _ as playtestinvites_noinvites,
  _ as playtestinvites_reject,
  _ as playtestinvites_sendinvite_cancel,
  _ as playtestinvites_sendinvite_confirm_desc,
  _ as playtestinvites_sendinvite_failure,
  _ as playtestinvites_sendinvite_lastinvite,
  _ as playtestinvites_sendinvite_lastinvite_limitedlaunch,
  _ as playtestinvites_sendinvite_pending,
  _ as playtestinvites_sendinvite_send,
  _ as playtestinvites_sendinvite_success,
  _ as playtestinvites_title,
  _ as playtestinvites_viewlibrary,
  _ as playtestinvites_welcome,
  _ as playtestinvites_welcome_limitedlaunch,
  _ as playtestinvites_welcome_notplayable,
  _ as playteststatus_details_allinvitesused,
  _ as playteststatus_details_moreinfo,
  _ as playteststatus_details_moreinfo_newshub,
  _ as playteststatus_details_moreinfo_storepage,
  _ as playteststatus_details_notplayable,
  _ as playteststatus_error_dataunavailable,
  _ as playteststatus_invite_count,
  _ as playteststatus_invite_count_plural,
  _ as playteststatus_invite_count_tooltip,
  _ as playteststatus_invite_count_tooltip2,
  _ as playteststatus_invitefrienddialog_header,
  _ as playteststatus_invitefrienddialog_ineligiblefriends,
  _ as playteststatus_invitefrienddialog_ineligiblefriends_purchaser,
  _ as playteststatus_invitefrienddialog_loadingerror,
  _ as playteststatus_invitefrienddialog_search_placeholder,
  _ as playteststatus_invitefriends,
  _ as playteststatus_invites_available,
  _ as playteststatus_none,
  _ as playteststatus_title,
  _ as pressoutlets_action_by_support,
  _ as pressoutlets_action_created,
  _ as pressoutlets_action_deleted,
  _ as pressoutlets_action_enterstaging,
  _ as pressoutlets_action_exitstaging,
  _ as pressoutlets_action_granted,
  _ as pressoutlets_action_removed,
  _ as pressoutlets_action_stagedadd,
  _ as pressoutlets_action_stageddelete,
  _ as pressoutlets_action_undeleted,
  _ as pressoutlets_action_updated,
  _ as pressoutlets_action_updated_domain_changed,
  _ as pressoutlets_action_updated_slots_changed,
  _ as pressoutlets_button_add,
  _ as pressoutlets_button_add_member,
  _ as pressoutlets_button_cancel,
  _ as pressoutlets_button_ok,
  _ as pressoutlets_button_show_history,
  _ as pressoutlets_email_domain_label,
  _ as pressoutlets_error_adding_outlet,
  _ as pressoutlets_error_already_owned,
  _ as pressoutlets_error_domain_empty,
  _ as pressoutlets_error_domain_used,
  _ as pressoutlets_error_generic_add_error,
  _ as pressoutlets_error_invalid_domain,
  _ as pressoutlets_error_slots_gt_zero,
  _ as pressoutlets_filter_active,
  _ as pressoutlets_filter_all,
  _ as pressoutlets_filter_deleted,
  _ as pressoutlets_filter_empty,
  _ as pressoutlets_filter_noadmins,
  _ as pressoutlets_friendcode,
  _ as pressoutlets_header_account,
  _ as pressoutlets_header_granted_at,
  _ as pressoutlets_header_grantee,
  _ as pressoutlets_header_is_group_admin,
  _ as pressoutlets_history_header,
  _ as pressoutlets_history_title,
  _ as pressoutlets_is_group_admin,
  _ as pressoutlets_is_not_group_admin,
  _ as pressoutlets_label_add_outlet,
  _ as pressoutlets_outlet_header,
  _ as pressoutlets_outlet_header_prefix,
  _ as pressoutlets_resign_your_key,
  _ as pressoutlets_resign_your_key_title,
  _ as pressoutlets_show_history,
  _ as pressoutlets_slots_label,
  _ as pressoutlets_steamid_to_add,
  _ as sitemap_genres,
  _ as sitemap_giftcards,
  _ as sitemap_home,
  _ as sitemap_pointsshop,
  _ as sitemap_section_account,
  _ as sitemap_section_account_account_details,
  _ as sitemap_section_account_cart,
  _ as sitemap_section_account_cart_with_count,
  _ as sitemap_section_account_cookes_and_browsing,
  _ as sitemap_section_account_family_management,
  _ as sitemap_section_account_followed_games,
  _ as sitemap_section_account_followed_games_with_count,
  _ as sitemap_section_account_language_preferences,
  _ as sitemap_section_account_notification_settings,
  _ as sitemap_section_account_security_and_devices,
  _ as sitemap_section_account_store_preferences,
  _ as sitemap_section_account_wishlist,
  _ as sitemap_section_account_wishlist_with_count,
  _ as sitemap_section_chartsandlists,
  _ as sitemap_section_chartsandlists_free_to_play,
  _ as sitemap_section_chartsandlists_most_played,
  _ as sitemap_section_chartsandlists_new_releases,
  _ as sitemap_section_chartsandlists_on_sale_now,
  _ as sitemap_section_chartsandlists_steam_charts,
  _ as sitemap_section_chartsandlists_top_sellers,
  _ as sitemap_section_chartsandlists_upcoming_releases,
  _ as sitemap_section_hardware,
  _ as sitemap_section_hardware_controller_friendly,
  _ as sitemap_section_hardware_great_on_deck,
  _ as sitemap_section_hardware_steam_deck,
  _ as sitemap_section_hardware_steam_deck_dock,
  _ as sitemap_section_hardware_vr_games,
  _ as sitemap_section_hardware_vr_hardware,
  _ as sitemap_section_newsupdates,
  _ as sitemap_section_newsupdates_featured_news,
  _ as sitemap_section_newsupdates_recently_updated,
  _ as sitemap_section_newsupdates_steam_official_news,
  _ as sitemap_section_newsupdates_your_recently_updated,
  _ as sitemap_section_newsupdates_your_upcoming_events,
  _ as sitemap_section_promosandevents,
  _ as sitemap_section_promosandevents_sale_events,
  _ as sitemap_section_promosandevents_special_offers,
  _ as sitemap_section_promosandevents_steam_awards,
  _ as sitemap_section_promosandevents_steam_next_fest,
  _ as sitemap_section_promosandevents_steam_replay,
  _ as sitemap_section_recommendations,
  _ as sitemap_section_recommendations_community_recommendations,
  _ as sitemap_section_recommendations_discovery_queue,
  _ as sitemap_section_recommendations_dlc_for_you,
  _ as sitemap_section_recommendations_interactive_recommender,
  _ as sitemap_section_recommendations_new_releases_queue,
  _ as sitemap_section_recommendations_popular_among_friends,
  _ as sitemap_section_recommendations_steam_curators,
  _ as sitemap_section_specialsections,
  _ as sitemap_section_waystoplay,
  _ as sitemap_themes,
  _ as sitemap_title,
  _ as store_tab_foryou_store_home,
  _ as trailerassets_invalidfile,
  _ as trailerassets_microtrailer,
  _ as trailerassets_trailer,
  _ as wishlist_browse_the_store,
  _ as wishlist_categories_advanced_addremove_title,
  _ as wishlist_categories_advanced_apply,
  _ as wishlist_categories_advanced_failed_items,
  _ as wishlist_categories_advanced_failed_items_Plural,
  _ as wishlist_categories_advanced_no_items,
  _ as wishlist_categories_advanced_pending,
  _ as wishlist_categories_advanced_pending_adds,
  _ as wishlist_categories_advanced_pending_removals,
  _ as wishlist_categories_advanced_rename_duplicate,
  _ as wishlist_categories_advanced_rename_failed,
  _ as wishlist_categories_advanced_rename_label,
  _ as wishlist_categories_advanced_rename_save,
  _ as wishlist_categories_advanced_revert,
  _ as wishlist_categories_advanced_select,
  _ as wishlist_categories_advanced_select_all,
  _ as wishlist_categories_advanced_select_none,
  _ as wishlist_categories_advanced_showing,
  _ as wishlist_categories_advanced_title,
  _ as wishlist_controls_categories_add,
  _ as wishlist_controls_categories_header_anonymous,
  _ as wishlist_controls_categories_multiselect_label,
  _ as wishlist_controls_demo_available,
  _ as wishlist_controls_demo_available_tooltip,
  _ as wishlist_controls_early_access_tooltip,
  _ as wishlist_controls_filter_tag_label,
  _ as wishlist_controls_options_category_category,
  _ as wishlist_controls_options_category_deck,
  _ as wishlist_controls_options_category_discount,
  _ as wishlist_controls_options_category_exclude,
  _ as wishlist_controls_options_category_platform,
  _ as wishlist_controls_options_category_price,
  _ as wishlist_controls_options_category_related,
  _ as wishlist_controls_options_category_tag,
  _ as wishlist_controls_options_category_type,
  _ as wishlist_controls_options_category_view,
  _ as wishlist_controls_options_deck_playable,
  _ as wishlist_controls_options_deck_verified,
  _ as wishlist_controls_options_discount_all,
  _ as wishlist_controls_options_discount_any,
  _ as wishlist_controls_options_discount_or_more,
  _ as wishlist_controls_options_exclude_vr,
  _ as wishlist_controls_options_platform_all,
  _ as wishlist_controls_options_platform_linux,
  _ as wishlist_controls_options_platform_mac,
  _ as wishlist_controls_options_price_any,
  _ as wishlist_controls_options_price_free,
  _ as wishlist_controls_options_price_max_price,
  _ as wishlist_controls_options_type_application,
  _ as wishlist_controls_options_type_dlc,
  _ as wishlist_controls_options_type_game,
  _ as wishlist_controls_options_type_video,
  _ as wishlist_controls_options_view_compact,
  _ as wishlist_controls_options_view_expanded,
  _ as wishlist_controls_share_description,
  _ as wishlist_controls_share_dialog_title,
  _ as wishlist_controls_share_generation_failure,
  _ as wishlist_controls_share_revokeall,
  _ as wishlist_controls_share_revokeall_success,
  _ as wishlist_controls_sortby_dateadded,
  _ as wishlist_controls_sortby_discount,
  _ as wishlist_controls_sortby_name,
  _ as wishlist_controls_sortby_order,
  _ as wishlist_controls_sortby_price,
  _ as wishlist_controls_sortby_releasedate,
  _ as wishlist_controls_sortby_reviews,
  _ as wishlist_controls_sortby_their_order,
  _ as wishlist_controls_sortby_topsellers,
  _ as wishlist_controls_tag_description,
  _ as wishlist_controls_tags_header,
  _ as wishlist_count,
  _ as wishlist_displayed_item_count,
  _ as wishlist_displayed_item_count_Plural,
  _ as wishlist_error_invalidsharetoken,
  _ as wishlist_error_profilenotfound,
  _ as wishlist_error_wishlistunavailable,
  _ as wishlist_errorpage_title,
  _ as wishlist_filter_matches_categories,
  _ as wishlist_filter_matches_categories_Plural,
  _ as wishlist_filter_matches_category,
  _ as wishlist_filter_matches_category_Plural,
  _ as wishlist_filter_matches_items,
  _ as wishlist_filter_matches_items_Plural,
  _ as wishlist_filter_matches_tag,
  _ as wishlist_filter_matches_tag_Plural,
  _ as wishlist_filter_matches_tags,
  _ as wishlist_filter_matches_tags_Plural,
  _ as wishlist_filter_results,
  _ as wishlist_filters_notification,
  _ as wishlist_gamepad_options,
  _ as wishlist_gamepad_options_remove,
  _ as wishlist_gamepad_visitstore,
  _ as wishlist_gamepaddragdrop_cancelreorder,
  _ as wishlist_gamepaddragdrop_commitreorder,
  _ as wishlist_gamepaddragdrop_reorderaction,
  _ as wishlist_header,
  _ as wishlist_item_add_credit_card,
  _ as wishlist_item_addedon_date,
  _ as wishlist_item_languagespecific_reviews,
  _ as wishlist_item_overallreviews,
  _ as wishlist_item_releasedate,
  _ as wishlist_item_remove,
  _ as wishlist_item_remove_tooltip,
  _ as wishlist_item_unavailable_region,
  _ as wishlist_item_unavailable_retired,
  _ as wishlist_item_unavailable_title,
  _ as wishlist_learn_more_button,
  _ as wishlist_no_items_matching_filters,
  _ as wishlist_options_button,
  _ as wishlist_others_wishlist_empty,
  _ as wishlist_search,
  _ as wishlist_search_all,
  _ as wishlist_share_tooltip,
  _ as wishlist_sign_in_to_see_your_wishlist,
  _ as wishlist_sortby_button,
  _ as wishlist_title,
  _ as wishlist_x_items_on_wishlist_but_none_match,
  _ as wishlist_x_items_on_wishlist_but_none_match_prefs,
  _ as wishlist_your_wishlist_empty,
  _ as youraccount_account,
  _ as youraccount_errorpage_title,
  _ as youraccount_users_account,
};
