var _ = `italian`,
  _ = `Gioca gratis fino a %1$s.`,
  _ = `L'offerta termina %1$s.`,
  _ = `Gioca gratis!`,
  _ = `Weekend gratis`,
  _ = `Gioca gratis fino a lunedì alle 19:00`,
  _ = `Gioca gratis fino a: %1$s`,
  _ = `Settimana gratuita`,
  _ = `Appena aggiornati`,
  _ = `SOLO PER UN PERIODO LIMITATO`,
  _ = `Preacquista per iniziare a giocare alla beta!`,
  _ = `GIOCA ALLA BETA ADESSO!`,
  _ = `Preacquista per avere accesso alla Beta`,
  _ = `Workshop di Steam disponibile ora`,
  _ = `Ora con il Workshop di Steam`,
  _ = `Ora con Steamworks`,
  _ = `Disponibile ora su SteamOS!`,
  _ = `Disponibile ora su SteamOS, Mac e Linux!`,
  _ = `Pre-scarica adesso`,
  _ = `Aggiornamento gratuito`,
  _ = `Gioca subito alla demo!`,
  _ = `Pre-scarica (gratis)`,
  _ = `Pre-scarica ora gratis`,
  _ = `Hai pre-scaricato`,
  _ = `Hai completato il pre-scaricamento`,
  _ = `Pre-scaricamento completato`,
  _ = `Preacquista ora`,
  _ = `Appena aggiornato con DLC gratuiti!`,
  _ = `Disponibile su Mac e SteamOS!`,
  _ = `A breve su SteamOS!`,
  _ = `Scarica il film e guardalo in alta definizione`,
  _ = `Aggiungi alla Lista dei desideri`,
  _ = `Accesso anticipato disponibile ora`,
  _ = `in accesso anticipato`,
  _ = `Nuovo aggiornamento disponibile`,
  _ = `Gratis`,
  _ = `Nuovo rilascio`,
  _ = `Appena uscito dall'accesso anticipato!`,
  _ = `Appena rilasciati`,
  _ = `Disponibile ora`,
  _ = `Nuovo gioco`,
  _ = `Disponibile ora - Free-to-Play`,
  _ = `Free-to-Play - Appena aggiornato`,
  _ = `Ora Free-to-Play in accesso anticipato`,
  _ = `Accesso con preacquisto disponibile`,
  _ = `Nuovo contenuto ora disponibile!`,
  _ = `Gioca gratis al gioco completo, solo per questo weekend`,
  _ = `Weekend gratis - in corso`,
  _ = `Versione di prova completa gratis`,
  _ = `Gioca ora gratis`,
  _ = `Preacquista e ricevi contenuti bonus`,
  _ = `I più venduti`,
  _ = `Nuove uscite`,
  _ = `Affare del fine settimana`,
  _ = `Affare di metà settimana`,
  _ = `Affare di metà settimana`,
  _ = `Saldi del franchise`,
  _ = `Evento di terze parti`,
  _ = `Aggiornamento importante`,
  _ = `Affare del giorno`,
  _ = `Affare della settimana`,
  _ = `Settimanali`,
  _ = `In omaggio!`,
  _ = `Per un periodo limitato, installalo ora e giocaci per sempre`,
  _ = `In arrivo`,
  _ = `Nuovi e in arrivo`,
  _ = `Offerte in evidenza`,
  _ = `Catalogo precedente`,
  _ = `Weekend dell'editore`,
  _ = `Saldi dell'editore`,
  _ = `Installa`,
  _ = `SCONTO FEDELTÀ! L'offerta termina tra %1$s`,
  _ = `Clicca per vedere i dettagli`,
  _ = `Gioca adesso`,
  _ = `Giocaci ora`,
  _ = `Acquista ora`,
  _ = `Clicca qui per ulteriori informazioni`,
  _ = `In offerta!`,
  _ = `Accesso alla beta in anteprima`,
  _ = `Nuovo DLC disponibile`,
  _ = `Scarica in anticipo adesso`,
  _ = `Sconto maggiore`,
  _ = `Offerta a tempo limitato`,
  _ = `Offerta a tempo limitato`,
  _ = `Disponibile ora`,
  _ = `Disponibile ora`,
  _ = `Disponibile ora per Mac`,
  _ = `Disponibile ora per PC, Mac e Linux!`,
  _ = `Ora Free-to-Play`,
  _ = `Nuovo gioco Free-to-Play`,
  _ = `DLC gratuito disponibile adesso`,
  _ = `Azione e sparatutto in prima persona`,
  _ = `Azione e sparatutto in prima persona`,
  _ = `Azione con visuale in 2D`,
  _ = `Azione con visuale in 2D`,
  _ = `Azione e sparatutto in terza persona`,
  _ = `Azione e sparatutto in terza persona`,
  _ = `Azione`,
  _ = `Azione`,
  _ = `Azione/avventura`,
  _ = `Azione/avventura`,
  _ = `Azione e avventura`,
  _ = `Azione e avventura`,
  _ = `Sparatutto in prima persona`,
  _ = `Sparatutto in prima persona`,
  _ = `Horror d'azione`,
  _ = `Horror d'azione`,
  _ = `Azione stile Rogue`,
  _ = `Azione stile Rogue`,
  _ = `Giochi di ruolo d'azione`,
  _ = `GDR d'azione`,
  _ = `Platform e Runner`,
  _ = `Platform e Runner`,
  _ = `Sparatutto`,
  _ = `Sparatutto`,
  _ = `Sparatutto in terza persona`,
  _ = `Sparatutto in terza persona`,
  _ = `Azioni e attività`,
  _ = `Azioni e attività`,
  _ = `Avventura`,
  _ = `Avventura`,
  _ = `Avventura e passatempo`,
  _ = `Avventura e passatempo`,
  _ = `Mondo aperto`,
  _ = `Mondo aperto`,
  _ = `Avventure punta e clicca`,
  _ = `Avventura punta e clicca`,
  _ = `GDR di avventura`,
  _ = `GDR di avventura`,
  _ = `Giochi di ruolo passatempo`,
  _ = `GDR passatempo`,
  _ = `Esteticamente piacevoli`,
  _ = `Temi`,
  _ = `Anime`,
  _ = `Anime`,
  _ = `Arcade`,
  _ = `Arcade`,
  _ = `Arcade e ritmici`,
  _ = `Arcade e ritmici`,
  _ = `Stili artistici e musicali`,
  _ = `Stili artistici e musicali`,
  _ = `Picchiaduro`,
  _ = `Picchiaduro`,
  _ = `Business e politici`,
  _ = `Business e politici`,
  _ = `Passatempo`,
  _ = `Passatempo`,
  _ = `Passatempo e da tavolo`,
  _ = `Passatempo e da tavolo`,
  _ = `Passatempo e rompicapo`,
  _ = `Passatempo e rompicapo`,
  _ = `Passatempo e narrativi`,
  _ = `Passatempo e narrativi`,
  _ = `Rompicapo passatempo`,
  _ = `Rompicapo passatempo`,
  _ = `Personaggi d'azione`,
  _ = `Clicker e incrementali`,
  _ = `Clicker e incrementale`,
  _ = `Crimine e giustizia`,
  _ = `Crimine e giustizia`,
  _ = `Carini e cartoni animati`,
  _ = `Carini e cartoni animati`,
  _ = `Simulatori di appuntamenti`,
  _ = `Simulatore di appuntamenti`,
  _ = `Guida e pilotaggio`,
  _ = `Guida e pilotaggio`,
  _ = `Scienza ed educazione`,
  _ = `Scienza ed educazione`,
  _ = `Sperimentali`,
  _ = `Sperimentali`,
  _ = `Mondo aperto`,
  _ = `Mondo aperto`,
  _ = `Fantasy`,
  _ = `Fantasy`,
  _ = `Fantasy e soprannaturali`,
  _ = `Fantasy e soprannaturali`,
  _ = `Lotta`,
  _ = `Lotta`,
  _ = `Lotta e arti marziali`,
  _ = `Lotta e arti marziali`,
  _ = `Free-to-Play`,
  _ = `Hack & slash`,
  _ = `Oggetto nascosto`,
  _ = `Oggetti nascosti`,
  _ = `Storici`,
  _ = `Horror`,
  _ = `Horror`,
  _ = `Dark e horror`,
  _ = `Dark e horror`,
  _ = `Festival Steam Scream`,
  _ = `Festival della costruzione di basi`,
  _ = `Stealth`,
  _ = `Shoot 'em up`,
  _ = `Storia ben curata`,
  _ = `Storia ben curata`,
  _ = `Interactive Stories`,
  _ = `Narrazione interattiva`,
  _ = `Simulatore di vita`,
  _ = `Ambientazioni e mondi`,
  _ = `Match 3`,
  _ = `Match 3`,
  _ = `Multi-giocatore`,
  _ = `Multigiocatore`,
  _ = `Militare e di guerra`,
  _ = `Militare e di guerra`,
  _ = `Minimalisti e astratti`,
  _ = `Minimalisti e astratti`,
  _ = `Multi-giocatore`,
  _ = `Multigiocatore`,
  _ = `Multigiocatore competitivi`,
  _ = `Competitivo`,
  _ = `Battle royale`,
  _ = `Battle Royale`,
  _ = `Co-op`,
  _ = `Co-op`,
  _ = `In rete locale`,
  _ = `LAN`,
  _ = `Multigiocatore locale e di società`,
  _ = `Locale e di società`,
  _ = `Multigiocatore di massa`,
  _ = `MMO`,
  _ = `MOBA e Combattimenti automatici`,
  _ = `MOBA e Combattimenti automatici`,
  _ = `Online competitivo`,
  _ = `Online competitivo`,
  _ = `Sparatutto multigiocatore`,
  _ = `Sparatutto`,
  _ = `Musica e Ritmici`,
  _ = `Musica e Ritmici`,
  _ = `Crafting e sopravvivenza a mondo aperto`,
  _ = `Crafting e sopravvivenza a mondo aperto`,
  _ = `Persone e Creature`,
  _ = `Giocatori`,
  _ = `Psichedelici`,
  _ = `Psichedelici`,
  _ = `Psichedelici e Surreali`,
  _ = `Psichedelici e Surreali`,
  _ = `Rompicapo`,
  _ = `Rompicapo`,
  _ = `Rompicapo`,
  _ = `Rompicapo`,
  _ = `Rompicapo difficile`,
  _ = `Rompicapo difficile`,
  _ = `Logica rompicapo`,
  _ = `Logica rompicapo`,
  _ = `Rompicapo multigiocatore`,
  _ = `Rompicapo multigiocatore`,
  _ = `Corse`,
  _ = `Gare con auto, biciclette, sci e molto altro`,
  _ = `Corse`,
  _ = `Simulazione di corse`,
  _ = `Simulatori di corse`,
  _ = `Combattimenti da corsa`,
  _ = `Combattimenti da corsa`,
  _ = `Corse e Pilotaggio`,
  _ = `Corse e Pilotaggio`,
  _ = `Retrò`,
  _ = `Retrò`,
  _ = `Rilassanti`,
  _ = `Rilassanti`,
  _ = `Metroidvania`,
  _ = `Metroidvania`,
  _ = `Minimalisti e Rilassanti`,
  _ = `Minimalisti e Rilassanti`,
  _ = `Stile Rogue a turni`,
  _ = `Stile Rogue a turni`,
  _ = `Stile Rogue e Roguelite`,
  _ = `Stile Rogue`,
  _ = `Stile Rogue`,
  _ = `Stile Rogue`,
  _ = `Di ruolo`,
  _ = `Di ruolo`,
  _ = `Giochi di ruolo d'azione`,
  _ = `GDR d'azione`,
  _ = `GDR classici`,
  _ = `GDR classici`,
  _ = `GDR classici`,
  _ = `GDR classici`,
  _ = `Dungeon crawler`,
  _ = `Dungeon crawler`,
  _ = `Giochi di ruolo giapponesi`,
  _ = `GDR giapponese`,
  _ = `Giochi di ruolo multigiocatore online di massa`,
  _ = `GDR multigiocatore di massa`,
  _ = `Giochi di ruolo con gruppo`,
  _ = `Con gruppo`,
  _ = `Giochi di ruolo dalla trama profonda`,
  _ = `Narrativi`,
  _ = `Giochi di ruolo strategici e tattici`,
  _ = `GDR strategici`,
  _ = `Giochi di ruolo con gruppo`,
  _ = `A turni`,
  _ = `Fantascienza e Cyberpunk`,
  _ = `Fantascienza e Cyberpunk`,
  _ = `Sparatutto`,
  _ = `Sparatutto`,
  _ = `Simulatori di costruzioni`,
  _ = `Costruzioni`,
  _ = `Simulatori di costruzioni e automazione`,
  _ = `Costruzioni e Automazione`,
  _ = `Business e Magnati`,
  _ = `Business e Magnati`,
  _ = `Simulatori di città e insediamenti`,
  _ = `Città e colonie`,
  _ = `Simulatori di fattoria`,
  _ = `Fattorie`,
  _ = `Simulatori di fattoria e creazione di oggetti`,
  _ = `Fattorie e Creazione di oggetti`,
  _ = `Simulatori immersivi e di vita`,
  _ = `Vita e Immersivi`,
  _ = `Simulatori di vita e romantici`,
  _ = `Vita e Romantici`,
  _ = `Simulazione e gestionali`,
  _ = `Simulazione e Gestionali`,
  _ = `Simulatori a mondo aperto`,
  _ = `Mondo aperto`,
  _ = `Sandbox e Simulatori di Fisica`,
  _ = `Sandbox e Fisica`,
  _ = `Simulatori di politica`,
  _ = `Politica`,
  _ = `Simulatori sandbox e di divinità`,
  _ = `Sandbox e divinità`,
  _ = `Simulatori spaziali e di volo`,
  _ = `Spazio e Volo`,
  _ = `Simulatori di appuntamenti`,
  _ = `Appuntamenti`,
  _ = `Simulazione`,
  _ = `Simulazione`,
  _ = `Giocatore singolo`,
  _ = `Giocatore singolo`,
  _ = `Supporto giocatore`,
  _ = `Sport`,
  _ = `Gestisci una squadra, allenati per un importante torneo o gioca semplicemente`,
  _ = `Tutti gli sport`,
  _ = `Sport e corse`,
  _ = `Sport e corse`,
  _ = `Sport con palle e palloni`,
  _ = `Sport con palle e palloni`,
  _ = `Sport di combattimenti`,
  _ = `Sport di combattimento`,
  _ = `Caccia e pesca`,
  _ = `Caccia e pesca`,
  _ = `Sport individuali`,
  _ = `Sport individuali`,
  _ = `Simulatori sportivi e sportivi gestionali`,
  _ = `Simulatori sportivi`,
  _ = `Sport di squadra`,
  _ = `Sport di squadra`,
  _ = `Sport invernali`,
  _ = `Sport invernali`,
  _ = `Paurosi`,
  _ = `Paurosi`,
  _ = `Narrativi`,
  _ = `Narrativi`,
  _ = `Strategia`,
  _ = `Strategia`,
  _ = `Di carte e da tavolo`,
  _ = `Di carte e da tavolo`,
  _ = `Costruzione di città e insediamenti`,
  _ = `Città e insediamenti`,
  _ = `Strategia su vasta scala e 4X`,
  _ = `Larga scala e 4X`,
  _ = `Strategia militare`,
  _ = `Militari`,
  _ = `MOBA e combattimenti automatici`,
  _ = `MOBA e combattimenti automatici`,
  _ = `Strategia in tempo reale`,
  _ = `Strategia in tempo reale`,
  _ = `Simulazione e Gestionali`,
  _ = `Simulazione e gestionali`,
  _ = `Strategia e tattici`,
  _ = `Strategia e tattici`,
  _ = `Strategia a turni`,
  _ = `Strategia a turni`,
  _ = `Sopravvivenza`,
  _ = `Sopravvivenza`,
  _ = `Sopravvivenza e stealth`,
  _ = `Sopravvivenza e stealth`,
  _ = `Temi`,
  _ = `Temi`,
  _ = `Temi e interessi`,
  _ = `Temi`,
  _ = `Gestione del tempo`,
  _ = `Gestione del tempo`,
  _ = `Difesa della torre`,
  _ = `Difesa della torre`,
  _ = `Racconti visivi`,
  _ = `Racconti visivi`,
  _ = `Simulatori di esplorazione`,
  _ = `Simulatore di esplorazione`,
  _ = `Spazio`,
  _ = `Spazio`,
  _ = `Protagonista femminile`,
  _ = `Protagonista femminile`,
  _ = `LGBTQ+`,
  _ = `LGBTQ+`,
  _ = `Pixel art e Retrò`,
  _ = `Pixel art e Retrò`,
  _ = `Scelte e conseguenze e incentrati sulla narrativa`,
  _ = `Scelte e conseguenze`,
  _ = `Mistero e Detective`,
  _ = `Mistero e Detective`,
  _ = `Simulatori di hobby e professioni`,
  _ = `Hobby e professioni`,
  _ = `Giochi in stile Rogue e Roguelite`,
  _ = `Perfetti per il Deck`,
  _ = `Perfetto per Steam Frame`,
  _ = `Capitalismo ed economia`,
  _ = `Pirati contro ninja`,
  _ = `Dinosauri contro robot`,
  _ = `Rigiocabilità infinita`,
  _ = `Esplorazione dello spazio`,
  _ = `Giochi di costruzione di mazzi`,
  _ = `GDR a turni`,
  _ = `Cucina`,
  _ = `Aerei, treni e automobili`,
  _ = `Pesca`,
  _ = `Lancia la tua lenza per una competizione o per semplice relax`,
  _ = `Incrementali`,
  _ = `Ritmici`,
  _ = `Sokoban`,
  _ = `Spostare le casse nell'ordine corretto`,
  _ = `Fattorie`,
  _ = `Giochi di guerra`,
  _ = `Collezione di creature`,
  _ = `Zombi contro vampiri`,
  _ = `Giochi di scatole`,
  _ = `Automazione`,
  _ = `Strategia 4X`,
  _ = `eXplore, eXpand, eXploit ed eXterminate`,
  _ = `Simulatori politici`,
  _ = `Animali`,
  _ = `Detective`,
  _ = `Metti insieme gli indizi e risolvi il caso`,
  _ = `Giochi da tavolo`,
  _ = `Scrittura`,
  _ = `Riesci a digitare super mega velocemente ma anche accuratamente?`,
  _ = `PVP di combattimento`,
  _ = `Cavalli`,
  _ = `Cavalca, gareggia e prenditi cura di cavalli, asini, pony, unicorni, ecc.`,
  _ = `Medievale`,
  _ = `Casa e domicilio`,
  _ = `Oceano`,
  _ = `Hentai`,
  _ = `Per adulti`,
  _ = `Proiettili`,
  _ = `Muoviti per evitare i flussi di proiettili nemici o spara i tuoi. In ogni caso, preparati al caos visivo.`,
  _ = `Abilità sociali
`,
  _ = `Osserva, indaga, bluffa e menti per scovare i traditori e dedurre informazioni nascoste prima che scada il tempo.`,
  _ = `Treni`,
  _ = `Posa binari, pianifica percorsi o semplicemente controlla la tua locomotiva attraverso città e campagne.`,
  _ = `Cyberpunk`,
  _ = `Alta tecnologia di ogni tipo, ambientata in un futuro fantascientifico distopico.`,
  _ = `Birilli e pioli`,
  _ = `Lanci palle che rimbalzano sui pioli e buttano giù i birilli.`,
  _ = `PvE crafting e sopravvivenza`,
  _ = `Raccogli e costruisci per garantire la tua sopravvivenza contro gli elementi.`,
  _ = `Programmazione`,
  _ = `Scrivi istruzioni, viola sistemi e risolvi complessi problemi di logica.`,
  _ = `GDR di gruppo`,
  _ = `Acquisisci equipaggiamento e aumenta di livello con la tua squadra.`,
  _ = `Fantasy e soprannaturali`,
  _ = `Sparatutto senza zombi`,
  _ = `Rompicapo rilassanti con animali`,
  _ = `Novità e tendenze`,
  _ = `Sconti ed eventi`,
  _ = `Difficoltà regolabile`,
  _ = `Questi giochi offrono diversi modi per regolare la difficoltà.`,
  _ = `Salva in qualsiasi momento`,
  _ = `Questi giochi ti consentono di salvare manualmente i progressi quasi in qualsiasi momento.`,
  _ = `Dimensioni testo regolabili`,
  _ = `Puoi regolare la dimensione del testo e il ridimensionamento dell'interfaccia utente in questi giochi per far apparire parole ed elementi più grandi o più piccoli.`,
  _ = `Opzioni sottotitoli`,
  _ = `Puoi regolare il modo in cui i sottotitoli sono visualizzati, come la dimensione dei caratteri, il colore e l'opacità dello sfondo.`,
  _ = `Alternative di colori`,
  _ = `Il gameplay non si basa sui colori per comunicare informazioni importanti, oppure puoi modificare i colori usati.`,
  _ = `Comfort telecamera`,
  _ = `Questi giochi permettono di regolare o disattivare i movimenti poco confortevoli della telecamera (come il tremolio dello schermo, l'oscillazione della telecamera o la sfocatura del movimento), oppure non presentano questi effetti.`,
  _ = `Controlli di volume personalizzati`,
  _ = `Questi giochi ti permettono di regolare indipendentemente il volume per diversi tipi di audio in gioco (come musica, effetti sonori o voci).`,
  _ = `Suono stereo`,
  _ = `Questi giochi ti permettono di usare l'audio stereo per capire la distanza e la direzione (sinistra o destra) da cui provengono i suoni.`,
  _ = `Suono surround`,
  _ = `Questi giochi ti permettono di usare il suono surround per identificare la distanza da cui provengono i suoni in qualsiasi direzione.`,
  _ = `Menu di gioco con narrazione`,
  _ = `Questi giochi offrono il supporto per lettori dello schermo o forniscono la narrazione del menu, in modo che i menu possano essere utilizzati e compresi senza vedere il testo.`,
  _ = `Giocabile senza quick time event`,
  _ = `Questi giochi ti consentono di evitare sequenze di input a tempo preciso ("quick time event") o la pressione ripetuta e consecutiva dei pulsanti.`,
  _ = `Opzione solo tastiera`,
  _ = `Si può giocare a questi giochi solo con una tastiera o con uno strumento di accessibilità che mappa gli input della tastiera.`,
  _ = `Opzione solo mouse`,
  _ = `Si può giocare a questi giochi solo con un mouse o con uno strumento di accessibilità che mappa gli input del mouse.`,
  _ = `Opzione solo touch`,
  _ = `Si può giocare a questi giochi solo con controlli touch o con uno strumento di accessibilità che mappa gli input touch.`,
  _ = `Chat vocale convertita in testo`,
  _ = `Questi giochi consentono che la chat vocale sia letta come una trascrizione di testo in tempo reale.`,
  _ = `Chat di testo convertita in voce`,
  _ = `Questi giochi consentono che la chat testuale sia narrata ad alta voce in tempo reale.`,
  _ = `Giocabile al proprio ritmo`,
  _ = `Questi giochi ti permettono di prendertela con calma tra ogni input.`,
  _ = `Giocabile da non vedenti`,
  _ = `Questi titoli possono essere giocati senza vedere lo schermo.`,
  _ = `Controlli del contrasto`,
  _ = `Questi giochi consentono di regolare il contrasto per avere maggiore comfort.`,
  _ = `Solo per adulti`,
  _ = `Demo`,
  _ = `Free-to-Play`,
  _ = `Accesso anticipato`,
  _ = `Perfetti per il Deck`,
  _ = `Perfetto per Steam Frame`,
  _ = `Compatibilità con i controller`,
  _ = `Remote Play`,
  _ = `Titoli in VR`,
  _ = `Hardware VR`,
  _ = `Software`,
  _ = `Colonne sonore`,
  _ = `macOS`,
  _ = `SteamOS + Linux`,
  _ = `Per PC Cafe`,
  _ = `Provalo subito`,
  _ = `Provalo subito`,
  _ = `dummy`,
  _ = {
    language: _,
    label_play_free_until_custom: _,
    promo_ends_custom: _,
    label_play_free_generic: _,
    label_free_weekend: _,
    msg_free_play_weekend: _,
    msg_free_play_until: _,
    label_free_week: _,
    label_just_updated: _,
    label_for_a_limited_time_only: _,
    msg_prepurchase_and_play_beta_now: _,
    msg_play_beta_now: _,
    msg_prepurchase_and_get_beta_access: _,
    msg_steam_workshop_now_available: _,
    msg_now_with_steam_workshop: _,
    msg_now_with_steamworks: _,
    msg_now_available_on_steamos: _,
    msg_now_available_on_steamos_mac_and_linux: _,
    msg_preload_now: _,
    msg_free_update: _,
    msg_play_demo_now: _,
    msg_preload_free: _,
    msg_preload_now_for_free: _,
    msg_preload_you_have_pre: _,
    msg_preload_you_have_completed: _,
    msg_preload_completed: _,
    msg_prepurchase_now: _,
    msg_just_updated_with_free_dlc: _,
    msg_now_available_for_mac_and_steamos: _,
    msg_coming_soon_to_steamos: _,
    msg_watch_movie_now: _,
    btn_add_to_wishlist: _,
    msg_early_access_now_available: _,
    msg_in_early_access: _,
    msg_new_update_available: _,
    browse_free: _,
    msg_available_new_release: _,
    msg_available_just_released_from_early_access: _,
    msg_available_just_released: _,
    msg_available_everywhere: _,
    msg_new_game: _,
    msg_available_now_free_to_play: _,
    msg_free_to_play_just_updated: _,
    msg_available_now_ftp_early: _,
    msg_advanced_access: _,
    msg_new_content_now_available: _,
    mst_weekend_description_free: _,
    msg_weekend_on_now: _,
    msg_weekend_trial: _,
    msg_weekend_play_free: _,
    msg_prepurchase_bonus: _,
    api_category_top_sellers: _,
    api_category_new_releases: _,
    spotlight_weekend_deal: _,
    spotlight_midweek_madness: _,
    spotlight_midweek_deal: _,
    spotlight_franchise_sale: _,
    spotlight_thirdparty_event: _,
    spotlight_major_update: _,
    spotlight_daily_deal: _,
    spotlight_weeklong_sale: _,
    spotlight_weeklong_header1: _,
    promo_giveaway: _,
    limitedtime_install_and_keep: _,
    api_category_coming_soon: _,
    label_new_and_upcoming: _,
    label_highlighted_deals: _,
    label_back_catalogue: _,
    msg_publisher_weekend: _,
    msg_publisher_sale: _,
    Library_Install: _,
    discount_desc_preset_loyalty: _,
    msg_action_details: _,
    msg_play_now: _,
    msg_play_it_now: _,
    msg_action_buy: _,
    msg_action_info: _,
    msg_on_sale_now: _,
    label_early_beta_access: _,
    label_new_dlc_available: _,
    label_pre_load_now: _,
    label_deepest_discount: _,
    discount_desc_limited_time: _,
    discount_desc_limited_time_date: _,
    text_now_available: _,
    text_now_available_steamplay: _,
    text_now_available_mac: _,
    text_now_available_on_pc_mac_and_linux: _,
    text_now_free_to_play: _,
    text_new_free_to_play: _,
    text_free_new_dlc_now_available: _,
    ContentHubby_Hub_1st_person_action_shooting: _,
    ContentHubby_Hub_1st_person_action_shooting_menu: _,
    ContentHubby_Hub_2d_view_action: _,
    ContentHubby_Hub_2d_view_action_menu: _,
    ContentHubby_Hub_3rd_person_action_shooting: _,
    ContentHubby_Hub_3rd_person_action_shooting_menu: _,
    ContentHubby_Hub_action: _,
    ContentHubby_Hub_action_menu: _,
    ContentHubby_Hub_action_dash_adventure: _,
    ContentHubby_Hub_action_dash_adventure_menu: _,
    ContentHubby_Hub_action_and_adventure: _,
    ContentHubby_Hub_action_and_adventure_menu: _,
    ContentHubby_Hub_action_fps: _,
    ContentHubby_Hub_action_fps_menu: _,
    ContentHubby_Hub_action_horror: _,
    ContentHubby_Hub_action_horror_menu: _,
    ContentHubby_Hub_action_rogue_like: _,
    ContentHubby_Hub_action_rogue_like_menu: _,
    ContentHubby_Hub_action_rpg: _,
    ContentHubby_Hub_action_rpg_menu: _,
    ContentHubby_Hub_action_run_jump: _,
    ContentHubby_Hub_action_run_jump_menu: _,
    ContentHubby_Hub_action_shooter: _,
    ContentHubby_Hub_action_shooter_menu: _,
    ContentHubby_Hub_action_tps: _,
    ContentHubby_Hub_action_tps_menu: _,
    ContentHubby_Hub_actions_activities: _,
    ContentHubby_Hub_actions_activities_menu: _,
    ContentHubby_Hub_adventure: _,
    ContentHubby_Hub_adventure_menu: _,
    ContentHubby_Hub_adventure_and_casual: _,
    ContentHubby_Hub_adventure_and_casual_menu: _,
    ContentHubby_Hub_adventure_explore_open_world: _,
    ContentHubby_Hub_adventure_explore_open_world_menu: _,
    ContentHubby_Hub_adventure_point_click: _,
    ContentHubby_Hub_adventure_point_click_menu: _,
    ContentHubby_Hub_adventure_rpg: _,
    ContentHubby_Hub_adventure_rpg_menu: _,
    ContentHubby_Hub_adventure_rpg_casual: _,
    ContentHubby_Hub_adventure_rpg_casual_menu: _,
    ContentHubby_Hub_aesthetic: _,
    ContentHubby_Hub_aesthetic_menu: _,
    ContentHubby_Hub_anime_mild: _,
    ContentHubby_Hub_anime_mild_menu: _,
    ContentHubby_Hub_arcade: _,
    ContentHubby_Hub_arcade_menu: _,
    ContentHubby_Hub_arcade_rhythm: _,
    ContentHubby_Hub_arcade_rhythm_menu: _,
    ContentHubby_Hub_artstyles_music: _,
    ContentHubby_Hub_artstyles_music_menu: _,
    ContentHubby_Hub_action_beat_em_up: _,
    ContentHubby_Hub_action_beat_em_up_menu: _,
    ContentHubby_Hub_business_politics: _,
    ContentHubby_Hub_business_politics_menu: _,
    ContentHubby_Hub_casual: _,
    ContentHubby_Hub_casual_menu: _,
    ContentHubby_Hub_casual_card_board: _,
    ContentHubby_Hub_casual_card_board_menu: _,
    ContentHubby_Hub_casual_and_puzzle: _,
    ContentHubby_Hub_casual_and_puzzle_menu: _,
    ContentHubby_Hub_casual_and_story: _,
    ContentHubby_Hub_casual_and_story_menu: _,
    ContentHubby_Hub_casual_puzzle: _,
    ContentHubby_Hub_casual_puzzle_menu: _,
    ContentHubby_Hub_character_action_game: _,
    ContentHubby_Hub_clickers_idlers: _,
    ContentHubby_Hub_clickers_idlers_menu: _,
    ContentHubby_Hub_crime_justice: _,
    ContentHubby_Hub_crime_justice_menu: _,
    ContentHubby_Hub_cute_cartoon: _,
    ContentHubby_Hub_cute_cartoon_menu: _,
    ContentHubby_Hub_dating_sim: _,
    ContentHubby_Hub_dating_sim_menu: _,
    ContentHubby_Hub_driving_piloting: _,
    ContentHubby_Hub_driving_piloting_menu: _,
    ContentHubby_Hub_education: _,
    ContentHubby_Hub_education_menu: _,
    ContentHubby_Hub_experimental: _,
    ContentHubby_Hub_experimental_menu: _,
    ContentHubby_Hub_exploration_open_world: _,
    ContentHubby_Hub_exploration_open_world_menu: _,
    ContentHubby_Hub_fantasy: _,
    ContentHubby_Hub_fantasy_menu: _,
    ContentHubby_Hub_fantasy_supernatural: _,
    ContentHubby_Hub_fantasy_supernatural_menu: _,
    ContentHubby_Hub_fighting: _,
    ContentHubby_Hub_fighting_menu: _,
    ContentHubby_Hub_fighting_martial_arts: _,
    ContentHubby_Hub_fighting_martial_arts_menu: _,
    ContentHubby_Hub_free_to_play: _,
    ContentHubby_Hub_hack_and_slash: _,
    ContentHubby_Hub_hidden_object_menu: _,
    ContentHubby_Hub_hidden_object: _,
    ContentHubby_Hub_history: _,
    ContentHubby_Hub_horror: _,
    ContentHubby_Hub_horror_menu: _,
    ContentHubby_Hub_horror_dark: _,
    ContentHubby_Hub_horror_dark_menu: _,
    ContentHubby_Hub_scream: _,
    ContentHubby_Hub_base_builder: _,
    ContentHubby_Hub_stealth: _,
    ContentHubby_Hub_shmup: _,
    ContentHubby_Hub_interactive_fiction: _,
    ContentHubby_Hub_interactive_fiction_menu: _,
    ContentHubby_Hub_interactive_stories: _,
    ContentHubby_Hub_interactive_stories_menu: _,
    ContentHubby_Hub_life_sim: _,
    ContentHubby_Hub_location_worlds: _,
    ContentHubby_Hub_match_3: _,
    ContentHubby_Hub_match_3_menu: _,
    ContentHubby_Hub_military: _,
    ContentHubby_Hub_military_menu: _,
    ContentHubby_Hub_military_warfare: _,
    ContentHubby_Hub_military_warfare_menu: _,
    ContentHubby_Hub_minimalist_abstract: _,
    ContentHubby_Hub_minimalist_abstract_menu: _,
    ContentHubby_Hub_multiplayer: _,
    ContentHubby_Hub_multiplayer_menu: _,
    ContentHubby_Hub_multiplayer_competitive: _,
    ContentHubby_Hub_multiplayer_competitive_menu: _,
    ContentHubby_Hub_multiplayer_battle_royale: _,
    ContentHubby_Hub_multiplayer_battle_royale_menu: _,
    ContentHubby_Hub_multiplayer_coop: _,
    ContentHubby_Hub_multiplayer_coop_menu: _,
    ContentHubby_Hub_multiplayer_lan: _,
    ContentHubby_Hub_multiplayer_lan_menu: `LAN`,
    ContentHubby_Hub_multiplayer_local_party: _,
    ContentHubby_Hub_multiplayer_local_party_menu: _,
    ContentHubby_Hub_multiplayer_mmo: _,
    ContentHubby_Hub_multiplayer_mmo_menu: `MMO`,
    ContentHubby_Hub_multiplayer_moba_auto_battler: _,
    ContentHubby_Hub_multiplayer_moba_auto_battler_menu: _,
    ContentHubby_Hub_multiplayer_online_competitive: _,
    ContentHubby_Hub_multiplayer_online_competitive_menu: _,
    ContentHubby_Hub_multiplayer_shooter: _,
    ContentHubby_Hub_multiplayer_shooter_menu: _,
    ContentHubby_Hub_music_rhythm: _,
    ContentHubby_Hub_music_rhythm_menu: _,
    ContentHubby_Hub_open_world_survival_craft: _,
    ContentHubby_Hub_open_world_survival_craft_menu: _,
    ContentHubby_Hub_people_creatures: _,
    ContentHubby_Hub_players: _,
    ContentHubby_Hub_psychedelic: _,
    ContentHubby_Hub_psychedelic_menu: _,
    ContentHubby_Hub_psychedelic_surreal: _,
    ContentHubby_Hub_psychedelic_surreal_menu: _,
    ContentHubby_Hub_puzzle: _,
    ContentHubby_Hub_puzzle_menu: _,
    ContentHubby_Hub_puzzle_matching: _,
    ContentHubby_Hub_puzzle_matching_menu: _,
    ContentHubby_Hub_puzzle_difficult: _,
    ContentHubby_Hub_puzzle_difficult_menu: _,
    ContentHubby_Hub_puzzle_logic: _,
    ContentHubby_Hub_puzzle_logic_menu: _,
    ContentHubby_Hub_puzzle_multiplayer: _,
    ContentHubby_Hub_puzzle_multiplayer_menu: _,
    ContentHubby_Hub_racing: _,
    ContentHubby_Hub_racing_desc: _,
    ContentHubby_Hub_racing_menu: _,
    ContentHubby_Hub_racing_sim: _,
    ContentHubby_Hub_racing_sim_menu: _,
    ContentHubby_Hub_racing_combat: _,
    ContentHubby_Hub_racing_combat_menu: _,
    ContentHubby_Hub_racing_piloting: _,
    ContentHubby_Hub_racing_piloting_menu: _,
    ContentHubby_Hub_retro: _,
    ContentHubby_Hub_retro_menu: _,
    ContentHubby_Hub_relaxing: _,
    ContentHubby_Hub_relaxing_menu: _,
    ContentHubby_Hub_metroidvania: _,
    ContentHubby_Hub_metroidvania_menu: _,
    ContentHubby_Hub_minimalist_relaxing: _,
    ContentHubby_Hub_minimalist_relaxing_menu: _,
    ContentHubby_Hub_rogue_like_turn_based: _,
    ContentHubby_Hub_rogue_like_turn_based_menu: _,
    ContentHubby_Hub_rogue_like_rogue_lite: _,
    ContentHubby_Hub_rogue_like_rogue_lite_menu: _,
    ContentHubby_Hub_rogue_like: _,
    ContentHubby_Hub_rogue_like_menu: _,
    ContentHubby_Hub_rpg: _,
    ContentHubby_Hub_rpg_menu: _,
    ContentHubby_Hub_rpg_action: _,
    ContentHubby_Hub_rpg_action_menu: _,
    ContentHubby_Hub_rpg_crpg: _,
    ContentHubby_Hub_rpg_crpg_menu: _,
    ContentHubby_Hub_rpg_crpg_traditional_rogue_like: _,
    ContentHubby_Hub_rpg_crpg_traditional_rogue_like_menu: _,
    ContentHubby_Hub_rpg_dungeon_crawler: _,
    ContentHubby_Hub_rpg_dungeon_crawler_menu: _,
    ContentHubby_Hub_rpg_jrpg: _,
    ContentHubby_Hub_rpg_jrpg_menu: _,
    ContentHubby_Hub_rpg_mmo: _,
    ContentHubby_Hub_rpg_mmo_menu: _,
    ContentHubby_Hub_rpg_party_based: _,
    ContentHubby_Hub_rpg_party_based_menu: _,
    ContentHubby_Hub_rpg_story: _,
    ContentHubby_Hub_rpg_story_menu: _,
    ContentHubby_Hub_rpg_strategy_tactics: _,
    ContentHubby_Hub_rpg_strategy_tactics_menu: _,
    ContentHubby_Hub_rpg_turn_based: _,
    ContentHubby_Hub_rpg_turn_based_menu: _,
    ContentHubby_Hub_science_fiction: _,
    ContentHubby_Hub_science_fiction_menu: _,
    ContentHubby_Hub_shooter: _,
    ContentHubby_Hub_shooter_menu: _,
    ContentHubby_Hub_sim_building: _,
    ContentHubby_Hub_sim_building_menu: _,
    ContentHubby_Hub_sim_building_automation: _,
    ContentHubby_Hub_sim_building_automation_menu: _,
    ContentHubby_Hub_sim_business_tycoon: _,
    ContentHubby_Hub_sim_business_tycoon_menu: _,
    ContentHubby_Hub_sim_cities_settlements: _,
    ContentHubby_Hub_sim_cities_settlements_menu: _,
    ContentHubby_Hub_sim_farming: _,
    ContentHubby_Hub_sim_farming_menu: _,
    ContentHubby_Hub_sim_farming_crafting: _,
    ContentHubby_Hub_sim_farming_crafting_menu: _,
    ContentHubby_Hub_sim_life: _,
    ContentHubby_Hub_sim_life_menu: _,
    ContentHubby_Hub_sim_life_romance: _,
    ContentHubby_Hub_sim_life_romance_menu: _,
    ContentHubby_Hub_sim_management: _,
    ContentHubby_Hub_sim_management_menu: _,
    ContentHubby_Hub_sim_open_world: _,
    ContentHubby_Hub_sim_open_world_menu: _,
    ContentHubby_Hub_sim_physics_sandbox: _,
    ContentHubby_Hub_sim_physics_sandbox_menu: _,
    ContentHubby_Hub_sim_policy: _,
    ContentHubby_Hub_sim_policy_menu: _,
    ContentHubby_Hub_sim_sandbox_god_game: _,
    ContentHubby_Hub_sim_sandbox_god_game_menu: _,
    ContentHubby_Hub_sim_space_flight: _,
    ContentHubby_Hub_sim_space_flight_menu: _,
    ContentHubby_Hub_sim_dating: _,
    ContentHubby_Hub_sim_dating_menu: _,
    ContentHubby_Hub_simulation: _,
    ContentHubby_Hub_simulation_menu: _,
    ContentHubby_Hub_singleplayer: _,
    ContentHubby_Hub_singleplayer_menu: _,
    ContentHubby_Hub_social_and_players: _,
    ContentHubby_Hub_sports: _,
    ContentHubby_Hub_sports_desc: _,
    ContentHubby_Hub_sports_menu: _,
    ContentHubby_Hub_sports_and_racing: _,
    ContentHubby_Hub_sports_and_racing_menu: _,
    ContentHubby_Hub_sports_ball: _,
    ContentHubby_Hub_sports_ball_menu: _,
    ContentHubby_Hub_sports_combat: _,
    ContentHubby_Hub_sports_combat_menu: _,
    ContentHubby_Hub_sports_fishing_hunting: _,
    ContentHubby_Hub_sports_fishing_hunting_menu: _,
    ContentHubby_Hub_sports_individual: _,
    ContentHubby_Hub_sports_individual_menu: _,
    ContentHubby_Hub_sports_sim: _,
    ContentHubby_Hub_sports_sim_menu: _,
    ContentHubby_Hub_sports_team: _,
    ContentHubby_Hub_sports_team_menu: _,
    ContentHubby_Hub_sports_winter: _,
    ContentHubby_Hub_sports_winter_menu: _,
    ContentHubby_Hub_spooky: _,
    ContentHubby_Hub_spooky_menu: _,
    ContentHubby_Hub_story_driven: _,
    ContentHubby_Hub_story_driven_menu: _,
    ContentHubby_Hub_strategy: _,
    ContentHubby_Hub_strategy_menu: _,
    ContentHubby_Hub_strategy_card_board: _,
    ContentHubby_Hub_strategy_card_board_menu: _,
    ContentHubby_Hub_strategy_cities_settlements: _,
    ContentHubby_Hub_strategy_cities_settlements_menu: _,
    ContentHubby_Hub_strategy_grand_4x: _,
    ContentHubby_Hub_strategy_grand_4x_menu: _,
    ContentHubby_Hub_strategy_military: _,
    ContentHubby_Hub_strategy_military_menu: _,
    ContentHubby_Hub_strategy_moba_auto_battler: _,
    ContentHubby_Hub_strategy_moba_auto_battler_menu: _,
    ContentHubby_Hub_strategy_real_time: _,
    ContentHubby_Hub_strategy_real_time_menu: _,
    ContentHubby_Hub_strategy_sim_management: _,
    ContentHubby_Hub_strategy_sim_management_menu: _,
    ContentHubby_Hub_strategy_tactics: _,
    ContentHubby_Hub_strategy_tactics_menu: _,
    ContentHubby_Hub_strategy_turn_based: _,
    ContentHubby_Hub_strategy_turn_based_menu: _,
    ContentHubby_Hub_survival: _,
    ContentHubby_Hub_survival_menu: _,
    ContentHubby_Hub_survival_stealth: _,
    ContentHubby_Hub_survival_stealth_menu: _,
    ContentHubby_Hub_themes: _,
    ContentHubby_Hub_themes_menu: _,
    ContentHubby_Hub_themes_and_interests: _,
    ContentHubby_Hub_themes_and_interests_menu: _,
    ContentHubby_Hub_time_management: _,
    ContentHubby_Hub_time_management_menu: _,
    ContentHubby_Hub_tower_defense: _,
    ContentHubby_Hub_tower_defense_menu: _,
    ContentHubby_Hub_visual_novel: _,
    ContentHubby_Hub_visual_novel_menu: _,
    ContentHubby_Hub_walking_simulator: _,
    ContentHubby_Hub_walking_simulator_menu: _,
    ContentHubby_Hub_space: _,
    ContentHubby_Hub_space_menu: _,
    ContentHubby_Hub_female_protagonist: _,
    ContentHubby_Hub_female_protagonist_menu: _,
    ContentHubby_Hub_lgbtq: _,
    ContentHubby_Hub_lgbtq_menu: _,
    ContentHubby_Hub_pixel_retro: _,
    ContentHubby_Hub_pixel_retro_menu: _,
    ContentHubby_Hub_choices_matter: _,
    ContentHubby_Hub_choices_matter_menu: _,
    ContentHubby_Hub_mystery_detective: _,
    ContentHubby_Hub_mystery_detective_menu: _,
    ContentHubby_Hub_hobby_sim: _,
    ContentHubby_Hub_hobby_sim_menu: _,
    ContentHubby_Hub_going_rogue: _,
    ContentHubby_Hub_greatondeck: _,
    ContentHubby_Hub_greatonframe: _,
    ContentHubby_Hub_capitalism_economy: _,
    ContentHubby_Hub_pirates_ninjas: _,
    ContentHubby_Hub_dinos_robots: _,
    ContentHubby_Hub_endlessly_replayable: _,
    ContentHubby_Hub_space_exploration: _,
    ContentHubby_Hub_deckbuilders: _,
    ContentHubby_Hub_turnbased_rpg: _,
    ContentHubby_Hub_cooking: _,
    ContentHubby_Hub_plane_train_autos: _,
    ContentHubby_Hub_fishing: _,
    ContentHubby_Hub_fishing_desc: _,
    ContentHubby_Hub_idle: _,
    ContentHubby_Hub_rhythm: _,
    ContentHubby_Hub_sokoban: _,
    ContentHubby_Hub_sokoban_desc: _,
    ContentHubby_Hub_farming: _,
    ContentHubby_Hub_wargame: _,
    ContentHubby_Hub_creature_collector: _,
    ContentHubby_Hub_zombies_vampires: _,
    ContentHubby_Hub_box_pushing: _,
    ContentHubby_Hub_automation: _,
    ContentHubby_Hub_4x_strategy: _,
    ContentHubby_Hub_4x_strategy_desc: _,
    ContentHubby_Hub_political_sim: _,
    ContentHubby_Hub_animals: _,
    ContentHubby_Hub_detective: _,
    ContentHubby_Hub_detective_desc: _,
    ContentHubby_Hub_board_games: _,
    ContentHubby_Hub_typing: _,
    ContentHubby_Hub_typing_desc: _,
    ContentHubby_Hub_combat_pvp: _,
    ContentHubby_Hub_horses: _,
    ContentHubby_Hub_horses_desc: _,
    ContentHubby_Hub_medieval: _,
    ContentHubby_Hub_house_home: _,
    ContentHubby_Hub_ocean: _,
    ContentHubby_Hub_hentai: _,
    ContentHubby_Hub_mature: _,
    ContentHubby_Hub_bullet: _,
    ContentHubby_Hub_bullet_desc: _,
    ContentHubby_Hub_deduction: _,
    ContentHubby_Hub_deduction_desc: _,
    ContentHubby_Hub_trains: _,
    ContentHubby_Hub_trains_desc: _,
    ContentHubby_Hub_cyberpunk: _,
    ContentHubby_Hub_cyberpunk_desc: _,
    ContentHubby_Hub_pinsandpegs: _,
    ContentHubby_Hub_pinsandpegs_desc: _,
    ContentHubby_Hub_pvesurvival: _,
    ContentHubby_Hub_pvesurvival_desc: _,
    ContentHubby_Hub_programming: _,
    ContentHubby_Hub_programming_desc: _,
    ContentHubby_Hub_partyrpg: _,
    ContentHubby_Hub_partyrpg_desc: _,
    ContentHubby_Hub_fantasy_and_supernatural: _,
    ContentHubby_Hub_shooters_without_zombies: _,
    ContentHubby_Hub_relaxing_animal_puzzles: _,
    ContentHubby_Menu_NewAndNoteworthy: _,
    ContentHubby_Menu_CurrentSpecials: _,
    ContentHubby_Hub_adjustable_difficulty: _,
    ContentHubby_Hub_adjustable_difficulty_desc: _,
    ContentHubby_Hub_save_anytime: _,
    ContentHubby_Hub_save_anytime_desc: _,
    ContentHubby_Hub_adjustable_text_size: _,
    ContentHubby_Hub_adjustable_text_size_desc: _,
    ContentHubby_Hub_subtitle_options: _,
    ContentHubby_Hub_subtitle_options_desc: _,
    ContentHubby_Hub_color_alternatives: _,
    ContentHubby_Hub_color_alternatives_desc: _,
    ContentHubby_Hub_camera_comfort: _,
    ContentHubby_Hub_camera_comfort_desc: _,
    ContentHubby_Hub_custom_volume_controls: _,
    ContentHubby_Hub_custom_volume_controls_desc: _,
    ContentHubby_Hub_stereo_sound: _,
    ContentHubby_Hub_stereo_sound_desc: _,
    ContentHubby_Hub_surround_sound: _,
    ContentHubby_Hub_surround_sound_desc: _,
    ContentHubby_Hub_narrated_game_menus: _,
    ContentHubby_Hub_narrated_game_menus_desc: _,
    ContentHubby_Hub_playable_without_timed_input: _,
    ContentHubby_Hub_playable_without_timed_input_desc: _,
    ContentHubby_Hub_keyboard_only_option: _,
    ContentHubby_Hub_keyboard_only_option_desc: _,
    ContentHubby_Hub_mouse_only_option: _,
    ContentHubby_Hub_mouse_only_option_desc: _,
    ContentHubby_Hub_touch_only_option: _,
    ContentHubby_Hub_touch_only_option_desc: _,
    ContentHubby_Hub_chat_speech_to_text: _,
    ContentHubby_Hub_chat_speech_to_text_desc: _,
    ContentHubby_Hub_chat_text_to_speech: _,
    ContentHubby_Hub_chat_text_to_speech_desc: _,
    ContentHubby_Hub_playable_at_your_own_pace: _,
    ContentHubby_Hub_playable_at_your_own_pace_desc: _,
    ContentHubby_Hub_playable_without_vision: _,
    ContentHubby_Hub_playable_without_vision_desc: _,
    ContentHubby_Hub_contrast_controls: _,
    ContentHubby_Hub_contrast_controls_desc: _,
    browse_adultonly: _,
    browse_demos: _,
    genre_free2play: _,
    genre_early_access: _,
    store_tab_greatondeck: _,
    store_tab_greatonframe: _,
    contenthub_title_controller: _,
    browse_remoteplay: _,
    Store_VR_MainMenu_Virtual_Reality: _,
    Store_VR_MainMenu_VR_Hardware: _,
    store_tab_software_home: _,
    additional_game_content_soundtracks: _,
    games_osx: _,
    store_tab_linux: _,
    contenthub_title_pccafe: _,
    msg_try_it_now: _,
    Library_Update_TryItNow2: _,
    dummy: _,
  };
export {
  _ as ContentHubby_Hub_1st_person_action_shooting,
  _ as ContentHubby_Hub_1st_person_action_shooting_menu,
  _ as ContentHubby_Hub_2d_view_action,
  _ as ContentHubby_Hub_2d_view_action_menu,
  _ as ContentHubby_Hub_3rd_person_action_shooting,
  _ as ContentHubby_Hub_3rd_person_action_shooting_menu,
  _ as ContentHubby_Hub_4x_strategy,
  _ as ContentHubby_Hub_4x_strategy_desc,
  _ as ContentHubby_Hub_action,
  _ as ContentHubby_Hub_action_and_adventure,
  _ as ContentHubby_Hub_action_and_adventure_menu,
  _ as ContentHubby_Hub_action_beat_em_up,
  _ as ContentHubby_Hub_action_beat_em_up_menu,
  _ as ContentHubby_Hub_action_dash_adventure,
  _ as ContentHubby_Hub_action_dash_adventure_menu,
  _ as ContentHubby_Hub_action_fps,
  _ as ContentHubby_Hub_action_fps_menu,
  _ as ContentHubby_Hub_action_horror,
  _ as ContentHubby_Hub_action_horror_menu,
  _ as ContentHubby_Hub_action_menu,
  _ as ContentHubby_Hub_action_rogue_like,
  _ as ContentHubby_Hub_action_rogue_like_menu,
  _ as ContentHubby_Hub_action_rpg,
  _ as ContentHubby_Hub_action_rpg_menu,
  _ as ContentHubby_Hub_action_run_jump,
  _ as ContentHubby_Hub_action_run_jump_menu,
  _ as ContentHubby_Hub_action_shooter,
  _ as ContentHubby_Hub_action_shooter_menu,
  _ as ContentHubby_Hub_action_tps,
  _ as ContentHubby_Hub_action_tps_menu,
  _ as ContentHubby_Hub_actions_activities,
  _ as ContentHubby_Hub_actions_activities_menu,
  _ as ContentHubby_Hub_adjustable_difficulty,
  _ as ContentHubby_Hub_adjustable_difficulty_desc,
  _ as ContentHubby_Hub_adjustable_text_size,
  _ as ContentHubby_Hub_adjustable_text_size_desc,
  _ as ContentHubby_Hub_adventure,
  _ as ContentHubby_Hub_adventure_and_casual,
  _ as ContentHubby_Hub_adventure_and_casual_menu,
  _ as ContentHubby_Hub_adventure_explore_open_world,
  _ as ContentHubby_Hub_adventure_explore_open_world_menu,
  _ as ContentHubby_Hub_adventure_menu,
  _ as ContentHubby_Hub_adventure_point_click,
  _ as ContentHubby_Hub_adventure_point_click_menu,
  _ as ContentHubby_Hub_adventure_rpg,
  _ as ContentHubby_Hub_adventure_rpg_casual,
  _ as ContentHubby_Hub_adventure_rpg_casual_menu,
  _ as ContentHubby_Hub_adventure_rpg_menu,
  _ as ContentHubby_Hub_aesthetic,
  _ as ContentHubby_Hub_aesthetic_menu,
  _ as ContentHubby_Hub_animals,
  _ as ContentHubby_Hub_anime_mild,
  _ as ContentHubby_Hub_anime_mild_menu,
  _ as ContentHubby_Hub_arcade,
  _ as ContentHubby_Hub_arcade_menu,
  _ as ContentHubby_Hub_arcade_rhythm,
  _ as ContentHubby_Hub_arcade_rhythm_menu,
  _ as ContentHubby_Hub_artstyles_music,
  _ as ContentHubby_Hub_artstyles_music_menu,
  _ as ContentHubby_Hub_automation,
  _ as ContentHubby_Hub_base_builder,
  _ as ContentHubby_Hub_board_games,
  _ as ContentHubby_Hub_box_pushing,
  _ as ContentHubby_Hub_bullet,
  _ as ContentHubby_Hub_bullet_desc,
  _ as ContentHubby_Hub_business_politics,
  _ as ContentHubby_Hub_business_politics_menu,
  _ as ContentHubby_Hub_camera_comfort,
  _ as ContentHubby_Hub_camera_comfort_desc,
  _ as ContentHubby_Hub_capitalism_economy,
  _ as ContentHubby_Hub_casual,
  _ as ContentHubby_Hub_casual_and_puzzle,
  _ as ContentHubby_Hub_casual_and_puzzle_menu,
  _ as ContentHubby_Hub_casual_and_story,
  _ as ContentHubby_Hub_casual_and_story_menu,
  _ as ContentHubby_Hub_casual_card_board,
  _ as ContentHubby_Hub_casual_card_board_menu,
  _ as ContentHubby_Hub_casual_menu,
  _ as ContentHubby_Hub_casual_puzzle,
  _ as ContentHubby_Hub_casual_puzzle_menu,
  _ as ContentHubby_Hub_character_action_game,
  _ as ContentHubby_Hub_chat_speech_to_text,
  _ as ContentHubby_Hub_chat_speech_to_text_desc,
  _ as ContentHubby_Hub_chat_text_to_speech,
  _ as ContentHubby_Hub_chat_text_to_speech_desc,
  _ as ContentHubby_Hub_choices_matter,
  _ as ContentHubby_Hub_choices_matter_menu,
  _ as ContentHubby_Hub_clickers_idlers,
  _ as ContentHubby_Hub_clickers_idlers_menu,
  _ as ContentHubby_Hub_color_alternatives,
  _ as ContentHubby_Hub_color_alternatives_desc,
  _ as ContentHubby_Hub_combat_pvp,
  _ as ContentHubby_Hub_contrast_controls,
  _ as ContentHubby_Hub_contrast_controls_desc,
  _ as ContentHubby_Hub_cooking,
  _ as ContentHubby_Hub_creature_collector,
  _ as ContentHubby_Hub_crime_justice,
  _ as ContentHubby_Hub_crime_justice_menu,
  _ as ContentHubby_Hub_custom_volume_controls,
  _ as ContentHubby_Hub_custom_volume_controls_desc,
  _ as ContentHubby_Hub_cute_cartoon,
  _ as ContentHubby_Hub_cute_cartoon_menu,
  _ as ContentHubby_Hub_cyberpunk,
  _ as ContentHubby_Hub_cyberpunk_desc,
  _ as ContentHubby_Hub_dating_sim,
  _ as ContentHubby_Hub_dating_sim_menu,
  _ as ContentHubby_Hub_deckbuilders,
  _ as ContentHubby_Hub_deduction,
  _ as ContentHubby_Hub_deduction_desc,
  _ as ContentHubby_Hub_detective,
  _ as ContentHubby_Hub_detective_desc,
  _ as ContentHubby_Hub_dinos_robots,
  _ as ContentHubby_Hub_driving_piloting,
  _ as ContentHubby_Hub_driving_piloting_menu,
  _ as ContentHubby_Hub_education,
  _ as ContentHubby_Hub_education_menu,
  _ as ContentHubby_Hub_endlessly_replayable,
  _ as ContentHubby_Hub_experimental,
  _ as ContentHubby_Hub_experimental_menu,
  _ as ContentHubby_Hub_exploration_open_world,
  _ as ContentHubby_Hub_exploration_open_world_menu,
  _ as ContentHubby_Hub_fantasy,
  _ as ContentHubby_Hub_fantasy_and_supernatural,
  _ as ContentHubby_Hub_fantasy_menu,
  _ as ContentHubby_Hub_fantasy_supernatural,
  _ as ContentHubby_Hub_fantasy_supernatural_menu,
  _ as ContentHubby_Hub_farming,
  _ as ContentHubby_Hub_female_protagonist,
  _ as ContentHubby_Hub_female_protagonist_menu,
  _ as ContentHubby_Hub_fighting,
  _ as ContentHubby_Hub_fighting_martial_arts,
  _ as ContentHubby_Hub_fighting_martial_arts_menu,
  _ as ContentHubby_Hub_fighting_menu,
  _ as ContentHubby_Hub_fishing,
  _ as ContentHubby_Hub_fishing_desc,
  _ as ContentHubby_Hub_free_to_play,
  _ as ContentHubby_Hub_going_rogue,
  _ as ContentHubby_Hub_greatondeck,
  _ as ContentHubby_Hub_greatonframe,
  _ as ContentHubby_Hub_hack_and_slash,
  _ as ContentHubby_Hub_hentai,
  _ as ContentHubby_Hub_hidden_object,
  _ as ContentHubby_Hub_hidden_object_menu,
  _ as ContentHubby_Hub_history,
  _ as ContentHubby_Hub_hobby_sim,
  _ as ContentHubby_Hub_hobby_sim_menu,
  _ as ContentHubby_Hub_horror,
  _ as ContentHubby_Hub_horror_dark,
  _ as ContentHubby_Hub_horror_dark_menu,
  _ as ContentHubby_Hub_horror_menu,
  _ as ContentHubby_Hub_horses,
  _ as ContentHubby_Hub_horses_desc,
  _ as ContentHubby_Hub_house_home,
  _ as ContentHubby_Hub_idle,
  _ as ContentHubby_Hub_interactive_fiction,
  _ as ContentHubby_Hub_interactive_fiction_menu,
  _ as ContentHubby_Hub_interactive_stories,
  _ as ContentHubby_Hub_interactive_stories_menu,
  _ as ContentHubby_Hub_keyboard_only_option,
  _ as ContentHubby_Hub_keyboard_only_option_desc,
  _ as ContentHubby_Hub_lgbtq,
  _ as ContentHubby_Hub_lgbtq_menu,
  _ as ContentHubby_Hub_life_sim,
  _ as ContentHubby_Hub_location_worlds,
  _ as ContentHubby_Hub_match_3,
  _ as ContentHubby_Hub_match_3_menu,
  _ as ContentHubby_Hub_mature,
  _ as ContentHubby_Hub_medieval,
  _ as ContentHubby_Hub_metroidvania,
  _ as ContentHubby_Hub_metroidvania_menu,
  _ as ContentHubby_Hub_military,
  _ as ContentHubby_Hub_military_menu,
  _ as ContentHubby_Hub_military_warfare,
  _ as ContentHubby_Hub_military_warfare_menu,
  _ as ContentHubby_Hub_minimalist_abstract,
  _ as ContentHubby_Hub_minimalist_abstract_menu,
  _ as ContentHubby_Hub_minimalist_relaxing,
  _ as ContentHubby_Hub_minimalist_relaxing_menu,
  _ as ContentHubby_Hub_mouse_only_option,
  _ as ContentHubby_Hub_mouse_only_option_desc,
  _ as ContentHubby_Hub_multiplayer,
  _ as ContentHubby_Hub_multiplayer_battle_royale,
  _ as ContentHubby_Hub_multiplayer_battle_royale_menu,
  _ as ContentHubby_Hub_multiplayer_competitive,
  _ as ContentHubby_Hub_multiplayer_competitive_menu,
  _ as ContentHubby_Hub_multiplayer_coop,
  _ as ContentHubby_Hub_multiplayer_coop_menu,
  _ as ContentHubby_Hub_multiplayer_lan,
  _ as ContentHubby_Hub_multiplayer_lan_menu,
  _ as ContentHubby_Hub_multiplayer_local_party,
  _ as ContentHubby_Hub_multiplayer_local_party_menu,
  _ as ContentHubby_Hub_multiplayer_menu,
  _ as ContentHubby_Hub_multiplayer_mmo,
  _ as ContentHubby_Hub_multiplayer_mmo_menu,
  _ as ContentHubby_Hub_multiplayer_moba_auto_battler,
  _ as ContentHubby_Hub_multiplayer_moba_auto_battler_menu,
  _ as ContentHubby_Hub_multiplayer_online_competitive,
  _ as ContentHubby_Hub_multiplayer_online_competitive_menu,
  _ as ContentHubby_Hub_multiplayer_shooter,
  _ as ContentHubby_Hub_multiplayer_shooter_menu,
  _ as ContentHubby_Hub_music_rhythm,
  _ as ContentHubby_Hub_music_rhythm_menu,
  _ as ContentHubby_Hub_mystery_detective,
  _ as ContentHubby_Hub_mystery_detective_menu,
  _ as ContentHubby_Hub_narrated_game_menus,
  _ as ContentHubby_Hub_narrated_game_menus_desc,
  _ as ContentHubby_Hub_ocean,
  _ as ContentHubby_Hub_open_world_survival_craft,
  _ as ContentHubby_Hub_open_world_survival_craft_menu,
  _ as ContentHubby_Hub_partyrpg,
  _ as ContentHubby_Hub_partyrpg_desc,
  _ as ContentHubby_Hub_people_creatures,
  _ as ContentHubby_Hub_pinsandpegs,
  _ as ContentHubby_Hub_pinsandpegs_desc,
  _ as ContentHubby_Hub_pirates_ninjas,
  _ as ContentHubby_Hub_pixel_retro,
  _ as ContentHubby_Hub_pixel_retro_menu,
  _ as ContentHubby_Hub_plane_train_autos,
  _ as ContentHubby_Hub_playable_at_your_own_pace,
  _ as ContentHubby_Hub_playable_at_your_own_pace_desc,
  _ as ContentHubby_Hub_playable_without_timed_input,
  _ as ContentHubby_Hub_playable_without_timed_input_desc,
  _ as ContentHubby_Hub_playable_without_vision,
  _ as ContentHubby_Hub_playable_without_vision_desc,
  _ as ContentHubby_Hub_players,
  _ as ContentHubby_Hub_political_sim,
  _ as ContentHubby_Hub_programming,
  _ as ContentHubby_Hub_programming_desc,
  _ as ContentHubby_Hub_psychedelic,
  _ as ContentHubby_Hub_psychedelic_menu,
  _ as ContentHubby_Hub_psychedelic_surreal,
  _ as ContentHubby_Hub_psychedelic_surreal_menu,
  _ as ContentHubby_Hub_puzzle,
  _ as ContentHubby_Hub_puzzle_difficult,
  _ as ContentHubby_Hub_puzzle_difficult_menu,
  _ as ContentHubby_Hub_puzzle_logic,
  _ as ContentHubby_Hub_puzzle_logic_menu,
  _ as ContentHubby_Hub_puzzle_matching,
  _ as ContentHubby_Hub_puzzle_matching_menu,
  _ as ContentHubby_Hub_puzzle_menu,
  _ as ContentHubby_Hub_puzzle_multiplayer,
  _ as ContentHubby_Hub_puzzle_multiplayer_menu,
  _ as ContentHubby_Hub_pvesurvival,
  _ as ContentHubby_Hub_pvesurvival_desc,
  _ as ContentHubby_Hub_racing,
  _ as ContentHubby_Hub_racing_combat,
  _ as ContentHubby_Hub_racing_combat_menu,
  _ as ContentHubby_Hub_racing_desc,
  _ as ContentHubby_Hub_racing_menu,
  _ as ContentHubby_Hub_racing_piloting,
  _ as ContentHubby_Hub_racing_piloting_menu,
  _ as ContentHubby_Hub_racing_sim,
  _ as ContentHubby_Hub_racing_sim_menu,
  _ as ContentHubby_Hub_relaxing,
  _ as ContentHubby_Hub_relaxing_animal_puzzles,
  _ as ContentHubby_Hub_relaxing_menu,
  _ as ContentHubby_Hub_retro,
  _ as ContentHubby_Hub_retro_menu,
  _ as ContentHubby_Hub_rhythm,
  _ as ContentHubby_Hub_rogue_like,
  _ as ContentHubby_Hub_rogue_like_menu,
  _ as ContentHubby_Hub_rogue_like_rogue_lite,
  _ as ContentHubby_Hub_rogue_like_rogue_lite_menu,
  _ as ContentHubby_Hub_rogue_like_turn_based,
  _ as ContentHubby_Hub_rogue_like_turn_based_menu,
  _ as ContentHubby_Hub_rpg,
  _ as ContentHubby_Hub_rpg_action,
  _ as ContentHubby_Hub_rpg_action_menu,
  _ as ContentHubby_Hub_rpg_crpg,
  _ as ContentHubby_Hub_rpg_crpg_menu,
  _ as ContentHubby_Hub_rpg_crpg_traditional_rogue_like,
  _ as ContentHubby_Hub_rpg_crpg_traditional_rogue_like_menu,
  _ as ContentHubby_Hub_rpg_dungeon_crawler,
  _ as ContentHubby_Hub_rpg_dungeon_crawler_menu,
  _ as ContentHubby_Hub_rpg_jrpg,
  _ as ContentHubby_Hub_rpg_jrpg_menu,
  _ as ContentHubby_Hub_rpg_menu,
  _ as ContentHubby_Hub_rpg_mmo,
  _ as ContentHubby_Hub_rpg_mmo_menu,
  _ as ContentHubby_Hub_rpg_party_based,
  _ as ContentHubby_Hub_rpg_party_based_menu,
  _ as ContentHubby_Hub_rpg_story,
  _ as ContentHubby_Hub_rpg_story_menu,
  _ as ContentHubby_Hub_rpg_strategy_tactics,
  _ as ContentHubby_Hub_rpg_strategy_tactics_menu,
  _ as ContentHubby_Hub_rpg_turn_based,
  _ as ContentHubby_Hub_rpg_turn_based_menu,
  _ as ContentHubby_Hub_save_anytime,
  _ as ContentHubby_Hub_save_anytime_desc,
  _ as ContentHubby_Hub_science_fiction,
  _ as ContentHubby_Hub_science_fiction_menu,
  _ as ContentHubby_Hub_scream,
  _ as ContentHubby_Hub_shmup,
  _ as ContentHubby_Hub_shooter,
  _ as ContentHubby_Hub_shooter_menu,
  _ as ContentHubby_Hub_shooters_without_zombies,
  _ as ContentHubby_Hub_sim_building,
  _ as ContentHubby_Hub_sim_building_automation,
  _ as ContentHubby_Hub_sim_building_automation_menu,
  _ as ContentHubby_Hub_sim_building_menu,
  _ as ContentHubby_Hub_sim_business_tycoon,
  _ as ContentHubby_Hub_sim_business_tycoon_menu,
  _ as ContentHubby_Hub_sim_cities_settlements,
  _ as ContentHubby_Hub_sim_cities_settlements_menu,
  _ as ContentHubby_Hub_sim_dating,
  _ as ContentHubby_Hub_sim_dating_menu,
  _ as ContentHubby_Hub_sim_farming,
  _ as ContentHubby_Hub_sim_farming_crafting,
  _ as ContentHubby_Hub_sim_farming_crafting_menu,
  _ as ContentHubby_Hub_sim_farming_menu,
  _ as ContentHubby_Hub_sim_life,
  _ as ContentHubby_Hub_sim_life_menu,
  _ as ContentHubby_Hub_sim_life_romance,
  _ as ContentHubby_Hub_sim_life_romance_menu,
  _ as ContentHubby_Hub_sim_management,
  _ as ContentHubby_Hub_sim_management_menu,
  _ as ContentHubby_Hub_sim_open_world,
  _ as ContentHubby_Hub_sim_open_world_menu,
  _ as ContentHubby_Hub_sim_physics_sandbox,
  _ as ContentHubby_Hub_sim_physics_sandbox_menu,
  _ as ContentHubby_Hub_sim_policy,
  _ as ContentHubby_Hub_sim_policy_menu,
  _ as ContentHubby_Hub_sim_sandbox_god_game,
  _ as ContentHubby_Hub_sim_sandbox_god_game_menu,
  _ as ContentHubby_Hub_sim_space_flight,
  _ as ContentHubby_Hub_sim_space_flight_menu,
  _ as ContentHubby_Hub_simulation,
  _ as ContentHubby_Hub_simulation_menu,
  _ as ContentHubby_Hub_singleplayer,
  _ as ContentHubby_Hub_singleplayer_menu,
  _ as ContentHubby_Hub_social_and_players,
  _ as ContentHubby_Hub_sokoban,
  _ as ContentHubby_Hub_sokoban_desc,
  _ as ContentHubby_Hub_space,
  _ as ContentHubby_Hub_space_exploration,
  _ as ContentHubby_Hub_space_menu,
  _ as ContentHubby_Hub_spooky,
  _ as ContentHubby_Hub_spooky_menu,
  _ as ContentHubby_Hub_sports,
  _ as ContentHubby_Hub_sports_and_racing,
  _ as ContentHubby_Hub_sports_and_racing_menu,
  _ as ContentHubby_Hub_sports_ball,
  _ as ContentHubby_Hub_sports_ball_menu,
  _ as ContentHubby_Hub_sports_combat,
  _ as ContentHubby_Hub_sports_combat_menu,
  _ as ContentHubby_Hub_sports_desc,
  _ as ContentHubby_Hub_sports_fishing_hunting,
  _ as ContentHubby_Hub_sports_fishing_hunting_menu,
  _ as ContentHubby_Hub_sports_individual,
  _ as ContentHubby_Hub_sports_individual_menu,
  _ as ContentHubby_Hub_sports_menu,
  _ as ContentHubby_Hub_sports_sim,
  _ as ContentHubby_Hub_sports_sim_menu,
  _ as ContentHubby_Hub_sports_team,
  _ as ContentHubby_Hub_sports_team_menu,
  _ as ContentHubby_Hub_sports_winter,
  _ as ContentHubby_Hub_sports_winter_menu,
  _ as ContentHubby_Hub_stealth,
  _ as ContentHubby_Hub_stereo_sound,
  _ as ContentHubby_Hub_stereo_sound_desc,
  _ as ContentHubby_Hub_story_driven,
  _ as ContentHubby_Hub_story_driven_menu,
  _ as ContentHubby_Hub_strategy,
  _ as ContentHubby_Hub_strategy_card_board,
  _ as ContentHubby_Hub_strategy_card_board_menu,
  _ as ContentHubby_Hub_strategy_cities_settlements,
  _ as ContentHubby_Hub_strategy_cities_settlements_menu,
  _ as ContentHubby_Hub_strategy_grand_4x,
  _ as ContentHubby_Hub_strategy_grand_4x_menu,
  _ as ContentHubby_Hub_strategy_menu,
  _ as ContentHubby_Hub_strategy_military,
  _ as ContentHubby_Hub_strategy_military_menu,
  _ as ContentHubby_Hub_strategy_moba_auto_battler,
  _ as ContentHubby_Hub_strategy_moba_auto_battler_menu,
  _ as ContentHubby_Hub_strategy_real_time,
  _ as ContentHubby_Hub_strategy_real_time_menu,
  _ as ContentHubby_Hub_strategy_sim_management,
  _ as ContentHubby_Hub_strategy_sim_management_menu,
  _ as ContentHubby_Hub_strategy_tactics,
  _ as ContentHubby_Hub_strategy_tactics_menu,
  _ as ContentHubby_Hub_strategy_turn_based,
  _ as ContentHubby_Hub_strategy_turn_based_menu,
  _ as ContentHubby_Hub_subtitle_options,
  _ as ContentHubby_Hub_subtitle_options_desc,
  _ as ContentHubby_Hub_surround_sound,
  _ as ContentHubby_Hub_surround_sound_desc,
  _ as ContentHubby_Hub_survival,
  _ as ContentHubby_Hub_survival_menu,
  _ as ContentHubby_Hub_survival_stealth,
  _ as ContentHubby_Hub_survival_stealth_menu,
  _ as ContentHubby_Hub_themes,
  _ as ContentHubby_Hub_themes_and_interests,
  _ as ContentHubby_Hub_themes_and_interests_menu,
  _ as ContentHubby_Hub_themes_menu,
  _ as ContentHubby_Hub_time_management,
  _ as ContentHubby_Hub_time_management_menu,
  _ as ContentHubby_Hub_touch_only_option,
  _ as ContentHubby_Hub_touch_only_option_desc,
  _ as ContentHubby_Hub_tower_defense,
  _ as ContentHubby_Hub_tower_defense_menu,
  _ as ContentHubby_Hub_trains,
  _ as ContentHubby_Hub_trains_desc,
  _ as ContentHubby_Hub_turnbased_rpg,
  _ as ContentHubby_Hub_typing,
  _ as ContentHubby_Hub_typing_desc,
  _ as ContentHubby_Hub_visual_novel,
  _ as ContentHubby_Hub_visual_novel_menu,
  _ as ContentHubby_Hub_walking_simulator,
  _ as ContentHubby_Hub_walking_simulator_menu,
  _ as ContentHubby_Hub_wargame,
  _ as ContentHubby_Hub_zombies_vampires,
  _ as ContentHubby_Menu_CurrentSpecials,
  _ as ContentHubby_Menu_NewAndNoteworthy,
  _ as Library_Install,
  _ as Library_Update_TryItNow2,
  _ as Store_VR_MainMenu_VR_Hardware,
  _ as Store_VR_MainMenu_Virtual_Reality,
  _ as additional_game_content_soundtracks,
  _ as api_category_coming_soon,
  _ as api_category_new_releases,
  _ as api_category_top_sellers,
  _ as browse_adultonly,
  _ as browse_demos,
  _ as browse_free,
  _ as browse_remoteplay,
  _ as btn_add_to_wishlist,
  _ as contenthub_title_controller,
  _ as contenthub_title_pccafe,
  _ as default,
  _ as discount_desc_limited_time,
  _ as discount_desc_limited_time_date,
  _ as discount_desc_preset_loyalty,
  _ as dummy,
  _ as games_osx,
  _ as genre_early_access,
  _ as genre_free2play,
  _ as label_back_catalogue,
  _ as label_deepest_discount,
  _ as label_early_beta_access,
  _ as label_for_a_limited_time_only,
  _ as label_free_week,
  _ as label_free_weekend,
  _ as label_highlighted_deals,
  _ as label_just_updated,
  _ as label_new_and_upcoming,
  _ as label_new_dlc_available,
  _ as label_play_free_generic,
  _ as label_play_free_until_custom,
  _ as label_pre_load_now,
  _ as language,
  _ as limitedtime_install_and_keep,
  _ as msg_action_buy,
  _ as msg_action_details,
  _ as msg_action_info,
  _ as msg_advanced_access,
  _ as msg_available_everywhere,
  _ as msg_available_just_released,
  _ as msg_available_just_released_from_early_access,
  _ as msg_available_new_release,
  _ as msg_available_now_free_to_play,
  _ as msg_available_now_ftp_early,
  _ as msg_coming_soon_to_steamos,
  _ as msg_early_access_now_available,
  _ as msg_free_play_until,
  _ as msg_free_play_weekend,
  _ as msg_free_to_play_just_updated,
  _ as msg_free_update,
  _ as msg_in_early_access,
  _ as msg_just_updated_with_free_dlc,
  _ as msg_new_content_now_available,
  _ as msg_new_game,
  _ as msg_new_update_available,
  _ as msg_now_available_for_mac_and_steamos,
  _ as msg_now_available_on_steamos,
  _ as msg_now_available_on_steamos_mac_and_linux,
  _ as msg_now_with_steam_workshop,
  _ as msg_now_with_steamworks,
  _ as msg_on_sale_now,
  _ as msg_play_beta_now,
  _ as msg_play_demo_now,
  _ as msg_play_it_now,
  _ as msg_play_now,
  _ as msg_preload_completed,
  _ as msg_preload_free,
  _ as msg_preload_now,
  _ as msg_preload_now_for_free,
  _ as msg_preload_you_have_completed,
  _ as msg_preload_you_have_pre,
  _ as msg_prepurchase_and_get_beta_access,
  _ as msg_prepurchase_and_play_beta_now,
  _ as msg_prepurchase_bonus,
  _ as msg_prepurchase_now,
  _ as msg_publisher_sale,
  _ as msg_publisher_weekend,
  _ as msg_steam_workshop_now_available,
  _ as msg_try_it_now,
  _ as msg_watch_movie_now,
  _ as msg_weekend_on_now,
  _ as msg_weekend_play_free,
  _ as msg_weekend_trial,
  _ as mst_weekend_description_free,
  _ as promo_ends_custom,
  _ as promo_giveaway,
  _ as spotlight_daily_deal,
  _ as spotlight_franchise_sale,
  _ as spotlight_major_update,
  _ as spotlight_midweek_deal,
  _ as spotlight_midweek_madness,
  _ as spotlight_thirdparty_event,
  _ as spotlight_weekend_deal,
  _ as spotlight_weeklong_header1,
  _ as spotlight_weeklong_sale,
  _ as store_tab_greatondeck,
  _ as store_tab_greatonframe,
  _ as store_tab_linux,
  _ as store_tab_software_home,
  _ as text_free_new_dlc_now_available,
  _ as text_new_free_to_play,
  _ as text_now_available,
  _ as text_now_available_mac,
  _ as text_now_available_on_pc_mac_and_linux,
  _ as text_now_available_steamplay,
  _ as text_now_free_to_play,
};
