var _ = `portuguese`,
  _ = `%1$s% das %2$s análises de utilizadores sobre este jogo são positivas`,
  _ = `%1$s% das %2$s análises de utilizadores em %3$s sobre este jogo são positivas`,
  _ = `%1$s% de desconto. Preço normal: %2$s. Com desconto: %3$s`,
  _ = `Preço especial: %1$s`,
  _ = `Grátis`,
  _ = `No carrinho`,
  _ = `+ Carrinho`,
  _ = `Comprar como presente`,
  _ = `Jogar agora`,
  _ = `Adicionar à biblioteca`,
  _ = `Iniciar sessão`,
  _ = `Inicia a sessão para adicionares este artigo gratuito à tua conta.`,
  _ = `Menu`,
  _ = `Os mais vendidos`,
  _ = `Novos lançamentos`,
  _ = `Em promoção`,
  _ = `Procurar na loja`,
  _ = `Limpar termo de pesquisa`,
  _ = `Lista de desejos`,
  _ = `Carrinho`,
  _ = `Jogos de R.V.`,
  _ = `Links populares`,
  _ = `Início`,
  _ = `Excelentes no Deck`,
  _ = `Excelentes no Frame`,
  _ = `Grátis para Jogar`,
  _ = `Tabelas Steam`,
  _ = `Próximos lançamentos`,
  _ = `Loja de Pontos`,
  _ = `Cartões-presente`,
  _ = `Notícias e atualizações`,
  _ = `Preferências`,
  _ = `Explorar`,
  _ = `Populares`,
  _ = `Recomendações`,
  _ = `Categorias`,
  _ = `Hardware`,
  _ = `Maneiras de jogar`,
  _ = `Secções especiais`,
  _ = `Ver tudo`,
  _ = `Mais`,
  _ = `Menu`,
  _ = `As minhas preferências`,
  _ = `Lista de desejos`,
  _ = `As minhas assinaturas`,
  _ = `Os jogos que sigo`,
  _ = `A minha conta`,
  _ = `A minha família`,
  _ = `Vistos recentemente`,
  _ = `Continua de onde paraste`,
  _ = `Recomendados para ti`,
  _ = `Da tua lista de desejos`,
  _ = `DLCs para ti`,
  _ = `Para ti`,
  _ = `Os links mais populares`,
  _ = `Os links mais populares`,
  _ = `Novidades populares`,
  _ = `Grátis para Jogar`,
  _ = `Os jogos grátis mais populares`,
  _ = `Os mais vendidos`,
  _ = `Novos lançamentos`,
  _ = `Explora conteúdo novo no Steam`,
  _ = `Vê o que está no calendário de lançamentos`,
  _ = `Descontos e eventos`,
  _ = `Todas as tabelas e estatísticas`,
  _ = `Explora os jogos mais populares por semana, mês ou ano`,
  _ = `A tua lista de desejos`,
  _ = `%1$s descontos`,
  _ = `Eventos especiais`,
  _ = `Jogos populares`,
  _ = `Promoções especiais`,
  _ = `Recomendações`,
  _ = `Fila de novos lançamentos`,
  _ = `Recomendações da Comunidade`,
  _ = `Recomendador Interativo`,
  _ = `Calendário pessoal`,
  _ = `Populares entre amigos`,
  _ = `Curadores Steam`,
  _ = `DLCs para ti`,
  _ = `A tua Fila de Descoberta`,
  _ = `Deixa que o Steam crie um conjunto personalizado de recomendações de jogos para ti`,
  _ = `Explorar a minha fila`,
  _ = `Recebe recomendações personalizadas do nosso sistema de aprendizagem automática`,
  _ = `Receber recomendações`,
  _ = `Explora uma lista personalizada de jogos que foram lançados recentemente ou que serão lançados em breve.`,
  _ = `Explorar o meu calendário`,
  _ = `NOVIDADE!`,
  _ = `Os teus géneros principais`,
  _ = `As tuas categorias principais`,
  _ = `Ver todos os géneros e temas`,
  _ = `Expandir`,
  _ = `Minimizar`,
  _ = `Ver todos os marcadores`,
  _ = `Todos os géneros e temas`,
  _ = `Hardware`,
  _ = `Hardware de R.V.`,
  _ = `Steam Deck`,
  _ = `Steam Controller`,
  _ = `Steam Machine`,
  _ = `Steam Frame`,
  _ = `Valve Index`,
  _ = `Base do Steam Deck`,
  _ = `Hardware Steam`,
  _ = `Maneiras de jogar`,
  _ = `Secções especiais`,
  _ = `Steam Next Fest`,
  _ = `Os Prémios Steam`,
  _ = `Steam Replay`,
  _ = `Laboratório Steam`,
  _ = `DLCs`,
  _ = `EVENTOS PROMOCIONAIS`,
  _ = `Vistos recentemente`,
  _ = `Pesquisas populares`,
  _ = `Resultados da pesquisa`,
  _ = `Os teus géneros principais`,
  _ = `Ver por...`,
  _ = `Nenhum item correspondeu à pesquisa.`,
  _ = `Pesquisa avançada`,
  _ = `%1$s jogos`,
  _ = `Pesquisar`,
  _ = `Menu da loja`,
  _ = `Inclui %1$s jogos`,
  _ = `NA BIBLIOTECA`,
  _ = `NA LISTA DE DESEJOS`,
  _ = `NO CARRINHO`,
  _ = `IGNORADO`,
  _ = `EXCLUÍDO POR PREFERÊNCIAS`,
  _ = `As minhas categorias:`,
  _ = `Nenhuma`,
  _ = `Filtrar por categoria`,
  _ = `Limpar filtros de categorias`,
  _ = `Criar categoria`,
  _ = `Remover categoria`,
  _ = `Remover esta categoria deste artigo`,
  _ = `Filtrar a tua lista de desejos por artigos nesta categoria`,
  _ = `Tudo`,
  _ = `Sem categoria`,
  _ = `Adicionar ou remover categorias`,
  _ = `À espera de um desconto`,
  _ = `Presentes de aniversário`,
  _ = `Recomendados por amigos`,
  _ = `Gerir categorias para "%1$s"`,
  _ = `Categorias atuais`,
  _ = `Pesquisa por nome ou adiciona uma categoria nova`,
  _ = `Criar categoria`,
  _ = `As minhas outras categorias`,
  _ = `Categorias sugeridas`,
  _ = `Este artigo da lista de desejos atingiu o limite de %1$s categorias.`,
  _ = `Avançado...`,
  _ = `NORMALMENTE`,
  _ = `+ BAIXO (ÚLT. 30 D)`,
  _ = `Este jogo esteve em promoção por %1$s nos últimos %2$s dias`,
  _ = `Este jogo está atualmente com o preço mais baixo dos últimos %1$s dias`,
  _ = `AGORA`,
  _ = `Desconto com base no preço mais baixo nos últimos 30 dias`,
  _ = `Calendário pessoal`,
  _ = `Uma lista personalizada para ti de novos jogos e próximos lançamentos`,
  _ = `E mais %1$s`,
  _ = `Explora o teu calendário pessoal completo`,
  _ = `Explorar mais`,
  _ = `Não temos nenhum lançamento novo para te recomendar neste dia. <1>Vê o resto do teu calendário!</1>`,
  _ = `NOVIDADE!`,
  _ = `Hoje`,
  _ = `dont translate`,
  _ = {
    language: _,
    review_summary_reviewrate: _,
    review_summary_reviewrate_language_specific: _,
    Discount_ARIA_Label: _,
    Discount_ARIA_Label_SpecialPrice: _,
    Price_Free: _,
    AddToCartButton_InCart: _,
    AddToCartButton_AddToCart: _,
    AddToCartButton_PurchaseAsGift: _,
    PlayGameButton_PlayNow: _,
    AddToLibraryButton: _,
    Button_SignIn: _,
    SignInToAddToLibrary_Tooltip: _,
    Menu_OpenFlyout: _,
    Menu_TopSellers: _,
    Menu_NewReleases: _,
    Menu_OnSale: _,
    Menu_SearchPlaceholder: _,
    Menu_ClearSearchTerm: _,
    Menu_Wishlist: _,
    Menu_Cart: _,
    Menu_VR: _,
    Menu_Popover_TopLinks: _,
    Menu_Popover_StoreHome: _,
    Menu_Popover_GreatonDeck: _,
    Menu_Popover_GreatonFrame: _,
    Menu_Popover_FreeToPlay: _,
    Menu_Popover_SteamCharts: _,
    Menu_Popover_Upcoming: _,
    Menu_Popover_PointsShop: _,
    Menu_Popover_GiftCards: _,
    Menu_Popover_NewsAndUpdates: _,
    Menu_Popover_Preferences: _,
    Menu_Popover_Browse: _,
    Menu_Popover_Top: _,
    Menu_Popover_Recommendations: _,
    Menu_Popover_Categories: _,
    Menu_Popover_Hardware: _,
    Menu_Popover_WaysToPlay: _,
    Menu_Popover_SpecialSections: _,
    Menu_Popover_ViewAll: _,
    Menu_Popover_More: _,
    Menu_Popover_Menu: _,
    Menu_Section_Browse_MyPreferences: _,
    Menu_Section_Browse_MyWishlist: _,
    Menu_Section_Browse_MySubscriptions: _,
    Menu_Section_Browse_MyFollowedGames: _,
    Menu_Section_Browse_MyAccount: _,
    Menu_Section_Browse_MyFamily: _,
    Menu_Section_Browse_RecentlyViewed: _,
    Menu_Section_Browse_PickUpWhereYouLeftOff: _,
    Menu_Section_Browse_Recommended: _,
    Menu_Section_Browse_FromYourWishlist: _,
    Menu_Section_Browse_DLCForYou: _,
    Menu_Section_Browse_ForYou: _,
    Menu_Section_Browse_BrowseTop: _,
    Menu_Section_Browse_Top: _,
    Menu_Section_Browse_PopularNew: _,
    Menu_Section_Browse_FreeToPlay: _,
    Menu_Section_Browse_TopFreeToPlay: _,
    Menu_Section_Browse_TopSellers: _,
    Menu_Section_Browse_NewReleases: _,
    Menu_Section_Browse_NewReleases_Desc: _,
    Menu_Section_Browse_Upcoming_Desc: _,
    Menu_Section_Browse_Discounts: _,
    Menu_Section_Browse_Charts: _,
    Menu_Section_Browse_Charts_Desc: _,
    Menu_Section_Browse_Discounts_YourWishlist: _,
    Menu_Section_Browse_Discounts_YourWishlist_Discounts: _,
    Menu_Section_Browse_Discounts_SpecialEvents: _,
    Menu_Section_Browse_Discounts_PopularTitles: _,
    Menu_Section_Browse_Discounts_SpecialOffers: _,
    Menu_Section_Recommendations: _,
    Menu_Section_Recommendations_NewReleasesQueue: _,
    Menu_Section_Recommendations_CommunityRecommendations: _,
    Menu_Section_Recommendations_InteractiveRecommender: _,
    Menu_Section_Recommendations_PersonalCalendar: _,
    Menu_Section_Recommendations_PopularAmongFriends: _,
    Menu_Section_Recommendations_SteamCurators: _,
    Menu_Section_Recommendations_DLCForYou: _,
    Menu_Section_Recommendations_DiscoveryQueue_Title: _,
    Menu_Section_Recommendations_DiscoveryQueue_Description: _,
    Menu_Section_Recommendations_DiscoveryQueue_ActionButton: _,
    Menu_Section_Recommendations_InteractiveRecommender_Description: _,
    Menu_Section_Recommendations_InteractiveRecommender_ActionButton: _,
    Menu_Section_Recommendations_PersonalCalendar_Description: _,
    Menu_Section_Recommendations_PersonalCalendar_ActionButton: _,
    Menu_Section_Recommendations_New: _,
    Menu_Section_Categories_YourTopGenres: _,
    Menu_Section_Categories_YourTopCategories: _,
    Menu_Section_Categories_ViewAll: _,
    Menu_Section_Categories_Expand: _,
    Menu_Section_Categories_Collapse: _,
    Menu_Section_Categories_ViewAllTags: _,
    Menu_Section_Categories_GenresAndThemes: _,
    Menu_Section_Hardware: _,
    Menu_Section_Hardware_VRHardware: _,
    Menu_Section_Hardware_SteamDeck: _,
    Menu_Section_Hardware_SteamController: _,
    Menu_Section_Hardware_SteamMachine: _,
    Menu_Section_Hardware_SteamFrame: _,
    Menu_Section_Hardware_ValveIndex: _,
    Menu_Section_Hardware_SteamDeckDock: _,
    Menu_Section_Hardware_Family: _,
    Menu_Section_WaysToPlay: _,
    Menu_Section_SpecialSections: _,
    Menu_Section_SpecialSections_NextFest: _,
    Menu_Section_SpecialSections_SteamAwards: _,
    Menu_Section_SpecialSections_SteamReplay: _,
    Menu_Section_SpecialSections_SteamLabs: _,
    Menu_Section_SpecialSections_DLCForYou: _,
    Menu_Section_SpecialSections_SaleEvents: _,
    Menu_SearchBar_RecentlyViewed: _,
    Menu_SearchBar_PopularSearches: _,
    Menu_SearchBar_SearchResults: _,
    Menu_SearchBar_YourTopGenres: _,
    Menu_SearchBar_BrowseBy: _,
    Menu_SearchBar_NoMatches: _,
    Menu_SearchBar_AdvancedSearch: _,
    Menu_SearchBar_CategoryGameCount: _,
    Menu_Search: _,
    Menu_Label: _,
    Menu_IncludesXGames: _,
    ItemFlag_InLibrary: _,
    ItemFlag_OnWishlist: _,
    ItemFlag_InCart: _,
    ItemFlag_Ignored: _,
    ItemFlag_ExcludedByPreferences: _,
    Wishlist_Controls_Categories_Header: _,
    Wishlist_Categories_None: _,
    Wishlist_Gamepad_Filter_Category: _,
    Wishlist_Gamepad_Filter_Clear_Category: _,
    Wishlist_Gamepad_Add_Category: _,
    Wishlist_Gamepad_Removecategory: _,
    Wishlist_Controls_Categories_Remove_Tooltip: _,
    Wishlist_Controls_Categories_Filter_Tooltip: _,
    Wishlist_Controls_Categories_All: _,
    Wishlist_Controls_Categories_Uncategorized: _,
    Wishlist_Controls_Categories_Manage: _,
    Wishlist_Categories_Suggested_Discount: _,
    Wishlist_Categories_Suggested_Birthday: _,
    Wishlist_Categories_Suggested_Recommended: _,
    Wishlist_Controls_Categories_Manageitem: _,
    Wishlist_Controls_Categories_Header_Current: _,
    Wishlist_Categories_Dialog_Search: _,
    Wishlist_Categories_Dialog_Add: _,
    Wishlist_Controls_Categories_Header_Other: _,
    Wishlist_Controls_Categories_Header_Suggested: _,
    Wishlist_Categories_Max_Per_App_Reached: _,
    Wishlist_Categories_Dialog_Advanced: _,
    Price_History_Normal_Price: _,
    Price_History_Recent_Low_Price: _,
    Price_History_Recent_Low_Price_Ttip: _,
    Price_History_Current_Low_Price_Ttip: _,
    Price_History_Current_Price: _,
    Price_History_Lowest_Previous_30: _,
    PersonalCalendar_Title: _,
    PersonalCalendar_Subtitle: _,
    PersonalCalendar_More: _,
    PersonalCalendar_Full: _,
    PersonalCalendar_Explore: _,
    PersonalCalendar_EmptyDay: _,
    NewBadge: _,
    Time_Today: _,
    store_ui_dummy: _,
  };
export {
  _ as AddToCartButton_AddToCart,
  _ as AddToCartButton_InCart,
  _ as AddToCartButton_PurchaseAsGift,
  _ as AddToLibraryButton,
  _ as Button_SignIn,
  _ as Discount_ARIA_Label,
  _ as Discount_ARIA_Label_SpecialPrice,
  _ as ItemFlag_ExcludedByPreferences,
  _ as ItemFlag_Ignored,
  _ as ItemFlag_InCart,
  _ as ItemFlag_InLibrary,
  _ as ItemFlag_OnWishlist,
  _ as Menu_Cart,
  _ as Menu_ClearSearchTerm,
  _ as Menu_IncludesXGames,
  _ as Menu_Label,
  _ as Menu_NewReleases,
  _ as Menu_OnSale,
  _ as Menu_OpenFlyout,
  _ as Menu_Popover_Browse,
  _ as Menu_Popover_Categories,
  _ as Menu_Popover_FreeToPlay,
  _ as Menu_Popover_GiftCards,
  _ as Menu_Popover_GreatonDeck,
  _ as Menu_Popover_GreatonFrame,
  _ as Menu_Popover_Hardware,
  _ as Menu_Popover_Menu,
  _ as Menu_Popover_More,
  _ as Menu_Popover_NewsAndUpdates,
  _ as Menu_Popover_PointsShop,
  _ as Menu_Popover_Preferences,
  _ as Menu_Popover_Recommendations,
  _ as Menu_Popover_SpecialSections,
  _ as Menu_Popover_SteamCharts,
  _ as Menu_Popover_StoreHome,
  _ as Menu_Popover_Top,
  _ as Menu_Popover_TopLinks,
  _ as Menu_Popover_Upcoming,
  _ as Menu_Popover_ViewAll,
  _ as Menu_Popover_WaysToPlay,
  _ as Menu_Search,
  _ as Menu_SearchBar_AdvancedSearch,
  _ as Menu_SearchBar_BrowseBy,
  _ as Menu_SearchBar_CategoryGameCount,
  _ as Menu_SearchBar_NoMatches,
  _ as Menu_SearchBar_PopularSearches,
  _ as Menu_SearchBar_RecentlyViewed,
  _ as Menu_SearchBar_SearchResults,
  _ as Menu_SearchBar_YourTopGenres,
  _ as Menu_SearchPlaceholder,
  _ as Menu_Section_Browse_BrowseTop,
  _ as Menu_Section_Browse_Charts,
  _ as Menu_Section_Browse_Charts_Desc,
  _ as Menu_Section_Browse_DLCForYou,
  _ as Menu_Section_Browse_Discounts,
  _ as Menu_Section_Browse_Discounts_PopularTitles,
  _ as Menu_Section_Browse_Discounts_SpecialEvents,
  _ as Menu_Section_Browse_Discounts_SpecialOffers,
  _ as Menu_Section_Browse_Discounts_YourWishlist,
  _ as Menu_Section_Browse_Discounts_YourWishlist_Discounts,
  _ as Menu_Section_Browse_ForYou,
  _ as Menu_Section_Browse_FreeToPlay,
  _ as Menu_Section_Browse_FromYourWishlist,
  _ as Menu_Section_Browse_MyAccount,
  _ as Menu_Section_Browse_MyFamily,
  _ as Menu_Section_Browse_MyFollowedGames,
  _ as Menu_Section_Browse_MyPreferences,
  _ as Menu_Section_Browse_MySubscriptions,
  _ as Menu_Section_Browse_MyWishlist,
  _ as Menu_Section_Browse_NewReleases,
  _ as Menu_Section_Browse_NewReleases_Desc,
  _ as Menu_Section_Browse_PickUpWhereYouLeftOff,
  _ as Menu_Section_Browse_PopularNew,
  _ as Menu_Section_Browse_RecentlyViewed,
  _ as Menu_Section_Browse_Recommended,
  _ as Menu_Section_Browse_Top,
  _ as Menu_Section_Browse_TopFreeToPlay,
  _ as Menu_Section_Browse_TopSellers,
  _ as Menu_Section_Browse_Upcoming_Desc,
  _ as Menu_Section_Categories_Collapse,
  _ as Menu_Section_Categories_Expand,
  _ as Menu_Section_Categories_GenresAndThemes,
  _ as Menu_Section_Categories_ViewAll,
  _ as Menu_Section_Categories_ViewAllTags,
  _ as Menu_Section_Categories_YourTopCategories,
  _ as Menu_Section_Categories_YourTopGenres,
  _ as Menu_Section_Hardware,
  _ as Menu_Section_Hardware_Family,
  _ as Menu_Section_Hardware_SteamController,
  _ as Menu_Section_Hardware_SteamDeck,
  _ as Menu_Section_Hardware_SteamDeckDock,
  _ as Menu_Section_Hardware_SteamFrame,
  _ as Menu_Section_Hardware_SteamMachine,
  _ as Menu_Section_Hardware_VRHardware,
  _ as Menu_Section_Hardware_ValveIndex,
  _ as Menu_Section_Recommendations,
  _ as Menu_Section_Recommendations_CommunityRecommendations,
  _ as Menu_Section_Recommendations_DLCForYou,
  _ as Menu_Section_Recommendations_DiscoveryQueue_ActionButton,
  _ as Menu_Section_Recommendations_DiscoveryQueue_Description,
  _ as Menu_Section_Recommendations_DiscoveryQueue_Title,
  _ as Menu_Section_Recommendations_InteractiveRecommender,
  _ as Menu_Section_Recommendations_InteractiveRecommender_ActionButton,
  _ as Menu_Section_Recommendations_InteractiveRecommender_Description,
  _ as Menu_Section_Recommendations_New,
  _ as Menu_Section_Recommendations_NewReleasesQueue,
  _ as Menu_Section_Recommendations_PersonalCalendar,
  _ as Menu_Section_Recommendations_PersonalCalendar_ActionButton,
  _ as Menu_Section_Recommendations_PersonalCalendar_Description,
  _ as Menu_Section_Recommendations_PopularAmongFriends,
  _ as Menu_Section_Recommendations_SteamCurators,
  _ as Menu_Section_SpecialSections,
  _ as Menu_Section_SpecialSections_DLCForYou,
  _ as Menu_Section_SpecialSections_NextFest,
  _ as Menu_Section_SpecialSections_SaleEvents,
  _ as Menu_Section_SpecialSections_SteamAwards,
  _ as Menu_Section_SpecialSections_SteamLabs,
  _ as Menu_Section_SpecialSections_SteamReplay,
  _ as Menu_Section_WaysToPlay,
  _ as Menu_TopSellers,
  _ as Menu_VR,
  _ as Menu_Wishlist,
  _ as NewBadge,
  _ as PersonalCalendar_EmptyDay,
  _ as PersonalCalendar_Explore,
  _ as PersonalCalendar_Full,
  _ as PersonalCalendar_More,
  _ as PersonalCalendar_Subtitle,
  _ as PersonalCalendar_Title,
  _ as PlayGameButton_PlayNow,
  _ as Price_Free,
  _ as Price_History_Current_Low_Price_Ttip,
  _ as Price_History_Current_Price,
  _ as Price_History_Lowest_Previous_30,
  _ as Price_History_Normal_Price,
  _ as Price_History_Recent_Low_Price,
  _ as Price_History_Recent_Low_Price_Ttip,
  _ as SignInToAddToLibrary_Tooltip,
  _ as Time_Today,
  _ as Wishlist_Categories_Dialog_Add,
  _ as Wishlist_Categories_Dialog_Advanced,
  _ as Wishlist_Categories_Dialog_Search,
  _ as Wishlist_Categories_Max_Per_App_Reached,
  _ as Wishlist_Categories_None,
  _ as Wishlist_Categories_Suggested_Birthday,
  _ as Wishlist_Categories_Suggested_Discount,
  _ as Wishlist_Categories_Suggested_Recommended,
  _ as Wishlist_Controls_Categories_All,
  _ as Wishlist_Controls_Categories_Filter_Tooltip,
  _ as Wishlist_Controls_Categories_Header,
  _ as Wishlist_Controls_Categories_Header_Current,
  _ as Wishlist_Controls_Categories_Header_Other,
  _ as Wishlist_Controls_Categories_Header_Suggested,
  _ as Wishlist_Controls_Categories_Manage,
  _ as Wishlist_Controls_Categories_Manageitem,
  _ as Wishlist_Controls_Categories_Remove_Tooltip,
  _ as Wishlist_Controls_Categories_Uncategorized,
  _ as Wishlist_Gamepad_Add_Category,
  _ as Wishlist_Gamepad_Filter_Category,
  _ as Wishlist_Gamepad_Filter_Clear_Category,
  _ as Wishlist_Gamepad_Removecategory,
  _ as default,
  _ as language,
  _ as review_summary_reviewrate,
  _ as review_summary_reviewrate_language_specific,
  _ as store_ui_dummy,
};
