var _ = `所有包含此內容的組合包：`,
  _ = `排序依據：`,
  _ = `熱門`,
  _ = `價格`,
  _ = `組合包折扣`,
  _ = `名稱`,
  _ = `推薦`,
  _ = `您的完整組合包`,
  _ = `這些組合包的所有內容都已在您的收藏庫中`,
  _ = `集齊全套組合包`,
  _ = `購買您收藏庫中尚未擁有的其餘商品以集齊整套組合包`,
  _ = `必須一併購買的組合包`,
  _ = `所有商品合併成一個組合包；必須購買整套`,
  _ = `© %1$s Valve Corporation. 版權所有。所有商標皆為各自所有權人在美國與其它國家（地區）之財產。`,
  _ = `所有價格均包含增值稅（如適用）。`,
  _ = `隱私權政策`,
  _ = `法律聲明`,
  _ = `輔助功能`,
  _ = `Steam 訂戶協議`,
  _ = `退款`,
  _ = `Cookie`,
  _ = `關於 Valve`,
  _ = `商業解決方案`,
  _ = `回收`,
  _ = `Steamworks`,
  _ = `Source 引擎`,
  _ = `人才招募`,
  _ = `禮物卡`,
  _ = `Steam 發行`,
  _ = `客服`,
  _ = `%1$s 的願望清單`,
  _ = `%1$s 的願望清單`,
  _ = `購物車（%1$s）`,
  _ = `檢視購物車`,
  _ = `願望清單（%1$s）`,
  _ = `選項`,
  _ = `排序方式：%1$s`,
  _ = `建立可分享的連結`,
  _ = `您的排序`,
  _ = `個人自訂排序`,
  _ = `暢銷商品`,
  _ = `發行日期`,
  _ = `新增日期`,
  _ = `評論分數`,
  _ = `定價`,
  _ = `名稱`,
  _ = `折扣`,
  _ = `可分享的連結`,
  _ = `撤銷所有連結`,
  _ = `連結已撤銷！`,
  _ = `無法產生可分享的連結（錯誤 %1$s）`,
  _ = `有此連結的人可檢視您在目前篩選條件下的願望清單，無論您的個人檔案隱私設定為何；但他們無法改變篩選條件。`,
  _ = `檢視`,
  _ = `詳細`,
  _ = `精簡`,
  _ = `作業系統`,
  _ = `任何作業系統`,
  _ = `macOS`,
  _ = `SteamOS + Linux`,
  _ = `類型`,
  _ = `遊戲`,
  _ = `軟體`,
  _ = `可下載內容`,
  _ = `影片`,
  _ = `定價`,
  _ = `折扣`,
  _ = `清單上的所有項目`,
  _ = `所有折扣項目`,
  _ = `%1$s% 或更高`,
  _ = `任何價格`,
  _ = `%1$s 以下`,
  _ = `免費`,
  _ = `排除`,
  _ = `相關項目`,
  _ = `搶先體驗`,
  _ = `此作品目前處於搶先體驗階段`,
  _ = `先行版`,
  _ = `僅限 VR`,
  _ = `有試玩版`,
  _ = `以試玩版篩選願望清單內的項目`,
  _ = `Deck 相容性`,
  _ = `已驗證`,
  _ = `可遊玩`,
  _ = `標籤`,
  _ = `以此標籤篩選願望清單內的項目`,
  _ = `使用者標籤：`,
  _ = `%1$s：%2$s`,
  _ = `類別`,
  _ = `類別：`,
  _ = `<1>類別：</1><2>%1$s</2>`,
  _ = `新增類別`,
  _ = `進階類別管理`,
  _ = `選擇要編輯的類別`,
  _ = `類別名稱`,
  _ = `重新命名`,
  _ = `您已經有一個使用此名稱的類別`,
  _ = `重新命名此類別時發生錯誤（代碼：%1$s）`,
  _ = `沒有與搜尋相符的願望清單項目。`,
  _ = `全部`,
  _ = `無`,
  _ = `顯示 %2$s 個項目中的前 %1$s 個。搜尋以縮小清單範圍。`,
  _ = `%1$s 個項目無法更新`,
  _ = `%1$s 個項目無法更新`,
  _ = `處理中`,
  _ = `新增：%1$s`,
  _ = `移除：%1$s`,
  _ = `還原`,
  _ = `套用變更`,
  _ = `新增 / 移除類別`,
  _ = `%1$s 個項目`,
  _ = `%1$s 個項目`,
  _ = `搜尋結果：`,
  _ = `名稱包含「%2$s」的 %1$s 個項目`,
  _ = `名稱包含「%2$s」的 %1$s 個項目`,
  _ = `類別為「%2$s」的 %1$s 個項目`,
  _ = `類別為「%2$s」的 %1$s 個項目`,
  _ = `類別包含「%2$s」的 %1$s 個項目`,
  _ = `類別包含「%2$s」的 %1$s 個項目`,
  _ = `標籤為「%2$s」的 %1$s 個項目`,
  _ = `標籤為「%2$s」的 %1$s 個項目`,
  _ = `標籤包含「%2$s」的 %1$s 個項目`,
  _ = `標籤包含「%2$s」的 %1$s 個項目`,
  _ = `依名稱或標籤搜尋`,
  _ = `搜尋名稱、標籤或類別`,
  _ = `整體評論：`,
  _ = `%1$s的評論：`,
  _ = `發行日期：`,
  _ = `新增於 %1$s`,
  _ = `移除`,
  _ = `從您的願望清單移除此項目`,
  _ = `（無法使用的項目）`,
  _ = `您所在的地區無法使用此項目。`,
  _ = `此項目已下架。`,
  _ = `您的國家 / 地區禁止 18 歲以下使用者觀賞成人內容。在您存取成人內容前，Valve 需要驗證您已年滿 18 歲。`,
  _ = `依照英國《網路安全法》（Online Safety Act），在您存取成人色情內容前，Valve 需要驗證您已年滿 18 歲。`,
  _ = `新增信用卡`,
  _ = `您的願望清單是空的。`,
  _ = `瀏覽商店並使用「新增至您的願望清單」按鈕來填滿願望清單。`,
  _ = `深入了解 Steam 願望清單`,
  _ = `登入以查看您的願望清單`,
  _ = `此願望清單是空的。`,
  _ = `無符合項目。`,
  _ = `此願望清單中有 %1$s 個項目，但沒有符合您的願望清單篩選條件和 / 或商店偏好設定的項目。`,
  _ = `此願望清單中有 %1$s 個項目，但沒有符合您的願望清單篩選條件和 / 或<1>商店偏好設定</1>的項目。`,
  _ = `重新排序`,
  _ = `取消重新排序`,
  _ = `放置在這裡`,
  _ = `選項`,
  _ = `移除`,
  _ = `造訪商店頁面`,
  _ = `願望清單 - 錯誤`,
  _ = `錯誤`,
  _ = `未知錯誤`,
  _ = `找不到個人檔案`,
  _ = `無法載入使用者的願望清單。`,
  _ = `此願望清單分享連結無效或已過期。`,
  _ = `願望清單通知遊戲`,
  _ = `%1$s 的帳戶`,
  _ = `帳戶 - 錯誤`,
  _ = `帳戶`,
  _ = `首頁`,
  _ = `帳戶詳細資料`,
  _ = `商店偏好設定`,
  _ = `語言偏好`,
  _ = `通知設定`,
  _ = `裝置`,
  _ = `安全性與裝置`,
  _ = `已授權的裝置（影片）`,
  _ = `行動遊戲裝置`,
  _ = `遊戲測試`,
  _ = `親友群組管理`,
  _ = `資料與瀏覽`,
  _ = `VR`,
  _ = `非常適合 Deck`,
  _ = `Frame 本機遊玩`,
  _ = `商店首頁`,
  _ = `類別`,
  _ = `搜尋 Steam`,
  _ = `載入限定存取資料失敗。`,
  _ = `Steam 遊戲測試邀請`,
  _ = `接受邀請`,
  _ = `拒絕邀請`,
  _ = `您已受邀加入一項 Steam 遊戲測試！`,
  _ = `您受邀加入限定發行！`,
  _ = `%1$s 邀請您加入一項 Steam 遊戲測試！`,
  _ = `%1$s 邀請您參與限定發行！`,
  _ = `沒有等待您回應的 Steam 遊戲測試或限定發行邀請。`,
  _ = `歡迎參加遊戲測試！現可在收藏庫中安裝「%1$s」。`,
  _ = `歡迎參加限定發行！現在即可在收藏庫中安裝「%1$s」。`,
  _ = `歡迎加入遊戲測試！「%1$s」目前並未開放。請留意開發者近期的發行計畫。`,
  _ = `檢視收藏庫`,
  _ = `Steam 遊戲測試是什麼？`,
  _ = `Steam 遊戲測試是用於協助正在開發中的遊戲進行測試。接受邀請或開發者同意授予存取權的要求，即會將遊戲自動加入您的收藏庫中。`,
  _ = `請參閱開發者提供的資訊以了解個別遊戲測試的性質。Steam 遊戲測試存取權不保證遊戲發行後會擁有存取權。`,
  _ = `已忽略的 Steam 遊戲測試邀請`,
  _ = `您已拒絕下列遊戲的遊戲測試或限定發行邀請。除非將遊戲從此清單中移除，否則您將不會再收到更多邀請。`,
  _ = `移除`,
  _ = `取消`,
  _ = `送出`,
  _ = `這是您有的此遊戲測試的最後一個可用邀請。`,
  _ = `這是您有的此限定發行的最後一個可用邀請。`,
  _ = `發送邀請至：`,
  _ = `正在邀請 %1$s…`,
  _ = `%1$s 已受邀！該邀請將會出現在其%2$s通知中。`,
  _ = `無法邀請 %1$s。他可能已受邀，或此遊戲可能在其地區不提供。`,
  _ = `邀請寄送記錄`,
  _ = `您最近向好友發送的遊戲測試和限定發行邀請`,
  _ = `已邀請 %1$s 加入 %2$s`,
  _ = `參加 Steam 遊戲測試`,
  _ = `您並未加入任何正在進行的 Steam 遊戲測試或限定發行。`,
  _ = `您有可用的邀請`,
  _ = `您有 %1$s 個可用的邀請`,
  _ = `您有 %1$s 個可用的邀請`,
  _ = `您可以透過邀請好友來給予他們此遊戲測試的存取權。`,
  _ = `加入的玩家數量增加時，可用的邀請數量可能會隨著改變。`,
  _ = `與時程和所含內容相關的更多詳情，可能已公佈在%1$s或%2$s中。`,
  _ = `商店頁面`,
  _ = `新聞中心`,
  _ = `此遊戲測試目前並未開放。`,
  _ = `您已用完所有的好友邀請`,
  _ = `邀請好友`,
  _ = `選擇邀請收件人`,
  _ = `依好友名稱搜尋…`,
  _ = `無法載入您的好友。`,
  _ = `無法邀請某些好友，因為他們與您成為好友的時間不到 30 天、已經有遊戲的存取權，或是基於其它原因而不符資格。`,
  _ = `無法邀請某些好友，因為他們已經有遊戲的存取權，或是基於其它原因而不符資格。`,
  _ = `限定發行`,
  _ = `您可以透過邀請好友來給予他們此限定發行的存取權。`,
  _ = `%1$s 正逐漸增加最初限定發行階段的玩家人數。%2$s或%3$s上可能有提供更多詳情。`,
  _ = `限定發行是什麼？`,
  _ = `有些免費遊玩遊戲會利用限定發行在遊戲首次發行時來慢慢增加玩家數。接受邀請或獲得開發者提供的存取請求後，該遊戲會加入您的收藏庫中，您可立即開始遊玩。`,
  _ = `Steam 商店網站地圖`,
  _ = `商店首頁`,
  _ = `我的帳戶`,
  _ = `我的帳戶詳細資料`,
  _ = `我的商店偏好設定`,
  _ = `親友群組管理`,
  _ = `安全性與裝置`,
  _ = `語言偏好`,
  _ = `Cookie 與瀏覽`,
  _ = `通知設定`,
  _ = `購物車`,
  _ = `購物車（%1$s）`,
  _ = `願望清單`,
  _ = `願望清單（%1$s）`,
  _ = `關注的遊戲與軟體`,
  _ = `關注的遊戲與軟體（%1$s）`,
  _ = `榜單與列表`,
  _ = `暢銷排行`,
  _ = `最多人遊玩`,
  _ = `新推出`,
  _ = `即將發行`,
  _ = `免費遊玩`,
  _ = `Steam 榜單`,
  _ = `特價中`,
  _ = `推薦商品`,
  _ = `探索佇列`,
  _ = `新推出佇列`,
  _ = `社群推薦`,
  _ = `互動式推薦專員`,
  _ = `好友間熱門`,
  _ = `Steam 鑑賞家`,
  _ = `為您推薦的 DLC`,
  _ = `硬體`,
  _ = `Steam Deck`,
  _ = `Steam Deck 基座`,
  _ = `VR 硬體`,
  _ = `VR 遊戲`,
  _ = `非常適合 Deck 的遊戲`,
  _ = `支援控制器的遊戲`,
  _ = `遊戲方式`,
  _ = `新聞與更新`,
  _ = `近期更新過的遊戲`,
  _ = `您近期更新過的遊戲`,
  _ = `您即將到來的活動`,
  _ = `精選新聞`,
  _ = `Steam 官方新聞與更新`,
  _ = `促銷與活動`,
  _ = `特別優惠`,
  _ = `特賣活動`,
  _ = `Steam 回顧`,
  _ = `Steam 新品節`,
  _ = `Steam 大獎`,
  _ = `特殊欄位`,
  _ = `Steam 點數商店`,
  _ = `禮物卡`,
  _ = `類型`,
  _ = `主題`,
  _ = `您近期內提出的請求次數過於頻繁。請稍後再重試您的請求。`,
  _ = `綜合討論`,
  _ = `已檢舉的文章`,
  _ = `工作坊討論`,
  _ = `交易`,
  _ = `活動與公告`,
  _ = `互動式推薦專員`,
  _ = `與您相似的玩家都喜愛…`,
  _ = `探索我們的機器學習系統根據您的 Steam 遊玩紀錄與其他數百萬名玩家的比較結果，為您個人挑選的推薦項目。請使用控制條和篩選條件自訂推薦結果，再儲存設定，好讓 Steam 記得您的偏好。`,
  _ = `您的相關遊戲時間`,
  _ = `%1$s 款遊戲`,
  _ = `前 %1$s 款遊戲`,
  _ = `近期遊戲`,
  _ = `%1$s 小時`,
  _ = `共 %1$s 小時`,
  _ = `最後執行時間：%1$s`,
  _ = `最後執行時間：超過 10 年前`,
  _ = `包含`,
  _ = `排除`,
  _ = `依熱門程度加權`,
  _ = `熱門`,
  _ = `小眾`,
  _ = `依發行時間篩選`,
  _ = `較舊`,
  _ = `較新`,
  _ = `有史以來`,
  _ = `5 年`,
  _ = `3 年`,
  _ = `2 年`,
  _ = `1 年`,
  _ = `6 個月`,
  _ = `為您推薦`,
  _ = `發行時間：%1$s`,
  _ = `於願望清單內`,
  _ = `加入購物車`,
  _ = `新增至您的願望清單`,
  _ = `免費遊玩`,
  _ = `輸入標籤名稱`,
  _ = `新增標籤篩選條件`,
  _ = `新增標籤排除條件`,
  _ = `排除願望清單中的遊戲`,
  _ = `僅包含有折扣的遊戲`,
  _ = `上個月發行`,
  _ = `最近 7 天發行`,
  _ = `即將推出`,
  _ = `您的個人行事曆`,
  _ = `包含 %1$s 款近期或即將推出遊戲的個人化列表`,
  _ = `標籤選擇器`,
  _ = `依標籤篩選…`,
  _ = `隱藏已擁有的遊戲`,
  _ = `仍會顯示結束搶先體驗後正式發行的遊戲`,
  _ = `隱藏搶先體驗中的遊戲`,
  _ = `僅顯示願望清單中的遊戲`,
  _ = `遊戲數量`,
  _ = `精簡行事曆`,
  _ = `可選的覆寫`,
  _ = `帳戶 ID`,
  _ = `查看全部 %1$s 款`,
  _ = `登入以檢視個人化推薦項目。`,
  _ = `全部展開`,
  _ = `Steam 實驗室實驗編號 16 | <1>了解詳情並留下意見回饋</1>`,
  _ = `願望清單中的遊戲`,
  _ = `顯示`,
  _ = `隱藏`,
  _ = `僅限`,
  _ = `願望清單內的遊戲過多，已停用`,
  _ = `載入行事曆時發生錯誤，請再試一次。`,
  _ = `《%1$s》的組合包列表`,
  _ = `組合包列表`,
  _ = `所有內含遊戲《%1$s》的組合包。`,
  _ = `Steam Deck 驗證`,
  _ = `《%1$s》屬於 Steam Deck 已驗證類型`,
  _ = `網站錯誤`,
  _ = `糟糕，抱歉！`,
  _ = `處理您的請求時發生錯誤。`,
  _ = `欄位數量必須大於零。`,
  _ = `電子郵件網域已用於另一個媒體。`,
  _ = `新增媒體失敗。`,
  _ = `電子郵件網域不能為空白。`,
  _ = `無效的電子郵件網域。`,
  _ = `帳戶已在一個媒體中。`,
  _ = `新增帳戶至媒體失敗。`,
  _ = `電子郵件網域`,
  _ = `欄位數量`,
  _ = `新增`,
  _ = `新增媒體：`,
  _ = `%1$s，已使用 %2$s/%3$s 個欄位`,
  _ = `顯示歷史記錄`,
  _ = `%1$s 的歷史記錄`,
  _ = `媒體序號由 %2$s 授予 %1$s`,
  _ = `%1$s 的媒體序號由 %2$s 撤銷`,
  _ = `媒體由 %1$s 建立`,
  _ = `媒體由 %1$s 更新`,
  _ = `電子郵件網域設定為 %1$s`,
  _ = `欄位數量設定為 %1$s`,
  _ = `媒體由 %1$s 刪除`,
  _ = `媒體由 %1$s 取消刪除`,
  _ = `媒體由 %1$s 設定為模擬預覽`,
  _ = `由 %1$s 套用的模擬預覽變更`,
  _ = `使用者 %1$s 排定由 %2$s 加入`,
  _ = `使用者 %1$s 排定由 %2$s 移除`,
  _ = `客服`,
  _ = `授予對象`,
  _ = `授予時間`,
  _ = `是否為群組管理員？`,
  _ = `要新增的 SteamID`,
  _ = `確定`,
  _ = `取消`,
  _ = `是`,
  _ = `否`,
  _ = `全部`,
  _ = `使用中`,
  _ = `已刪除`,
  _ = `空白`,
  _ = `媒體內無管理員`,
  _ = `媒體：`,
  _ = `好友代碼：`,
  _ = `放棄您的媒體序號： `,
  _ = `確定要放棄您的媒體序號？`,
  _ = `媒體歷史記錄`,
  _ = `新增成員`,
  _ = `顯示歷史記錄`,
  _ = `帳戶`,
  _ = `未找到宣傳片`,
  _ = `宣傳片`,
  _ = `小型宣傳片`,
  _ = `儲存您的通知設定時發生錯誤`,
  _ = `載入您的通知設定時發生錯誤`,
  _ = `這個取消訂閱的連結無效或已過期。請登入並前往<1>通知設定</1>`,
  _ = `若啟用用戶端快顯通知或行動應用程式，就會自動啟用動態消息。`,
  _ = `僅通知 %1$s 關於這些願望清單類別的消息`,
  _ = `幀率預估器`,
  _ = `選擇一款應用程式和一個電腦配置以獲得預估幀率圖表，此預估幀率是根據其他 Steam 使用者的幀率所計算得出`,
  _ = `CPU`,
  _ = `系統 RAM`,
  _ = `GPU`,
  _ = `您已儲存的硬體`,
  _ = `您沒有已儲存的硬體。`,
  _ = `從硬體中選擇以檢視預估幀率。`,
  _ = `<未選擇>`,
  _ = `若在 Steam 用戶端中檢視此項，則可新增目前使用的硬體。`,
  _ = `新增已儲存的硬體`,
  _ = `新增已儲存的硬體（不在用戶端中）`,
  _ = `若您希望為幀率預估器提供匿名資料以協助改善預估器，可點擊下方連結前往偏好設定並在資料收集區塊中選擇參與。`,
  _ = `偏好設定`,
  _ = `FPS`,
  _ = `搜尋遊戲`,
  _ = `選擇一個 CPU`,
  _ = `選擇一個 GPU`,
  _ = `符合訓練遊戲條目的數量`,
  _ = `符合訓練 CPU 條目的數量`,
  _ = `符合訓練 GPU 條目的數量`,
  _ = `不明`,
  _ = `寄送禮物卡`,
  _ = ``,
  _ = {
    BundleList_SubTitle: _,
    BundleList_SortBy: _,
    BundleList_SortBy_Popular: _,
    BundleList_SortBy_Price: _,
    BundleList_SortBy_Discount: _,
    BundleList_SortBy_Name: _,
    BundleList_SortBy_Recommend: _,
    BundleList_AllInLibrary: _,
    BundleList_AllInLibrarySubtitle: _,
    BundleList_CompleteTheSet: _,
    BundleList_CompleteTheSetSubtitle: _,
    BundleList_MustPurchaseAsSet: _,
    BundleList_MustPurchaseAsSetSubtitle: _,
    footer_legal_notice: _,
    footer_vat_included: _,
    footer_privacy_policy: _,
    footer_legal: _,
    footer_accessibility: _,
    footer_ssa: _,
    footer_refunds: _,
    footer_cookies: _,
    footer_about_valve: _,
    footer_business_solutions: _,
    footer_recycling: _,
    footer_steamworks: _,
    footer_source_engine: _,
    footer_jobs: _,
    footer_walletcode: _,
    footer_steam_distribution: _,
    footer_nav_help_support: _,
    wishlist_title: _,
    wishlist_header: _,
    cart_count: _,
    cart_view_cart: _,
    wishlist_count: _,
    wishlist_options_button: _,
    wishlist_sortby_button: _,
    wishlist_share_tooltip: _,
    wishlist_controls_sortby_order: _,
    wishlist_controls_sortby_their_order: _,
    wishlist_controls_sortby_topsellers: _,
    wishlist_controls_sortby_releasedate: _,
    wishlist_controls_sortby_dateadded: _,
    wishlist_controls_sortby_reviews: _,
    wishlist_controls_sortby_price: _,
    wishlist_controls_sortby_name: _,
    wishlist_controls_sortby_discount: _,
    wishlist_controls_share_dialog_title: _,
    wishlist_controls_share_revokeall: _,
    wishlist_controls_share_revokeall_success: _,
    wishlist_controls_share_generation_failure: _,
    wishlist_controls_share_description: _,
    wishlist_controls_options_category_view: _,
    wishlist_controls_options_view_expanded: _,
    wishlist_controls_options_view_compact: _,
    wishlist_controls_options_category_platform: _,
    wishlist_controls_options_platform_all: _,
    wishlist_controls_options_platform_mac: _,
    wishlist_controls_options_platform_linux: _,
    wishlist_controls_options_category_type: _,
    wishlist_controls_options_type_game: _,
    wishlist_controls_options_type_application: _,
    wishlist_controls_options_type_dlc: _,
    wishlist_controls_options_type_video: _,
    wishlist_controls_options_category_price: _,
    wishlist_controls_options_category_discount: _,
    wishlist_controls_options_discount_all: _,
    wishlist_controls_options_discount_any: _,
    wishlist_controls_options_discount_or_more: _,
    wishlist_controls_options_price_any: _,
    wishlist_controls_options_price_max_price: _,
    wishlist_controls_options_price_free: _,
    wishlist_controls_options_category_exclude: _,
    wishlist_controls_options_category_related: _,
    genre_early_access: _,
    wishlist_controls_early_access_tooltip: _,
    category_prerelease: _,
    wishlist_controls_options_exclude_vr: _,
    wishlist_controls_demo_available: _,
    wishlist_controls_demo_available_tooltip: _,
    wishlist_controls_options_category_deck: _,
    wishlist_controls_options_deck_verified: _,
    wishlist_controls_options_deck_playable: _,
    wishlist_controls_options_category_tag: _,
    wishlist_controls_tag_description: _,
    wishlist_controls_tags_header: _,
    wishlist_controls_filter_tag_label: _,
    wishlist_controls_options_category_category: _,
    wishlist_controls_categories_header_anonymous: _,
    wishlist_controls_categories_multiselect_label: _,
    wishlist_controls_categories_add: _,
    wishlist_categories_advanced_title: _,
    wishlist_categories_advanced_select: _,
    wishlist_categories_advanced_rename_label: _,
    wishlist_categories_advanced_rename_save: _,
    wishlist_categories_advanced_rename_duplicate: _,
    wishlist_categories_advanced_rename_failed: _,
    wishlist_categories_advanced_no_items: _,
    wishlist_categories_advanced_select_all: _,
    wishlist_categories_advanced_select_none: `無`,
    wishlist_categories_advanced_showing: _,
    wishlist_categories_advanced_failed_items: _,
    wishlist_categories_advanced_failed_items_Plural: _,
    wishlist_categories_advanced_pending: _,
    wishlist_categories_advanced_pending_adds: _,
    wishlist_categories_advanced_pending_removals: _,
    wishlist_categories_advanced_revert: _,
    wishlist_categories_advanced_apply: _,
    wishlist_categories_advanced_addremove_title: _,
    wishlist_displayed_item_count: _,
    wishlist_displayed_item_count_Plural: _,
    wishlist_filter_results: _,
    wishlist_filter_matches_items: _,
    wishlist_filter_matches_items_Plural: _,
    wishlist_filter_matches_category: _,
    wishlist_filter_matches_category_Plural: _,
    wishlist_filter_matches_categories: _,
    wishlist_filter_matches_categories_Plural: _,
    wishlist_filter_matches_tag: _,
    wishlist_filter_matches_tag_Plural: _,
    wishlist_filter_matches_tags: _,
    wishlist_filter_matches_tags_Plural: _,
    wishlist_search: _,
    wishlist_search_all: _,
    wishlist_item_overallreviews: _,
    wishlist_item_languagespecific_reviews: _,
    wishlist_item_releasedate: _,
    wishlist_item_addedon_date: _,
    wishlist_item_remove: _,
    wishlist_item_remove_tooltip: _,
    wishlist_item_unavailable_title: _,
    wishlist_item_unavailable_region: _,
    wishlist_item_unavailable_retired: _,
    mature_content_requires_creditcard: _,
    mature_content_requires_creditcard_gb: _,
    wishlist_item_add_credit_card: _,
    wishlist_your_wishlist_empty: _,
    wishlist_browse_the_store: _,
    wishlist_learn_more_button: _,
    wishlist_sign_in_to_see_your_wishlist: _,
    wishlist_others_wishlist_empty: _,
    wishlist_no_items_matching_filters: _,
    wishlist_x_items_on_wishlist_but_none_match: _,
    wishlist_x_items_on_wishlist_but_none_match_prefs: _,
    wishlist_gamepaddragdrop_reorderaction: _,
    wishlist_gamepaddragdrop_cancelreorder: _,
    wishlist_gamepaddragdrop_commitreorder: _,
    wishlist_gamepad_options: _,
    wishlist_gamepad_options_remove: _,
    wishlist_gamepad_visitstore: _,
    wishlist_errorpage_title: _,
    errorpage_error: _,
    errorpage_unknownerror: _,
    wishlist_error_profilenotfound: _,
    wishlist_error_wishlistunavailable: _,
    wishlist_error_invalidsharetoken: _,
    wishlist_filters_notification: _,
    youraccount_users_account: _,
    youraccount_errorpage_title: _,
    youraccount_account: _,
    m_home: _,
    global_menu_account_details: _,
    global_menu_account_preferences: _,
    global_menu_account_language_preferences: _,
    global_menu_account_notification_settings: _,
    global_menu_account_hardware_used: _,
    global_menu_account_security_devices: _,
    global_menu_account_video_authorized_devices: _,
    global_menu_account_mobile_game_devices: _,
    global_menu_account_gated_access_games: _,
    accountpreferences_familymanagement_header: _,
    CookiePreferences: _,
    global_menu_vr: `VR`,
    global_menu_greatondeck: _,
    global_menu_localplayonframe: _,
    store_tab_foryou_store_home: _,
    browse_categories: _,
    m_search_steam: _,
    playteststatus_error_dataunavailable: _,
    playtestinvites_title: _,
    playtestinvites_accept: _,
    playtestinvites_reject: _,
    playtestinvites_invitedescription_fromapp2: _,
    playtestinvites_invitedescription_fromapp_limitedlaunch: _,
    playtestinvites_invitedescription_fromuser2: _,
    playtestinvites_invitedescription_fromuser_limitedlaunch: _,
    playtestinvites_noinvites: _,
    playtestinvites_welcome: _,
    playtestinvites_welcome_limitedlaunch: _,
    playtestinvites_welcome_notplayable: _,
    playtestinvites_viewlibrary: _,
    playtestinvites_desc_title: _,
    playtestinvites_desc1: _,
    playtestinvites_desc2: _,
    playtestinvites_ignored_title: _,
    playtestinvites_ignored_desc: _,
    playtestinvites_ignored_remove: _,
    playtestinvites_sendinvite_cancel: _,
    playtestinvites_sendinvite_send: _,
    playtestinvites_sendinvite_lastinvite: _,
    playtestinvites_sendinvite_lastinvite_limitedlaunch: _,
    playtestinvites_sendinvite_confirm_desc: _,
    playtestinvites_sendinvite_pending: _,
    playtestinvites_sendinvite_success: _,
    playtestinvites_sendinvite_failure: _,
    playtestinvitehistory_title: _,
    playtestinvitehistory_desc: _,
    playtestinvitehistory_invite_detail: _,
    playteststatus_title: _,
    playteststatus_none: _,
    playteststatus_invites_available: _,
    playteststatus_invite_count: _,
    playteststatus_invite_count_plural: _,
    playteststatus_invite_count_tooltip: _,
    playteststatus_invite_count_tooltip2: _,
    playteststatus_details_moreinfo: _,
    playteststatus_details_moreinfo_storepage: _,
    playteststatus_details_moreinfo_newshub: _,
    playteststatus_details_notplayable: _,
    playteststatus_details_allinvitesused: _,
    playteststatus_invitefriends: _,
    playteststatus_invitefrienddialog_header: _,
    playteststatus_invitefrienddialog_search_placeholder: _,
    playteststatus_invitefrienddialog_loadingerror: _,
    playteststatus_invitefrienddialog_ineligiblefriends: _,
    playteststatus_invitefrienddialog_ineligiblefriends_purchaser: _,
    gatedaccess_limitedlaunch_badge: _,
    gatedaccess_limitedlaunch_invite_count_tooltip: _,
    gatedaccess_limitedlaunch_details_moreinfo: _,
    gatedaccess_limitedlaunch_desc_title: _,
    gatedaccess_limitedlaunch_desc: _,
    sitemap_title: _,
    sitemap_home: _,
    sitemap_section_account: _,
    sitemap_section_account_account_details: _,
    sitemap_section_account_store_preferences: _,
    sitemap_section_account_family_management: _,
    sitemap_section_account_security_and_devices: _,
    sitemap_section_account_language_preferences: _,
    sitemap_section_account_cookes_and_browsing: _,
    sitemap_section_account_notification_settings: _,
    sitemap_section_account_cart: _,
    sitemap_section_account_cart_with_count: _,
    sitemap_section_account_wishlist: _,
    sitemap_section_account_wishlist_with_count: _,
    sitemap_section_account_followed_games: _,
    sitemap_section_account_followed_games_with_count: _,
    sitemap_section_chartsandlists: _,
    sitemap_section_chartsandlists_top_sellers: _,
    sitemap_section_chartsandlists_most_played: _,
    sitemap_section_chartsandlists_new_releases: _,
    sitemap_section_chartsandlists_upcoming_releases: _,
    sitemap_section_chartsandlists_free_to_play: _,
    sitemap_section_chartsandlists_steam_charts: _,
    sitemap_section_chartsandlists_on_sale_now: _,
    sitemap_section_recommendations: _,
    sitemap_section_recommendations_discovery_queue: _,
    sitemap_section_recommendations_new_releases_queue: _,
    sitemap_section_recommendations_community_recommendations: _,
    sitemap_section_recommendations_interactive_recommender: _,
    sitemap_section_recommendations_popular_among_friends: _,
    sitemap_section_recommendations_steam_curators: _,
    sitemap_section_recommendations_dlc_for_you: _,
    sitemap_section_hardware: _,
    sitemap_section_hardware_steam_deck: _,
    sitemap_section_hardware_steam_deck_dock: _,
    sitemap_section_hardware_vr_hardware: _,
    sitemap_section_hardware_vr_games: _,
    sitemap_section_hardware_great_on_deck: _,
    sitemap_section_hardware_controller_friendly: _,
    sitemap_section_waystoplay: _,
    sitemap_section_newsupdates: _,
    sitemap_section_newsupdates_recently_updated: _,
    sitemap_section_newsupdates_your_recently_updated: _,
    sitemap_section_newsupdates_your_upcoming_events: _,
    sitemap_section_newsupdates_featured_news: _,
    sitemap_section_newsupdates_steam_official_news: _,
    sitemap_section_promosandevents: _,
    sitemap_section_promosandevents_special_offers: _,
    sitemap_section_promosandevents_sale_events: _,
    sitemap_section_promosandevents_steam_replay: _,
    sitemap_section_promosandevents_steam_next_fest: _,
    sitemap_section_promosandevents_steam_awards: _,
    sitemap_section_specialsections: _,
    sitemap_pointsshop: _,
    sitemap_giftcards: _,
    sitemap_genres: _,
    sitemap_themes: _,
    Error_RateLimited: _,
    Discussions_ForumName_General: _,
    Discussions_ForumName_ReportedPosts: _,
    Discussions_ForumName_Workshop: _,
    Discussions_ForumName_Trading: _,
    Discussions_ForumName_Events: _,
    ir_name: _,
    ir_header: _,
    ir_body: _,
    ir_playtime_header: _,
    ir_playtime_games: _,
    ir_playtime_topgames: _,
    ir_playtime_recentgames: _,
    ir_playtime_hours: _,
    ir_playtime_hourstotal: _,
    ir_playtime_lastplayed: _,
    ir_playtime_lastplayedmax: _,
    ir_playtime_unignore: _,
    ir_playtime_ignore: _,
    ir_popularity_title: _,
    ir_popularity_popular: _,
    ir_popularity_niche: _,
    ir_recency_title: _,
    ir_recency_older: _,
    ir_recency_newer: _,
    ir_filter_age_all: _,
    ir_filter_age_60: _,
    ir_filter_age_36: _,
    ir_filter_age_24: _,
    ir_filter_age_12: _,
    ir_filter_age_6: _,
    ir_recommendations_header: _,
    ir_release_date: _,
    ir_on_wishlist: _,
    ir_add_to_cart: _,
    ir_add_to_wishlist: _,
    ir_free_to_play: _,
    ir_tag_placeholder: _,
    ir_tag_filter: _,
    ir_tag_exclude: _,
    ir_no_wishlisted: _,
    ir_discounted_only: _,
    PersonalCalendar_LastMonthGames: _,
    PersonalCalendar_LastWeekGames: _,
    PersonalCalendar_Upcoming: _,
    PersonalCalendar_Title: _,
    PersonalCalendar_Description: _,
    PersonalCalendar_TagSelector: _,
    PersonalCalendar_TagSelector_Placeholder: _,
    PersonalCalendar_HideOwned: _,
    PersonalCalendar_HideEATooltip: _,
    PersonalCalendar_HideEarlyAccess: _,
    PersonalCalendar_ShowOnlyWishlisted: _,
    PersonalCalendar_ResultCountSelector: _,
    PersonalCalendar_CompactMode: _,
    PersonalCalendar_AccountPlaceholder: _,
    PersonalCalendar_Account: _,
    PersonalCalendar_ShowMore: _,
    PersonalCalendar_LoginPrompt: _,
    PersonalCalendar_ShowAll: _,
    PersonalCalendar_SteamLabs: _,
    PersonalCalendar_Wishlisted: _,
    PersonalCalendar_WishlistShow: _,
    PersonalCalendar_WishlistHide: _,
    PersonalCalendar_WishlistOnly: _,
    PersonalCalendar_IgnoringWishlists: _,
    PersonalCalendar_Error_Backend: _,
    BundleList_Title: _,
    BundleList_Title_Fallback: _,
    BundleList_Page: _,
    Verification_DeckOnly: _,
    Verification_DeckOnly_Desc: _,
    FatalErrorPage_Title: _,
    FatalErrorPage_Header: _,
    FatalErrorPage_Message: _,
    pressoutlets_error_slots_gt_zero: _,
    pressoutlets_error_domain_used: _,
    pressoutlets_error_adding_outlet: _,
    pressoutlets_error_domain_empty: _,
    pressoutlets_error_invalid_domain: _,
    pressoutlets_error_already_owned: _,
    pressoutlets_error_generic_add_error: _,
    pressoutlets_email_domain_label: _,
    pressoutlets_slots_label: _,
    pressoutlets_button_add: _,
    pressoutlets_label_add_outlet: _,
    pressoutlets_outlet_header: _,
    pressoutlets_show_history: _,
    pressoutlets_history_title: _,
    pressoutlets_action_granted: _,
    pressoutlets_action_removed: _,
    pressoutlets_action_created: _,
    pressoutlets_action_updated: _,
    pressoutlets_action_updated_domain_changed: _,
    pressoutlets_action_updated_slots_changed: _,
    pressoutlets_action_deleted: _,
    pressoutlets_action_undeleted: _,
    pressoutlets_action_enterstaging: _,
    pressoutlets_action_exitstaging: _,
    pressoutlets_action_stagedadd: _,
    pressoutlets_action_stageddelete: _,
    pressoutlets_action_by_support: _,
    pressoutlets_header_grantee: _,
    pressoutlets_header_granted_at: _,
    pressoutlets_header_is_group_admin: _,
    pressoutlets_steamid_to_add: _,
    pressoutlets_button_ok: _,
    pressoutlets_button_cancel: _,
    pressoutlets_is_group_admin: `是`,
    pressoutlets_is_not_group_admin: `否`,
    pressoutlets_filter_all: _,
    pressoutlets_filter_active: _,
    pressoutlets_filter_deleted: _,
    pressoutlets_filter_empty: _,
    pressoutlets_filter_noadmins: _,
    pressoutlets_outlet_header_prefix: _,
    pressoutlets_friendcode: _,
    pressoutlets_resign_your_key: _,
    pressoutlets_resign_your_key_title: _,
    pressoutlets_history_header: _,
    pressoutlets_button_add_member: _,
    pressoutlets_button_show_history: _,
    pressoutlets_header_account: _,
    trailerassets_invalidfile: _,
    trailerassets_trailer: _,
    trailerassets_microtrailer: _,
    account_notification_settings_error_saving: _,
    account_notification_settings_error_loading: _,
    account_notification_settings_error_invalidoptouttoken: _,
    account_notification_settings_feed_disabled: _,
    account_notification_settings_wishlist_categories_persona: _,
    framerate_title: _,
    framerate_subheader: _,
    framerate_cpu: `CPU`,
    framerate_ram: _,
    framerate_gpu: `GPU`,
    framerate_saved_hardware: _,
    framerate_saved_hardware_none: _,
    framerate_saved_hardware_select: _,
    framerate_saved_hardware_option_none: _,
    framerate_saved_add: _,
    framerate_saved_add_btn: _,
    framerate_saved_add_not_in_client_btn: _,
    framerate_opt_in_data_collection_desc: _,
    framerate_opt_in_link: _,
    framerate_fps: `FPS`,
    framerate_game_name: _,
    framerate_select_cpu: _,
    framerate_select_gpu: _,
    framerate_training_game: _,
    framerate_training_cpu: _,
    framerate_training_gpu: _,
    generic_unknown: _,
    giftcards_banner_text: _,
    empty_no_trailing_comma: ``,
  };
export {
  _ as BundleList_AllInLibrary,
  _ as BundleList_AllInLibrarySubtitle,
  _ as BundleList_CompleteTheSet,
  _ as BundleList_CompleteTheSetSubtitle,
  _ as BundleList_MustPurchaseAsSet,
  _ as BundleList_MustPurchaseAsSetSubtitle,
  _ as BundleList_Page,
  _ as BundleList_SortBy,
  _ as BundleList_SortBy_Discount,
  _ as BundleList_SortBy_Name,
  _ as BundleList_SortBy_Popular,
  _ as BundleList_SortBy_Price,
  _ as BundleList_SortBy_Recommend,
  _ as BundleList_SubTitle,
  _ as BundleList_Title,
  _ as BundleList_Title_Fallback,
  _ as CookiePreferences,
  _ as Discussions_ForumName_Events,
  _ as Discussions_ForumName_General,
  _ as Discussions_ForumName_ReportedPosts,
  _ as Discussions_ForumName_Trading,
  _ as Discussions_ForumName_Workshop,
  _ as Error_RateLimited,
  _ as FatalErrorPage_Header,
  _ as FatalErrorPage_Message,
  _ as FatalErrorPage_Title,
  _ as PersonalCalendar_Account,
  _ as PersonalCalendar_AccountPlaceholder,
  _ as PersonalCalendar_CompactMode,
  _ as PersonalCalendar_Description,
  _ as PersonalCalendar_Error_Backend,
  _ as PersonalCalendar_HideEATooltip,
  _ as PersonalCalendar_HideEarlyAccess,
  _ as PersonalCalendar_HideOwned,
  _ as PersonalCalendar_IgnoringWishlists,
  _ as PersonalCalendar_LastMonthGames,
  _ as PersonalCalendar_LastWeekGames,
  _ as PersonalCalendar_LoginPrompt,
  _ as PersonalCalendar_ResultCountSelector,
  _ as PersonalCalendar_ShowAll,
  _ as PersonalCalendar_ShowMore,
  _ as PersonalCalendar_ShowOnlyWishlisted,
  _ as PersonalCalendar_SteamLabs,
  _ as PersonalCalendar_TagSelector,
  _ as PersonalCalendar_TagSelector_Placeholder,
  _ as PersonalCalendar_Title,
  _ as PersonalCalendar_Upcoming,
  _ as PersonalCalendar_WishlistHide,
  _ as PersonalCalendar_WishlistOnly,
  _ as PersonalCalendar_WishlistShow,
  _ as PersonalCalendar_Wishlisted,
  _ as Verification_DeckOnly,
  _ as Verification_DeckOnly_Desc,
  _ as account_notification_settings_error_invalidoptouttoken,
  _ as account_notification_settings_error_loading,
  _ as account_notification_settings_error_saving,
  _ as account_notification_settings_feed_disabled,
  _ as account_notification_settings_wishlist_categories_persona,
  _ as accountpreferences_familymanagement_header,
  _ as browse_categories,
  _ as cart_count,
  _ as cart_view_cart,
  _ as category_prerelease,
  _ as default,
  _ as empty_no_trailing_comma,
  _ as errorpage_error,
  _ as errorpage_unknownerror,
  _ as footer_about_valve,
  _ as footer_accessibility,
  _ as footer_business_solutions,
  _ as footer_cookies,
  _ as footer_jobs,
  _ as footer_legal,
  _ as footer_legal_notice,
  _ as footer_nav_help_support,
  _ as footer_privacy_policy,
  _ as footer_recycling,
  _ as footer_refunds,
  _ as footer_source_engine,
  _ as footer_ssa,
  _ as footer_steam_distribution,
  _ as footer_steamworks,
  _ as footer_vat_included,
  _ as footer_walletcode,
  _ as framerate_cpu,
  _ as framerate_fps,
  _ as framerate_game_name,
  _ as framerate_gpu,
  _ as framerate_opt_in_data_collection_desc,
  _ as framerate_opt_in_link,
  _ as framerate_ram,
  _ as framerate_saved_add,
  _ as framerate_saved_add_btn,
  _ as framerate_saved_add_not_in_client_btn,
  _ as framerate_saved_hardware,
  _ as framerate_saved_hardware_none,
  _ as framerate_saved_hardware_option_none,
  _ as framerate_saved_hardware_select,
  _ as framerate_select_cpu,
  _ as framerate_select_gpu,
  _ as framerate_subheader,
  _ as framerate_title,
  _ as framerate_training_cpu,
  _ as framerate_training_game,
  _ as framerate_training_gpu,
  _ as gatedaccess_limitedlaunch_badge,
  _ as gatedaccess_limitedlaunch_desc,
  _ as gatedaccess_limitedlaunch_desc_title,
  _ as gatedaccess_limitedlaunch_details_moreinfo,
  _ as gatedaccess_limitedlaunch_invite_count_tooltip,
  _ as generic_unknown,
  _ as genre_early_access,
  _ as giftcards_banner_text,
  _ as global_menu_account_details,
  _ as global_menu_account_gated_access_games,
  _ as global_menu_account_hardware_used,
  _ as global_menu_account_language_preferences,
  _ as global_menu_account_mobile_game_devices,
  _ as global_menu_account_notification_settings,
  _ as global_menu_account_preferences,
  _ as global_menu_account_security_devices,
  _ as global_menu_account_video_authorized_devices,
  _ as global_menu_greatondeck,
  _ as global_menu_localplayonframe,
  _ as global_menu_vr,
  _ as ir_add_to_cart,
  _ as ir_add_to_wishlist,
  _ as ir_body,
  _ as ir_discounted_only,
  _ as ir_filter_age_12,
  _ as ir_filter_age_24,
  _ as ir_filter_age_36,
  _ as ir_filter_age_6,
  _ as ir_filter_age_60,
  _ as ir_filter_age_all,
  _ as ir_free_to_play,
  _ as ir_header,
  _ as ir_name,
  _ as ir_no_wishlisted,
  _ as ir_on_wishlist,
  _ as ir_playtime_games,
  _ as ir_playtime_header,
  _ as ir_playtime_hours,
  _ as ir_playtime_hourstotal,
  _ as ir_playtime_ignore,
  _ as ir_playtime_lastplayed,
  _ as ir_playtime_lastplayedmax,
  _ as ir_playtime_recentgames,
  _ as ir_playtime_topgames,
  _ as ir_playtime_unignore,
  _ as ir_popularity_niche,
  _ as ir_popularity_popular,
  _ as ir_popularity_title,
  _ as ir_recency_newer,
  _ as ir_recency_older,
  _ as ir_recency_title,
  _ as ir_recommendations_header,
  _ as ir_release_date,
  _ as ir_tag_exclude,
  _ as ir_tag_filter,
  _ as ir_tag_placeholder,
  _ as m_home,
  _ as m_search_steam,
  _ as mature_content_requires_creditcard,
  _ as mature_content_requires_creditcard_gb,
  _ as playtestinvitehistory_desc,
  _ as playtestinvitehistory_invite_detail,
  _ as playtestinvitehistory_title,
  _ as playtestinvites_accept,
  _ as playtestinvites_desc1,
  _ as playtestinvites_desc2,
  _ as playtestinvites_desc_title,
  _ as playtestinvites_ignored_desc,
  _ as playtestinvites_ignored_remove,
  _ as playtestinvites_ignored_title,
  _ as playtestinvites_invitedescription_fromapp2,
  _ as playtestinvites_invitedescription_fromapp_limitedlaunch,
  _ as playtestinvites_invitedescription_fromuser2,
  _ as playtestinvites_invitedescription_fromuser_limitedlaunch,
  _ as playtestinvites_noinvites,
  _ as playtestinvites_reject,
  _ as playtestinvites_sendinvite_cancel,
  _ as playtestinvites_sendinvite_confirm_desc,
  _ as playtestinvites_sendinvite_failure,
  _ as playtestinvites_sendinvite_lastinvite,
  _ as playtestinvites_sendinvite_lastinvite_limitedlaunch,
  _ as playtestinvites_sendinvite_pending,
  _ as playtestinvites_sendinvite_send,
  _ as playtestinvites_sendinvite_success,
  _ as playtestinvites_title,
  _ as playtestinvites_viewlibrary,
  _ as playtestinvites_welcome,
  _ as playtestinvites_welcome_limitedlaunch,
  _ as playtestinvites_welcome_notplayable,
  _ as playteststatus_details_allinvitesused,
  _ as playteststatus_details_moreinfo,
  _ as playteststatus_details_moreinfo_newshub,
  _ as playteststatus_details_moreinfo_storepage,
  _ as playteststatus_details_notplayable,
  _ as playteststatus_error_dataunavailable,
  _ as playteststatus_invite_count,
  _ as playteststatus_invite_count_plural,
  _ as playteststatus_invite_count_tooltip,
  _ as playteststatus_invite_count_tooltip2,
  _ as playteststatus_invitefrienddialog_header,
  _ as playteststatus_invitefrienddialog_ineligiblefriends,
  _ as playteststatus_invitefrienddialog_ineligiblefriends_purchaser,
  _ as playteststatus_invitefrienddialog_loadingerror,
  _ as playteststatus_invitefrienddialog_search_placeholder,
  _ as playteststatus_invitefriends,
  _ as playteststatus_invites_available,
  _ as playteststatus_none,
  _ as playteststatus_title,
  _ as pressoutlets_action_by_support,
  _ as pressoutlets_action_created,
  _ as pressoutlets_action_deleted,
  _ as pressoutlets_action_enterstaging,
  _ as pressoutlets_action_exitstaging,
  _ as pressoutlets_action_granted,
  _ as pressoutlets_action_removed,
  _ as pressoutlets_action_stagedadd,
  _ as pressoutlets_action_stageddelete,
  _ as pressoutlets_action_undeleted,
  _ as pressoutlets_action_updated,
  _ as pressoutlets_action_updated_domain_changed,
  _ as pressoutlets_action_updated_slots_changed,
  _ as pressoutlets_button_add,
  _ as pressoutlets_button_add_member,
  _ as pressoutlets_button_cancel,
  _ as pressoutlets_button_ok,
  _ as pressoutlets_button_show_history,
  _ as pressoutlets_email_domain_label,
  _ as pressoutlets_error_adding_outlet,
  _ as pressoutlets_error_already_owned,
  _ as pressoutlets_error_domain_empty,
  _ as pressoutlets_error_domain_used,
  _ as pressoutlets_error_generic_add_error,
  _ as pressoutlets_error_invalid_domain,
  _ as pressoutlets_error_slots_gt_zero,
  _ as pressoutlets_filter_active,
  _ as pressoutlets_filter_all,
  _ as pressoutlets_filter_deleted,
  _ as pressoutlets_filter_empty,
  _ as pressoutlets_filter_noadmins,
  _ as pressoutlets_friendcode,
  _ as pressoutlets_header_account,
  _ as pressoutlets_header_granted_at,
  _ as pressoutlets_header_grantee,
  _ as pressoutlets_header_is_group_admin,
  _ as pressoutlets_history_header,
  _ as pressoutlets_history_title,
  _ as pressoutlets_is_group_admin,
  _ as pressoutlets_is_not_group_admin,
  _ as pressoutlets_label_add_outlet,
  _ as pressoutlets_outlet_header,
  _ as pressoutlets_outlet_header_prefix,
  _ as pressoutlets_resign_your_key,
  _ as pressoutlets_resign_your_key_title,
  _ as pressoutlets_show_history,
  _ as pressoutlets_slots_label,
  _ as pressoutlets_steamid_to_add,
  _ as sitemap_genres,
  _ as sitemap_giftcards,
  _ as sitemap_home,
  _ as sitemap_pointsshop,
  _ as sitemap_section_account,
  _ as sitemap_section_account_account_details,
  _ as sitemap_section_account_cart,
  _ as sitemap_section_account_cart_with_count,
  _ as sitemap_section_account_cookes_and_browsing,
  _ as sitemap_section_account_family_management,
  _ as sitemap_section_account_followed_games,
  _ as sitemap_section_account_followed_games_with_count,
  _ as sitemap_section_account_language_preferences,
  _ as sitemap_section_account_notification_settings,
  _ as sitemap_section_account_security_and_devices,
  _ as sitemap_section_account_store_preferences,
  _ as sitemap_section_account_wishlist,
  _ as sitemap_section_account_wishlist_with_count,
  _ as sitemap_section_chartsandlists,
  _ as sitemap_section_chartsandlists_free_to_play,
  _ as sitemap_section_chartsandlists_most_played,
  _ as sitemap_section_chartsandlists_new_releases,
  _ as sitemap_section_chartsandlists_on_sale_now,
  _ as sitemap_section_chartsandlists_steam_charts,
  _ as sitemap_section_chartsandlists_top_sellers,
  _ as sitemap_section_chartsandlists_upcoming_releases,
  _ as sitemap_section_hardware,
  _ as sitemap_section_hardware_controller_friendly,
  _ as sitemap_section_hardware_great_on_deck,
  _ as sitemap_section_hardware_steam_deck,
  _ as sitemap_section_hardware_steam_deck_dock,
  _ as sitemap_section_hardware_vr_games,
  _ as sitemap_section_hardware_vr_hardware,
  _ as sitemap_section_newsupdates,
  _ as sitemap_section_newsupdates_featured_news,
  _ as sitemap_section_newsupdates_recently_updated,
  _ as sitemap_section_newsupdates_steam_official_news,
  _ as sitemap_section_newsupdates_your_recently_updated,
  _ as sitemap_section_newsupdates_your_upcoming_events,
  _ as sitemap_section_promosandevents,
  _ as sitemap_section_promosandevents_sale_events,
  _ as sitemap_section_promosandevents_special_offers,
  _ as sitemap_section_promosandevents_steam_awards,
  _ as sitemap_section_promosandevents_steam_next_fest,
  _ as sitemap_section_promosandevents_steam_replay,
  _ as sitemap_section_recommendations,
  _ as sitemap_section_recommendations_community_recommendations,
  _ as sitemap_section_recommendations_discovery_queue,
  _ as sitemap_section_recommendations_dlc_for_you,
  _ as sitemap_section_recommendations_interactive_recommender,
  _ as sitemap_section_recommendations_new_releases_queue,
  _ as sitemap_section_recommendations_popular_among_friends,
  _ as sitemap_section_recommendations_steam_curators,
  _ as sitemap_section_specialsections,
  _ as sitemap_section_waystoplay,
  _ as sitemap_themes,
  _ as sitemap_title,
  _ as store_tab_foryou_store_home,
  _ as trailerassets_invalidfile,
  _ as trailerassets_microtrailer,
  _ as trailerassets_trailer,
  _ as wishlist_browse_the_store,
  _ as wishlist_categories_advanced_addremove_title,
  _ as wishlist_categories_advanced_apply,
  _ as wishlist_categories_advanced_failed_items,
  _ as wishlist_categories_advanced_failed_items_Plural,
  _ as wishlist_categories_advanced_no_items,
  _ as wishlist_categories_advanced_pending,
  _ as wishlist_categories_advanced_pending_adds,
  _ as wishlist_categories_advanced_pending_removals,
  _ as wishlist_categories_advanced_rename_duplicate,
  _ as wishlist_categories_advanced_rename_failed,
  _ as wishlist_categories_advanced_rename_label,
  _ as wishlist_categories_advanced_rename_save,
  _ as wishlist_categories_advanced_revert,
  _ as wishlist_categories_advanced_select,
  _ as wishlist_categories_advanced_select_all,
  _ as wishlist_categories_advanced_select_none,
  _ as wishlist_categories_advanced_showing,
  _ as wishlist_categories_advanced_title,
  _ as wishlist_controls_categories_add,
  _ as wishlist_controls_categories_header_anonymous,
  _ as wishlist_controls_categories_multiselect_label,
  _ as wishlist_controls_demo_available,
  _ as wishlist_controls_demo_available_tooltip,
  _ as wishlist_controls_early_access_tooltip,
  _ as wishlist_controls_filter_tag_label,
  _ as wishlist_controls_options_category_category,
  _ as wishlist_controls_options_category_deck,
  _ as wishlist_controls_options_category_discount,
  _ as wishlist_controls_options_category_exclude,
  _ as wishlist_controls_options_category_platform,
  _ as wishlist_controls_options_category_price,
  _ as wishlist_controls_options_category_related,
  _ as wishlist_controls_options_category_tag,
  _ as wishlist_controls_options_category_type,
  _ as wishlist_controls_options_category_view,
  _ as wishlist_controls_options_deck_playable,
  _ as wishlist_controls_options_deck_verified,
  _ as wishlist_controls_options_discount_all,
  _ as wishlist_controls_options_discount_any,
  _ as wishlist_controls_options_discount_or_more,
  _ as wishlist_controls_options_exclude_vr,
  _ as wishlist_controls_options_platform_all,
  _ as wishlist_controls_options_platform_linux,
  _ as wishlist_controls_options_platform_mac,
  _ as wishlist_controls_options_price_any,
  _ as wishlist_controls_options_price_free,
  _ as wishlist_controls_options_price_max_price,
  _ as wishlist_controls_options_type_application,
  _ as wishlist_controls_options_type_dlc,
  _ as wishlist_controls_options_type_game,
  _ as wishlist_controls_options_type_video,
  _ as wishlist_controls_options_view_compact,
  _ as wishlist_controls_options_view_expanded,
  _ as wishlist_controls_share_description,
  _ as wishlist_controls_share_dialog_title,
  _ as wishlist_controls_share_generation_failure,
  _ as wishlist_controls_share_revokeall,
  _ as wishlist_controls_share_revokeall_success,
  _ as wishlist_controls_sortby_dateadded,
  _ as wishlist_controls_sortby_discount,
  _ as wishlist_controls_sortby_name,
  _ as wishlist_controls_sortby_order,
  _ as wishlist_controls_sortby_price,
  _ as wishlist_controls_sortby_releasedate,
  _ as wishlist_controls_sortby_reviews,
  _ as wishlist_controls_sortby_their_order,
  _ as wishlist_controls_sortby_topsellers,
  _ as wishlist_controls_tag_description,
  _ as wishlist_controls_tags_header,
  _ as wishlist_count,
  _ as wishlist_displayed_item_count,
  _ as wishlist_displayed_item_count_Plural,
  _ as wishlist_error_invalidsharetoken,
  _ as wishlist_error_profilenotfound,
  _ as wishlist_error_wishlistunavailable,
  _ as wishlist_errorpage_title,
  _ as wishlist_filter_matches_categories,
  _ as wishlist_filter_matches_categories_Plural,
  _ as wishlist_filter_matches_category,
  _ as wishlist_filter_matches_category_Plural,
  _ as wishlist_filter_matches_items,
  _ as wishlist_filter_matches_items_Plural,
  _ as wishlist_filter_matches_tag,
  _ as wishlist_filter_matches_tag_Plural,
  _ as wishlist_filter_matches_tags,
  _ as wishlist_filter_matches_tags_Plural,
  _ as wishlist_filter_results,
  _ as wishlist_filters_notification,
  _ as wishlist_gamepad_options,
  _ as wishlist_gamepad_options_remove,
  _ as wishlist_gamepad_visitstore,
  _ as wishlist_gamepaddragdrop_cancelreorder,
  _ as wishlist_gamepaddragdrop_commitreorder,
  _ as wishlist_gamepaddragdrop_reorderaction,
  _ as wishlist_header,
  _ as wishlist_item_add_credit_card,
  _ as wishlist_item_addedon_date,
  _ as wishlist_item_languagespecific_reviews,
  _ as wishlist_item_overallreviews,
  _ as wishlist_item_releasedate,
  _ as wishlist_item_remove,
  _ as wishlist_item_remove_tooltip,
  _ as wishlist_item_unavailable_region,
  _ as wishlist_item_unavailable_retired,
  _ as wishlist_item_unavailable_title,
  _ as wishlist_learn_more_button,
  _ as wishlist_no_items_matching_filters,
  _ as wishlist_options_button,
  _ as wishlist_others_wishlist_empty,
  _ as wishlist_search,
  _ as wishlist_search_all,
  _ as wishlist_share_tooltip,
  _ as wishlist_sign_in_to_see_your_wishlist,
  _ as wishlist_sortby_button,
  _ as wishlist_title,
  _ as wishlist_x_items_on_wishlist_but_none_match,
  _ as wishlist_x_items_on_wishlist_but_none_match_prefs,
  _ as wishlist_your_wishlist_empty,
  _ as youraccount_account,
  _ as youraccount_errorpage_title,
  _ as youraccount_users_account,
};
