var _ = `Kaikki myyntipaketit, jotka sisältävät seuraavan tuotteen:`,
  _ = `Lajitteluperuste:`,
  _ = `Suosio`,
  _ = `Hinta`,
  _ = `Myyntipaketin alennus`,
  _ = `Nimi`,
  _ = `Suositus`,
  _ = `Kokonaiset myyntipakettisi`,
  _ = `Kaikki näiden myyntipakettien sisältö löytyy kirjastostasi`,
  _ = `Täydennä sarja -myyntipaketit`,
  _ = `Täydennä sarja ostamalla kirjastostasi puuttuvat pelit`,
  _ = `Ostettava yhdessä -myyntipaketit`,
  _ = `Sisältää kaikki tuotteet yhdessä myyntipaketissa. Tuotteita ei voi ostaa erikseen.`,
  _ = `© %1$s Valve Corporation. Kaikki oikeudet pidätetään. Kaikki tavaramerkit ovat omistajiensa omaisuutta Yhdysvalloissa ja kaikkialla maailmassa.`,
  _ = `Kaikki hinnat sisältävät asiaankuuluvan arvonlisäveron.`,
  _ = `Tietosuojakäytäntö`,
  _ = `Juridiset tiedot`,
  _ = `Helppokäyttötoiminnot`,
  _ = `Steam-tilaussopimus`,
  _ = `Hyvitykset`,
  _ = `Evästeet`,
  _ = `Tietoja Valvesta`,
  _ = `Liiketoimintaratkaisut`,
  _ = `Kierrätys`,
  _ = `Steamworks`,
  _ = `Source-pelimoottori`,
  _ = `Työpaikat`,
  _ = `Lahjakortit`,
  _ = `Steam-jakelu`,
  _ = `Tuki`,
  _ = `Käyttäjän %1$s toivelista`,
  _ = `Käyttäjän %1$s toivelista`,
  _ = `Ostoskori (%1$s)`,
  _ = `Näytä ostoskori`,
  _ = `Toivelista (%1$s)`,
  _ = `Vaihtoehdot`,
  _ = `Lajitteluperuste: %1$s`,
  _ = `Luo jaettava linkki`,
  _ = `Oma sijoitus`,
  _ = `Sijoituksen mukaan`,
  _ = `Myydyimmät`,
  _ = `Julkaisupäivä`,
  _ = `Lisäyspäivä`,
  _ = `Arvostelupisteet`,
  _ = `Hinta`,
  _ = `Nimi`,
  _ = `Alennus`,
  _ = `Jaettava linkki`,
  _ = `Poista kaikki linkit käytöstä`,
  _ = `Linkit on poistettu käytöstä.`,
  _ = `Jaettavan linkin luominen epäonnistui (virhe %1$s).`,
  _ = `Kuka tahansa, jolla on tämä linkki, voi tarkastella toivelistaasi nykyisillä suodattimilla profiilisi näkyvyysasetuksista riippumatta. Linkin haltijat eivät voi muuttaa suodattimia.`,
  _ = `Näytä`,
  _ = `Laajennettu`,
  _ = `Tiivistetty`,
  _ = `Alusta`,
  _ = `Mikä tahansa`,
  _ = `macOS`,
  _ = `SteamOS + Linux`,
  _ = `Tyyppi`,
  _ = `Pelit`,
  _ = `Ohjelmisto`,
  _ = `Lisämateriaali`,
  _ = `Videot`,
  _ = `Hinta`,
  _ = `Alennus`,
  _ = `Kaikki listan tuotteet`,
  _ = `Kaikki alennetut`,
  _ = `%1$s % tai enemmän`,
  _ = `Ei hintarajoitusta`,
  _ = `Alle %1$s`,
  _ = `Ilmainen`,
  _ = `Sulje pois`,
  _ = `Aiheeseen liittyvät tuotteet`,
  _ = `Early Access`,
  _ = `Peli on tällä hetkellä Early Access -vaiheessa`,
  _ = `Ennakkojulkaisut`,
  _ = `Vain VR`,
  _ = `Demo saatavilla`,
  _ = `Suodata toivelistasi tuotteet, joilla on demo.`,
  _ = `Steam Deck -yhteensopivuus`,
  _ = `Vahvistettu`,
  _ = `Pelattavissa`,
  _ = `Tunniste`,
  _ = `Suodata tällä tunnisteella`,
  _ = `Käyttäjän tunnisteet:`,
  _ = `%1$s: %2$s`,
  _ = `Kategoria`,
  _ = `Kategoriat:`,
  _ = `<1>Kategoriat:</1> <2>%1$s</2>`,
  _ = `Lisää kategoria`,
  _ = `Edistynyt luokkien hallinta`,
  _ = `VALITSE MUOKATTAVA LUOKKA`,
  _ = `LUOKAN NIMI`,
  _ = `Nimeä uudelleen`,
  _ = `Sinulla on jo samanniminen luokka`,
  _ = `Luokan uudelleennimeämisessä tapahtui virhe (koodi: %1$s)`,
  _ = `Hakuehdot täyttäviä toivelistakohteita ei löytynyt.`,
  _ = `Kaikki`,
  _ = `Ei valintaa`,
  _ = `Näytetään ensimmäiset %1$s %2$s tuotteesta. Käytä hakua rajataksesi listaa.`,
  _ = `%1$s kohdetta ei voitu päivittää`,
  _ = `%1$s kohdetta ei voitu päivittää`,
  _ = `Odottaa`,
  _ = `Lisätään %1$s`,
  _ = `Poistetaan %1$s`,
  _ = `Palauta`,
  _ = `Vahvista muutokset`,
  _ = `LISÄÄ TAI POISTA LUOKKA`,
  _ = `%1$s TUOTE`,
  _ = `%1$s TUOTETTA`,
  _ = `Hakutulokset:`,
  _ = `%1$s tuote, jonka nimessä esiintyy %2$s.`,
  _ = `%1$s tuotetta, joiden nimissä esiintyy %2$s.`,
  _ = `%1$s tuote, jonka kategoria on %2$s.`,
  _ = `%1$s tuotetta, joiden kategoria on %2$s.`,
  _ = `%1$s tuote, jonka kategorioissa esiintyy %2$s.`,
  _ = `%1$s tuotetta, joiden kategorioissa esiintyy %2$s.`,
  _ = `%1$s tuote, jonka tunniste on %2$s.`,
  _ = `%1$s tuotetta, joiden tunniste on %2$s.`,
  _ = `%1$s tuote, joiden tunnisteissa esiintyy %2$s.`,
  _ = `%1$s tuotetta, joiden tunnisteissa esiintyy %2$s.`,
  _ = `Hae nimellä tai tunnisteella`,
  _ = `Hae nimellä, tunnisteella tai kategorialla`,
  _ = `Kaikki arvostelut:`,
  _ = `Kielen %1$s arvostelut:`,
  _ = `Julkaisupäivä:`,
  _ = `Lisätty %1$s`,
  _ = `poista`,
  _ = `Poista tämä tuote toivelistaltasi`,
  _ = `(ei saatavilla)`,
  _ = `Tuote ei ole saatavilla alueellasi.`,
  _ = `Tuote ei ole enää saatavilla.`,
  _ = `Aikuisille suunnattu sisältö ei ole sallittua maassasi alle 18-vuotiaille käyttäjille. Ennen sisällön näyttämistä Valven täytyy varmistaa, että olet vähintään 18-vuotias.`,
  _ = `Yhdistyneen kuningaskunnan verkkoturvallisuuslain nojalla Valven on varmistettava, että olet vähintään 18-vuotias ennen kuin voit käyttää aikuisille suunnattua seksuaalista sisältöä.`,
  _ = `Lisää luottokortti`,
  _ = `Toivelistasi on tyhjä.`,
  _ = `Selaa kauppaa ja lisää tuotteita toivelistalle Lisää toivelistalle -painikkeella.`,
  _ = `Lue lisätietoja Steamin toivelistoista`,
  _ = `Kirjaudu sisään nähdäksesi toivelistasi`,
  _ = `Toivelista on tyhjä.`,
  _ = `Ei hakua vastaavia tuloksia.`,
  _ = `Toivelistalla on %1$s tuotetta, mutta mikään niistä ei vastaa toivelistan suodattimia tai kaupan asetuksia.`,
  _ = `Toivelistalla on %1$s tuotetta, mutta mikään niistä ei vastaa toivelistan suodattimia tai <1>kaupan asetuksia</1>.`,
  _ = `Järjestä uudelleen`,
  _ = `Peru uudelleenjärjestys`,
  _ = `Sijoita tähän`,
  _ = `Asetukset`,
  _ = `Poista`,
  _ = `Käy kauppasivulla`,
  _ = `Toivelista – virhe`,
  _ = `Virhe`,
  _ = `Tuntematon virhe`,
  _ = `Profiilia ei löytynyt`,
  _ = `Käyttäjän toivelistan lataus epäonnistui.`,
  _ = `Tämä toivelistan jakamislinkki on virheellinen tai vanhentunut.`,
  _ = `Toivelistailmoitusten pelit`,
  _ = `Käyttäjän %1$s tili`,
  _ = `Tili – virhe`,
  _ = `Tili`,
  _ = `Aloitussivu`,
  _ = `Tilitiedot`,
  _ = `Kauppa-asetukset`,
  _ = `Kieliasetukset`,
  _ = `Ilmoitusasetukset`,
  _ = `Laitteet`,
  _ = `Turvallisuus ja laitteet`,
  _ = `Valtuutetut laitteet (video)`,
  _ = `Mobiilipelilaitteet`,
  _ = `Pelitestit`,
  _ = `Perheen hallinta`,
  _ = `Tiedot ja selaus`,
  _ = `VR`,
  _ = `Toimii hyvin Deckillä`,
  _ = `Pelaa paikallisesti Steam Framella`,
  _ = `Kaupan etusivu`,
  _ = `Kategoriat`,
  _ = `Hae Steamistä`,
  _ = `Rajoitetun käyttöoikeuden tietojen lataaminen epäonnistui.`,
  _ = `Steam Playtest -kutsut`,
  _ = `Hyväksy kutsu`,
  _ = `Hylkää kutsu`,
  _ = `Sinut on kutsuttu Steam Playtestiin!`,
  _ = `Sinut on kutsuttu rajoitettuun julkaisuun!`,
  _ = `%1$s kutsui sinut Steam Playtestiin!`,
  _ = `%1$s kutsui sinut rajoitettuun julkaisuun!`,
  _ = `Sinulla ei ole odottavia kutsuja Steam Playtestiin tai rajoitettuun julkaisuun.`,
  _ = `Tervetuloa Playtestiin! Pelin %1$s voi nyt asentaa Steam-kirjastosta.`,
  _ = `Tervetuloa rajoitettuun julkaisuun! %1$s on nyt asennettavissa kirjastostasi.`,
  _ = `Tervetuloa Playtestiin! %1$s ei ole tällä hetkellä aktiivinen. Seuraa kehittäjän tulevia julkaisusuunnitelmia.`,
  _ = `Näytä kirjasto`,
  _ = `Mikä on Steam Playtest?`,
  _ = `Steam Playtestiä käytetään vielä työn alla olevien pelien testaamiseen. Peli lisätään automaattisesti Steam-kirjastoosi, jos hyväksyt kutsun tai kehittäjä antaa sinulle oikeuden peliin.`,
  _ = `Saat pelin kehittäjältä lisätietoa kustakin pelitestistä. Steam Playtestiin osallistuminen ei takaa täysversion käyttöoikeutta pelin julkaisemisen jälkeen.`,
  _ = `Ohitetut Steam Playtest -kutsut`,
  _ = `Olet hylännyt kutsut seuraavien pelien Steam Playtestiin tai rajoitettuun julkaisuun. Et saa muita kutsuja ennen kuin poistat pelit tästä listasta.`,
  _ = `Poista`,
  _ = `Peru`,
  _ = `Lähetä`,
  _ = `Tämä on viimeinen saatavilla oleva kutsu tähän Playtestiin.`,
  _ = `Tämä on viimeinen saatavilla oleva kutsu tähän rajoitettuun julkaisuun.`,
  _ = `Lähetetään kutsu henkilölle:`,
  _ = `Kutsutaan %1$s`,
  _ = `%1$s on saanut kutsun. Se näkyy hänen %2$s-ilmoituksissaan.`,
  _ = `Käyttäjää %1$s ei voitu kutsua. Hänet on ehkä jo kutsuttu tai peli ei ole käytettävissä hänen alueellaan.`,
  _ = `Lähetettyjen kutsujen historia`,
  _ = `Viime aikoina kavereille lähettämäsi kutsut Steam Playtestiin tai rajoitettuun julkaisuun`,
  _ = `Käyttäjä %1$s kutsuttiin testaamaan peliä %2$s`,
  _ = `Steam Playtestiin osallistuminen`,
  _ = `Et ole osallistunut mihinkään käynnissä olevaan Steam Playtestiin tai rajoitettuun julkaisuun.`,
  _ = `Sinulla on vielä käytettäviä kutsuja`,
  _ = `Sinulla on %1$s odottava kutsu`,
  _ = `Sinulla on %1$s kutsua jäljellä`,
  _ = `Voit antaa kavereillesi pääsyn tähän Playtestiin kutsumalla heidät.`,
  _ = `Saatavilla olevien kutsujen määrä saattaa muuttua, kun lisää pelaajia liittyy.`,
  _ = `Pelin %1$s tai %2$s saattaa sisältää lisätietoja aikataulusta ja saatavilla olevasta sisällöstä.`,
  _ = `kauppasivu`,
  _ = `uutiskeskus`,
  _ = `Playtest ei ole aktiivinen tällä hetkellä.`,
  _ = `Olet käyttänyt kaikki kaverikutsut.`,
  _ = `Kutsu kavereita`,
  _ = `Valitse kutsun saaja`,
  _ = `Hae kaverin nimellä`,
  _ = `Kavereiden lataaminen epäonnistui.`,
  _ = `Joidenkin kavereiden kutsuminen ei onnistu, koska he ovat olleet kavereitasi alle 30 päivää, heillä on jo pääsy peliin tai eivät täytä muita ehtoja.`,
  _ = `Joidenkin kavereiden kutsuminen ei onnistu, koska heillä on jo pääsy peliin tai eivät täytä muita ehtoja.`,
  _ = `Rajoitettu julkaisu`,
  _ = `Voit antaa kavereillesi pääsyn rajoitettuun julkaisuun kutsumalla heidät.`,
  _ = `%1$s lisää pelaajien määrää hitaasti ensimmäisen rajoitetun julkaisun aikana. Lisätietoja saattaa löytyä sivuilta %2$s tai %3$s.`,
  _ = `Mikä on rajoitettu julkaisu?`,
  _ = `Rajoitettu julkaisu on ilmaiseksi pelattavien pelien hyödyntämä tapa kasvattaa pelaajamäärää pelin ensijulkaisua varten. Kutsun hyväksyminen tai luvan saaminen kehittäjältä lisää pelin kirjastoosi, jolloin voit aloittaa pelaamisen välittömästi.`,
  _ = `Steam-kaupan sivustokartta`,
  _ = `Kaupan aloitussivu`,
  _ = `Oma tili`,
  _ = `Omat tilitiedot`,
  _ = `Oman kaupan asetukset`,
  _ = `Perheen hallinta`,
  _ = `Turvallisuus ja laitteet`,
  _ = `Kieliasetukset`,
  _ = `Evästeet ja selaus`,
  _ = `Ilmoitusasetukset`,
  _ = `Ostoskori`,
  _ = `Ostoskori (%1$s)`,
  _ = `Toivelista`,
  _ = `Toivelista (%1$s)`,
  _ = `Seuraamasi pelit ja sovellukset`,
  _ = `Seuraamasi pelit ja sovellukset (%1$s)`,
  _ = `Tilastot ja listat`,
  _ = `Myydyimmät`,
  _ = `Pelatuimmat`,
  _ = `Uudet julkaisut`,
  _ = `Tulevat julkaisut`,
  _ = `Ilmaiset`,
  _ = `Steam-tilastot`,
  _ = `Tarjouksessa`,
  _ = `Suositukset`,
  _ = `Löytöjono`,
  _ = `Uusien julkaisujen jono`,
  _ = `Yhteisösuositukset`,
  _ = `Interaktiivinen suositusjärjestelmä`,
  _ = `Kavereiden suosikit`,
  _ = `Steam-kuraattorit`,
  _ = `Suositellut lisämateriaalit`,
  _ = `Laitteistot`,
  _ = `Steam Deck`,
  _ = `Steam Deck -telakka`,
  _ = `VR-laitteistot`,
  _ = `VR-pelit`,
  _ = `Toimii hyvin Deckillä`,
  _ = `Ohjainystävälliset pelit`,
  _ = `Tapoja pelata`,
  _ = `Uutiset ja päivitykset`,
  _ = `Hiljattain päivitetyt pelit`,
  _ = `Omat hiljattain päivitetyt pelit`,
  _ = `Tulevat tapahtumat`,
  _ = `Ajankohtaiset uutiset`,
  _ = `Steamin viralliset uutiset ja päivitykset`,
  _ = `Promot ja tapahtumat`,
  _ = `Erikoistarjoukset`,
  _ = `Aletapahtumat`,
  _ = `Steam Replay`,
  _ = `Steam Next Fest`,
  _ = `Steam-palkinnot`,
  _ = `Erikoisosiot`,
  _ = `Steamin pistekauppa`,
  _ = `Lahjakortit`,
  _ = `Lajityypit`,
  _ = `Teemat`,
  _ = `Olet tehnyt liian monta pyyntöä viime aikoina. Yritä myöhemmin uudelleen.`,
  _ = `Yleinen keskustelu`,
  _ = `Ilmiannetut viestit`,
  _ = `Workshop-keskustelut`,
  _ = `Vaihtokaupat`,
  _ = `Tapahtumat ja ilmoitukset`,
  _ = `Interaktiivinen suositusjärjestelmä`,
  _ = `Saatat pitää myös näistä`,
  _ = `Tutustu räätälöityihin suosituksiin, jotka koneoppimisjärjestelmä on koonnut Steam-pelihistoriasi perusteella verrattuna miljoonien muiden pelaajien tekemiin valintoihin. Rajaa tuloksia säätimillä ja suodattimilla ja tallenna asetukset, jotta Steam muistaa mieltymyksesi.`,
  _ = `Mukaan laskettu peliaikasi`,
  _ = `%1$s peliä`,
  _ = `suosituimmat %1$s peliä`,
  _ = `viimeisimmät pelit`,
  _ = `%1$s tuntia`,
  _ = `yhteensä %1$s tuntia`,
  _ = `pelattu viimeksi %1$s`,
  _ = `pelattu viimeksi yli 10 vuotta sitten`,
  _ = `Sisällytä`,
  _ = `Jätä pois`,
  _ = `Järjestä suosion mukaan`,
  _ = `suosittu`,
  _ = `erityiseen makuun`,
  _ = `Suodata julkaisuajan mukaan`,
  _ = `vanhempi`,
  _ = `uudempi`,
  _ = `Alusta saakka`,
  _ = `5 vuotta`,
  _ = `3 vuotta`,
  _ = `2 vuotta`,
  _ = ` 1 vuosi`,
  _ = `6 kuukautta`,
  _ = `Juuri sinulle`,
  _ = `Julkaistu %1$s`,
  _ = `Toivelistalla`,
  _ = `Lisää ostoskoriin`,
  _ = `Lisää toivelistalle`,
  _ = `Pelaa ilmaiseksi`,
  _ = `Anna tunnisteen nimi`,
  _ = `Lisää tunnistesuodattimia`,
  _ = `Lisää tunnisterajauksia`,
  _ = `Älä huomioi toivelistan pelejä`,
  _ = `Vain alennetut pelit`,
  _ = `Kuluneen kuukauden julkaisut`,
  _ = `Kuluneen viikon julkaisut`,
  _ = `Tulossa`,
  _ = `Oma pelikalenteri`,
  _ = `%1$s pelin lista juuri sinulle suositelluista uusista tai pian julkaistavista peleistä`,
  _ = `Tunnisteen valinta`,
  _ = `Valitse`,
  _ = `Piilota omistetut pelit`,
  _ = `Early Access -vaiheesta julkaistavat pelit näytetään edelleen`,
  _ = `Piilota Early Access -pelit`,
  _ = `Näytä vain toivelistalle lisätyt pelit`,
  _ = `Pelien lukumäärä`,
  _ = `Tiivistetty kalenteri`,
  _ = `Valinnainen ohitus`,
  _ = `Tilin tunnus`,
  _ = `Näytä kaikki %1$s`,
  _ = `Kirjautumalla näet henkilökohtaisia ehdotuksia.`,
  _ = `Laajenna kaikki`,
  _ = `Steam-laboratorion kokeilu 16 – <1>Lue lisää ja anna palautetta</1>`,
  _ = `Toivelistalle lisätyt pelit`,
  _ = `Näytä`,
  _ = `Piilota`,
  _ = `Vain`,
  _ = `Liikaa pelejä toivelistalla, ei käytössä`,
  _ = `Virhe kalenterin lataamisessa. Yritä uudelleen.`,
  _ = `Pelin %1$s myyntipaketit`,
  _ = `Myyntipakettien lista`,
  _ = `Kaikki myyntipaketit, joihin peli %1$s sisältyy.`,
  _ = `Steam Deck Verified`,
  _ = `%1$s toimii hyvin Steam Deckillä`,
  _ = `Virhe sivustolla`,
  _ = `VOI HARMI!`,
  _ = `Pyyntösi käsittelyssä tapahtui virhe.`,
  _ = `Määrän on oltava suurempi kuin 0.`,
  _ = `Sähköpostin verkkotunnus on jo toisen tiedotusvälineen käytössä.`,
  _ = `Tiedotusvälineen lisääminen epäonnistui.`,
  _ = `Sähköpostin verkkotunnusta ei voi jättää tyhjäksi.`,
  _ = `Sähköpostin verkkotunnus ei kelpaa.`,
  _ = `Tili on jo toisen tiedotusvälineen käytössä.`,
  _ = `Tilin lisääminen tiedotusvälineen käyttöön epäonnistui.`,
  _ = `Sähköpostin verkkotunnus`,
  _ = `Paikkojen määrä`,
  _ = `Lisää`,
  _ = `Lisää tiedotusväline`,
  _ = `%1$s – %2$s/%3$s paikasta käytössä`,
  _ = `Näytä historia`,
  _ = `%1$s – Historia`,
  _ = `%2$s myönsi lehdistötunnuksen käyttäjälle %1$s.`,
  _ = `%2$s peruutti käyttäjän %1$s lehdistötunnuksen.`,
  _ = `%1$s lisäsi tiedotusvälineen.`,
  _ = `%1$s päivitti tiedotusvälineen.`,
  _ = `Sähköpostin verkkotunnukseksi on määritetty %1$s.`,
  _ = `Paikkojen määräksi on asetettu %1$s.`,
  _ = `%1$s poisti tiedotusvälineen.`,
  _ = `%1$s palautti tiedotusvälineen.`,
  _ = `%1$s asetti tiedotusvälineen esikatselutilaan`,
  _ = `%1$s otti käyttöön esikatselutilassa tehdyt muutokset`,
  _ = `%2$s otti käyttöön käyttäjän %1$s esikatselutilassa tekemät muutokset`,
  _ = `%2$s poisti käyttäjän %1$s esikatselutilassa tekemät muutokset`,
  _ = `tuki`,
  _ = `Myöntäjä`,
  _ = `Myönnetty`,
  _ = `Onko kyseessä ryhmän ylläpitäjä?`,
  _ = `Lisättävä Steam-tunnus`,
  _ = `OK`,
  _ = `Peru`,
  _ = `Kyllä`,
  _ = `Ei`,
  _ = `Kaikki`,
  _ = `Aktiivinen`,
  _ = `Poistettu`,
  _ = `Tyhjä`,
  _ = `Tiedotusväline ilman ylläpitäjiä`,
  _ = `Tiedotusväline`,
  _ = `Kaverikoodi`,
  _ = `Luovuta lehdistötunnus `,
  _ = `Haluatko varmasti luovuttaa lehdistötunnuksen?`,
  _ = `Tiedotusvälineen historia`,
  _ = `Lisää jäsen`,
  _ = `Näytä historia`,
  _ = `Tili`,
  _ = `Traileria ei löytynyt`,
  _ = `Traileri`,
  _ = `Mikrotraileri`,
  _ = `Ilmoitusasetuksien tallentamisessa ilmeni virhe`,
  _ = `Ilmoitusasetuksien lataamisessa ilmeni virhe`,
  _ = `Tilauksen perumislinkki on virheellinen tai vanhentunut. Kirjaudu sisään ja käy <1>ilmoitusasetuksissa</1>.`,
  _ = `Syöte on automaattisesti käytössä, jos käytät työpöytä- tai mobiilisovelluksen ilmoituksia.`,
  _ = `Lähetä ilmoitus vain käyttäjälle %1$s näistä toivelistan luokista`,
  _ = `Arvioitu kuvataajuus`,
  _ = `Valitsemalla sovelluksen ja tietokoneen kokoonpanon saat arvioiduista kuvataajuuksista kaavion, joka perustuu muiden Steam-käyttäjien tuloksiin`,
  _ = `CPU`,
  _ = `Järjestelmän RAM-muisti`,
  _ = `GPU`,
  _ = `Oma tallennettu laitteisto`,
  _ = `Ei tallennettuja laitteistoja.`,
  _ = `Näet arvioidun kuvataajuuden valitsemalla oman laitteistosi.`,
  _ = `<Ei valittu>`,
  _ = `Voit lisätä nykyisen laitteistosi tarkastelemalla tietoja Steam-asiakasohjelmasta käsin.`,
  _ = `Lisää tallennettu laitteisto`,
  _ = `Lisää tallennettu laitteisto (asiakasohjelman ulkopuolella)`,
  _ = `Jos haluat osallistua anonymisoitujen kuvataajuusarvioiden keräämiseen, jotta tiedoista olisi hyötyä mahdollisimman monelle, voit muuttaa asetuksiasi alla olevan linkin Tietojen keräys -osiosta.`,
  _ = `Asetukset`,
  _ = `FPS`,
  _ = `Hae peliä`,
  _ = `Valitse suoritin`,
  _ = `Valitse näytönohjain`,
  _ = `Pelejä vastaavien koneoppimistietojen määrä`,
  _ = `Suoritinta vastaavien koneoppimistietojen määrä`,
  _ = `Näytönohjainta vastaavien koneoppimistietojen määrä`,
  _ = `Tuntematon`,
  _ = `Lähetä lahjakortti`,
  _ = ``,
  _ = {
    BundleList_SubTitle: _,
    BundleList_SortBy: _,
    BundleList_SortBy_Popular: _,
    BundleList_SortBy_Price: _,
    BundleList_SortBy_Discount: _,
    BundleList_SortBy_Name: _,
    BundleList_SortBy_Recommend: _,
    BundleList_AllInLibrary: _,
    BundleList_AllInLibrarySubtitle: _,
    BundleList_CompleteTheSet: _,
    BundleList_CompleteTheSetSubtitle: _,
    BundleList_MustPurchaseAsSet: _,
    BundleList_MustPurchaseAsSetSubtitle: _,
    footer_legal_notice: _,
    footer_vat_included: _,
    footer_privacy_policy: _,
    footer_legal: _,
    footer_accessibility: _,
    footer_ssa: _,
    footer_refunds: _,
    footer_cookies: _,
    footer_about_valve: _,
    footer_business_solutions: _,
    footer_recycling: _,
    footer_steamworks: _,
    footer_source_engine: _,
    footer_jobs: _,
    footer_walletcode: _,
    footer_steam_distribution: _,
    footer_nav_help_support: _,
    wishlist_title: _,
    wishlist_header: _,
    cart_count: _,
    cart_view_cart: _,
    wishlist_count: _,
    wishlist_options_button: _,
    wishlist_sortby_button: _,
    wishlist_share_tooltip: _,
    wishlist_controls_sortby_order: _,
    wishlist_controls_sortby_their_order: _,
    wishlist_controls_sortby_topsellers: _,
    wishlist_controls_sortby_releasedate: _,
    wishlist_controls_sortby_dateadded: _,
    wishlist_controls_sortby_reviews: _,
    wishlist_controls_sortby_price: _,
    wishlist_controls_sortby_name: _,
    wishlist_controls_sortby_discount: _,
    wishlist_controls_share_dialog_title: _,
    wishlist_controls_share_revokeall: _,
    wishlist_controls_share_revokeall_success: _,
    wishlist_controls_share_generation_failure: _,
    wishlist_controls_share_description: _,
    wishlist_controls_options_category_view: _,
    wishlist_controls_options_view_expanded: _,
    wishlist_controls_options_view_compact: _,
    wishlist_controls_options_category_platform: _,
    wishlist_controls_options_platform_all: _,
    wishlist_controls_options_platform_mac: _,
    wishlist_controls_options_platform_linux: _,
    wishlist_controls_options_category_type: _,
    wishlist_controls_options_type_game: _,
    wishlist_controls_options_type_application: _,
    wishlist_controls_options_type_dlc: _,
    wishlist_controls_options_type_video: _,
    wishlist_controls_options_category_price: _,
    wishlist_controls_options_category_discount: _,
    wishlist_controls_options_discount_all: _,
    wishlist_controls_options_discount_any: _,
    wishlist_controls_options_discount_or_more: _,
    wishlist_controls_options_price_any: _,
    wishlist_controls_options_price_max_price: _,
    wishlist_controls_options_price_free: _,
    wishlist_controls_options_category_exclude: _,
    wishlist_controls_options_category_related: _,
    genre_early_access: _,
    wishlist_controls_early_access_tooltip: _,
    category_prerelease: _,
    wishlist_controls_options_exclude_vr: _,
    wishlist_controls_demo_available: _,
    wishlist_controls_demo_available_tooltip: _,
    wishlist_controls_options_category_deck: _,
    wishlist_controls_options_deck_verified: _,
    wishlist_controls_options_deck_playable: _,
    wishlist_controls_options_category_tag: _,
    wishlist_controls_tag_description: _,
    wishlist_controls_tags_header: _,
    wishlist_controls_filter_tag_label: _,
    wishlist_controls_options_category_category: _,
    wishlist_controls_categories_header_anonymous: _,
    wishlist_controls_categories_multiselect_label: _,
    wishlist_controls_categories_add: _,
    wishlist_categories_advanced_title: _,
    wishlist_categories_advanced_select: _,
    wishlist_categories_advanced_rename_label: _,
    wishlist_categories_advanced_rename_save: _,
    wishlist_categories_advanced_rename_duplicate: _,
    wishlist_categories_advanced_rename_failed: _,
    wishlist_categories_advanced_no_items: _,
    wishlist_categories_advanced_select_all: _,
    wishlist_categories_advanced_select_none: _,
    wishlist_categories_advanced_showing: _,
    wishlist_categories_advanced_failed_items: _,
    wishlist_categories_advanced_failed_items_Plural: _,
    wishlist_categories_advanced_pending: _,
    wishlist_categories_advanced_pending_adds: _,
    wishlist_categories_advanced_pending_removals: _,
    wishlist_categories_advanced_revert: _,
    wishlist_categories_advanced_apply: _,
    wishlist_categories_advanced_addremove_title: _,
    wishlist_displayed_item_count: _,
    wishlist_displayed_item_count_Plural: _,
    wishlist_filter_results: _,
    wishlist_filter_matches_items: _,
    wishlist_filter_matches_items_Plural: _,
    wishlist_filter_matches_category: _,
    wishlist_filter_matches_category_Plural: _,
    wishlist_filter_matches_categories: _,
    wishlist_filter_matches_categories_Plural: _,
    wishlist_filter_matches_tag: _,
    wishlist_filter_matches_tag_Plural: _,
    wishlist_filter_matches_tags: _,
    wishlist_filter_matches_tags_Plural: _,
    wishlist_search: _,
    wishlist_search_all: _,
    wishlist_item_overallreviews: _,
    wishlist_item_languagespecific_reviews: _,
    wishlist_item_releasedate: _,
    wishlist_item_addedon_date: _,
    wishlist_item_remove: _,
    wishlist_item_remove_tooltip: _,
    wishlist_item_unavailable_title: _,
    wishlist_item_unavailable_region: _,
    wishlist_item_unavailable_retired: _,
    mature_content_requires_creditcard: _,
    mature_content_requires_creditcard_gb: _,
    wishlist_item_add_credit_card: _,
    wishlist_your_wishlist_empty: _,
    wishlist_browse_the_store: _,
    wishlist_learn_more_button: _,
    wishlist_sign_in_to_see_your_wishlist: _,
    wishlist_others_wishlist_empty: _,
    wishlist_no_items_matching_filters: _,
    wishlist_x_items_on_wishlist_but_none_match: _,
    wishlist_x_items_on_wishlist_but_none_match_prefs: _,
    wishlist_gamepaddragdrop_reorderaction: _,
    wishlist_gamepaddragdrop_cancelreorder: _,
    wishlist_gamepaddragdrop_commitreorder: _,
    wishlist_gamepad_options: _,
    wishlist_gamepad_options_remove: _,
    wishlist_gamepad_visitstore: _,
    wishlist_errorpage_title: _,
    errorpage_error: _,
    errorpage_unknownerror: _,
    wishlist_error_profilenotfound: _,
    wishlist_error_wishlistunavailable: _,
    wishlist_error_invalidsharetoken: _,
    wishlist_filters_notification: _,
    youraccount_users_account: _,
    youraccount_errorpage_title: _,
    youraccount_account: _,
    m_home: _,
    global_menu_account_details: _,
    global_menu_account_preferences: _,
    global_menu_account_language_preferences: _,
    global_menu_account_notification_settings: _,
    global_menu_account_hardware_used: _,
    global_menu_account_security_devices: _,
    global_menu_account_video_authorized_devices: _,
    global_menu_account_mobile_game_devices: _,
    global_menu_account_gated_access_games: _,
    accountpreferences_familymanagement_header: _,
    CookiePreferences: _,
    global_menu_vr: `VR`,
    global_menu_greatondeck: _,
    global_menu_localplayonframe: _,
    store_tab_foryou_store_home: _,
    browse_categories: _,
    m_search_steam: _,
    playteststatus_error_dataunavailable: _,
    playtestinvites_title: _,
    playtestinvites_accept: _,
    playtestinvites_reject: _,
    playtestinvites_invitedescription_fromapp2: _,
    playtestinvites_invitedescription_fromapp_limitedlaunch: _,
    playtestinvites_invitedescription_fromuser2: _,
    playtestinvites_invitedescription_fromuser_limitedlaunch: _,
    playtestinvites_noinvites: _,
    playtestinvites_welcome: _,
    playtestinvites_welcome_limitedlaunch: _,
    playtestinvites_welcome_notplayable: _,
    playtestinvites_viewlibrary: _,
    playtestinvites_desc_title: _,
    playtestinvites_desc1: _,
    playtestinvites_desc2: _,
    playtestinvites_ignored_title: _,
    playtestinvites_ignored_desc: _,
    playtestinvites_ignored_remove: _,
    playtestinvites_sendinvite_cancel: _,
    playtestinvites_sendinvite_send: _,
    playtestinvites_sendinvite_lastinvite: _,
    playtestinvites_sendinvite_lastinvite_limitedlaunch: _,
    playtestinvites_sendinvite_confirm_desc: _,
    playtestinvites_sendinvite_pending: _,
    playtestinvites_sendinvite_success: _,
    playtestinvites_sendinvite_failure: _,
    playtestinvitehistory_title: _,
    playtestinvitehistory_desc: _,
    playtestinvitehistory_invite_detail: _,
    playteststatus_title: _,
    playteststatus_none: _,
    playteststatus_invites_available: _,
    playteststatus_invite_count: _,
    playteststatus_invite_count_plural: _,
    playteststatus_invite_count_tooltip: _,
    playteststatus_invite_count_tooltip2: _,
    playteststatus_details_moreinfo: _,
    playteststatus_details_moreinfo_storepage: _,
    playteststatus_details_moreinfo_newshub: _,
    playteststatus_details_notplayable: _,
    playteststatus_details_allinvitesused: _,
    playteststatus_invitefriends: _,
    playteststatus_invitefrienddialog_header: _,
    playteststatus_invitefrienddialog_search_placeholder: _,
    playteststatus_invitefrienddialog_loadingerror: _,
    playteststatus_invitefrienddialog_ineligiblefriends: _,
    playteststatus_invitefrienddialog_ineligiblefriends_purchaser: _,
    gatedaccess_limitedlaunch_badge: _,
    gatedaccess_limitedlaunch_invite_count_tooltip: _,
    gatedaccess_limitedlaunch_details_moreinfo: _,
    gatedaccess_limitedlaunch_desc_title: _,
    gatedaccess_limitedlaunch_desc: _,
    sitemap_title: _,
    sitemap_home: _,
    sitemap_section_account: _,
    sitemap_section_account_account_details: _,
    sitemap_section_account_store_preferences: _,
    sitemap_section_account_family_management: _,
    sitemap_section_account_security_and_devices: _,
    sitemap_section_account_language_preferences: _,
    sitemap_section_account_cookes_and_browsing: _,
    sitemap_section_account_notification_settings: _,
    sitemap_section_account_cart: _,
    sitemap_section_account_cart_with_count: _,
    sitemap_section_account_wishlist: _,
    sitemap_section_account_wishlist_with_count: _,
    sitemap_section_account_followed_games: _,
    sitemap_section_account_followed_games_with_count: _,
    sitemap_section_chartsandlists: _,
    sitemap_section_chartsandlists_top_sellers: _,
    sitemap_section_chartsandlists_most_played: _,
    sitemap_section_chartsandlists_new_releases: _,
    sitemap_section_chartsandlists_upcoming_releases: _,
    sitemap_section_chartsandlists_free_to_play: _,
    sitemap_section_chartsandlists_steam_charts: _,
    sitemap_section_chartsandlists_on_sale_now: _,
    sitemap_section_recommendations: _,
    sitemap_section_recommendations_discovery_queue: _,
    sitemap_section_recommendations_new_releases_queue: _,
    sitemap_section_recommendations_community_recommendations: _,
    sitemap_section_recommendations_interactive_recommender: _,
    sitemap_section_recommendations_popular_among_friends: _,
    sitemap_section_recommendations_steam_curators: _,
    sitemap_section_recommendations_dlc_for_you: _,
    sitemap_section_hardware: _,
    sitemap_section_hardware_steam_deck: _,
    sitemap_section_hardware_steam_deck_dock: _,
    sitemap_section_hardware_vr_hardware: _,
    sitemap_section_hardware_vr_games: _,
    sitemap_section_hardware_great_on_deck: _,
    sitemap_section_hardware_controller_friendly: _,
    sitemap_section_waystoplay: _,
    sitemap_section_newsupdates: _,
    sitemap_section_newsupdates_recently_updated: _,
    sitemap_section_newsupdates_your_recently_updated: _,
    sitemap_section_newsupdates_your_upcoming_events: _,
    sitemap_section_newsupdates_featured_news: _,
    sitemap_section_newsupdates_steam_official_news: _,
    sitemap_section_promosandevents: _,
    sitemap_section_promosandevents_special_offers: _,
    sitemap_section_promosandevents_sale_events: _,
    sitemap_section_promosandevents_steam_replay: _,
    sitemap_section_promosandevents_steam_next_fest: _,
    sitemap_section_promosandevents_steam_awards: _,
    sitemap_section_specialsections: _,
    sitemap_pointsshop: _,
    sitemap_giftcards: _,
    sitemap_genres: _,
    sitemap_themes: _,
    Error_RateLimited: _,
    Discussions_ForumName_General: _,
    Discussions_ForumName_ReportedPosts: _,
    Discussions_ForumName_Workshop: _,
    Discussions_ForumName_Trading: _,
    Discussions_ForumName_Events: _,
    ir_name: _,
    ir_header: _,
    ir_body: _,
    ir_playtime_header: _,
    ir_playtime_games: _,
    ir_playtime_topgames: _,
    ir_playtime_recentgames: _,
    ir_playtime_hours: _,
    ir_playtime_hourstotal: _,
    ir_playtime_lastplayed: _,
    ir_playtime_lastplayedmax: _,
    ir_playtime_unignore: _,
    ir_playtime_ignore: _,
    ir_popularity_title: _,
    ir_popularity_popular: _,
    ir_popularity_niche: _,
    ir_recency_title: _,
    ir_recency_older: _,
    ir_recency_newer: _,
    ir_filter_age_all: _,
    ir_filter_age_60: _,
    ir_filter_age_36: _,
    ir_filter_age_24: _,
    ir_filter_age_12: _,
    ir_filter_age_6: _,
    ir_recommendations_header: _,
    ir_release_date: _,
    ir_on_wishlist: _,
    ir_add_to_cart: _,
    ir_add_to_wishlist: _,
    ir_free_to_play: _,
    ir_tag_placeholder: _,
    ir_tag_filter: _,
    ir_tag_exclude: _,
    ir_no_wishlisted: _,
    ir_discounted_only: _,
    PersonalCalendar_LastMonthGames: _,
    PersonalCalendar_LastWeekGames: _,
    PersonalCalendar_Upcoming: _,
    PersonalCalendar_Title: _,
    PersonalCalendar_Description: _,
    PersonalCalendar_TagSelector: _,
    PersonalCalendar_TagSelector_Placeholder: _,
    PersonalCalendar_HideOwned: _,
    PersonalCalendar_HideEATooltip: _,
    PersonalCalendar_HideEarlyAccess: _,
    PersonalCalendar_ShowOnlyWishlisted: _,
    PersonalCalendar_ResultCountSelector: _,
    PersonalCalendar_CompactMode: _,
    PersonalCalendar_AccountPlaceholder: _,
    PersonalCalendar_Account: _,
    PersonalCalendar_ShowMore: _,
    PersonalCalendar_LoginPrompt: _,
    PersonalCalendar_ShowAll: _,
    PersonalCalendar_SteamLabs: _,
    PersonalCalendar_Wishlisted: _,
    PersonalCalendar_WishlistShow: _,
    PersonalCalendar_WishlistHide: _,
    PersonalCalendar_WishlistOnly: _,
    PersonalCalendar_IgnoringWishlists: _,
    PersonalCalendar_Error_Backend: _,
    BundleList_Title: _,
    BundleList_Title_Fallback: _,
    BundleList_Page: _,
    Verification_DeckOnly: _,
    Verification_DeckOnly_Desc: _,
    FatalErrorPage_Title: _,
    FatalErrorPage_Header: _,
    FatalErrorPage_Message: _,
    pressoutlets_error_slots_gt_zero: _,
    pressoutlets_error_domain_used: _,
    pressoutlets_error_adding_outlet: _,
    pressoutlets_error_domain_empty: _,
    pressoutlets_error_invalid_domain: _,
    pressoutlets_error_already_owned: _,
    pressoutlets_error_generic_add_error: _,
    pressoutlets_email_domain_label: _,
    pressoutlets_slots_label: _,
    pressoutlets_button_add: _,
    pressoutlets_label_add_outlet: _,
    pressoutlets_outlet_header: _,
    pressoutlets_show_history: _,
    pressoutlets_history_title: _,
    pressoutlets_action_granted: _,
    pressoutlets_action_removed: _,
    pressoutlets_action_created: _,
    pressoutlets_action_updated: _,
    pressoutlets_action_updated_domain_changed: _,
    pressoutlets_action_updated_slots_changed: _,
    pressoutlets_action_deleted: _,
    pressoutlets_action_undeleted: _,
    pressoutlets_action_enterstaging: _,
    pressoutlets_action_exitstaging: _,
    pressoutlets_action_stagedadd: _,
    pressoutlets_action_stageddelete: _,
    pressoutlets_action_by_support: _,
    pressoutlets_header_grantee: _,
    pressoutlets_header_granted_at: _,
    pressoutlets_header_is_group_admin: _,
    pressoutlets_steamid_to_add: _,
    pressoutlets_button_ok: `OK`,
    pressoutlets_button_cancel: _,
    pressoutlets_is_group_admin: _,
    pressoutlets_is_not_group_admin: `Ei`,
    pressoutlets_filter_all: _,
    pressoutlets_filter_active: _,
    pressoutlets_filter_deleted: _,
    pressoutlets_filter_empty: _,
    pressoutlets_filter_noadmins: _,
    pressoutlets_outlet_header_prefix: _,
    pressoutlets_friendcode: _,
    pressoutlets_resign_your_key: _,
    pressoutlets_resign_your_key_title: _,
    pressoutlets_history_header: _,
    pressoutlets_button_add_member: _,
    pressoutlets_button_show_history: _,
    pressoutlets_header_account: _,
    trailerassets_invalidfile: _,
    trailerassets_trailer: _,
    trailerassets_microtrailer: _,
    account_notification_settings_error_saving: _,
    account_notification_settings_error_loading: _,
    account_notification_settings_error_invalidoptouttoken: _,
    account_notification_settings_feed_disabled: _,
    account_notification_settings_wishlist_categories_persona: _,
    framerate_title: _,
    framerate_subheader: _,
    framerate_cpu: `CPU`,
    framerate_ram: _,
    framerate_gpu: `GPU`,
    framerate_saved_hardware: _,
    framerate_saved_hardware_none: _,
    framerate_saved_hardware_select: _,
    framerate_saved_hardware_option_none: _,
    framerate_saved_add: _,
    framerate_saved_add_btn: _,
    framerate_saved_add_not_in_client_btn: _,
    framerate_opt_in_data_collection_desc: _,
    framerate_opt_in_link: _,
    framerate_fps: `FPS`,
    framerate_game_name: _,
    framerate_select_cpu: _,
    framerate_select_gpu: _,
    framerate_training_game: _,
    framerate_training_cpu: _,
    framerate_training_gpu: _,
    generic_unknown: _,
    giftcards_banner_text: _,
    empty_no_trailing_comma: ``,
  };
export {
  _ as BundleList_AllInLibrary,
  _ as BundleList_AllInLibrarySubtitle,
  _ as BundleList_CompleteTheSet,
  _ as BundleList_CompleteTheSetSubtitle,
  _ as BundleList_MustPurchaseAsSet,
  _ as BundleList_MustPurchaseAsSetSubtitle,
  _ as BundleList_Page,
  _ as BundleList_SortBy,
  _ as BundleList_SortBy_Discount,
  _ as BundleList_SortBy_Name,
  _ as BundleList_SortBy_Popular,
  _ as BundleList_SortBy_Price,
  _ as BundleList_SortBy_Recommend,
  _ as BundleList_SubTitle,
  _ as BundleList_Title,
  _ as BundleList_Title_Fallback,
  _ as CookiePreferences,
  _ as Discussions_ForumName_Events,
  _ as Discussions_ForumName_General,
  _ as Discussions_ForumName_ReportedPosts,
  _ as Discussions_ForumName_Trading,
  _ as Discussions_ForumName_Workshop,
  _ as Error_RateLimited,
  _ as FatalErrorPage_Header,
  _ as FatalErrorPage_Message,
  _ as FatalErrorPage_Title,
  _ as PersonalCalendar_Account,
  _ as PersonalCalendar_AccountPlaceholder,
  _ as PersonalCalendar_CompactMode,
  _ as PersonalCalendar_Description,
  _ as PersonalCalendar_Error_Backend,
  _ as PersonalCalendar_HideEATooltip,
  _ as PersonalCalendar_HideEarlyAccess,
  _ as PersonalCalendar_HideOwned,
  _ as PersonalCalendar_IgnoringWishlists,
  _ as PersonalCalendar_LastMonthGames,
  _ as PersonalCalendar_LastWeekGames,
  _ as PersonalCalendar_LoginPrompt,
  _ as PersonalCalendar_ResultCountSelector,
  _ as PersonalCalendar_ShowAll,
  _ as PersonalCalendar_ShowMore,
  _ as PersonalCalendar_ShowOnlyWishlisted,
  _ as PersonalCalendar_SteamLabs,
  _ as PersonalCalendar_TagSelector,
  _ as PersonalCalendar_TagSelector_Placeholder,
  _ as PersonalCalendar_Title,
  _ as PersonalCalendar_Upcoming,
  _ as PersonalCalendar_WishlistHide,
  _ as PersonalCalendar_WishlistOnly,
  _ as PersonalCalendar_WishlistShow,
  _ as PersonalCalendar_Wishlisted,
  _ as Verification_DeckOnly,
  _ as Verification_DeckOnly_Desc,
  _ as account_notification_settings_error_invalidoptouttoken,
  _ as account_notification_settings_error_loading,
  _ as account_notification_settings_error_saving,
  _ as account_notification_settings_feed_disabled,
  _ as account_notification_settings_wishlist_categories_persona,
  _ as accountpreferences_familymanagement_header,
  _ as browse_categories,
  _ as cart_count,
  _ as cart_view_cart,
  _ as category_prerelease,
  _ as default,
  _ as empty_no_trailing_comma,
  _ as errorpage_error,
  _ as errorpage_unknownerror,
  _ as footer_about_valve,
  _ as footer_accessibility,
  _ as footer_business_solutions,
  _ as footer_cookies,
  _ as footer_jobs,
  _ as footer_legal,
  _ as footer_legal_notice,
  _ as footer_nav_help_support,
  _ as footer_privacy_policy,
  _ as footer_recycling,
  _ as footer_refunds,
  _ as footer_source_engine,
  _ as footer_ssa,
  _ as footer_steam_distribution,
  _ as footer_steamworks,
  _ as footer_vat_included,
  _ as footer_walletcode,
  _ as framerate_cpu,
  _ as framerate_fps,
  _ as framerate_game_name,
  _ as framerate_gpu,
  _ as framerate_opt_in_data_collection_desc,
  _ as framerate_opt_in_link,
  _ as framerate_ram,
  _ as framerate_saved_add,
  _ as framerate_saved_add_btn,
  _ as framerate_saved_add_not_in_client_btn,
  _ as framerate_saved_hardware,
  _ as framerate_saved_hardware_none,
  _ as framerate_saved_hardware_option_none,
  _ as framerate_saved_hardware_select,
  _ as framerate_select_cpu,
  _ as framerate_select_gpu,
  _ as framerate_subheader,
  _ as framerate_title,
  _ as framerate_training_cpu,
  _ as framerate_training_game,
  _ as framerate_training_gpu,
  _ as gatedaccess_limitedlaunch_badge,
  _ as gatedaccess_limitedlaunch_desc,
  _ as gatedaccess_limitedlaunch_desc_title,
  _ as gatedaccess_limitedlaunch_details_moreinfo,
  _ as gatedaccess_limitedlaunch_invite_count_tooltip,
  _ as generic_unknown,
  _ as genre_early_access,
  _ as giftcards_banner_text,
  _ as global_menu_account_details,
  _ as global_menu_account_gated_access_games,
  _ as global_menu_account_hardware_used,
  _ as global_menu_account_language_preferences,
  _ as global_menu_account_mobile_game_devices,
  _ as global_menu_account_notification_settings,
  _ as global_menu_account_preferences,
  _ as global_menu_account_security_devices,
  _ as global_menu_account_video_authorized_devices,
  _ as global_menu_greatondeck,
  _ as global_menu_localplayonframe,
  _ as global_menu_vr,
  _ as ir_add_to_cart,
  _ as ir_add_to_wishlist,
  _ as ir_body,
  _ as ir_discounted_only,
  _ as ir_filter_age_12,
  _ as ir_filter_age_24,
  _ as ir_filter_age_36,
  _ as ir_filter_age_6,
  _ as ir_filter_age_60,
  _ as ir_filter_age_all,
  _ as ir_free_to_play,
  _ as ir_header,
  _ as ir_name,
  _ as ir_no_wishlisted,
  _ as ir_on_wishlist,
  _ as ir_playtime_games,
  _ as ir_playtime_header,
  _ as ir_playtime_hours,
  _ as ir_playtime_hourstotal,
  _ as ir_playtime_ignore,
  _ as ir_playtime_lastplayed,
  _ as ir_playtime_lastplayedmax,
  _ as ir_playtime_recentgames,
  _ as ir_playtime_topgames,
  _ as ir_playtime_unignore,
  _ as ir_popularity_niche,
  _ as ir_popularity_popular,
  _ as ir_popularity_title,
  _ as ir_recency_newer,
  _ as ir_recency_older,
  _ as ir_recency_title,
  _ as ir_recommendations_header,
  _ as ir_release_date,
  _ as ir_tag_exclude,
  _ as ir_tag_filter,
  _ as ir_tag_placeholder,
  _ as m_home,
  _ as m_search_steam,
  _ as mature_content_requires_creditcard,
  _ as mature_content_requires_creditcard_gb,
  _ as playtestinvitehistory_desc,
  _ as playtestinvitehistory_invite_detail,
  _ as playtestinvitehistory_title,
  _ as playtestinvites_accept,
  _ as playtestinvites_desc1,
  _ as playtestinvites_desc2,
  _ as playtestinvites_desc_title,
  _ as playtestinvites_ignored_desc,
  _ as playtestinvites_ignored_remove,
  _ as playtestinvites_ignored_title,
  _ as playtestinvites_invitedescription_fromapp2,
  _ as playtestinvites_invitedescription_fromapp_limitedlaunch,
  _ as playtestinvites_invitedescription_fromuser2,
  _ as playtestinvites_invitedescription_fromuser_limitedlaunch,
  _ as playtestinvites_noinvites,
  _ as playtestinvites_reject,
  _ as playtestinvites_sendinvite_cancel,
  _ as playtestinvites_sendinvite_confirm_desc,
  _ as playtestinvites_sendinvite_failure,
  _ as playtestinvites_sendinvite_lastinvite,
  _ as playtestinvites_sendinvite_lastinvite_limitedlaunch,
  _ as playtestinvites_sendinvite_pending,
  _ as playtestinvites_sendinvite_send,
  _ as playtestinvites_sendinvite_success,
  _ as playtestinvites_title,
  _ as playtestinvites_viewlibrary,
  _ as playtestinvites_welcome,
  _ as playtestinvites_welcome_limitedlaunch,
  _ as playtestinvites_welcome_notplayable,
  _ as playteststatus_details_allinvitesused,
  _ as playteststatus_details_moreinfo,
  _ as playteststatus_details_moreinfo_newshub,
  _ as playteststatus_details_moreinfo_storepage,
  _ as playteststatus_details_notplayable,
  _ as playteststatus_error_dataunavailable,
  _ as playteststatus_invite_count,
  _ as playteststatus_invite_count_plural,
  _ as playteststatus_invite_count_tooltip,
  _ as playteststatus_invite_count_tooltip2,
  _ as playteststatus_invitefrienddialog_header,
  _ as playteststatus_invitefrienddialog_ineligiblefriends,
  _ as playteststatus_invitefrienddialog_ineligiblefriends_purchaser,
  _ as playteststatus_invitefrienddialog_loadingerror,
  _ as playteststatus_invitefrienddialog_search_placeholder,
  _ as playteststatus_invitefriends,
  _ as playteststatus_invites_available,
  _ as playteststatus_none,
  _ as playteststatus_title,
  _ as pressoutlets_action_by_support,
  _ as pressoutlets_action_created,
  _ as pressoutlets_action_deleted,
  _ as pressoutlets_action_enterstaging,
  _ as pressoutlets_action_exitstaging,
  _ as pressoutlets_action_granted,
  _ as pressoutlets_action_removed,
  _ as pressoutlets_action_stagedadd,
  _ as pressoutlets_action_stageddelete,
  _ as pressoutlets_action_undeleted,
  _ as pressoutlets_action_updated,
  _ as pressoutlets_action_updated_domain_changed,
  _ as pressoutlets_action_updated_slots_changed,
  _ as pressoutlets_button_add,
  _ as pressoutlets_button_add_member,
  _ as pressoutlets_button_cancel,
  _ as pressoutlets_button_ok,
  _ as pressoutlets_button_show_history,
  _ as pressoutlets_email_domain_label,
  _ as pressoutlets_error_adding_outlet,
  _ as pressoutlets_error_already_owned,
  _ as pressoutlets_error_domain_empty,
  _ as pressoutlets_error_domain_used,
  _ as pressoutlets_error_generic_add_error,
  _ as pressoutlets_error_invalid_domain,
  _ as pressoutlets_error_slots_gt_zero,
  _ as pressoutlets_filter_active,
  _ as pressoutlets_filter_all,
  _ as pressoutlets_filter_deleted,
  _ as pressoutlets_filter_empty,
  _ as pressoutlets_filter_noadmins,
  _ as pressoutlets_friendcode,
  _ as pressoutlets_header_account,
  _ as pressoutlets_header_granted_at,
  _ as pressoutlets_header_grantee,
  _ as pressoutlets_header_is_group_admin,
  _ as pressoutlets_history_header,
  _ as pressoutlets_history_title,
  _ as pressoutlets_is_group_admin,
  _ as pressoutlets_is_not_group_admin,
  _ as pressoutlets_label_add_outlet,
  _ as pressoutlets_outlet_header,
  _ as pressoutlets_outlet_header_prefix,
  _ as pressoutlets_resign_your_key,
  _ as pressoutlets_resign_your_key_title,
  _ as pressoutlets_show_history,
  _ as pressoutlets_slots_label,
  _ as pressoutlets_steamid_to_add,
  _ as sitemap_genres,
  _ as sitemap_giftcards,
  _ as sitemap_home,
  _ as sitemap_pointsshop,
  _ as sitemap_section_account,
  _ as sitemap_section_account_account_details,
  _ as sitemap_section_account_cart,
  _ as sitemap_section_account_cart_with_count,
  _ as sitemap_section_account_cookes_and_browsing,
  _ as sitemap_section_account_family_management,
  _ as sitemap_section_account_followed_games,
  _ as sitemap_section_account_followed_games_with_count,
  _ as sitemap_section_account_language_preferences,
  _ as sitemap_section_account_notification_settings,
  _ as sitemap_section_account_security_and_devices,
  _ as sitemap_section_account_store_preferences,
  _ as sitemap_section_account_wishlist,
  _ as sitemap_section_account_wishlist_with_count,
  _ as sitemap_section_chartsandlists,
  _ as sitemap_section_chartsandlists_free_to_play,
  _ as sitemap_section_chartsandlists_most_played,
  _ as sitemap_section_chartsandlists_new_releases,
  _ as sitemap_section_chartsandlists_on_sale_now,
  _ as sitemap_section_chartsandlists_steam_charts,
  _ as sitemap_section_chartsandlists_top_sellers,
  _ as sitemap_section_chartsandlists_upcoming_releases,
  _ as sitemap_section_hardware,
  _ as sitemap_section_hardware_controller_friendly,
  _ as sitemap_section_hardware_great_on_deck,
  _ as sitemap_section_hardware_steam_deck,
  _ as sitemap_section_hardware_steam_deck_dock,
  _ as sitemap_section_hardware_vr_games,
  _ as sitemap_section_hardware_vr_hardware,
  _ as sitemap_section_newsupdates,
  _ as sitemap_section_newsupdates_featured_news,
  _ as sitemap_section_newsupdates_recently_updated,
  _ as sitemap_section_newsupdates_steam_official_news,
  _ as sitemap_section_newsupdates_your_recently_updated,
  _ as sitemap_section_newsupdates_your_upcoming_events,
  _ as sitemap_section_promosandevents,
  _ as sitemap_section_promosandevents_sale_events,
  _ as sitemap_section_promosandevents_special_offers,
  _ as sitemap_section_promosandevents_steam_awards,
  _ as sitemap_section_promosandevents_steam_next_fest,
  _ as sitemap_section_promosandevents_steam_replay,
  _ as sitemap_section_recommendations,
  _ as sitemap_section_recommendations_community_recommendations,
  _ as sitemap_section_recommendations_discovery_queue,
  _ as sitemap_section_recommendations_dlc_for_you,
  _ as sitemap_section_recommendations_interactive_recommender,
  _ as sitemap_section_recommendations_new_releases_queue,
  _ as sitemap_section_recommendations_popular_among_friends,
  _ as sitemap_section_recommendations_steam_curators,
  _ as sitemap_section_specialsections,
  _ as sitemap_section_waystoplay,
  _ as sitemap_themes,
  _ as sitemap_title,
  _ as store_tab_foryou_store_home,
  _ as trailerassets_invalidfile,
  _ as trailerassets_microtrailer,
  _ as trailerassets_trailer,
  _ as wishlist_browse_the_store,
  _ as wishlist_categories_advanced_addremove_title,
  _ as wishlist_categories_advanced_apply,
  _ as wishlist_categories_advanced_failed_items,
  _ as wishlist_categories_advanced_failed_items_Plural,
  _ as wishlist_categories_advanced_no_items,
  _ as wishlist_categories_advanced_pending,
  _ as wishlist_categories_advanced_pending_adds,
  _ as wishlist_categories_advanced_pending_removals,
  _ as wishlist_categories_advanced_rename_duplicate,
  _ as wishlist_categories_advanced_rename_failed,
  _ as wishlist_categories_advanced_rename_label,
  _ as wishlist_categories_advanced_rename_save,
  _ as wishlist_categories_advanced_revert,
  _ as wishlist_categories_advanced_select,
  _ as wishlist_categories_advanced_select_all,
  _ as wishlist_categories_advanced_select_none,
  _ as wishlist_categories_advanced_showing,
  _ as wishlist_categories_advanced_title,
  _ as wishlist_controls_categories_add,
  _ as wishlist_controls_categories_header_anonymous,
  _ as wishlist_controls_categories_multiselect_label,
  _ as wishlist_controls_demo_available,
  _ as wishlist_controls_demo_available_tooltip,
  _ as wishlist_controls_early_access_tooltip,
  _ as wishlist_controls_filter_tag_label,
  _ as wishlist_controls_options_category_category,
  _ as wishlist_controls_options_category_deck,
  _ as wishlist_controls_options_category_discount,
  _ as wishlist_controls_options_category_exclude,
  _ as wishlist_controls_options_category_platform,
  _ as wishlist_controls_options_category_price,
  _ as wishlist_controls_options_category_related,
  _ as wishlist_controls_options_category_tag,
  _ as wishlist_controls_options_category_type,
  _ as wishlist_controls_options_category_view,
  _ as wishlist_controls_options_deck_playable,
  _ as wishlist_controls_options_deck_verified,
  _ as wishlist_controls_options_discount_all,
  _ as wishlist_controls_options_discount_any,
  _ as wishlist_controls_options_discount_or_more,
  _ as wishlist_controls_options_exclude_vr,
  _ as wishlist_controls_options_platform_all,
  _ as wishlist_controls_options_platform_linux,
  _ as wishlist_controls_options_platform_mac,
  _ as wishlist_controls_options_price_any,
  _ as wishlist_controls_options_price_free,
  _ as wishlist_controls_options_price_max_price,
  _ as wishlist_controls_options_type_application,
  _ as wishlist_controls_options_type_dlc,
  _ as wishlist_controls_options_type_game,
  _ as wishlist_controls_options_type_video,
  _ as wishlist_controls_options_view_compact,
  _ as wishlist_controls_options_view_expanded,
  _ as wishlist_controls_share_description,
  _ as wishlist_controls_share_dialog_title,
  _ as wishlist_controls_share_generation_failure,
  _ as wishlist_controls_share_revokeall,
  _ as wishlist_controls_share_revokeall_success,
  _ as wishlist_controls_sortby_dateadded,
  _ as wishlist_controls_sortby_discount,
  _ as wishlist_controls_sortby_name,
  _ as wishlist_controls_sortby_order,
  _ as wishlist_controls_sortby_price,
  _ as wishlist_controls_sortby_releasedate,
  _ as wishlist_controls_sortby_reviews,
  _ as wishlist_controls_sortby_their_order,
  _ as wishlist_controls_sortby_topsellers,
  _ as wishlist_controls_tag_description,
  _ as wishlist_controls_tags_header,
  _ as wishlist_count,
  _ as wishlist_displayed_item_count,
  _ as wishlist_displayed_item_count_Plural,
  _ as wishlist_error_invalidsharetoken,
  _ as wishlist_error_profilenotfound,
  _ as wishlist_error_wishlistunavailable,
  _ as wishlist_errorpage_title,
  _ as wishlist_filter_matches_categories,
  _ as wishlist_filter_matches_categories_Plural,
  _ as wishlist_filter_matches_category,
  _ as wishlist_filter_matches_category_Plural,
  _ as wishlist_filter_matches_items,
  _ as wishlist_filter_matches_items_Plural,
  _ as wishlist_filter_matches_tag,
  _ as wishlist_filter_matches_tag_Plural,
  _ as wishlist_filter_matches_tags,
  _ as wishlist_filter_matches_tags_Plural,
  _ as wishlist_filter_results,
  _ as wishlist_filters_notification,
  _ as wishlist_gamepad_options,
  _ as wishlist_gamepad_options_remove,
  _ as wishlist_gamepad_visitstore,
  _ as wishlist_gamepaddragdrop_cancelreorder,
  _ as wishlist_gamepaddragdrop_commitreorder,
  _ as wishlist_gamepaddragdrop_reorderaction,
  _ as wishlist_header,
  _ as wishlist_item_add_credit_card,
  _ as wishlist_item_addedon_date,
  _ as wishlist_item_languagespecific_reviews,
  _ as wishlist_item_overallreviews,
  _ as wishlist_item_releasedate,
  _ as wishlist_item_remove,
  _ as wishlist_item_remove_tooltip,
  _ as wishlist_item_unavailable_region,
  _ as wishlist_item_unavailable_retired,
  _ as wishlist_item_unavailable_title,
  _ as wishlist_learn_more_button,
  _ as wishlist_no_items_matching_filters,
  _ as wishlist_options_button,
  _ as wishlist_others_wishlist_empty,
  _ as wishlist_search,
  _ as wishlist_search_all,
  _ as wishlist_share_tooltip,
  _ as wishlist_sign_in_to_see_your_wishlist,
  _ as wishlist_sortby_button,
  _ as wishlist_title,
  _ as wishlist_x_items_on_wishlist_but_none_match,
  _ as wishlist_x_items_on_wishlist_but_none_match_prefs,
  _ as wishlist_your_wishlist_empty,
  _ as youraccount_account,
  _ as youraccount_errorpage_title,
  _ as youraccount_users_account,
};
