var _ = `vietnamese`,
  _ = `Chơi miễn phí đến %1$s.`,
  _ = `Ưu đãi kết thúc vào %1$s.`,
  _ = `Chơi miễn phí!`,
  _ = `Miễn phí cuối tuần`,
  _ = `Chơi miễn phí đến thứ Hai lúc 10:00 giờ PT`,
  _ = `Chơi miễn phí đến %1$s`,
  _ = `Cả tuần miễn phí`,
  _ = `Vừa cập nhật`,
  _ = `THỜI GIAN CÓ HẠN`,
  _ = `Mua trước và chơi bản beta ngay!`,
  _ = `CHƠI BẢN BETA NGAY!`,
  _ = `Mua trước và truy cập bản beta`,
  _ = `Hiện đã hỗ trợ Steam Workshop`,
  _ = `Hiện đã có Steam Workshop`,
  _ = `Hiện đã có Steamworks`,
  _ = `Hiện đã có trên SteamOS!`,
  _ = `Hiện đã có trên SteamOS, Mac và Linux!`,
  _ = `Tải trước ngay`,
  _ = `Cập nhật miễn phí`,
  _ = `Chơi bản demo ngay!`,
  _ = `Tải trước (miễn phí)`,
  _ = `Tải trước miễn phí ngay`,
  _ = `Bạn đã tải trước xong`,
  _ = `Bạn đã hoàn tất việc tải trước`,
  _ = `Tải trước hoàn tất`,
  _ = `Mua trước ngay`,
  _ = `Vừa cập nhật với DLC miễn phí!`,
  _ = `Giờ đã có trên Mac và SteamOS!`,
  _ = `Sắp có mặt trên SteamOS!`,
  _ = `Tải và xem phim full HD`,
  _ = `Thêm vào danh sách ước`,
  _ = `Hiện đã có truy cập sớm`,
  _ = `trong Truy cập sớm`,
  _ = `Có cập nhật mới`,
  _ = `Miễn phí`,
  _ = `Mới phát hành`,
  _ = `Vừa được phát hành từ Truy cập sớm!`,
  _ = `Vừa phát hành`,
  _ = `Đã ra mắt`,
  _ = `Trò chơi mới`,
  _ = `Đã ra mắt - Chơi miễn phí`,
  _ = `Chơi miễn phí - Vừa cập nhật`,
  _ = `Nay chơi miễn phí trong mục Truy cập sớm`,
  _ = `Có gói truy cập ưu tiên`,
  _ = `Nội dung mới đã ra mắt`,
  _ = `Chơi miễn phí bản đầy đủ chỉ trong cuối tuần này`,
  _ = `Miễn phí cuối tuần - đã bắt đầu`,
  _ = `Chơi thử miễn phí bản đầy đủ`,
  _ = `Chơi ngay miễn phí`,
  _ = `Mua trước và nhận quà thưởng`,
  _ = `Bán chạy nhất`,
  _ = `Mới phát hành`,
  _ = `Ưu đãi cuối tuần`,
  _ = `Ưu đãi giữa tuần`,
  _ = `Ưu đãi giữa tuần`,
  _ = `Ưu đãi loạt sản phẩm`,
  _ = `Sự kiện bên thứ ba`,
  _ = `Cập nhật lớn`,
  _ = `Ưu đãi hằng ngày`,
  _ = `Ưu đãi suốt tuần`,
  _ = `Suốt tuần`,
  _ = `Tặng quà!`,
  _ = `Trong thời gian có hạn, cài đặt ngay và giữ mãi mãi`,
  _ = `Sắp ra mắt`,
  _ = `Mới và sắp tới`,
  _ = `Ưu đãi nổi bật`,
  _ = `Mục lục sản phẩm`,
  _ = `Cuối tuần cùng nhà phát hành`,
  _ = `Ưu đãi từ nhà phát hành`,
  _ = `Cài đặt`,
  _ = `TRI ÂN KHÁCH HÀNG! Ưu đãi kết thúc trong %1$s`,
  _ = `Nhấp để xem chi tiết`,
  _ = `Chơi Ngay`,
  _ = `Chơi ngay`,
  _ = `Hốt nhanh`,
  _ = `Nhấp để xem chi tiết`,
  _ = `Hiện đang ưu đãi!`,
  _ = `Truy cập beta sớm`,
  _ = `Ra mắt DLC mới`,
  _ = `Tải trước ngay`,
  _ = `Giảm giá sâu nhất`,
  _ = `Ưu đãi có thời hạn`,
  _ = `Ưu đãi có thời hạn`,
  _ = `Đã ra mắt`,
  _ = `Đã ra mắt`,
  _ = `Đã có mặt trên Mac`,
  _ = `Đã có mặt trên PC, Mac và Linux!`,
  _ = `Nay chơi miễn phí`,
  _ = `Trò chơi miễn phí mới`,
  _ = `Đã có bản DLC miễn phí`,
  _ = `Hành động & bắn súng góc nhìn thứ nhất`,
  _ = `Hành động & bắn súng góc nhìn thứ nhất`,
  _ = `Hành động 2D`,
  _ = `Hành động 2D`,
  _ = `Hành động & bắn súng góc nhìn thứ ba`,
  _ = `Hành động & bắn súng góc nhìn thứ nhất`,
  _ = `Hành động`,
  _ = `Hành động`,
  _ = `Hành động-Phiêu lưu`,
  _ = `Hành động-Phiêu lưu`,
  _ = `Hành động & Phiêu lưu`,
  _ = `Hành động & Phiêu lưu`,
  _ = `Bắn súng góc nhìn thứ nhất`,
  _ = `Bắn súng góc nhìn thứ nhất`,
  _ = `Hành động kinh dị`,
  _ = `Hành động kinh dị`,
  _ = `Hành động rogue-like`,
  _ = `Hành động rogue-like`,
  _ = `Hành động nhập vai`,
  _ = `Hành động nhập vai`,
  _ = `Platformer & Rượt đuổi`,
  _ = `Platformer & Rượt đuổi`,
  _ = `Bắn súng`,
  _ = `Bắn súng`,
  _ = `Bắn súng góc nhìn thứ ba`,
  _ = `Bắn súng góc nhìn thứ ba`,
  _ = `Hành động & Hoạt động`,
  _ = `Hành động & Hoạt động`,
  _ = `Phiêu lưu`,
  _ = `Phiêu lưu`,
  _ = `Phiêu lưu & Đơn giản`,
  _ = `Phiêu lưu & Đơn giản`,
  _ = `Thế giới mở`,
  _ = `Thế giới mở`,
  _ = `Phiêu lưu trỏ và nhấp`,
  _ = `Phiêu lưu trỏ và nhấp`,
  _ = `Nhập vai phiêu lưu`,
  _ = `Nhập vai phiêu lưu`,
  _ = `Nhập vai đơn giản`,
  _ = `Nhập vai đơn giản`,
  _ = `Mãn nhãn`,
  _ = `Chủ đề`,
  _ = `Anime`,
  _ = `Anime`,
  _ = `Arcade`,
  _ = `Arcade`,
  _ = `Arcade & Nhịp điệu`,
  _ = `Arcade & Nhịp điệu`,
  _ = `Phong cách nghệ thuật & Âm nhạc`,
  _ = `Phong cách nghệ thuật & Âm nhạc`,
  _ = `Beat 'Em Up`,
  _ = `Beat 'Em Up`,
  _ = `Kinh doanh & Chính trị`,
  _ = `Kinh doanh & Chính trị`,
  _ = `Đơn giản`,
  _ = `Đơn giản`,
  _ = `Bài bàn đơn giản`,
  _ = `Bài bàn đơn giản`,
  _ = `Đơn giản & Giải đố`,
  _ = `Đơn giản & Giải đố`,
  _ = `Đơn giản & Cốt truyện`,
  _ = `Đơn giản & Cốt truyện`,
  _ = `Đơn giản giải đố`,
  _ = `Đơn giản giải đố`,
  _ = `Trò chơi hành động nhân vật`,
  _ = `Nhấp chuột & Treo máy`,
  _ = `Nhấp chuột & Treo máy`,
  _ = `Tội ác & Công lý`,
  _ = `Tội ác & Công lý`,
  _ = `Hoạt hình & dễ thương`,
  _ = `Hoạt hình & dễ thương`,
  _ = `Mô phỏng hẹn hò`,
  _ = `Mô phỏng hẹn hò`,
  _ = `Lái xe & máy bay`,
  _ = `Lái xe & máy bay`,
  _ = `Khoa học & Giáo dục`,
  _ = `Khoa học & Giáo dục`,
  _ = `Thử nghiệm`,
  _ = `Thử nghiệm`,
  _ = `Thế giới mở`,
  _ = `Thế giới mở`,
  _ = `Kỳ ảo`,
  _ = `Kỳ ảo`,
  _ = `Kỳ ảo & Siêu nhiên`,
  _ = `Kỳ ảo & Siêu nhiên`,
  _ = `Đối kháng`,
  _ = `Đối kháng`,
  _ = `Đối kháng & Võ thuật`,
  _ = `Đối kháng & Võ thuật`,
  _ = `Chơi miễn phí`,
  _ = `Chặt chém`,
  _ = `Tìm đồ vật`,
  _ = `Tìm đồ vật`,
  _ = `Lịch sử`,
  _ = `Kinh dị`,
  _ = `Kinh dị`,
  _ = `Đen tối & Kinh dị`,
  _ = `Đen tối & Kinh dị`,
  _ = `Lễ hội Steam Gào Rú`,
  _ = `Lễ hội xây thành`,
  _ = `Lén lút`,
  _ = `shmup`,
  _ = `Giàu cốt truyện`,
  _ = `Giàu cốt truyện`,
  _ = `Interactive Stories`,
  _ = `Cốt truyện tương tác`,
  _ = `Mô phỏng đời sống`,
  _ = `Địa điểm & Thế giới`,
  _ = `Khớp 3 cái`,
  _ = `Nối 3 điểm`,
  _ = `Nhiều người`,
  _ = `Nhiều người`,
  _ = `Quân đội & Chiến tranh`,
  _ = `Quân đội & Chiến tranh`,
  _ = `Tối giản & Trừu tượng`,
  _ = `Tối giản & trừu tượng`,
  _ = `Nhiều người`,
  _ = `Nhiều người`,
  _ = `Thi đấu nhiều người`,
  _ = `Thi đấu`,
  _ = `Đấu trường sinh tử`,
  _ = `Battle Royale`,
  _ = `Phối hợp`,
  _ = `Phối hợp`,
  _ = `Mạng nội bộ`,
  _ = `Mạng nội bộ`,
  _ = `Nhiều người cục bộ & Hội nhóm`,
  _ = `Cục bộ & Hội nhóm`,
  _ = `Trực tuyến nhiều người chơi`,
  _ = `MMO`,
  _ = `MOBA & Auto-Battler`,
  _ = `MOBA & Auto-Battler`,
  _ = `Thi đấu trực tuyến`,
  _ = `Thi đấu trực tuyến`,
  _ = `Bắn súng nhiều người chơi`,
  _ = `Bắn súng`,
  _ = `Âm nhạc & Nhịp điệu`,
  _ = `Âm nhạc & Nhịp điệu`,
  _ = `Chế tác sinh tồn thế giới mở`,
  _ = `Chế tác sinh tồn thế giới mở`,
  _ = `Loài người & Sinh vật`,
  _ = `Người chơi`,
  _ = `Ảo giác`,
  _ = `Ảo giác`,
  _ = `Ảo giác & Siêu thực`,
  _ = `Ảo giác & Siêu thực`,
  _ = `Giải đố`,
  _ = `Giải đố`,
  _ = `Giải đố`,
  _ = `Giải đố`,
  _ = `Giải đố khó`,
  _ = `Giải đố khó`,
  _ = `Giải đố logic`,
  _ = `Giải đố logic`,
  _ = `Giải đố nhiều người`,
  _ = `Giải đố nhiều người`,
  _ = `Đua tốc độ`,
  _ = `Đua ô tô, xe đạp, trượt tuyết và nhiều nữa`,
  _ = `Đua tốc độ`,
  _ = `Mô phỏng đua xe`,
  _ = `Mô phỏng đua xe`,
  _ = `Đua tốc độ giao chiến`,
  _ = `Đua tốc độ giao chiến`,
  _ = `Đua tốc độ & Lái máy bay`,
  _ = `Đua tốc độ & Lái máy bay`,
  _ = `Retro`,
  _ = `Retro`,
  _ = `Thư giãn`,
  _ = `Thư giãn`,
  _ = `Metroidvania`,
  _ = `Metroidvania`,
  _ = `Tối giản & Thư giãn`,
  _ = `Nhẹ nhàng & thư giãn`,
  _ = `Rogue-Like theo lượt`,
  _ = `Rogue-Like theo lượt`,
  _ = `Rogue-Like & Rogue-Lite`,
  _ = `Rogue-Like`,
  _ = `Rogue-Like`,
  _ = `Rogue-Like`,
  _ = `Nhập vai`,
  _ = `Nhập vai`,
  _ = `Hành động nhập vai`,
  _ = `Hành động nhập vai`,
  _ = `Nhập vai cổ điển`,
  _ = `Nhập vai cổ điển (CRPG)`,
  _ = `Nhập vai cổ điển`,
  _ = `Nhập vai cổ điển (CRPG)`,
  _ = `Cày hầm ngục`,
  _ = `Cày hầm ngục`,
  _ = `Nhập vai Nhật Bản`,
  _ = `JRPG`,
  _ = `Nhập vai trực tuyến nhiều người`,
  _ = `MMORPG`,
  _ = `Nhập vai tổ đội`,
  _ = `Tổ đội`,
  _ = `Nhập vai giàu cốt truyện`,
  _ = `Giàu cốt truyện`,
  _ = `Nhập vai chiến thuật & chiến lược`,
  _ = `Nhập vai chiến thuật`,
  _ = `Nhập vai theo lượt`,
  _ = `Theo lượt`,
  _ = `Khoa học viễn tưởng & Cyberpunk`,
  _ = `Khoa học viễn tưởng & Cyberpunk`,
  _ = `Bắn súng`,
  _ = `Bắn súng`,
  _ = `Mô phỏng xây dựng`,
  _ = `Xây dựng`,
  _ = `Mô phỏng xây dựng & tự động hóa`,
  _ = `Xây dựng & Tự động hóa`,
  _ = `Kinh doanh & Tycoon`,
  _ = `Kinh doanh & Tycoon`,
  _ = `Mô phỏng thành phố & lập cư`,
  _ = `Thành phố & Lập cư`,
  _ = `Mô phỏng nông trại`,
  _ = `Nông trại`,
  _ = `Mô phỏng nông trại & chế tác`,
  _ = `Nông trại & Chế tác`,
  _ = `Mô phỏng chân thực & đời sống`,
  _ = `Chân thực & Đời sống`,
  _ = `Mô phỏng đời sống & lãng mạn`,
  _ = `Đời sống & Lãng mạn`,
  _ = `Mô phỏng & Quản lý`,
  _ = `Mô phỏng & Quản lý`,
  _ = `Mô phỏng thế giới mở`,
  _ = `Thế giới mở`,
  _ = `Mô phỏng vật lý & Sandbox`,
  _ = `Vật lý & Sandbox`,
  _ = `Mô phỏng chính sách`,
  _ = `Chính sách`,
  _ = `Mô phỏng Sandbox & Làm đấng sáng tạo`,
  _ = `Sandbox & Làm đấng sáng tạo`,
  _ = `Mô phỏng vũ trụ & bay lượn`,
  _ = `Vũ trụ & Bay lượn`,
  _ = `Mô phỏng hẹn hò`,
  _ = `Hẹn hò`,
  _ = `Mô phỏng`,
  _ = `Mô phỏng`,
  _ = `Chơi đơn`,
  _ = `Chơi đơn`,
  _ = `Hỗ trợ người chơi`,
  _ = `Thể thao`,
  _ = `Quản lý đội tuyển, tập luyện cho giải đấu lớn, hoặc đơn giản là chơi thôi`,
  _ = `Thể thao`,
  _ = `Thể thao & Đua tốc độ`,
  _ = `Thể thao & Đua tốc độ`,
  _ = `Thể thao dùng banh`,
  _ = `Thể thao dùng banh`,
  _ = `Thể thao đối kháng`,
  _ = `Đối kháng thể thao`,
  _ = `Câu cá & Săn bắn`,
  _ = `Câu cá & Săn bắn`,
  _ = `Thể thao cá nhân`,
  _ = `Thể thao cá nhân`,
  _ = `Mô phỏng & quản lý thể thao`,
  _ = `Mô phỏng thể thao`,
  _ = `Thể thao đồng đội`,
  _ = `Thể thao đồng đội`,
  _ = `Thể thao mùa đông`,
  _ = `Thể thao mùa đông`,
  _ = `Ma quái`,
  _ = `Ma quái`,
  _ = `Giàu cốt truyện`,
  _ = `Giàu cốt truyện`,
  _ = `Chiến thuật`,
  _ = `Chiến thuật`,
  _ = `Bài & Bàn`,
  _ = `Bài & Bàn`,
  _ = `Xây thành phố & Lập cư`,
  _ = `Thành phố & Lập cư`,
  _ = `Chiến thuật vĩ mô & 4X`,
  _ = `Vĩ mô & 4X`,
  _ = `Chiến thuật quân đội`,
  _ = `Quân đội`,
  _ = `MOBA & Auto-Battler`,
  _ = `MOBA & Auto-Battler`,
  _ = `Chiến thuật thời gian thực (RTS)`,
  _ = `Chiến thuật thời gian thực (RTS)`,
  _ = `Mô phỏng & Quản lý`,
  _ = `Mô phỏng & Quản lý`,
  _ = `Chiến thuật & Chiến lược`,
  _ = `Chiến thuật & Chiến lược`,
  _ = `Chiến thuật theo lượt`,
  _ = `Chiến lược theo lượt`,
  _ = `Sinh tồn`,
  _ = `Sinh tồn`,
  _ = `Sinh tồn & Lén lút`,
  _ = `Sinh tồn & Lén lút`,
  _ = `Chủ đề`,
  _ = `Chủ đề`,
  _ = `Chủ đề & Sở thích`,
  _ = `Chủ đề`,
  _ = `Quản lý thời gian`,
  _ = `Quản lý thời gian`,
  _ = `Thủ thành`,
  _ = `Thủ thành`,
  _ = `Visual Novel`,
  _ = `Visual Novel`,
  _ = `Nhiều cảnh đi bộ`,
  _ = `Nhiều cảnh đi bộ`,
  _ = `Vũ trụ`,
  _ = `Vũ trụ`,
  _ = `Nữ chính`,
  _ = `Nữ chính`,
  _ = `LGBTQ+`,
  _ = `LGBTQ+`,
  _ = `Pixel & Retro`,
  _ = `Pixel & Retro`,
  _ = `Lựa chọn phân nhánh & Dựa theo cốt truyện`,
  _ = `Lựa chọn phân nhánh`,
  _ = `Bí ẩn & Trinh thám`,
  _ = `Bí ẩn & Trinh thám`,
  _ = `Mô phỏng thú vui & nghề nghiệp`,
  _ = `Thú vui & Nghề nghiệp`,
  _ = `Going Rogue`,
  _ = `Tuyệt trên Deck`,
  _ = `Tuyệt trên Frame`,
  _ = `Kinh tế & Tư bản`,
  _ = `Cướp biển chọi Ninja`,
  _ = `Khủng long đấu Robot`,
  _ = `Chơi đi chơi lại`,
  _ = `Khám phá không gian`,
  _ = `Xây dựng bộ bài`,
  _ = `Nhập vai theo lượt`,
  _ = `Nấu nướng`,
  _ = `Máy bay, tàu hỏa, ô tô`,
  _ = `Câu cá`,
  _ = `Thả cần câu để thi đấu hoặc thư giãn`,
  _ = `Treo máy`,
  _ = `Nhịp điệu`,
  _ = `Sokoban`,
  _ = `Đẩy thùng theo đúng thứ tự`,
  _ = `Nông trại`,
  _ = `Tái hiện chiến tranh`,
  _ = `Sưu tầm sinh vật`,
  _ = `Zombie chiến ma cà rồng`,
  _ = `Đẩy thùng`,
  _ = `Tự động hóa`,
  _ = `Chiến thuật 4X`,
  _ = `eXplore - Thăm dò, eXpand - Mở rộng, eXploit - Khai thác, và eXterminate - Triệt tiêu`,
  _ = `Mô phỏng chính trị`,
  _ = `Động vật`,
  _ = `Trinh thám`,
  _ = `Ghép nối manh mối và giải quyết vụ án`,
  _ = `Trên bàn`,
  _ = `Đánh máy`,
  _ = `Bạn có thể gõ siêu nhanh mà không sai chữ nào không?`,
  _ = `Giao chiến PvP`,
  _ = `Ngựa`,
  _ = `Cưỡi, đua, và nuôi ngựa, lừa, ngựa con, kỳ lân, v.v.`,
  _ = `Trung cổ`,
  _ = `Nhà cửa`,
  _ = `Đại dương`,
  _ = `Hentai`,
  _ = `Mang yếu tố trưởng thành`,
  _ = `Mưa đạn`,
  _ = `Khéo léo né các làn đạn từ kẻ địch hoặc tự tay khai hỏa liên hồi. Dù thế nào đi nữa, hãy chuẩn bị đối phó khung cảnh hỗn loạn`,
  _ = `Kiểu ma sói`,
  _ = `Quan sát, điều tra, lừa gạt, và gian dối để truy ra kẻ phản bội và suy đoán thông tin mật trước khi hết giờ`,
  _ = `Tàu hỏa và tàu điện`,
  _ = `Lắp đường ray, lên lộ trình, hoặc điều khiển đầu tàu qua thành phố và ngoại ô`,
  _ = `Cyberpunk`,
  _ = `Đủ loại công nghệ cao, lấy bối cảnh tương lai khoa học viễn tưởng phản địa đàng`,
  _ = `Cọc và chốt`,
  _ = `Bắn bóng nảy qua lại giữa các cọc chốt và đánh đổ ki`,
  _ = `Chế tác sinh tồn PvE`,
  _ = `Thu thập và chế tác để sinh tồn trước các yếu tố môi trường`,
  _ = `Lập trình`,
  _ = `Viết câu lệnh, hack, và giải các câu đố logic phức tạp`,
  _ = `Nhập vai tổ đội`,
  _ = `Kiếm trang bị và lên cấp cùng với tổ đội của mình`,
  _ = `Kỳ ảo & Siêu nhiên`,
  _ = `Bắn súng không zombie`,
  _ = `Giải đố động vật thư giãn`,
  _ = `Mới & Đáng chú ý`,
  _ = `Giảm giá & sự kiện`,
  _ = `Độ khó có thể điều chỉnh`,
  _ = `Có nhiều cách để điều chỉnh độ khó cho những trò chơi này.`,
  _ = `Lưu bất cứ lúc nào`,
  _ = `Những trò chơi này cho phép bạn tự tay lưu lại tiến trình gần như mọi lúc.`,
  _ = `Kích thước chữ có thể điều chỉnh`,
  _ = `Bạn có thể điều chỉnh kích thước chữ và tỉ lệ giao diện trong những trò chơi này để chữ hoặc các chi tiết trông to hơn hoặc nhỏ hơn.`,
  _ = `Tùy chọn phụ đề`,
  _ = `Bạn có thể điều chỉnh cách phụ đề hiển thị, như font chữ, màu sắc, và độ mờ nền.`,
  _ = `Lựa chọn màu thay thế`,
  _ = `Lối chơi không dựa trên màu sắc để truyền đạt những thông tin quan trọng, hoặc bạn có thể thay đổi màu sắc đang dùng.`,
  _ = `Độ thoải mái camera`,
  _ = `Những trò chơi này cho phép điều chỉnh hoặc tắt chuyển động camera gây khó chịu (như rung màn hình, lắc lư camera, hoặc nhòe mờ khi chuyển động), hoặc không có các hiệu ứng trên.`,
  _ = `Điều khiển âm lượng tùy chỉnh`,
  _ = `Những trò chơi này cho phép bạn điều chỉnh âm lượng riêng biệt của các loại âm thanh khác nhau trong trò chơi (như nhạc nền, hiệu ứng âm thanh, hoặc giọng nói).`,
  _ = `Âm thanh stereo`,
  _ = `Những trò chơi này cho phép bạn dùng âm thanh stereo để nhận biết âm thanh phát ra từ bên trái hoặc phải bao xa.`,
  _ = `Âm thanh vòm`,
  _ = `Những trò chơi này cho phép bạn dùng âm thanh vòm để nhận biết âm thanh phát ra từ mọi hướng ở khoảng cách xa bao nhiêu.`,
  _ = `Menu trò chơi có tường thuật`,
  _ = `Những trò chơi này hỗ trợ phần mềm đọc màn hình hoặc menu có tường thuật, để có thể dùng và hiểu menu mà không cần nhìn thấy văn bản.`,
  _ = `Chơi được không cần QTE`,
  _ = `Những trò chơi này cho phép bạn tránh chuỗi hành động yêu cầu nhập chính xác thời điểm (QTE) hoặc nhấn nút liên tục.`,
  _ = `Tùy chọn chỉ sử dụng bàn phím`,
  _ = `Có thể chơi những trò này chỉ với một bàn phím, hoặc một công cụ tiếp cận giúp gán nút vào tín hiệu nhập của bàn phím.`,
  _ = `Tùy chọn chỉ sử dụng chuột`,
  _ = `Có thể chơi những trò này chỉ với một con chuột, hoặc một công cụ tiếp cận giúp gán nút vào tín hiệu nhập của chuột.`,
  _ = `Tùy chọn chỉ sử dụng cảm ứng`,
  _ = `Có thể chơi những trò này chỉ với điều khiển cảm ứng, hoặc một công cụ tiếp cận giúp gán nút vào tín hiệu nhập của điều khiển cảm ứng.`,
  _ = `Trò chuyện — Chuyển giọng nói thành văn bản`,
  _ = `Những trò chơi này cho phép trò chuyện bằng giọng nói được đọc dưới dạng văn bản trong thời gian thực.`,
  _ = `Trò chuyện — Chuyển văn bản thành giọng nói`,
  _ = `Những trò chơi này cho phép trò chuyện bằng văn bản được tường thuật thành tiếng trong thời gian thực.`,
  _ = `Chơi được theo nhịp độ riêng`,
  _ = `Trò chơi cho bạn thoải mái suy nghĩ giữa mỗi lần nhập đầu vào.`,
  _ = `Chơi được không cần nhìn`,
  _ = `Có thể thưởng thức trò chơi mà không cần nhìn màn hình.`,
  _ = `Điều khiển độ tương phản`,
  _ = `Trò chơi cho phép điều chỉnh độ tương phản phù hợp với sở thích của bạn.`,
  _ = `Dành cho người lớn`,
  _ = `Demo`,
  _ = `Chơi miễn phí`,
  _ = `Truy cập sớm`,
  _ = `Tuyệt trên Deck`,
  _ = `Tuyệt trên Frame`,
  _ = `Thân thiện với tay cầm`,
  _ = `Remote Play`,
  _ = `Trò chơi VR`,
  _ = `Thiết bị VR`,
  _ = `Phần mềm`,
  _ = `Nhạc`,
  _ = `macOS`,
  _ = `SteamOS + Linux`,
  _ = `Cho phòng máy`,
  _ = `Thử ngay`,
  _ = `Thử ngay`,
  _ = `dummy`,
  _ = {
    language: _,
    label_play_free_until_custom: _,
    promo_ends_custom: _,
    label_play_free_generic: _,
    label_free_weekend: _,
    msg_free_play_weekend: _,
    msg_free_play_until: _,
    label_free_week: _,
    label_just_updated: _,
    label_for_a_limited_time_only: _,
    msg_prepurchase_and_play_beta_now: _,
    msg_play_beta_now: _,
    msg_prepurchase_and_get_beta_access: _,
    msg_steam_workshop_now_available: _,
    msg_now_with_steam_workshop: _,
    msg_now_with_steamworks: _,
    msg_now_available_on_steamos: _,
    msg_now_available_on_steamos_mac_and_linux: _,
    msg_preload_now: _,
    msg_free_update: _,
    msg_play_demo_now: _,
    msg_preload_free: _,
    msg_preload_now_for_free: _,
    msg_preload_you_have_pre: _,
    msg_preload_you_have_completed: _,
    msg_preload_completed: _,
    msg_prepurchase_now: _,
    msg_just_updated_with_free_dlc: _,
    msg_now_available_for_mac_and_steamos: _,
    msg_coming_soon_to_steamos: _,
    msg_watch_movie_now: _,
    btn_add_to_wishlist: _,
    msg_early_access_now_available: _,
    msg_in_early_access: _,
    msg_new_update_available: _,
    browse_free: _,
    msg_available_new_release: _,
    msg_available_just_released_from_early_access: _,
    msg_available_just_released: _,
    msg_available_everywhere: _,
    msg_new_game: _,
    msg_available_now_free_to_play: _,
    msg_free_to_play_just_updated: _,
    msg_available_now_ftp_early: _,
    msg_advanced_access: _,
    msg_new_content_now_available: _,
    mst_weekend_description_free: _,
    msg_weekend_on_now: _,
    msg_weekend_trial: _,
    msg_weekend_play_free: _,
    msg_prepurchase_bonus: _,
    api_category_top_sellers: _,
    api_category_new_releases: _,
    spotlight_weekend_deal: _,
    spotlight_midweek_madness: _,
    spotlight_midweek_deal: _,
    spotlight_franchise_sale: _,
    spotlight_thirdparty_event: _,
    spotlight_major_update: _,
    spotlight_daily_deal: _,
    spotlight_weeklong_sale: _,
    spotlight_weeklong_header1: _,
    promo_giveaway: _,
    limitedtime_install_and_keep: _,
    api_category_coming_soon: _,
    label_new_and_upcoming: _,
    label_highlighted_deals: _,
    label_back_catalogue: _,
    msg_publisher_weekend: _,
    msg_publisher_sale: _,
    Library_Install: _,
    discount_desc_preset_loyalty: _,
    msg_action_details: _,
    msg_play_now: _,
    msg_play_it_now: _,
    msg_action_buy: _,
    msg_action_info: _,
    msg_on_sale_now: _,
    label_early_beta_access: _,
    label_new_dlc_available: _,
    label_pre_load_now: _,
    label_deepest_discount: _,
    discount_desc_limited_time: _,
    discount_desc_limited_time_date: _,
    text_now_available: _,
    text_now_available_steamplay: _,
    text_now_available_mac: _,
    text_now_available_on_pc_mac_and_linux: _,
    text_now_free_to_play: _,
    text_new_free_to_play: _,
    text_free_new_dlc_now_available: _,
    ContentHubby_Hub_1st_person_action_shooting: _,
    ContentHubby_Hub_1st_person_action_shooting_menu: _,
    ContentHubby_Hub_2d_view_action: _,
    ContentHubby_Hub_2d_view_action_menu: _,
    ContentHubby_Hub_3rd_person_action_shooting: _,
    ContentHubby_Hub_3rd_person_action_shooting_menu: _,
    ContentHubby_Hub_action: _,
    ContentHubby_Hub_action_menu: _,
    ContentHubby_Hub_action_dash_adventure: _,
    ContentHubby_Hub_action_dash_adventure_menu: _,
    ContentHubby_Hub_action_and_adventure: _,
    ContentHubby_Hub_action_and_adventure_menu: _,
    ContentHubby_Hub_action_fps: _,
    ContentHubby_Hub_action_fps_menu: _,
    ContentHubby_Hub_action_horror: _,
    ContentHubby_Hub_action_horror_menu: _,
    ContentHubby_Hub_action_rogue_like: _,
    ContentHubby_Hub_action_rogue_like_menu: _,
    ContentHubby_Hub_action_rpg: _,
    ContentHubby_Hub_action_rpg_menu: _,
    ContentHubby_Hub_action_run_jump: _,
    ContentHubby_Hub_action_run_jump_menu: _,
    ContentHubby_Hub_action_shooter: _,
    ContentHubby_Hub_action_shooter_menu: _,
    ContentHubby_Hub_action_tps: _,
    ContentHubby_Hub_action_tps_menu: _,
    ContentHubby_Hub_actions_activities: _,
    ContentHubby_Hub_actions_activities_menu: _,
    ContentHubby_Hub_adventure: _,
    ContentHubby_Hub_adventure_menu: _,
    ContentHubby_Hub_adventure_and_casual: _,
    ContentHubby_Hub_adventure_and_casual_menu: _,
    ContentHubby_Hub_adventure_explore_open_world: _,
    ContentHubby_Hub_adventure_explore_open_world_menu: _,
    ContentHubby_Hub_adventure_point_click: _,
    ContentHubby_Hub_adventure_point_click_menu: _,
    ContentHubby_Hub_adventure_rpg: _,
    ContentHubby_Hub_adventure_rpg_menu: _,
    ContentHubby_Hub_adventure_rpg_casual: _,
    ContentHubby_Hub_adventure_rpg_casual_menu: _,
    ContentHubby_Hub_aesthetic: _,
    ContentHubby_Hub_aesthetic_menu: _,
    ContentHubby_Hub_anime_mild: _,
    ContentHubby_Hub_anime_mild_menu: _,
    ContentHubby_Hub_arcade: _,
    ContentHubby_Hub_arcade_menu: _,
    ContentHubby_Hub_arcade_rhythm: _,
    ContentHubby_Hub_arcade_rhythm_menu: _,
    ContentHubby_Hub_artstyles_music: _,
    ContentHubby_Hub_artstyles_music_menu: _,
    ContentHubby_Hub_action_beat_em_up: _,
    ContentHubby_Hub_action_beat_em_up_menu: _,
    ContentHubby_Hub_business_politics: _,
    ContentHubby_Hub_business_politics_menu: _,
    ContentHubby_Hub_casual: _,
    ContentHubby_Hub_casual_menu: _,
    ContentHubby_Hub_casual_card_board: _,
    ContentHubby_Hub_casual_card_board_menu: _,
    ContentHubby_Hub_casual_and_puzzle: _,
    ContentHubby_Hub_casual_and_puzzle_menu: _,
    ContentHubby_Hub_casual_and_story: _,
    ContentHubby_Hub_casual_and_story_menu: _,
    ContentHubby_Hub_casual_puzzle: _,
    ContentHubby_Hub_casual_puzzle_menu: _,
    ContentHubby_Hub_character_action_game: _,
    ContentHubby_Hub_clickers_idlers: _,
    ContentHubby_Hub_clickers_idlers_menu: _,
    ContentHubby_Hub_crime_justice: _,
    ContentHubby_Hub_crime_justice_menu: _,
    ContentHubby_Hub_cute_cartoon: _,
    ContentHubby_Hub_cute_cartoon_menu: _,
    ContentHubby_Hub_dating_sim: _,
    ContentHubby_Hub_dating_sim_menu: _,
    ContentHubby_Hub_driving_piloting: _,
    ContentHubby_Hub_driving_piloting_menu: _,
    ContentHubby_Hub_education: _,
    ContentHubby_Hub_education_menu: _,
    ContentHubby_Hub_experimental: _,
    ContentHubby_Hub_experimental_menu: _,
    ContentHubby_Hub_exploration_open_world: _,
    ContentHubby_Hub_exploration_open_world_menu: _,
    ContentHubby_Hub_fantasy: _,
    ContentHubby_Hub_fantasy_menu: _,
    ContentHubby_Hub_fantasy_supernatural: _,
    ContentHubby_Hub_fantasy_supernatural_menu: _,
    ContentHubby_Hub_fighting: _,
    ContentHubby_Hub_fighting_menu: _,
    ContentHubby_Hub_fighting_martial_arts: _,
    ContentHubby_Hub_fighting_martial_arts_menu: _,
    ContentHubby_Hub_free_to_play: _,
    ContentHubby_Hub_hack_and_slash: _,
    ContentHubby_Hub_hidden_object_menu: _,
    ContentHubby_Hub_hidden_object: _,
    ContentHubby_Hub_history: _,
    ContentHubby_Hub_horror: _,
    ContentHubby_Hub_horror_menu: _,
    ContentHubby_Hub_horror_dark: _,
    ContentHubby_Hub_horror_dark_menu: _,
    ContentHubby_Hub_scream: _,
    ContentHubby_Hub_base_builder: _,
    ContentHubby_Hub_stealth: _,
    ContentHubby_Hub_shmup: _,
    ContentHubby_Hub_interactive_fiction: _,
    ContentHubby_Hub_interactive_fiction_menu: _,
    ContentHubby_Hub_interactive_stories: _,
    ContentHubby_Hub_interactive_stories_menu: _,
    ContentHubby_Hub_life_sim: _,
    ContentHubby_Hub_location_worlds: _,
    ContentHubby_Hub_match_3: _,
    ContentHubby_Hub_match_3_menu: _,
    ContentHubby_Hub_military: _,
    ContentHubby_Hub_military_menu: _,
    ContentHubby_Hub_military_warfare: _,
    ContentHubby_Hub_military_warfare_menu: _,
    ContentHubby_Hub_minimalist_abstract: _,
    ContentHubby_Hub_minimalist_abstract_menu: _,
    ContentHubby_Hub_multiplayer: _,
    ContentHubby_Hub_multiplayer_menu: _,
    ContentHubby_Hub_multiplayer_competitive: _,
    ContentHubby_Hub_multiplayer_competitive_menu: _,
    ContentHubby_Hub_multiplayer_battle_royale: _,
    ContentHubby_Hub_multiplayer_battle_royale_menu: _,
    ContentHubby_Hub_multiplayer_coop: _,
    ContentHubby_Hub_multiplayer_coop_menu: _,
    ContentHubby_Hub_multiplayer_lan: _,
    ContentHubby_Hub_multiplayer_lan_menu: _,
    ContentHubby_Hub_multiplayer_local_party: _,
    ContentHubby_Hub_multiplayer_local_party_menu: _,
    ContentHubby_Hub_multiplayer_mmo: _,
    ContentHubby_Hub_multiplayer_mmo_menu: `MMO`,
    ContentHubby_Hub_multiplayer_moba_auto_battler: _,
    ContentHubby_Hub_multiplayer_moba_auto_battler_menu: _,
    ContentHubby_Hub_multiplayer_online_competitive: _,
    ContentHubby_Hub_multiplayer_online_competitive_menu: _,
    ContentHubby_Hub_multiplayer_shooter: _,
    ContentHubby_Hub_multiplayer_shooter_menu: _,
    ContentHubby_Hub_music_rhythm: _,
    ContentHubby_Hub_music_rhythm_menu: _,
    ContentHubby_Hub_open_world_survival_craft: _,
    ContentHubby_Hub_open_world_survival_craft_menu: _,
    ContentHubby_Hub_people_creatures: _,
    ContentHubby_Hub_players: _,
    ContentHubby_Hub_psychedelic: _,
    ContentHubby_Hub_psychedelic_menu: _,
    ContentHubby_Hub_psychedelic_surreal: _,
    ContentHubby_Hub_psychedelic_surreal_menu: _,
    ContentHubby_Hub_puzzle: _,
    ContentHubby_Hub_puzzle_menu: _,
    ContentHubby_Hub_puzzle_matching: _,
    ContentHubby_Hub_puzzle_matching_menu: _,
    ContentHubby_Hub_puzzle_difficult: _,
    ContentHubby_Hub_puzzle_difficult_menu: _,
    ContentHubby_Hub_puzzle_logic: _,
    ContentHubby_Hub_puzzle_logic_menu: _,
    ContentHubby_Hub_puzzle_multiplayer: _,
    ContentHubby_Hub_puzzle_multiplayer_menu: _,
    ContentHubby_Hub_racing: _,
    ContentHubby_Hub_racing_desc: _,
    ContentHubby_Hub_racing_menu: _,
    ContentHubby_Hub_racing_sim: _,
    ContentHubby_Hub_racing_sim_menu: _,
    ContentHubby_Hub_racing_combat: _,
    ContentHubby_Hub_racing_combat_menu: _,
    ContentHubby_Hub_racing_piloting: _,
    ContentHubby_Hub_racing_piloting_menu: _,
    ContentHubby_Hub_retro: _,
    ContentHubby_Hub_retro_menu: _,
    ContentHubby_Hub_relaxing: _,
    ContentHubby_Hub_relaxing_menu: _,
    ContentHubby_Hub_metroidvania: _,
    ContentHubby_Hub_metroidvania_menu: _,
    ContentHubby_Hub_minimalist_relaxing: _,
    ContentHubby_Hub_minimalist_relaxing_menu: _,
    ContentHubby_Hub_rogue_like_turn_based: _,
    ContentHubby_Hub_rogue_like_turn_based_menu: _,
    ContentHubby_Hub_rogue_like_rogue_lite: _,
    ContentHubby_Hub_rogue_like_rogue_lite_menu: _,
    ContentHubby_Hub_rogue_like: _,
    ContentHubby_Hub_rogue_like_menu: _,
    ContentHubby_Hub_rpg: _,
    ContentHubby_Hub_rpg_menu: _,
    ContentHubby_Hub_rpg_action: _,
    ContentHubby_Hub_rpg_action_menu: _,
    ContentHubby_Hub_rpg_crpg: _,
    ContentHubby_Hub_rpg_crpg_menu: _,
    ContentHubby_Hub_rpg_crpg_traditional_rogue_like: _,
    ContentHubby_Hub_rpg_crpg_traditional_rogue_like_menu: _,
    ContentHubby_Hub_rpg_dungeon_crawler: _,
    ContentHubby_Hub_rpg_dungeon_crawler_menu: _,
    ContentHubby_Hub_rpg_jrpg: _,
    ContentHubby_Hub_rpg_jrpg_menu: _,
    ContentHubby_Hub_rpg_mmo: _,
    ContentHubby_Hub_rpg_mmo_menu: _,
    ContentHubby_Hub_rpg_party_based: _,
    ContentHubby_Hub_rpg_party_based_menu: _,
    ContentHubby_Hub_rpg_story: _,
    ContentHubby_Hub_rpg_story_menu: _,
    ContentHubby_Hub_rpg_strategy_tactics: _,
    ContentHubby_Hub_rpg_strategy_tactics_menu: _,
    ContentHubby_Hub_rpg_turn_based: _,
    ContentHubby_Hub_rpg_turn_based_menu: _,
    ContentHubby_Hub_science_fiction: _,
    ContentHubby_Hub_science_fiction_menu: _,
    ContentHubby_Hub_shooter: _,
    ContentHubby_Hub_shooter_menu: _,
    ContentHubby_Hub_sim_building: _,
    ContentHubby_Hub_sim_building_menu: _,
    ContentHubby_Hub_sim_building_automation: _,
    ContentHubby_Hub_sim_building_automation_menu: _,
    ContentHubby_Hub_sim_business_tycoon: _,
    ContentHubby_Hub_sim_business_tycoon_menu: _,
    ContentHubby_Hub_sim_cities_settlements: _,
    ContentHubby_Hub_sim_cities_settlements_menu: _,
    ContentHubby_Hub_sim_farming: _,
    ContentHubby_Hub_sim_farming_menu: _,
    ContentHubby_Hub_sim_farming_crafting: _,
    ContentHubby_Hub_sim_farming_crafting_menu: _,
    ContentHubby_Hub_sim_life: _,
    ContentHubby_Hub_sim_life_menu: _,
    ContentHubby_Hub_sim_life_romance: _,
    ContentHubby_Hub_sim_life_romance_menu: _,
    ContentHubby_Hub_sim_management: _,
    ContentHubby_Hub_sim_management_menu: _,
    ContentHubby_Hub_sim_open_world: _,
    ContentHubby_Hub_sim_open_world_menu: _,
    ContentHubby_Hub_sim_physics_sandbox: _,
    ContentHubby_Hub_sim_physics_sandbox_menu: _,
    ContentHubby_Hub_sim_policy: _,
    ContentHubby_Hub_sim_policy_menu: _,
    ContentHubby_Hub_sim_sandbox_god_game: _,
    ContentHubby_Hub_sim_sandbox_god_game_menu: _,
    ContentHubby_Hub_sim_space_flight: _,
    ContentHubby_Hub_sim_space_flight_menu: _,
    ContentHubby_Hub_sim_dating: _,
    ContentHubby_Hub_sim_dating_menu: _,
    ContentHubby_Hub_simulation: _,
    ContentHubby_Hub_simulation_menu: _,
    ContentHubby_Hub_singleplayer: _,
    ContentHubby_Hub_singleplayer_menu: _,
    ContentHubby_Hub_social_and_players: _,
    ContentHubby_Hub_sports: _,
    ContentHubby_Hub_sports_desc: _,
    ContentHubby_Hub_sports_menu: _,
    ContentHubby_Hub_sports_and_racing: _,
    ContentHubby_Hub_sports_and_racing_menu: _,
    ContentHubby_Hub_sports_ball: _,
    ContentHubby_Hub_sports_ball_menu: _,
    ContentHubby_Hub_sports_combat: _,
    ContentHubby_Hub_sports_combat_menu: _,
    ContentHubby_Hub_sports_fishing_hunting: _,
    ContentHubby_Hub_sports_fishing_hunting_menu: _,
    ContentHubby_Hub_sports_individual: _,
    ContentHubby_Hub_sports_individual_menu: _,
    ContentHubby_Hub_sports_sim: _,
    ContentHubby_Hub_sports_sim_menu: _,
    ContentHubby_Hub_sports_team: _,
    ContentHubby_Hub_sports_team_menu: _,
    ContentHubby_Hub_sports_winter: _,
    ContentHubby_Hub_sports_winter_menu: _,
    ContentHubby_Hub_spooky: _,
    ContentHubby_Hub_spooky_menu: _,
    ContentHubby_Hub_story_driven: _,
    ContentHubby_Hub_story_driven_menu: _,
    ContentHubby_Hub_strategy: _,
    ContentHubby_Hub_strategy_menu: _,
    ContentHubby_Hub_strategy_card_board: _,
    ContentHubby_Hub_strategy_card_board_menu: _,
    ContentHubby_Hub_strategy_cities_settlements: _,
    ContentHubby_Hub_strategy_cities_settlements_menu: _,
    ContentHubby_Hub_strategy_grand_4x: _,
    ContentHubby_Hub_strategy_grand_4x_menu: _,
    ContentHubby_Hub_strategy_military: _,
    ContentHubby_Hub_strategy_military_menu: _,
    ContentHubby_Hub_strategy_moba_auto_battler: _,
    ContentHubby_Hub_strategy_moba_auto_battler_menu: _,
    ContentHubby_Hub_strategy_real_time: _,
    ContentHubby_Hub_strategy_real_time_menu: _,
    ContentHubby_Hub_strategy_sim_management: _,
    ContentHubby_Hub_strategy_sim_management_menu: _,
    ContentHubby_Hub_strategy_tactics: _,
    ContentHubby_Hub_strategy_tactics_menu: _,
    ContentHubby_Hub_strategy_turn_based: _,
    ContentHubby_Hub_strategy_turn_based_menu: _,
    ContentHubby_Hub_survival: _,
    ContentHubby_Hub_survival_menu: _,
    ContentHubby_Hub_survival_stealth: _,
    ContentHubby_Hub_survival_stealth_menu: _,
    ContentHubby_Hub_themes: _,
    ContentHubby_Hub_themes_menu: _,
    ContentHubby_Hub_themes_and_interests: _,
    ContentHubby_Hub_themes_and_interests_menu: _,
    ContentHubby_Hub_time_management: _,
    ContentHubby_Hub_time_management_menu: _,
    ContentHubby_Hub_tower_defense: _,
    ContentHubby_Hub_tower_defense_menu: _,
    ContentHubby_Hub_visual_novel: _,
    ContentHubby_Hub_visual_novel_menu: _,
    ContentHubby_Hub_walking_simulator: _,
    ContentHubby_Hub_walking_simulator_menu: _,
    ContentHubby_Hub_space: _,
    ContentHubby_Hub_space_menu: _,
    ContentHubby_Hub_female_protagonist: _,
    ContentHubby_Hub_female_protagonist_menu: _,
    ContentHubby_Hub_lgbtq: _,
    ContentHubby_Hub_lgbtq_menu: _,
    ContentHubby_Hub_pixel_retro: _,
    ContentHubby_Hub_pixel_retro_menu: _,
    ContentHubby_Hub_choices_matter: _,
    ContentHubby_Hub_choices_matter_menu: _,
    ContentHubby_Hub_mystery_detective: _,
    ContentHubby_Hub_mystery_detective_menu: _,
    ContentHubby_Hub_hobby_sim: _,
    ContentHubby_Hub_hobby_sim_menu: _,
    ContentHubby_Hub_going_rogue: _,
    ContentHubby_Hub_greatondeck: _,
    ContentHubby_Hub_greatonframe: _,
    ContentHubby_Hub_capitalism_economy: _,
    ContentHubby_Hub_pirates_ninjas: _,
    ContentHubby_Hub_dinos_robots: _,
    ContentHubby_Hub_endlessly_replayable: _,
    ContentHubby_Hub_space_exploration: _,
    ContentHubby_Hub_deckbuilders: _,
    ContentHubby_Hub_turnbased_rpg: _,
    ContentHubby_Hub_cooking: _,
    ContentHubby_Hub_plane_train_autos: _,
    ContentHubby_Hub_fishing: _,
    ContentHubby_Hub_fishing_desc: _,
    ContentHubby_Hub_idle: _,
    ContentHubby_Hub_rhythm: _,
    ContentHubby_Hub_sokoban: _,
    ContentHubby_Hub_sokoban_desc: _,
    ContentHubby_Hub_farming: _,
    ContentHubby_Hub_wargame: _,
    ContentHubby_Hub_creature_collector: _,
    ContentHubby_Hub_zombies_vampires: _,
    ContentHubby_Hub_box_pushing: _,
    ContentHubby_Hub_automation: _,
    ContentHubby_Hub_4x_strategy: _,
    ContentHubby_Hub_4x_strategy_desc: _,
    ContentHubby_Hub_political_sim: _,
    ContentHubby_Hub_animals: _,
    ContentHubby_Hub_detective: _,
    ContentHubby_Hub_detective_desc: _,
    ContentHubby_Hub_board_games: _,
    ContentHubby_Hub_typing: _,
    ContentHubby_Hub_typing_desc: _,
    ContentHubby_Hub_combat_pvp: _,
    ContentHubby_Hub_horses: _,
    ContentHubby_Hub_horses_desc: _,
    ContentHubby_Hub_medieval: _,
    ContentHubby_Hub_house_home: _,
    ContentHubby_Hub_ocean: _,
    ContentHubby_Hub_hentai: _,
    ContentHubby_Hub_mature: _,
    ContentHubby_Hub_bullet: _,
    ContentHubby_Hub_bullet_desc: _,
    ContentHubby_Hub_deduction: _,
    ContentHubby_Hub_deduction_desc: _,
    ContentHubby_Hub_trains: _,
    ContentHubby_Hub_trains_desc: _,
    ContentHubby_Hub_cyberpunk: _,
    ContentHubby_Hub_cyberpunk_desc: _,
    ContentHubby_Hub_pinsandpegs: _,
    ContentHubby_Hub_pinsandpegs_desc: _,
    ContentHubby_Hub_pvesurvival: _,
    ContentHubby_Hub_pvesurvival_desc: _,
    ContentHubby_Hub_programming: _,
    ContentHubby_Hub_programming_desc: _,
    ContentHubby_Hub_partyrpg: _,
    ContentHubby_Hub_partyrpg_desc: _,
    ContentHubby_Hub_fantasy_and_supernatural: _,
    ContentHubby_Hub_shooters_without_zombies: _,
    ContentHubby_Hub_relaxing_animal_puzzles: _,
    ContentHubby_Menu_NewAndNoteworthy: _,
    ContentHubby_Menu_CurrentSpecials: _,
    ContentHubby_Hub_adjustable_difficulty: _,
    ContentHubby_Hub_adjustable_difficulty_desc: _,
    ContentHubby_Hub_save_anytime: _,
    ContentHubby_Hub_save_anytime_desc: _,
    ContentHubby_Hub_adjustable_text_size: _,
    ContentHubby_Hub_adjustable_text_size_desc: _,
    ContentHubby_Hub_subtitle_options: _,
    ContentHubby_Hub_subtitle_options_desc: _,
    ContentHubby_Hub_color_alternatives: _,
    ContentHubby_Hub_color_alternatives_desc: _,
    ContentHubby_Hub_camera_comfort: _,
    ContentHubby_Hub_camera_comfort_desc: _,
    ContentHubby_Hub_custom_volume_controls: _,
    ContentHubby_Hub_custom_volume_controls_desc: _,
    ContentHubby_Hub_stereo_sound: _,
    ContentHubby_Hub_stereo_sound_desc: _,
    ContentHubby_Hub_surround_sound: _,
    ContentHubby_Hub_surround_sound_desc: _,
    ContentHubby_Hub_narrated_game_menus: _,
    ContentHubby_Hub_narrated_game_menus_desc: _,
    ContentHubby_Hub_playable_without_timed_input: _,
    ContentHubby_Hub_playable_without_timed_input_desc: _,
    ContentHubby_Hub_keyboard_only_option: _,
    ContentHubby_Hub_keyboard_only_option_desc: _,
    ContentHubby_Hub_mouse_only_option: _,
    ContentHubby_Hub_mouse_only_option_desc: _,
    ContentHubby_Hub_touch_only_option: _,
    ContentHubby_Hub_touch_only_option_desc: _,
    ContentHubby_Hub_chat_speech_to_text: _,
    ContentHubby_Hub_chat_speech_to_text_desc: _,
    ContentHubby_Hub_chat_text_to_speech: _,
    ContentHubby_Hub_chat_text_to_speech_desc: _,
    ContentHubby_Hub_playable_at_your_own_pace: _,
    ContentHubby_Hub_playable_at_your_own_pace_desc: _,
    ContentHubby_Hub_playable_without_vision: _,
    ContentHubby_Hub_playable_without_vision_desc: _,
    ContentHubby_Hub_contrast_controls: _,
    ContentHubby_Hub_contrast_controls_desc: _,
    browse_adultonly: _,
    browse_demos: _,
    genre_free2play: _,
    genre_early_access: _,
    store_tab_greatondeck: _,
    store_tab_greatonframe: _,
    contenthub_title_controller: _,
    browse_remoteplay: _,
    Store_VR_MainMenu_Virtual_Reality: _,
    Store_VR_MainMenu_VR_Hardware: _,
    store_tab_software_home: _,
    additional_game_content_soundtracks: _,
    games_osx: _,
    store_tab_linux: _,
    contenthub_title_pccafe: _,
    msg_try_it_now: _,
    Library_Update_TryItNow2: _,
    dummy: _,
  };
export {
  _ as ContentHubby_Hub_1st_person_action_shooting,
  _ as ContentHubby_Hub_1st_person_action_shooting_menu,
  _ as ContentHubby_Hub_2d_view_action,
  _ as ContentHubby_Hub_2d_view_action_menu,
  _ as ContentHubby_Hub_3rd_person_action_shooting,
  _ as ContentHubby_Hub_3rd_person_action_shooting_menu,
  _ as ContentHubby_Hub_4x_strategy,
  _ as ContentHubby_Hub_4x_strategy_desc,
  _ as ContentHubby_Hub_action,
  _ as ContentHubby_Hub_action_and_adventure,
  _ as ContentHubby_Hub_action_and_adventure_menu,
  _ as ContentHubby_Hub_action_beat_em_up,
  _ as ContentHubby_Hub_action_beat_em_up_menu,
  _ as ContentHubby_Hub_action_dash_adventure,
  _ as ContentHubby_Hub_action_dash_adventure_menu,
  _ as ContentHubby_Hub_action_fps,
  _ as ContentHubby_Hub_action_fps_menu,
  _ as ContentHubby_Hub_action_horror,
  _ as ContentHubby_Hub_action_horror_menu,
  _ as ContentHubby_Hub_action_menu,
  _ as ContentHubby_Hub_action_rogue_like,
  _ as ContentHubby_Hub_action_rogue_like_menu,
  _ as ContentHubby_Hub_action_rpg,
  _ as ContentHubby_Hub_action_rpg_menu,
  _ as ContentHubby_Hub_action_run_jump,
  _ as ContentHubby_Hub_action_run_jump_menu,
  _ as ContentHubby_Hub_action_shooter,
  _ as ContentHubby_Hub_action_shooter_menu,
  _ as ContentHubby_Hub_action_tps,
  _ as ContentHubby_Hub_action_tps_menu,
  _ as ContentHubby_Hub_actions_activities,
  _ as ContentHubby_Hub_actions_activities_menu,
  _ as ContentHubby_Hub_adjustable_difficulty,
  _ as ContentHubby_Hub_adjustable_difficulty_desc,
  _ as ContentHubby_Hub_adjustable_text_size,
  _ as ContentHubby_Hub_adjustable_text_size_desc,
  _ as ContentHubby_Hub_adventure,
  _ as ContentHubby_Hub_adventure_and_casual,
  _ as ContentHubby_Hub_adventure_and_casual_menu,
  _ as ContentHubby_Hub_adventure_explore_open_world,
  _ as ContentHubby_Hub_adventure_explore_open_world_menu,
  _ as ContentHubby_Hub_adventure_menu,
  _ as ContentHubby_Hub_adventure_point_click,
  _ as ContentHubby_Hub_adventure_point_click_menu,
  _ as ContentHubby_Hub_adventure_rpg,
  _ as ContentHubby_Hub_adventure_rpg_casual,
  _ as ContentHubby_Hub_adventure_rpg_casual_menu,
  _ as ContentHubby_Hub_adventure_rpg_menu,
  _ as ContentHubby_Hub_aesthetic,
  _ as ContentHubby_Hub_aesthetic_menu,
  _ as ContentHubby_Hub_animals,
  _ as ContentHubby_Hub_anime_mild,
  _ as ContentHubby_Hub_anime_mild_menu,
  _ as ContentHubby_Hub_arcade,
  _ as ContentHubby_Hub_arcade_menu,
  _ as ContentHubby_Hub_arcade_rhythm,
  _ as ContentHubby_Hub_arcade_rhythm_menu,
  _ as ContentHubby_Hub_artstyles_music,
  _ as ContentHubby_Hub_artstyles_music_menu,
  _ as ContentHubby_Hub_automation,
  _ as ContentHubby_Hub_base_builder,
  _ as ContentHubby_Hub_board_games,
  _ as ContentHubby_Hub_box_pushing,
  _ as ContentHubby_Hub_bullet,
  _ as ContentHubby_Hub_bullet_desc,
  _ as ContentHubby_Hub_business_politics,
  _ as ContentHubby_Hub_business_politics_menu,
  _ as ContentHubby_Hub_camera_comfort,
  _ as ContentHubby_Hub_camera_comfort_desc,
  _ as ContentHubby_Hub_capitalism_economy,
  _ as ContentHubby_Hub_casual,
  _ as ContentHubby_Hub_casual_and_puzzle,
  _ as ContentHubby_Hub_casual_and_puzzle_menu,
  _ as ContentHubby_Hub_casual_and_story,
  _ as ContentHubby_Hub_casual_and_story_menu,
  _ as ContentHubby_Hub_casual_card_board,
  _ as ContentHubby_Hub_casual_card_board_menu,
  _ as ContentHubby_Hub_casual_menu,
  _ as ContentHubby_Hub_casual_puzzle,
  _ as ContentHubby_Hub_casual_puzzle_menu,
  _ as ContentHubby_Hub_character_action_game,
  _ as ContentHubby_Hub_chat_speech_to_text,
  _ as ContentHubby_Hub_chat_speech_to_text_desc,
  _ as ContentHubby_Hub_chat_text_to_speech,
  _ as ContentHubby_Hub_chat_text_to_speech_desc,
  _ as ContentHubby_Hub_choices_matter,
  _ as ContentHubby_Hub_choices_matter_menu,
  _ as ContentHubby_Hub_clickers_idlers,
  _ as ContentHubby_Hub_clickers_idlers_menu,
  _ as ContentHubby_Hub_color_alternatives,
  _ as ContentHubby_Hub_color_alternatives_desc,
  _ as ContentHubby_Hub_combat_pvp,
  _ as ContentHubby_Hub_contrast_controls,
  _ as ContentHubby_Hub_contrast_controls_desc,
  _ as ContentHubby_Hub_cooking,
  _ as ContentHubby_Hub_creature_collector,
  _ as ContentHubby_Hub_crime_justice,
  _ as ContentHubby_Hub_crime_justice_menu,
  _ as ContentHubby_Hub_custom_volume_controls,
  _ as ContentHubby_Hub_custom_volume_controls_desc,
  _ as ContentHubby_Hub_cute_cartoon,
  _ as ContentHubby_Hub_cute_cartoon_menu,
  _ as ContentHubby_Hub_cyberpunk,
  _ as ContentHubby_Hub_cyberpunk_desc,
  _ as ContentHubby_Hub_dating_sim,
  _ as ContentHubby_Hub_dating_sim_menu,
  _ as ContentHubby_Hub_deckbuilders,
  _ as ContentHubby_Hub_deduction,
  _ as ContentHubby_Hub_deduction_desc,
  _ as ContentHubby_Hub_detective,
  _ as ContentHubby_Hub_detective_desc,
  _ as ContentHubby_Hub_dinos_robots,
  _ as ContentHubby_Hub_driving_piloting,
  _ as ContentHubby_Hub_driving_piloting_menu,
  _ as ContentHubby_Hub_education,
  _ as ContentHubby_Hub_education_menu,
  _ as ContentHubby_Hub_endlessly_replayable,
  _ as ContentHubby_Hub_experimental,
  _ as ContentHubby_Hub_experimental_menu,
  _ as ContentHubby_Hub_exploration_open_world,
  _ as ContentHubby_Hub_exploration_open_world_menu,
  _ as ContentHubby_Hub_fantasy,
  _ as ContentHubby_Hub_fantasy_and_supernatural,
  _ as ContentHubby_Hub_fantasy_menu,
  _ as ContentHubby_Hub_fantasy_supernatural,
  _ as ContentHubby_Hub_fantasy_supernatural_menu,
  _ as ContentHubby_Hub_farming,
  _ as ContentHubby_Hub_female_protagonist,
  _ as ContentHubby_Hub_female_protagonist_menu,
  _ as ContentHubby_Hub_fighting,
  _ as ContentHubby_Hub_fighting_martial_arts,
  _ as ContentHubby_Hub_fighting_martial_arts_menu,
  _ as ContentHubby_Hub_fighting_menu,
  _ as ContentHubby_Hub_fishing,
  _ as ContentHubby_Hub_fishing_desc,
  _ as ContentHubby_Hub_free_to_play,
  _ as ContentHubby_Hub_going_rogue,
  _ as ContentHubby_Hub_greatondeck,
  _ as ContentHubby_Hub_greatonframe,
  _ as ContentHubby_Hub_hack_and_slash,
  _ as ContentHubby_Hub_hentai,
  _ as ContentHubby_Hub_hidden_object,
  _ as ContentHubby_Hub_hidden_object_menu,
  _ as ContentHubby_Hub_history,
  _ as ContentHubby_Hub_hobby_sim,
  _ as ContentHubby_Hub_hobby_sim_menu,
  _ as ContentHubby_Hub_horror,
  _ as ContentHubby_Hub_horror_dark,
  _ as ContentHubby_Hub_horror_dark_menu,
  _ as ContentHubby_Hub_horror_menu,
  _ as ContentHubby_Hub_horses,
  _ as ContentHubby_Hub_horses_desc,
  _ as ContentHubby_Hub_house_home,
  _ as ContentHubby_Hub_idle,
  _ as ContentHubby_Hub_interactive_fiction,
  _ as ContentHubby_Hub_interactive_fiction_menu,
  _ as ContentHubby_Hub_interactive_stories,
  _ as ContentHubby_Hub_interactive_stories_menu,
  _ as ContentHubby_Hub_keyboard_only_option,
  _ as ContentHubby_Hub_keyboard_only_option_desc,
  _ as ContentHubby_Hub_lgbtq,
  _ as ContentHubby_Hub_lgbtq_menu,
  _ as ContentHubby_Hub_life_sim,
  _ as ContentHubby_Hub_location_worlds,
  _ as ContentHubby_Hub_match_3,
  _ as ContentHubby_Hub_match_3_menu,
  _ as ContentHubby_Hub_mature,
  _ as ContentHubby_Hub_medieval,
  _ as ContentHubby_Hub_metroidvania,
  _ as ContentHubby_Hub_metroidvania_menu,
  _ as ContentHubby_Hub_military,
  _ as ContentHubby_Hub_military_menu,
  _ as ContentHubby_Hub_military_warfare,
  _ as ContentHubby_Hub_military_warfare_menu,
  _ as ContentHubby_Hub_minimalist_abstract,
  _ as ContentHubby_Hub_minimalist_abstract_menu,
  _ as ContentHubby_Hub_minimalist_relaxing,
  _ as ContentHubby_Hub_minimalist_relaxing_menu,
  _ as ContentHubby_Hub_mouse_only_option,
  _ as ContentHubby_Hub_mouse_only_option_desc,
  _ as ContentHubby_Hub_multiplayer,
  _ as ContentHubby_Hub_multiplayer_battle_royale,
  _ as ContentHubby_Hub_multiplayer_battle_royale_menu,
  _ as ContentHubby_Hub_multiplayer_competitive,
  _ as ContentHubby_Hub_multiplayer_competitive_menu,
  _ as ContentHubby_Hub_multiplayer_coop,
  _ as ContentHubby_Hub_multiplayer_coop_menu,
  _ as ContentHubby_Hub_multiplayer_lan,
  _ as ContentHubby_Hub_multiplayer_lan_menu,
  _ as ContentHubby_Hub_multiplayer_local_party,
  _ as ContentHubby_Hub_multiplayer_local_party_menu,
  _ as ContentHubby_Hub_multiplayer_menu,
  _ as ContentHubby_Hub_multiplayer_mmo,
  _ as ContentHubby_Hub_multiplayer_mmo_menu,
  _ as ContentHubby_Hub_multiplayer_moba_auto_battler,
  _ as ContentHubby_Hub_multiplayer_moba_auto_battler_menu,
  _ as ContentHubby_Hub_multiplayer_online_competitive,
  _ as ContentHubby_Hub_multiplayer_online_competitive_menu,
  _ as ContentHubby_Hub_multiplayer_shooter,
  _ as ContentHubby_Hub_multiplayer_shooter_menu,
  _ as ContentHubby_Hub_music_rhythm,
  _ as ContentHubby_Hub_music_rhythm_menu,
  _ as ContentHubby_Hub_mystery_detective,
  _ as ContentHubby_Hub_mystery_detective_menu,
  _ as ContentHubby_Hub_narrated_game_menus,
  _ as ContentHubby_Hub_narrated_game_menus_desc,
  _ as ContentHubby_Hub_ocean,
  _ as ContentHubby_Hub_open_world_survival_craft,
  _ as ContentHubby_Hub_open_world_survival_craft_menu,
  _ as ContentHubby_Hub_partyrpg,
  _ as ContentHubby_Hub_partyrpg_desc,
  _ as ContentHubby_Hub_people_creatures,
  _ as ContentHubby_Hub_pinsandpegs,
  _ as ContentHubby_Hub_pinsandpegs_desc,
  _ as ContentHubby_Hub_pirates_ninjas,
  _ as ContentHubby_Hub_pixel_retro,
  _ as ContentHubby_Hub_pixel_retro_menu,
  _ as ContentHubby_Hub_plane_train_autos,
  _ as ContentHubby_Hub_playable_at_your_own_pace,
  _ as ContentHubby_Hub_playable_at_your_own_pace_desc,
  _ as ContentHubby_Hub_playable_without_timed_input,
  _ as ContentHubby_Hub_playable_without_timed_input_desc,
  _ as ContentHubby_Hub_playable_without_vision,
  _ as ContentHubby_Hub_playable_without_vision_desc,
  _ as ContentHubby_Hub_players,
  _ as ContentHubby_Hub_political_sim,
  _ as ContentHubby_Hub_programming,
  _ as ContentHubby_Hub_programming_desc,
  _ as ContentHubby_Hub_psychedelic,
  _ as ContentHubby_Hub_psychedelic_menu,
  _ as ContentHubby_Hub_psychedelic_surreal,
  _ as ContentHubby_Hub_psychedelic_surreal_menu,
  _ as ContentHubby_Hub_puzzle,
  _ as ContentHubby_Hub_puzzle_difficult,
  _ as ContentHubby_Hub_puzzle_difficult_menu,
  _ as ContentHubby_Hub_puzzle_logic,
  _ as ContentHubby_Hub_puzzle_logic_menu,
  _ as ContentHubby_Hub_puzzle_matching,
  _ as ContentHubby_Hub_puzzle_matching_menu,
  _ as ContentHubby_Hub_puzzle_menu,
  _ as ContentHubby_Hub_puzzle_multiplayer,
  _ as ContentHubby_Hub_puzzle_multiplayer_menu,
  _ as ContentHubby_Hub_pvesurvival,
  _ as ContentHubby_Hub_pvesurvival_desc,
  _ as ContentHubby_Hub_racing,
  _ as ContentHubby_Hub_racing_combat,
  _ as ContentHubby_Hub_racing_combat_menu,
  _ as ContentHubby_Hub_racing_desc,
  _ as ContentHubby_Hub_racing_menu,
  _ as ContentHubby_Hub_racing_piloting,
  _ as ContentHubby_Hub_racing_piloting_menu,
  _ as ContentHubby_Hub_racing_sim,
  _ as ContentHubby_Hub_racing_sim_menu,
  _ as ContentHubby_Hub_relaxing,
  _ as ContentHubby_Hub_relaxing_animal_puzzles,
  _ as ContentHubby_Hub_relaxing_menu,
  _ as ContentHubby_Hub_retro,
  _ as ContentHubby_Hub_retro_menu,
  _ as ContentHubby_Hub_rhythm,
  _ as ContentHubby_Hub_rogue_like,
  _ as ContentHubby_Hub_rogue_like_menu,
  _ as ContentHubby_Hub_rogue_like_rogue_lite,
  _ as ContentHubby_Hub_rogue_like_rogue_lite_menu,
  _ as ContentHubby_Hub_rogue_like_turn_based,
  _ as ContentHubby_Hub_rogue_like_turn_based_menu,
  _ as ContentHubby_Hub_rpg,
  _ as ContentHubby_Hub_rpg_action,
  _ as ContentHubby_Hub_rpg_action_menu,
  _ as ContentHubby_Hub_rpg_crpg,
  _ as ContentHubby_Hub_rpg_crpg_menu,
  _ as ContentHubby_Hub_rpg_crpg_traditional_rogue_like,
  _ as ContentHubby_Hub_rpg_crpg_traditional_rogue_like_menu,
  _ as ContentHubby_Hub_rpg_dungeon_crawler,
  _ as ContentHubby_Hub_rpg_dungeon_crawler_menu,
  _ as ContentHubby_Hub_rpg_jrpg,
  _ as ContentHubby_Hub_rpg_jrpg_menu,
  _ as ContentHubby_Hub_rpg_menu,
  _ as ContentHubby_Hub_rpg_mmo,
  _ as ContentHubby_Hub_rpg_mmo_menu,
  _ as ContentHubby_Hub_rpg_party_based,
  _ as ContentHubby_Hub_rpg_party_based_menu,
  _ as ContentHubby_Hub_rpg_story,
  _ as ContentHubby_Hub_rpg_story_menu,
  _ as ContentHubby_Hub_rpg_strategy_tactics,
  _ as ContentHubby_Hub_rpg_strategy_tactics_menu,
  _ as ContentHubby_Hub_rpg_turn_based,
  _ as ContentHubby_Hub_rpg_turn_based_menu,
  _ as ContentHubby_Hub_save_anytime,
  _ as ContentHubby_Hub_save_anytime_desc,
  _ as ContentHubby_Hub_science_fiction,
  _ as ContentHubby_Hub_science_fiction_menu,
  _ as ContentHubby_Hub_scream,
  _ as ContentHubby_Hub_shmup,
  _ as ContentHubby_Hub_shooter,
  _ as ContentHubby_Hub_shooter_menu,
  _ as ContentHubby_Hub_shooters_without_zombies,
  _ as ContentHubby_Hub_sim_building,
  _ as ContentHubby_Hub_sim_building_automation,
  _ as ContentHubby_Hub_sim_building_automation_menu,
  _ as ContentHubby_Hub_sim_building_menu,
  _ as ContentHubby_Hub_sim_business_tycoon,
  _ as ContentHubby_Hub_sim_business_tycoon_menu,
  _ as ContentHubby_Hub_sim_cities_settlements,
  _ as ContentHubby_Hub_sim_cities_settlements_menu,
  _ as ContentHubby_Hub_sim_dating,
  _ as ContentHubby_Hub_sim_dating_menu,
  _ as ContentHubby_Hub_sim_farming,
  _ as ContentHubby_Hub_sim_farming_crafting,
  _ as ContentHubby_Hub_sim_farming_crafting_menu,
  _ as ContentHubby_Hub_sim_farming_menu,
  _ as ContentHubby_Hub_sim_life,
  _ as ContentHubby_Hub_sim_life_menu,
  _ as ContentHubby_Hub_sim_life_romance,
  _ as ContentHubby_Hub_sim_life_romance_menu,
  _ as ContentHubby_Hub_sim_management,
  _ as ContentHubby_Hub_sim_management_menu,
  _ as ContentHubby_Hub_sim_open_world,
  _ as ContentHubby_Hub_sim_open_world_menu,
  _ as ContentHubby_Hub_sim_physics_sandbox,
  _ as ContentHubby_Hub_sim_physics_sandbox_menu,
  _ as ContentHubby_Hub_sim_policy,
  _ as ContentHubby_Hub_sim_policy_menu,
  _ as ContentHubby_Hub_sim_sandbox_god_game,
  _ as ContentHubby_Hub_sim_sandbox_god_game_menu,
  _ as ContentHubby_Hub_sim_space_flight,
  _ as ContentHubby_Hub_sim_space_flight_menu,
  _ as ContentHubby_Hub_simulation,
  _ as ContentHubby_Hub_simulation_menu,
  _ as ContentHubby_Hub_singleplayer,
  _ as ContentHubby_Hub_singleplayer_menu,
  _ as ContentHubby_Hub_social_and_players,
  _ as ContentHubby_Hub_sokoban,
  _ as ContentHubby_Hub_sokoban_desc,
  _ as ContentHubby_Hub_space,
  _ as ContentHubby_Hub_space_exploration,
  _ as ContentHubby_Hub_space_menu,
  _ as ContentHubby_Hub_spooky,
  _ as ContentHubby_Hub_spooky_menu,
  _ as ContentHubby_Hub_sports,
  _ as ContentHubby_Hub_sports_and_racing,
  _ as ContentHubby_Hub_sports_and_racing_menu,
  _ as ContentHubby_Hub_sports_ball,
  _ as ContentHubby_Hub_sports_ball_menu,
  _ as ContentHubby_Hub_sports_combat,
  _ as ContentHubby_Hub_sports_combat_menu,
  _ as ContentHubby_Hub_sports_desc,
  _ as ContentHubby_Hub_sports_fishing_hunting,
  _ as ContentHubby_Hub_sports_fishing_hunting_menu,
  _ as ContentHubby_Hub_sports_individual,
  _ as ContentHubby_Hub_sports_individual_menu,
  _ as ContentHubby_Hub_sports_menu,
  _ as ContentHubby_Hub_sports_sim,
  _ as ContentHubby_Hub_sports_sim_menu,
  _ as ContentHubby_Hub_sports_team,
  _ as ContentHubby_Hub_sports_team_menu,
  _ as ContentHubby_Hub_sports_winter,
  _ as ContentHubby_Hub_sports_winter_menu,
  _ as ContentHubby_Hub_stealth,
  _ as ContentHubby_Hub_stereo_sound,
  _ as ContentHubby_Hub_stereo_sound_desc,
  _ as ContentHubby_Hub_story_driven,
  _ as ContentHubby_Hub_story_driven_menu,
  _ as ContentHubby_Hub_strategy,
  _ as ContentHubby_Hub_strategy_card_board,
  _ as ContentHubby_Hub_strategy_card_board_menu,
  _ as ContentHubby_Hub_strategy_cities_settlements,
  _ as ContentHubby_Hub_strategy_cities_settlements_menu,
  _ as ContentHubby_Hub_strategy_grand_4x,
  _ as ContentHubby_Hub_strategy_grand_4x_menu,
  _ as ContentHubby_Hub_strategy_menu,
  _ as ContentHubby_Hub_strategy_military,
  _ as ContentHubby_Hub_strategy_military_menu,
  _ as ContentHubby_Hub_strategy_moba_auto_battler,
  _ as ContentHubby_Hub_strategy_moba_auto_battler_menu,
  _ as ContentHubby_Hub_strategy_real_time,
  _ as ContentHubby_Hub_strategy_real_time_menu,
  _ as ContentHubby_Hub_strategy_sim_management,
  _ as ContentHubby_Hub_strategy_sim_management_menu,
  _ as ContentHubby_Hub_strategy_tactics,
  _ as ContentHubby_Hub_strategy_tactics_menu,
  _ as ContentHubby_Hub_strategy_turn_based,
  _ as ContentHubby_Hub_strategy_turn_based_menu,
  _ as ContentHubby_Hub_subtitle_options,
  _ as ContentHubby_Hub_subtitle_options_desc,
  _ as ContentHubby_Hub_surround_sound,
  _ as ContentHubby_Hub_surround_sound_desc,
  _ as ContentHubby_Hub_survival,
  _ as ContentHubby_Hub_survival_menu,
  _ as ContentHubby_Hub_survival_stealth,
  _ as ContentHubby_Hub_survival_stealth_menu,
  _ as ContentHubby_Hub_themes,
  _ as ContentHubby_Hub_themes_and_interests,
  _ as ContentHubby_Hub_themes_and_interests_menu,
  _ as ContentHubby_Hub_themes_menu,
  _ as ContentHubby_Hub_time_management,
  _ as ContentHubby_Hub_time_management_menu,
  _ as ContentHubby_Hub_touch_only_option,
  _ as ContentHubby_Hub_touch_only_option_desc,
  _ as ContentHubby_Hub_tower_defense,
  _ as ContentHubby_Hub_tower_defense_menu,
  _ as ContentHubby_Hub_trains,
  _ as ContentHubby_Hub_trains_desc,
  _ as ContentHubby_Hub_turnbased_rpg,
  _ as ContentHubby_Hub_typing,
  _ as ContentHubby_Hub_typing_desc,
  _ as ContentHubby_Hub_visual_novel,
  _ as ContentHubby_Hub_visual_novel_menu,
  _ as ContentHubby_Hub_walking_simulator,
  _ as ContentHubby_Hub_walking_simulator_menu,
  _ as ContentHubby_Hub_wargame,
  _ as ContentHubby_Hub_zombies_vampires,
  _ as ContentHubby_Menu_CurrentSpecials,
  _ as ContentHubby_Menu_NewAndNoteworthy,
  _ as Library_Install,
  _ as Library_Update_TryItNow2,
  _ as Store_VR_MainMenu_VR_Hardware,
  _ as Store_VR_MainMenu_Virtual_Reality,
  _ as additional_game_content_soundtracks,
  _ as api_category_coming_soon,
  _ as api_category_new_releases,
  _ as api_category_top_sellers,
  _ as browse_adultonly,
  _ as browse_demos,
  _ as browse_free,
  _ as browse_remoteplay,
  _ as btn_add_to_wishlist,
  _ as contenthub_title_controller,
  _ as contenthub_title_pccafe,
  _ as default,
  _ as discount_desc_limited_time,
  _ as discount_desc_limited_time_date,
  _ as discount_desc_preset_loyalty,
  _ as dummy,
  _ as games_osx,
  _ as genre_early_access,
  _ as genre_free2play,
  _ as label_back_catalogue,
  _ as label_deepest_discount,
  _ as label_early_beta_access,
  _ as label_for_a_limited_time_only,
  _ as label_free_week,
  _ as label_free_weekend,
  _ as label_highlighted_deals,
  _ as label_just_updated,
  _ as label_new_and_upcoming,
  _ as label_new_dlc_available,
  _ as label_play_free_generic,
  _ as label_play_free_until_custom,
  _ as label_pre_load_now,
  _ as language,
  _ as limitedtime_install_and_keep,
  _ as msg_action_buy,
  _ as msg_action_details,
  _ as msg_action_info,
  _ as msg_advanced_access,
  _ as msg_available_everywhere,
  _ as msg_available_just_released,
  _ as msg_available_just_released_from_early_access,
  _ as msg_available_new_release,
  _ as msg_available_now_free_to_play,
  _ as msg_available_now_ftp_early,
  _ as msg_coming_soon_to_steamos,
  _ as msg_early_access_now_available,
  _ as msg_free_play_until,
  _ as msg_free_play_weekend,
  _ as msg_free_to_play_just_updated,
  _ as msg_free_update,
  _ as msg_in_early_access,
  _ as msg_just_updated_with_free_dlc,
  _ as msg_new_content_now_available,
  _ as msg_new_game,
  _ as msg_new_update_available,
  _ as msg_now_available_for_mac_and_steamos,
  _ as msg_now_available_on_steamos,
  _ as msg_now_available_on_steamos_mac_and_linux,
  _ as msg_now_with_steam_workshop,
  _ as msg_now_with_steamworks,
  _ as msg_on_sale_now,
  _ as msg_play_beta_now,
  _ as msg_play_demo_now,
  _ as msg_play_it_now,
  _ as msg_play_now,
  _ as msg_preload_completed,
  _ as msg_preload_free,
  _ as msg_preload_now,
  _ as msg_preload_now_for_free,
  _ as msg_preload_you_have_completed,
  _ as msg_preload_you_have_pre,
  _ as msg_prepurchase_and_get_beta_access,
  _ as msg_prepurchase_and_play_beta_now,
  _ as msg_prepurchase_bonus,
  _ as msg_prepurchase_now,
  _ as msg_publisher_sale,
  _ as msg_publisher_weekend,
  _ as msg_steam_workshop_now_available,
  _ as msg_try_it_now,
  _ as msg_watch_movie_now,
  _ as msg_weekend_on_now,
  _ as msg_weekend_play_free,
  _ as msg_weekend_trial,
  _ as mst_weekend_description_free,
  _ as promo_ends_custom,
  _ as promo_giveaway,
  _ as spotlight_daily_deal,
  _ as spotlight_franchise_sale,
  _ as spotlight_major_update,
  _ as spotlight_midweek_deal,
  _ as spotlight_midweek_madness,
  _ as spotlight_thirdparty_event,
  _ as spotlight_weekend_deal,
  _ as spotlight_weeklong_header1,
  _ as spotlight_weeklong_sale,
  _ as store_tab_greatondeck,
  _ as store_tab_greatonframe,
  _ as store_tab_linux,
  _ as store_tab_software_home,
  _ as text_free_new_dlc_now_available,
  _ as text_new_free_to_play,
  _ as text_now_available,
  _ as text_now_available_mac,
  _ as text_now_available_on_pc_mac_and_linux,
  _ as text_now_available_steamplay,
  _ as text_now_free_to_play,
};
