var _ = `schinese`,
  _ = `此游戏的 %2$s 篇用户评测中有 %1$s% 为好评。`,
  _ = `此游戏的 %2$s 篇%3$s用户评测中有 %1$s% 为好评。`,
  _ = `立省 %1$s%。原价为 %2$s，折后为 %3$s。`,
  _ = `特价 %1$s`,
  _ = `免费`,
  _ = `在购物车中`,
  _ = `添加到购物车`,
  _ = `作为礼物购买`,
  _ = `立刻播放`,
  _ = `添加到库`,
  _ = `登录`,
  _ = `登录以将此免费物品添加至您的帐户。`,
  _ = `菜单`,
  _ = `热销商品`,
  _ = `新品`,
  _ = `特卖中`,
  _ = `搜索商店`,
  _ = `清除搜索词`,
  _ = `愿望单`,
  _ = `购物车`,
  _ = `VR 作品`,
  _ = `热门链接`,
  _ = `商店主页`,
  _ = `非常适合 Deck`,
  _ = `非常适合 Frame`,
  _ = `免费开玩游戏`,
  _ = `Steam 榜单`,
  _ = `即将推出`,
  _ = `点数商店`,
  _ = `礼物卡`,
  _ = `新闻与更新`,
  _ = `偏好`,
  _ = `浏览`,
  _ = `热门`,
  _ = `推荐`,
  _ = `类别`,
  _ = `硬件`,
  _ = `畅玩方式`,
  _ = `特别栏目`,
  _ = `查看全部`,
  _ = `更多`,
  _ = `菜单`,
  _ = `我的偏好`,
  _ = `我的愿望单`,
  _ = `我的订阅`,
  _ = `我关注的游戏`,
  _ = `我的帐户`,
  _ = `我的家庭`,
  _ = `最近查看过`,
  _ = `从上次停止的地方继续`,
  _ = `为您推荐`,
  _ = `在您的愿望单中`,
  _ = `为您推荐的 DLC`,
  _ = `为您推荐`,
  _ = `浏览热门栏目`,
  _ = `热门栏目`,
  _ = `人气蹿升的新品`,
  _ = `免费开玩游戏`,
  _ = `热门免费开玩`,
  _ = `热销商品`,
  _ = `新品`,
  _ = `探索 Steam 上的新内容`,
  _ = `查看发行日历上的内容`,
  _ = `折扣与活动`,
  _ = `所有榜单和统计数据`,
  _ = `按周、月或年探索热门作品`,
  _ = `您的愿望单`,
  _ = `%1$s 项折扣`,
  _ = `特别活动`,
  _ = `热门作品`,
  _ = `特别优惠`,
  _ = `推荐`,
  _ = `新品队列`,
  _ = `社区推荐`,
  _ = `交互式推荐模型`,
  _ = `您的个人日历`,
  _ = `好友中热门`,
  _ = `Steam 鉴赏家`,
  _ = `为您推荐的 DLC`,
  _ = `您的探索队列`,
  _ = `让 Steam 量身为您推荐一组游戏`,
  _ = `浏览我的队列`,
  _ = `获取我们机器学习系统的个性化推荐`,
  _ = `获取推荐`,
  _ = `探索个性化的游戏列表，其中列出了最近发行或即将推出的游戏。`,
  _ = `探索我的日历`,
  _ = `全新`,
  _ = `您最喜欢的类型`,
  _ = `您最喜欢的类别`,
  _ = `查看所有类型和主题`,
  _ = `展开`,
  _ = `折叠`,
  _ = `查看所有标签`,
  _ = `所有类型和主题`,
  _ = `硬件`,
  _ = `VR 硬件`,
  _ = `Steam Deck`,
  _ = `Steam Controller`,
  _ = `Steam Machine`,
  _ = `Steam Frame`,
  _ = `Valve Index`,
  _ = `基座`,
  _ = `Steam 硬件`,
  _ = `畅玩游戏的方式`,
  _ = `特别栏目`,
  _ = `Steam 新品节`,
  _ = `Steam 大奖`,
  _ = `Steam 回顾`,
  _ = `Steam 实验室`,
  _ = `DLC`,
  _ = `特卖活动`,
  _ = `最近查看过`,
  _ = `热门搜索`,
  _ = `搜索结果`,
  _ = `您最喜欢的类型`,
  _ = `浏览关键词：`,
  _ = `没有符合您查询条件的物品。`,
  _ = `高级搜索`,
  _ = `%1$s 款游戏`,
  _ = `搜索`,
  _ = `商店菜单`,
  _ = `包含 %1$s 个游戏`,
  _ = `在库中`,
  _ = `已在愿望单中`,
  _ = `在购物车中`,
  _ = `已忽略`,
  _ = `已按偏好排除`,
  _ = `我的类别：`,
  _ = `无`,
  _ = `按类别筛选`,
  _ = `清除类别筛选条件`,
  _ = `添加类别`,
  _ = `移除类别`,
  _ = `从此项目中移除此类别`,
  _ = `筛选愿望单，仅显示此类别中的项目`,
  _ = `全部`,
  _ = `未分类`,
  _ = `添加或移除类别`,
  _ = `正在等待特卖`,
  _ = `生日列表`,
  _ = `由好友推荐`,
  _ = `管理“%1$s”的类别`,
  _ = `当前类别`,
  _ = `按名称搜索或添加新类别`,
  _ = `添加类别`,
  _ = `我的其他类别`,
  _ = `建议类别`,
  _ = `此愿望单项目已达到 %1$s 个类别的上限。`,
  _ = `高级…`,
  _ = `正常价格`,
  _ = `30 天最低价格`,
  _ = `此游戏在过去的 %2$s 天内曾以 %1$s 的折扣价出售`,
  _ = `此游戏当前价格为过去 %1$s 天内最低`,
  _ = `当前价格`,
  _ = `折扣基于过去 30 天的最低价格`,
  _ = `您的个人日历`,
  _ = `您专属的个性化游戏列表，其中列出了新游戏和即将推出的游戏`,
  _ = `+%1$s 项`,
  _ = `探索您的完整个人日历`,
  _ = `探索更多`,
  _ = `我们在这一天没有可向您推荐的新品 <1>快去看看您日历上的其他日期吧！</1>`,
  _ = `新`,
  _ = `今天`,
  _ = `dont translate`,
  _ = {
    language: _,
    review_summary_reviewrate: _,
    review_summary_reviewrate_language_specific: _,
    Discount_ARIA_Label: _,
    Discount_ARIA_Label_SpecialPrice: _,
    Price_Free: _,
    AddToCartButton_InCart: _,
    AddToCartButton_AddToCart: _,
    AddToCartButton_PurchaseAsGift: _,
    PlayGameButton_PlayNow: _,
    AddToLibraryButton: _,
    Button_SignIn: _,
    SignInToAddToLibrary_Tooltip: _,
    Menu_OpenFlyout: _,
    Menu_TopSellers: _,
    Menu_NewReleases: _,
    Menu_OnSale: _,
    Menu_SearchPlaceholder: _,
    Menu_ClearSearchTerm: _,
    Menu_Wishlist: _,
    Menu_Cart: _,
    Menu_VR: _,
    Menu_Popover_TopLinks: _,
    Menu_Popover_StoreHome: _,
    Menu_Popover_GreatonDeck: _,
    Menu_Popover_GreatonFrame: _,
    Menu_Popover_FreeToPlay: _,
    Menu_Popover_SteamCharts: _,
    Menu_Popover_Upcoming: _,
    Menu_Popover_PointsShop: _,
    Menu_Popover_GiftCards: _,
    Menu_Popover_NewsAndUpdates: _,
    Menu_Popover_Preferences: _,
    Menu_Popover_Browse: _,
    Menu_Popover_Top: _,
    Menu_Popover_Recommendations: _,
    Menu_Popover_Categories: _,
    Menu_Popover_Hardware: _,
    Menu_Popover_WaysToPlay: _,
    Menu_Popover_SpecialSections: _,
    Menu_Popover_ViewAll: _,
    Menu_Popover_More: _,
    Menu_Popover_Menu: _,
    Menu_Section_Browse_MyPreferences: _,
    Menu_Section_Browse_MyWishlist: _,
    Menu_Section_Browse_MySubscriptions: _,
    Menu_Section_Browse_MyFollowedGames: _,
    Menu_Section_Browse_MyAccount: _,
    Menu_Section_Browse_MyFamily: _,
    Menu_Section_Browse_RecentlyViewed: _,
    Menu_Section_Browse_PickUpWhereYouLeftOff: _,
    Menu_Section_Browse_Recommended: _,
    Menu_Section_Browse_FromYourWishlist: _,
    Menu_Section_Browse_DLCForYou: _,
    Menu_Section_Browse_ForYou: _,
    Menu_Section_Browse_BrowseTop: _,
    Menu_Section_Browse_Top: _,
    Menu_Section_Browse_PopularNew: _,
    Menu_Section_Browse_FreeToPlay: _,
    Menu_Section_Browse_TopFreeToPlay: _,
    Menu_Section_Browse_TopSellers: _,
    Menu_Section_Browse_NewReleases: _,
    Menu_Section_Browse_NewReleases_Desc: _,
    Menu_Section_Browse_Upcoming_Desc: _,
    Menu_Section_Browse_Discounts: _,
    Menu_Section_Browse_Charts: _,
    Menu_Section_Browse_Charts_Desc: _,
    Menu_Section_Browse_Discounts_YourWishlist: _,
    Menu_Section_Browse_Discounts_YourWishlist_Discounts: _,
    Menu_Section_Browse_Discounts_SpecialEvents: _,
    Menu_Section_Browse_Discounts_PopularTitles: _,
    Menu_Section_Browse_Discounts_SpecialOffers: _,
    Menu_Section_Recommendations: _,
    Menu_Section_Recommendations_NewReleasesQueue: _,
    Menu_Section_Recommendations_CommunityRecommendations: _,
    Menu_Section_Recommendations_InteractiveRecommender: _,
    Menu_Section_Recommendations_PersonalCalendar: _,
    Menu_Section_Recommendations_PopularAmongFriends: _,
    Menu_Section_Recommendations_SteamCurators: _,
    Menu_Section_Recommendations_DLCForYou: _,
    Menu_Section_Recommendations_DiscoveryQueue_Title: _,
    Menu_Section_Recommendations_DiscoveryQueue_Description: _,
    Menu_Section_Recommendations_DiscoveryQueue_ActionButton: _,
    Menu_Section_Recommendations_InteractiveRecommender_Description: _,
    Menu_Section_Recommendations_InteractiveRecommender_ActionButton: _,
    Menu_Section_Recommendations_PersonalCalendar_Description: _,
    Menu_Section_Recommendations_PersonalCalendar_ActionButton: _,
    Menu_Section_Recommendations_New: _,
    Menu_Section_Categories_YourTopGenres: _,
    Menu_Section_Categories_YourTopCategories: _,
    Menu_Section_Categories_ViewAll: _,
    Menu_Section_Categories_Expand: _,
    Menu_Section_Categories_Collapse: _,
    Menu_Section_Categories_ViewAllTags: _,
    Menu_Section_Categories_GenresAndThemes: _,
    Menu_Section_Hardware: _,
    Menu_Section_Hardware_VRHardware: _,
    Menu_Section_Hardware_SteamDeck: _,
    Menu_Section_Hardware_SteamController: _,
    Menu_Section_Hardware_SteamMachine: _,
    Menu_Section_Hardware_SteamFrame: _,
    Menu_Section_Hardware_ValveIndex: _,
    Menu_Section_Hardware_SteamDeckDock: _,
    Menu_Section_Hardware_Family: _,
    Menu_Section_WaysToPlay: _,
    Menu_Section_SpecialSections: _,
    Menu_Section_SpecialSections_NextFest: _,
    Menu_Section_SpecialSections_SteamAwards: _,
    Menu_Section_SpecialSections_SteamReplay: _,
    Menu_Section_SpecialSections_SteamLabs: _,
    Menu_Section_SpecialSections_DLCForYou: `DLC`,
    Menu_Section_SpecialSections_SaleEvents: _,
    Menu_SearchBar_RecentlyViewed: _,
    Menu_SearchBar_PopularSearches: _,
    Menu_SearchBar_SearchResults: _,
    Menu_SearchBar_YourTopGenres: _,
    Menu_SearchBar_BrowseBy: _,
    Menu_SearchBar_NoMatches: _,
    Menu_SearchBar_AdvancedSearch: _,
    Menu_SearchBar_CategoryGameCount: _,
    Menu_Search: _,
    Menu_Label: _,
    Menu_IncludesXGames: _,
    ItemFlag_InLibrary: _,
    ItemFlag_OnWishlist: _,
    ItemFlag_InCart: _,
    ItemFlag_Ignored: _,
    ItemFlag_ExcludedByPreferences: _,
    Wishlist_Controls_Categories_Header: _,
    Wishlist_Categories_None: `无`,
    Wishlist_Gamepad_Filter_Category: _,
    Wishlist_Gamepad_Filter_Clear_Category: _,
    Wishlist_Gamepad_Add_Category: _,
    Wishlist_Gamepad_Removecategory: _,
    Wishlist_Controls_Categories_Remove_Tooltip: _,
    Wishlist_Controls_Categories_Filter_Tooltip: _,
    Wishlist_Controls_Categories_All: _,
    Wishlist_Controls_Categories_Uncategorized: _,
    Wishlist_Controls_Categories_Manage: _,
    Wishlist_Categories_Suggested_Discount: _,
    Wishlist_Categories_Suggested_Birthday: _,
    Wishlist_Categories_Suggested_Recommended: _,
    Wishlist_Controls_Categories_Manageitem: _,
    Wishlist_Controls_Categories_Header_Current: _,
    Wishlist_Categories_Dialog_Search: _,
    Wishlist_Categories_Dialog_Add: _,
    Wishlist_Controls_Categories_Header_Other: _,
    Wishlist_Controls_Categories_Header_Suggested: _,
    Wishlist_Categories_Max_Per_App_Reached: _,
    Wishlist_Categories_Dialog_Advanced: _,
    Price_History_Normal_Price: _,
    Price_History_Recent_Low_Price: _,
    Price_History_Recent_Low_Price_Ttip: _,
    Price_History_Current_Low_Price_Ttip: _,
    Price_History_Current_Price: _,
    Price_History_Lowest_Previous_30: _,
    PersonalCalendar_Title: _,
    PersonalCalendar_Subtitle: _,
    PersonalCalendar_More: _,
    PersonalCalendar_Full: _,
    PersonalCalendar_Explore: _,
    PersonalCalendar_EmptyDay: _,
    NewBadge: `新`,
    Time_Today: _,
    store_ui_dummy: _,
  };
export {
  _ as AddToCartButton_AddToCart,
  _ as AddToCartButton_InCart,
  _ as AddToCartButton_PurchaseAsGift,
  _ as AddToLibraryButton,
  _ as Button_SignIn,
  _ as Discount_ARIA_Label,
  _ as Discount_ARIA_Label_SpecialPrice,
  _ as ItemFlag_ExcludedByPreferences,
  _ as ItemFlag_Ignored,
  _ as ItemFlag_InCart,
  _ as ItemFlag_InLibrary,
  _ as ItemFlag_OnWishlist,
  _ as Menu_Cart,
  _ as Menu_ClearSearchTerm,
  _ as Menu_IncludesXGames,
  _ as Menu_Label,
  _ as Menu_NewReleases,
  _ as Menu_OnSale,
  _ as Menu_OpenFlyout,
  _ as Menu_Popover_Browse,
  _ as Menu_Popover_Categories,
  _ as Menu_Popover_FreeToPlay,
  _ as Menu_Popover_GiftCards,
  _ as Menu_Popover_GreatonDeck,
  _ as Menu_Popover_GreatonFrame,
  _ as Menu_Popover_Hardware,
  _ as Menu_Popover_Menu,
  _ as Menu_Popover_More,
  _ as Menu_Popover_NewsAndUpdates,
  _ as Menu_Popover_PointsShop,
  _ as Menu_Popover_Preferences,
  _ as Menu_Popover_Recommendations,
  _ as Menu_Popover_SpecialSections,
  _ as Menu_Popover_SteamCharts,
  _ as Menu_Popover_StoreHome,
  _ as Menu_Popover_Top,
  _ as Menu_Popover_TopLinks,
  _ as Menu_Popover_Upcoming,
  _ as Menu_Popover_ViewAll,
  _ as Menu_Popover_WaysToPlay,
  _ as Menu_Search,
  _ as Menu_SearchBar_AdvancedSearch,
  _ as Menu_SearchBar_BrowseBy,
  _ as Menu_SearchBar_CategoryGameCount,
  _ as Menu_SearchBar_NoMatches,
  _ as Menu_SearchBar_PopularSearches,
  _ as Menu_SearchBar_RecentlyViewed,
  _ as Menu_SearchBar_SearchResults,
  _ as Menu_SearchBar_YourTopGenres,
  _ as Menu_SearchPlaceholder,
  _ as Menu_Section_Browse_BrowseTop,
  _ as Menu_Section_Browse_Charts,
  _ as Menu_Section_Browse_Charts_Desc,
  _ as Menu_Section_Browse_DLCForYou,
  _ as Menu_Section_Browse_Discounts,
  _ as Menu_Section_Browse_Discounts_PopularTitles,
  _ as Menu_Section_Browse_Discounts_SpecialEvents,
  _ as Menu_Section_Browse_Discounts_SpecialOffers,
  _ as Menu_Section_Browse_Discounts_YourWishlist,
  _ as Menu_Section_Browse_Discounts_YourWishlist_Discounts,
  _ as Menu_Section_Browse_ForYou,
  _ as Menu_Section_Browse_FreeToPlay,
  _ as Menu_Section_Browse_FromYourWishlist,
  _ as Menu_Section_Browse_MyAccount,
  _ as Menu_Section_Browse_MyFamily,
  _ as Menu_Section_Browse_MyFollowedGames,
  _ as Menu_Section_Browse_MyPreferences,
  _ as Menu_Section_Browse_MySubscriptions,
  _ as Menu_Section_Browse_MyWishlist,
  _ as Menu_Section_Browse_NewReleases,
  _ as Menu_Section_Browse_NewReleases_Desc,
  _ as Menu_Section_Browse_PickUpWhereYouLeftOff,
  _ as Menu_Section_Browse_PopularNew,
  _ as Menu_Section_Browse_RecentlyViewed,
  _ as Menu_Section_Browse_Recommended,
  _ as Menu_Section_Browse_Top,
  _ as Menu_Section_Browse_TopFreeToPlay,
  _ as Menu_Section_Browse_TopSellers,
  _ as Menu_Section_Browse_Upcoming_Desc,
  _ as Menu_Section_Categories_Collapse,
  _ as Menu_Section_Categories_Expand,
  _ as Menu_Section_Categories_GenresAndThemes,
  _ as Menu_Section_Categories_ViewAll,
  _ as Menu_Section_Categories_ViewAllTags,
  _ as Menu_Section_Categories_YourTopCategories,
  _ as Menu_Section_Categories_YourTopGenres,
  _ as Menu_Section_Hardware,
  _ as Menu_Section_Hardware_Family,
  _ as Menu_Section_Hardware_SteamController,
  _ as Menu_Section_Hardware_SteamDeck,
  _ as Menu_Section_Hardware_SteamDeckDock,
  _ as Menu_Section_Hardware_SteamFrame,
  _ as Menu_Section_Hardware_SteamMachine,
  _ as Menu_Section_Hardware_VRHardware,
  _ as Menu_Section_Hardware_ValveIndex,
  _ as Menu_Section_Recommendations,
  _ as Menu_Section_Recommendations_CommunityRecommendations,
  _ as Menu_Section_Recommendations_DLCForYou,
  _ as Menu_Section_Recommendations_DiscoveryQueue_ActionButton,
  _ as Menu_Section_Recommendations_DiscoveryQueue_Description,
  _ as Menu_Section_Recommendations_DiscoveryQueue_Title,
  _ as Menu_Section_Recommendations_InteractiveRecommender,
  _ as Menu_Section_Recommendations_InteractiveRecommender_ActionButton,
  _ as Menu_Section_Recommendations_InteractiveRecommender_Description,
  _ as Menu_Section_Recommendations_New,
  _ as Menu_Section_Recommendations_NewReleasesQueue,
  _ as Menu_Section_Recommendations_PersonalCalendar,
  _ as Menu_Section_Recommendations_PersonalCalendar_ActionButton,
  _ as Menu_Section_Recommendations_PersonalCalendar_Description,
  _ as Menu_Section_Recommendations_PopularAmongFriends,
  _ as Menu_Section_Recommendations_SteamCurators,
  _ as Menu_Section_SpecialSections,
  _ as Menu_Section_SpecialSections_DLCForYou,
  _ as Menu_Section_SpecialSections_NextFest,
  _ as Menu_Section_SpecialSections_SaleEvents,
  _ as Menu_Section_SpecialSections_SteamAwards,
  _ as Menu_Section_SpecialSections_SteamLabs,
  _ as Menu_Section_SpecialSections_SteamReplay,
  _ as Menu_Section_WaysToPlay,
  _ as Menu_TopSellers,
  _ as Menu_VR,
  _ as Menu_Wishlist,
  _ as NewBadge,
  _ as PersonalCalendar_EmptyDay,
  _ as PersonalCalendar_Explore,
  _ as PersonalCalendar_Full,
  _ as PersonalCalendar_More,
  _ as PersonalCalendar_Subtitle,
  _ as PersonalCalendar_Title,
  _ as PlayGameButton_PlayNow,
  _ as Price_Free,
  _ as Price_History_Current_Low_Price_Ttip,
  _ as Price_History_Current_Price,
  _ as Price_History_Lowest_Previous_30,
  _ as Price_History_Normal_Price,
  _ as Price_History_Recent_Low_Price,
  _ as Price_History_Recent_Low_Price_Ttip,
  _ as SignInToAddToLibrary_Tooltip,
  _ as Time_Today,
  _ as Wishlist_Categories_Dialog_Add,
  _ as Wishlist_Categories_Dialog_Advanced,
  _ as Wishlist_Categories_Dialog_Search,
  _ as Wishlist_Categories_Max_Per_App_Reached,
  _ as Wishlist_Categories_None,
  _ as Wishlist_Categories_Suggested_Birthday,
  _ as Wishlist_Categories_Suggested_Discount,
  _ as Wishlist_Categories_Suggested_Recommended,
  _ as Wishlist_Controls_Categories_All,
  _ as Wishlist_Controls_Categories_Filter_Tooltip,
  _ as Wishlist_Controls_Categories_Header,
  _ as Wishlist_Controls_Categories_Header_Current,
  _ as Wishlist_Controls_Categories_Header_Other,
  _ as Wishlist_Controls_Categories_Header_Suggested,
  _ as Wishlist_Controls_Categories_Manage,
  _ as Wishlist_Controls_Categories_Manageitem,
  _ as Wishlist_Controls_Categories_Remove_Tooltip,
  _ as Wishlist_Controls_Categories_Uncategorized,
  _ as Wishlist_Gamepad_Add_Category,
  _ as Wishlist_Gamepad_Filter_Category,
  _ as Wishlist_Gamepad_Filter_Clear_Category,
  _ as Wishlist_Gamepad_Removecategory,
  _ as default,
  _ as language,
  _ as review_summary_reviewrate,
  _ as review_summary_reviewrate_language_specific,
  _ as store_ui_dummy,
};
