var _ = `Alla buntar som innehåller:`,
  _ = `Sortera efter:`,
  _ = `Populärt`,
  _ = `Pris`,
  _ = `Buntrabatt`,
  _ = `Namn`,
  _ = `Rekommenderat`,
  _ = `Dina kompletta buntar`,
  _ = `Allt innehåll i dessa buntar finns i ditt bibliotek`,
  _ = `Komplettera uppsättningen-buntar`,
  _ = `Köp de återstående titlarna som ännu inte finns i ditt bibliotek för att komplettera bunten.`,
  _ = `Måste köpas tillsammans-buntar`,
  _ = `Inkluderar alla produkter tillsammans som en bunt; måste köpas som en komplett uppsättning.`,
  _ = `© %1$s Valve Corporation. Alla rättigheter förbehållna. Alla varumärken tillhör respektive ägare i USA och andra länder.`,
  _ = `Moms inräknat i alla priser där det är tillämpligt.`,
  _ = `Integritetspolicy`,
  _ = `Juridisk information`,
  _ = `Tillgänglighet`,
  _ = `Steams abonnentavtal`,
  _ = `Återbetalningar`,
  _ = `Cookies`,
  _ = `Om Valve`,
  _ = `Affärslösningar`,
  _ = `Återvinning`,
  _ = `Steamworks`,
  _ = `Source Engine`,
  _ = `Jobb`,
  _ = `Presentkort`,
  _ = `Distribution på Steam`,
  _ = `Support`,
  _ = `Önskelista från %1$s`,
  _ = `ÖNSKELISTA FRÅN %1$s`,
  _ = `Kundvagn (%1$s)`,
  _ = `Visa kundvagnen`,
  _ = `Önskelista (%1$s)`,
  _ = `Alternativ`,
  _ = `Sortera efter: %1$s`,
  _ = `Skapa en delningslänk`,
  _ = `Din rangordning`,
  _ = `Rangordning`,
  _ = `Bästsäljare`,
  _ = `Lanseringsdatum`,
  _ = `Datum tillagt`,
  _ = `Recensionspoäng`,
  _ = `Pris`,
  _ = `Namn`,
  _ = `Rabatt`,
  _ = `Delningslänk`,
  _ = `Återkalla alla länkar`,
  _ = `Länkar återkallade!`,
  _ = `Misslyckades med att generera delningsbar länk (fel %1$s)`,
  _ = `Alla med den här länken kan se din önskelista med de aktuella filtren oavsett vilka synlighetsinställningar du har för din profil. De kan inte ändra filtren.`,
  _ = `Vy`,
  _ = `Expanderad`,
  _ = `Kompakt`,
  _ = `Plattform`,
  _ = `Alla OS`,
  _ = `macOS`,
  _ = `SteamOS + Linux`,
  _ = `Sort`,
  _ = `Spel`,
  _ = `Programvara`,
  _ = `DLC`,
  _ = `Videor`,
  _ = `Pris`,
  _ = `Rabatt`,
  _ = `Alla artiklar på listan`,
  _ = `Alla med rabatt`,
  _ = `%1$s % eller mer`,
  _ = `Alla priser`,
  _ = `Under %1$s`,
  _ = `Gratis`,
  _ = `Exkludera`,
  _ = `Relaterade produkter`,
  _ = `Early Access`,
  _ = `Det här spelet är i Early Access`,
  _ = `Förhandsversion`,
  _ = `Endast VR`,
  _ = `Demo tillgänglig`,
  _ = `Filtrera önskelistan till produkter med demor`,
  _ = `Kompatibilitet med Steam Deck`,
  _ = `Verifierat`,
  _ = `Spelbart`,
  _ = `Tagg`,
  _ = `Filtrera önskelistan till artiklar med denna tagg`,
  _ = `Användartaggar:`,
  _ = `%1$s: %2$s`,
  _ = `Kategori`,
  _ = `Kategorier:`,
  _ = `<1>Kategorier:</1> <2>%1$s</2>`,
  _ = `Lägg till kategori`,
  _ = `Avancerad kategorihantering`,
  _ = `VÄLJ KATEGORI ATT REDIGERA`,
  _ = `KATEGORINAMN`,
  _ = `Byt namn`,
  _ = `Du har redan en kategori med det namnet`,
  _ = `Det uppstod ett fel när kategorin skulle byta namn (kod: %1$s)`,
  _ = `Ingenting på önskelistan matchar sökningen.`,
  _ = `Alla`,
  _ = `Inga`,
  _ = `Visar %1$s av %2$s artiklar. Begränsa listan med en sökning.`,
  _ = `%1$s artikel kunde inte uppdateras`,
  _ = `%1$s artiklar kunde inte uppdateras`,
  _ = `Väntar`,
  _ = `Tillägg: %1$s`,
  _ = `Borttagningar: %1$s`,
  _ = `Återställ`,
  _ = `Tillämpa ändringar`,
  _ = `LÄGG TILL/TA BORT KATEGORI`,
  _ = `%1$s ARTIKEL`,
  _ = `%1$s ARTIKLAR`,
  _ = `Sökresultat:`,
  _ = `%1$s artikel med namn innehåller ”%2$s”`,
  _ = `%1$s artiklar med namn innehåller ”%2$s”`,
  _ = `%1$s artikel med kategorin %2$s`,
  _ = `%1$s artiklar med kategorin %2$s`,
  _ = `%1$s artikel med kategorier som innehåller ”%2$s”`,
  _ = `%1$s artiklar med kategorier som innehåller ”%2$s”`,
  _ = `%1$s artikel med taggen %2$s`,
  _ = `%1$s artiklar med taggen %2$s`,
  _ = `%1$s artikel med taggar som innehåller ”%2$s”`,
  _ = `%1$s artiklar med taggar som innehåller ”%2$s”`,
  _ = `Sök efter namn eller tagg`,
  _ = `Sök på namn, tagg eller kategori`,
  _ = `Alla recensioner:`,
  _ = `Recensioner på %1$s:`,
  _ = `Lanseringsdatum:`,
  _ = `Tillagt %1$s`,
  _ = `ta bort`,
  _ = `Ta bort artikeln från önskelistan`,
  _ = `(otillgänglig artikel)`,
  _ = `Denna artikel är inte tillgänglig i din region.`,
  _ = `Denna artikel är inte längre tillgänglig.`,
  _ = `Vuxet innehåll är förbjudet för användare under 18 år i ditt land. Valve måste bekräfta att du är över 18 år innan du kan få tillgång till vuxet innehåll.`,
  _ = `Enligt den brittiska lagen om onlinesäkerhet (Online Safety Act) måste Valve bekräfta att du är över 18 år innan du kan få tillgång till sexuellt innehåll för vuxna.`,
  _ = `Lägg till kreditkort`,
  _ = `Din önskelista är tom.`,
  _ = `Fyll på önskelistan genom att utforska produkter i butiken och använda knappen Lägg till på önskelistan.`,
  _ = `Läs mer om önskelistor på Steam`,
  _ = `Logga in för att se önskelistan`,
  _ = `Den här önskelistan är tom.`,
  _ = `Inga matchande artiklar.`,
  _ = `Det finns %1$s produkter på den här önskelistan, men ingen av dem matchar dina önskelistefilter och/eller butikspreferenser.`,
  _ = `Det finns %1$s produkter på den här önskelistan, men ingen av dem matchar dina önskelistefilter och/eller <1>butikspreferenser</1>.`,
  _ = `Ändra ordning`,
  _ = `Avbryt omsortering`,
  _ = `Placera här`,
  _ = `Alternativ`,
  _ = `Ta bort`,
  _ = `Visa butikssida`,
  _ = `Önskelista – fel`,
  _ = `Fel`,
  _ = `Okänt fel`,
  _ = `Profilen hittades inte`,
  _ = `Användarens önskelista kunde inte läsas in.`,
  _ = `Den här länken för att dela önskelistan är ogiltig eller har upphört att gälla.`,
  _ = `Spel med önskelisteaviseringar`,
  _ = `Kontot till %1$s`,
  _ = `Konto – fel`,
  _ = `Konto`,
  _ = `Hem`,
  _ = `Kontodetaljer`,
  _ = `Butikspreferenser`,
  _ = `Språkpreferenser`,
  _ = `Aviseringsinställningar`,
  _ = `Enheter`,
  _ = `Säkerhet och enheter`,
  _ = `Auktoriserade enheter (video)`,
  _ = `Enheter för mobilspel`,
  _ = `Speltester`,
  _ = `Familjehantering`,
  _ = `Data och navigering`,
  _ = `VR`,
  _ = `Bra på Deck`,
  _ = `Lokala spel på Frame`,
  _ = `Startsida`,
  _ = `Kategorier`,
  _ = `Sök på Steam`,
  _ = `Kunde inte läsa in data med begränsad tillgång.`,
  _ = `Inbjudningar till Steam Playtest`,
  _ = `Acceptera inbjudan`,
  _ = `Avböj inbjudan`,
  _ = `Du har blivit inbjuden att delta i Steam Playtest!`,
  _ = `Du har blivit inbjuden till en begränsad lansering!`,
  _ = `%1$s har bjudit in dig att delta i ett Steam Playtest!`,
  _ = `%1$s har bjudit in dig till en begränsad lansering!`,
  _ = `Du har inga inbjudningar till Steam Playtest eller begränsade lanseringar som väntar på svar från dig.`,
  _ = `Välkommen till detta Playtest! %1$s kan nu installeras från ditt bibliotek.`,
  _ = `Välkommen till den begränsade lanseringen! %1$s kan nu installeras i biblioteket.`,
  _ = `Välkommen till speltestet! %1$s är inte aktivt just nu. Håll utkik efter kommande lanseringsplaner från utvecklaren.`,
  _ = `Visa bibliotek`,
  _ = `Vad är Steam Playtest?`,
  _ = `Steam Playtest används för att testa spel som fortfarande är under utveckling. Om du accepterar en inbjudan eller får en åtkomstförfrågan beviljad av utvecklaren, läggs spelet till i ditt bibliotek automatiskt.`,
  _ = `Se information från utvecklaren om det individuella speltestets karaktär. Åtkomst till Steam Playtest garanterar inte tillgång till spelet vid lansering.`,
  _ = `Ignorerade inbjudningar till Steam Playtest`,
  _ = `Du har avböjt en inbjudan till ett Steam Playtest eller en begränsad lansering för följande spel. Du kommer inte att få några fler inbjudningar förrän du tar bort de avböjda spelen från listan.`,
  _ = `Ta bort`,
  _ = `Avbryt`,
  _ = `Skicka`,
  _ = `Detta är din sista tillgängliga inbjudan för detta speltest.`,
  _ = `Detta är den sista tillgängliga inbjudan du har för denna begränsade lansering.`,
  _ = `Skicka en inbjudan till:`,
  _ = `Bjuder in %1$s ...`,
  _ = `%1$s är inbjuden! Inbjudan visas i hens %2$s aviseringar.`,
  _ = `%1$s kunde inte bjudas in. Hen kanske redan har blivit inbjuden eller så är spelet inte tillgängligt i hens region.`,
  _ = `Historik över skickade inbjudningar`,
  _ = `De senaste inbjudningarna till Steam Playtest och begränsad lansering som du har skickat till dina vänner`,
  _ = `Bjöd in %1$s till %2$s`,
  _ = `Steam Playtest-deltagande`,
  _ = `Du har inte gått med i några pågående speltester i Steam Playtest eller begränsade lanseringar.`,
  _ = `Du har inbjudningar tillgängliga`,
  _ = `Du har %1$s inbjudan tillgänglig`,
  _ = `Du har %1$s inbjudningar tillgängliga`,
  _ = `Du kan ge dina vänner tillgång till detta speltest genom att bjuda in dem.`,
  _ = `Antalet tillgängliga inbjudningar kan ändras vartefter som fler spelare går med.`,
  _ = `Mer information, t.ex. schema och inkluderat innehåll, kan finnas på spelets %1$s eller %2$s.`,
  _ = `butikssida`,
  _ = `nyhetshubb`,
  _ = `Speltestet är inte aktivt just nu.`,
  _ = `Du har använt alla dina väninbjudningar`,
  _ = `Bjud in vänner`,
  _ = `Välj inbjudningsmottagare`,
  _ = `Sök på vännens namn ...`,
  _ = `Det gick inte att läsa in dina vänner.`,
  _ = `Vissa vänner kan inte bjudas in eftersom ni inte har varit vänner i 30 dagar, de har redan tillgång till spelet eller uppfyller inte kraven för att delta.`,
  _ = `Vissa vänner kan inte bjudas in eftersom de redan har tillgång till spelet, eller så uppfyller de inte kraven för att delta.`,
  _ = `Begränsad lansering`,
  _ = `Du kan ge dina vänner tillgång till den begränsade lanseringen genom att bjuda in dem.`,
  _ = `%1$s ökar långsamt antalet spelare under en initial begränsad lansering. Mer information kan finnas tillgänglig på spelets %2$s eller %3$s.`,
  _ = `Vad innebär begränsad lansering?`,
  _ = `Begränsad lansering används av vissa gratisspel för att långsamt öka spelarantalet under spelets inledande utgivning. Om du accepterar en inbjudan eller får en åtkomstförfrågan beviljad av utvecklaren läggs spelet till i ditt bibliotek och du kan börja spela omedelbart.`,
  _ = `Webbplatsöversikt för Steam-butiken`,
  _ = `Startsida`,
  _ = `Mitt konto`,
  _ = `Kontouppgifter`,
  _ = `Butiksinställningar`,
  _ = `Familjehantering`,
  _ = `Säkerhet och enheter`,
  _ = `Språkpreferenser`,
  _ = `Cookies och navigering`,
  _ = `Aviseringsinställningar`,
  _ = `Kundvagn`,
  _ = `Kundvagn (%1$s)`,
  _ = `Lägg till på önskelistan`,
  _ = `Önskelista (%1$s)`,
  _ = `Spel och program som du följer`,
  _ = `Spel och program som du följer (%1$s)`,
  _ = `Tabeller och listor`,
  _ = `Toppsäljare`,
  _ = `Mest spelade`,
  _ = `Nya lanseringar`,
  _ = `Kommande lanseringar`,
  _ = `Gratis att spela`,
  _ = `Steam-listor`,
  _ = `På rea nu`,
  _ = `Rekommendationer`,
  _ = `Discovery-kö`,
  _ = `Kö med nya släpp`,
  _ = `Gemenskapsrekommendationer`,
  _ = `Interaktiv rekommenderare`,
  _ = `Populärt bland vänner`,
  _ = `Steam-kuratorer`,
  _ = `DLC för dig`,
  _ = `Maskinvara`,
  _ = `Steam Deck`,
  _ = `Steam Deck-dockningsstation`,
  _ = `VR-maskinvara`,
  _ = `VR-spel`,
  _ = `Bra på Deck`,
  _ = `Kontrollvänliga spel`,
  _ = `Sätt att spela`,
  _ = `Nyheter och uppdateringar`,
  _ = `Nyligen uppdaterade spel`,
  _ = `Dina nyligen uppdaterade spel`,
  _ = `Dina kommande event`,
  _ = `Nyheter i fokus`,
  _ = `Officiella nyheter och uppdateringar från Steam`,
  _ = `Kampanjer och event`,
  _ = `Specialerbjudanden`,
  _ = `Reaevent`,
  _ = `Steam Replay`,
  _ = `Steams förfestival`,
  _ = `Steampriserna`,
  _ = `Specialsektioner`,
  _ = `Steams poängbutik`,
  _ = `Presentkort`,
  _ = `Genrer:`,
  _ = `Teman`,
  _ = `Du har gjort för många förfrågningar nyligen. Vänta och försök igen senare.`,
  _ = `Allmänna diskussioner`,
  _ = `Anmälda inlägg`,
  _ = `Workshop-diskussioner`,
  _ = `Byteshandel`,
  _ = `Event och tillkännagivanden`,
  _ = `Interaktiv rekommenderare ...`,
  _ = `Spelare som du gillar ...`,
  _ = `Utforska personliga rekommendationer från vårt maskininlärningssystem som baseras på din spelhistorik och jämförs med miljontals andra spelare. Anpassa dina resultat genom att använda skjutreglagen och filter, och spara sedan dina inställningar så Steam kommer ihåg vad du letar efter.`,
  _ = `Din relevanta speltid`,
  _ = `%1$s spel`,
  _ = `topp %1$s-spel`,
  _ = `senaste spelen`,
  _ = `%1$s timmar`,
  _ = `%1$s timmar totalt`,
  _ = `senast spelat %1$s`,
  _ = `senast spelat > 10 år sedan`,
  _ = `Inkludera`,
  _ = `Exkludera`,
  _ = `Ordna efter popularitet`,
  _ = `populärt`,
  _ = `nisch`,
  _ = `Filtrera efter ålder`,
  _ = `äldre`,
  _ = `nyare`,
  _ = `Genom tiderna`,
  _ = `5 år`,
  _ = `3 år`,
  _ = `2 år`,
  _ = `1 år`,
  _ = `6 månader`,
  _ = `Rekommendationer för dig`,
  _ = `Lanserades %1$s`,
  _ = `På önskelistan`,
  _ = `Lägg till i kundvagn`,
  _ = `Lägg till på önskelistan`,
  _ = `Gratis att spela`,
  _ = `Skriv ett taggnamn`,
  _ = `Lägg till taggfilter`,
  _ = `Lägg till taggexkluderingar`,
  _ = `Exkludera spel på önskelistan`,
  _ = `Endast rabatterade spel`,
  _ = `Släpptes under den senaste månaden`,
  _ = `Släpptes under den senaste veckan`,
  _ = `Kommande`,
  _ = `Din personliga kalender`,
  _ = `En personlig lista för dig som innehåller %1$s spel som nyligen släppts eller kommer snart.`,
  _ = `Taggväljare`,
  _ = `Filtrera efter tagg ...`,
  _ = `Dölj ägda spel`,
  _ = `Spel som släpps från Early Access visas fortfarande`,
  _ = `Dölj Early Access-spel`,
  _ = `Visa endast spel på önskelistan`,
  _ = `Antal spel`,
  _ = `Kompakt kalender`,
  _ = `Valfri åsidosättning`,
  _ = `Konto-ID`,
  _ = `Visa alla %1$s`,
  _ = `Logga in för att se personanpassade förslag.`,
  _ = `Utöka alla`,
  _ = `Steam Labs experiment 16 | <1>Läs mer och lämna feedback</1>`,
  _ = `Spel på önskelistan`,
  _ = `Visa`,
  _ = `Dölj`,
  _ = `Endast`,
  _ = `För många spel på önskelistan, inaktiverat`,
  _ = `Ett fel uppstod vid inläsning av kalendern. Försök igen.`,
  _ = `Lista över buntar för %1$s`,
  _ = `Lista över buntar`,
  _ = `Alla buntar som innehåller spelet %1$s.`,
  _ = `Verifierat på Steam Deck`,
  _ = `%1$s är verifierat på Steam Deck`,
  _ = `Fel på sidan`,
  _ = `HOPPSAN!`,
  _ = `Ett fel uppstod när din begäran behandlades.`,
  _ = `Antal platser måste vara större än 0.`,
  _ = `E-postdomän används redan för ett annat pressorgan.`,
  _ = `Kunde inte lägga till pressorgan.`,
  _ = `E-postdomän kan inte vara tom.`,
  _ = `Ogiltig e-postdomän.`,
  _ = `Kontot är redan i ett pressorgan.`,
  _ = `Kunde inte lägga till kontot i pressorganet.`,
  _ = `E-postdomän`,
  _ = `Antal platser`,
  _ = `Lägg till`,
  _ = `Lägg till pressorgan:`,
  _ = `%1$s, %2$s/%3$s platser använda`,
  _ = `Visa historik`,
  _ = `Historik för %1$s`,
  _ = `Pressnyckel beviljad till %1$s av %2$s`,
  _ = `Pressnyckel återkallad från %1$s av %2$s`,
  _ = `Pressorgan skapat av %1$s`,
  _ = `Pressorgan uppdaterat av %1$s`,
  _ = `E-postdomän inställd på %1$s`,
  _ = `Antal platser inställt på %1$s`,
  _ = `Pressorgan raderat av %1$s`,
  _ = `Pressorgan återställt av %1$s`,
  _ = `Mediekanal i testmiljö, av %1$s`,
  _ = `Ändringar från testmiljön tillämpade av %1$s`,
  _ = `Användaren %1$s är redo att läggas till av %2$s`,
  _ = `Användaren %1$s är redo att tas bort av %2$s`,
  _ = `support`,
  _ = `Mottagare`,
  _ = `Tilldelades`,
  _ = `Är gruppadministratör?`,
  _ = `Steam-ID att lägga till`,
  _ = `OK`,
  _ = `Avbryt`,
  _ = `Ja`,
  _ = `Nej`,
  _ = `Alla`,
  _ = `Aktiva`,
  _ = `Raderade`,
  _ = `Tomma`,
  _ = `Inga administratörer i pressorgan`,
  _ = `Pressorgan:`,
  _ = `Vänkod:`,
  _ = `Överlämna pressnyckel: `,
  _ = `Vill du verkligen överlämna din pressnyckel?`,
  _ = `Historik för pressorgan`,
  _ = `Lägg till medlem`,
  _ = `Visa historik`,
  _ = `Konto`,
  _ = `Trailern hittades inte`,
  _ = `Trailer`,
  _ = `Mikrotrailer`,
  _ = `Ett fel uppstod när dina aviseringsinställningar skulle sparas.`,
  _ = `Ett fel uppstod när dina aviseringsinställningar skulle läsas in.`,
  _ = `Den här avregistreringslänken är ogiltig eller har upphört att gälla. Logga in och gå till <1>Aviseringsinställningar</1>`,
  _ = `Flödet aktiveras automatiskt om popup-aviseringar i klienten eller mobilappen har aktiverats.`,
  _ = `Meddela endast %1$s om dessa önskelistekategorier`,
  _ = `Bildfrekvensberäknare`,
  _ = `Välj en app och en pc-konfiguration för att få ett diagram med uppskattade bildfrekvenser, baserat på bildfrekvenser från andra Steam-användare.`,
  _ = `CPU`,
  _ = `Systemminne`,
  _ = `GPU`,
  _ = `Din sparade maskinvara`,
  _ = `Du har ingen sparad maskinvara.`,
  _ = `Välj maskinvara för att se en uppskattad bildfrekvens.`,
  _ = `<Ingen vald>`,
  _ = `Du kan lägga till din nuvarande maskinvara om du tittar på detta inifrån Steam-klienten.`,
  _ = `Lägg till sparad maskinvara`,
  _ = `Lägg till sparad maskinvara (inte i klienten)`,
  _ = `Om du vill bidra med anonymiserade data till bildfrekvensberäknaren och hjälpa till att göra den mer användbar, kan du besöka dina preferenser genom att klicka på länken nedan och välja att delta under sektionen Datainsamling.`,
  _ = `Preferenser`,
  _ = `FPS`,
  _ = `Sök efter ett spel`,
  _ = `Välj CPU`,
  _ = `Välj GPU`,
  _ = `Antal matchande träningsposter för spel`,
  _ = `Antal matchande träningsposter för CPU`,
  _ = `Antal matchande träningsposter för GPU`,
  _ = `Okänd`,
  _ = `Skicka ett presentkort`,
  _ = ``,
  _ = {
    BundleList_SubTitle: _,
    BundleList_SortBy: _,
    BundleList_SortBy_Popular: _,
    BundleList_SortBy_Price: _,
    BundleList_SortBy_Discount: _,
    BundleList_SortBy_Name: _,
    BundleList_SortBy_Recommend: _,
    BundleList_AllInLibrary: _,
    BundleList_AllInLibrarySubtitle: _,
    BundleList_CompleteTheSet: _,
    BundleList_CompleteTheSetSubtitle: _,
    BundleList_MustPurchaseAsSet: _,
    BundleList_MustPurchaseAsSetSubtitle: _,
    footer_legal_notice: _,
    footer_vat_included: _,
    footer_privacy_policy: _,
    footer_legal: _,
    footer_accessibility: _,
    footer_ssa: _,
    footer_refunds: _,
    footer_cookies: _,
    footer_about_valve: _,
    footer_business_solutions: _,
    footer_recycling: _,
    footer_steamworks: _,
    footer_source_engine: _,
    footer_jobs: _,
    footer_walletcode: _,
    footer_steam_distribution: _,
    footer_nav_help_support: _,
    wishlist_title: _,
    wishlist_header: _,
    cart_count: _,
    cart_view_cart: _,
    wishlist_count: _,
    wishlist_options_button: _,
    wishlist_sortby_button: _,
    wishlist_share_tooltip: _,
    wishlist_controls_sortby_order: _,
    wishlist_controls_sortby_their_order: _,
    wishlist_controls_sortby_topsellers: _,
    wishlist_controls_sortby_releasedate: _,
    wishlist_controls_sortby_dateadded: _,
    wishlist_controls_sortby_reviews: _,
    wishlist_controls_sortby_price: _,
    wishlist_controls_sortby_name: _,
    wishlist_controls_sortby_discount: _,
    wishlist_controls_share_dialog_title: _,
    wishlist_controls_share_revokeall: _,
    wishlist_controls_share_revokeall_success: _,
    wishlist_controls_share_generation_failure: _,
    wishlist_controls_share_description: _,
    wishlist_controls_options_category_view: `Vy`,
    wishlist_controls_options_view_expanded: _,
    wishlist_controls_options_view_compact: _,
    wishlist_controls_options_category_platform: _,
    wishlist_controls_options_platform_all: _,
    wishlist_controls_options_platform_mac: _,
    wishlist_controls_options_platform_linux: _,
    wishlist_controls_options_category_type: _,
    wishlist_controls_options_type_game: _,
    wishlist_controls_options_type_application: _,
    wishlist_controls_options_type_dlc: `DLC`,
    wishlist_controls_options_type_video: _,
    wishlist_controls_options_category_price: _,
    wishlist_controls_options_category_discount: _,
    wishlist_controls_options_discount_all: _,
    wishlist_controls_options_discount_any: _,
    wishlist_controls_options_discount_or_more: _,
    wishlist_controls_options_price_any: _,
    wishlist_controls_options_price_max_price: _,
    wishlist_controls_options_price_free: _,
    wishlist_controls_options_category_exclude: _,
    wishlist_controls_options_category_related: _,
    genre_early_access: _,
    wishlist_controls_early_access_tooltip: _,
    category_prerelease: _,
    wishlist_controls_options_exclude_vr: _,
    wishlist_controls_demo_available: _,
    wishlist_controls_demo_available_tooltip: _,
    wishlist_controls_options_category_deck: _,
    wishlist_controls_options_deck_verified: _,
    wishlist_controls_options_deck_playable: _,
    wishlist_controls_options_category_tag: _,
    wishlist_controls_tag_description: _,
    wishlist_controls_tags_header: _,
    wishlist_controls_filter_tag_label: _,
    wishlist_controls_options_category_category: _,
    wishlist_controls_categories_header_anonymous: _,
    wishlist_controls_categories_multiselect_label: _,
    wishlist_controls_categories_add: _,
    wishlist_categories_advanced_title: _,
    wishlist_categories_advanced_select: _,
    wishlist_categories_advanced_rename_label: _,
    wishlist_categories_advanced_rename_save: _,
    wishlist_categories_advanced_rename_duplicate: _,
    wishlist_categories_advanced_rename_failed: _,
    wishlist_categories_advanced_no_items: _,
    wishlist_categories_advanced_select_all: _,
    wishlist_categories_advanced_select_none: _,
    wishlist_categories_advanced_showing: _,
    wishlist_categories_advanced_failed_items: _,
    wishlist_categories_advanced_failed_items_Plural: _,
    wishlist_categories_advanced_pending: _,
    wishlist_categories_advanced_pending_adds: _,
    wishlist_categories_advanced_pending_removals: _,
    wishlist_categories_advanced_revert: _,
    wishlist_categories_advanced_apply: _,
    wishlist_categories_advanced_addremove_title: _,
    wishlist_displayed_item_count: _,
    wishlist_displayed_item_count_Plural: _,
    wishlist_filter_results: _,
    wishlist_filter_matches_items: _,
    wishlist_filter_matches_items_Plural: _,
    wishlist_filter_matches_category: _,
    wishlist_filter_matches_category_Plural: _,
    wishlist_filter_matches_categories: _,
    wishlist_filter_matches_categories_Plural: _,
    wishlist_filter_matches_tag: _,
    wishlist_filter_matches_tag_Plural: _,
    wishlist_filter_matches_tags: _,
    wishlist_filter_matches_tags_Plural: _,
    wishlist_search: _,
    wishlist_search_all: _,
    wishlist_item_overallreviews: _,
    wishlist_item_languagespecific_reviews: _,
    wishlist_item_releasedate: _,
    wishlist_item_addedon_date: _,
    wishlist_item_remove: _,
    wishlist_item_remove_tooltip: _,
    wishlist_item_unavailable_title: _,
    wishlist_item_unavailable_region: _,
    wishlist_item_unavailable_retired: _,
    mature_content_requires_creditcard: _,
    mature_content_requires_creditcard_gb: _,
    wishlist_item_add_credit_card: _,
    wishlist_your_wishlist_empty: _,
    wishlist_browse_the_store: _,
    wishlist_learn_more_button: _,
    wishlist_sign_in_to_see_your_wishlist: _,
    wishlist_others_wishlist_empty: _,
    wishlist_no_items_matching_filters: _,
    wishlist_x_items_on_wishlist_but_none_match: _,
    wishlist_x_items_on_wishlist_but_none_match_prefs: _,
    wishlist_gamepaddragdrop_reorderaction: _,
    wishlist_gamepaddragdrop_cancelreorder: _,
    wishlist_gamepaddragdrop_commitreorder: _,
    wishlist_gamepad_options: _,
    wishlist_gamepad_options_remove: _,
    wishlist_gamepad_visitstore: _,
    wishlist_errorpage_title: _,
    errorpage_error: `Fel`,
    errorpage_unknownerror: _,
    wishlist_error_profilenotfound: _,
    wishlist_error_wishlistunavailable: _,
    wishlist_error_invalidsharetoken: _,
    wishlist_filters_notification: _,
    youraccount_users_account: _,
    youraccount_errorpage_title: _,
    youraccount_account: _,
    m_home: `Hem`,
    global_menu_account_details: _,
    global_menu_account_preferences: _,
    global_menu_account_language_preferences: _,
    global_menu_account_notification_settings: _,
    global_menu_account_hardware_used: _,
    global_menu_account_security_devices: _,
    global_menu_account_video_authorized_devices: _,
    global_menu_account_mobile_game_devices: _,
    global_menu_account_gated_access_games: _,
    accountpreferences_familymanagement_header: _,
    CookiePreferences: _,
    global_menu_vr: `VR`,
    global_menu_greatondeck: _,
    global_menu_localplayonframe: _,
    store_tab_foryou_store_home: _,
    browse_categories: _,
    m_search_steam: _,
    playteststatus_error_dataunavailable: _,
    playtestinvites_title: _,
    playtestinvites_accept: _,
    playtestinvites_reject: _,
    playtestinvites_invitedescription_fromapp2: _,
    playtestinvites_invitedescription_fromapp_limitedlaunch: _,
    playtestinvites_invitedescription_fromuser2: _,
    playtestinvites_invitedescription_fromuser_limitedlaunch: _,
    playtestinvites_noinvites: _,
    playtestinvites_welcome: _,
    playtestinvites_welcome_limitedlaunch: _,
    playtestinvites_welcome_notplayable: _,
    playtestinvites_viewlibrary: _,
    playtestinvites_desc_title: _,
    playtestinvites_desc1: _,
    playtestinvites_desc2: _,
    playtestinvites_ignored_title: _,
    playtestinvites_ignored_desc: _,
    playtestinvites_ignored_remove: _,
    playtestinvites_sendinvite_cancel: _,
    playtestinvites_sendinvite_send: _,
    playtestinvites_sendinvite_lastinvite: _,
    playtestinvites_sendinvite_lastinvite_limitedlaunch: _,
    playtestinvites_sendinvite_confirm_desc: _,
    playtestinvites_sendinvite_pending: _,
    playtestinvites_sendinvite_success: _,
    playtestinvites_sendinvite_failure: _,
    playtestinvitehistory_title: _,
    playtestinvitehistory_desc: _,
    playtestinvitehistory_invite_detail: _,
    playteststatus_title: _,
    playteststatus_none: _,
    playteststatus_invites_available: _,
    playteststatus_invite_count: _,
    playteststatus_invite_count_plural: _,
    playteststatus_invite_count_tooltip: _,
    playteststatus_invite_count_tooltip2: _,
    playteststatus_details_moreinfo: _,
    playteststatus_details_moreinfo_storepage: _,
    playteststatus_details_moreinfo_newshub: _,
    playteststatus_details_notplayable: _,
    playteststatus_details_allinvitesused: _,
    playteststatus_invitefriends: _,
    playteststatus_invitefrienddialog_header: _,
    playteststatus_invitefrienddialog_search_placeholder: _,
    playteststatus_invitefrienddialog_loadingerror: _,
    playteststatus_invitefrienddialog_ineligiblefriends: _,
    playteststatus_invitefrienddialog_ineligiblefriends_purchaser: _,
    gatedaccess_limitedlaunch_badge: _,
    gatedaccess_limitedlaunch_invite_count_tooltip: _,
    gatedaccess_limitedlaunch_details_moreinfo: _,
    gatedaccess_limitedlaunch_desc_title: _,
    gatedaccess_limitedlaunch_desc: _,
    sitemap_title: _,
    sitemap_home: _,
    sitemap_section_account: _,
    sitemap_section_account_account_details: _,
    sitemap_section_account_store_preferences: _,
    sitemap_section_account_family_management: _,
    sitemap_section_account_security_and_devices: _,
    sitemap_section_account_language_preferences: _,
    sitemap_section_account_cookes_and_browsing: _,
    sitemap_section_account_notification_settings: _,
    sitemap_section_account_cart: _,
    sitemap_section_account_cart_with_count: _,
    sitemap_section_account_wishlist: _,
    sitemap_section_account_wishlist_with_count: _,
    sitemap_section_account_followed_games: _,
    sitemap_section_account_followed_games_with_count: _,
    sitemap_section_chartsandlists: _,
    sitemap_section_chartsandlists_top_sellers: _,
    sitemap_section_chartsandlists_most_played: _,
    sitemap_section_chartsandlists_new_releases: _,
    sitemap_section_chartsandlists_upcoming_releases: _,
    sitemap_section_chartsandlists_free_to_play: _,
    sitemap_section_chartsandlists_steam_charts: _,
    sitemap_section_chartsandlists_on_sale_now: _,
    sitemap_section_recommendations: _,
    sitemap_section_recommendations_discovery_queue: _,
    sitemap_section_recommendations_new_releases_queue: _,
    sitemap_section_recommendations_community_recommendations: _,
    sitemap_section_recommendations_interactive_recommender: _,
    sitemap_section_recommendations_popular_among_friends: _,
    sitemap_section_recommendations_steam_curators: _,
    sitemap_section_recommendations_dlc_for_you: _,
    sitemap_section_hardware: _,
    sitemap_section_hardware_steam_deck: _,
    sitemap_section_hardware_steam_deck_dock: _,
    sitemap_section_hardware_vr_hardware: _,
    sitemap_section_hardware_vr_games: _,
    sitemap_section_hardware_great_on_deck: _,
    sitemap_section_hardware_controller_friendly: _,
    sitemap_section_waystoplay: _,
    sitemap_section_newsupdates: _,
    sitemap_section_newsupdates_recently_updated: _,
    sitemap_section_newsupdates_your_recently_updated: _,
    sitemap_section_newsupdates_your_upcoming_events: _,
    sitemap_section_newsupdates_featured_news: _,
    sitemap_section_newsupdates_steam_official_news: _,
    sitemap_section_promosandevents: _,
    sitemap_section_promosandevents_special_offers: _,
    sitemap_section_promosandevents_sale_events: _,
    sitemap_section_promosandevents_steam_replay: _,
    sitemap_section_promosandevents_steam_next_fest: _,
    sitemap_section_promosandevents_steam_awards: _,
    sitemap_section_specialsections: _,
    sitemap_pointsshop: _,
    sitemap_giftcards: _,
    sitemap_genres: _,
    sitemap_themes: _,
    Error_RateLimited: _,
    Discussions_ForumName_General: _,
    Discussions_ForumName_ReportedPosts: _,
    Discussions_ForumName_Workshop: _,
    Discussions_ForumName_Trading: _,
    Discussions_ForumName_Events: _,
    ir_name: _,
    ir_header: _,
    ir_body: _,
    ir_playtime_header: _,
    ir_playtime_games: _,
    ir_playtime_topgames: _,
    ir_playtime_recentgames: _,
    ir_playtime_hours: _,
    ir_playtime_hourstotal: _,
    ir_playtime_lastplayed: _,
    ir_playtime_lastplayedmax: _,
    ir_playtime_unignore: _,
    ir_playtime_ignore: _,
    ir_popularity_title: _,
    ir_popularity_popular: _,
    ir_popularity_niche: _,
    ir_recency_title: _,
    ir_recency_older: _,
    ir_recency_newer: _,
    ir_filter_age_all: _,
    ir_filter_age_60: _,
    ir_filter_age_36: _,
    ir_filter_age_24: _,
    ir_filter_age_12: _,
    ir_filter_age_6: _,
    ir_recommendations_header: _,
    ir_release_date: _,
    ir_on_wishlist: _,
    ir_add_to_cart: _,
    ir_add_to_wishlist: _,
    ir_free_to_play: _,
    ir_tag_placeholder: _,
    ir_tag_filter: _,
    ir_tag_exclude: _,
    ir_no_wishlisted: _,
    ir_discounted_only: _,
    PersonalCalendar_LastMonthGames: _,
    PersonalCalendar_LastWeekGames: _,
    PersonalCalendar_Upcoming: _,
    PersonalCalendar_Title: _,
    PersonalCalendar_Description: _,
    PersonalCalendar_TagSelector: _,
    PersonalCalendar_TagSelector_Placeholder: _,
    PersonalCalendar_HideOwned: _,
    PersonalCalendar_HideEATooltip: _,
    PersonalCalendar_HideEarlyAccess: _,
    PersonalCalendar_ShowOnlyWishlisted: _,
    PersonalCalendar_ResultCountSelector: _,
    PersonalCalendar_CompactMode: _,
    PersonalCalendar_AccountPlaceholder: _,
    PersonalCalendar_Account: _,
    PersonalCalendar_ShowMore: _,
    PersonalCalendar_LoginPrompt: _,
    PersonalCalendar_ShowAll: _,
    PersonalCalendar_SteamLabs: _,
    PersonalCalendar_Wishlisted: _,
    PersonalCalendar_WishlistShow: _,
    PersonalCalendar_WishlistHide: _,
    PersonalCalendar_WishlistOnly: _,
    PersonalCalendar_IgnoringWishlists: _,
    PersonalCalendar_Error_Backend: _,
    BundleList_Title: _,
    BundleList_Title_Fallback: _,
    BundleList_Page: _,
    Verification_DeckOnly: _,
    Verification_DeckOnly_Desc: _,
    FatalErrorPage_Title: _,
    FatalErrorPage_Header: _,
    FatalErrorPage_Message: _,
    pressoutlets_error_slots_gt_zero: _,
    pressoutlets_error_domain_used: _,
    pressoutlets_error_adding_outlet: _,
    pressoutlets_error_domain_empty: _,
    pressoutlets_error_invalid_domain: _,
    pressoutlets_error_already_owned: _,
    pressoutlets_error_generic_add_error: _,
    pressoutlets_email_domain_label: _,
    pressoutlets_slots_label: _,
    pressoutlets_button_add: _,
    pressoutlets_label_add_outlet: _,
    pressoutlets_outlet_header: _,
    pressoutlets_show_history: _,
    pressoutlets_history_title: _,
    pressoutlets_action_granted: _,
    pressoutlets_action_removed: _,
    pressoutlets_action_created: _,
    pressoutlets_action_updated: _,
    pressoutlets_action_updated_domain_changed: _,
    pressoutlets_action_updated_slots_changed: _,
    pressoutlets_action_deleted: _,
    pressoutlets_action_undeleted: _,
    pressoutlets_action_enterstaging: _,
    pressoutlets_action_exitstaging: _,
    pressoutlets_action_stagedadd: _,
    pressoutlets_action_stageddelete: _,
    pressoutlets_action_by_support: _,
    pressoutlets_header_grantee: _,
    pressoutlets_header_granted_at: _,
    pressoutlets_header_is_group_admin: _,
    pressoutlets_steamid_to_add: _,
    pressoutlets_button_ok: `OK`,
    pressoutlets_button_cancel: _,
    pressoutlets_is_group_admin: `Ja`,
    pressoutlets_is_not_group_admin: `Nej`,
    pressoutlets_filter_all: _,
    pressoutlets_filter_active: _,
    pressoutlets_filter_deleted: _,
    pressoutlets_filter_empty: _,
    pressoutlets_filter_noadmins: _,
    pressoutlets_outlet_header_prefix: _,
    pressoutlets_friendcode: _,
    pressoutlets_resign_your_key: _,
    pressoutlets_resign_your_key_title: _,
    pressoutlets_history_header: _,
    pressoutlets_button_add_member: _,
    pressoutlets_button_show_history: _,
    pressoutlets_header_account: _,
    trailerassets_invalidfile: _,
    trailerassets_trailer: _,
    trailerassets_microtrailer: _,
    account_notification_settings_error_saving: _,
    account_notification_settings_error_loading: _,
    account_notification_settings_error_invalidoptouttoken: _,
    account_notification_settings_feed_disabled: _,
    account_notification_settings_wishlist_categories_persona: _,
    framerate_title: _,
    framerate_subheader: _,
    framerate_cpu: `CPU`,
    framerate_ram: _,
    framerate_gpu: `GPU`,
    framerate_saved_hardware: _,
    framerate_saved_hardware_none: _,
    framerate_saved_hardware_select: _,
    framerate_saved_hardware_option_none: _,
    framerate_saved_add: _,
    framerate_saved_add_btn: _,
    framerate_saved_add_not_in_client_btn: _,
    framerate_opt_in_data_collection_desc: _,
    framerate_opt_in_link: _,
    framerate_fps: `FPS`,
    framerate_game_name: _,
    framerate_select_cpu: _,
    framerate_select_gpu: _,
    framerate_training_game: _,
    framerate_training_cpu: _,
    framerate_training_gpu: _,
    generic_unknown: _,
    giftcards_banner_text: _,
    empty_no_trailing_comma: ``,
  };
export {
  _ as BundleList_AllInLibrary,
  _ as BundleList_AllInLibrarySubtitle,
  _ as BundleList_CompleteTheSet,
  _ as BundleList_CompleteTheSetSubtitle,
  _ as BundleList_MustPurchaseAsSet,
  _ as BundleList_MustPurchaseAsSetSubtitle,
  _ as BundleList_Page,
  _ as BundleList_SortBy,
  _ as BundleList_SortBy_Discount,
  _ as BundleList_SortBy_Name,
  _ as BundleList_SortBy_Popular,
  _ as BundleList_SortBy_Price,
  _ as BundleList_SortBy_Recommend,
  _ as BundleList_SubTitle,
  _ as BundleList_Title,
  _ as BundleList_Title_Fallback,
  _ as CookiePreferences,
  _ as Discussions_ForumName_Events,
  _ as Discussions_ForumName_General,
  _ as Discussions_ForumName_ReportedPosts,
  _ as Discussions_ForumName_Trading,
  _ as Discussions_ForumName_Workshop,
  _ as Error_RateLimited,
  _ as FatalErrorPage_Header,
  _ as FatalErrorPage_Message,
  _ as FatalErrorPage_Title,
  _ as PersonalCalendar_Account,
  _ as PersonalCalendar_AccountPlaceholder,
  _ as PersonalCalendar_CompactMode,
  _ as PersonalCalendar_Description,
  _ as PersonalCalendar_Error_Backend,
  _ as PersonalCalendar_HideEATooltip,
  _ as PersonalCalendar_HideEarlyAccess,
  _ as PersonalCalendar_HideOwned,
  _ as PersonalCalendar_IgnoringWishlists,
  _ as PersonalCalendar_LastMonthGames,
  _ as PersonalCalendar_LastWeekGames,
  _ as PersonalCalendar_LoginPrompt,
  _ as PersonalCalendar_ResultCountSelector,
  _ as PersonalCalendar_ShowAll,
  _ as PersonalCalendar_ShowMore,
  _ as PersonalCalendar_ShowOnlyWishlisted,
  _ as PersonalCalendar_SteamLabs,
  _ as PersonalCalendar_TagSelector,
  _ as PersonalCalendar_TagSelector_Placeholder,
  _ as PersonalCalendar_Title,
  _ as PersonalCalendar_Upcoming,
  _ as PersonalCalendar_WishlistHide,
  _ as PersonalCalendar_WishlistOnly,
  _ as PersonalCalendar_WishlistShow,
  _ as PersonalCalendar_Wishlisted,
  _ as Verification_DeckOnly,
  _ as Verification_DeckOnly_Desc,
  _ as account_notification_settings_error_invalidoptouttoken,
  _ as account_notification_settings_error_loading,
  _ as account_notification_settings_error_saving,
  _ as account_notification_settings_feed_disabled,
  _ as account_notification_settings_wishlist_categories_persona,
  _ as accountpreferences_familymanagement_header,
  _ as browse_categories,
  _ as cart_count,
  _ as cart_view_cart,
  _ as category_prerelease,
  _ as default,
  _ as empty_no_trailing_comma,
  _ as errorpage_error,
  _ as errorpage_unknownerror,
  _ as footer_about_valve,
  _ as footer_accessibility,
  _ as footer_business_solutions,
  _ as footer_cookies,
  _ as footer_jobs,
  _ as footer_legal,
  _ as footer_legal_notice,
  _ as footer_nav_help_support,
  _ as footer_privacy_policy,
  _ as footer_recycling,
  _ as footer_refunds,
  _ as footer_source_engine,
  _ as footer_ssa,
  _ as footer_steam_distribution,
  _ as footer_steamworks,
  _ as footer_vat_included,
  _ as footer_walletcode,
  _ as framerate_cpu,
  _ as framerate_fps,
  _ as framerate_game_name,
  _ as framerate_gpu,
  _ as framerate_opt_in_data_collection_desc,
  _ as framerate_opt_in_link,
  _ as framerate_ram,
  _ as framerate_saved_add,
  _ as framerate_saved_add_btn,
  _ as framerate_saved_add_not_in_client_btn,
  _ as framerate_saved_hardware,
  _ as framerate_saved_hardware_none,
  _ as framerate_saved_hardware_option_none,
  _ as framerate_saved_hardware_select,
  _ as framerate_select_cpu,
  _ as framerate_select_gpu,
  _ as framerate_subheader,
  _ as framerate_title,
  _ as framerate_training_cpu,
  _ as framerate_training_game,
  _ as framerate_training_gpu,
  _ as gatedaccess_limitedlaunch_badge,
  _ as gatedaccess_limitedlaunch_desc,
  _ as gatedaccess_limitedlaunch_desc_title,
  _ as gatedaccess_limitedlaunch_details_moreinfo,
  _ as gatedaccess_limitedlaunch_invite_count_tooltip,
  _ as generic_unknown,
  _ as genre_early_access,
  _ as giftcards_banner_text,
  _ as global_menu_account_details,
  _ as global_menu_account_gated_access_games,
  _ as global_menu_account_hardware_used,
  _ as global_menu_account_language_preferences,
  _ as global_menu_account_mobile_game_devices,
  _ as global_menu_account_notification_settings,
  _ as global_menu_account_preferences,
  _ as global_menu_account_security_devices,
  _ as global_menu_account_video_authorized_devices,
  _ as global_menu_greatondeck,
  _ as global_menu_localplayonframe,
  _ as global_menu_vr,
  _ as ir_add_to_cart,
  _ as ir_add_to_wishlist,
  _ as ir_body,
  _ as ir_discounted_only,
  _ as ir_filter_age_12,
  _ as ir_filter_age_24,
  _ as ir_filter_age_36,
  _ as ir_filter_age_6,
  _ as ir_filter_age_60,
  _ as ir_filter_age_all,
  _ as ir_free_to_play,
  _ as ir_header,
  _ as ir_name,
  _ as ir_no_wishlisted,
  _ as ir_on_wishlist,
  _ as ir_playtime_games,
  _ as ir_playtime_header,
  _ as ir_playtime_hours,
  _ as ir_playtime_hourstotal,
  _ as ir_playtime_ignore,
  _ as ir_playtime_lastplayed,
  _ as ir_playtime_lastplayedmax,
  _ as ir_playtime_recentgames,
  _ as ir_playtime_topgames,
  _ as ir_playtime_unignore,
  _ as ir_popularity_niche,
  _ as ir_popularity_popular,
  _ as ir_popularity_title,
  _ as ir_recency_newer,
  _ as ir_recency_older,
  _ as ir_recency_title,
  _ as ir_recommendations_header,
  _ as ir_release_date,
  _ as ir_tag_exclude,
  _ as ir_tag_filter,
  _ as ir_tag_placeholder,
  _ as m_home,
  _ as m_search_steam,
  _ as mature_content_requires_creditcard,
  _ as mature_content_requires_creditcard_gb,
  _ as playtestinvitehistory_desc,
  _ as playtestinvitehistory_invite_detail,
  _ as playtestinvitehistory_title,
  _ as playtestinvites_accept,
  _ as playtestinvites_desc1,
  _ as playtestinvites_desc2,
  _ as playtestinvites_desc_title,
  _ as playtestinvites_ignored_desc,
  _ as playtestinvites_ignored_remove,
  _ as playtestinvites_ignored_title,
  _ as playtestinvites_invitedescription_fromapp2,
  _ as playtestinvites_invitedescription_fromapp_limitedlaunch,
  _ as playtestinvites_invitedescription_fromuser2,
  _ as playtestinvites_invitedescription_fromuser_limitedlaunch,
  _ as playtestinvites_noinvites,
  _ as playtestinvites_reject,
  _ as playtestinvites_sendinvite_cancel,
  _ as playtestinvites_sendinvite_confirm_desc,
  _ as playtestinvites_sendinvite_failure,
  _ as playtestinvites_sendinvite_lastinvite,
  _ as playtestinvites_sendinvite_lastinvite_limitedlaunch,
  _ as playtestinvites_sendinvite_pending,
  _ as playtestinvites_sendinvite_send,
  _ as playtestinvites_sendinvite_success,
  _ as playtestinvites_title,
  _ as playtestinvites_viewlibrary,
  _ as playtestinvites_welcome,
  _ as playtestinvites_welcome_limitedlaunch,
  _ as playtestinvites_welcome_notplayable,
  _ as playteststatus_details_allinvitesused,
  _ as playteststatus_details_moreinfo,
  _ as playteststatus_details_moreinfo_newshub,
  _ as playteststatus_details_moreinfo_storepage,
  _ as playteststatus_details_notplayable,
  _ as playteststatus_error_dataunavailable,
  _ as playteststatus_invite_count,
  _ as playteststatus_invite_count_plural,
  _ as playteststatus_invite_count_tooltip,
  _ as playteststatus_invite_count_tooltip2,
  _ as playteststatus_invitefrienddialog_header,
  _ as playteststatus_invitefrienddialog_ineligiblefriends,
  _ as playteststatus_invitefrienddialog_ineligiblefriends_purchaser,
  _ as playteststatus_invitefrienddialog_loadingerror,
  _ as playteststatus_invitefrienddialog_search_placeholder,
  _ as playteststatus_invitefriends,
  _ as playteststatus_invites_available,
  _ as playteststatus_none,
  _ as playteststatus_title,
  _ as pressoutlets_action_by_support,
  _ as pressoutlets_action_created,
  _ as pressoutlets_action_deleted,
  _ as pressoutlets_action_enterstaging,
  _ as pressoutlets_action_exitstaging,
  _ as pressoutlets_action_granted,
  _ as pressoutlets_action_removed,
  _ as pressoutlets_action_stagedadd,
  _ as pressoutlets_action_stageddelete,
  _ as pressoutlets_action_undeleted,
  _ as pressoutlets_action_updated,
  _ as pressoutlets_action_updated_domain_changed,
  _ as pressoutlets_action_updated_slots_changed,
  _ as pressoutlets_button_add,
  _ as pressoutlets_button_add_member,
  _ as pressoutlets_button_cancel,
  _ as pressoutlets_button_ok,
  _ as pressoutlets_button_show_history,
  _ as pressoutlets_email_domain_label,
  _ as pressoutlets_error_adding_outlet,
  _ as pressoutlets_error_already_owned,
  _ as pressoutlets_error_domain_empty,
  _ as pressoutlets_error_domain_used,
  _ as pressoutlets_error_generic_add_error,
  _ as pressoutlets_error_invalid_domain,
  _ as pressoutlets_error_slots_gt_zero,
  _ as pressoutlets_filter_active,
  _ as pressoutlets_filter_all,
  _ as pressoutlets_filter_deleted,
  _ as pressoutlets_filter_empty,
  _ as pressoutlets_filter_noadmins,
  _ as pressoutlets_friendcode,
  _ as pressoutlets_header_account,
  _ as pressoutlets_header_granted_at,
  _ as pressoutlets_header_grantee,
  _ as pressoutlets_header_is_group_admin,
  _ as pressoutlets_history_header,
  _ as pressoutlets_history_title,
  _ as pressoutlets_is_group_admin,
  _ as pressoutlets_is_not_group_admin,
  _ as pressoutlets_label_add_outlet,
  _ as pressoutlets_outlet_header,
  _ as pressoutlets_outlet_header_prefix,
  _ as pressoutlets_resign_your_key,
  _ as pressoutlets_resign_your_key_title,
  _ as pressoutlets_show_history,
  _ as pressoutlets_slots_label,
  _ as pressoutlets_steamid_to_add,
  _ as sitemap_genres,
  _ as sitemap_giftcards,
  _ as sitemap_home,
  _ as sitemap_pointsshop,
  _ as sitemap_section_account,
  _ as sitemap_section_account_account_details,
  _ as sitemap_section_account_cart,
  _ as sitemap_section_account_cart_with_count,
  _ as sitemap_section_account_cookes_and_browsing,
  _ as sitemap_section_account_family_management,
  _ as sitemap_section_account_followed_games,
  _ as sitemap_section_account_followed_games_with_count,
  _ as sitemap_section_account_language_preferences,
  _ as sitemap_section_account_notification_settings,
  _ as sitemap_section_account_security_and_devices,
  _ as sitemap_section_account_store_preferences,
  _ as sitemap_section_account_wishlist,
  _ as sitemap_section_account_wishlist_with_count,
  _ as sitemap_section_chartsandlists,
  _ as sitemap_section_chartsandlists_free_to_play,
  _ as sitemap_section_chartsandlists_most_played,
  _ as sitemap_section_chartsandlists_new_releases,
  _ as sitemap_section_chartsandlists_on_sale_now,
  _ as sitemap_section_chartsandlists_steam_charts,
  _ as sitemap_section_chartsandlists_top_sellers,
  _ as sitemap_section_chartsandlists_upcoming_releases,
  _ as sitemap_section_hardware,
  _ as sitemap_section_hardware_controller_friendly,
  _ as sitemap_section_hardware_great_on_deck,
  _ as sitemap_section_hardware_steam_deck,
  _ as sitemap_section_hardware_steam_deck_dock,
  _ as sitemap_section_hardware_vr_games,
  _ as sitemap_section_hardware_vr_hardware,
  _ as sitemap_section_newsupdates,
  _ as sitemap_section_newsupdates_featured_news,
  _ as sitemap_section_newsupdates_recently_updated,
  _ as sitemap_section_newsupdates_steam_official_news,
  _ as sitemap_section_newsupdates_your_recently_updated,
  _ as sitemap_section_newsupdates_your_upcoming_events,
  _ as sitemap_section_promosandevents,
  _ as sitemap_section_promosandevents_sale_events,
  _ as sitemap_section_promosandevents_special_offers,
  _ as sitemap_section_promosandevents_steam_awards,
  _ as sitemap_section_promosandevents_steam_next_fest,
  _ as sitemap_section_promosandevents_steam_replay,
  _ as sitemap_section_recommendations,
  _ as sitemap_section_recommendations_community_recommendations,
  _ as sitemap_section_recommendations_discovery_queue,
  _ as sitemap_section_recommendations_dlc_for_you,
  _ as sitemap_section_recommendations_interactive_recommender,
  _ as sitemap_section_recommendations_new_releases_queue,
  _ as sitemap_section_recommendations_popular_among_friends,
  _ as sitemap_section_recommendations_steam_curators,
  _ as sitemap_section_specialsections,
  _ as sitemap_section_waystoplay,
  _ as sitemap_themes,
  _ as sitemap_title,
  _ as store_tab_foryou_store_home,
  _ as trailerassets_invalidfile,
  _ as trailerassets_microtrailer,
  _ as trailerassets_trailer,
  _ as wishlist_browse_the_store,
  _ as wishlist_categories_advanced_addremove_title,
  _ as wishlist_categories_advanced_apply,
  _ as wishlist_categories_advanced_failed_items,
  _ as wishlist_categories_advanced_failed_items_Plural,
  _ as wishlist_categories_advanced_no_items,
  _ as wishlist_categories_advanced_pending,
  _ as wishlist_categories_advanced_pending_adds,
  _ as wishlist_categories_advanced_pending_removals,
  _ as wishlist_categories_advanced_rename_duplicate,
  _ as wishlist_categories_advanced_rename_failed,
  _ as wishlist_categories_advanced_rename_label,
  _ as wishlist_categories_advanced_rename_save,
  _ as wishlist_categories_advanced_revert,
  _ as wishlist_categories_advanced_select,
  _ as wishlist_categories_advanced_select_all,
  _ as wishlist_categories_advanced_select_none,
  _ as wishlist_categories_advanced_showing,
  _ as wishlist_categories_advanced_title,
  _ as wishlist_controls_categories_add,
  _ as wishlist_controls_categories_header_anonymous,
  _ as wishlist_controls_categories_multiselect_label,
  _ as wishlist_controls_demo_available,
  _ as wishlist_controls_demo_available_tooltip,
  _ as wishlist_controls_early_access_tooltip,
  _ as wishlist_controls_filter_tag_label,
  _ as wishlist_controls_options_category_category,
  _ as wishlist_controls_options_category_deck,
  _ as wishlist_controls_options_category_discount,
  _ as wishlist_controls_options_category_exclude,
  _ as wishlist_controls_options_category_platform,
  _ as wishlist_controls_options_category_price,
  _ as wishlist_controls_options_category_related,
  _ as wishlist_controls_options_category_tag,
  _ as wishlist_controls_options_category_type,
  _ as wishlist_controls_options_category_view,
  _ as wishlist_controls_options_deck_playable,
  _ as wishlist_controls_options_deck_verified,
  _ as wishlist_controls_options_discount_all,
  _ as wishlist_controls_options_discount_any,
  _ as wishlist_controls_options_discount_or_more,
  _ as wishlist_controls_options_exclude_vr,
  _ as wishlist_controls_options_platform_all,
  _ as wishlist_controls_options_platform_linux,
  _ as wishlist_controls_options_platform_mac,
  _ as wishlist_controls_options_price_any,
  _ as wishlist_controls_options_price_free,
  _ as wishlist_controls_options_price_max_price,
  _ as wishlist_controls_options_type_application,
  _ as wishlist_controls_options_type_dlc,
  _ as wishlist_controls_options_type_game,
  _ as wishlist_controls_options_type_video,
  _ as wishlist_controls_options_view_compact,
  _ as wishlist_controls_options_view_expanded,
  _ as wishlist_controls_share_description,
  _ as wishlist_controls_share_dialog_title,
  _ as wishlist_controls_share_generation_failure,
  _ as wishlist_controls_share_revokeall,
  _ as wishlist_controls_share_revokeall_success,
  _ as wishlist_controls_sortby_dateadded,
  _ as wishlist_controls_sortby_discount,
  _ as wishlist_controls_sortby_name,
  _ as wishlist_controls_sortby_order,
  _ as wishlist_controls_sortby_price,
  _ as wishlist_controls_sortby_releasedate,
  _ as wishlist_controls_sortby_reviews,
  _ as wishlist_controls_sortby_their_order,
  _ as wishlist_controls_sortby_topsellers,
  _ as wishlist_controls_tag_description,
  _ as wishlist_controls_tags_header,
  _ as wishlist_count,
  _ as wishlist_displayed_item_count,
  _ as wishlist_displayed_item_count_Plural,
  _ as wishlist_error_invalidsharetoken,
  _ as wishlist_error_profilenotfound,
  _ as wishlist_error_wishlistunavailable,
  _ as wishlist_errorpage_title,
  _ as wishlist_filter_matches_categories,
  _ as wishlist_filter_matches_categories_Plural,
  _ as wishlist_filter_matches_category,
  _ as wishlist_filter_matches_category_Plural,
  _ as wishlist_filter_matches_items,
  _ as wishlist_filter_matches_items_Plural,
  _ as wishlist_filter_matches_tag,
  _ as wishlist_filter_matches_tag_Plural,
  _ as wishlist_filter_matches_tags,
  _ as wishlist_filter_matches_tags_Plural,
  _ as wishlist_filter_results,
  _ as wishlist_filters_notification,
  _ as wishlist_gamepad_options,
  _ as wishlist_gamepad_options_remove,
  _ as wishlist_gamepad_visitstore,
  _ as wishlist_gamepaddragdrop_cancelreorder,
  _ as wishlist_gamepaddragdrop_commitreorder,
  _ as wishlist_gamepaddragdrop_reorderaction,
  _ as wishlist_header,
  _ as wishlist_item_add_credit_card,
  _ as wishlist_item_addedon_date,
  _ as wishlist_item_languagespecific_reviews,
  _ as wishlist_item_overallreviews,
  _ as wishlist_item_releasedate,
  _ as wishlist_item_remove,
  _ as wishlist_item_remove_tooltip,
  _ as wishlist_item_unavailable_region,
  _ as wishlist_item_unavailable_retired,
  _ as wishlist_item_unavailable_title,
  _ as wishlist_learn_more_button,
  _ as wishlist_no_items_matching_filters,
  _ as wishlist_options_button,
  _ as wishlist_others_wishlist_empty,
  _ as wishlist_search,
  _ as wishlist_search_all,
  _ as wishlist_share_tooltip,
  _ as wishlist_sign_in_to_see_your_wishlist,
  _ as wishlist_sortby_button,
  _ as wishlist_title,
  _ as wishlist_x_items_on_wishlist_but_none_match,
  _ as wishlist_x_items_on_wishlist_but_none_match_prefs,
  _ as wishlist_your_wishlist_empty,
  _ as youraccount_account,
  _ as youraccount_errorpage_title,
  _ as youraccount_users_account,
};
