var _ = `Toate seturile care conțin:`,
  _ = `Sortează după:`,
  _ = `Popularitate`,
  _ = `Preț`,
  _ = `Reducerea pentru set`,
  _ = `Nume`,
  _ = `Recomandate`,
  _ = `Seturile tale complete`,
  _ = `Întregul conținut al acestor seturi se află în biblioteca ta`,
  _ = `Seturi pentru completarea colecției`,
  _ = `Achiziționează restul titlurilor care nu se află în biblioteca ta pentru a completa setul.`,
  _ = `Seturi de tip „Trebuie achiziționate împreună”`,
  _ = `Include toate articolele împreună ca un singur set; setul trebuie achiziționat ca o colecție completă.`,
  _ = `© %1$s Valve Corporation. Toate drepturile rezervate. Toate mărcile comerciale sunt proprietatea deținătorilor respectivi din SUA și celelalte țări.`,
  _ = `TVA inclus în toate prețurile, după caz.`,
  _ = `Politica de confidențialitate`,
  _ = `Mențiuni legale`,
  _ = `Accesibilitate`,
  _ = `Acordul Steam pentru abonați`,
  _ = `Rambursări`,
  _ = `Cookie-uri`,
  _ = `Despre Valve`,
  _ = `Soluții pentru afaceri`,
  _ = `Reciclare`,
  _ = `Steamworks`,
  _ = `Motorul Source`,
  _ = `Angajări`,
  _ = `Carduri cadou`,
  _ = `Distribuire pe Steam`,
  _ = `Asistență`,
  _ = `Lista de dorințe a lui %1$s`,
  _ = `LISTA DE DORINȚE A LUI %1$s`,
  _ = `Coș (%1$s)`,
  _ = `Vezi coșul`,
  _ = `Lista de dorințe (%1$s)`,
  _ = `Opțiuni`,
  _ = `Sortează după: %1$s`,
  _ = `Creează un link ce poate fi distribuit`,
  _ = `Ordonarea personalizată`,
  _ = `Ordinea preferințelor`,
  _ = `Cele mai vândute`,
  _ = `Data de lansare`,
  _ = `Data adăugării`,
  _ = `Scorul recenziilor`,
  _ = `Preț`,
  _ = `Nume`,
  _ = `Reducere`,
  _ = `Link partajabil`,
  _ = `Revocă toate linkurile`,
  _ = `Linkuri revocate!`,
  _ = `Linkul partajabil nu a putut fi generat (eroare: %1$s)`,
  _ = `Toate persoanele care au acest link îți vor putea vedea lista de dorințe cu filtrele actuale, indiferent de setările de vizibilitate ale profilului tău, dar nu vor putea modifica filtrele.`,
  _ = `Vizualizare`,
  _ = `Extins`,
  _ = `Compact`,
  _ = `Platformă`,
  _ = `Orice SO`,
  _ = `macOS`,
  _ = `SteamOS + Linux`,
  _ = `Tip`,
  _ = `Jocuri`,
  _ = `Software`,
  _ = `DLC-uri`,
  _ = `Conținut video`,
  _ = `Preț`,
  _ = `Reduceri`,
  _ = `Toate articolele din listă`,
  _ = `Toate articolele cu reduceri`,
  _ = `%1$s% sau mai mult`,
  _ = `Orice preț`,
  _ = `Sub %1$s`,
  _ = `Gratuite`,
  _ = `Exclude`,
  _ = `Articole asociate`,
  _ = `Acces timpuriu`,
  _ = `Acest titlu este în prezent în acces timpuriu.`,
  _ = `Prelansări`,
  _ = `Doar RV`,
  _ = `Demo disponibil`,
  _ = `Filtrează-ți lista de dorințe în funcție de articole cu demouri`,
  _ = `Compatibilitatea cu Steam Deck`,
  _ = `Verificat`,
  _ = `Jucabil`,
  _ = `Etichetă`,
  _ = `Filtrează-ți articolele din lista ta de dorințe care au eticheta aceasta`,
  _ = `Etichetele utilizatorilor:`,
  _ = `%1$s: %2$s`,
  _ = `Categorie`,
  _ = `Categorii:`,
  _ = `<1>Categorii:</1> <2>%1$s</2>`,
  _ = `Adaugă o categorie`,
  _ = `Gestionare avansată a categoriilor`,
  _ = `SELECTEAZĂ O CATEGORIE PENTRU A O EDITA`,
  _ = `NUMELE CATEGORIEI`,
  _ = `Redenumește`,
  _ = `Ai deja o categorie cu acest nume.`,
  _ = `A apărut o eroare la redenumirea acestei categorii (cod: %1$s).`,
  _ = `Niciun articol din lista de dorințe nu corespunde căutării tale.`,
  _ = `Toate`,
  _ = `Niciuna`,
  _ = `Se afișează primele %1$s din %2$s articole. Efectuează o căutare pentru a restrânge lista.`,
  _ = `%1$s articol nu a putut fi actualizat.`,
  _ = `%1$s articole nu au putut fi actualizate.`,
  _ = `În aşteptare`,
  _ = `Adăugări: %1$s`,
  _ = `Eliminări: %1$s`,
  _ = `Anulează`,
  _ = `Aplică modificările`,
  _ = `ADAUGĂ/ELIMINĂ O CATEGORIE`,
  _ = `%1$s ARTICOL`,
  _ = `%1$s ARTICOLE`,
  _ = `Rezultatele căutării:`,
  _ = `%1$s articol care conține în denumire „%2$s”`,
  _ = `%1$s articole care conțin în denumire „%2$s”`,
  _ = `%1$s articol din categoria „%2$s”`,
  _ = `%1$s articole din categoria „%2$s”`,
  _ = `%1$s articol din categoriile care conțin „%2$s”`,
  _ = `%1$s articole din categoriile care conțin „%2$s”`,
  _ = `%1$s articol cu eticheta „%2$s”`,
  _ = `%1$s articole cu eticheta „%2$s”`,
  _ = `%1$s articol cu etichete care conțin „%2$s”`,
  _ = `%1$s articole cu etichete care conțin „%2$s”`,
  _ = `Caută după nume sau etichetă`,
  _ = `Căutare după nume, etichetă sau categorie`,
  _ = `Recenzii generale:`,
  _ = `Recenzii în %1$s:`,
  _ = `Data de lansare:`,
  _ = `Adăugat pe %1$s`,
  _ = `elimină`,
  _ = `Elimină acest produs din lista ta de dorințe.`,
  _ = `(articol indisponibil)`,
  _ = `Articolul acesta nu este disponibil în regiunea ta.`,
  _ = `Articolul acesta nu mai este disponibil.`,
  _ = `Conținutul destinat publicului matur nu este permis în țara ta pentru utilizatorii sub 18 ani. Valve are obligația să se asigure că ai minim 18 ani înainte de a accesa conținut destinat publicului matur.`,
  _ = `Conform legii privind siguranța online (Online Safety Act) din Regatul Unit, Valve are obligația să se asigure că ai minim 18 ani înainte de a accesa conținut sexual destinat publicului matur.`,
  _ = `Adaugă un card de credit`,
  _ = `Lista ta de dorințe e goală.`,
  _ = `Explorează magazinul și utilizează butonul „Adaugă în lista de dorințe” pentru a-ți completa lista de dorințe.`,
  _ = `Află mai multe despre listele de dorințe Steam`,
  _ = `Conectează-te pentru a-ți accesa lista de dorințe`,
  _ = `Această listă de dorințe e goală.`,
  _ = `Niciun articol corespunzător.`,
  _ = `Există %1$s articole în lista aceasta de dorințe, dar niciunul nu corespunde filtrelor listei tale de dorințe și/sau preferințelor tale pentru magazin.`,
  _ = `Există %1$s articole în lista aceasta de dorințe, dar niciunul nu corespunde filtrelor listei tale de dorințe și/sau <1>preferințelor tale pentru magazin</1>.`,
  _ = `Reordonează`,
  _ = `Anulează reordonarea`,
  _ = `Trage aici`,
  _ = `Opțiuni`,
  _ = `Elimină`,
  _ = `Accesează pagina din magazin`,
  _ = `Listă de dorințe – Eroare`,
  _ = `Eroare`,
  _ = `Eroare necunoscută`,
  _ = `Profilul nu a fost găsit`,
  _ = `Lista de dorințe a utilizatorului nu a putut fi încărcată.`,
  _ = `Acest link de partajare a listei de dorințe este nevalid sau a expirat.`,
  _ = `Notificări pentru jocurile din lista de dorințe`,
  _ = `Cont: %1$s`,
  _ = `Cont – eroare`,
  _ = `Cont`,
  _ = `Pagina principală`,
  _ = `Detalii privind contul`,
  _ = `Preferințe pentru magazin`,
  _ = `Preferințe de limbă`,
  _ = `Setări pentru notificări`,
  _ = `Dispozitive`,
  _ = `Securitate și dispozitive`,
  _ = `Dispozitive autorizate (video)`,
  _ = `Dispozitive mobile de joc`,
  _ = `Playteste`,
  _ = `Gestionarea familiei`,
  _ = `Date și navigare`,
  _ = `RV`,
  _ = `Impecabile pe Deck`,
  _ = `Rulare locală pe Frame`,
  _ = `Pagina principală a magazinului`,
  _ = `Categorii`,
  _ = `Caută pe Steam`,
  _ = `Datele despre accesul limitat nu au putut fi încărcate.`,
  _ = `Invitații pentru playteste`,
  _ = `Acceptă invitația`,
  _ = `Refuză invitația`,
  _ = `Ai primit o invitație pentru a participa la un Steam Playtest!`,
  _ = `Ai fost invitat să participi la o lansare limitată!`,
  _ = `%1$s te-a invitat să participi la un Steam Playtest!`,
  _ = `%1$s te-a invitat să participi la o lansare limitată!`,
  _ = `Nu ai nicio invitație pentru vreun Steam Playtest sau o lansare limitată care să aștepte răspunsul tău.`,
  _ = `Bun-venit la playtest! Acum poți instala %1$s din biblioteca ta.`,
  _ = `Bun-venit la lansarea limitată! Acum poți instala %1$s din biblioteca ta.`,
  _ = `Bun-venit la playtest! Playtestul %1$s nu este momentan activ. Urmărește dezvoltatorul pentru a afla mai multe despre planurile de lansare viitoare ale acestuia.`,
  _ = `Vezi biblioteca`,
  _ = `Ce este un Steam Playtest?`,
  _ = `Un Steam Playtest este folosit pentru a ajuta la testarea jocurilor care se află încă în dezvoltare. În urma acceptării unei invitații sau obținerii accesului de la un dezvoltator, jocul va fi adăugat în mod automat în biblioteca ta.`,
  _ = `Te rugăm să consulți informațiile oferite de dezvoltatori cu privire la natura fiecărui playtest. Accesul oferit de un Steam Playtest nu-ți va garanta acces la jocul complet atunci când acesta se va lansa.`,
  _ = `Invitații ignorate pentru playteste`,
  _ = `Ai respins invitația de a participa la un playtest sau o lansare limitată pentru următoarele jocuri. Nu vei mai primi invitații până când nu le vei elimina din această listă.`,
  _ = `Elimină`,
  _ = `Anulează`,
  _ = `Trimite`,
  _ = `Aceasta este ultima ta invitație disponibilă pentru acest playtest.`,
  _ = `Aceasta este ultima ta invitație disponibilă pentru această testare limitată.`,
  _ = `Vei trimite o invitație către:`,
  _ = `Se trimite invitația către %1$s...`,
  _ = `%1$s a primit o invitație! Aceasta va apărea în notificările sale %2$s.`,
  _ = `%1$s nu a putut fi invitat. Este posibil ca persoana respectivă să fi fost invitată deja sau jocul nu e disponibil în regiunea sa.`,
  _ = `Istoricul invitațiilor trimise`,
  _ = `Invitațiile recente pe care le-ai trimis prietenilor pentru playteste și lansări limitate.`,
  _ = `%1$s a primit o invitație de la tine pentru %2$s.`,
  _ = `Participare la Steam Playtest`,
  _ = `Nu te-ai alăturat niciunui Steam Playtest sau vreunei lansări limitate aflată în desfășurare.`,
  _ = `Ai invitații disponibile`,
  _ = `Ai o invitație disponibilă`,
  _ = `Ai %1$s invitații disponibile`,
  _ = `Le poți oferi prietenilor acces la playtest invitându-i.`,
  _ = `Numărul de invitații disponibile se poate modifica pe măsură ce se alătură mai mulți jucători.`,
  _ = `Mai multe detalii, precum programul și conținutul inclus, pot fi disponibile pe %1$s sau în %2$s.`,
  _ = `pagina din magazin`,
  _ = `centrul de știri`,
  _ = `Acest playtest nu este momentan activ.`,
  _ = `Ai utilizat toate invitațiile pentru prieteni.`,
  _ = `Invită prieteni`,
  _ = `Selectează destinatarul invitației`,
  _ = `Caută după numele prietenului...`,
  _ = `Prietenii tăi nu au putut fi încărcați.`,
  _ = `Unii prieteni nu pot fi invitați deoarece aceștia nu se află în lista ta de prieteni de cel puțin 30 de zile, au deja acces la joc sau nu sunt eligibili din alte motive.`,
  _ = `Unii prieteni nu pot fi invitați deoarece aceștia au deja acces la joc sau nu sunt eligibili din alte motive.`,
  _ = `Lansare limitată`,
  _ = `Le poți oferi prietenilor acces la lansarea limitată invitându-i.`,
  _ = `%1$s oferă treptat acces cât mai multor jucători pe durata unei lansări limitate inițiale. Mai multe detalii sunt disponibile pe %2$s sau în %3$s.`,
  _ = `Ce este lansarea limitată?`,
  _ = `Lansarea limitată este utilizată de unele jocuri gratuite pentru a mări gradual numărul de jucători pe durata lansării sale inițiale. Dacă accepți o invitație sau dezvoltatorul îți acceptă o solicitare de acces, titlul va fi adăugat în biblioteca ta și vei putea începe să-l joci imediat.`,
  _ = `Harta magazinului Steam`,
  _ = `Pagina principală a magazinului`,
  _ = `Contul meu`,
  _ = `Detalii privind contul meu`,
  _ = `Preferințele mele pentru magazin`,
  _ = `Gestionarea familiei`,
  _ = `Securitate și dispozitive`,
  _ = `Preferințe de limbă`,
  _ = `Cookie-uri și navigare`,
  _ = `Setări pentru notificări`,
  _ = `Coș`,
  _ = `Coș (%1$s)`,
  _ = `Lista de dorințe`,
  _ = `Lista de dorințe (%1$s)`,
  _ = `Jocurile și software-urile urmărite`,
  _ = `Jocurile și software-urile urmărite (%1$s)`,
  _ = `Clasamente și liste`,
  _ = `Cele mai vândute`,
  _ = `Cele mai jucate`,
  _ = `Lansări noi`,
  _ = `Lansări viitoare`,
  _ = `Gratuite`,
  _ = `Clasamentele Steam`,
  _ = `Acum la reducere`,
  _ = `Recomandări`,
  _ = `Lista de descoperiri`,
  _ = `Lista de descoperiri – Lansări noi`,
  _ = `Recomandările comunității`,
  _ = `Consultantul interactiv`,
  _ = `Populare în rândul prietenilor`,
  _ = `Curatori Steam`,
  _ = `DLC-uri pentru tine`,
  _ = `Hardware`,
  _ = `Steam Deck`,
  _ = `Stația de andocare pentru Steam Deck`,
  _ = `Hardware RV`,
  _ = `Jocuri RV`,
  _ = `Jocuri impecabile pe Steam Deck`,
  _ = `Jocuri compatibile cu controlere`,
  _ = `Modalități de joc`,
  _ = `Știri și actualizări`,
  _ = `Jocuri actualizate recent`,
  _ = `Jocurile tale actualizate recent`,
  _ = `Evenimentele tale viitoare`,
  _ = `Știri deosebite`,
  _ = `Știri și actualizări oficiale Steam`,
  _ = `Promoții și evenimente`,
  _ = `Oferte speciale`,
  _ = `Evenimente promoționale`,
  _ = `Retrospectiva Steam`,
  _ = `Festivalul Steam Next`,
  _ = `Premiile Steam`,
  _ = `Secțiuni speciale`,
  _ = `Magazinul cu puncte Steam`,
  _ = `Carduri cadou`,
  _ = `Genuri`,
  _ = `Tematici`,
  _ = `Ai realizat prea multe solicitări recent. Te rugăm să aștepți și să încerci din nou mai târziu.`,
  _ = `Discuții generale`,
  _ = `Postări raportate`,
  _ = `Discuții despre atelier`,
  _ = `Schimburi`,
  _ = `Evenimente și anunțuri`,
  _ = `Consultantul interactiv`,
  _ = `Jucători ca tine adoră...`,
  _ = `Explorează recomandările personalizate de la sistemul nostru bazat pe învățare automată, totul în funcție de istoricul tău de titluri jucate pe Steam, în comparație cu cel al milioane de alți jucători. Personalizează-ți rezultatele prin folosirea glisoarelor și filtrelor, iar apoi salvează-ți setările pentru ca Steam să rețină ceea ce-ți place.`,
  _ = `Timpul tău de joc relevant`,
  _ = `%1$s jocuri`,
  _ = `cele mai populare %1$s jocuri`,
  _ = `jocuri recente`,
  _ = `%1$s ore`,
  _ = `%1$s ore în total`,
  _ = `jucat ultima dată: %1$s`,
  _ = `jucat ultima dată: cu mai mult de 10 ani în urmă`,
  _ = `Include`,
  _ = `Exclude`,
  _ = `Sortează după popularitate`,
  _ = `populare`,
  _ = `de nișă`,
  _ = `Filtrează după vârstă`,
  _ = `mai vechi`,
  _ = `mai noi`,
  _ = `Din toate timpurile`,
  _ = `5 ani`,
  _ = `3 ani`,
  _ = `2 ani`,
  _ = `1 an`,
  _ = `6 luni`,
  _ = `Recomandate pentru tine`,
  _ = `Lansare: %1$s`,
  _ = `În lista de dorințe`,
  _ = `Adaugă în coș`,
  _ = `Adaugă în lista de dorințe`,
  _ = `Gratuit`,
  _ = `Scrie numele unei etichete`,
  _ = `Adaugă filtre pentru etichete`,
  _ = `Adaugă excluderi de etichete`,
  _ = `Exclude jocurile din lista de dorințe`,
  _ = `Numai jocuri la reducere`,
  _ = `Lansate în ultima lună`,
  _ = `Lansate în ultimele 7 zile`,
  _ = `Viitoare`,
  _ = `Calendarul tău personal`,
  _ = `O listă personalizată care include %1$s jocuri lansate recent sau care urmează să fie lansate în curând.`,
  _ = `Selector de etichete`,
  _ = `Filtrează după etichetă...`,
  _ = `Ascunde jocurile deținute`,
  _ = `Jocurile care părăsesc accesul timpuriu vor fi în continuare afișate.`,
  _ = `Ascunde jocurile aflate în acces timpuriu`,
  _ = `Afișează numai jocurile din lista de dorințe`,
  _ = `Numărul de jocuri`,
  _ = `Calendar compact`,
  _ = `Suprascriere opțională`,
  _ = `ID-ul contului`,
  _ = `Vezi tot (%1$s)`,
  _ = `Conectează-te pentru a vizualiza sugestii personalizate.`,
  _ = `Extinde tot`,
  _ = `Experimentul #16 din laboratoarele Steam | <1>Află mai multe și oferă feedback</1>`,
  _ = `Jocuri din lista de dorințe`,
  _ = `Afișează`,
  _ = `Ascunde`,
  _ = `Numai`,
  _ = `Prea multe jocuri în lista de dorințe (dezactivat)`,
  _ = `Eroare la încărcarea calendarului. Te rugăm să încerci din nou.`,
  _ = `Lista cu seturile %1$s`,
  _ = `Lista seturilor`,
  _ = `Toate seturile care conțin jocul %1$s.`,
  _ = `Verificat pe Steam Deck`,
  _ = `%1$s este verificat pe Steam Deck`,
  _ = `Eroare de site`,
  _ = `UPS, NE PARE RĂU!`,
  _ = `A apărut o eroare la procesarea solicitării tale.`,
  _ = `Numărul de sloturi trebuie să fie mai mare de 0.`,
  _ = `Domeniul de e-mail este deja utilizat de o altă agenție de presă.`,
  _ = `Agenția de presă nu a putut fi adăugată.`,
  _ = `Domeniul de e-mail nu poate fi gol.`,
  _ = `Domeniul de e-mail este nevalid.`,
  _ = `Contul este deja asociat unei agenții de presă.`,
  _ = `Contului nu a putut fi asociat unei agenții de presă.`,
  _ = `Domeniul de e-mail`,
  _ = `Numărul de sloturi`,
  _ = `Adaugă`,
  _ = `Adaugă agenția de presă:`,
  _ = `%1$s, %2$s/%3$s sloturi utilizate`,
  _ = `Afișează istoricul`,
  _ = `Istoricul pentru %1$s`,
  _ = `Codul destinat pentru presă a fost acordat utilizatorului %1$s de către %2$s`,
  _ = `Codul destinat pentru presă deținut de %1$s a fost revocat de %2$s`,
  _ = `Agenția de presă a fost creată de %1$s`,
  _ = `Agenția de presă a fost actualizată de %1$s`,
  _ = `Domeniul de e-mail a fost setat ca %1$s`,
  _ = `Numărul de sloturi a fost setat la %1$s`,
  _ = `Agenția de presă a fost ștearsă de %1$s`,
  _ = `Agenția de presă a fost restabilită de %1$s`,
  _ = `Agenția de presă a fost trecută în stadiul de pregătire de %1$s`,
  _ = `Modificările din stadiul de pregătire au fost aplicate de %1$s`,
  _ = `Utilizatorul %1$s a fost programat să fie adăugat de %2$s`,
  _ = `Utilizatorul %1$s a fost programat să fie eliminat de %2$s`,
  _ = `asistență`,
  _ = `Beneficiar`,
  _ = `Acordat:`,
  _ = `Este administratorul grupului?`,
  _ = `ID-ul Steam de adăugat`,
  _ = `OK`,
  _ = `Anulează`,
  _ = `Da`,
  _ = `Nu`,
  _ = `Tot`,
  _ = `Activă`,
  _ = `Ștearsă`,
  _ = `Gol`,
  _ = `Agenția de presă nu are niciun administrator`,
  _ = `Agenție de presă:`,
  _ = `Codul de prieten:`,
  _ = `Renunță la codul tău destinat presei: `,
  _ = `Sigur renunți la codul tău destinat presei?`,
  _ = `Istoricul agenției de presă`,
  _ = `Adăugare membru`,
  _ = `Afișează istoricul`,
  _ = `Cont`,
  _ = `Trailerul nu a fost găsit`,
  _ = `Trailer`,
  _ = `Microtrailer`,
  _ = `A apărut o eroare la salvarea setărilor tale pentru notificări.`,
  _ = `A apărut o eroare la încărcarea setărilor tale pentru notificări.`,
  _ = `Acest link de dezabonare este nevalid sau a expirat. Te rugăm să te conectezi și să accesezi <1>setările pentru notificări</1>.`,
  _ = `Fluxul este activat automat dacă opțiunea „Notificare pop-up în client” sau „Aplicația mobilă” este activată.`,
  _ = `Trimite notificări doar către %1$s despre aceste categorii din lista de dorințe.`,
  _ = `Estimator de frecvență de cadre`,
  _ = `Selectează o aplicație și o configurație de PC pentru a obține un grafic cu frecvențele de cadre estimate în baza frecvențelor de cadre ale altor utilizatori Steam.`,
  _ = `Procesor`,
  _ = `RAM sistem`,
  _ = `Placă video`,
  _ = `Hardware-ul salvat`,
  _ = `Nu ai niciun hardware salvat.`,
  _ = `Selectează unul din sistemele tale hardware pentru a vedea o frecvență de cadre estimată.`,
  _ = `<Nicio selecție>`,
  _ = `Îți poți adăuga sistemul hardware actual dacă vizualizezi aceste date din cadrul clientului Steam.`,
  _ = `Adaugă hardware-ul salvat`,
  _ = `Adaugă hardware-ul salvat (din afara clientului)`,
  _ = `Dacă dorești să contribui cu date anonime pentru estimatorul de frecvență de cadre și să ajuți la îmbunătățirea preciziei acestuia pentru toți ceilalți, accesează linkul de mai jos pentru a-ți modifica preferințele privind colectarea datelor.`,
  _ = `Preferințe`,
  _ = `CPS`,
  _ = `Caută un joc`,
  _ = `Selectează un procesor`,
  _ = `Selectează o placă video`,
  _ = `Numărul de înregistrări de antrenament corespunzătoare jocului`,
  _ = `Numărul de înregistrări de antrenament corespunzătoare procesorului`,
  _ = `Numărul de înregistrări de antrenament corespunzătoare plăcii video`,
  _ = `Necunoscut`,
  _ = `Trimite un card cadou`,
  _ = ``,
  _ = {
    BundleList_SubTitle: _,
    BundleList_SortBy: _,
    BundleList_SortBy_Popular: _,
    BundleList_SortBy_Price: _,
    BundleList_SortBy_Discount: _,
    BundleList_SortBy_Name: _,
    BundleList_SortBy_Recommend: _,
    BundleList_AllInLibrary: _,
    BundleList_AllInLibrarySubtitle: _,
    BundleList_CompleteTheSet: _,
    BundleList_CompleteTheSetSubtitle: _,
    BundleList_MustPurchaseAsSet: _,
    BundleList_MustPurchaseAsSetSubtitle: _,
    footer_legal_notice: _,
    footer_vat_included: _,
    footer_privacy_policy: _,
    footer_legal: _,
    footer_accessibility: _,
    footer_ssa: _,
    footer_refunds: _,
    footer_cookies: _,
    footer_about_valve: _,
    footer_business_solutions: _,
    footer_recycling: _,
    footer_steamworks: _,
    footer_source_engine: _,
    footer_jobs: _,
    footer_walletcode: _,
    footer_steam_distribution: _,
    footer_nav_help_support: _,
    wishlist_title: _,
    wishlist_header: _,
    cart_count: _,
    cart_view_cart: _,
    wishlist_count: _,
    wishlist_options_button: _,
    wishlist_sortby_button: _,
    wishlist_share_tooltip: _,
    wishlist_controls_sortby_order: _,
    wishlist_controls_sortby_their_order: _,
    wishlist_controls_sortby_topsellers: _,
    wishlist_controls_sortby_releasedate: _,
    wishlist_controls_sortby_dateadded: _,
    wishlist_controls_sortby_reviews: _,
    wishlist_controls_sortby_price: _,
    wishlist_controls_sortby_name: _,
    wishlist_controls_sortby_discount: _,
    wishlist_controls_share_dialog_title: _,
    wishlist_controls_share_revokeall: _,
    wishlist_controls_share_revokeall_success: _,
    wishlist_controls_share_generation_failure: _,
    wishlist_controls_share_description: _,
    wishlist_controls_options_category_view: _,
    wishlist_controls_options_view_expanded: _,
    wishlist_controls_options_view_compact: _,
    wishlist_controls_options_category_platform: _,
    wishlist_controls_options_platform_all: _,
    wishlist_controls_options_platform_mac: _,
    wishlist_controls_options_platform_linux: _,
    wishlist_controls_options_category_type: `Tip`,
    wishlist_controls_options_type_game: _,
    wishlist_controls_options_type_application: _,
    wishlist_controls_options_type_dlc: _,
    wishlist_controls_options_type_video: _,
    wishlist_controls_options_category_price: _,
    wishlist_controls_options_category_discount: _,
    wishlist_controls_options_discount_all: _,
    wishlist_controls_options_discount_any: _,
    wishlist_controls_options_discount_or_more: _,
    wishlist_controls_options_price_any: _,
    wishlist_controls_options_price_max_price: _,
    wishlist_controls_options_price_free: _,
    wishlist_controls_options_category_exclude: _,
    wishlist_controls_options_category_related: _,
    genre_early_access: _,
    wishlist_controls_early_access_tooltip: _,
    category_prerelease: _,
    wishlist_controls_options_exclude_vr: _,
    wishlist_controls_demo_available: _,
    wishlist_controls_demo_available_tooltip: _,
    wishlist_controls_options_category_deck: _,
    wishlist_controls_options_deck_verified: _,
    wishlist_controls_options_deck_playable: _,
    wishlist_controls_options_category_tag: _,
    wishlist_controls_tag_description: _,
    wishlist_controls_tags_header: _,
    wishlist_controls_filter_tag_label: _,
    wishlist_controls_options_category_category: _,
    wishlist_controls_categories_header_anonymous: _,
    wishlist_controls_categories_multiselect_label: _,
    wishlist_controls_categories_add: _,
    wishlist_categories_advanced_title: _,
    wishlist_categories_advanced_select: _,
    wishlist_categories_advanced_rename_label: _,
    wishlist_categories_advanced_rename_save: _,
    wishlist_categories_advanced_rename_duplicate: _,
    wishlist_categories_advanced_rename_failed: _,
    wishlist_categories_advanced_no_items: _,
    wishlist_categories_advanced_select_all: _,
    wishlist_categories_advanced_select_none: _,
    wishlist_categories_advanced_showing: _,
    wishlist_categories_advanced_failed_items: _,
    wishlist_categories_advanced_failed_items_Plural: _,
    wishlist_categories_advanced_pending: _,
    wishlist_categories_advanced_pending_adds: _,
    wishlist_categories_advanced_pending_removals: _,
    wishlist_categories_advanced_revert: _,
    wishlist_categories_advanced_apply: _,
    wishlist_categories_advanced_addremove_title: _,
    wishlist_displayed_item_count: _,
    wishlist_displayed_item_count_Plural: _,
    wishlist_filter_results: _,
    wishlist_filter_matches_items: _,
    wishlist_filter_matches_items_Plural: _,
    wishlist_filter_matches_category: _,
    wishlist_filter_matches_category_Plural: _,
    wishlist_filter_matches_categories: _,
    wishlist_filter_matches_categories_Plural: _,
    wishlist_filter_matches_tag: _,
    wishlist_filter_matches_tag_Plural: _,
    wishlist_filter_matches_tags: _,
    wishlist_filter_matches_tags_Plural: _,
    wishlist_search: _,
    wishlist_search_all: _,
    wishlist_item_overallreviews: _,
    wishlist_item_languagespecific_reviews: _,
    wishlist_item_releasedate: _,
    wishlist_item_addedon_date: _,
    wishlist_item_remove: _,
    wishlist_item_remove_tooltip: _,
    wishlist_item_unavailable_title: _,
    wishlist_item_unavailable_region: _,
    wishlist_item_unavailable_retired: _,
    mature_content_requires_creditcard: _,
    mature_content_requires_creditcard_gb: _,
    wishlist_item_add_credit_card: _,
    wishlist_your_wishlist_empty: _,
    wishlist_browse_the_store: _,
    wishlist_learn_more_button: _,
    wishlist_sign_in_to_see_your_wishlist: _,
    wishlist_others_wishlist_empty: _,
    wishlist_no_items_matching_filters: _,
    wishlist_x_items_on_wishlist_but_none_match: _,
    wishlist_x_items_on_wishlist_but_none_match_prefs: _,
    wishlist_gamepaddragdrop_reorderaction: _,
    wishlist_gamepaddragdrop_cancelreorder: _,
    wishlist_gamepaddragdrop_commitreorder: _,
    wishlist_gamepad_options: _,
    wishlist_gamepad_options_remove: _,
    wishlist_gamepad_visitstore: _,
    wishlist_errorpage_title: _,
    errorpage_error: _,
    errorpage_unknownerror: _,
    wishlist_error_profilenotfound: _,
    wishlist_error_wishlistunavailable: _,
    wishlist_error_invalidsharetoken: _,
    wishlist_filters_notification: _,
    youraccount_users_account: _,
    youraccount_errorpage_title: _,
    youraccount_account: _,
    m_home: _,
    global_menu_account_details: _,
    global_menu_account_preferences: _,
    global_menu_account_language_preferences: _,
    global_menu_account_notification_settings: _,
    global_menu_account_hardware_used: _,
    global_menu_account_security_devices: _,
    global_menu_account_video_authorized_devices: _,
    global_menu_account_mobile_game_devices: _,
    global_menu_account_gated_access_games: _,
    accountpreferences_familymanagement_header: _,
    CookiePreferences: _,
    global_menu_vr: `RV`,
    global_menu_greatondeck: _,
    global_menu_localplayonframe: _,
    store_tab_foryou_store_home: _,
    browse_categories: _,
    m_search_steam: _,
    playteststatus_error_dataunavailable: _,
    playtestinvites_title: _,
    playtestinvites_accept: _,
    playtestinvites_reject: _,
    playtestinvites_invitedescription_fromapp2: _,
    playtestinvites_invitedescription_fromapp_limitedlaunch: _,
    playtestinvites_invitedescription_fromuser2: _,
    playtestinvites_invitedescription_fromuser_limitedlaunch: _,
    playtestinvites_noinvites: _,
    playtestinvites_welcome: _,
    playtestinvites_welcome_limitedlaunch: _,
    playtestinvites_welcome_notplayable: _,
    playtestinvites_viewlibrary: _,
    playtestinvites_desc_title: _,
    playtestinvites_desc1: _,
    playtestinvites_desc2: _,
    playtestinvites_ignored_title: _,
    playtestinvites_ignored_desc: _,
    playtestinvites_ignored_remove: _,
    playtestinvites_sendinvite_cancel: _,
    playtestinvites_sendinvite_send: _,
    playtestinvites_sendinvite_lastinvite: _,
    playtestinvites_sendinvite_lastinvite_limitedlaunch: _,
    playtestinvites_sendinvite_confirm_desc: _,
    playtestinvites_sendinvite_pending: _,
    playtestinvites_sendinvite_success: _,
    playtestinvites_sendinvite_failure: _,
    playtestinvitehistory_title: _,
    playtestinvitehistory_desc: _,
    playtestinvitehistory_invite_detail: _,
    playteststatus_title: _,
    playteststatus_none: _,
    playteststatus_invites_available: _,
    playteststatus_invite_count: _,
    playteststatus_invite_count_plural: _,
    playteststatus_invite_count_tooltip: _,
    playteststatus_invite_count_tooltip2: _,
    playteststatus_details_moreinfo: _,
    playteststatus_details_moreinfo_storepage: _,
    playteststatus_details_moreinfo_newshub: _,
    playteststatus_details_notplayable: _,
    playteststatus_details_allinvitesused: _,
    playteststatus_invitefriends: _,
    playteststatus_invitefrienddialog_header: _,
    playteststatus_invitefrienddialog_search_placeholder: _,
    playteststatus_invitefrienddialog_loadingerror: _,
    playteststatus_invitefrienddialog_ineligiblefriends: _,
    playteststatus_invitefrienddialog_ineligiblefriends_purchaser: _,
    gatedaccess_limitedlaunch_badge: _,
    gatedaccess_limitedlaunch_invite_count_tooltip: _,
    gatedaccess_limitedlaunch_details_moreinfo: _,
    gatedaccess_limitedlaunch_desc_title: _,
    gatedaccess_limitedlaunch_desc: _,
    sitemap_title: _,
    sitemap_home: _,
    sitemap_section_account: _,
    sitemap_section_account_account_details: _,
    sitemap_section_account_store_preferences: _,
    sitemap_section_account_family_management: _,
    sitemap_section_account_security_and_devices: _,
    sitemap_section_account_language_preferences: _,
    sitemap_section_account_cookes_and_browsing: _,
    sitemap_section_account_notification_settings: _,
    sitemap_section_account_cart: _,
    sitemap_section_account_cart_with_count: _,
    sitemap_section_account_wishlist: _,
    sitemap_section_account_wishlist_with_count: _,
    sitemap_section_account_followed_games: _,
    sitemap_section_account_followed_games_with_count: _,
    sitemap_section_chartsandlists: _,
    sitemap_section_chartsandlists_top_sellers: _,
    sitemap_section_chartsandlists_most_played: _,
    sitemap_section_chartsandlists_new_releases: _,
    sitemap_section_chartsandlists_upcoming_releases: _,
    sitemap_section_chartsandlists_free_to_play: _,
    sitemap_section_chartsandlists_steam_charts: _,
    sitemap_section_chartsandlists_on_sale_now: _,
    sitemap_section_recommendations: _,
    sitemap_section_recommendations_discovery_queue: _,
    sitemap_section_recommendations_new_releases_queue: _,
    sitemap_section_recommendations_community_recommendations: _,
    sitemap_section_recommendations_interactive_recommender: _,
    sitemap_section_recommendations_popular_among_friends: _,
    sitemap_section_recommendations_steam_curators: _,
    sitemap_section_recommendations_dlc_for_you: _,
    sitemap_section_hardware: _,
    sitemap_section_hardware_steam_deck: _,
    sitemap_section_hardware_steam_deck_dock: _,
    sitemap_section_hardware_vr_hardware: _,
    sitemap_section_hardware_vr_games: _,
    sitemap_section_hardware_great_on_deck: _,
    sitemap_section_hardware_controller_friendly: _,
    sitemap_section_waystoplay: _,
    sitemap_section_newsupdates: _,
    sitemap_section_newsupdates_recently_updated: _,
    sitemap_section_newsupdates_your_recently_updated: _,
    sitemap_section_newsupdates_your_upcoming_events: _,
    sitemap_section_newsupdates_featured_news: _,
    sitemap_section_newsupdates_steam_official_news: _,
    sitemap_section_promosandevents: _,
    sitemap_section_promosandevents_special_offers: _,
    sitemap_section_promosandevents_sale_events: _,
    sitemap_section_promosandevents_steam_replay: _,
    sitemap_section_promosandevents_steam_next_fest: _,
    sitemap_section_promosandevents_steam_awards: _,
    sitemap_section_specialsections: _,
    sitemap_pointsshop: _,
    sitemap_giftcards: _,
    sitemap_genres: _,
    sitemap_themes: _,
    Error_RateLimited: _,
    Discussions_ForumName_General: _,
    Discussions_ForumName_ReportedPosts: _,
    Discussions_ForumName_Workshop: _,
    Discussions_ForumName_Trading: _,
    Discussions_ForumName_Events: _,
    ir_name: _,
    ir_header: _,
    ir_body: _,
    ir_playtime_header: _,
    ir_playtime_games: _,
    ir_playtime_topgames: _,
    ir_playtime_recentgames: _,
    ir_playtime_hours: _,
    ir_playtime_hourstotal: _,
    ir_playtime_lastplayed: _,
    ir_playtime_lastplayedmax: _,
    ir_playtime_unignore: _,
    ir_playtime_ignore: _,
    ir_popularity_title: _,
    ir_popularity_popular: _,
    ir_popularity_niche: _,
    ir_recency_title: _,
    ir_recency_older: _,
    ir_recency_newer: _,
    ir_filter_age_all: _,
    ir_filter_age_60: _,
    ir_filter_age_36: _,
    ir_filter_age_24: _,
    ir_filter_age_12: _,
    ir_filter_age_6: _,
    ir_recommendations_header: _,
    ir_release_date: _,
    ir_on_wishlist: _,
    ir_add_to_cart: _,
    ir_add_to_wishlist: _,
    ir_free_to_play: _,
    ir_tag_placeholder: _,
    ir_tag_filter: _,
    ir_tag_exclude: _,
    ir_no_wishlisted: _,
    ir_discounted_only: _,
    PersonalCalendar_LastMonthGames: _,
    PersonalCalendar_LastWeekGames: _,
    PersonalCalendar_Upcoming: _,
    PersonalCalendar_Title: _,
    PersonalCalendar_Description: _,
    PersonalCalendar_TagSelector: _,
    PersonalCalendar_TagSelector_Placeholder: _,
    PersonalCalendar_HideOwned: _,
    PersonalCalendar_HideEATooltip: _,
    PersonalCalendar_HideEarlyAccess: _,
    PersonalCalendar_ShowOnlyWishlisted: _,
    PersonalCalendar_ResultCountSelector: _,
    PersonalCalendar_CompactMode: _,
    PersonalCalendar_AccountPlaceholder: _,
    PersonalCalendar_Account: _,
    PersonalCalendar_ShowMore: _,
    PersonalCalendar_LoginPrompt: _,
    PersonalCalendar_ShowAll: _,
    PersonalCalendar_SteamLabs: _,
    PersonalCalendar_Wishlisted: _,
    PersonalCalendar_WishlistShow: _,
    PersonalCalendar_WishlistHide: _,
    PersonalCalendar_WishlistOnly: _,
    PersonalCalendar_IgnoringWishlists: _,
    PersonalCalendar_Error_Backend: _,
    BundleList_Title: _,
    BundleList_Title_Fallback: _,
    BundleList_Page: _,
    Verification_DeckOnly: _,
    Verification_DeckOnly_Desc: _,
    FatalErrorPage_Title: _,
    FatalErrorPage_Header: _,
    FatalErrorPage_Message: _,
    pressoutlets_error_slots_gt_zero: _,
    pressoutlets_error_domain_used: _,
    pressoutlets_error_adding_outlet: _,
    pressoutlets_error_domain_empty: _,
    pressoutlets_error_invalid_domain: _,
    pressoutlets_error_already_owned: _,
    pressoutlets_error_generic_add_error: _,
    pressoutlets_email_domain_label: _,
    pressoutlets_slots_label: _,
    pressoutlets_button_add: _,
    pressoutlets_label_add_outlet: _,
    pressoutlets_outlet_header: _,
    pressoutlets_show_history: _,
    pressoutlets_history_title: _,
    pressoutlets_action_granted: _,
    pressoutlets_action_removed: _,
    pressoutlets_action_created: _,
    pressoutlets_action_updated: _,
    pressoutlets_action_updated_domain_changed: _,
    pressoutlets_action_updated_slots_changed: _,
    pressoutlets_action_deleted: _,
    pressoutlets_action_undeleted: _,
    pressoutlets_action_enterstaging: _,
    pressoutlets_action_exitstaging: _,
    pressoutlets_action_stagedadd: _,
    pressoutlets_action_stageddelete: _,
    pressoutlets_action_by_support: _,
    pressoutlets_header_grantee: _,
    pressoutlets_header_granted_at: _,
    pressoutlets_header_is_group_admin: _,
    pressoutlets_steamid_to_add: _,
    pressoutlets_button_ok: `OK`,
    pressoutlets_button_cancel: _,
    pressoutlets_is_group_admin: `Da`,
    pressoutlets_is_not_group_admin: `Nu`,
    pressoutlets_filter_all: `Tot`,
    pressoutlets_filter_active: _,
    pressoutlets_filter_deleted: _,
    pressoutlets_filter_empty: `Gol`,
    pressoutlets_filter_noadmins: _,
    pressoutlets_outlet_header_prefix: _,
    pressoutlets_friendcode: _,
    pressoutlets_resign_your_key: _,
    pressoutlets_resign_your_key_title: _,
    pressoutlets_history_header: _,
    pressoutlets_button_add_member: _,
    pressoutlets_button_show_history: _,
    pressoutlets_header_account: _,
    trailerassets_invalidfile: _,
    trailerassets_trailer: _,
    trailerassets_microtrailer: _,
    account_notification_settings_error_saving: _,
    account_notification_settings_error_loading: _,
    account_notification_settings_error_invalidoptouttoken: _,
    account_notification_settings_feed_disabled: _,
    account_notification_settings_wishlist_categories_persona: _,
    framerate_title: _,
    framerate_subheader: _,
    framerate_cpu: _,
    framerate_ram: _,
    framerate_gpu: _,
    framerate_saved_hardware: _,
    framerate_saved_hardware_none: _,
    framerate_saved_hardware_select: _,
    framerate_saved_hardware_option_none: _,
    framerate_saved_add: _,
    framerate_saved_add_btn: _,
    framerate_saved_add_not_in_client_btn: _,
    framerate_opt_in_data_collection_desc: _,
    framerate_opt_in_link: _,
    framerate_fps: `CPS`,
    framerate_game_name: _,
    framerate_select_cpu: _,
    framerate_select_gpu: _,
    framerate_training_game: _,
    framerate_training_cpu: _,
    framerate_training_gpu: _,
    generic_unknown: _,
    giftcards_banner_text: _,
    empty_no_trailing_comma: ``,
  };
export {
  _ as BundleList_AllInLibrary,
  _ as BundleList_AllInLibrarySubtitle,
  _ as BundleList_CompleteTheSet,
  _ as BundleList_CompleteTheSetSubtitle,
  _ as BundleList_MustPurchaseAsSet,
  _ as BundleList_MustPurchaseAsSetSubtitle,
  _ as BundleList_Page,
  _ as BundleList_SortBy,
  _ as BundleList_SortBy_Discount,
  _ as BundleList_SortBy_Name,
  _ as BundleList_SortBy_Popular,
  _ as BundleList_SortBy_Price,
  _ as BundleList_SortBy_Recommend,
  _ as BundleList_SubTitle,
  _ as BundleList_Title,
  _ as BundleList_Title_Fallback,
  _ as CookiePreferences,
  _ as Discussions_ForumName_Events,
  _ as Discussions_ForumName_General,
  _ as Discussions_ForumName_ReportedPosts,
  _ as Discussions_ForumName_Trading,
  _ as Discussions_ForumName_Workshop,
  _ as Error_RateLimited,
  _ as FatalErrorPage_Header,
  _ as FatalErrorPage_Message,
  _ as FatalErrorPage_Title,
  _ as PersonalCalendar_Account,
  _ as PersonalCalendar_AccountPlaceholder,
  _ as PersonalCalendar_CompactMode,
  _ as PersonalCalendar_Description,
  _ as PersonalCalendar_Error_Backend,
  _ as PersonalCalendar_HideEATooltip,
  _ as PersonalCalendar_HideEarlyAccess,
  _ as PersonalCalendar_HideOwned,
  _ as PersonalCalendar_IgnoringWishlists,
  _ as PersonalCalendar_LastMonthGames,
  _ as PersonalCalendar_LastWeekGames,
  _ as PersonalCalendar_LoginPrompt,
  _ as PersonalCalendar_ResultCountSelector,
  _ as PersonalCalendar_ShowAll,
  _ as PersonalCalendar_ShowMore,
  _ as PersonalCalendar_ShowOnlyWishlisted,
  _ as PersonalCalendar_SteamLabs,
  _ as PersonalCalendar_TagSelector,
  _ as PersonalCalendar_TagSelector_Placeholder,
  _ as PersonalCalendar_Title,
  _ as PersonalCalendar_Upcoming,
  _ as PersonalCalendar_WishlistHide,
  _ as PersonalCalendar_WishlistOnly,
  _ as PersonalCalendar_WishlistShow,
  _ as PersonalCalendar_Wishlisted,
  _ as Verification_DeckOnly,
  _ as Verification_DeckOnly_Desc,
  _ as account_notification_settings_error_invalidoptouttoken,
  _ as account_notification_settings_error_loading,
  _ as account_notification_settings_error_saving,
  _ as account_notification_settings_feed_disabled,
  _ as account_notification_settings_wishlist_categories_persona,
  _ as accountpreferences_familymanagement_header,
  _ as browse_categories,
  _ as cart_count,
  _ as cart_view_cart,
  _ as category_prerelease,
  _ as default,
  _ as empty_no_trailing_comma,
  _ as errorpage_error,
  _ as errorpage_unknownerror,
  _ as footer_about_valve,
  _ as footer_accessibility,
  _ as footer_business_solutions,
  _ as footer_cookies,
  _ as footer_jobs,
  _ as footer_legal,
  _ as footer_legal_notice,
  _ as footer_nav_help_support,
  _ as footer_privacy_policy,
  _ as footer_recycling,
  _ as footer_refunds,
  _ as footer_source_engine,
  _ as footer_ssa,
  _ as footer_steam_distribution,
  _ as footer_steamworks,
  _ as footer_vat_included,
  _ as footer_walletcode,
  _ as framerate_cpu,
  _ as framerate_fps,
  _ as framerate_game_name,
  _ as framerate_gpu,
  _ as framerate_opt_in_data_collection_desc,
  _ as framerate_opt_in_link,
  _ as framerate_ram,
  _ as framerate_saved_add,
  _ as framerate_saved_add_btn,
  _ as framerate_saved_add_not_in_client_btn,
  _ as framerate_saved_hardware,
  _ as framerate_saved_hardware_none,
  _ as framerate_saved_hardware_option_none,
  _ as framerate_saved_hardware_select,
  _ as framerate_select_cpu,
  _ as framerate_select_gpu,
  _ as framerate_subheader,
  _ as framerate_title,
  _ as framerate_training_cpu,
  _ as framerate_training_game,
  _ as framerate_training_gpu,
  _ as gatedaccess_limitedlaunch_badge,
  _ as gatedaccess_limitedlaunch_desc,
  _ as gatedaccess_limitedlaunch_desc_title,
  _ as gatedaccess_limitedlaunch_details_moreinfo,
  _ as gatedaccess_limitedlaunch_invite_count_tooltip,
  _ as generic_unknown,
  _ as genre_early_access,
  _ as giftcards_banner_text,
  _ as global_menu_account_details,
  _ as global_menu_account_gated_access_games,
  _ as global_menu_account_hardware_used,
  _ as global_menu_account_language_preferences,
  _ as global_menu_account_mobile_game_devices,
  _ as global_menu_account_notification_settings,
  _ as global_menu_account_preferences,
  _ as global_menu_account_security_devices,
  _ as global_menu_account_video_authorized_devices,
  _ as global_menu_greatondeck,
  _ as global_menu_localplayonframe,
  _ as global_menu_vr,
  _ as ir_add_to_cart,
  _ as ir_add_to_wishlist,
  _ as ir_body,
  _ as ir_discounted_only,
  _ as ir_filter_age_12,
  _ as ir_filter_age_24,
  _ as ir_filter_age_36,
  _ as ir_filter_age_6,
  _ as ir_filter_age_60,
  _ as ir_filter_age_all,
  _ as ir_free_to_play,
  _ as ir_header,
  _ as ir_name,
  _ as ir_no_wishlisted,
  _ as ir_on_wishlist,
  _ as ir_playtime_games,
  _ as ir_playtime_header,
  _ as ir_playtime_hours,
  _ as ir_playtime_hourstotal,
  _ as ir_playtime_ignore,
  _ as ir_playtime_lastplayed,
  _ as ir_playtime_lastplayedmax,
  _ as ir_playtime_recentgames,
  _ as ir_playtime_topgames,
  _ as ir_playtime_unignore,
  _ as ir_popularity_niche,
  _ as ir_popularity_popular,
  _ as ir_popularity_title,
  _ as ir_recency_newer,
  _ as ir_recency_older,
  _ as ir_recency_title,
  _ as ir_recommendations_header,
  _ as ir_release_date,
  _ as ir_tag_exclude,
  _ as ir_tag_filter,
  _ as ir_tag_placeholder,
  _ as m_home,
  _ as m_search_steam,
  _ as mature_content_requires_creditcard,
  _ as mature_content_requires_creditcard_gb,
  _ as playtestinvitehistory_desc,
  _ as playtestinvitehistory_invite_detail,
  _ as playtestinvitehistory_title,
  _ as playtestinvites_accept,
  _ as playtestinvites_desc1,
  _ as playtestinvites_desc2,
  _ as playtestinvites_desc_title,
  _ as playtestinvites_ignored_desc,
  _ as playtestinvites_ignored_remove,
  _ as playtestinvites_ignored_title,
  _ as playtestinvites_invitedescription_fromapp2,
  _ as playtestinvites_invitedescription_fromapp_limitedlaunch,
  _ as playtestinvites_invitedescription_fromuser2,
  _ as playtestinvites_invitedescription_fromuser_limitedlaunch,
  _ as playtestinvites_noinvites,
  _ as playtestinvites_reject,
  _ as playtestinvites_sendinvite_cancel,
  _ as playtestinvites_sendinvite_confirm_desc,
  _ as playtestinvites_sendinvite_failure,
  _ as playtestinvites_sendinvite_lastinvite,
  _ as playtestinvites_sendinvite_lastinvite_limitedlaunch,
  _ as playtestinvites_sendinvite_pending,
  _ as playtestinvites_sendinvite_send,
  _ as playtestinvites_sendinvite_success,
  _ as playtestinvites_title,
  _ as playtestinvites_viewlibrary,
  _ as playtestinvites_welcome,
  _ as playtestinvites_welcome_limitedlaunch,
  _ as playtestinvites_welcome_notplayable,
  _ as playteststatus_details_allinvitesused,
  _ as playteststatus_details_moreinfo,
  _ as playteststatus_details_moreinfo_newshub,
  _ as playteststatus_details_moreinfo_storepage,
  _ as playteststatus_details_notplayable,
  _ as playteststatus_error_dataunavailable,
  _ as playteststatus_invite_count,
  _ as playteststatus_invite_count_plural,
  _ as playteststatus_invite_count_tooltip,
  _ as playteststatus_invite_count_tooltip2,
  _ as playteststatus_invitefrienddialog_header,
  _ as playteststatus_invitefrienddialog_ineligiblefriends,
  _ as playteststatus_invitefrienddialog_ineligiblefriends_purchaser,
  _ as playteststatus_invitefrienddialog_loadingerror,
  _ as playteststatus_invitefrienddialog_search_placeholder,
  _ as playteststatus_invitefriends,
  _ as playteststatus_invites_available,
  _ as playteststatus_none,
  _ as playteststatus_title,
  _ as pressoutlets_action_by_support,
  _ as pressoutlets_action_created,
  _ as pressoutlets_action_deleted,
  _ as pressoutlets_action_enterstaging,
  _ as pressoutlets_action_exitstaging,
  _ as pressoutlets_action_granted,
  _ as pressoutlets_action_removed,
  _ as pressoutlets_action_stagedadd,
  _ as pressoutlets_action_stageddelete,
  _ as pressoutlets_action_undeleted,
  _ as pressoutlets_action_updated,
  _ as pressoutlets_action_updated_domain_changed,
  _ as pressoutlets_action_updated_slots_changed,
  _ as pressoutlets_button_add,
  _ as pressoutlets_button_add_member,
  _ as pressoutlets_button_cancel,
  _ as pressoutlets_button_ok,
  _ as pressoutlets_button_show_history,
  _ as pressoutlets_email_domain_label,
  _ as pressoutlets_error_adding_outlet,
  _ as pressoutlets_error_already_owned,
  _ as pressoutlets_error_domain_empty,
  _ as pressoutlets_error_domain_used,
  _ as pressoutlets_error_generic_add_error,
  _ as pressoutlets_error_invalid_domain,
  _ as pressoutlets_error_slots_gt_zero,
  _ as pressoutlets_filter_active,
  _ as pressoutlets_filter_all,
  _ as pressoutlets_filter_deleted,
  _ as pressoutlets_filter_empty,
  _ as pressoutlets_filter_noadmins,
  _ as pressoutlets_friendcode,
  _ as pressoutlets_header_account,
  _ as pressoutlets_header_granted_at,
  _ as pressoutlets_header_grantee,
  _ as pressoutlets_header_is_group_admin,
  _ as pressoutlets_history_header,
  _ as pressoutlets_history_title,
  _ as pressoutlets_is_group_admin,
  _ as pressoutlets_is_not_group_admin,
  _ as pressoutlets_label_add_outlet,
  _ as pressoutlets_outlet_header,
  _ as pressoutlets_outlet_header_prefix,
  _ as pressoutlets_resign_your_key,
  _ as pressoutlets_resign_your_key_title,
  _ as pressoutlets_show_history,
  _ as pressoutlets_slots_label,
  _ as pressoutlets_steamid_to_add,
  _ as sitemap_genres,
  _ as sitemap_giftcards,
  _ as sitemap_home,
  _ as sitemap_pointsshop,
  _ as sitemap_section_account,
  _ as sitemap_section_account_account_details,
  _ as sitemap_section_account_cart,
  _ as sitemap_section_account_cart_with_count,
  _ as sitemap_section_account_cookes_and_browsing,
  _ as sitemap_section_account_family_management,
  _ as sitemap_section_account_followed_games,
  _ as sitemap_section_account_followed_games_with_count,
  _ as sitemap_section_account_language_preferences,
  _ as sitemap_section_account_notification_settings,
  _ as sitemap_section_account_security_and_devices,
  _ as sitemap_section_account_store_preferences,
  _ as sitemap_section_account_wishlist,
  _ as sitemap_section_account_wishlist_with_count,
  _ as sitemap_section_chartsandlists,
  _ as sitemap_section_chartsandlists_free_to_play,
  _ as sitemap_section_chartsandlists_most_played,
  _ as sitemap_section_chartsandlists_new_releases,
  _ as sitemap_section_chartsandlists_on_sale_now,
  _ as sitemap_section_chartsandlists_steam_charts,
  _ as sitemap_section_chartsandlists_top_sellers,
  _ as sitemap_section_chartsandlists_upcoming_releases,
  _ as sitemap_section_hardware,
  _ as sitemap_section_hardware_controller_friendly,
  _ as sitemap_section_hardware_great_on_deck,
  _ as sitemap_section_hardware_steam_deck,
  _ as sitemap_section_hardware_steam_deck_dock,
  _ as sitemap_section_hardware_vr_games,
  _ as sitemap_section_hardware_vr_hardware,
  _ as sitemap_section_newsupdates,
  _ as sitemap_section_newsupdates_featured_news,
  _ as sitemap_section_newsupdates_recently_updated,
  _ as sitemap_section_newsupdates_steam_official_news,
  _ as sitemap_section_newsupdates_your_recently_updated,
  _ as sitemap_section_newsupdates_your_upcoming_events,
  _ as sitemap_section_promosandevents,
  _ as sitemap_section_promosandevents_sale_events,
  _ as sitemap_section_promosandevents_special_offers,
  _ as sitemap_section_promosandevents_steam_awards,
  _ as sitemap_section_promosandevents_steam_next_fest,
  _ as sitemap_section_promosandevents_steam_replay,
  _ as sitemap_section_recommendations,
  _ as sitemap_section_recommendations_community_recommendations,
  _ as sitemap_section_recommendations_discovery_queue,
  _ as sitemap_section_recommendations_dlc_for_you,
  _ as sitemap_section_recommendations_interactive_recommender,
  _ as sitemap_section_recommendations_new_releases_queue,
  _ as sitemap_section_recommendations_popular_among_friends,
  _ as sitemap_section_recommendations_steam_curators,
  _ as sitemap_section_specialsections,
  _ as sitemap_section_waystoplay,
  _ as sitemap_themes,
  _ as sitemap_title,
  _ as store_tab_foryou_store_home,
  _ as trailerassets_invalidfile,
  _ as trailerassets_microtrailer,
  _ as trailerassets_trailer,
  _ as wishlist_browse_the_store,
  _ as wishlist_categories_advanced_addremove_title,
  _ as wishlist_categories_advanced_apply,
  _ as wishlist_categories_advanced_failed_items,
  _ as wishlist_categories_advanced_failed_items_Plural,
  _ as wishlist_categories_advanced_no_items,
  _ as wishlist_categories_advanced_pending,
  _ as wishlist_categories_advanced_pending_adds,
  _ as wishlist_categories_advanced_pending_removals,
  _ as wishlist_categories_advanced_rename_duplicate,
  _ as wishlist_categories_advanced_rename_failed,
  _ as wishlist_categories_advanced_rename_label,
  _ as wishlist_categories_advanced_rename_save,
  _ as wishlist_categories_advanced_revert,
  _ as wishlist_categories_advanced_select,
  _ as wishlist_categories_advanced_select_all,
  _ as wishlist_categories_advanced_select_none,
  _ as wishlist_categories_advanced_showing,
  _ as wishlist_categories_advanced_title,
  _ as wishlist_controls_categories_add,
  _ as wishlist_controls_categories_header_anonymous,
  _ as wishlist_controls_categories_multiselect_label,
  _ as wishlist_controls_demo_available,
  _ as wishlist_controls_demo_available_tooltip,
  _ as wishlist_controls_early_access_tooltip,
  _ as wishlist_controls_filter_tag_label,
  _ as wishlist_controls_options_category_category,
  _ as wishlist_controls_options_category_deck,
  _ as wishlist_controls_options_category_discount,
  _ as wishlist_controls_options_category_exclude,
  _ as wishlist_controls_options_category_platform,
  _ as wishlist_controls_options_category_price,
  _ as wishlist_controls_options_category_related,
  _ as wishlist_controls_options_category_tag,
  _ as wishlist_controls_options_category_type,
  _ as wishlist_controls_options_category_view,
  _ as wishlist_controls_options_deck_playable,
  _ as wishlist_controls_options_deck_verified,
  _ as wishlist_controls_options_discount_all,
  _ as wishlist_controls_options_discount_any,
  _ as wishlist_controls_options_discount_or_more,
  _ as wishlist_controls_options_exclude_vr,
  _ as wishlist_controls_options_platform_all,
  _ as wishlist_controls_options_platform_linux,
  _ as wishlist_controls_options_platform_mac,
  _ as wishlist_controls_options_price_any,
  _ as wishlist_controls_options_price_free,
  _ as wishlist_controls_options_price_max_price,
  _ as wishlist_controls_options_type_application,
  _ as wishlist_controls_options_type_dlc,
  _ as wishlist_controls_options_type_game,
  _ as wishlist_controls_options_type_video,
  _ as wishlist_controls_options_view_compact,
  _ as wishlist_controls_options_view_expanded,
  _ as wishlist_controls_share_description,
  _ as wishlist_controls_share_dialog_title,
  _ as wishlist_controls_share_generation_failure,
  _ as wishlist_controls_share_revokeall,
  _ as wishlist_controls_share_revokeall_success,
  _ as wishlist_controls_sortby_dateadded,
  _ as wishlist_controls_sortby_discount,
  _ as wishlist_controls_sortby_name,
  _ as wishlist_controls_sortby_order,
  _ as wishlist_controls_sortby_price,
  _ as wishlist_controls_sortby_releasedate,
  _ as wishlist_controls_sortby_reviews,
  _ as wishlist_controls_sortby_their_order,
  _ as wishlist_controls_sortby_topsellers,
  _ as wishlist_controls_tag_description,
  _ as wishlist_controls_tags_header,
  _ as wishlist_count,
  _ as wishlist_displayed_item_count,
  _ as wishlist_displayed_item_count_Plural,
  _ as wishlist_error_invalidsharetoken,
  _ as wishlist_error_profilenotfound,
  _ as wishlist_error_wishlistunavailable,
  _ as wishlist_errorpage_title,
  _ as wishlist_filter_matches_categories,
  _ as wishlist_filter_matches_categories_Plural,
  _ as wishlist_filter_matches_category,
  _ as wishlist_filter_matches_category_Plural,
  _ as wishlist_filter_matches_items,
  _ as wishlist_filter_matches_items_Plural,
  _ as wishlist_filter_matches_tag,
  _ as wishlist_filter_matches_tag_Plural,
  _ as wishlist_filter_matches_tags,
  _ as wishlist_filter_matches_tags_Plural,
  _ as wishlist_filter_results,
  _ as wishlist_filters_notification,
  _ as wishlist_gamepad_options,
  _ as wishlist_gamepad_options_remove,
  _ as wishlist_gamepad_visitstore,
  _ as wishlist_gamepaddragdrop_cancelreorder,
  _ as wishlist_gamepaddragdrop_commitreorder,
  _ as wishlist_gamepaddragdrop_reorderaction,
  _ as wishlist_header,
  _ as wishlist_item_add_credit_card,
  _ as wishlist_item_addedon_date,
  _ as wishlist_item_languagespecific_reviews,
  _ as wishlist_item_overallreviews,
  _ as wishlist_item_releasedate,
  _ as wishlist_item_remove,
  _ as wishlist_item_remove_tooltip,
  _ as wishlist_item_unavailable_region,
  _ as wishlist_item_unavailable_retired,
  _ as wishlist_item_unavailable_title,
  _ as wishlist_learn_more_button,
  _ as wishlist_no_items_matching_filters,
  _ as wishlist_options_button,
  _ as wishlist_others_wishlist_empty,
  _ as wishlist_search,
  _ as wishlist_search_all,
  _ as wishlist_share_tooltip,
  _ as wishlist_sign_in_to_see_your_wishlist,
  _ as wishlist_sortby_button,
  _ as wishlist_title,
  _ as wishlist_x_items_on_wishlist_but_none_match,
  _ as wishlist_x_items_on_wishlist_but_none_match_prefs,
  _ as wishlist_your_wishlist_empty,
  _ as youraccount_account,
  _ as youraccount_errorpage_title,
  _ as youraccount_users_account,
};
