var _ = `dutch`,
  _ = `%1$s% van de %2$s gebruikersrecensies voor dit spel is positief`,
  _ = `%1$s% van de %2$s gebruikersrecensies voor dit spel in het %3$s is positief`,
  _ = `%1$s% korting. Normaal %2$s, nu voor %3$s.`,
  _ = `Speciale prijs van %1$s`,
  _ = `Gratis`,
  _ = `In winkelwagen`,
  _ = `Aan winkelwagen toevoegen`,
  _ = `Als geschenk kopen`,
  _ = `Nu spelen`,
  _ = `Toevoegen aan bibliotheek`,
  _ = `Inloggen`,
  _ = `Log in om dit gratis artikel aan je account toe te voegen.`,
  _ = `Menu`,
  _ = `Bestsellers`,
  _ = `Nieuwe uitgaven`,
  _ = `In de uitverkoop`,
  _ = `Zoeken in de winkel`,
  _ = `Zoekterm wissen`,
  _ = `Verlanglijst`,
  _ = `Winkelwagen`,
  _ = `VR-titels`,
  _ = `Populaire links`,
  _ = `Winkel-startpagina`,
  _ = `Geweldig op Deck`,
  _ = `Geweldig op Frame`,
  _ = `Gratis spelen`,
  _ = `Steam-lijsten`,
  _ = `Aankomende uitgaven`,
  _ = `Puntenwinkel`,
  _ = `Cadeaukaarten`,
  _ = `Nieuws en updates`,
  _ = `Voorkeuren`,
  _ = `Bladeren`,
  _ = `Populair`,
  _ = `Aanbevelingen`,
  _ = `Categorieën`,
  _ = `Hardware`,
  _ = `Manieren om te spelen`,
  _ = `Speciale secties`,
  _ = `Alles weergeven`,
  _ = `Meer`,
  _ = `Menu`,
  _ = `Mijn voorkeuren`,
  _ = `Mijn verlanglijst`,
  _ = `Mijn abonnementen`,
  _ = `Mijn gevolgde spellen`,
  _ = `Mijn account`,
  _ = `Mijn gezin`,
  _ = `Onlangs bekeken`,
  _ = `Ga verder waar je gebleven was`,
  _ = `Aanbevolen voor jou`,
  _ = `Van je verlanglijst`,
  _ = `DLC voor jou`,
  _ = `Voor jou`,
  _ = `Populaire bestemmingen`,
  _ = `Populaire bestemmingen`,
  _ = `Nieuw en populair`,
  _ = `Gratis spelen`,
  _ = `Beste gratis te spelen`,
  _ = `Bestsellers`,
  _ = `Nieuwe uitgaven`,
  _ = `Ontdek nieuwe inhoud op Steam`,
  _ = `Bekijk de agenda van nieuwe releases`,
  _ = `Kortingen en evenementen`,
  _ = `Alle lijsten en statistieken`,
  _ = `Bekijk de populairste titels per week, maand of jaar`,
  _ = `Je verlanglijst`,
  _ = `%1$s met korting`,
  _ = `Speciale evenementen`,
  _ = `Populaire titels`,
  _ = `Speciale aanbiedingen`,
  _ = `Aanbevelingen`,
  _ = `Wachtrij nieuwe uitgaven`,
  _ = `Communityaanbevelingen`,
  _ = `Interactief aanbevelingssysteem`,
  _ = `Je persoonlijke agenda`,
  _ = `Populair onder vrienden`,
  _ = `Steam-curators`,
  _ = `DLC voor jou`,
  _ = `Je ontdekkingswachtrij`,
  _ = `Laat Steam speciaal voor jou een gepersonaliseerde lijst samenstellen van aanbevolen spellen`,
  _ = `Mijn ontdekkingswachtrij verkennen`,
  _ = `Krijg gepersonaliseerde aanbevelingen van ons interactieve systeem met machinelearning`,
  _ = `Aanbevelingen bekijken`,
  _ = `Verken een speciaal voor jou samengestelde lijst van spellen die onlangs zijn uitgekomen of binnenkort worden verwacht.`,
  _ = `Mijn agenda verkennen`,
  _ = `NIEUW`,
  _ = `Je favoriete genres`,
  _ = `Je favoriete categorieën`,
  _ = `Alle genres en thema's weergeven`,
  _ = `Uitvouwen`,
  _ = `Inklappen`,
  _ = `Alle tags weergeven`,
  _ = `Alle genres en thema's`,
  _ = `Hardware`,
  _ = `VR-hardware`,
  _ = `Steam Deck`,
  _ = `Steam Controller`,
  _ = `Steam Machine`,
  _ = `Steam Frame`,
  _ = `Valve Index`,
  _ = `Dock`,
  _ = `Steam-hardware`,
  _ = `Manieren om te spelen`,
  _ = `Speciale secties`,
  _ = `Steam Next Festival`,
  _ = `De Steam Awards`,
  _ = `Steam Replay`,
  _ = `Steam-laboratoria`,
  _ = `DLC`,
  _ = `UITVERKOPEN`,
  _ = `Onlangs bekeken`,
  _ = `Populaire zoekopdrachten`,
  _ = `Zoekresultaten`,
  _ = `Je favoriete genres`,
  _ = `Sorteren op ...`,
  _ = `Er zijn geen resultaten voor je zoekopdracht.`,
  _ = `Geavanceerd zoeken`,
  _ = `%1$s spellen`,
  _ = `Zoeken`,
  _ = `Winkelmenu`,
  _ = `Bevat %1$s spellen`,
  _ = `IN BIBLIOTHEEK`,
  _ = `OP VERLANGLIJST`,
  _ = `IN WINKELWAGEN`,
  _ = `GENEGEERD`,
  _ = `UITGESLOTEN DOOR VOORKEUREN`,
  _ = `Mijn categorieën:`,
  _ = `Geen`,
  _ = `Filteren op categorie`,
  _ = `Categoriefilters wissen`,
  _ = `Categorie toevoegen`,
  _ = `Categorie verwijderen`,
  _ = `Deze categorie van dit artikel verwijderen`,
  _ = `Je verlanglijst filteren op artikelen in deze categorie`,
  _ = `Alle`,
  _ = `Ongecategoriseerd`,
  _ = `Categorieën toevoegen of verwijderen`,
  _ = `Wachten op uitverkoop`,
  _ = `Verjaardagslijstje`,
  _ = `Aanbevolen door vrienden`,
  _ = `Categorieën beheren voor %1$s`,
  _ = `Huidige categorieën`,
  _ = `Zoeken op naam of een nieuwe categorie toevoegen`,
  _ = `Categorie toevoegen`,
  _ = `Mijn andere categorieën`,
  _ = `Aanbevolen categorieën`,
  _ = `Dit artikel op je verlanglijst heeft de limiet van %1$s categorieën bereikt.`,
  _ = `Geavanceerd ...`,
  _ = `NORMAAL`,
  _ = `LAAGSTE IN 30 DAGEN`,
  _ = `Dit spel was in de afgelopen %2$s dagen in de uitverkoop voor %1$s.`,
  _ = `De huidige prijs voor dit spel is de laagste prijs in de afgelopen %1$s dagen.`,
  _ = `NU`,
  _ = `Korting op basis van de laagste prijs in de afgelopen 30 dagen`,
  _ = `Je persoonlijke agenda`,
  _ = `Een speciaal voor jou samengestelde lijst van nieuwe en binnenkort verwachte spellen`,
  _ = `+ nog %1$s`,
  _ = `Je volledige persoonlijke agenda bekijken`,
  _ = `Meer ontdekken`,
  _ = `We hebben op deze dag geen nieuwe uitgaven die we je kunnen aanbevelen <1>Bekijk de rest van je agenda!</1>`,
  _ = `NIEUW`,
  _ = `Vandaag`,
  _ = `dont translate`,
  _ = {
    language: _,
    review_summary_reviewrate: _,
    review_summary_reviewrate_language_specific: _,
    Discount_ARIA_Label: _,
    Discount_ARIA_Label_SpecialPrice: _,
    Price_Free: _,
    AddToCartButton_InCart: _,
    AddToCartButton_AddToCart: _,
    AddToCartButton_PurchaseAsGift: _,
    PlayGameButton_PlayNow: _,
    AddToLibraryButton: _,
    Button_SignIn: _,
    SignInToAddToLibrary_Tooltip: _,
    Menu_OpenFlyout: _,
    Menu_TopSellers: _,
    Menu_NewReleases: _,
    Menu_OnSale: _,
    Menu_SearchPlaceholder: _,
    Menu_ClearSearchTerm: _,
    Menu_Wishlist: _,
    Menu_Cart: _,
    Menu_VR: _,
    Menu_Popover_TopLinks: _,
    Menu_Popover_StoreHome: _,
    Menu_Popover_GreatonDeck: _,
    Menu_Popover_GreatonFrame: _,
    Menu_Popover_FreeToPlay: _,
    Menu_Popover_SteamCharts: _,
    Menu_Popover_Upcoming: _,
    Menu_Popover_PointsShop: _,
    Menu_Popover_GiftCards: _,
    Menu_Popover_NewsAndUpdates: _,
    Menu_Popover_Preferences: _,
    Menu_Popover_Browse: _,
    Menu_Popover_Top: _,
    Menu_Popover_Recommendations: _,
    Menu_Popover_Categories: _,
    Menu_Popover_Hardware: _,
    Menu_Popover_WaysToPlay: _,
    Menu_Popover_SpecialSections: _,
    Menu_Popover_ViewAll: _,
    Menu_Popover_More: _,
    Menu_Popover_Menu: _,
    Menu_Section_Browse_MyPreferences: _,
    Menu_Section_Browse_MyWishlist: _,
    Menu_Section_Browse_MySubscriptions: _,
    Menu_Section_Browse_MyFollowedGames: _,
    Menu_Section_Browse_MyAccount: _,
    Menu_Section_Browse_MyFamily: _,
    Menu_Section_Browse_RecentlyViewed: _,
    Menu_Section_Browse_PickUpWhereYouLeftOff: _,
    Menu_Section_Browse_Recommended: _,
    Menu_Section_Browse_FromYourWishlist: _,
    Menu_Section_Browse_DLCForYou: _,
    Menu_Section_Browse_ForYou: _,
    Menu_Section_Browse_BrowseTop: _,
    Menu_Section_Browse_Top: _,
    Menu_Section_Browse_PopularNew: _,
    Menu_Section_Browse_FreeToPlay: _,
    Menu_Section_Browse_TopFreeToPlay: _,
    Menu_Section_Browse_TopSellers: _,
    Menu_Section_Browse_NewReleases: _,
    Menu_Section_Browse_NewReleases_Desc: _,
    Menu_Section_Browse_Upcoming_Desc: _,
    Menu_Section_Browse_Discounts: _,
    Menu_Section_Browse_Charts: _,
    Menu_Section_Browse_Charts_Desc: _,
    Menu_Section_Browse_Discounts_YourWishlist: _,
    Menu_Section_Browse_Discounts_YourWishlist_Discounts: _,
    Menu_Section_Browse_Discounts_SpecialEvents: _,
    Menu_Section_Browse_Discounts_PopularTitles: _,
    Menu_Section_Browse_Discounts_SpecialOffers: _,
    Menu_Section_Recommendations: _,
    Menu_Section_Recommendations_NewReleasesQueue: _,
    Menu_Section_Recommendations_CommunityRecommendations: _,
    Menu_Section_Recommendations_InteractiveRecommender: _,
    Menu_Section_Recommendations_PersonalCalendar: _,
    Menu_Section_Recommendations_PopularAmongFriends: _,
    Menu_Section_Recommendations_SteamCurators: _,
    Menu_Section_Recommendations_DLCForYou: _,
    Menu_Section_Recommendations_DiscoveryQueue_Title: _,
    Menu_Section_Recommendations_DiscoveryQueue_Description: _,
    Menu_Section_Recommendations_DiscoveryQueue_ActionButton: _,
    Menu_Section_Recommendations_InteractiveRecommender_Description: _,
    Menu_Section_Recommendations_InteractiveRecommender_ActionButton: _,
    Menu_Section_Recommendations_PersonalCalendar_Description: _,
    Menu_Section_Recommendations_PersonalCalendar_ActionButton: _,
    Menu_Section_Recommendations_New: _,
    Menu_Section_Categories_YourTopGenres: _,
    Menu_Section_Categories_YourTopCategories: _,
    Menu_Section_Categories_ViewAll: _,
    Menu_Section_Categories_Expand: _,
    Menu_Section_Categories_Collapse: _,
    Menu_Section_Categories_ViewAllTags: _,
    Menu_Section_Categories_GenresAndThemes: _,
    Menu_Section_Hardware: _,
    Menu_Section_Hardware_VRHardware: _,
    Menu_Section_Hardware_SteamDeck: _,
    Menu_Section_Hardware_SteamController: _,
    Menu_Section_Hardware_SteamMachine: _,
    Menu_Section_Hardware_SteamFrame: _,
    Menu_Section_Hardware_ValveIndex: _,
    Menu_Section_Hardware_SteamDeckDock: _,
    Menu_Section_Hardware_Family: _,
    Menu_Section_WaysToPlay: _,
    Menu_Section_SpecialSections: _,
    Menu_Section_SpecialSections_NextFest: _,
    Menu_Section_SpecialSections_SteamAwards: _,
    Menu_Section_SpecialSections_SteamReplay: _,
    Menu_Section_SpecialSections_SteamLabs: _,
    Menu_Section_SpecialSections_DLCForYou: `DLC`,
    Menu_Section_SpecialSections_SaleEvents: _,
    Menu_SearchBar_RecentlyViewed: _,
    Menu_SearchBar_PopularSearches: _,
    Menu_SearchBar_SearchResults: _,
    Menu_SearchBar_YourTopGenres: _,
    Menu_SearchBar_BrowseBy: _,
    Menu_SearchBar_NoMatches: _,
    Menu_SearchBar_AdvancedSearch: _,
    Menu_SearchBar_CategoryGameCount: _,
    Menu_Search: _,
    Menu_Label: _,
    Menu_IncludesXGames: _,
    ItemFlag_InLibrary: _,
    ItemFlag_OnWishlist: _,
    ItemFlag_InCart: _,
    ItemFlag_Ignored: _,
    ItemFlag_ExcludedByPreferences: _,
    Wishlist_Controls_Categories_Header: _,
    Wishlist_Categories_None: _,
    Wishlist_Gamepad_Filter_Category: _,
    Wishlist_Gamepad_Filter_Clear_Category: _,
    Wishlist_Gamepad_Add_Category: _,
    Wishlist_Gamepad_Removecategory: _,
    Wishlist_Controls_Categories_Remove_Tooltip: _,
    Wishlist_Controls_Categories_Filter_Tooltip: _,
    Wishlist_Controls_Categories_All: _,
    Wishlist_Controls_Categories_Uncategorized: _,
    Wishlist_Controls_Categories_Manage: _,
    Wishlist_Categories_Suggested_Discount: _,
    Wishlist_Categories_Suggested_Birthday: _,
    Wishlist_Categories_Suggested_Recommended: _,
    Wishlist_Controls_Categories_Manageitem: _,
    Wishlist_Controls_Categories_Header_Current: _,
    Wishlist_Categories_Dialog_Search: _,
    Wishlist_Categories_Dialog_Add: _,
    Wishlist_Controls_Categories_Header_Other: _,
    Wishlist_Controls_Categories_Header_Suggested: _,
    Wishlist_Categories_Max_Per_App_Reached: _,
    Wishlist_Categories_Dialog_Advanced: _,
    Price_History_Normal_Price: _,
    Price_History_Recent_Low_Price: _,
    Price_History_Recent_Low_Price_Ttip: _,
    Price_History_Current_Low_Price_Ttip: _,
    Price_History_Current_Price: `NU`,
    Price_History_Lowest_Previous_30: _,
    PersonalCalendar_Title: _,
    PersonalCalendar_Subtitle: _,
    PersonalCalendar_More: _,
    PersonalCalendar_Full: _,
    PersonalCalendar_Explore: _,
    PersonalCalendar_EmptyDay: _,
    NewBadge: _,
    Time_Today: _,
    store_ui_dummy: _,
  };
export {
  _ as AddToCartButton_AddToCart,
  _ as AddToCartButton_InCart,
  _ as AddToCartButton_PurchaseAsGift,
  _ as AddToLibraryButton,
  _ as Button_SignIn,
  _ as Discount_ARIA_Label,
  _ as Discount_ARIA_Label_SpecialPrice,
  _ as ItemFlag_ExcludedByPreferences,
  _ as ItemFlag_Ignored,
  _ as ItemFlag_InCart,
  _ as ItemFlag_InLibrary,
  _ as ItemFlag_OnWishlist,
  _ as Menu_Cart,
  _ as Menu_ClearSearchTerm,
  _ as Menu_IncludesXGames,
  _ as Menu_Label,
  _ as Menu_NewReleases,
  _ as Menu_OnSale,
  _ as Menu_OpenFlyout,
  _ as Menu_Popover_Browse,
  _ as Menu_Popover_Categories,
  _ as Menu_Popover_FreeToPlay,
  _ as Menu_Popover_GiftCards,
  _ as Menu_Popover_GreatonDeck,
  _ as Menu_Popover_GreatonFrame,
  _ as Menu_Popover_Hardware,
  _ as Menu_Popover_Menu,
  _ as Menu_Popover_More,
  _ as Menu_Popover_NewsAndUpdates,
  _ as Menu_Popover_PointsShop,
  _ as Menu_Popover_Preferences,
  _ as Menu_Popover_Recommendations,
  _ as Menu_Popover_SpecialSections,
  _ as Menu_Popover_SteamCharts,
  _ as Menu_Popover_StoreHome,
  _ as Menu_Popover_Top,
  _ as Menu_Popover_TopLinks,
  _ as Menu_Popover_Upcoming,
  _ as Menu_Popover_ViewAll,
  _ as Menu_Popover_WaysToPlay,
  _ as Menu_Search,
  _ as Menu_SearchBar_AdvancedSearch,
  _ as Menu_SearchBar_BrowseBy,
  _ as Menu_SearchBar_CategoryGameCount,
  _ as Menu_SearchBar_NoMatches,
  _ as Menu_SearchBar_PopularSearches,
  _ as Menu_SearchBar_RecentlyViewed,
  _ as Menu_SearchBar_SearchResults,
  _ as Menu_SearchBar_YourTopGenres,
  _ as Menu_SearchPlaceholder,
  _ as Menu_Section_Browse_BrowseTop,
  _ as Menu_Section_Browse_Charts,
  _ as Menu_Section_Browse_Charts_Desc,
  _ as Menu_Section_Browse_DLCForYou,
  _ as Menu_Section_Browse_Discounts,
  _ as Menu_Section_Browse_Discounts_PopularTitles,
  _ as Menu_Section_Browse_Discounts_SpecialEvents,
  _ as Menu_Section_Browse_Discounts_SpecialOffers,
  _ as Menu_Section_Browse_Discounts_YourWishlist,
  _ as Menu_Section_Browse_Discounts_YourWishlist_Discounts,
  _ as Menu_Section_Browse_ForYou,
  _ as Menu_Section_Browse_FreeToPlay,
  _ as Menu_Section_Browse_FromYourWishlist,
  _ as Menu_Section_Browse_MyAccount,
  _ as Menu_Section_Browse_MyFamily,
  _ as Menu_Section_Browse_MyFollowedGames,
  _ as Menu_Section_Browse_MyPreferences,
  _ as Menu_Section_Browse_MySubscriptions,
  _ as Menu_Section_Browse_MyWishlist,
  _ as Menu_Section_Browse_NewReleases,
  _ as Menu_Section_Browse_NewReleases_Desc,
  _ as Menu_Section_Browse_PickUpWhereYouLeftOff,
  _ as Menu_Section_Browse_PopularNew,
  _ as Menu_Section_Browse_RecentlyViewed,
  _ as Menu_Section_Browse_Recommended,
  _ as Menu_Section_Browse_Top,
  _ as Menu_Section_Browse_TopFreeToPlay,
  _ as Menu_Section_Browse_TopSellers,
  _ as Menu_Section_Browse_Upcoming_Desc,
  _ as Menu_Section_Categories_Collapse,
  _ as Menu_Section_Categories_Expand,
  _ as Menu_Section_Categories_GenresAndThemes,
  _ as Menu_Section_Categories_ViewAll,
  _ as Menu_Section_Categories_ViewAllTags,
  _ as Menu_Section_Categories_YourTopCategories,
  _ as Menu_Section_Categories_YourTopGenres,
  _ as Menu_Section_Hardware,
  _ as Menu_Section_Hardware_Family,
  _ as Menu_Section_Hardware_SteamController,
  _ as Menu_Section_Hardware_SteamDeck,
  _ as Menu_Section_Hardware_SteamDeckDock,
  _ as Menu_Section_Hardware_SteamFrame,
  _ as Menu_Section_Hardware_SteamMachine,
  _ as Menu_Section_Hardware_VRHardware,
  _ as Menu_Section_Hardware_ValveIndex,
  _ as Menu_Section_Recommendations,
  _ as Menu_Section_Recommendations_CommunityRecommendations,
  _ as Menu_Section_Recommendations_DLCForYou,
  _ as Menu_Section_Recommendations_DiscoveryQueue_ActionButton,
  _ as Menu_Section_Recommendations_DiscoveryQueue_Description,
  _ as Menu_Section_Recommendations_DiscoveryQueue_Title,
  _ as Menu_Section_Recommendations_InteractiveRecommender,
  _ as Menu_Section_Recommendations_InteractiveRecommender_ActionButton,
  _ as Menu_Section_Recommendations_InteractiveRecommender_Description,
  _ as Menu_Section_Recommendations_New,
  _ as Menu_Section_Recommendations_NewReleasesQueue,
  _ as Menu_Section_Recommendations_PersonalCalendar,
  _ as Menu_Section_Recommendations_PersonalCalendar_ActionButton,
  _ as Menu_Section_Recommendations_PersonalCalendar_Description,
  _ as Menu_Section_Recommendations_PopularAmongFriends,
  _ as Menu_Section_Recommendations_SteamCurators,
  _ as Menu_Section_SpecialSections,
  _ as Menu_Section_SpecialSections_DLCForYou,
  _ as Menu_Section_SpecialSections_NextFest,
  _ as Menu_Section_SpecialSections_SaleEvents,
  _ as Menu_Section_SpecialSections_SteamAwards,
  _ as Menu_Section_SpecialSections_SteamLabs,
  _ as Menu_Section_SpecialSections_SteamReplay,
  _ as Menu_Section_WaysToPlay,
  _ as Menu_TopSellers,
  _ as Menu_VR,
  _ as Menu_Wishlist,
  _ as NewBadge,
  _ as PersonalCalendar_EmptyDay,
  _ as PersonalCalendar_Explore,
  _ as PersonalCalendar_Full,
  _ as PersonalCalendar_More,
  _ as PersonalCalendar_Subtitle,
  _ as PersonalCalendar_Title,
  _ as PlayGameButton_PlayNow,
  _ as Price_Free,
  _ as Price_History_Current_Low_Price_Ttip,
  _ as Price_History_Current_Price,
  _ as Price_History_Lowest_Previous_30,
  _ as Price_History_Normal_Price,
  _ as Price_History_Recent_Low_Price,
  _ as Price_History_Recent_Low_Price_Ttip,
  _ as SignInToAddToLibrary_Tooltip,
  _ as Time_Today,
  _ as Wishlist_Categories_Dialog_Add,
  _ as Wishlist_Categories_Dialog_Advanced,
  _ as Wishlist_Categories_Dialog_Search,
  _ as Wishlist_Categories_Max_Per_App_Reached,
  _ as Wishlist_Categories_None,
  _ as Wishlist_Categories_Suggested_Birthday,
  _ as Wishlist_Categories_Suggested_Discount,
  _ as Wishlist_Categories_Suggested_Recommended,
  _ as Wishlist_Controls_Categories_All,
  _ as Wishlist_Controls_Categories_Filter_Tooltip,
  _ as Wishlist_Controls_Categories_Header,
  _ as Wishlist_Controls_Categories_Header_Current,
  _ as Wishlist_Controls_Categories_Header_Other,
  _ as Wishlist_Controls_Categories_Header_Suggested,
  _ as Wishlist_Controls_Categories_Manage,
  _ as Wishlist_Controls_Categories_Manageitem,
  _ as Wishlist_Controls_Categories_Remove_Tooltip,
  _ as Wishlist_Controls_Categories_Uncategorized,
  _ as Wishlist_Gamepad_Add_Category,
  _ as Wishlist_Gamepad_Filter_Category,
  _ as Wishlist_Gamepad_Filter_Clear_Category,
  _ as Wishlist_Gamepad_Removecategory,
  _ as default,
  _ as language,
  _ as review_summary_reviewrate,
  _ as review_summary_reviewrate_language_specific,
  _ as store_ui_dummy,
};
