var _ = `bulgarian`,
  _ = `Играйте безплатно! Приключва след %1$s.`,
  _ = `Офертата е валидна до %1$s.`,
  _ = `Играйте безплатно!`,
  _ = `Безплатен уикенд`,
  _ = `Играйте безплатно до понеделник в 20:00 часа българско време`,
  _ = `Пускайте безплатно до %1$s`,
  _ = `Безплатна седмица`,
  _ = `Току-що обновено`,
  _ = `САМО ЗА ОГРАНИЧЕНО ВРЕМЕ`,
  _ = `Предплатете и играйте бетата сега!`,
  _ = `ПУСНЕТЕ БЕТАТА СЕГА!`,
  _ = `Предплатете и получавате бета достъп`,
  _ = `Steam работилница вече е достъпна`,
  _ = `Вече в Steam работилницата`,
  _ = `Вече със Steamworks`,
  _ = `Вече достъпно за SteamOS!`,
  _ = `Вече достъпно за SteamOS, Mac и Linux!`,
  _ = `Предварително сваляне сега`,
  _ = `Безплатно обновление`,
  _ = `Пуснете демото сега!`,
  _ = `Предварително сваляне (безплатно)`,
  _ = `Безплатно предварително сваляне сега`,
  _ = `Вие свалихте предварително`,
  _ = `Вие завършихте предварителното сваляне`,
  _ = `Предварителното сваляне е завършено`,
  _ = `Предплатете сега`,
  _ = `Току-що обновено с безплатно сваляемо съдържание!`,
  _ = `Вече достъпно за Mac и SteamOS!`,
  _ = `Скоро за SteamOS!`,
  _ = `Сваляне и гледане на филма във Full HD резолюция`,
  _ = `Добавяне към списъка с желания`,
  _ = `Вече достъпно в „Ранен достъп“`,
  _ = `в „Ранен достъп“`,
  _ = `Достъпно е ново обновление`,
  _ = `Безплатно`,
  _ = `Новоиздадени`,
  _ = `Току-що издадена от „Ранен достъп“!`,
  _ = `Току-що издадени`,
  _ = `Вече достъпно`,
  _ = `Нова игра`,
  _ = `Вече достъпно — Безплатно за пускане`,
  _ = `Безплатно за пускане — Току-що обновено`,
  _ = `Вече безплатно за пускане в „Ранен достъп“`,
  _ = `Достъпен „Разширен достъп“`,
  _ = `Вече е достъпно ново съдържание`,
  _ = `Пускайте цялата игра безплатно, само този уикенд`,
  _ = `Безплатен уикенд — започва сега`,
  _ = `Безплатен пробен период за пълната игра`,
  _ = `Играйте сега безплатно`,
  _ = `Предплатете и получавате бонус`,
  _ = `Най-продавани`,
  _ = `Новоиздадени`,
  _ = `Уикенд сделка`,
  _ = `Средседмична сделка`,
  _ = `Средседмична сделка`,
  _ = `Разпродажба на поредица`,
  _ = `Събитие от трети страни`,
  _ = `Значително обновление`,
  _ = `Дневна сделка`,
  _ = `Седмична разпродажба`,
  _ = `Седмични`,
  _ = `Томбола!`,
  _ = `За ограничено време, инсталирайте сега и запазете завинаги`,
  _ = `Очаквайте скоро`,
  _ = `Нови и предстоящи`,
  _ = `Отличени сделки`,
  _ = `Продуктов каталог`,
  _ = `Уикенд на издателя`,
  _ = `Разпродажба на издателя`,
  _ = `Инсталиране`,
  _ = `ОТСТЪПКА ЗА ЛОЯЛНИ КЛИЕНТИ! Офертата е валидна до %1$s`,
  _ = `Кликнете за подробности`,
  _ = `Пускане сега`,
  _ = `Пускане сега`,
  _ = `Купуване сега`,
  _ = `Кликнете тук за още информация`,
  _ = `На разпродажба сега!`,
  _ = `Ранен достъп до бета`,
  _ = `Достъпно е ново сваляемо съдържание`,
  _ = `Предварително сваляне сега`,
  _ = `Най-дълбока отстъпка`,
  _ = `Оферта с ограничено време`,
  _ = `Оферта с ограничено време`,
  _ = `Вече достъпно`,
  _ = `Вече достъпно`,
  _ = `Вече достъпно на Mac`,
  _ = `Вече достъпно на Windows, Mac и Linux!`,
  _ = `Вече безплатно за пускане`,
  _ = `Ново безплатно за пускане`,
  _ = `Достъпно е ново безплатно сваляемо съдържание`,
  _ = `Екшъни и стрелбищни от първо лице`,
  _ = `Екшъни и стрелбищни от първо лице`,
  _ = `Екшъни с двуизмерен изглед`,
  _ = `Екшън с двуизмерен изглед`,
  _ = `Екшъни и стрелбищни игри от трето лице`,
  _ = `Екшън и стрелбищна от трето лице`,
  _ = `Екшъни`,
  _ = `Екшъни`,
  _ = `Екшън приключенски`,
  _ = `Екшън приключенски`,
  _ = `Екшън и приключенски`,
  _ = `Екшън и приключенски`,
  _ = `Стрелбищни от първо лице`,
  _ = `Стрелбищни от първо лице`,
  _ = `Екшън ужаси`,
  _ = `Екшън ужас`,
  _ = `Екшъни подобни на Rogue`,
  _ = `Екшън подобна на Rogue`,
  _ = `Екшън ролеви`,
  _ = `Екшън ролеви игри`,
  _ = `Платформъри и бегачи`,
  _ = `Платформъри и бегачи`,
  _ = `Стрелбищни`,
  _ = `Стрелбищни`,
  _ = `Стрелбищни от трето лице`,
  _ = `Стрелбищни от трето лице`,
  _ = `Екшъни и дейности`,
  _ = `Екшъни и дейности`,
  _ = `Приключенски`,
  _ = `Приключенска`,
  _ = `Приключенски и неангажиращи`,
  _ = `Приключенска и неангажираща`,
  _ = `Отворен свят`,
  _ = `Отворен свят`,
  _ = `Приключенски с посочване и кликване`,
  _ = `Приключенска с посочване и кликване`,
  _ = `Приключенски ролеви`,
  _ = `Приключенски ролеви`,
  _ = `Неангажиращи ролеви`,
  _ = `Неангажиращи ролеви`,
  _ = `Естетически приятни`,
  _ = `Тематики`,
  _ = `Аниме`,
  _ = `Аниме`,
  _ = `Аркадни`,
  _ = `Аркадни`,
  _ = `Аркадни и ритъмни`,
  _ = `Аркадни и ритъмни`,
  _ = `Художествени стилове и музика`,
  _ = `Художествени стилове и музика`,
  _ = `Ръкопашни схватки`,
  _ = `Ръкопашни схватки`,
  _ = `Бизнес и политически`,
  _ = `Бизнес и политически`,
  _ = `Неангажиращи`,
  _ = `Неангажираща`,
  _ = `Неангажиращи с карти и на дъска`,
  _ = `Неангажиращи с карти и на дъска`,
  _ = `Неангажиращи и пъзели`,
  _ = `Неангажиращи и пъзели`,
  _ = `Неангажиращи и сюжетни`,
  _ = `Неангажираща и сюжетна`,
  _ = `Неангажиращи пъзели`,
  _ = `Неангажиращи пъзели`,
  _ = `Екшън игри с персонаж`,
  _ = `Кликърски и бездействащи`,
  _ = `Кликърски и бездействащи`,
  _ = `Криминални и правосъдни`,
  _ = `Криминални и правосъдни`,
  _ = `Привлекателни и анимационни`,
  _ = `Привлекателни и анимационни`,
  _ = `Симулатори за срещи`,
  _ = `Симулатори за срещи`,
  _ = `Шофиране и пилотиране`,
  _ = `Шофиране и пилотиране`,
  _ = `Научни и образователни`,
  _ = `Научни и образователни`,
  _ = `Експериментални`,
  _ = `Експериментални`,
  _ = `Отворен свят`,
  _ = `Отворен свят`,
  _ = `Фентъзи`,
  _ = `Фентъзи`,
  _ = `Фентъзи и свръхестествени`,
  _ = `Фентъзи и свръхестествени`,
  _ = `Бойни`,
  _ = `Бойни`,
  _ = `Бой и бойни изкуства`,
  _ = `Бой и бойни изкуства`,
  _ = `Безплатни за пускане`,
  _ = `Хак енд слаш`,
  _ = `Скрити обекти`,
  _ = `Скрити обекти`,
  _ = `Исторически`,
  _ = `Ужаси`,
  _ = `Ужаси`,
  _ = `Мрачни и ужаси`,
  _ = `Мрачна и ужас`,
  _ = `Фестивал „Steam писък“`,
  _ = `Фестивал за строене на бази`,
  _ = `Стелт`,
  _ = `Престрелки`,
  _ = `Пищен сюжет`,
  _ = `Пищен сюжет`,
  _ = `Interactive Stories`,
  _ = `Интерактивен сюжет`,
  _ = `Симулатори на живот`,
  _ = `Местонахождения и светове`,
  _ = `Напаснете 3`,
  _ = `Напаснете 3`,
  _ = `Мрежови`,
  _ = `Мрежови`,
  _ = `Войскови и военни`,
  _ = `Войскови и военни`,
  _ = `Минималистични и абстрактни`,
  _ = `Минималистични и абстрактни`,
  _ = `Мрежови`,
  _ = `Мрежови`,
  _ = `Съревнователни мрежови`,
  _ = `Съревнователни`,
  _ = `Величествени битки`,
  _ = `Величествени битки`,
  _ = `Кооперативни`,
  _ = `Кооперативни`,
  _ = `Локално мрежови игри`,
  _ = `Локална мрежа`,
  _ = `Локални мрежови и дружинни`,
  _ = `Локални и екипни`,
  _ = `Масивни мрежови`,
  _ = `Масивна мрежова игра`,
  _ = `МОБА и авт. бойни`,
  _ = `МОБА и авт. бойни`,
  _ = `Съревнователни на линия`,
  _ = `Съревнователни на линия`,
  _ = `Мрежови стрелбищни`,
  _ = `Стрелбищни`,
  _ = `Музикални и ритъмни`,
  _ = `Музикални и ритъмни`,
  _ = `Oтворен свят за оцеляване и изработване`,
  _ = `Oтворен свят за оцеляване и изработване`,
  _ = `Хора и създания`,
  _ = `Играчи`,
  _ = `Психеделични`,
  _ = `Психеделични`,
  _ = `Психеделични и сюрреалистични`,
  _ = `Психеделични и сюрреалистични`,
  _ = `Пъзели`,
  _ = `Пъзели`,
  _ = `Пъзели`,
  _ = `Пъзели`,
  _ = `Трудни пъзели`,
  _ = `Трудни пъзели`,
  _ = `Логически пъзели`,
  _ = `Логически пъзели`,
  _ = `Мрежови пъзели`,
  _ = `Мрежови пъзели`,
  _ = `Състезателни`,
  _ = `Съревнование с коли, велосипеди, ски и още други.`,
  _ = `Състезателни`,
  _ = `Състезателни симулатори`,
  _ = `Състезателни симулатори`,
  _ = `Състезателни битки`,
  _ = `Състезателни битки`,
  _ = `Състезаване и пилотиране`,
  _ = `Състезаване и пилотиране`,
  _ = `Ретро`,
  _ = `Ретро`,
  _ = `Отпускащи`,
  _ = `Отпускащи`,
  _ = `Metroidvania`,
  _ = `Metroidvania`,
  _ = `Минималистични и отпускащи`,
  _ = `Минималистични и отпускащи`,
  _ = `Походови подобни на Rogue`,
  _ = `Походови подобни на Rogue`,
  _ = `Подобни на Rogue и с елементи от Rogue`,
  _ = `Подобна на Rogue`,
  _ = `Подобни на Rogue`,
  _ = `Подобна на Rogue`,
  _ = `Ролеви`,
  _ = `Ролеви`,
  _ = `Екшън ролеви`,
  _ = `Екшън ролеви игри`,
  _ = `Компютърни ролеви`,
  _ = `Компютърни ролеви`,
  _ = `Компютърни ролеви`,
  _ = `Компютърни ролеви`,
  _ = `Приключения в тъмници`,
  _ = `Приключения в тъмници`,
  _ = `Японски ролеви`,
  _ = `Японски ролеви`,
  _ = `Масивни мрежови ролеви игри на линия`,
  _ = `Масивни мрежови ролеви на линия`,
  _ = `Дружинно базирани ролеви`,
  _ = `Екипно базирани`,
  _ = `Ролеви, водени от сюжета`,
  _ = `Водена от сюжета`,
  _ = `Стратегически и тактически ролеви`,
  _ = `Стратегически ролеви`,
  _ = `Походови ролеви`,
  _ = `Походови`,
  _ = `Научнофантастични и киберпънк`,
  _ = `Научнофантастични и киберпънк`,
  _ = `Стрелбищни`,
  _ = `Стрелбищни`,
  _ = `Строителни симулатори`,
  _ = `Строителство`,
  _ = `Симулатори за строителство и автоматизация`,
  _ = `Строителство и автоматизация`,
  _ = `Бизнес и магнатски`,
  _ = `Бизнес и магнат`,
  _ = `Симулатори на градоустройствени и населени места`,
  _ = `Градоустройствени и населени места`,
  _ = `Селскостопански симулатори`,
  _ = `Селскостопански`,
  _ = `Симулатори за селско стопанство и изработване`,
  _ = `Селско стопанство и изработване`,
  _ = `Симулатори на живот и завладяващи симулатори`,
  _ = `Живот и завладяващи`,
  _ = `Симулатори на живот и романтика`,
  _ = `Живот и романтика`,
  _ = `Симулатори и управленчески`,
  _ = `Симулатори и управленчески`,
  _ = `Симулатори с отворен свят`,
  _ = `Отворен свят`,
  _ = `Пясъчници и физични симулатори`,
  _ = `Пясъчници и физични`,
  _ = `Политически симулатори`,
  _ = `Политика`,
  _ = `Симулатори на пясъчници и обожествяващи игри`,
  _ = `Пясъчници и обожествяващи игри`,
  _ = `Космически и летателни симулатори`,
  _ = `Космически и летателни`,
  _ = `Симулатори за срещи`,
  _ = `Срещи`,
  _ = `Симулатори`,
  _ = `Симулатор`,
  _ = `Самостоятелни`,
  _ = `Самостоятелни`,
  _ = `Поддръжка за играчи`,
  _ = `Спортни`,
  _ = `Управлявайте отбор, тренирайте за големия турнир или просто играйте.`,
  _ = `Всички спортни`,
  _ = `Спортни и състезателни`,
  _ = `Спортни и състезателни`,
  _ = `Спортни с топка`,
  _ = `Спортна с топка`,
  _ = `Бойни спортни`,
  _ = `Бойни спортни`,
  _ = `Ловни и риболовни`,
  _ = `Ловни и риболовни`,
  _ = `Индивидуални спортни`,
  _ = `Индивидуални спортни`,
  _ = `Спортни симулатори и спортни управленчески`,
  _ = `Спортни симулатори`,
  _ = `Отборни спортни`,
  _ = `Отборни спортни`,
  _ = `Зимни спортни`,
  _ = `Зимни спортни`,
  _ = `Призрачни`,
  _ = `Призрачна`,
  _ = `Водени от сюжета`,
  _ = `Водена от сюжета`,
  _ = `Стратегии`,
  _ = `Стратегии`,
  _ = `С карти и на дъска`,
  _ = `С карти и на дъска`,
  _ = `Изграждане на градоустройствени и населени места`,
  _ = `Градоустройствени и населени места`,
  _ = `Гранд стратегии и 4X`,
  _ = `Гранд и 4X`,
  _ = `Войскови стратегически`,
  _ = `Войскови`,
  _ = `МОБА и авт. бойни`,
  _ = `МОБА и авт. бойни`,
  _ = `Реално времеви стратегии`,
  _ = `Реално времеви стратегии`,
  _ = `Симулатори и управленчески`,
  _ = `Симулатори и управленчески`,
  _ = `Стратегически и тактически`,
  _ = `Стратегически и тактически`,
  _ = `Походови стратегии`,
  _ = `Походови стратегии`,
  _ = `Оцеляване`,
  _ = `Оцеляване`,
  _ = `Оцеляване и стелт`,
  _ = `Оцеляване и стелт`,
  _ = `Тематики`,
  _ = `Тематики`,
  _ = `Тематика и интереси`,
  _ = `Тематики`,
  _ = `Времево управленчески`,
  _ = `Времево управленчески`,
  _ = `Отбранителни кули`,
  _ = `Отбранителни кули`,
  _ = `Графични новели`,
  _ = `Графични новели`,
  _ = `Пешеходни симулатори`,
  _ = `Пешеходни симулатори`,
  _ = `Космически`,
  _ = `Космически`,
  _ = `Жени протагонисти`,
  _ = `Жени протагонисти`,
  _ = `ЛГБТК+`,
  _ = `ЛГБТК+`,
  _ = `Пикселни и ретро`,
  _ = `Пикселни и ретро`,
  _ = `Значими избори и водеща сюжетна линия`,
  _ = `Значими избори`,
  _ = `Мистерии и детективски`,
  _ = `Мистерии и детективски`,
  _ = `Симулатори на хобита и професии`,
  _ = `Хобита и професии`,
  _ = `Изживяване в стил Rogue`,
  _ = `Страхотно преживяване в Steam Deck`,
  _ = `Страхотни на Steam Frame`,
  _ = `Капитализъм и икономика`,
  _ = `Пирати срещу нинджи`,
  _ = `Динозаври срещу роботи`,
  _ = `Безконечно преиграване`,
  _ = `Космическо проучване`,
  _ = `Колоди с карти`,
  _ = `Походово базирани ролеви`,
  _ = `Готвене`,
  _ = `Самолети, влакове и автомобили`,
  _ = `Риболовни`,
  _ = `Хвърляйте своята въдица за съревнование или отмора.`,
  _ = `Бездействащи`,
  _ = `Ритъмни`,
  _ = `Сокобан`,
  _ = `Разместване на кутии в правилния ред.`,
  _ = `Селскостопански`,
  _ = `Военни игри`,
  _ = `Колекции от създания`,
  _ = `Зомбита с/у вампири`,
  _ = `Разместване на кутии`,
  _ = `Автоматизация`,
  _ = `4X стратегии`,
  _ = `Проучвайте (eXplore), разширявайте (eXpand), използвайте (eXploit) и изтребвайте (eXterminate).`,
  _ = `Политически симулатори`,
  _ = `Животни`,
  _ = `Детективски`,
  _ = `Събирайте уликите и разрешете случая.`,
  _ = `Игри на дъска`,
  _ = `Писане`,
  _ = `Можете ли да пишете супер мега бързо, но също така, спазвайки правописа?`,
  _ = `Бойни за играчи с/у играчи`,
  _ = `Коне`,
  _ = `Яздете, състезавайте се и се грижете за коне, магарета, понита, еднорози и т.н.`,
  _ = `Средновековни`,
  _ = `Къщи и домове`,
  _ = `Океан`,
  _ = `Хентай`,
  _ = `За възрастни`,
  _ = `Куршумен`,
  _ = `Маневрирайте, за да избягвате потоци от вражески снаряди или изстреляйте купища Ваши собствени. Така или иначе, подгответе се за визуален хаос.`,
  _ = `Социална дедукция`,
  _ = `Наблюдавайте, разследвайте, блъфирайте и лъжете, за да разкриете предатели и да надушите скрита информация, преди времето да изтече.`,
  _ = `Влакове`,
  _ = `Полагайте релси, планирайте маршрути или просто контролирайте локомотива си из градове и провинции.`,
  _ = `Киберпънк`,
  _ = `Всякакви видове високотехнологични джунджурии, развиващи се в дистопично научнофантастично бъдеще.`,
  _ = `Кегли и колчета`,
  _ = `Изстрелване на топки, които да отскачат от колчета и да събарят кегли.`,
  _ = `Играчи с/у обкръжение за оцеляване и изработване`,
  _ = `Събирайте и изработвайте, за да подсигурите оцеляването си срещу стихиите.`,
  _ = `Програмиране`,
  _ = `Пишете инструкции, хаквайте и разрешавайте сложни логически пъзели.`,
  _ = `Екипно базирани ролеви`,
  _ = `Придобивайте екипировка и повишавайте нивото си със своя собствен екип.`,
  _ = `Фентъзи и свръхестествени`,
  _ = `Стрелбищни без зомбита`,
  _ = `Отпускащи пъзели с животни`,
  _ = `Нови и заслужаващи внимание`,
  _ = `Отстъпки и събития`,
  _ = `Регулируема трудност`,
  _ = `Тези игри предоставят множество начини за регулиране на нивото на трудността.`,
  _ = `Запазване по всяко време`,
  _ = `Тези игри Ви позволяват да запазвате напредъка си ръчно почти по всяко време.`,
  _ = `Регулируем размер на текста`,
  _ = `Можете да регулирате размера на текста и мащабирането на потребителския интерфейс в тези игри така, че да направите думите и елементите да изглеждат по-големи или по-малки.`,
  _ = `Опции за субтитри`,
  _ = `Можете да регулирате начина, по който субтитрите се изобразяват, като например размер на шрифта, цвят и непрозрачност на фона.`,
  _ = `Цветови алтернативи`,
  _ = `Игралното преживяване не разчита на цветове, за да предава важна информация, или можете да коригирате използваните.`,
  _ = `Комфорт на камерата`,
  _ = `Тези игри Ви позволяват да коригирате или преустановявате неудобно движение на камерата (като например поклащане на екрана, подскачане на камерата, неясност при движение) или не включват такива ефекти.`,
  _ = `Персонализиране на контролите за силата на звука`,
  _ = `Тези игри Ви позволяват да коригирате силата на звука за различните типове аудио в заглавието независимо едни от други (като например музика, звукови ефекти или гласове).`,
  _ = `Стерео озвучаване`,
  _ = `Тези игри Ви позволяват да използвате стерео аудио, за да разберете колко надалеч отляво или отдясно идват звуците.`,
  _ = `Съраунд озвучаване`,
  _ = `Тези игри Ви позволяват да използвате съраунд озвучаване, за да разберете колко надалеч в някаква посока идват звуците.`,
  _ = `Изговаряни игрални менюта`,
  _ = `Тези игри поддържат екранни четци или предлагат изговаряне на менютата, така че те да могат да бъдат използвани и разбрани, без да се вижда текстът.`,
  _ = `Годно за пускане без моменти за бърза реакция`,
  _ = `Тези игри Ви позволяват да избягвате последователности от времево ограничени въвеждания („моменти за бърза реакция“) или бързи последователни натискания на бутони.`,
  _ = `Опция само за клавиатура`,
  _ = `Тези игри могат да бъдат пускани само с клавиатура или инструмент за достъпност, който преобразува към въвеждане от клавиатура.`,
  _ = `Опция само за мишка`,
  _ = `Тези игри могат да бъдат пускани само с мишка или инструмент за достъпност, който преобразува към въвеждане от мишка.`,
  _ = `Опция само за сензорен допир`,
  _ = `Тези игри могат да бъдат пускани само със сензорен контролер или инструмент за достъпност, който преобразува към въвеждане от сензорен контролер.`,
  _ = `Говор към текст за чата`,
  _ = `Тези игри позволяват гласовият чат помежду играчите да бъде изчитан като текстов препис в реално време.`,
  _ = `Текст към говор за чата`,
  _ = `Тези игри позволяват гласовият чат да бъде изговарян гласно в реално време.`,
  _ = `Годно за пускане с Ваше собствено темпо`,
  _ = `Тези игри Ви позволяват да отделяте необходимо за Вас време между всяко въвеждане.`,
  _ = `Годно за пускане без зрение`,
  _ = `Тези игри могат да бъдат пускани, без да се вижда екранът.`,
  _ = `Контроли за контраста`,
  _ = `Тези игри позволяват коригиране на контраста за Ваше удобство.`,
  _ = `Само за възрастни`,
  _ = `Демота`,
  _ = `Безплатни за пускане`,
  _ = `Ранен достъп`,
  _ = `Страхотно преживяване в Steam Deck`,
  _ = `Страхотни на Steam Frame`,
  _ = `Удачни за контролер`,
  _ = `Steam Remote Play`,
  _ = `ВР заглавия`,
  _ = `ВР хардуер`,
  _ = `Софтуер`,
  _ = `Саундтракове`,
  _ = `macOS`,
  _ = `SteamOS + Linux`,
  _ = `За\xA0компютърни\xA0зали`,
  _ = `Опитайте го сега`,
  _ = `Опитайте го сега`,
  _ = `бутафор`,
  _ = {
    language: _,
    label_play_free_until_custom: _,
    promo_ends_custom: _,
    label_play_free_generic: _,
    label_free_weekend: _,
    msg_free_play_weekend: _,
    msg_free_play_until: _,
    label_free_week: _,
    label_just_updated: _,
    label_for_a_limited_time_only: _,
    msg_prepurchase_and_play_beta_now: _,
    msg_play_beta_now: _,
    msg_prepurchase_and_get_beta_access: _,
    msg_steam_workshop_now_available: _,
    msg_now_with_steam_workshop: _,
    msg_now_with_steamworks: _,
    msg_now_available_on_steamos: _,
    msg_now_available_on_steamos_mac_and_linux: _,
    msg_preload_now: _,
    msg_free_update: _,
    msg_play_demo_now: _,
    msg_preload_free: _,
    msg_preload_now_for_free: _,
    msg_preload_you_have_pre: _,
    msg_preload_you_have_completed: _,
    msg_preload_completed: _,
    msg_prepurchase_now: _,
    msg_just_updated_with_free_dlc: _,
    msg_now_available_for_mac_and_steamos: _,
    msg_coming_soon_to_steamos: _,
    msg_watch_movie_now: _,
    btn_add_to_wishlist: _,
    msg_early_access_now_available: _,
    msg_in_early_access: _,
    msg_new_update_available: _,
    browse_free: _,
    msg_available_new_release: _,
    msg_available_just_released_from_early_access: _,
    msg_available_just_released: _,
    msg_available_everywhere: _,
    msg_new_game: _,
    msg_available_now_free_to_play: _,
    msg_free_to_play_just_updated: _,
    msg_available_now_ftp_early: _,
    msg_advanced_access: _,
    msg_new_content_now_available: _,
    mst_weekend_description_free: _,
    msg_weekend_on_now: _,
    msg_weekend_trial: _,
    msg_weekend_play_free: _,
    msg_prepurchase_bonus: _,
    api_category_top_sellers: _,
    api_category_new_releases: _,
    spotlight_weekend_deal: _,
    spotlight_midweek_madness: _,
    spotlight_midweek_deal: _,
    spotlight_franchise_sale: _,
    spotlight_thirdparty_event: _,
    spotlight_major_update: _,
    spotlight_daily_deal: _,
    spotlight_weeklong_sale: _,
    spotlight_weeklong_header1: _,
    promo_giveaway: _,
    limitedtime_install_and_keep: _,
    api_category_coming_soon: _,
    label_new_and_upcoming: _,
    label_highlighted_deals: _,
    label_back_catalogue: _,
    msg_publisher_weekend: _,
    msg_publisher_sale: _,
    Library_Install: _,
    discount_desc_preset_loyalty: _,
    msg_action_details: _,
    msg_play_now: _,
    msg_play_it_now: _,
    msg_action_buy: _,
    msg_action_info: _,
    msg_on_sale_now: _,
    label_early_beta_access: _,
    label_new_dlc_available: _,
    label_pre_load_now: _,
    label_deepest_discount: _,
    discount_desc_limited_time: _,
    discount_desc_limited_time_date: _,
    text_now_available: _,
    text_now_available_steamplay: _,
    text_now_available_mac: _,
    text_now_available_on_pc_mac_and_linux: _,
    text_now_free_to_play: _,
    text_new_free_to_play: _,
    text_free_new_dlc_now_available: _,
    ContentHubby_Hub_1st_person_action_shooting: _,
    ContentHubby_Hub_1st_person_action_shooting_menu: _,
    ContentHubby_Hub_2d_view_action: _,
    ContentHubby_Hub_2d_view_action_menu: _,
    ContentHubby_Hub_3rd_person_action_shooting: _,
    ContentHubby_Hub_3rd_person_action_shooting_menu: _,
    ContentHubby_Hub_action: _,
    ContentHubby_Hub_action_menu: _,
    ContentHubby_Hub_action_dash_adventure: _,
    ContentHubby_Hub_action_dash_adventure_menu: _,
    ContentHubby_Hub_action_and_adventure: _,
    ContentHubby_Hub_action_and_adventure_menu: _,
    ContentHubby_Hub_action_fps: _,
    ContentHubby_Hub_action_fps_menu: _,
    ContentHubby_Hub_action_horror: _,
    ContentHubby_Hub_action_horror_menu: _,
    ContentHubby_Hub_action_rogue_like: _,
    ContentHubby_Hub_action_rogue_like_menu: _,
    ContentHubby_Hub_action_rpg: _,
    ContentHubby_Hub_action_rpg_menu: _,
    ContentHubby_Hub_action_run_jump: _,
    ContentHubby_Hub_action_run_jump_menu: _,
    ContentHubby_Hub_action_shooter: _,
    ContentHubby_Hub_action_shooter_menu: _,
    ContentHubby_Hub_action_tps: _,
    ContentHubby_Hub_action_tps_menu: _,
    ContentHubby_Hub_actions_activities: _,
    ContentHubby_Hub_actions_activities_menu: _,
    ContentHubby_Hub_adventure: _,
    ContentHubby_Hub_adventure_menu: _,
    ContentHubby_Hub_adventure_and_casual: _,
    ContentHubby_Hub_adventure_and_casual_menu: _,
    ContentHubby_Hub_adventure_explore_open_world: _,
    ContentHubby_Hub_adventure_explore_open_world_menu: _,
    ContentHubby_Hub_adventure_point_click: _,
    ContentHubby_Hub_adventure_point_click_menu: _,
    ContentHubby_Hub_adventure_rpg: _,
    ContentHubby_Hub_adventure_rpg_menu: _,
    ContentHubby_Hub_adventure_rpg_casual: _,
    ContentHubby_Hub_adventure_rpg_casual_menu: _,
    ContentHubby_Hub_aesthetic: _,
    ContentHubby_Hub_aesthetic_menu: _,
    ContentHubby_Hub_anime_mild: _,
    ContentHubby_Hub_anime_mild_menu: _,
    ContentHubby_Hub_arcade: _,
    ContentHubby_Hub_arcade_menu: _,
    ContentHubby_Hub_arcade_rhythm: _,
    ContentHubby_Hub_arcade_rhythm_menu: _,
    ContentHubby_Hub_artstyles_music: _,
    ContentHubby_Hub_artstyles_music_menu: _,
    ContentHubby_Hub_action_beat_em_up: _,
    ContentHubby_Hub_action_beat_em_up_menu: _,
    ContentHubby_Hub_business_politics: _,
    ContentHubby_Hub_business_politics_menu: _,
    ContentHubby_Hub_casual: _,
    ContentHubby_Hub_casual_menu: _,
    ContentHubby_Hub_casual_card_board: _,
    ContentHubby_Hub_casual_card_board_menu: _,
    ContentHubby_Hub_casual_and_puzzle: _,
    ContentHubby_Hub_casual_and_puzzle_menu: _,
    ContentHubby_Hub_casual_and_story: _,
    ContentHubby_Hub_casual_and_story_menu: _,
    ContentHubby_Hub_casual_puzzle: _,
    ContentHubby_Hub_casual_puzzle_menu: _,
    ContentHubby_Hub_character_action_game: _,
    ContentHubby_Hub_clickers_idlers: _,
    ContentHubby_Hub_clickers_idlers_menu: _,
    ContentHubby_Hub_crime_justice: _,
    ContentHubby_Hub_crime_justice_menu: _,
    ContentHubby_Hub_cute_cartoon: _,
    ContentHubby_Hub_cute_cartoon_menu: _,
    ContentHubby_Hub_dating_sim: _,
    ContentHubby_Hub_dating_sim_menu: _,
    ContentHubby_Hub_driving_piloting: _,
    ContentHubby_Hub_driving_piloting_menu: _,
    ContentHubby_Hub_education: _,
    ContentHubby_Hub_education_menu: _,
    ContentHubby_Hub_experimental: _,
    ContentHubby_Hub_experimental_menu: _,
    ContentHubby_Hub_exploration_open_world: _,
    ContentHubby_Hub_exploration_open_world_menu: _,
    ContentHubby_Hub_fantasy: _,
    ContentHubby_Hub_fantasy_menu: _,
    ContentHubby_Hub_fantasy_supernatural: _,
    ContentHubby_Hub_fantasy_supernatural_menu: _,
    ContentHubby_Hub_fighting: _,
    ContentHubby_Hub_fighting_menu: _,
    ContentHubby_Hub_fighting_martial_arts: _,
    ContentHubby_Hub_fighting_martial_arts_menu: _,
    ContentHubby_Hub_free_to_play: _,
    ContentHubby_Hub_hack_and_slash: _,
    ContentHubby_Hub_hidden_object_menu: _,
    ContentHubby_Hub_hidden_object: _,
    ContentHubby_Hub_history: _,
    ContentHubby_Hub_horror: _,
    ContentHubby_Hub_horror_menu: _,
    ContentHubby_Hub_horror_dark: _,
    ContentHubby_Hub_horror_dark_menu: _,
    ContentHubby_Hub_scream: _,
    ContentHubby_Hub_base_builder: _,
    ContentHubby_Hub_stealth: _,
    ContentHubby_Hub_shmup: _,
    ContentHubby_Hub_interactive_fiction: _,
    ContentHubby_Hub_interactive_fiction_menu: _,
    ContentHubby_Hub_interactive_stories: _,
    ContentHubby_Hub_interactive_stories_menu: _,
    ContentHubby_Hub_life_sim: _,
    ContentHubby_Hub_location_worlds: _,
    ContentHubby_Hub_match_3: _,
    ContentHubby_Hub_match_3_menu: _,
    ContentHubby_Hub_military: _,
    ContentHubby_Hub_military_menu: _,
    ContentHubby_Hub_military_warfare: _,
    ContentHubby_Hub_military_warfare_menu: _,
    ContentHubby_Hub_minimalist_abstract: _,
    ContentHubby_Hub_minimalist_abstract_menu: _,
    ContentHubby_Hub_multiplayer: _,
    ContentHubby_Hub_multiplayer_menu: _,
    ContentHubby_Hub_multiplayer_competitive: _,
    ContentHubby_Hub_multiplayer_competitive_menu: _,
    ContentHubby_Hub_multiplayer_battle_royale: _,
    ContentHubby_Hub_multiplayer_battle_royale_menu: _,
    ContentHubby_Hub_multiplayer_coop: _,
    ContentHubby_Hub_multiplayer_coop_menu: _,
    ContentHubby_Hub_multiplayer_lan: _,
    ContentHubby_Hub_multiplayer_lan_menu: _,
    ContentHubby_Hub_multiplayer_local_party: _,
    ContentHubby_Hub_multiplayer_local_party_menu: _,
    ContentHubby_Hub_multiplayer_mmo: _,
    ContentHubby_Hub_multiplayer_mmo_menu: _,
    ContentHubby_Hub_multiplayer_moba_auto_battler: _,
    ContentHubby_Hub_multiplayer_moba_auto_battler_menu: _,
    ContentHubby_Hub_multiplayer_online_competitive: _,
    ContentHubby_Hub_multiplayer_online_competitive_menu: _,
    ContentHubby_Hub_multiplayer_shooter: _,
    ContentHubby_Hub_multiplayer_shooter_menu: _,
    ContentHubby_Hub_music_rhythm: _,
    ContentHubby_Hub_music_rhythm_menu: _,
    ContentHubby_Hub_open_world_survival_craft: _,
    ContentHubby_Hub_open_world_survival_craft_menu: _,
    ContentHubby_Hub_people_creatures: _,
    ContentHubby_Hub_players: _,
    ContentHubby_Hub_psychedelic: _,
    ContentHubby_Hub_psychedelic_menu: _,
    ContentHubby_Hub_psychedelic_surreal: _,
    ContentHubby_Hub_psychedelic_surreal_menu: _,
    ContentHubby_Hub_puzzle: _,
    ContentHubby_Hub_puzzle_menu: _,
    ContentHubby_Hub_puzzle_matching: _,
    ContentHubby_Hub_puzzle_matching_menu: _,
    ContentHubby_Hub_puzzle_difficult: _,
    ContentHubby_Hub_puzzle_difficult_menu: _,
    ContentHubby_Hub_puzzle_logic: _,
    ContentHubby_Hub_puzzle_logic_menu: _,
    ContentHubby_Hub_puzzle_multiplayer: _,
    ContentHubby_Hub_puzzle_multiplayer_menu: _,
    ContentHubby_Hub_racing: _,
    ContentHubby_Hub_racing_desc: _,
    ContentHubby_Hub_racing_menu: _,
    ContentHubby_Hub_racing_sim: _,
    ContentHubby_Hub_racing_sim_menu: _,
    ContentHubby_Hub_racing_combat: _,
    ContentHubby_Hub_racing_combat_menu: _,
    ContentHubby_Hub_racing_piloting: _,
    ContentHubby_Hub_racing_piloting_menu: _,
    ContentHubby_Hub_retro: _,
    ContentHubby_Hub_retro_menu: _,
    ContentHubby_Hub_relaxing: _,
    ContentHubby_Hub_relaxing_menu: _,
    ContentHubby_Hub_metroidvania: _,
    ContentHubby_Hub_metroidvania_menu: _,
    ContentHubby_Hub_minimalist_relaxing: _,
    ContentHubby_Hub_minimalist_relaxing_menu: _,
    ContentHubby_Hub_rogue_like_turn_based: _,
    ContentHubby_Hub_rogue_like_turn_based_menu: _,
    ContentHubby_Hub_rogue_like_rogue_lite: _,
    ContentHubby_Hub_rogue_like_rogue_lite_menu: _,
    ContentHubby_Hub_rogue_like: _,
    ContentHubby_Hub_rogue_like_menu: _,
    ContentHubby_Hub_rpg: _,
    ContentHubby_Hub_rpg_menu: _,
    ContentHubby_Hub_rpg_action: _,
    ContentHubby_Hub_rpg_action_menu: _,
    ContentHubby_Hub_rpg_crpg: _,
    ContentHubby_Hub_rpg_crpg_menu: _,
    ContentHubby_Hub_rpg_crpg_traditional_rogue_like: _,
    ContentHubby_Hub_rpg_crpg_traditional_rogue_like_menu: _,
    ContentHubby_Hub_rpg_dungeon_crawler: _,
    ContentHubby_Hub_rpg_dungeon_crawler_menu: _,
    ContentHubby_Hub_rpg_jrpg: _,
    ContentHubby_Hub_rpg_jrpg_menu: _,
    ContentHubby_Hub_rpg_mmo: _,
    ContentHubby_Hub_rpg_mmo_menu: _,
    ContentHubby_Hub_rpg_party_based: _,
    ContentHubby_Hub_rpg_party_based_menu: _,
    ContentHubby_Hub_rpg_story: _,
    ContentHubby_Hub_rpg_story_menu: _,
    ContentHubby_Hub_rpg_strategy_tactics: _,
    ContentHubby_Hub_rpg_strategy_tactics_menu: _,
    ContentHubby_Hub_rpg_turn_based: _,
    ContentHubby_Hub_rpg_turn_based_menu: _,
    ContentHubby_Hub_science_fiction: _,
    ContentHubby_Hub_science_fiction_menu: _,
    ContentHubby_Hub_shooter: _,
    ContentHubby_Hub_shooter_menu: _,
    ContentHubby_Hub_sim_building: _,
    ContentHubby_Hub_sim_building_menu: _,
    ContentHubby_Hub_sim_building_automation: _,
    ContentHubby_Hub_sim_building_automation_menu: _,
    ContentHubby_Hub_sim_business_tycoon: _,
    ContentHubby_Hub_sim_business_tycoon_menu: _,
    ContentHubby_Hub_sim_cities_settlements: _,
    ContentHubby_Hub_sim_cities_settlements_menu: _,
    ContentHubby_Hub_sim_farming: _,
    ContentHubby_Hub_sim_farming_menu: _,
    ContentHubby_Hub_sim_farming_crafting: _,
    ContentHubby_Hub_sim_farming_crafting_menu: _,
    ContentHubby_Hub_sim_life: _,
    ContentHubby_Hub_sim_life_menu: _,
    ContentHubby_Hub_sim_life_romance: _,
    ContentHubby_Hub_sim_life_romance_menu: _,
    ContentHubby_Hub_sim_management: _,
    ContentHubby_Hub_sim_management_menu: _,
    ContentHubby_Hub_sim_open_world: _,
    ContentHubby_Hub_sim_open_world_menu: _,
    ContentHubby_Hub_sim_physics_sandbox: _,
    ContentHubby_Hub_sim_physics_sandbox_menu: _,
    ContentHubby_Hub_sim_policy: _,
    ContentHubby_Hub_sim_policy_menu: _,
    ContentHubby_Hub_sim_sandbox_god_game: _,
    ContentHubby_Hub_sim_sandbox_god_game_menu: _,
    ContentHubby_Hub_sim_space_flight: _,
    ContentHubby_Hub_sim_space_flight_menu: _,
    ContentHubby_Hub_sim_dating: _,
    ContentHubby_Hub_sim_dating_menu: _,
    ContentHubby_Hub_simulation: _,
    ContentHubby_Hub_simulation_menu: _,
    ContentHubby_Hub_singleplayer: _,
    ContentHubby_Hub_singleplayer_menu: _,
    ContentHubby_Hub_social_and_players: _,
    ContentHubby_Hub_sports: _,
    ContentHubby_Hub_sports_desc: _,
    ContentHubby_Hub_sports_menu: _,
    ContentHubby_Hub_sports_and_racing: _,
    ContentHubby_Hub_sports_and_racing_menu: _,
    ContentHubby_Hub_sports_ball: _,
    ContentHubby_Hub_sports_ball_menu: _,
    ContentHubby_Hub_sports_combat: _,
    ContentHubby_Hub_sports_combat_menu: _,
    ContentHubby_Hub_sports_fishing_hunting: _,
    ContentHubby_Hub_sports_fishing_hunting_menu: _,
    ContentHubby_Hub_sports_individual: _,
    ContentHubby_Hub_sports_individual_menu: _,
    ContentHubby_Hub_sports_sim: _,
    ContentHubby_Hub_sports_sim_menu: _,
    ContentHubby_Hub_sports_team: _,
    ContentHubby_Hub_sports_team_menu: _,
    ContentHubby_Hub_sports_winter: _,
    ContentHubby_Hub_sports_winter_menu: _,
    ContentHubby_Hub_spooky: _,
    ContentHubby_Hub_spooky_menu: _,
    ContentHubby_Hub_story_driven: _,
    ContentHubby_Hub_story_driven_menu: _,
    ContentHubby_Hub_strategy: _,
    ContentHubby_Hub_strategy_menu: _,
    ContentHubby_Hub_strategy_card_board: _,
    ContentHubby_Hub_strategy_card_board_menu: _,
    ContentHubby_Hub_strategy_cities_settlements: _,
    ContentHubby_Hub_strategy_cities_settlements_menu: _,
    ContentHubby_Hub_strategy_grand_4x: _,
    ContentHubby_Hub_strategy_grand_4x_menu: _,
    ContentHubby_Hub_strategy_military: _,
    ContentHubby_Hub_strategy_military_menu: _,
    ContentHubby_Hub_strategy_moba_auto_battler: _,
    ContentHubby_Hub_strategy_moba_auto_battler_menu: _,
    ContentHubby_Hub_strategy_real_time: _,
    ContentHubby_Hub_strategy_real_time_menu: _,
    ContentHubby_Hub_strategy_sim_management: _,
    ContentHubby_Hub_strategy_sim_management_menu: _,
    ContentHubby_Hub_strategy_tactics: _,
    ContentHubby_Hub_strategy_tactics_menu: _,
    ContentHubby_Hub_strategy_turn_based: _,
    ContentHubby_Hub_strategy_turn_based_menu: _,
    ContentHubby_Hub_survival: _,
    ContentHubby_Hub_survival_menu: _,
    ContentHubby_Hub_survival_stealth: _,
    ContentHubby_Hub_survival_stealth_menu: _,
    ContentHubby_Hub_themes: _,
    ContentHubby_Hub_themes_menu: _,
    ContentHubby_Hub_themes_and_interests: _,
    ContentHubby_Hub_themes_and_interests_menu: _,
    ContentHubby_Hub_time_management: _,
    ContentHubby_Hub_time_management_menu: _,
    ContentHubby_Hub_tower_defense: _,
    ContentHubby_Hub_tower_defense_menu: _,
    ContentHubby_Hub_visual_novel: _,
    ContentHubby_Hub_visual_novel_menu: _,
    ContentHubby_Hub_walking_simulator: _,
    ContentHubby_Hub_walking_simulator_menu: _,
    ContentHubby_Hub_space: _,
    ContentHubby_Hub_space_menu: _,
    ContentHubby_Hub_female_protagonist: _,
    ContentHubby_Hub_female_protagonist_menu: _,
    ContentHubby_Hub_lgbtq: _,
    ContentHubby_Hub_lgbtq_menu: _,
    ContentHubby_Hub_pixel_retro: _,
    ContentHubby_Hub_pixel_retro_menu: _,
    ContentHubby_Hub_choices_matter: _,
    ContentHubby_Hub_choices_matter_menu: _,
    ContentHubby_Hub_mystery_detective: _,
    ContentHubby_Hub_mystery_detective_menu: _,
    ContentHubby_Hub_hobby_sim: _,
    ContentHubby_Hub_hobby_sim_menu: _,
    ContentHubby_Hub_going_rogue: _,
    ContentHubby_Hub_greatondeck: _,
    ContentHubby_Hub_greatonframe: _,
    ContentHubby_Hub_capitalism_economy: _,
    ContentHubby_Hub_pirates_ninjas: _,
    ContentHubby_Hub_dinos_robots: _,
    ContentHubby_Hub_endlessly_replayable: _,
    ContentHubby_Hub_space_exploration: _,
    ContentHubby_Hub_deckbuilders: _,
    ContentHubby_Hub_turnbased_rpg: _,
    ContentHubby_Hub_cooking: _,
    ContentHubby_Hub_plane_train_autos: _,
    ContentHubby_Hub_fishing: _,
    ContentHubby_Hub_fishing_desc: _,
    ContentHubby_Hub_idle: _,
    ContentHubby_Hub_rhythm: _,
    ContentHubby_Hub_sokoban: _,
    ContentHubby_Hub_sokoban_desc: _,
    ContentHubby_Hub_farming: _,
    ContentHubby_Hub_wargame: _,
    ContentHubby_Hub_creature_collector: _,
    ContentHubby_Hub_zombies_vampires: _,
    ContentHubby_Hub_box_pushing: _,
    ContentHubby_Hub_automation: _,
    ContentHubby_Hub_4x_strategy: _,
    ContentHubby_Hub_4x_strategy_desc: _,
    ContentHubby_Hub_political_sim: _,
    ContentHubby_Hub_animals: _,
    ContentHubby_Hub_detective: _,
    ContentHubby_Hub_detective_desc: _,
    ContentHubby_Hub_board_games: _,
    ContentHubby_Hub_typing: _,
    ContentHubby_Hub_typing_desc: _,
    ContentHubby_Hub_combat_pvp: _,
    ContentHubby_Hub_horses: _,
    ContentHubby_Hub_horses_desc: _,
    ContentHubby_Hub_medieval: _,
    ContentHubby_Hub_house_home: _,
    ContentHubby_Hub_ocean: _,
    ContentHubby_Hub_hentai: _,
    ContentHubby_Hub_mature: _,
    ContentHubby_Hub_bullet: _,
    ContentHubby_Hub_bullet_desc: _,
    ContentHubby_Hub_deduction: _,
    ContentHubby_Hub_deduction_desc: _,
    ContentHubby_Hub_trains: _,
    ContentHubby_Hub_trains_desc: _,
    ContentHubby_Hub_cyberpunk: _,
    ContentHubby_Hub_cyberpunk_desc: _,
    ContentHubby_Hub_pinsandpegs: _,
    ContentHubby_Hub_pinsandpegs_desc: _,
    ContentHubby_Hub_pvesurvival: _,
    ContentHubby_Hub_pvesurvival_desc: _,
    ContentHubby_Hub_programming: _,
    ContentHubby_Hub_programming_desc: _,
    ContentHubby_Hub_partyrpg: _,
    ContentHubby_Hub_partyrpg_desc: _,
    ContentHubby_Hub_fantasy_and_supernatural: _,
    ContentHubby_Hub_shooters_without_zombies: _,
    ContentHubby_Hub_relaxing_animal_puzzles: _,
    ContentHubby_Menu_NewAndNoteworthy: _,
    ContentHubby_Menu_CurrentSpecials: _,
    ContentHubby_Hub_adjustable_difficulty: _,
    ContentHubby_Hub_adjustable_difficulty_desc: _,
    ContentHubby_Hub_save_anytime: _,
    ContentHubby_Hub_save_anytime_desc: _,
    ContentHubby_Hub_adjustable_text_size: _,
    ContentHubby_Hub_adjustable_text_size_desc: _,
    ContentHubby_Hub_subtitle_options: _,
    ContentHubby_Hub_subtitle_options_desc: _,
    ContentHubby_Hub_color_alternatives: _,
    ContentHubby_Hub_color_alternatives_desc: _,
    ContentHubby_Hub_camera_comfort: _,
    ContentHubby_Hub_camera_comfort_desc: _,
    ContentHubby_Hub_custom_volume_controls: _,
    ContentHubby_Hub_custom_volume_controls_desc: _,
    ContentHubby_Hub_stereo_sound: _,
    ContentHubby_Hub_stereo_sound_desc: _,
    ContentHubby_Hub_surround_sound: _,
    ContentHubby_Hub_surround_sound_desc: _,
    ContentHubby_Hub_narrated_game_menus: _,
    ContentHubby_Hub_narrated_game_menus_desc: _,
    ContentHubby_Hub_playable_without_timed_input: _,
    ContentHubby_Hub_playable_without_timed_input_desc: _,
    ContentHubby_Hub_keyboard_only_option: _,
    ContentHubby_Hub_keyboard_only_option_desc: _,
    ContentHubby_Hub_mouse_only_option: _,
    ContentHubby_Hub_mouse_only_option_desc: _,
    ContentHubby_Hub_touch_only_option: _,
    ContentHubby_Hub_touch_only_option_desc: _,
    ContentHubby_Hub_chat_speech_to_text: _,
    ContentHubby_Hub_chat_speech_to_text_desc: _,
    ContentHubby_Hub_chat_text_to_speech: _,
    ContentHubby_Hub_chat_text_to_speech_desc: _,
    ContentHubby_Hub_playable_at_your_own_pace: _,
    ContentHubby_Hub_playable_at_your_own_pace_desc: _,
    ContentHubby_Hub_playable_without_vision: _,
    ContentHubby_Hub_playable_without_vision_desc: _,
    ContentHubby_Hub_contrast_controls: _,
    ContentHubby_Hub_contrast_controls_desc: _,
    browse_adultonly: _,
    browse_demos: _,
    genre_free2play: _,
    genre_early_access: _,
    store_tab_greatondeck: _,
    store_tab_greatonframe: _,
    contenthub_title_controller: _,
    browse_remoteplay: _,
    Store_VR_MainMenu_Virtual_Reality: _,
    Store_VR_MainMenu_VR_Hardware: _,
    store_tab_software_home: _,
    additional_game_content_soundtracks: _,
    games_osx: _,
    store_tab_linux: _,
    contenthub_title_pccafe: _,
    msg_try_it_now: _,
    Library_Update_TryItNow2: _,
    dummy: _,
  };
export {
  _ as ContentHubby_Hub_1st_person_action_shooting,
  _ as ContentHubby_Hub_1st_person_action_shooting_menu,
  _ as ContentHubby_Hub_2d_view_action,
  _ as ContentHubby_Hub_2d_view_action_menu,
  _ as ContentHubby_Hub_3rd_person_action_shooting,
  _ as ContentHubby_Hub_3rd_person_action_shooting_menu,
  _ as ContentHubby_Hub_4x_strategy,
  _ as ContentHubby_Hub_4x_strategy_desc,
  _ as ContentHubby_Hub_action,
  _ as ContentHubby_Hub_action_and_adventure,
  _ as ContentHubby_Hub_action_and_adventure_menu,
  _ as ContentHubby_Hub_action_beat_em_up,
  _ as ContentHubby_Hub_action_beat_em_up_menu,
  _ as ContentHubby_Hub_action_dash_adventure,
  _ as ContentHubby_Hub_action_dash_adventure_menu,
  _ as ContentHubby_Hub_action_fps,
  _ as ContentHubby_Hub_action_fps_menu,
  _ as ContentHubby_Hub_action_horror,
  _ as ContentHubby_Hub_action_horror_menu,
  _ as ContentHubby_Hub_action_menu,
  _ as ContentHubby_Hub_action_rogue_like,
  _ as ContentHubby_Hub_action_rogue_like_menu,
  _ as ContentHubby_Hub_action_rpg,
  _ as ContentHubby_Hub_action_rpg_menu,
  _ as ContentHubby_Hub_action_run_jump,
  _ as ContentHubby_Hub_action_run_jump_menu,
  _ as ContentHubby_Hub_action_shooter,
  _ as ContentHubby_Hub_action_shooter_menu,
  _ as ContentHubby_Hub_action_tps,
  _ as ContentHubby_Hub_action_tps_menu,
  _ as ContentHubby_Hub_actions_activities,
  _ as ContentHubby_Hub_actions_activities_menu,
  _ as ContentHubby_Hub_adjustable_difficulty,
  _ as ContentHubby_Hub_adjustable_difficulty_desc,
  _ as ContentHubby_Hub_adjustable_text_size,
  _ as ContentHubby_Hub_adjustable_text_size_desc,
  _ as ContentHubby_Hub_adventure,
  _ as ContentHubby_Hub_adventure_and_casual,
  _ as ContentHubby_Hub_adventure_and_casual_menu,
  _ as ContentHubby_Hub_adventure_explore_open_world,
  _ as ContentHubby_Hub_adventure_explore_open_world_menu,
  _ as ContentHubby_Hub_adventure_menu,
  _ as ContentHubby_Hub_adventure_point_click,
  _ as ContentHubby_Hub_adventure_point_click_menu,
  _ as ContentHubby_Hub_adventure_rpg,
  _ as ContentHubby_Hub_adventure_rpg_casual,
  _ as ContentHubby_Hub_adventure_rpg_casual_menu,
  _ as ContentHubby_Hub_adventure_rpg_menu,
  _ as ContentHubby_Hub_aesthetic,
  _ as ContentHubby_Hub_aesthetic_menu,
  _ as ContentHubby_Hub_animals,
  _ as ContentHubby_Hub_anime_mild,
  _ as ContentHubby_Hub_anime_mild_menu,
  _ as ContentHubby_Hub_arcade,
  _ as ContentHubby_Hub_arcade_menu,
  _ as ContentHubby_Hub_arcade_rhythm,
  _ as ContentHubby_Hub_arcade_rhythm_menu,
  _ as ContentHubby_Hub_artstyles_music,
  _ as ContentHubby_Hub_artstyles_music_menu,
  _ as ContentHubby_Hub_automation,
  _ as ContentHubby_Hub_base_builder,
  _ as ContentHubby_Hub_board_games,
  _ as ContentHubby_Hub_box_pushing,
  _ as ContentHubby_Hub_bullet,
  _ as ContentHubby_Hub_bullet_desc,
  _ as ContentHubby_Hub_business_politics,
  _ as ContentHubby_Hub_business_politics_menu,
  _ as ContentHubby_Hub_camera_comfort,
  _ as ContentHubby_Hub_camera_comfort_desc,
  _ as ContentHubby_Hub_capitalism_economy,
  _ as ContentHubby_Hub_casual,
  _ as ContentHubby_Hub_casual_and_puzzle,
  _ as ContentHubby_Hub_casual_and_puzzle_menu,
  _ as ContentHubby_Hub_casual_and_story,
  _ as ContentHubby_Hub_casual_and_story_menu,
  _ as ContentHubby_Hub_casual_card_board,
  _ as ContentHubby_Hub_casual_card_board_menu,
  _ as ContentHubby_Hub_casual_menu,
  _ as ContentHubby_Hub_casual_puzzle,
  _ as ContentHubby_Hub_casual_puzzle_menu,
  _ as ContentHubby_Hub_character_action_game,
  _ as ContentHubby_Hub_chat_speech_to_text,
  _ as ContentHubby_Hub_chat_speech_to_text_desc,
  _ as ContentHubby_Hub_chat_text_to_speech,
  _ as ContentHubby_Hub_chat_text_to_speech_desc,
  _ as ContentHubby_Hub_choices_matter,
  _ as ContentHubby_Hub_choices_matter_menu,
  _ as ContentHubby_Hub_clickers_idlers,
  _ as ContentHubby_Hub_clickers_idlers_menu,
  _ as ContentHubby_Hub_color_alternatives,
  _ as ContentHubby_Hub_color_alternatives_desc,
  _ as ContentHubby_Hub_combat_pvp,
  _ as ContentHubby_Hub_contrast_controls,
  _ as ContentHubby_Hub_contrast_controls_desc,
  _ as ContentHubby_Hub_cooking,
  _ as ContentHubby_Hub_creature_collector,
  _ as ContentHubby_Hub_crime_justice,
  _ as ContentHubby_Hub_crime_justice_menu,
  _ as ContentHubby_Hub_custom_volume_controls,
  _ as ContentHubby_Hub_custom_volume_controls_desc,
  _ as ContentHubby_Hub_cute_cartoon,
  _ as ContentHubby_Hub_cute_cartoon_menu,
  _ as ContentHubby_Hub_cyberpunk,
  _ as ContentHubby_Hub_cyberpunk_desc,
  _ as ContentHubby_Hub_dating_sim,
  _ as ContentHubby_Hub_dating_sim_menu,
  _ as ContentHubby_Hub_deckbuilders,
  _ as ContentHubby_Hub_deduction,
  _ as ContentHubby_Hub_deduction_desc,
  _ as ContentHubby_Hub_detective,
  _ as ContentHubby_Hub_detective_desc,
  _ as ContentHubby_Hub_dinos_robots,
  _ as ContentHubby_Hub_driving_piloting,
  _ as ContentHubby_Hub_driving_piloting_menu,
  _ as ContentHubby_Hub_education,
  _ as ContentHubby_Hub_education_menu,
  _ as ContentHubby_Hub_endlessly_replayable,
  _ as ContentHubby_Hub_experimental,
  _ as ContentHubby_Hub_experimental_menu,
  _ as ContentHubby_Hub_exploration_open_world,
  _ as ContentHubby_Hub_exploration_open_world_menu,
  _ as ContentHubby_Hub_fantasy,
  _ as ContentHubby_Hub_fantasy_and_supernatural,
  _ as ContentHubby_Hub_fantasy_menu,
  _ as ContentHubby_Hub_fantasy_supernatural,
  _ as ContentHubby_Hub_fantasy_supernatural_menu,
  _ as ContentHubby_Hub_farming,
  _ as ContentHubby_Hub_female_protagonist,
  _ as ContentHubby_Hub_female_protagonist_menu,
  _ as ContentHubby_Hub_fighting,
  _ as ContentHubby_Hub_fighting_martial_arts,
  _ as ContentHubby_Hub_fighting_martial_arts_menu,
  _ as ContentHubby_Hub_fighting_menu,
  _ as ContentHubby_Hub_fishing,
  _ as ContentHubby_Hub_fishing_desc,
  _ as ContentHubby_Hub_free_to_play,
  _ as ContentHubby_Hub_going_rogue,
  _ as ContentHubby_Hub_greatondeck,
  _ as ContentHubby_Hub_greatonframe,
  _ as ContentHubby_Hub_hack_and_slash,
  _ as ContentHubby_Hub_hentai,
  _ as ContentHubby_Hub_hidden_object,
  _ as ContentHubby_Hub_hidden_object_menu,
  _ as ContentHubby_Hub_history,
  _ as ContentHubby_Hub_hobby_sim,
  _ as ContentHubby_Hub_hobby_sim_menu,
  _ as ContentHubby_Hub_horror,
  _ as ContentHubby_Hub_horror_dark,
  _ as ContentHubby_Hub_horror_dark_menu,
  _ as ContentHubby_Hub_horror_menu,
  _ as ContentHubby_Hub_horses,
  _ as ContentHubby_Hub_horses_desc,
  _ as ContentHubby_Hub_house_home,
  _ as ContentHubby_Hub_idle,
  _ as ContentHubby_Hub_interactive_fiction,
  _ as ContentHubby_Hub_interactive_fiction_menu,
  _ as ContentHubby_Hub_interactive_stories,
  _ as ContentHubby_Hub_interactive_stories_menu,
  _ as ContentHubby_Hub_keyboard_only_option,
  _ as ContentHubby_Hub_keyboard_only_option_desc,
  _ as ContentHubby_Hub_lgbtq,
  _ as ContentHubby_Hub_lgbtq_menu,
  _ as ContentHubby_Hub_life_sim,
  _ as ContentHubby_Hub_location_worlds,
  _ as ContentHubby_Hub_match_3,
  _ as ContentHubby_Hub_match_3_menu,
  _ as ContentHubby_Hub_mature,
  _ as ContentHubby_Hub_medieval,
  _ as ContentHubby_Hub_metroidvania,
  _ as ContentHubby_Hub_metroidvania_menu,
  _ as ContentHubby_Hub_military,
  _ as ContentHubby_Hub_military_menu,
  _ as ContentHubby_Hub_military_warfare,
  _ as ContentHubby_Hub_military_warfare_menu,
  _ as ContentHubby_Hub_minimalist_abstract,
  _ as ContentHubby_Hub_minimalist_abstract_menu,
  _ as ContentHubby_Hub_minimalist_relaxing,
  _ as ContentHubby_Hub_minimalist_relaxing_menu,
  _ as ContentHubby_Hub_mouse_only_option,
  _ as ContentHubby_Hub_mouse_only_option_desc,
  _ as ContentHubby_Hub_multiplayer,
  _ as ContentHubby_Hub_multiplayer_battle_royale,
  _ as ContentHubby_Hub_multiplayer_battle_royale_menu,
  _ as ContentHubby_Hub_multiplayer_competitive,
  _ as ContentHubby_Hub_multiplayer_competitive_menu,
  _ as ContentHubby_Hub_multiplayer_coop,
  _ as ContentHubby_Hub_multiplayer_coop_menu,
  _ as ContentHubby_Hub_multiplayer_lan,
  _ as ContentHubby_Hub_multiplayer_lan_menu,
  _ as ContentHubby_Hub_multiplayer_local_party,
  _ as ContentHubby_Hub_multiplayer_local_party_menu,
  _ as ContentHubby_Hub_multiplayer_menu,
  _ as ContentHubby_Hub_multiplayer_mmo,
  _ as ContentHubby_Hub_multiplayer_mmo_menu,
  _ as ContentHubby_Hub_multiplayer_moba_auto_battler,
  _ as ContentHubby_Hub_multiplayer_moba_auto_battler_menu,
  _ as ContentHubby_Hub_multiplayer_online_competitive,
  _ as ContentHubby_Hub_multiplayer_online_competitive_menu,
  _ as ContentHubby_Hub_multiplayer_shooter,
  _ as ContentHubby_Hub_multiplayer_shooter_menu,
  _ as ContentHubby_Hub_music_rhythm,
  _ as ContentHubby_Hub_music_rhythm_menu,
  _ as ContentHubby_Hub_mystery_detective,
  _ as ContentHubby_Hub_mystery_detective_menu,
  _ as ContentHubby_Hub_narrated_game_menus,
  _ as ContentHubby_Hub_narrated_game_menus_desc,
  _ as ContentHubby_Hub_ocean,
  _ as ContentHubby_Hub_open_world_survival_craft,
  _ as ContentHubby_Hub_open_world_survival_craft_menu,
  _ as ContentHubby_Hub_partyrpg,
  _ as ContentHubby_Hub_partyrpg_desc,
  _ as ContentHubby_Hub_people_creatures,
  _ as ContentHubby_Hub_pinsandpegs,
  _ as ContentHubby_Hub_pinsandpegs_desc,
  _ as ContentHubby_Hub_pirates_ninjas,
  _ as ContentHubby_Hub_pixel_retro,
  _ as ContentHubby_Hub_pixel_retro_menu,
  _ as ContentHubby_Hub_plane_train_autos,
  _ as ContentHubby_Hub_playable_at_your_own_pace,
  _ as ContentHubby_Hub_playable_at_your_own_pace_desc,
  _ as ContentHubby_Hub_playable_without_timed_input,
  _ as ContentHubby_Hub_playable_without_timed_input_desc,
  _ as ContentHubby_Hub_playable_without_vision,
  _ as ContentHubby_Hub_playable_without_vision_desc,
  _ as ContentHubby_Hub_players,
  _ as ContentHubby_Hub_political_sim,
  _ as ContentHubby_Hub_programming,
  _ as ContentHubby_Hub_programming_desc,
  _ as ContentHubby_Hub_psychedelic,
  _ as ContentHubby_Hub_psychedelic_menu,
  _ as ContentHubby_Hub_psychedelic_surreal,
  _ as ContentHubby_Hub_psychedelic_surreal_menu,
  _ as ContentHubby_Hub_puzzle,
  _ as ContentHubby_Hub_puzzle_difficult,
  _ as ContentHubby_Hub_puzzle_difficult_menu,
  _ as ContentHubby_Hub_puzzle_logic,
  _ as ContentHubby_Hub_puzzle_logic_menu,
  _ as ContentHubby_Hub_puzzle_matching,
  _ as ContentHubby_Hub_puzzle_matching_menu,
  _ as ContentHubby_Hub_puzzle_menu,
  _ as ContentHubby_Hub_puzzle_multiplayer,
  _ as ContentHubby_Hub_puzzle_multiplayer_menu,
  _ as ContentHubby_Hub_pvesurvival,
  _ as ContentHubby_Hub_pvesurvival_desc,
  _ as ContentHubby_Hub_racing,
  _ as ContentHubby_Hub_racing_combat,
  _ as ContentHubby_Hub_racing_combat_menu,
  _ as ContentHubby_Hub_racing_desc,
  _ as ContentHubby_Hub_racing_menu,
  _ as ContentHubby_Hub_racing_piloting,
  _ as ContentHubby_Hub_racing_piloting_menu,
  _ as ContentHubby_Hub_racing_sim,
  _ as ContentHubby_Hub_racing_sim_menu,
  _ as ContentHubby_Hub_relaxing,
  _ as ContentHubby_Hub_relaxing_animal_puzzles,
  _ as ContentHubby_Hub_relaxing_menu,
  _ as ContentHubby_Hub_retro,
  _ as ContentHubby_Hub_retro_menu,
  _ as ContentHubby_Hub_rhythm,
  _ as ContentHubby_Hub_rogue_like,
  _ as ContentHubby_Hub_rogue_like_menu,
  _ as ContentHubby_Hub_rogue_like_rogue_lite,
  _ as ContentHubby_Hub_rogue_like_rogue_lite_menu,
  _ as ContentHubby_Hub_rogue_like_turn_based,
  _ as ContentHubby_Hub_rogue_like_turn_based_menu,
  _ as ContentHubby_Hub_rpg,
  _ as ContentHubby_Hub_rpg_action,
  _ as ContentHubby_Hub_rpg_action_menu,
  _ as ContentHubby_Hub_rpg_crpg,
  _ as ContentHubby_Hub_rpg_crpg_menu,
  _ as ContentHubby_Hub_rpg_crpg_traditional_rogue_like,
  _ as ContentHubby_Hub_rpg_crpg_traditional_rogue_like_menu,
  _ as ContentHubby_Hub_rpg_dungeon_crawler,
  _ as ContentHubby_Hub_rpg_dungeon_crawler_menu,
  _ as ContentHubby_Hub_rpg_jrpg,
  _ as ContentHubby_Hub_rpg_jrpg_menu,
  _ as ContentHubby_Hub_rpg_menu,
  _ as ContentHubby_Hub_rpg_mmo,
  _ as ContentHubby_Hub_rpg_mmo_menu,
  _ as ContentHubby_Hub_rpg_party_based,
  _ as ContentHubby_Hub_rpg_party_based_menu,
  _ as ContentHubby_Hub_rpg_story,
  _ as ContentHubby_Hub_rpg_story_menu,
  _ as ContentHubby_Hub_rpg_strategy_tactics,
  _ as ContentHubby_Hub_rpg_strategy_tactics_menu,
  _ as ContentHubby_Hub_rpg_turn_based,
  _ as ContentHubby_Hub_rpg_turn_based_menu,
  _ as ContentHubby_Hub_save_anytime,
  _ as ContentHubby_Hub_save_anytime_desc,
  _ as ContentHubby_Hub_science_fiction,
  _ as ContentHubby_Hub_science_fiction_menu,
  _ as ContentHubby_Hub_scream,
  _ as ContentHubby_Hub_shmup,
  _ as ContentHubby_Hub_shooter,
  _ as ContentHubby_Hub_shooter_menu,
  _ as ContentHubby_Hub_shooters_without_zombies,
  _ as ContentHubby_Hub_sim_building,
  _ as ContentHubby_Hub_sim_building_automation,
  _ as ContentHubby_Hub_sim_building_automation_menu,
  _ as ContentHubby_Hub_sim_building_menu,
  _ as ContentHubby_Hub_sim_business_tycoon,
  _ as ContentHubby_Hub_sim_business_tycoon_menu,
  _ as ContentHubby_Hub_sim_cities_settlements,
  _ as ContentHubby_Hub_sim_cities_settlements_menu,
  _ as ContentHubby_Hub_sim_dating,
  _ as ContentHubby_Hub_sim_dating_menu,
  _ as ContentHubby_Hub_sim_farming,
  _ as ContentHubby_Hub_sim_farming_crafting,
  _ as ContentHubby_Hub_sim_farming_crafting_menu,
  _ as ContentHubby_Hub_sim_farming_menu,
  _ as ContentHubby_Hub_sim_life,
  _ as ContentHubby_Hub_sim_life_menu,
  _ as ContentHubby_Hub_sim_life_romance,
  _ as ContentHubby_Hub_sim_life_romance_menu,
  _ as ContentHubby_Hub_sim_management,
  _ as ContentHubby_Hub_sim_management_menu,
  _ as ContentHubby_Hub_sim_open_world,
  _ as ContentHubby_Hub_sim_open_world_menu,
  _ as ContentHubby_Hub_sim_physics_sandbox,
  _ as ContentHubby_Hub_sim_physics_sandbox_menu,
  _ as ContentHubby_Hub_sim_policy,
  _ as ContentHubby_Hub_sim_policy_menu,
  _ as ContentHubby_Hub_sim_sandbox_god_game,
  _ as ContentHubby_Hub_sim_sandbox_god_game_menu,
  _ as ContentHubby_Hub_sim_space_flight,
  _ as ContentHubby_Hub_sim_space_flight_menu,
  _ as ContentHubby_Hub_simulation,
  _ as ContentHubby_Hub_simulation_menu,
  _ as ContentHubby_Hub_singleplayer,
  _ as ContentHubby_Hub_singleplayer_menu,
  _ as ContentHubby_Hub_social_and_players,
  _ as ContentHubby_Hub_sokoban,
  _ as ContentHubby_Hub_sokoban_desc,
  _ as ContentHubby_Hub_space,
  _ as ContentHubby_Hub_space_exploration,
  _ as ContentHubby_Hub_space_menu,
  _ as ContentHubby_Hub_spooky,
  _ as ContentHubby_Hub_spooky_menu,
  _ as ContentHubby_Hub_sports,
  _ as ContentHubby_Hub_sports_and_racing,
  _ as ContentHubby_Hub_sports_and_racing_menu,
  _ as ContentHubby_Hub_sports_ball,
  _ as ContentHubby_Hub_sports_ball_menu,
  _ as ContentHubby_Hub_sports_combat,
  _ as ContentHubby_Hub_sports_combat_menu,
  _ as ContentHubby_Hub_sports_desc,
  _ as ContentHubby_Hub_sports_fishing_hunting,
  _ as ContentHubby_Hub_sports_fishing_hunting_menu,
  _ as ContentHubby_Hub_sports_individual,
  _ as ContentHubby_Hub_sports_individual_menu,
  _ as ContentHubby_Hub_sports_menu,
  _ as ContentHubby_Hub_sports_sim,
  _ as ContentHubby_Hub_sports_sim_menu,
  _ as ContentHubby_Hub_sports_team,
  _ as ContentHubby_Hub_sports_team_menu,
  _ as ContentHubby_Hub_sports_winter,
  _ as ContentHubby_Hub_sports_winter_menu,
  _ as ContentHubby_Hub_stealth,
  _ as ContentHubby_Hub_stereo_sound,
  _ as ContentHubby_Hub_stereo_sound_desc,
  _ as ContentHubby_Hub_story_driven,
  _ as ContentHubby_Hub_story_driven_menu,
  _ as ContentHubby_Hub_strategy,
  _ as ContentHubby_Hub_strategy_card_board,
  _ as ContentHubby_Hub_strategy_card_board_menu,
  _ as ContentHubby_Hub_strategy_cities_settlements,
  _ as ContentHubby_Hub_strategy_cities_settlements_menu,
  _ as ContentHubby_Hub_strategy_grand_4x,
  _ as ContentHubby_Hub_strategy_grand_4x_menu,
  _ as ContentHubby_Hub_strategy_menu,
  _ as ContentHubby_Hub_strategy_military,
  _ as ContentHubby_Hub_strategy_military_menu,
  _ as ContentHubby_Hub_strategy_moba_auto_battler,
  _ as ContentHubby_Hub_strategy_moba_auto_battler_menu,
  _ as ContentHubby_Hub_strategy_real_time,
  _ as ContentHubby_Hub_strategy_real_time_menu,
  _ as ContentHubby_Hub_strategy_sim_management,
  _ as ContentHubby_Hub_strategy_sim_management_menu,
  _ as ContentHubby_Hub_strategy_tactics,
  _ as ContentHubby_Hub_strategy_tactics_menu,
  _ as ContentHubby_Hub_strategy_turn_based,
  _ as ContentHubby_Hub_strategy_turn_based_menu,
  _ as ContentHubby_Hub_subtitle_options,
  _ as ContentHubby_Hub_subtitle_options_desc,
  _ as ContentHubby_Hub_surround_sound,
  _ as ContentHubby_Hub_surround_sound_desc,
  _ as ContentHubby_Hub_survival,
  _ as ContentHubby_Hub_survival_menu,
  _ as ContentHubby_Hub_survival_stealth,
  _ as ContentHubby_Hub_survival_stealth_menu,
  _ as ContentHubby_Hub_themes,
  _ as ContentHubby_Hub_themes_and_interests,
  _ as ContentHubby_Hub_themes_and_interests_menu,
  _ as ContentHubby_Hub_themes_menu,
  _ as ContentHubby_Hub_time_management,
  _ as ContentHubby_Hub_time_management_menu,
  _ as ContentHubby_Hub_touch_only_option,
  _ as ContentHubby_Hub_touch_only_option_desc,
  _ as ContentHubby_Hub_tower_defense,
  _ as ContentHubby_Hub_tower_defense_menu,
  _ as ContentHubby_Hub_trains,
  _ as ContentHubby_Hub_trains_desc,
  _ as ContentHubby_Hub_turnbased_rpg,
  _ as ContentHubby_Hub_typing,
  _ as ContentHubby_Hub_typing_desc,
  _ as ContentHubby_Hub_visual_novel,
  _ as ContentHubby_Hub_visual_novel_menu,
  _ as ContentHubby_Hub_walking_simulator,
  _ as ContentHubby_Hub_walking_simulator_menu,
  _ as ContentHubby_Hub_wargame,
  _ as ContentHubby_Hub_zombies_vampires,
  _ as ContentHubby_Menu_CurrentSpecials,
  _ as ContentHubby_Menu_NewAndNoteworthy,
  _ as Library_Install,
  _ as Library_Update_TryItNow2,
  _ as Store_VR_MainMenu_VR_Hardware,
  _ as Store_VR_MainMenu_Virtual_Reality,
  _ as additional_game_content_soundtracks,
  _ as api_category_coming_soon,
  _ as api_category_new_releases,
  _ as api_category_top_sellers,
  _ as browse_adultonly,
  _ as browse_demos,
  _ as browse_free,
  _ as browse_remoteplay,
  _ as btn_add_to_wishlist,
  _ as contenthub_title_controller,
  _ as contenthub_title_pccafe,
  _ as default,
  _ as discount_desc_limited_time,
  _ as discount_desc_limited_time_date,
  _ as discount_desc_preset_loyalty,
  _ as dummy,
  _ as games_osx,
  _ as genre_early_access,
  _ as genre_free2play,
  _ as label_back_catalogue,
  _ as label_deepest_discount,
  _ as label_early_beta_access,
  _ as label_for_a_limited_time_only,
  _ as label_free_week,
  _ as label_free_weekend,
  _ as label_highlighted_deals,
  _ as label_just_updated,
  _ as label_new_and_upcoming,
  _ as label_new_dlc_available,
  _ as label_play_free_generic,
  _ as label_play_free_until_custom,
  _ as label_pre_load_now,
  _ as language,
  _ as limitedtime_install_and_keep,
  _ as msg_action_buy,
  _ as msg_action_details,
  _ as msg_action_info,
  _ as msg_advanced_access,
  _ as msg_available_everywhere,
  _ as msg_available_just_released,
  _ as msg_available_just_released_from_early_access,
  _ as msg_available_new_release,
  _ as msg_available_now_free_to_play,
  _ as msg_available_now_ftp_early,
  _ as msg_coming_soon_to_steamos,
  _ as msg_early_access_now_available,
  _ as msg_free_play_until,
  _ as msg_free_play_weekend,
  _ as msg_free_to_play_just_updated,
  _ as msg_free_update,
  _ as msg_in_early_access,
  _ as msg_just_updated_with_free_dlc,
  _ as msg_new_content_now_available,
  _ as msg_new_game,
  _ as msg_new_update_available,
  _ as msg_now_available_for_mac_and_steamos,
  _ as msg_now_available_on_steamos,
  _ as msg_now_available_on_steamos_mac_and_linux,
  _ as msg_now_with_steam_workshop,
  _ as msg_now_with_steamworks,
  _ as msg_on_sale_now,
  _ as msg_play_beta_now,
  _ as msg_play_demo_now,
  _ as msg_play_it_now,
  _ as msg_play_now,
  _ as msg_preload_completed,
  _ as msg_preload_free,
  _ as msg_preload_now,
  _ as msg_preload_now_for_free,
  _ as msg_preload_you_have_completed,
  _ as msg_preload_you_have_pre,
  _ as msg_prepurchase_and_get_beta_access,
  _ as msg_prepurchase_and_play_beta_now,
  _ as msg_prepurchase_bonus,
  _ as msg_prepurchase_now,
  _ as msg_publisher_sale,
  _ as msg_publisher_weekend,
  _ as msg_steam_workshop_now_available,
  _ as msg_try_it_now,
  _ as msg_watch_movie_now,
  _ as msg_weekend_on_now,
  _ as msg_weekend_play_free,
  _ as msg_weekend_trial,
  _ as mst_weekend_description_free,
  _ as promo_ends_custom,
  _ as promo_giveaway,
  _ as spotlight_daily_deal,
  _ as spotlight_franchise_sale,
  _ as spotlight_major_update,
  _ as spotlight_midweek_deal,
  _ as spotlight_midweek_madness,
  _ as spotlight_thirdparty_event,
  _ as spotlight_weekend_deal,
  _ as spotlight_weeklong_header1,
  _ as spotlight_weeklong_sale,
  _ as store_tab_greatondeck,
  _ as store_tab_greatonframe,
  _ as store_tab_linux,
  _ as store_tab_software_home,
  _ as text_free_new_dlc_now_available,
  _ as text_new_free_to_play,
  _ as text_now_available,
  _ as text_now_available_mac,
  _ as text_now_available_on_pc_mac_and_linux,
  _ as text_now_available_steamplay,
  _ as text_now_free_to_play,
};
