var _ = `swedish`,
  _ = `Spela gratis fram till %1$s.`,
  _ = `Erbjudandet upphör %1$s.`,
  _ = `Spela gratis!`,
  _ = `Gratishelg`,
  _ = `Spela gratis till på måndag kl. 19.00`,
  _ = `Spela gratis fram till %1$s`,
  _ = `Gratisvecka`,
  _ = `Nyligen uppdaterat`,
  _ = `ENDAST UNDER BEGRÄNSAD TID`,
  _ = `Förköp och spela betan nu!`,
  _ = `SPELA BETAVERSIONEN NU!`,
  _ = `Förköp och få tillgång till betan`,
  _ = `Steam Workshop nu tillgängligt`,
  _ = `Nu med Steam Workshop`,
  _ = `Nu med Steamworks`,
  _ = `Nu tillgängligt på SteamOS!`,
  _ = `Tillgängligt nu på SteamOS, Mac och Linux!`,
  _ = `Förladda nu`,
  _ = `Gratis uppdatering`,
  _ = `Spela demoversionen nu!`,
  _ = `Förladda (gratis)`,
  _ = `Förladda nu gratis`,
  _ = `Du har förladdat`,
  _ = `Du har slutfört förladdningen `,
  _ = `Förladdning slutförd`,
  _ = `Förköp nu`,
  _ = `Precis uppdaterat med gratis DLC!`,
  _ = `Tillgängligt nu på Mac och SteamOS!`,
  _ = `Kommer snart till SteamOS!`,
  _ = `Ladda ned och titta på filmen i full HD-kvalitet`,
  _ = `Lägg till på önskelistan`,
  _ = `Nu i Early Access`,
  _ = `i Early Access`,
  _ = `Ny uppdatering tillgänglig`,
  _ = `Gratis`,
  _ = `Nytt släpp`,
  _ = `Nyligen släppt från Early Access!`,
  _ = `Nyligen släppt`,
  _ = `Ute nu`,
  _ = `Nytt spel`,
  _ = `Tillgängligt nu – gratis att spela`,
  _ = `Gratis att spela – Nyligen uppdaterat`,
  _ = `Nu gratis att spela i Early Access`,
  _ = `Advance Access tillgänglig`,
  _ = `Nytt innehåll tillgängligt nu`,
  _ = `Spela hela spelet gratis – endast denna helg`,
  _ = `Gratishelg – pågår nu`,
  _ = `Gratis provversion av hela spelet`,
  _ = `Spela gratis nu`,
  _ = `Förköp och få en bonus`,
  _ = `Bästsäljare`,
  _ = `Nya släpp`,
  _ = `Helgerbjudande`,
  _ = `Mitt i veckan-erbjudande`,
  _ = `Mitt i veckan-erbjudande`,
  _ = `Franchiserea`,
  _ = `Tredjepartseventet`,
  _ = `Stor uppdatering`,
  _ = `Dagens erbjudande`,
  _ = `Veckorea`,
  _ = `Hela veckan`,
  _ = `Gåva!`,
  _ = `Under begränsad tid: Installera nu och behåll för alltid`,
  _ = `Kommer snart`,
  _ = `Nytt och kommande`,
  _ = `Framhävda erbjudanden`,
  _ = `Katalog`,
  _ = `Utgivarhelg`,
  _ = `Utgivarrea`,
  _ = `Installera`,
  _ = `LOJALITETSRABATT! Erbjudandet upphör om %1$s`,
  _ = `Mer information`,
  _ = `Spela nu`,
  _ = `Spela det nu`,
  _ = `Köp det nu`,
  _ = `Klicka här om du vill veta mer`,
  _ = `På rea nu!`,
  _ = `Tidig tillgång till betaversion`,
  _ = `Nytt DLC tillgängligt`,
  _ = `Förladda nu`,
  _ = `Största rabatten`,
  _ = `Tidsbegränsat erbjudande`,
  _ = `Tidsbegränsat erbjudande`,
  _ = `Ute nu`,
  _ = `Ute nu`,
  _ = `Ute nu till Mac`,
  _ = `Ute nu till pc, Mac och Linux!`,
  _ = `Nu gratis att spela`,
  _ = `Nytt gratis att spela`,
  _ = `Ny gratis DLC ute nu`,
  _ = `Förstapersonsaction och skjutare`,
  _ = `Förstapersonsaction och skjutare`,
  _ = `2D-action`,
  _ = `2D-action`,
  _ = `Tredjepersons action och skjutare`,
  _ = `Tredjepersons action och skjutare`,
  _ = `Action`,
  _ = `Action`,
  _ = `Actionäventyr`,
  _ = `Actionäventyr`,
  _ = `Action och äventyr`,
  _ = `Actionäventyr`,
  _ = `Förstapersonsskjutare`,
  _ = `Förstapersonsskjutare`,
  _ = `Actionskräck`,
  _ = `Actionskräck`,
  _ = `Rogue-aktig action`,
  _ = `Rogue-aktig action`,
  _ = `Actionrollspel`,
  _ = `Action-RPG`,
  _ = `Plattformare & runners`,
  _ = `Plattformare & runner`,
  _ = `Skjutare`,
  _ = `Skjutare`,
  _ = `Tredjepersonsskjutare`,
  _ = `Tredjepersonsskjutare`,
  _ = `Action och aktiviteter`,
  _ = `Action och aktiviteter`,
  _ = `Äventyr`,
  _ = `Äventyr`,
  _ = `Äventyr och fritid`,
  _ = `Äventyr och fritid`,
  _ = `Öppen värld`,
  _ = `Öppen värld`,
  _ = `Peka och klicka-äventyr`,
  _ = `Peka och klicka-äventyr`,
  _ = `Äventyrsrollspel`,
  _ = `Äventyrsrollspel`,
  _ = `Avkopplande rollspel`,
  _ = `Avkopplande rollspel`,
  _ = `Estetiskt tilltalande`,
  _ = `Teman`,
  _ = `Anime`,
  _ = `Anime`,
  _ = `Arkad`,
  _ = `Arkad`,
  _ = `Arkad och rytm`,
  _ = `Arkad & rytm`,
  _ = `Konststilar och musik`,
  _ = `Konststilar och musik`,
  _ = `Beat 'em up`,
  _ = `Beat 'Em Up`,
  _ = `Business och politik`,
  _ = `Business & politik`,
  _ = `Fritid`,
  _ = `Fritid`,
  _ = `Avkopplande kort- och brädspel`,
  _ = `Fritid: Kortspel och brädspel`,
  _ = `Fritid och pussel`,
  _ = `Fritid och pussel`,
  _ = `Fritid och berättande`,
  _ = `Fritid och berättande`,
  _ = `Avkopplande pussel`,
  _ = `Avkopplande pussel`,
  _ = `Karaktärsactionspel`,
  _ = `Klick- och passivitetsspel`,
  _ = `Klick och passivt`,
  _ = `Brott och straff`,
  _ = `Brott och straff`,
  _ = `Sött och tecknat`,
  _ = `Sött och tecknat`,
  _ = `Dejtsimuleringar`,
  _ = `Dejtsimulering`,
  _ = `Kör- och pilotspel`,
  _ = `Kör- & pilotspel`,
  _ = `Vetenskap och lärande`,
  _ = `Vetenskap och lärande`,
  _ = `Experimentellt`,
  _ = `Experimentellt`,
  _ = `Öppen värld`,
  _ = `Öppen värld`,
  _ = `Fantasy`,
  _ = `Fantasy`,
  _ = `Fantasy och övernaturligt`,
  _ = `Fantasy och övernaturligt`,
  _ = `Fighting`,
  _ = `Fighting`,
  _ = `Fighting och kampsport`,
  _ = `Fighting & kampsport`,
  _ = `Gratis att spela`,
  _ = `Hacka och slå`,
  _ = `Dolda objekt`,
  _ = `Dolda objekt`,
  _ = `Historia`,
  _ = `Skräck`,
  _ = `Skräck`,
  _ = `Mörkt och skräck`,
  _ = `Mörkt och skräck`,
  _ = `Steams Scream-festival`,
  _ = `Base Builder Festival`,
  _ = `Smygspel`,
  _ = `Shoot 'em up`,
  _ = `Berättelserikt`,
  _ = `Berättelserikt`,
  _ = `Interactive Stories`,
  _ = `Interaktiv berättelse`,
  _ = `Livssimulering`,
  _ = `Platser och världar`,
  _ = `Matcha 3`,
  _ = `Matcha 3`,
  _ = `Flera spelare`,
  _ = `Flera spelare`,
  _ = `Militär och krig`,
  _ = `Militär och krig`,
  _ = `Minimalistiskt och abstrakt`,
  _ = `Minimalistiskt och abstrakt`,
  _ = `Flera spelare`,
  _ = `Flera spelare`,
  _ = `Tävlingsinriktat för flera spelare`,
  _ = `Tävlingsinriktat`,
  _ = `Battle royale`,
  _ = `Battle Royale`,
  _ = `Co-op`,
  _ = `Co-op`,
  _ = `LAN`,
  _ = `LAN`,
  _ = `Lokala flerspelar- och gruppspel`,
  _ = `Lokalt & grupp`,
  _ = `MMO`,
  _ = `MMO`,
  _ = `MOBA och autobattler`,
  _ = `MOBA och autobattler`,
  _ = `Tävlingsinriktat online`,
  _ = `Tävlingsinriktat online`,
  _ = `Skjutare för flera spelare`,
  _ = `Skjutare`,
  _ = `Musik och rytm`,
  _ = `Musik & rytm`,
  _ = `Överlevnad och tillverkning i öppen värld`,
  _ = `Överlevnad och tillverkning i öppen värld`,
  _ = `Människor och varelser`,
  _ = `Spelare`,
  _ = `Psykedeliskt`,
  _ = `Psykedeliskt`,
  _ = `Psykedeliskt och surrealistiskt`,
  _ = `Psykedeliskt och surrealistiskt`,
  _ = `Pussel`,
  _ = `Pussel`,
  _ = `Pussel`,
  _ = `Pussel`,
  _ = `Svårt pussel`,
  _ = `Svårt pussel`,
  _ = `Logikpussel`,
  _ = `Logikpussel`,
  _ = `Pussel för flera spelare`,
  _ = `Pussel för flera spelare`,
  _ = `Racing`,
  _ = `Tävling med bilar, cyklar, skidor och mer.`,
  _ = `Racing`,
  _ = `Racingsimulering`,
  _ = `Racingsimulering`,
  _ = `Stridsracing`,
  _ = `Stridsracing`,
  _ = `Racing- och pilotspel`,
  _ = `Racing- & pilotspel`,
  _ = `Retro`,
  _ = `Retro`,
  _ = `Avslappnande`,
  _ = `Avslappnande`,
  _ = `Metroidvania`,
  _ = `Metroidvania`,
  _ = `Minimalt och avslappnande`,
  _ = `Minimalt och avslappnande`,
  _ = `Turbaserat rogue-aktigt`,
  _ = `Turbaserat rogue-aktigt`,
  _ = `Rogue-aktigt och rogue-lite`,
  _ = `Rogue-aktigt`,
  _ = `Rogue-aktiga`,
  _ = `Rogue-aktigt`,
  _ = `Rollspel`,
  _ = `Rollspel`,
  _ = `Actionrollspel`,
  _ = `Action-RPG`,
  _ = `CRPG`,
  _ = `CRPG`,
  _ = `CRPG`,
  _ = `CRPG`,
  _ = `Dungeon crawlers`,
  _ = `Dungeon crawler`,
  _ = `Japanska rollspel`,
  _ = `JRPG`,
  _ = `MMORPG`,
  _ = `MMORPG`,
  _ = `Gruppbaserat rollspel`,
  _ = `Gruppbaserat`,
  _ = `Berättelsedrivet rollspel`,
  _ = `Berättelsedrivet`,
  _ = `Strategiskt och taktiskt rollspel`,
  _ = `Strategiskt RPG`,
  _ = `Turbaserat rollspel`,
  _ = `Turbaserat`,
  _ = `Sci-fi och cyberpunk`,
  _ = `Sci-fi & cyberpunk`,
  _ = `Skjutare`,
  _ = `Skjutare`,
  _ = `Byggsimuleringar`,
  _ = `Byggare`,
  _ = `Bygg- och automationssimulering`,
  _ = `Byggare & automation`,
  _ = `Business och tycoon`,
  _ = `Business & tycoon`,
  _ = `Stads- och bosättningssimuleringar`,
  _ = `Stad & bosättning`,
  _ = `Lantbrukssimuleringar`,
  _ = `Lantbruk`,
  _ = `Jordbruks- och tillverkningssimulering`,
  _ = `Lantbruk & tillverkning`,
  _ = `Livssimulering och fängslande spel`,
  _ = `Liv & fängslande`,
  _ = `Livssimuleringar och romantik`,
  _ = `Liv & romantik`,
  _ = `Simulering och management`,
  _ = `Simulering och management`,
  _ = `Öppen värld-simuleringar`,
  _ = `Öppen värld`,
  _ = `Sandlåde- och fysiksimuleringar`,
  _ = `Sandlåda & fysik`,
  _ = `Politiksimuleringar`,
  _ = `Politik`,
  _ = `Sandlådesimuleringar och gudaspel`,
  _ = `Sandlåda och gudaspel`,
  _ = `Rymd- och flygsimulering`,
  _ = `Rymd och flyg`,
  _ = `Dejtsimuleringar`,
  _ = `Dejting`,
  _ = `Simulering`,
  _ = `Simuleringar`,
  _ = `En spelare`,
  _ = `En spelare`,
  _ = `Spelarstöd`,
  _ = `Sport`,
  _ = `Led ett lag, träna inför den stora turneringen eller bara spela.`,
  _ = `Alla sporter`,
  _ = `Sport och racing`,
  _ = `Sport och racing`,
  _ = `Bollsport`,
  _ = `Bollsport`,
  _ = `Stridssport`,
  _ = `Stridssport`,
  _ = `Fiske och jakt`,
  _ = `Fiske & jakt`,
  _ = `Individuell sport`,
  _ = `Individuell sport`,
  _ = `Sportsimuleringar och sportmanager`,
  _ = `Sportsimulering`,
  _ = `Lagsport`,
  _ = `Lagsport`,
  _ = `Vintersport`,
  _ = `Vintersport`,
  _ = `Kusligt`,
  _ = `Kusligt`,
  _ = `Berättelsedrivet`,
  _ = `Berättelsedrivet`,
  _ = `Strategi`,
  _ = `Strategi`,
  _ = `Kort- och brädspel`,
  _ = `Kortspel & brädspel`,
  _ = `Stad- och bosättningsbyggare`,
  _ = `Stad & bosättning`,
  _ = `Storstrategi och 4X`,
  _ = `Storstrategi & 4X`,
  _ = `Militär strategi`,
  _ = `Militärt`,
  _ = `MOBA- och autobattler-spel`,
  _ = `MOBA och autobattler`,
  _ = `Realtidsstrategi`,
  _ = `Realtidsstrategi`,
  _ = `Simulering och management`,
  _ = `Simulering & management`,
  _ = `Strategi och taktik`,
  _ = `Strategi och taktik`,
  _ = `Turbaserad strategi`,
  _ = `Turbaserad strategi`,
  _ = `Överlevnad`,
  _ = `Överlevnad`,
  _ = `Överlevnad och smygspel`,
  _ = `Överlevnad och smyg`,
  _ = `Teman`,
  _ = `Teman`,
  _ = `Teman och intressen`,
  _ = `Teman`,
  _ = `Tidsplanering`,
  _ = `Tidsplanering`,
  _ = `Tower defense`,
  _ = `Tower defense`,
  _ = `Visuella romaner`,
  _ = `Visuell roman`,
  _ = `Vandringssimuleringar`,
  _ = `Vandringssimulering`,
  _ = `Rymden`,
  _ = `Rymden`,
  _ = `Kvinnlig huvudperson`,
  _ = `Kvinnlig huvudperson`,
  _ = `HBTQ+`,
  _ = `HBTQ+`,
  _ = `Pixel och retro`,
  _ = `Pixel & retro`,
  _ = `Val har betydelse och berättelsedrivet`,
  _ = `Val har betydelse`,
  _ = `Mysterium och deckare`,
  _ = `Mysterium & deckare`,
  _ = `Hobby- och jobbsimulering`,
  _ = `Hobby & jobb`,
  _ = `Going rogue`,
  _ = `Bra på Deck`,
  _ = `Bra på Steam Frame`,
  _ = `Kapitalism och ekonomi`,
  _ = `Pirater vs ninjor`,
  _ = `Dinosaurier vs robotar`,
  _ = `Oändlig återspelning`,
  _ = `Rymdutforskning`,
  _ = `Kortleksbyggare`,
  _ = `Turbaserat RPG`,
  _ = `Matlagning`,
  _ = `Fordon`,
  _ = `Fiske`,
  _ = `Kasta ut fiskelinan för tävling eller avkoppling.`,
  _ = `Passivt`,
  _ = `Rytm`,
  _ = `Sokoban`,
  _ = `Putta på lådor i rätt ordning.`,
  _ = `Jordbruk`,
  _ = `Krigsspel`,
  _ = `Samla varelser`,
  _ = `Zombier vs vampyrer`,
  _ = `Blockknuffare`,
  _ = `Automation`,
  _ = `4X-strategi`,
  _ = `eXplore (utforska), eXpand (utöka), eXploit (utnyttja) och eXterminate (utrota).`,
  _ = `Politiksimulering`,
  _ = `Djur`,
  _ = `Deckare`,
  _ = `Samla ledtrådar och lös fallet.`,
  _ = `Brädspel`,
  _ = `Maskinskrivning`,
  _ = `Kan du skriva supersnabbt – och felfritt – på tangentbordet?`,
  _ = `Strids-PVP`,
  _ = `Hästar`,
  _ = `Rid, tävla och ta hand om hästar, åsnor, ponnyer, enhörningar osv.`,
  _ = `Medeltida`,
  _ = `Hus och hem`,
  _ = `Havet`,
  _ = `Hentai`,
  _ = `Vuxet`,
  _ = `Kulor`,
  _ = `Manövrera dig igenom fiendens projektiler eller avfyra ett gäng egna. Oavsett vilket, förbered dig på visuellt kaos.`,
  _ = `Deduktion`,
  _ = `Observera, utred, bluffa och ljug för att avslöja förrädare och dra slutsatser från dold information innan tiden rinner ut.`,
  _ = `Tåg`,
  _ = `Lägg spår, planera rutter och kör loket genom städer och landsbygd.`,
  _ = `Cyberpunk`,
  _ = `Alla möjliga typer av högteknologi i en dystopisk science fiction-framtid.`,
  _ = `Arkad och bowling`,
  _ = `Skjut iväg bollar som studsar mot pinnar, och slå ner käglor.`,
  _ = `Överlevnad och tillverkning (PvE)`,
  _ = `Samla och tillverka saker för att överleva mot naturens krafter.`,
  _ = `Programmering`,
  _ = `Skriv instruktioner, hacka och lös svåra logiska pussel.`,
  _ = `Gruppbaserat RPG`,
  _ = `Skaffa utrustning och gå upp i nivå med ditt team.`,
  _ = `Fantasy och övernaturligt`,
  _ = `Skjutare utan zombier`,
  _ = `Avslappnande djurpussel`,
  _ = `Nytt och intressant`,
  _ = `Rabatter och event`,
  _ = `Justerbar svårighetsgrad`,
  _ = `De här spelen erbjuder flera sätt att justera svårighetsgraden.`,
  _ = `Spara när som helst`,
  _ = `I de här spelen kan du manuellt spara framsteg nästan när som helst.`,
  _ = `Justerbar textstorlek`,
  _ = `Justera textstorlek och gränssnittsskalning för att få ord och element att se större eller mindre ut.`,
  _ = `Undertextalternativ`,
  _ = `Justera hur undertexter visas genom att ändra teckenstorlek, färg, bakgrundsopacitet med mera.`,
  _ = `Färgalternativ`,
  _ = `Färger används inte för att kommunicera viktig information eller så kan färgerna ändras.`,
  _ = `Kamerakomfort`,
  _ = `I de här spelen kan du justera eller inaktivera obekväma kamerarörelser (som skärmskakning, gungande kamera eller rörelseoskärpa).`,
  _ = `Personanpassade volymkontroller`,
  _ = `I de här spelen kan du justera volymen för olika typer av ljud i spelet separat (som musik, ljudeffekter eller röster).`,
  _ = `Steroljud`,
  _ = `I de här spelen kan du använda stereoljud för att avgöra hur långt från vänster eller höger ljud kommer ifrån.`,
  _ = `Surroundljud`,
  _ = `I de här spelen kan du använda surroundljud för att identifiera hur långt i vilken riktning ljud kommer ifrån.`,
  _ = `Upplästa spelmenyer`,
  _ = `De här spelen stöder skärmläsare eller erbjuder upplästa spelmenyer. Menyerna kan användas och förstås utan att man behöver läsa texten.`,
  _ = `Spelbart utan quick time events`,
  _ = `I de här spelen kan du undvika sekvenser av exakt tajmade inmatningar (quick time events) eller snabbtryck på knappar (button mashing).`,
  _ = `Endast tangentbord`,
  _ = `De här spelen kan spelas med endast tangentbord eller med ett tillgänglighetsverktyg som motsvarar tangentbordsinmatning.`,
  _ = `Endast mus`,
  _ = `De här spelen kan spelas med endast mus eller med ett tillgänglighetsverktyg som motsvarar musinmatning.`,
  _ = `Endast beröring`,
  _ = `De här spelen kan spelas med endast beröringskontroller eller med ett tillgänglighetsverktyg som motsvarar beröringsinmatning.`,
  _ = `Tal till text i chatt`,
  _ = `I de här spelen kan röstchatt läsas som en texttranskription i realtid.`,
  _ = `Text till tal i chatt`,
  _ = `I de här spelen kan textchatt läsas upp i realtid.`,
  _ = `Spelbart i din egen takt`,
  _ = `I de här spelen kan du ta din tid mellan varje inmatning.`,
  _ = `Spelbart utan synförmåga`,
  _ = `De här spelen kan spelas utan att se skärmen.`,
  _ = `Kontrastjustering`,
  _ = `I de här spelen kan du justera kontrasten efter behov.`,
  _ = `Enbart för vuxna`,
  _ = `Demoversioner`,
  _ = `Gratis att spela`,
  _ = `Early Access`,
  _ = `Bra på Deck`,
  _ = `Bra på Steam Frame`,
  _ = `Kontrollvänligt`,
  _ = `Remote Play`,
  _ = `VR-titlar`,
  _ = `VR-maskinvara`,
  _ = `Programvara`,
  _ = `Soundtrack`,
  _ = `macOS`,
  _ = `SteamOS + Linux`,
  _ = `För internetkaféer`,
  _ = `Testa nu`,
  _ = `Prova det nu`,
  _ = `dummy`,
  _ = {
    language: _,
    label_play_free_until_custom: _,
    promo_ends_custom: _,
    label_play_free_generic: _,
    label_free_weekend: _,
    msg_free_play_weekend: _,
    msg_free_play_until: _,
    label_free_week: _,
    label_just_updated: _,
    label_for_a_limited_time_only: _,
    msg_prepurchase_and_play_beta_now: _,
    msg_play_beta_now: _,
    msg_prepurchase_and_get_beta_access: _,
    msg_steam_workshop_now_available: _,
    msg_now_with_steam_workshop: _,
    msg_now_with_steamworks: _,
    msg_now_available_on_steamos: _,
    msg_now_available_on_steamos_mac_and_linux: _,
    msg_preload_now: _,
    msg_free_update: _,
    msg_play_demo_now: _,
    msg_preload_free: _,
    msg_preload_now_for_free: _,
    msg_preload_you_have_pre: _,
    msg_preload_you_have_completed: _,
    msg_preload_completed: _,
    msg_prepurchase_now: _,
    msg_just_updated_with_free_dlc: _,
    msg_now_available_for_mac_and_steamos: _,
    msg_coming_soon_to_steamos: _,
    msg_watch_movie_now: _,
    btn_add_to_wishlist: _,
    msg_early_access_now_available: _,
    msg_in_early_access: _,
    msg_new_update_available: _,
    browse_free: _,
    msg_available_new_release: _,
    msg_available_just_released_from_early_access: _,
    msg_available_just_released: _,
    msg_available_everywhere: _,
    msg_new_game: _,
    msg_available_now_free_to_play: _,
    msg_free_to_play_just_updated: _,
    msg_available_now_ftp_early: _,
    msg_advanced_access: _,
    msg_new_content_now_available: _,
    mst_weekend_description_free: _,
    msg_weekend_on_now: _,
    msg_weekend_trial: _,
    msg_weekend_play_free: _,
    msg_prepurchase_bonus: _,
    api_category_top_sellers: _,
    api_category_new_releases: _,
    spotlight_weekend_deal: _,
    spotlight_midweek_madness: _,
    spotlight_midweek_deal: _,
    spotlight_franchise_sale: _,
    spotlight_thirdparty_event: _,
    spotlight_major_update: _,
    spotlight_daily_deal: _,
    spotlight_weeklong_sale: _,
    spotlight_weeklong_header1: _,
    promo_giveaway: _,
    limitedtime_install_and_keep: _,
    api_category_coming_soon: _,
    label_new_and_upcoming: _,
    label_highlighted_deals: _,
    label_back_catalogue: _,
    msg_publisher_weekend: _,
    msg_publisher_sale: _,
    Library_Install: _,
    discount_desc_preset_loyalty: _,
    msg_action_details: _,
    msg_play_now: _,
    msg_play_it_now: _,
    msg_action_buy: _,
    msg_action_info: _,
    msg_on_sale_now: _,
    label_early_beta_access: _,
    label_new_dlc_available: _,
    label_pre_load_now: _,
    label_deepest_discount: _,
    discount_desc_limited_time: _,
    discount_desc_limited_time_date: _,
    text_now_available: _,
    text_now_available_steamplay: _,
    text_now_available_mac: _,
    text_now_available_on_pc_mac_and_linux: _,
    text_now_free_to_play: _,
    text_new_free_to_play: _,
    text_free_new_dlc_now_available: _,
    ContentHubby_Hub_1st_person_action_shooting: _,
    ContentHubby_Hub_1st_person_action_shooting_menu: _,
    ContentHubby_Hub_2d_view_action: _,
    ContentHubby_Hub_2d_view_action_menu: _,
    ContentHubby_Hub_3rd_person_action_shooting: _,
    ContentHubby_Hub_3rd_person_action_shooting_menu: _,
    ContentHubby_Hub_action: _,
    ContentHubby_Hub_action_menu: _,
    ContentHubby_Hub_action_dash_adventure: _,
    ContentHubby_Hub_action_dash_adventure_menu: _,
    ContentHubby_Hub_action_and_adventure: _,
    ContentHubby_Hub_action_and_adventure_menu: _,
    ContentHubby_Hub_action_fps: _,
    ContentHubby_Hub_action_fps_menu: _,
    ContentHubby_Hub_action_horror: _,
    ContentHubby_Hub_action_horror_menu: _,
    ContentHubby_Hub_action_rogue_like: _,
    ContentHubby_Hub_action_rogue_like_menu: _,
    ContentHubby_Hub_action_rpg: _,
    ContentHubby_Hub_action_rpg_menu: _,
    ContentHubby_Hub_action_run_jump: _,
    ContentHubby_Hub_action_run_jump_menu: _,
    ContentHubby_Hub_action_shooter: _,
    ContentHubby_Hub_action_shooter_menu: _,
    ContentHubby_Hub_action_tps: _,
    ContentHubby_Hub_action_tps_menu: _,
    ContentHubby_Hub_actions_activities: _,
    ContentHubby_Hub_actions_activities_menu: _,
    ContentHubby_Hub_adventure: _,
    ContentHubby_Hub_adventure_menu: _,
    ContentHubby_Hub_adventure_and_casual: _,
    ContentHubby_Hub_adventure_and_casual_menu: _,
    ContentHubby_Hub_adventure_explore_open_world: _,
    ContentHubby_Hub_adventure_explore_open_world_menu: _,
    ContentHubby_Hub_adventure_point_click: _,
    ContentHubby_Hub_adventure_point_click_menu: _,
    ContentHubby_Hub_adventure_rpg: _,
    ContentHubby_Hub_adventure_rpg_menu: _,
    ContentHubby_Hub_adventure_rpg_casual: _,
    ContentHubby_Hub_adventure_rpg_casual_menu: _,
    ContentHubby_Hub_aesthetic: _,
    ContentHubby_Hub_aesthetic_menu: _,
    ContentHubby_Hub_anime_mild: _,
    ContentHubby_Hub_anime_mild_menu: _,
    ContentHubby_Hub_arcade: _,
    ContentHubby_Hub_arcade_menu: _,
    ContentHubby_Hub_arcade_rhythm: _,
    ContentHubby_Hub_arcade_rhythm_menu: _,
    ContentHubby_Hub_artstyles_music: _,
    ContentHubby_Hub_artstyles_music_menu: _,
    ContentHubby_Hub_action_beat_em_up: _,
    ContentHubby_Hub_action_beat_em_up_menu: _,
    ContentHubby_Hub_business_politics: _,
    ContentHubby_Hub_business_politics_menu: _,
    ContentHubby_Hub_casual: _,
    ContentHubby_Hub_casual_menu: _,
    ContentHubby_Hub_casual_card_board: _,
    ContentHubby_Hub_casual_card_board_menu: _,
    ContentHubby_Hub_casual_and_puzzle: _,
    ContentHubby_Hub_casual_and_puzzle_menu: _,
    ContentHubby_Hub_casual_and_story: _,
    ContentHubby_Hub_casual_and_story_menu: _,
    ContentHubby_Hub_casual_puzzle: _,
    ContentHubby_Hub_casual_puzzle_menu: _,
    ContentHubby_Hub_character_action_game: _,
    ContentHubby_Hub_clickers_idlers: _,
    ContentHubby_Hub_clickers_idlers_menu: _,
    ContentHubby_Hub_crime_justice: _,
    ContentHubby_Hub_crime_justice_menu: _,
    ContentHubby_Hub_cute_cartoon: _,
    ContentHubby_Hub_cute_cartoon_menu: _,
    ContentHubby_Hub_dating_sim: _,
    ContentHubby_Hub_dating_sim_menu: _,
    ContentHubby_Hub_driving_piloting: _,
    ContentHubby_Hub_driving_piloting_menu: _,
    ContentHubby_Hub_education: _,
    ContentHubby_Hub_education_menu: _,
    ContentHubby_Hub_experimental: _,
    ContentHubby_Hub_experimental_menu: _,
    ContentHubby_Hub_exploration_open_world: _,
    ContentHubby_Hub_exploration_open_world_menu: _,
    ContentHubby_Hub_fantasy: _,
    ContentHubby_Hub_fantasy_menu: _,
    ContentHubby_Hub_fantasy_supernatural: _,
    ContentHubby_Hub_fantasy_supernatural_menu: _,
    ContentHubby_Hub_fighting: _,
    ContentHubby_Hub_fighting_menu: _,
    ContentHubby_Hub_fighting_martial_arts: _,
    ContentHubby_Hub_fighting_martial_arts_menu: _,
    ContentHubby_Hub_free_to_play: _,
    ContentHubby_Hub_hack_and_slash: _,
    ContentHubby_Hub_hidden_object_menu: _,
    ContentHubby_Hub_hidden_object: _,
    ContentHubby_Hub_history: _,
    ContentHubby_Hub_horror: _,
    ContentHubby_Hub_horror_menu: _,
    ContentHubby_Hub_horror_dark: _,
    ContentHubby_Hub_horror_dark_menu: _,
    ContentHubby_Hub_scream: _,
    ContentHubby_Hub_base_builder: _,
    ContentHubby_Hub_stealth: _,
    ContentHubby_Hub_shmup: _,
    ContentHubby_Hub_interactive_fiction: _,
    ContentHubby_Hub_interactive_fiction_menu: _,
    ContentHubby_Hub_interactive_stories: _,
    ContentHubby_Hub_interactive_stories_menu: _,
    ContentHubby_Hub_life_sim: _,
    ContentHubby_Hub_location_worlds: _,
    ContentHubby_Hub_match_3: _,
    ContentHubby_Hub_match_3_menu: _,
    ContentHubby_Hub_military: _,
    ContentHubby_Hub_military_menu: _,
    ContentHubby_Hub_military_warfare: _,
    ContentHubby_Hub_military_warfare_menu: _,
    ContentHubby_Hub_minimalist_abstract: _,
    ContentHubby_Hub_minimalist_abstract_menu: _,
    ContentHubby_Hub_multiplayer: _,
    ContentHubby_Hub_multiplayer_menu: _,
    ContentHubby_Hub_multiplayer_competitive: _,
    ContentHubby_Hub_multiplayer_competitive_menu: _,
    ContentHubby_Hub_multiplayer_battle_royale: _,
    ContentHubby_Hub_multiplayer_battle_royale_menu: _,
    ContentHubby_Hub_multiplayer_coop: _,
    ContentHubby_Hub_multiplayer_coop_menu: _,
    ContentHubby_Hub_multiplayer_lan: `LAN`,
    ContentHubby_Hub_multiplayer_lan_menu: `LAN`,
    ContentHubby_Hub_multiplayer_local_party: _,
    ContentHubby_Hub_multiplayer_local_party_menu: _,
    ContentHubby_Hub_multiplayer_mmo: `MMO`,
    ContentHubby_Hub_multiplayer_mmo_menu: `MMO`,
    ContentHubby_Hub_multiplayer_moba_auto_battler: _,
    ContentHubby_Hub_multiplayer_moba_auto_battler_menu: _,
    ContentHubby_Hub_multiplayer_online_competitive: _,
    ContentHubby_Hub_multiplayer_online_competitive_menu: _,
    ContentHubby_Hub_multiplayer_shooter: _,
    ContentHubby_Hub_multiplayer_shooter_menu: _,
    ContentHubby_Hub_music_rhythm: _,
    ContentHubby_Hub_music_rhythm_menu: _,
    ContentHubby_Hub_open_world_survival_craft: _,
    ContentHubby_Hub_open_world_survival_craft_menu: _,
    ContentHubby_Hub_people_creatures: _,
    ContentHubby_Hub_players: _,
    ContentHubby_Hub_psychedelic: _,
    ContentHubby_Hub_psychedelic_menu: _,
    ContentHubby_Hub_psychedelic_surreal: _,
    ContentHubby_Hub_psychedelic_surreal_menu: _,
    ContentHubby_Hub_puzzle: _,
    ContentHubby_Hub_puzzle_menu: _,
    ContentHubby_Hub_puzzle_matching: _,
    ContentHubby_Hub_puzzle_matching_menu: _,
    ContentHubby_Hub_puzzle_difficult: _,
    ContentHubby_Hub_puzzle_difficult_menu: _,
    ContentHubby_Hub_puzzle_logic: _,
    ContentHubby_Hub_puzzle_logic_menu: _,
    ContentHubby_Hub_puzzle_multiplayer: _,
    ContentHubby_Hub_puzzle_multiplayer_menu: _,
    ContentHubby_Hub_racing: _,
    ContentHubby_Hub_racing_desc: _,
    ContentHubby_Hub_racing_menu: _,
    ContentHubby_Hub_racing_sim: _,
    ContentHubby_Hub_racing_sim_menu: _,
    ContentHubby_Hub_racing_combat: _,
    ContentHubby_Hub_racing_combat_menu: _,
    ContentHubby_Hub_racing_piloting: _,
    ContentHubby_Hub_racing_piloting_menu: _,
    ContentHubby_Hub_retro: _,
    ContentHubby_Hub_retro_menu: _,
    ContentHubby_Hub_relaxing: _,
    ContentHubby_Hub_relaxing_menu: _,
    ContentHubby_Hub_metroidvania: _,
    ContentHubby_Hub_metroidvania_menu: _,
    ContentHubby_Hub_minimalist_relaxing: _,
    ContentHubby_Hub_minimalist_relaxing_menu: _,
    ContentHubby_Hub_rogue_like_turn_based: _,
    ContentHubby_Hub_rogue_like_turn_based_menu: _,
    ContentHubby_Hub_rogue_like_rogue_lite: _,
    ContentHubby_Hub_rogue_like_rogue_lite_menu: _,
    ContentHubby_Hub_rogue_like: _,
    ContentHubby_Hub_rogue_like_menu: _,
    ContentHubby_Hub_rpg: _,
    ContentHubby_Hub_rpg_menu: _,
    ContentHubby_Hub_rpg_action: _,
    ContentHubby_Hub_rpg_action_menu: _,
    ContentHubby_Hub_rpg_crpg: _,
    ContentHubby_Hub_rpg_crpg_menu: _,
    ContentHubby_Hub_rpg_crpg_traditional_rogue_like: _,
    ContentHubby_Hub_rpg_crpg_traditional_rogue_like_menu: _,
    ContentHubby_Hub_rpg_dungeon_crawler: _,
    ContentHubby_Hub_rpg_dungeon_crawler_menu: _,
    ContentHubby_Hub_rpg_jrpg: _,
    ContentHubby_Hub_rpg_jrpg_menu: _,
    ContentHubby_Hub_rpg_mmo: _,
    ContentHubby_Hub_rpg_mmo_menu: _,
    ContentHubby_Hub_rpg_party_based: _,
    ContentHubby_Hub_rpg_party_based_menu: _,
    ContentHubby_Hub_rpg_story: _,
    ContentHubby_Hub_rpg_story_menu: _,
    ContentHubby_Hub_rpg_strategy_tactics: _,
    ContentHubby_Hub_rpg_strategy_tactics_menu: _,
    ContentHubby_Hub_rpg_turn_based: _,
    ContentHubby_Hub_rpg_turn_based_menu: _,
    ContentHubby_Hub_science_fiction: _,
    ContentHubby_Hub_science_fiction_menu: _,
    ContentHubby_Hub_shooter: _,
    ContentHubby_Hub_shooter_menu: _,
    ContentHubby_Hub_sim_building: _,
    ContentHubby_Hub_sim_building_menu: _,
    ContentHubby_Hub_sim_building_automation: _,
    ContentHubby_Hub_sim_building_automation_menu: _,
    ContentHubby_Hub_sim_business_tycoon: _,
    ContentHubby_Hub_sim_business_tycoon_menu: _,
    ContentHubby_Hub_sim_cities_settlements: _,
    ContentHubby_Hub_sim_cities_settlements_menu: _,
    ContentHubby_Hub_sim_farming: _,
    ContentHubby_Hub_sim_farming_menu: _,
    ContentHubby_Hub_sim_farming_crafting: _,
    ContentHubby_Hub_sim_farming_crafting_menu: _,
    ContentHubby_Hub_sim_life: _,
    ContentHubby_Hub_sim_life_menu: _,
    ContentHubby_Hub_sim_life_romance: _,
    ContentHubby_Hub_sim_life_romance_menu: _,
    ContentHubby_Hub_sim_management: _,
    ContentHubby_Hub_sim_management_menu: _,
    ContentHubby_Hub_sim_open_world: _,
    ContentHubby_Hub_sim_open_world_menu: _,
    ContentHubby_Hub_sim_physics_sandbox: _,
    ContentHubby_Hub_sim_physics_sandbox_menu: _,
    ContentHubby_Hub_sim_policy: _,
    ContentHubby_Hub_sim_policy_menu: _,
    ContentHubby_Hub_sim_sandbox_god_game: _,
    ContentHubby_Hub_sim_sandbox_god_game_menu: _,
    ContentHubby_Hub_sim_space_flight: _,
    ContentHubby_Hub_sim_space_flight_menu: _,
    ContentHubby_Hub_sim_dating: _,
    ContentHubby_Hub_sim_dating_menu: _,
    ContentHubby_Hub_simulation: _,
    ContentHubby_Hub_simulation_menu: _,
    ContentHubby_Hub_singleplayer: _,
    ContentHubby_Hub_singleplayer_menu: _,
    ContentHubby_Hub_social_and_players: _,
    ContentHubby_Hub_sports: _,
    ContentHubby_Hub_sports_desc: _,
    ContentHubby_Hub_sports_menu: _,
    ContentHubby_Hub_sports_and_racing: _,
    ContentHubby_Hub_sports_and_racing_menu: _,
    ContentHubby_Hub_sports_ball: _,
    ContentHubby_Hub_sports_ball_menu: _,
    ContentHubby_Hub_sports_combat: _,
    ContentHubby_Hub_sports_combat_menu: _,
    ContentHubby_Hub_sports_fishing_hunting: _,
    ContentHubby_Hub_sports_fishing_hunting_menu: _,
    ContentHubby_Hub_sports_individual: _,
    ContentHubby_Hub_sports_individual_menu: _,
    ContentHubby_Hub_sports_sim: _,
    ContentHubby_Hub_sports_sim_menu: _,
    ContentHubby_Hub_sports_team: _,
    ContentHubby_Hub_sports_team_menu: _,
    ContentHubby_Hub_sports_winter: _,
    ContentHubby_Hub_sports_winter_menu: _,
    ContentHubby_Hub_spooky: _,
    ContentHubby_Hub_spooky_menu: _,
    ContentHubby_Hub_story_driven: _,
    ContentHubby_Hub_story_driven_menu: _,
    ContentHubby_Hub_strategy: _,
    ContentHubby_Hub_strategy_menu: _,
    ContentHubby_Hub_strategy_card_board: _,
    ContentHubby_Hub_strategy_card_board_menu: _,
    ContentHubby_Hub_strategy_cities_settlements: _,
    ContentHubby_Hub_strategy_cities_settlements_menu: _,
    ContentHubby_Hub_strategy_grand_4x: _,
    ContentHubby_Hub_strategy_grand_4x_menu: _,
    ContentHubby_Hub_strategy_military: _,
    ContentHubby_Hub_strategy_military_menu: _,
    ContentHubby_Hub_strategy_moba_auto_battler: _,
    ContentHubby_Hub_strategy_moba_auto_battler_menu: _,
    ContentHubby_Hub_strategy_real_time: _,
    ContentHubby_Hub_strategy_real_time_menu: _,
    ContentHubby_Hub_strategy_sim_management: _,
    ContentHubby_Hub_strategy_sim_management_menu: _,
    ContentHubby_Hub_strategy_tactics: _,
    ContentHubby_Hub_strategy_tactics_menu: _,
    ContentHubby_Hub_strategy_turn_based: _,
    ContentHubby_Hub_strategy_turn_based_menu: _,
    ContentHubby_Hub_survival: _,
    ContentHubby_Hub_survival_menu: _,
    ContentHubby_Hub_survival_stealth: _,
    ContentHubby_Hub_survival_stealth_menu: _,
    ContentHubby_Hub_themes: _,
    ContentHubby_Hub_themes_menu: _,
    ContentHubby_Hub_themes_and_interests: _,
    ContentHubby_Hub_themes_and_interests_menu: _,
    ContentHubby_Hub_time_management: _,
    ContentHubby_Hub_time_management_menu: _,
    ContentHubby_Hub_tower_defense: _,
    ContentHubby_Hub_tower_defense_menu: _,
    ContentHubby_Hub_visual_novel: _,
    ContentHubby_Hub_visual_novel_menu: _,
    ContentHubby_Hub_walking_simulator: _,
    ContentHubby_Hub_walking_simulator_menu: _,
    ContentHubby_Hub_space: _,
    ContentHubby_Hub_space_menu: _,
    ContentHubby_Hub_female_protagonist: _,
    ContentHubby_Hub_female_protagonist_menu: _,
    ContentHubby_Hub_lgbtq: _,
    ContentHubby_Hub_lgbtq_menu: _,
    ContentHubby_Hub_pixel_retro: _,
    ContentHubby_Hub_pixel_retro_menu: _,
    ContentHubby_Hub_choices_matter: _,
    ContentHubby_Hub_choices_matter_menu: _,
    ContentHubby_Hub_mystery_detective: _,
    ContentHubby_Hub_mystery_detective_menu: _,
    ContentHubby_Hub_hobby_sim: _,
    ContentHubby_Hub_hobby_sim_menu: _,
    ContentHubby_Hub_going_rogue: _,
    ContentHubby_Hub_greatondeck: _,
    ContentHubby_Hub_greatonframe: _,
    ContentHubby_Hub_capitalism_economy: _,
    ContentHubby_Hub_pirates_ninjas: _,
    ContentHubby_Hub_dinos_robots: _,
    ContentHubby_Hub_endlessly_replayable: _,
    ContentHubby_Hub_space_exploration: _,
    ContentHubby_Hub_deckbuilders: _,
    ContentHubby_Hub_turnbased_rpg: _,
    ContentHubby_Hub_cooking: _,
    ContentHubby_Hub_plane_train_autos: _,
    ContentHubby_Hub_fishing: _,
    ContentHubby_Hub_fishing_desc: _,
    ContentHubby_Hub_idle: _,
    ContentHubby_Hub_rhythm: _,
    ContentHubby_Hub_sokoban: _,
    ContentHubby_Hub_sokoban_desc: _,
    ContentHubby_Hub_farming: _,
    ContentHubby_Hub_wargame: _,
    ContentHubby_Hub_creature_collector: _,
    ContentHubby_Hub_zombies_vampires: _,
    ContentHubby_Hub_box_pushing: _,
    ContentHubby_Hub_automation: _,
    ContentHubby_Hub_4x_strategy: _,
    ContentHubby_Hub_4x_strategy_desc: _,
    ContentHubby_Hub_political_sim: _,
    ContentHubby_Hub_animals: _,
    ContentHubby_Hub_detective: _,
    ContentHubby_Hub_detective_desc: _,
    ContentHubby_Hub_board_games: _,
    ContentHubby_Hub_typing: _,
    ContentHubby_Hub_typing_desc: _,
    ContentHubby_Hub_combat_pvp: _,
    ContentHubby_Hub_horses: _,
    ContentHubby_Hub_horses_desc: _,
    ContentHubby_Hub_medieval: _,
    ContentHubby_Hub_house_home: _,
    ContentHubby_Hub_ocean: _,
    ContentHubby_Hub_hentai: _,
    ContentHubby_Hub_mature: _,
    ContentHubby_Hub_bullet: _,
    ContentHubby_Hub_bullet_desc: _,
    ContentHubby_Hub_deduction: _,
    ContentHubby_Hub_deduction_desc: _,
    ContentHubby_Hub_trains: _,
    ContentHubby_Hub_trains_desc: _,
    ContentHubby_Hub_cyberpunk: _,
    ContentHubby_Hub_cyberpunk_desc: _,
    ContentHubby_Hub_pinsandpegs: _,
    ContentHubby_Hub_pinsandpegs_desc: _,
    ContentHubby_Hub_pvesurvival: _,
    ContentHubby_Hub_pvesurvival_desc: _,
    ContentHubby_Hub_programming: _,
    ContentHubby_Hub_programming_desc: _,
    ContentHubby_Hub_partyrpg: _,
    ContentHubby_Hub_partyrpg_desc: _,
    ContentHubby_Hub_fantasy_and_supernatural: _,
    ContentHubby_Hub_shooters_without_zombies: _,
    ContentHubby_Hub_relaxing_animal_puzzles: _,
    ContentHubby_Menu_NewAndNoteworthy: _,
    ContentHubby_Menu_CurrentSpecials: _,
    ContentHubby_Hub_adjustable_difficulty: _,
    ContentHubby_Hub_adjustable_difficulty_desc: _,
    ContentHubby_Hub_save_anytime: _,
    ContentHubby_Hub_save_anytime_desc: _,
    ContentHubby_Hub_adjustable_text_size: _,
    ContentHubby_Hub_adjustable_text_size_desc: _,
    ContentHubby_Hub_subtitle_options: _,
    ContentHubby_Hub_subtitle_options_desc: _,
    ContentHubby_Hub_color_alternatives: _,
    ContentHubby_Hub_color_alternatives_desc: _,
    ContentHubby_Hub_camera_comfort: _,
    ContentHubby_Hub_camera_comfort_desc: _,
    ContentHubby_Hub_custom_volume_controls: _,
    ContentHubby_Hub_custom_volume_controls_desc: _,
    ContentHubby_Hub_stereo_sound: _,
    ContentHubby_Hub_stereo_sound_desc: _,
    ContentHubby_Hub_surround_sound: _,
    ContentHubby_Hub_surround_sound_desc: _,
    ContentHubby_Hub_narrated_game_menus: _,
    ContentHubby_Hub_narrated_game_menus_desc: _,
    ContentHubby_Hub_playable_without_timed_input: _,
    ContentHubby_Hub_playable_without_timed_input_desc: _,
    ContentHubby_Hub_keyboard_only_option: _,
    ContentHubby_Hub_keyboard_only_option_desc: _,
    ContentHubby_Hub_mouse_only_option: _,
    ContentHubby_Hub_mouse_only_option_desc: _,
    ContentHubby_Hub_touch_only_option: _,
    ContentHubby_Hub_touch_only_option_desc: _,
    ContentHubby_Hub_chat_speech_to_text: _,
    ContentHubby_Hub_chat_speech_to_text_desc: _,
    ContentHubby_Hub_chat_text_to_speech: _,
    ContentHubby_Hub_chat_text_to_speech_desc: _,
    ContentHubby_Hub_playable_at_your_own_pace: _,
    ContentHubby_Hub_playable_at_your_own_pace_desc: _,
    ContentHubby_Hub_playable_without_vision: _,
    ContentHubby_Hub_playable_without_vision_desc: _,
    ContentHubby_Hub_contrast_controls: _,
    ContentHubby_Hub_contrast_controls_desc: _,
    browse_adultonly: _,
    browse_demos: _,
    genre_free2play: _,
    genre_early_access: _,
    store_tab_greatondeck: _,
    store_tab_greatonframe: _,
    contenthub_title_controller: _,
    browse_remoteplay: _,
    Store_VR_MainMenu_Virtual_Reality: _,
    Store_VR_MainMenu_VR_Hardware: _,
    store_tab_software_home: _,
    additional_game_content_soundtracks: _,
    games_osx: _,
    store_tab_linux: _,
    contenthub_title_pccafe: _,
    msg_try_it_now: _,
    Library_Update_TryItNow2: _,
    dummy: _,
  };
export {
  _ as ContentHubby_Hub_1st_person_action_shooting,
  _ as ContentHubby_Hub_1st_person_action_shooting_menu,
  _ as ContentHubby_Hub_2d_view_action,
  _ as ContentHubby_Hub_2d_view_action_menu,
  _ as ContentHubby_Hub_3rd_person_action_shooting,
  _ as ContentHubby_Hub_3rd_person_action_shooting_menu,
  _ as ContentHubby_Hub_4x_strategy,
  _ as ContentHubby_Hub_4x_strategy_desc,
  _ as ContentHubby_Hub_action,
  _ as ContentHubby_Hub_action_and_adventure,
  _ as ContentHubby_Hub_action_and_adventure_menu,
  _ as ContentHubby_Hub_action_beat_em_up,
  _ as ContentHubby_Hub_action_beat_em_up_menu,
  _ as ContentHubby_Hub_action_dash_adventure,
  _ as ContentHubby_Hub_action_dash_adventure_menu,
  _ as ContentHubby_Hub_action_fps,
  _ as ContentHubby_Hub_action_fps_menu,
  _ as ContentHubby_Hub_action_horror,
  _ as ContentHubby_Hub_action_horror_menu,
  _ as ContentHubby_Hub_action_menu,
  _ as ContentHubby_Hub_action_rogue_like,
  _ as ContentHubby_Hub_action_rogue_like_menu,
  _ as ContentHubby_Hub_action_rpg,
  _ as ContentHubby_Hub_action_rpg_menu,
  _ as ContentHubby_Hub_action_run_jump,
  _ as ContentHubby_Hub_action_run_jump_menu,
  _ as ContentHubby_Hub_action_shooter,
  _ as ContentHubby_Hub_action_shooter_menu,
  _ as ContentHubby_Hub_action_tps,
  _ as ContentHubby_Hub_action_tps_menu,
  _ as ContentHubby_Hub_actions_activities,
  _ as ContentHubby_Hub_actions_activities_menu,
  _ as ContentHubby_Hub_adjustable_difficulty,
  _ as ContentHubby_Hub_adjustable_difficulty_desc,
  _ as ContentHubby_Hub_adjustable_text_size,
  _ as ContentHubby_Hub_adjustable_text_size_desc,
  _ as ContentHubby_Hub_adventure,
  _ as ContentHubby_Hub_adventure_and_casual,
  _ as ContentHubby_Hub_adventure_and_casual_menu,
  _ as ContentHubby_Hub_adventure_explore_open_world,
  _ as ContentHubby_Hub_adventure_explore_open_world_menu,
  _ as ContentHubby_Hub_adventure_menu,
  _ as ContentHubby_Hub_adventure_point_click,
  _ as ContentHubby_Hub_adventure_point_click_menu,
  _ as ContentHubby_Hub_adventure_rpg,
  _ as ContentHubby_Hub_adventure_rpg_casual,
  _ as ContentHubby_Hub_adventure_rpg_casual_menu,
  _ as ContentHubby_Hub_adventure_rpg_menu,
  _ as ContentHubby_Hub_aesthetic,
  _ as ContentHubby_Hub_aesthetic_menu,
  _ as ContentHubby_Hub_animals,
  _ as ContentHubby_Hub_anime_mild,
  _ as ContentHubby_Hub_anime_mild_menu,
  _ as ContentHubby_Hub_arcade,
  _ as ContentHubby_Hub_arcade_menu,
  _ as ContentHubby_Hub_arcade_rhythm,
  _ as ContentHubby_Hub_arcade_rhythm_menu,
  _ as ContentHubby_Hub_artstyles_music,
  _ as ContentHubby_Hub_artstyles_music_menu,
  _ as ContentHubby_Hub_automation,
  _ as ContentHubby_Hub_base_builder,
  _ as ContentHubby_Hub_board_games,
  _ as ContentHubby_Hub_box_pushing,
  _ as ContentHubby_Hub_bullet,
  _ as ContentHubby_Hub_bullet_desc,
  _ as ContentHubby_Hub_business_politics,
  _ as ContentHubby_Hub_business_politics_menu,
  _ as ContentHubby_Hub_camera_comfort,
  _ as ContentHubby_Hub_camera_comfort_desc,
  _ as ContentHubby_Hub_capitalism_economy,
  _ as ContentHubby_Hub_casual,
  _ as ContentHubby_Hub_casual_and_puzzle,
  _ as ContentHubby_Hub_casual_and_puzzle_menu,
  _ as ContentHubby_Hub_casual_and_story,
  _ as ContentHubby_Hub_casual_and_story_menu,
  _ as ContentHubby_Hub_casual_card_board,
  _ as ContentHubby_Hub_casual_card_board_menu,
  _ as ContentHubby_Hub_casual_menu,
  _ as ContentHubby_Hub_casual_puzzle,
  _ as ContentHubby_Hub_casual_puzzle_menu,
  _ as ContentHubby_Hub_character_action_game,
  _ as ContentHubby_Hub_chat_speech_to_text,
  _ as ContentHubby_Hub_chat_speech_to_text_desc,
  _ as ContentHubby_Hub_chat_text_to_speech,
  _ as ContentHubby_Hub_chat_text_to_speech_desc,
  _ as ContentHubby_Hub_choices_matter,
  _ as ContentHubby_Hub_choices_matter_menu,
  _ as ContentHubby_Hub_clickers_idlers,
  _ as ContentHubby_Hub_clickers_idlers_menu,
  _ as ContentHubby_Hub_color_alternatives,
  _ as ContentHubby_Hub_color_alternatives_desc,
  _ as ContentHubby_Hub_combat_pvp,
  _ as ContentHubby_Hub_contrast_controls,
  _ as ContentHubby_Hub_contrast_controls_desc,
  _ as ContentHubby_Hub_cooking,
  _ as ContentHubby_Hub_creature_collector,
  _ as ContentHubby_Hub_crime_justice,
  _ as ContentHubby_Hub_crime_justice_menu,
  _ as ContentHubby_Hub_custom_volume_controls,
  _ as ContentHubby_Hub_custom_volume_controls_desc,
  _ as ContentHubby_Hub_cute_cartoon,
  _ as ContentHubby_Hub_cute_cartoon_menu,
  _ as ContentHubby_Hub_cyberpunk,
  _ as ContentHubby_Hub_cyberpunk_desc,
  _ as ContentHubby_Hub_dating_sim,
  _ as ContentHubby_Hub_dating_sim_menu,
  _ as ContentHubby_Hub_deckbuilders,
  _ as ContentHubby_Hub_deduction,
  _ as ContentHubby_Hub_deduction_desc,
  _ as ContentHubby_Hub_detective,
  _ as ContentHubby_Hub_detective_desc,
  _ as ContentHubby_Hub_dinos_robots,
  _ as ContentHubby_Hub_driving_piloting,
  _ as ContentHubby_Hub_driving_piloting_menu,
  _ as ContentHubby_Hub_education,
  _ as ContentHubby_Hub_education_menu,
  _ as ContentHubby_Hub_endlessly_replayable,
  _ as ContentHubby_Hub_experimental,
  _ as ContentHubby_Hub_experimental_menu,
  _ as ContentHubby_Hub_exploration_open_world,
  _ as ContentHubby_Hub_exploration_open_world_menu,
  _ as ContentHubby_Hub_fantasy,
  _ as ContentHubby_Hub_fantasy_and_supernatural,
  _ as ContentHubby_Hub_fantasy_menu,
  _ as ContentHubby_Hub_fantasy_supernatural,
  _ as ContentHubby_Hub_fantasy_supernatural_menu,
  _ as ContentHubby_Hub_farming,
  _ as ContentHubby_Hub_female_protagonist,
  _ as ContentHubby_Hub_female_protagonist_menu,
  _ as ContentHubby_Hub_fighting,
  _ as ContentHubby_Hub_fighting_martial_arts,
  _ as ContentHubby_Hub_fighting_martial_arts_menu,
  _ as ContentHubby_Hub_fighting_menu,
  _ as ContentHubby_Hub_fishing,
  _ as ContentHubby_Hub_fishing_desc,
  _ as ContentHubby_Hub_free_to_play,
  _ as ContentHubby_Hub_going_rogue,
  _ as ContentHubby_Hub_greatondeck,
  _ as ContentHubby_Hub_greatonframe,
  _ as ContentHubby_Hub_hack_and_slash,
  _ as ContentHubby_Hub_hentai,
  _ as ContentHubby_Hub_hidden_object,
  _ as ContentHubby_Hub_hidden_object_menu,
  _ as ContentHubby_Hub_history,
  _ as ContentHubby_Hub_hobby_sim,
  _ as ContentHubby_Hub_hobby_sim_menu,
  _ as ContentHubby_Hub_horror,
  _ as ContentHubby_Hub_horror_dark,
  _ as ContentHubby_Hub_horror_dark_menu,
  _ as ContentHubby_Hub_horror_menu,
  _ as ContentHubby_Hub_horses,
  _ as ContentHubby_Hub_horses_desc,
  _ as ContentHubby_Hub_house_home,
  _ as ContentHubby_Hub_idle,
  _ as ContentHubby_Hub_interactive_fiction,
  _ as ContentHubby_Hub_interactive_fiction_menu,
  _ as ContentHubby_Hub_interactive_stories,
  _ as ContentHubby_Hub_interactive_stories_menu,
  _ as ContentHubby_Hub_keyboard_only_option,
  _ as ContentHubby_Hub_keyboard_only_option_desc,
  _ as ContentHubby_Hub_lgbtq,
  _ as ContentHubby_Hub_lgbtq_menu,
  _ as ContentHubby_Hub_life_sim,
  _ as ContentHubby_Hub_location_worlds,
  _ as ContentHubby_Hub_match_3,
  _ as ContentHubby_Hub_match_3_menu,
  _ as ContentHubby_Hub_mature,
  _ as ContentHubby_Hub_medieval,
  _ as ContentHubby_Hub_metroidvania,
  _ as ContentHubby_Hub_metroidvania_menu,
  _ as ContentHubby_Hub_military,
  _ as ContentHubby_Hub_military_menu,
  _ as ContentHubby_Hub_military_warfare,
  _ as ContentHubby_Hub_military_warfare_menu,
  _ as ContentHubby_Hub_minimalist_abstract,
  _ as ContentHubby_Hub_minimalist_abstract_menu,
  _ as ContentHubby_Hub_minimalist_relaxing,
  _ as ContentHubby_Hub_minimalist_relaxing_menu,
  _ as ContentHubby_Hub_mouse_only_option,
  _ as ContentHubby_Hub_mouse_only_option_desc,
  _ as ContentHubby_Hub_multiplayer,
  _ as ContentHubby_Hub_multiplayer_battle_royale,
  _ as ContentHubby_Hub_multiplayer_battle_royale_menu,
  _ as ContentHubby_Hub_multiplayer_competitive,
  _ as ContentHubby_Hub_multiplayer_competitive_menu,
  _ as ContentHubby_Hub_multiplayer_coop,
  _ as ContentHubby_Hub_multiplayer_coop_menu,
  _ as ContentHubby_Hub_multiplayer_lan,
  _ as ContentHubby_Hub_multiplayer_lan_menu,
  _ as ContentHubby_Hub_multiplayer_local_party,
  _ as ContentHubby_Hub_multiplayer_local_party_menu,
  _ as ContentHubby_Hub_multiplayer_menu,
  _ as ContentHubby_Hub_multiplayer_mmo,
  _ as ContentHubby_Hub_multiplayer_mmo_menu,
  _ as ContentHubby_Hub_multiplayer_moba_auto_battler,
  _ as ContentHubby_Hub_multiplayer_moba_auto_battler_menu,
  _ as ContentHubby_Hub_multiplayer_online_competitive,
  _ as ContentHubby_Hub_multiplayer_online_competitive_menu,
  _ as ContentHubby_Hub_multiplayer_shooter,
  _ as ContentHubby_Hub_multiplayer_shooter_menu,
  _ as ContentHubby_Hub_music_rhythm,
  _ as ContentHubby_Hub_music_rhythm_menu,
  _ as ContentHubby_Hub_mystery_detective,
  _ as ContentHubby_Hub_mystery_detective_menu,
  _ as ContentHubby_Hub_narrated_game_menus,
  _ as ContentHubby_Hub_narrated_game_menus_desc,
  _ as ContentHubby_Hub_ocean,
  _ as ContentHubby_Hub_open_world_survival_craft,
  _ as ContentHubby_Hub_open_world_survival_craft_menu,
  _ as ContentHubby_Hub_partyrpg,
  _ as ContentHubby_Hub_partyrpg_desc,
  _ as ContentHubby_Hub_people_creatures,
  _ as ContentHubby_Hub_pinsandpegs,
  _ as ContentHubby_Hub_pinsandpegs_desc,
  _ as ContentHubby_Hub_pirates_ninjas,
  _ as ContentHubby_Hub_pixel_retro,
  _ as ContentHubby_Hub_pixel_retro_menu,
  _ as ContentHubby_Hub_plane_train_autos,
  _ as ContentHubby_Hub_playable_at_your_own_pace,
  _ as ContentHubby_Hub_playable_at_your_own_pace_desc,
  _ as ContentHubby_Hub_playable_without_timed_input,
  _ as ContentHubby_Hub_playable_without_timed_input_desc,
  _ as ContentHubby_Hub_playable_without_vision,
  _ as ContentHubby_Hub_playable_without_vision_desc,
  _ as ContentHubby_Hub_players,
  _ as ContentHubby_Hub_political_sim,
  _ as ContentHubby_Hub_programming,
  _ as ContentHubby_Hub_programming_desc,
  _ as ContentHubby_Hub_psychedelic,
  _ as ContentHubby_Hub_psychedelic_menu,
  _ as ContentHubby_Hub_psychedelic_surreal,
  _ as ContentHubby_Hub_psychedelic_surreal_menu,
  _ as ContentHubby_Hub_puzzle,
  _ as ContentHubby_Hub_puzzle_difficult,
  _ as ContentHubby_Hub_puzzle_difficult_menu,
  _ as ContentHubby_Hub_puzzle_logic,
  _ as ContentHubby_Hub_puzzle_logic_menu,
  _ as ContentHubby_Hub_puzzle_matching,
  _ as ContentHubby_Hub_puzzle_matching_menu,
  _ as ContentHubby_Hub_puzzle_menu,
  _ as ContentHubby_Hub_puzzle_multiplayer,
  _ as ContentHubby_Hub_puzzle_multiplayer_menu,
  _ as ContentHubby_Hub_pvesurvival,
  _ as ContentHubby_Hub_pvesurvival_desc,
  _ as ContentHubby_Hub_racing,
  _ as ContentHubby_Hub_racing_combat,
  _ as ContentHubby_Hub_racing_combat_menu,
  _ as ContentHubby_Hub_racing_desc,
  _ as ContentHubby_Hub_racing_menu,
  _ as ContentHubby_Hub_racing_piloting,
  _ as ContentHubby_Hub_racing_piloting_menu,
  _ as ContentHubby_Hub_racing_sim,
  _ as ContentHubby_Hub_racing_sim_menu,
  _ as ContentHubby_Hub_relaxing,
  _ as ContentHubby_Hub_relaxing_animal_puzzles,
  _ as ContentHubby_Hub_relaxing_menu,
  _ as ContentHubby_Hub_retro,
  _ as ContentHubby_Hub_retro_menu,
  _ as ContentHubby_Hub_rhythm,
  _ as ContentHubby_Hub_rogue_like,
  _ as ContentHubby_Hub_rogue_like_menu,
  _ as ContentHubby_Hub_rogue_like_rogue_lite,
  _ as ContentHubby_Hub_rogue_like_rogue_lite_menu,
  _ as ContentHubby_Hub_rogue_like_turn_based,
  _ as ContentHubby_Hub_rogue_like_turn_based_menu,
  _ as ContentHubby_Hub_rpg,
  _ as ContentHubby_Hub_rpg_action,
  _ as ContentHubby_Hub_rpg_action_menu,
  _ as ContentHubby_Hub_rpg_crpg,
  _ as ContentHubby_Hub_rpg_crpg_menu,
  _ as ContentHubby_Hub_rpg_crpg_traditional_rogue_like,
  _ as ContentHubby_Hub_rpg_crpg_traditional_rogue_like_menu,
  _ as ContentHubby_Hub_rpg_dungeon_crawler,
  _ as ContentHubby_Hub_rpg_dungeon_crawler_menu,
  _ as ContentHubby_Hub_rpg_jrpg,
  _ as ContentHubby_Hub_rpg_jrpg_menu,
  _ as ContentHubby_Hub_rpg_menu,
  _ as ContentHubby_Hub_rpg_mmo,
  _ as ContentHubby_Hub_rpg_mmo_menu,
  _ as ContentHubby_Hub_rpg_party_based,
  _ as ContentHubby_Hub_rpg_party_based_menu,
  _ as ContentHubby_Hub_rpg_story,
  _ as ContentHubby_Hub_rpg_story_menu,
  _ as ContentHubby_Hub_rpg_strategy_tactics,
  _ as ContentHubby_Hub_rpg_strategy_tactics_menu,
  _ as ContentHubby_Hub_rpg_turn_based,
  _ as ContentHubby_Hub_rpg_turn_based_menu,
  _ as ContentHubby_Hub_save_anytime,
  _ as ContentHubby_Hub_save_anytime_desc,
  _ as ContentHubby_Hub_science_fiction,
  _ as ContentHubby_Hub_science_fiction_menu,
  _ as ContentHubby_Hub_scream,
  _ as ContentHubby_Hub_shmup,
  _ as ContentHubby_Hub_shooter,
  _ as ContentHubby_Hub_shooter_menu,
  _ as ContentHubby_Hub_shooters_without_zombies,
  _ as ContentHubby_Hub_sim_building,
  _ as ContentHubby_Hub_sim_building_automation,
  _ as ContentHubby_Hub_sim_building_automation_menu,
  _ as ContentHubby_Hub_sim_building_menu,
  _ as ContentHubby_Hub_sim_business_tycoon,
  _ as ContentHubby_Hub_sim_business_tycoon_menu,
  _ as ContentHubby_Hub_sim_cities_settlements,
  _ as ContentHubby_Hub_sim_cities_settlements_menu,
  _ as ContentHubby_Hub_sim_dating,
  _ as ContentHubby_Hub_sim_dating_menu,
  _ as ContentHubby_Hub_sim_farming,
  _ as ContentHubby_Hub_sim_farming_crafting,
  _ as ContentHubby_Hub_sim_farming_crafting_menu,
  _ as ContentHubby_Hub_sim_farming_menu,
  _ as ContentHubby_Hub_sim_life,
  _ as ContentHubby_Hub_sim_life_menu,
  _ as ContentHubby_Hub_sim_life_romance,
  _ as ContentHubby_Hub_sim_life_romance_menu,
  _ as ContentHubby_Hub_sim_management,
  _ as ContentHubby_Hub_sim_management_menu,
  _ as ContentHubby_Hub_sim_open_world,
  _ as ContentHubby_Hub_sim_open_world_menu,
  _ as ContentHubby_Hub_sim_physics_sandbox,
  _ as ContentHubby_Hub_sim_physics_sandbox_menu,
  _ as ContentHubby_Hub_sim_policy,
  _ as ContentHubby_Hub_sim_policy_menu,
  _ as ContentHubby_Hub_sim_sandbox_god_game,
  _ as ContentHubby_Hub_sim_sandbox_god_game_menu,
  _ as ContentHubby_Hub_sim_space_flight,
  _ as ContentHubby_Hub_sim_space_flight_menu,
  _ as ContentHubby_Hub_simulation,
  _ as ContentHubby_Hub_simulation_menu,
  _ as ContentHubby_Hub_singleplayer,
  _ as ContentHubby_Hub_singleplayer_menu,
  _ as ContentHubby_Hub_social_and_players,
  _ as ContentHubby_Hub_sokoban,
  _ as ContentHubby_Hub_sokoban_desc,
  _ as ContentHubby_Hub_space,
  _ as ContentHubby_Hub_space_exploration,
  _ as ContentHubby_Hub_space_menu,
  _ as ContentHubby_Hub_spooky,
  _ as ContentHubby_Hub_spooky_menu,
  _ as ContentHubby_Hub_sports,
  _ as ContentHubby_Hub_sports_and_racing,
  _ as ContentHubby_Hub_sports_and_racing_menu,
  _ as ContentHubby_Hub_sports_ball,
  _ as ContentHubby_Hub_sports_ball_menu,
  _ as ContentHubby_Hub_sports_combat,
  _ as ContentHubby_Hub_sports_combat_menu,
  _ as ContentHubby_Hub_sports_desc,
  _ as ContentHubby_Hub_sports_fishing_hunting,
  _ as ContentHubby_Hub_sports_fishing_hunting_menu,
  _ as ContentHubby_Hub_sports_individual,
  _ as ContentHubby_Hub_sports_individual_menu,
  _ as ContentHubby_Hub_sports_menu,
  _ as ContentHubby_Hub_sports_sim,
  _ as ContentHubby_Hub_sports_sim_menu,
  _ as ContentHubby_Hub_sports_team,
  _ as ContentHubby_Hub_sports_team_menu,
  _ as ContentHubby_Hub_sports_winter,
  _ as ContentHubby_Hub_sports_winter_menu,
  _ as ContentHubby_Hub_stealth,
  _ as ContentHubby_Hub_stereo_sound,
  _ as ContentHubby_Hub_stereo_sound_desc,
  _ as ContentHubby_Hub_story_driven,
  _ as ContentHubby_Hub_story_driven_menu,
  _ as ContentHubby_Hub_strategy,
  _ as ContentHubby_Hub_strategy_card_board,
  _ as ContentHubby_Hub_strategy_card_board_menu,
  _ as ContentHubby_Hub_strategy_cities_settlements,
  _ as ContentHubby_Hub_strategy_cities_settlements_menu,
  _ as ContentHubby_Hub_strategy_grand_4x,
  _ as ContentHubby_Hub_strategy_grand_4x_menu,
  _ as ContentHubby_Hub_strategy_menu,
  _ as ContentHubby_Hub_strategy_military,
  _ as ContentHubby_Hub_strategy_military_menu,
  _ as ContentHubby_Hub_strategy_moba_auto_battler,
  _ as ContentHubby_Hub_strategy_moba_auto_battler_menu,
  _ as ContentHubby_Hub_strategy_real_time,
  _ as ContentHubby_Hub_strategy_real_time_menu,
  _ as ContentHubby_Hub_strategy_sim_management,
  _ as ContentHubby_Hub_strategy_sim_management_menu,
  _ as ContentHubby_Hub_strategy_tactics,
  _ as ContentHubby_Hub_strategy_tactics_menu,
  _ as ContentHubby_Hub_strategy_turn_based,
  _ as ContentHubby_Hub_strategy_turn_based_menu,
  _ as ContentHubby_Hub_subtitle_options,
  _ as ContentHubby_Hub_subtitle_options_desc,
  _ as ContentHubby_Hub_surround_sound,
  _ as ContentHubby_Hub_surround_sound_desc,
  _ as ContentHubby_Hub_survival,
  _ as ContentHubby_Hub_survival_menu,
  _ as ContentHubby_Hub_survival_stealth,
  _ as ContentHubby_Hub_survival_stealth_menu,
  _ as ContentHubby_Hub_themes,
  _ as ContentHubby_Hub_themes_and_interests,
  _ as ContentHubby_Hub_themes_and_interests_menu,
  _ as ContentHubby_Hub_themes_menu,
  _ as ContentHubby_Hub_time_management,
  _ as ContentHubby_Hub_time_management_menu,
  _ as ContentHubby_Hub_touch_only_option,
  _ as ContentHubby_Hub_touch_only_option_desc,
  _ as ContentHubby_Hub_tower_defense,
  _ as ContentHubby_Hub_tower_defense_menu,
  _ as ContentHubby_Hub_trains,
  _ as ContentHubby_Hub_trains_desc,
  _ as ContentHubby_Hub_turnbased_rpg,
  _ as ContentHubby_Hub_typing,
  _ as ContentHubby_Hub_typing_desc,
  _ as ContentHubby_Hub_visual_novel,
  _ as ContentHubby_Hub_visual_novel_menu,
  _ as ContentHubby_Hub_walking_simulator,
  _ as ContentHubby_Hub_walking_simulator_menu,
  _ as ContentHubby_Hub_wargame,
  _ as ContentHubby_Hub_zombies_vampires,
  _ as ContentHubby_Menu_CurrentSpecials,
  _ as ContentHubby_Menu_NewAndNoteworthy,
  _ as Library_Install,
  _ as Library_Update_TryItNow2,
  _ as Store_VR_MainMenu_VR_Hardware,
  _ as Store_VR_MainMenu_Virtual_Reality,
  _ as additional_game_content_soundtracks,
  _ as api_category_coming_soon,
  _ as api_category_new_releases,
  _ as api_category_top_sellers,
  _ as browse_adultonly,
  _ as browse_demos,
  _ as browse_free,
  _ as browse_remoteplay,
  _ as btn_add_to_wishlist,
  _ as contenthub_title_controller,
  _ as contenthub_title_pccafe,
  _ as default,
  _ as discount_desc_limited_time,
  _ as discount_desc_limited_time_date,
  _ as discount_desc_preset_loyalty,
  _ as dummy,
  _ as games_osx,
  _ as genre_early_access,
  _ as genre_free2play,
  _ as label_back_catalogue,
  _ as label_deepest_discount,
  _ as label_early_beta_access,
  _ as label_for_a_limited_time_only,
  _ as label_free_week,
  _ as label_free_weekend,
  _ as label_highlighted_deals,
  _ as label_just_updated,
  _ as label_new_and_upcoming,
  _ as label_new_dlc_available,
  _ as label_play_free_generic,
  _ as label_play_free_until_custom,
  _ as label_pre_load_now,
  _ as language,
  _ as limitedtime_install_and_keep,
  _ as msg_action_buy,
  _ as msg_action_details,
  _ as msg_action_info,
  _ as msg_advanced_access,
  _ as msg_available_everywhere,
  _ as msg_available_just_released,
  _ as msg_available_just_released_from_early_access,
  _ as msg_available_new_release,
  _ as msg_available_now_free_to_play,
  _ as msg_available_now_ftp_early,
  _ as msg_coming_soon_to_steamos,
  _ as msg_early_access_now_available,
  _ as msg_free_play_until,
  _ as msg_free_play_weekend,
  _ as msg_free_to_play_just_updated,
  _ as msg_free_update,
  _ as msg_in_early_access,
  _ as msg_just_updated_with_free_dlc,
  _ as msg_new_content_now_available,
  _ as msg_new_game,
  _ as msg_new_update_available,
  _ as msg_now_available_for_mac_and_steamos,
  _ as msg_now_available_on_steamos,
  _ as msg_now_available_on_steamos_mac_and_linux,
  _ as msg_now_with_steam_workshop,
  _ as msg_now_with_steamworks,
  _ as msg_on_sale_now,
  _ as msg_play_beta_now,
  _ as msg_play_demo_now,
  _ as msg_play_it_now,
  _ as msg_play_now,
  _ as msg_preload_completed,
  _ as msg_preload_free,
  _ as msg_preload_now,
  _ as msg_preload_now_for_free,
  _ as msg_preload_you_have_completed,
  _ as msg_preload_you_have_pre,
  _ as msg_prepurchase_and_get_beta_access,
  _ as msg_prepurchase_and_play_beta_now,
  _ as msg_prepurchase_bonus,
  _ as msg_prepurchase_now,
  _ as msg_publisher_sale,
  _ as msg_publisher_weekend,
  _ as msg_steam_workshop_now_available,
  _ as msg_try_it_now,
  _ as msg_watch_movie_now,
  _ as msg_weekend_on_now,
  _ as msg_weekend_play_free,
  _ as msg_weekend_trial,
  _ as mst_weekend_description_free,
  _ as promo_ends_custom,
  _ as promo_giveaway,
  _ as spotlight_daily_deal,
  _ as spotlight_franchise_sale,
  _ as spotlight_major_update,
  _ as spotlight_midweek_deal,
  _ as spotlight_midweek_madness,
  _ as spotlight_thirdparty_event,
  _ as spotlight_weekend_deal,
  _ as spotlight_weeklong_header1,
  _ as spotlight_weeklong_sale,
  _ as store_tab_greatondeck,
  _ as store_tab_greatonframe,
  _ as store_tab_linux,
  _ as store_tab_software_home,
  _ as text_free_new_dlc_now_available,
  _ as text_new_free_to_play,
  _ as text_now_available,
  _ as text_now_available_mac,
  _ as text_now_available_on_pc_mac_and_linux,
  _ as text_now_available_steamplay,
  _ as text_now_free_to_play,
};
