{
	"language": "german",
	"Button_Append": "Anhängen",
	"Button_Cancel": "Abbrechen",
	"Button_Close": "Schließen",
	"Button_Clone": "Klonen",
	"Button_Confirm": "Bestätigen",
	"Button_Copy": "Kopieren",
	"Button_CopyClipboard": "In Zwischenablage kopieren",
	"Button_CopyLink": "Link kopieren",
	"Button_Continue": "Weiter",
	"Button_Create": "Erstellen",
	"Button_Delete": "Löschen",
	"Button_Discuss": "Diskutieren",
	"Button_Dismiss": "Verwerfen",
	"Button_Edit": "Bearbeiten",
	"Button_Learn": "Weitere Informationen",
	"Button_Publish": "Veröffentlichen",
	"Button_Post": "Veröffentlichen",
	"Button_OK": "OK",
	"Button_Overwrite": "Überschreiben",
	"Button_Retry": "Erneut versuchen",
	"Button_Remove": "Entfernen",
	"Button_Save": "Speichern",
	"Button_Saved": "Gespeichert",
	"Button_Share": "Teilen",
	"Button_Update": "Aktualisieren",
	"Button_SaveAndContinue": "Speichern und fortfahren",
	"Button_Follow": "Folgen",
	"Button_Followed": "Gefolgt",
	"Button_Ignore": "Ignorieren",
	"Button_Ignored": "Ignoriert",
	"Button_NotifyMe": "Mich benachrichtigen",
	"Button_NotInterested": "Kein Interesse",
	"Button_RateUp": "Positiv bewerten",
	"Button_ViewPage": "Seite anzeigen",
	"Button_Accept": "Annehmen",
	"Button_Reject": "Ablehnen",
	"ToolTip_CopyLinkToClipboard": "Link in Zwischenablage kopieren",
	"Input_Error_NumberTooSmall": "Zahl zu klein.",
	"Input_Error_NumberTooLarge": "Zahl zu groß.",
	"Input_Error_MustBeURL": "Feld ist keine gültige URL.",
	"Input_Error_MustBeEmail": "Feld ist keine gültige E-Mail.",
	"Input_Error_MustBeNumber": "Feld muss eine Zahl sein.",
	"Loading": "Ladevorgang läuft...",
	"Updating": "Wird aktualisiert...",
	"Uploading": "Wird hochgeladen…",
	"Settings": "Einstellungen",
	"FriendSettings_AlwaysNewChatWindow": "Immer ein neues Chatfenster öffnen statt eines neuen Tabs",
	"g_DisabledOnWeb": "In der Webversion nicht verfügbar",
	"VoiceTransmissionType_Disabled": "Offenes Mikrofon nur in der Webversion",
	"VoiceVolume": "Lautstärke",
	"VoiceSetupHeader": "Sprachchat einrichten und testen",
	"VoiceStartLocalMicTest": "Mikrofontest starten",
	"VoiceStopLocalMicTest": "Mikrofontest beenden",
	"VoiceWhenMicIsWorking": "Wenn Ihr Mikrofon funktioniert, sollten Sie sich selbst hören und neben Ihrem Avatar einen farbigen Balken sehen, wenn Sie sprechen.",
	"VoiceDevice": "Gerät zur Spracheingabe",
	"VoiceOutputDevice": "Sprachausgabegerät",
	"VoiceInputGain": "Eingangslautstärke/Verstärkung",
	"VoiceInputGainExplainer": "(Mein Mikrofon)",
	"VoiceOutputGain": "Ausgangslautstärke/Verstärkung",
	"VoiceOutputGainExplainer": "(Meine Freunde)",
	"VoiceTransmissionType": "Push-to-Talk",
	"VoiceTransmissionType_Label": "Art der Sprachübertragung",
	"VoiceTransmissionType_OpenMic": "Offenes Mikrofon",
	"VoiceTransmissionType_PushToTalk": "Push-to-Talk",
	"VoiceTransmissionType_PushToMute": "Push-to-Mute",
	"VoiceClearHotKeyTooltip": "Tastenzuweisung fürs Stummschalten entfernen",
	"VoiceTransmissionTypeExplainer": "Drücken Sie eine benutzerdefinierte Taste, um an Sprachchats teilzunehmen",
	"VoiceTransmissionType_WhenSpeaking": "Automatisch",
	"VoiceTransmissionType_PushToTalk_Key": "Push-to-Talk: %1$s",
	"VoicePushToTalkPressHotKey": "Zur Zuweisung eine Taste/Maustaste drücken",
	"VoicePushToTalkAssigned": "Push-to-Talk Hotkey zugewiesen als",
	"VoicePushToMuteAssigned": "Push-to-Mute-Hotkey zugewiesen als",
	"VoiceMuteToggleAssigned": "Zugewiesene Taste zum Stummschalten:",
	"VoicePushToSomethingSoundOption": "Kurzen Ton beim Umschalten des Mikrofons abspielen",
	"VoiceTransmisionThreshold": "Schwellenwert der Sprachübertragung",
	"VoiceTransmissionThresholdExplainer": "Wenn Ihr Mikrofon eingeschaltet ist, werden wir keine Geräusche unterhalb dieses Schwellenwerts übertragen:",
	"VoiceTransmissionThresholdOff": "Aus",
	"VoiceTransmissionThresholdMedium": "Mittel",
	"VoiceTransmissionThresholdHigh": "Hoch",
	"VoiceTransmissionThresholdRecommended": "Empfohlen",
	"VoiceAdvancedSettings": "Erweiterte Einstellungen",
	"VoiceShowAdvancedSettings": "Erweiterte Einstellungen anzeigen",
	"VoiceHideAdvancedSettings": "Erweiterte Einstellungen verstecken",
	"VoiceAdvancedSettingsExplainer": "(Diese Mikrofoneinstellungen werden von Ihrer Plattform oder Ihrem Browser reguliert)",
	"VoiceEchoCancellation": "Echokompensation",
	"VoiceNoiseCancellation": "Geräuschunterdrückung",
	"VoiceAutoGainControl": "Automatische Lautstärke/Verstärkungskontrolle",
	"DefaultMic": "Standard",
	"MicLoading...": "Ladevorgang läuft...",
	"DefaultOutputDevice": "Standard",
	"OutputDeviceLoading...": "Ladevorgang läuft...",
	"BreadCrumbs_AllEvents": "Alle Events",
	"BreadCrumbs_GameEvents": "Events zu %1$s",
	"CreatorHome_ThisGame": "Über dieses Spiel:",
	"CreatorHome_DevelopedBy": "Entwickler:",
	"CreatorHome_PublishedBy": "Publisher:",
	"CreatorHome_InFranchise": "Franchise:",
	"CreatorHome_Followers": "%1$s<br>Follower",
	"CreatorHome_JustFollowers": "Follower",
	"CreatorHome_Follow_tooltip": "Folgen Sie diesem Entwickler/Publisher, um per E-Mail und im Steam-Shop benachrichtigt zu werden, wenn dieser ein neues Spiel veröffentlicht. E-Mail-Benachrichtigungen können jederzeit deaktiviert werden.",
	"EventBrowse_MoreEventsTitle": "Weitere Events von %1$s",
	"EventBrowse_MoreEventsBtn": "Alle anzeigen",
	"EventBrowse_RecentUpdates": "Kürzliche Updates",
	"EventBrowse_RecentEvents": "Neueste Events & Ankündigungen",
	"EventCalendar_Title": "Steam-%1$sNews-Hub",
	"EventCalendar_FilterSubSection_EventTypeGroups": "Diese Art Beiträge anzeigen",
	"EventCalendar_FilterSubSection_GameSources": "Beiträge für diese Quellen anzeigen",
	"EventCalendar_EmptyCalendar": "Es wurden keine Beiträge gefunden. Bitte wählen Sie auf der Randleiste andere Suchkriterien aus.",
	"EventCalendar_DisabledFilter_LoginPrompt": "Bitte melden Sie sich an, um diese Kategorien zu aktivieren.",
	"EventCalendar_MainLoginPrompt": "Melden Sie sich an, um Ihren persönlichen News-Hub aufzurufen.",
	"EventCalendar_NoMoreFutureEvents": "Keine späteren Beiträge gefunden",
	"EventCalendar_NoMorePastEvents": "Keine älteren Beiträge gefunden",
	"EventCalendar_GameSearch": "Spielsuche",
	"EventCalendar_GameSearch_NoneFound": "Keine Treffer",
	"EventCalendar_GlobalCalendar_Action": "Zurück zum News-Hub",
	"EventCalendar_SpecificCalendar": "News-Hub für %2$s %1$s",
	"EventCalendar_Goto_SpecificCalendar": "Zum News-Hub für %1$s",
	"EventCalendar_SingleAppIsMuted": "Hinweis: Dieses Spiel ist versteckt und erscheint nicht in Ihrem persönlichen News-Hub.",
	"SteamLabs": "Steam Laboratorien",
	"SteamLabs_ExperimentNumber": "Experiment %1$s",
	"SteamLabs_DiscussionLink": "Zum Diskussionsforum",
	"EventCalendar_FutureEventsHint": "Scrollen Sie nach oben, um geplante Events zu sehen",
	"EventCalendar_FutureEventsHeader": "Bald verfügbar",
	"EventCalendar_LiveAndRecentEventsHeader": "Live & Neu",
	"EventCalendar_LiveNow": "jetzt live",
	"EventCalendar_TimeLeft": "Endet in %1$s",
	"EventCalendar_PostedAtTime": "Veröffentlicht am %1$s",
	"EventCalendar_StartedAtTime": "Start: %1$s",
	"EventCalendar_Upcoming": "bevorstehend",
	"EventCalendar_WillStartAtTime": "Beginnt am %1$s",
	"EventCalendar_WillStartAfterDuration": "Beginnt in %1$s",
	"EventCalendar_LaterToday": "im Laufe des Tages",
	"EventCalendar_Tomorrow": "morgen",
	"EventCalendar_ThisWeek": "diese Woche",
	"EventCalendar_ThisMonth": "diesen Monat",
	"EventCalendar_MuchLater": "viel später",
	"EventCalendar_MuteApp": "App stummschalten",
	"EventCalendar_MuteApp_Title": "%1$s stummschalten",
	"EventCalendar_Ignore": "Ignorieren",
	"EventCalendar_IgnoreApp": "%1$s ignorieren",
	"EventCalendar_IgnoreApp_ttip": "Ignorierte Titel werden Ihnen nicht empfohlen und tauchen nicht in hervorgehobenen Bereichen auf.",
	"EventCalendar_IgnoreApp_newhub": "Der News-Hub wendet Ihre Einstellungen zu ignorierten Titeln an und verhindert, dass im Shop ignorierte Spiele in Ihrer Nachrichtenzentrale erscheinen. Sie können ignorierte Spiele hier verwalten:",
	"EventCalendar_UnignoreApp": "%1$s nicht mehr ignorieren",
	"EventCalendar_UnMuteApp_Title": "%1$s wieder anzeigen",
	"EventCalendar_MuteApp_ttip": "Entfernt dieses Spiel aus Ihrem News-Hub und blockiert zukünftige Mitteilungen dazu.",
	"EventCalendar_UnMuteApp_ttip": "Das Spiel erscheint wieder in Ihrem News-Hub und Sie empfangen zukünftig Mitteilungen dazu.",
	"EventCalendar_MuteApp_details": "Verhindert, dass „%1$s“ in Ihrem News-Hub angezeigt wird, und blockiert zukünftige Meldungen dazu. Entscheidungen zu stummgeschalteten Inhalten können jederzeit durch Aufruf der folgenden Seite rückgängig gemacht werden:",
	"EventCalendar_ManageMutedApps": "Stummgeschaltete Apps verwalten",
	"EventCalendar_ManageStorePref": "Shop-Einstellungen verwalten",
	"EventCalendar_MuteApp_Unknown": "Unbekannt",
	"EVentCalendar_Hide_EventType": "Alle Beiträge vom Typ „%1$s“ ausblenden",
	"EventCalender_LastPlayed": "Zuletzt gespielt: %1$s",
	"EventCalender_Reason_recent": "Dieses Spiel wurde kürzlich gespielt.",
	"EventCalender_Reason_library": "Dieses Spiel ist in Ihrer Bibliothek",
	"EventCalender_Reason_following": "Sie folgen diesem Spiel",
	"EventCalender_Reason_wishlist": "Dieses Spiel ist auf Ihrer Wunschliste",
	"EventCalender_Reason_recommended": "Dieses Spiel wird für Sie empfohlen",
	"EventCalender_Reason_steam": "Dieser Beitrag ist von der Steam-Plattform",
	"EventCalender_Reason_topx": "Spiel ist in den Topsellern",
	"EventCalender_Hide_Reason_recent": "Beiträge von kürzlich gespielten Spielen verstecken",
	"EventCalender_Hide_Reason_library": "Beiträge zu Spielen in Ihrer Bibliothek ausblenden",
	"EventCalender_Hide_Reason_following": "Beiträge zu Spielen, denen Sie folgen, ausblenden",
	"EventCalender_Hide_Reason_wishlist": "Beträge zu Spielen auf Ihrer Wunschliste ausblenden",
	"EventCalender_Hide_Reason_recommended": "Beiträge zu Spielen, die für Sie empfohlen werden, ausblenden",
	"EventCalender_Hide_Reason_steam": "Beiträge von der Steam-Plattform ausblenden",
	"EventCalender_Hide_Reason_topx": "Beiträge von den Topsellern verstecken",
	"EventCalendar_ForceDesktopView": "Desktopansicht anfordern",
	"EventCalendar_ShowResponsiveView": "Responsive Ansicht anfordern",
	"EventCalendar_EventTypeGroup_news": "Neuigkeiten",
	"EventCalendar_EventTypeGroup_ttip_news": "Beinhaltet allgemeine Neuigkeiten, Dev-Blogs und Ankündigungen.",
	"EventCalendar_EventTypeGroup_events": "Events",
	"EventCalendar_EventTypeGroup_ttip_events": "Beinhaltet Online-/Chat- und Live-Events sowie Events im Spiel.",
	"EventCalendar_EventTypeGroup_streaming": "Livestreams",
	"EventCalendar_EventTypeGroup_ttip_streaming": "Beinhaltet Entwickler-Livestreams wie Turniere und Sitzungen zum Mitspielen.",
	"EventCalendar_EventTypeGroup_updates": "Inhaltsupdates",
	"EventCalendar_EventTypeGroup_ttip_updates": "Beinhaltet Neuigkeiten zu neuen Spielinhalten, Erweiterungen, Zusatzinhalten und Fehlerbehebungen.",
	"EventCalendar_EventTypeGroup_releases": "Neuerscheinungen",
	"EventCalendar_EventTypeGroup_ttip_releases": "Beinhaltet geplante Veröffentlichungen für neue Spiele, Betas, Saisons und Zusatzinhalte.",
	"EventCalendar_EventTypeGroup_sales": "Rabattaktionen",
	"EventCalendar_EventTypeGroup_ttip_sales": "Beinhaltet Rabatte, Promotionen und kostenlose Demoversionen.",
	"EventCalendar_GameSource_recent": "Kürzlich gespielt",
	"EventCalendar_GameSource_ttip_recent": "Beiträge zu innerhalb der letzten sechs Monate gespielten oder gekauften Spielen miteinbeziehen",
	"EventCalendar_GameSource_EventExplanation_ttip_recent": "Sie haben dieses Spiell innerhalb der letzten sechs Monate gespielt.",
	"EventCalendar_GameSource_library": "Bibliothek",
	"EventCalendar_GameSource_ttip_library": "Beiträge zu Spielen in Ihrer Bibliothek miteinbeziehen",
	"EventCalendar_GameSource_EventExplanation_ttip_library": "Dieses Spiel ist in Ihrer Bibliothek",
	"EventCalendar_GameSource_wishlist": "Wunschliste",
	"EventCalendar_GameSource_ttip_wishlist": "Beiträge zu Spielen auf Ihrer Wunschliste miteinbeziehen",
	"EventCalendar_GameSource_EventExplanation_ttip_wishlist": "Dieses Spiel ist auf Ihrer Wunschliste",
	"EventCalendar_GameSource_following": "Ich folge",
	"EventCalendar_GameSource_ttip_following": "Beiträge zu Spielen, denen Sie folgen, miteinbeziehen",
	"EventCalendar_GameSource_EventExplanation_ttip_following": "Sie folgen diesem Spiel",
	"EventCalendar_GameSource_recommended": "Empfohlen",
	"EventCalendar_GameSource_recommended_Verbose": "Empfohlenes Spiel",
	"EventCalendar_GameSource_ttip_recommended": "Beiträge zu empfohlenen Spielen miteinbeziehen",
	"EventCalendar_GameSource_EventExplanation_ttip_recommended": "Wir glauben, dieses Spiel könnte Ihnen gefallen",
	"EventCalendar_GameSource_steam": "Steam",
	"EventCalendar_GameSource_ttip_steam": "Zur Steam-Plattform veröffentlichte Beiträge einschließen",
	"EventCalendar_GameSource_topx": "Topseller",
	"EventCalendar_GameSource_ttip_topx": "Beiträge zu Spielen aus den regionalen Listen von Topsellern miteinbeziehen",
	"EventCalendar_GameSource_EventExplanation_ttip_steam": "Hierbei handelt es sich um einen Beitrag zu Steam.",
	"EventDisplay_Admin_Title": "Admin-Werkzeuge:",
	"EventDisplay_ViewInLibrary": "In Bibliothek anzeigen",
	"EventDisplay_ViewStorePage": "Shopseite anzeigen",
	"EventDisplay_ViewCommunityPage": "Communityseite anzeigen",
	"EventDisplay_CallToAction_LearnMore": "Weitere Informationen",
	"EventDisplay_CallToAction_InLibrary": "In Bibliothek",
	"EventDisplay_CallToAction_PlayNow": "Jetzt spielen",
	"EventDisplay_CallToAction_ComingSoon": "Bald verfügbar",
	"EventDisplay_CallToAction_FreeToPlay": "Kostenlos spielbar",
	"EventDisplay_Events": "Admin-Dashboard",
	"EventDisplay_SeeOldVersion": "Aktuelle Kundenversion anzeigen",
	"EventDisplay_SalesPage": "Aktionsseite anzeigen",
	"EventDisplay_StatsPage": "(nur Valve) Statistikseite",
	"EventDisplay_RightColumnTitle_Game": "Spiel",
	"EventDisplay_RightColumnTitle_Blog": "Blog",
	"EventDisplay_RightColumnTitle_DateAndTime": "Datum und Zeit",
	"EventDisplay_RightColumnTitle_EventType": "Typ",
	"EventDisplay_PostedBy": "von ",
	"EventDisplay_Reminder_SetReminder": "Erinnerung festlegen",
	"EventDisplay_Reminder_GetNotification_Via": "Benachrichtigung erhalten",
	"EventDisplay_Reminder_ViaEmail": "per E-Mail",
	"EventDisplay_Reminder_ViaMobileApp": "per Steam-Mobile-App",
	"EventDisplay_Reminder_FollowEvent": "Event folgen",
	"EventDisplay_Reminder_FollowEvent_ttip": "Folgen Sie einem Event, um bei Beginn benachrichtigt zu werden.",
	"EventDisplay_Reminder_RemindAtStart": "Wenn das Event beginnt,",
	"EventDisplay_Reminder_RemindAtStart_ttip": "erhalten Sie zum Zeitpunkt des Beginns eine Benachrichtigung von Steam.",
	"EventDisplay_Reminder_IgnoreEvent": "Event ignorieren",
	"EventDisplay_Reminder_IgnoreStop": "Erinnerungen nicht mehr empfangen",
	"EventDisplay_Reminder_IgnoreEvent_ttip": "Wenn Sie ein Event ignorieren, wird Steam dieses bei zukünftigen Vorschlägen und Empfehlungen ausschließen.",
	"EventDisplay_Reminder_FollowEvent_Error": "Fehler beim Folgen des Events",
	"EventDisplay_Reminder_FollowEvent_ErrorDesc": "Beim Ändern der Funktion \"Event folgen\" ist folgender Fehler aufgetreten:",
	"EventDisplay_Reminder_IgnoreEvent_Error": "Fehler beim Ignorieren des Events",
	"EventDisplay_Reminder_IgnoreEvent_ErrorDesc": "Beim Ändern der Funktion \"Event ignorieren\" ist folgender Fehler aufgetreten:",
	"EventDisplay_Reminder_Toast": "Steam-Popupbenachrichtigung beim Start",
	"EventDisplay_Reminder_AddToCalendar": "Zum Kalender hinzufügen",
	"EventDisplay_Reminder_AddToApple": "Zum Apple-Kalender hinzufügen",
	"EventDisplay_Reminder_AppleCalendar_Short": "Apple",
	"EventDisplay_Reminder_AddToGoogle": "Zum Google-Kalender hinzufügen",
	"EventDisplay_Reminder_GoogleCalendar_Short": "Google",
	"EventDisplay_Reminder_AddToOutlook": "Zum Outlook-Kalender hinzufügen",
	"EventDisplay_Reminder_OutlookCalendar_Short": "Outlook",
	"EventDisplay_Reminder_AddToYahoo": "Zum Yahoo-Kalender hinzufügen",
	"EventDisplay_Reminder_Preferences": "Erinnerungseinstellungen bearbeiten",
	"EventDisplay_TimeDisplay": "%1$s–%2$s",
	"EventDisplay_TimeDisplayNone": "Keine Datums- oder Zeitangaben",
	"EventDisplay_TimeBeginsOn": "Bevorstehendes Event beginnt",
	"EventDisplay_TimeBeginsOn_Past": "Hat begonnen",
	"EventDisplay_TimeBeginsOn_StartAndEnd_Past": "Voriges Event hat begonnen",
	"EventDisplay_TimeEndsOn": "Endet",
	"EventDisplay_TimeEndsOn_Past": "Beendet",
	"EventDisplay_RunsForDuration": "Dauer: %1$s",
	"EventDisplay_TimeLeft": "Endet in %1$s",
	"EventDisplay_TimeEndsOn_Ran": "Abgelaufen",
	"EventDisplay_TimeRange": "Eventzeit",
	"EventDisplay_TimeInPast": "Veröffentlicht",
	"EventDisplay_TimeUpcoming": "Event beginnt",
	"EventDisplay_EventUpcoming_WithDateAndTime": "Eventbeginn: %1$s %2$s",
	"EventDisplay_TimeEventActive": "Event läuft",
	"EventDisplay_TimeEventOnNow": "Jetzt live!",
	"EventDisplay_Share_Link": "Link: ",
	"EventDisplay_Share_OnMyStatus": "Direkt in meinem Status teilen",
	"EventDisplay_Share_OnMyStatus_Details": "Veröffentlichen Sie diesen Status im Aktivitätenfeed Ihrer Freunde. Steam wird dort die Nachricht und das unten angezeigte Vorschaubild anzeigen.",
	"EventDisplay_Share_OnMyStatus_Placeholder": "Sagen Sie etwas dazu zu Ihren Freunden...",
	"EventDisplay_Share_OnSteam": "In der Steam Community als Statusmeldung teilen",
	"EventDisplay_Share_OnFaceBook": "Auf Facebook teilen",
	"EventDisplay_Share_OnTwitter": "Auf Twitter teilen",
	"EventDisplay_Share_OnReddit": "Auf Reddit teilen",
	"EventDisplay_Share_Success": "Erfolg!",
	"EventDisplay_Share_Failure": "Folgender Fehler ist aufgetreten: ",
	"EventDisplay_Share_Announcement": "Ankündigung zu %1$s",
	"EventDisplay_Share_Event": "Event zu %1$s",
	"EventDisplay_Share_NotLoggedIn": "Nicht angemeldet",
	"EventDisplay_Share_NotLoggedIn_Description": "Sie müssen sich bei Steam anmelden, um diese Funktion verwenden zu können.",
	"EventDisplay_Share_CommentMigrationInProcess": "Die Diskussionen für dieses Event warten auf die Migration in das Eventsystem. Sie sind vorübergehend nicht verfügbar. Bitte kommen Sie später wieder.",
	"EventDisplay_Share_OpenActivityFeed": "Meinen Aktivitätenfeed öffnen",
	"EventDisplay_AreYouSure": "Möchten Sie dieses Event (%1$s) wirklich löschen? Dies kann nicht rückgängig gemacht werden.",
	"EventDisplay_AreYouSure_Visible": "Möchten Sie dieses Event (%1$s) wirklich löschen? Dies kann nicht rückgängig gemacht werden. Das Event wird innerhalb weniger Minuten von allen Orten entfernt, an denen Nutzer es finden können.",
	"EventDisplay_DeleteEvent_InProgress": "Event wird gelöscht. Bitte warten...",
	"EventDisplay_DeleteEvent_Error": "Beim Löschvorgang ist ein Fehler aufgetreten:",
	"EventDisplay_DeleteEvent_ForumTopicError": "Das Event wurde erfolgreich gelöscht. Beim Versuch, das Thema im Forum zu löschen, ist jedoch ein Fehler aufgetreten. Versuchen Sie es erneut über %1$s. Fehlerdetails:",
	"EventDisplay_DeleteEvent_Success": "Event erfolgreich gelöscht.",
	"EventDisplay_DeleteEvent_Comment": "Möchten Sie die Kommentare zu diesem Event im Diskussionsforum ebenfalls löschen?",
	"EventDisplay_SocialTitle": "Mehr über dieses Spiel",
	"EventDisplay_Sketchfab": "Sketchfab-Modell",
	"EventDisplay_SketchFab_Error_Network": "Verbindung mit Sketchfab konnte nicht hergestellt werden",
	"EventEditor_Publish_VisibleNow": "Jetzt sichtbar machen",
	"EventEditor_Publish_VisibleNow_ttip": "Dieses Event wird zum geplanten Zeitpunkt automatisch sichtbar. Mit dieser Schaltfläche können Sie das Event sofort sichtbar machen.",
	"EventEditor_Edit": "Event bearbeiten",
	"EventDisplay_DeleteEvent": "Event löschen",
	"EventReminder_InProgress": "(Beachten Sie, dass die hier angezeigten Benachrichtigungsoptionen noch nicht funktionieren.)",
	"EventReminder_NotifyByEmail": "Ich möchte per E-Mail benachrichtigt werden",
	"EventReminder_NotifyByEmail_ttip": "Steam sendet Ihnen eine E-Mail-Benachrichtigung, sobald das Event startet.",
	"EventReminder_NotifyByMobile": "Ich möchte auf meinem Mobilgerät benachrichtigt werden",
	"EventReminder_NotifyByMobile_ttip": "Steam sendet zu Eventbeginn eine Nachricht an alle Geräte, auf denen die Steam-Mobile-App installiert ist und auf denen Sie sich angemeldet haben.",
	"EventReminder_NotifyByEmail_Missing": "Bitte verifizieren Sie Ihre E-Mail-Adresse, um sich für E-Mail-Benachrichtigungen anzumelden.",
	"EventReminder_NotifyByEmail_Missing_Add": "Verifizieren Sie Ihre E-Mail-Adresse.",
	"EventReminder_NotifyByMobile_Missing": "Installieren Sie eine der Steam-Anwendungen, um sich für Benachrichtigungen auf Mobilgeräten anzumelden. ",
	"EventReminder_NotifyByMobile_Install": "Verfügbare Apps anzeigen.",
	"EventEmail_Subject_NewUpdate": "%1$s – Neues Update",
	"EventEmail_Subject_UpcomingLaunch": "%1$s – bevorstehende Veröffentlichung",
	"EventEmail_Subject_NowAvailable": "Jetzt verfügbar: %1$s",
	"EventEmail_Subject_FreeDemoAvailable": "%1$s – Kostenlose Demo jetzt verfügbar",
	"EventEmail_Subject_SpecialOffer": "Jetzt im Angebot: %1$s",
	"EventEmail_Subject_Tournament_Now": "Jetzt ansehen: Turnier %1$s",
	"EventEmail_Subject_LiveStream_Now": "Jetzt ansehen: Livestream %1$s",
	"Email_Wishlist_NewReleaseEA_Subject": "%1$s wurde im Early-Access-Status veröffentlicht!",
	"EventEmail_Button_ClickForMoreDetails": "Weitere Infos",
	"EventEmail_Button_PrepurchaseNow": "Jetzt vorbestellen!",
	"EventEmail_Button_BuyNow": "Jetzt kaufen!",
	"EventEmail_Button_PlayNow": "Jetzt spielen!",
	"EventEmail_Button_WishlistNow": "Jetzt auf die Wunschliste setzen!",
	"EventEmail_WatchNow": "Jetzt zuschauen",
	"EventEmail_Destination_Store": "Steam-Shopseite des Spiels",
	"EventEmail_Destination_Event": "Eventdetailseite",
	"EventEmail_Destination_SalesPage": "Steam-Aktionsseite",
	"EventDashBoard_SummaryStats_Admin_Title": "(Nur für Admins sichtbar)",
	"EventDashBoard_SummaryStats_Title": "Gesamtzahl eindeutiger Impressionen und Seitenaufrufe",
	"EventDashBoard_SummaryStats_Desc": "(Beta) Hierbei handelt es sich um Impressionen und Seitenaufrufe Ihrer Events und Ankündigungen durch eindeutige angemeldete Benutzer. Diese Zahlen werden nur für neue Events und Ankündigungen erfasst, die mit diesem Editor erstellt wurden.",
	"EventDashBoard_SummaryStats_Link": "Klicken Sie hier für weitere Informationen.",
	"EventDashBoard_Summary_LibraryHome_Shown": "Eventimpressionen (Hauptkapsel):",
	"EventDashBoard_Summary_LibraryHome_Read": "Seitenaufrufe eines Events zur Detailansicht:",
	"EventDashBoard_Summary_AppDetailSpotlight_Shown": "Spotlight-Banner-Impressionen:",
	"EventDashBoard_Summary_AppDetailSpotlight_Read": "Seitenaufrufe eines Spotlight-Banners zur Detailansicht:",
	"EventDashBoard_Summary_AppDetailActivity_Shown": "Eventimpressionen im Aktivitätenfeed:",
	"EventDashBoard_Summary_AppDetailActivity_Read": "Seitenaufrufe eines Events zur Detailansicht:",
	"EventDashBoard_Summary_StoreAppPage_Shown": "Eventimpressionen (Hauptkapsel):",
	"EventDashBoard_Summary_StoreAppPage_Read": "Seitenaufrufe eines Events zur Detailansicht:",
	"EventDashBoard_Summary_Community_Shown": "Impressionen der Eventzusammenfassung:",
	"EventDashBoard_Summary_Community_Read": "Seitenaufrufe der Eventzusammenfassung zur Detailansicht:",
	"EventDashBoard_Summary_NewsHub_Shown": "Impressionen des Events im News-Hub:",
	"EventDashBoard_Summary_NewsHub_Read": "Seitenaufrufe des Events zur Detailansicht:",
	"EventDashBoard_Location_LibraryHome": "Bibliotheksstartseite",
	"EventDashBoard_Location_LibraryDetail": "Produktseite in der Bibliothek",
	"EventDashBoard_Location_StoreDetail": "Shopseite des Spiels",
	"EventDashBoard_Location_CommunityDetail": "Communityhub der Anwendung",
	"EventDashBoard_Location_PopUpViews": "Seitenaufrufe von Event-Popups",
	"EventDashBoard_Location_NewsHubDetail": "News-Hub",
	"AddToWishlist": "Zur Wunschliste hinzufügen",
	"Wishlisted": "Auf Ihrer Wunschliste",
	"AddToWishlist_ttip": "Erhalten Sie eine E-Mail-Benachrichtigung, sobald Artikel von Ihrer Wunschliste zum Kauf verfügbar werden",
	"Wishlist_Error": "Fehler beim Aktualisieren der Wunschliste",
	"Wishlist_Error_Desc": "Beim Aktualisieren Ihrer Wunschliste ist ein Fehler aufgetreten. Bitte versuchen Sie es später erneut.",
	"WindowTitle_FriendsList": "Freundesliste",
	"FriendsList_OfflineTitle": "FEHLER",
	"FriendsList_OfflineOrFailure": "Freunde-Netzwerk nicht erreichbar",
	"FriendsList_OfflineDetail": "Dieser Fehler kann darauf hinweisen, dass Ihr lokales Netzwerk offline ist oder dass die Steam-Freunde-Server momentan offline sind.",
	"FriendsList_SignedOut": "Nicht bei Freunde & Chat angemeldet",
	"FriendsList_SignedOut_Detail": "Sie sind zurzeit offline. Melden Sie sich an, um auf Ihre Freundesliste und den Chat zugreifen zu können.",
	"FriendsList_OfflineMode": "Nicht bei Freunde & Chat angemeldet",
	"FriendsList_OfflineMode_Detail": "Freunde und Chat sind im Offlinemodus nicht verfügbar. Bitte melden Sie sich an, um auf Ihre Freundesliste und auf den Chat zugreifen zu können.",
	"Friends_RetryLoading": "Erneuter Verbindungsversuch",
	"Friends_SignIn": "Anmelden",
	"FriendsList_Offline_Disconnected": "Verbindung unterbrochen",
	"FriendsList_LoadingTitle": "LADEVORGANG LÄUFT",
	"FriendsList_StillLoadingSummary": "Freunde-Netzwerk wird geladen...",
	"FriendsList_StillLoadingDetail": "Steam versucht, eine Verbindung zum Freunde-Netzwerk herzustellen. Dies kann ein paar Sekunden in Anspruch nehmen.",
	"Dialog_On": "AN",
	"Dialog_Off": "AUS",
	"TimeInterval_XYears": "%1$s Jahre",
	"TimeInterval_1YearXMonths": "1 Jahr und %1$s Monate",
	"TimeInterval_1Year": "1 Jahr",
	"TimeInterval_XMonths": "%1$s Monate",
	"TimeInterval_1Month": "1 Monat",
	"TimeInterval_1MonthX": "1 Monat und %1$s Tage",
	"TimeInterval_XWeeks": "%1$s Wochen",
	"TimeInterval_1Week": "1 Woche",
	"TimeInterval_XDays": "%1$s Tage",
	"TimeInterval_1Day": "1 Tag",
	"TimeInterval_1DayXHours": "1 Tag und %1$s Stunden",
	"TimeInterval_XHours": "%1$s Stunden",
	"TimeInterval_1Hour": "1 Stunde",
	"TimeInterval_1HourXMinutes": "1 Stunde und %1$s Minuten",
	"TimeInterval_LessThanAnHour": "weniger als eine Stunde",
	"TimeInterval_XMinutes": "%1$s Minuten",
	"TimeInterval_1Minute": "1 Minute",
	"TimeInterval_LessThanAMinute": "weniger als eine Minute",
	"TimeSince_XYears": "vor %1$s Jahren",
	"TimeSince_1YearXMonths": "vor einem Jahr und %1$s Monaten",
	"TimeSince_1Year": "vor einem Jahr",
	"TimeSince_XMonths": "vor %1$s Monaten",
	"TimeSince_1Month": "vor einem Monat",
	"TimeSince_1MonthXDays": "vor einem Monat und %1$s Tagen",
	"TimeSince_XWeeks": "vor %1$s Wochen",
	"TimeSince_1Week": "vor 1 Woche",
	"TimeSince_XDays": "vor %1$s Tagen",
	"TimeSince_1Day": "vor einem Tag",
	"TimeSince_1DayXHours": "vor einem Tag und %1$s Stunden",
	"TimeSince_XHours": "vor %1$s Stunden",
	"TimeSince_1Hour": "vor einer Stunde",
	"TimeSince_1HourXMinutes": "vor einer Stunde und %1$s Minuten",
	"TimeSince_LessThanAnHour": "vor weniger als einer Stunde",
	"TimeSince_XMinutes": "vor %1$s Minuten",
	"TimeSince_1Minute": "vor einer Minute",
	"TimeSince_LessThanAMinute": "vor weniger als einer Minute",
	"TimeSince_ThisWeek": "Diese Woche",
	"Time_Today": "Heute",
	"Time_Tomorrow": "Morgen",
	"Time_Yesterday": "Gestern",
	"Time_Recent": "Kürzlich",
	"ContextMenu_Copy": "Kopieren",
	"ContextMenu_Cut": "Ausschneiden",
	"ContextMenu_Paste": "Einfügen",
	"ContextMenu_CopyLinkURL": "Link-URL kopieren",
	"ContextMenu_OpenLinkInNewWindow": "Link in neuem Fenster öffnen",
	"ContextMenu_CopyImageURL": "Bild-URL kopieren",
	"ContextMenu_OpenImageInNewWindow": "Bild in neuem Fenster öffnen",
	"Tooltip_Settings": "Einstellungen der Freundesliste bearbeiten",
	"Tooltip_VoiceSettings": "Spracheinstellungen verwalten",
	"Tooltip_SearchFriends": "Freundesliste durchsuchen",
	"Tooltip_AddFriend": "Freund hinzufügen",
	"Tooltip_FriendRequest": "%1$s eingehende Anfrage",
	"Tooltip_FriendRequest_Plural": "%1$s eingehende Anfragen",
	"Tooltip_CreateGroupChat": "Gruppenchat erstellen",
	"Tooltip_InviteToGroup": "Einen Freund in diesen Gruppenchat einladen",
	"Tooltip_InviteToGroup_Denied": "Sie haben keine Berechtigung, um Mitglieder in diese Gruppe einzuladen",
	"Tooltip_GroupChatSettings": "Einstellungen zum Gruppenchat bearbeiten",
	"Tooltip_MemberCollapse": "Mitgliederliste verbergen",
	"Tooltip_MemberExpand": "Mitgliederliste erweitern",
	"Tooltip_ChatsCollapse": "Chatliste verbergen",
	"Tooltip_ChatsExpand": "Chatliste anzeigen",
	"Tooltip_MinimizeList": "Liste minimieren",
	"Tooltip_ExpandList": "Liste ausklappen",
	"Tooltip_PinChannelList": "Kanalliste anheften",
	"Tooltip_UnpinChannelList": "Kanalliste lösen",
	"Tooltip_TextChannel": "Textchat mit Gruppenmitgliedern",
	"Tooltip_TextChannelCreate": "Neuen Textchat erstellen",
	"Tooltip_NoPermissionChannelCreate": "Sie haben keine Berechtigung, um in diesem Gruppenchat Kanäle zu erstellen.",
	"Tooltip_VoiceChannel": "Sprachchat in diesen Sprachkanälen",
	"Tooltip_VoiceChannelCreate": "Neuen Sprachkanal erstellen",
	"Tooltip_DismissVoice": "Spracheinladung ablehnen",
	"Tooltip_MicStatus_Active": "Mikrofon ist aktiv",
	"Tooltip_MicStatus_Muted": "Mikrofon ist stumm geschaltet",
	"Tooltip_RemoteMicStatus_Muted": "Nutzer hat sein Mikrofon auf stumm gestellt",
	"Tooltip_MicStatus_NoMic": "Nutzer hat kein Mikrofon angeschlossen",
	"Tooltip_RemoteOutputStatus_Muted": "Nutzer hat Audio von diesem Kanal deaktiviert",
	"Tooltip_YourMicStatus_Muted": "Ihr Mikrofon ist auf stumm gestellt",
	"Tooltip_YourOutputStatus_Muted": "Sie haben Audio von diesem Kanal deaktiviert",
	"Tooltip_VoiceControlButton_1v1_inactive": "Sprachchatanfrage senden",
	"Tooltip_VoiceControlButton_1v1_active": "Sprachkanal verlassen",
	"Tooltip_VoiceControlButton_group_create": "Sprachkanal erstellen",
	"Tooltip_VoiceControlButton_group_leave": "Sprachkanal verlassen",
	"Tooltip_VoiceControlButton_group_joinsingle": "Sprachkanal beitreten",
	"Tooltip_VoiceControlButton_group_joinmultiple": "Sprachkanal zum Beitritt auswählen",
	"LanguageTitle": "Sprache",
	"Language_english": "Englisch",
	"Language_german": "Deutsch",
	"Language_french": "Französisch",
	"Language_italian": "Italienisch",
	"Language_korean": "Koreanisch",
	"Language_spanish": "Spanisch - Spanien",
	"Language_schinese": "Chinesisch (vereinfacht)",
	"Language_tchinese": "Chinesisch (traditionell)",
	"Language_russian": "Russisch",
	"Language_thai": "Thailändisch",
	"Language_japanese": "Japanisch",
	"Language_portuguese": "Portugiesisch",
	"Language_polish": "Polnisch",
	"Language_danish": "Dänisch",
	"Language_dutch": "Niederländisch",
	"Language_finnish": "Finnisch",
	"Language_norwegian": "Norwegisch",
	"Language_swedish": "Schwedisch",
	"Language_hungarian": "Ungarisch",
	"Language_czech": "Tschechisch",
	"Language_romanian": "Rumänisch",
	"Language_turkish": "Türkisch",
	"Language_arabic": "Arabisch",
	"Language_brazilian": "Portugiesisch - Brasilien",
	"Language_bulgarian": "Bulgarisch",
	"Language_greek": "Griechisch",
	"Language_ukrainian": "Ukrainisch",
	"Language_latam": "Spanisch - Lateinamerika",
	"Language_vietnamese": "Vietnamesisch",
	"Language_koreana": "Koreanisch",
	"language_selection_english": "Englisch",
	"language_selection_spanish": "Español - España (Spanisch – Spanien)",
	"language_selection_french": "Français (Französisch)",
	"language_selection_italian": "Italiano (Italienisch)",
	"language_selection_german": "Deutsch",
	"language_selection_greek": "Ελληνικά (Griechisch)",
	"language_selection_koreana": "한국어 (Koreanisch)",
	"language_selection_korean": "한국어 (Koreanisch)",
	"language_selection_schinese": "简体中文 (Vereinfachtes Chinesisch)",
	"language_selection_tchinese": "繁體中文 (Traditionelles Chinesisch)",
	"language_selection_russian": "Русский (Russisch)",
	"language_selection_thai": "ไทย (Thailändisch)",
	"language_selection_japanese": "日本語 (Japanisch)",
	"language_selection_portuguese": "Português (Portugiesich – Portugal)",
	"language_selection_brazilian": "Português (Portugiesisch – Brasilien)",
	"language_selection_polish": "Polski (Polnisch)",
	"language_selection_danish": "Dansk (Dänisch)",
	"language_selection_dutch": "Nederlands (Niederländisch)",
	"language_selection_finnish": "Suomi (Finnisch)",
	"language_selection_norwegian": "Norsk (Norwegisch)",
	"language_selection_swedish": "Svenska (Schwedisch)",
	"language_selection_czech": "Čeština (Tschechisch)",
	"language_selection_hungarian": "Magyar (Ungarisch)",
	"language_selection_romanian": "Română (Rumänisch)",
	"language_selection_bulgarian": "Български (Bulgarisch)",
	"language_selection_pirate": "Pirate (Arr!)",
	"language_selection_turkish": "Türkçe (Türkisch)",
	"language_selection_ukrainian": "Українська (Ukrainisch)",
	"language_selection_vietnamese": "Tiếng Việt (Vietnamesisch)",
	"language_selection_arabic": "العربية (Arabisch)",
	"language_selection_spanish_mexican": "Español Mexicano (Spanisch – Mexiko)",
	"language_selection_latam": "Español Latinoamérica (Spanisch – Lateinamerika)",
	"Bbcode_Originally_Posted_By": "Ursprünglicher Beitrag von",
	"Bbcode_No_Match": "Keine Übereinstimmung zu unterstütztem BBCode",
	"Editor_Bold": "Fett",
	"Editor_Underline": "Unterstrichen",
	"Editor_Italics": "Kursiv",
	"Editor_StrikeThrough": "Durchgestrichen",
	"Editor_Link": "Link einfügen",
	"Editor_Unordered": "Ungeordnete Liste",
	"Editor_Ordered": "Geordnete Liste",
	"Editor_Header": "Kopfzeile",
	"Editor_Header2": "Kopfzeile 2",
	"Editor_Header3": "Kopfzeile 3",
	"Editor_Emoticon": "Emoticon einfügen",
	"EventEditor_ConvertHTML_Error": "Fehler beim Konvertieren von HTML",
	"EventEditor_ConvertHTML_Error_Desc": "Beim Konvertieren von HTML zu bbcode ist folgender Fehler aufgetreten: %1$s",
	"EventEditor_InsertLinkURL": "URL einfügen",
	"EventEditor_FormattingHelp_GetHelpLink": "Formatierungshilfe",
	"EventEditor_ImportHTML": "HTML importieren",
	"EventEditor_ImportFromHTML": "Import aus HTML",
	"EventEditor_ImportFromHTML_ttip": "Import aus HTML. Wandelt Ihre HTML-Datei automatisch in Steam-Formatierungs-Tags um.",
	"EventEditor_ImportFromHTML_Instruction": "Unten HTML eingeben oder einfügen.",
	"EventEditor_ImportFromHTML_PreserveNewlines": "Zeilenumbrüche beibehalten",
	"EventEditor_ImportFromHTML_PreserveNewlines_Hint": "In HTML haben Zeilenumbrüche normalerweise keine Auswirkung, aber in BBCode werden sie als leere Zeilen angezeigt. Wenn Sie die Tags <p> oder <br> verwendet haben, lassen Sie diese Option deaktiviert. Wenn Sie Blog-Software verwenden, die automatisch <br>-Tags für Zeilenumbrüche hinzufügt, empfiehlt es sich, dieses Kontrollkästchen zu markieren.",
	"EventEditor_ImportFromHTML_ConvertToBBCode": "Zu BBCode konvertieren:",
	"EventEditor_ImportFromHTML_ConversionInProgress": "Konvertierung läuft. Bitte lassen Sie das Dialogfenster geöffnet.",
	"EventEditor_ImportFromHTML_ConvertFinished": "Konvertierung abgeschlossen. Sie können das Dialogfenster schließen.",
	"EventEditor_InsertYouTube": "YouTube™-Video einfügen",
	"EventEditor_InsertYouTube_Left": "Linksbündig",
	"EventEditor_InsertYouTube_Right": "Rechtsbündig",
	"EventEditor_InsertYouTube_Full": "Gesamte Breite",
	"EventEditor_InsertYouTube_URL": "Vollständige URL",
	"EventEditor_InsertYouTube_Position": "Position",
	"EventEditor_InsertYouTube_Placholder": "YouTube™-URL eingeben",
	"EventEditor_InsertYouTube_NoURL": "Bitte geben Sie eine gültige YouTube™-URL ein.",
	"EventEditor_InsertYouTube_Summary": "Kurzbeschreibung",
	"EventEditor_InsertImage": "Bild aus Web einfügen",
	"EventEditor_InsertImage_Title": "Bild einfügen",
	"EventEditor_InsertImage_Desc": "Geben Sie die URL eines Bildes (z. B. .jpg, .gif oder .png) ein, um das Bild in Ihrem Beitrag einzubetten.",
	"EventEditor_InsertImage_URL": "Bild-URL",
	"EventEditor_InsertImage_Placeholder": "Geben Sie eine gültige URL ein",
	"EventEditor_InsertImage_Anchor": "Optional: URL öffnen, wenn das Bild angeklickt wird",
	"EventEditor_LinkDescription": "Anzuzeigender Text",
	"EventEditor_LinkURL": "URL",
	"EventEditor_YouTubeVideoTitle": "YouTube™-Video: %1$s",
	"EventEditor_YouTubeVideoViews": "Aufrufe: %1$s",
	"EventEditor_Author": "Von: %1$s",
	"EventEditor_Comments": "Kommentare",
	"EventEditor_UpVotes": "Positive Bewertungen",
	"EventEditor_DownVotes": "Negative Bewertungen",
	"Error_Message": "Fehlermeldung",
	"Warning_Message": "Warnung",
	"Informational_Message": "Infonachricht",
	"Error_Description": "Fehler (Code: %1$s) Details: (%2$s)",
	"Error_FailureNotice": "Fehler",
	"Error_GenericFailureDescription": "Entschuldigung, das hat nicht funktioniert.",
	"Image_ErrorTitle": "Bild „%1$s“ konnte nicht geladen werden. Mögliche Fehlerursachen:",
	"Image_Error_msg1": "Überprüfen Sie bitte, ob der Bildpfad korrekt ist.",
	"Image_Error_msg2": "Überprüfen Sie bitte, ob der Server, auf dem das Bild liegt, anonyme Zugriffe erlaubt. Die Konsole des Browsers zeigt sonst einen Fehler vom Typ „Access-Control-Allow-Origin“ an.",
	"Image_Error_suggestion": "Sie können das Bild stets zur freien Verfügung auf Steam hochladen.",
	"Platform_Hint_Mobile": "auf Mobilgeräten",
	"Platform_Hint_BigPicture": "im Big-Picture-Modus",
	"Platform_Hint_VR": "in Virtueller Realität",
	"Hover_SteamLevel": "Steam-Level",
	"Hover_BadgeXP": "%1$s EP",
	"PersonaStateOffline": "Offline",
	"PersonaStateAway": "Abwesend",
	"PersonaStateOnline": "Online",
	"PersonaStateBlocked": "Blockiert",
	"PersonaStateInGame": "Im Spiel",
	"PersonaStateBusy": "Beschäftigt",
	"PersonaStateSnooze": "Abwesend",
	"PersonaStateInNonSteamGame": "In Steam-fremdem Spiel",
	"PersonaStateWatchingBroadcast": "Schaut Übertragung:",
	"PersonaStateLookingToTrade": "Möchte handeln",
	"PersonaStateLookingToPlay": "Möchte spielen",
	"PersonaStateLastSeen": "Zuletzt online: %1$s",
	"PersonaStateLastSeen_JustNow": "Zuletzt online: gerade eben",
	"PersonaStateRemotePlayTogether": "Remote Play Together",
	"User_WantsToPlay": "Beitreten",
	"User_ToggleDoNotDisturb": "Bitte nicht stören",
	"User_GameInfoHidden": "Ihr Spielstatus ist aufgrund Ihrer Privatsphäreeinstellungen vor Ihren Freunden verborgen.",
	"User_LimitedAccount": "Ihr Account erfüllt nicht die Bedingungen zur Nutzung dieser Funktion. Weitere Informationen: %1$s",
	"User_LimitedAccount_UrlInfo": "Zum Steam-Support",
	"isNickname": "Ihr Spitzname für diesen Freund",
	"Friend_Menu_NotAFriendLabel": "Nicht befreundet",
	"Friend_Menu_NotAFriendRequesting": "Freundschaftsanfrage",
	"DASHPlayerStats_BytesReceived": "Bytes erhalten:",
	"DASHPlayerStats_BufferingResolution": "Buffer-Auflösung:",
	"DASHPlayerStats_PlaybackResolution": "Wiedergabeauflösung:",
	"DASHPlayerStats_HtmlResolution": "Bildschirmauflösung:",
	"DASHPlayerStats_DroppedFrames": "Frame-Drops:",
	"DASHPlayerStats_VideoBuffered": "Videopufferung:",
	"DASHPlayerStats_AudioBuffered": "Audiopufferung:",
	"DASHPlayerStats_BandwidthRequired": "Benötigte Bandbreite (Mbit/s):",
	"DASHPlayerStats_BandwidthVideo": "Video-Bandbreite (MBit/s):",
	"DASHPlayerStats_BandwidthNums": "Bandbreite – Min./Max./Durchschnitt (Mbit/s):",
	"DASHPlayerStats_DownloadNums": "DL-Zeiten – Min./Max./Durchschnitt (Sek.):",
	"DASHPlayerStats_ContentServer": "Host:",
	"DASHPlayerStats_ActiveDownloads": "Aktive Downloads:",
	"DASHPlayerStats_StallEvents": "Verzögerungen:",
	"DASHPlayerStats_FailedDownloads": "Fehlgeschlagene Downloads:",
	"DASHPlayerStats_VideoDownloadProgress": "Fortschritt des Videodownloads:",
	"DASHPlayerStats_TimeToFirstFrame": "Zeit zum ersten Bild (in ms):",
	"DASHPlayerStats_DroppingFrames": "Anhaltende Frame-Drops erkannt:",
	"DASHPlayerStats_CurrentFPS": "Derzeitige FPS:",
	"DASHPlayerStats_Tracking": "Daten werden gesammelt...",
	"DASHPlayerStats_PlaybackRate": "Wiedergabegeschwindigkeit:",
	"DASHPlayerStats_VideoBufferRange": "Videopufferung %1$s:",
	"DASHPlayerStats_AudioBufferRange": "Audiopufferung %1$s:",
	"DASHPlayerStats_VideoNoRangeInformation": "Keine gepufferten Videosegmente",
	"DASHPlayerStats_AudioNoRangeInformation": "Keine gepufferten Audiosegmente",
	"DASHPlayerControls_GoLive": "Zu Live springen",
	"DASHPlayerControls_IsLive": "Live",
	"DASHPlayerControls_ClickToPlay": "Zum Abspielen klicken",
	"DASHPlayerControls_IsReplay": "WIEDERHOLUNG",
	"DASHPlayerControls_Start": "Start",
	"DASHPlayerControls_End": "Ende",
	"Played_Minutes": "%1$s Minuten",
	"Played_Hours": "%1$s Stunden",
	"WriteReview_Dialog_PostReview": "Review veröffentlichen",
	"WriteReview_Dialog_ReviseReview": "Review überarbeiten",
	"WriteReview_Dialog_Title": "Review",
	"WriteReview_Dialog_Playtime": "Spielzeit: %1$s",
	"WriteReview_Dialog_Playtime_Software": "Sie haben diesen Titel für %1$s gespielt.",
	"WriteReview_Dialog_Playtime_Revise": "Ihre zusätzliche Spielzeit: %1$s",
	"WriteReview_Dialog_RecommendGame": "Würden Sie dieses Spiel anderen Spielern empfehlen?",
	"WriteReview_Dialog_RecommendGame_Software": "Würden Sie diese Software anderen Spielern empfehlen?",
	"WriteReview_Dialog_RecommendGame_Revise": "Möchten Sie Ihre Review überarbeiten?",
	"WriteReview_Dialog_GetHelp_Btn": "Hilfe zu diesem Kauf",
	"WriteReview_Dialog_Visibility": "Sichtbarkeit:",
	"WriteReview_Dialog_Public": "Öffentlich",
	"WriteReview_Dialog_Friends": "Nur Freunde",
	"WriteReview_Dialog_Yes": "Ja",
	"WriteReview_Dialog_No": "Nein",
	"WriteReview_Dialog_GetSupport_Btn": "Hilfe zu diesem Kauf",
	"WriteReview_Dialog_GetSupport_Desc": "Erhalten Sie technische Hilfe, offiziellen Support oder beantragen Sie eine Rückerstattung.",
	"WriteReview_Dialog_AddReview_Btn": "Review verfassen",
	"WriteReview_Dialog_AddReview_Desc": "Teilen Sie Ihre Gedanken mit anderen Spielern.",
	"WriteReview_Dialog_AddReview_Header": "Möchten Sie ein Review verfassen?",
	"WriteReview_Dialog_ReviewInstructions_Link": "Regeln und Richtlinien",
	"WriteReview_Dialog_ReviewInstructions": "Bitte beschreiben Sie, was Ihnen an diesem Produkt gefällt oder nicht gefällt und ob Sie es Anderen empfehlen. Bitte denken Sie daran, höflich zu bleiben und die %1$s zu befolgen. Um eine Empfehlung zu veröffentlichen, ist eine Beschreibung erforderlich.",
	"WriteReview_Dialog_AllowComments": "Kommentare zulassen",
	"WriteReview_Dialog_FreeDisclaimer": "Markieren Sie dieses Kästchen, wenn Sie das Produkt kostenlos erhalten haben.",
	"WriteReview_Dialog_FreeDisclaimer_Tooltip": "Markieren Sie dieses Kästchen, wenn Sie das Produkt kostenlos erhalten haben. Neben Ihrem Review wird „Produkt kostenlos erhalten“ angezeigt. Wenn Sie zusätzliche Kompensation für das Verfassen eines Reviews zu diesem Spiel erhalten haben, müssen Sie dies im Text Ihres Reviews angeben.",
	"WriteReview_Dialog_FormattingHelp": "Formatierungshilfe",
	"WriteReview_Dialog_GenericError": "Beim Veröffentlichen Ihres Reviews ist ein Fehler aufgetreten. Bitte versuchen Sie es später erneut.",
	"WriteReview_Dialog_NoTextError": "Bitte beschreiben Sie, was Ihnen an diesem Produkt gefällt oder nicht gefällt.",
	"WriteReview_Dialog_Delay": "Später vielleicht",
	"Broadcast_View_Stack_H": "Horizontale Ansicht",
	"Broadcast_View_Stack_V": "Vertikale Ansicht",
	"Broadcast_View_Theater": "Kinomodus",
	"Broadcast_View_Fullscreen": "Vollbild",
	"Broadcast_View_HideChat": "Chat ausblenden",
	"Broadcast_View_ShowBothChats": "Beide Chats anzeigen",
	"Broadcast_View_ShowSingleChats": "Nur einen Chat anzeigen",
	"Broadcast_View_ShowChat": "Chat anzeigen",
	"Broadcast_Store_FreeToPlay": "Kostenlos spielbar",
	"PartnerEvent_1": "Anderes Event",
	"PartnerEvent_2": "Spielevent",
	"PartnerEvent_3": "Party-Event",
	"PartnerEvent_4": "Live-Treffen",
	"PartnerEvent_5": "Besonderer Anlass",
	"PartnerEvent_6": "Musik- und Kunst-Event",
	"PartnerEvent_7": "Sport-Event",
	"PartnerEvent_8": "Live-Veranstaltungs-Event",
	"PartnerEvent_9": "Chat",
	"PartnerEvent_9_editor": "Eine Chat- oder AMA-Sitzung",
	"PartnerEvent_10": "Neues Spiel",
	"PartnerEvent_10_editor": "Spiel ist jetzt verfügbar!",
	"PartnerEvent_11": "Livestream / Übertragung",
	"PartnerEvent_12": "Kleine Updates (Patchnotizen)",
	"PartnerEvent_13": "Reguläres Update",
	"PartnerEvent_14": "Großes Update",
	"PartnerEvent_15": "Neue Zusatzinhalte",
	"PartnerEvent_16": "Bevorstehende Veröffentlichung",
	"PartnerEvent_16_editor": "Spiel wird zu einem bestimmten Datum veröffentlicht",
	"PartnerEvent_17": "E-Sport-Turnierübertragung",
	"PartnerEvent_18": "Entwicklerstream",
	"PartnerEvent_19": "Berühmte Übertragung",
	"PartnerEvent_20": "Spielrabatt",
	"PartnerEvent_20_editor": "Rabatt auf dieses Spiel",
	"PartnerEvent_21": "Rabatt auf einen Gegenstand oder Zusatzinhalt",
	"PartnerEvent_21_editor": "Rabatt auf spielinterne Gegenstände oder Zusatzinhalte",
	"PartnerEvent_22": "Bonus-EP",
	"PartnerEvent_23": "Beuteevent",
	"PartnerEvent_24": "Extras",
	"PartnerEvent_25": "Herausforderung",
	"PartnerEvent_26": "Wettbewerb",
	"PartnerEvent_27": "Reale Veranstaltung",
	"PartnerEvent_27_editor": "Besuch von Ausstellung, Messe oder Treffen",
	"PartnerEvent_28": "Neuigkeiten",
	"PartnerEvent_28_editor": "Ankündigung/Neuigkeiten",
	"PartnerEvent_29": "Beta-Veröffentlichung",
	"PartnerEvent_29_editor": "Einladung/Neuigkeiten zur Beta",
	"PartnerEvent_30": "Neue Spielinhalte",
	"PartnerEvent_31": "Kostenlose Testversion",
	"PartnerEvent_32": "Veröffentlichung eines Saison- oder Schlachtenpasses",
	"PartnerEvent_33": "Saison-Update",
	"PartnerEvent_34": "Übergreifende Aktion",
	"PartnerEvent_35": "Allgemeines Event im Spiel",
	"PartnerEvent_Other": "Andere Veranstaltung",
	"PartnerEvent_SteamAwardNominations": "Wir bitten um Ihre Nominierungen für die Steam-Awards",
	"PartnerEvent_SteamAwardVoteRequest": "Abstimmungsaufforderung für die Steam-Awards",
	"SocialMedia_Type_ShortName_1": "Steam",
	"SocialMedia_Type_ShortName_2": "Google",
	"SocialMedia_Type_ShortName_3": "Facebook",
	"SocialMedia_Type_ShortName_4": "Twitter",
	"SocialMedia_Type_ShortName_5": "Twitch",
	"SocialMedia_Type_ShortName_6": "YouTube",
	"SocialMedia_Type_ShortName_7": "Facebook",
	"MobileLogin_NoSteamAccount": "Sie haben keinen Steam-Account?",
	"MobileLogin_CreateAccount": "Kostenlosen Account erstellen",
	"MobileLogin_ForgotPassword": "Passwort oder Accountnamen vergessen?",
	"MobileLogin_RefreshCaptcha": "Aktualisieren",
	"MobileLogin_SignIn": "Anmelden",
	"MobileLogin_SigningIn": "Anmeldung",
	"MobileLogin_AccountName": "Steam-Accountname",
	"MobileLogin_Password": "Passwort",
	"MobileLogin_CaptchaVerification": "Verifizierung",
	"MobileLogin_Enter2FA": "Geben Sie den Steam-Guard-Code aus Ihrer Steam-Mobile-App ein.",
	"MobileLogin_Enter2FAHelp": "Ich kann nicht auf meinen Steam-Guard-Code zugreifen.",
	"MobileLogin_EnterSteamguard": "Ich habe keine E-Mail mit einem Steam-Guard-Code erhalten.",
	"MobileLogin_SteamguardCode": "Steam-Guard-Code",
	"MobileLogin_SteamguardSubmit": "Absenden & anmelden",
	"MobileLogin_SentSteamguard_1": "Wir haben eine Nachricht an Ihre",
	"MobileLogin_SentSteamguard_2": "E-Mail-Adresse gesendet. Bitte geben Sie den darin angegebenen Steam-Guard-Code ein.",
	"MobileLogin_IncorrectSteamGuard": "Der eingegebene Steam-Guard-Code ist nicht korrekt. Bitte überprüfen Sie den Code und versuchen Sie es erneut.",
	"MobileLogin_Error_RateLimitExceeded": "Es gab von Ihrem Netzwerk aus zu viele fehlgeschlagene Anmeldeversuche in kurzer Zeit. Bitte warten Sie eine Weile und versuchen Sie es dann erneut.",
	"Login_SignIn": "Anmelden",
	"Login_SigningIn": "Anmeldung",
	"Login_AccountName": "Steam-Accountname",
	"Login_Password": "Passwort",
	"Login_RememberMe": "Auf diesem Computer merken",
	"Login_ForgotPassword": "Passwort oder Accountnamen vergessen?",
	"Login_NoSteamAccount": "Sie haben keinen Steam-Account?",
	"Login_CreateAccount": "Kostenlosen Account erstellen",
	"Login_CaptchaVerification": "Bitte geben Sie die Captcha-Zeichen erneut ein, um zu beweisen, dass Sie ein Mensch sind.",
	"Login_RefreshCaptcha": "Aktualisieren",
	"Login_Enter2FA": "Geben Sie den Steam-Guard-Code aus Ihrer Steam-Mobile-App ein.",
	"Login_Enter2FAHelp": "Ich kann nicht auf meinen Steam-Guard-Code zugreifen.",
	"Login_EnterSteamguard": "Ich habe keine E-Mail mit einem Steam-Guard-Code erhalten.",
	"Login_SteamguardSubmit": "Absenden & anmelden",
	"Login_SentSteamguard": "Wir haben Ihnen eine Nachricht an die folgende E-Mail-Adresse gesendet: %1$s. Bitte geben Sie den gesendeten Steam-Guard-Code ein.",
	"Login_SignOut": "Abmelden",
	"Emoticon_Search": "Emoticons durchsuchen",
	"Chat_Settings_Error_ChatFileTooLarge": "%1$s ist zu groß. (max. 10 MB)",
	"Chat_Settings_Error_ChatFileTypeNotSupported": "%1$s kann nicht hochgeladen werden. Nur die folgenden Dateitypen werden unterstützt: jpg, png, gif, webm, mpg und ogv.",
	"ConnectionTrouble_FailedToConnect": "Verbindungsaufbau zu Steam fehlgeschlagen",
	"Chat_Upload_ErrorCloud": "Bildupload zum Cloudserver fehlgeschlagen.",
	"Chat_Settings_Error_ServerError": "Ein Serverfehler ist aufgetreten",
	"Broadcast_ViewerCount": "%1$s Zuschauer",
	"Broadcast_VideoContext_ToggleStats": "Technische Daten ein-/ausblenden",
	"Broadcast_VideoContext_OpenStore": "Zum Shop",
	"Broadcast_None": "Keine",
	"BroadcastWatch_MinBrowser": "Sie können diese Übertragung nicht ansehen, weil Ihr Webbrowser die minimalen Anforderungen nicht unterstützt.",
	"BroadcastWatch_RequestFailed": "Fehler beim Laden dieser Übertragung",
	"BroadcastWatch_NotAvailable": "Die Übertragung dieses Nutzers ist offline.",
	"BroadcastWatch_WaitingForResponse": "Warten auf Annahme der Anfrage",
	"BroadcastWatch_WaitingForStart": "Übertragung startet…",
	"BroadcastWatch_WaitingForReconnect": "Verbindung wird wiederhergestellt…",
	"BroadcastWatch_ServerLoad": "Die Übertragungsserver von Steam sind zurzeit stark ausgelastet und können leider keinen weiteren Zuschauerplatz reservieren. Bitte versuchen Sie es in ein paar Minuten erneut.",
	"BroadcastWatch_SystemNotSupported": "Das System dieses Übertragenden unterstützt derzeit keine Steam-Übertragungen.",
	"BroadcastWatch_UserRestricted": "Dieser Nutzer ist zurzeit nicht berechtigt, Steam-Übertragungen zu starten.",
	"BroadcastWatch_PoorUploadQuality": "Dieser Nutzer kann zurzeit keine stabile Verbindung zu den Übertragungsservern von Steam aufbauen.",
	"BroadcastChat_Reconnected": "Mit Chat wieder verbunden",
	"BroadcastChat_UnableToJoinChat": "Wiederverbinden mit Chat nicht möglich",
	"BroadcastChat_NeverTell": "Verraten Sie niemals jemandem Ihr Passwort",
	"BroadcastChat_EnterResponse": "Nachricht eingeben",
	"BroadcastChat_InsertEmoticon": "Emoticon einfügen",
	"BroadcastChat_Send": "Senden",
	"BroadcastChat_UserJoined": "%1$s nimmt jetzt am Chat teil",
	"BroadcastChat_UserLeft": "%1$s hat den Chat verlassen",
	"BroadcastChat_UserMuted": "%1$s wurde in diesem Chat stummgeschaltet",
	"BroadcastChat_UserMutedLocal": "%1$s wurde stummgeschaltet",
	"BroadcastChat_UserUnmutedLocal": "%1$s wurde lautgeschaltet",
	"BroadcastChat_UserMuteFailed": "Fehler beim Stummschalten von %1$s. Bitte versuchen Sie es erneut.",
	"BroadcastChat_RemoveMessagesFailed": "Fehler beim Entfernen der Nachrichten für %1$s. Bitte versuchen Sie es erneut.",
	"BroadcastChat_UserUnmuteFailed": "Fehler beim Lautschalten von %1$s. Bitte versuchen Sie es erneut.",
	"BroadcastChat_YouMuted": "Sie wurden stummgeschaltet und können keine Nachrichten an diesen Chat senden",
	"BroadcastChat_FailedToSendMsg": "Fehler beim Senden der Chatnachricht: %1$s",
	"BroadcastChat_Cooldown": "Sie senden zu viele Nachrichten in kurzer Zeit. Bitte versuchen Sie es in %1$s Sekunden erneut.",
	"BroadcastChat_Mute": "Stummschalten",
	"BroadcastChat_Unmute": "Lautschalten",
	"BroadcastChat_MuteLocal": "Lokal stummschalten",
	"BroadcastChat_UnmuteLocal": "Lokale Stummschaltung aufheben",
	"BroadcastChat_Login": "Anmelden, um Chat beizutreten",
	"BroadcastChat_LimitedUser": "Begrenzter Chatzugriff",
	"BroadcastChat_RemoveMessages": "Nachrichten dieses Benutzers entfernen",
	"BroadcastChat_Blocked": "Während dieser Übertragung können nur Spielbesitzer Chatnachrichten senden.",
	"BroadcastChat_half_Mute": "Nutzer für 12 Stunden stummschalten",
	"BroadcastChat_day_Mute": "Nutzer für einen Tag stummschalten",
	"BroadcastChat_week_Mute": "Nutzer für eine Woche stummschalten",
	"BroadcastChat_perm_Mute": "Nutzer dauerhaft stummschalten",
	"BroadcastChat_half_Shadow": "Nutzer heimlich für 12 Stunden stummschalten",
	"BroadcastChat_day_Shadow": "Nutzer heimlich für einen Tag stummschalten",
	"BroadcastChat_week_Shadow": "Nutzer heimlich für eine Woche stummschalten",
	"BroadcastChat_perm_Shadow": "Nutzer heimlich dauerhaft stummschalten",
	"BroadcastChat_Add_Moderator": "Diesen Nutzer zum Moderator machen",
	"BroadcastChat_Remove_Moderator": "Moderatorstatus des Nutzers aufheben",
	"BroadcastChat_Change_Moderator_Title": "Moderatorstatus des Nutzers ändern",
	"BroadcastChat_Change_Add_Confirm": "Sind Sie sicher, dass Sie den folgenden Nutzer als Moderator hinzufügen möchten? Moderatoren können andere Nutzer im Übertragungschat stummschalten.",
	"BroadcastChat_Change_Remove_Confirm": "Sind Sie sicher, dass Sie den folgenden Nutzer als Moderator entfernen möchten?",
	"BroadcastChat_Tooltip_Show_Chat_Viewers": "Liste aller Leute anzeigen, die sich derzeit im Chatfenster befinden.",
	"BroadcastChat_Tooltip_Minimize_Chat": "Chatfenster minimieren",
	"BroadcastChat_Tooltip_Maximize_Chat": "Chatfenster maximieren",
	"BroadcastChat_Tooltip_Popout_Chat": "Chat in neuem Fenster öffnen",
	"BroadcastChat_ChatOnly_Title": "Nur Übertragungschat",
	"BroadcastChat_DefaultMessage": "Willkommen im Chat!",
	"BroadcastChat_Moderator": "Moderator",
	"BroadcastChat_Broadcaster": "Ausstrahlender",
	"ChatEntryButton_Submit": "Senden",
	"ChatEntryButton_Emoticon": "Emoticonauswahl",
	"ChatEntryButton_Flair": "Flairauswahl",
	"ChatEntryButton_SendEmbed": "Sonstiges senden",
	"Store_AddToCart": "In den Warenkorb",
	"YouTubePlayer_Loading": "YouTube wird geladen …",
	"home_page_live_broadcast": "Live",
	"StoreBroadcast_Hide_Tooltip": "Liveübertragung anzeigen/ausblenden",
	"StoreBroadcast_Detault_popout_Title": "Übertragung läuft",
	"StoreBroadcast_close_broadcast_popup": "Schließt die Übertragungsmeldung und wird diese während der laufenden Sitzung nicht wieder anzeigen.",
	"StoreBroadcast_Change_store_Broadcast_settings": "Übertragungseinstellungen bearbeiten",
	"Broadcast_Embedded_viewer": "%1$s Zuschauer",
	"Broadcast_Embedded_viewer_Plural": "%1$s Zuschauer",
	"BroadcastWatch_View_Broadcast_Page": "Übertragungsseite anzeigen",
	"Broadcast_Embed_Watch_SteamTV": "Auf Steam.tv ansehen",
	"Broadcast_Embed_Watch_With_Frieds_SteamTV": "Auf Steam.tv mit Freunden zuschauen und chatten",
	"sale_three_section_hide_chat": "Chat ausblenden",
	"sale_three_section_show_chat": "Chat anzeigen",
	"btn_live_streams_all": "Alle anzeigen",
	"Broadcast_default_title_dev": "Aktive Übertragung: Schauen Sie dem Entwickler beim Spielen zu",
	"Broadcast_default_title_community": "Aktive Übertragung: Schauen Sie der Community beim Spielen zu",
	"Broadcast_default_title_comp": "Aktive Übertragung: Schauen Sie sich dieses Wettkampfspiel an",
	"Broadcast_default_title_speed": "Aktive Übertragung: Schauen Sie diesem Speedrun zu",
	"Sale_BundleSave": "Beinhaltet %1$s Gegenstände.",
	"Sale_PackageSave": "Beinhaltet %1$s Gegenstände.",
	"Sale_ShowContents": "Inhalte anzeigen",
	"Sale_ShowMore": "Mehr anzeigen",
	"Sale_ShowLess": "Weniger anzeigen",
	"Sale_OnWishlist": "Auf der Wunschliste",
	"Sale_InLibrary": "In Bibliothek",
	"Sale_HiddenItems": "%1$s Artikel wurden aufgrund von %2$s versteckt",
	"Sale_HiddenItem_Single": "%1$s Artikel wurde aufgrund von %2$s versteckt",
	"Sale_StorePreferences": "Ihre Shopeinstellungen",
	"Sale_SeeAllSpecials": "Alle Angebote anzeigen",
	"Sale_AddToWishlist": "Zur Wunschliste hinzufügen",
	"Sale_RemoveFromWishlist": "Von der Wunschliste entfernen",
	"Sale_Preferences": "Einstellungen",
	"Sale_PlaceHolder": "Vorschaumodus: Dieser Abschnitt verfügt über keine Kapseln und erscheint nicht auf der Nutzerseite, wenn er leer ist.",
	"Sale_SmartPlaceHolder": "Vorschaumodus: Dieser Smart-Abschnitt verfügt über keine Anwendungen und erscheint nicht auf der Nutzerseite, wenn er leer ist.",
	"Sale_default_label": "(kein Titel)",
	"Sale_default_label_OnSale": "Im Angebot",
	"Sale_default_label_TopSellers": "Topseller",
	"Sale_default_label_FreeToPlay": "Kostenlos spielbar",
	"Sale_default_label_HorrorGames": "Horrorspiele",
	"Sale_default_label_HorrorVR": "Horror-VR-Spiele",
	"Sale_default_label_HorrorFreeToPlay": "Kostenlose Horrorspiele",
	"Sale_default_label_HalloweenEventsHorror": "Halloween-Events in Horrorspielen",
	"Sale_default_label_HalloweenEventsNonHorror": "Halloween-Events in Spielen anderer Genres (kein Horror)",
	"Sale_default_label_MoreHalloweenEvents": "Weitere Halloween-Events",
	"Sale_default_label_MoreHalloweenEventsNonHorror": "Weitere Halloween-Events in Spielen anderer Genres (kein Horror)",
	"Sale_default_label_NewAndUpcomingHorror": "Neue und bevorstehende Horrortitel",
	"Sale_default_label_RemotePlay_Together": "Play Together: Spielen Sie mit Freunden",
	"Sale_default_label_RemotePlay_Phone": "Play Anywhere: Spielen Sie auf Ihrem Smartphone",
	"Sale_default_label_RemotePlay_Tablet": "Play Anywhere: Spielen Sie auf Ihrem Tablet",
	"Sale_default_label_RemotePlay_TV": "Play Anywhere: Spielen Sie auf Ihrem Fernseher",
	"Sale_default_label_OnYourWishlist": "Auf Ihrer Wunschliste",
	"Sale_default_label_RecommendedForYou": "Für Sie empfohlen",
	"Sale_default_label_ComingSoon": "Bald verfügbar",
	"Sale_default_label_JustAnnounced": "Gerade angekündigt",
	"Sale_default_label_JustUpdated": "Gerade aktualisiert",
	"Sale_default_label_FreeWeekend": "Gratiswochenende",
	"Sale_default_label_FreeWeek": "Gratiswoche",
	"Sale_default_label_PrePurchase": "Jetzt vorbestellen",
	"Sale_default_label_NewReleases": "Neuerscheinungen",
	"Sale_default_label_JustReleased": "Gerade veröffentlicht",
	"Sale_default_label_Highlighted": "Angebote im Rampenlicht",
	"Sale_default_label_BackCat": "Back-Katalog",
	"Sale_default_label_PlayForFree": "Kostenlos spielen!",
	"Sale_defautl_label_FreeToKeep": "Nur für kurze Zeit: jetzt installieren und für immer behalten",
	"SalePage_LoginPrompt": "Melden Sie sich an, um sich Ihre weiteren Empfehlungen anzusehen.",
	"SalePage_ParentApp_DLC": "DLC für",
	"SalePage_ParentApp_SoundTrack": "Soundtrack für",
	"SalePage_WatchForDrop_Minutes_Developer": "Sehen Sie sich den Stream für %1$s Minuten an und erhalten Sie am Ende des Events vom Entwickler Gewinne!",
	"SalePage_WatchForDrop_Minutes_CreatorNamed": "Sehen Sie sich den Stream für %1$s Minuten an und erhalten Sie am Ende des Events von %2$s Gewinne!",
	"SalePage_WatchForDrop_Hours_Developer": "Sehen Sie sich den Stream für %1$s Stunden an und erhalten Sie am Ende des Events vom Entwickler Gewinne!",
	"SalePage_WatchForDrop_Hours_CreatorNamed": "Sehen Sie sich den Stream für %1$s Stunden an und erhalten Sie am Ende des Events von %2$s Gewinne!",
	"SalePage_WatchForDrop_LearnMore": "Weitere Informationen zu den Gewinnen finden Sie hier.",
	"SalePage_Admin_SaleEventDay": "Aktionstag %1$s anzeigen",
	"Steam_Settings_Compat_Launch_Prefix": "Läuft auf diesem Computer via",
	"Steam_Settings_Compat_Launch_Name": "Steam Play.",
	"Steam_Settings_Compat_Launch_Forced": "Von Ihnen für diesen Titel ausgewählt.",
	"Steam_Settings_Compat_Launch_Wildcard": "Von Ihnen für alle Titel ausgewählt.",
	"Steam_Settings_Compat_Launch_Whitelisted": "Durch Tests von Valve ausgewählt.",
	"SteamAwards_EventMainTitle": "Steam-Awards nominieren",
	"SteamAwards_EventMainTitleSecondLine": "Kandidat",
	"SteamAwards_EventCallToAction": "Beginnt im Dezember",
	"SteamAwards_EventVotingDateTeaser": "Dezember 2019",
	"SteamAwards_EventVoteForGamePrompt": "Klicken Sie unten, um %1$s Ihre Stimme für diese Kategorie zu geben:",
	"SteamAwards_EventNominateGamePrompt_Long": "Nominieren Sie %1$s unten für die von den Entwicklern vorgeschlagene Kategorie oder wählen Sie eine andere Kategorie",
	"SteamAwards_EventNominateGamePrompt_NoCategory": "Klicken Sie hier, um %1$s für eine Kategorie der Steam-Awards zu nominieren.",
	"SteamAwards_Event_NominationsClosed": "Nominierungen abgeschlossen. Abstimmung während der Winteraktion. Die Gewinner werden am 31. Dezember bekannt gegeben.",
	"SteamAwards_Event_VotesClosed": "Die Abstimmung ist beendet. Klicken Sie hier für die Ergebnisse.",
	"SteamAwards_EventNominateGamePrompt_CategoryPrefix": "Nominieren für:",
	"SteamAwards_EventNominationAlternativeLinkText": "Eine andere Kategorie wählen",
	"SteamAward_CategoryTitle_none": "Keine Kategorie",
	"SteamAward_CategoryDesc_none": "Schlagen Sie keine bestimmte Kategorie vor, sondern überlassen Sie die Wahl Ihren Fans! Das Event fügt nichtsdestotrotz einen Link zur Nominierungsseite ein.",
	"SteamAward_CategoryTitle_goty": "Spiel des Jahres 2019",
	"SteamAward_CategoryDesc_goty": "Vielleicht war es das immersive Gameplay oder die packende Geschichte, die gut gestalteten Charaktere, ein makelloses Design oder ein süchtig machender Mehrspielermodus. Wie dem auch sei, der Gewinner des diesjährigen Preises für das Spiel des Jahres hat sich sofort als Klassiker etabliert.",
	"SteamAward_CategoryTitle_vrgoty": "VR-Spiel des Jahres 2019",
	"SteamAward_CategoryDesc_vrgoty": "Wenn es darum geht, neue Rahmen zu sprengen, gibt es kaum etwas Explosiveres als der atemberaubende Fortschritt in VR. Wenn es nach uns ginge, würden alle VR-Entwickler einen Preis dafür erhalten, dass sie mit VR die Zukunft immersiver Spiele und Erlebnisse erschaffen, die kein anderes Medium erreicht. Da es aber nur einen Preis zu verleihen gibt, liegt es an Ihnen, sehr geehrtes Ausschussmitglied der Steam-Awards, ein VR-Spiel als das beste dieses Jahres zu krönen.",
	"SteamAward_CategoryTitle_love": "Werk der Liebe 2019",
	"SteamAward_CategoryDesc_love": "Dieses Spiel ist bereits seit einer ganzen Weile auf dem Markt. Das Entwicklerteam hat den Schleier seines kreativen Schatzes längst gelüftet, doch als gute Eltern feilen sie noch immer an Ihrer Kreation. Dieses Spiel wird bis heute unterstützt und bekommt nach all den Jahren noch immer neue Inhalte.",
	"SteamAward_CategoryTitle_friends": "Besser mit Freunden 2019",
	"SteamAward_CategoryDesc_friends": "Es gibt Spiele, die ein besseres Erlebnis bieten, wenn man sie nicht allein spielt. Vielleicht brauchen Sie einen Freund, der Ihnen den Rücken freihält. Vielleicht haben Sie einen Freund, dem Sie einen Dolch in den Rücken stoßen möchten. Wie dem auch sei, wenn man diese Spiele mit Freunden spielt, ist Freude vorprogrammiert.",
	"SteamAward_CategoryTitle_gameplay": "Innovativstes Gameplay",
	"SteamAward_CategoryDesc_gameplay": "Dieses Spiel stellt die Vorhut der Experimentierfreudigen dar und sprengt die Grenzen des Mediums mit aufregenden neuen Interaktionen und Überraschungen, die Ihr Gehirn zermartern. Dieses Spiel wird Sie verändern!",
	"SteamAward_CategoryTitle_storyrich": "Herausragendes Spiel mit tiefgründiger Story",
	"SteamAward_CategoryDesc_storyrich": "An manchen Tagen tut es nur ein Spiel mit tiefgründiger Story und dieses Spiel ist Story pur. So ergreifend wie eine Seifenoper, so fein abgestimmt wie ein Prestige-Fernsehfilm – Hut ab! Wir fühlen mit!",
	"SteamAward_CategoryTitle_yousuck": "Bestes Spiel in dem Sie schlecht sind",
	"SteamAward_CategoryDesc_yousuck": "Spiele können uns auf eine Art und Weise über Grenzen treiben, die wir nicht für möglich gehalten haben. Wie bei einer Filmmontage trainieren wir wochenlang die Geschwindigkeit und Gelenkigkeit unserer Finger und meistern Timing und Platzierung. Am Ende des Spießrutenlaufs werden wir mit atemberaubender Schönheit und einem befriedigenden Gefühl persönlichen Wachstums belohnt. Es sei denn, man hat seinen Monitor schon am ersten Tag aus dem Fenster geschmissen.",
	"SteamAward_CategoryTitle_visual": "Herausragender visueller Stil",
	"SteamAward_CategoryDesc_visual": "Diese Entwickler sind wie Willy Wonka für die Augen. Der visuelle Stil versucht nicht die grafische Auflösung der Realität einzufangen (obwohl das durchaus ein nobles Unterfangen ist), sondern verfügt über ein einzigartiges Aussehen und eine besondere Atmosphäre, die sich durch das gesamte Spiel ziehen. Dieses Spiel veranschaulicht nicht nur einen zur Spielwelt passenden visuellen Zusammenhalt und Ausdruck, sondern lässt unsere Welt im Vergleich armselig erscheinen.",
	"SteamAward_NominationConflictWarning_Title": "Sie möchten Ihre Nominierung ändern?",
	"SteamAward_NominationConflictWarning_Explanation": "Es kann nur ein Spiel pro Kategorie nominiert werden und Sie haben bereits %1$s für diese Kategorie nominiert. Möchten Sie Ihre Wahl ändern und stattdessen %2$s nominieren?",
	"SteamAward_VoteButton_PromptText": "Abstimmen",
	"SteamAward_VoteButton_AlreadyVotedText": "Stimme abgegeben",
	"SteamAward_VoteConflictWarning_Title": "Sie möchten Ihre Stimme ändern?",
	"SteamAward_VoteConflictWarning_Explanation": "Es kann nur für ein Spiel pro Kategorie abgestimmt werden und Sie haben bereits %1$s Ihre Stimme für diese Kategorie gegeben. Möchten Sie Ihre Stimme ändern und stattdessen %2$s geben?",
	"Store_VR_Support_OnlyVR": "Nur VR",
	"Store_VR_Support_SupportsVR": "VR-Unterstützung",
	"Giveaway_CountDown": "Noch %1$s bis zur nächsten Auslosung!",
	"Giveaway_CountDown2": "Verbleibende Zeit bis zur nächsten Auslosung.",
	"Giveaway_KeepWatching": "Schauen Sie für eine Gewinnchance weiter zu!",
	"Giveaway_RandomDraw": "Auslosung läuft…",
	"Giveaway_Congratulation": "Anzahl glücklicher Gewinner!",
	"Giveaway_Closed_NoWinnerInfo": "Die Auslosung ist beendet. Danke für Ihre Teilnahme!",
	"Giveaway_Closed": "Die Auslosung ist jetzt mit %1$s glücklichen Gewinnern vorbei. Danke für Ihre Teilnahme!",
	"Giveaway_LearnMore": "Klicken Sie hier für weitere Informationen zu Preisen, Gewinnern und Regeln.",
	"Lunar2020_CheckBackEachDay": "Schauen Sie jeden Tag für ein neues Geschenk vom Kaiser vorbei!",
	"Lunar2020_CheckBackEachDayForStory": "Schauen Sie jeden Tag für ein neues Kapitel vorbei",
	"Lunar2020_FirstGift": "Erstes Geschenk",
	"Lunar2020_SecondGift": "Zweites Geschenk",
	"Lunar2020_ThirdGift": "Drittes Geschenk",
	"Lunar2020_FourthGift": "Viertes Geschenk",
	"Lunar2020_GiftWasOpened": "geöffnet",
	"Lunar2020_RereadStory": "Geschichte anzeigen",
	"Lunar2020_GiftCanBeOpenedNow": "jetzt öffnen",
	"Lunar2020_GiftCanBeOpenedAfterThePreviousOne": "nächstes öffnen",
	"Lunar2020_GiftLockedUntilDate": "am %1$s öffnen",
	"Lunar2020_ErrorLoadingVideo": "Bitte verwenden Sie einen Browser, der HTML-Videos unterstützt, um Ihren Umschlag zu öffnen.",
	"Lunar2020_LinkBackToSale": "Zurück zur Rabattaktion",
	"Lunar2020_LinkFromVideoToMarket": "Zum Markt",
	"Lunar2020_ReceivedNumberOfTokens": "Sie haben %1$s Marken erhalten",
	"Lunar2020_YourBalancePrefix": "Ihre Marken",
	"Lunar2020_BalanceNumberOfTokens": "%1$s Marken",
	"Lunar2020_LimitedUserDialogTitle": "Umschlag konnte nicht geöffnet werden",
	"Lunar2020_StoryTitle": "DAS GROSSE RENNEN DES KAISERS",
	"Lunar2020_StorySubTitle": "Der Ursprung der chinesischen Tierkreiszeichen",
	"Lunar2020_StoryDayOneHeader": "TEIL I VON IV",
	"Lunar2020_StoryDayTwoHeader": "TEIL II VON IV",
	"Lunar2020_StoryDayThreeHeader": "TEIL III VON IV",
	"Lunar2020_StoryDayFourHeader": "TEIL IV VON IV",
	"Lunar2020_StoryDayOne": "Der Jadekaiser rief alle Kreaturen seines Königreichs dazu auf, am Rennen zum himmlischen Palast teilzunehmen, um sich einen Platz in seinem neuen Kalender als einer der ersten zwölf Ankömmlinge zu verdienen.\n\nDie schlaue Ratte erreichte als Erstes die himmlische Ebene. Schwimmen war allgemein überbewertet, daher überließ sie es dem Ochsen und ritt auf dessen Rücken. Sekunden bevor dieser das Ufer erreichte, sprang sie in den himmlischen Garten des Kaisers.\n\nDer Ochse war am Ergebnis des Rennens nicht sonderlich interessiert und ließ sich beim Überqueren Zeit. Den ersten Platz wollte er der Ratte gern überlassen.",
	"Lunar2020_StoryDayTwo": "Der eigenständige Tiger bewegte sich zu vorsichtig, als dass er den Ochsen hätte überholen können. Besser auf dem 3. Platz landen, als auf gar keinem.\n\nDer flinke Hase schwamm in Seelenruhe den Fluss entlang. Zwar ging diese Strategie nicht auf, aber ein günstiger Wind gab ihm den nötigen Schub in die richtige Richtung.\n\nDer Gipfel des fliegenden Drachen zeigte ihm Andere in Schwierigkeiten und er half allen, auch dem Hasen. Was ist ein 5. Platz in einem Rennen, wenn es um die Ehre geht?",
	"Lunar2020_StoryDayThree": "Die verstohlene Schlange hatte an einem Langstreckenlauf auch kein Interesse, also wickelte sie sich um den Huf des Pferdes.\n\nAls dieses die Ziellinie fast erreicht hatte, glitt sie zu Boden und erschreckte das Pferd dadurch so sehr, dass sie es noch gerade auf den 6. Platz schaffte, mit dem Pferd hintendrein.",
	"Lunar2020_StoryDayFour": "Ziege, Affe und Hahn vertrauten auf Teamarbeit, überließen Ziege aber als Rückgrat des Teams den 8. Platz. Der fröhliche Affe gelangte verdient auf den 9. Platz und Hahn stolzierte auf Platz 10 über die Ziellinie, zufrieden damit, dass alles fair lief.\n\nDer verspielte Hund wollte eigentlich nur herumplanschen und hielt den 11. Platz für einen fairen Tausch für mehr Schwimmspaß.\n\nAn 12. Stelle kam Schwein, das eine kurze Verdauungspause eingelegt hatte – wohlwissend, dass jedes Tier eine Audienz beim Kaiser erhält.",
	"SteamChina_PendingPersonaName": "Profiländerungen treten erst nach der Überprüfung in Kraft",
	"Legal_Footer_WithYear": "© %1$s Valve Corporation. Alle Rechte vorbehalten. Alle Marken sind Eigentum der entsprechenden Besitzer in den USA und anderen Ländern.",
	"shared_dummy": "dont translate"
}
