{
	"language": "latam",
	"Button_Append": "Anexar",
	"Button_Cancel": "Cancelar",
	"Button_Close": "Cerrar",
	"Button_Clone": "Clonar",
	"Button_Confirm": "Confirmar",
	"Button_Copy": "Copiar",
	"Button_CopyClipboard": "Copiar al portapapeles",
	"Button_CopyLink": "Copiar enlace",
	"Button_Continue": "Continuar",
	"Button_Create": "Crear",
	"Button_Delete": "Eliminar",
	"Button_Discuss": "Discutir",
	"Button_Dismiss": "Ignorar",
	"Button_Edit": "Editar",
	"Button_Learn": "Más información aquí",
	"Button_Publish": "Publicar",
	"Button_Post": "Publicar",
	"Button_OK": "Aceptar",
	"Button_Overwrite": "Sobrescribir",
	"Button_Retry": "Reintentar",
	"Button_Remove": "Eliminar",
	"Button_Save": "Guardar",
	"Button_Saved": "Guardado",
	"Button_Share": "Compartir",
	"Button_Update": "Actualizar",
	"Button_SaveAndContinue": "Guardar y continuar",
	"Button_Follow": "Seguir",
	"Button_Followed": "Siguiendo",
	"Button_Ignore": "Ignorar",
	"Button_Ignored": "Ignorado",
	"Button_NotifyMe": "Notificarme",
	"Button_NotInterested": "No me interesa",
	"Button_RateUp": "Valorar positivamente",
	"Button_ViewPage": "Ver página",
	"Button_Accept": "Aceptar",
	"Button_Reject": "Rechazar",
	"ToolTip_CopyLinkToClipboard": "Copiar el enlace al portapapeles",
	"Input_Error_NumberTooSmall": "Número demasiado pequeño.",
	"Input_Error_NumberTooLarge": "Número demasiado grande.",
	"Input_Error_MustBeURL": "El campo no incluye una dirección URL válida.",
	"Input_Error_MustBeEmail": "El campo no incluye un correo electrónico válido.",
	"Input_Error_MustBeNumber": "El campo debe ser un número.",
	"Loading": "Cargando...",
	"Updating": "Actualizando...",
	"Uploading": "Cargando...",
	"Settings": "Configuración",
	"FriendSettings_AlwaysNewChatWindow": "Abrir siempre una nueva ventana de chat en lugar de una pestaña",
	"g_DisabledOnWeb": "No disponible en la versión web",
	"VoiceTransmissionType_Disabled": "Micrófono abierto solo para la versión web",
	"VoiceVolume": "Volumen",
	"VoiceSetupHeader": "Configuración y pruebas de voz",
	"VoiceStartLocalMicTest": "Iniciar prueba de micrófono",
	"VoiceStopLocalMicTest": "Finalizar prueba de micrófono",
	"VoiceWhenMicIsWorking": "Si tu micrófono funciona, deberías escucharte y ver moverse la barra de colores que hay junto a tu avatar mientras hablas.",
	"VoiceDevice": "Dispositivo de entrada de voz",
	"VoiceOutputDevice": "Dispositivo de salida de voz",
	"VoiceInputGain": "Entrada de volumen/ganancia",
	"VoiceInputGainExplainer": "(Mi micrófono)",
	"VoiceOutputGain": "Salida de volumen/ganancia",
	"VoiceOutputGainExplainer": "(Mis amigos)",
	"VoiceTransmissionType": "Presionar para hablar",
	"VoiceTransmissionType_Label": "Tipo de transmisión de voz",
	"VoiceTransmissionType_OpenMic": "Micrófono abierto",
	"VoiceTransmissionType_PushToTalk": "Presionar para hablar",
	"VoiceTransmissionType_PushToMute": "Presionar para silenciar",
	"VoiceClearHotKeyTooltip": "Eliminar la asignación de la tecla rápida para conmutar el micrófono",
	"VoiceTransmissionTypeExplainer": "Presionar una tecla definida por el usuario para hablar en los canales de voz",
	"VoiceTransmissionType_WhenSpeaking": "Automática",
	"VoiceTransmissionType_PushToTalk_Key": "Presionar para hablar: %1$s",
	"VoicePushToTalkPressHotKey": "Presiona la tecla o el botón del mouse para asignar",
	"VoicePushToTalkAssigned": "La tecla rápida de Presionar para hablar ha sido asignada como",
	"VoicePushToMuteAssigned": "La tecla rápida de Presionar para silenciar ha sido asignada como",
	"VoiceMuteToggleAssigned": "Tecla rápida para alternar el micrófono",
	"VoicePushToSomethingSoundOption": "Reproduce un sonido breve al activar/desactivar el micrófono",
	"VoiceTransmisionThreshold": "Límite de transmisión de voz",
	"VoiceTransmissionThresholdExplainer": "Cuando tu micrófono esté encendido, no se transmitirá el ruido por debajo de este límite:",
	"VoiceTransmissionThresholdOff": "Desactivado",
	"VoiceTransmissionThresholdMedium": "Medio",
	"VoiceTransmissionThresholdHigh": "Alto",
	"VoiceTransmissionThresholdRecommended": "Recomendado",
	"VoiceAdvancedSettings": "Configuraciones avanzadas",
	"VoiceShowAdvancedSettings": "Mostrar configuraciones avanzadas",
	"VoiceHideAdvancedSettings": "Ocultar configuraciones avanzadas",
	"VoiceAdvancedSettingsExplainer": "(Estas son configuraciones de micrófono gestionadas por la plataforma o navegador).",
	"VoiceEchoCancellation": "Cancelación de eco",
	"VoiceNoiseCancellation": "Cancelación de ruido",
	"VoiceAutoGainControl": "Control automático de volumen/ganancia",
	"DefaultMic": "Predeterminado",
	"MicLoading...": "Cargando...",
	"DefaultOutputDevice": "Predeterminado",
	"OutputDeviceLoading...": "Cargando...",
	"BreadCrumbs_AllEvents": "Todos los eventos",
	"BreadCrumbs_GameEvents": "Eventos de %1$s",
	"CreatorHome_ThisGame": "Sobre este juego:",
	"CreatorHome_DevelopedBy": "Desarrollador:",
	"CreatorHome_PublishedBy": "Editor:",
	"CreatorHome_InFranchise": "Franquicia:",
	"CreatorHome_Followers": "Seguidores:<br>%1$s",
	"CreatorHome_JustFollowers": "seguidores",
	"CreatorHome_Follow_tooltip": "Sigue a este creador para recibir una notificación por correo electrónico y en tu tienda de Steam cuando publique un nuevo juego. Las notificaciones por correo electrónico pueden desactivarse en cualquier momento.",
	"EventBrowse_MoreEventsTitle": "Más eventos de %1$s",
	"EventBrowse_MoreEventsBtn": "Ver todos",
	"EventBrowse_RecentUpdates": "Actualizaciones recientes",
	"EventBrowse_RecentEvents": "Eventos y anuncios recientes",
	"EventCalendar_Title": "Centro de noticias%1$sde Steam",
	"EventCalendar_FilterSubSection_EventTypeGroups": "Mostrar estos tipos de publicaciones",
	"EventCalendar_FilterSubSection_GameSources": "Mostrar publicaciones de estos recursos",
	"EventCalendar_EmptyCalendar": "No se encontraron publicaciones. Prueba seleccionando criterios de búsqueda diferentes en la barra lateral.",
	"EventCalendar_DisabledFilter_LoginPrompt": "Inicia sesión para activar estas categorías",
	"EventCalendar_MainLoginPrompt": "Inicia sesión para ver tu centro de noticias personal",
	"EventCalendar_NoMoreFutureEvents": "No se encontraron publicaciones",
	"EventCalendar_NoMorePastEvents": "No se encontraron publicaciones más antiguas",
	"EventCalendar_GameSearch": "Búsqueda de juegos",
	"EventCalendar_GameSearch_NoneFound": "No se encontraron coincidencias",
	"EventCalendar_GlobalCalendar_Action": "Volver al centro de noticias",
	"EventCalendar_SpecificCalendar": "%1$s%2$s Centro de noticias",
	"EventCalendar_Goto_SpecificCalendar": "Ir al centro de noticias de %1$s",
	"EventCalendar_SingleAppIsMuted": "Aviso: Este juego está silenciado y no aparecerá en tu centro de noticias personalizado.",
	"SteamLabs": "Laboratorios de Steam",
	"SteamLabs_ExperimentNumber": "Experimento %1$s",
	"SteamLabs_DiscussionLink": "Comenta sobre este experimento",
	"EventCalendar_FutureEventsHint": "Desplaza hacia arriba para ver lo que está por venir",
	"EventCalendar_FutureEventsHeader": "Próximamente",
	"EventCalendar_LiveAndRecentEventsHeader": "En directo y recientes",
	"EventCalendar_LiveNow": "en directo",
	"EventCalendar_TimeLeft": "termina en %1$s",
	"EventCalendar_PostedAtTime": "Publicado el %1$s",
	"EventCalendar_StartedAtTime": "Comenzó: %1$s",
	"EventCalendar_Upcoming": "próximos",
	"EventCalendar_WillStartAtTime": "Comienza el %1$s",
	"EventCalendar_WillStartAfterDuration": "Comienza en %1$s",
	"EventCalendar_LaterToday": "en un rato",
	"EventCalendar_Tomorrow": "mañana",
	"EventCalendar_ThisWeek": "esta semana",
	"EventCalendar_ThisMonth": "este mes",
	"EventCalendar_MuchLater": "más tarde",
	"EventCalendar_MuteApp": "Silenciar aplicación",
	"EventCalendar_MuteApp_Title": "Silenciar %1$s",
	"EventCalendar_Ignore": "Ignorar",
	"EventCalendar_IgnoreApp": "Ignorar %1$s",
	"EventCalendar_IgnoreApp_ttip": "Los títulos ignorados no se te recomendarán y no aparecerán en áreas de destacados.",
	"EventCalendar_IgnoreApp_newhub": "El centro de noticias ahora aplicará tu configuración y evitará que tus juegos ignorados de la tienda aparezcan en tu centro de noticias. Puedes administrar los juegos ignorados aquí:",
	"EventCalendar_UnignoreApp": "Dejar de ignorar %1$s",
	"EventCalendar_UnMuteApp_Title": "Dejar de silenciar %1$s",
	"EventCalendar_MuteApp_ttip": "Eliminar este juego de tu centro de noticias y bloquear las comunicaciones futuras.",
	"EventCalendar_UnMuteApp_ttip": "Restablece este juego en tu Centro de noticias y desbloquea las comunicaciones futuras.",
	"EventCalendar_MuteApp_details": "Elimina \"%1$s\" de tu centro de noticias y bloquea todas las comunicaciones futuras. Las decisiones sobre contenido silenciado siempre se pueden revertir visitando esta página:",
	"EventCalendar_ManageMutedApps": "Administrar aplicaciones silenciadas",
	"EventCalendar_ManageStorePref": "Administrar preferencias de la tienda",
	"EventCalendar_MuteApp_Unknown": "Desconocido",
	"EVentCalendar_Hide_EventType": "Ocultar todas las publicaciones del tipo \"%1$s\"",
	"EventCalender_LastPlayed": "Última sesión: %1$s",
	"EventCalender_Reason_recent": "Jugaste a este juego recientemente",
	"EventCalender_Reason_library": "Este juego ya está en tu biblioteca",
	"EventCalender_Reason_following": "Ya sigues este juego",
	"EventCalender_Reason_wishlist": "Este juego está en tu lista de deseados",
	"EventCalender_Reason_recommended": "Este juego está recomendado para ti",
	"EventCalender_Reason_steam": "Esta publicación es de la plataforma Steam",
	"EventCalender_Reason_topx": "El juego está entre los más vendidos",
	"EventCalender_Hide_Reason_recent": "Ocultar publicaciones de juegos jugados recientemente",
	"EventCalender_Hide_Reason_library": "Ocultar publicaciones de juegos que tengas en tu biblioteca",
	"EventCalender_Hide_Reason_following": "Ocultar publicaciones de juegos que sigues",
	"EventCalender_Hide_Reason_wishlist": "Ocultar publicaciones de juegos que tengas en tu lista de deseados",
	"EventCalender_Hide_Reason_recommended": "Ocultar publicaciones de juegos recomendados para ti",
	"EventCalender_Hide_Reason_steam": "Ocultar publicaciones de la plataforma Steam",
	"EventCalender_Hide_Reason_topx": "Ocultar publicaciones de lo más vendido",
	"EventCalendar_ForceDesktopView": "Solicitar vista de escritorio",
	"EventCalendar_ShowResponsiveView": "Solicitar vista adaptativa",
	"EventCalendar_EventTypeGroup_news": "Noticias",
	"EventCalendar_EventTypeGroup_ttip_news": "Incluye noticias generales, blogs de desarrollo y anuncios.",
	"EventCalendar_EventTypeGroup_events": "Eventos",
	"EventCalendar_EventTypeGroup_ttip_events": "Incluye eventos en juegos, en línea, en el chat y en el mundo real.",
	"EventCalendar_EventTypeGroup_streaming": "Retransmisiones en directo",
	"EventCalendar_EventTypeGroup_ttip_streaming": "Incluye retransmisiones en vivo para desarrolladores, como torneos y juegos.",
	"EventCalendar_EventTypeGroup_updates": "Actualizaciones de contenido",
	"EventCalendar_EventTypeGroup_ttip_updates": "Incluye noticias sobre nuevos contenidos, expansiones, DLC y correcciones de errores de juegos.",
	"EventCalendar_EventTypeGroup_releases": "Lanzamientos",
	"EventCalendar_EventTypeGroup_ttip_releases": "Incluye publicaciones sobre fechas de lanzamiento de nuevos juegos, betas, temporadas o DLC.",
	"EventCalendar_EventTypeGroup_sales": "Ofertas",
	"EventCalendar_EventTypeGroup_ttip_sales": "Incluye descuentos, promociones y pruebas gratuitas.",
	"EventCalendar_GameSource_recent": "Jugados recientemente",
	"EventCalendar_GameSource_ttip_recent": "Incluye publicaciones sobre juegos que has jugado o comprado en los últimos seis meses",
	"EventCalendar_GameSource_EventExplanation_ttip_recent": "Jugaste a este juego en los últimos seis meses",
	"EventCalendar_GameSource_library": "Biblioteca",
	"EventCalendar_GameSource_ttip_library": "Incluye publicaciones sobre juegos de tu biblioteca",
	"EventCalendar_GameSource_EventExplanation_ttip_library": "Este juego ya está en tu biblioteca",
	"EventCalendar_GameSource_wishlist": "Lista de deseados",
	"EventCalendar_GameSource_ttip_wishlist": "Incluye publicaciones sobre juegos de tu lista de deseados",
	"EventCalendar_GameSource_EventExplanation_ttip_wishlist": "Este juego ya está en tu lista de deseados",
	"EventCalendar_GameSource_following": "siguiendo",
	"EventCalendar_GameSource_ttip_following": "Incluye publicaciones sobre juegos que sigues",
	"EventCalendar_GameSource_EventExplanation_ttip_following": "Ya estás siguiendo este juego",
	"EventCalendar_GameSource_recommended": "Recomendados",
	"EventCalendar_GameSource_recommended_Verbose": "Juego recomendado",
	"EventCalendar_GameSource_ttip_recommended": "Incluye publicaciones sobre juegos que creemos que te gustarían",
	"EventCalendar_GameSource_EventExplanation_ttip_recommended": "Pensamos que te va a gustar este juego",
	"EventCalendar_GameSource_steam": "steam",
	"EventCalendar_GameSource_ttip_steam": "Incluye publicaciones sobre la plataforma Steam",
	"EventCalendar_GameSource_topx": "Lo más vendido",
	"EventCalendar_GameSource_ttip_topx": "Incluir publicaciones sobre juegos que están en las listas de lo más vendido de la región",
	"EventCalendar_GameSource_EventExplanation_ttip_steam": "Esta es una publicación sobre Steam",
	"EventDisplay_Admin_Title": "Herramientas de administrador:",
	"EventDisplay_ViewInLibrary": "Ver en la biblioteca",
	"EventDisplay_ViewStorePage": "Ver página de la tienda",
	"EventDisplay_ViewCommunityPage": "Ver página de la comunidad",
	"EventDisplay_CallToAction_LearnMore": "Más información",
	"EventDisplay_CallToAction_InLibrary": "En la biblioteca",
	"EventDisplay_CallToAction_PlayNow": "Jugar ahora",
	"EventDisplay_CallToAction_ComingSoon": "Próximamente",
	"EventDisplay_CallToAction_FreeToPlay": "Free to Play",
	"EventDisplay_Events": "Panel de administración",
	"EventDisplay_SeeOldVersion": "Ver la versión actual del cliente",
	"EventDisplay_SalesPage": "Ver la página de ofertas de la tienda",
	"EventDisplay_StatsPage": "(SV) Página de estadísticas",
	"EventDisplay_RightColumnTitle_Game": "Juego",
	"EventDisplay_RightColumnTitle_Blog": "Blog",
	"EventDisplay_RightColumnTitle_DateAndTime": "Fecha y hora",
	"EventDisplay_RightColumnTitle_EventType": "Tipo",
	"EventDisplay_PostedBy": "por ",
	"EventDisplay_Reminder_SetReminder": "Crear un recordatorio",
	"EventDisplay_Reminder_GetNotification_Via": "Obtener una notificación",
	"EventDisplay_Reminder_ViaEmail": "por correo electrónico",
	"EventDisplay_Reminder_ViaMobileApp": "por aplicación móvil",
	"EventDisplay_Reminder_FollowEvent": "Seguir evento",
	"EventDisplay_Reminder_FollowEvent_ttip": "Sigue un evento para recibir una notificación cuando este comience.",
	"EventDisplay_Reminder_RemindAtStart": "Cuando comience el evento",
	"EventDisplay_Reminder_RemindAtStart_ttip": "Steam te enviará una notificación cuando comience el evento.",
	"EventDisplay_Reminder_IgnoreEvent": "Ignorar este evento",
	"EventDisplay_Reminder_IgnoreStop": "Cancelar recordatorios",
	"EventDisplay_Reminder_IgnoreEvent_ttip": "Al ignorar un evento, le indicas a Steam que lo excluya de futuras sugerencias y recomendaciones.",
	"EventDisplay_Reminder_FollowEvent_Error": "Error al seguir el evento",
	"EventDisplay_Reminder_FollowEvent_ErrorDesc": "Se produjo el siguiente error al tratar de seguir el evento:",
	"EventDisplay_Reminder_IgnoreEvent_Error": "Error al ignorar el evento",
	"EventDisplay_Reminder_IgnoreEvent_ErrorDesc": "Se produjo el siguiente error al tratar de ignorar el evento:",
	"EventDisplay_Reminder_Toast": "Notificación del sistema de Steam cuando comience el evento",
	"EventDisplay_Reminder_AddToCalendar": "Añadir al calendario",
	"EventDisplay_Reminder_AddToApple": "Añadir al calendario de Apple",
	"EventDisplay_Reminder_AppleCalendar_Short": "Apple",
	"EventDisplay_Reminder_AddToGoogle": "Añadir al calendario de Google",
	"EventDisplay_Reminder_GoogleCalendar_Short": "Google",
	"EventDisplay_Reminder_AddToOutlook": "Añadir al calendario de Outlook",
	"EventDisplay_Reminder_OutlookCalendar_Short": "Outlook",
	"EventDisplay_Reminder_AddToYahoo": "Añadir al calendario de Yahoo",
	"EventDisplay_Reminder_Preferences": "Editar preferencias de recordatorio...",
	"EventDisplay_TimeDisplay": "De %1$s a %2$s",
	"EventDisplay_TimeDisplayNone": "Sin información de fecha y hora",
	"EventDisplay_TimeBeginsOn": "El próximo evento va a comenzar",
	"EventDisplay_TimeBeginsOn_Past": "Comenzó el",
	"EventDisplay_TimeBeginsOn_StartAndEnd_Past": "Evento anterior iniciado",
	"EventDisplay_TimeEndsOn": "Finaliza",
	"EventDisplay_TimeEndsOn_Past": "Finalizado",
	"EventDisplay_RunsForDuration": "Dura: %1$s",
	"EventDisplay_TimeLeft": "Termina el %1$s",
	"EventDisplay_TimeEndsOn_Ran": "Completado",
	"EventDisplay_TimeRange": "Hora del evento",
	"EventDisplay_TimeInPast": "Publicado",
	"EventDisplay_TimeUpcoming": "Comenzar evento",
	"EventDisplay_EventUpcoming_WithDateAndTime": "El evento comienza el %1$s a las %2$s",
	"EventDisplay_TimeEventActive": "El evento ha comenzado",
	"EventDisplay_TimeEventOnNow": "¡En vivo ahora!",
	"EventDisplay_Share_Link": "Enlace: ",
	"EventDisplay_Share_OnMyStatus": "Compartir directamente a mi estado",
	"EventDisplay_Share_OnMyStatus_Details": "Publica este estado en la fuente de actividad de tus amigos. Steam incluirá el mensaje y la vista previa del elemento que se muestra a continuación.",
	"EventDisplay_Share_OnMyStatus_Placeholder": "Cuéntaselo a tus amigos...",
	"EventDisplay_Share_OnSteam": "Compartir en la Comunidad Steam como una actualización de estado",
	"EventDisplay_Share_OnFaceBook": "Compartir en Facebook",
	"EventDisplay_Share_OnTwitter": "Compartir en Twitter",
	"EventDisplay_Share_OnReddit": "Compartir en Reddit",
	"EventDisplay_Share_Success": "¡Hecho!",
	"EventDisplay_Share_Failure": "Ha habido un error con el siguiente mensaje: ",
	"EventDisplay_Share_Announcement": "Anuncio: %1$s",
	"EventDisplay_Share_Event": "Evento: %1$s",
	"EventDisplay_Share_NotLoggedIn": "No has iniciado sesión",
	"EventDisplay_Share_NotLoggedIn_Description": "Para usar esta función, primero debes iniciar sesión en Steam",
	"EventDisplay_Share_CommentMigrationInProcess": "Las discusiones para este evento están en cola para transferirlas al sistema de eventos, por lo que están temporalmente inaccesibles. Vuelve más tarde.",
	"EventDisplay_Share_OpenActivityFeed": "Abrir mi fuente de actividad",
	"EventDisplay_AreYouSure": "¿Estás seguro de que quieres eliminar este evento (%1$s)? Esta acción no se puede deshacer.",
	"EventDisplay_AreYouSure_Visible": "¿Estás seguro de que quieres eliminar este evento (%1$s)? Esta acción no se puede deshacer. Este evento se eliminará, en unos pocos minutos, de todos los lugares donde un usuario pueda encontrarlo.",
	"EventDisplay_DeleteEvent_InProgress": "Eliminando. Por favor, espera...",
	"EventDisplay_DeleteEvent_Error": "Se ha producido un error al procesar la solicitud de eliminación:",
	"EventDisplay_DeleteEvent_ForumTopicError": "El evento fue eliminado con éxito. Hemos fallado al intentar eliminar el hilo del tema del foro para el evento. Siempre puedes intentarlo en el sitio %1$s. Detalles del error:",
	"EventDisplay_DeleteEvent_Success": "El evento se ha eliminado con éxito.",
	"EventDisplay_DeleteEvent_Comment": "¿Quieres también eliminar el hilo de comentarios del foro de discusión para este evento?",
	"EventDisplay_SocialTitle": "Más sobre este juego",
	"EventDisplay_Sketchfab": "Modelo de Sketchfab",
	"EventDisplay_SketchFab_Error_Network": "No se pudo contactar con Sketchfab",
	"EventEditor_Publish_VisibleNow": "Hacer visible ahora",
	"EventEditor_Publish_VisibleNow_ttip": "Este evento estará visible a la hora programada. Este botón hace que el evento esté visible inmediatamente.",
	"EventEditor_Edit": "Editar evento",
	"EventDisplay_DeleteEvent": "Eliminar evento",
	"EventReminder_InProgress": "(ten en cuenta que las opciones de notificación que se muestran aquí son representativas y aún no funcionan)",
	"EventReminder_NotifyByEmail": "Enviar una notificación a mi correo electrónico",
	"EventReminder_NotifyByEmail_ttip": "Steam enviará una notificación por correo electrónico a tu cuenta cuando comience el evento.",
	"EventReminder_NotifyByMobile": "Enviar una notificación a mi dispositivo móvil",
	"EventReminder_NotifyByMobile_ttip": "Steam enviará una notificación cuando el evento comience a todos los dispositivos donde hayas instalado e iniciado sesión en la aplicación Steam Mobile.",
	"EventReminder_NotifyByEmail_Missing": "Verifica tu dirección de correo electrónico para suscribirte a los recordatorios.",
	"EventReminder_NotifyByEmail_Missing_Add": "Verifica tu dirección de correo electrónico.",
	"EventReminder_NotifyByMobile_Missing": "Instala una de las aplicaciones de Steam para suscribirte a los recordatorios de móvil. ",
	"EventReminder_NotifyByMobile_Install": "Ve las aplicaciones disponibles aquí.",
	"EventEmail_Subject_NewUpdate": "%1$s, nueva actualización",
	"EventEmail_Subject_UpcomingLaunch": "%1$s, próximo lanzamiento",
	"EventEmail_Subject_NowAvailable": "%1$s ya disponible",
	"EventEmail_Subject_FreeDemoAvailable": "Demo gratis ya disponible: %1$s",
	"EventEmail_Subject_SpecialOffer": "Oferta especial de %1$s",
	"EventEmail_Subject_Tournament_Now": "Torneo %1$s, conéctate ya",
	"EventEmail_Subject_LiveStream_Now": "Retransmisión en directo de %1$s, conéctate ya",
	"Email_Wishlist_NewReleaseEA_Subject": "¡%1$s ya está disponible en acceso anticipado en Steam!",
	"EventEmail_Button_ClickForMoreDetails": "Leer más",
	"EventEmail_Button_PrepurchaseNow": "¡Precómpralo ya!",
	"EventEmail_Button_BuyNow": "¡Comprar ahora!",
	"EventEmail_Button_PlayNow": "¡Juégalo ahora!",
	"EventEmail_Button_WishlistNow": "¡Añadir a la lista de deseados!",
	"EventEmail_WatchNow": "Ver ahora",
	"EventEmail_Destination_Store": "Página de producto de la tienda de Steam",
	"EventEmail_Destination_Event": "Página de detalles del evento",
	"EventEmail_Destination_SalesPage": "Página de ofertas de la tienda de Steam",
	"EventDashBoard_SummaryStats_Admin_Title": "(Solo visible para administradores)",
	"EventDashBoard_SummaryStats_Title": "Total de impresiones y vistas únicas",
	"EventDashBoard_SummaryStats_Desc": "(Beta) Estas son las impresiones y vistas de tus eventos y anuncios de usuarios únicos registrados. Esto es solo para eventos y anuncios nuevos creados con este editor.",
	"EventDashBoard_SummaryStats_Link": "Haz clic aquí para más detalles.",
	"EventDashBoard_Summary_LibraryHome_Shown": "Impresiones de eventos (imagen de portada):",
	"EventDashBoard_Summary_LibraryHome_Read": "Clics en un evento para ver los detalles:",
	"EventDashBoard_Summary_AppDetailSpotlight_Shown": "Impresiones de una imagen destacada:",
	"EventDashBoard_Summary_AppDetailSpotlight_Read": "Clics en una imagen destacada para ver los detalles:",
	"EventDashBoard_Summary_AppDetailActivity_Shown": "Impresiones de eventos en una fuente de actividad:",
	"EventDashBoard_Summary_AppDetailActivity_Read": "Clics en un evento para ver los detalles:",
	"EventDashBoard_Summary_StoreAppPage_Shown": "Impresiones de eventos (imagen de portada):",
	"EventDashBoard_Summary_StoreAppPage_Read": "Clics en un evento para ver los detalles:",
	"EventDashBoard_Summary_Community_Shown": "Impresiones del resumen del evento:",
	"EventDashBoard_Summary_Community_Read": "Clics en un resumen de evento para ver los detalles:",
	"EventDashBoard_Summary_NewsHub_Shown": "Impresiones de eventos en un centro de noticias:",
	"EventDashBoard_Summary_NewsHub_Read": "Clics en un evento para ver los detalles:",
	"EventDashBoard_Location_LibraryHome": "Página principal de la biblioteca",
	"EventDashBoard_Location_LibraryDetail": "Página del juego en la biblioteca",
	"EventDashBoard_Location_StoreDetail": "Página del juego en la tienda",
	"EventDashBoard_Location_CommunityDetail": "Punto de encuentro de la comunidad para la aplicación",
	"EventDashBoard_Location_PopUpViews": "Vistas de nota emergente de tu evento",
	"EventDashBoard_Location_NewsHubDetail": "Centro de noticias",
	"AddToWishlist": "Añadir a tu lista de deseados",
	"Wishlisted": "En tu lista de deseados",
	"AddToWishlist_ttip": "Recibe una notificación por correo electrónico cuando los artículos en tu lista de deseados se publiquen o estén en oferta",
	"Wishlist_Error": "Error de actualización de la lista de deseados",
	"Wishlist_Error_Desc": "Error al añadir a tu lista de deseados. Inténtalo de nuevo más tarde:",
	"WindowTitle_FriendsList": "Lista de amigos",
	"FriendsList_OfflineTitle": "ERROR",
	"FriendsList_OfflineOrFailure": "No se puede obtener acceso a la red de amigos",
	"FriendsList_OfflineDetail": "Este error puede indicar que tu red local está desconectada o que los servidores de Amigos de Steam están desconectados actualmente.",
	"FriendsList_SignedOut": "Sesión de Amigos y chat cerrada",
	"FriendsList_SignedOut_Detail": "Estás desconectado. Inicia sesión para acceder a tu lista de amigos y chat.",
	"FriendsList_OfflineMode": "Sesión de Amigos y chat cerrada",
	"FriendsList_OfflineMode_Detail": "Los amigos y el chat no están disponibles en modo desconectado. Conéctate para acceder a tu lista de amigos y chat.",
	"Friends_RetryLoading": "Reintentar conexión",
	"Friends_SignIn": "Iniciar sesión",
	"FriendsList_Offline_Disconnected": "Desconectado",
	"FriendsList_LoadingTitle": "CARGANDO",
	"FriendsList_StillLoadingSummary": "Red de amigos cargando...",
	"FriendsList_StillLoadingDetail": "Steam está tratando de conectarse a la red de amigos, lo que puede tardar unos segundos.",
	"Dialog_On": "SÍ",
	"Dialog_Off": "NO",
	"TimeInterval_XYears": "%1$s años",
	"TimeInterval_1YearXMonths": "1 año y %1$s meses",
	"TimeInterval_1Year": "1 año",
	"TimeInterval_XMonths": "%1$s meses",
	"TimeInterval_1Month": "1 mes",
	"TimeInterval_1MonthX": "1 mes y %1$s días",
	"TimeInterval_XWeeks": "%1$s semanas",
	"TimeInterval_1Week": "1 semana",
	"TimeInterval_XDays": "%1$s días",
	"TimeInterval_1Day": "1 día",
	"TimeInterval_1DayXHours": "1 día y %1$s horas",
	"TimeInterval_XHours": "%1$s horas",
	"TimeInterval_1Hour": "1 hora",
	"TimeInterval_1HourXMinutes": "1 hora y %1$s minutos",
	"TimeInterval_LessThanAnHour": "menos de 1 hora",
	"TimeInterval_XMinutes": "%1$s minutos",
	"TimeInterval_1Minute": "1 minuto",
	"TimeInterval_LessThanAMinute": "menos de 1 minuto",
	"TimeSince_XYears": "hace %1$s años",
	"TimeSince_1YearXMonths": "hace 1 año y %1$s meses",
	"TimeSince_1Year": "hace 1 año",
	"TimeSince_XMonths": "hace %1$s meses",
	"TimeSince_1Month": "hace 1 mes",
	"TimeSince_1MonthXDays": "hace 1 mes y %1$s días",
	"TimeSince_XWeeks": "hace %1$s semanas",
	"TimeSince_1Week": "hace 1 semana",
	"TimeSince_XDays": "hace %1$s días",
	"TimeSince_1Day": "hace 1 día",
	"TimeSince_1DayXHours": "hace 1 día y %1$s horas",
	"TimeSince_XHours": "hace %1$s horas",
	"TimeSince_1Hour": "hace 1 hora",
	"TimeSince_1HourXMinutes": "hace 1 hora y %1$s minutos",
	"TimeSince_LessThanAnHour": "hace menos de 1 hora",
	"TimeSince_XMinutes": "hace %1$s minutos",
	"TimeSince_1Minute": "hace 1 minuto",
	"TimeSince_LessThanAMinute": "hace menos de 1 minuto",
	"TimeSince_ThisWeek": "Esta semana",
	"Time_Today": "Hoy",
	"Time_Tomorrow": "Mañana",
	"Time_Yesterday": "Ayer",
	"Time_Recent": "Reciente",
	"ContextMenu_Copy": "Copiar",
	"ContextMenu_Cut": "Cortar",
	"ContextMenu_Paste": "Pegar",
	"ContextMenu_CopyLinkURL": "Copiar URL de enlace",
	"ContextMenu_OpenLinkInNewWindow": "Abrir enlace en una ventana nueva",
	"ContextMenu_CopyImageURL": "Copiar URL de imagen",
	"ContextMenu_OpenImageInNewWindow": "Abrir imagen en una ventana nueva",
	"Tooltip_Settings": "Gestionar la configuración de la lista de amigos",
	"Tooltip_VoiceSettings": "Administrar la configuración de voz",
	"Tooltip_SearchFriends": "Buscar en la lista de amigos",
	"Tooltip_AddFriend": "Añadir a un amigo",
	"Tooltip_FriendRequest": "%1$s solicitud entrante",
	"Tooltip_FriendRequest_Plural": "%1$s solicitudes entrantes",
	"Tooltip_CreateGroupChat": "Crear un chat de grupo",
	"Tooltip_InviteToGroup": "Invitar a un amigo a este chat de grupo",
	"Tooltip_InviteToGroup_Denied": "No tienes permiso para invitar a usuarios a este grupo",
	"Tooltip_GroupChatSettings": "Gestionar la configuración de chat de grupo",
	"Tooltip_MemberCollapse": "Contraer la lista de miembros",
	"Tooltip_MemberExpand": "Expandir la lista de miembros",
	"Tooltip_ChatsCollapse": "Contraer la lista de chats",
	"Tooltip_ChatsExpand": "Expandir la lista de chats",
	"Tooltip_MinimizeList": "Minimizar lista",
	"Tooltip_ExpandList": "Expandir lista",
	"Tooltip_PinChannelList": "Anclar lista de canales",
	"Tooltip_UnpinChannelList": "Desanclar lista de canales",
	"Tooltip_TextChannel": "Chat de texto con los miembros del grupo",
	"Tooltip_TextChannelCreate": "Crear nuevo canal de texto",
	"Tooltip_NoPermissionChannelCreate": "No tienes permiso para crear canales en este chat de grupo",
	"Tooltip_VoiceChannel": "Chat de voz en estos canales de voz",
	"Tooltip_VoiceChannelCreate": "Crear un canal de voz",
	"Tooltip_DismissVoice": "Rechazar invitación de voz",
	"Tooltip_MicStatus_Active": "Micrófono activo",
	"Tooltip_MicStatus_Muted": "Micrófono silenciado",
	"Tooltip_RemoteMicStatus_Muted": "El usuario ha silenciado su micrófono",
	"Tooltip_MicStatus_NoMic": "El usuario no tiene el micrófono conectado",
	"Tooltip_RemoteOutputStatus_Muted": "El usuario ha desactivado el audio de este canal",
	"Tooltip_YourMicStatus_Muted": "Has silenciado tu micrófono",
	"Tooltip_YourOutputStatus_Muted": "Has desactivado el audio de este canal",
	"Tooltip_VoiceControlButton_1v1_inactive": "Enviar una solicitud de voz",
	"Tooltip_VoiceControlButton_1v1_active": "Abandonar canal de voz",
	"Tooltip_VoiceControlButton_group_create": "Crear un canal de voz",
	"Tooltip_VoiceControlButton_group_leave": "Abandonar el canal de voz",
	"Tooltip_VoiceControlButton_group_joinsingle": "Unirse al canal de voz",
	"Tooltip_VoiceControlButton_group_joinmultiple": "Selecciona un canal de voz para unirte",
	"LanguageTitle": "Idioma",
	"Language_english": "Inglés",
	"Language_german": "Alemán",
	"Language_french": "Francés",
	"Language_italian": "Italiano",
	"Language_korean": "Coreano",
	"Language_spanish": "Español — España",
	"Language_schinese": "Chino simplificado",
	"Language_tchinese": "Chino tradicional",
	"Language_russian": "Ruso",
	"Language_thai": "Tailandés",
	"Language_japanese": "Japonés",
	"Language_portuguese": "Portugués",
	"Language_polish": "Polaco",
	"Language_danish": "Danés",
	"Language_dutch": "Holandés",
	"Language_finnish": "Finés",
	"Language_norwegian": "Noruego",
	"Language_swedish": "Sueco",
	"Language_hungarian": "Húngaro",
	"Language_czech": "Checo",
	"Language_romanian": "Rumano",
	"Language_turkish": "Turco",
	"Language_arabic": "Árabe",
	"Language_brazilian": "Portugués — Brasil",
	"Language_bulgarian": "Búlgaro",
	"Language_greek": "Griego",
	"Language_ukrainian": "Ucraniano",
	"Language_latam": "Español — Latinoamérica",
	"Language_vietnamese": "Vietnamita",
	"Language_koreana": "Coreano",
	"language_selection_english": "English (Inglés)",
	"language_selection_spanish": "Español - España",
	"language_selection_french": "Français (Francés)",
	"language_selection_italian": "Italiano (Italiano)",
	"language_selection_german": "Deutsch (Alemán)",
	"language_selection_greek": "Ελληνικά (Griego)",
	"language_selection_koreana": "한국어 (Coreano)",
	"language_selection_korean": "한국어 (Coreano)",
	"language_selection_schinese": "简体中文 (Chino simplificado)",
	"language_selection_tchinese": "繁體中文 (Chino tradicional)",
	"language_selection_russian": "Русский (Ruso)",
	"language_selection_thai": "ไทย (Tailandés)",
	"language_selection_japanese": "日本語 (Japonés)",
	"language_selection_portuguese": "Português (Portugués)",
	"language_selection_brazilian": "Português-Brasil (Portugués de Brasil)",
	"language_selection_polish": "Polski (Polaco)",
	"language_selection_danish": "Dansk (Danés)",
	"language_selection_dutch": "Nederlands (Holandés)",
	"language_selection_finnish": "Suomi (Finés)",
	"language_selection_norwegian": "Norsk (Noruego)",
	"language_selection_swedish": "Svenska (Sueco)",
	"language_selection_czech": "Čeština (Checo)",
	"language_selection_hungarian": "Magyar (Húngaro)",
	"language_selection_romanian": "Română (Rumano)",
	"language_selection_bulgarian": "Български (Búlgaro)",
	"language_selection_pirate": "Pirata (¡Arr!)",
	"language_selection_turkish": "Türkçe (Turco)",
	"language_selection_ukrainian": "Українська (Ucraniano)",
	"language_selection_vietnamese": "Tiếng Việt (Vietnamita)",
	"language_selection_arabic": "العربية (Árabe)",
	"language_selection_spanish_mexican": "Español de México",
	"language_selection_latam": "Español de Latinoamérica",
	"Bbcode_Originally_Posted_By": "Publicado originalmente por",
	"Bbcode_No_Match": "No hay coincidencias para el BBCode compatible",
	"Editor_Bold": "Negrita",
	"Editor_Underline": "Subrayado",
	"Editor_Italics": "Cursiva",
	"Editor_StrikeThrough": "Tachada",
	"Editor_Link": "Insertar enlace",
	"Editor_Unordered": "Lista sin orden",
	"Editor_Ordered": "Lista ordenada",
	"Editor_Header": "Encabezamiento",
	"Editor_Header2": "Encabezamiento 2",
	"Editor_Header3": "Encabezamiento 3",
	"Editor_Emoticon": "Insertar emoticono",
	"EventEditor_ConvertHTML_Error": "Error al convertir el HTML",
	"EventEditor_ConvertHTML_Error_Desc": "Error al convertir el HTML a bbcode con el siguiente error: '%1$s'",
	"EventEditor_InsertLinkURL": "Insertar URL",
	"EventEditor_FormattingHelp_GetHelpLink": "Ayuda sobre formato",
	"EventEditor_ImportHTML": "Importar HTML",
	"EventEditor_ImportFromHTML": "Importar desde HTML",
	"EventEditor_ImportFromHTML_ttip": "Importación desde HTML. Convertirá automáticamente tu HTML en etiquetas con el formato que usa Steam.",
	"EventEditor_ImportFromHTML_Instruction": "Escribe o pega el HTML a continuación.",
	"EventEditor_ImportFromHTML_PreserveNewlines": "Conservar saltos de línea",
	"EventEditor_ImportFromHTML_PreserveNewlines_Hint": "En HTML, los cambios de línea no suelen tener efecto, pero en BBCode se muestran como líneas en blanco.  Si utilizaste etiquetas <p> o <br>, deja esto sin marcar.  Si sueles usar software para blogs que añade automáticamente etiquetas <br> para las nuevas líneas, probablemente tendrás que marcar esta casilla.",
	"EventEditor_ImportFromHTML_ConvertToBBCode": "Convertir a BBCode:",
	"EventEditor_ImportFromHTML_ConversionInProgress": "Conversión en curso. No cierres el cuadro de diálogo.",
	"EventEditor_ImportFromHTML_ConvertFinished": "La conversión ha terminado. Ahora puedes cerrar este cuadro de diálogo de forma segura.",
	"EventEditor_InsertYouTube": "Insertar video de YouTube™",
	"EventEditor_InsertYouTube_Left": "Alineado a la izquierda",
	"EventEditor_InsertYouTube_Right": "Alineado a la derecha",
	"EventEditor_InsertYouTube_Full": "Ancho completo",
	"EventEditor_InsertYouTube_URL": "URL completo",
	"EventEditor_InsertYouTube_Position": "Posición",
	"EventEditor_InsertYouTube_Placholder": "Introduce tu URL de YouTube™",
	"EventEditor_InsertYouTube_NoURL": "Por favor, introduce un URL de YouTube™ válido.",
	"EventEditor_InsertYouTube_Summary": "Versión resumida descriptiva",
	"EventEditor_InsertImage": "Insertar una imagen de la web",
	"EventEditor_InsertImage_Title": "Insertar imagen",
	"EventEditor_InsertImage_Desc": "Introduce el URL de una imagen (como .jpg, .gif o .png) para incluirla en tu publicación.",
	"EventEditor_InsertImage_URL": "URL de la imagen",
	"EventEditor_InsertImage_Placeholder": "Introduce un URL válido",
	"EventEditor_InsertImage_Anchor": "Opcional: URL que se abre al hacer clic en la imagen",
	"EventEditor_LinkDescription": "Texto que se mostrará",
	"EventEditor_LinkURL": "URL",
	"EventEditor_YouTubeVideoTitle": "Video de YouTube™: %1$s",
	"EventEditor_YouTubeVideoViews": "Reproducciones: %1$s",
	"EventEditor_Author": "Por %1$s",
	"EventEditor_Comments": "Comentarios",
	"EventEditor_UpVotes": "Votos positivos",
	"EventEditor_DownVotes": "Votos negativos",
	"Error_Message": "Mensaje de error",
	"Warning_Message": "Mensaje de advertencia",
	"Informational_Message": "Mensaje informativo",
	"Error_Description": "El error (código: %1$s) ocurrió con los siguientes detalles: (%2$s)",
	"Error_FailureNotice": "Error",
	"Error_GenericFailureDescription": "Lo sentimos, eso no ha funcionado.",
	"Image_ErrorTitle": "Error al cargar la imagen '%1$s', el posible problema incluye:",
	"Image_Error_msg1": "Verifica que la ruta de la imagen sea la correcta.",
	"Image_Error_msg2": "Comprueba si el servidor que aloja la imagen admite el acceso anónimo. La consola del navegador puede indicar un error relacionado con Access-Control-Allow-Origin si no lo hace.",
	"Image_Error_suggestion": "Puedes siempre subir la imagen a Steam para alojar el contenido de forma gratuita.",
	"Platform_Hint_Mobile": "en un dispositivo móvil",
	"Platform_Hint_BigPicture": "en Big Picture",
	"Platform_Hint_VR": "en realidad virtual",
	"Hover_SteamLevel": "Nivel de Steam",
	"Hover_BadgeXP": "%1$s EXP",
	"PersonaStateOffline": "Desconectado",
	"PersonaStateAway": "Ausente",
	"PersonaStateOnline": "Conectado",
	"PersonaStateBlocked": "Bloqueado",
	"PersonaStateInGame": "Jugando",
	"PersonaStateBusy": "Ocupado",
	"PersonaStateSnooze": "Durmiendo",
	"PersonaStateInNonSteamGame": "En un juego que no es de Steam",
	"PersonaStateWatchingBroadcast": "Viendo retransmisión:",
	"PersonaStateLookingToTrade": "Deseando intercambiar",
	"PersonaStateLookingToPlay": "Deseando jugar",
	"PersonaStateLastSeen": "Última conexión: %1$s",
	"PersonaStateLastSeen_JustNow": "Última conexión ahora mismo",
	"PersonaStateRemotePlayTogether": "Remote Play Together",
	"User_WantsToPlay": "Unirse",
	"User_ToggleDoNotDisturb": "No molestar",
	"User_GameInfoHidden": "Tus amigos no pueden ver tu estado de juego debido a tu configuración de privacidad",
	"User_LimitedAccount": "Tu cuenta no cumple con los requisitos necesarios para utilizar esta característica. Para obtener más información, visita: %1$s.",
	"User_LimitedAccount_UrlInfo": "Visita el Soporte de Steam",
	"isNickname": "Tu alias para este amigo",
	"Friend_Menu_NotAFriendLabel": "No son amigos",
	"Friend_Menu_NotAFriendRequesting": "Solicitando ser amigos",
	"DASHPlayerStats_BytesReceived": "Bytes recibidos:",
	"DASHPlayerStats_BufferingResolution": "Resolución de búfer:",
	"DASHPlayerStats_PlaybackResolution": "Resolución de reproducción:",
	"DASHPlayerStats_HtmlResolution": "Resolución de pantalla:",
	"DASHPlayerStats_DroppedFrames": "Fotogramas perdidos:",
	"DASHPlayerStats_VideoBuffered": "Video en búfer:",
	"DASHPlayerStats_AudioBuffered": "Audio en búfer:",
	"DASHPlayerStats_BandwidthRequired": "Ancho de banda necesario (Mbps):",
	"DASHPlayerStats_BandwidthVideo": "Ancho de banda de video (Mbps):",
	"DASHPlayerStats_BandwidthNums": "Ancho de banda mín./máx./med. (Mbps):",
	"DASHPlayerStats_DownloadNums": "Tiempo de descarga mín./máx./med. (segundos):",
	"DASHPlayerStats_ContentServer": "Host:",
	"DASHPlayerStats_ActiveDownloads": "Descargas activas:",
	"DASHPlayerStats_StallEvents": "Eventos de detención:",
	"DASHPlayerStats_FailedDownloads": "Eventos de descarga fallida:",
	"DASHPlayerStats_VideoDownloadProgress": "Progreso de la descarga de video:",
	"DASHPlayerStats_TimeToFirstFrame": "Tiempo hasta el primer fotograma (ms):",
	"DASHPlayerStats_DroppingFrames": "Pérdidas persistentes de fotogramas detectadas:",
	"DASHPlayerStats_CurrentFPS": "FPS actuales:",
	"DASHPlayerStats_Tracking": "Recopilando datos...",
	"DASHPlayerStats_PlaybackRate": "Velocidad de reproducción:",
	"DASHPlayerStats_VideoBufferRange": "Búfer de video %1$s:",
	"DASHPlayerStats_AudioBufferRange": "Búfer de audio %1$s:",
	"DASHPlayerStats_VideoNoRangeInformation": "No hay segmentos de video en el búfer",
	"DASHPlayerStats_AudioNoRangeInformation": "No hay segmentos de audio en el búfer",
	"DASHPlayerControls_GoLive": "Transmitir en tiempo real",
	"DASHPlayerControls_IsLive": "En vivo",
	"DASHPlayerControls_ClickToPlay": "Haz clic para reproducir",
	"DASHPlayerControls_IsReplay": "VOLVER A RETRANSMITIR",
	"DASHPlayerControls_Start": "Iniciar",
	"DASHPlayerControls_End": "Finalizar",
	"Played_Minutes": "%1$s minutos",
	"Played_Hours": "%1$s horas",
	"WriteReview_Dialog_PostReview": "Publicar reseña",
	"WriteReview_Dialog_ReviseReview": "Revisar reseña",
	"WriteReview_Dialog_Title": "Reseña",
	"WriteReview_Dialog_Playtime": "Has jugado durante %1$s",
	"WriteReview_Dialog_Playtime_Software": "Usaste este título durante %1$s",
	"WriteReview_Dialog_Playtime_Revise": "Has jugado %1$s más",
	"WriteReview_Dialog_RecommendGame": "¿Recomendarías este juego a otros jugadores?",
	"WriteReview_Dialog_RecommendGame_Software": "¿Recomendarías este software a otros jugadores?",
	"WriteReview_Dialog_RecommendGame_Revise": "¿Te gustaría revisar tu reseña?",
	"WriteReview_Dialog_GetHelp_Btn": "Obtén ayuda con tu compra",
	"WriteReview_Dialog_Visibility": "Visibilidad:",
	"WriteReview_Dialog_Public": "Pública",
	"WriteReview_Dialog_Friends": "Solo amigos",
	"WriteReview_Dialog_Yes": "Sí",
	"WriteReview_Dialog_No": "No",
	"WriteReview_Dialog_GetSupport_Btn": "Obtén ayuda con tu compra",
	"WriteReview_Dialog_GetSupport_Desc": "Obtén asesoramiento técnico, atención al cliente oficial o solicita un reembolso.",
	"WriteReview_Dialog_AddReview_Btn": "Publicar una reseña",
	"WriteReview_Dialog_AddReview_Desc": "Comparte tus pensamientos con otros jugadores.",
	"WriteReview_Dialog_AddReview_Header": "¿Te gustaría publicar una reseña?",
	"WriteReview_Dialog_ReviewInstructions_Link": "Normas y directrices",
	"WriteReview_Dialog_ReviewInstructions": "Describe lo que te gustó o no de este producto y si lo recomiendas a otros. Por favor, recuerda ser cortés y sigue las %1$s. Se requiere una descripción para publicar tu recomendación.",
	"WriteReview_Dialog_AllowComments": "Permitir comentarios",
	"WriteReview_Dialog_FreeDisclaimer": "Marca esta casilla si recibiste el producto de forma gratuita",
	"WriteReview_Dialog_FreeDisclaimer_Tooltip": "Marca esta casilla si recibiste el producto de forma gratuita. Junto a tu reseña podrá leerse \"Producto recibido de forma gratuita\". Si has recibido una compensación adicional por reseñar este juego, debes indicarlo en el texto de la reseña.",
	"WriteReview_Dialog_FormattingHelp": "Ayuda sobre formato",
	"WriteReview_Dialog_GenericError": "Hemos encontrado un problema al publicar tu reseña. Por favor, inténtalo de nuevo más tarde.",
	"WriteReview_Dialog_NoTextError": "Por favor, describe lo que te ha gustado o no de este producto.",
	"WriteReview_Dialog_Delay": "Quizás más tarde",
	"Broadcast_View_Stack_H": "Vista horizontal",
	"Broadcast_View_Stack_V": "Vista vertical",
	"Broadcast_View_Theater": "Modo cine",
	"Broadcast_View_Fullscreen": "Pantalla completa",
	"Broadcast_View_HideChat": "Ocultar chat",
	"Broadcast_View_ShowBothChats": "Mostrar ambos chats",
	"Broadcast_View_ShowSingleChats": "Mostrar un solo chat",
	"Broadcast_View_ShowChat": "Mostrar chat",
	"Broadcast_Store_FreeToPlay": "Free to Play",
	"PartnerEvent_1": "Otro evento",
	"PartnerEvent_2": "Evento del juego",
	"PartnerEvent_3": "Evento del grupo",
	"PartnerEvent_4": "Evento de reunión",
	"PartnerEvent_5": "Causa benéfica",
	"PartnerEvent_6": "Evento musical y artístico",
	"PartnerEvent_7": "Evento deportivo",
	"PartnerEvent_8": "Evento de viaje en directo",
	"PartnerEvent_9": "Chatear",
	"PartnerEvent_9_editor": "Una sesión de chat o \"pregúntame lo que sea\"",
	"PartnerEvent_10": "Lanzamiento del juego",
	"PartnerEvent_10_editor": "¡Juego ya disponible!",
	"PartnerEvent_11": "Retransmisión en directo",
	"PartnerEvent_12": "Actualización menor (notas de parche)",
	"PartnerEvent_13": "Actualización normal",
	"PartnerEvent_14": "Actualización importante",
	"PartnerEvent_15": "Lanzamiento de DLC",
	"PartnerEvent_16": "Próximo lanzamiento",
	"PartnerEvent_16_editor": "El juego se lanzará en una fecha específica",
	"PartnerEvent_17": "Retransmisión de torneo eSport",
	"PartnerEvent_18": "Difusión de retransmisión de desarrollador",
	"PartnerEvent_19": "Retransmisión famosa",
	"PartnerEvent_20": "Descuento en juego",
	"PartnerEvent_20_editor": "Descuento en este juego",
	"PartnerEvent_21": "Descuento en artículo o DLC",
	"PartnerEvent_21_editor": "Descuento en artículos en el juego o DLC",
	"PartnerEvent_22": "Potenciador de EXP",
	"PartnerEvent_23": "Evento de botín",
	"PartnerEvent_24": "Evento con incentivos",
	"PartnerEvent_25": "Evento de desafío",
	"PartnerEvent_26": "Concurso",
	"PartnerEvent_27": "Evento de IRL",
	"PartnerEvent_27_editor": "Asistir a una exposición, reunión o convención",
	"PartnerEvent_28": "Noticias",
	"PartnerEvent_28_editor": "Anuncio / Noticias",
	"PartnerEvent_29": "Lanzamiento de versión beta",
	"PartnerEvent_29_editor": "Invitación a la beta / noticias",
	"PartnerEvent_30": "Lanzamiento de contenido en el juego",
	"PartnerEvent_31": "Prueba gratuita",
	"PartnerEvent_32": "Lanzamiento del pase de batalla o de temporada",
	"PartnerEvent_33": "Actualización de temporada",
	"PartnerEvent_34": "Promoción cruzada",
	"PartnerEvent_35": "Evento general en el juego",
	"PartnerEvent_Other": "Otro evento",
	"PartnerEvent_SteamAwardNominations": "Solicitud de nominación para los Premios Steam",
	"PartnerEvent_SteamAwardVoteRequest": "Solicitud de voto de los Premios Steam",
	"SocialMedia_Type_ShortName_1": "Steam",
	"SocialMedia_Type_ShortName_2": "Google",
	"SocialMedia_Type_ShortName_3": "Facebook",
	"SocialMedia_Type_ShortName_4": "Twitter",
	"SocialMedia_Type_ShortName_5": "Twitch",
	"SocialMedia_Type_ShortName_6": "YouTube",
	"SocialMedia_Type_ShortName_7": "Facebook",
	"MobileLogin_NoSteamAccount": "¿No tienes una cuenta de Steam?",
	"MobileLogin_CreateAccount": "Crear una cuenta gratuita",
	"MobileLogin_ForgotPassword": "¿Has olvidado tu nombre de cuenta o contraseña?",
	"MobileLogin_RefreshCaptcha": "Actualizar",
	"MobileLogin_SignIn": "Iniciar sesión",
	"MobileLogin_SigningIn": "Iniciando sesión",
	"MobileLogin_AccountName": "Nombre de la cuenta de Steam",
	"MobileLogin_Password": "Contraseña",
	"MobileLogin_CaptchaVerification": "Verificación",
	"MobileLogin_Enter2FA": "Introduce el código generado en la sección Steam Guard de tu aplicación Steam Mobile.",
	"MobileLogin_Enter2FAHelp": "No puedo acceder a mi código de Steam Guard",
	"MobileLogin_EnterSteamguard": "No he recibido el correo electrónico de Steam Guard",
	"MobileLogin_SteamguardCode": "Código de Steam Guard",
	"MobileLogin_SteamguardSubmit": "Enviar e iniciar sesión",
	"MobileLogin_SentSteamguard_1": "Hemos enviado un mensaje a tu",
	"MobileLogin_SentSteamguard_2": "correo electrónico. Introduce el código de Steam Guard proporcionado.",
	"MobileLogin_IncorrectSteamGuard": "El código de Steam Guard introducido es incorrecto. Comprueba el código e inténtalo de nuevo.",
	"MobileLogin_Error_RateLimitExceeded": "Se han realizado demasiados intentos de inicio de sesión fallidos desde tu red en un corto período de tiempo. Por favor, espera y vuelve a intentarlo más tarde.",
	"Login_SignIn": "Iniciar sesión",
	"Login_SigningIn": "Iniciando sesión",
	"Login_AccountName": "Nombre de la cuenta de Steam",
	"Login_Password": "Contraseña",
	"Login_RememberMe": "Recordarme en este equipo",
	"Login_ForgotPassword": "¿Has olvidado tu nombre de cuenta o contraseña?",
	"Login_NoSteamAccount": "¿No tienes una cuenta de Steam?",
	"Login_CreateAccount": "Crear una cuenta de forma gratuita",
	"Login_CaptchaVerification": "Demuestra que eres un ser humano introduciendo de nuevo los caracteres en el captcha.",
	"Login_RefreshCaptcha": "Actualizar",
	"Login_Enter2FA": "Introduce el código generado en la sección Steam Guard de tu aplicación Steam Mobile.",
	"Login_Enter2FAHelp": "No puedo acceder a mi código de Steam Guard",
	"Login_EnterSteamguard": "No he recibido el correo electrónico de Steam Guard",
	"Login_SteamguardSubmit": "Enviar e iniciar sesión",
	"Login_SentSteamguard": "Hemos enviado un mensaje a tu correo electrónico %1$s. Introduce el código de Steam Guard proporcionado en él.",
	"Login_SignOut": "Cerrar sesión",
	"Emoticon_Search": "Buscar emoticonos",
	"Chat_Settings_Error_ChatFileTooLarge": "%1$s es demasiado grande (10 MB máximo).",
	"Chat_Settings_Error_ChatFileTypeNotSupported": "No se puede cargar %1$s.  Solo se admiten los tipos de archivo jpg, png, gif, webm, mpg y ogv.",
	"ConnectionTrouble_FailedToConnect": "No se pudo conectar a Steam",
	"Chat_Upload_ErrorCloud": "Error al cargar los datos de la imagen en el servidor de la nube.",
	"Chat_Settings_Error_ServerError": "Se produjo un error en el servidor",
	"Broadcast_ViewerCount": "%1$s espectadores",
	"Broadcast_VideoContext_ToggleStats": "Alternar estadísticas técnicas",
	"Broadcast_VideoContext_OpenStore": "Visitar tienda",
	"Broadcast_None": "Ninguna",
	"BroadcastWatch_MinBrowser": "Tu navegador no cumple los requisitos mínimos para ver esta retransmisión",
	"BroadcastWatch_RequestFailed": "No se pudo cargar esta retransmisión",
	"BroadcastWatch_NotAvailable": "Este emisor está desconectado",
	"BroadcastWatch_WaitingForResponse": "Esperando aprobación para ver",
	"BroadcastWatch_WaitingForStart": "Esta retransmisión está empezando",
	"BroadcastWatch_WaitingForReconnect": "Reconectándose a esta retransmisión",
	"BroadcastWatch_ServerLoad": "Steam está experimentando una alta carga de retransmisiones y actualmente no puede reservar un puesto en el servidor para iniciar esta retransmisión. Inténtalo de nuevo dentro de unos minutos.",
	"BroadcastWatch_SystemNotSupported": "La retransmisión de Steam no es compatible actualmente con el sistema de este emisor",
	"BroadcastWatch_UserRestricted": "Este emisor tiene actualmente restringida la retransmisión en Steam",
	"BroadcastWatch_PoorUploadQuality": "Este emisor no puede mantener actualmente una conexión estable de retransmisión con Steam",
	"BroadcastChat_Reconnected": "Reconectado al chat",
	"BroadcastChat_UnableToJoinChat": "No se pudo unirse al chat",
	"BroadcastChat_NeverTell": "Nunca reveles to contraseña a nadie",
	"BroadcastChat_EnterResponse": "Escribe para chatear",
	"BroadcastChat_InsertEmoticon": "Insertar emoticono",
	"BroadcastChat_Send": "Enviar",
	"BroadcastChat_UserJoined": "%1$s se unió al chat",
	"BroadcastChat_UserLeft": "%1$s abandonó el chat",
	"BroadcastChat_UserMuted": "%1$s fue silenciado en esta sala de chat",
	"BroadcastChat_UserMutedLocal": "%1$s fue silenciado",
	"BroadcastChat_UserUnmutedLocal": "%1$s ya no está silenciado",
	"BroadcastChat_UserMuteFailed": "Error al silenciar a %1$s. Inténtalo de nuevo.",
	"BroadcastChat_RemoveMessagesFailed": "Error al eliminar los mensajes para %1$s. Inténtalo de nuevo.",
	"BroadcastChat_UserUnmuteFailed": "Error al dejar de silenciar a %1$s. Inténtalo de nuevo.",
	"BroadcastChat_YouMuted": "Has sido silenciado y no puedes publicar mensajes en este chat",
	"BroadcastChat_FailedToSendMsg": "Error al enviar mensaje de chat: %1$s",
	"BroadcastChat_Cooldown": "Estás enviado mensajes muy rápido. Inténtalo de nuevo en %1$s segundos.",
	"BroadcastChat_Mute": "Silenciar",
	"BroadcastChat_Unmute": "Dejar de silenciar",
	"BroadcastChat_MuteLocal": "Silenciar localmente",
	"BroadcastChat_UnmuteLocal": "Dejar de silenciar localmente",
	"BroadcastChat_Login": "Iniciar sesión para unirse al chat",
	"BroadcastChat_LimitedUser": "Acceso a chat limitado",
	"BroadcastChat_RemoveMessages": "Eliminar mensajes de este usuario",
	"BroadcastChat_Blocked": "Únicamente los dueños del juego pueden enviar mensajes de chat durante esta retransmisión.",
	"BroadcastChat_half_Mute": "Silenciar usuario por 12 horas",
	"BroadcastChat_day_Mute": "Silenciar usuario por un día",
	"BroadcastChat_week_Mute": "Silenciar usuario por una semana",
	"BroadcastChat_perm_Mute": "Silenciar usuario de forma permanente",
	"BroadcastChat_half_Shadow": "Silenciar usuario de forma invisible por 12 horas",
	"BroadcastChat_day_Shadow": "Silenciar usuario de forma invisible por un día",
	"BroadcastChat_week_Shadow": "Silenciar usuario de forma invisible por una semana",
	"BroadcastChat_perm_Shadow": "Silenciar usuario de forma invisible permanentemente",
	"BroadcastChat_Add_Moderator": "Hacer moderador a este usuario",
	"BroadcastChat_Remove_Moderator": "Quitar el rol de moderador del usuario",
	"BroadcastChat_Change_Moderator_Title": "Cambiar el rol de moderador del usuario",
	"BroadcastChat_Change_Add_Confirm": "¿Seguro que quieres añadir a este usuario como moderador? Podrá silenciar a otros usuarios en el chat de retransmisión.",
	"BroadcastChat_Change_Remove_Confirm": "¿Seguro que quieres quitar a este usuario como moderador?",
	"BroadcastChat_Tooltip_Show_Chat_Viewers": "Mostrar una lista de las personas que están actualmente en la ventana del chat.",
	"BroadcastChat_Tooltip_Minimize_Chat": "Minimizar la ventana del chat",
	"BroadcastChat_Tooltip_Maximize_Chat": "Maximizar la ventana del chat",
	"BroadcastChat_Tooltip_Popout_Chat": "Abrir el chat en una ventana nueva",
	"BroadcastChat_ChatOnly_Title": "Solo el chat de la retransmisión",
	"BroadcastChat_DefaultMessage": "¡Te damos la bienvenida al chat!",
	"BroadcastChat_Moderator": "Moderador",
	"BroadcastChat_Broadcaster": "Comentarista",
	"ChatEntryButton_Submit": "Enviar",
	"ChatEntryButton_Emoticon": "Selector de emoticonos",
	"ChatEntryButton_Flair": "Elegir una insignia",
	"ChatEntryButton_SendEmbed": "Enviar elemento especial",
	"Store_AddToCart": "Añadir al carrito",
	"YouTubePlayer_Loading": "Cargando YouTube...",
	"home_page_live_broadcast": "En directo",
	"StoreBroadcast_Hide_Tooltip": "Mostrar u ocultar la retransmisión en directo",
	"StoreBroadcast_Detault_popout_Title": "Retransmisión en curso",
	"StoreBroadcast_close_broadcast_popup": "Cierra la ventana de la retransmisión, que no volverá a abrirse durante esta sesión.",
	"StoreBroadcast_Change_store_Broadcast_settings": "Cambiar la configuración de la retransmisión",
	"Broadcast_Embedded_viewer": "%1$s espectador",
	"Broadcast_Embedded_viewer_Plural": "%1$s espectadores",
	"BroadcastWatch_View_Broadcast_Page": "Ver la página de retransmisión",
	"Broadcast_Embed_Watch_SteamTV": "Ver en Steam.tv",
	"Broadcast_Embed_Watch_With_Frieds_SteamTV": "Ver y chatear con amigos en Steam.tv",
	"sale_three_section_hide_chat": "Ocultar chat",
	"sale_three_section_show_chat": "Mostrar chat",
	"btn_live_streams_all": "Ver todas",
	"Broadcast_default_title_dev": "Retransmisión en curso: Observa al desarrollador jugar",
	"Broadcast_default_title_community": "Retransmisión en curso: Observa a la comunidad jugar",
	"Broadcast_default_title_comp": "Retransmisión en curso: Mira esta partida competitiva",
	"Broadcast_default_title_speed": "Retransmisión en curso: Mira este speedrun",
	"Sale_BundleSave": "Incluye %1$s artículos.",
	"Sale_PackageSave": "Incluye %1$s artículos.",
	"Sale_ShowContents": "Mostrar contenido",
	"Sale_ShowMore": "Mostrar más",
	"Sale_ShowLess": "Mostrar menos",
	"Sale_OnWishlist": "En tu lista de deseados",
	"Sale_InLibrary": "En la biblioteca",
	"Sale_HiddenItems": "Hay %1$s objeto(s) ocultos debido a %2$s",
	"Sale_HiddenItem_Single": "%1$s artículo está oculto debido a %2$s",
	"Sale_StorePreferences": "tus preferencias de la tienda",
	"Sale_SeeAllSpecials": "Ver todos los especiales",
	"Sale_AddToWishlist": "Añadir a la lista de deseados",
	"Sale_RemoveFromWishlist": "Eliminar de la lista de deseados",
	"Sale_Preferences": "Preferencias",
	"Sale_PlaceHolder": "Modo de vista previa: Esta sección no tiene cápsulas. No aparecerá en la página del usuario si está vacía.",
	"Sale_SmartPlaceHolder": "Modo de vista previa: Esta sección inteligente no tiene aplicaciones para ti. No aparecerá en la página del usuario si está vacía.",
	"Sale_default_label": "(sin título)",
	"Sale_default_label_OnSale": "En oferta",
	"Sale_default_label_TopSellers": "Lo más vendido",
	"Sale_default_label_FreeToPlay": "Free to Play",
	"Sale_default_label_HorrorGames": "Juegos de terror",
	"Sale_default_label_HorrorVR": "Terror en la RV",
	"Sale_default_label_HorrorFreeToPlay": "Terror Free to Play",
	"Sale_default_label_HalloweenEventsHorror": "Eventos de Halloween en juegos de terror",
	"Sale_default_label_HalloweenEventsNonHorror": "Eventos de Halloween en juegos que no son de terror",
	"Sale_default_label_MoreHalloweenEvents": "Más eventos de Halloween",
	"Sale_default_label_MoreHalloweenEventsNonHorror": "Más eventos de Halloween en juegos que no son de terror",
	"Sale_default_label_NewAndUpcomingHorror": "Nuevos y próximos lanzamientos de terror",
	"Sale_default_label_RemotePlay_Together": "Play Together - Con amigos en la distancia",
	"Sale_default_label_RemotePlay_Phone": "Play Anywhere - En tu teléfono",
	"Sale_default_label_RemotePlay_Tablet": "Play Anywhere - En tu tableta",
	"Sale_default_label_RemotePlay_TV": "Play Anywhere - En tu TV",
	"Sale_default_label_OnYourWishlist": "En tu lista de deseados",
	"Sale_default_label_RecommendedForYou": "Recomendado para ti",
	"Sale_default_label_ComingSoon": "Próximamente",
	"Sale_default_label_JustAnnounced": "Recién anunciados",
	"Sale_default_label_JustUpdated": "Recién actualizados",
	"Sale_default_label_FreeWeekend": "Fin de semana gratis",
	"Sale_default_label_FreeWeek": "Semana gratis",
	"Sale_default_label_PrePurchase": "Precómpralo ahora",
	"Sale_default_label_NewReleases": "Nuevos lanzamientos",
	"Sale_default_label_JustReleased": "Recién lanzados",
	"Sale_default_label_Highlighted": "Ofertas destacadas",
	"Sale_default_label_BackCat": "Catálogo anterior",
	"Sale_default_label_PlayForFree": "¡Juega gratis!",
	"Sale_defautl_label_FreeToKeep": "Por tiempo limitado, instálalo ahora y quédatelo para siempre",
	"SalePage_LoginPrompt": "Inicia sesión para ver artículos adicionales seleccionados solo para ti.",
	"SalePage_ParentApp_DLC": "DLC para",
	"SalePage_ParentApp_SoundTrack": "Banda sonora para",
	"SalePage_WatchForDrop_Minutes_Developer": "Mira el directo por %1$s minutos y consigue objetos aleatorios del desarrollador cuando el evento termine.",
	"SalePage_WatchForDrop_Minutes_CreatorNamed": "Mira el directo por %1$s minutos y consigue objetos aleatorios de %2$s cuando el evento termine.",
	"SalePage_WatchForDrop_Hours_Developer": "Mira el directo por %1$s horas y consigue objetos aleatorios del desarrollador cuando el evento termine.",
	"SalePage_WatchForDrop_Hours_CreatorNamed": "Mira el directo por %1$s horas y consigue objetos aleatorios de %2$s cuando el evento termine.",
	"SalePage_WatchForDrop_LearnMore": "Obtener más información sobre los objetos aleatorios aquí.",
	"SalePage_Admin_SaleEventDay": "Ver el día de las rebajas %1$s",
	"Steam_Settings_Compat_Launch_Prefix": "Funciona en este equipo por medio de",
	"Steam_Settings_Compat_Launch_Name": "Steam Play.",
	"Steam_Settings_Compat_Launch_Forced": "seleccionado por ti para este título.",
	"Steam_Settings_Compat_Launch_Wildcard": "seleccionado por ti para todos los títulos.",
	"Steam_Settings_Compat_Launch_Whitelisted": "seleccionado por las pruebas de Valve.",
	"SteamAwards_EventMainTitle": "Los Premios Steam",
	"SteamAwards_EventMainTitleSecondLine": "Nominado",
	"SteamAwards_EventCallToAction": "Este mes de diciembre",
	"SteamAwards_EventVotingDateTeaser": "Diciembre 2019",
	"SteamAwards_EventVoteForGamePrompt": "Haz clic a continuación para votar por %1$s en la categoría:",
	"SteamAwards_EventNominateGamePrompt_Long": "Nomina a %1$s para la siguiente categoría, según lo sugerido por los desarrolladores de este juego, o selecciona una categoría diferente",
	"SteamAwards_EventNominateGamePrompt_NoCategory": "Haz clic aquí para nominar a %1$s para una categoría en la página de los Premios Steam.",
	"SteamAwards_Event_NominationsClosed": "Las nominaciones se han cerrado. Vota durante las rebajas de invierno. Los ganadores se anunciarán el 31 de diciembre.",
	"SteamAwards_Event_VotesClosed": "La votación ha terminado. Haz clic aquí para ver los resultados.",
	"SteamAwards_EventNominateGamePrompt_CategoryPrefix": "Nominar como:",
	"SteamAwards_EventNominationAlternativeLinkText": "O elige otra categoría",
	"SteamAward_CategoryTitle_none": "Sin categoría",
	"SteamAward_CategoryDesc_none": "No sugieras una categoría específica, en su lugar, permite que tus fans elijan la categoría que creen que mejor se adapta a tu juego. El evento aún incluirá un enlace a la página de nominaciones.",
	"SteamAward_CategoryTitle_goty": "Juego del año 2019",
	"SteamAward_CategoryDesc_goty": "Tal vez fue su jugabilidad inmersiva, o su apasionante historia... sus personajes bien diseñados, su diseño impecable o el multijugador adictivo. Cualquiera que sea la razón, el ganador del Premio al Juego del año es un clásico instantáneo.",
	"SteamAward_CategoryTitle_vrgoty": "Juego de RV del año 2019",
	"SteamAward_CategoryDesc_vrgoty": "Cuando se trata de abrir nuevos caminos en los juegos, no hay mayor ritmo de avance que en la realidad virtual. Si nos saliéramos con la nuestra, todos los desarrolladores de realidad virtual obtendrían un premio por construir el futuro de los juegos inmersivos y las experiencias que no tienen igual en cualquier otro medio. Pero como solo hay un trofeo, depende de ti, como miembro del comité de selección de los Premios Steam, coronar a uno solo como el mejor del año.",
	"SteamAward_CategoryTitle_love": "Con amor y dedicación 2019",
	"SteamAward_CategoryDesc_love": "Este juego lleva tiempo que salió. El equipo ya pasó la primera presentación de su bebé creativo, pero siendo los buenos padres que son, estos desarrolladores continúan trabajando y apoyando a su creación. Este juego, hasta el día de hoy, sigue recibiendo nuevo contenido después de todos estos años.",
	"SteamAward_CategoryTitle_friends": "Mejor con amigos 2019",
	"SteamAward_CategoryDesc_friends": "Hay algunos juegos que no son igual de entretenidos cuando los juegas solo. Quizás necesites tener un amigo que te vigile la espalda. Tal vez necesites tener un amigo que puedas apuñalar por la espalda. De cualquier manera, la diversión espera a quienes se reúnen con sus amigos para jugar estos juegos.",
	"SteamAward_CategoryTitle_gameplay": "Jugabilidad más innovadora",
	"SteamAward_CategoryDesc_gameplay": "Este juego está al frente en los conceptos de experimentación, rompiendo las fronteras del medio con interacciones emocionantes, novedosas y con sorpresas prometedoras. ¡Este juego se sale fuera de lo común y te sacará a ti con él!",
	"SteamAward_CategoryTitle_storyrich": "Juego con una historia genial",
	"SteamAward_CategoryDesc_storyrich": "Algunos días, solo un juego con mucha narración dará en el clavo, y este tiene un gran éxito. Es tan apasionante como cualquier telenovela y tan bien afinado como un guion de TV de prestigio. Bravísimo: ¡por hacernos sentir así!",
	"SteamAward_CategoryTitle_yousuck": "El mejor juego que no sabes jugar",
	"SteamAward_CategoryDesc_yousuck": "Los juegos son capaces de empujarnos más allá de cualquier límite que pensáramos que teníamos. Como en una secuencia de montaje, les dedicamos esfuerzo, entrenando nuestros dedos para que sean rápidos y hábiles, aprendiendo a dominar los tiempos y la colocación durante semanas y semanas. Al final de la lucha, somos recompensados con profunda belleza y un hondo sentimiento de crecimiento personal. A menos que hayas tirado el monitor por la ventana el primer día.",
	"SteamAward_CategoryTitle_visual": "Estilo visual excepcional",
	"SteamAward_CategoryDesc_visual": "Estos desarrolladores son los Willy Wonka de los video juegos. El estilo visual no aspira a la fidelidad gráfica de la vida real (aunque es noble objetivo en sí mismo)… describe un aspecto y un comportamiento distintivos que impregnan un juego por completo. Este título muestra una cohesión visual y una expresión que no solo encajan en el mundo del juego, sino que hacen que el nuestro parezca miserable en comparación.",
	"SteamAward_NominationConflictWarning_Title": "¿Quieres cambiar tu nominación?",
	"SteamAward_NominationConflictWarning_Explanation": "Solo puedes nominar un juego por cada categoría, y ya nominaste a %1$s para esta. ¿Quieres nominar a %2$s en su lugar?",
	"SteamAward_VoteButton_PromptText": "Votar",
	"SteamAward_VoteButton_AlreadyVotedText": "Voto enviado",
	"SteamAward_VoteConflictWarning_Title": "¿Quieres cambiar tu voto?",
	"SteamAward_VoteConflictWarning_Explanation": "Solo puedes votar por un juego en cada categoría y ya votaste por %1$s en esta. ¿Quieres cambiar tu voto a %2$s?",
	"Store_VR_Support_OnlyVR": "Solo RV",
	"Store_VR_Support_SupportsVR": "Soporte para RV",
	"Giveaway_CountDown": "¡Quedan %1$s hasta el próximo sorteo!",
	"Giveaway_CountDown2": "Tiempo restante hasta el próximo sorteo.",
	"Giveaway_KeepWatching": "¡Sigue mirando para tener la oportunidad de ganar!",
	"Giveaway_RandomDraw": "Sorteo en curso",
	"Giveaway_Congratulation": "¡%1$s ganadores afortunados hasta ahora!",
	"Giveaway_Closed_NoWinnerInfo": "Ya finalizó el sorteo, gracias por participar.",
	"Giveaway_Closed": "El sorteo finalizó con %1$s ganadores afortunados, gracias por participar.",
	"Giveaway_LearnMore": "Haz clic para obtener más información sobre los premios, los ganadores y las reglas",
	"Lunar2020_CheckBackEachDay": "¡Regresa cada día para obtener un nuevo regalo del Emperador!",
	"Lunar2020_CheckBackEachDayForStory": "Vuelve cada día para ver un nuevo capítulo",
	"Lunar2020_FirstGift": "Primer regalo",
	"Lunar2020_SecondGift": "Segundo regalo",
	"Lunar2020_ThirdGift": "Tercer regalo",
	"Lunar2020_FourthGift": "Cuarto regalo",
	"Lunar2020_GiftWasOpened": "abierto",
	"Lunar2020_RereadStory": "mostrar historia",
	"Lunar2020_GiftCanBeOpenedNow": "abrir ahora",
	"Lunar2020_GiftCanBeOpenedAfterThePreviousOne": "abrir siguiente",
	"Lunar2020_GiftLockedUntilDate": "abrir %1$s",
	"Lunar2020_ErrorLoadingVideo": "Por favor, utiliza un navegador compatible con videos HTML para abrir el sobre.",
	"Lunar2020_LinkBackToSale": "Volver a las rebajas",
	"Lunar2020_LinkFromVideoToMarket": "Visitar el mercado ahora",
	"Lunar2020_ReceivedNumberOfTokens": "Recibiste %1$s fichas",
	"Lunar2020_YourBalancePrefix": "Tu saldo",
	"Lunar2020_BalanceNumberOfTokens": "%1$s fichas",
	"Lunar2020_LimitedUserDialogTitle": "No se puede abrir el sobre",
	"Lunar2020_StoryTitle": "LA GRAN CARRERA DEL EMPERADOR",
	"Lunar2020_StorySubTitle": "El origen del horóscopo chino",
	"Lunar2020_StoryDayOneHeader": "Parte I de IV",
	"Lunar2020_StoryDayTwoHeader": "Parte II de IV",
	"Lunar2020_StoryDayThreeHeader": "Parte III de IV",
	"Lunar2020_StoryDayFourHeader": "Parte IV de IV",
	"Lunar2020_StoryDayOne": "El Emperador de Jade invocó a todas las criaturas de su reino a competir en una carrera hacia la corte celestial declarando que los primeros doce en llegar serían honrados con un lugar en su nuevo calendario.\n\nLa inteligente rata fue la primera en llegar al dominio celestial. Como no le gustaba nadar, se subió al lomo del confiable buey, saltando entusiasmada al jardín celestial del emperador justo antes de que el buey llegara a la orilla.\n\nEl constante Buey cruzó el río con facilidad. Sin preocuparse por los resultados de la carrera, el buey se sentía satisfecho con su papel en el éxito de la rata.",
	"Lunar2020_StoryDayTwo": "El autosuficiente tigre viajó con demasiado cuidado para superar al buey, pensando que quedar tercero era mejor que nada.\n\nEl veloz conejo saltó sobre un tronco flotando sin rumbo, pero la suerte le sonrió ya que un viento útil lo impulsó con seguridad en su rumbo.\n\nLa perspectiva del dragón volador reveló a una aldea en necesidad, así que se detuvo para ayudar, incluso hasta para regalarle una ráfaga de viento al conejo en el río. El honor era mucho más importante que la victoria y el dragón encontró que la quinta posición le iba bien.",
	"Lunar2020_StoryDayThree": "La sigilosa serpiente no estaba muy interesada en esforzarse demasiado, así que se enrolló alrededor de una de las pezuñas delanteras del caballo sin que nadie lo notara.\n\nMientras el caballo galopaba hacia la meta, la serpiente se desenrolló, asustando al corcel lo suficiente como para arrastrarse hacia la sexta posición con el temeroso caballo trotando inmediatamente detrás de ella.",
	"Lunar2020_StoryDayFour": "La oveja, el mono y el gallo trabajaron juntos, pero dejaron que la oveja reclamara la octava posición como recompensa por la ayuda durante el viaje. El mono obtuvo la novena posición y el gallo la décima, orgulloso de que el orden fuera justo.\n\nEl juguetón perro estaba más interesado en jugar en el agua que en ganar, por lo que terminó siendo el undécimo: un buen negocio considerando toda la diversión.\n\nEn la duodécima posición, llegó el cerdo, que se había detenido para comer y dormir; siendo lo suficientemente sabio como para saber que cada animal tendría su momento con el emperador.",
	"SteamChina_PendingPersonaName": "Los cambios en el perfil tendrán efecto tras su revisión",
	"Legal_Footer_WithYear": "© %1$s Valve Corporation. Todos los derechos reservados. Todas las marcas registradas pertenecen a sus respectivos dueños en EE. UU. y otros países.",
	"shared_dummy": "dont translate"
}
