{
	"language": "greek",
	"Button_Append": "Προσάρτηση",
	"Button_Cancel": "Άκυρο",
	"Button_Close": "Κλείσιμο",
	"Button_Clone": "Κλωνοποίηση",
	"Button_Confirm": "Επιβεβαίωση",
	"Button_Copy": "Αντιγραφή",
	"Button_CopyClipboard": "Αντιγραφή στο πρόχειρο",
	"Button_CopyLink": "Αντιγραφή συνδέσμου",
	"Button_Continue": "Συνέχεια",
	"Button_Create": "Δημιουργία",
	"Button_Delete": "Διαγραφή",
	"Button_Discuss": "Συζήτηση",
	"Button_Dismiss": "Απόρριψη",
	"Button_Edit": "Επεξεργασία",
	"Button_Learn": "Μάθετε περισσότερα εδώ",
	"Button_Publish": "Δημοσίευση",
	"Button_Post": "Ανάρτηση",
	"Button_OK": "Εντάξει",
	"Button_Overwrite": "Αντικατάσταση",
	"Button_Retry": "Επανάληψη",
	"Button_Remove": "Αφαίρεση",
	"Button_Save": "Αποθήκευση",
	"Button_Saved": "Αποθηκεύτηκε",
	"Button_Share": "Κοινοποίηση",
	"Button_Update": "Ενημέρωση",
	"Button_SaveAndContinue": "Αποθήκευση και συνέχεια",
	"Button_Follow": "Ακολούθηση",
	"Button_Followed": "Ακολουθείται",
	"Button_Ignore": "Αγνόηση",
	"Button_Ignored": "Σε αγνόηση",
	"Button_NotifyMe": "Να ειδοποιούμαι",
	"Button_NotInterested": "Δεν ενδιαφέρομαι",
	"Button_RateUp": "Θετική ψήφος",
	"Button_ViewPage": "Προβολή σελίδας",
	"Button_Accept": "Αποδοχή",
	"Button_Reject": "Απόρριψη",
	"ToolTip_CopyLinkToClipboard": "Αντιγραφή συνδέσμου στο πρόχειρο",
	"Input_Error_NumberTooSmall": "Αριθμός πολύ μικρός.",
	"Input_Error_NumberTooLarge": "Αριθμός πολύ μεγάλος.",
	"Input_Error_MustBeURL": "Το πεδίο δεν είναι έγκυρο URL.",
	"Input_Error_MustBeEmail": "Το πεδίο δεν είναι έγκυρο email.",
	"Input_Error_MustBeNumber": "Το πεδίο πρέπει να είναι αριθμός.",
	"Loading": "Φόρτωση...",
	"Updating": "Ενημέρωση...",
	"Uploading": "Μεταφόρτωση...",
	"Settings": "Ρυθμίσεις",
	"FriendSettings_AlwaysNewChatWindow": "Άνοιγμα πάντα νέου παραθύρου αντί για μια καρτέλα",
	"g_DisabledOnWeb": "ΜΗ ΔΙΑΘΕΣΙΜΟ ΣΕ ΔΙΑΔΙΚΤΥΑΚΗ ΕΚΔΟΣΗ",
	"VoiceTransmissionType_Disabled": "Ανοικτό μικρόφωνο μόνο για διαδικτυακή έκδοση",
	"VoiceVolume": "ΕΝΤΑΣΗ",
	"VoiceSetupHeader": "Εγκατάσταση και δοκιμή φωνής",
	"VoiceStartLocalMicTest": "Έναρξη δοκιμής μικροφώνου",
	"VoiceStopLocalMicTest": "Λήξη δοκιμής μικροφώνου",
	"VoiceWhenMicIsWorking": "Αν το μικρόφωνό σας λειτουργεί τότε θα πρέπει να ακούτε και τον εαυτό σας και να βλέπετε τη χρωματιστή μπάρα δίπλα από την εικόνα προφίλ σας να κινείται καθώς μιλάτε.",
	"VoiceDevice": "ΣΥΣΚΕΥΗ ΕΙΣΟΔΟΥ ΦΩΝΗΣ",
	"VoiceOutputDevice": "ΣΥΣΚΕΥΗ ΕΞΟΔΟΥ ΦΩΝΗΣ",
	"VoiceInputGain": "Ένταση φωνής",
	"VoiceInputGainExplainer": "(Το μικρόφωνο μου)",
	"VoiceOutputGain": "Ένταση εξόδου",
	"VoiceOutputGainExplainer": "(Οι φίλοι μου)",
	"VoiceTransmissionType": "Πάτημα-για-ομιλία",
	"VoiceTransmissionType_Label": "ΤΥΠΟΣ ΜΕΤΑΔΟΣΗΣ ΦΩΝΗΣ",
	"VoiceTransmissionType_OpenMic": "Ανοικτό μικρόφωνο",
	"VoiceTransmissionType_PushToTalk": "Πάτημα-για-ομιλία",
	"VoiceTransmissionType_PushToMute": "Πάτημα-για-σίγαση",
	"VoiceClearHotKeyTooltip": "Εκκαθάριση κουμπιού εναλλαγής σίγασης",
	"VoiceTransmissionTypeExplainer": "Πατήστε ένα συγκεκριμένο πλήκτρο για να μιλήσετε στα φωνητικά κανάλια",
	"VoiceTransmissionType_WhenSpeaking": "Αυτόματο",
	"VoiceTransmissionType_PushToTalk_Key": "Πάτημα-για-ομιλία: %1$s",
	"VoicePushToTalkPressHotKey": "Πατήστε κουμπί για ορισμό",
	"VoicePushToTalkAssigned": "Το κουμπί πατήματος-για-ομιλία ορίστηκε ως",
	"VoicePushToMuteAssigned": "Το κουμπί πατήματος-για-σίγαση ορίστηκε ως",
	"VoiceMuteToggleAssigned": "Το κουμπί εναλλαγής σίγασης ορίστηκε ως",
	"VoicePushToSomethingSoundOption": "Αναπαραγωγή ενός σύντομου ήχου στην εναλλαγή μικροφώνου",
	"VoiceTransmisionThreshold": "ΟΡΙΟ ΜΕΤΑΔΟΣΗΣ ΦΩΝΗΣ",
	"VoiceTransmissionThresholdExplainer": "Όταν το μικρόφωνο σας είναι ενεργοποιημένο, δεν θα μεταδίδουμε ήχο κάτω από αυτό το όριο:",
	"VoiceTransmissionThresholdOff": "Ανενεργό",
	"VoiceTransmissionThresholdMedium": "Μέτριο",
	"VoiceTransmissionThresholdHigh": "Υψηλό",
	"VoiceTransmissionThresholdRecommended": "Προτεινόμενο",
	"VoiceAdvancedSettings": "ΠΡΟΧΩΡΗΜΕΝΕΣ ΡΥΘΜΙΣΕΙΣ",
	"VoiceShowAdvancedSettings": "Εμφάνιση προχωρημένων ρυθμίσεων",
	"VoiceHideAdvancedSettings": "Απόκρυψη προχωρημένων ρυθμίσεων",
	"VoiceAdvancedSettingsExplainer": "(Αυτές είναι ρυθμίσεις μικροφώνου που ελέγχονται από την πλατφόρμα ή το πρόγραμμα περιήγησης σας.)",
	"VoiceEchoCancellation": "Ακύρωση ηχούς",
	"VoiceNoiseCancellation": "Ακύρωση θορύβου",
	"VoiceAutoGainControl": "Αυτόματος έλεγχος έντασης",
	"DefaultMic": "Προεπιλογή",
	"MicLoading...": "Φόρτωση...",
	"DefaultOutputDevice": "Προεπιλογή",
	"OutputDeviceLoading...": "Φόρτωση...",
	"BreadCrumbs_AllEvents": "Όλα τα συμβάντα",
	"BreadCrumbs_GameEvents": "%1$s Συμβάντα",
	"CreatorHome_ThisGame": "Σχετικά με το παιχνίδι:",
	"CreatorHome_DevelopedBy": "Δημιουργήθηκε από:",
	"CreatorHome_PublishedBy": "Δημοσιεύτηκε από:",
	"CreatorHome_InFranchise": "Σε franchise:",
	"CreatorHome_Followers": "%1$s<br>ακόλουθοι",
	"CreatorHome_JustFollowers": "ακόλουθοι",
	"CreatorHome_Follow_tooltip": "Ακολουθήστε αυτόν τον δημιουργό για να ειδοποιήστε με email και στο κατάστημα Steam σας όταν κυκλοφορούν ένα νέο παιχνίδι. Μπορείτε να απενεργοποιήσετε τις ειδοποιήσεις email οποιαδήποτε στιγμή.",
	"EventBrowse_MoreEventsTitle": "Περισσότερα συμβάντα από %1$s",
	"EventBrowse_MoreEventsBtn": "Προβολή όλων",
	"EventBrowse_RecentUpdates": "Πρόσφατες ενημερώσεις",
	"EventBrowse_RecentEvents": "Πρόσφατα συμβάντα & ανακοινώσεις",
	"EventCalendar_Title": "Κέντρο νέων Steam %1$s",
	"EventCalendar_FilterSubSection_EventTypeGroups": "Εμφάνιση αυτού του τύπου αναρτήσεων",
	"EventCalendar_FilterSubSection_GameSources": "Εμφάνιση αναρτήσεων από αυτές τις πηγές",
	"EventCalendar_EmptyCalendar": "Δε βρέθηκαν αναρτήσεις. Δοκιμάστε να επιλέξετε διαφορετικά κριτήρια αναζήτησης στην πλαϊνή μπάρα.",
	"EventCalendar_DisabledFilter_LoginPrompt": "Συνδεθείτε για να ενεργοποιήσετε αυτές τις κατηγορίες",
	"EventCalendar_MainLoginPrompt": "Συνδεθείτε για να δείτε το προσωπικό σας κέντρο νέων",
	"EventCalendar_NoMoreFutureEvents": "Δε βρέθηκαν νεότερες αναρτήσεις",
	"EventCalendar_NoMorePastEvents": "Δε βρέθηκαν παλαιότερες αναρτήσεις",
	"EventCalendar_GameSearch": "Αναζήτηση παιχνιδιών",
	"EventCalendar_GameSearch_NoneFound": "Δε βρέθηκαν αποτελέσματα",
	"EventCalendar_GlobalCalendar_Action": "Επιστροφή στο Κέντρο νέων",
	"EventCalendar_SpecificCalendar": "Κέντρο νέων %2$s %1$s",
	"EventCalendar_Goto_SpecificCalendar": "Μετάβαση στο Κέντρο νέων %1$s",
	"EventCalendar_SingleAppIsMuted": "Σημείωση: Αυτό το παιχνίδι έχει σιγή και δε θα εμφανίζεται στο προσωποποιημένο κέντρο νέων σας.",
	"SteamLabs": "Ερ. κέντρο Steam",
	"SteamLabs_ExperimentNumber": "Πείραμα %1$s",
	"SteamLabs_DiscussionLink": "Συζητήστε το πείραμα",
	"EventCalendar_FutureEventsHint": "Κυλίστε πάνω για να δείτε τι έρχεται",
	"EventCalendar_FutureEventsHeader": "Προσεχώς",
	"EventCalendar_LiveAndRecentEventsHeader": "Ζωντανά και πρόσφατα",
	"EventCalendar_LiveNow": "ΖΩΝΤΑΝΑ",
	"EventCalendar_TimeLeft": "λήγει σε %1$s",
	"EventCalendar_PostedAtTime": "Αναρτήθηκε %1$s",
	"EventCalendar_StartedAtTime": "Ξεκίνησε %1$s",
	"EventCalendar_Upcoming": "ΕΠΕΡΧΟΜΕΝΗ",
	"EventCalendar_WillStartAtTime": "Ξεκινάει %1$s",
	"EventCalendar_WillStartAfterDuration": "Ξεκινάει σε %1$s",
	"EventCalendar_LaterToday": "ΑΡΓΟΤΕΡΑ ΣΗΜΕΡΑ",
	"EventCalendar_Tomorrow": "αύριο",
	"EventCalendar_ThisWeek": "ΑΥΤΗ ΤΗΝ ΕΒΔΟΜΑΔΑ",
	"EventCalendar_ThisMonth": "ΑΥΤΟ ΤΟ ΜΗΝΑ",
	"EventCalendar_MuchLater": "ΠΟΛΥ ΑΡΓΟΤΕΡΑ",
	"EventCalendar_MuteApp": "Σίγαση εφαρμογής",
	"EventCalendar_MuteApp_Title": "Σίγαση %1$s",
	"EventCalendar_Ignore": "Αγνόηση",
	"EventCalendar_IgnoreApp": "Αγνόηση %1$s",
	"EventCalendar_IgnoreApp_ttip": "Τίτλοι που έχουν αγνοηθεί δε θα σας προτείνονται και δε θα εμφανίζονται σε προβαλλόμενες περιοχές.",
	"EventCalendar_IgnoreApp_newhub": "Το Κέντρο νέων θα εφαρμόσει τις ρυθμίσεις αγνόησής σας και θα αποτρέψει παιχνίδια που αγνοείτε στο κατάστημα από το να εμφανίζονται στο κέντρο νέων σας. Μπορείετ να διαχειριστείτε τα αγνοημένα παιχνίδια εδώ:",
	"EventCalendar_UnignoreApp": "Αφαίρεση αγνόησης %1$s",
	"EventCalendar_UnMuteApp_Title": "Αφαίρεση σίγασης %1$s",
	"EventCalendar_MuteApp_ttip": "Αφαιρέστε αυτό το παιχνίδι από το κέντρο νέων σας και μπλοκάρετε μελλοντική επικοινωνία.",
	"EventCalendar_UnMuteApp_ttip": "Επαναφορά αυτού του παιχνιδιού στο Κέντρο νέων σας και κατάργηση αποκλεισμού μελλοντικής επικοινωνίας.",
	"EventCalendar_MuteApp_details": "Αφαίρεση «%1$s» από το να εμφανίζεται στο κέντρο νέων σας και μπλοκάρισμα κάθε μελλοντικής επικοινωνίας. Οι αποφάσεις αποσιώπησης περιεχομένου μπορούν πάντα να ανακληθούν επισκεπτόμενοι αυτή τη σελίδα:",
	"EventCalendar_ManageMutedApps": "Διαχείριση σιγασμένων εφαρμογών",
	"EventCalendar_ManageStorePref": "Διαχείριση προτιμήσεων καταστήματος",
	"EventCalendar_MuteApp_Unknown": "Άγνωστο",
	"EVentCalendar_Hide_EventType": "Απόκρυψη όλων των αναρτήσεων τύπου «%1$s»",
	"EventCalender_LastPlayed": "Τελευταίο παιχνίδι %1$s",
	"EventCalender_Reason_recent": "Αυτό το παιχνίδι παίχθηκε πρόσφατα",
	"EventCalender_Reason_library": "Αυτό το παιχνίδι είναι στη συλλογή σας",
	"EventCalender_Reason_following": "Ακολουθείτε αυτό το παιχνίδι",
	"EventCalender_Reason_wishlist": "Αυτό το παιχνίδι είναι στη λίστα επιθυμιών σας",
	"EventCalender_Reason_recommended": "Αυτό το παιχνίδι προτείνεται για εσάς",
	"EventCalender_Reason_steam": "Αυτή η ανάρτηση είναι από την πλατφόρμα του Steam",
	"EventCalender_Reason_topx": "Παιχνίδι είναι στις Κορυφαίες πωλήσεις",
	"EventCalender_Hide_Reason_recent": "Απόκρυψη αναρτήσεων από πρόσφατα παιχνίδια",
	"EventCalender_Hide_Reason_library": "Απόκρυψη αναρτήσεων από παιχνίδια στη συλλογή σας",
	"EventCalender_Hide_Reason_following": "Απόκρυψη αναρτήσεων από παιχνίδια που ακολουθείτε",
	"EventCalender_Hide_Reason_wishlist": "Απόκρυψη αναρτήσεων από παιχνίδια στη λίστα επιθυμιών σας",
	"EventCalender_Hide_Reason_recommended": "Απόκρυψη αναρτήσεων από παιχνίδια που προτείνονται για εσάς",
	"EventCalender_Hide_Reason_steam": "Απόκρυψη αναρτήσεων από τη πλατφόρμα Steam",
	"EventCalender_Hide_Reason_topx": "Απόκρυψη αναρτήσεων από Κορυφαίες πωλήσεις",
	"EventCalendar_ForceDesktopView": "Αίτηση προβολής επ. εργασίας",
	"EventCalendar_ShowResponsiveView": "Αίτηση αποκριτικής προβολής",
	"EventCalendar_EventTypeGroup_news": "Νέα",
	"EventCalendar_EventTypeGroup_ttip_news": "Περιλαμβάνει γενικά νέα, ιστολόγια δημιουργών και ανακοινώσεις",
	"EventCalendar_EventTypeGroup_events": "Συμβάντα",
	"EventCalendar_EventTypeGroup_ttip_events": "Περιλαμβάνει συμβάντα εντός παιχνιδιού, διαδικτυακά/συνομιλίας και πραγμ. κόσμου",
	"EventCalendar_EventTypeGroup_streaming": "Ζωντανές μεταδόσεις",
	"EventCalendar_EventTypeGroup_ttip_streaming": "Περιλαμβάνει συμβάντα ζωντανής μετάδοσης, όπως τουρνουά",
	"EventCalendar_EventTypeGroup_updates": "Ενημερώσεις περιεχομένου",
	"EventCalendar_EventTypeGroup_ttip_updates": "Περιλαμβάνει νέα για νέο περιεχόμενο παιχνιδιού, επεκτάσεις, DLC και διορθώσεις σφαλμάτων",
	"EventCalendar_EventTypeGroup_releases": "Κυκλοφορίες",
	"EventCalendar_EventTypeGroup_ttip_releases": "Περιλαμβάνει ημ/νίες κυκλοφορίας νέων παιχνιδιών, δοκιμών, σεζόν ή DLC",
	"EventCalendar_EventTypeGroup_sales": "Εκπτώσεις",
	"EventCalendar_EventTypeGroup_ttip_sales": "Περιλαμβάνει εκπτώσεις, προσφορές και δωρεάν δοκιμές",
	"EventCalendar_GameSource_recent": "Προσφάτως παιγμένα",
	"EventCalendar_GameSource_ttip_recent": "Συμπερίληψη αναρτήσεων για παιχνίδια που έχετε παίξει ή αγοράσει τους τελευταίους 6 μήνες",
	"EventCalendar_GameSource_EventExplanation_ttip_recent": "Έχετε παίξει αυτό το παιχνίδι τους τελευταίους 6 μήνες",
	"EventCalendar_GameSource_library": "Συλλογή",
	"EventCalendar_GameSource_ttip_library": "Συμπερίληψη αναρτήσεων για παιχνίδια στη συλλογή σας",
	"EventCalendar_GameSource_EventExplanation_ttip_library": "Αυτό το παιχνίδι είναι στη συλλογή σας",
	"EventCalendar_GameSource_wishlist": "λίστα επιθυμιών",
	"EventCalendar_GameSource_ttip_wishlist": "Συμπερίληψη αναρτήσεων για παιχνίδια στη λ. επιθυμιών σας",
	"EventCalendar_GameSource_EventExplanation_ttip_wishlist": "Αυτό το παιχνίδι είναι στη λίστα επιθυμιών σας",
	"EventCalendar_GameSource_following": "ακολουθείτε",
	"EventCalendar_GameSource_ttip_following": "Συμπερίληψη αναρτήσεων για παιχνίδια που ακολουθείτε",
	"EventCalendar_GameSource_EventExplanation_ttip_following": "Αυτό είναι ένα παιχνίδι που ακολουθείτε",
	"EventCalendar_GameSource_recommended": "προτείνεται",
	"EventCalendar_GameSource_recommended_Verbose": "Προτεινόμενο παιχνίδι",
	"EventCalendar_GameSource_ttip_recommended": "Συμπερίληψη αναρτήσεων για παιχνίδια που θα σας αρέσουν",
	"EventCalendar_GameSource_EventExplanation_ttip_recommended": "Αυτό είναι ένα παιχνίδι που θα σας αρέσει",
	"EventCalendar_GameSource_steam": "steam",
	"EventCalendar_GameSource_ttip_steam": "Συμπερίληψη αναρτήσεων για την πλατφόρμα Steam",
	"EventCalendar_GameSource_topx": "Κορυφαίες πωλήσεις",
	"EventCalendar_GameSource_ttip_topx": "Συμπερίληψη αναρτήσεων για παιχνίδια στις τοπικές λίστες κορυφαίων πωλήσεων",
	"EventCalendar_GameSource_EventExplanation_ttip_steam": "Αυτή είναι μια ανάρτηση σχετικά με το Steam",
	"EventDisplay_Admin_Title": "Εργαλεία διαχειριστή:",
	"EventDisplay_ViewInLibrary": "Προβολή στη Συλλογή",
	"EventDisplay_ViewStorePage": "Προβολή σελ. καταστήματος",
	"EventDisplay_ViewCommunityPage": "Προβολή σελίδας κοινότητας",
	"EventDisplay_CallToAction_LearnMore": "Μάθετε περισσότερα",
	"EventDisplay_CallToAction_InLibrary": "Στη συλλογή",
	"EventDisplay_CallToAction_PlayNow": "Παίξτε τώρα",
	"EventDisplay_CallToAction_ComingSoon": "Προσεχώς",
	"EventDisplay_CallToAction_FreeToPlay": "Δωρεάν",
	"EventDisplay_Events": "Πάνελ διαχειριστή",
	"EventDisplay_SeeOldVersion": "Προβολή τρέχουσας έκδοσης πελάτη",
	"EventDisplay_SalesPage": "Προβολή σελίδας εκτώσεων καταστήματος",
	"EventDisplay_StatsPage": "(Valve) Σελίδα στατιστικών",
	"EventDisplay_RightColumnTitle_Game": "Παιχνίδι",
	"EventDisplay_RightColumnTitle_Blog": "Ιστολόγιο",
	"EventDisplay_RightColumnTitle_DateAndTime": "Ημερομηνία και ώρα",
	"EventDisplay_RightColumnTitle_EventType": "Τύπος",
	"EventDisplay_PostedBy": "από ",
	"EventDisplay_Reminder_SetReminder": "Ορισμός υπενθύμισης",
	"EventDisplay_Reminder_GetNotification_Via": "Λάβετε μια ειδοποίηση",
	"EventDisplay_Reminder_ViaEmail": "μέσω email",
	"EventDisplay_Reminder_ViaMobileApp": "μέσω εφαρμογής κινητού",
	"EventDisplay_Reminder_FollowEvent": "Ακολούθηση εκδήλωσης",
	"EventDisplay_Reminder_FollowEvent_ttip": "Ακολουθήστε μια εκδήλωση για να ειδοποιηθείτε όταν ξεκινήσει.",
	"EventDisplay_Reminder_RemindAtStart": "Όταν ξεκινήσει η εκδήλωση",
	"EventDisplay_Reminder_RemindAtStart_ttip": "Το Steam θα σας ειδοποιήσει τη στιγμή που θα ξεκινήσει η εκδήλωση.",
	"EventDisplay_Reminder_IgnoreEvent": "Αγνόηση εκδήλωσης",
	"EventDisplay_Reminder_IgnoreStop": "Διακοπή υπενθυμίσεων",
	"EventDisplay_Reminder_IgnoreEvent_ttip": "Η αγνόηση μιας εκδήλωσης θα πει στο Steam να αποκλείσει αυτή την εκδήλωση από μελλοντικές προτάσεις και συστάσεις.",
	"EventDisplay_Reminder_FollowEvent_Error": "Σφάλμα ακολούθησης εκδήλωσης",
	"EventDisplay_Reminder_FollowEvent_ErrorDesc": "Η αλλαγή της κατάστασης ακολούθησης της εκδήλωσης παρουσίασε το ακόλουθο σφάλμα:",
	"EventDisplay_Reminder_IgnoreEvent_Error": "Σφάλμα αγνόησης εκδήλωσης",
	"EventDisplay_Reminder_IgnoreEvent_ErrorDesc": "Η αλλαγή της κατάστασης αγνόησης της εκδήλωσης παρουσίασε το ακόλουθο σφάλμα:",
	"EventDisplay_Reminder_Toast": "Αναδυόμενη ειδοποίηση Steam στην έναρξη",
	"EventDisplay_Reminder_AddToCalendar": "Προσθήκη στο ημερολόγιο",
	"EventDisplay_Reminder_AddToApple": "Προσθήκη στην ημερολόγιο Apple",
	"EventDisplay_Reminder_AppleCalendar_Short": "Apple",
	"EventDisplay_Reminder_AddToGoogle": "Προσθήκη στην ημερολόγιο Google",
	"EventDisplay_Reminder_GoogleCalendar_Short": "Google",
	"EventDisplay_Reminder_AddToOutlook": "Προσθήκη στην ημερολόγιο Outlook",
	"EventDisplay_Reminder_OutlookCalendar_Short": "Outlook",
	"EventDisplay_Reminder_AddToYahoo": "Προσθήκη στην ημερολόγιο Yahoo",
	"EventDisplay_Reminder_Preferences": "Επεξεργασία προτιμήσεων υπενθυμίσεων...",
	"EventDisplay_TimeDisplay": "Από %1$s έως %2$s",
	"EventDisplay_TimeDisplayNone": "Χωρίς πληροφορίες ημερομηνίας και ώρας",
	"EventDisplay_TimeBeginsOn": "Επερχόμενη εκδήλωση ξεκινάει",
	"EventDisplay_TimeBeginsOn_Past": "Ξεκίνησε",
	"EventDisplay_TimeBeginsOn_StartAndEnd_Past": "Παλιά εκδήλωση ξεκίνησε",
	"EventDisplay_TimeEndsOn": "Λήγει",
	"EventDisplay_TimeEndsOn_Past": "Έληξε",
	"EventDisplay_RunsForDuration": "Διαρκεί για %1$s",
	"EventDisplay_TimeLeft": "Λήγει σε %1$s",
	"EventDisplay_TimeEndsOn_Ran": "Έτρεξε",
	"EventDisplay_TimeRange": "Ώρα εκδήλωσης",
	"EventDisplay_TimeInPast": "Αναρτήθηκε",
	"EventDisplay_TimeUpcoming": "Εκδήλωση ξεκινάει",
	"EventDisplay_EventUpcoming_WithDateAndTime": "Το συμβάν ξεκινάει %1$s στις %2$s",
	"EventDisplay_TimeEventActive": "Η εκδήλωση τρέχει τώρα",
	"EventDisplay_TimeEventOnNow": "Ζωντανό τώρα!",
	"EventDisplay_Share_Link": "Σύνδεσμος: ",
	"EventDisplay_Share_OnMyStatus": "Κοινοποίηση απευθείας ως κατάστασή μου",
	"EventDisplay_Share_OnMyStatus_Details": "Αναρτήστε αυτή την κατάσταση στη ροή δραστηριότητας φίλων σας. Το Steam θα συμπεριλάβει το μήνυμα και την προεπισκόπηση αντικειμένου που εμφανίζεται παρακάτω.",
	"EventDisplay_Share_OnMyStatus_Placeholder": "Πείτε κάτι για αυτό στους φίλους σας...",
	"EventDisplay_Share_OnSteam": "Κοινοποίηση στην κοινότητα Steam ως ενημέρωση κατάστασης",
	"EventDisplay_Share_OnFaceBook": "Κοινοποίηση στο Facebook",
	"EventDisplay_Share_OnTwitter": "Κοινοποίηση στο Twitter",
	"EventDisplay_Share_OnReddit": "Κοινοποίηση στο Reddit",
	"EventDisplay_Share_Success": "Επιτυχία!",
	"EventDisplay_Share_Failure": "Αποτυχία με το ακόλουθο μήνυμα: ",
	"EventDisplay_Share_Announcement": "%1$s Ανακοίνωση",
	"EventDisplay_Share_Event": "%1$s Εκδήλωση",
	"EventDisplay_Share_NotLoggedIn": "Χωρίς σύνδεση",
	"EventDisplay_Share_NotLoggedIn_Description": "Για να χρησιμοποιήσετε αυτή τη λειτουργία, πρέπει πρώτα να συνδεθείτε στο Steam",
	"EventDisplay_Share_CommentMigrationInProcess": "Η συζήτηση για αυτό το συμβάν είναι σε σειρά για να μεταναστεύσει στο σύστημα συμβάντων. Είναι προσωρινά μη προσπελάσιμες. Ελάτε ξανά αργότερα.",
	"EventDisplay_Share_OpenActivityFeed": "Άνοιγμα της ροής δραστηριότητάς μου",
	"EventDisplay_AreYouSure": "Θέλετε σίγουρα να διαγράψετε αυτή την εκδήλωση (%1$s); Αυτή η ενέργεια δεν μπορεί να ανακληθεί.",
	"EventDisplay_AreYouSure_Visible": "Θέλετε σίγουρα να διαγράψετε αυτή την εκδήλωση (%1$s); Αυτή η ενέργεια δεν μπορεί να ανακληθεί. Η εκδήλωση θα αφαιρεθεί από όλα τα μέρη που μπορεί να την ανακαλύψει ένας χρήστης εντός μερικών λεπτών.",
	"EventDisplay_DeleteEvent_InProgress": "Διαγραφή σε εξέλιξη. Παρακαλούμε περιμένετε.",
	"EventDisplay_DeleteEvent_Error": "Παρουσιάστηκε ένα σφάλμα κατά την επεξεργασία του αιτήματος διαγραφής:",
	"EventDisplay_DeleteEvent_ForumTopicError": "Η εκδήλωση διαγράφηκε επιτυχώς. Αποτύχαμε όταν προσπαθήσαμε να διαγράψουμε τη συζήτηση φόρουμ για αυτή την εκδήλωση. Μπορείτε πάντα να προσπαθήσετε ξανά στην ιστοσελίδα %1$s. Λεπτομέρειες σφάλματος:",
	"EventDisplay_DeleteEvent_Success": "Η εκδήλωση διαγράφηκε επιτυχώς.",
	"EventDisplay_DeleteEvent_Comment": "Επίσης διαγραφή της συζήτησης φόρουμ για αυτή την εκδήλωση;",
	"EventDisplay_SocialTitle": "Περισσότερα σχετικά με αυτό το παιχνίδι",
	"EventDisplay_Sketchfab": "Μοντέλο Sketchfab",
	"EventDisplay_SketchFab_Error_Network": "Αδυναμία επικοινωνίας με Sketchfab",
	"EventEditor_Publish_VisibleNow": "Να γίνει ορατή τώρα",
	"EventEditor_Publish_VisibleNow_ttip": "Αυτή η εκδήλωση θα γίνει αυτόματα ορατή την προγραμματισμένη ώρα. Αυτό το κουμπί εξαναγκάζει την εκδήλωση να γίνει αμέσως ορατή.",
	"EventEditor_Edit": "Επεξεργασία εκδήλωσης",
	"EventDisplay_DeleteEvent": "Διαγραφή εκδήλωσης",
	"EventReminder_InProgress": "(σημείωση ότι οι επιλογές ειδοποίησης που εμφανίζονται εδώ είναι αντιπροσωπευτικές και δε λειτουργούν ακόμα)",
	"EventReminder_NotifyByEmail": "Να ειδοποιούμαι με email",
	"EventReminder_NotifyByEmail_ttip": "To Steam θα στείλει μια ειδοποίηση με email στο λογαριασμό σας όταν το συμβάν ξεκινήσει.",
	"EventReminder_NotifyByMobile": "Να ειδοποιούμαι στην κινητή συσκευή μου",
	"EventReminder_NotifyByMobile_ttip": "Το Steam θα στείλει μια ειδοποίηση όταν ξεκινήσει το συμβάν σε όλες τις συσκευές που έχετε εγκαταστημένη την εφαρμογή κινητού Steam και είστε συνδεδεμένος.",
	"EventReminder_NotifyByEmail_Missing": "Επιβεβαιώστε τη διεύθυνση email σας για να εγγραφείτε για υπενθυμίσεις email.",
	"EventReminder_NotifyByEmail_Missing_Add": "Επιβεβαιώστε τη διεύθυνση email σας εδώ.",
	"EventReminder_NotifyByMobile_Missing": "Εγκαταστήστε μία από τις εφαρμογές Steam για να εγγραφείτε για ειδοποιήσεις κινητού. ",
	"EventReminder_NotifyByMobile_Install": "Δείτε τις διαθέσιμες εφαρμογές εδώ.",
	"EventEmail_Subject_NewUpdate": "%1$s, Νέα ενημέρωση",
	"EventEmail_Subject_UpcomingLaunch": "%1$s, Επερχόμενη κυκλοφορία",
	"EventEmail_Subject_NowAvailable": "%1$s τώρα διαθέσιμο",
	"EventEmail_Subject_FreeDemoAvailable": "Τώρα διαθέσιμο δωρεάν Demo %1$s",
	"EventEmail_Subject_SpecialOffer": "Ειδική προσφορά %1$s",
	"EventEmail_Subject_Tournament_Now": "Τουρνουά %1$s, συντονιστείτε τώρα",
	"EventEmail_Subject_LiveStream_Now": "Ζωντανή μετάδοση %1$s, συντονιστείτε τώρα",
	"Email_Wishlist_NewReleaseEA_Subject": "Το %1$s είναι τώρα διαθέσιμο σε Πρόωρη πρόσβαση στο Steam!",
	"EventEmail_Button_ClickForMoreDetails": "Διαβάστε περισσότερα",
	"EventEmail_Button_PrepurchaseNow": "Προαγοράστε τώρα!",
	"EventEmail_Button_BuyNow": "Αγοράστε τώρα!",
	"EventEmail_Button_PlayNow": "Παίξτε τώρα!",
	"EventEmail_Button_WishlistNow": "Προσθήκη σε λίστα επιθυμιών!",
	"EventEmail_WatchNow": "Παρακολουθήστε τώρα",
	"EventEmail_Destination_Store": "Σελίδα καταστήματος προϊόντος παιχνιδιού Steam",
	"EventEmail_Destination_Event": "Σελίδα λεπτομερειών συμβάντος",
	"EventEmail_Destination_SalesPage": "Σελίδα καταστήματος εκπτώσεων Steam",
	"EventDashBoard_SummaryStats_Admin_Title": "(Ορατό μόνο σε διαχειριστές)",
	"EventDashBoard_SummaryStats_Title": "Ολικές μοναδικές εντυπώσεις και προβολές",
	"EventDashBoard_SummaryStats_Desc": "(Δοκιμή) Αυτές είναι οι εντυπώσεις και οι προβολές για τα συμβάντα και τις ανακοινώσεις σας ανά μοναδικούς συνδεδεμένους χρήστες. Αυτό είναι μόνο για νέα συμβάντα και ανακοινώσεις που φτιάχτηκαν με αυτό το σύστημα.",
	"EventDashBoard_SummaryStats_Link": "Πατήστε εδώ για περισσότερες λεπτομέρειες.",
	"EventDashBoard_Summary_LibraryHome_Shown": "Εντυπώσεις συμβάντων (εικόνα κάλυψης):",
	"EventDashBoard_Summary_LibraryHome_Read": "Πατήματα σε συμβάν για προβολή λεπτομερειών:",
	"EventDashBoard_Summary_AppDetailSpotlight_Shown": "Εντυπώσεις από μπάνερ επίκεντρου:",
	"EventDashBoard_Summary_AppDetailSpotlight_Read": "Πατήματα σε μπάνερ επίκεντρου για προβολή λεπτομερειών:",
	"EventDashBoard_Summary_AppDetailActivity_Shown": "Εντυπώσεις συμβάντων σε ροή δραστηριότητας:",
	"EventDashBoard_Summary_AppDetailActivity_Read": "Πατήματα σε συμβάν για προβολή λεπτομερειών:",
	"EventDashBoard_Summary_StoreAppPage_Shown": "Εντυπώσεις συμβάντων (εικόνα κάλυψης):",
	"EventDashBoard_Summary_StoreAppPage_Read": "Πατήματα σε συμβάν για προβολή λεπτομερειών:",
	"EventDashBoard_Summary_Community_Shown": "Εντυπώσεις από περίληψη συμβάντος:",
	"EventDashBoard_Summary_Community_Read": "Πατήματα σε περίληψη συμβάντος για προβολή λεπτομερειών:",
	"EventDashBoard_Summary_NewsHub_Shown": "Εντυπώσεις συμβάντος στο κέντρο νέων:",
	"EventDashBoard_Summary_NewsHub_Read": "Πατήματα σε συμβάν για προβολή λεπτομερειών:",
	"EventDashBoard_Location_LibraryHome": "Αρχική σελίδα συλλογής",
	"EventDashBoard_Location_LibraryDetail": "Αρχική σελίδα παιχνιδιού",
	"EventDashBoard_Location_StoreDetail": "Σελίδα καταστήματος παιχνιδιού",
	"EventDashBoard_Location_CommunityDetail": "Κέντρο κοινότητας εφαρμογής",
	"EventDashBoard_Location_PopUpViews": "Προβολές αναδυόμενων συμβάντος",
	"EventDashBoard_Location_NewsHubDetail": "Κέντρο νέων",
	"AddToWishlist": "Προσθήκη σε λίστα επιθυμιών",
	"Wishlisted": "Στη λίστα επιθυμιών σας",
	"AddToWishlist_ttip": "Θα ειδοποιηθείτε με email όταν τα αντικείμενα στη λίστα επιθυμιών σας κυκλοφορήσουν ή έχουν έκπτωση",
	"Wishlist_Error": "Σφάλμα ενημέρωσης λίστας επιθυμιών",
	"Wishlist_Error_Desc": "Αντιμετωπίσαμε ένα σφάλμα κατά την προσθήκη στη λίστα επιθυμιών σας. Προσπαθήστε ξανά αργότερα:",
	"WindowTitle_FriendsList": "Λίστα φίλων",
	"FriendsList_OfflineTitle": "ΣΦΑΛΜΑ",
	"FriendsList_OfflineOrFailure": "ΑΔΥΝΑΜΙΑ ΕΝΤΟΠΙΣΜΟΥ ΔΙΚΤΥΟΥ ΦΙΛΩΝ",
	"FriendsList_OfflineDetail": "Αυτό το σφάλμα μπορεί να υποδεικνύει ότι το τοπικό σας δίκτυο ή ότι οι διακομιστές φίλων Steam είναι αυτή τη στιγμή εκτός σύνδεσης.",
	"FriendsList_SignedOut": "ΑΠΟΣΥΝΔΕΔΕΜΕΝΟ ΑΠΟ ΦΙΛΟΥΣ ΚΑΙ ΣΥΝΟΜΙΛΙΑ",
	"FriendsList_SignedOut_Detail": "Αυτή τη στιγμή είστε εκτός σύνδεσης. Συνδεθείτε για να αποκτήσετε πρόσβαση στη λίστα φίλων σας και στη συνομιλία.",
	"FriendsList_OfflineMode": "ΑΠΟΣΥΝΔΕΔΕΜΕΝΟ ΑΠΟ ΦΙΛΟΥΣ ΚΑΙ ΣΥΝΟΜΙΛΙΑ",
	"FriendsList_OfflineMode_Detail": "Οι φίλοι και η συνομιλία δεν είναι διαθέσιμα σε λειτουργία εκτός σύνδεσης. Παρακαλούμε συνδεθείτε για να αποκτήσετε πρόσβαση στη λίστα φίλων σας και στη συνομιλία.",
	"Friends_RetryLoading": "ΕΠΑΝΑΛΗΨΗ ΣΥΝΔΕΣΗΣ",
	"Friends_SignIn": "ΣΥΝΔΕΣΗ",
	"FriendsList_Offline_Disconnected": "Αποσυνδεδεμένο",
	"FriendsList_LoadingTitle": "ΦΟΡΤΩΣΗ",
	"FriendsList_StillLoadingSummary": "ΦΟΡΤΩΣΗ ΔΙΚΤΥΟΥ ΦΙΛΩΝ...",
	"FriendsList_StillLoadingDetail": "Το Steam προσπαθεί να συνδεθεί στο δίκτυο φίλων. Αυτό μπορεί να διαρκέσει μερικά δευτερόλεπτα ακόμα.",
	"Dialog_On": "ΕΝΕΡΓΟ",
	"Dialog_Off": "ΟΧΙ",
	"TimeInterval_XYears": "%1$s χρόνια",
	"TimeInterval_1YearXMonths": "1 χρόνο και %1$s μήνες",
	"TimeInterval_1Year": "1 χρόνο",
	"TimeInterval_XMonths": "%1$s μήνες",
	"TimeInterval_1Month": "1 μήνας",
	"TimeInterval_1MonthX": "1 μήνας και %1$s ημέρες",
	"TimeInterval_XWeeks": "%1$s εβδομάδες",
	"TimeInterval_1Week": "1 εβδομάδα",
	"TimeInterval_XDays": "%1$s ημέρες",
	"TimeInterval_1Day": "1 ημέρα",
	"TimeInterval_1DayXHours": "1 ημέρα και %1$s ώρες",
	"TimeInterval_XHours": "%1$s ώρες",
	"TimeInterval_1Hour": "1 ώρα",
	"TimeInterval_1HourXMinutes": "1 ώρα και %1$s λεπτά",
	"TimeInterval_LessThanAnHour": "λιγότερο από μία ώρα",
	"TimeInterval_XMinutes": "%1$s λεπτά",
	"TimeInterval_1Minute": "1 λεπτό",
	"TimeInterval_LessThanAMinute": "λιγότερο από ένα λεπτό",
	"TimeSince_XYears": "πριν %1$s χρόνια",
	"TimeSince_1YearXMonths": "πριν 1 χρόνο και %1$s μήνες",
	"TimeSince_1Year": "πριν 1 χρόνο",
	"TimeSince_XMonths": "πριν %1$s μήνες",
	"TimeSince_1Month": "πριν 1 μήνα",
	"TimeSince_1MonthXDays": "πριν 1 μήνα και %1$s ημέρες",
	"TimeSince_XWeeks": "πριν %1$s εβδομάδες",
	"TimeSince_1Week": "πριν 1 εβδομάδα",
	"TimeSince_XDays": "πριν %1$s ημέρες",
	"TimeSince_1Day": "πριν 1 ημέρα",
	"TimeSince_1DayXHours": "πριν 1 ημέρα και %1$s ώρες",
	"TimeSince_XHours": "πριν %1$s ώρες",
	"TimeSince_1Hour": "πριν 1 ώρα",
	"TimeSince_1HourXMinutes": "πριν 1 ώρα και %1$s λεπτά",
	"TimeSince_LessThanAnHour": "πριν από λιγότερο από μία ώρα",
	"TimeSince_XMinutes": "πριν %1$s λεπτά",
	"TimeSince_1Minute": "πριν 1 λεπτό",
	"TimeSince_LessThanAMinute": "πριν από λιγότερο από ένα λεπτό",
	"TimeSince_ThisWeek": "Αυτή την εβδομάδα",
	"Time_Today": "Σήμερα",
	"Time_Tomorrow": "Αύριο",
	"Time_Yesterday": "Χθες",
	"Time_Recent": "Πρόσφατα",
	"ContextMenu_Copy": "Αντιγραφή",
	"ContextMenu_Cut": "Αποκοπή",
	"ContextMenu_Paste": "Επικόλληση",
	"ContextMenu_CopyLinkURL": "Αντιγραφή URL συνδέσμου",
	"ContextMenu_OpenLinkInNewWindow": "Άνοιγμα συνδέσμου σε νέο παράθυρο",
	"ContextMenu_CopyImageURL": "Αντιγραφή URL εικόνας",
	"ContextMenu_OpenImageInNewWindow": "Άνοιγμα εικόνας σε νέο παράθυρο",
	"Tooltip_Settings": "Διαχείριση ρυθμίσεων λίστας φίλων",
	"Tooltip_VoiceSettings": "Διαχείριση ρυθμίσεων φωνής",
	"Tooltip_SearchFriends": "Αναζήτηση λίστας φίλων",
	"Tooltip_AddFriend": "Προσθήκη φίλου",
	"Tooltip_FriendRequest": "%1$s εισερχόμενο αίτημα",
	"Tooltip_FriendRequest_Plural": "%1$s εισερχόμενα αιτήματα",
	"Tooltip_CreateGroupChat": "Δημιουργία ομαδικής συνομιλίας",
	"Tooltip_InviteToGroup": "Πρόσκληση φίλου σε αυτή την ομαδική συνομιλία",
	"Tooltip_InviteToGroup_Denied": "Δεν έχετε άδεια να προσκαλέσετε χρήστες σε αυτή την ομάδα",
	"Tooltip_GroupChatSettings": "Διαχείριση ρυθμίσεων ομαδικής συνομιλίας",
	"Tooltip_MemberCollapse": "Σμίκρυνση λίστας μελών",
	"Tooltip_MemberExpand": "Επέκταση λίστας μελών",
	"Tooltip_ChatsCollapse": "Σμίκρυνση λίστας συνομιλιών",
	"Tooltip_ChatsExpand": "Επέκταση λίστας συνομιλιών",
	"Tooltip_MinimizeList": "Ελαχιστοποίηση λίστας",
	"Tooltip_ExpandList": "Ανάπτυξη λίστας",
	"Tooltip_PinChannelList": "Καρφίτσωμα λίστας καναλιών",
	"Tooltip_UnpinChannelList": "Ξεκαρφίτσωμα λίστας καναλιών",
	"Tooltip_TextChannel": "Συνομιλία κειμένου με μέλη ομάδας",
	"Tooltip_TextChannelCreate": "Δημιουργία νέου καναλιού κειμένου",
	"Tooltip_NoPermissionChannelCreate": "Δεν έχετε άδεια να δημιουργήσετε κανάλια σε αυτή την ομαδική συνομιλία",
	"Tooltip_VoiceChannel": "Φωνητική συνομιλία σε αυτά τα φωνητικά κανάλια",
	"Tooltip_VoiceChannelCreate": "Δημιουργία νέου φωνητικού καναλιού",
	"Tooltip_DismissVoice": "Απόρριψη φωνητικής πρόσκλησης",
	"Tooltip_MicStatus_Active": "Το μικρόφωνο είναι ενεργό",
	"Tooltip_MicStatus_Muted": "Το μικρόφωνο είναι σε σίγαση",
	"Tooltip_RemoteMicStatus_Muted": "Ο χρήστης σίγασε το μικροφώνο του",
	"Tooltip_MicStatus_NoMic": "Ο χρήστης δεν έχει μικρόφωνο συνδεδεμένο",
	"Tooltip_RemoteOutputStatus_Muted": "Ο χρήστης απενεργοποίησε τον ήχο από αυτό το κανάλι",
	"Tooltip_YourMicStatus_Muted": "Σιγάσατε το μικρόφωνό σας",
	"Tooltip_YourOutputStatus_Muted": "Απενεργοποιήσατε τον ήχο από αυτό το κανάλι",
	"Tooltip_VoiceControlButton_1v1_inactive": "Στείλτε ένα αίτημα φωνητικής συνομιλίας",
	"Tooltip_VoiceControlButton_1v1_active": "Απόχωρηση από φωνητικό κανάλι",
	"Tooltip_VoiceControlButton_group_create": "Δημιουργία φωνητικού καναλιού",
	"Tooltip_VoiceControlButton_group_leave": "Απόχωρηση από φωνητικό κανάλι",
	"Tooltip_VoiceControlButton_group_joinsingle": "Σύνδεση σε φωνητικό κανάλι",
	"Tooltip_VoiceControlButton_group_joinmultiple": "Επιλογή φωνητικού καναλιού για σύνδεση",
	"LanguageTitle": "Γλώσσα",
	"Language_english": "Αγγλικά",
	"Language_german": "Γερμανικά",
	"Language_french": "Γαλλικά",
	"Language_italian": "Ιταλικά",
	"Language_korean": "Κορεατικά",
	"Language_spanish": "Ισπανικά - Ισπανία",
	"Language_schinese": "Απλοποιημένα Κινεζικά",
	"Language_tchinese": "Παραδοσιακά Κινεζικά",
	"Language_russian": "Ρωσικά",
	"Language_thai": "Ταϊλανδικά",
	"Language_japanese": "Ιαπωνικά",
	"Language_portuguese": "Πορτογαλικά",
	"Language_polish": "Πολωνικά",
	"Language_danish": "Δανικά",
	"Language_dutch": "Ολλανδικά",
	"Language_finnish": "Φινλανδικά",
	"Language_norwegian": "Νορβηγικά",
	"Language_swedish": "Σουηδικά",
	"Language_hungarian": "Ουγγρικά",
	"Language_czech": "Τσεχικά",
	"Language_romanian": "Ρουμανικά",
	"Language_turkish": "Τουρκικά",
	"Language_arabic": "Αραβικά",
	"Language_brazilian": "Πορτογαλικά - Βραζιλία",
	"Language_bulgarian": "Βουλγαρικά",
	"Language_greek": "Ελληνικά",
	"Language_ukrainian": "Ουκρανικά",
	"Language_latam": "Ισπανικά - Λατινική Αμερική",
	"Language_vietnamese": "Βιετναμικά",
	"Language_koreana": "Κορεατικά",
	"language_selection_english": "English (Αγγλικά)",
	"language_selection_spanish": "Español — España (Ισπανικά — Ισπανία)",
	"language_selection_french": "Français (Γαλλικά)",
	"language_selection_italian": "Italiano (Ιταλικά)",
	"language_selection_german": "Deutsch (Γερμανικά)",
	"language_selection_greek": "Ελληνικά",
	"language_selection_koreana": "한국어 (Κορεατικά)",
	"language_selection_korean": "한국어 (Κορεατικά)",
	"language_selection_schinese": "简体中文 (Απλοποιημένα Κινεζικά)",
	"language_selection_tchinese": "繁體中文 (Παραδοσιακά Κινεζικά)",
	"language_selection_russian": "Русский (Ρωσικά)",
	"language_selection_thai": "ไทย (Ταϊλανδέζικα)",
	"language_selection_japanese": "日本語 (Ιαπωνικά)",
	"language_selection_portuguese": "Português (Πορτογαλικά)",
	"language_selection_brazilian": "Português - Brasil (Πορτογαλικά - Βραζιλία)",
	"language_selection_polish": "Polski (Πολωνικά)",
	"language_selection_danish": "Dansk (Δανεζικά)",
	"language_selection_dutch": "Nederlands (Ολλανδικά)",
	"language_selection_finnish": "Suomi (Φινλανδικά)",
	"language_selection_norwegian": "Norsk (Νορβηγικά)",
	"language_selection_swedish": "Svenska (Σουηδικά)",
	"language_selection_czech": "Čeština (Τσέχικα)",
	"language_selection_hungarian": "Magyar (Ουγγρικά)",
	"language_selection_romanian": "Română (Ρουμανικά)",
	"language_selection_bulgarian": "Български (Βουλγάρικα)",
	"language_selection_pirate": "Πειρατικά (Γιαρ!)",
	"language_selection_turkish": "Türkçe (Τούρκικα)",
	"language_selection_ukrainian": "Українська (Ουκρανικά)",
	"language_selection_vietnamese": "Tiếng Việt (Βιετναμέζικα)",
	"language_selection_arabic": "العربية (Αραβικά)",
	"language_selection_spanish_mexican": "Español — Mexicano (Ισπανικά — Μεξικό)",
	"language_selection_latam": "Español — Latinoamérica (Ισπανικά — Λατινική Αμερική)",
	"Bbcode_Originally_Posted_By": "Αναρτήθηκε αρχικά από",
	"Bbcode_No_Match": "Κανένα ταίριασμα στο υποστηριζόμενο BBCode",
	"Editor_Bold": "Έντονα",
	"Editor_Underline": "Υπογραμμισμένα",
	"Editor_Italics": "Πλάγια",
	"Editor_StrikeThrough": "Διαγραμμένα",
	"Editor_Link": "Εισαγωγή συνδέσμου",
	"Editor_Unordered": "Μη διατεταγμένη λίστα",
	"Editor_Ordered": "Διατεταγμένη λίστα",
	"Editor_Header": "Κεφαλίδα",
	"Editor_Header2": "Κεφαλίδα 2",
	"Editor_Header3": "Κεφαλίδα 3",
	"Editor_Emoticon": "Προσθήκη Emoticon",
	"EventEditor_ConvertHTML_Error": "Αποτυχία μετατροπής HTML",
	"EventEditor_ConvertHTML_Error_Desc": "Αποτυχία μετατροπής HTML σε bbcode με το ακόλουθο σφάλμα: «%1$s»",
	"EventEditor_InsertLinkURL": "Εισαγωγή URL",
	"EventEditor_FormattingHelp_GetHelpLink": "Βοήθεια μορφοποίησης",
	"EventEditor_ImportHTML": "Εισαγωγή HTML",
	"EventEditor_ImportFromHTML": "Εισαγωγή από HTML",
	"EventEditor_ImportFromHTML_ttip": "Εισαγωγή από HTML. Θα μετατρέψει αυτόματα το html σας σε ετικέτες μορφοποίησης Steam.",
	"EventEditor_ImportFromHTML_Instruction": "Πληκτρολογήστε ή επικολλήστε HTML παρακάτω.",
	"EventEditor_ImportFromHTML_PreserveNewlines": "Διατήρηση νέων γραμμών",
	"EventEditor_ImportFromHTML_PreserveNewlines_Hint": "Στην HTML, τα σύμβολα νέας γραμμής συνήθως δεν έχουν επίδραση, αλλά στο BBCode θα εμφανίζονται ως κενές γραμμές. Αν χρησιμοποιήσατε ετικέτες <p> ή <br>, αφήστε το κενό. Αν χρησιμοποιείτε συνήθως λογισμικό ιστολογίου που προσθέτει αυτόματα ετικέτες <br> για νέες γραμμές, πιθανώς χρειάζεται να επιλέξετε αυτό το κουτί.",
	"EventEditor_ImportFromHTML_ConvertToBBCode": "Μετατροπή σε BBCode:",
	"EventEditor_ImportFromHTML_ConversionInProgress": "Μετατροπή σε εξέλιξη. Παρακαλούμε μην κλείσετε παράθυρο διαλόγου.",
	"EventEditor_ImportFromHTML_ConvertFinished": "Η μετατροπή τελείωσε. Μπορείτε τώρα να κλείσετε με ασφάλεια αυτό το παράθυρο διαλόγου.",
	"EventEditor_InsertYouTube": "Εισαγωγή βίντεο YouTube™",
	"EventEditor_InsertYouTube_Left": "Αριστερή στοίχιση",
	"EventEditor_InsertYouTube_Right": "Δεξιά στοίχιση",
	"EventEditor_InsertYouTube_Full": "Πλήρες πλάτος",
	"EventEditor_InsertYouTube_URL": "Πλήρης URL",
	"EventEditor_InsertYouTube_Position": "Θέση",
	"EventEditor_InsertYouTube_Placholder": "Εισαγωγή URL YouTube™",
	"EventEditor_InsertYouTube_NoURL": "Παρακαλούμε εισάγετε μια έγκυρη URL YouTube™.",
	"EventEditor_InsertYouTube_Summary": "Έκδοση περιγραφικής περίληψης",
	"EventEditor_InsertImage": "Εισαγωγή εικόνας από το διαδίκτυο",
	"EventEditor_InsertImage_Title": "Εισαγωγή εικόνας",
	"EventEditor_InsertImage_Desc": "Εισάγετε ένα URL για μια εικόνα (όπως .jpg .gif ή .png) για να συμπεριληφθεί αυτή η εικόνα στην ανάρτησή σας.",
	"EventEditor_InsertImage_URL": "URL εικόνας",
	"EventEditor_InsertImage_Placeholder": "Εισάγετε μια έγκυρη URL",
	"EventEditor_InsertImage_Anchor": "Προαιρετικό: URL για άνοιγμα όταν πατηθεί η εικόνα",
	"EventEditor_LinkDescription": "Κείμενο για προβολή",
	"EventEditor_LinkURL": "URL",
	"EventEditor_YouTubeVideoTitle": "Βίντεο YouTube™: %1$s",
	"EventEditor_YouTubeVideoViews": "Προβολές: %1$s",
	"EventEditor_Author": "Από: %1$s",
	"EventEditor_Comments": "Σχόλια",
	"EventEditor_UpVotes": "Θετικές ψήφοι",
	"EventEditor_DownVotes": "Αρνητικές ψήφοι",
	"Error_Message": "Μήνυμα σφάλματος",
	"Warning_Message": "Μήνυμα ειδοποίησης",
	"Informational_Message": "Μήνυμα πληροφόρησης",
	"Error_Description": "Παρουσιάστηκε σφάλμα (κωδικός: %1$s) με λεπτομέρειες: (%2$s)",
	"Error_FailureNotice": "Αποτυχία",
	"Error_GenericFailureDescription": "Συγγνώμη, αυτό δε λειτούργησε.",
	"Image_ErrorTitle": "Αποτυχία φόρτωσης εικόνας «%1$s», τα πιθανά προβλήματα περιλαμβάνουν:",
	"Image_Error_msg1": "Ελέγξτε ότι η διαδρομή στην εικόνα είναι σωστή.",
	"Image_Error_msg2": "Ελέγξτε αν ο διακομιστής που φιλοξενεί την εικόνα υποστηρίζει ανώνυμη πρόσβαση. Η κονσόλα περιηγητή μπορεί να υποδεικνύει ένα σφάλμα «Access-Control-Allow-Origin» αν δεν υποστηρίζει.",
	"Image_Error_suggestion": "Μπορείτε πάντα να μεταφορτώσετε την εικόνα στο Steam για να φιλοξενήσει το περιεχόμενο δωρεάν.",
	"Platform_Hint_Mobile": "σε κινητή συσκευή",
	"Platform_Hint_BigPicture": "σε Big Picture",
	"Platform_Hint_VR": "σε Εικονική πραγματικότητα",
	"Hover_SteamLevel": "Επίπεδο Steam",
	"Hover_BadgeXP": "%1$s εμπειρία",
	"PersonaStateOffline": "Εκτός σύνδεσης",
	"PersonaStateAway": "Απών",
	"PersonaStateOnline": "Συνδεδεμένος",
	"PersonaStateBlocked": "Αποκλεισμένος",
	"PersonaStateInGame": "Σε παιχνίδι",
	"PersonaStateBusy": "Απασχολημένος",
	"PersonaStateSnooze": "Απών",
	"PersonaStateInNonSteamGame": "Σε παιχνίδι εκτός Steam",
	"PersonaStateWatchingBroadcast": "Παρακολουθεί μετάδοση:",
	"PersonaStateLookingToTrade": "Αναζητεί ανταλλαγή",
	"PersonaStateLookingToPlay": "Αναζητεί παιχνίδι",
	"PersonaStateLastSeen": "Τελευταία σύνδεση %1$s",
	"PersonaStateLastSeen_JustNow": "Τελευταία σύνδεση πριν από μια στιγμή",
	"PersonaStateRemotePlayTogether": "Remote Play Together",
	"User_WantsToPlay": "Σύνδεση",
	"User_ToggleDoNotDisturb": "Μην ενοχλείτε",
	"User_GameInfoHidden": "Η κατάσταση παιχνιδιού σας είναι κρυμμένη από τους φίλους εξαιτίας των ρυθμίσεων απορρήτου σας",
	"User_LimitedAccount": "Ο λογαριασμός σας δεν πληροί τις απαιτήσεις για να χρησιμοποιήσετε αυτή τη λειτουργία. %1$s για περισσότερες πληροφορίες.",
	"User_LimitedAccount_UrlInfo": "Επισκεφτείτε την Υποστήριξη Steam",
	"isNickname": "Το ψευδώνυμό σας για αυτό το φίλο",
	"Friend_Menu_NotAFriendLabel": "ΔΕΝ ΕΙΣΤΕ ΦΙΛΟΙ",
	"Friend_Menu_NotAFriendRequesting": "ΖΗΤΑΕΙ ΝΑ ΓΙΝΕΤΕ ΦΙΛΟΙ",
	"DASHPlayerStats_BytesReceived": "Byte που λήφθηκαν:",
	"DASHPlayerStats_BufferingResolution": "Ανάλυση buffer:",
	"DASHPlayerStats_PlaybackResolution": "Ανάλυση αναπαραγωγής:",
	"DASHPlayerStats_HtmlResolution": "Ανάλυση οθόνης:",
	"DASHPlayerStats_DroppedFrames": "Χαμένα καρέ:",
	"DASHPlayerStats_VideoBuffered": "Βίντεο στο buffer:",
	"DASHPlayerStats_AudioBuffered": "Ήχος στο buffer:",
	"DASHPlayerStats_BandwidthRequired": "Απαιτούμενο εύρος ζώνης (Mbps):",
	"DASHPlayerStats_BandwidthVideo": "Εύρος ζώνης βίντεο (Mbps):",
	"DASHPlayerStats_BandwidthNums": "Ελαχ/Μεγ/Μέσο εύρος ζώνης (Mbps):",
	"DASHPlayerStats_DownloadNums": "Ελαχ/Μεγ/Μέσοι χρόνοι λήψης (Δευτ):",
	"DASHPlayerStats_ContentServer": "Διακομιστής:",
	"DASHPlayerStats_ActiveDownloads": "Ενεργές λήψεις:",
	"DASHPlayerStats_StallEvents": "Συμβάντα καθυστέρησης:",
	"DASHPlayerStats_FailedDownloads": "Συμβάντα αποτυχημένων λήψεων:",
	"DASHPlayerStats_VideoDownloadProgress": "Πρόοδος λήψης βίντεο:",
	"DASHPlayerStats_TimeToFirstFrame": "Χρόνος μέχρι το πρώτο καρέ (ms):",
	"DASHPlayerStats_DroppingFrames": "Ανιχνευμένες μόνιμες απώλειες καρέ:",
	"DASHPlayerStats_CurrentFPS": "Τρέχον FPS:",
	"DASHPlayerStats_Tracking": "Συλλογή δεδομένων...",
	"DASHPlayerStats_PlaybackRate": "Ταχύτητα αναπαραγωγής:",
	"DASHPlayerStats_VideoBufferRange": "Βίντεο στο buffer %1$s:",
	"DASHPlayerStats_AudioBufferRange": "Ήχος στο buffer %1$s:",
	"DASHPlayerStats_VideoNoRangeInformation": "Χωρίς τμήματα βίντεο στο buffer",
	"DASHPlayerStats_AudioNoRangeInformation": "Χωρίς τμήματα ήχου στο buffer",
	"DASHPlayerControls_GoLive": "ΖΩΝΤΑΝΑ",
	"DASHPlayerControls_IsLive": "Ζωντανά",
	"DASHPlayerControls_ClickToPlay": "ΠΑΤΗΣΤΕ ΓΙΑ ΕΚΚΙΝΗΣΗ",
	"DASHPlayerControls_IsReplay": "ΑΝΑΜΕΤΑΔΟΣΗ",
	"DASHPlayerControls_Start": "Εκκίνηση",
	"DASHPlayerControls_End": "Λήξη",
	"Played_Minutes": "%1$s λεπτά",
	"Played_Hours": "%1$s ώρες",
	"WriteReview_Dialog_PostReview": "Ανάρτηση κριτικής",
	"WriteReview_Dialog_ReviseReview": "Αναθεώρηση κριτικής",
	"WriteReview_Dialog_Title": "Κριτική",
	"WriteReview_Dialog_Playtime": "Έχετε παίξει για %1$s",
	"WriteReview_Dialog_Playtime_Software": "Έχετε χρησιμοποιήσει αυτόν τον τίτλο για %1$s",
	"WriteReview_Dialog_Playtime_Revise": "Έχετε παίξει επιπλέον %1$s",
	"WriteReview_Dialog_RecommendGame": "Θα προτείνατε αυτό το παιχνίδι σε άλλους παίκτες;",
	"WriteReview_Dialog_RecommendGame_Software": "Θέλετε να προτείνετε αυτό το λογισμικό σε άλλους παίκτες;",
	"WriteReview_Dialog_RecommendGame_Revise": "Θέλετε να αναθεωρήσετε την κριτική σας;",
	"WriteReview_Dialog_GetHelp_Btn": "Λάβετε βοήθεια με την αγορά σας",
	"WriteReview_Dialog_Visibility": "Ορατότητα:",
	"WriteReview_Dialog_Public": "Δημόσια",
	"WriteReview_Dialog_Friends": "Φίλοι μόνο",
	"WriteReview_Dialog_Yes": "Ναι",
	"WriteReview_Dialog_No": "Όχι",
	"WriteReview_Dialog_GetSupport_Btn": "Λάβετε βοήθεια με την αγορά σας",
	"WriteReview_Dialog_GetSupport_Desc": "Λάβετε τεχνικές συμβουλές, επίσημη υποστήριξη πελατών ή ζητήστε επιστροφή χρημάτων.",
	"WriteReview_Dialog_AddReview_Btn": "Ανάρτηση κριτικής",
	"WriteReview_Dialog_AddReview_Desc": "Μοιραστείτε τις σκέψεις σας με άλλους παίκτες.",
	"WriteReview_Dialog_AddReview_Header": "Θέλετε να αναρτήσετε μια κριτική;",
	"WriteReview_Dialog_ReviewInstructions_Link": "κανόνες και τις οδηγίες",
	"WriteReview_Dialog_ReviewInstructions": "Παρακαλούμε περιγράψτε τι σας άρεσε ή όχι σε αυτό το προϊόν και αν το προτείνετε σε άλλους. Θυμηθείτε να είστε ευγενικοί και να ακολουθείτε τους %1$s. Απαιτείται μια περιγραφή για να αναρτήσετε την πρότασή σας.",
	"WriteReview_Dialog_AllowComments": "Να επιτρέπονται σχόλια",
	"WriteReview_Dialog_FreeDisclaimer": "Επιλέξτε αυτό το πλαίσιο ελέγχου αν λάβατε αυτό το προϊόν δωρεάν",
	"WriteReview_Dialog_FreeDisclaimer_Tooltip": "Επιλέξτε αυτό το κουτί εάν λάβατε αυτό το προϊόν δωρεάν. Θα εμφανιστεί «Έλαβε το προϊόν δωρεάν» μαζί με την κριτική σας. Αν λάβατε επιπλέον αποζημίωση για την κριτική αυτού του παιχνιδιού, θα πρέπει να το συμπεριλάβετε στο κείμενο της κριτικής σας.",
	"WriteReview_Dialog_FormattingHelp": "Βοήθεια μορφοποίησης",
	"WriteReview_Dialog_GenericError": "Αντιμετωπίσαμε ένα πρόβλημα κατά την ανάρτηση της κριτικής σας. Παρακαλούμε δοκιμάστε ξανά αργότερα.",
	"WriteReview_Dialog_NoTextError": "Παρακαλούμε περιγράψτε τι σας άρεσε ή όχι σε αυτό το προϊόν.",
	"WriteReview_Dialog_Delay": "Ίσως αργότερα",
	"Broadcast_View_Stack_H": "Οριζόντια προβολή",
	"Broadcast_View_Stack_V": "Κατακόρυφη προβολή",
	"Broadcast_View_Theater": "Λειτουργία θεάτρου",
	"Broadcast_View_Fullscreen": "Πλήρης οθόνη",
	"Broadcast_View_HideChat": "Απόκρυψη συνομιλίας",
	"Broadcast_View_ShowBothChats": "Εμφάνιση και των δύο συνομιλιών",
	"Broadcast_View_ShowSingleChats": "Εμφάνιση μίας συνομιλίας",
	"Broadcast_View_ShowChat": "Εμφάνιση συνομιλίας",
	"Broadcast_Store_FreeToPlay": "Δωρεάν για παίξιμο",
	"PartnerEvent_1": "Άλλη εκδήλωση",
	"PartnerEvent_2": "Συμβάν παιχνιδιού",
	"PartnerEvent_3": "Πάρτι",
	"PartnerEvent_4": "Εκδήλωση συνάντησης",
	"PartnerEvent_5": "Ειδικός σκοπός",
	"PartnerEvent_6": "Μουσική και τέχνες",
	"PartnerEvent_7": "Αθλητικό συμβάν",
	"PartnerEvent_8": "Ζωντανό ταξίδι",
	"PartnerEvent_9": "Συνομιλία",
	"PartnerEvent_9_editor": "Μια συνομιλία ή συνεδρία ερωτήσεων",
	"PartnerEvent_10": "Κυκλοφορία παιχνιδιού",
	"PartnerEvent_10_editor": "Το παιχνίδι κυκλοφορεί τώρα!",
	"PartnerEvent_11": "Ζωντανή μετάδοση",
	"PartnerEvent_12": "Μικρή ενημέρωση",
	"PartnerEvent_13": "Κανονική ενημέρωση",
	"PartnerEvent_14": "Ενημέρωση Major",
	"PartnerEvent_15": "Κυκλοφορία DLC",
	"PartnerEvent_16": "Μελλοντική κυκλοφορία",
	"PartnerEvent_16_editor": "Το παιχνίδι κυκλοφορεί σε μια συγκεκριμένη ημερομηνία",
	"PartnerEvent_17": "Μετάδοση τουρνουά esport",
	"PartnerEvent_18": "Μετάδοση ροής δημιουργών",
	"PartnerEvent_19": "Διάσημη μετάδοση",
	"PartnerEvent_20": "Έκπτωση παιχνιδιού",
	"PartnerEvent_20_editor": "Έκπτωση σε αυτό το παιχνίδι",
	"PartnerEvent_21": "Έκπτωση αντικειμένου ή DLC",
	"PartnerEvent_21_editor": "Έκπτωση σε αντικείμενα εντός παιχνιδιού ή DLC",
	"PartnerEvent_22": "Επαύξηση εμπειρίας",
	"PartnerEvent_23": "Εκδήλωση λήψης αντικειμένων",
	"PartnerEvent_24": "Συμβάν προνομίων",
	"PartnerEvent_25": "Συμβάν πρόκλησης",
	"PartnerEvent_26": "Διαγωνισμός",
	"PartnerEvent_27": "Συμβάν πραγμ. ζωής",
	"PartnerEvent_27_editor": "Παρεύρεση σε έκθεση, συνάντηση ή συνέδριο",
	"PartnerEvent_28": "Νέα",
	"PartnerEvent_28_editor": "Ανακοίνωση / Νέα",
	"PartnerEvent_29": "Κυκλοφορία δοκιμής",
	"PartnerEvent_29_editor": "Πρόσκληση σε δοκιμή / Νέα",
	"PartnerEvent_30": "Ενημερώθηκε περιεχόμενο εντός παιχνιδιού",
	"PartnerEvent_31": "Δωρεάν δοκιμή",
	"PartnerEvent_32": "Κυκλοφορία σεζόν ή πάσου μάχης",
	"PartnerEvent_33": "Ενημέρωση σεζόν",
	"PartnerEvent_34": "Προώθηση άλλου",
	"PartnerEvent_35": "Γενικό συμβάν εντός παιχνιδιού",
	"PartnerEvent_Other": "Άλλη εκδήλωση",
	"PartnerEvent_SteamAwardNominations": "Αίτημα πρότασης για Βραβεία Steam",
	"PartnerEvent_SteamAwardVoteRequest": "Αίτημα ψήφου για Βραβεία Steam",
	"SocialMedia_Type_ShortName_1": "Steam",
	"SocialMedia_Type_ShortName_2": "Google",
	"SocialMedia_Type_ShortName_3": "Facebook",
	"SocialMedia_Type_ShortName_4": "Twitter",
	"SocialMedia_Type_ShortName_5": "Twitch",
	"SocialMedia_Type_ShortName_6": "YouTube",
	"SocialMedia_Type_ShortName_7": "Facebook",
	"MobileLogin_NoSteamAccount": "Δεν έχετε λογαριασμό Steam;",
	"MobileLogin_CreateAccount": "Δημιουργήστε έναν δωρεάν λογαριασμό",
	"MobileLogin_ForgotPassword": "Ξεχάσατε το όνομα λογαριασμού ή τον κωδικό;",
	"MobileLogin_RefreshCaptcha": "Ανανέωση",
	"MobileLogin_SignIn": "Σύνδεση",
	"MobileLogin_SigningIn": "Γίνεται σύνδεση",
	"MobileLogin_AccountName": "Όνομα λογαριασμού Steam",
	"MobileLogin_Password": "Κωδικός",
	"MobileLogin_CaptchaVerification": "Επαλήθευση",
	"MobileLogin_Enter2FA": "Εισάγετε τον κωδικό που δημιουργήθηκε στην ενότητα Steam Guard της εφαρμογής Steam για κινητά.",
	"MobileLogin_Enter2FAHelp": "Δεν έχω πρόσβαση στον κωδικό Steam Guard μου",
	"MobileLogin_EnterSteamguard": "Δεν έλαβα e-mail Stam Guard",
	"MobileLogin_SteamguardCode": "Κωδικός Steam Guard",
	"MobileLogin_SteamguardSubmit": "Υποβολή & σύνδεση",
	"MobileLogin_SentSteamguard_1": "Στείλαμε ένα μήνυμα στο",
	"MobileLogin_SentSteamguard_2": "e-mail σας. Εισάγετε τον κωδικό Steam Guard που περιέχει.",
	"MobileLogin_IncorrectSteamGuard": "Ο κωδικός Steam Guard που εισήχθη είναι λάθος. Ελέγξτε τον κωδικό και προσπαθήστε ξανά.",
	"MobileLogin_Error_RateLimitExceeded": "Υπήρξαν πάρα πολλές αποτυχημένες προσπάθειες σύνδεσης από το δίκτυό σας σε σύντομο χρονικό διάστημα. Παρακαλούμε περιμένετε και προσπαθήστε ξανά αργότερα.",
	"Login_SignIn": "Σύνδεση",
	"Login_SigningIn": "Γίνεται σύνδεση",
	"Login_AccountName": "Όνομα λογαριασμού Steam",
	"Login_Password": "Κωδικός",
	"Login_RememberMe": "Να με θυμάστε σε αυτόν τον υπολογιστή",
	"Login_ForgotPassword": "Ξεχάσατε το όνομα λογαριασμού ή τον κωδικό;",
	"Login_NoSteamAccount": "Δεν έχετε λογαριασμό Steam;",
	"Login_CreateAccount": "Δημιουργήστε έναν δωρεάν λογαριασμό",
	"Login_CaptchaVerification": "Επιβεβαιώστε ότι είστε άνθρωπος επανεισάγοντας τους χαρακτήρες στο captcha.",
	"Login_RefreshCaptcha": "Ανανέωση",
	"Login_Enter2FA": "Εισάγετε τον κωδικό που δημιουργήθηκε στην ενότητα Steam Guard της εφαρμογής Steam για κινητά.",
	"Login_Enter2FAHelp": "Δεν έχω πρόσβαση στον κωδικό Steam Guard μου",
	"Login_EnterSteamguard": "Δεν έλαβα e-mail κωδικού Steam Guard μου",
	"Login_SteamguardSubmit": "Υποβολή & σύνδεση",
	"Login_SentSteamguard": "Σας στείλαμε ένα μήνυμα στο e-mail σας, %1$s. Εισάγετε τον κωδικό Steam Guard που παρείχαμε.",
	"Login_SignOut": "Αποσύνδεση",
	"Emoticon_Search": "Αναζήτηση emoticon",
	"Chat_Settings_Error_ChatFileTooLarge": "Το %1$s είναι πολύ μεγάλο (10MB το πολύ).",
	"Chat_Settings_Error_ChatFileTypeNotSupported": "Αδυναμία μεταφόρτωσης %1$s. Υποστηρίζονται μόνο τύποι  jpg, png, gif, webm, mpg και ogv.",
	"ConnectionTrouble_FailedToConnect": "Αποτυχία σύνδεσης στο Steam",
	"Chat_Upload_ErrorCloud": "Αποτυχία μεταφόρτωσης δεδομένων εικόνας στο διακομιστή cloud.",
	"Chat_Settings_Error_ServerError": "Παρουσιάστηκε σφάλμα διακομιστή",
	"Broadcast_ViewerCount": "%1$s θεατές",
	"Broadcast_VideoContext_ToggleStats": "Εναλλαγή τεχνικών στατιστικών",
	"Broadcast_VideoContext_OpenStore": "Προβολή καταστήματος",
	"Broadcast_None": "Καμία",
	"BroadcastWatch_MinBrowser": "Ο περιηγητής διαδικτύου σας δεν υποστηρίζει το ελάχιστο σύνολο χαρακτηριστικών που απαιτούνται για την παρακολούθηση αυτής της μετάδοσης",
	"BroadcastWatch_RequestFailed": "Αποτυχία φόρτωσης μετάδοσης",
	"BroadcastWatch_NotAvailable": "Ο ΜΕΤΑΔΟΤΗΣ ΕΙΝΑΙ ΕΚΤΟΣ ΣΥΝΔΕΣΗΣ",
	"BroadcastWatch_WaitingForResponse": "Αναμονή έγκρισης για παρακολούθηση",
	"BroadcastWatch_WaitingForStart": "Η μετάδοση ξεκινάει",
	"BroadcastWatch_WaitingForReconnect": "Επανασύνδεση στη μετάδοση",
	"BroadcastWatch_ServerLoad": "Το Steam αντιμετωπίζει υψηλό φόρτο μεταδόσεων και αδυνατεί αυτή τη στιγμή να κρατήσει μια θέση διακομιστή για έναρξη της μετάδοσης. Προσπαθήστε ξανά σε μερικά λεπτά.",
	"BroadcastWatch_SystemNotSupported": "Η μετάδοση Steam δεν υποστηρίζεται αυτή τη στιγμή στο σύστημα του μεταδότη",
	"BroadcastWatch_UserRestricted": "Ο μεταδότης είναι αυτή τη στιγμή αποκλεισμένος από μεταδόσεις στο Steam",
	"BroadcastWatch_PoorUploadQuality": "Ο μεταδότης αδυνατεί αυτή τη στιγμή να διατηρήσει μια σταθερή σύνδεση μετάδοσης στο Steam",
	"BroadcastChat_Reconnected": "Επανασυνδεθήκατε στη συνομιλία",
	"BroadcastChat_UnableToJoinChat": "Αδυναμία σύνδεσης στη συνομιλία",
	"BroadcastChat_NeverTell": "Ποτέ μην πείτε τον κωδικό σας σε κανέναν",
	"BroadcastChat_EnterResponse": "Πληκτρολογήστε για να συνομιλήσετε",
	"BroadcastChat_InsertEmoticon": "Προσθήκη Emoticon",
	"BroadcastChat_Send": "Αποστολή",
	"BroadcastChat_UserJoined": "Ο %1$s συνδέθηκε στη συνομιλία",
	"BroadcastChat_UserLeft": "Ο %1$s αποχώρησε από τη συνομιλία",
	"BroadcastChat_UserMuted": "Ο %1$s σιγάστηκε σε αυτό το κανάλι συνομιλίας",
	"BroadcastChat_UserMutedLocal": "Ο %1$s σιγάστηκε",
	"BroadcastChat_UserUnmutedLocal": "Καταργήθηκε η σίγαση του %1$s",
	"BroadcastChat_UserMuteFailed": "Αποτυχία σίγασης του %1$s. Παρακαλούμε προσπαθήστε ξανά.",
	"BroadcastChat_RemoveMessagesFailed": "Αποτυχία αφαίρεσης μηνυμάτων για %1$s. Παρακαλούμε προσπαθήστε ξανά.",
	"BroadcastChat_UserUnmuteFailed": "Αποτυχία κατάργησης σίγασης του %1$s. Παρακαλούμε προσπαθήστε ξανά.",
	"BroadcastChat_YouMuted": "Έχετε σιγαστεί και δεν μπορείτε να στείλετε μηνύματα σε αυτή τη συνομιλία",
	"BroadcastChat_FailedToSendMsg": "Αποτυχία αποστολής μηνύματος συνομιλίας: %1$s",
	"BroadcastChat_Cooldown": "Στέλνετε μηνύματα πολύ γρήγορα, προσπαθήστε ξανά σε %1$s δευτερόλεπτα.",
	"BroadcastChat_Mute": "Σίγαση",
	"BroadcastChat_Unmute": "Κατάργηση σίγασης",
	"BroadcastChat_MuteLocal": "Σίγαση τοπικά",
	"BroadcastChat_UnmuteLocal": "Κατάργηση τοπικής σίγασης",
	"BroadcastChat_Login": "Συνδεθείτε για να συμμετάσχετε στη συνομιλία",
	"BroadcastChat_LimitedUser": "Περιορισμένη πρόσβαση στη συνομιλία",
	"BroadcastChat_RemoveMessages": "Αφαίρεση των μηνυμάτων αυτού του χρήστη",
	"BroadcastChat_Blocked": "Μόνο οι κάτοχοι παιχνιδιού μπορούν να στέλνουν μηνύματα κατά τη διάρκεια αυτής της μετάδοσης.",
	"BroadcastChat_half_Mute": "Σίγαση χρήστη για 12 ώρες",
	"BroadcastChat_day_Mute": "Σίγαση χρήστη για μια ημέρα",
	"BroadcastChat_week_Mute": "Σίγαση χρήστη για μια εβδομάδα",
	"BroadcastChat_perm_Mute": "Σίγαση χρήστη μόνιμα",
	"BroadcastChat_half_Shadow": "Κρυφή σίγαση χρήστη για 12 ώρες",
	"BroadcastChat_day_Shadow": "Κρυφή σίγαση χρήστη για μια ημέρα",
	"BroadcastChat_week_Shadow": "Κρυφή σίγαση χρήστη για μια εβδομάδα",
	"BroadcastChat_perm_Shadow": "Κρυφή σίγαση χρήστη μόνιμα",
	"BroadcastChat_Add_Moderator": "Ορισμός χρήστη ως συντονιστή",
	"BroadcastChat_Remove_Moderator": "Αφαίρεση κατάστασης συντονιστή από χρήστη",
	"BroadcastChat_Change_Moderator_Title": "Αλλαγή κατάστασης συντονιστή στον χρήστη",
	"BroadcastChat_Change_Add_Confirm": "Θέλετε σίγουρα να προσθέσετε τον ακόλουθο χρήστη ως συντονιστή; Θα μπορούν να θέτουν σε σίγαση άλλους χρήστες στη συνομιλία μετάδοσης.",
	"BroadcastChat_Change_Remove_Confirm": "Θέλετε σίγουρα να αφαιρέσετε τον ακόλουθο χρήστη από συντονιστή;",
	"BroadcastChat_Tooltip_Show_Chat_Viewers": "Εμφάνιση λίστας χρηστών που είναι αυτή τη στιγμή στο παράθυρο συνομιλίας.",
	"BroadcastChat_Tooltip_Minimize_Chat": "Ελαχιστοποίηση παραθύρου συνομιλίας",
	"BroadcastChat_Tooltip_Maximize_Chat": "Μεγιστοποίηση παραθύρου συνομιλίας",
	"BroadcastChat_Tooltip_Popout_Chat": "Μεταφορά της συνομιλίας σε νέο παράθυρο",
	"BroadcastChat_ChatOnly_Title": "Μόνο συνομιλία μετάδοσης",
	"BroadcastChat_DefaultMessage": "Καλώς ορίσατε στη συνομιλία!",
	"BroadcastChat_Moderator": "Συντονιστής",
	"BroadcastChat_Broadcaster": "Μεταδότης",
	"ChatEntryButton_Submit": "Αποστολή",
	"ChatEntryButton_Emoticon": "Επιλογέας emoticon",
	"ChatEntryButton_Flair": "Επιλογέας σήματος",
	"ChatEntryButton_SendEmbed": "Αποστολή ειδικού κειμένου",
	"Store_AddToCart": "Προσθήκη στο καλάθι",
	"YouTubePlayer_Loading": "Φόρτωση Youtube...",
	"home_page_live_broadcast": "Ζωντανά",
	"StoreBroadcast_Hide_Tooltip": "Εμφάνιση/απόκρυψη της ζωντανής μετάδοσης",
	"StoreBroadcast_Detault_popout_Title": "Τώρα σε μετάδοση",
	"StoreBroadcast_close_broadcast_popup": "Κλείνει το παράθυρο μετάδοσης. Δε θα ξανανοίξει αυτή τη συνεδρία.",
	"StoreBroadcast_Change_store_Broadcast_settings": "Αλλαγή ρυθμίσεων μετάδοσης",
	"Broadcast_Embedded_viewer": "%1$s θεατής",
	"Broadcast_Embedded_viewer_Plural": "%1$s θεατές",
	"BroadcastWatch_View_Broadcast_Page": "Προβολή σελίδας μετάδοσης",
	"Broadcast_Embed_Watch_SteamTV": "Παρακολουθήστε στο Steam.tv",
	"Broadcast_Embed_Watch_With_Frieds_SteamTV": "Παρακολουθήστε και συνομιλήστε με φίλους στο Steam.tv",
	"sale_three_section_hide_chat": "Απόκρυψη συνομιλίας",
	"sale_three_section_show_chat": "Εμφάνιση συνομιλίας",
	"btn_live_streams_all": "Προβολή όλων",
	"Broadcast_default_title_dev": "Ζωντανή μετάδοση: Δείτε τον δημιουργό να παίζει",
	"Broadcast_default_title_community": "Ζωντανή μετάδοση: Δείτε την κοινότητα να παίζει",
	"Broadcast_default_title_comp": "Ζωντανή μετάδοση: Δείτε αυτόν τον ανταγωνιστικό αγώνα",
	"Broadcast_default_title_speed": "Ζωντανή μετάδοση: Δείτε αυτό το speedrun",
	"Sale_BundleSave": "Περιλαμβάνει %1$s αντικείμενα.",
	"Sale_PackageSave": "Περιλαμβάνει %1$s αντικείμενα.",
	"Sale_ShowContents": "Εμφάνιση περιεχομένων",
	"Sale_ShowMore": "Εμφάνιση περισσότερων",
	"Sale_ShowLess": "Εμφάνιση λιγότερων",
	"Sale_OnWishlist": "Σε λίστα επιθυμιών",
	"Sale_InLibrary": "Στη συλλογή",
	"Sale_HiddenItems": "%1$s αντικείμενα είναι κρυμμένα λόγω %2$s",
	"Sale_HiddenItem_Single": "%1$s αντικείμενο είναι κρυμμένο λόγω %2$s",
	"Sale_StorePreferences": "των προτιμήσεων καταστήματός σας",
	"Sale_SeeAllSpecials": "Δείτε όλες τις προσφορές",
	"Sale_AddToWishlist": "Προσθήκη σε λίστα επιθυμιών",
	"Sale_RemoveFromWishlist": "Αφαίρεση από τη λίστα επιθυμιών",
	"Sale_Preferences": "Προτιμήσεις",
	"Sale_PlaceHolder": "Λειτ. Προεπισκόπησης: Αυτή η ενότητα δεν έχει κάψουλες. Δε θα εμφανιστεί στη σελίδα χρήστη αν είναι άδειο",
	"Sale_SmartPlaceHolder": "Λειτ. Προεπισκόπησης: Αυτή η έξυπνη ενότητα δεν έχει εφαρμογές για εσάς. Δε θα εμφανιστεί στη σελίδα χρήστη αν είναι άδειο.",
	"Sale_default_label": "(χωρίς τίτλο)",
	"Sale_default_label_OnSale": "Σε έκπτωση",
	"Sale_default_label_TopSellers": "ΚΟΡΥΦΑΙΑ ΣΕ ΠΩΛΗΣΕΙΣ",
	"Sale_default_label_FreeToPlay": "Δωρεάν",
	"Sale_default_label_HorrorGames": "Παιχνίδια τρόμου",
	"Sale_default_label_HorrorVR": "Τρόμου VR",
	"Sale_default_label_HorrorFreeToPlay": "Δωρεάν τρόμου",
	"Sale_default_label_HalloweenEventsHorror": "Συμβάντα Halloween σε παιχνίδια τρόμου",
	"Sale_default_label_HalloweenEventsNonHorror": "Συμβάντα Halloween σε παιχνίδια μη τρόμου",
	"Sale_default_label_MoreHalloweenEvents": "Περισσότερα συμβάντα Halloween",
	"Sale_default_label_MoreHalloweenEventsNonHorror": "Περισσότερα συμβάντα Halloween σε παιχνίδια μη τρόμου",
	"Sale_default_label_NewAndUpcomingHorror": "Νέα και επερχόμενα τρόμου",
	"Sale_default_label_RemotePlay_Together": "Play Together – ΜΕ ΜΑΚΡΙΝΟΥΣ ΦΙΛΟΥΣ",
	"Sale_default_label_RemotePlay_Phone": "Play Anywhere - ΣΤΟ ΤΗΛΕΦΩΝΟ ΣΑΣ",
	"Sale_default_label_RemotePlay_Tablet": "Play Anywhere - ΣΤΟ ΤΑΜΠΛΕΤ ΣΑΣ",
	"Sale_default_label_RemotePlay_TV": "Play Anywhere - ΣΤΗΝ ΤΗΛΕΟΡΑΣΗ ΣΑΣ",
	"Sale_default_label_OnYourWishlist": "Στη λίστα επιθυμιών σας",
	"Sale_default_label_RecommendedForYou": "Προτεινόμενα για εσάς",
	"Sale_default_label_ComingSoon": "Προσεχώς",
	"Sale_default_label_JustAnnounced": "Μόλις ανακοινώθηκε",
	"Sale_default_label_JustUpdated": "Μόλις ενημερώθηκε",
	"Sale_default_label_FreeWeekend": "Δωρεάν σαββατοκύριακο",
	"Sale_default_label_FreeWeek": "Δωρεάν εβδομάδα",
	"Sale_default_label_PrePurchase": "Προαγοράστε τώρα",
	"Sale_default_label_NewReleases": "Νέες κυκλοφορίες",
	"Sale_default_label_JustReleased": "Μόλις κυκλοφόρησε",
	"Sale_default_label_Highlighted": "Επιλεγμένες προσφορές",
	"Sale_default_label_BackCat": "Παλαιότερος κατάλογος",
	"Sale_default_label_PlayForFree": "Παίξτε δωρεάν!",
	"Sale_defautl_label_FreeToKeep": "Για περιορισμένο χρόνο, εγκαταστήστε τώρα και κρατήστε το για πάντα",
	"SalePage_LoginPrompt": "Συνδεθείτε για να δείτε περισσότερα αντικείμενα επιλεγμένα μόνο για εσάς.",
	"SalePage_ParentApp_DLC": "DLC για",
	"SalePage_ParentApp_SoundTrack": "Soundtrack για",
	"SalePage_WatchForDrop_Minutes_Developer": "Παρακολουθήστε τη μετάδοση για %1$s λεπτά και λάβετε αντικείμενα από τον δημιουργό όταν λήξει το συμβάν!",
	"SalePage_WatchForDrop_Minutes_CreatorNamed": "Παρακολουθήστε τη μετάδοση για %1$s λεπτά και λάβετε αντικείμενα από %2$s όταν λήξει το συμβάν!",
	"SalePage_WatchForDrop_Hours_Developer": "Παρακολουθήστε τη μετάδοση για %1$s ώρες και λάβετε αντικείμενα από τον δημιουργό όταν λήξει το συμβάν!",
	"SalePage_WatchForDrop_Hours_CreatorNamed": "Παρακολουθήστε τη μετάδοση για %1$s ώρες και λάβετε αντικείμενα από %2$s όταν λήξει το συμβάν!",
	"SalePage_WatchForDrop_LearnMore": "Μάθετε περισσότερα για ρίψεις αντικειμένων εδώ.",
	"SalePage_Admin_SaleEventDay": "Προβολή ημέρας εκπτώσεων %1$s",
	"Steam_Settings_Compat_Launch_Prefix": "Τρέχει σε αυτόν τον υπολογιστή μέσω",
	"Steam_Settings_Compat_Launch_Name": "Steam Play.",
	"Steam_Settings_Compat_Launch_Forced": "επιλέχθηκε από εσάς για αυτόν τον τίτλο.",
	"Steam_Settings_Compat_Launch_Wildcard": "επιλέχθηκε από εσάς για όλους τους τίτλους.",
	"Steam_Settings_Compat_Launch_Whitelisted": "επιλέχθηκε από δοκιμή Valve.",
	"SteamAwards_EventMainTitle": "τα Βραβεία Steam",
	"SteamAwards_EventMainTitleSecondLine": "Υποψήφιος",
	"SteamAwards_EventCallToAction": "Έρχονται αυτό το Δεκέμβριο",
	"SteamAwards_EventVotingDateTeaser": "Δεκέμβριος 2019",
	"SteamAwards_EventVoteForGamePrompt": "Πατήστε παρακάτω για να ψηφίσετε το %1$s για την κατηγορία:",
	"SteamAwards_EventNominateGamePrompt_Long": "Προτείνετε το %1$s για την παρακάτω κατηγορία όπως προτείνεται από τους δημιουργούς του παιχνιδιού ή επιλέξτε μια διαφορετική κατηγορία",
	"SteamAwards_EventNominateGamePrompt_NoCategory": "Πατήστε εδώ για να προτείνετε το %1$s για μια κατηγορία στη σελίδα Βραβείων Steam.",
	"SteamAwards_Event_NominationsClosed": "Οι υποψηφιότητες έκλεισαν. Ψηφοφορία κατά τις Χειμερινές εκπτώσεις. Οι νικητές ανακοινώθηκαν 31 Δεκεμβρίου.",
	"SteamAwards_Event_VotesClosed": "Η ψηφοφορία έληξε. Πατήστε εδώ για να δείτε τα αποτελέσματα.",
	"SteamAwards_EventNominateGamePrompt_CategoryPrefix": "Προτείνετε για:",
	"SteamAwards_EventNominationAlternativeLinkText": "Ή επιλέξτε μια άλλη κατηγορία",
	"SteamAward_CategoryTitle_none": "Χωρίς κατηγορία",
	"SteamAward_CategoryDesc_none": "Μην προτείνετε μια συγκεκριμένη κατηγορία και αντ' αυτού επιτρέψτε τους θαυμαστές σας να επιλέξουν την κατηγορία που πιστεύουν ότι ταιριάζει στο παιχνίδι σας. Το συμβάν θα εξακολουθεί να συμπεριλαμβάνει ένα σύνδεσμο στη σελίδα υποψηφιοτήτων.",
	"SteamAward_CategoryTitle_goty": "Παιχνίδι της χρονιάς 2019",
	"SteamAward_CategoryDesc_goty": "Ίσως ήταν ο συναρπαστικός τρόπος παιχνιδιού του, ή η μαγευτική του ιστορία... οι καλοφτιαγμένοι χαρακτήρες του, ο αγνός σχεδιασμός του ή το εθιστικό παιχνίδι πολλών παικτών του. Όποιος και αν ήταν ο λόγος, ο νικητής του Βραβείου Παιχνιδιού της Χρονιάς είναι ένας απευθείας κλασικός τίτλος.",
	"SteamAward_CategoryTitle_vrgoty": "VR Παιχνίδι της χρονιάς 2019",
	"SteamAward_CategoryDesc_vrgoty": "Σχετικά με την καινοτομία στα παιχνίδια, δεν υπάρχει μεγαλύτερο βήμα πρωτοπορίας από την εικ. πραγματικότητα. Αν ήταν όπως το θέλουμε, όλοι οι δημιουργοί VR θα λάμβαναν ένα βραβείο που φτιάχνουν το μέλλον των συναρπαστικών παιχνιδιών και εμπειριών ασύγκριτες με οποιοδήποτε άλλο μέσο. Αλλά αφού υπάρχει μόνο ένα τρόπαιο, εξαρτάται από εσάς, ως μέλος της επιτροπής επιλογής των Βραβείων Steam, να βραβεύσετε μόνο ένα ως καλύτερο της χρονιάς.",
	"SteamAward_CategoryTitle_love": "Δουλειά αγάπης 2019",
	"SteamAward_CategoryDesc_love": "Αυτό το παιχνίδι κυκλοφορεί για καιρό. Η ομάδα έχει αφήσει αρκετά πίσω της τα αποκαλυπτήρια του δημιουργικού μωρού της, αλλά όντας καλοί γονείς, αυτοί οι δημιουργοί συνεχίζουν να προστατεύουν και να υποστηρίζουν τη δημιουργία τους. Σε αυτό το παιχνίδι, μέχρι και σήμερα, προστίθεται ακόμα νέο περιεχόμενο μετά από τόσα χρόνια.",
	"SteamAward_CategoryTitle_friends": "Καλύτερο με φίλους 2019",
	"SteamAward_CategoryDesc_friends": "Υπάρχουν μερικά παιχνίδια εκεί έξω που δεν είναι το ίδιο όταν τα παίζετε μόνος. Ίσως χρειάζεστε ένα φίλο να προσέχει τα νώτα σας. Ίσως χρειάζεστε ένα φίλο για να τον μαχαιρώσετε πισώπλατα. Όπως και να 'χει, όταν μαζεύονται φίλοι για να παίξουν αυτά τα παιχνίδια πάντα ξεφαντώνουν.",
	"SteamAward_CategoryTitle_gameplay": "Πιο πρωτοποριακό",
	"SteamAward_CategoryDesc_gameplay": "Αυτό το παιχνίδι είναι στην εμπροσθοφυλακή του πειραματισμού, ωθώντας τα όρια του μέσου με νέες συναρπαστικές αλληλεπιδράσεις και ριζοσπαστικές εκπλήξεις. Αυτό το παιχνίδι σκέφτεται έξω από το πλαίσιο και σας τραβάει και εσάς έξω μαζί!",
	"SteamAward_CategoryTitle_storyrich": "Εξαιρετικά πλούσια ιστορία",
	"SteamAward_CategoryDesc_storyrich": "Μερικές μέρες, μόνο ένα παιχνίδι με βαριά αφήγηση θα κάνει δουλειά και αυτό κουβαλάει πολλή. Είναι τόσο συναρπαστικό όσο μια σαπουνόπερα και καλοφτιαγμένο σαν σειρά τηλεόρασης: Μπράβο που μας κάνετε να νιώθουμε πράγματα!",
	"SteamAward_CategoryTitle_yousuck": "Καλύτερο παιχνίδι που είστε χάλια",
	"SteamAward_CategoryDesc_yousuck": "Τα παιχνίδια έχουν ένα τρόπο να μας ωθούν πέρα από τα όρια που νομίζουμε πως έχουμε. Όπως μια αλληλουχία μοντάζ, δουλεύουμε, εξασκούμε τα δάκτυλά μας να είναι γρήγορα και ευλύγιστα, μαθαίνουμε χρόνους και σημεία για βδομάδες. Αλλά στο τέλος, ανταμειβόμαστε με βαθύ αίσθημα ομορφιάς και προσωπικής ανάπτυξης. Εκτός αν πετάξατε την οθόνη σας από το παράθυρο την πρώτη μέρα.",
	"SteamAward_CategoryTitle_visual": "Εξαιρετικό οπτικό στιλ",
	"SteamAward_CategoryDesc_visual": "Αυτοί οι δημιουργοί είναι ο Willy Wonka των οπτικών εφέ. Το οπτικό στυλ δε φιλοδοξεί να πετύχει γραφική πιστότητα πραγματικού κόσμου (αν και είναι ευγενής στόχος από μόνος του)… περιγράφει μια ξεχωριστή εμφάνιση και αίσθημα που επικαλύπτει ένα ολόκληρο παιχνίδι. Αυτό το παιχνίδι παρουσιάζει οπτική συνοχή και έκφραση που δεν ταιριάζει μόνο στον κόσμο του παιχνιδιού, αλλά κάνει τον κόσμο μας να νοιάζει μουντός συγκριτικά.",
	"SteamAward_NominationConflictWarning_Title": "Αλλαγή της πρότασής σας;",
	"SteamAward_NominationConflictWarning_Explanation": "Μπορείτε να προτείνετε μόνο ένα παιχνίδι για κάθε κατηγορία και έχετε ήδη προτείνει το %1$s για αυτή. Θέλετε να προτείνετε το %2$s αντ' αυτού;",
	"SteamAward_VoteButton_PromptText": "Ψηφίστε",
	"SteamAward_VoteButton_AlreadyVotedText": "Καταχωρήθηκε",
	"SteamAward_VoteConflictWarning_Title": "Αλλάγη της ψήφου σας;",
	"SteamAward_VoteConflictWarning_Explanation": "Μπορείτε να ψηφίσετε μόνο ένα παιχνίδι για κάθε κατηγορία και έχετε ήδη ψηφίσει το %1$s για αυτή. Θέλετε να να αλλάξετε τη ψήφο σας σε %2$s;",
	"Store_VR_Support_OnlyVR": "Μόνο VR",
	"Store_VR_Support_SupportsVR": "Υποστήριξη VR",
	"Giveaway_CountDown": "Απομένουν %1$s μέχρι την επόμενη κλήρωση!",
	"Giveaway_CountDown2": "Χρόνος μέχρι την επόμενη κλήρωση.",
	"Giveaway_KeepWatching": "Συνεχίστε να παρακολουθείτε για μια πιθανότητα να κερδίσετε!",
	"Giveaway_RandomDraw": "Τυχαία κλήρωση σε εξέλιξη",
	"Giveaway_Congratulation": "Αριθμός τυχερών νικητών ως τώρα!",
	"Giveaway_Closed_NoWinnerInfo": "Η κλήρωση πλέον τελείωσε. Ευχαριστούμε για τη συμμετοχή σας.",
	"Giveaway_Closed": "Η κλήρωση πλέον τελείωσε με πάνω από %1$s τυχερούς νικήτες, ευχαριστούμε για τη συμμετοχή σας.",
	"Giveaway_LearnMore": "Πατήστε για να μάθετε περισσότερα για τα βραβεία, νικητές και κανόνες",
	"Lunar2020_CheckBackEachDay": "Γυρίστε πίσω κάθε μέρα για ένα νέο δώρο από τον Αυτοκράτορα!",
	"Lunar2020_CheckBackEachDayForStory": "Γυρίστε πίσω κάθε μέρα για ένα νέο κεφάλαιο",
	"Lunar2020_FirstGift": "Πρώτο δώρο",
	"Lunar2020_SecondGift": "Δεύτερο δώρο",
	"Lunar2020_ThirdGift": "Τρίτο δώρο",
	"Lunar2020_FourthGift": "Τέταρτο δώρο",
	"Lunar2020_GiftWasOpened": "ΑΝΟΙΧΘΗΚΕ",
	"Lunar2020_RereadStory": "εμφάνιση ιστορίας",
	"Lunar2020_GiftCanBeOpenedNow": "ΑΝΟΙΓΜΑ ΤΩΡΑ",
	"Lunar2020_GiftCanBeOpenedAfterThePreviousOne": "ΑΝΟΙΓΜΑ ΕΠΟΜΕΝΟΥ",
	"Lunar2020_GiftLockedUntilDate": "άνοιγμα %1$s",
	"Lunar2020_ErrorLoadingVideo": "Παρακαλούμε χρησιμοποιήστε έναν περιηγητή που υποστηρίζει βίντεο HTML για να ανοίξετε τον φάκελο σας.",
	"Lunar2020_LinkBackToSale": "Επιστροφή στις εκπτώσεις",
	"Lunar2020_LinkFromVideoToMarket": "Επισκεφτείτε την αγορά τώρα",
	"Lunar2020_ReceivedNumberOfTokens": "Λάβατε %1$s μάρκες",
	"Lunar2020_YourBalancePrefix": "Απομένουν",
	"Lunar2020_BalanceNumberOfTokens": "%1$s μάρκες",
	"Lunar2020_LimitedUserDialogTitle": "Αδυναμία ανοίγματος φακέλου",
	"Lunar2020_StoryTitle": "Ο ΜΕΓΑΛΟΣ ΑΓΩΝΑΣ ΤΟΥ ΑΥΤΟΚΡΑΤΟΡΑ",
	"Lunar2020_StorySubTitle": "Οι απαρχές του Κινέζικου Ζωδιακού κύκλου",
	"Lunar2020_StoryDayOneHeader": "Μέρος I από IV",
	"Lunar2020_StoryDayTwoHeader": "Μέρος II από IV",
	"Lunar2020_StoryDayThreeHeader": "Μέρος III από IV",
	"Lunar2020_StoryDayFourHeader": "Μέρος IV από IV",
	"Lunar2020_StoryDayOne": "Ο Αυτοκράτορας από νεφρίτη κάλεσε όλα τα πλάσματα του βασιλείου του σε αγώνα ταχύτητας προς το ουράνιο παλάτι του, ανακοινώνοντας ότι τα δώδεκα πρώτα που θα φτάσουν θα τιμηθούν με μια θέση στο νέο του ημερολόγιο.\n\nΟ έξυπνος Αρουραίος ήταν ο πρώτος που διέσχισε τον ποταμό προς την ουράνια πλάση. Μιας και δεν του αρέσει το κολύμπι, ο Αρουραίος σκαρφάλωσε πάνω στο έμπιστο Βόδι και πήδηξε με ενθουσιασμό στον κήπο του αυτοκράτορα πριν οι δυο τους φτάσουν την ακτή.\n\nΤο σταθερό Βόδι πέρασε τον ποταμό με άνεση. Χωρίς να τον νοιάζουν τα αποτελέσματα του αγώνα, το Βόδι ήταν χαρούμενο που έπαιξε ένα ρόλο στην επιτυχία του Αρουραίου.",
	"Lunar2020_StoryDayTwo": "Η αυτάρκης Τίγρη ταξίδεψε πολύ προσεκτικά χωρίς να προλαβαίνει το Βόδι, σκεπτόμενη πως είναι καλύτερο να φτάσει τρίτη από το να μη φτάσει καθόλου.\n\nΟ γρήγορος Λαγός πήδηξε σε ένα κούτσουρο που επέπλεε γρήγορα στο πουθενά. Αλλά η τύχη απέδωσε εκεί που έπιασε η στρατηγική, και άνεμος αρωγός οδήγησε την αυτοσχέδια βάρκα με ασφάλεια στο δρόμο της.\n\nΗ όραση του ιπτάμενου Δράκου αποκάλυψε ένα χωριό σε ανάγκη, οπότε φυσικά ο Δράκος σταμάτησε να βοηθήσει. Χάρισε ακόμα και στο λαγό ένα φύσημα για να διασχίσει το ποτάμι. Η τιμή ήταν πολύ πιο σημαντική από τη νίκη και ο Δράκος βρήκε την πέμπτη θέση αρμόζουσα.",
	"Lunar2020_StoryDayThree": "Το μουλωχτό Φίδι δεν ενδιαφερόταν για προσπάθεια μεγάλης απόστασης, οπότε τυλίχθηκε απαρατήρητο γύρω από την μπροστινή οπλή του Αλόγου.\n\nΚαθώς το Άλογο κάλπαζε προς τον τερματισμό, το Φίδι ξετυλίχθηκε, τρομάζοντας το άτι αρκετά για να γλιστρίσει στην έκτη θέση—με το skittish Άλογο να ακολουθεί πίσω του σε κοντινή απόσταση.",
	"Lunar2020_StoryDayFour": "Η Γίδα, η Μαϊμού και ο Κόκορας εργάστηκαν μαζί, αλλά άφησαν τη Γίδα να κατακτήσει την όγδοη θέση ως backbone του ταξιδιού τους. Η χαρωπή Μαϊμού ήταν η επόμενη και ο αλαζονικός Κόκορας πέρασε τέταρτος, περήφανος πως η σειρά ήταν δίκαιη.\n\nΟ παιχνιδιάρης Σκύλος ενδιαφερόταν κυρίως στο να πλατζουρίζει τριγύρω, νιώθοντας πώς η ενδέκατη θέση ήταν καλή ανταλλαγή για την όλη διασκέδαση.\n\nΤελευταίο ήρθε το Γουρούνι, που είχα σταματήσει για ένα σνακ και για έναν υπνάκο, όντας αρκετό σοφό να γνωρίζει πως κάθε ζώο θα έχει το χρόνο του στη χάρη του Αυτοκράτορα.",
	"SteamChina_PendingPersonaName": "Οι αλλαγές προφίλ λαμβάνουν χώρα μετά τον έλεγχο",
	"Legal_Footer_WithYear": "© %1$s Valve Corporation. Με επιφύλαξη παντός δικαιώματος. Όλα τα εμπορικά σήματα ανήκουν στους αντίστοιχους ιδιοκτήτες τους στις Η.Π.Α. και σε άλλες χώρες.",
	"shared_dummy": "dont translate"
}
