{
	"language": "french",
	"Button_Append": "Ajouter",
	"Button_Cancel": "Annuler",
	"Button_Close": "Fermer",
	"Button_Clone": "Dupliquer",
	"Button_Confirm": "Confirmer",
	"Button_Copy": "Copier",
	"Button_CopyClipboard": "Copier dans le Presse-papier",
	"Button_CopyLink": "Copier le lien",
	"Button_Continue": "Continuer",
	"Button_Create": "Créer",
	"Button_Delete": "Supprimer",
	"Button_Discuss": "Commenter",
	"Button_Dismiss": "Ignorer",
	"Button_Edit": "Modifier",
	"Button_Learn": "Plus d'informations",
	"Button_Publish": "Publier",
	"Button_Post": "Publier",
	"Button_OK": "OK",
	"Button_Overwrite": "Remplacer",
	"Button_Retry": "Réessayer",
	"Button_Remove": "Supprimer",
	"Button_Save": "Enregistrer",
	"Button_Saved": "Enregistré",
	"Button_Share": "Partager",
	"Button_Update": "Mettre à jour",
	"Button_SaveAndContinue": "Enregistrer et continuer",
	"Button_Follow": "Suivre",
	"Button_Followed": "Abonné(e)",
	"Button_Ignore": "Ignorer",
	"Button_Ignored": "Ignoré",
	"Button_NotifyMe": "M'envoyer une notification",
	"Button_NotInterested": "Pas intéressé(e)",
	"Button_RateUp": "Vote positif",
	"Button_ViewPage": "Voir la page",
	"Button_Accept": "Accepter",
	"Button_Reject": "Refuser",
	"ToolTip_CopyLinkToClipboard": "Copier le lien dans le presse-papier",
	"Input_Error_NumberTooSmall": "Valeur trop faible.",
	"Input_Error_NumberTooLarge": "Valeur trop grande.",
	"Input_Error_MustBeURL": "Veuillez saisir une URL valide.",
	"Input_Error_MustBeEmail": "Veuillez saisir une adresse e-mail valide.",
	"Input_Error_MustBeNumber": "Ce champ doit être un nombre.",
	"Loading": "Chargement...",
	"Updating": "Mise à jour...",
	"Uploading": "Téléchargement...",
	"Settings": "Paramètres",
	"FriendSettings_AlwaysNewChatWindow": "Toujours ouvrir une nouvelle fenêtre de chat plutôt qu'un onglet",
	"g_DisabledOnWeb": "Non disponible dans la version web",
	"VoiceTransmissionType_Disabled": "L'option « Micro ouvert » est disponible uniquement pour la version web",
	"VoiceVolume": "Volume",
	"VoiceSetupHeader": "Configuration et test du micro",
	"VoiceStartLocalMicTest": "Début du test micro",
	"VoiceStopLocalMicTest": "Fin du test micro",
	"VoiceWhenMicIsWorking": "Si vous pouvez vous entendre et voir la barre de couleur à côté de votre avatar bouger quand vous parlez, c'est que votre micro fonctionne.",
	"VoiceDevice": "Dispositif d'entrée pour la voix",
	"VoiceOutputDevice": "Dispositif de sortie pour la voix",
	"VoiceInputGain": "Volume/gain en entrée",
	"VoiceInputGainExplainer": "(Mon micro)",
	"VoiceOutputGain": "Volume/gain en sortie",
	"VoiceOutputGainExplainer": "(Mes amis)",
	"VoiceTransmissionType": "Push-to-talk",
	"VoiceTransmissionType_Label": "Type de transmission vocale",
	"VoiceTransmissionType_OpenMic": "Micro ouvert",
	"VoiceTransmissionType_PushToTalk": "Push-to-talk ",
	"VoiceTransmissionType_PushToMute": "Push-to-mute",
	"VoiceClearHotKeyTooltip": "Supprimer le raccourci d'activation/désactivation du micro",
	"VoiceTransmissionTypeExplainer": "Appuyez sur une touche définie par l’utilisateur pour parler dans les canaux vocaux",
	"VoiceTransmissionType_WhenSpeaking": "Automatique",
	"VoiceTransmissionType_PushToTalk_Key": "Push-to-talk : %1$s",
	"VoicePushToTalkPressHotKey": "Appuyez sur la touche ou le bouton de la souris pour l'affecter",
	"VoicePushToTalkAssigned": "Raccourci du Push-to-talk affecté à",
	"VoicePushToMuteAssigned": "Raccourci du Push-to-mute affecté à",
	"VoiceMuteToggleAssigned": "Raccourci d'activation/désactivation du micro affecté à",
	"VoicePushToSomethingSoundOption": "Émettre un son bref lorsque le micro est activé ou désactivé",
	"VoiceTransmisionThreshold": "Seuil de transmission vocale",
	"VoiceTransmissionThresholdExplainer": "Quand votre micro est activé, nous ne transmettrons pas de bruit en dessous de ce seuil :",
	"VoiceTransmissionThresholdOff": "Désactivé",
	"VoiceTransmissionThresholdMedium": "Moyen",
	"VoiceTransmissionThresholdHigh": "Haut",
	"VoiceTransmissionThresholdRecommended": "Recommandé",
	"VoiceAdvancedSettings": "Paramètres avancés",
	"VoiceShowAdvancedSettings": "Afficher les paramètres avancés",
	"VoiceHideAdvancedSettings": "Masquer les paramètres avancés",
	"VoiceAdvancedSettingsExplainer": "(Ces paramètres du micro sont gérés par votre plateforme ou navigateur.)",
	"VoiceEchoCancellation": "Annulation de l'écho",
	"VoiceNoiseCancellation": "Annulation du bruit",
	"VoiceAutoGainControl": "Contrôle automatique du volume/gain",
	"DefaultMic": "Par défaut",
	"MicLoading...": "Chargement...",
	"DefaultOutputDevice": "Par défaut",
	"OutputDeviceLoading...": "Chargement...",
	"BreadCrumbs_AllEvents": "Tous les événements",
	"BreadCrumbs_GameEvents": "Événements %1$s",
	"CreatorHome_ThisGame": "À propos de ce jeu :",
	"CreatorHome_DevelopedBy": "Développeur :",
	"CreatorHome_PublishedBy": "Éditeur :",
	"CreatorHome_InFranchise": "Franchise :",
	"CreatorHome_Followers": "%1$s<br>abonnés",
	"CreatorHome_JustFollowers": "abonnés",
	"CreatorHome_Follow_tooltip": "Abonnez-vous à ce créateur pour recevoir des notifications par e-mail et dans votre magasin Steam quand il publiera un nouveau jeu. Vous pouvez désactiver les notifications e-mail à tout moment.",
	"EventBrowse_MoreEventsTitle": "Plus d'événements de %1$s",
	"EventBrowse_MoreEventsBtn": "Tout voir",
	"EventBrowse_RecentUpdates": "Mises à jour récentes",
	"EventBrowse_RecentEvents": "Annonces et événements récents",
	"EventCalendar_Title": "Hub d'actualités%1$sSteam",
	"EventCalendar_FilterSubSection_EventTypeGroups": "Afficher ces types de billets",
	"EventCalendar_FilterSubSection_GameSources": "Afficher les billets de ces sources",
	"EventCalendar_EmptyCalendar": "Aucun billet trouvé. Essayez de sélectionner d'autres critères de recherche dans la barre latérale.",
	"EventCalendar_DisabledFilter_LoginPrompt": "Connectez-vous pour activer ces catégories",
	"EventCalendar_MainLoginPrompt": "Connectez-vous pour voir votre hub d'actualités personnalisé",
	"EventCalendar_NoMoreFutureEvents": "Aucun billet plus récent trouvé",
	"EventCalendar_NoMorePastEvents": "Aucun billet plus ancien trouvé",
	"EventCalendar_GameSearch": "Recherche de jeux",
	"EventCalendar_GameSearch_NoneFound": "Aucun résultat trouvé",
	"EventCalendar_GlobalCalendar_Action": "Revenir au hub d'actualités",
	"EventCalendar_SpecificCalendar": "Hub d'actualités : %1$s %2$s",
	"EventCalendar_Goto_SpecificCalendar": "Accéder au hub d'actualités de %1$s",
	"EventCalendar_SingleAppIsMuted": "Remarque : vous avez bloqué les notifications de ce jeu, il n'apparaîtra donc pas dans votre hub d'actualités personnalisé.",
	"SteamLabs": "Steam Labs",
	"SteamLabs_ExperimentNumber": "Expérience n° %1$s",
	"SteamLabs_DiscussionLink": "Discuter de cette expérience",
	"EventCalendar_FutureEventsHint": "Faites défiler vers le haut pour voir les prochains événements",
	"EventCalendar_FutureEventsHeader": "Prochainement",
	"EventCalendar_LiveAndRecentEventsHeader": "En direct et récent",
	"EventCalendar_LiveNow": "en cours",
	"EventCalendar_TimeLeft": "se termine dans %1$s",
	"EventCalendar_PostedAtTime": "Publication : %1$s",
	"EventCalendar_StartedAtTime": "A commencé à %1$s",
	"EventCalendar_Upcoming": "à venir",
	"EventCalendar_WillStartAtTime": "Commence à %1$s",
	"EventCalendar_WillStartAfterDuration": "Commence dans %1$s",
	"EventCalendar_LaterToday": "plus tard aujourd'hui",
	"EventCalendar_Tomorrow": "demain",
	"EventCalendar_ThisWeek": "cette semaine",
	"EventCalendar_ThisMonth": "ce mois-ci",
	"EventCalendar_MuchLater": "beaucoup plus tard",
	"EventCalendar_MuteApp": "Bloquer les notifications de cette application",
	"EventCalendar_MuteApp_Title": "Bloquer les notifications de %1$s",
	"EventCalendar_Ignore": "Ignorer",
	"EventCalendar_IgnoreApp": "Ignorer %1$s",
	"EventCalendar_IgnoreApp_ttip": "Les titres ignorés ne vous seront pas recommandés et n'apparaîtront pas dans les espaces d'affichage.",
	"EventCalendar_IgnoreApp_newhub": "Le hub d'actualités tiendra compte de vos paramètres et n'affichera pas les jeux que vous avez ignorés sur le magasin Steam. Vous pouvez gérer les jeux que vous avez ignorés depuis cette page :",
	"EventCalendar_UnignoreApp": "Ne plus ignorer %1$s",
	"EventCalendar_UnMuteApp_Title": "Recevoir des notifications pour %1$s",
	"EventCalendar_MuteApp_ttip": "Supprimer ce jeu de votre hub d'actualités et bloquer les communications à son sujet.",
	"EventCalendar_UnMuteApp_ttip": "Réintégrer ce jeu dans votre hub d'actualités et réactiver les communications.",
	"EventCalendar_MuteApp_details": "Supprimer %1$s de votre hub d'actualités et bloquer toutes les futures communications à son sujet. Vous pouvez toujours revenir en arrière depuis cette page :",
	"EventCalendar_ManageMutedApps": "Gérer les notifications pour les applications",
	"EventCalendar_ManageStorePref": "Gérer les préférences du magasin",
	"EventCalendar_MuteApp_Unknown": "Inconnu",
	"EVentCalendar_Hide_EventType": "Masquer tous les billets du type « %1$s »",
	"EventCalender_LastPlayed": "Dernier lancement %1$s",
	"EventCalender_Reason_recent": "Ce jeu a été lancé récemment",
	"EventCalender_Reason_library": "Ce jeu est dans votre bibliothèque",
	"EventCalender_Reason_following": "Vous suivez ce jeu",
	"EventCalender_Reason_wishlist": "Ce jeu est dans votre liste de souhaits",
	"EventCalender_Reason_recommended": "Steam vous recommande ce jeu",
	"EventCalender_Reason_steam": "Ce billet a été publié par l'équipe Steam",
	"EventCalender_Reason_topx": "Ce jeu fait partie des meilleures ventes",
	"EventCalender_Hide_Reason_recent": "Masquer les billets concernant les jeux lancés récemment",
	"EventCalender_Hide_Reason_library": "Masquer les billets à propos des jeux dans votre bibliothèque",
	"EventCalender_Hide_Reason_following": "Masquer les billets à propos des jeux que vous suivez",
	"EventCalender_Hide_Reason_wishlist": "Masquer les billets à propos des jeux dans votre liste de souhaits",
	"EventCalender_Hide_Reason_recommended": "Masquer les billets à propos des jeux qui vous sont recommandés",
	"EventCalender_Hide_Reason_steam": "Masquer les billets de l'équipe Steam",
	"EventCalender_Hide_Reason_topx": "Masquer les billets à propos des jeux les plus vendus",
	"EventCalendar_ForceDesktopView": "Afficher la vue bureau",
	"EventCalendar_ShowResponsiveView": "Afficher la vue réactive",
	"EventCalendar_EventTypeGroup_news": "Actualités",
	"EventCalendar_EventTypeGroup_ttip_news": "Actualités générales, billets de développeurs et annonces.",
	"EventCalendar_EventTypeGroup_events": "Événements",
	"EventCalendar_EventTypeGroup_ttip_events": "Événements en jeu, en ligne/dans le chat et événements IRL.",
	"EventCalendar_EventTypeGroup_streaming": "Diffusions en direct",
	"EventCalendar_EventTypeGroup_ttip_streaming": "Diffusions de développeurs en direct (tournois, parties en marge de tournois).",
	"EventCalendar_EventTypeGroup_updates": "Mises à jour de contenus",
	"EventCalendar_EventTypeGroup_ttip_updates": "Actualités sur les nouveaux contenus de jeu, les extensions, les DLC et les corrections de bugs.",
	"EventCalendar_EventTypeGroup_releases": "Sorties",
	"EventCalendar_EventTypeGroup_ttip_releases": "Programmation des sorties d'un nouveau jeu, d'une nouvelle bêta, d'une nouvelle saison ou d'un nouveau DLC.",
	"EventCalendar_EventTypeGroup_sales": "Soldes",
	"EventCalendar_EventTypeGroup_ttip_sales": "Remises, promotions et essais gratuits.",
	"EventCalendar_GameSource_recent": "Lancés récemment",
	"EventCalendar_GameSource_ttip_recent": "Inclure les billets à propos des jeux que vous avez achetés ou lancés au cours des six derniers mois",
	"EventCalendar_GameSource_EventExplanation_ttip_recent": "Vous avez joué à ce jeu au cours des six derniers mois",
	"EventCalendar_GameSource_library": "Bibliothèque",
	"EventCalendar_GameSource_ttip_library": "Inclure les billets à propos des jeux dans votre bibliothèque",
	"EventCalendar_GameSource_EventExplanation_ttip_library": "Ce jeu est dans votre bibliothèque",
	"EventCalendar_GameSource_wishlist": "Liste de souhaits",
	"EventCalendar_GameSource_ttip_wishlist": "Inclure les billets à propos des jeux dans votre liste de souhaits",
	"EventCalendar_GameSource_EventExplanation_ttip_wishlist": "Ce jeu est dans votre liste de souhaits",
	"EventCalendar_GameSource_following": "Jeux suivis",
	"EventCalendar_GameSource_ttip_following": "Inclure les billets à propos des jeux que vous suivez",
	"EventCalendar_GameSource_EventExplanation_ttip_following": "Vous suivez ce jeu",
	"EventCalendar_GameSource_recommended": "Jeux recommandés",
	"EventCalendar_GameSource_recommended_Verbose": "Jeu recommandé",
	"EventCalendar_GameSource_ttip_recommended": "Inclure les billets à propos des jeux que vous pourriez aimer",
	"EventCalendar_GameSource_EventExplanation_ttip_recommended": "Vous pourriez aimer ce jeu",
	"EventCalendar_GameSource_steam": "Steam",
	"EventCalendar_GameSource_ttip_steam": "Inclure les billets à propos de la plateforme Steam",
	"EventCalendar_GameSource_topx": "Meilleures ventes",
	"EventCalendar_GameSource_ttip_topx": "Inclure les billets à propos des jeux les plus vendus dans votre région",
	"EventCalendar_GameSource_EventExplanation_ttip_steam": "Ceci est un billet à propos de Steam",
	"EventDisplay_Admin_Title": "Outils d'admin. :",
	"EventDisplay_ViewInLibrary": "Voir dans la bibliothèque",
	"EventDisplay_ViewStorePage": "Consulter la page du magasin",
	"EventDisplay_ViewCommunityPage": "Voir la page de la communauté",
	"EventDisplay_CallToAction_LearnMore": "En savoir plus",
	"EventDisplay_CallToAction_InLibrary": "Dans votre bibliothèque",
	"EventDisplay_CallToAction_PlayNow": "Jouer",
	"EventDisplay_CallToAction_ComingSoon": "Prochainement",
	"EventDisplay_CallToAction_FreeToPlay": "Gratuit (F2P)",
	"EventDisplay_Events": "Tableau d'administrateur",
	"EventDisplay_SeeOldVersion": "Voir la version client actuelle",
	"EventDisplay_SalesPage": "Consulter la page des soldes du magasin",
	"EventDisplay_StatsPage": "(Valve uniquement) Page des statistiques",
	"EventDisplay_RightColumnTitle_Game": "Jeu",
	"EventDisplay_RightColumnTitle_Blog": "Blog",
	"EventDisplay_RightColumnTitle_DateAndTime": "Date et heure",
	"EventDisplay_RightColumnTitle_EventType": "Type",
	"EventDisplay_PostedBy": "par ",
	"EventDisplay_Reminder_SetReminder": "Créer un rappel",
	"EventDisplay_Reminder_GetNotification_Via": "Recevoir une notification",
	"EventDisplay_Reminder_ViaEmail": "par e-mail",
	"EventDisplay_Reminder_ViaMobileApp": "depuis l'application mobile",
	"EventDisplay_Reminder_FollowEvent": "Suivre l'événement",
	"EventDisplay_Reminder_FollowEvent_ttip": "Suivez un événement pour être averti quand il commencera.",
	"EventDisplay_Reminder_RemindAtStart": "Quand l'événement commencera",
	"EventDisplay_Reminder_RemindAtStart_ttip": "Steam vous enverra une notification quand l'événement commencera.",
	"EventDisplay_Reminder_IgnoreEvent": "Ignorer cet événement",
	"EventDisplay_Reminder_IgnoreStop": "Arrêter les rappels",
	"EventDisplay_Reminder_IgnoreEvent_ttip": "Steam exclura les événements ignorés des futures suggestions et recommandations.",
	"EventDisplay_Reminder_FollowEvent_Error": "Impossible de suivre l'événement",
	"EventDisplay_Reminder_FollowEvent_ErrorDesc": "Une erreur est survenue quand vous avez essayé de suivre ou d'arrêter de suivre l'événement :",
	"EventDisplay_Reminder_IgnoreEvent_Error": "Impossible d'ignorer l'événement",
	"EventDisplay_Reminder_IgnoreEvent_ErrorDesc": "Une erreur est survenue quand vous avez essayé d'ignorer ou d'arrêter d'ignorer l'événement :",
	"EventDisplay_Reminder_Toast": "Envoyer une notification toast de Steam au début de l'événement",
	"EventDisplay_Reminder_AddToCalendar": "Ajouter au calendrier",
	"EventDisplay_Reminder_AddToApple": "Ajouter à l'application Calendrier d'Apple",
	"EventDisplay_Reminder_AppleCalendar_Short": "Apple",
	"EventDisplay_Reminder_AddToGoogle": "Ajouter à Google Agenda",
	"EventDisplay_Reminder_GoogleCalendar_Short": "Google",
	"EventDisplay_Reminder_AddToOutlook": "Ajouter au Calendrier Outlook",
	"EventDisplay_Reminder_OutlookCalendar_Short": "Outlook",
	"EventDisplay_Reminder_AddToYahoo": "Ajouter à l'Agenda Yahoo",
	"EventDisplay_Reminder_Preferences": "Modifier les préférences de rappel...",
	"EventDisplay_TimeDisplay": "De %1$s à %2$s",
	"EventDisplay_TimeDisplayNone": "Aucune date ou heure n'a été indiquée",
	"EventDisplay_TimeBeginsOn": "Cet événement commence dans",
	"EventDisplay_TimeBeginsOn_Past": "Cet événement a commencé",
	"EventDisplay_TimeBeginsOn_StartAndEnd_Past": "Événement commencé (ancien)",
	"EventDisplay_TimeEndsOn": "Se termine le",
	"EventDisplay_TimeEndsOn_Past": "Cet événement s'est terminé",
	"EventDisplay_RunsForDuration": "Dure %1$s",
	"EventDisplay_TimeLeft": "Se termine dans %1$s",
	"EventDisplay_TimeEndsOn_Ran": "Durée :",
	"EventDisplay_TimeRange": "Heure de l'événement",
	"EventDisplay_TimeInPast": "Publié",
	"EventDisplay_TimeUpcoming": "Début de l'événement :",
	"EventDisplay_EventUpcoming_WithDateAndTime": "L'événement commence le %1$s à %2$s",
	"EventDisplay_TimeEventActive": "Cet événement est en cours",
	"EventDisplay_TimeEventOnNow": "En ce moment !",
	"EventDisplay_Share_Link": "Lien : ",
	"EventDisplay_Share_OnMyStatus": "Partager comme statut",
	"EventDisplay_Share_OnMyStatus_Details": "Publiez ce statut dans le flux d'activités de vos amis. Steam inclura le message et l'aperçu de l'item montré ci-dessous.",
	"EventDisplay_Share_OnMyStatus_Placeholder": "Dites quelque chose à ce sujet à vos amis...",
	"EventDisplay_Share_OnSteam": "Partagez ceci avec la communauté Steam sous forme de statut",
	"EventDisplay_Share_OnFaceBook": "Partager sur Facebook",
	"EventDisplay_Share_OnTwitter": "Partager sur Twitter",
	"EventDisplay_Share_OnReddit": "Partager sur Reddit",
	"EventDisplay_Share_Success": "Succès !",
	"EventDisplay_Share_Failure": "Impossible de partager le message suivant : ",
	"EventDisplay_Share_Announcement": "Annonce : %1$s",
	"EventDisplay_Share_Event": "Événement : %1$s",
	"EventDisplay_Share_NotLoggedIn": "Déconnecté(e)",
	"EventDisplay_Share_NotLoggedIn_Description": "Pour utiliser cette fonctionnalité, vous devez être connecté(e) à Steam",
	"EventDisplay_Share_CommentMigrationInProcess": "Les discussions pour cet événement attendent d'être déplacées vers le système d'événements. Elles sont temporairement inaccessibles. Veuillez revenir plus tard.",
	"EventDisplay_Share_OpenActivityFeed": "Ouvrir mon flux d'activité",
	"EventDisplay_AreYouSure": "Voulez-vous vraiment supprimer cet événement (%1$s) ? Cette action est irréversible.",
	"EventDisplay_AreYouSure_Visible": "Voulez-vous vraiment supprimer cet événement (%1$s) ? Cette action est irréversible. Cet événement sera supprimé de tous les endroits visibles par les utilisateurs en quelques minutes.",
	"EventDisplay_DeleteEvent_InProgress": "Suppression en cours. Veuillez patienter.",
	"EventDisplay_DeleteEvent_Error": "Une erreur est survenue lors de la suppression de l'événement :",
	"EventDisplay_DeleteEvent_ForumTopicError": "L'événement a bien été supprimé, mais le sujet de discussion de cet événement n'a pas pu être supprimé. Vous pouvez réessayer depuis le site %1$s. Détails de l'erreur :",
	"EventDisplay_DeleteEvent_Success": "L'événement a bien été supprimé.",
	"EventDisplay_DeleteEvent_Comment": "Voulez-vous également supprimer le sujet de discussion de cet événement ?",
	"EventDisplay_SocialTitle": "Plus d'informations sur ce jeu",
	"EventDisplay_Sketchfab": "Modèle Sketchfab",
	"EventDisplay_SketchFab_Error_Network": "Échec de la connexion à Sketchfab",
	"EventEditor_Publish_VisibleNow": "Rendre visible maintenant",
	"EventEditor_Publish_VisibleNow_ttip": "Cet événement deviendra automatiquement visible à l'heure prévue. Ce bouton force l'événement à devenir immédiatement visible.",
	"EventEditor_Edit": "Modifier l'événement",
	"EventDisplay_DeleteEvent": "Supprimer l’événement",
	"EventReminder_InProgress": "(les options de notification ci-dessous sont figuratives et ne fonctionnent pas encore)",
	"EventReminder_NotifyByEmail": "M'envoyer une notification par e-mail",
	"EventReminder_NotifyByEmail_ttip": "Au début de l'événement, Steam enverra un e-mail à l'adresse e-mail associée à votre compte.",
	"EventReminder_NotifyByMobile": "M'envoyer une notification sur mon appareil mobile",
	"EventReminder_NotifyByMobile_ttip": "Au début de l'événement, Steam enverra une notification push à tous les appareils mobiles sur lesquels l'application mobile Steam est installée et où vous êtes connecté(e).",
	"EventReminder_NotifyByEmail_Missing": "Veuillez vérifier votre adresse e-mail pour recevoir des rappels.",
	"EventReminder_NotifyByEmail_Missing_Add": "Veuillez vérifier votre adresse e-mail.",
	"EventReminder_NotifyByMobile_Missing": "Installez une des applications Steam pour recevoir des rappels sur mobiles. ",
	"EventReminder_NotifyByMobile_Install": "Cliquez ici pour voir les applications disponibles.",
	"EventEmail_Subject_NewUpdate": "%1$s : nouvelle mise à jour",
	"EventEmail_Subject_UpcomingLaunch": "%1$s : sortie prochaine",
	"EventEmail_Subject_NowAvailable": "%1$s maintenant disponible",
	"EventEmail_Subject_FreeDemoAvailable": "Démo gratuite de %1$s maintenant disponible",
	"EventEmail_Subject_SpecialOffer": "Offre spéciale sur %1$s",
	"EventEmail_Subject_Tournament_Now": "Tournoi %1$s : suivez-le dès maintenant",
	"EventEmail_Subject_LiveStream_Now": "Diffusion de %1$s : regardez-la dès maintenant",
	"Email_Wishlist_NewReleaseEA_Subject": "%1$s est maintenant disponible en accès anticipé sur Steam !",
	"EventEmail_Button_ClickForMoreDetails": "Plus d'informations",
	"EventEmail_Button_PrepurchaseNow": "Préacheter maintenant",
	"EventEmail_Button_BuyNow": "Acheter maintenant",
	"EventEmail_Button_PlayNow": "Jouer maintenant !",
	"EventEmail_Button_WishlistNow": "Ajouter à votre liste de souhaits",
	"EventEmail_WatchNow": "Regarder",
	"EventEmail_Destination_Store": "Page du magasin Steam du jeu",
	"EventEmail_Destination_Event": "Page des détails de l'événement",
	"EventEmail_Destination_SalesPage": "Page des soldes du magasin Steam",
	"EventDashBoard_SummaryStats_Admin_Title": "(uniquement visible par les administrateurs)",
	"EventDashBoard_SummaryStats_Title": "Total d'expositions et de lectures uniques",
	"EventDashBoard_SummaryStats_Desc": "(Bêta) Il s'agit des impressions et vues de vos événements et annonces par des utilisateurs connectés uniques. S'applique uniquement aux nouveaux événements et annonces créés à l'aide de cet éditeur.",
	"EventDashBoard_SummaryStats_Link": "Cliquez ici pour plus d'informations.",
	"EventDashBoard_Summary_LibraryHome_Shown": "Impressions d'événements (image de couverture) :",
	"EventDashBoard_Summary_LibraryHome_Read": "Clics sur un événement pour voir les détails :",
	"EventDashBoard_Summary_AppDetailSpotlight_Shown": "Impressions de bannière coup de projecteur :",
	"EventDashBoard_Summary_AppDetailSpotlight_Read": "Clics sur une bannière coup de projecteur pour voir les détails :",
	"EventDashBoard_Summary_AppDetailActivity_Shown": "Impressions d'événements dans le flux d'activité :",
	"EventDashBoard_Summary_AppDetailActivity_Read": "Clics sur un événement pour voir les détails :",
	"EventDashBoard_Summary_StoreAppPage_Shown": "Impressions d'événements (image de couverture) :",
	"EventDashBoard_Summary_StoreAppPage_Read": "Clics sur un événement pour voir les détails :",
	"EventDashBoard_Summary_Community_Shown": "Impressions du résumé d'un événement :",
	"EventDashBoard_Summary_Community_Read": "Clics sur le résumé d'un événement pour voir les détails :",
	"EventDashBoard_Summary_NewsHub_Shown": "Impressions de l'événement dans le hub d'actualités :",
	"EventDashBoard_Summary_NewsHub_Read": "Clics sur un événement pour voir les détails :",
	"EventDashBoard_Location_LibraryHome": "Bibliothèque : page d'accueil",
	"EventDashBoard_Location_LibraryDetail": "Bibliothèque : page de jeu",
	"EventDashBoard_Location_StoreDetail": "Page de jeu dans le magasin",
	"EventDashBoard_Location_CommunityDetail": "Hub de la communauté du produit",
	"EventDashBoard_Location_PopUpViews": "Vues de la page contextuelle d'un événement",
	"EventDashBoard_Location_NewsHubDetail": "Hub d'actualités",
	"AddToWishlist": "Ajouter à votre liste de souhaits",
	"Wishlisted": "Dans votre liste de souhaits",
	"AddToWishlist_ttip": "Recevez une notification par e-mail quand des articles de votre liste de souhaits sont publiés ou en solde",
	"Wishlist_Error": "Erreur de mise à jour de la liste de souhaits",
	"Wishlist_Error_Desc": "Une erreur s'est produite lors de l'ajout de votre liste de souhaits. Veuillez réessayer plus tard :",
	"WindowTitle_FriendsList": "Liste d’amis",
	"FriendsList_OfflineTitle": "ERREUR",
	"FriendsList_OfflineOrFailure": "Impossible d'accéder au réseau d'amis",
	"FriendsList_OfflineDetail": "Ceci peut indiquer que votre réseau local est hors ligne ou que les serveurs d'amis Steam sont actuellement hors ligne.",
	"FriendsList_SignedOut": "Déconnecté du réseau d'amis et du chat",
	"FriendsList_SignedOut_Detail": "Vous êtes actuellement hors ligne. Veuillez vous connecter pour accéder à votre liste d'amis et au chat.",
	"FriendsList_OfflineMode": "Déconnecté du réseau d'amis et du chat",
	"FriendsList_OfflineMode_Detail": "Le réseau d'amis et le chat ne sont pas disponibles en mode hors ligne. Veuillez vous connecter pour accéder à votre liste d'amis et au chat.",
	"Friends_RetryLoading": "Réessayer la connexion",
	"Friends_SignIn": "Se connecter",
	"FriendsList_Offline_Disconnected": "Déconnecté",
	"FriendsList_LoadingTitle": "CHARGEMENT",
	"FriendsList_StillLoadingSummary": "Chargement du réseau d'amis...",
	"FriendsList_StillLoadingDetail": "Steam essaye de se connecter au réseau d'amis. Cela peut prendre quelques secondes supplémentaires.",
	"Dialog_On": "OUI",
	"Dialog_Off": "NON",
	"TimeInterval_XYears": "%1$s années",
	"TimeInterval_1YearXMonths": "1 an et %1$s mois",
	"TimeInterval_1Year": "1 an",
	"TimeInterval_XMonths": "%1$s mois",
	"TimeInterval_1Month": "1 mois",
	"TimeInterval_1MonthX": "1 mois et %1$s jours",
	"TimeInterval_XWeeks": "%1$s semaines",
	"TimeInterval_1Week": "1 semaine",
	"TimeInterval_XDays": "%1$s jours",
	"TimeInterval_1Day": "1 jour",
	"TimeInterval_1DayXHours": "1 jour et %1$s heures",
	"TimeInterval_XHours": "%1$s heures",
	"TimeInterval_1Hour": "1 heure",
	"TimeInterval_1HourXMinutes": "1 heure et %1$s minutes",
	"TimeInterval_LessThanAnHour": "moins d'une heure",
	"TimeInterval_XMinutes": "%1$s minutes",
	"TimeInterval_1Minute": "1 minute",
	"TimeInterval_LessThanAMinute": "moins d'une minute",
	"TimeSince_XYears": "il y a %1$s ans",
	"TimeSince_1YearXMonths": "il y a 1 an et %1$s mois",
	"TimeSince_1Year": "il y a 1 an",
	"TimeSince_XMonths": "il y a %1$s mois",
	"TimeSince_1Month": "il y a 1 mois",
	"TimeSince_1MonthXDays": "il y a 1 mois et %1$s jours",
	"TimeSince_XWeeks": "il y a %1$s semaines",
	"TimeSince_1Week": "Il y a une semaine",
	"TimeSince_XDays": "il y a %1$s jours",
	"TimeSince_1Day": "il y a 1 jour",
	"TimeSince_1DayXHours": "il y a 1 jour et %1$s heures",
	"TimeSince_XHours": "il y a %1$s heures",
	"TimeSince_1Hour": "il y a 1 heure",
	"TimeSince_1HourXMinutes": "il y a 1 heure et %1$s minutes",
	"TimeSince_LessThanAnHour": "il y a moins d'une heure",
	"TimeSince_XMinutes": "il y a %1$s minutes",
	"TimeSince_1Minute": "il y a 1 minute",
	"TimeSince_LessThanAMinute": "il y a moins d'une minute",
	"TimeSince_ThisWeek": "cette semaine",
	"Time_Today": "aujourd'hui",
	"Time_Tomorrow": "demain",
	"Time_Yesterday": "hier",
	"Time_Recent": "Récent",
	"ContextMenu_Copy": "Copier",
	"ContextMenu_Cut": "Couper",
	"ContextMenu_Paste": "Coller",
	"ContextMenu_CopyLinkURL": "Copier l'URL du lien",
	"ContextMenu_OpenLinkInNewWindow": "Ouvrir le lien dans une nouvelle fenêtre",
	"ContextMenu_CopyImageURL": "Copier l'URL de l'image",
	"ContextMenu_OpenImageInNewWindow": "Ouvrir l'image dans une nouvelle fenêtre",
	"Tooltip_Settings": "Gérer les paramètres de la liste d'amis",
	"Tooltip_VoiceSettings": "Gérer les paramètres de voix",
	"Tooltip_SearchFriends": "Rechercher dans ma liste d'amis",
	"Tooltip_AddFriend": "Ajouter un(e) ami(e)",
	"Tooltip_FriendRequest": "%1$s nouvelle demande",
	"Tooltip_FriendRequest_Plural": "%1$s nouvelles demandes",
	"Tooltip_CreateGroupChat": "Créer un chat de groupe",
	"Tooltip_InviteToGroup": "Inviter un ami dans ce chat de groupe",
	"Tooltip_InviteToGroup_Denied": "Vous n'avez pas l'autorisation d'inviter des utilisateurs à ce groupe",
	"Tooltip_GroupChatSettings": "Gérer les paramètres du chat de groupe",
	"Tooltip_MemberCollapse": "Réduire la liste des membres",
	"Tooltip_MemberExpand": "Développer la liste des membres",
	"Tooltip_ChatsCollapse": "Réduire la liste des chats",
	"Tooltip_ChatsExpand": "Développer la liste des chats",
	"Tooltip_MinimizeList": "Réduire la liste",
	"Tooltip_ExpandList": "Développer la liste",
	"Tooltip_PinChannelList": "Épingler la liste de canaux",
	"Tooltip_UnpinChannelList": "Dépingler la liste de canaux",
	"Tooltip_TextChannel": "Chat de texte avec les membres du groupe",
	"Tooltip_TextChannelCreate": "Créer un nouveau canal de texte",
	"Tooltip_NoPermissionChannelCreate": "Vous n'avez pas l'autorisation de créer des canaux dans ce chat de groupe",
	"Tooltip_VoiceChannel": "Chatter sur ces canaux vocaux",
	"Tooltip_VoiceChannelCreate": "Créer un nouveau canal vocal",
	"Tooltip_DismissVoice": "Refuser l'invitation au canal vocal",
	"Tooltip_MicStatus_Active": "Micro actif",
	"Tooltip_MicStatus_Muted": "Micro muet",
	"Tooltip_RemoteMicStatus_Muted": "L'utilisateur a coupé son micro",
	"Tooltip_MicStatus_NoMic": "L'utilisateur n'a pas de micro connecté",
	"Tooltip_RemoteOutputStatus_Muted": "L'utilisateur a désactivé le son de ce canal",
	"Tooltip_YourMicStatus_Muted": "Vous avez coupé votre micro",
	"Tooltip_YourOutputStatus_Muted": "Vous avez désactivé le son de ce canal",
	"Tooltip_VoiceControlButton_1v1_inactive": "Envoyer une demande de chat vocal",
	"Tooltip_VoiceControlButton_1v1_active": "Quitter le canal vocal",
	"Tooltip_VoiceControlButton_group_create": "Créer un canal vocal",
	"Tooltip_VoiceControlButton_group_leave": "Quitter le canal vocal",
	"Tooltip_VoiceControlButton_group_joinsingle": "Rejoindre le canal vocal",
	"Tooltip_VoiceControlButton_group_joinmultiple": "Choisir un canal vocal à rejoindre",
	"LanguageTitle": "Langue",
	"Language_english": "Anglais",
	"Language_german": "Allemand",
	"Language_french": "Français",
	"Language_italian": "Italien",
	"Language_korean": "Coréen",
	"Language_spanish": "Espagnol (Espagne)",
	"Language_schinese": "Chinois simplifié",
	"Language_tchinese": "Chinois traditionnel",
	"Language_russian": "Russe",
	"Language_thai": "Thaï",
	"Language_japanese": "Japonais",
	"Language_portuguese": "Portugais",
	"Language_polish": "Polonais",
	"Language_danish": "Danois",
	"Language_dutch": "Néerlandais",
	"Language_finnish": "Finnois",
	"Language_norwegian": "Norvégien",
	"Language_swedish": "Suédois",
	"Language_hungarian": "Hongrois",
	"Language_czech": "Tchèque",
	"Language_romanian": "Roumain",
	"Language_turkish": "Turc",
	"Language_arabic": "Arabe",
	"Language_brazilian": "Portugais du Brésil",
	"Language_bulgarian": "Bulgare",
	"Language_greek": "Grec",
	"Language_ukrainian": "Ukrainien",
	"Language_latam": "Espagnol (Amérique latine)",
	"Language_vietnamese": "Vietnamien",
	"Language_koreana": "Coréen",
	"language_selection_english": "English (anglais)",
	"language_selection_spanish": "Español - España (espagnol d'Espagne)",
	"language_selection_french": "Français",
	"language_selection_italian": "Italiano (italien)",
	"language_selection_german": "Deutsch (allemand)",
	"language_selection_greek": "Ελληνικά (grec)",
	"language_selection_koreana": "한국어 (coréen)",
	"language_selection_korean": "한국어 (coréen)",
	"language_selection_schinese": "简体中文 (chinois simplifié)",
	"language_selection_tchinese": "繁體中文 (chinois traditionnel)",
	"language_selection_russian": "Русский (russe)",
	"language_selection_thai": "ไทย (thaï)",
	"language_selection_japanese": "日本語 (japonais)",
	"language_selection_portuguese": "Português (portugais)",
	"language_selection_brazilian": "Português - Brasil (portugais du Brésil)",
	"language_selection_polish": "Polski (polonais)",
	"language_selection_danish": "Dansk (danois)",
	"language_selection_dutch": "Nederlands (néerlandais)",
	"language_selection_finnish": "Suomi (Finnois)",
	"language_selection_norwegian": "Norsk (norvégien)",
	"language_selection_swedish": "Svenska (suédois)",
	"language_selection_czech": "Čeština (tchèque)",
	"language_selection_hungarian": "Magyar (hongrois)",
	"language_selection_romanian": "Română (roumain)",
	"language_selection_bulgarian": "Български (bulgare)",
	"language_selection_pirate": "Pirate (Yarr !)",
	"language_selection_turkish": "Türkçe (turc)",
	"language_selection_ukrainian": "Українська (ukrainien)",
	"language_selection_vietnamese": "Tiếng Việt (vietnamien)",
	"language_selection_arabic": "العربية (arabe)",
	"language_selection_spanish_mexican": "Español-Mexicano (espagnol du Mexique)",
	"language_selection_latam": "Español - Latinoamérica (espagnol d'Amérique latine)",
	"Bbcode_Originally_Posted_By": "Publié par",
	"Bbcode_No_Match": "Ne correspond à aucun BBCode pris en charge",
	"Editor_Bold": "Gras",
	"Editor_Underline": "Souligné",
	"Editor_Italics": "Italique",
	"Editor_StrikeThrough": "Barré",
	"Editor_Link": "Insérer un lien",
	"Editor_Unordered": "Liste non ordonnée",
	"Editor_Ordered": "Liste ordonnée",
	"Editor_Header": "En-tête",
	"Editor_Header2": "En-tête 2",
	"Editor_Header3": "En-tête 3",
	"Editor_Emoticon": "Insérer des émoticônes",
	"EventEditor_ConvertHTML_Error": "Impossible de convertir le code HTML",
	"EventEditor_ConvertHTML_Error_Desc": "Une erreur est survenue lors de la conversation du code HTML en BBcode : « %1$s »",
	"EventEditor_InsertLinkURL": "Ajouter une URL",
	"EventEditor_FormattingHelp_GetHelpLink": "Aide au formatage",
	"EventEditor_ImportHTML": "Importer du code HTML",
	"EventEditor_ImportFromHTML": "Importer depuis HTML",
	"EventEditor_ImportFromHTML_ttip": "Importez du code HTML. Il sera automatiquement converti au format utilisé par Steam.",
	"EventEditor_ImportFromHTML_Instruction": "Tapez ou collez le code HTML ci-dessous.",
	"EventEditor_ImportFromHTML_PreserveNewlines": "Garder les sauts de ligne",
	"EventEditor_ImportFromHTML_PreserveNewlines_Hint": "En HTML, les sauts de ligne n'ont généralement aucun effet, mais en BBCode, ils affichent des lignes vides. Si votre code contient des balises <p> ou <br>, laissez cette case décochée. Si vous utilisez un logiciel de blog qui ajoute automatiquement des balises <br> pour les sauts de ligne, nous vous conseillons de cocher cette case.",
	"EventEditor_ImportFromHTML_ConvertToBBCode": "Convertir en BBCode :",
	"EventEditor_ImportFromHTML_ConversionInProgress": "Conversion en cours. Veuillez ne pas fermer cette fenêtre.",
	"EventEditor_ImportFromHTML_ConvertFinished": "Conversion terminée. Vous pouvez fermer cette fenêtre.",
	"EventEditor_InsertYouTube": "Insérer une vidéo YouTube™",
	"EventEditor_InsertYouTube_Left": "Aligner à gauche",
	"EventEditor_InsertYouTube_Right": "Aligner à droite",
	"EventEditor_InsertYouTube_Full": "Pleine largeur",
	"EventEditor_InsertYouTube_URL": "URL complète",
	"EventEditor_InsertYouTube_Position": "Position",
	"EventEditor_InsertYouTube_Placholder": "Saisissez l’URL de la vidéo YouTube™",
	"EventEditor_InsertYouTube_NoURL": "Veuillez saisir une URL valide.",
	"EventEditor_InsertYouTube_Summary": "Résumé descriptif",
	"EventEditor_InsertImage": "Insérer une image via son URL",
	"EventEditor_InsertImage_Title": "Insérer une image",
	"EventEditor_InsertImage_Desc": "Saisissez l'URL d'une image (au format JPG, GIF ou PNG) pour ajouter cette image à votre publication.",
	"EventEditor_InsertImage_URL": "URL de l'image",
	"EventEditor_InsertImage_Placeholder": "Saisissez une URL valide",
	"EventEditor_InsertImage_Anchor": "Facultatif : ouvrir l'URL quand on clique sur l'image",
	"EventEditor_LinkDescription": "Texte à afficher",
	"EventEditor_LinkURL": "URL ",
	"EventEditor_YouTubeVideoTitle": "Vidéo YouTube™ : %1$s",
	"EventEditor_YouTubeVideoViews": "Vues : %1$s",
	"EventEditor_Author": "Par : %1$s",
	"EventEditor_Comments": "Commentaires",
	"EventEditor_UpVotes": "Votes positifs",
	"EventEditor_DownVotes": "Votes négatifs",
	"Error_Message": "Message d'erreur",
	"Warning_Message": "Message d'avertissement",
	"Informational_Message": "Message d'information",
	"Error_Description": "Une erreur (code : %1$s) s'est produite. Détails : (%2$s)",
	"Error_FailureNotice": "Échec",
	"Error_GenericFailureDescription": "Une erreur s'est produite.",
	"Image_ErrorTitle": "Impossible de charger l'image « %1$s ». Erreurs possibles :",
	"Image_Error_msg1": "Vérifiez que le chemin d'accès de l'image est correct.",
	"Image_Error_msg2": "Vérifiez que le serveur qui héberge l'image autorise les accès anonymes. Si ce n'est pas le cas, la console du navigateur peut indiquer une erreur Access-Control-Allow-Origin.",
	"Image_Error_suggestion": "Vous pouvez toujours charger l'image sur Steam pour un hébergement gratuit du contenu.",
	"Platform_Hint_Mobile": "sur mobile",
	"Platform_Hint_BigPicture": "dans le mode Big Picture",
	"Platform_Hint_VR": "en VR",
	"Hover_SteamLevel": "Niveau Steam",
	"Hover_BadgeXP": "%1$s d'XP",
	"PersonaStateOffline": "Hors ligne",
	"PersonaStateAway": "Absent(e)",
	"PersonaStateOnline": "En ligne",
	"PersonaStateBlocked": "Bloqué(e)",
	"PersonaStateInGame": "En jeu",
	"PersonaStateBusy": "Occupé(e)",
	"PersonaStateSnooze": "Absent(e)",
	"PersonaStateInNonSteamGame": "Dans un jeu non Steam",
	"PersonaStateWatchingBroadcast": "Regarde la diffusion de :",
	"PersonaStateLookingToTrade": "Souhaite échanger",
	"PersonaStateLookingToPlay": "Souhaite jouer",
	"PersonaStateLastSeen": "Dernière connexion : %1$s",
	"PersonaStateLastSeen_JustNow": "En ligne il y a un instant",
	"PersonaStateRemotePlayTogether": "Remote Play Together",
	"User_WantsToPlay": "Rejoindre",
	"User_ToggleDoNotDisturb": "Ne pas déranger",
	"User_GameInfoHidden": "Votre statut « en jeu » n'est pas visible de vos amis en raison de vos paramètres de confidentialité",
	"User_LimitedAccount": "Votre compte ne répond pas aux exigences pour utiliser cette fonctionnalité. %1$s pour plus d'informations.",
	"User_LimitedAccount_UrlInfo": "Consulter le Support Steam",
	"isNickname": "Votre surnom pour cet ami",
	"Friend_Menu_NotAFriendLabel": "Vous n'êtes pas amis",
	"Friend_Menu_NotAFriendRequesting": "Demande à être votre ami(e)",
	"DASHPlayerStats_BytesReceived": "Octets reçus :",
	"DASHPlayerStats_BufferingResolution": "Résolution de la mémoire tampon :",
	"DASHPlayerStats_PlaybackResolution": "Résolution de lecture :",
	"DASHPlayerStats_HtmlResolution": "Résolution d'affichage :",
	"DASHPlayerStats_DroppedFrames": "Images perdues :",
	"DASHPlayerStats_VideoBuffered": "Mémoire tampon de la vidéo :",
	"DASHPlayerStats_AudioBuffered": "Audio en mémoire tampon :",
	"DASHPlayerStats_BandwidthRequired": "Bande passante requise (Mbit/s) :",
	"DASHPlayerStats_BandwidthVideo": "Bande passante vidéo (Mbit/s) : ",
	"DASHPlayerStats_BandwidthNums": "Bande passante min./max./moy. (Mbit/s) :",
	"DASHPlayerStats_DownloadNums": "Temps de téléchargement min./max./moy. (secondes) :",
	"DASHPlayerStats_ContentServer": "Hôte :",
	"DASHPlayerStats_ActiveDownloads": "Téléchargements en cours :",
	"DASHPlayerStats_StallEvents": "Événements en pause :",
	"DASHPlayerStats_FailedDownloads": "Téléchargements échoués :",
	"DASHPlayerStats_VideoDownloadProgress": "Progression de téléchargement de la vidéo :",
	"DASHPlayerStats_TimeToFirstFrame": "Temps avant la première image (en ms) :",
	"DASHPlayerStats_DroppingFrames": "Perte d'images constante détectée :",
	"DASHPlayerStats_CurrentFPS": "Nombre d'IPS actuel :",
	"DASHPlayerStats_Tracking": "Récupération des données...",
	"DASHPlayerStats_PlaybackRate": "Vitesse de lecture :",
	"DASHPlayerStats_VideoBufferRange": "Tampon vidéo %1$s :",
	"DASHPlayerStats_AudioBufferRange": "Tampon audio %1$s :",
	"DASHPlayerStats_VideoNoRangeInformation": "Pas de segment vidéo en mémoire tampon",
	"DASHPlayerStats_AudioNoRangeInformation": "Pas de segment audio en mémoire tampon",
	"DASHPlayerControls_GoLive": "Direct",
	"DASHPlayerControls_IsLive": "En direct",
	"DASHPlayerControls_ClickToPlay": "Cliquez pour lire la vidéo",
	"DASHPlayerControls_IsReplay": "REDIFFUSION",
	"DASHPlayerControls_Start": "Commencer",
	"DASHPlayerControls_End": "Terminer",
	"Played_Minutes": "%1$s minutes",
	"Played_Hours": "%1$s heures",
	"WriteReview_Dialog_PostReview": "Publier l'évaluation",
	"WriteReview_Dialog_ReviseReview": "Modifier l'évaluation",
	"WriteReview_Dialog_Title": "Évaluation",
	"WriteReview_Dialog_Playtime": "Vous avez joué %1$s",
	"WriteReview_Dialog_Playtime_Software": "Vous avez utilisé ce produit pendant %1$s",
	"WriteReview_Dialog_Playtime_Revise": "Vous avez joué %1$s de plus",
	"WriteReview_Dialog_RecommendGame": "Recommanderiez-vous ce jeu à d'autres joueurs ?",
	"WriteReview_Dialog_RecommendGame_Software": "Recommanderiez-vous ce produit à d'autres joueurs ?",
	"WriteReview_Dialog_RecommendGame_Revise": "Voulez-vous modifier votre évaluation ?",
	"WriteReview_Dialog_GetHelp_Btn": "Obtenir de l'aide à propos de mon achat",
	"WriteReview_Dialog_Visibility": "Visibilité :",
	"WriteReview_Dialog_Public": "publique",
	"WriteReview_Dialog_Friends": "amis uniquement",
	"WriteReview_Dialog_Yes": "Oui",
	"WriteReview_Dialog_No": "Non",
	"WriteReview_Dialog_GetSupport_Btn": "Obtenir de l'aide à propos de mon achat",
	"WriteReview_Dialog_GetSupport_Desc": "Obtenez des conseils techniques, contactez l'assistance ou faites une demande de remboursement.",
	"WriteReview_Dialog_AddReview_Btn": "Publier une évaluation",
	"WriteReview_Dialog_AddReview_Desc": "Partagez votre avis avec d'autres joueurs.",
	"WriteReview_Dialog_AddReview_Header": "Voulez-vous publier une évaluation ?",
	"WriteReview_Dialog_ReviewInstructions_Link": "règles et recommandations",
	"WriteReview_Dialog_ReviewInstructions": "Veuillez décrire ce que vous avez aimé ou n'avez pas aimé à propos de ce produit. Veuillez également indiquer si vous le recommandez à d'autres utilisateurs. Veillez à garder un langage correct et à respecter les %1$s. Votre recommandation ne sera pas publiée s'il n'y a pas de description.",
	"WriteReview_Dialog_AllowComments": "Autoriser les commentaires",
	"WriteReview_Dialog_FreeDisclaimer": "Cochez cette case si vous avez reçu ce produit gratuitement",
	"WriteReview_Dialog_FreeDisclaimer_Tooltip": "Cochez cette case si vous avez reçu ce produit gratuitement. La mention « Produit reçu gratuitement » s'affichera avec votre évaluation. Si vous avez été rémunéré pour évaluer ce jeu, vous devez le préciser dans votre évaluation.",
	"WriteReview_Dialog_FormattingHelp": "Aide au formatage",
	"WriteReview_Dialog_GenericError": "Une erreur s'est produite lors de la publication de votre évaluation. Veuillez réessayer ultérieurement.",
	"WriteReview_Dialog_NoTextError": "Veuillez décrire ce que vous avez aimé ou n'avez pas aimé à propos de ce produit.",
	"WriteReview_Dialog_Delay": "Peut-être plus tard",
	"Broadcast_View_Stack_H": "Vue horizontale",
	"Broadcast_View_Stack_V": "Vue verticale",
	"Broadcast_View_Theater": "Mode cinéma",
	"Broadcast_View_Fullscreen": "Plein écran",
	"Broadcast_View_HideChat": "Masquer le chat",
	"Broadcast_View_ShowBothChats": "Afficher les deux chats",
	"Broadcast_View_ShowSingleChats": "Afficher un seul chat",
	"Broadcast_View_ShowChat": "Afficher le chat",
	"Broadcast_Store_FreeToPlay": "Jeu gratuit",
	"PartnerEvent_1": "Autre événement",
	"PartnerEvent_2": "Événement du jeu",
	"PartnerEvent_3": "Événement : fête",
	"PartnerEvent_4": "Événement : rencontre",
	"PartnerEvent_5": "Événement caritatif",
	"PartnerEvent_6": "Événement musical et artistique",
	"PartnerEvent_7": "Événement sportif",
	"PartnerEvent_8": "En direct depuis un événement",
	"PartnerEvent_9": "Chat",
	"PartnerEvent_9_editor": "Chat ou session de questions-réponses",
	"PartnerEvent_10": "Sortie de jeu",
	"PartnerEvent_10_editor": "Sortie officielle d'un jeu",
	"PartnerEvent_11": "Stream ou diffusion",
	"PartnerEvent_12": "Mise à jour mineure (correctifs)",
	"PartnerEvent_13": "Mise à jour régulière",
	"PartnerEvent_14": "Mise à jour importante",
	"PartnerEvent_15": "Nouveau DLC",
	"PartnerEvent_16": "Sortie à venir",
	"PartnerEvent_16_editor": "Sortie d'un jeu à une certaine date",
	"PartnerEvent_17": "Diffusion d'un tournoi e-sport",
	"PartnerEvent_18": "Diffusion de développeur",
	"PartnerEvent_19": "Diffusion de célébrité",
	"PartnerEvent_20": "Jeu en promotion",
	"PartnerEvent_20_editor": "Promotion sur ce jeu",
	"PartnerEvent_21": "Promotion sur un article ou DLC",
	"PartnerEvent_21_editor": "Promotion sur des items en jeu ou des DLC",
	"PartnerEvent_22": "XP bonus",
	"PartnerEvent_23": "Événement : récompenses",
	"PartnerEvent_24": "Événement : avantages",
	"PartnerEvent_25": "Événement : défi",
	"PartnerEvent_26": "Concours",
	"PartnerEvent_27": "Événement : IRL",
	"PartnerEvent_27_editor": "Participation à une expo, une rencontre ou une convention",
	"PartnerEvent_28": "Actualités",
	"PartnerEvent_28_editor": "Annonces et actualités",
	"PartnerEvent_29": "Sortie en version bêta",
	"PartnerEvent_29_editor": "Invitation à participer à une bêta et actualités",
	"PartnerEvent_30": "Contenu en jeu mis à jour",
	"PartnerEvent_31": "Essai gratuit",
	"PartnerEvent_32": "Lancement d'un passe de bataille ou de saison",
	"PartnerEvent_33": "Mise à jour de saison",
	"PartnerEvent_34": "Promotion croisée",
	"PartnerEvent_35": "Événement en jeu général",
	"PartnerEvent_Other": "Autre événement",
	"PartnerEvent_SteamAwardNominations": "Demande de nomination aux Steam Awards",
	"PartnerEvent_SteamAwardVoteRequest": "Demande de votes pour les Steam Awards",
	"SocialMedia_Type_ShortName_1": "Steam",
	"SocialMedia_Type_ShortName_2": "Google",
	"SocialMedia_Type_ShortName_3": "Facebook",
	"SocialMedia_Type_ShortName_4": "Twitter",
	"SocialMedia_Type_ShortName_5": "Twitch",
	"SocialMedia_Type_ShortName_6": "YouTube",
	"SocialMedia_Type_ShortName_7": "Facebook",
	"MobileLogin_NoSteamAccount": "Vous n'avez pas de compte Steam ?",
	"MobileLogin_CreateAccount": "Créez un compte gratuitement",
	"MobileLogin_ForgotPassword": "Nom de compte ou mot de passe oublié ?",
	"MobileLogin_RefreshCaptcha": "Actualiser",
	"MobileLogin_SignIn": "Connexion",
	"MobileLogin_SigningIn": "Connexion",
	"MobileLogin_AccountName": "Nom du compte Steam",
	"MobileLogin_Password": "Mot de passe",
	"MobileLogin_CaptchaVerification": "Vérification",
	"MobileLogin_Enter2FA": "Saisissez le code généré dans la section Steam Guard de l'application mobile Steam.",
	"MobileLogin_Enter2FAHelp": "Je n'ai pas accès à mon code Steam Guard",
	"MobileLogin_EnterSteamguard": "Je n'ai pas reçu mon code Steam Guard par e-mail",
	"MobileLogin_SteamguardCode": "Code Steam Guard",
	"MobileLogin_SteamguardSubmit": "Envoyer et se connecter",
	"MobileLogin_SentSteamguard_1": "Un message vous a été envoyé à l'adresse e-mail",
	"MobileLogin_SentSteamguard_2": "Veuillez saisir le code Steam Guard envoyé.",
	"MobileLogin_IncorrectSteamGuard": "Le code Steam Guard saisi est incorrect. Veuillez vérifier le code et réessayer.",
	"MobileLogin_Error_RateLimitExceeded": "Trop de tentatives de connexion échouées ont eu lieu depuis votre réseau. Veuillez patienter et réessayer plus tard.",
	"Login_SignIn": "Se connecter",
	"Login_SigningIn": "Connexion",
	"Login_AccountName": "Nom du compte Steam",
	"Login_Password": "Mot de passe",
	"Login_RememberMe": "Se souvenir de moi sur cet ordinateur",
	"Login_ForgotPassword": "Nom de compte ou mot de passe oublié ?",
	"Login_NoSteamAccount": "Vous n'avez pas de compte Steam ?",
	"Login_CreateAccount": "Créez un compte gratuitement",
	"Login_CaptchaVerification": "Pour garantir que vous n'êtes pas un robot, saisissez à nouveau les caractères du captcha.",
	"Login_RefreshCaptcha": "Actualiser",
	"Login_Enter2FA": "Saisissez le code généré dans la section Steam Guard de l'application mobile Steam.",
	"Login_Enter2FAHelp": "Je n'ai pas accès à mon code Steam Guard",
	"Login_EnterSteamguard": "Je n'ai pas reçu mon code Steam Guard par e-mail",
	"Login_SteamguardSubmit": "Envoyer et se connecter",
	"Login_SentSteamguard": "Nous vous avons envoyé un message à l'adresse e-mail suivante : %1$s. Veuillez saisir le code Steam Guard envoyé.",
	"Login_SignOut": "Déconnexion",
	"Emoticon_Search": "Rechercher des émoticônes",
	"Chat_Settings_Error_ChatFileTooLarge": "%1$s est trop volumineux (10 Mo maximum).",
	"Chat_Settings_Error_ChatFileTypeNotSupported": "Impossible de télécharger %1$s. Seuls les fichiers au format jpg, png, gif, webm, mpg et ogv sont pris en charge.",
	"ConnectionTrouble_FailedToConnect": "Impossible de se connecter à Steam",
	"Chat_Upload_ErrorCloud": "Échec de l'envoi des données de l'image au serveur cloud.",
	"Chat_Settings_Error_ServerError": "Une erreur serveur s’est produite",
	"Broadcast_ViewerCount": "%1$s spectateurs",
	"Broadcast_VideoContext_ToggleStats": "Afficher/masquer les statistiques",
	"Broadcast_VideoContext_OpenStore": "Visiter la page du magasin",
	"Broadcast_None": "Aucune",
	"BroadcastWatch_MinBrowser": "Votre navigateur ne prend pas en charge les fonctionnalités de base requises pour regarder cette diffusion",
	"BroadcastWatch_RequestFailed": "Impossible de charger cette diffusion",
	"BroadcastWatch_NotAvailable": "Ce diffuseur est hors ligne",
	"BroadcastWatch_WaitingForResponse": "En attente d'acceptation",
	"BroadcastWatch_WaitingForStart": "Cette diffusion va commencer",
	"BroadcastWatch_WaitingForReconnect": "Reconnexion à la diffusion",
	"BroadcastWatch_ServerLoad": "Steam connaît actuellement une forte charge en diffusion et ne peut pas réserver d'emplacement serveur pour démarrer cette diffusion. Veuillez réessayer dans quelques minutes.",
	"BroadcastWatch_SystemNotSupported": "La diffusion Steam n'est actuellement pas compatible avec le système de ce diffuseur",
	"BroadcastWatch_UserRestricted": "Ce diffuseur ne peut pas diffuser sur Steam pour le moment",
	"BroadcastWatch_PoorUploadQuality": "Ce diffuseur ne parvient pas actuellement à maintenir une connexion de diffusion stable avec Steam",
	"BroadcastChat_Reconnected": "Reconnecté(e) au chat",
	"BroadcastChat_UnableToJoinChat": "Impossible de rejoindre le chat",
	"BroadcastChat_NeverTell": "Ne partagez jamais votre mot de passe",
	"BroadcastChat_EnterResponse": "Écrivez pour discuter",
	"BroadcastChat_InsertEmoticon": "Insérer des émoticônes",
	"BroadcastChat_Send": "Envoyer",
	"BroadcastChat_UserJoined": "%1$s a rejoint le chat",
	"BroadcastChat_UserLeft": "%1$s a quitté le chat",
	"BroadcastChat_UserMuted": "%1$s n'est plus autorisé à discuter dans cette salle de chat",
	"BroadcastChat_UserMutedLocal": "%1$s a été bloqué(e)",
	"BroadcastChat_UserUnmutedLocal": "%1$s a été débloqué(e)",
	"BroadcastChat_UserMuteFailed": "Impossible de bloquer %1$s. Veuillez réessayer.",
	"BroadcastChat_RemoveMessagesFailed": "Impossible de supprimer les messages de %1$s. Veuillez réessayer.",
	"BroadcastChat_UserUnmuteFailed": "Impossible de débloquer %1$s. Veuillez réessayer.",
	"BroadcastChat_YouMuted": "Vous avez été bloqué(e) et ne pouvez pas publier de messages sur ce chat",
	"BroadcastChat_FailedToSendMsg": "Impossible d’envoyer le message : %1$s",
	"BroadcastChat_Cooldown": "Vous envoyez des messages trop vite. Veuillez réessayer dans %1$s secondes.",
	"BroadcastChat_Mute": "Bloquer",
	"BroadcastChat_Unmute": "Débloquer",
	"BroadcastChat_MuteLocal": "Bloquer pour ce chat",
	"BroadcastChat_UnmuteLocal": "Débloquer pour ce chat",
	"BroadcastChat_Login": "Connectez-vous pour rejoindre le chat",
	"BroadcastChat_LimitedUser": "Accès au chat limité",
	"BroadcastChat_RemoveMessages": "Supprimer les messages de cet utilisateur",
	"BroadcastChat_Blocked": "Seuls les propriétaires du jeu sont autorisés à envoyer des messages pendant cette diffusion.",
	"BroadcastChat_half_Mute": "Bloquer pendant 12 heures",
	"BroadcastChat_day_Mute": "Bloquer pendant 24 heures",
	"BroadcastChat_week_Mute": "Bloquer pendant une semaine",
	"BroadcastChat_perm_Mute": "Bloquer indéfiniment",
	"BroadcastChat_half_Shadow": "Rendre invisible pendant 12 heures",
	"BroadcastChat_day_Shadow": "Rendre invisible pendant 24 heures",
	"BroadcastChat_week_Shadow": "Rendre invisible pendant une semaine",
	"BroadcastChat_perm_Shadow": "Rendre invisible indéfiniment",
	"BroadcastChat_Add_Moderator": "Promouvoir cet utilisateur au rang de modérateur",
	"BroadcastChat_Remove_Moderator": "Supprimer le statut de modérateur de l'utilisateur",
	"BroadcastChat_Change_Moderator_Title": "Changer le statut de modérateur de l'utilisateur ",
	"BroadcastChat_Change_Add_Confirm": "Voulez-vous vraiment ajouter cet utilisateur comme modérateur ? Il pourra bloquer les autres utilisateurs sur le chat de diffusion.",
	"BroadcastChat_Change_Remove_Confirm": "Voulez-vous vraiment supprimer les droits de modération de cet utilisateur ?",
	"BroadcastChat_Tooltip_Show_Chat_Viewers": "Afficher la liste des utilisateurs présents dans le chat.",
	"BroadcastChat_Tooltip_Minimize_Chat": "Réduire la fenêtre de chat",
	"BroadcastChat_Tooltip_Maximize_Chat": "Agrandir la fenêtre de chat",
	"BroadcastChat_Tooltip_Popout_Chat": "Faire apparaître le chat dans une nouvelle fenêtre",
	"BroadcastChat_ChatOnly_Title": "Chat de diffusion uniquement",
	"BroadcastChat_DefaultMessage": "Bienvenue dans le chat !",
	"BroadcastChat_Moderator": "Modérateur",
	"BroadcastChat_Broadcaster": "Diffuseur",
	"ChatEntryButton_Submit": "Envoyer",
	"ChatEntryButton_Emoticon": "Sélecteur d'émoticônes",
	"ChatEntryButton_Flair": "Choisir un badge",
	"ChatEntryButton_SendEmbed": "Pièce jointe",
	"Store_AddToCart": "Ajouter au panier",
	"YouTubePlayer_Loading": "Chargement de YouTube...",
	"home_page_live_broadcast": "En direct",
	"StoreBroadcast_Hide_Tooltip": "Afficher/masquer la diffusion en direct",
	"StoreBroadcast_Detault_popout_Title": "Diffusion en cours",
	"StoreBroadcast_close_broadcast_popup": "Ferme la fenêtre de la diffusion. Cette fenêtre ne s'ouvrira plus jusqu'à la fin de la session.",
	"StoreBroadcast_Change_store_Broadcast_settings": "Modifier les paramètres de diffusion",
	"Broadcast_Embedded_viewer": "%1$s spectateur",
	"Broadcast_Embedded_viewer_Plural": "%1$s spectateurs",
	"BroadcastWatch_View_Broadcast_Page": "Voir la page de diffusion",
	"Broadcast_Embed_Watch_SteamTV": "Regarder sur Steam.tv",
	"Broadcast_Embed_Watch_With_Frieds_SteamTV": "Regarder la diffusion et discuter avec vos amis sur Steam.tv",
	"sale_three_section_hide_chat": "Masquer le chat",
	"sale_three_section_show_chat": "Afficher le chat",
	"btn_live_streams_all": "Tout voir",
	"Broadcast_default_title_dev": "Diffusion en cours : regardez le développeur jouer",
	"Broadcast_default_title_community": "Diffusion en cours : regardez la communauté jouer",
	"Broadcast_default_title_comp": "Diffusion en cours : regardez ce match compétitif",
	"Broadcast_default_title_speed": "Diffusion en cours : regardez ce speedrun",
	"Sale_BundleSave": "Comprend %1$s articles.",
	"Sale_PackageSave": "Comprend %1$s articles.",
	"Sale_ShowContents": "Afficher les contenus",
	"Sale_ShowMore": "Afficher plus",
	"Sale_ShowLess": "Réduire",
	"Sale_OnWishlist": "Dans votre liste de souhaits",
	"Sale_InLibrary": "Dans votre bibliothèque",
	"Sale_HiddenItems": "%1$s article(s) masqué(s) par %2$s",
	"Sale_HiddenItem_Single": "%1$s article masqué par %2$s",
	"Sale_StorePreferences": "vos préférences du contenu du magasin",
	"Sale_SeeAllSpecials": "Voir toutes les promotions",
	"Sale_AddToWishlist": "Ajouter à la liste de souhaits",
	"Sale_RemoveFromWishlist": "Supprimer de la liste de souhaits",
	"Sale_Preferences": "Préférences",
	"Sale_PlaceHolder": "Mode de prévisualisation : cette section n'a pas de capsules. Elle n'apparaîtra pas sur la page des utilisateurs si elle vide.",
	"Sale_SmartPlaceHolder": "Mode de prévisualisation : cette section « intelligente » n'a pas d'applications à vous recommander. Elle n'apparaîtra pas sur la page des utilisateurs si elle vide.",
	"Sale_default_label": "(sans titre)",
	"Sale_default_label_OnSale": "En promotion",
	"Sale_default_label_TopSellers": "Meilleures ventes",
	"Sale_default_label_FreeToPlay": "Gratuit",
	"Sale_default_label_HorrorGames": "Jeux d'horreur",
	"Sale_default_label_HorrorVR": "Horreur en VR",
	"Sale_default_label_HorrorFreeToPlay": "Jeu d'horreur gratuit",
	"Sale_default_label_HalloweenEventsHorror": "Événements d'Halloween (jeux d'horreur)",
	"Sale_default_label_HalloweenEventsNonHorror": "Événements d'Halloween (autres jeux)",
	"Sale_default_label_MoreHalloweenEvents": "Autres événements pour Halloween",
	"Sale_default_label_MoreHalloweenEventsNonHorror": "Plus d'événements d'Halloween (autres jeux)",
	"Sale_default_label_NewAndUpcomingHorror": "Nouveux jeux d'horreur et sorties prochaines",
	"Sale_default_label_RemotePlay_Together": "Play Together : avec vos amis à distance",
	"Sale_default_label_RemotePlay_Phone": "Play Anywhere : sur votre téléphone",
	"Sale_default_label_RemotePlay_Tablet": "Play Anywhere : sur votre tablette",
	"Sale_default_label_RemotePlay_TV": "Play Anywhere : sur votre téléviseur",
	"Sale_default_label_OnYourWishlist": "Sur votre liste de souhaits",
	"Sale_default_label_RecommendedForYou": "Recommandé pour vous",
	"Sale_default_label_ComingSoon": "Prochainement",
	"Sale_default_label_JustAnnounced": "Annoncé récemment",
	"Sale_default_label_JustUpdated": "Mis à jour récemment",
	"Sale_default_label_FreeWeekend": "Weekend gratuit",
	"Sale_default_label_FreeWeek": "Semaine gratuite",
	"Sale_default_label_PrePurchase": "Préachetez maintenant",
	"Sale_default_label_NewReleases": "Nouveautés",
	"Sale_default_label_JustReleased": "Sorti récemment",
	"Sale_default_label_Highlighted": "Offres en vedette",
	"Sale_default_label_BackCat": "Fond de catalogue",
	"Sale_default_label_PlayForFree": "Jouez gratuitement !",
	"Sale_defautl_label_FreeToKeep": "Offre à durée limitée : installez le jeu maintenant et gardez-le",
	"SalePage_LoginPrompt": "Connectez-vous pour voir des articles supplémentaires sélectionnés rien que pour vous.",
	"SalePage_ParentApp_DLC": "DLC pour",
	"SalePage_ParentApp_SoundTrack": "Bande-son pour",
	"SalePage_WatchForDrop_Minutes_Developer": "Regardez la diffusion pendant %1$s minutes et recevez des items de la part du développeur à la fin de l'événement !",
	"SalePage_WatchForDrop_Minutes_CreatorNamed": "Regardez la diffusion pendant %1$s minutes et recevez des items de la part de %2$s à la fin de l'événement !",
	"SalePage_WatchForDrop_Hours_Developer": "Regardez la diffusion pendant %1$s heures et recevez des items de la part du développeur à la fin de l'événement !",
	"SalePage_WatchForDrop_Hours_CreatorNamed": "Regardez la diffusion pendant %1$s heures et recevez des items de la part de %2$s à la fin de l'événement !",
	"SalePage_WatchForDrop_LearnMore": "Pour plus d'informations sur la distribution d'items, cliquez ici.",
	"SalePage_Admin_SaleEventDay": "Voir le jour %1$s des soldes",
	"Steam_Settings_Compat_Launch_Prefix": "Fonctionne sur cet ordinateur via",
	"Steam_Settings_Compat_Launch_Name": "Steam Play.",
	"Steam_Settings_Compat_Launch_Forced": "sélectionné par vous pour ce titre.",
	"Steam_Settings_Compat_Launch_Wildcard": "sélectionné par vous pour tous les titres.",
	"Steam_Settings_Compat_Launch_Whitelisted": "sélectionné par Valve.",
	"SteamAwards_EventMainTitle": "Les Steam Awards",
	"SteamAwards_EventMainTitleSecondLine": "Nominé",
	"SteamAwards_EventCallToAction": "Prochainement en décembre",
	"SteamAwards_EventVotingDateTeaser": "Décembre 2019",
	"SteamAwards_EventVoteForGamePrompt": "Cliquez ci-dessous pour voter pour %1$s dans la catégorie :",
	"SteamAwards_EventNominateGamePrompt_Long": "Nominez %1$s dans la catégorie ci-dessous (suggérée par les développeurs du jeu) ou sélectionnez une catégorie différente",
	"SteamAwards_EventNominateGamePrompt_NoCategory": "Cliquez ici pour nominer %1$s dans une catégorie des Steam Awards.",
	"SteamAwards_Event_NominationsClosed": "Les nominations sont terminées. Vous pourrez voter pendant les soldes d'hiver. Les gagnants seront annoncés le 31 décembre.",
	"SteamAwards_Event_VotesClosed": "Les votes sont clos. Cliquez ici pour découvrir les résultats.",
	"SteamAwards_EventNominateGamePrompt_CategoryPrefix": "Nominez dans la catégorie :",
	"SteamAwards_EventNominationAlternativeLinkText": "Ou choisissez une autre catégorie",
	"SteamAward_CategoryTitle_none": "Aucune catégorie",
	"SteamAward_CategoryDesc_none": "Ne proposer aucune catégorie et laisser vos fans choisir la catégorie qui, selon eux, correspond le mieux à votre jeu. Un lien qui mène à la page des nominations sera tout de même inclus à votre événement.",
	"SteamAward_CategoryTitle_goty": "Jeu de l'année 2019",
	"SteamAward_CategoryDesc_goty": "Peut-être était-ce son gameplay immersif, ou son histoire captivante, ses personnages bien conçus, son design immaculé ou son mode multijoueur addictif. Quelle que soit la raison, le gagnant du prix du meilleur jeu de 2018 est un vrai classique.",
	"SteamAward_CategoryTitle_vrgoty": "Jeu VR de l'année 2019",
	"SteamAward_CategoryDesc_vrgoty": "Lorsqu'il s'agit d'innover dans l'industrie du jeu, aucun domaine ne progresse aussi rapidement que la VR. Si cela ne tenait qu'à nous, tous les développeurs de VR seraient récompensés pour leur travail précurseur dans la création de jeux immersifs et d'expériences inégalées par les autres médias. Il n'y a cependant qu'un seul trophée, et c'est à vous, en tant que membre du comité de sélection des Steam Awards, de décerner le prix au meilleur d'entre eux.",
	"SteamAward_CategoryTitle_love": "Amour indéfectible 2019",
	"SteamAward_CategoryDesc_love": "Ce jeu est sorti depuis un moment. L'équipe a présenté sa création pour la première fois depuis bien longtemps, mais en bonne mère, elle continue de materner et soutenir son bébé. Ce jeu, jusqu'à ce jour, reçoit toujours du nouveau contenu après toutes ces années.",
	"SteamAward_CategoryTitle_friends": "C'est mieux avec des amis 2019",
	"SteamAward_CategoryDesc_friends": "Pour certains jeux, jouer tout seul, ce n'est vraiment pas pareil. Que vous ayez besoin d'un ami pour surveiller vos arrières, ou pour le poignarder dans le dos, jouer à ces jeux avec des amis, c'est la joie garantie.",
	"SteamAward_CategoryTitle_gameplay": "Gameplay le plus innovant",
	"SteamAward_CategoryDesc_gameplay": "Ce jeu est à l'avant-garde de l'expérimentation. Il repousse les frontières de l'industrie grâce à de toutes nouvelles interactions ingénieuses et des surprises déconcertantes. Avec ce jeu, vous sortirez des sentiers battus !",
	"SteamAward_CategoryTitle_storyrich": "Jeu à l'histoire exceptionnelle",
	"SteamAward_CategoryDesc_storyrich": "Parfois, seul un jeu à l'histoire bien ficelée parvient au sommet. Celui-ci est un premier de cordée. Il est aussi captivant qu'un bon feuilleton et aussi bien mené qu'un scénario de série primée. Chapeau bas pour nous avoir procuré autant d'émotions !",
	"SteamAward_CategoryTitle_yousuck": "Meilleur jeu auquel vous êtes nul",
	"SteamAward_CategoryDesc_yousuck": "Les jeux sont capables de repousser nos limites au-delà de ce que nous pensions possible. Comme dans un schéma préétabli, nous nous mettons au travail. Pendant des semaines, nous exerçons nos doigts pour qu'ils deviennent rapides et agiles, nous apprenons à optimiser le temps et nos mouvements. À la fin de la joute, nous sommes récompensés par une profonde beauté et un sentiment de développement personnel. Sauf si vous avez jeté votre écran à travers la fenêtre dès le premier jour.",
	"SteamAward_CategoryTitle_visual": "Style visuel exceptionnel",
	"SteamAward_CategoryDesc_visual": "Ces développeurs sont les Willy Wonka des friandises visuelles. Le style visuel n'aspire pas à la fidélité graphique au monde réel (même si c'est un but fort noble en soi), il insuffle au jeu son identité visuelle et son atmosphère. Dans ce jeu, la cohésion et l'expression visuelles collent parfaitement à l'univers et font paraître notre monde bien fade en comparaison.",
	"SteamAward_NominationConflictWarning_Title": "Voulez-vous changer votre nomination ?",
	"SteamAward_NominationConflictWarning_Explanation": "Vous ne pouvez nominer qu'un seul jeu dans chaque catégorie, et vous avez déjà nominé %1$s dans cette catégorie. Voulez-vous nominer %2$s à la place ?",
	"SteamAward_VoteButton_PromptText": "Voter",
	"SteamAward_VoteButton_AlreadyVotedText": "Vote pris en compte",
	"SteamAward_VoteConflictWarning_Title": "Voulez-vous changer votre vote ?",
	"SteamAward_VoteConflictWarning_Explanation": "Vous ne pouvez voter que pour un seul jeu dans chaque catégorie, et vous avez déjà voté pour %1$s dans cette catégorie. Voulez-vous voter pour %2$s à la place ?",
	"Store_VR_Support_OnlyVR": "VR seulement",
	"Store_VR_Support_SupportsVR": "VR prise en charge",
	"Giveaway_CountDown": "Temps restant avant le prochain tirage au sort : %1$s",
	"Giveaway_CountDown2": "Temps restant avant le prochain tirage au sort.",
	"Giveaway_KeepWatching": "Continuez à regarder pour tenter de gagner une récompense !",
	"Giveaway_RandomDraw": "Tirage au sort en cours",
	"Giveaway_Congratulation": "Nombre actuel de gagnants",
	"Giveaway_Closed_NoWinnerInfo": "Le concours est maintenant terminé. Merci de votre participation !",
	"Giveaway_Closed": "Le concours est maintenant terminé. Il y a eu %1$s heureux gagnants. Merci de votre participation !",
	"Giveaway_LearnMore": "Cliquez ici pour en savoir plus sur les récompenses, les gagnants et les règles",
	"Lunar2020_CheckBackEachDay": "Revenez chaque jour chercher un nouveau cadeau de l'Empereur !",
	"Lunar2020_CheckBackEachDayForStory": "Revenez chaque jour découvrir un nouveau chapitre",
	"Lunar2020_FirstGift": "Premier cadeau",
	"Lunar2020_SecondGift": "Deuxième cadeau",
	"Lunar2020_ThirdGift": "Troisième cadeau",
	"Lunar2020_FourthGift": "Quatrième cadeau",
	"Lunar2020_GiftWasOpened": "ouvert",
	"Lunar2020_RereadStory": "lire l'histoire",
	"Lunar2020_GiftCanBeOpenedNow": "ouvrir maintenant",
	"Lunar2020_GiftCanBeOpenedAfterThePreviousOne": "ouvrir le prochain",
	"Lunar2020_GiftLockedUntilDate": "ouvrir le %1$s",
	"Lunar2020_ErrorLoadingVideo": "Veuillez utiliser un navigateur qui prend en charge les vidéos HTML pour ouvrir votre enveloppe.",
	"Lunar2020_LinkBackToSale": "Revenir aux soldes",
	"Lunar2020_LinkFromVideoToMarket": "Explorer le marché",
	"Lunar2020_ReceivedNumberOfTokens": "Vous avez reçu %1$s jetons",
	"Lunar2020_YourBalancePrefix": "Votre solde",
	"Lunar2020_BalanceNumberOfTokens": "%1$s jetons",
	"Lunar2020_LimitedUserDialogTitle": "Impossible d'ouvrir l'enveloppe",
	"Lunar2020_StoryTitle": "LA GRANDE COURSE DE L'EMPEREUR",
	"Lunar2020_StorySubTitle": "Les origines de l'astrologie chinoise",
	"Lunar2020_StoryDayOneHeader": "Partie I sur IV",
	"Lunar2020_StoryDayTwoHeader": "Partie II sur IV",
	"Lunar2020_StoryDayThreeHeader": "Partie III sur IV",
	"Lunar2020_StoryDayFourHeader": "Partie IV sur IV",
	"Lunar2020_StoryDayOne": "L'Empereur de jade appela toutes les créatures de son empire à faire la course vers le palais céleste et déclara que les douze premières à franchir la ligne d'arrivée seraient mises à l'honneur sur son nouveau calendrier.\n\nL'ingénieux rat était le premier à franchir la rivière et accéder au monde des cieux. Comme il n'aimait pas nager, il demanda au fidèle bœuf de l'emmener sur son dos, et bondit vers les jardins célestes de l'Empereur juste avant que sa monture n'atteignît le rivage.\n\nLe robuste bœuf traversa la rivière aisément, sans se soucier du résultat de la course. La deuxième place lui convenait, d'autant qu'il avait pu contribuer à la victoire du rat.",
	"Lunar2020_StoryDayTwo": "La prudence dont le tigre indépendant faisait preuve lors de ses déplacements ne lui permit pas de dépasser le bœuf, et il préféra se contenter de la troisième place qui lui permettait tout de même de refermer les marches du podium.\n\nLe lièvre véloce bondit sur un bois flottant qui naviguait bien lentement. La chance finit par tourner et une brise bienvenue poussa rapidement son bateau de fortune vers sa destination.\n\nLe dragon ailé observait de son haut point de vue les autres en difficulté, et ne put s'empêcher de les aider. Il gratifia même le lièvre d'une bourrasque au-dessus de la rivière. L'honneur lui importait bien plus que la victoire, et la cinquième place lui seyait parfaitement.",
	"Lunar2020_StoryDayThree": "Le serpent furtif ne trouvait aucun intérêt à s'éreinter sur une longue distance et s'enroula discrètement autour du sabot avant du cheval.\n\nTandis que le cheval galopait en direction de la ligne d'arrivée, le serpent glissa au sol et surprit son destrier suffisamment longtemps pour ramper vers la sixième place, talonné par le cheval désarçonné.",
	"Lunar2020_StoryDayFour": "La chèvre, le singe et le coq firent équipe, mais la huitième place revint à la chèvre pour la récompenser de son aide précieuse pendant le trajet. Le singe obtint la neuvième place, et le coq se pavana à la dixième place d'un classement qu'il estimait légitime.\n\nLe chien espiègle se complut à patauger dans l'eau, considérant que la onzième place était une bonne affaire face au divertissement.\n\nArriva enfin en douzième position le cochon, qui s'était arrêté pour grignoter et piquer un petit somme. Il savait pertinemment que chaque animal aurait l'occasion de trouver grâce aux yeux de l'Empereur.",
	"SteamChina_PendingPersonaName": "Les modifications du profil prendront effet après vérification",
	"Legal_Footer_WithYear": "© %1$s Valve Corporation. Tous droits réservés. Toutes les marques commerciales sont la propriété de leurs détenteurs respectifs, aux États-Unis et dans d'autres pays.",
	"shared_dummy": "dont translate"
}
