{
	"language":		"english",

	"Button_Append": "Append",
	"Button_Cancel": "Cancel",
	"Button_Close": "Close",
	"Button_Clone": "Clone",
	"Button_Confirm": "Confirm",
	"Button_Copy": "Copy",
	"Button_CopyClipboard": "Copy to Clipboard",
	"Button_CopyLink": "Copy Link",
	"Button_Create": "Create",
	"Button_Delete": "Delete",
	"Button_Discuss": "Discuss",
	"Button_Dismiss": "Dismiss",
	"Button_Edit": "Edit",
	"Button_Publish": "Publish",
	"Button_Post": "Post",
	"Button_OK": "OK",
	"Button_Overwrite": "Overwrite",
	"Button_Retry": "Retry",
	"Button_Remove": "Remove",
	"Button_Save": "Save",
	"Button_Saved": "Saved",
	"Button_Share": "Share",
	"Button_Update": "Update",
	"Button_SaveAndContinue": "Save and Continue",
	"Button_Follow": "Follow",
	"Button_Followed": "Followed",
	"Button_Ignore": "Ignore",
	"Button_Ignored": "Ignored",
	"Button_NotifyMe": "Notify Me",
	"Button_NotInterested": "Not Interested",
	"Button_RateUp": "Rate Up",
	"Button_ViewPage": "View Page",
	"Button_Accept": "Accept",
	"Button_Reject": "Reject",

	"ToolTip_CopyLinkToClipboard": "Copy link to clipboard",

	"Input_Error_NumberTooSmall": "Number too small.",
	"Input_Error_NumberTooLarge": "Number too large.",
	"Input_Error_MustBeURL": "Field is not a valid URL.",
	"Input_Error_MustBeEmail": "Field is not a valid Email.",
	"Input_Error_MustBeNumber": "Field must be a number.",

	"Loading": "Loading...",
	"Updating": "Updating...",

	"Settings":	"Settings",
	"FriendSettings_AlwaysNewChatWindow": "Always open a new chat window rather than a tab",

	"g_DisabledOnWeb": "Unavailable in web version",

	"VoiceTransmissionType_Disabled": "Open Microphone only for web version",

	"VoiceVolume": "Volume",
	"VoiceSetupHeader": "Voice Setup And Testing",
	"VoiceStartLocalMicTest": "Start Microphone Test",
	"VoiceStopLocalMicTest": "End Microphone Test",
	"VoiceWhenMicIsWorking": "If your microphone is working then you should both hear yourself and see the colored bar next to your avatar move as you speak.",
	"VoiceDevice": "Voice Input Device",
	"VoiceOutputDevice": "Voice Output Device",
	"VoiceInputGain": "Input volume/gain",
	"VoiceInputGainExplainer": "(My microphone)",
	"VoiceOutputGain": "Output volume/gain",
	"VoiceOutputGainExplainer": "(My friends)",
	"VoiceTransmissionType": "Push-to-talk",
	"VoiceTransmissionType_Label": "Voice Transmission Type",
	"VoiceTransmissionType_OpenMic": "Open Microphone",
	"VoiceTransmissionType_PushToTalk": "Push-to-Talk",
	"VoiceTransmissionType_PushToMute": "Push-to-Mute",
	"VoiceClearHotKeyTooltip": "Clear mute toggle hotkey assignment",
	"VoiceTransmissionTypeExplainer": "Push a user defined key to talk in voice channels",
	"VoiceTransmissionType_WhenSpeaking": "Automatic",
	"VoiceTransmissionType_PushToTalk_Key": "Push-to-Talk: %1$s",
	"VoicePushToTalkPressHotKey": "Press key or mouse-button to assign",
	"VoicePushToTalkAssigned": "Push-to-talk hotkey assigned as",
	"VoicePushToMuteAssigned": "Push-to-mute hotkey assigned as",
	"VoiceMuteToggleAssigned": "Mute toggle hotkey assigned as",
	"VoicePushToSomethingSoundOption": "Play a short sound on microphone toggle",
	"VoiceTransmisionThreshold": "Voice Transmission Threshold",
	"VoiceTransmissionThresholdExplainer": "When your microphone is on, we won't transmit noise below this threshold:",
	"VoiceTransmissionThresholdOff": "Off",
	"VoiceTransmissionThresholdMedium": "Medium",
	"VoiceTransmissionThresholdHigh": "High",
	"VoiceTransmissionThresholdRecommended": "(Recommended)",
	"VoiceAdvancedSettings": "Advanced Settings",
	"VoiceShowAdvancedSettings": "Show Advanced Settings",
	"VoiceHideAdvancedSettings": "Hide Advanced Settings",
	"VoiceAdvancedSettingsExplainer": "(These are microphone settings handled by your platform or browser.)",
	"VoiceEchoCancellation": "Echo cancellation",
	"VoiceNoiseCancellation": "Noise cancellation",
	"VoiceAutoGainControl": "Automatic volume/gain control",
	"DefaultMic": "Default",
	"MicLoading...": "Loading...",
	"DefaultOutputDevice": "Default",
	"OutputDeviceLoading...": "Loading...",

	"BreadCrumbs_AllEvents": "All Events",
	"BreadCrumbs_GameEvents": "%1$s Events",

	"CreatorHome_ThisGame": "About This Game:",
	"CreatorHome_DevelopedBy": "Developed By:",
	"CreatorHome_PublishedBy": "Published By:",
	"CreatorHome_InFranchise": "In Franchise:",
	"CreatorHome_Followers": "%1$s<br>followers",
	"CreatorHome_JustFollowers": "followers",
	"CreatorHome_Follow_tooltip": "Follow this creator to to be notified via e-mail and in your Steam store when they release a new game. Email notifications can be turned off at any time.",

	"EventBrowse_MoreEventsTitle": "More events from %1$s",
	"EventBrowse_MoreEventsBtn": "View All",
	"EventBrowse_RecentUpdates": "Recent Updates",
	"EventBrowse_RecentEvents": "Recent Events & Announcements",

	"EventCalendar_Title": "events",
	"EventCalendar_SubTitle": "Upcoming events and activities hosted by game creators",
	"EventCalendar_LiveNow": "live now",
	"EventCalendar_Upcoming": "upcoming",
	"EventCalendar_LaterToday": "later today",
	"EventCalendar_ThisWeek": "this week",
	"EventCalendar_ThisMonth": "this month",
	"EventCalendar_MuchLater": "much later",

	"EventCalender_Type_Global": "global",
	"EventCalender_Type_Recommended": "recommended",

	"EventCalender_Show": "show",
	"EventCalender_Show_All": "all",

	"EventDisplay_Admin_Title": "Admin tools:",

	"EventDisplay_CallToAction_LearnMore": "Learn More",
	"EventDisplay_CallToAction_InLibrary": "In Library",
	"EventDisplay_CallToAction_PlayNow": "Play Now",
	"EventDisplay_CallToAction_ComingSoon": "Coming Soon",
	"EventDisplay_CallToAction_FreeToPlay": "Free To Play",

	"EventDisplay_Events": "Admin Dashboard",
	"EventDisplay_SeeOldVersion": "View Current Customer Version",

	"EventDisplay_RightColumnTitle_Game": "Game",
	"EventDisplay_RightColumnTitle_Blog": "Blog",
	"EventDisplay_RightColumnTitle_DateAndTime": "Date and Time",
	"EventDisplay_RightColumnTitle_EventType": "Type",

	"EventDisplay_PostedBy": "by ",

	"EventDisplay_Reminder_SetReminder": "Set a reminder",
	"EventDisplay_Reminder_FollowEvent": "Follow Event",
	"EventDisplay_Reminder_FollowEvent_ttip": "Follow an event to be notified when the event starts.",
	"EventDisplay_Reminder_RemindAtStart": "When the event starts",
	"EventDisplay_Reminder_RemindAtStart_ttip": "Steam will notify you at the time the event starts.",
	"EventDisplay_Reminder_IgnoreEvent": "Ignore This Event",
	"EventDisplay_Reminder_IgnoreStop": "Stop Reminders",
	"EventDisplay_Reminder_IgnoreEvent_ttip": "Ignoring an event will tell Steam to exclude this event for future suggestion and recommendations.",
	"EventDisplay_Reminder_FollowEvent_Error": "Follow Event Error",
	"EventDisplay_Reminder_FollowEvent_ErrorDesc": "Changing the event follow state hit the following error:",
	"EventDisplay_Reminder_IgnoreEvent_Error": "Ignore Event Error",
	"EventDisplay_Reminder_IgnoreEvent_ErrorDesc": "Changing the event ignore state hit the following error:",
	"EventDisplay_Reminder_Toast": "Steam Desktop Toast at Start",
	"EventDisplay_Reminder_AddToCalendar": "Add to calendar",
	"EventDisplay_Reminder_AddToApple": "Add to Apple Calendar",
	"EventDisplay_Reminder_AddToGoogle": "Add to Google Calendar",
	"EventDisplay_Reminder_AddToOutlook": "Add to Outlook Calendar",
	"EventDisplay_Reminder_AddToYahoo": "Add to Yahoo Calendar",
	"EventDisplay_Reminder_Preferences": "Edit Reminder Preferences...",

	"EventDisplay_TimeDisplay": "From %1$s to %2$s",
	"EventDisplay_TimeDisplayNone": "No Date and Time Information",
	"EventDisplay_TimeBeginsOn": "Upcoming Event Starts",
	"EventDisplay_TimeBeginsOn_Past": "Started",
	"EventDisplay_TimeBeginsOn_StartAndEnd_Past": "Past Event Started",
	"EventDisplay_TimeEndsOn": "Ends",
	"EventDisplay_TimeEndsOn_Past": "Ended",
	"EventDisplay_TimeEndsOn_Ran": "Ran",
	"EventDisplay_TimeRange": "Event Time",
	"EventDisplay_TimeInPast": "Posted",
	"EventDisplay_TimeUpcoming": "Event Starts",
	"EventDisplay_TimeEventActive": "Event is running now",
	"EventDisplay_TimeEventOnNow": "On now!",

	"EventDisplay_Share_Link": "Link: ",
	"EventDisplay_Share_OnMyStatus": "Share directly to my status",
	"EventDisplay_Share_OnMyStatus_Details": "Post this status to your Friends Activity feed. Steam will include the message and item preview shown below.",
	"EventDisplay_Share_OnMyStatus_Placeholder": "Say something about this to your friends...",
	"EventDisplay_Share_OnSteam": "Share on Steam Community as a status update",
	"EventDisplay_Share_OnFaceBook": "Share on Facebook",
	"EventDisplay_Share_OnTwitter": "Share on Twitter",
	"EventDisplay_Share_OnReddit": "Share on Reddit",
	"EventDisplay_Share_Success": "Success!",
	"EventDisplay_Share_Failure": "Failed with following message: ",
	"EventDisplay_Share_Announcement": "%1$s Announcement",
	"EventDisplay_Share_Event": "%1$s Event",
	"EventDisplay_Share_NotLoggedIn": "Not signed in",
	"EventDisplay_Share_NotLoggedIn_Description": "To use this feature, you first need to sign into Steam",
	"EventDisplay_Share_CommentMigrationInProcess": "Discussion for this event are queued to be migrated to the events system. They are temporarily unaccessible. Please come back later.",
	"EventDisplay_Share_OpenActivityFeed": "Open my activity feed",

	"EventDisplay_AreYouSure": "Are you sure you want to delete this event (%1$s)? This action cannot be undone.",
	"EventDisplay_AreYouSure_Visible": "Are you sure you want to delete this event (%1$s)? This action cannot be undone. This event will be removed from all places a user can discover it within a few minutes.",
	"EventDisplay_DeleteEvent_InProgress": "Delete in progress. Please wait.",
	"EventDisplay_DeleteEvent_Error": "There was an error processing the delete request:",
	"EventDisplay_DeleteEvent_ForumTopicError": "The event was successfully deleted. We failed when attempting to delete the forum topic thread for the event. You can always try against in %1$s site. Error details:",
	"EventDisplay_DeleteEvent_Success": "The event was successfully deleted.",
	"EventDisplay_DeleteEvent_Comment": "Also delete the discussion forum comment thread for this event?",
	"EventDisplay_SocialTitle": "More About This Game",

	"EventEditor_Publish_VisibleNow": "Make Visible Now",
	"EventEditor_Publish_VisibleNow_ttip": "This event will automatically become visible at the scheduled time. This button forces the event to become immediately visible.",

	"EventEditor_Edit": "Edit Event",
	"EventDisplay_DeleteEvent": "Delete Event",

	"EventReminder_InProgress": "(note that notification options shown here are representative and not yet functional)",
	"EventReminder_NotifyByEmail": "Notify me by Email",
	"EventReminder_NotifyByEmail_ttip": "Steam will send an email notification to your account when the event starts.",
	"EventReminder_NotifyByMobile": "Notify me on my Mobile device",
	"EventReminder_NotifyByMobile_ttip": "Steam will send a push notification to all mobiles you have an install and logged in Steam mobile app when the event starts.",
	"EventReminder_NotifyByEmail_Missing": "No verified email available.",
	"EventReminder_NotifyByEmail_Missing_Add": "Add one here.",
	"EventReminder_NotifyByMobile_Missing": "No mobile app installed.",
	"EventReminder_NotifyByMobile_Install": "View available apps here.",

	"EventEmail_Subject_NewUpdate": "%1$s, New Update",
	"EventEmail_Subject_UpcomingLaunch": "%1$s, Upcoming Launch",
	"EventEmail_Subject_NowAvailable": "%1$s Now Available",
	"EventEmail_Subject_FreeDemoAvailable": "%1$s Free Demo Now Available",
	"EventEmail_Subject_SpecialOffer": "%1$s Special Offer",
	"EventEmail_Subject_Tournament_Now": "%1$s Tournament, Tune in Now",
	"EventEmail_Subject_LiveStream_Now": "%1$s Live Stream, Tune in Now",
	"EventEmail_Button_ClickForMoreDetails": "Click for more details",
	"EventEmail_Button_PrepurchaseNow": "Prepurchase now!",
	"EventEmail_Button_BuyNow": "Buy now!",
	"EventEmail_Button_PlayNow": "Play Now!",
	"EventEmail_Button_WishlistNow": "Wishlist now!",
	"EventEmail_WatchNow": "Watch Now",
	"EventEmail_Destination_Store": "Steam Store Game Product Page",
	"EventEmail_Destination_Event": "Event Detail Page",
	"EventEmail_Destination_SalesPage": "Steam Store Sales Page",

	"EventDashBoard_SummaryStats_Admin_Title": "(Visible only to admins)",
	"EventDashBoard_SummaryStats_Title": "Total Unique Impressions and Views",
	"EventDashBoard_SummaryStats_Desc": "(Beta) These are impressions and views of your events and announcements by unique logged-in users. This is only for new events and announcements crafted with this editor.",
	"EventDashBoard_SummaryStats_Link": "Click here for more details.",
	"EventDashBoard_Summary_LibraryHome_Shown": "Impressions of events (cover image):",
	"EventDashBoard_Summary_LibraryHome_Read": "Clicks on an event to view details:",
	"EventDashBoard_Summary_AppDetailSpotlight_Shown": "Impressions of spotlight banner:",
	"EventDashBoard_Summary_AppDetailSpotlight_Read": "Clicks on a spotlight banner to view details:",
	"EventDashBoard_Summary_AppDetailActivity_Shown": "Impressions of events in activity feed:",
	"EventDashBoard_Summary_AppDetailActivity_Read": "Clicks on an event to view details:",
	"EventDashBoard_Summary_StoreAppPage_Shown": "Impressions of events (cover image):",
	"EventDashBoard_Summary_StoreAppPage_Read": "Clicks on an event to view details:",
	"EventDashBoard_Summary_Community_Shown": "Impressions of event summary:",
	"EventDashBoard_Summary_Community_Read": "Clicks on event summary to view details:",
	"EventDashBoard_Location_LibraryHome": "Library Home Page",
	"EventDashBoard_Location_LibraryDetail": "Library Game Page",
	"EventDashBoard_Location_StoreDetail": "Store Game Page",
	"EventDashBoard_Location_CommunityDetail": "Community App Hub",
	"EventDashBoard_Location_PopUpViews": "Views of event pop-up",

	"AddToWishlist": "Add to your Wishlist",
	"Wishlisted": "On your Wishlist",
	"AddToWishlist_ttip": "Get notified by email when your wishlisted items get released or are on sale",
	"Wishlist_Error": "Update Wishlist Error",
	"Wishlist_Error_Desc": "We encountered an error adding to your wishlist. Please try again later:",

	"WindowTitle_FriendsList": "Friends List",
	"FriendsList_OfflineTitle": "ERROR",
	"FriendsList_OfflineOrFailure": "Friends Network Unreachable",
	"FriendsList_OfflineDetail": "This failure may indicate that your local network is offline or that the Steam Friends servers are currently offline.",
	"FriendsList_SignedOut": "Signed Out of Friends & Chat",
	"FriendsList_SignedOut_Detail": "You are currently offline.  Sign in to access your friends list and chat.",
	"FriendsList_OfflineMode": "Signed Out of Friends & Chat",
	"FriendsList_OfflineMode_Detail": "Friends and chat are not available in Offline Mode. Please go online to access your friends list and chat.",
	"Friends_RetryLoading": "Retry Connection",
	"Friends_SignIn": "Sign In",
	"FriendsList_Offline_Disconnected": "Disconnected",

	"FriendsList_LoadingTitle": "LOADING",
	"FriendsList_StillLoadingSummary": "Friends Network Loading...",
	"FriendsList_StillLoadingDetail": "Steam is trying to connect to the friends network.  This may take a few seconds longer.",

	"Dialog_On": "ON",
	"Dialog_Off": "OFF",

	"TimeInterval_XYears": "%1$s years",
	"TimeInterval_1YearXMonths": "1 year and %1$s months",
	"TimeInterval_1Year": "1 year",
	"TimeInterval_XMonths": "%1$s months",
	"TimeInterval_1Month": "1 month",
	"TimeInterval_1MonthX": "1 month and %1$s days",
	"TimeInterval_XWeeks": "%1$s weeks",
	"TimeInterval_1Week": "1 week",
	"TimeInterval_XDays": "%1$s days",
	"TimeInterval_1Day": "1 day",
	"TimeInterval_1DayXHours": "1 day and %1$s hours",
	"TimeInterval_XHours": "%1$s hours",
	"TimeInterval_1Hour": "1 hour",
	"TimeInterval_1HourXMinutes": "1 hour and %1$s minutes",
	"TimeInterval_LessThanAnHour": "less than an hour",
	"TimeInterval_XMinutes": "%1$s minutes",
	"TimeInterval_1Minute": "1 minute",
	"TimeInterval_LessThanAMinute": "less than a minute",

	"TimeSince_XYears":			"%1$s years ago",
	"TimeSince_1YearXMonths":	"1 year and %1$s months ago",
	"TimeSince_1Year":			"1 year ago",
	"TimeSince_XMonths":			"%1$s months ago",
	"TimeSince_1Month":			"1 month ago",
	"TimeSince_1MonthXDays":		"1 month and %1$s days ago",
	"TimeSince_XWeeks":			"%1$s weeks ago",
	"TimeSince_1Week":			"1 week ago",
	"TimeSince_XDays":			"%1$s days ago",
	"TimeSince_1Day":			"1 day ago",
	"TimeSince_1DayXHours":		"1 day and %1$s hours ago",
	"TimeSince_XHours":			"%1$s hours ago",
	"TimeSince_1Hour":			"1 hour ago",
	"TimeSince_1HourXMinutes":	"1 hour and %1$s minutes ago",
	"TimeSince_LessThanAnHour":	"less than an hour ago",
	"TimeSince_XMinutes":		"%1$s minutes ago",
	"TimeSince_1Minute":			"1 minute ago",
	"TimeSince_LessThanAMinute":	"less than a minute ago",
	"TimeSince_ThisWeek":		"This week",

	"Time_Today": "Today",
	"Time_Yesterday": "Yesterday",
	"Time_Recent": "Recent",

	"ContextMenu_Copy":		"Copy",
	"ContextMenu_Cut":		"Cut",
	"ContextMenu_Paste":	"Paste",
	"ContextMenu_CopyLinkURL":	"Copy Link URL",
	"ContextMenu_OpenLinkInNewWindow":	"Open Link in New Window",
	"ContextMenu_CopyImageURL": "Copy Image URL",
	"ContextMenu_OpenImageInNewWindow": "Open Image in New Window",

	"Tooltip_Settings": "Manage friends list settings",
	"Tooltip_VoiceSettings": "Manage voice settings",
	"Tooltip_SearchFriends": "Search my friends list",
	"Tooltip_AddFriend": "Add a friend",
	"Tooltip_FriendRequest": "%1$s incoming request",
	"Tooltip_FriendRequest_Plural": "%1$s incoming requests",
	"Tooltip_CreateGroupChat": "Create a group chat",
	"Tooltip_InviteToGroup": "Invite a friend to this group chat",
	"Tooltip_InviteToGroup_Denied": "You do not have permission to invite users to this group",
	"Tooltip_GroupChatSettings": "Manage group chat settings",
	"Tooltip_MemberCollapse": "Collapse member list",
	"Tooltip_MemberExpand": "Expand member list",
	"Tooltip_ChatsCollapse": "Collapse chats list",
	"Tooltip_ChatsExpand": "Expand chats list",
	"Tooltip_MinimizeList": "Minimize List",
	"Tooltip_ExpandList": "Expand List",
	"Tooltip_PinChannelList": "Pin Channel List",
	"Tooltip_UnpinChannelList": "Unpin Channel List",
	"Tooltip_TextChannel": "Text chat with group members",
	"Tooltip_TextChannelCreate": "Create new text channel",
	"Tooltip_NoPermissionChannelCreate": "You do not have permission to create channels in this group chat",
	"Tooltip_VoiceChannel": "Voice chat in these voice channels",
	"Tooltip_VoiceChannelCreate": "Create new voice channel",
	"Tooltip_DismissVoice": "Decline Voice Invite",
	"Tooltip_MicStatus_Active": "Microphone is active",
	"Tooltip_MicStatus_Muted": "Microphone is muted",
	"Tooltip_RemoteMicStatus_Muted": "User muted their microphone",
	"Tooltip_MicStatus_NoMic": "User has no microphone connected",
	"Tooltip_RemoteOutputStatus_Muted": "User disabled audio from this channel",
	"Tooltip_YourMicStatus_Muted": "You muted your microphone",
	"Tooltip_YourOutputStatus_Muted": "You disabled audio from this channel",
	"Tooltip_VoiceControlButton_1v1_inactive": "Send a voice request",
	"Tooltip_VoiceControlButton_1v1_active": "Leave voice channel",
	"Tooltip_VoiceControlButton_group_create": "Create a voice channel",
	"Tooltip_VoiceControlButton_group_leave": "Leave voice channel",
	"Tooltip_VoiceControlButton_group_joinsingle": "Join voice channel",
	"Tooltip_VoiceControlButton_group_joinmultiple": "Select a voice channel to join",

	"LanguageTitle": "Language",

	"Language_english": "English",
	"Language_german": "German",
	"Language_french": "French",
	"Language_italian": "Italian",
	"Language_korean": "Korean",
	"Language_spanish": "Spanish - Spain",
	"Language_schinese": "Simplified Chinese",
	"Language_tchinese": "Traditional Chinese",
	"Language_russian": "Russian",
	"Language_thai": "Thai",
	"Language_japanese": "Japanese",
	"Language_portuguese": "Portuguese",
	"Language_polish": "Polish",
	"Language_danish": "Danish",
	"Language_dutch": "Dutch",
	"Language_finnish": "Finnish",
	"Language_norwegian": "Norwegian",
	"Language_swedish": "Swedish",
	"Language_hungarian": "Hungarian",
	"Language_czech": "Czech",
	"Language_romanian": "Romanian",
	"Language_turkish": "Turkish",
	"Language_arabic": "Arabic",
	"Language_brazilian": "Portuguese - Brazil",
	"Language_bulgarian": "Bulgarian",
	"Language_greek": "Greek",
	"Language_ukrainian": "Ukrainian",
	"Language_latam": "Spanish - Latin America",
	"Language_vietnamese": "Vietnamese",

	"Language_koreana": "Korean",

	"language_selection_english": "English",
	"language_selection_spanish": "Español - España (Spanish - Spain)",
	"language_selection_french": "Français (French)",
	"language_selection_italian": "Italiano (Italian)",
	"language_selection_german": "Deutsch (German)",
	"language_selection_greek": "Ελληνικά (Greek)",
	"language_selection_koreana": "한국어 (Korean)",
	"language_selection_korean": "한국어 (Korean)",
	"language_selection_schinese": "简体中文 (Simplified Chinese)",
	"language_selection_tchinese": "繁體中文 (Traditional Chinese)",
	"language_selection_russian": "Русский (Russian)",
	"language_selection_thai": "ไทย (Thai)",
	"language_selection_japanese": "日本語 (Japanese)",
	"language_selection_portuguese": "Português (Portuguese)",
	"language_selection_brazilian": "Português - Brasil (Portuguese - Brazil)",
	"language_selection_polish": "Polski (Polish)",
	"language_selection_danish": "Dansk (Danish)",
	"language_selection_dutch": "Nederlands (Dutch)",
	"language_selection_finnish": "Suomi (Finnish)",
	"language_selection_norwegian": "Norsk (Norwegian)",
	"language_selection_swedish": "Svenska (Swedish)",
	"language_selection_czech": "Čeština (Czech)",
	"language_selection_hungarian": "Magyar (Hungarian)",
	"language_selection_romanian": "Română (Romanian)",
	"language_selection_bulgarian": "Български (Bulgarian)",
	"language_selection_pirate": "Pirate (Yarr!)",
	"language_selection_turkish": "Türkçe (Turkish)",
	"language_selection_ukrainian": "Українська (Ukrainian)",
	"language_selection_vietnamese": "Tiếng Việt (Vietnamese)",
	"language_selection_arabic": "العربية (Arabic)",
	"language_selection_spanish_mexican": "Español - Mexicano (Spanish - Mexican)",
	"language_selection_latam": "Español - Latinoamérica (Spanish - Latin America)",


	"Bbcode_Originally_Posted_By": "Originally posted by",
	"Bbcode_No_Match": "No matches to supported BBCode",

	"Editor_Bold": "Bold",
	"Editor_Underline": "Underline",
	"Editor_Italics": "Italics",
	"Editor_StrikeThrough": "Strikethrough",
	"Editor_Link": "Insert Link",
	"Editor_Unordered": "Unordered List",
	"Editor_Ordered": "Ordered List",
	"Editor_Header": "Header",
	"Editor_Emoticon": "Insert Emoticon",

	"EventEditor_ConvertHTML_Error": "Failed Converting HTML",
	"EventEditor_ConvertHTML_Error_Desc": "Failed Converting HTML to BBcode with the following error: '%1$s'",
	"EventEditor_InsertLinkURL": "Insert URL",
	"EventEditor_FormattingHelp_GetHelpLink": "Formatting help",
	"EventEditor_ImportHTML": "Import HTML",
	"EventEditor_ImportFromHTML": "Import from HTML",
	"EventEditor_ImportFromHTML_ttip": "Import from HTML. Will automatically convert your html to Steam formatting tags.",
	"EventEditor_ImportFromHTML_Instruction": "Type or paste HTML below.",
	"EventEditor_ImportFromHTML_PreserveNewlines": "Preserve newlines",
	"EventEditor_ImportFromHTML_PreserveNewlines_Hint": "In HTML, newlines usually have no effect, but in BBCode they will show as blank lines.  If you used <p> or <br> tags, leave this unchecked.  If you usually use blog software that automatically adds <br> tags for newlines, you will probably want to check this box.",
	"EventEditor_ImportFromHTML_ConvertToBBCode": "Convert to BBCode:",
	"EventEditor_ImportFromHTML_ConversionInProgress": "Conversion in progress. Please do not close dialog.",
	"EventEditor_ImportFromHTML_ConvertFinished": "Conversion Finished. You can now safely close this dialog.",
	"EventEditor_InsertYouTube": "Insert YouTube™ Video",
	"EventEditor_InsertYouTube_Left": "Left-aligned",
	"EventEditor_InsertYouTube_Right": "Right-aligned",
	"EventEditor_InsertYouTube_Full": "Full width",
	"EventEditor_InsertYouTube_URL": "Full URL",
	"EventEditor_InsertYouTube_Position": "Position",
	"EventEditor_InsertYouTube_Placholder": "Enter YouTube™ URL",
	"EventEditor_InsertYouTube_NoURL": "Please enter a valid YouTube™ URL.",
	"EventEditor_InsertYouTube_Summary": "Descriptive summary version",
	"EventEditor_InsertImage": "Insert an image from the web",
	"EventEditor_InsertImage_Title": "Insert Image",
	"EventEditor_InsertImage_Desc": "Enter an URL for an image (such as .jpg .gif or .png) to include that image in your post.",
	"EventEditor_InsertImage_URL": "Image URL",
	"EventEditor_InsertImage_Placeholder": "Enter a valid URL",
	"EventEditor_InsertImage_Anchor": "Optional: URL to open when image clicked",
	"EventEditor_LinkDescription": "Text To Display",
	"EventEditor_LinkURL": "URL",
	"EventEditor_YouTubeVideoTitle": "YouTube™ Video: %1$s",
	"EventEditor_YouTubeVideoViews": "Views: %1$s",
	"EventEditor_Author": "By: %1$s",
	"EventEditor_Comments": "Comments",
	"EventEditor_UpVotes": "Up Votes",
	"EventEditor_DownVotes": "Down Votes",

	"Error_Message": "Error Message",
	"Warning_Message": "Warning Message",
	"Informational_Message": "Informational Message",
	"Error_Description": "Error (code: %1$s) occured with details: (%2$s)",
	"Error_FailureNotice": "Failure",
	"Error_GenericFailureDescription": "Sorry, that didn't work.",

	"Image_ErrorTitle": "Failed to Load Image '%1$s', possible issues include:",
	"Image_Error_msg1": "Check that the path to the image is correct.",
	"Image_Error_msg2": "Check if server hosting the image supports anonymous access. The browser console may indicate an error related Access-Control-Allow-Origin if it doesn't.",
	"Image_Error_suggestion": "You can always upload the image to Steam to host the content for free.",

	"Platform_Hint_Mobile": "on Mobile Device",
	"Platform_Hint_BigPicture": "in Big Picture",
	"Platform_Hint_VR": "in Virtual Reality",

	"Hover_SteamLevel": "Steam Level",
	"Hover_BadgeXP": "%1$s XP",

	"PersonaStateOffline": "Offline",
	"PersonaStateAway": "Away",
	"PersonaStateOnline": "Online",
	"PersonaStateBlocked": "Blocked",
	"PersonaStateInGame": "In-Game",
	"PersonaStateBusy": "Busy",
	"PersonaStateSnooze": "Away",
	"PersonaStateInNonSteamGame": "In non-Steam game",
	"PersonaStateWatchingBroadcast": "Watching broadcast:",
	"PersonaStateLookingToTrade": "Looking to Trade",
	"PersonaStateLookingToPlay": "Looking to Play",
	"PersonaStateLastSeen": "Last online %1$s",
	"PersonaStateLastSeen_JustNow": "Last online just now",

	"User_WantsToPlay": "Join",
	"User_ToggleDoNotDisturb": "Do Not Disturb",
	"User_GameInfoHidden": "Your game status is hidden from friends because of your privacy settings",
	"User_LimitedAccount": "Your account does not meet the requirements to use this feature. %1$s for more information.",
	"User_LimitedAccount_UrlInfo": "Visit Steam Support",

	"isNickname": "Your nickname for this friend",
	"Friend_Menu_NotAFriendLabel": "Not Friends",
	"Friend_Menu_NotAFriendRequesting": "Requesting to be Friends",

	"DASHPlayerStats_BytesReceived": "Bytes Received:",
	"DASHPlayerStats_BufferingResolution": "Buffering Resolution:",
	"DASHPlayerStats_PlaybackResolution": "Playback Resolution:",
	"DASHPlayerStats_HtmlResolution": "Display Resolution:",
	"DASHPlayerStats_DroppedFrames": "Dropped Frames:",
	"DASHPlayerStats_VideoBuffered": "Video Buffered:",
	"DASHPlayerStats_AudioBuffered": "Audio Buffered:",
	"DASHPlayerStats_BandwidthRequired": "Bandwidth Required (Mbps):",
	"DASHPlayerStats_BandwidthVideo": "Bandwidth Video (Mbps):",
	"DASHPlayerStats_BandwidthNums": "Bandwidth Min/Max/Avg (Mbps):",
	"DASHPlayerStats_DownloadNums": "DL Times Min/Max/Avg (Sec):",
	"DASHPlayerStats_ContentServer": "Host:",
	"DASHPlayerStats_ActiveDownloads": "Active Downloads:",
	"DASHPlayerStats_StallEvents": "Stall Events:",
	"DASHPlayerStats_FailedDownloads": "Failed Download Events:",
	"DASHPlayerStats_VideoDownloadProgress": "Video Download Progress:",
	"DASHPlayerStats_TimeToFirstFrame": "Time to First Frame MS:",
	"DASHPlayerStats_DroppingFrames": "Persistent Frame Drops Detected:",
	"DASHPlayerStats_CurrentFPS": "Current FPS:",
	"DASHPlayerStats_Tracking": "Gathering Data...",
	"DASHPlayerStats_PlaybackRate": "Playback Speed:",
	"DASHPlayerStats_VideoBufferRange": "Video Buffer %1$s:",
	"DASHPlayerStats_AudioBufferRange": "Audio Buffer %1$s:",
	"DASHPlayerStats_VideoNoRangeInformation": "No Buffered Video Segments",
	"DASHPlayerStats_AudioNoRangeInformation": "No Buffered Audio Segments",
	"DASHPlayerControls_GoLive": "Go Live",
	"DASHPlayerControls_IsLive": "Live",
	"DASHPlayerControls_ClickToPlay": "Click to Play",
	"DASHPlayerControls_IsReplay": "RE-BROADCAST",
	"DASHPlayerControls_Start": "Start",
	"DASHPlayerControls_End": "End",

	"Played_Minutes" : "%1$s minutes",
	"Played_Hours": "%1$s hours",

	"WriteReview_Dialog_PostReview":	"Post review",
	"WriteReview_Dialog_ReviseReview":	"Revise review",
	"WriteReview_Dialog_Title":	"Review",
	"WriteReview_Dialog_Playtime":	"You've played for %1$s",
	"WriteReview_Dialog_Playtime_Software":	"You've used this title for %1$s",
	"WriteReview_Dialog_Playtime_Revise":	"You've played an additional %1$s",
	"WriteReview_Dialog_RecommendGame":	"Would you recommend this game to other players?",
	"WriteReview_Dialog_RecommendGame_Software":	"Would you recommend this software to other players?",
	"WriteReview_Dialog_RecommendGame_Revise":	"Would you like to revise your review?",
	"WriteReview_Dialog_GetHelp_Btn":	"Get help with your purchase",
	"WriteReview_Dialog_Visibility":	"Visibility:",
	"WriteReview_Dialog_Public":	"Public",
	"WriteReview_Dialog_Friends":	"Friends Only",
	"WriteReview_Dialog_Yes":	"Yes",
	"WriteReview_Dialog_No":	"No",
	"WriteReview_Dialog_GetSupport_Btn":	"Get help with your purchase",
	"WriteReview_Dialog_GetSupport_Desc":	"Get technical advice, official customer support, or request a refund.",
	"WriteReview_Dialog_AddReview_Btn":	"Post a review",
	"WriteReview_Dialog_AddReview_Desc":	"Share your thoughts with other players.",
	"WriteReview_Dialog_AddReview_Header":	"Would you like to post a review?",
	"WriteReview_Dialog_ReviewInstructions_Link":	"Rules and Guidelines",
	"WriteReview_Dialog_ReviewInstructions":	"Please describe what you liked or disliked about this product and whether you recommend it to others. Please remember to be polite and follow the %1$s. A description is required to post your recommendation.",
	"WriteReview_Dialog_AllowComments":	"Allow comments",
	"WriteReview_Dialog_FreeDisclaimer":	"Check this box if you received this product for free",
	"WriteReview_Dialog_FreeDisclaimer_Tooltip":	"Check this box if you were given this product for free. Will show Product received for free alongside your review. If you received additional compensation for the review of this game, you must disclose that in the text of your review.",
	"WriteReview_Dialog_FormattingHelp":	"Formatting Help",
	"WriteReview_Dialog_GenericError":	"We encountered a problem while posting your review. Please try again later.",
	"WriteReview_Dialog_NoTextError": "Please describe what you liked or disliked about this product.",
	"WriteReview_Dialog_Delay": "Maybe Later",

	"Broadcast_View_Stack_H":		"Horizontal View",
	"Broadcast_View_Stack_V":		"Vertical View",
	"Broadcast_View_Theater":		"Theater Mode",
	"Broadcast_View_Fullscreen":		"Fullscreen",
	"Broadcast_View_HideChat":		"Hide Chat",
	"Broadcast_View_ShowBothChats":		"Show Both Chats",
	"Broadcast_View_ShowSingleChats":	"Show Single Chat",
	"Broadcast_View_ShowChat":		"Show Chat",
	"Broadcast_Store_FreeToPlay": "Free to Play",

	"PartnerEvent_1":		"Other Event",
	"PartnerEvent_2":		"Game Event",
	"PartnerEvent_3":		"Party Event",
	"PartnerEvent_4":		"Meeting Event",
	"PartnerEvent_5":		"Special Cause",
	"PartnerEvent_6":		"Music and Arts Event",
	"PartnerEvent_7":		"Sports Event",
	"PartnerEvent_8":		"Live Trip Event",
	"PartnerEvent_9":		"Chat",
	"PartnerEvent_10":		"Game Release",
	"PartnerEvent_11":		"Live-Stream / Broadcast",
	"PartnerEvent_12":		"Small Updates/Patches",
	"PartnerEvent_13":		"Update",
	"PartnerEvent_14":		"Major Update",
	"PartnerEvent_15":		"DLC Release",
	"PartnerEvent_16":		"Upcoming Release",
	"PartnerEvent_17":		"ESport Tournament Broadcast",
	"PartnerEvent_18":		"Dev Stream Broadcast",
	"PartnerEvent_19":		"Famous Broadcast",
	"PartnerEvent_20":		"Game Sales",
	"PartnerEvent_21":		"In-game Item Discounts",
	"PartnerEvent_22":		"Bonus XP",
	"PartnerEvent_23":		"Loot Event",
	"PartnerEvent_24":		"Perks Event",
	"PartnerEvent_25":		"Challenge Event",
	"PartnerEvent_26":		"Contest Event",
	"PartnerEvent_27":		"IRL Event",
	"PartnerEvent_28":		"News",
	"PartnerEvent_29":		"Beta Release",
	"PartnerEvent_30":		"In-Game Content Updated",
	"PartnerEvent_31":		"Free Trial",
	"PartnerEvent_32":		"New DLC or Season Launch",
	"PartnerEvent_33":		"Season Update",
	"PartnerEvent_34":		"Cross Promotion",
	"PartnerEvent_35":		"General In-Game Event",
	"PartnerEvent_Other":	"Other Event",

	"SocialMedia_Type_ShortName_1": "Steam",
	"SocialMedia_Type_ShortName_2": "Google",
	"SocialMedia_Type_ShortName_3": "Facebook",
	"SocialMedia_Type_ShortName_4": "Twitter",
	"SocialMedia_Type_ShortName_5": "Twitch",
	"SocialMedia_Type_ShortName_6": "YouTube",
	"SocialMedia_Type_ShortName_7": "Facebook",

	"MobileLogin_NoSteamAccount": "Don't have a Steam account?",
	"MobileLogin_CreateAccount": "Create a Free Account",
	"MobileLogin_ForgotPassword": "Forgot your account name or password?",
	"MobileLogin_RefreshCaptcha": "Refresh",
	"MobileLogin_SignIn": "Sign in",
	"MobileLogin_SigningIn": "Signing in",
	"MobileLogin_AccountName": "Steam Account Name",
	"MobileLogin_Password": "Password",
	"MobileLogin_CaptchaVerification": "Verification",
	"MobileLogin_Enter2FA": "Enter the code generated on the Steam Guard section of your Steam Mobile App.",
	"MobileLogin_Enter2FAHelp": "I cannot access my Steam Guard code",
	"MobileLogin_EnterSteamguard": "I did not receive a Steam Guard e-mail",
	"MobileLogin_SteamguardCode": "Steam Guard Code",
	"MobileLogin_SteamguardSubmit": "Submit & Sign In",
	"MobileLogin_SentSteamguard_1": "We sent a message to your",
	"MobileLogin_SentSteamguard_2": "e-mail. Enter the Steam Guard code provided.",
	"MobileLogin_IncorrectSteamGuard": "The entered Steam Guard code is incorrect. Please check the code and try again.",

	"MobileLogin_Error_RateLimitExceeded": "There have been too many login failures from your network in a short time period. Please wait and try again later.",

	"Login_SignIn": "Sign in",
	"Login_SigningIn": "Signing in",
	"Login_AccountName": "Steam Account Name",
	"Login_Password": "Password",
	"Login_RememberMe": "Remember me on this computer",
	"Login_ForgotPassword": "Forgot your account name or password?",
	"Login_NoSteamAccount": "Don't have a Steam account?",
	"Login_CreateAccount": "Create a Free Account",
	"Login_CaptchaVerification": "Please verify your humanity by re-entering the characters in the captcha.",
	"Login_RefreshCaptcha": "Refresh",
	"Login_Enter2FA": "Enter the code generated on the Steam Guard section of your Steam Mobile App.",
	"Login_Enter2FAHelp": "I cannot access my Steam Guard code",
	"Login_EnterSteamguard": "I did not receive a Steam Guard e-mail",
	"Login_SteamguardSubmit": "Submit & Sign In",
	"Login_SentSteamguard": "We sent a message to your %1$s e-mail. Enter the Steam Guard code provided.",
	"Login_SignOut": "Sign out",

	"Emoticon_Search": "Search Emoticons",
	"Chat_Settings_Error_ChatFileTooLarge": "%1$s is too large (10MB maximum).",
	"Chat_Settings_Error_ChatFileTypeNotSupported": "Cannot upload %1$s.  Only jpg, png, gif, webm, mpg, and ogv file types are supported.",
	"ConnectionTrouble_FailedToConnect": "Failed to connect to Steam",
	"Chat_Upload_ErrorCloud": "Failed to upload image data to cloud server.",
	"Chat_Settings_Error_ServerError": "A server error occurred",
	"Broadcast_ViewerCount":		"%1$s viewers",
	"Broadcast_VideoContext_ToggleStats": "Toggle technical stats",
	"Broadcast_VideoContext_OpenStore": "Visit Store",
	"Broadcast_None": "None",

	"BroadcastWatch_MinBrowser": "Your web browser does not support the minimum set of features required to watch this broadcast",
	"BroadcastWatch_RequestFailed": "Failed to load this broadcast",
	"BroadcastWatch_NotAvailable": "This broadcaster is offline",
	"BroadcastWatch_WaitingForResponse": "Waiting for approval to watch",
	"BroadcastWatch_WaitingForStart": "This broadcast is starting",
	"BroadcastWatch_WaitingForReconnect": "Reconnecting to this broadcast",
	"BroadcastWatch_ServerLoad": "Steam is experiencing high broadcast load and is currently unable to reserve a server spot to start this broadcast. Please try again in a few minutes.",
	"BroadcastWatch_SystemNotSupported": "Steam Broadcasting is not currently supported on this broadcaster's system",
	"BroadcastWatch_UserRestricted": "This broadcaster is currently restricted from broadcasting on Steam",
	"BroadcastWatch_PoorUploadQuality": "This broadcaster is currently unable to maintain a stable broadcast connection to Steam",

	"BroadcastChat_Reconnected": "Reconnected to chat",
	"BroadcastChat_UnableToJoinChat": "Unable to join chat",
	"BroadcastChat_NeverTell": "Never tell your password to anyone",
	"BroadcastChat_EnterResponse": "Type to chat",
	"BroadcastChat_InsertEmoticon": "Insert Emoticon",
	"BroadcastChat_Send": "Send",
	"BroadcastChat_UserJoined": "%1$s joined the chat",
	"BroadcastChat_UserLeft": "%1$s left the chat",
	"BroadcastChat_UserMuted": "%1$s has been muted in this chatroom",
	"BroadcastChat_UserMutedLocal": "%1$s has been muted",
	"BroadcastChat_UserUnmutedLocal": "%1$s has been unmuted",
	"BroadcastChat_UserMuteFailed": "Failed to mute %1$s. Please try again.",
	"BroadcastChat_RemoveMessagesFailed": "Failed to remove messages for %1$s. Please try again.",
	"BroadcastChat_UserUnmuteFailed": "Failed to unmute %1$s. Please try again.",
	"BroadcastChat_YouMuted": "You have been muted and cannot post messages to this chat",
	"BroadcastChat_FailedToSendMsg": "Failed to send chat message: %1$s",
	"BroadcastChat_Cooldown": "You are sending messages too fast, try again in %1$s seconds.",
	"BroadcastChat_Mute": "Mute",
	"BroadcastChat_Unmute": "Unmute",
	"BroadcastChat_MuteLocal": "Mute Locally",
	"BroadcastChat_UnmuteLocal": "Unmute Locally",
	"BroadcastChat_Login": "Login to join chat",
	"BroadcastChat_LimitedUser": "Limited chat access",
	"BroadcastChat_RemoveMessages": "Remove this user's messages",
	"BroadcastChat_Blocked": "Only game owners are allowed to send chat messages during this broadcast.",
	"BroadcastChat_half_Mute": "Mute user for 12 hours",
	"BroadcastChat_day_Mute": "Mute user for a day",
	"BroadcastChat_week_Mute": "Mute user for a week",
	"BroadcastChat_perm_Mute": "Mute user permanently",
	"BroadcastChat_half_Shadow": "Shadow-Mute user for 12 hours",
	"BroadcastChat_day_Shadow": "Shadow-Mute user for a day",
	"BroadcastChat_week_Shadow": "Shadow-Mute user for a week",
	"BroadcastChat_perm_Shadow": "Shadow-Mute user for permanently",
	"BroadcastChat_Add_Moderator": "Make this user a Moderator",
	"BroadcastChat_Remove_Moderator": "Remove Moderator status for user",
	"BroadcastChat_Change_Moderator_Title": "Change Moderator status for user",
	"BroadcastChat_Change_Add_Confirm": "Are you sure you want to add the following user as a moderator? They will be able to mute other users on the broadcast chat.",
	"BroadcastChat_Change_Remove_Confirm": "Are you sure you want to remove the following user as a moderator?",
	"BroadcastChat_Tooltip_Show_Chat_Viewers": "Show a list of people who are currently in the chat window.",
	"BroadcastChat_Tooltip_Minimize_Chat": "Minimize the chat window",
	"BroadcastChat_Tooltip_Maximize_Chat": "Maximize the chat window",
	"BroadcastChat_Tooltip_Popout_Chat": "Pop-out the chat into a new window",
	"BroadcastChat_ChatOnly_Title": "Broadcast Chat Only",
	"BroadcastChat_DefaultMessage": "Welcome to the chat!",
	"BroadcastChat_Moderator": "Moderator",
	"BroadcastChat_Broadcaster": "Broadcaster",

	"ChatEntryButton_Submit": "Submit",
	"ChatEntryButton_Emoticon": "Emoticon Picker",
	"ChatEntryButton_Flair": "Flair Picker",
	"ChatEntryButton_SendEmbed": "Send Special",

	"Store_AddToCart": "Add to Cart",

	"home_page_live_broadcast": "Live",
	"StoreBroadcast_Hide_Tooltip": "Show/hide the live broadcast",
	"StoreBroadcast_Detault_popout_Title": "Now Broadcasting",
	"StoreBroadcast_close_broadcast_popup": "Closes broadcast popup. The pop-up will not re-open during this session.",
	"StoreBroadcast_Change_store_Broadcast_settings": "Change broadcast settings",
	"Broadcast_Embedded_viewer": "%1$s Viewer",
	"Broadcast_Embedded_viewer_Plural": "%1$s Viewers",
	"BroadcastWatch_View_Broadcast_Page": "View broadcast page",
	"Broadcast_Embed_Watch_SteamTV": "Watch on Steam.tv",
	"Broadcast_Embed_Watch_With_Frieds_SteamTV": "Watch and chat with Friends on Steam.tv",
	"sale_three_section_hide_chat": "Hide Chat",
	"sale_three_section_show_chat": "Show Chat",
	"btn_live_streams_all": "View all",

	"Broadcast_default_title_dev": "Now broadcasting: Watch the developer play",
	"Broadcast_default_title_community": "Now broadcasting: Watch the community play",
	"Broadcast_default_title_comp": "Now broadcasting: Watch this competitive match",
	"Broadcast_default_title_speed": "Now broadcasting: Watch this speedrun",

	"Sale_BundleSave": "Includes %1$s items.",
	"Sale_PackageSave": "Includes %1$s items.",
	"Sale_ShowContents": "Show contents",
	"Sale_ShowMore": "Show more",
	"Sale_OnWishlist": "On Wishlist",
	"Sale_InLibrary": "In Library",
	"Sale_HiddenItems": "%1$s item(s) are hidden due to %2$s",
	"Sale_StorePreferences": "your store preferences",
	"Sale_SeeAllSpecials": "See All Specials",
	"Sale_AddToWishlist": "Add to Wishlist",
	"Sale_Preferences": "Preferences",
	"Sale_default_label": "(no title)",
	"Sale_default_label_OnSale": "On Sale",
	"Sale_default_label_TopSellers": "Top Sellers",
	"Sale_default_label_FreeToPlay": "Free to Play",
	"Sale_default_label_HorrorGames": "Horror Games",
	"Sale_default_label_HorrorVR": "Horror VR",
	"Sale_default_label_HorrorFreeToPlay": "Horror Free to Play",
	"Sale_default_label_HalloweenEventsHorror": "Halloween Events in Horror Games",
	"Sale_default_label_HalloweenEventsNonHorror": "Halloween Events in Non-Horror Games",
	"Sale_default_label_MoreHalloweenEvents": "More Halloween Events",
	"Sale_default_label_MoreHalloweenEventsNonHorror": "More Halloween Events in Non-Horror Games",
	"Sale_default_label_NewAndUpcomingHorror": "New and Upcoming Horror",
	"Sale_default_label_RemotePlay_Together": "Play Together – With Remote Friends",
	"Sale_default_label_RemotePlay_Phone": "Play Anywhere - On your Phone",
	"Sale_default_label_RemotePlay_Tablet": "Play Anywhere - On your Tablet",
	"Sale_default_label_RemotePlay_TV": "Play Anywhere - On your TV",
	"Sale_default_label_OnYourWishlist": "On Your Wishlist",
	"Sale_default_label_RecommendedForYou": "Recommended For You",

	"SalePage_WatchForDrop_Minutes_Developer": "Watch the stream for %1$s minutes and get item drops from the developer when the event is over!",
	"SalePage_WatchForDrop_Minutes_CreatorNamed": "Watch the stream for %1$s minutes and get item drops from %2$s when the event is over!",
	"SalePage_WatchForDrop_Hours_Developer": "Watch the stream for %1$s hours and get item drops from the developer when the event is over!",
	"SalePage_WatchForDrop_Hours_CreatorNamed": "Watch the stream for %1$s hours and get item drops from %2$s when the event is over!",
	"SalePage_WatchForDrop_LearnMore": "Learn more about the drops here.",

	"Steam_Settings_Compat_Launch_Prefix":	"Runs on this computer via",
	"Steam_Settings_Compat_Launch_Name":	"Steam Play.",
	"Steam_Settings_Compat_Launch_Forced":	"selected by you for this title.",
	"Steam_Settings_Compat_Launch_Wildcard":	"selected by you for all titles.",
	"Steam_Settings_Compat_Launch_Whitelisted":	"selected by Valve testing.",

	"shared_dummy": "dont translate"
}
