{
	"AppType_0": "Invalid",
	"AppType_1": "Games",
	"AppType_2": "Software",
	"AppType_4": "Tools",
	"AppType_20": "DLC",
	"AppType_800": "Videos",
	"AppType_2000": "Music",

	"AppType_Singular_0": "Invalid",
	"AppType_Singular_1": "game",
	"AppType_Singular_2": "application",
	"AppType_Singular_4": "tool",
	"AppType_Singular_20": "DLC",
	"AppType_Singular_800": "video",
	"AppType_Singular_2000": "music",
	"AppType_Singular_8000": "comic",
	"AppType_Singular_40000000": "shortcut",

	"FilterEdit_SavedFilters": "Saved Filters",
	"FilterEdit_FirstColumnHeader": "Filter Type",
	"FilterEdit_Customize": "Customize",
	"FilterEdit_SearchModeHeader": "Advanced Filters",
	"FilterEdit_CollectionModeHeader" : "Edit Collection",

	"FilterEdit_SaveCollectionNameInputPrompt": "enter a name",
	"FilterEdit_SaveOverwrite": "Collection \"%1$s\" already exists. Overwrite?",
	"FilterEdit_SaveCollection": "Save as Collection",
	"FilterEdit_SaveCollectionVerbose": "Save this collection so that you can use it again in the future. You can always edit, rename, or delete a collection in the future, or drag items in or out of it.",
	"FilterEdit_SearchPrompt": "Search by Name",
	"FilterEdit_ClearSearch": "Exit Search",
	"FilterEdit_SearchResults": "Search results",
	"FilterEdit_CollectionsHiddenPromptTitle": "Collections are hidden",
	"FilterEdit_CollectionsHiddenPrompt": "Would you like to change the game list view so that the new collection is visible?",
	"FilterEdit_AcceptGameListViewChange": "Yes, show collections",
	"FilterEdit_RejectGameListViewChange": "No, leave view unchanged",

	"FilterEdit_FilterTags": "Filter Tags",

	"FilterEdit_AcceptsAny": "Any",
	"FilterEdit_AcceptsAnyOfThese": "Any of these",
	"FilterEdit_NeedsAllOfThese": "All of these",
	"FilterEdit_AcceptsBoth": "%1$s or %2$s",
	"FilterEdit_NeedsBoth": "%1$s and %2$s",
	"FilterEdit_AcceptsAnyWithNumberOfOthers": "%1$s or %2$s others",
	"FilterEdit_NeedsAllWithNumberOfOthers": "%1$s and %2$s others",

	"FilterCategory_1": "Status",
	"FilterCategory_Features": "FEATURE",
	"FilterCategory_3": "Category",
	"FilterCategory_4": "Store Tag",
	"FilterCategory_Type": "TYPE",
	"FilterCategory_Genre": "GENRE",
	"FilterCategory_PlayState": "STATE",

	"FilterElement_All": "All",
	"FilterElement_VR": "VR",
	"FilterElement_Recent": "Recent",
	"FilterElement_Installed": "Installed",
	"FilterElement_ReadyToPlay": "Ready to Play",
	"FilterElement_Favorites": "Favorites",
	"FilterElement_PlayedPreviously": "Played",
	"FilterElement_Unplayed": "Unplayed",
	"FilterElement_Hidden": "Hidden",
	"FilterElement_FullControllerSupport": "Full controller support",
	"FilterElement_PartialControllerSupport": "Partial controller support",
	"FilterElement_VRSupported": "VR supported",
	"FilterElement_TradingCards": "Trading cards",
	"FilterElement_Workshop": "Workshop",
	"FilterElement_Achievements": "Achievements",
	"FilterElement_SinglePlayer": "Single player",
	"FilterElement_MultiPlayer": "Multiplayer",
	"FilterElement_CoOp": "Cooperative",
	"FilterElement_LocalMultiPlayer": "Local multiplayer",
	"FilterElement_GenreAction": "Action",
	"FilterElement_GenreAdventure": "Adventure",
	"FilterElement_GenreCasual": "Casual",
	"FilterElement_GenreIndie": "Indie",
	"FilterElement_GenreMMO": "Massively multiplayer",
	"FilterElement_GenreRacing": "Racing",
	"FilterElement_GenreRPG": "RPG",
	"FilterElement_GenreSimulation": "Simulation",
	"FilterElement_GenreSports": "Sports",
	"FilterElement_GenreStrategy": "Strategy",

	"LibraryFilter_All": "All",
	"LibraryFilter_Custom": "Custom",
	"LibraryFilter_Installed": "Installed",
	"LibraryFilter_Favorites": "Favorites",
	"LibraryFilter_Hidden": "Hidden",
	"LibraryFilter_FullController": "Full controller support",
	"LibraryFilter_VR": "VR Supported",

	"CollectionView_EmptyReadOnlyCollection": "Nothing to see here",
	"CollectionView_EmptyCollection": "Drag games here to build this collection",
	"CollectionView_MissingCollection": "No collection found.",

	"LibraryFilter_All_OfType": "All %1$s",
	"LibraryFilter_Custom_OfType": "Custom Filtered %1$s",
	"LibraryFilter_Installed_OfType": "Installed %1$s",
	"LibraryFilter_Favorites_OfType": "Favorite %1$s",
	"LibraryFilter_Hidden_OfType": "Hidden %1$s",
	"LibraryFilter_FullController_OfType": "Full controller support",
	"LibraryFilter_VR_OfType": "VR Supported",
	"Filter_Tag": "%1$s Tagged %2$s",
	"Filter_Text": "%1$s ('%2$s')",

	"GameList_Home" : "Library Home",
	"GameList_Search" : "Search",
	"GameList_Filter" : "Filter",
	"GameList_Category_Uncategorized" : "Uncategorized",
	"GameList_Category_Favorites": "Favorites",
	"GameList_Category_Hidden": "Hidden",
	"GameList_Category_YourCollections": "Your Collections",
	"GameList_Category_SharedLibraries": "Shared Libraries",
	"GameList_SectionHeader_SearchResults": "Results from Search and Filter",
	"GameList_SectionHeader_AddedManually": "Manually Added",
	"GameList_SectionHeader_RemovedManually": "Manually Removed",
	"GameList_SectionHeader_NoRecentActivity": "Earlier",

	"CollectionAction_ViewOnlyThis" : "View just this collection",
	"CollectionAction_Collapse" : "Collapse",
	"CollectionAction_Expand" : "Expand",
	"CollectionAction_Manage" : "Manage",
	"CollectionAction_Edit" : "Edit...",
	"CollectionAction_Delete" : "Delete...",
	"CollectionAction_DeleteDialog" : "Confirm Delete",
	"CollectionAction_ConfirmDelete": "Are you sure you want to permanently delete collection \"%1$s\"?",
	"CollectionAction_SaveFailed": "Could not save collection \"%1$s\"",
	"CollectionAction_CannotOverwrite": "Cannot overwrite collection \"%1$s\". Please choose a new name.",
	"CollectionAction_DeleteFailed": "Could not delete collection \"%1$s\"",

	"LibraryHome_FriendsActivity": "FRIENDS ACTIVITY",
	"LibraryHome_RecentGames": "RECENT GAMES",
	"LibraryHome_NewUpdates": "YOUR GAME UPDATES",
	"LibraryHome_YourCollection": "YOUR COMPLETE COLLECTION",

	"Library_SortCollectionBy": "SORT BY:",
	"Library_SortByFavoritesFirst": "Favorites First",
	"Library_SortByAlphabetical": "Alphabetical",
	"Library_SortByPctAchievementsComplete": "% of Achievements Complete",
	"Library_SortByLastUpdated": "Last Updated",
	"Library_SortByHoursPlayed": "Hours Played",
	"Library_SortByLastPlayed": "Last Played",
	"Library_SortByReleaseDate": "Release Date",
	"Library_SortByAddedToLibrary": "Date Added to Library",
	"Library_SortBySizeOnDisk": "Size on Disk",
	"Library_SortByMetacriticScore": "Metacritic Score",

	"Library_InstalledOnlyCheck": "INSTALLED ONLY",
	"Library_CoverSize": "COVER SIZE",

	"GridSection_Favorites": "Favorites",
	"GridSection_EverythingElse": "Everything Else",

	"GridSection_Over100Hours": "Over 100 Hours",
	"GridSection_Over60Hours": "Over 60 Hours",
	"GridSection_Over40Hours": "Over 40 Hours",
	"GridSection_Over20Hours": "Over 20 Hours",
	"GridSection_Over10Hours": "Over 10 Hours",
	"GridSection_Over1Hour": "Over 1 Hour",
	"GridSection_LessThan1Hour": "Under 1 Hour",

	"GridSection_Over90Metacritic": "Over 90",
	"GridSection_Over80Metacritic": "Over 80",
	"GridSection_Over70Metacritic": "Over 70",
	"GridSection_Over50Metacritic": "Over 50",
	"GridSection_EverythingElseMetacritic": "Everything Else",

	"GridSection_UnknownReleaseDate": "Unknown",

	"GridSection_GreaterThan100GB": "Greater than 100GB",
	"GridSection_GreaterThan50GB": "Greater than 50GB",
	"GridSection_GreaterThan20GB": "Greater than 20GB",
	"GridSection_LessThan20GB": "Less than 20GB",
	"GridSection_NoSizeOnDisk": "No Size",
	"GridSection_NotInstalled": "Not Installed",

	"GridSection_MoreThan10YearsAgo": "10+ years ago",
	"GridSection_Never": "Never",

	"AppDetails_SectionTitle_Activity": "Activity",
	"AppDetails_SectionTitle_Friends": "Play Now With",
	"AppDetails_SectionTitle_Achievements": "Achievements",
	"AppDetails_SectionTitle_TradingCards": "Trading Cards",
	"AppDetails_SectionTitle_Screenshots": "Screenshots",
	"AppDetails_SectionTitle_Updates": "Recent Events and Updates",
	"AppDetails_SectionTitle_DLC": "DLC",
	"AppDetails_SectionTitle_LastPlayed": "Last Played",
	"AppDetails_SectionTitle_PlayTime": "Play Time",
	"AppDetails_SectionTitle_Workshop": "Workshop",

	"AppDetails_Links_Store": "Store Page",
	"AppDetails_Links_Community": "Community Hub",

	"Bbcode_Originally_Posted_By": "Originally posted by",

	"GameAction_Stop": "Stop",
	"GameAction_Cancel": "Cancel",
	"GameAction_Install": "Install",
	"GameAction_Uninstall": "Uninstall",
	"GameAction_Play": "Play",
	"GameAction_Launch": "Launch",
	"GameAction_PreLoad": "Preload",
	"GameAction_Update": "Update",
	"GameAction_Download": "Download",
	"GameAction_Pause": "Pause",
	"GameAction_BorrowApp": "Borrow",
	"GameAction_PurchaseApp": "Purchase",
	"GameAction_GameProperties": "Properties...",
	"GameAction_AddToFavorites": "Add to Favorites",
	"GameAction_RemoveFromFavorites": "Remove from Favorites",
	"GameAction_AddToHidden": "Hide this game",
	"GameAction_RemoveFromHidden": "Remove from Hidden",
	"GameAction_AddToNewCollection": "new collection...",
	"GameAction_NewCollectionDialogTitle": "New Collection",
	"GameAction_AddToFamilyGames": "Add to Family Games",
	"GameAction_RemoveFromFamilyGames": "Remove from Family Games",
	"GameAction_RemoveShortcut": "Delete Shortcut",
	"GameAction_Manage": "Manage",
	"GameAction_AddToCollection": "Add to",
	"GameAction_RemoveFromCollection": "Remove from",
	"GameAction_RemoveAppFromCollectionLong": "Drag here to remove %1$s from collection %2$s",
	"GameAction_CreateDesktopShortcut": "Add Desktop Shortcut",
	"GameAction_BackUpFiles": "Back Up Game Files...",

	"DisplayStatus_Launching": "Launching",
	"DisplayStatus_Uninstalling": "Uninstalling",
	"DisplayStatus_Installing": "Installing",
	"DisplayStatus_Running": "Running",
	"DisplayStatus_Validating": "Validating",
	"DisplayStatus_Updating": "Updating",
	"DisplayStatus_Downloading": "Downloading",
	"DisplayStatus_Synchronizing": "Synchronizing with Steam Cloud",
	"DisplayStatus_ReadyToInstall": "Ready to Install",
	"DisplayStatus_ReadyToPreload": "Ready to Preload",
	"DisplayStatus_ReadyToLaunch": "Ready to Launch",
	"DisplayStatus_RegionRestricted": "Unavailable in current region",
	"DisplayStatus_PresaleOnly": "Game is not released yet",
	"DisplayStatus_InvalidPlatform": "Available for",
	"DisplayStatus_ParentalBlocked": "Blocked by Steam Family View",
	"DisplayStatus_PreloadOnly": "Preload Period",
	"DisplayStatus_BorrowerLocked": "This library is not currently available for Family Sharing",
	"DisplayStatus_UpdatePaused": "Update Paused",
	"DisplayStatus_UpdateQueued": "Update Queued",
	"DisplayStatus_UpdateRequired": "Update Required",
	"DisplayStatus_UpdateDisabled": "Downloads are disabled because Steam is in Offline Mode. Go online to finish updating this game.",
	"DisplayStatus_DownloadPaused": "Download Paused",
	"DisplayStatus_DownloadQueued": "Download Queued",
	"DisplayStatus_DownloadRequired": "Download Required",
	"DisplayStatus_DownloadDisabled": "Downloads are disabled because Steam is in Offline Mode. Go online to finish downloading this game.",
	"DisplayStatus_LicensePending": "Your purchase has not yet completed.",
	"DisplayStatus_LicenseExpired": "License Expired",
	"DisplayStatus_AvailForFree": "Available for free",
	"DisplayStatus_AvailToBorrow": "Available to borrow",
	"DisplayStatus_AvailGuestPass": "Guest pass available",
	"DisplayStatus_Purchase": "Available to purchase",

	"DisplayStatus_Compact_Launching": "Launching",
	"DisplayStatus_Compact_Uninstalling": "Uninstalling",
	"DisplayStatus_Compact_Installing": "Installing",
	"DisplayStatus_Compact_Running": "Running",
	"DisplayStatus_Compact_Validating": "Validating",
	"DisplayStatus_Compact_Updating": "Updating",
	"DisplayStatus_Compact_Downloading": "Downloading",
	"DisplayStatus_Compact_Synchronizing": "Synchronizing with Steam Cloud",
	"DisplayStatus_Compact_ReadyToInstall": "Ready to Install",
	"DisplayStatus_Compact_ReadyToPreload": "Ready to Preload",
	"DisplayStatus_Compact_ReadyToLaunch": "Ready to Launch",
	"DisplayStatus_Compact_RegionRestricted": "Unavailable in this region",
	"DisplayStatus_Compact_PresaleOnly": "Game is not released yet",
	"DisplayStatus_Compact_InvalidPlatform": "Available for",
	"DisplayStatus_Compact_ParentalBlocked": "Blocked by Steam Family View",
	"DisplayStatus_Compact_PreloadOnly": "Preload Period",
	"DisplayStatus_Compact_BorrowerLocked": "Family Sharing not Available",
	"DisplayStatus_Compact_UpdatePaused": "Update Paused",
	"DisplayStatus_Compact_UpdateQueued": "Update Queued",
	"DisplayStatus_Compact_UpdateRequired": "Update Required",
	"DisplayStatus_Compact_UpdateDisabled": "Update disabled in Offline Mode.",
	"DisplayStatus_Compact_DownloadPaused": "Download Paused",
	"DisplayStatus_Compact_DownloadQueued": "Download Queued",
	"DisplayStatus_Compact_DownloadRequired": "Download Required",
	"DisplayStatus_Compact_DownloadDisabled": "Download disabled in Offline Mode.",
	"DisplayStatus_Compact_LicensePending": "Completing Purchase",
	"DisplayStatus_Compact_LicenseExpired": "License Expired",
	"DisplayStatus_Compact_AvailForFree": "Available for free",
	"DisplayStatus_Compact_AvailToBorrow": "Available to borrow",
	"DisplayStatus_Compact_AvailGuestPass": "Guest pass available",
	"DisplayStatus_Compact_Purchase": "Available to purchase",

	"Downloads_State_Bytes_Of_Bytes" : "%1$s of %2$s",
	"Downloads_State_None": "",
	"Downloads_State_Reconfiguring": "Resuming Download",
	"Downloads_State_Validating": "Validating Files",
	"Downloads_State_AddingFiles": "Copying Files",
	"Downloads_State_Preallocating": "Reserving Space",
	"Downloads_State_Downloading": "",
	"Downloads_State_Staging": "",
	"Downloads_State_Committing": "Finalizing",
	"Downloads_State_Verifying": "Verifying Download",
	"Downloads_State_Stopping" : "Stopping Download",
	"Downloads_State_Running" : "",
	"Downloads_State_SecondsRemaining" : "%1$s sec remaining",
	"Downloads_State_MinutesRemaining" : "%1$s min remaining",
	"Downloads_State_Calculating" : "Calculating...",

	"LaunchApp_Action_UpdatingAppInfo":	"Checking configuration",
	"LaunchApp_Action_ShowEula": "Showing EULA",
	"LaunchApp_Action_DownloadingDepots":	"Downloading content (%1$s%)",
	"LaunchApp_Action_DownloadingWorkshop":	"Downloading workshop (%1$s%)",
	"LaunchApp_Action_UpdatingDRM":	"Updating executable",
	"LaunchApp_Action_GettingLegacyKey": "Updating product key",
	"LaunchApp_Action_RunningInstallScript": "Running install script (%1$s)",
	"LaunchApp_Action_SynchronizingCloud":	"Synchronizing cloud",
	"LaunchApp_Action_VerifyingFiles":	"Verifying executable",
	"LaunchApp_Action_CreatingProcess":	"Launching executable",
	"LaunchApp_Action_WaitingGameWindow":	"Launching executable",
	"LaunchApp_Action_DelayLaunch":	"Delaying launch (%1$s%)",

	"AppDetails_TitleUpdatedSincePlayed": "This game has been updated since you last played",
	"AppDetails_TitleUpdatedSincePlayedLink": "Read about the changes",

	"AppDetails_BadgeLevel": "Level %1$s, XP: %2$s",
	"AppDetails_UnearnedBadgeXP": "%1$s XP",

	"AppDetails_Review_Time": "You wrote a review on %1$s",
	"AppDetails_Review_ViewOrEdit": "Edit my review",
	"AppDetails_Review_YourReview": "My Review",
	"AppDetails_Review_Ignore_Stale_Reviews": "Don't remind me to update this review.",
	"AppDetails_Review_Unignore_Stale_Reviews": "Allow old review highlight for this game.",

	"AppDetails_Review_RecommendGame": "Would you recommend this game?",
	"AppDetails_Review_PlayedForTime": "You've played for %1$s",
	"AppDetails_Review_RecommendGameButton_Yes": "Yes",
	"AppDetails_Review_RecommendGameButton_No": "No",
	"AppDetails_Review_PlaytimeAtReview": "%1$s played at review time",
	"AppDetails_Review_NotRecommended": "Not Recommended",
	"AppDetails_Review_Recommended": "Recommended",
	"AppDetails_Review_AdditionalPlaytime": "You've played an additional %1$s.",
	"AppDetails_Review_ChangedYourMind": "Have you changed your mind?",
	"AppDetails_Review_IHaveNotChangedMyMind": "No I have not",

	"OverflowBox_Action_Collapse" : "See less",
	"OverflowBox_Action_Expand" : "Read more",

	"AppDetails_FriendsInGameNow": "%1$s friend is playing right now",
	"AppDetails_FriendsInGameNow_Plural": "%1$s friends are playing right now",
	"AppDetails_FriendsPlayedRecently": "%1$s friend has played recently",
	"AppDetails_FriendsPlayedRecently_Plural": "%1$s friends have played recently",
	"AppDetails_FriendsPlayed": "%1$s friend has played previously",
	"AppDetails_FriendsPlayed_Plural": "%1$s friends have played previously",
	"AppDetails_FriendsWishlisted": "%1$s friend has %2$s on their wishlist",
	"AppDetails_FriendsWishlisted_Plural": "%1$s friends have %2$s on their wishlist",
	"AppDetails_Friends_ViewAll": "View all friends who play",
	"AppDetails_GameInfo": "Game Info",
	"AppDetails_Publisher": "Publisher:",
	"AppDetails_Developer": "Developer:",
	"AppDetails_Franchise": "Franchise:",
	"AppDetails_ReleaseDate": "Release Date:",
	"AppDetails_OriginalReleaseDate": "Original Release Date:",
	"AppDetails_Feature_SinglePlayer": "Single-Player",
	"AppDetails_Feature_MultiPlayer": "Multi-Player",
	"AppDetails_Feature_SteamAchievements": "Achievements",
	"AppDetails_Feature_SteamCloud": "Cloud Saves",
	"AppDetails_Feature_FullController": "Full Controller Support",
	"AppDetails_Feature_PartialController": "Partial Controller Support",
	"AppDetails_Feature_SteamWorkshop": "Steam Workshop",

	"AppDetails_ViewAllUpdates": "View All Updates",
	"AppDetails_ViewAllAchievements": "View My Achievements",
	"AppDetails_ViewGlobalAchievements": "View Global Achievement Stats",
	"AppDetails_Achievements_Unlocked": "Unlocked on %1$s",
	"AppDetails_PctUnlocked": "%1$s% of players have this achievement",

	"AppDetails_BrowseWorkshop": "Browse the Workshop",
	"AppDetails_ViewSubscribedItems": "View My Subscriptions",
	"AppDetails_ViewItemInWorkshop": "View In Workshop",
	"AppDetails_MoreItemsFrom": "View Items From This Creator",
	"AppDetails_SubscribeToItem": "Subscribe",
	"AppDetails_UnsubscribeFromItem": "Unsubscribe",
	"AppDetails_Subscribed": "Subscribed",
	"AppDetails_ViewMoreInWorkshop": "View more in the Workshop",

	"DLCStatus_installed": "Installed",
	"DLCStatus_notinstalled": "Not Installed",
	"DLCStatus_downloading": "Downloading",
	"DLC_DateAdded": "Added: %1$s",
	"AppDetails_ManageDLC": "Manage my %1$s DLC",
	"AppDetails_ManageMyDLC": "Manage My DLC",
	"AppDetails_ViewStoreDLC": "View DLC In Store",
	"ManageDLC_Title": "Manage DLC",
	"ManageDLC_Column_Name": "Name",
	"ManageDLC_Column_DateAdded": "Date Added",
	"ManageDLC_Column_Enabled": "Enabled",
	"ManageDLC_Column_Installed": "Installed",
	"ManageDLC_Search": "Search...",
	"ManageDLC_Installed": "%1$s/%2$s installed",
	"ManageDLC_ViewMore": "View more in the store",
	"ManageDLC_NoResults": "No results matching \"%1$s\"",
	"AppDetails_ViewBadgePage": "View Badge Page",
	"AppDetails_VisitTradeForum": "Visit Trade Forum",
	"AppDetails_BuyCards": "Buy Remaining Cards on the Market",
	"AppDetails_SellCards": "Sell These Cards on the Market",
	"AppDetails_SearchCard": "Show This Card on the Market",

	"AppDetails_ShowFriendsList": "Show Friends List",
	"AppDetails_ViewFriendsWhoPlay": "View Friends Who Play",

	"AppDetails_Link_Discussions": "Discussions",
	"AppDetails_Link_FindGroups": "Find Groups",
	"AppDetails_Link_GameHub": "Community Hub",
	"AppDetails_Link_Guides": "Guides",
	"AppDetails_Link_Store": "Store Page",
	"AppDetails_Link_Support": "Support",
	"AppDetails_Link_Workshop": "Workshop",
	"AppDetails_Link_Controller": "Controller Configuration",

	"AppDetails_SocialMediaLink": "%1$s on %2$s",
	"AppDetails_SocialMediaType_4": "Twitter",
	"AppDetails_SocialMediaType_5": "Twitch",
	"AppDetails_SocialMediaType_6": "YouTube",
	"AppDetails_SocialMediaType_7": "Facebook",

	"AppDetails_Screenshot": "Screenshot",
	"AppDetails_Screenshot_Caption": "Caption: %1$s",
	"AppDetails_Screenshot_Date": "Date: %1$s",
	"AppDetails_Screenshot_Dimensions": "Dimensions: %1$s x %2$s pixels",
	"AppDetails_OpenScreenshotUploader": "Open Screenshot Uploader",
	"AppDetails_ViewUploadedScreenshots": "View Uploaded Screenshots",
	"AppDetails_ManageMyScreenshots": "Manage my %1$s screenshots",
	"AppDetails_HowToScreenshot": "You can take a screenshot by pressing %1$s while in game.",
	"AppDetails_ChangeMyScreenshotKey": "Change My Screenshot Key",

	"AppBox_NewToLibrary": "New to library",
	"AppBox_PlayTimeHeader": "Time played",
	"AppBox_RecentPlayTime_Hours": "Last two weeks: %1$s hrs",
	"AppBox_RecentPlayTime_Minutes": "Last two weeks: %1$s min",
	"AppBox_TotalPlayTime_Hours": "Total: %1$s hrs",
	"AppBox_TotalPlayTime_Minutes": "Total: %1$s min",

	"AppActivity_Achieved":	" achieved:",
	"AppActivity_PostedScreenshot": " shared a screenshot:",
	"AppActivity_PostedScreenshot_Plural": " shared %1$s screenshots:",
	"AppActivity_ReceivedNewGame": " now owns %1$s.",
	"AppActivity_PlayedGameFirstTime": " played %1$s for the first time.",
	"AppActivity_AddedGameToWishlist": " added %1$s to their wishlist.",
	"AppActivity_Achieved_PlusMore": "+%1$s more achievements",
	"AppActivity_NoActivity": "No recent activity.",

	"AppDetails_Shortcut_Explanation": "Some detailed information on %1$s is unavailable because it is a non-Steam mod or shortcut. Steam will still manage launching the game for you and in most cases the in-game overlay will be available.",

	"AppPortraitHover_DownloadStatusTitle": "Downloading",
	"AppPortraitHover_DownloadStatusTitle_Update": "Downloading Update",
	"AppPortraitHover_DaysSinceLastUpdate": "Updated %1$s days ago",
	"AppPortraitHover_DaysSinceLastUpdateToday": "Updated today",
	"AppPortraitHover_FriendsPlaying": "%1$s Friends Playing"
}
