{
	"Generic_Okay": "OK",
	"Generic_Close": "Fechar",
	"Generic_Open": "Abrir",
	"Generic_GotIt": "OK!",
	"Generic_Share": "Partilhar",
	"Generic_Upload": "Enviar",
	"Generic_Delete": "Eliminar",
	"Privacy_Public": "Pública",
	"Privacy_FriendsOnly": "Só para amigos",
	"Privacy_Private": "Privada",
	"AppType_0": "(Inválido)",
	"AppType_1": "Jogos",
	"AppType_2": "Software",
	"AppType_4": "Ferramentas",
	"AppType_20": "DLC",
	"AppType_800": "Vídeos",
	"AppType_2000": "Bandas sonoras",
	"AppType_Singular_0": "(Inválido)",
	"AppType_Singular_1": "jogo",
	"AppType_Singular_2": "aplicação",
	"AppType_Singular_4": "ferramenta",
	"AppType_Singular_20": "DLC",
	"AppType_Singular_800": "vídeo",
	"AppType_Singular_2000": "música",
	"AppType_Singular_8000": "banda desenhada",
	"AppType_Singular_40000000": "atalho",
	"FilterEdit_SavedFilters": "Filtros guardados",
	"FilterEdit_FirstColumnHeader": "Tipo de filtro",
	"FilterEdit_Customize": "Personalizar",
	"FilterEdit_SearchModeHeader": "Filtros avançados",
	"FilterEdit_CollectionModeHeader": "Editar filtros de coleção",
	"CollectionEdit_CollectionNameField": "Nome da coleção:",
	"CollectionEdit_RenameButton": "Mudar nome da coleção",
	"Collection_DynamicCollection": "Coleção dinâmica",
	"FilterEdit_AdvancedTooltip": "Filtros avançados para organizares os teus jogos por género, funcionalidades, etc.",
	"Collection_FreezeDynamicCollection_Button": "Converter em coleção simples",
	"Collection_FreezeDynamicCollection_ToolTip": "Converte esta coleção dinâmica numa simples, mantendo a lista de jogos atual.",
	"Collection_FreezeDynamicCollection_DialogTitle": "Converter em coleção simples",
	"Collection_FreezeDynamicCollection_Confirmation": "Tens a certeza de que queres converter esta coleção? Esta deixará de se atualizar dinamicamente quando adicionares jogos correspondentes à tua biblioteca.",
	"Collection_ResetDialogTitle": "Repor coleções",
	"Collection_ResetConfirmation": "Tens a certeza de que queres repor a tua lista de coleções e reimportar as tuas categorias antigas?",
	"Collection_AfterResetSummary_NoCollections": "Não vais ter nenhuma coleção depois da reposição.",
	"Collection_AfterResetSummary_CountAndNames": "Vais ter estas %1$s coleções depois da reposição: %2$s",
	"Collection_ResetFailed": "Não foi possível repor coleções",
	"FilterEdit_SelectedFilters": "Filtros selecionados",
	"FilterEdit_SaveCollectionNameInputPrompt": "Dá um nome à coleção",
	"FilterEdit_SaveOverwrite": "Já existe uma coleção chamada \"%1$s\". Substituir?",
	"FilterEdit_SaveCollection": "Guardar como coleção",
	"FilterEdit_SaveDynamicCollectionWithIcon": "Guardar como %1$scoleção dinâmica",
	"FilterEdit_SaveDynamicCollectionNoIcon": "Guardar como coleção dinâmica",
	"FilterEdit_SaveCollectionVerbose": "Guarda esta lista como uma coleção para uso futuro. Podes editar, eliminar ou mudar o nome desta coleção quando quiseres, assim como arrastar itens para dentro ou fora dela.",
	"FilterEdit_SaveStandardCollectionButtonDesc": "Coleções são uma forma simples de organizar a tua biblioteca. Arrasta títulos para uma coleção ou clica com o botão direito num título para adicioná-lo a uma coleção existente.",
	"FilterEdit_SaveDynamicCollectionButtonDesc": "Coleções dinâmicas usam filtros para criar coleções que se atualizam à medida que a tua biblioteca cresce.",
	"FilterEdit_SelectCollectionType": "Seleciona um tipo de coleção",
	"FilterEdit_SelectCollectionTypeButtonCreate": "Criar coleção",
	"FilterEdit_SelectCollectionTypeButtonCreateDynamic": "Criar coleção dinâmica",
	"FilterEdit_RequiredField": "( OBRIGATÓRIO )",
	"FilterEdit_SearchPrompt": "Procurar por nome",
	"FilterEdit_ClearSearch": "Sair da procura",
	"FilterEdit_SearchResults": "Resultados da procura",
	"FilterEdit_CollectionsHiddenPromptTitle": "Coleções ocultas",
	"FilterEdit_CollectionsHiddenPrompt": "Gostarias de mudar de tipo de vista para que possas ver a nova coleção?",
	"FilterEdit_AcceptGameListViewChange": "Sim, mostrar coleções",
	"FilterEdit_RejectGameListViewChange": "Não, deixar como está",
	"AdvancedSearch_PaneTitle": "Procurar por tipo",
	"AdvancedSearch_PlayerSection": "Jogadores",
	"AdvancedSearch_HardwareSection": "Compatibilidade",
	"AdvancedSearch_FeatureSection": "Funcionalidades",
	"AdvancedSearch_StateSection": "Estado",
	"AdvancedSearch_GenreSection": "Género",
	"AdvancedSearch_StoreTagSection": "Marcadores da loja",
	"AdvancedSearch_StoreTagPrompt": "introduz um marcador",
	"FilterCategory_1": "Estado",
	"FilterCategory_Features": "FUNCIONALIDADE",
	"FilterCategory_3": "Categoria",
	"FilterCategory_4": "Marcador da loja",
	"FilterCategory_Type": "TIPO",
	"FilterCategory_Genre": "GÉNERO",
	"FilterCategory_PlayState": "ESTADO",
	"FilterElement_VR": "Realidade virtual",
	"FilterElement_Tooltip_VR": "Incluir jogos compatíveis com hardware de realidade virtual.",
	"FilterElement_Installed": "Instalados localmente",
	"FilterElement_Tooltip_Installed": "Incluir jogos que estão instalados neste computador.",
	"FilterElement_ReadyToPlay": "Prontos para jogar",
	"FilterElement_Tooltip_ReadyToPlay": "Incluir jogos que podem ser jogados localmente ou transmitidos de outro computador.",
	"FilterElement_PlayedPreviously": "Já jogados",
	"FilterElement_Tooltip_PlayedPreviously": "Incluir jogos que já jogaste.",
	"FilterElement_Unplayed": "Nunca jogados",
	"FilterElement_Tooltip_Unplayed": "Incluir jogos que ainda não jogaste.",
	"FilterElement_FullControllerSupport": "Comandos (total)",
	"FilterElement_Tooltip_FullControllerSupport": "Incluir jogos que podem ser jogados totalmente com um comando.",
	"FilterElement_PartialControllerSupport": "Comandos (parcial)",
	"FilterElement_Tooltip_PartialControllerSupport": "Incluir jogos que podem ser jogados com um comando, mas que podem precisar de teclado e rato durante a instalação ou para interações limitadas.",
	"FilterElement_VRSupported": "Compatíveis com R.V.",
	"FilterElement_TradingCards": "Cartas colecionáveis",
	"FilterElement_Tooltip_TradingCards": "Incluir jogos que tenham cartas colecionáveis do Steam.",
	"FilterElement_Workshop": "Workshop",
	"FilterElement_Tooltip_Workshop": "Incluir jogos que tenham o Steam Workshop integrado.",
	"FilterElement_Achievements": "Proezas",
	"FilterElement_Tooltip_Achievements": "Incluir jogos que tenham Proezas Steam.",
	"FilterElement_SinglePlayer": "Um jogador",
	"FilterElement_Tooltip_SinglePlayer": "Incluir jogos com um modo para um só jogador.",
	"FilterElement_MultiPlayer": "Multijogador",
	"FilterElement_Tooltip_MultiPlayer": "Incluir jogos com um modo multijogador.",
	"FilterElement_CoOp": "Co-op",
	"FilterElement_Tooltip_CoOp": "Incluir jogos com um modo multijogador cooperativo.",
	"FilterElement_GenreAction": "Ação",
	"FilterElement_Tooltip_GenreAction": "Incluir jogos de ação.",
	"FilterElement_GenreAdventure": "Aventura",
	"FilterElement_Tooltip_GenreAdventure": "Incluir jogos de aventura.",
	"FilterElement_GenreCasual": "Casual",
	"FilterElement_Tooltip_GenreCasual": "Incluir jogos casuais.",
	"FilterElement_GenreIndie": "Indie",
	"FilterElement_Tooltip_GenreIndie": "Incluir jogos indie.",
	"FilterElement_GenreMMO": "MMO",
	"FilterElement_Tooltip_GenreMMO": "Incluir jogos do género MMO (multijogador massivo online).",
	"FilterElement_GenreRacing": "Corridas",
	"FilterElement_Tooltip_GenreRacing": "Incluir jogos de corridas.",
	"FilterElement_GenreRPG": "RPG",
	"FilterElement_Tooltip_GenreRPG": "Incluir jogos do género RPG.",
	"FilterElement_GenreSimulation": "Simulação",
	"FilterElement_Tooltip_GenreSimulation": "Incluir jogos de simulação.",
	"FilterElement_GenreSports": "Desporto",
	"FilterElement_Tooltip_GenreSports": "Incluir jogos de desporto.",
	"FilterElement_GenreStrategy": "Estratégia",
	"FilterElement_Tooltip_GenreStrategy": "Incluir jogos de estratégia.",
	"FilterElement_Tooltip_StoreTag": "Incluir produtos com o marcador \"%1$s\" no Steam.",
	"FilterElement_SteamCloud": "Steam Cloud",
	"FilterElement_Tooltip_SteamCloud": "Incluir jogos que guardam o progresso na Steam Cloud.",
	"FilterElement_RemotePlayTogether": "Remote Play Together",
	"FilterElement_Tooltip_RemotePlayTogether": "Incluir jogos compatíveis com Remote Play Together.",
	"CollectionViewHeader_Tooltip_ManuallyAddedApp": "Este jogo foi adicionado manualmente à coleção.",
	"CollectionViewHeader_Tooltip_ManuallyRemovedApp": "Este jogo foi removido da coleção.",
	"CollectionViewHeader_Tooltip_ManuallyRemovedApps_WithCount": "%1$s jogos foram removidos desta coleção.",
	"CollectionViewHeader_ManuallyRemovedApps_WithCount": "%1$s removido(s)",
	"CollectionView_EmptyReadOnlyCollection": "Não há nada aqui",
	"CollectionView_EmptyDynamicCollection_Line1": "Nenhum jogo corresponde a este filtro!",
	"CollectionView_EmptyDynamicCollection_Line2": "Muda o filtro ou arrasta jogos para aqui para começares a reunir esta coleção.",
	"CollectionView_EmptyCollection": "Arrasta jogos para aqui para começares a reunir esta coleção.",
	"CollectionView_EmptyCollection_BecauseFilter": "%1$s jogo desta coleção não está a aparecer aqui por causa dos filtros selecionados.",
	"CollectionView_EmptyCollection_BecauseFilter_Plural": "%1$s jogos desta coleção não estão a aparecer aqui por causa dos filtros selecionados.",
	"CollectionView_MissingCollection": "Nenhuma coleção encontrada.",
	"CollectionView_GamesExcluded": "+%1$s",
	"CollectionView_GamesExcluded_Desc": "jogos não disponíveis para jogar",
	"AllCollectionsView_Title": "As tuas coleções",
	"AllCollectionsView_InfoIcon": "Cria %1$s para organizares os teus jogos a teu gosto, ou cria %2$s para agrupares jogos por um conjunto de filtros. %3$s",
	"AllCollectionsView_InfoIconCollections": "coleções",
	"AllCollectionsView_InfoIconDynamicCollections": "coleções dinâmicas",
	"AllCollectionsView_InfoIconFav": "Os teus %1$s vão aparecer sempre aqui, no topo da página.",
	"AllCollectionsView_InfoIconFavorites": "Favoritos",
	"AllCollectionsView_AddCollection": "Criar coleção nova",
	"AllCollectionsView_DragToAddCollection": "Arrasta p/ aqui p/ criares uma coleção",
	"GameList_Home": "Início",
	"GameList_Search": "Procurar",
	"GameList_Category_Uncategorized": "Sem categoria",
	"GameList_Category_Favorites": "Favoritos",
	"GameList_Category_Hidden": "Ocultos",
	"GameList_Category_Hidden_Tooltip": "Jogos ocultos não irão aparecer na tua biblioteca a menos que procures por eles. Podes ver todos os jogos ocultos a partir do menu \"Ver\".",
	"GameList_Category_YourCollections": "As tuas coleções",
	"GameList_Category_SharedLibraries": "Bibliotecas partilhadas",
	"GameList_SectionHeader_SearchResults": "Resultados da procura e filtros",
	"GameList_SectionHeader_AddedManually": "Adicionados manualmente",
	"GameList_SectionHeader_RemovedManually": "Removidos manualmente",
	"GameList_SectionHeader_NoRecentActivity": "Sem atividade registada",
	"GameList_View_Collections": "As tuas coleções",
	"GameList_View_ThisCollection": "Ver esta coleção",
	"GameList_View_OneCollection": "Coleção",
	"GameList_View_SearchResults": "Resultados da procura",
	"GameList_View_ShowAllCollections": "Mostrar todas as coleções",
	"GameList_View_GroupByCollections": "Agrupar por coleção",
	"GameList_View_ExitSearch": "Sair da procura",
	"GameList_View_All": "Todos",
	"GameList_View_Recent": "Recentes",
	"GameList_View_SortByRecent": "Ordenar por atividade recente",
	"GameList_View_ShowOnlyReadyToPlay": "Mostrar só jogos prontos para jogar",
	"GameList_View_ShowingReadyToPlay": "A mostrar só jogos prontos para jogar",
	"GameList_View_ShowingOnlyReadyToPlay": "A mostrar jogos prontos para jogar",
	"GameList_View_ShowOnlyVR": "Mostrar só jogos de R.V.",
	"GameList_View_Platform_Linux": "Mostrar só jogos compatíveis com Linux",
	"GameList_View_Platform_Apple": "Mostrar só jogos compatíveis com macOS",
	"GameList_View_MyOwnGames": "Os meus jogos",
	"GameList_View_GamesSharedByOther": "Jogos de %1$s",
	"GameList_View_NothingSelected": "Nenhum",
	"GameList_View_NothingSelected_HelpText": "Nada corresponde a este filtro.",
	"GameList_Search_GamesCheckbox_Link": "Mostrar jogos",
	"GameList_View_GroupSharedLibraries": "Agrupar por biblioteca",
	"GameList_View_GroupingDisabled_ToolTip": "Não é possível agrupar neste modo de visualização",
	"GameList_View_ReadyToPlay_ToolTip1": "• Instalados neste computador",
	"GameList_View_ReadyToPlay_ToolTip2": "• Podem ser transmitidos de outro computador",
	"GameList_Entry_ReadyToPlay_ToolTip": "Vai ser transmitido de outro computador",
	"GameList_Entry_Invalid_OSType": "A tua versão atual do macOS (Catalina) não pode executar jogos de 32 bits, como este.",
	"GameList_Entry_Invalid_OSType2": "Este jogo é compatível com Steam Play, o que significa que podes jogá-lo no Windows via Boot Camp, ou num PC.",
	"GameList_Entry_Invalid_OSType3": "Fica a saber mais.",
	"Shelf_SectionHeader_ExpandTooltip": "Expande a prateleira para que mais filas sejam mostradas",
	"Shelf_SectionHeader_ExpandTooltipFilter": "Expande a prateleira para que mais filas sejam mostradas. %1$s produto(s) não listado(s) por causa dos filtros selecionados",
	"GameList_SectionHeader_AppCountToolTip": "%1$s não listado(s) por causa dos filtros selecionados",
	"GameList_SectionHeader_AppCountToolTipAllHidden": "Nada listado por causa dos filtros selecionados",
	"CollectionAction_ViewOnlyThis": "Ver apenas esta coleção",
	"CollectionAction_ViewOnlyThisFavorites": "Ver apenas Favoritos",
	"CollectionAction_ViewOnlyThisUncategorized": "Ver apenas não categorizados",
	"CollectionAction_Collapse": "Minimizar",
	"CollectionAction_CollapseAll": "Minimizar tudo",
	"CollectionAction_CollapseAllCollections": "Minimizar todas as coleções",
	"CollectionAction_Expand": "Expandir",
	"CollectionAction_ExpandAll": "Expandir tudo",
	"CollectionAction_ExpandAllCollections": "Expandir todas as coleções",
	"CollectionAction_Manage": "Gerir",
	"CollectionAction_Edit": "Editar filtros de coleção",
	"CollectionAction_Rename": "Mudar nome de coleção",
	"CollectionAction_Delete": "Remover coleção",
	"CollectionAction_DeleteDialog": "Remover coleção",
	"CollectionAction_ConfirmDelete": "Tens a certeza de que queres remover permanentemente a coleção \"%1$s\"?",
	"CollectionAction_SaveFailed": "Não foi possível guardar a coleção \"%1$s\"",
	"CollectionAction_CannotOverwrite": "Não é possível substituir a coleção \"%1$s\". Por favor, escolhe outro nome.",
	"CollectionAction_DeleteFailed": "Não foi possível eliminar a coleção \"%1$s\"",
	"LibraryHome_FriendsActivity": "Atividade de amigos",
	"LibraryHome_RecentGames": "Jogos recentes",
	"LibraryHome_NewUpdates": "Novidades",
	"LibraryHome_YourCollection": "A tua biblioteca completa",
	"LibraryHome_RecentFriendsActivity": "Atividade recente de amigos",
	"LibraryHome_NewUpdates_LoweredPriority": "Agora a mostrar menos atualizações de %1$s.",
	"LibraryHome_NewUpdates_RaisedPriority": "Agora a mostrar mais atualizações de %1$s.",
	"LibraryHome_NewUpdates_Undo": "Anular",
	"LibraryHome_RecentFriendsActivity_Empty": "De momento, não há nada de novo ou popular no teu grupo de amigos. Esta prateleira irá ocultar-se automaticamente quando não houver nada para mostrar.",
	"WhatsNewSettings": "Definições das Novidades",
	"WhatsNew": "Novidades",
	"WhatsNewFeatureExplainer": "Novidades é uma secção em que criadores de jogos divulgam atualizações, torneios, DLCs, eventos e outras informações sobre os seus jogos. O Steam vai mostrar as novidades mais relevantes para ti com base nos teus jogos, especialmente nos que jogaste recentemente.",
	"WhatsNewFeatureExplainer2": "Alguns jogos serão automaticamente excluídos das Novidades se não jogaste mais do que algumas horas e se já passou muito tempo desde a última vez que acedeste ao jogo.",
	"WhatsNewVisibilitySettings": "Definições de visibilidade",
	"WhatsNewSettings_ShowOnlyForRecentlyPlayed": "Mostrar só jogos que tenha jogado nos últimos 90 dias",
	"WhatsNewSettings_ShowOnlyForRecentlyPlayed_Explainer": "(A frequência de um jogo pode ser ajustada clicando com o botão direito do rato numa das notícias.)",
	"WhatsNewSettings_ShowOnlyGameUpdates": "Mostrar só atualizações de produtos (excluir eventos e notícias)",
	"WhatsNewSettings_ShowOnlyGameUpdates_Explainer": "(A frequência de um jogo pode ser ajustada clicando com o botão direito do rato numa das notícias.)",
	"WhatsNewPrioritySettings": "Definições de prioridade",
	"WhatsNewPriorityExplainer": "(Clica com o botão direito numa das notícias para definires se o jogo deveria aparecer mais ou menos vezes.)",
	"WhatsNewYouHaveAskedToShowLessFor": "Selecionaste \"Mostrar menos\" para os seguintes jogos:",
	"WhatsNewYouHaveNothingShowingLess": "Não selecionaste \"Mostrar menos\" para nenhum jogo.",
	"WhatsNewYouHaveAskedToShowMoreFor": "Selecionaste \"Mostrar mais\" para os seguintes jogos:",
	"WhatsNewYouHaveNothingShowingMore": "Não selecionaste \"Mostrar mais\" para nenhum jogo.",
	"WhatsNewYouHaveNItemsHidden": "%1$s jogos da tua biblioteca estão ocultos e, por isso, não aparecerão nas Novidades.",
	"Library_FriendsActivity_HotRightNowHeading": "Na atualidade",
	"Library_FriendsActivity_HotRightNowHover": "Estamos a mostrar-te este jogo porque vários amigos teus estão a jogá-lo agora mesmo.",
	"Library_FriendsActivity_TrendingHeading": "Nova tendência",
	"Library_FriendsActivity_TrendingHover": "Estamos a mostrar-te este jogo porque alguns dos teus amigos o jogaram mais na semana passada do que na semana anterior.",
	"Library_FriendsActivity_BeingDiscussedHeading": "Na boca do povo",
	"Library_FriendsActivity_BeingDiscussedHover": "Estamos a mostrar-te este jogo porque os teus amigos têm andado a publicar capturas de ecrã ou mensagens de estado acerca dele.",
	"Library_FriendsActivity_RecentlyPurchasedHeading": "Comprado recentemente",
	"Library_FriendsActivity_RecentlyPurchasedHover": "Estamos a mostrar-te este jogo porque o compraste recentemente e os teus amigos estão a jogá-lo.",
	"Library_FriendsActivity_UnownedHeading": "Experimenta algo novo",
	"Library_FriendsActivity_UnownedHover": "Estamos a mostrar-te este jogo porque é popular entre os teus amigos e não o tens.",
	"Library_FriendsActivity_PopularHeading": "Popular",
	"Library_FriendsActivity_PopularHover": "Estamos a mostrar-te este jogo porque muitos dos teus amigos têm andado a jogá-lo recentemente.",
	"Library_FriendsActivity_DontForgetHeading": "Não te esqueças",
	"Library_FriendsActivity_DontForgetHover": "Estamos a mostrar-te este jogo porque não o jogaste recentemente, mas os teus amigos sim.",
	"Library_FriendsActivity_NewToGroupHeading": "Novidade entre amigos",
	"Library_FriendsActivity_NewToGroupHover": "Estamos a mostrar-te este jogo porque os teus amigos começaram a jogá-lo recentemente.",
	"Library_FriendsActivity_ReturnedToGroupHeading": "De volta à atualidade",
	"Library_FriendsActivity_ReturnedToGroupHover": "Estamos a mostrar-te este jogo porque os teus amigos começaram a jogá-lo novamente.",
	"Library_FriendsActivity_UnownedBanner": "Ver na Loja Steam",
	"Library_FriendsActivity_UnownedMenu_Store": "Loja",
	"Library_FriendsActivity_UnownedMenu_Hub": "Central Comunitária",
	"Library_FriendsActivity_UnownedMenu_Reviews": "Análises",
	"Library_FriendsActivity_UnownedMenu_Discussions": "Discussões",
	"Library_Recent_NoRecentGames_GamesOwned": "Tens %1$s jogos.",
	"Library_Recent_NoRecentGames_StoreLink": "Visita a %1$s para encontrares jogos:",
	"Library_Recent_NoRecentGames_SteamStore": "Loja Steam",
	"Library_Recent_NoRecentGames_FreeToPlay": "Jogos Grátis para Jogar",
	"Library_Recent_NoRecentGames_GamesOnSale": "Jogos em promoção",
	"Library_Recent_NoRecentGames_NewReleases": "Novos lançamentos",
	"Library_Recent_NoRecentGames_ActivateProduct": "Ativar um produto",
	"Library_Recent_NoRecentGames_RedeemCode": "Ativar código para a Carteira Steam",
	"Library_SortCollectionBy": "Ordenar:",
	"Library_SortByFavoritesFirst": "Favoritos primeiro",
	"Library_SortByAlphabetical": "Alfabeticamente",
	"Library_SortByPctAchievementsComplete": "% de proezas alcançadas",
	"Library_SortByLastUpdated": "Última atualização",
	"Library_SortByHoursPlayed": "Horas de jogo",
	"Library_SortByLastPlayed": "Última sessão",
	"Library_SortByReleaseDate": "Data de lançamento",
	"Library_SortByAddedToLibrary": "Data de aquisição",
	"Library_SortBySizeOnDisk": "Espaço no disco",
	"Library_SortByMetacriticScore": "Pontuação no Metacritic",
	"Library_SortByFriendsPlaying": "Amigos que estão a jogar",
	"Library_SortBySteamReview": "Análises Steam",
	"Library_SortByPctAchievementsComplete_Tag": "%1$s% alcançado",
	"Library_SortByPctAchievementsNoAchievements_Tag": "Sem proezas",
	"Library_InstalledOnlyCheck": "Só instalados",
	"GridSection_Favorites": "Favoritos",
	"GridSection_EverythingElse": "Tudo o resto",
	"GridSection_Over100Hours": "Mais de 100 horas",
	"GridSection_Over60Hours": "Mais de 60 horas",
	"GridSection_Over40Hours": "Mais de 40 horas",
	"GridSection_Over20Hours": "Mais de 20 horas",
	"GridSection_Over10Hours": "Mais de 10 horas",
	"GridSection_Over1Hour": "Mais de 1 hora",
	"GridSection_LessThan1Hour": "Menos de 1 hora",
	"GridSection_Over90Metacritic": "Mais de 90",
	"GridSection_Over80Metacritic": "Mais de 80",
	"GridSection_Over70Metacritic": "Mais de 70",
	"GridSection_Over50Metacritic": "Mais de 50",
	"GridSection_EverythingElseMetacritic": "Tudo o resto",
	"GridSection_UnknownReleaseDate": "Desconhecida",
	"GridSection_GreaterThan100GB": "Mais de 100 GB",
	"GridSection_GreaterThan50GB": "Mais de 50 GB",
	"GridSection_GreaterThan20GB": "Mais de 20 GB",
	"GridSection_LessThan20GB": "Menos de 20 GB",
	"GridSection_NoSizeOnDisk": "Sem espaço ocupado",
	"GridSection_NotInstalled": "Não instalados",
	"GridSection_MoreThan10YearsAgo": "Há mais de 10 anos",
	"GridSection_Never": "Nunca",
	"AppDetails_SectionTitle_Stream": "Transmissão dos desenvolvedores",
	"AppDetails_SectionTitle_Activity": "Atividade",
	"AppDetails_SectionTitle_Friends": "Amigos que jogam",
	"AppDetails_SectionTitle_Friends_Software": "Amigos que usam isto",
	"AppDetails_SectionTitle_Achievements": "Proezas",
	"AppDetails_SectionTitle_TradingCards": "Cartas colecionáveis",
	"AppDetails_SectionTitle_Screenshots": "Capturas de ecrã",
	"AppDetails_SectionTitle_AdditionalContent": "Conteúdo adicional",
	"AppDetails_SectionTitle_Updates": "Atualizações e eventos recentes",
	"AppDetails_SectionTitle_DLC": "DLC",
	"AppDetails_SectionTitle_LastPlayed": "Última sessão",
	"AppDetails_SectionTitle_LastLaunched": "Última sessão",
	"AppDetails_SectionTitle_PlayTime": "Tempo de jogo",
	"AppDetails_SectionTitle_UsageTime": "Tempo de uso",
	"AppDetails_SectionTitle_Workshop": "Steam Workshop",
	"AppDetails_SectionTitle_Community": "Conteúdo comunitário",
	"AppDetails_SectionTitle_Links": "Links",
	"AppDetails_SectionTitle_SignIn_Pre": "Inicia a sessão",
	"AppDetails_SectionTitle_SignIn": "%1$s para veres a atividade de amigos",
	"AppDetails_SectionTitle_OpenFriends": "Abrir lista de amigos",
	"AppDetails_SectionTitle_OfflineMode": "Modo offline",
	"AppDetails_Broadcast_ViewOnWeb": "Ver no browser",
	"AppDetails_Community_Tooltip1": "Esta secção contém capturas de ecrã, arte, vídeos, guias e outros conteúdos enviados pela Comunidade.",
	"AppDetails_Community_Tooltip2": "Podes votar positivamente, partilhar, comentar ou denunciar este conteúdo.",
	"AppDetails_Community_Guide": "Guia comunitário",
	"AppDetails_Links_Store": "Página na loja",
	"AppDetails_Links_Community": "Central comunitária",
	"Bbcode_Originally_Posted_By": "Publicado inicialmente por",
	"AppDetails_InOfflineMode": "O Steam está no Modo Offline, durante o qual muitos recursos da tua Biblioteca Steam, tais como o feed de atividade e a lista de amigos, estão indisponíveis. Fica online para veres este conteúdo.",
	"AppDetails_GoOnline": "Ficar online",
	"AppDetails_PartnerEventFailedLoad": "Não foi possível carregar este evento",
	"GameAction_Stop": "Parar",
	"GameAction_Cancel": "Cancelar",
	"GameAction_Install": "Instalar",
	"GameAction_Uninstall": "Desinstalar",
	"GameAction_Play": "Jogar",
	"GameAction_PlayMusic": "Reproduzir álbum",
	"GameAction_Launch": "Iniciar",
	"GameAction_PreLoad": "Pré-carregar",
	"GameAction_Update": "Atualizar",
	"GameAction_Download": "Transferir",
	"GameAction_Resume": "Retomar",
	"GameAction_Pause": "Pausar",
	"GameAction_BorrowApp": "Pedir emprestado",
	"GameAction_PurchaseApp": "Comprar",
	"GameAction_GameProperties": "Propriedades...",
	"GameAction_AddToFavorites": "Adicionar aos Favoritos",
	"GameAction_RemoveFromFavorites": "Remover dos Favoritos",
	"GameAction_AddToHidden": "Ocultar este jogo",
	"GameAction_RemoveFromHidden": "Deixar de ocultar",
	"GameAction_RemoveGameLicense": "Remover da conta",
	"GameAction_AddToFamilyGames": "Adicionar aos jogos da família",
	"GameAction_RemoveFromFamilyGames": "Remover dos jogos da família",
	"GameAction_RemoveShortcut": "Remover jogo não-Steam da tua biblioteca",
	"GameAction_AddToCollection": "Adicionar a...",
	"GameAction_RemoveFromCollection": "Remover de...",
	"GameAction_CreateDesktopShortcut": "Adicionar atalho ao ambiente de trabalho",
	"GameAction_BackUpFiles": "Fazer cópias de segurança...",
	"GameAction_Stream": "Transmitir",
	"GameAction_Connect": "Conectar",
	"GameAction_SetCustomArtwork": "Definir imagem personalizada",
	"GameAction_ClearCustomArtwork": "Remover imagem personalizada",
	"GameAction_ViewCDKeys": "Códigos de produto",
	"GameAction_ControllerConfiguration": "Configuração do comando",
	"GameAction_Launching": "A iniciar",
	"GameAction_RemoveAppFromCollection": "ARRASTA P/ AQUI p/ removeres \"%1$s\" de \"%2$s\"",
	"GameAction_RemoveAppFromMultipleCollections": "ARRASTA P/ AQUI p/ removeres \"%1$s\" destas coleções",
	"GameAction_RemoveMultipleAppsFromCollection": "ARRASTA P/ AQUI para removê-los de \"%1$s\"",
	"GameAction_RemoveMultipleAppsFromMultipleCollections": "ARRASTA P/ AQUI p/ removê-los destas coleções",
	"GameAction_NavigateToAllCollectionsWithDrag": "ARRASTA E MANTÉM AQUI p/ veres todas as coleções",
	"GameAction_AddToCollectionOption_NewCollection": "Coleção nova...",
	"GameAction_NewCollectionDialogTitle": "Coleção nova",
	"GameAction_Manage": "Gerir",
	"GameAction_Favorite": "Adicionar aos Favoritos",
	"GameAction_UnFavorite": "Já está nos Favoritos",
	"GameAction_ViewDetails": "Mostrar mais detalhes",
	"GameAction_BrowseLocalFiles": "Ver pasta de instalação",
	"GameAction_ViewDetails_Collapse": "Mostrar menos detalhes",
	"GameAction_ViewDetails_ScrollUp": "Ir para o topo",
	"GameActionPlural_Install": "Instalar selecionados",
	"GameActionPlural_Uninstall": "Desinstalar selecionados",
	"GameActionPlural_PreLoad": "Pré-carregar selecionados",
	"GameActionPlural_Update": "Atualizar selecionados",
	"GameActionPlural_Download": "Transferir selecionados",
	"GameActionPlural_Resume": "Retomar selecionados",
	"GameActionPlural_AddToFavorites": "Adicionar selecionados aos Favoritos",
	"GameActionPlural_RemoveFromFavorites": "Remover selecionados dos Favoritos",
	"GameActionPlural_AddToHidden": "Ocultar selecionados",
	"GameActionPlural_RemoveFromHidden": "Deixar de ocultar selecionados",
	"GameActionPlural_AddToFamilyGames": "Adicionar selecionados aos jogos da família",
	"GameActionPlural_RemoveFromFamilyGames": "Remover selecionados dos jogos da família",
	"GameActionPlural_RemoveShortcut": "Remover jogos não-Steam selecionados da tua biblioteca",
	"GameActionPlural_AddToCollection": "Adicionar selecionados a",
	"GameActionPlural_RemoveFromCollection": "Remover selecionados de",
	"GameActionPlural_CreateDesktopShortcut": "Adicionar atalhos ao ambiente de trabalho",
	"GameActionPlural_BackUpFiles": "Fazer cópias de segurança...",
	"PrePurchase_Preload_Title": "%1$s pode agora ser pré-carregado",
	"PrePurchase_Preload_Desc": "Faz o download dos ficheiros do jogo já para que possas começar a jogá-lo assim que estiver disponível!",
	"PrePurchase_PreloadComplete_Title": "%1$s foi pré-carregado",
	"PrePurchase_PreloadComplete_Desc": "Assim que o jogo estiver disponível, poderás começar a jogá-lo!",
	"PrePurchase_Install_Title": "%1$s está agora pronto para ser instalado e jogado",
	"PrePurchase_Install_Desc": "Instala já para começares a jogar!",
	"PrePurchase_PlayNow_Title": "%1$s está agora pronto para ser jogado",
	"PrePurchase_PlayNow_Desc": "Começa já a jogar!",
	"DisplayStatus_Launching": "A iniciar",
	"DisplayStatus_Uninstalling": "A desinstalar",
	"DisplayStatus_Installing": "A instalar",
	"DisplayStatus_Running": "Em execução",
	"DisplayStatus_Validating": "A validar",
	"DisplayStatus_Updating": "A atualizar",
	"DisplayStatus_Downloading": "A transferir",
	"DisplayStatus_Synchronizing": "A sincronizar com a Steam Cloud",
	"DisplayStatus_ReadyToInstall": "Pronto para instalar",
	"DisplayStatus_ReadyToPreload": "Pronto para pré-carregar",
	"DisplayStatus_ReadyToLaunch": "Pronto para iniciar",
	"DisplayStatus_RegionRestricted": "Indisponível na região atual",
	"DisplayStatus_PresaleOnly": "Este item ainda não está disponível",
	"DisplayStatus_InvalidPlatform": "Disponível para",
	"DisplayStatus_PreloadComplete": "Pré-carregamento concluído",
	"DisplayStatus_BorrowerLocked": "Esta biblioteca ainda não está disponível para partilha",
	"DisplayStatus_UpdatePaused": "Atualização em pausa",
	"DisplayStatus_UpdateQueued": "Atualização na fila",
	"DisplayStatus_UpdateRequired": "Atualização necessária",
	"DisplayStatus_UpdateDisabled": "Atualizações desativadas porque o Steam está no Modo Offline. Fica online para concluíres esta atualização.",
	"DisplayStatus_DownloadPaused": "Download em pausa",
	"DisplayStatus_DownloadQueued": "Download na fila",
	"DisplayStatus_DownloadRequired": "Download necessário",
	"DisplayStatus_DownloadDisabled": "Downloads desativados porque o Steam está no Modo Offline. Fica online para concluíres este download.",
	"DisplayStatus_LicensePending": "A tua compra ainda não foi concluída.",
	"DisplayStatus_LicenseExpired": "A licença expirou",
	"DisplayStatus_AvailForFree": "Disponível gratuitamente",
	"DisplayStatus_AvailToBorrow": "Pode ser emprestado",
	"DisplayStatus_AvailGuestPass": "Passe de convidado disponível",
	"DisplayStatus_Purchase": "Disponível para compra",
	"DisplayStatus_Preallocating": "A pré-alocar",
	"DisplayStatus_Committing": "A aplicar",
	"DisplayStatus_Verifying": "A verificar",
	"DisplayStatus_Unpacking": "A descomprimir",
	"DisplayStatus_Compact_Launching": "A iniciar",
	"DisplayStatus_Compact_Uninstalling": "A desinstalar",
	"DisplayStatus_Compact_Installing": "A instalar",
	"DisplayStatus_Compact_Running": "Em execução",
	"DisplayStatus_Compact_Validating": "A validar",
	"DisplayStatus_Compact_Updating": "A atualizar",
	"DisplayStatus_Compact_Downloading": "A transferir",
	"DisplayStatus_Compact_Synchronizing": "A sincronizar com a Steam Cloud",
	"DisplayStatus_Compact_ReadyToInstall": "Pronto para instalar",
	"DisplayStatus_Compact_ReadyToPreload": "Pronto para pré-carregar",
	"DisplayStatus_Compact_ReadyToLaunch": "Pronto para iniciar",
	"DisplayStatus_Compact_RegionRestricted": "Indisponível nesta região",
	"DisplayStatus_Compact_PresaleOnly": "Jogo ainda não lançado",
	"DisplayStatus_Compact_InvalidPlatform": "Disponível para",
	"DisplayStatus_Compact_ParentalBlocked": "Bloqueado pelo Modo Família",
	"DisplayStatus_Compact_PreloadComplete": "Pré-carregamento concluído",
	"DisplayStatus_Compact_BorrowerLocked": "Partilha de Biblioteca indisponível",
	"DisplayStatus_Compact_UpdatePaused": "Atualização em pausa",
	"DisplayStatus_Compact_UpdateQueued": "Atualização na fila",
	"DisplayStatus_Compact_UpdateRequired": "Atualização necessária",
	"DisplayStatus_Compact_UpdateDisabled": "Atualizações desativadas no Modo Offline.",
	"DisplayStatus_Compact_DownloadPaused": "Download em pausa",
	"DisplayStatus_Compact_DownloadQueued": "Download na fila",
	"DisplayStatus_Compact_DownloadRequired": "Download necessário",
	"DisplayStatus_Compact_DownloadDisabled": "Downloads desativados no Modo Offline.",
	"DisplayStatus_Compact_LicensePending": "Compra pendente",
	"DisplayStatus_Compact_LicenseExpired": "A licença expirou",
	"DisplayStatus_Compact_AvailForFree": "Disponível grátis",
	"DisplayStatus_Compact_AvailToBorrow": "Pode ser emprestado",
	"DisplayStatus_Compact_AvailGuestPass": "Passe disponível",
	"DisplayStatus_Compact_Purchase": "Disponível para compra",
	"DisplayStatus_ReleaseDate": "Lançamento: %1$s",
	"DisplayStatus_CustomReleaseDate": "Data de lançamento planeada: %1$s",
	"Downloads_State_Bytes_Of_Bytes": "%1$s de %2$s",
	"Downloads_State_None": "",
	"Downloads_State_Reconfiguring": "A iniciar download",
	"Downloads_State_Validating": "A validar ficheiros",
	"Downloads_State_AddingFiles": "A copiar ficheiros",
	"Downloads_State_Preallocating": "A reservar espaço",
	"Downloads_State_Downloading": "",
	"Downloads_State_Staging": "",
	"Downloads_State_Committing": "A finalizar",
	"Downloads_State_Verifying": "A verificar download",
	"Downloads_State_Stopping": "A interromper download",
	"Downloads_State_Running": "",
	"Downloads_State_SecondsRemaining": "Tempo restante: %1$s seg.",
	"Downloads_State_MinutesRemaining": "Tempo restante: %1$s min.",
	"Downloads_State_Calculating": "A calcular...",
	"LaunchApp_Action_UpdatingAppInfo": "A verificar configuração",
	"LaunchApp_Action_ShowEula": "A mostrar acordo",
	"LaunchApp_Action_DownloadingDepots": "A transferir conteúdo (%1$s%)",
	"LaunchApp_Action_DownloadingWorkshop": "A transferir workshop (%1$s%)",
	"LaunchApp_Action_UpdatingDRM": "A atualizar executável",
	"LaunchApp_Action_GettingLegacyKey": "A atualizar código de produto",
	"LaunchApp_Action_RunningInstallScript": "A executar script de instalação (%1$s)",
	"LaunchApp_Action_SynchronizingCloud": "A sincronizar com a cloud",
	"LaunchApp_Action_VerifyingFiles": "A verificar executável",
	"LaunchApp_Action_CreatingProcess": "A iniciar executável",
	"LaunchApp_Action_WaitingGameWindow": "A iniciar executável",
	"LaunchApp_Action_DelayLaunch": "A adiar inicialização (%1$s%)",
	"AppDetails_TitleUpdatedSincePlayed": "Este jogo foi atualizado desde a última vez que o jogaste",
	"AppDetails_TitleUpdatedSincePlayedLink": "Lê sobre o que há de novo",
	"AppDetails_BadgeLevel": "Nível %1$s, %2$s XP",
	"AppDetails_UnearnedBadgeXP": "%1$s XP",
	"AppDetails_BadgeLevelNoXP": "Nível %1$s",
	"AppDetails_Review_ViewOrEdit": "Editar a minha análise",
	"AppDetails_Review_YourReview": "A minha análise",
	"AppDetails_Review_Ignore_Stale_Reviews": "Não me lembrem de atualizar esta análise.",
	"AppDetails_Review_Unignore_Stale_Reviews": "Lembrem-me de atualizar a análise deste jogo.",
	"AppDetails_Review_RecommendGame": "Recomendas este jogo?",
	"AppDetails_Review_RecommendSoftware": "Recomendas este software?",
	"AppDetails_Review_WriteReview": "Escreve uma análise sobre %1$s",
	"AppDetails_Review_PlayedForTime": "Jogaste este jogo durante %1$s",
	"AppDetails_Review_PlayedForTime_Software": "Usaste este software durante %1$s",
	"AppDetails_Review_RecommendGameButton_Yes": "Sim",
	"AppDetails_Review_RecommendGameButton_No": "Não",
	"AppDetails_Review_PlaytimeAtReview": "Tempo de jogo antes da publicação: %1$s",
	"AppDetails_Review_PlaytimeAtReview_Software": "Tempo de uso antes da publicação: %1$s",
	"AppDetails_Review_NotRecommended": "Não recomendado",
	"AppDetails_Review_Recommended": "Recomendado",
	"AppDetails_Review_AdditionalPlaytime": "Jogaste mais %1$s desde a publicação desta análise.",
	"AppDetails_Review_AdditionalPlaytime_Software": "Usaste isto durante mais %1$s desde a publicação da análise.",
	"AppDetails_Review_ChangedYourMind": "Mudaste de ideias?",
	"AppDetails_Review_IHaveNotChangedMyMind": "Não mudei",
	"AppDetails_Review_UpVotes": "Votos positivos:",
	"AppDetails_Review_Comments": "Comentários:",
	"AppDetails_Review_ViewAll": "Ver todas as minhas análises",
	"AppDetails_Review_ViewAllByFriend": "Ver todas as análises de %1$s",
	"OverflowBox_Action_Collapse": "Ver menos",
	"OverflowBox_Action_Expand": "Ver mais",
	"OverflowBox_More": "(mais %1$s)",
	"AppDetails_FriendsInGameNow": "%1$s amigo a jogar agora mesmo",
	"AppDetails_FriendsInGameNow_Plural": "%1$s amigos a jogar agora mesmo",
	"AppDetails_FriendsPlayedRecently": "%1$s amigo jogou recentemente",
	"AppDetails_FriendsPlayedRecently_Plural": "%1$s amigos jogaram recentemente",
	"AppDetails_FriendsPlayedRecentlyExpand": "Ver todos os que jogaram recentemente",
	"AppDetails_FriendsPlayed": "%1$s amigo jogou no passado",
	"AppDetails_FriendsPlayed_Plural": "%1$s amigos jogaram no passado",
	"AppDetails_FriendsPlayedExpand": "Ver todos os que jogaram no passado",
	"AppDetails_FriendsMore": "(mais %1$s)",
	"AppDetails_FriendsLess": "Mostrar menos",
	"AppDetails_FriendsWishlisted": "%1$s amigo adicionou %2$s à lista de desejos",
	"AppDetails_FriendsWishlisted_Plural": "%1$s amigos adicionaram %2$s à lista de desejos",
	"AppDetails_FriendsWishlistExpand": "Ver todos",
	"AppDetails_Friends_ViewAll": "Ver todos os amigos que jogam",
	"AppDetails_GameInfo": "Informações",
	"AppDetails_Publisher": "Editora:",
	"AppDetails_Developer": "Desenvolvedor:",
	"AppDetails_Franchise": "Série:",
	"AppDetails_ReleaseDate": "Data de lançamento:",
	"AppDetails_LastUpdate": "Última atualização local:",
	"AppDetails_OriginalReleaseDate": "Data de lançamento original:",
	"AppDetails_Feature_SinglePlayer": "Um jogador",
	"AppDetails_Feature_MultiPlayer": "Multijogador",
	"AppDetails_Feature_CoOp": "Cooperativo",
	"AppDetails_Feature_SteamAchievements": "Proezas",
	"AppDetails_Feature_SteamCloud": "Progresso guardado na Cloud",
	"AppDetails_Feature_FullController": "Compatibilidade total com comando",
	"AppDetails_Feature_PartialController": "Compatibilidade parcial com comando",
	"AppDetails_Feature_SteamWorkshop": "Steam Workshop",
	"AppDetails_Feature_VRSupport": "Compatibilidade com R.V.",
	"AppDetails_ViewAllUpdates": "Ver todas as atualizações",
	"AppDetails_ViewAllAchievements": "Ver as minhas proezas",
	"AppDetails_ViewGlobalAchievements": "Ver estatísticas globais de proezas",
	"AppDetails_PlayerUnlockedPercent": "Desbloqueaste %1$s/%2$s",
	"AppDetails_PlayerUnlockedPercentAll": "Desbloqueaste todas as proezas! %1$s/%2$s",
	"AppDetails_Achievements_Unlocked": "Desbloqueada em %1$s",
	"AppDetails_PctUnlocked": "%1$s% dos jogadores têm esta proeza",
	"AppDetails_GlobalCompare": "É mais do que %1$s% dos jogadores",
	"AppDetails_ViewTradingCards": "Ver as minhas cartas colecionáveis",
	"AppDetails_Achievements_Locked": "Proezas bloqueadas",
	"AppDetails_TradingCardsLeft": "1 carta por colecionar",
	"AppDetails_TradingCardsLeft_Plural": "%1$s cartas por colecionar",
	"AppDetails_TradingCardsLevelUp": "Tens cartas suficientes para subires de nível!",
	"AppDetails_TradingCardsMaxed": "Parabéns! Medalha no nível máximo!",
	"AppDetails_TradingCards_Tooltip1": "Podes encontrar cartas colecionáveis enquanto jogas. Troca com amigos ou visita o Mercado da Comunidade Steam para conseguires as cartas que te faltam.",
	"AppDetails_TradingCards_Tooltip2": "Completa um conjunto completo de cartas e transforma-o numa medalha. Medalhas ajudam a subir o teu nível Steam e trazem vantagens ao teu perfil e à tua conta.",
	"AppDetails_BrowseWorkshop": "Visitar Workshop",
	"AppDetails_ViewSubscribedItems": "Ver as minhas subscrições",
	"AppDetails_ViewItemInWorkshop": "Ver no Workshop",
	"AppDetails_MoreItemsFrom": "Ver itens deste criador",
	"AppDetails_SubscribeToItem": "Subscrever",
	"AppDetails_UnsubscribeFromItem": "Anular subscrição",
	"AppDetails_Subscribed": "Subscrito",
	"AppDetails_ViewMoreInWorkshop": "Ver mais no Workshop",
	"AppDetails_WorkshopSubCount": "Subscreveste %1$s itens do Workshop.",
	"AppDetails_WorkshopVisit": "Visitar Workshop",
	"AppDetails_WorkshopLearnMore": "Saber mais",
	"AppDetails_WorkshopFeaturedHeader": "Item popular",
	"AppDetails_WorkshopFeaturedItem": "Item popular",
	"AppDetails_WorkshopFeaturedMoreInfo": "Ler mais",
	"AppDetails_WorkshopFeaturedHideItem": "Ocultar este item",
	"AppDetails_WorkshopFileSize": "Tamanho do ficheiro: %1$s",
	"AppDetails_WorkshopFileSizeBytes": "%1$s bytes",
	"AppDetails_WorkshopFileSizeKb": "%1$s KB",
	"AppDetails_WorkshopFileSizeMb": "%1$s MB",
	"AppDetails_WorkshopFileSizeGb": "%1$s GB",
	"AppDetails_WorkshopLastUpdated": "Última atualização: %1$s",
	"DLCStatus_installed": "Instalado",
	"DLCStatus_notinstalled": "Não instalado",
	"DLCStatus_downloading": "A transferir",
	"DLC_DateAdded": "Adquirido: %1$s",
	"AppDetails_ManageDLC": "Gerir os meus DLCs (%1$s)",
	"AppDetails_ManageMyDLC": "Gerir os meus DLCs",
	"AppDetails_ViewStoreDLC": "Ver DLC na loja",
	"AppDetails_DLCSpotlight": "O DLC que acabaste de adquirir foi adicionado e será instalado juntamente com o jogo. Faz a gestão do teu DLC %1$s.",
	"AppDetails_DLCSpotlight_Installed": "O DLC que acabaste de adquirir foi instalado automaticamente. Faz a gestão do teu DLC %1$s.",
	"AppDetails_DLCSpotlight_here": "aqui",
	"ManageDLC_Title": "Gerir DLC",
	"ManageDLC_Column_Name": "Nome",
	"ManageDLC_Column_DateAdded": "Data de aquisição",
	"ManageDLC_Column_Enabled": "Ativo",
	"ManageDLC_Column_Installed": "Instalado",
	"ManageDLC_Search": "Procurar...",
	"ManageDLC_Installed": "%1$s/%2$s instalado(s)",
	"ManageDLC_ViewMore": "Ver mais na loja",
	"ManageDLC_NoResults": "Sem resultados para \"%1$s\"",
	"AppDetails_ViewBadgePage": "Ver página da medalha",
	"AppDetails_VisitTradeForum": "Visitar fórum de trocas",
	"AppDetails_BuyCards": "Comprar cartas restantes no Mercado",
	"AppDetails_SellCards": "Vender estas cartas no Mercado",
	"AppDetails_SearchCard": "Mostrar esta carta no Mercado",
	"AppDetails_ShowFriendsList": "Mostrar lista de amigos",
	"AppDetails_ViewFriendsWhoPlay": "Ver amigos que jogam",
	"AppDetails_Link_Discussions": "Discussões",
	"AppDetails_Link_FindGroups": "Procurar grupos",
	"AppDetails_Link_GameHub": "Central comunitária",
	"AppDetails_Link_Guides": "Guias",
	"AppDetails_Link_Store": "Página na loja",
	"AppDetails_Link_Support": "Apoio",
	"AppDetails_Link_Workshop": "Workshop",
	"AppDetails_Link_Market": "Mercado",
	"AppDetails_Link_Controller": "Configuração do comando",
	"AppDetails_SocialMediaLink": "%1$s no %2$s",
	"AppDetails_SocialMediaType_4": "Twitter",
	"AppDetails_SocialMediaType_5": "Twitch",
	"AppDetails_SocialMediaType_6": "YouTube",
	"AppDetails_SocialMediaType_7": "Facebook",
	"AppDetails_Screenshot": "Captura de ecrã",
	"AppDetails_Screenshot_Caption": "Legenda: %1$s",
	"AppDetails_Screenshot_Date": "Data: %1$s",
	"AppDetails_Screenshot_Dimensions": "Dimensões: %1$s x %2$s pixels",
	"AppDetails_Screenshot_Uploaded": "Enviado a %1$s às %2$s",
	"AppDetails_OpenScreenshotUploader": "Abrir gestor de capturas de ecrã",
	"AppDetails_ViewUploadedScreenshots": "Ver capturas de ecrã enviadas",
	"AppDetails_ManageMyScreenshot": "Gerir a minha captura de ecrã",
	"AppDetails_ManageMyScreenshot_Plural": "Gerir as minhas capturas de ecrã (%1$s)",
	"AppDetails_HowToScreenshot": "Pressiona %1$s enquanto jogas para capturares o ecrã.",
	"AppDetails_ChangeMyScreenshotKey": "Alterar atalho de captura",
	"AppDetails_NoScreenshots": "Ainda não guardaste nenhuma captura de ecrã",
	"AppDetails_Screenshot_SpoilerAlert": "Possíveis spoilers. Passa o cursor por cima para revelar.",
	"AppDetails_Artwork": "Arte",
	"AppDetails_Video": "Vídeos",
	"AppDetails_CommunityItem": "Conteúdo comunitário",
	"AppDetails_CommunityFeed_OutOfContent": "Sem conteúdo adicional",
	"AppDetails_CommunityFeed_Inappropriate": "O conteúdo pode não ser apropriado para todas as idades",
	"AppDetails_CommunityFeed_ViewContent": "Ver conteúdo",
	"AppDetails_CommunityFeed_EditPreferences": "Editar preferências",
	"AppDetails_CommunityFeed_LoadCommunity": "Carregar mais conteúdo comunitário",
	"AppBox_NewToLibrary": "Novo",
	"AppBox_ComingSoon": "Em breve",
	"AppBox_NewToLibrary_Short": "Novo",
	"AppBox_ComingSoon_Short": "Disponível em breve",
	"AppBox_PlayTimeHeader": "Tempo de jogo",
	"AppBox_RecentPlayTime_Hours": "Nas últ. 2 semanas: %1$s h.",
	"AppBox_RecentPlayTime_Minutes": "Nas últ. 2 semanas: %1$s min.",
	"AppBox_TotalPlayTime_Hours": "Total: %1$s h.",
	"AppBox_TotalPlayTime_Minutes": "Total: %1$s min.",
	"AppActivity_Achieved": " alcançou proezas",
	"AppActivity_PostedScreenshot": " partilhou uma captura de ecrã",
	"AppActivity_PostedScreenshot_Plural": " partilhou %1$s capturas de ecrã",
	"AppActivity_PostedVideo": " partilhou um vídeo",
	"AppActivity_PostedVideo_Plural": " partilharam %1$s vídeos",
	"AppActivity_ReceivedNewGame": " agora tem %1$s",
	"AppActivity_PlayedGameFirstTime": " jogou %1$s pela primeira vez",
	"AppActivity_LaunchedSoftwareFirstTime": " iniciou %1$s pela primeira vez",
	"AppActivity_AddedGameToWishlist": " adicionou %1$s à %2$s",
	"AppActivity_Wishlist": "lista de desejos",
	"AppActivity_Achieved_PlusMore": "…e mais outras %1$s",
	"AppActivity_Achieved_PlusMore_Label": "Ver todas as proezas de %1$s",
	"AppActivity_NoActivity": "Não há atividade recente dos desenvolvedores ou dos teus amigos referente a este jogo.",
	"AppActivity_UserStatus_Time": " publicou uma mensagem de estado em %1$s",
	"AppActivity_UserStatus": " publicou uma mensagem de estado",
	"AppActivity_StatusUpdate": "Publica uma mensagem de estado para os teus amigos",
	"AppActivity_StatusUpdate_Post": "Diz algo sobre este jogo aos teus amigos...",
	"AppActivity_StatusUpdate_Software_Post": "Diz algo sobre este software aos teus amigos...",
	"AppActivity_Comment_Reply": "Deixar comentário...",
	"AppActivity_PostStatusUpdate": "Publicar",
	"AppActivity_FetchMore": "Carregar mais atividade",
	"AppActivity_EndofFeed": "Fim da atividade",
	"AppActivity_DeleteUserNews": "Clica para eliminares esta mensagem.",
	"AppActivity_ConfirmDeleteTitle": "Eliminar mensagem de estado",
	"AppActivity_ConfirmDeleteTitle_Desc": "Tens a certeza de que queres eliminar esta mensagem? Esta ação não poderá ser anulada.",
	"AppActivity_RecommendedGame": " publicou uma análise sobre este jogo",
	"AppActivity_RecommendedGame_ReadMore": "Ler mais",
	"AppActivity_RatingDetails": "%1$s pessoas gostam disto",
	"AppActivity_RatingDetails_1Other": "1 pessoa gosta disto: %1$s",
	"AppActivity_RatingDetails_2Others": "%1$s pessoas gostam disto, incluindo %2$s e %3$s",
	"AppActivity_RatingDetails_User": "Gostas disto",
	"AppActivity_RatingDetails_User_1Other": "%1$s pessoas gostam disto, incluindo tu e %2$s",
	"AppActivity_RatingDetails_User_2Others": "%1$s pessoas gostam disto, incluindo tu, %2$s e %3$s",
	"AppActivity_RatingDetails_PublishedFile": "%1$s gostam disto",
	"AppActivity_RateUp": "Gosto",
	"AppActivity_ConfirmDeleteCommentTitle": "Eliminar comentário",
	"AppActivity_ConfirmDeleteCommentTitle_Desc": "Tens a certeza de que queres eliminar este comentário? Esta ação não poderá ser anulada.",
	"AppActivity_MakeCommentsVisible": "Ver comentários anteriores (%1$s)",
	"AppActivity_Settings": "Definições",
	"AppActivity_ViewComments": "Ver comentários",
	"AppActivity_AddComments": "Adicionar comentário",
	"AppActivity_ContributeComments": "Comenta sobre isto",
	"AppActivity_SteamTradingCards_EarnedTradingCards": " ganhou cartas colecionáveis",
	"AppActivity_SteamTradingCards_EarnedTradingCard": " ganhou uma carta colecionável",
	"AppActivity_SteamTradingCards_EarnedBoosterPack": " ganhou um booster",
	"AppActivity_SteamTradingCards_BadgeCrafted": " fabricou uma medalha",
	"AppActivity_ViewLatestNews": "Ver notícias recentes",
	"AppActivity_EventType_GameUpdate": "Atualização de jogo",
	"AppSpotlight_PostGameSummary": "Resumo pós-jogo",
	"AppDetails_Shortcut_Explanation": "Algumas informações detalhadas sobre %1$s estão indisponíveis por ser um mod ou um jogo não-Steam. Mesmo assim, o Steam fará a gestão do arranque do jogo para ti e, na maioria dos casos, o Painel Steam estará disponível dentro do jogo.",
	"AppDetails_Takeover_Update_Header": "Caso não tenhas visto",
	"AppDetails_Takeover_Update_ViewAll": "Ver todas as atualizações (%1$s)",
	"AppDetails_Takeover_Update_ReadMore": "Ler mais",
	"AppDetails_Takeover_DLC_Header": "Novos itens adicionados",
	"AppDetails_Takeover_DLC_ViewInStore": "Ver %1$s na loja",
	"AppDetails_Takeover_Achievements_Header": "Jogaste durante %2$s e alcançaste uma proeza...",
	"AppDetails_Takeover_Achievements_Header_Plural": "Jogaste durante %2$s e alcançaste proezas...",
	"AppDetails_Takeover_TradingCards_Header": "Jogaste durante %2$s e ganhaste um item...",
	"AppDetails_Takeover_TradingCards_Header_Plural": "Jogaste durante %2$s e ganhaste itens...",
	"AppDetails_ViewMyInventory": "Ver inventário",
	"AppDetails_ViewInMyInventory": "Ver no meu inventário",
	"AppDetails_Soundtrack_TotalTracks": "%1$s faixas",
	"AppDetails_Soundtrack_DiscNumber": "Disco %1$s",
	"AppDetails_Soundtrack_TrackCount": "%1$s faixas",
	"AppDetails_Soundtrack_PlayAlbum": "Reproduzir álbum",
	"AppDetails_Soundtrack_DownloadAlbum": "Transferir álbum",
	"AppDetails_Soundtrack_AddToQueue": "Adicionar à fila",
	"AppDetails_Soundtrack_AddToPlaylist": "Adicionar à lista de reprodução",
	"AppDetails_Soundtrack_ViewOnDisk": "Ver no disco",
	"AppDetails_Soundtrack_ViewAdditionalArtwork": "Ver arte adicional",
	"AppDetails_Soundtrack_ViewStorePage": "Ver página na loja",
	"AppDetails_Soundtrack_Support": "Ver página de apoio",
	"AppDetails_Soundtrack_ParentAppLink": "Banda sonora de: %1$s",
	"AppPortraitHover_DownloadStatusTitle": "A transferir",
	"AppPortraitHover_DownloadStatusTitle_Update": "A transferir atualização",
	"AppPortraitHover_DaysSinceLastUpdate": "Atualizado: %1$s",
	"AppPortraitHover_FriendsPlaying": "%1$s amigos a jogar",
	"MajorUpdate_ViewDetails": "Ver detalhes",
	"MajorUpdate_NextUpdate": "Próxima atualização",
	"MajorUpdate_PostTime": "Publicado há %1$s dias às %2$s:%3$s",
	"MajorUpdate_PostTimeToday": "Publicado hoje às %1$s:%2$s",
	"MajorUpdate_WatchNow": "Ver na SteamTV",
	"MajorUpdate_Type0": "Grande atualização",
	"MajorUpdate_Type1": "Stream em direto",
	"MajorUpdate_Type14": "Grande atualização",
	"MajorUpdate_Context_RemoveThisUpdate": "Remover esta atualização",
	"MajorUpdate_Context_ShowMeFewerForApp": "Mostrar menos de %1$s",
	"MajorUpdate_Context_ShowMeMoreForApp": "Mostrar mais de %1$s",
	"MajorUpdate_Context_ResetHiddenUpdates": "Mostrar todas as atualizações",
	"MajorUpdate_Context_WhyAmISeeingThis": "Porque é que me apareceu isto?",
	"MajorUpdate_Context_WhyAmISeeingThis_Text": "Isto é uma grande atualização para um jogo na tua biblioteca que jogaste durante mais de 20 horas.",
	"MajorUpdate_Context_WhyAmISeeingThis_Close": "Fechar",
	"CustomArt_ErrorTitle": "Erro",
	"CustomArt_BadFileType": "O ficheiro tem de estar no formato JPG ou PNG.",
	"CustomArt_UnknownError": "Ocorreu um erro ao definir a imagem.",
	"CustomArt_SetCustomBackground": "Definir imagem de fundo",
	"CustomArt_ClearCustomBackground": "Limpar imagem de fundo",
	"CustomArt_SetCustomLogo": "Definir logótipo",
	"CustomArt_ClearCustomLogo": "Limpar logótipo",
	"CustomArt_EditLogoPosition": "Ajustar posição do logótipo",
	"CustomArt_ResetLogoPosition": "Reiniciar posição do logótipo",
	"CustomArt_DoneEditingLogo": "OK",
	"AppDetails_LibraryInUse": "Biblioteca em uso por",
	"AppDetails_InSharedLibrary": "Da biblioteca de",
	"FriendContextMenu_OpenFriends": "Ver amigos e chat",
	"FriendContextMenu_ViewProfile": "Ver perfil",
	"Generic_ScrollToTop": "Ir para o topo",
	"Generic_ViewGameDetails": "Ver jogo na biblioteca",
	"GameDetails_CollectionContext_GoTo": "Ver coleção",
	"GameDetails_CollectionContext_Remove": "Remover da coleção",
	"ArtworkModal_ViewAll": "Ver todas as capturas de ecrã",
	"ArtworkModal_FileSize": "Tamanho do ficheiro:",
	"ArtworkModal_Posted": "Data de publicação:",
	"ArtworkModal_Size": "Dimensões:",
	"ArtworkModal_CreatedBy": "Autor:",
	"ArtworkModal_ScrollForMore": "Desce para veres comentários",
	"ArtworkModal_ScrollForDetails": "Desce para mais detalhes",
	"CommunityItem_Menu_Report": "Denunciar",
	"ReportItem_Title": "Denunciar este item",
	"ReportItem_Description": "Por favor, descreve de que maneira este item viola os Termos de Serviço do Steam. Inclui todas as informações ou links relevantes na tua denúncia. Uma vez enviada, a denúncia não poderá ser removida no futuro.",
	"ReportItem_Description_Line2": "Itens denunciados deixarão de aparecer na tua biblioteca.",
	"ReportItem_DMCA": "(Se deseja denunciar uma violação de direitos de autor e é o possuidor dos mesmos, aceda ao nosso formulário de aviso de violação de direitos de autor de acordo com a DMCA, disponível %1$s.)",
	"ReportItem_DMCA_LinkText": "aqui",
	"ReportItem_Error": "Ocorreu um problema ao enviar o pedido para os nossos servidores. Por favor, tenta de novo mais tarde.",
	"ReportItem_SubmitReport": "Enviar denúncia",
	"RemoveFreeApp_Title": "Remover da tua conta",
	"RemoveFreeApp_Description": "%1$s foi adicionado à tua conta através de uma licença gratuita. Podes removê-lo da tua conta para que deixe de estar incluído na tua biblioteca Steam e na lista de jogos na tua posse.",
	"RemoveFreeApp_Question": "Tens a certeza de que queres remover %1$s da tua conta?",
	"RemoveFreeApp_Remove": "Remover",
	"RemoveFreeApp_Removing": "A remover %1$s",
	"RemoveFreeApp_Error": "Ocorreu um erro ao tentar remover %1$s",
	"UninstallDialog_Title": "Desinstalar",
	"UninstallDialog_Uninstall": "Desinstalar",
	"UninstallDialog_ErrorMessage": "Não foi possível desinstalar %1$s devido ao seguinte:",
	"UninstallDialog_Busy": "Está atualmente a decorrer outra operação de instalação/desinstalação. Por favor, aguarda pela conclusão dessa ação.",
	"UninstallDialog_SecuROM": "Para desinstalar esta aplicação, é necessária uma ligação à internet.",
	"UninstallDialog_UnknownError": "Ocorreu um erro inesperado ao desinstalar esta aplicação.",
	"UninstallDialog_AppUpdateError": "Erro de desinstalação - %1$s",
	"UninstallDialog_Confirmation_Single": "Gostarias de desinstalar %1$s deste computador? O jogo permanecerá na tua biblioteca de jogos, mas para poderes jogá-lo mais tarde, terás de voltar a fazer o download de todo o respetivo conteúdo.",
	"UninstallDialog_Confirmation_Multiple": "Gostarias de desinstalar os jogos selecionados deste computador? Os mesmos permanecerão na tua biblioteca de jogos, mas para poderes jogá-los mais tarde, terás de voltar a fazer o download de todo o respetivo conteúdo.",
	"UninstallingDialog_Uninstalling": "A desinstalar",
	"UninstallingDialog_UninstallingApp": "A desinstalar %1$s",
	"UninstallingDialog_WaitingForPassword": "A aguardar por palavra-passe",
	"Showcase_AddNewShowcase": "Adicionar prateleira",
	"Showcase_DeleteShowcase": "Eliminar esta prateleira",
	"Showcase_SelectCategory": "Seleciona uma prateleira",
	"Showcase_EmptyShowcaseHint": "Escolhe o que colocar nesta prateleira. Também podes alterar ou eliminar a prateleira a partir daqui!",
	"Showcase_GoToCollection": "Ver coleção",
	"Showcase_GoToAllCollections": "Ver todas as coleções",
	"Showcase_AllYourGames": "Todos os jogos",
	"Showcase_AllCollections": "Coleções",
	"Showcase_RecentGames": "Jogos recentes",
	"Showcase_DoneReordering": "OK",
	"Playtime_TwoWeeks_Minutes": "Tempo de jogo recente: %1$s min.",
	"Playtime_TwoWeeks_Hours": "Tempo de jogo recente: %1$s h.",
	"Playtime_Total_Minutes": "Tempo de jogo total: %1$s min.",
	"Playtime_Total_Hours": "Tempo de jogo total: %1$s h.",
	"Playtime_Minutes": "%1$s minutos",
	"Playtime_Hours": "%1$s horas",
	"Playtime_Recently": "Tempo de jogo recente: %1$s",
	"Playtime_Total": "Tempo de jogo total: %1$s",
	"GameList_Search_NoResults_Title": "Não encontras o que procuras?",
	"GameList_Search_NoResults_Link": "Procurar na Loja Steam",
	"StreamingClient_Select_ThisMachine": "Este computador",
	"StreamingClient_Select_RemotePlayPhone": "Telemóveis",
	"StreamingClient_Select_RemotePlayTablet": "Tablets",
	"StreamingClient_Select_RemotePlayMobile": "Dispositivos móveis",
	"StreamingClient_Select_RemotePlayTV": "TVs",
	"StreamingClient_Select_RemotePlayTVPhone": "TVs e telemóveis",
	"StreamingClient_Select_RemotePlayTVTablet": "TVs e tablets",
	"StreamingClient_Select_RemotePlayTVMobile": "TVs e dispositivos móveis",
	"Beta_BetaTag": "BETA",
	"Beta_Changelist": "Lista de alterações",
	"Beta_GiveFeedback": "Dá-nos a tua opinião",
	"ContextMenu_SaveScreenshot": "Guardar captura de ecrã como...",
	"ContextMenu_BrowseScreenshot": "Abrir pasta da captura de ecrã",
	"ContextMenu_ManageScreenshots": "Gerir capturas de ecrã",
	"SteamChina_DurationControl_Init_1": "Healthy Gaming Advisory",
	"SteamChina_DurationControl_Init_2": "Boycott harmful games; reject game piracy.",
	"SteamChina_DurationControl_Init_3": "Exercise self-protection; avoid deception.",
	"SteamChina_DurationControl_Init_4": "Moderation promotes brain health; excess play is harmful to the body.",
	"SteamChina_DurationControl_Init_5": "Well-planned use of your time will lead to a healthy lifestyle.",
	"Steam_AppUpdateError_0": "nenhum erro",
	"Steam_AppUpdateError_1": "erro desconhecido",
	"Steam_AppUpdateError_2": "atualização pausada",
	"Steam_AppUpdateError_3": "atualização cancelada",
	"Steam_AppUpdateError_4": "atualização suspensa",
	"Steam_AppUpdateError_5": "sem licença",
	"Steam_AppUpdateError_6": "sem ligação à internet",
	"Steam_AppUpdateError_7": "ligação expirou",
	"Steam_AppUpdateError_8": "o conteúdo ainda está encriptado",
	"Steam_AppUpdateError_9": "configuração da aplicação indisponível",
	"Steam_AppUpdateError_10": "erro de leitura de disco",
	"Steam_AppUpdateError_11": "erro de gravação no disco",
	"Steam_AppUpdateError_12": "sem espaço livre suficiente no disco",
	"Steam_AppUpdateError_13": "ficheiros de conteúdo corrompidos",
	"Steam_AppUpdateError_14": "à espera de disco de instalação",
	"Steam_AppUpdateError_15": "diretório de instalação inválido",
	"Steam_AppUpdateError_16": "aplicação em execução",
	"Steam_AppUpdateError_17": "conteúdo partilhado em falta",
	"Steam_AppUpdateError_18": "não instalado",
	"Steam_AppUpdateError_19": "requer atualização",
	"Steam_AppUpdateError_20": "ocupado",
	"Steam_AppUpdateError_21": "servidores indisponíveis",
	"Steam_AppUpdateError_22": "configuração de aplicação inválida",
	"Steam_AppUpdateError_23": "configuração de depot inválida",
	"Steam_AppUpdateError_24": "manifesto indisponível",
	"Steam_AppUpdateError_25": "aplicação não lançada",
	"Steam_AppUpdateError_26": "restringido a certas regiões",
	"Steam_AppUpdateError_27": "cache de conteúdo corrompida",
	"Steam_AppUpdateError_28": "executável em falta",
	"Steam_AppUpdateError_29": "plataforma inválida",
	"Steam_AppUpdateError_30": "sistema de ficheiros não suportado",
	"Steam_AppUpdateError_31": "ficheiros de atualização corrompidos",
	"Steam_AppUpdateError_32": "downloads desativados",
	"Steam_AppUpdateError_33": "biblioteca partilhada bloqueada",
	"Steam_AppUpdateError_34": "compra pendente",
	"Steam_AppUpdateError_35": "outra sessão de jogo existente",
	"Steam_AppUpdateError_36": "download corrompido",
	"Steam_AppUpdateError_37": "disco corrompido",
	"Steam_AppUpdateError_38": "permissões de ficheiros em falta",
	"Steam_AppUpdateError_39": "ficheiro de conteúdo bloqueado",
	"Steam_AppUpdateError_40": "conteúdo indisponível",
	"Steam_AppUpdateError_41": "o executável requer um sistema operativo de 64 bits",
	"Steam_AppUpdateError_42": "ficheiros transferidos em falta",
	"Steam_AppUpdateError_43": "sem espaço livre suficiente para o utilizador - verifica as definições do disco do S.O.",
	"Steam_AppUpdateError_44": "licença de local bloqueada",
	"Steam_AppUpdateError_45": "bloqueado por controlo parental",
	"Steam_AppUpdateError_46": "a criação de processo falhou",
	"Steam_AppUpdateError_47": "aplicação Steam desatualizada",
	"ShareDialog_Title": "Partilhar",
	"ShareUploadScreenshot_Description": "Envia esta captura de ecrã para o teu perfil e feed de atividade no Steam.",
	"ShareUploadScreenshot_AddCaption": "adiciona uma legenda aqui",
	"ShareUploadScreenshot_CaptionHeader": "Legenda:",
	"ShareUploadScreenshot_TagSpoiler": "Marcar como spoiler",
	"ShareUploadScreenshot_CloudUsage": "Vai usar %1$s dos teus %2$s de espaço na cloud",
	"ShareUploadScreenshot_Uploading": "A enviar para o Steam",
	"ShareUploadScreenshot_PermissionDenied": "O Steam não pôde enviar esta captura de ecrã. Não podes enviar conteúdo devido a um banimento ativo na tua conta.",
	"ShareUploadScreenshot_UnexpectedError": "Ocorreu um erro inesperado ao enviar esta captura de ecrã. Por favor, tenta de novo.",
	"DeleteScreenshot_Title": "Eliminar captura de ecrã",
	"DeleteScreenshot_Single": "Tens a certeza de que queres eliminar permanentemente esta captura de ecrã do teu disco rígido?",
	"DeleteScreenshot_Failed": "O Steam não pôde eliminar a captura de ecrã selecionada do teu disco rígido.",
	"AppDetailsAchievement_Hidden": "Proeza oculta",
	"AppDetailsAchievement_HiddenDesc": "Continua a jogar para descobrires esta proeza.",
	"Demo_SpotlightIntro": "Vê o jogo completo",
	"Demo_VisitStorePage": "Visita a página na loja",
	"SteamReviewScore_9": "Extremamente positivas",
	"SteamReviewScore_8": "Muito positivas",
	"SteamReviewScore_7": "Positivas",
	"SteamReviewScore_6": "Praticamente positivas",
	"SteamReviewScore_5": "Neutras",
	"SteamReviewScore_4": "Praticamente negativas",
	"SteamReviewScore_3": "Negativas",
	"SteamReviewScore_2": "Muito negativas",
	"SteamReviewScore_1": "Extremamente negativas"
}
