{
	"Generic_Okay": "OK",
	"Generic_Close": "Đóng",
	"Generic_Open": "Mở",
	"Generic_GotIt": "Đã rõ!",
	"AppType_0": "Không hợp lệ",
	"AppType_1": "Trò chơi",
	"AppType_2": "Phần mềm",
	"AppType_4": "Công cụ",
	"AppType_20": "DLC",
	"AppType_800": "Video",
	"AppType_2000": "Nhạc",
	"AppType_Singular_0": "Không hợp lệ",
	"AppType_Singular_1": "trò chơi",
	"AppType_Singular_2": "ứng dụng",
	"AppType_Singular_4": "công cụ",
	"AppType_Singular_20": "DLC",
	"AppType_Singular_800": "video",
	"AppType_Singular_2000": "nhạc",
	"AppType_Singular_8000": "truyện tranh",
	"AppType_Singular_40000000": "lối tắt",
	"FilterEdit_SavedFilters": "Bộ lọc đã lưu",
	"FilterEdit_FirstColumnHeader": "Lọc theo",
	"FilterEdit_Customize": "Tùy chỉnh",
	"FilterEdit_SearchModeHeader": "Lọc nâng cao",
	"FilterEdit_CollectionModeHeader": "Chỉnh sửa lọc bộ sưu tập",
	"CollectionEdit_CollectionNameField": "Tên bộ sưu tập:",
	"CollectionEdit_RenameButton": "Đổi tên bộ sưu tập",
	"Collection_DynamicCollection": "Bộ sưu tập linh hoạt",
	"FilterEdit_AdvancedTooltip": "Sử dụng tùy chọn lọc nâng cao để làm rõ hơn danh sách trò chơi của bạn theo thể loại, tính năng, v.v...",
	"FilterEdit_SelectedFilters": "Bộ lọc đã chọn",
	"FilterEdit_SaveCollectionNameInputPrompt": "Đặt tên cho bộ sưu tập",
	"FilterEdit_SaveOverwrite": "Đã có bộ sưu tập \"%1$s\". Ghi đè lên?",
	"FilterEdit_SaveCollection": "Lưu dưới dạng bộ sưu tập",
	"FilterEdit_SaveDynamicCollectionWithIcon": "Lưu dưới dạng bộ sưu tập linh hoạt %1$s",
	"FilterEdit_SaveDynamicCollectionNoIcon": "Lưu dưới dạng bộ sưu tập linh hoạt",
	"FilterEdit_SaveCollectionVerbose": "Lưu tìm kiếm này vào bộ sưu tập để bạn có thể sử dụng lại sau này. Bạn vẫn có thể chỉnh sửa, đổi tên, hoặc xóa một bộ sưu tập trong tương lai, hay kéo thả các lựa chọn ra vào.",
	"FilterEdit_SaveStandardCollectionButtonDesc": "Bộ sưu tập là cách đơn giản để sắp xếp thư viện của bạn. Kéo thả các tựa vào trong bộ sưu tập hoặc nhấp chuột phải vào tựa sản phẩm để thêm chúng vào bộ sưu tập đã có.",
	"FilterEdit_SaveDynamicCollectionButtonDesc": "Bộ sưu tập linh hoạt sử dụng các bộ lọc để cập nhật khi thư viện của bạn mở rộng.",
	"FilterEdit_SelectCollectionType": "Chọn loại bộ sưu tập",
	"FilterEdit_SelectCollectionTypeButtonCreate": "Tạo bộ sưu tập",
	"FilterEdit_SelectCollectionTypeButtonCreateDynamic": "Tạo bộ sưu tập linh hoạt",
	"FilterEdit_RequiredField": "( BẮT BUỘC )",
	"FilterEdit_SearchPrompt": "Tìm theo tên",
	"FilterEdit_ClearSearch": "Thoát tìm kiếm",
	"FilterEdit_SearchResults": "Kết quả tìm kiếm",
	"FilterEdit_CollectionsHiddenPromptTitle": "Đã ẩn bộ sưu tập",
	"FilterEdit_CollectionsHiddenPrompt": "Bạn có muốn thay đổi kiểu hiển thị danh sách trò chơi để có thể nhìn thấy bộ sưu tập mới?",
	"FilterEdit_AcceptGameListViewChange": "Có, xem bộ sưu tập",
	"FilterEdit_RejectGameListViewChange": "Không, đừng thay đổi cách nhìn",
	"AdvancedSearch_PaneTitle": "Tìm theo loại",
	"AdvancedSearch_PlayerSection": "Người chơi",
	"AdvancedSearch_HardwareSection": "Hỗ trợ phần cứng",
	"AdvancedSearch_FeatureSection": "Tính năng",
	"AdvancedSearch_StateSection": "Trạng thái chơi",
	"AdvancedSearch_GenreSection": "Thể loại",
	"AdvancedSearch_StoreTagSection": "Nhãn cửa hàng",
	"AdvancedSearch_StoreTagPrompt": "nhập một nhãn",
	"FilterCategory_1": "Trạng thái",
	"FilterCategory_Features": "TÍNH NĂNG",
	"FilterCategory_3": "Danh mục",
	"FilterCategory_4": "Nhãn cửa hàng",
	"FilterCategory_Type": "LOẠI",
	"FilterCategory_Genre": "THỂ LOẠI",
	"FilterCategory_PlayState": "TRẠNG THÁI",
	"FilterElement_VR": "VR",
	"FilterElement_Tooltip_VR": "Bao gồm các trò chơi hỗ trợ thiết bị phần cứng thực tế ảo.",
	"FilterElement_Installed": "Cài đặt trên máy",
	"FilterElement_Tooltip_Installed": "Bao gồm các trò chơi được cài trên máy tính này.",
	"FilterElement_ReadyToPlay": "Sẵn sàng chơi",
	"FilterElement_Tooltip_ReadyToPlay": "Bao gồm các trò chơi mà bạn có thể chơi lân cận hoặc phát sóng từ một máy tính khác.",
	"FilterElement_PlayedPreviously": "Từng chơi",
	"FilterElement_Tooltip_PlayedPreviously": "Bao gồm các trò mà bạn đã từng chơi.",
	"FilterElement_Unplayed": "Chưa chơi",
	"FilterElement_Tooltip_Unplayed": "Bao gồm các trò mà bạn chưa từng chơi lần nào.",
	"FilterElement_FullControllerSupport": "Tay cầm (đầy đủ)",
	"FilterElement_Tooltip_FullControllerSupport": "Bao gồm các trò chơi mà bạn có thể chơi hoàn toàn với tay cầm.",
	"FilterElement_PartialControllerSupport": "Tay cầm (bán phần)",
	"FilterElement_Tooltip_PartialControllerSupport": "Bao gồm các trò chơi mà bạn có thể chơi với tay cầm nhưng sẽ cần chuột và bàn phím để cài đặt hoặc tương tác giới hạn.",
	"FilterElement_VRSupported": "Hỗ trợ VR",
	"FilterElement_TradingCards": "Thẻ trao đổi",
	"FilterElement_Tooltip_TradingCards": "Bao gồm các trò chơi có thẻ trao đổi Steam.",
	"FilterElement_Workshop": "Workshop",
	"FilterElement_Tooltip_Workshop": "Bao gồm các trò chơi có hỗ trợ Steam Workshop.",
	"FilterElement_Achievements": "Thành tựu",
	"FilterElement_Tooltip_Achievements": "Bao gồm các trò chơi có thành tựu Steam.",
	"FilterElement_SinglePlayer": "Chơi đơn",
	"FilterElement_Tooltip_SinglePlayer": "Bao gồm các trò chơi đơn.",
	"FilterElement_MultiPlayer": "Chơi nhiều người",
	"FilterElement_Tooltip_MultiPlayer": "Bao gồm các trò chơi nhiều người.",
	"FilterElement_CoOp": "Phối hợp nhiều người",
	"FilterElement_Tooltip_CoOp": "Bao gồm các trò chơi phối hợp nhiều người.",
	"FilterElement_GenreAction": "Hành động",
	"FilterElement_Tooltip_GenreAction": "Bao gồm các trò chơi hành động.",
	"FilterElement_GenreAdventure": "Phiêu lưu",
	"FilterElement_Tooltip_GenreAdventure": "Bao gồm các trò chơi phiêu lưu.",
	"FilterElement_GenreCasual": "Đơn giản",
	"FilterElement_Tooltip_GenreCasual": "Bao gồm các trò chơi đơn giản.",
	"FilterElement_GenreIndie": "Indie",
	"FilterElement_Tooltip_GenreIndie": "Bao gồm các trò chơi indie.",
	"FilterElement_GenreMMO": "MMO",
	"FilterElement_Tooltip_GenreMMO": "Bao gồm các trò chơi MMO.",
	"FilterElement_GenreRacing": "Đua tốc độ",
	"FilterElement_Tooltip_GenreRacing": "Bao gồm các trò chơi đua xe.",
	"FilterElement_GenreRPG": "Nhập vai",
	"FilterElement_Tooltip_GenreRPG": "Bao gồm các trò chơi nhập vai.",
	"FilterElement_GenreSimulation": "Mô phỏng",
	"FilterElement_Tooltip_GenreSimulation": "Bao gồm các trò chơi mô phỏng.",
	"FilterElement_GenreSports": "Thể thao",
	"FilterElement_Tooltip_GenreSports": "Bao gồm các trò chơi thể thao.",
	"FilterElement_GenreStrategy": "Chiến thuật",
	"FilterElement_Tooltip_GenreStrategy": "Bao gồm các trò chơi chiến thuật.",
	"FilterElement_Tooltip_StoreTag": "Bao gồm ứng dụng nhãn %1$s trên Steam.",
	"CollectionViewHeader_Tooltip_ManuallyAddedApp": "Trò chơi này được kéo vào bộ sưu tập bởi người dùng.",
	"CollectionViewHeader_Tooltip_ManuallyRemovedApp": "Trò chơi này bị gỡ bỏ khỏi bộ sưu tập.",
	"CollectionView_EmptyReadOnlyCollection": "Không có gì hiện ở đây",
	"CollectionView_EmptyDynamicCollection_Line1": "Không có trò chơi phù hợp với bộ lọc này!",
	"CollectionView_EmptyDynamicCollection_Line2": "Thay đổi bộ lọc hoặc kéo trò chơi vào để bắt đầu bộ sưu tập này.",
	"CollectionView_EmptyCollection": "Kéo trò chơi vào đây để dựng bộ sưu tập này.",
	"CollectionView_EmptyCollection_BecauseFilter": "%1$s trò chơi trong bộ sưu tập này đang không hiển thị, do bộ lọc mà bạn chọn.",
	"CollectionView_EmptyCollection_BecauseFilter_Plural": "%1$s trò chơi trong bộ sưu tập này đang không hiển thị, do bộ lọc mà bạn chọn.",
	"CollectionView_MissingCollection": "Không tìm thấy bộ sưu tập.",
	"CollectionView_GamesExcluded": "+%1$s",
	"CollectionView_GamesExcluded_Desc": "tựa chưa sẵn sàng chơi",
	"AllCollectionsView_Title": "Bộ sưu tập của bạn",
	"AllCollectionsView_InfoIcon": "Tạo %1$s để sắp xếp các tựa theo ý muốn, hoặc tạo %2$s để nhóm các tựa theo những bộ lọc nhất định. %3$s",
	"AllCollectionsView_InfoIconCollections": "Bộ sưu tập",
	"AllCollectionsView_InfoIconDynamicCollections": "Bộ sưu tập linh hoạt",
	"AllCollectionsView_InfoIconFav": "%1$s của bạn sẽ luôn được hiển thị ở trên cùng của trang.",
	"AllCollectionsView_InfoIconFavorites": "Yêu thích",
	"AllCollectionsView_AddCollection": "Tạo một bộ sưu tập mới",
	"AllCollectionsView_DragToAddCollection": "Kéo vào đây để tạo bộ sưu tập mới",
	"GameList_Home": "Trang chủ thư viện",
	"GameList_Search": "Tìm kiếm",
	"GameList_Category_Uncategorized": "Chưa phân loại",
	"GameList_Category_Favorites": "Yêu thích",
	"GameList_Category_Hidden": "Ẩn",
	"GameList_Category_Hidden_Tooltip": "Trò chơi được ẩn sẽ không xuất hiện trên thư viện của bạn trừ phi chủ động tìm kiếm. Bạn có thể xem toàn bộ trò chơi được ẩn trừ trình đơn 'Xem' trên đầu.",
	"GameList_Category_YourCollections": "Bộ sưu tập của bạn",
	"GameList_Category_SharedLibraries": "Thư viện chia sẻ",
	"GameList_SectionHeader_SearchResults": "Kết quả từ tìm kiếm và bộ lọc",
	"GameList_SectionHeader_AddedManually": "Được thêm vào thủ công",
	"GameList_SectionHeader_RemovedManually": "Được gỡ ra thủ công",
	"GameList_SectionHeader_NoRecentActivity": "Không ghi nhận được hoạt động nào",
	"GameList_View_Collections": "Bộ sưu tập của bạn",
	"GameList_View_ThisCollection": "Xem bộ sưu tập này",
	"GameList_View_LibraryList": "Danh sách lọc",
	"GameList_View_OneCollection": "Xem bộ sưu tập",
	"GameList_View_SearchResults": "Kết quả tìm kiếm",
	"GameList_View_ShowAllCollections": "Xem tất cả bộ sưu tập",
	"GameList_View_GroupByCollections": "Nhóm theo bộ sưu tập",
	"GameList_View_ExitSearch": "Rời tìm kiếm",
	"GameList_View_All": "Tất cả",
	"GameList_View_SortByRecent": "Xếp theo hoạt động gần đây",
	"GameList_View_ShowOnlyReadyToPlay": "Chỉ hiện trò chơi có thể mở ngay",
	"GameList_View_ShowingOnlyReadyToPlay": "Chỉ hiện trò có thể dùng ngay",
	"GameList_View_ShowOnlyVR": "Chỉ hiện trò chơi VR",
	"GameList_View_ReadyToPlay_ToolTip1": "• Đã cài đặt trên máy này",
	"GameList_View_ReadyToPlay_ToolTip2": "• Có thể phát sóng từ một máy khác",
	"GameList_Entry_ReadyToPlay_ToolTip": "Sẽ được phát sóng từ một máy khác",
	"Shelf_SectionHeader_ExpandTooltip": "Mở kệ để hiện thêm nhiều hàng",
	"Shelf_SectionHeader_ExpandTooltipFilter": "Mở kệ để hiện thêm nhiều hàng, %1$s tựa không hiển thị do bộ lọc của bạn",
	"GameList_SectionHeader_AppCountToolTip": "%1$s tựa không hiển thị do bộ lọc của bạn",
	"GameList_SectionHeader_AppCountToolTipAllHidden": "Không có tựa nào hiển thị do bộ lọc của bạn",
	"CollectionAction_ViewOnlyThis": "Chỉ xem bộ sưu tập này",
	"CollectionAction_ViewOnlyThisFavorites": "Chỉ xem mục yêu thích",
	"CollectionAction_ViewOnlyThisUncategorized": "Chỉ xem sản phẩm chưa phân loại",
	"CollectionAction_Collapse": "Đóng",
	"CollectionAction_Expand": "Mở",
	"CollectionAction_Manage": "Quản lý",
	"CollectionAction_Edit": "Chỉnh sửa lọc bộ sưu tập",
	"CollectionAction_Rename": "Đổi tên bộ sưu tập",
	"CollectionAction_Delete": "Xóa bộ sưu tập",
	"CollectionAction_DeleteDialog": "Xóa bộ sưu tập",
	"CollectionAction_ConfirmDelete": "Bạn có chắc mình muốn xóa vĩnh viễn bộ sưu tập \"%1$s\"?",
	"CollectionAction_SaveFailed": "Không thể lưu bộ sưu tập \"%1$s\"",
	"CollectionAction_CannotOverwrite": "Không thể ghi đè lên bộ sưu tập \"%1$s\". Xin vui lòng chọn một tên mới.",
	"CollectionAction_DeleteFailed": "Không thể xóa bộ sưu tập \"%1$s\"",
	"LibraryHome_FriendsActivity": "Hoạt động bạn bè",
	"LibraryHome_RecentGames": "Trò chơi gần đây",
	"LibraryHome_NewUpdates": "Có gì mới mẻ",
	"LibraryHome_YourCollection": "Thư viện đầy đủ của bạn",
	"LibraryHome_RecentFriendsActivity": "Hoạt động bạn bè gần đây",
	"Library_FriendsActivity_HotRightNowHeading": "Có gì hot",
	"Library_FriendsActivity_HotRightNowHover": "Chúng tôi hiển thị cho bạn trò chơi này bởi một vài người bạn đang chơi lúc này.",
	"Library_FriendsActivity_TrendingHeading": "Thịnh hành",
	"Library_FriendsActivity_TrendingHover": "Chúng tôi hiển thị cho bạn trò chơi này bởi vì một vài người bạn chơi trò này hơn trong tuần qua nhiều hơn so với tuần trước.",
	"Library_FriendsActivity_BeingDiscussedHeading": "Đang có thảo luận",
	"Library_FriendsActivity_BeingDiscussedHover": "Chúng tôi hiển thị cho bạn trò chơi này bởi vì bạn bè đã đăng ảnh chụp hoặc tin nhắn trạng thái.",
	"Library_FriendsActivity_RecentlyPurchasedHeading": "Mua gần đây",
	"Library_FriendsActivity_RecentlyPurchasedHover": "Chúng tôi hiển thị cho bạn trò chơi này bởi vì bạn gần đây đã mua nó và bạn bè cũng đang chơi.",
	"Library_FriendsActivity_UnownedHeading": "Thử cảm giác mới",
	"Library_FriendsActivity_UnownedHover": "Chúng tôi hiển thị cho bạn trò chơi này bởi vì nó đang phổ biến với bạn bè và bạn không sở hữu nó.",
	"Library_FriendsActivity_PopularHeading": "Phổ biến",
	"Library_FriendsActivity_PopularHover": "Chúng tôi hiển thị cho bạn trò chơi này bởi vì có rất nhiều bạn bè đang chơi trò này gần đây.",
	"Library_FriendsActivity_DontForgetHeading": "Đừng quên",
	"Library_FriendsActivity_DontForgetHover": "Chúng tôi hiển thị cho bạn trò chơi này bởi vì bạn không hề chơi nó gần đây, nhưng bạn bè thì có.",
	"Library_FriendsActivity_NewToGroupHeading": "Mới với bạn bè của bạn",
	"Library_FriendsActivity_NewToGroupHover": "Chúng tôi hiển thị cho bạn trò chơi này bởi vì bạn bè bắt đầu chơi trò này gần đây.",
	"Library_FriendsActivity_ReturnedToGroupHeading": "Tái xuất giang hồ",
	"Library_FriendsActivity_ReturnedToGroupHover": "Chúng tôi hiển thị cho bạn trò chơi này bởi vì bạn bè bắt đầu chơi lại trò chơi này.",
	"Library_Recent_NoRecentGames_GamesOwned": "Bạn có (%1$s) trò chơi.",
	"Library_Recent_NoRecentGames_StoreLink": "Ghé thăm %1$s để thêm trò chơi:",
	"Library_Recent_NoRecentGames_SteamStore": "Cửa hàng Steam",
	"Library_Recent_NoRecentGames_FreeToPlay": "Trò chơi miễn phí",
	"Library_Recent_NoRecentGames_GamesOnSale": "Trò chơi đang hạ giá",
	"Library_Recent_NoRecentGames_NewReleases": "Mới phát hành",
	"Library_Recent_NoRecentGames_ActivateProduct": "Kích hoạt một sản phẩm",
	"Library_Recent_NoRecentGames_RedeemCode": "Kích hoạt mã ví",
	"Library_SortCollectionBy": "Sắp xếp",
	"Library_SortByFavoritesFirst": "Yêu thích trước",
	"Library_SortByAlphabetical": "Theo bảng chữ cái",
	"Library_SortByPctAchievementsComplete": "% thành tựu hoàn thành",
	"Library_SortByLastUpdated": "Cập nhật lần cuối",
	"Library_SortByHoursPlayed": "Theo giờ chơi",
	"Library_SortByLastPlayed": "Chơi lần cuối",
	"Library_SortByReleaseDate": "Theo ngày phát hành",
	"Library_SortByAddedToLibrary": "Ngày thêm vào thư viện",
	"Library_SortBySizeOnDisk": "Kích thước",
	"Library_SortByMetacriticScore": "Điểm Metacritic",
	"Library_SortByFriendsPlaying": "Theo bạn bè chơi",
	"Library_InstalledOnlyCheck": "Chỉ khi đã cài đặt",
	"GridSection_Favorites": "Yêu thích",
	"GridSection_EverythingElse": "Linh tinh",
	"GridSection_Over100Hours": "Trên 100 tiếng",
	"GridSection_Over60Hours": "Trên 60 tiếng",
	"GridSection_Over40Hours": "Trên 40 tiếng",
	"GridSection_Over20Hours": "Trên 20 tiếng",
	"GridSection_Over10Hours": "Trên 10 tiếng",
	"GridSection_Over1Hour": "Trên 1 tiếng",
	"GridSection_LessThan1Hour": "Dưới 1 tiếng",
	"GridSection_Over90Metacritic": "Trên 90",
	"GridSection_Over80Metacritic": "Trên 80",
	"GridSection_Over70Metacritic": "Trên 70",
	"GridSection_Over50Metacritic": "Trên 50",
	"GridSection_EverythingElseMetacritic": "Linh tinh",
	"GridSection_UnknownReleaseDate": "Không rõ",
	"GridSection_GreaterThan100GB": "Nhiều hơn 100GB",
	"GridSection_GreaterThan50GB": "Nhiều hơn 50GB",
	"GridSection_GreaterThan20GB": "Nhiều hơn 20GB",
	"GridSection_LessThan20GB": "Ít hơn 20GB",
	"GridSection_NoSizeOnDisk": "Không có dung lượng",
	"GridSection_NotInstalled": "Chưa được cài",
	"GridSection_MoreThan10YearsAgo": "Hơn 10 năm trước",
	"GridSection_Never": "Không bao giờ",
	"AppDetails_SectionTitle_Activity": "Hoạt động",
	"AppDetails_SectionTitle_Friends": "Bạn bè đã chơi qua",
	"AppDetails_SectionTitle_Friends_Software": "Bạn bè dùng qua",
	"AppDetails_SectionTitle_Achievements": "Thành tựu",
	"AppDetails_SectionTitle_TradingCards": "Thẻ trao đổi",
	"AppDetails_SectionTitle_Screenshots": "Ảnh chụp",
	"AppDetails_SectionTitle_Updates": "Sự kiện và cập nhật gần đây",
	"AppDetails_SectionTitle_DLC": "DLC",
	"AppDetails_SectionTitle_LastPlayed": "Lần cuối chơi",
	"AppDetails_SectionTitle_LastLaunched": "Lần khởi chạy cuối",
	"AppDetails_SectionTitle_PlayTime": "Thời gian chơi",
	"AppDetails_SectionTitle_UsageTime": "Thời gian dùng",
	"AppDetails_SectionTitle_Workshop": "Steam Workshop",
	"AppDetails_SectionTitle_Community": "Nội dung cộng đồng",
	"AppDetails_SectionTitle_Links": "Liên kết",
	"AppDetails_SectionTitle_SignIn_Pre": "Đăng nhập",
	"AppDetails_SectionTitle_SignIn": "%1$s để xem hoạt động của bạn bè",
	"AppDetails_SectionTitle_OpenFriends": "Mở danh sách bạn bè",
	"AppDetails_SectionTitle_OfflineMode": "Chế độ ngắt mạng",
	"AppDetails_Community_Tooltip1": "Mục này bao gồm ảnh chụp, tác phẩm, video, hướng dẫn, và những thứ khác do cộng đồng đăng lên.",
	"AppDetails_Community_Tooltip2": "Bạn có thể thích, chia sẻ, bình luận, hoặc tố cáo nội dung này.",
	"AppDetails_Community_Guide": "Hướng dẫn cộng đồng",
	"AppDetails_Links_Store": "Trang cửa hàng",
	"AppDetails_Links_Community": "Trung tâm cộng đồng",
	"Bbcode_Originally_Posted_By": "Nguyên văn bởi",
	"AppDetails_InOfflineMode": "Steam đang chạy trong chế độ ngắt mạng. Trong chế độ này, nhiều tính năng thư viện Steam của bạn, ví dụ như hoạt động và bạn bè, sẽ không hoạt động. Nối mạng để xem nội dung này.",
	"AppDetails_GoOnline": "Nối mạng",
	"GameAction_Stop": "Dừng",
	"GameAction_Cancel": "Hủy",
	"GameAction_Install": "Cài đặt",
	"GameAction_Uninstall": "Gỡ cài đặt",
	"GameAction_Play": "Chơi",
	"GameAction_Launch": "Khởi động",
	"GameAction_PreLoad": "Nạp trước nội dung",
	"GameAction_Update": "Cập nhật",
	"GameAction_Download": "Tải về",
	"GameAction_Resume": "Tiếp tục",
	"GameAction_Pause": "Tạm dừng",
	"GameAction_BorrowApp": "Mượn",
	"GameAction_PurchaseApp": "Mua",
	"GameAction_GameProperties": "Thiết lập...",
	"GameAction_AddToFavorites": "Thêm vào yêu thích",
	"GameAction_RemoveFromFavorites": "Xóa khỏi ưa thích",
	"GameAction_AddToHidden": "Ẩn trò chơi này",
	"GameAction_RemoveFromHidden": "Cho hiển thị lại",
	"GameAction_AddToFamilyGames": "Thêm vào trò chơi gia đình",
	"GameAction_RemoveFromFamilyGames": "Gỡ khỏi trò chơi gia đình",
	"GameAction_RemoveShortcut": "Xóa trò chơi ngoài Steam",
	"GameAction_AddToCollection": "Thêm vào",
	"GameAction_RemoveFromCollection": "Gỡ khỏi",
	"GameAction_CreateDesktopShortcut": "Thêm lối tắt desktop",
	"GameAction_BackUpFiles": "Sao lưu tệp trò chơi...",
	"GameAction_Stream": "Phát sóng",
	"GameAction_Connect": "Kết nối",
	"GameAction_SetCustomArtwork": "Đặt ảnh tùy chọn",
	"GameAction_ClearCustomArtwork": "Xóa ảnh tùy chọn",
	"GameAction_ViewCDKeys": "Mã CD",
	"GameAction_ControllerConfiguration": "Thiết lập tay cầm",
	"GameAction_RemoveAppFromCollection": "KÉO VÀO ĐÂY để gỡ %1$s khỏi bộ sưu tập %2$s",
	"GameAction_RemoveAppFromMultipleCollections": "DRAG HERE to remove %1$s from these collections",
	"GameAction_RemoveMultipleAppsFromCollection": "KÉO VÀO ĐÂY để gỡ các ứng dụng này khỏi %1$s",
	"GameAction_RemoveMultipleAppsFromMultipleCollections": "KÉO VÀO ĐÂY để gỡ bỏ các ứng dụng này những bộ sưu tập",
	"GameAction_NavigateToAllCollectionsWithDrag": "KÉO và GIỮ Ở ĐÂY để xem tất cả bộ sưu tập",
	"GameAction_AddToCollectionOption_NewCollection": "Bộ sưu tập mới...",
	"GameAction_NewCollectionDialogTitle": "Bộ sưu tập mới",
	"GameAction_Manage": "Quản lý",
	"GameAction_Favorite": "Thêm vào yêu thích",
	"GameAction_UnFavorite": "Trong danh sách ưa thích",
	"GameAction_ViewDetails": "Hiện thêm chi tiết",
	"GameAction_ViewDetails_Collapse": "Ẩn bớt chi tiết",
	"GameAction_ViewDetails_ScrollUp": "Cuộn lên đầu",
	"GameActionPlural_Install": "Cài đặt tắt cả",
	"GameActionPlural_Uninstall": "Gỡ cài đặt tất cả",
	"GameActionPlural_PreLoad": "Tải trước tất cả",
	"GameActionPlural_Update": "Cập nhật tất cả",
	"GameActionPlural_Download": "Tải xuống tất cả",
	"GameActionPlural_Resume": "Tiếp tục lại toàn bộ",
	"GameActionPlural_AddToFavorites": "Thêm tất cả vào yêu thích",
	"GameActionPlural_RemoveFromFavorites": "Gỡ bỏ tất cả khỏi yêu thích",
	"GameActionPlural_AddToHidden": "Ẩn toàn bộ các trò chơi này",
	"GameActionPlural_RemoveFromHidden": "Gỡ bỏ tất cả khỏi mục ẩn",
	"GameActionPlural_AddToFamilyGames": "Thêm tất cả vào trò chơi gia đình",
	"GameActionPlural_RemoveFromFamilyGames": "Gỡ tất cả khỏi trò chơi gia đình",
	"GameActionPlural_RemoveShortcut": "Xóa tất cả trò chơi ngoài Steam",
	"GameActionPlural_AddToCollection": "Thêm tất cả vào",
	"GameActionPlural_RemoveFromCollection": "Gỡ tất cả khỏi",
	"GameActionPlural_CreateDesktopShortcut": "Thêm lối tắt desktop",
	"GameActionPlural_BackUpFiles": "Sao lưu tệp trò chơi...",
	"DisplayStatus_Launching": "Đang khởi động",
	"DisplayStatus_Uninstalling": "Đang gỡ bỏ",
	"DisplayStatus_Installing": "Đang cài đặt",
	"DisplayStatus_Running": "Đang chạy",
	"DisplayStatus_Validating": "Đang xác thực",
	"DisplayStatus_Updating": "Đang cập nhật",
	"DisplayStatus_Downloading": "Đang tải xuống",
	"DisplayStatus_Synchronizing": "Đang đồng bộ Steam Cloud",
	"DisplayStatus_ReadyToInstall": "Sẵn sàng để cài",
	"DisplayStatus_ReadyToPreload": "Sẵn sàng để tải trước",
	"DisplayStatus_ReadyToLaunch": "Sẵn sàng khởi chạy",
	"DisplayStatus_RegionRestricted": "Không có tại khu vực hiện hành",
	"DisplayStatus_PresaleOnly": "Ứng dụng này chưa ra mắt",
	"DisplayStatus_InvalidPlatform": "Hiện có trên",
	"DisplayStatus_PreloadComplete": "Tải trước hoàn thành",
	"DisplayStatus_BorrowerLocked": "Hiện không thể dùng chia sẻ gia đình cho thư viện này",
	"DisplayStatus_UpdatePaused": "Cập nhật tạm dừng",
	"DisplayStatus_UpdateQueued": "Cập nhật chờ lượt",
	"DisplayStatus_UpdateRequired": "Cần cập nhật",
	"DisplayStatus_UpdateDisabled": "Cập nhật hiện được tắt do Steam đang ở chế độ ngắt mạng. Nối mạng để hoàn thành cập nhật trò chơi này.",
	"DisplayStatus_DownloadPaused": "Tải về tạm dừng",
	"DisplayStatus_DownloadQueued": "Tải về chờ lượt",
	"DisplayStatus_DownloadRequired": "Cần tải về",
	"DisplayStatus_DownloadDisabled": "Tải về hiện được tắt do Steam đang ở chế độ ngắt mạng. Nối mạng để hoàn thành tải về trò chơi này.",
	"DisplayStatus_LicensePending": "Đơn hàng của bạn chưa hoàn thành.",
	"DisplayStatus_LicenseExpired": "Giấy phép đã hết hạn",
	"DisplayStatus_AvailForFree": "Có thể dùng miễn phí",
	"DisplayStatus_AvailToBorrow": "Có thể mượn",
	"DisplayStatus_AvailGuestPass": "Có vé khách",
	"DisplayStatus_Purchase": "Có thể mua",
	"DisplayStatus_Compact_Launching": "Đang khởi động",
	"DisplayStatus_Compact_Uninstalling": "Đang gỡ bỏ",
	"DisplayStatus_Compact_Installing": "Đang cài đặt",
	"DisplayStatus_Compact_Running": "Đang chạy",
	"DisplayStatus_Compact_Validating": "Đang xác thực",
	"DisplayStatus_Compact_Updating": "Đang cập nhật",
	"DisplayStatus_Compact_Downloading": "Đang tải về",
	"DisplayStatus_Compact_Synchronizing": "Đang đồng bộ với Steam Cloud",
	"DisplayStatus_Compact_ReadyToInstall": "Sẵn sàng để cài",
	"DisplayStatus_Compact_ReadyToPreload": "Sẵn sàng để tải trước",
	"DisplayStatus_Compact_ReadyToLaunch": "Sẵn sàng khởi chạy",
	"DisplayStatus_Compact_RegionRestricted": "Không có tại khu vực này",
	"DisplayStatus_Compact_PresaleOnly": "Trò chơi chưa được phát hành",
	"DisplayStatus_Compact_InvalidPlatform": "Hiện có trên",
	"DisplayStatus_Compact_ParentalBlocked": "Bị chặn bởi hiển thị gia đình Steam",
	"DisplayStatus_Compact_PreloadComplete": "Tải trước hoàn thành",
	"DisplayStatus_Compact_BorrowerLocked": "Chia sẻ gia đình không khả dụng",
	"DisplayStatus_Compact_UpdatePaused": "Cập nhật tạm dừng",
	"DisplayStatus_Compact_UpdateQueued": "Cập nhật chờ lượt",
	"DisplayStatus_Compact_UpdateRequired": "Cần cập nhật",
	"DisplayStatus_Compact_UpdateDisabled": "Không thể cập nhật trong chế độ ngắt mạng.",
	"DisplayStatus_Compact_DownloadPaused": "Tải về tạm dừng",
	"DisplayStatus_Compact_DownloadQueued": "Tải về chờ lượt",
	"DisplayStatus_Compact_DownloadRequired": "Cần tải về",
	"DisplayStatus_Compact_DownloadDisabled": "Không thể tải về trong chế độ ngắt mạng.",
	"DisplayStatus_Compact_LicensePending": "Hoàn thành đơn hàng",
	"DisplayStatus_Compact_LicenseExpired": "Giấy phép đã hết hạn",
	"DisplayStatus_Compact_AvailForFree": "Có thể dùng miễn phí",
	"DisplayStatus_Compact_AvailToBorrow": "Có thể mượn",
	"DisplayStatus_Compact_AvailGuestPass": "Có vé khách",
	"DisplayStatus_Compact_Purchase": "Có thể mua",
	"DisplayStatus_ReleaseDate": "Ra mắt vào %1$s",
	"DisplayStatus_CustomReleaseDate": "Ngày ra mắt dự kiến: %1$s",
	"Downloads_State_Bytes_Of_Bytes": "%1$s trên %2$s",
	"Downloads_State_None": "",
	"Downloads_State_Reconfiguring": "Bắt đầu tải xuống",
	"Downloads_State_Validating": "Đang xác thực tệp",
	"Downloads_State_AddingFiles": "Đang chép tệp",
	"Downloads_State_Preallocating": "Đang dự trữ dung lượng",
	"Downloads_State_Downloading": "",
	"Downloads_State_Staging": "",
	"Downloads_State_Committing": "Đang hoàn thiện",
	"Downloads_State_Verifying": "Đang xác minh tải xuống",
	"Downloads_State_Stopping": "Đang dừng tải xuống",
	"Downloads_State_Running": "",
	"Downloads_State_SecondsRemaining": "Còn %1$s giây",
	"Downloads_State_MinutesRemaining": "Còn %1$s phút",
	"Downloads_State_Calculating": "Đang tính toán...",
	"LaunchApp_Action_UpdatingAppInfo": "Đang kiểm tra cấu hình",
	"LaunchApp_Action_ShowEula": "Hiện thỏa thuận EULA",
	"LaunchApp_Action_DownloadingDepots": "Đang tải nội dung (%1$s%)",
	"LaunchApp_Action_DownloadingWorkshop": "Đang tải workshop (%1$s%)",
	"LaunchApp_Action_UpdatingDRM": "Đang cập nhật tệp thực thi",
	"LaunchApp_Action_GettingLegacyKey": "Đang cập nhật mã sản phẩm",
	"LaunchApp_Action_RunningInstallScript": "Đang chạy mã cài đặt (%1$s)",
	"LaunchApp_Action_SynchronizingCloud": "Đang đồng bộ đám mây",
	"LaunchApp_Action_VerifyingFiles": "Đang xác minh tệp thực thi",
	"LaunchApp_Action_CreatingProcess": "Đang khởi động thực thi",
	"LaunchApp_Action_WaitingGameWindow": "Đang khởi động tệp thực thi",
	"LaunchApp_Action_DelayLaunch": "Đang chờ khởi động (%1$s%)",
	"AppDetails_TitleUpdatedSincePlayed": "Trò chơi này đã được cập nhật kể từ lần cuối cùng bạn chơi",
	"AppDetails_TitleUpdatedSincePlayedLink": "Đọc thông tin về các thay đổi",
	"AppDetails_BadgeLevel": "Cấp %1$s, XP: %2$s",
	"AppDetails_UnearnedBadgeXP": "%1$s XP",
	"AppDetails_BadgeLevelNoXP": "Cấp %1$s",
	"AppDetails_Review_ViewOrEdit": "Chỉnh sửa đánh giá của tôi",
	"AppDetails_Review_YourReview": "Đánh giá của tôi",
	"AppDetails_Review_Ignore_Stale_Reviews": "Đừng nhắc tôi cập nhật đánh giá này.",
	"AppDetails_Review_Unignore_Stale_Reviews": "Cho phép các đánh giá cũ nổi lên cho trò chơi này.",
	"AppDetails_Review_RecommendGame": "Bạn có muốn khuyến nghị trò chơi này?",
	"AppDetails_Review_RecommendSoftware": "Bạn có muốn khuyến nghị phần mềm này?",
	"AppDetails_Review_WriteReview": "Viết đánh giá cho %1$s",
	"AppDetails_Review_PlayedForTime": "Bạn đã chơi %1$s",
	"AppDetails_Review_PlayedForTime_Software": "Bạn đã dùng sản phẩm này được %1$s",
	"AppDetails_Review_RecommendGameButton_Yes": "Có",
	"AppDetails_Review_RecommendGameButton_No": "Không",
	"AppDetails_Review_PlaytimeAtReview": "%1$s vào thời điểm đánh giá trò chơi",
	"AppDetails_Review_PlaytimeAtReview_Software": "%1$s sử dụng tại thời điểm đánh giá",
	"AppDetails_Review_NotRecommended": "Tiêu cực",
	"AppDetails_Review_Recommended": "Tích cực",
	"AppDetails_Review_AdditionalPlaytime": "Bạn đã chơi %1$s từ lúc viết đánh giá này.",
	"AppDetails_Review_AdditionalPlaytime_Software": "Bạn đã dùng sản phẩm này được %1$s từ lúc viết đánh giá này.",
	"AppDetails_Review_ChangedYourMind": "Bạn có đổi ý không?",
	"AppDetails_Review_IHaveNotChangedMyMind": "Không hề",
	"AppDetails_Review_UpVotes": "Thích:",
	"AppDetails_Review_Comments": "Bình luận:",
	"AppDetails_Review_ViewAll": "Xem tất cả đánh giá của tôi",
	"AppDetails_Review_ViewAllByFriend": "Xem tất cả đánh giá bởi %1$s",
	"OverflowBox_Action_Collapse": "Xem ít hơn",
	"OverflowBox_Action_Expand": "Đọc thêm",
	"OverflowBox_More": "(còn %1$s nữa)",
	"AppDetails_FriendsInGameNow": "%1$s bạn bè hiện đang chơi",
	"AppDetails_FriendsInGameNow_Plural": "%1$s bạn bè hiện đang chơi",
	"AppDetails_FriendsPlayedRecently": "%1$s bạn bè đã chơi trò này gần đây",
	"AppDetails_FriendsPlayedRecently_Plural": "%1$s bạn bè đã chơi trò này trước đây",
	"AppDetails_FriendsPlayedRecentlyExpand": "Hiển thị tất cả đã chơi gần đây",
	"AppDetails_FriendsPlayed": "%1$s bạn bè đã chơi trò này trước đây",
	"AppDetails_FriendsPlayed_Plural": "%1$s bạn bè đã chơi trò này trước đây",
	"AppDetails_FriendsPlayedExpand": "Hiển thị tất cả đã chơi trước đây",
	"AppDetails_FriendsMore": "(còn %1$s bạn nữa)",
	"AppDetails_FriendsLess": "Hiển thị bớt",
	"AppDetails_FriendsWishlisted": "%1$s bạn bè đã thêm %2$s vào danh sách ước",
	"AppDetails_FriendsWishlisted_Plural": "%1$s bạn bè đã thêm %2$s vào danh sách ước",
	"AppDetails_FriendsWishlistExpand": "Xem tất cả mong ước",
	"AppDetails_Friends_ViewAll": "Xem tất cả bạn bè đã chơi",
	"AppDetails_GameInfo": "Thông tin trò chơi",
	"AppDetails_Publisher": "Nhà phát hành:",
	"AppDetails_Developer": "Nhà phát triển:",
	"AppDetails_Franchise": "Loạt sản phẩm:",
	"AppDetails_ReleaseDate": "Ngày phát hành:",
	"AppDetails_OriginalReleaseDate": "Ngày phát hành gốc:",
	"AppDetails_Feature_SinglePlayer": "Chơi đơn",
	"AppDetails_Feature_MultiPlayer": "Chơi nhiều người",
	"AppDetails_Feature_CoOp": "Chơi phối hợp",
	"AppDetails_Feature_SteamAchievements": "Thành tựu",
	"AppDetails_Feature_SteamCloud": "Lưu trên đám mây",
	"AppDetails_Feature_FullController": "Hỗ trợ đầy đủ tay cầm",
	"AppDetails_Feature_PartialController": "Hỗ trợ bán phần tay cầm",
	"AppDetails_Feature_SteamWorkshop": "Steam Workshop",
	"AppDetails_Feature_VRSupport": "Hỗ trợ VR",
	"AppDetails_ViewAllUpdates": "Xem tất cả cập nhật",
	"AppDetails_ViewAllAchievements": "Xem thành tựu của tôi",
	"AppDetails_ViewGlobalAchievements": "Xem thông số thành tựu chung",
	"AppDetails_PlayerUnlockedPercent": "Bạn đã đạt %1$s/%2$s",
	"AppDetails_PlayerUnlockedPercentAll": "Bạn đã hoàn thành tất cả thành tựu! %1$s/%2$s",
	"AppDetails_Achievements_Unlocked": "Hoàn thành vào lúc %1$s",
	"AppDetails_PctUnlocked": "%1$s% người chơi đã mở khóa thành tựu này",
	"AppDetails_GlobalCompare": "Tức là hơn %1$s% số người chơi",
	"AppDetails_ViewTradingCards": "Xem thẻ trao đổi của tôi",
	"AppDetails_Achievements_Locked": "Thành tựu chưa mở",
	"AppDetails_TradingCardsLeft": "Còn phải thu thập thêm 1 thẻ",
	"AppDetails_TradingCardsLeft_Plural": "Còn phải thu thập thêm %1$s thẻ",
	"AppDetails_TradingCardsLevelUp": "Bạn đã có đủ thẻ trao đổi để lên cấp!",
	"AppDetails_TradingCardsMaxed": "Chúc mừng! Huy hiệu đã đạt cấp tối đa!",
	"AppDetails_BrowseWorkshop": "Duyệt qua Workshop",
	"AppDetails_ViewSubscribedItems": "Xem các đăng ký",
	"AppDetails_ViewItemInWorkshop": "Xem trong Workshop",
	"AppDetails_MoreItemsFrom": "Xem các vật phẩm từ tác giả này",
	"AppDetails_SubscribeToItem": "Đăng ký",
	"AppDetails_UnsubscribeFromItem": "Hủy đăng ký",
	"AppDetails_Subscribed": "Đã đăng ký",
	"AppDetails_ViewMoreInWorkshop": "Xem thêm trong Workshop",
	"AppDetails_WorkshopSubCount": "Bạn có (%1$s) đăng ký Workshop.",
	"AppDetails_WorkshopVisit": "Xem Workshop này",
	"AppDetails_WorkshopLearnMore": "Tìm hiểu thêm",
	"AppDetails_WorkshopFeaturedHeader": "Vật phẩm nổi bật",
	"AppDetails_WorkshopFeaturedItem": "Vật phẩm phổ biến",
	"AppDetails_WorkshopFeaturedMoreInfo": "Đọc thêm",
	"AppDetails_WorkshopFeaturedHideItem": "Ẩn vật phẩm này",
	"AppDetails_WorkshopFileSize": "Kích cỡ tệp: %1$s",
	"AppDetails_WorkshopFileSizeBytes": "%1$s bytes",
	"AppDetails_WorkshopFileSizeKb": "%1$s KB",
	"AppDetails_WorkshopFileSizeMb": "%1$s MB",
	"AppDetails_WorkshopFileSizeGb": "%1$s GB",
	"AppDetails_WorkshopLastUpdated": "Cập nhật lần cuối: %1$s",
	"DLCStatus_installed": "Đã cài đặt",
	"DLCStatus_notinstalled": "Chưa được cài",
	"DLCStatus_downloading": "Đang tải xuống",
	"DLC_DateAdded": "Được thêm vào: %1$s",
	"AppDetails_ManageDLC": "Quản lý DLC %1$s của tôi",
	"AppDetails_ManageMyDLC": "Quản lý DLC của tôi",
	"AppDetails_ViewStoreDLC": "Xem DLC trong cửa hàng",
	"AppDetails_DLCSpotlight": "Đã thêm DLC mới nhận, nó sẽ được cài cùng trò chơi. Quản lý DLC của bạn %1$s.",
	"AppDetails_DLCSpotlight_Installed": "DLC mới nhận đã được tự động cài. Quản lý DLC của bạn %1$s.",
	"AppDetails_DLCSpotlight_here": "tại đây",
	"ManageDLC_Title": "Quản lý DLC",
	"ManageDLC_Column_Name": "Tên",
	"ManageDLC_Column_DateAdded": "Ngày thêm vào",
	"ManageDLC_Column_Enabled": "Bật",
	"ManageDLC_Column_Installed": "Đã cài đặt",
	"ManageDLC_Search": "Tìm kiếm...",
	"ManageDLC_Installed": "Đã cài %1$s/%2$s",
	"ManageDLC_ViewMore": "Xem thêm trong cửa hàng",
	"ManageDLC_NoResults": "Không có kết quả nào khớp với \"%1$s\"",
	"AppDetails_ViewBadgePage": "Xem trang huy hiệu",
	"AppDetails_VisitTradeForum": "Đến diễn đàn trao đổi",
	"AppDetails_BuyCards": "Mua thẻ bài còn lại trên chợ",
	"AppDetails_SellCards": "Bán các thẻ bài này trên chợ",
	"AppDetails_SearchCard": "Hiện thẻ bài này trên chợ",
	"AppDetails_ShowFriendsList": "Hiện danh sách bạn bè",
	"AppDetails_ViewFriendsWhoPlay": "Xem bạn bè nào chơi",
	"AppDetails_Link_Discussions": "Thảo luận",
	"AppDetails_Link_FindGroups": "Tìm nhóm",
	"AppDetails_Link_GameHub": "Trung tâm cộng đồng",
	"AppDetails_Link_Guides": "Hướng dẫn",
	"AppDetails_Link_Store": "Trang cửa hàng",
	"AppDetails_Link_Support": "Hỗ trợ",
	"AppDetails_Link_Workshop": "Workshop",
	"AppDetails_Link_Controller": "Thiết lập tay cầm",
	"AppDetails_SocialMediaLink": "%1$s trên %2$s",
	"AppDetails_SocialMediaType_4": "Twitter",
	"AppDetails_SocialMediaType_5": "Twitch",
	"AppDetails_SocialMediaType_6": "YouTube",
	"AppDetails_SocialMediaType_7": "Facebook",
	"AppDetails_Screenshot": "Ảnh chụp",
	"AppDetails_Screenshot_Caption": "Chú thích: %1$s",
	"AppDetails_Screenshot_Date": "Ngày: %1$s",
	"AppDetails_Screenshot_Dimensions": "Kích thước: %1$s x %2$s pixel",
	"AppDetails_Screenshot_Uploaded": "Tải lên: %1$s lúc %2$s",
	"AppDetails_OpenScreenshotUploader": "Mở trình tải lên ảnh chụp",
	"AppDetails_ViewUploadedScreenshots": "Xem ảnh chụp đã tải lên",
	"AppDetails_ManageMyScreenshot": "Quản lý ảnh chụp của tôi",
	"AppDetails_ManageMyScreenshot_Plural": "Quản lý ảnh chụp của tôi (%1$s)",
	"AppDetails_HowToScreenshot": "Bạn có thể chụp ảnh màn hình bằng cách nhấn %1$s khi đang trong trò chơi.",
	"AppDetails_ChangeMyScreenshotKey": "Thay đổi phím tắt chụp ảnh",
	"AppDetails_NoScreenshots": "Bạn chưa chụp ảnh nào",
	"AppDetails_Artwork": "Tác phẩm",
	"AppDetails_Video": "Video",
	"AppDetails_CommunityItem": "Nội dung cộng đồng",
	"AppDetails_CommunityFeed_OutOfContent": "Không có nội dung bổ sung",
	"AppDetails_CommunityFeed_Inappropriate": "Nội dung có thể không phù hợp với mọi khán giả",
	"AppDetails_CommunityFeed_ViewContent": "Xem nội dung",
	"AppDetails_CommunityFeed_EditPreferences": "Chỉnh sửa Tùy chọn",
	"AppDetails_CommunityFeed_LoadCommunity": "Tải thêm nội dung cộng đồng",
	"AppBox_NewToLibrary": "Mới có trong thư viện",
	"AppBox_ComingSoon": "Sắp ra mắt",
	"AppBox_NewToLibrary_Short": "Mới",
	"AppBox_ComingSoon_Short": "Sắp ra",
	"AppBox_PlayTimeHeader": "Thời gian đã chơi",
	"AppBox_RecentPlayTime_Hours": "Hai tuần qua: %1$s tiếng",
	"AppBox_RecentPlayTime_Minutes": "Hai tuần qua: %1$s phút",
	"AppBox_TotalPlayTime_Hours": "Tổng: %1$s tiếng",
	"AppBox_TotalPlayTime_Minutes": "Tổng: %1$s phút",
	"AppActivity_Achieved": " đạt được",
	"AppActivity_PostedScreenshot": " chia sẻ một ảnh chụp",
	"AppActivity_PostedScreenshot_Plural": " chia sẻ %1$s ảnh chụp",
	"AppActivity_PostedVideo": " chia sẻ một video",
	"AppActivity_PostedVideo_Plural": " chia sẻ %1$s video",
	"AppActivity_ReceivedNewGame": " vừa sở hữu %1$s",
	"AppActivity_PlayedGameFirstTime": " lần đầu chơi %1$s",
	"AppActivity_LaunchedSoftwareFirstTime": " đã lần đầu tiên khởi chạy %1$s",
	"AppActivity_AddedGameToWishlist": " thêm %1$s vào %2$s của họ.",
	"AppActivity_Wishlist": "danh sách ước",
	"AppActivity_Achieved_PlusMore": "…và %1$s thành tựu khác",
	"AppActivity_Achieved_PlusMore_Label": "Xem tất cả thành tựu của %1$s",
	"AppActivity_NoActivity": "Gần đây từ các nhà phát triển sản phẩm này hoặc từ bạn bè không có hoạt động nào.",
	"AppActivity_UserStatus_Time": " đăng cập nhật trạng thái vào %1$s",
	"AppActivity_UserStatus": " đăng cập nhật trạng thái",
	"AppActivity_StatusUpdate": "Đăng một trạng thái tới bạn bè",
	"AppActivity_StatusUpdate_Post": "Phát biểu gì đó về trò chơi này với bạn bè...",
	"AppActivity_StatusUpdate_Software_Post": "Phát biểu gì đó về phần mềm này với bạn bè...",
	"AppActivity_Comment_Reply": "Thêm hồi âm...",
	"AppActivity_PostStatusUpdate": "Đăng",
	"AppActivity_FetchMore": "Nạp thêm hoạt động",
	"AppActivity_EndofFeed": "Hết tin",
	"AppActivity_DeleteUserNews": "Nhấp để xóa bài đăng này.",
	"AppActivity_ConfirmDeleteTitle": "Xóa bài đăng trạng thái",
	"AppActivity_ConfirmDeleteTitle_Desc": "Bạn có chắc muốn xóa bài đăng này? Việc này sẽ không thể hoàn tác được.",
	"AppActivity_RecommendedGame": " đã đánh giá trò chơi này",
	"AppActivity_RecommendedGame_ReadMore": "Đọc thêm",
	"AppActivity_RatingDetails": "%1$s người thích tin này",
	"AppActivity_RatingDetails_1Other": "1 người thích tin này, %1$s",
	"AppActivity_RatingDetails_2Others": "%1$s người thích tin này, bao gồm %2$s và %3$s",
	"AppActivity_RatingDetails_User": "Bạn thích tin này",
	"AppActivity_RatingDetails_User_1Other": "%1$s người thích tin này, bao gồm bạn và %2$s",
	"AppActivity_RatingDetails_User_2Others": "%1$s người thích tin này, bao gồm bạn, %2$s và %3$s",
	"AppActivity_RatingDetails_PublishedFile": "%1$s thích",
	"AppActivity_RateUp": "Thích",
	"AppActivity_ConfirmDeleteCommentTitle": "Xóa bình luận",
	"AppActivity_ConfirmDeleteCommentTitle_Desc": "Bạn có chắc muốn xóa bình luận này? Việc này sẽ không thể hoàn tác được.",
	"AppActivity_MakeCommentsVisible": "Xem bình luận trước (%1$s ẩn)",
	"AppActivity_Settings": "Thiết lập",
	"AppActivity_ViewComments": "Xem bình luận",
	"AppActivity_AddComments": "Thêm bình luận",
	"AppActivity_ContributeComments": "Góp bình luận",
	"AppActivity_SteamTradingCards_EarnedTradingCards": " đã nhận được thẻ trao đổi",
	"AppActivity_SteamTradingCards_EarnedTradingCard": " đã nhận được một thẻ trao đổi",
	"AppActivity_SteamTradingCards_EarnedBoosterPack": " đã nhận một gói bổ sung",
	"AppActivity_SteamTradingCards_BadgeCrafted": " đã tạo một huy hiệu",
	"AppActivity_ViewLatestNews": "Xem tin tức mới nhất",
	"AppActivity_EventType_GameUpdate": "Cập nhật trò chơi",
	"AppSpotlight_PostGameSummary": "Tổng kết sau trận đấu",
	"AppDetails_Shortcut_Explanation": "Một số thông tin chi tiết về %1$s hiện không có sẵn, vì đây là một bản mod hoặc lối tắt không thuộc Steam. Steam vẫn sẽ quản lý việc khởi chạy trò chơi cho bạn và trong hầu hết các trường hợp, lớp phủ trong trò chơi vẫn sẽ hoạt động.",
	"AppDetails_Takeover_Update_Header": "Phòng khi bạn bỏ lỡ",
	"AppDetails_Takeover_Update_ViewAll": "Xem toàn bộ %1$s cập nhật trò chơi",
	"AppDetails_Takeover_Update_ReadMore": "Đọc thêm",
	"AppDetails_Takeover_DLC_Header": "Đã thêm vật phẩm mới",
	"AppDetails_Takeover_DLC_ViewInStore": "Xem %1$s trong cửa hàng",
	"AppDetails_Takeover_Achievements_Header": "Đã chơi %2$s, bạn đạt một thành tựu mới...",
	"AppDetails_Takeover_Achievements_Header_Plural": "Đã chơi %2$s, bạn đạt các thành tựu mới...",
	"AppDetails_Takeover_TradingCards_Header": "Đã chơi %2$s, bạn có một vật phẩm mới...",
	"AppDetails_Takeover_TradingCards_Header_Plural": "Đã chơi %2$s, bạn có các vật phẩm mới...",
	"AppDetails_ViewMyInventory": "Xem kho đồ của tôi",
	"AppDetails_ViewInMyInventory": "Xem trong kho đồ của tôi",
	"AppPortraitHover_DownloadStatusTitle": "Đang tải xuống",
	"AppPortraitHover_DownloadStatusTitle_Update": "Đang tải cập nhật",
	"AppPortraitHover_DaysSinceLastUpdate": "Cập nhật %1$s",
	"AppPortraitHover_FriendsPlaying": "%1$s bạn bè đang chơi",
	"MajorUpdate_ViewDetails": "Xem chi tiết",
	"MajorUpdate_NextUpdate": "Cập nhật tiếp theo",
	"MajorUpdate_PostTime": "Đăng cách đây %1$s ngày vào %2$s:%3$s",
	"MajorUpdate_PostTimeToday": "Đăng vào hôm nay lúc%1$s:%2$s",
	"MajorUpdate_WatchNow": "Xem trên SteamTV",
	"MajorUpdate_Type0": "Cập nhật lớn",
	"MajorUpdate_Type1": "Kênh trực tiếp",
	"MajorUpdate_Type14": "Cập nhật lớn",
	"MajorUpdate_Context_RemoveThisUpdate": "Gỡ bỏ cập nhật này",
	"MajorUpdate_Context_ResetHiddenUpdates": "Hiện lại toàn bộ cập nhật",
	"MajorUpdate_Context_WhyAmISeeingThis": "Tại sao tôi lại thấy tin này?",
	"MajorUpdate_Context_WhyAmISeeingThis_Text": "Đây là bản cập nhật lớn cho một sản phẩm trong thư viện của bạn với hơn 20 giờ chơi (giữ chỗ).",
	"MajorUpdate_Context_WhyAmISeeingThis_Close": "Đóng",
	"CustomArt_ErrorTitle": "Lỗi",
	"CustomArt_BadFileType": "Tệp của bạn phải ở định dạng JPG hoặc PNG.",
	"CustomArt_UnknownError": "Đã có một lỗi xảy ra khi thiết lập tác phẩm của bạn.",
	"AppDetails_LibraryInUse": "Thư viện hiện được dùng bởi",
	"AppDetails_InSharedLibrary": "Từ thư viện của",
	"FriendContextMenu_OpenFriends": "Mở bạn bè & trò chuyện",
	"FriendContextMenu_ViewProfile": "Xem hồ sơ",
	"Generic_ScrollToTop": "Cuộn lên đầu",
	"Generic_ViewGameDetails": "Xem trò chơi trong thư viện",
	"GameDetails_CollectionContext_GoTo": "Đến bộ sưu tập",
	"GameDetails_CollectionContext_Remove": "Gỡ bỏ khỏi bộ sưu tập",
	"ArtworkModal_ViewAll": "Xem tất cả ảnh chụp",
	"ArtworkModal_FileSize": "Kích cỡ tệp",
	"ArtworkModal_Posted": "Đã đăng",
	"ArtworkModal_Size": "Kích thước",
	"ArtworkModal_CreatedBy": "Tạo bởi",
	"CommunityItem_Menu_Report": "Báo cáo",
	"ReportItem_Title": "Báo cáo vật phẩm này",
	"ReportItem_Description": "Vui lòng mô tả chi tiết vì sao vật phẩm này lại vi phạm Điều khoản dịch vụ của Steam. Xin hãy đính kèm bất kì thông tin hoặc đường dẫn nào có liên quan. Sau khi đã gửi, bạn sẽ không thể rút lại báo cáo này.",
	"ReportItem_Description_Line2": "Các vật phẩm bị báo cáo sẽ không còn xuất hiện trên trang thư viện của bạn.",
	"ReportItem_DMCA": "Nếu bạn là chủ sở hữu bản quyền và muốn báo cáo vi phạm bản quyền, vui lòng đi tới trang chứa mẫu thông báo khiếu nại vi phạm bản quyền theo DMCA của chúng tôi %1$s",
	"ReportItem_DMCA_LinkText": "tại đây",
	"ReportItem_Error": "Chúng tôi gặp sự cố khi gửi yêu cầu của bạn đến máy chủ. Vui lòng thử lại sau.",
	"ReportItem_SubmitReport": "Gửi báo cáo",
	"Showcase_AddNewShowcase": "Thêm giá trưng bày mới",
	"Showcase_DeleteShowcase": "Xóa giá trưng bày này",
	"Showcase_SelectCategory": "Chọn một giá trưng bày",
	"Showcase_EmptyShowcaseHint": "Chọn thứ bạn muốn trưng bày trên giá này. Bạn cũng có thể thay đổi hoặc xóa bỏ giá trưng bày tại đây!",
	"Showcase_GoToCollection": "Đến bộ sưu tập",
	"Showcase_GoToAllCollections": "Đến tất cả các bộ sưu tập",
	"Showcase_AllYourGames": "Tất cả trò chơi",
	"Showcase_AllCollections": "Xem bộ sưu tập",
	"Playtime_TwoWeeks_Minutes": "Chơi gần đây %1$s phút",
	"Playtime_TwoWeeks_Hours": "Chơi gần đây %1$s giờ",
	"Playtime_Total_Minutes": "Chơi tổng cộng %1$s phút",
	"Playtime_Total_Hours": "Chơi tổng cộng %1$s giờ",
	"Playtime_Minutes": "%1$s phút",
	"Playtime_Hours": "%1$s giờ",
	"Playtime_Recently": "Chơi gần đây %1$s",
	"Playtime_Total": "Chơi tổng cộng %1$s",
	"GameList_Search_NoResults_Title": "Bạn không tìm thấy thứ mình cần?",
	"GameList_Search_NoResults_Link": "Tìm trên cửa hàng Steam",
	"StreamingClient_Select_ThisMachine": "Máy tính này",
	"Beta_BetaTag": "BETA",
	"Beta_Changelist": "Changelist",
	"Beta_GiveFeedback": "Give Feedback"
}
