{
	"Generic_Okay": "Гаразд",
	"Generic_Close": "Закрити",
	"Generic_Open": "Відкрити",
	"Generic_GotIt": "Зрозуміло!",
	"Generic_Share": "Поділитися",
	"Generic_Upload": "Вивантажити",
	"Generic_Delete": "Видалити",
	"Privacy_Public": "Для всіх",
	"Privacy_FriendsOnly": "Лише для друзів",
	"Privacy_Private": "Лише для себе",
	"AppType_0": "Помилка",
	"AppType_1": "Ігри",
	"AppType_2": "Програми",
	"AppType_4": "Інструменти",
	"AppType_20": "Додатковий вміст",
	"AppType_800": "Відео",
	"AppType_2000": "Саундтреки",
	"AppType_Singular_0": "Помилка",
	"AppType_Singular_1": "гра",
	"AppType_Singular_2": "застосунок",
	"AppType_Singular_4": "інструмент",
	"AppType_Singular_20": "додатковий вміст",
	"AppType_Singular_800": "відео",
	"AppType_Singular_2000": "музика",
	"AppType_Singular_8000": "комікс",
	"AppType_Singular_40000000": "ярлик",
	"FilterEdit_SavedFilters": "Збережені фільтри",
	"FilterEdit_FirstColumnHeader": "Тип фільтра",
	"FilterEdit_Customize": "Змінити",
	"FilterEdit_SearchModeHeader": "Розширені фільтри",
	"FilterEdit_CollectionModeHeader": "Налаштувати фільтри колекції",
	"CollectionEdit_CollectionNameField": "Назва колекції:",
	"CollectionEdit_RenameButton": "Змінити назву колекції",
	"Collection_DynamicCollection": "Динамічна колекція",
	"FilterEdit_AdvancedTooltip": "Розширені фільтри для визначення ігор за жанром, особливостями тощо.",
	"Collection_FreezeDynamicCollection_Button": "Знімок",
	"Collection_FreezeDynamicCollection_ToolTip": "Конвертувати цю динамічну колекцію у звичайну через замороження поточного списку ігор.",
	"Collection_FreezeDynamicCollection_DialogTitle": "Колекція знімків",
	"Collection_FreezeDynamicCollection_Confirmation": "Ви дійсно бажаєте конвертувати цю колекцію? Вона більше не оновлюватиметься динамічно після додавання відповідних ігор до бібліотеки.",
	"Collection_ResetDialogTitle": "Сикнути колекції",
	"Collection_ResetConfirmation": "Ви дійсно бажаєте скинути список колекцій та повернути старі категорії?",
	"Collection_AfterResetSummary_NoCollections": "Після скидання у вас не буде жодної колекції.",
	"Collection_AfterResetSummary_CountAndNames": "Після скидання у ваш лишаються такі колекції: %2$s",
	"Collection_ResetFailed": "Помилка скидання колекцій",
	"FilterEdit_SelectedFilters": "Вибрані фільтри",
	"FilterEdit_SaveCollectionNameInputPrompt": "Уведіть назву для колекції",
	"FilterEdit_SaveOverwrite": "Колекція «%1$s» вже існує. Переписати?",
	"FilterEdit_SaveCollection": "Зберегти як колекцію",
	"FilterEdit_SaveDynamicCollectionWithIcon": "Зберегти як %1$sдинамічну колекцію",
	"FilterEdit_SaveDynamicCollectionNoIcon": "Зберегти як динамічну колекцію",
	"FilterEdit_SaveCollectionVerbose": "Збережіть цей пошук як колекцію, щоби використовувати його пізніше. Ви можете редагувати чи видаляти цю колекцію, змінювати її назву, додавати чи видаляти з неї продукти.",
	"FilterEdit_SaveStandardCollectionButtonDesc": "Колекція — це простий спосіб керувати своєю бібліотекою. Перетягніть товари у колекцію або клацніть правою кнопкою миші на них, щоби додати у вже наявну колекцію.",
	"FilterEdit_SaveDynamicCollectionButtonDesc": "Динамічні колекції використовують фільтри, щоби самостійно оновлюватися зі зростанням вашої бібліотеки.",
	"FilterEdit_SelectCollectionType": "Виберіть тип колекції",
	"FilterEdit_SelectCollectionTypeButtonCreate": "Створити колекцію",
	"FilterEdit_SelectCollectionTypeButtonCreateDynamic": "Створити динамічну колекцію",
	"FilterEdit_RequiredField": "( ОБОВ’ЯЗКОВО )",
	"FilterEdit_SearchPrompt": "Шукати за назвою",
	"FilterEdit_ClearSearch": "Покинути пошук",
	"FilterEdit_SearchResults": "Результати пошуку",
	"FilterEdit_CollectionsHiddenPromptTitle": "Колекції приховані",
	"FilterEdit_CollectionsHiddenPrompt": "Чи бажаєте змінити вид переліку ігор, щоби показати нову колекцію?",
	"FilterEdit_AcceptGameListViewChange": "Так, показати колекції",
	"FilterEdit_RejectGameListViewChange": "Ні, не змінювати",
	"AdvancedSearch_PaneTitle": "Шукати за типом",
	"AdvancedSearch_PlayerSection": "Гравці",
	"AdvancedSearch_HardwareSection": "Підтримка пристроїв",
	"AdvancedSearch_FeatureSection": "Особливості",
	"AdvancedSearch_StateSection": "Стан гри",
	"AdvancedSearch_GenreSection": "Жанр",
	"AdvancedSearch_StoreTagSection": "Позначки крамниці",
	"AdvancedSearch_StoreTagPrompt": "введіть позначку",
	"FilterCategory_1": "Стан",
	"FilterCategory_Features": "ОСОБЛИВІСТЬ",
	"FilterCategory_3": "Категорія",
	"FilterCategory_4": "Позначка крамниці",
	"FilterCategory_Type": "ТИП",
	"FilterCategory_Genre": "ЖАНР",
	"FilterCategory_PlayState": "СТАН",
	"FilterElement_VR": "ВР",
	"FilterElement_Tooltip_VR": "Ігри, що підтримують пристрої віртуальної реальності.",
	"FilterElement_Installed": "Інстальовано локально",
	"FilterElement_Tooltip_Installed": "Ігри, інстальовані на цьому комп’ютері.",
	"FilterElement_ReadyToPlay": "Готові до гри",
	"FilterElement_Tooltip_ReadyToPlay": "Ігри, які можна запустити на цьому комп’ютері або транслювати з іншого.",
	"FilterElement_PlayedPreviously": "Зіграні",
	"FilterElement_Tooltip_PlayedPreviously": "Ігри, в які ви вже грали раніше.",
	"FilterElement_Unplayed": "Не зіграні",
	"FilterElement_Tooltip_Unplayed": "Ігри, в які ви ще не грали.",
	"FilterElement_FullControllerSupport": "Повна підтримка контролерів",
	"FilterElement_Tooltip_FullControllerSupport": "Ігри, які мають повну підтримку гри з контролерами.",
	"FilterElement_PartialControllerSupport": "Часткова підтримка контролерів",
	"FilterElement_Tooltip_PartialControllerSupport": "Ігри, в які можна грати з контролером, але під час певних дій чи інсталяції потрібні клавіатура й мишка.",
	"FilterElement_VRSupported": "Підтримка ВР",
	"FilterElement_TradingCards": "Колекційні картки",
	"FilterElement_Tooltip_TradingCards": "Ігри, які мають колекційні картки Steam.",
	"FilterElement_Workshop": "Майстерня",
	"FilterElement_Tooltip_Workshop": "Ігри з підтримкою майстерні Steam.",
	"FilterElement_Achievements": "Досягнення",
	"FilterElement_Tooltip_Achievements": "Ігри з підтримкою досягнень Steam.",
	"FilterElement_SinglePlayer": "Самітна гра",
	"FilterElement_Tooltip_SinglePlayer": "Ігри, в які можна грати одному.",
	"FilterElement_MultiPlayer": "Багатокористувацька гра",
	"FilterElement_Tooltip_MultiPlayer": "Ігри, в які можна грати спільно.",
	"FilterElement_CoOp": "Кооперативна гра",
	"FilterElement_Tooltip_CoOp": "Ігри з кооперативним багатокористувацьким режимом.",
	"FilterElement_GenreAction": "Бойовик",
	"FilterElement_Tooltip_GenreAction": "Динамічні ігри-бойовики.",
	"FilterElement_GenreAdventure": "Пригоди",
	"FilterElement_Tooltip_GenreAdventure": "Пригодницькі ігри.",
	"FilterElement_GenreCasual": "Казуальна гра",
	"FilterElement_Tooltip_GenreCasual": "Казуальні ігри.",
	"FilterElement_GenreIndie": "Інді",
	"FilterElement_Tooltip_GenreIndie": "Ігри від інді-розробників.",
	"FilterElement_GenreMMO": "MMO",
	"FilterElement_Tooltip_GenreMMO": "Масові багатокористувацькі ігри.",
	"FilterElement_GenreRacing": "Перегони",
	"FilterElement_Tooltip_GenreRacing": "Ігри з перегонами на транспортних засобах.",
	"FilterElement_GenreRPG": "Рольова гра",
	"FilterElement_Tooltip_GenreRPG": "Рольові ігри.",
	"FilterElement_GenreSimulation": "Симулятор",
	"FilterElement_Tooltip_GenreSimulation": "Ігри-симулятори.",
	"FilterElement_GenreSports": "Спорт",
	"FilterElement_Tooltip_GenreSports": "Спортивні ігри.",
	"FilterElement_GenreStrategy": "Стратегія",
	"FilterElement_Tooltip_GenreStrategy": "Стратегічні ігри.",
	"FilterElement_Tooltip_StoreTag": "Ігри з позначкою крамниці «%1$s».",
	"FilterElement_SteamCloud": "Steam Cloud",
	"FilterElement_Tooltip_SteamCloud": "Включити ігри, які працюють зі Steam Cloud.",
	"FilterElement_RemotePlayTogether": "Remote Play Together",
	"FilterElement_Tooltip_RemotePlayTogether": "Ігри, що підтримують Remote Play Together.",
	"CollectionViewHeader_Tooltip_ManuallyAddedApp": "Ця гра додана в колекцію вручну.",
	"CollectionViewHeader_Tooltip_ManuallyRemovedApp": "Ця гра видалена з колеції.",
	"CollectionViewHeader_Tooltip_ManuallyRemovedApps_WithCount": "Вилучено ігор із цієї колекції: %1$s.",
	"CollectionViewHeader_ManuallyRemovedApps_WithCount": "%1$s вилучено",
	"CollectionView_EmptyReadOnlyCollection": "Тут нічого немає",
	"CollectionView_EmptyDynamicCollection_Line1": "Із цим фільтром ігор немає!",
	"CollectionView_EmptyDynamicCollection_Line2": "Змініть фільтр або перетягніть сюди гру, щоби створити колекцію.",
	"CollectionView_EmptyCollection": "Перетягніть сюди гру, щоби створити колекцію.",
	"CollectionView_EmptyCollection_BecauseFilter": "Через вибрані фільтри в цій колекції не показано кілька ігор: %1$s.",
	"CollectionView_EmptyCollection_BecauseFilter_Plural": "Через вибрані фільтри в цій колекції не показано кілька ігор: %1$s.",
	"CollectionView_MissingCollection": "Колекції не знайдено.",
	"CollectionView_GamesExcluded": "+%1$s",
	"CollectionView_GamesExcluded_Desc": "ігор, не готових до запуску",
	"AllCollectionsView_Title": "Ваші колекції",
	"AllCollectionsView_InfoIcon": "%1$s — збирайте свої ігри до купи власноруч. %2$s — налаштовуйте фільтри, щоб автоматично групувати ігри. %3$s",
	"AllCollectionsView_InfoIconCollections": "Колекції",
	"AllCollectionsView_InfoIconDynamicCollections": "Динамічні колекції",
	"AllCollectionsView_InfoIconFav": "%1$s завжди показуватимуться вгорі цієї сторінки.",
	"AllCollectionsView_InfoIconFavorites": "Вибране",
	"AllCollectionsView_AddCollection": "Створити колекцію",
	"AllCollectionsView_DragToAddCollection": "Перетягніть сюди, щоби створити нову колекцію",
	"GameList_Home": "Домівка",
	"GameList_Search": "Пошук",
	"GameList_Category_Uncategorized": "Без категорії",
	"GameList_Category_Favorites": "Вибране",
	"GameList_Category_Hidden": "Приховані",
	"GameList_Category_Hidden_Tooltip": "Приховані ігри показуватимуться у вашій бібліотеці лише під час пошуку. З меню «Вигляд» вгорі ви можете перейти до всіх прихованих ігор.",
	"GameList_Category_YourCollections": "Ваші колекції",
	"GameList_Category_SharedLibraries": "Спільні бібліотеки",
	"GameList_SectionHeader_SearchResults": "Результати пошуку й сортування",
	"GameList_SectionHeader_AddedManually": "Додано вручну",
	"GameList_SectionHeader_RemovedManually": "Вилучено вручну",
	"GameList_SectionHeader_NoRecentActivity": "Немає активності",
	"GameList_View_Collections": "Ваші колекції",
	"GameList_View_ThisCollection": "Проглянути цю колекцію",
	"GameList_View_OneCollection": "Перегляд колекцій",
	"GameList_View_SearchResults": "Результати пошуку",
	"GameList_View_ShowAllCollections": "Показати всі колекції",
	"GameList_View_GroupByCollections": "Групувати за колекцією",
	"GameList_View_ExitSearch": "Покинути пошук",
	"GameList_View_All": "Все",
	"GameList_View_Recent": "Нещодавні",
	"GameList_View_SortByRecent": "Сортувати за нещодавньою активністю",
	"GameList_View_ShowOnlyReadyToPlay": "Показати лише готові до запуску ігри",
	"GameList_View_ShowingReadyToPlay": "Показувати лише готові до запуску ігри",
	"GameList_View_ShowingOnlyReadyToPlay": "Показано лише готові до запуску",
	"GameList_View_ShowOnlyVR": "Показати лише ігри з ВР",
	"GameList_View_Platform_Linux": "Показувати лише ігри для Linux",
	"GameList_View_Platform_Apple": "Показувати лише ігри для macOS",
	"GameList_View_MyOwnGames": "Мої ігри",
	"GameList_View_GamesSharedByOther": "Ігри гравця %1$s",
	"GameList_View_NothingSelected": "Нічого",
	"GameList_View_NothingSelected_HelpText": "Під цей фільтр нічого не підходить.",
	"GameList_Search_GamesCheckbox_Link": "Показати ігри",
	"GameList_View_GroupSharedLibraries": "Групувати за бібліотекою",
	"GameList_View_GroupingDisabled_ToolTip": "Групування вимкнено в цьому поданні",
	"GameList_View_ReadyToPlay_ToolTip1": "• Інстальовано на цьому комп’ютері",
	"GameList_View_ReadyToPlay_ToolTip2": "• Можна транслювати з іншого комп’ютера",
	"GameList_Entry_ReadyToPlay_ToolTip": "Транслюватиметься з іншого комп’ютера",
	"GameList_Entry_Invalid_OSType": "На поточній версії вашої MacOS (Catalina) неможливо запускати 32-бітні ігри.",
	"GameList_Entry_Invalid_OSType2": "Ця гра має функцію Steam Play, тож ви можете грати в неї за допомогою Boot Camp чи з комп’ютера з операційною системою Windows.",
	"GameList_Entry_Invalid_OSType3": "Докладніше.",
	"Shelf_SectionHeader_ExpandTooltip": "Розтягніть полицю, щоби показати більше рядків",
	"Shelf_SectionHeader_ExpandTooltipFilter": "Розтягніть полицю, щоби показати більше рядків. Є предмети (%1$s), які не потрапили у фільтр",
	"GameList_SectionHeader_AppCountToolTip": "Є предмети (%1$s), які не потрапили у фільтр",
	"GameList_SectionHeader_AppCountToolTipAllHidden": "Нічого не показано через вибраний фільтр",
	"CollectionAction_ViewOnlyThis": "Проглянути тільки цю колекцію",
	"CollectionAction_ViewOnlyThisFavorites": "Проглянути лише вибране",
	"CollectionAction_ViewOnlyThisUncategorized": "Проглянути продукти лише без категорії",
	"CollectionAction_Collapse": "Згорнути",
	"CollectionAction_CollapseAll": "Згорнути все",
	"CollectionAction_CollapseAllCollections": "Згорнути всі колекції",
	"CollectionAction_Expand": "Розгорнути",
	"CollectionAction_ExpandAll": "Розгорнути все",
	"CollectionAction_ExpandAllCollections": "Розгорнути всі колекції",
	"CollectionAction_Manage": "Управління",
	"CollectionAction_Edit": "Редагувати фільтри колекції",
	"CollectionAction_Rename": "Змінити назву колекції",
	"CollectionAction_Delete": "Вилучити колекцію",
	"CollectionAction_DeleteDialog": "Вилучити колекцію",
	"CollectionAction_ConfirmDelete": "Ви дійсно бажаєте назавжди видалити колекцію «%1$s»?",
	"CollectionAction_SaveFailed": "Помилка збереження колекції «%1$s»",
	"CollectionAction_CannotOverwrite": "Помилка перезаписування колекції «%1$s». Виберіть іншу назву.",
	"CollectionAction_DeleteFailed": "Помилка видалення колекції «%1$s»",
	"LibraryHome_FriendsActivity": "Активність друзів",
	"LibraryHome_RecentGames": "Нещодавні ігри",
	"LibraryHome_NewUpdates": "Що нового",
	"LibraryHome_YourCollection": "Уся ваша бібліотека",
	"LibraryHome_RecentFriendsActivity": "Нещодавня активність друзів",
	"LibraryHome_NewUpdates_LoweredPriority": "Тепер для %1$s показується менше новин.",
	"LibraryHome_NewUpdates_RaisedPriority": "Тепер для %1$s показується більше новин.",
	"LibraryHome_NewUpdates_Undo": "Скасувати",
	"LibraryHome_RecentFriendsActivity_Empty": "У друзів зараз немає нічого нового чи популярного. Ця полиця автоматично ховається, якщо нічого показувати.",
	"WhatsNewSettings": "Налаштування розділу «Що нового»",
	"WhatsNew": "Що нового",
	"WhatsNewFeatureExplainer": "У розділі «Що нового» розробники ваших ігор повідомляють про оновлення, турніри, завантажуваний вміст, події та інші ігрові новини. Steam показуватиме найдоречніші новини на основі ваших нещодавно зіграних ігор і проведеного в них часу.",
	"WhatsNewFeatureExplainer2": "Деякі ігри автоматично виключаються з розділу «Що нового», якщо ви не грали в них більше кількох годин і довго не мали жодної ігрової активності.",
	"WhatsNewVisibilitySettings": "Налаштування видимості",
	"WhatsNewSettings_ShowOnlyForRecentlyPlayed": "Показувати тільки для ігор, запущених протягом останніх 90 днів",
	"WhatsNewSettings_ShowOnlyForRecentlyPlayed_Explainer": "(частоту для конкретної гри можна налаштувати, клацнувши новину правою кнопкою миші).",
	"WhatsNewSettings_ShowOnlyGameUpdates": "Показувати лише оновлення, а не інші типи подій і новин",
	"WhatsNewSettings_ShowOnlyGameUpdates_Explainer": "(частоту для конкретної гри можна налаштувати, клацнувши новину правою кнопкою миші).",
	"WhatsNewPrioritySettings": "Налаштування пріоритету",
	"WhatsNewPriorityExplainer": "(кількість новин для конкретної гри можна налаштувати в розділі «Що нового», клацнувши її правою кнопкою миші та вибравши потрібний параметр).",
	"WhatsNewYouHaveAskedToShowLessFor": "Ви обрали «Показувати менше» для цих ігор:",
	"WhatsNewYouHaveNothingShowingLess": "Ви ще не вказали «Показувати менше» для жодної гри.",
	"WhatsNewYouHaveAskedToShowMoreFor": "Ви обрали «Показувати більше» для цих ігор:",
	"WhatsNewYouHaveNothingShowingMore": "Ви ще не вказали «Показувати більше» для жодної гри.",
	"WhatsNewYouHaveNItemsHidden": "У вашій бібліотеці є приховані ігри (%1$s). Ці ігри не показуватимуться в розділі «Що нового».",
	"Library_FriendsActivity_HotRightNowHeading": "Актуально",
	"Library_FriendsActivity_HotRightNowHover": "Ми показуємо вам цю гру, оскільки багато ваших друзів грає в неї зараз.",
	"Library_FriendsActivity_TrendingHeading": "Популярність зростає",
	"Library_FriendsActivity_TrendingHover": "Ми показуємо вам цю гру, оскільки кілька ваших друзів грали в неї цього тижня частіше, ніж минулого.",
	"Library_FriendsActivity_BeingDiscussedHeading": "Обговорюються",
	"Library_FriendsActivity_BeingDiscussedHover": "Ми показуємо цю гру, оскільки ваші друзі публікують знімки екрана з неї або повідомлення про неї.",
	"Library_FriendsActivity_RecentlyPurchasedHeading": "Нещодавно придбані",
	"Library_FriendsActivity_RecentlyPurchasedHover": "Ми показуємо цю гру, оскільки ви нещодавно придбали її, а ваші друзі вже грають у неї.",
	"Library_FriendsActivity_UnownedHeading": "Щось новеньке",
	"Library_FriendsActivity_UnownedHover": "Ми показуємо цю гру, оскільки вона популярна серед ваших друзів, але ви не купували її.",
	"Library_FriendsActivity_PopularHeading": "Популярні",
	"Library_FriendsActivity_PopularHover": "Ми показуємо вам цю гру, оскільки багато ваших друзів зіграло в неї останнім часом.",
	"Library_FriendsActivity_DontForgetHeading": "Не забувайте",
	"Library_FriendsActivity_DontForgetHover": "Ми показуємо цю гру, оскільки ви давно в неї не грали, а от ваші друзі грали нещодавно.",
	"Library_FriendsActivity_NewToGroupHeading": "Новинка для друзів",
	"Library_FriendsActivity_NewToGroupHover": "Ми показуємо вам цю гру, оскільки ваші друзі почали грати в неї нещодавно.",
	"Library_FriendsActivity_ReturnedToGroupHeading": "Знову повертається",
	"Library_FriendsActivity_ReturnedToGroupHover": "Ми показуємо вам цю гру, оскільки ваші друзі знову почали грати в неї.",
	"Library_FriendsActivity_UnownedBanner": "Переглянути у крамниці Steam",
	"Library_FriendsActivity_UnownedMenu_Store": "Крамниця",
	"Library_FriendsActivity_UnownedMenu_Hub": "Центр спільноти",
	"Library_FriendsActivity_UnownedMenu_Reviews": "Рецензії",
	"Library_FriendsActivity_UnownedMenu_Discussions": "Обговорення",
	"Library_Recent_NoRecentGames_GamesOwned": "Ви маєте ігор: %1$s.",
	"Library_Recent_NoRecentGames_StoreLink": "Відвідайте %1$s, щоби знайти ігри для додавання:",
	"Library_Recent_NoRecentGames_SteamStore": "крамницю Steam",
	"Library_Recent_NoRecentGames_FreeToPlay": "Ігри з вільним доступом",
	"Library_Recent_NoRecentGames_GamesOnSale": "Ігри на розпродажі",
	"Library_Recent_NoRecentGames_NewReleases": "Новинки",
	"Library_Recent_NoRecentGames_ActivateProduct": "Активувати продукт",
	"Library_Recent_NoRecentGames_RedeemCode": "Використати код гаманця",
	"Library_SortCollectionBy": "Сортувати",
	"Library_SortByFavoritesFirst": "за уподобаннями",
	"Library_SortByAlphabetical": "за абеткою",
	"Library_SortByPctAchievementsComplete": "за % завершених досягнень",
	"Library_SortByLastUpdated": "за датою останнього оновлення",
	"Library_SortByHoursPlayed": "за часом у грі",
	"Library_SortByLastPlayed": "за останнім запуском",
	"Library_SortByReleaseDate": "за датою випуску",
	"Library_SortByAddedToLibrary": "за датою придбання",
	"Library_SortBySizeOnDisk": "за розміром",
	"Library_SortByMetacriticScore": "за оцінкою Metacritic",
	"Library_SortByFriendsPlaying": "за друзями, що грають",
	"Library_SortBySteamReview": "за рецензіями Steam",
	"Library_SortByPctAchievementsComplete_Tag": "Здобуто: %1$s%",
	"Library_SortByPctAchievementsNoAchievements_Tag": "Без досягнень",
	"Library_InstalledOnlyCheck": "Лише інстальовані",
	"GridSection_Favorites": "Вибране",
	"GridSection_EverythingElse": "Усе інше",
	"GridSection_Over100Hours": "Понад 100 год",
	"GridSection_Over60Hours": "Понад 60 год",
	"GridSection_Over40Hours": "Понад 40 год",
	"GridSection_Over20Hours": "Понад 20 год",
	"GridSection_Over10Hours": "Понад 10 год",
	"GridSection_Over1Hour": "Понад 1 год",
	"GridSection_LessThan1Hour": "Менше 1 год",
	"GridSection_Over90Metacritic": "Понад 90",
	"GridSection_Over80Metacritic": "Понад 80",
	"GridSection_Over70Metacritic": "Понад 70",
	"GridSection_Over50Metacritic": "Понад 50",
	"GridSection_EverythingElseMetacritic": "Усе інше",
	"GridSection_UnknownReleaseDate": "Невідомо",
	"GridSection_GreaterThan100GB": "Понад 100 ГБ",
	"GridSection_GreaterThan50GB": "Понад 50 ГБ",
	"GridSection_GreaterThan20GB": "Понад 20 ГБ",
	"GridSection_LessThan20GB": "Менше 20 ГБ",
	"GridSection_NoSizeOnDisk": "Без розміру",
	"GridSection_NotInstalled": "Не інстальовані",
	"GridSection_MoreThan10YearsAgo": "Понад 10 р. тому",
	"GridSection_Never": "Ніколи",
	"AppDetails_SectionTitle_Stream": "Трансляція розробника",
	"AppDetails_SectionTitle_Activity": "Активність",
	"AppDetails_SectionTitle_Friends": "Друзі, які грають",
	"AppDetails_SectionTitle_Friends_Software": "Друзі, які використовують",
	"AppDetails_SectionTitle_Achievements": "Досягнення",
	"AppDetails_SectionTitle_TradingCards": "Колекційні картки",
	"AppDetails_SectionTitle_Screenshots": "Знімки екрана",
	"AppDetails_SectionTitle_AdditionalContent": "Додатковий вміст",
	"AppDetails_SectionTitle_Updates": "Нещодавні події та оновлення",
	"AppDetails_SectionTitle_DLC": "Додатковий вміст",
	"AppDetails_SectionTitle_LastPlayed": "Востаннє зіграно",
	"AppDetails_SectionTitle_LastLaunched": "Останнє із запущеного",
	"AppDetails_SectionTitle_PlayTime": "Час гри",
	"AppDetails_SectionTitle_UsageTime": "Час використання",
	"AppDetails_SectionTitle_Workshop": "Майстерня Steam",
	"AppDetails_SectionTitle_Community": "Вміст від спільноти",
	"AppDetails_SectionTitle_Links": "Посилання",
	"AppDetails_SectionTitle_SignIn_Pre": "Увійти",
	"AppDetails_SectionTitle_SignIn": "%1$s, щоби побачити діяльність друзів",
	"AppDetails_SectionTitle_OpenFriends": "Відкрити список друзів",
	"AppDetails_SectionTitle_OfflineMode": "Автономний режим",
	"AppDetails_Broadcast_ViewOnWeb": "Дивитися у браузері",
	"AppDetails_Community_Tooltip1": "Цей розділ містить знімки екрана, творчі роботи, відео, посібники та інше, створене спільнотою.",
	"AppDetails_Community_Tooltip2": "Ви можете вподобати, поділитися, відкоментувати або поскаржитися на цей вміст.",
	"AppDetails_Community_Guide": "Посібник від спільноти",
	"AppDetails_Links_Store": "Сторінка в крамниці",
	"AppDetails_Links_Community": "Центр спільноти",
	"Bbcode_Originally_Posted_By": "Спершу опубліковано: ",
	"AppDetails_InOfflineMode": "Steam наразі працює в автономному режимі. У ньому недоступні багато функцій бібліотеки Steam, зокрема списки друзів та їхня діяльність. Увійдіть в мережу, щоби користуватися цими функціями.",
	"AppDetails_GoOnline": "Увійти в мережу",
	"AppDetails_PartnerEventFailedLoad": "Не вдалося завантажити цю подію",
	"GameAction_Stop": "Зупинити",
	"GameAction_Cancel": "Скасувати",
	"GameAction_Install": "Інсталювати",
	"GameAction_Uninstall": "Видалити",
	"GameAction_Play": "Грати",
	"GameAction_PlayMusic": "Відтворити альбом",
	"GameAction_Launch": "Запустити",
	"GameAction_PreLoad": "Завчасно завантажити",
	"GameAction_Update": "Оновити",
	"GameAction_Download": "Завантажити",
	"GameAction_Resume": "Продовжити",
	"GameAction_Pause": "Призупинити",
	"GameAction_BorrowApp": "Позичити",
	"GameAction_PurchaseApp": "Придбати",
	"GameAction_GameProperties": "Властивості…",
	"GameAction_AddToFavorites": "Додати у вибране",
	"GameAction_RemoveFromFavorites": "Вилучити з вибраного",
	"GameAction_AddToHidden": "Сховати цю гру",
	"GameAction_RemoveFromHidden": "Вилучити зі схованого",
	"GameAction_RemoveGameLicense": "Вилучити з акаунта",
	"GameAction_AddToFamilyGames": "Додати до сімейних ігор",
	"GameAction_RemoveFromFamilyGames": "Вилучити з сімейних ігор",
	"GameAction_RemoveShortcut": "Видалити сторонню гру з бібліотеки",
	"GameAction_AddToCollection": "Додати до",
	"GameAction_RemoveFromCollection": "Вилучити з",
	"GameAction_CreateDesktopShortcut": "Створити ярлик на робочому столі",
	"GameAction_BackUpFiles": "Створити резервну копію файлів…",
	"GameAction_Stream": "Трансляція",
	"GameAction_Connect": "Підключитися",
	"GameAction_SetCustomArtwork": "Встановити свою обкладинку",
	"GameAction_ClearCustomArtwork": "Вилучити свою обкладинку",
	"GameAction_ViewCDKeys": "Цифрові ключі",
	"GameAction_ControllerConfiguration": "Конфігурація контролера",
	"GameAction_Launching": "Запуск",
	"GameAction_RemoveAppFromCollection": "ПЕРЕТЯГНІТЬ СЮДИ, щоби вилучити %1$s з колекції «%2$s»",
	"GameAction_RemoveAppFromMultipleCollections": "ПЕРЕТЯГНІТЬ СЮДИ, щоби вилучити %1$s з цих колекцій",
	"GameAction_RemoveMultipleAppsFromCollection": "ПЕРЕТЯГНІТЬ СЮДИ, щоби вилучити ці застосунки з колекції «%1$s»",
	"GameAction_RemoveMultipleAppsFromMultipleCollections": "ПЕРЕТЯГНІТЬ СЮДИ, щоби вилучити ці застосунки з цих колекцій",
	"GameAction_NavigateToAllCollectionsWithDrag": "ПЕРЕТЯГНІТЬ та УТРИМУЙТЕ ТУТ, щоби проглянути всі колекції",
	"GameAction_AddToCollectionOption_NewCollection": "Нова колекція…",
	"GameAction_NewCollectionDialogTitle": "Нова колекція",
	"GameAction_Manage": "Управління",
	"GameAction_Favorite": "Додати у вибране",
	"GameAction_UnFavorite": "У вибраному",
	"GameAction_ViewDetails": "Більше подробиць",
	"GameAction_BrowseLocalFiles": "Переглянути локальні файли",
	"GameAction_ViewDetails_Collapse": "Менше подробиць",
	"GameAction_ViewDetails_ScrollUp": "Прокрутити вгору",
	"GameActionPlural_Install": "Інсталювати обране",
	"GameActionPlural_Uninstall": "Видалити обране",
	"GameActionPlural_PreLoad": "Завчасно завантажити обране",
	"GameActionPlural_Update": "Оновити обране",
	"GameActionPlural_Download": "Завантажити обране",
	"GameActionPlural_Resume": "Продовжити обране",
	"GameActionPlural_AddToFavorites": "Додати обране у вибране",
	"GameActionPlural_RemoveFromFavorites": "Вилучити обране з вибраного",
	"GameActionPlural_AddToHidden": "Сховати обрані ігри",
	"GameActionPlural_RemoveFromHidden": "Вилучити обране зі схованого",
	"GameActionPlural_AddToFamilyGames": "Додати обране до сімейних ігор",
	"GameActionPlural_RemoveFromFamilyGames": "Вилучити обране із сімейних ігор",
	"GameActionPlural_RemoveShortcut": "Видалити обрані сторонні ігри з бібліотеки",
	"GameActionPlural_AddToCollection": "Додати обране до",
	"GameActionPlural_RemoveFromCollection": "Вилучити обране з",
	"GameActionPlural_CreateDesktopShortcut": "Створити ярлики на робочому столі",
	"GameActionPlural_BackUpFiles": "Створити резервну копію файлів…",
	"PrePurchase_Preload_Title": "%1$s можна завчасно завантажити",
	"PrePurchase_Preload_Desc": "Завантажте ігрові файли зараз, щоби почати грати одразу після виходу!",
	"PrePurchase_PreloadComplete_Title": "%1$s завчасно завантажено",
	"PrePurchase_PreloadComplete_Desc": "Одразу після виходу гри ви зможете в неї грати!",
	"PrePurchase_Install_Title": "%1$s можна інсталювати і грати",
	"PrePurchase_Install_Desc": "Інсталюйте зараз і грайте!",
	"PrePurchase_PlayNow_Title": "%1$s вже доступна",
	"PrePurchase_PlayNow_Desc": "Розпочніть грати!",
	"DisplayStatus_Launching": "Запуск",
	"DisplayStatus_Uninstalling": "Видалення",
	"DisplayStatus_Installing": "Інсталювання",
	"DisplayStatus_Running": "Запущено",
	"DisplayStatus_Validating": "Перевірка",
	"DisplayStatus_Updating": "Оновлення",
	"DisplayStatus_Downloading": "Завантаження",
	"DisplayStatus_Synchronizing": "Синхронізація зі Steam Cloud",
	"DisplayStatus_ReadyToInstall": "Готово до інсталювання",
	"DisplayStatus_ReadyToPreload": "Готово до завчасного завантаження",
	"DisplayStatus_ReadyToLaunch": "Готово до запуску",
	"DisplayStatus_RegionRestricted": "Недоступно в поточному регіоні",
	"DisplayStatus_PresaleOnly": "Цей предмет ще недоступний",
	"DisplayStatus_InvalidPlatform": "Доступно для",
	"DisplayStatus_PreloadComplete": "Завчасне завантаження завершено",
	"DisplayStatus_BorrowerLocked": "Ця бібліотека наразі недоступна як сімейна бібліотека",
	"DisplayStatus_UpdatePaused": "Оновлення призупинено",
	"DisplayStatus_UpdateQueued": "Оновлення в черзі",
	"DisplayStatus_UpdateRequired": "Необхідне оновлення",
	"DisplayStatus_UpdateDisabled": "Оновлення вимкнені, оскільки Steam знаходиться в автономному режимі. Увійдіть у мережу, щоби завершити оновлення цієї гри.",
	"DisplayStatus_DownloadPaused": "Завантаження призупинено",
	"DisplayStatus_DownloadQueued": "Завантаження в черзі",
	"DisplayStatus_DownloadRequired": "Необхідне завантаження",
	"DisplayStatus_DownloadDisabled": "Завантаження вимкнені, оскільки Steam знаходиться в автономному режимі. Увійдіть у мережу, щоби завершити завантаження цієї гри.",
	"DisplayStatus_LicensePending": "Ваше придбання не завершено.",
	"DisplayStatus_LicenseExpired": "Завершився термін дії ліцензії",
	"DisplayStatus_AvailForFree": "Доступно безкоштовно",
	"DisplayStatus_AvailToBorrow": "Доступно для позичання",
	"DisplayStatus_AvailGuestPass": "Доступна гостьова перепустка",
	"DisplayStatus_Purchase": "Доступно для придбання",
	"DisplayStatus_Preallocating": "Виділення місця",
	"DisplayStatus_Committing": "Виконання",
	"DisplayStatus_Verifying": "Перевірка",
	"DisplayStatus_Unpacking": "Розпаковування",
	"DisplayStatus_Compact_Launching": "Запуск",
	"DisplayStatus_Compact_Uninstalling": "Видалення",
	"DisplayStatus_Compact_Installing": "Інсталювання",
	"DisplayStatus_Compact_Running": "Запущено",
	"DisplayStatus_Compact_Validating": "Перевірка",
	"DisplayStatus_Compact_Updating": "Оновлення",
	"DisplayStatus_Compact_Downloading": "Завантаження",
	"DisplayStatus_Compact_Synchronizing": "Синхронізація зі Steam Cloud",
	"DisplayStatus_Compact_ReadyToInstall": "Готово до інсталювання",
	"DisplayStatus_Compact_ReadyToPreload": "Готово до завчасного завантаження",
	"DisplayStatus_Compact_ReadyToLaunch": "Готово до запуску",
	"DisplayStatus_Compact_RegionRestricted": "Недоступно в цьому регіоні",
	"DisplayStatus_Compact_PresaleOnly": "Гра ще не вийшла",
	"DisplayStatus_Compact_InvalidPlatform": "Доступно для",
	"DisplayStatus_Compact_ParentalBlocked": "Заблоковано сімейними налаштуваннями",
	"DisplayStatus_Compact_PreloadComplete": "Завчасне завантаження завершено",
	"DisplayStatus_Compact_BorrowerLocked": "Сімейна бібліотека не доступна",
	"DisplayStatus_Compact_UpdatePaused": "Оновлення призупинено",
	"DisplayStatus_Compact_UpdateQueued": "Оновлення в черзі",
	"DisplayStatus_Compact_UpdateRequired": "Необхідне оновлення",
	"DisplayStatus_Compact_UpdateDisabled": "Оновлення в автономному режимі вимкнені.",
	"DisplayStatus_Compact_DownloadPaused": "Завантаження призупинено",
	"DisplayStatus_Compact_DownloadQueued": "Завантаження в черзі",
	"DisplayStatus_Compact_DownloadRequired": "Необхідне завантаження",
	"DisplayStatus_Compact_DownloadDisabled": "Завантаження в автономному режимі вимкнені.",
	"DisplayStatus_Compact_LicensePending": "Завершення придбання",
	"DisplayStatus_Compact_LicenseExpired": "Завершився термін дії ліцензії",
	"DisplayStatus_Compact_AvailForFree": "Доступно безкоштовно",
	"DisplayStatus_Compact_AvailToBorrow": "Доступно для позичання",
	"DisplayStatus_Compact_AvailGuestPass": "Доступна гостьова перепустка",
	"DisplayStatus_Compact_Purchase": "Доступно для придбання",
	"DisplayStatus_ReleaseDate": "Виходить %1$s",
	"DisplayStatus_CustomReleaseDate": "Запланована дата виходу: %1$s",
	"Downloads_State_Bytes_Of_Bytes": "%1$s із %2$s",
	"Downloads_State_None": "",
	"Downloads_State_Reconfiguring": "Початок завантаження",
	"Downloads_State_Validating": "Перевірка файлів",
	"Downloads_State_AddingFiles": "Копіювання файлів",
	"Downloads_State_Preallocating": "Виділення місця",
	"Downloads_State_Downloading": "",
	"Downloads_State_Staging": "",
	"Downloads_State_Committing": "Завершення",
	"Downloads_State_Verifying": "Перевірка завантаження",
	"Downloads_State_Stopping": "Зупинка завантаження",
	"Downloads_State_Running": "",
	"Downloads_State_SecondsRemaining": "%1$s с лишається",
	"Downloads_State_MinutesRemaining": "%1$s хв лишається",
	"Downloads_State_Calculating": "Обчислення…",
	"LaunchApp_Action_UpdatingAppInfo": "Перевірка конфігурації",
	"LaunchApp_Action_ShowEula": "Показ користувацької угоди",
	"LaunchApp_Action_DownloadingDepots": "Завантаження вмісту (%1$s%)",
	"LaunchApp_Action_DownloadingWorkshop": "Завантаження майстерні (%1$s%)",
	"LaunchApp_Action_UpdatingDRM": "Оновлення виконуваного файлу",
	"LaunchApp_Action_GettingLegacyKey": "Оновлення ключа продукту",
	"LaunchApp_Action_RunningInstallScript": "Запуск скрипта інсталювання (%1$s)",
	"LaunchApp_Action_SynchronizingCloud": "Синхронізація з хмарою",
	"LaunchApp_Action_VerifyingFiles": "Перевірка виконуваного файлу",
	"LaunchApp_Action_CreatingProcess": "Запуск виконуваного файлу",
	"LaunchApp_Action_WaitingGameWindow": "Запуск виконуваного файлу",
	"LaunchApp_Action_DelayLaunch": "Затримка запуску (%1$s%)",
	"AppDetails_TitleUpdatedSincePlayed": "Цю гру було оновлено з часу вашого останнього запуску",
	"AppDetails_TitleUpdatedSincePlayedLink": "Прочитати список змін",
	"AppDetails_BadgeLevel": "Рівень %1$s, %2$s досвіду",
	"AppDetails_UnearnedBadgeXP": "%1$s досвіду",
	"AppDetails_BadgeLevelNoXP": "Рівень %1$s",
	"AppDetails_Review_ViewOrEdit": "Редагувати мою рецензію",
	"AppDetails_Review_YourReview": "Моя рецензія",
	"AppDetails_Review_Ignore_Stale_Reviews": "Не нагадувати мені про оновлення цієї рецензії.",
	"AppDetails_Review_Unignore_Stale_Reviews": "Показувати стару рецензію на цю гру.",
	"AppDetails_Review_RecommendGame": "Чи рекомендуєте ви цю гру?",
	"AppDetails_Review_RecommendSoftware": "Чи рекомендуєте ви це програмне забезпечення?",
	"AppDetails_Review_WriteReview": "Написати рецензію для %1$s",
	"AppDetails_Review_PlayedForTime": "Ви грали %1$s",
	"AppDetails_Review_PlayedForTime_Software": "Ви користувалися цим продуктом %1$s",
	"AppDetails_Review_RecommendGameButton_Yes": "Так",
	"AppDetails_Review_RecommendGameButton_No": "Ні",
	"AppDetails_Review_PlaytimeAtReview": "%1$s зіграно на час написання рецензії",
	"AppDetails_Review_PlaytimeAtReview_Software": "%1$s користувалися на час написання рецензії",
	"AppDetails_Review_NotRecommended": "Не рекомендовано",
	"AppDetails_Review_Recommended": "Рекомендовано",
	"AppDetails_Review_AdditionalPlaytime": "Ви грали %1$s після написання цієї рецензії.",
	"AppDetails_Review_AdditionalPlaytime_Software": "Ви користувалися %1$s після написання рецензії.",
	"AppDetails_Review_ChangedYourMind": "Чи змінили ви свою думку?",
	"AppDetails_Review_IHaveNotChangedMyMind": "Ні, все без змін",
	"AppDetails_Review_UpVotes": "Вподобання:",
	"AppDetails_Review_Comments": "Коментарі:",
	"AppDetails_Review_ViewAll": "Переглянути всі мої рецензії",
	"AppDetails_Review_ViewAllByFriend": "Переглянути всі рецензії від %1$s",
	"OverflowBox_Action_Collapse": "Бачити менше",
	"OverflowBox_Action_Expand": "Докладніше",
	"OverflowBox_More": "(ще %1$s)",
	"AppDetails_FriendsInGameNow": "Друзів грає просто зараз: %1$s",
	"AppDetails_FriendsInGameNow_Plural": "Друзів грає просто зараз: %1$s",
	"AppDetails_FriendsPlayedRecently": "Друзів, які грали нещодавно: %1$s",
	"AppDetails_FriendsPlayedRecently_Plural": "Друзів, які грали нещодавно: %1$s",
	"AppDetails_FriendsPlayedRecentlyExpand": "Показати всіх, хто грав нещодавно",
	"AppDetails_FriendsPlayed": "Друзів, які колись грали: %1$s",
	"AppDetails_FriendsPlayed_Plural": "Друзів, які колись грали: %1$s",
	"AppDetails_FriendsPlayedExpand": "Показати всіх, хто колись грав",
	"AppDetails_FriendsMore": "(ще %1$s)",
	"AppDetails_FriendsLess": "Показати менше",
	"AppDetails_FriendsWishlisted": "Друзів, які додали %2$s до свого бажаного: %1$s",
	"AppDetails_FriendsWishlisted_Plural": "Друзів, які додали %2$s до свого бажаного: %1$s",
	"AppDetails_FriendsWishlistExpand": "Показати всіх, хто додав до бажаного",
	"AppDetails_Friends_ViewAll": "Всі друзі, які грали",
	"AppDetails_GameInfo": "Про гру",
	"AppDetails_Publisher": "Видавець:",
	"AppDetails_Developer": "Розробник:",
	"AppDetails_Franchise": "Франшиза:",
	"AppDetails_ReleaseDate": "Дата виходу:",
	"AppDetails_LastUpdate": "Останнє локальне оновлення:",
	"AppDetails_OriginalReleaseDate": "Початкова дата виходу:",
	"AppDetails_Feature_SinglePlayer": "Самітна гра",
	"AppDetails_Feature_MultiPlayer": "Багатокористувацька гра",
	"AppDetails_Feature_CoOp": "Кооперативна гра",
	"AppDetails_Feature_SteamAchievements": "Досягнення",
	"AppDetails_Feature_SteamCloud": "Хмарні збереження",
	"AppDetails_Feature_FullController": "Повна підтримка контролерів",
	"AppDetails_Feature_PartialController": "Часткова підтримка контролерів",
	"AppDetails_Feature_SteamWorkshop": "Майстерня Steam",
	"AppDetails_Feature_VRSupport": "Підтримка ВР",
	"AppDetails_ViewAllUpdates": "Всі оновлення",
	"AppDetails_ViewAllAchievements": "Мої досягнення",
	"AppDetails_ViewGlobalAchievements": "Глобальна статистика досягнень",
	"AppDetails_PlayerUnlockedPercent": "Ви здобули %1$s із %2$s",
	"AppDetails_PlayerUnlockedPercentAll": "Ви здобули всі досягнення! %1$s із %2$s",
	"AppDetails_Achievements_Unlocked": "Здобуто %1$s",
	"AppDetails_PctUnlocked": "%1$s% гравців мають це досягнення",
	"AppDetails_GlobalCompare": "Це більше, ніж у %1$s% гравців",
	"AppDetails_ViewTradingCards": "Мої колекційні картки",
	"AppDetails_Achievements_Locked": "Нездобуті досягнення",
	"AppDetails_TradingCardsLeft": "Незібраних карток: 1",
	"AppDetails_TradingCardsLeft_Plural": "Незібраних карток: %1$s",
	"AppDetails_TradingCardsLevelUp": "У вас достатньо карток, щоби підняти рівень!",
	"AppDetails_TradingCardsMaxed": "Вітаємо! Значок має найвищий рівень!",
	"AppDetails_TradingCards_Tooltip1": "Колекційні картки випадають під час вашої гри. Картки, яких вам бракує, можна виміняти у друзів (або купити на ринку спільноти Steam).",
	"AppDetails_TradingCards_Tooltip2": "Збирайте повні набори колекційних карток і перетворюйте їх на значки. Значки піднімають ваш рівень Steam та розблоковують додаткові переваги для вашого профілю й акаунта.",
	"AppDetails_BrowseWorkshop": "Переглянути майстерню",
	"AppDetails_ViewSubscribedItems": "Мої підписки",
	"AppDetails_ViewItemInWorkshop": "Переглянути в майстерні",
	"AppDetails_MoreItemsFrom": "Інші предмети цього автора",
	"AppDetails_SubscribeToItem": "Підписатися",
	"AppDetails_UnsubscribeFromItem": "Відписатися",
	"AppDetails_Subscribed": "Підписано",
	"AppDetails_ViewMoreInWorkshop": "Переглянути більше в майстерні",
	"AppDetails_WorkshopSubCount": "Підписок у майстерні: %1$s.",
	"AppDetails_WorkshopVisit": "Відвідати цю майстерню",
	"AppDetails_WorkshopLearnMore": "Довідатися більше",
	"AppDetails_WorkshopFeaturedHeader": "Предмет набуває популярності",
	"AppDetails_WorkshopFeaturedItem": "Популярний предмет",
	"AppDetails_WorkshopFeaturedMoreInfo": "Докладніше",
	"AppDetails_WorkshopFeaturedHideItem": "Сховати цей предмет",
	"AppDetails_WorkshopFileSize": "Розмір файлу: %1$s",
	"AppDetails_WorkshopFileSizeBytes": "%1$s байт",
	"AppDetails_WorkshopFileSizeKb": "%1$s КБ",
	"AppDetails_WorkshopFileSizeMb": "%1$s МБ",
	"AppDetails_WorkshopFileSizeGb": "%1$s ГБ",
	"AppDetails_WorkshopLastUpdated": "Останнє оновлення: %1$s",
	"DLCStatus_installed": "Інстальовано",
	"DLCStatus_notinstalled": "Не інстальовано",
	"DLCStatus_downloading": "Завантаження",
	"DLC_DateAdded": "Додано: %1$s",
	"AppDetails_ManageDLC": "Управляти додатковим вмістом (%1$s)",
	"AppDetails_ManageMyDLC": "Управляти додатковим вмістом",
	"AppDetails_ViewStoreDLC": "Показати додатковий вміст у крамниці",
	"AppDetails_DLCSpotlight": "Додано нещодавно отриманий додатковий вміст, його буде інстальовано разом із грою. Управляйте своїм додатковим вмістом %1$s.",
	"AppDetails_DLCSpotlight_Installed": "Нещодавно отриманий додатковий вміст автоматично інстальовано. Управляйте своїм додатковим вмістом %1$s.",
	"AppDetails_DLCSpotlight_here": "ось тут",
	"ManageDLC_Title": "Управління додатковим вмістом",
	"ManageDLC_Column_Name": "Назва",
	"ManageDLC_Column_DateAdded": "Додано",
	"ManageDLC_Column_Enabled": "Увімкнено",
	"ManageDLC_Column_Installed": "Інстальовано",
	"ManageDLC_Search": "Пошук…",
	"ManageDLC_Installed": "Інстальовано %1$s із %2$s",
	"ManageDLC_ViewMore": "Переглянути більше в крамниці",
	"ManageDLC_NoResults": "Немає результатів для «%1$s»",
	"AppDetails_ViewBadgePage": "Сторінка значка",
	"AppDetails_VisitTradeForum": "Форум обміну",
	"AppDetails_BuyCards": "Купити відсутні картки на ринку",
	"AppDetails_SellCards": "Продати ці картки на ринку",
	"AppDetails_SearchCard": "Показати цю картку на ринку",
	"AppDetails_ShowFriendsList": "Показати список друзів",
	"AppDetails_ViewFriendsWhoPlay": "Показати всіх друзів, які грали",
	"AppDetails_Link_Discussions": "Обговорення",
	"AppDetails_Link_FindGroups": "Знайти групи",
	"AppDetails_Link_GameHub": "Центр спільноти",
	"AppDetails_Link_Guides": "Посібники",
	"AppDetails_Link_Store": "Сторінка в крамниці",
	"AppDetails_Link_Support": "Підтримка",
	"AppDetails_Link_Workshop": "Майстерня",
	"AppDetails_Link_Market": "Ринок",
	"AppDetails_Link_Controller": "Конфігурація контролера",
	"AppDetails_SocialMediaLink": "%1$s у %2$s",
	"AppDetails_SocialMediaType_4": "Twitter",
	"AppDetails_SocialMediaType_5": "Twitch",
	"AppDetails_SocialMediaType_6": "YouTube",
	"AppDetails_SocialMediaType_7": "Facebook",
	"AppDetails_Screenshot": "Знімок екрана",
	"AppDetails_Screenshot_Caption": "Підпис: %1$s",
	"AppDetails_Screenshot_Date": "Дата: %1$s",
	"AppDetails_Screenshot_Dimensions": "Розмір: %1$s на %2$s пікс.",
	"AppDetails_Screenshot_Uploaded": "Вивантажено: %1$s о %2$s",
	"AppDetails_OpenScreenshotUploader": "Відкрити вивантажувач знімків екрана",
	"AppDetails_ViewUploadedScreenshots": "Переглянути вивантажені знімки екрана",
	"AppDetails_ManageMyScreenshot": "Управляти моїми знімками екрана",
	"AppDetails_ManageMyScreenshot_Plural": "Управляти моїми знімками екрана (%1$s)",
	"AppDetails_HowToScreenshot": "Ви можете зробити знімок екрана натисканням %1$s під час гри.",
	"AppDetails_ChangeMyScreenshotKey": "Змінити клавішу для знімка екрана",
	"AppDetails_NoScreenshots": "Ви ще не робили жодних знімків екрана",
	"AppDetails_Screenshot_SpoilerAlert": "Можливі спойлери. Наведіть вказівник, щоб побачити зображення.",
	"AppDetails_Artwork": "Творча робота",
	"AppDetails_Video": "Відео",
	"AppDetails_CommunityItem": "Вміст від спільноти",
	"AppDetails_CommunityFeed_OutOfContent": "Немає додаткового вмісту",
	"AppDetails_CommunityFeed_Inappropriate": "Вміст може бути неприйнятним для всієї аудиторії",
	"AppDetails_CommunityFeed_ViewContent": "Переглянути вміст",
	"AppDetails_CommunityFeed_EditPreferences": "Редагувати вподобання",
	"AppDetails_CommunityFeed_LoadCommunity": "Завантажити вміст від спільноти",
	"AppBox_NewToLibrary": "Нове в бібліотеці",
	"AppBox_ComingSoon": "Незабаром",
	"AppBox_NewToLibrary_Short": "Нове",
	"AppBox_ComingSoon_Short": "Незабаром",
	"AppBox_PlayTimeHeader": "Зіграно часу",
	"AppBox_RecentPlayTime_Hours": "%1$s год за останні два тижні",
	"AppBox_RecentPlayTime_Minutes": "%1$s хв за останні два тижні",
	"AppBox_TotalPlayTime_Hours": "Всього: %1$s год",
	"AppBox_TotalPlayTime_Minutes": "Всього: %1$s хв",
	"AppActivity_Achieved": " отримує досягнення",
	"AppActivity_PostedScreenshot": " ділиться знімком екрана",
	"AppActivity_PostedScreenshot_Plural": " ділиться знімками екрана (%1$s)",
	"AppActivity_PostedVideo": " ділиться відео",
	"AppActivity_PostedVideo_Plural": " ділиться відео (%1$s)",
	"AppActivity_ReceivedNewGame": " тепер володіє %1$s",
	"AppActivity_PlayedGameFirstTime": " вперше грає у %1$s",
	"AppActivity_LaunchedSoftwareFirstTime": " вперше запускає %1$s",
	"AppActivity_AddedGameToWishlist": " додає %1$s до свого %2$s.",
	"AppActivity_Wishlist": "списку бажаного",
	"AppActivity_Achieved_PlusMore": "…і ще кілька досягнень: %1$s",
	"AppActivity_Achieved_PlusMore_Label": "Переглянути всі досягнення %1$s",
	"AppActivity_NoActivity": "Відсутня діяльність розробників цього продукту чи ваших друзів.",
	"AppActivity_UserStatus_Time": " публікує оновлення статусу о %1$s",
	"AppActivity_UserStatus": " публікує оновлення статусу",
	"AppActivity_StatusUpdate": "Опублікуйте статус для друзів",
	"AppActivity_StatusUpdate_Post": "Скажіть щось про цю гру друзям…",
	"AppActivity_StatusUpdate_Software_Post": "Скажіть щось про це програмне забезпечення друзям…",
	"AppActivity_Comment_Reply": "Відповісти…",
	"AppActivity_PostStatusUpdate": "Опублікувати",
	"AppActivity_FetchMore": "Завантажити більше діяльності",
	"AppActivity_EndofFeed": "Кінець діяльності",
	"AppActivity_DeleteUserNews": "Клацніть, щоби видалити цей допис.",
	"AppActivity_ConfirmDeleteTitle": "Видалити допис статусу",
	"AppActivity_ConfirmDeleteTitle_Desc": "Ви дійсно бажаєте видалити цей допис? Цю дію не можна буде скасувати.",
	"AppActivity_RecommendedGame": " публікує рецензію на цю гру",
	"AppActivity_RecommendedGame_ReadMore": "Докладніше",
	"AppActivity_RatingDetails": "%1$s людей це оцінили",
	"AppActivity_RatingDetails_1Other": "1 особа це оцінила — %1$s",
	"AppActivity_RatingDetails_2Others": "%1$s людей це оцінили, зокрема %2$s та %3$s",
	"AppActivity_RatingDetails_User": "Ви це оцінили",
	"AppActivity_RatingDetails_User_1Other": "%1$s людей це оцінили, зокрема ви та %2$s",
	"AppActivity_RatingDetails_User_2Others": "%1$s людей це оцінили, зокрема ви, %2$s та %3$s",
	"AppActivity_RatingDetails_PublishedFile": "Вподобань: %1$s",
	"AppActivity_RateUp": "Подобається",
	"AppActivity_ConfirmDeleteCommentTitle": "Видалити коментар",
	"AppActivity_ConfirmDeleteCommentTitle_Desc": "Ви дійсно бажаєте видалити цей коментар? Ця дія незворотна.",
	"AppActivity_MakeCommentsVisible": "Переглянути попередні коментарі (ще %1$s)",
	"AppActivity_Settings": "Налаштування",
	"AppActivity_ViewComments": "Переглянути коментарі",
	"AppActivity_AddComments": "Додати коментар",
	"AppActivity_ContributeComments": "Коментувати",
	"AppActivity_SteamTradingCards_EarnedTradingCards": " отримує колекційні картки",
	"AppActivity_SteamTradingCards_EarnedTradingCard": " отримує колекційну картку",
	"AppActivity_SteamTradingCards_EarnedBoosterPack": " отримує набір карток",
	"AppActivity_SteamTradingCards_BadgeCrafted": " створює значок",
	"AppActivity_ViewLatestNews": "Переглянути останні новини",
	"AppActivity_EventType_GameUpdate": "Оновлення гри",
	"AppSpotlight_PostGameSummary": "Підсумки гри",
	"AppDetails_Shortcut_Explanation": "Деяка інформація про %1$s недоступна через те, що це стороння гра або модифікація. Steam все одно може запустити цю гру, і в більшості випадків оверлей буде доступним.",
	"AppDetails_Takeover_Update_Header": "Якщо ви пропустили",
	"AppDetails_Takeover_Update_ViewAll": "Переглянути всі оновлення гри (%1$s)",
	"AppDetails_Takeover_Update_ReadMore": "Докладніше",
	"AppDetails_Takeover_DLC_Header": "Додано нові продукти",
	"AppDetails_Takeover_DLC_ViewInStore": "Переглянути %1$s в крамниці",
	"AppDetails_Takeover_Achievements_Header": "Зіграно %2$s. У вас нове досягнення…",
	"AppDetails_Takeover_Achievements_Header_Plural": "Зіграно %2$s. У вас нові досягнення…",
	"AppDetails_Takeover_TradingCards_Header": "Зіграно %2$s. У вас новий предмет…",
	"AppDetails_Takeover_TradingCards_Header_Plural": "Зіграно %2$s. У вас нові предмети…",
	"AppDetails_ViewMyInventory": "Переглянути мій інвентар",
	"AppDetails_ViewInMyInventory": "Переглянути в інвентарі",
	"AppDetails_Soundtrack_TotalTracks": "Доріжок: %1$s",
	"AppDetails_Soundtrack_DiscNumber": "Диск %1$s",
	"AppDetails_Soundtrack_TrackCount": "Доріжок: %1$s",
	"AppDetails_Soundtrack_PlayAlbum": "Відтворити альбом",
	"AppDetails_Soundtrack_DownloadAlbum": "Завантажити альбом",
	"AppDetails_Soundtrack_AddToQueue": "Додати в список",
	"AppDetails_Soundtrack_AddToPlaylist": "Додати в список відтворення",
	"AppDetails_Soundtrack_ViewOnDisk": "Переглянути на диску",
	"AppDetails_Soundtrack_ViewAdditionalArtwork": "Переглянути ілюстрації",
	"AppDetails_Soundtrack_ViewStorePage": "Переглянути в крамниці",
	"AppDetails_Soundtrack_Support": "Підтримка",
	"AppDetails_Soundtrack_ParentAppLink": "Саундтрек для %1$s",
	"AppPortraitHover_DownloadStatusTitle": "Завантаження",
	"AppPortraitHover_DownloadStatusTitle_Update": "Завантаження оновлення",
	"AppPortraitHover_DaysSinceLastUpdate": "Оновлено %1$s",
	"AppPortraitHover_FriendsPlaying": "Друзів грає: %1$s",
	"MajorUpdate_ViewDetails": "Подробиці",
	"MajorUpdate_NextUpdate": "Наступне оновлення",
	"MajorUpdate_PostTime": "Опубліковано %1$s дн. тому о %2$s:%3$s",
	"MajorUpdate_PostTimeToday": "Опубліковано сьогодні о %1$s:%2$s",
	"MajorUpdate_WatchNow": "Переглянути у SteamTV",
	"MajorUpdate_Type0": "Велике оновлення",
	"MajorUpdate_Type1": "Трансляція наживо",
	"MajorUpdate_Type14": "Велике оновлення",
	"MajorUpdate_Context_RemoveThisUpdate": "Вилучити це оновлення",
	"MajorUpdate_Context_ShowMeFewerForApp": "Показувати менше від %1$s",
	"MajorUpdate_Context_ShowMeMoreForApp": "Показувати більше від %1$s",
	"MajorUpdate_Context_ResetHiddenUpdates": "Знову показати всі оновлення",
	"MajorUpdate_Context_WhyAmISeeingThis": "Чому я це бачу?",
	"MajorUpdate_Context_WhyAmISeeingThis_Text": "Це велике оновлення для продукту з вашої бібліотеки, у якому ви провели понад 20 годин.",
	"MajorUpdate_Context_WhyAmISeeingThis_Close": "Закрити",
	"CustomArt_ErrorTitle": "Помилка",
	"CustomArt_BadFileType": "Файл повинен бути у форматі JPG або PNG.",
	"CustomArt_UnknownError": "Під час встановлення вашого зображення сталася помилка.",
	"CustomArt_SetCustomBackground": "Встановити своє тло",
	"CustomArt_ClearCustomBackground": "Прибрати своє тло",
	"CustomArt_SetCustomLogo": "Встановити свій логотип",
	"CustomArt_ClearCustomLogo": "Прибрати свій логотип",
	"CustomArt_EditLogoPosition": "Змінити розташування логотипу",
	"CustomArt_ResetLogoPosition": "Скинути розташування логотипу",
	"CustomArt_DoneEditingLogo": "Готово",
	"AppDetails_LibraryInUse": "Бібліотека використовується",
	"AppDetails_InSharedLibrary": "З бібліотеки",
	"FriendContextMenu_OpenFriends": "Відкрити список друзів і чат",
	"FriendContextMenu_ViewProfile": "Переглянути профіль",
	"Generic_ScrollToTop": "Прокрутити вгору",
	"Generic_ViewGameDetails": "Переглянути гру в бібліотеці",
	"GameDetails_CollectionContext_GoTo": "Перейти до колекції",
	"GameDetails_CollectionContext_Remove": "Вилучити з колекції",
	"ArtworkModal_ViewAll": "Переглянути знімки екрана",
	"ArtworkModal_FileSize": "Розмір файлу",
	"ArtworkModal_Posted": "Опубліковано",
	"ArtworkModal_Size": "Розмір",
	"ArtworkModal_CreatedBy": "Автор:",
	"ArtworkModal_ScrollForMore": "Прокрутіть вниз, щоби побачити коментарі",
	"ArtworkModal_ScrollForDetails": "Прокрутіть вниз для перегляду подробиць",
	"CommunityItem_Menu_Report": "Поскаржитися",
	"ReportItem_Title": "Поскаржитися на предмет",
	"ReportItem_Description": "Опишіть, чому цей предмет порушує правила використання Steam. Також додайте будь-яку відповідну інформацію чи посилання. Після подання цю скаргу неможливо скасувати.",
	"ReportItem_Description_Line2": "Оскаржені предмети не з’являтимуться у вашій бібліотеці.",
	"ReportItem_DMCA": "Якщо ви — правовласник і хочете поскаржитися на порушення авторських прав, то скористайтеся %1$s нашою формою, яка відповідає політиці DMCA",
	"ReportItem_DMCA_LinkText": "ось тут",
	"ReportItem_Error": "Під час надсилання запиту до наших серверів сталася помилка. Спробуйте пізніше знову.",
	"ReportItem_SubmitReport": "Надіслати скаргу",
	"RemoveFreeApp_Title": "Вилучити зі свого акаунта",
	"RemoveFreeApp_Description": "%1$s додано до вашого акаунта за безкоштовною ліцензією. Ви можете прибрати продукт зі свого акаунта та вилучити з бібліотеки Steam і списку ігор у власності.",
	"RemoveFreeApp_Question": "Чи бажаєте ви вилучити %1$s зі свого акаунта?",
	"RemoveFreeApp_Remove": "Вилучити",
	"RemoveFreeApp_Removing": "Вилучення %1$s",
	"RemoveFreeApp_Error": "Під час вилучення %1$s сталася помилка",
	"UninstallDialog_Title": "Видалити",
	"UninstallDialog_Uninstall": "Видалити",
	"UninstallDialog_ErrorMessage": "Не вдалося видалити %1$s:",
	"UninstallDialog_Busy": "Наразі триває інша операція інсталювання/видалення. Будь ласка, зачекайте, доки вона завершиться.",
	"UninstallDialog_SecuROM": "Видалення цього застосунка потребує Інтернет-підключення.",
	"UninstallDialog_UnknownError": "Під час видалення цього застосунка сталася непередбачена помилка.",
	"UninstallDialog_AppUpdateError": "Помилка видалення — %1$s",
	"UninstallDialog_Confirmation_Single": "Ви точно хочете видалити %1$s з цього комп’ютера? Продукт залишиться у вашій бібліотеці, але щоби пограти в нього знову, вам доведеться заново завантажити весь його вміст.",
	"UninstallDialog_Confirmation_Multiple": "Ви точно хочете видалити ці продукти зі свого комп’ютера? Вони залишаться у вашій бібліотеці, але щоби пограти в них знову, вам доведеться заново завантажити весь їхній вміст.",
	"UninstallingDialog_Uninstalling": "Видалення",
	"UninstallingDialog_UninstallingApp": "Видалення %1$s",
	"UninstallingDialog_WaitingForPassword": "Очікування на пароль",
	"Showcase_AddNewShowcase": "Додати нову полицю",
	"Showcase_DeleteShowcase": "Вилучити цю полицю",
	"Showcase_SelectCategory": "Вибрати полицю",
	"Showcase_EmptyShowcaseHint": "Виберіть те, що хочете бачити на цій полиці. Звідси ви також можете змінювати чи видаляти її!",
	"Showcase_GoToCollection": "Перейти до колекції",
	"Showcase_GoToAllCollections": "Перейти до всіх колекцій",
	"Showcase_AllYourGames": "Усі ігри",
	"Showcase_AllCollections": "Перегляд колекцій",
	"Showcase_RecentGames": "Нещодавні ігри",
	"Showcase_DoneReordering": "Готово",
	"Playtime_TwoWeeks_Minutes": "%1$s хв. зіграно нещодавно",
	"Playtime_TwoWeeks_Hours": "%1$s год. зіграно нещодавно",
	"Playtime_Total_Minutes": "%1$s хв. зіграно всього",
	"Playtime_Total_Hours": "%1$s год. зіграно всього",
	"Playtime_Minutes": "%1$s хв.",
	"Playtime_Hours": "%1$s год.",
	"Playtime_Recently": "%1$s зіграно нещодавно",
	"Playtime_Total": "%1$s зіграно всього",
	"GameList_Search_NoResults_Title": "Не можете знайти те, що шукаєте?",
	"GameList_Search_NoResults_Link": "Пошукайте в крамниці Steam",
	"StreamingClient_Select_ThisMachine": "Цей пристрій",
	"StreamingClient_Select_RemotePlayPhone": "Телефони",
	"StreamingClient_Select_RemotePlayTablet": "Планшети",
	"StreamingClient_Select_RemotePlayMobile": "Мобільні пристрої",
	"StreamingClient_Select_RemotePlayTV": "Телевізори",
	"StreamingClient_Select_RemotePlayTVPhone": "Телевізори й телефони",
	"StreamingClient_Select_RemotePlayTVTablet": "Телевізори та планшети",
	"StreamingClient_Select_RemotePlayTVMobile": "Телевізори й мобільні пристрої",
	"Beta_BetaTag": "БЕТА",
	"Beta_Changelist": "Список змін",
	"Beta_GiveFeedback": "Залишити відгук",
	"ContextMenu_SaveScreenshot": "Зберегти знімок екрана як…",
	"ContextMenu_BrowseScreenshot": "Переглянути знімок екрана",
	"ContextMenu_ManageScreenshots": "Управляти моїми знімками екрана",
	"SteamChina_DurationControl_Init_1": "Healthy Gaming Advisory",
	"SteamChina_DurationControl_Init_2": "Boycott harmful games; reject game piracy.",
	"SteamChina_DurationControl_Init_3": "Exercise self-protection; avoid deception.",
	"SteamChina_DurationControl_Init_4": "Moderation promotes brain health; excess play is harmful to the body.",
	"SteamChina_DurationControl_Init_5": "Well-planned use of your time will lead to a healthy lifestyle.",
	"Steam_AppUpdateError_0": "без помилок",
	"Steam_AppUpdateError_1": "невідома помилка",
	"Steam_AppUpdateError_2": "оновлення призупинено",
	"Steam_AppUpdateError_3": "оновлення скасовано",
	"Steam_AppUpdateError_4": "оновлення в очікуванні",
	"Steam_AppUpdateError_5": "немає ліцензій",
	"Steam_AppUpdateError_6": "немає Інтернет-підключення",
	"Steam_AppUpdateError_7": "сплинув час очікування підключення",
	"Steam_AppUpdateError_8": "вміст досі зашифрований",
	"Steam_AppUpdateError_9": "конфігурація застосунку недоступна",
	"Steam_AppUpdateError_10": "помилка читання з носія",
	"Steam_AppUpdateError_11": "помилка запису на носій",
	"Steam_AppUpdateError_12": "замало вільного місця на носії",
	"Steam_AppUpdateError_13": "файли вмісту пошкоджені",
	"Steam_AppUpdateError_14": "очікування на інсталяційний диск",
	"Steam_AppUpdateError_15": "неприпустиме розташування для інсталяції",
	"Steam_AppUpdateError_16": "продукт запущено",
	"Steam_AppUpdateError_17": "відсутній спільний вміст",
	"Steam_AppUpdateError_18": "не інстальовано",
	"Steam_AppUpdateError_19": "необхідне оновлення",
	"Steam_AppUpdateError_20": "зайнято",
	"Steam_AppUpdateError_21": "сервери вмісту недоступні",
	"Steam_AppUpdateError_22": "конфігурація застосунку неприпустима",
	"Steam_AppUpdateError_23": "конфігурація сховища неприпустима",
	"Steam_AppUpdateError_24": "маніфест недоступний",
	"Steam_AppUpdateError_25": "продукт ще не вийшов",
	"Steam_AppUpdateError_26": "регіон заблокований",
	"Steam_AppUpdateError_27": "пошкоджені файли кешу",
	"Steam_AppUpdateError_28": "відсутній виконуваний файл",
	"Steam_AppUpdateError_29": "неприпустима платформа",
	"Steam_AppUpdateError_30": "непідтримувана файлова система",
	"Steam_AppUpdateError_31": "пошкоджені файли оновлення",
	"Steam_AppUpdateError_32": "завантаження відключені",
	"Steam_AppUpdateError_33": "бібліотека позики заблокована",
	"Steam_AppUpdateError_34": "придбання не підтверджене",
	"Steam_AppUpdateError_35": "запущено інший сеанс",
	"Steam_AppUpdateError_36": "завантаження пошкоджено",
	"Steam_AppUpdateError_37": "носій пошкоджено",
	"Steam_AppUpdateError_38": "відмовлено в правах доступу до файлу",
	"Steam_AppUpdateError_39": "файл вмісту заблоковано",
	"Steam_AppUpdateError_40": "вміст недоступний",
	"Steam_AppUpdateError_41": "виконуваний файл потребує 64-бітної операційної системи",
	"Steam_AppUpdateError_42": "відсутні завантажені файли",
	"Steam_AppUpdateError_43": "недостатньо вільного місця на диску для користувача — перевірте налаштування дискових квот в ОС",
	"Steam_AppUpdateError_44": "ліцензія майданчика заблокована",
	"Steam_AppUpdateError_45": "заблоковано батьківським контролем",
	"Steam_AppUpdateError_46": "помилка процесу створення",
	"Steam_AppUpdateError_47": "клієнт Steam застарів",
	"ShareDialog_Title": "Поділитися",
	"ShareUploadScreenshot_Description": "Вивантажте цей знімок екрану в профіль Steam і стрічку діяльності.",
	"ShareUploadScreenshot_AddCaption": "додайте підпис",
	"ShareUploadScreenshot_CaptionHeader": "Підпис:",
	"ShareUploadScreenshot_TagSpoiler": "Позначити як спойлер",
	"ShareUploadScreenshot_CloudUsage": "Буде використано %1$s з %2$s простору у вашому хмарному сховищі",
	"ShareUploadScreenshot_Uploading": "Вивантаження в Steam",
	"ShareUploadScreenshot_PermissionDenied": "Steam не вдалося вивантажити цей знімок екрана. Вам заборонено вивантажувати вміст через активне блокування на вашому акаунті.",
	"ShareUploadScreenshot_UnexpectedError": "Steam не вдалося вивантажити цей знімок екрана до Steam Cloud. Повторіть спробу пізніше.",
	"DeleteScreenshot_Title": "Видалити знімок екрана",
	"DeleteScreenshot_Single": "Ви дійсно бажаєте назавжди видалити цей знімок екрана зі свого жорсткого диска?",
	"DeleteScreenshot_Failed": "Steam не вдалося видалити вибраний знімок екрана з вашого диска.",
	"AppDetailsAchievement_Hidden": "Приховане досягнення",
	"AppDetailsAchievement_HiddenDesc": "Продовжуйте грати, щоб відкрити це досягнення.",
	"Demo_SpotlightIntro": "Спробуйте повну версію гри",
	"Demo_VisitStorePage": "Відкрити сторінку крамниці",
	"SteamReviewScore_9": "Виключно схвальні",
	"SteamReviewScore_8": "Дуже схвальні",
	"SteamReviewScore_7": "Схвальні",
	"SteamReviewScore_6": "Переважно схвальні",
	"SteamReviewScore_5": "Змішані",
	"SteamReviewScore_4": "Переважно негативні",
	"SteamReviewScore_3": "Негативні",
	"SteamReviewScore_2": "Дуже негативні",
	"SteamReviewScore_1": "Виключно негативні"
}
