{
	"Generic_Okay": "OK",
	"Generic_Close": "Κλείσιμο",
	"Generic_Open": "Άνοιγμα",
	"Generic_GotIt": "Εντάξει!",
	"Generic_Share": "Κοινοποίηση",
	"Generic_Upload": "Ανέβασμα",
	"Generic_Delete": "Διαγραφή",
	"Privacy_Public": "Δημόσια",
	"Privacy_FriendsOnly": "Φίλοι μόνο",
	"Privacy_Private": "Ιδιωτικό",
	"AppType_0": "Μη έγκυρο",
	"AppType_1": "Παιχνίδια",
	"AppType_2": "Λογισμικό",
	"AppType_4": "Εργαλεία",
	"AppType_20": "DLC",
	"AppType_800": "Βίντεο",
	"AppType_2000": "Μουσικές υπόκρουσεις",
	"AppType_Singular_0": "Μη έγκυρο",
	"AppType_Singular_1": "παιχνίδι",
	"AppType_Singular_2": "εφαρμογή",
	"AppType_Singular_4": "εργαλείο",
	"AppType_Singular_20": "DLC",
	"AppType_Singular_800": "βίντεο",
	"AppType_Singular_2000": "μουσική",
	"AppType_Singular_8000": "κόμικ",
	"AppType_Singular_40000000": "συντόμευση",
	"FilterEdit_SavedFilters": "Αποθ. φίλτρα",
	"FilterEdit_FirstColumnHeader": "Τύπος φίλτρου",
	"FilterEdit_Customize": "Προσαρμογή",
	"FilterEdit_SearchModeHeader": "Προχ. φίλτρα",
	"FilterEdit_CollectionModeHeader": "Επεξεργασία φίλτρων συλλογής",
	"CollectionEdit_CollectionNameField": "Όνομα συλλογής:",
	"CollectionEdit_RenameButton": "Μετονομασία συλλογής",
	"Collection_DynamicCollection": "Δυναμική συλλογή",
	"FilterEdit_AdvancedTooltip": "Προχωρημένες επιλογές φιλτραρίσματος για να διυλίσετε τη λίστα παιχνιδιών σας ανά γένος, χαρακτηριστικά κτλ.",
	"Collection_FreezeDynamicCollection_Button": "Παγωμένη",
	"Collection_FreezeDynamicCollection_ToolTip": "Μετατροπή αυτής της δυναμικής συλλογής σε μια απλή, παγώνοντας την τρέχουσα λίστα παιχνιδιών.",
	"Collection_FreezeDynamicCollection_DialogTitle": "Παγωμένη συλλογή",
	"Collection_FreezeDynamicCollection_Confirmation": "Θέλετε σίγουρα να μετατρέψετε αυτή τη συλλογή; Δε θα ενημερώνεται πλέον δυναμικά όταν προσθέτετε ταιριαστά παιχνίδια στη συλλογή παιχνιδιών σας.",
	"Collection_ResetDialogTitle": "Επαναφορά συλλογών",
	"Collection_ResetConfirmation": "Θέλετε σίγουρα να επαναφέρετε τη λίστα συλλογών και και να επαναεισάγετε τις παλιές σας κατηγορίες;",
	"Collection_AfterResetSummary_NoCollections": "Δε θα έχετε συλλογές μετά την επαναφορά.",
	"Collection_AfterResetSummary_CountAndNames": "Θα έχετε τις ακόλουθες %1$s συλλογές μετά την επαναφορά: %2$s",
	"Collection_ResetFailed": "Αδυναμία επαναφοράς συλλόγων",
	"FilterEdit_SelectedFilters": "Επιλεγμένα φίλτρα",
	"FilterEdit_SaveCollectionNameInputPrompt": "Εισάγετε ένα όνομα για τη συλλογή",
	"FilterEdit_SaveOverwrite": "Η συλλογή «%1$s» υπάρχει ήδη. Αντικατάσταση;",
	"FilterEdit_SaveCollection": "Αποθήκευση ως συλλογή",
	"FilterEdit_SaveDynamicCollectionWithIcon": "Αποθήκευση ως %1$s δυναμική συλλογή",
	"FilterEdit_SaveDynamicCollectionNoIcon": "Αποθήκευση ως δυναμική συλλογή",
	"FilterEdit_SaveCollectionVerbose": "Αποθήκευση αυτής της αναζήτησης ως συλλογή ώστε να μπορείτε να τη χρησιμοποιήσετε ξανά στο μέλλον. Μπορείτε πάντα να επεξεργαστείτε, μετονομάστε ή να διαγράψετε αυτή τη συλλογή στο μέλλον ή να σύρετε αντικείμενα μέσα ή έξω της.",
	"FilterEdit_SaveStandardCollectionButtonDesc": "Μια συλλογή είναι ένας απλός τρόπος να οργανώσετε τα παιχνίδια σας. Σύρετε τίτλους στη συλλογή ή πατήστε δεξί κλικ σε έναν τίτλο για να τον προσθέσετε σε μια υπάρχουσα συλλογή.",
	"FilterEdit_SaveDynamicCollectionButtonDesc": "Οι δυναμικές συλλογές χρησιμοποιούν φίλτρα για να δημιουργήσουν συλλογές που ενημερώνονται διαρκώς.",
	"FilterEdit_SelectCollectionType": "Επιλέξτε έναν τύπο συλλογής",
	"FilterEdit_SelectCollectionTypeButtonCreate": "Δημιουργία συλλογής",
	"FilterEdit_SelectCollectionTypeButtonCreateDynamic": "Δημιουργία δυναμικής συλλογής",
	"FilterEdit_RequiredField": "( ΑΠΑΙΤΕΙΤΑΙ )",
	"FilterEdit_SearchPrompt": "Αναζήτηση ανά όνομα",
	"FilterEdit_ClearSearch": "Έξοδος από αναζήτηση",
	"FilterEdit_SearchResults": "ΑΠΟΤ. ΑΝΑΖΗΤΗΣΗΣ",
	"FilterEdit_CollectionsHiddenPromptTitle": "Οι συλλογές είναι κρυφές",
	"FilterEdit_CollectionsHiddenPrompt": "Θέλετε να αλλάξετε την προβολή λίστας παιχνιδιών ώστε η νέα συλλογή να είναι ορατή;",
	"FilterEdit_AcceptGameListViewChange": "Ναι, εμφάνιση συλλογών",
	"FilterEdit_RejectGameListViewChange": "Όχι, να μην αλλάξει η προβολή",
	"AdvancedSearch_PaneTitle": "Αναζήτηση ανά τύπο",
	"AdvancedSearch_PlayerSection": "Παίκτες",
	"AdvancedSearch_HardwareSection": "Υποστήριξη υλικού",
	"AdvancedSearch_FeatureSection": "Χαρακτηριστικά",
	"AdvancedSearch_StateSection": "Κατάσταση παιχνιδιού",
	"AdvancedSearch_GenreSection": "Είδος",
	"AdvancedSearch_StoreTagSection": "Ετικέτες καταστήματος",
	"AdvancedSearch_StoreTagPrompt": "εισάγετε μια ετικέτα",
	"FilterCategory_1": "Κατάσταση",
	"FilterCategory_Features": "ΧΑΡΑΚΤΗΡΙΣΤΙΚΟ",
	"FilterCategory_3": "Κατηγορία",
	"FilterCategory_4": "Ετικέτα καταστήματος",
	"FilterCategory_Type": "ΤΥΠΟΣ",
	"FilterCategory_Genre": "ΕΙΔΟΣ",
	"FilterCategory_PlayState": "ΚΑΤΑΣΤΑΣΗ",
	"FilterElement_VR": "VR",
	"FilterElement_Tooltip_VR": "Συμπερίληψη παιχνιδιών που υποστηρίζουν υλικό εικονικής πραγματικότητας.",
	"FilterElement_Installed": "Εγκατεστημένο τοπικά",
	"FilterElement_Tooltip_Installed": "Συμπερίληψη παιχνιδιών που είναι εγκατεστημένα σε αυτόν τον υπολογιστή.",
	"FilterElement_ReadyToPlay": "Έτοιμα για παιχνίδι",
	"FilterElement_Tooltip_ReadyToPlay": "Συμπερίληψη παιχνιδιών που μπορείτε να παίξετε τοπικά ή με μετάδοση από άλλον υπολογιστή.",
	"FilterElement_PlayedPreviously": "Παιγμένα",
	"FilterElement_Tooltip_PlayedPreviously": "Συμπερίληψη παιχνιδιών που έχετε ήδη παίξει.",
	"FilterElement_Unplayed": "Μη παιγμένα",
	"FilterElement_Tooltip_Unplayed": "Συμπερίληψη παιχνιδιών που δεν έχετε παίξει ακόμα.",
	"FilterElement_FullControllerSupport": "Χειριστήριο (πλήρης)",
	"FilterElement_Tooltip_FullControllerSupport": "Συμπερίληψη παιχνιδιών που μπορούν να παιχτούν πλήρως με χειριστήριο.",
	"FilterElement_PartialControllerSupport": "Χειριστήριο (μερική)",
	"FilterElement_Tooltip_PartialControllerSupport": "Συμπερίληψη παιχνιδιών που μπορούν να παιχτούν με χειριστήριο αλλά μπορεί να απαιτούν πληκτρολόγιο και ποντίκι κατά την εγκατάσταση ή για περιορισμένες αλληλεπιδράσεις.",
	"FilterElement_VRSupported": "Υποστήριξη VR",
	"FilterElement_TradingCards": "Κάρτες ανταλλαγών",
	"FilterElement_Tooltip_TradingCards": "Συμπερίληψη παιχνιδιών που διαθέτουν κάρτες ανταλλαγών Steam.",
	"FilterElement_Workshop": "Εργαστήρι",
	"FilterElement_Tooltip_Workshop": "Συμπερίληψη παιχνιδιών με ενσωμάτωση εργαστηρίου Steam.",
	"FilterElement_Achievements": "Επιτεύγματα",
	"FilterElement_Tooltip_Achievements": "Συμπερίληψη παιχνιδιών που ανταμείβουν επιτεύγματα Steam.",
	"FilterElement_SinglePlayer": "Ενός παίκτη",
	"FilterElement_Tooltip_SinglePlayer": "Συμπερίληψη παιχνιδιών με λειτουργία ενός παίκτη.",
	"FilterElement_MultiPlayer": "Πολλών παικτών",
	"FilterElement_Tooltip_MultiPlayer": "Συμπερίληψη παιχνιδιών με λειτουργία πολλών παικτών.",
	"FilterElement_CoOp": "Συνεργατικά",
	"FilterElement_Tooltip_CoOp": "Συμπερίληψη παιχνιδιών με συνεργατική λειτουργία πολλών παικτών.",
	"FilterElement_GenreAction": "Δράση",
	"FilterElement_Tooltip_GenreAction": "Συμπερίληψη παιχνιδιών δράσης.",
	"FilterElement_GenreAdventure": "Περιπέτεια",
	"FilterElement_Tooltip_GenreAdventure": "Συμπερίληψη παιχνιδιών περιπέτειας.",
	"FilterElement_GenreCasual": "Χαλαρά",
	"FilterElement_Tooltip_GenreCasual": "Συμπερίληψη χαλαρών παιχνιδιών.",
	"FilterElement_GenreIndie": "Indie",
	"FilterElement_Tooltip_GenreIndie": "Συμπερίληψη indie παιχνιδιών.",
	"FilterElement_GenreMMO": "MMO",
	"FilterElement_Tooltip_GenreMMO": "Συμπερίληψη παιχνιδιών πάρα πολλών παικτών.",
	"FilterElement_GenreRacing": "Αγώνας ταχύτητας",
	"FilterElement_Tooltip_GenreRacing": "Συμπερίληψη παιχνιδιών αγώνων ταχύτητας.",
	"FilterElement_GenreRPG": "RPG",
	"FilterElement_Tooltip_GenreRPG": "Συμπερίληψη παιχνιδιών ρόλων.",
	"FilterElement_GenreSimulation": "Προσομοίωση",
	"FilterElement_Tooltip_GenreSimulation": "Συμπερίληψη παιχνιδιών προσομοίωσης.",
	"FilterElement_GenreSports": "Αθλήματα",
	"FilterElement_Tooltip_GenreSports": "Συμπερίληψη αθλητικών παιχνιδιών.",
	"FilterElement_GenreStrategy": "Στρατηγική",
	"FilterElement_Tooltip_GenreStrategy": "Συμπερίληψη παιχνιδιών στρατηγικής.",
	"FilterElement_Tooltip_StoreTag": "Συμπερίληψη εφαρμογών με ετικέτα %1$s στο Steam.",
	"FilterElement_SteamCloud": "Steam Cloud",
	"FilterElement_Tooltip_SteamCloud": "Συμπερίληψη παιχνιδιών που αποθηκεύονται στο Steam Cloud.",
	"FilterElement_RemotePlayTogether": "Remote Play Together",
	"FilterElement_Tooltip_RemotePlayTogether": "Συμπερίληψη παιχνιδιών που υποστηρίζουν Remote Play Together.",
	"CollectionViewHeader_Tooltip_ManuallyAddedApp": "Αυτό το παιχνίδι προστέθηκε στη συλλογή αυτόματα.",
	"CollectionViewHeader_Tooltip_ManuallyRemovedApp": "Αυτό το παιχνίδι αφαιρέθηκε από αυτή τη συλλογή.",
	"CollectionViewHeader_Tooltip_ManuallyRemovedApps_WithCount": "%1$s παιχνίδια αφαιρέθηκαν από αυτή τη συλλογή.",
	"CollectionViewHeader_ManuallyRemovedApps_WithCount": "%1$s αφαιρέθηκαν",
	"CollectionView_EmptyReadOnlyCollection": "Τίποτα να δείτε εδώ",
	"CollectionView_EmptyDynamicCollection_Line1": "Δεν ταιριάζει κανένα παιχνίδι αυτό το φίλτρο!",
	"CollectionView_EmptyDynamicCollection_Line2": "Αλλάξτε το φίλτρο ή σύρτε παιχνίδια εδώ για να χτίσετε αυτή τη συλλογή.",
	"CollectionView_EmptyCollection": "Σύρετε παιχνίδια εδώ για να χτίσετε αυτή αυτή τη συλλογή.",
	"CollectionView_EmptyCollection_BecauseFilter": "%1$s παιχνίδι σε αυτή τη συλλογή δε φαίνεται αυτή τη στιγμή λόγω του επιλεγμένου φίλτρου προβολής σας.",
	"CollectionView_EmptyCollection_BecauseFilter_Plural": "%1$s παιχνίδια σε αυτή τη συλλογή δε φαίνονται αυτή τη στιγμή λόγω του επιλεγμένου φίλτρου προβολής σας.",
	"CollectionView_MissingCollection": "Δε βρέθηκε συλλογή.",
	"CollectionView_GamesExcluded": "+%1$s",
	"CollectionView_GamesExcluded_Desc": "τίτλοι δεν είναι έτοιμοι για παιχνίδι",
	"AllCollectionsView_Title": "Οι συλλογές σας",
	"AllCollectionsView_InfoIcon": "Δημιουργήστε %1$s για να οργανώσετε τους τίτλους σας όπως σας βολεύει ή δημιουργήστε %2$s για να οργανώσετε τίτλους ανά ένα σετ φίλτρων. %3$s",
	"AllCollectionsView_InfoIconCollections": "Συλλογές",
	"AllCollectionsView_InfoIconDynamicCollections": "Δυναμικές συλλογές",
	"AllCollectionsView_InfoIconFav": "Οι %1$s σας σας θα εμφανίζονται πάντα εδώ στην κορυφή της σελίδας.",
	"AllCollectionsView_InfoIconFavorites": "Αγαπημένα",
	"AllCollectionsView_AddCollection": "Δημιουργία νέας συλλογής",
	"AllCollectionsView_DragToAddCollection": "ΣΥΡΕΤΕ ΕΔΩ ΓΙΑ ΔΗΜΙΟΥΡΓΙΑ ΝΕΑΣ ΣΥΛΛΟΓΗΣ",
	"GameList_Home": "ΑΡΧΙΚΗ",
	"GameList_Search": "Αναζήτηση",
	"GameList_Category_Uncategorized": "Χωρίς κατηγορία",
	"GameList_Category_Favorites": "Αγαπημένα",
	"GameList_Category_Hidden": "Κρυφά",
	"GameList_Category_Hidden_Tooltip": "Τα κρυφά παιχνίδια δε θα εμφανίζονται στη συλλογή σας εκτός αν ψάξετε για αυτά. Μπορείτε να δείτε όλα τα κρυφά παιχνίδια από το μενού «Προβολή» στο πάνω μέρος.",
	"GameList_Category_YourCollections": "ΟΙ ΣΥΛΛΟΓΕΣ ΣΑΣ",
	"GameList_Category_SharedLibraries": "Κοινές συλλογές",
	"GameList_SectionHeader_SearchResults": "Αποτελέσματα από αναζήτηση και φιλτράρισμα",
	"GameList_SectionHeader_AddedManually": "Προστέθηκε χειροκίνητα",
	"GameList_SectionHeader_RemovedManually": "Αφαιρέθηκε χειροκίνητα",
	"GameList_SectionHeader_NoRecentActivity": "Χωρίς καταγεγραμμένη δραστηριότητα",
	"GameList_View_Collections": "Οι συλλογές σας",
	"GameList_View_ThisCollection": "Προβολή αυτής της συλλογής",
	"GameList_View_OneCollection": "Προβολή συλλογής",
	"GameList_View_SearchResults": "Αποτελέσματα αναζήτησης",
	"GameList_View_ShowAllCollections": "Εμφάνιση όλων των συλλογών",
	"GameList_View_GroupByCollections": "Οργάνωση ανά συλλογή",
	"GameList_View_ExitSearch": "Έξοδος από αναζήτηση",
	"GameList_View_All": "Όλα",
	"GameList_View_Recent": "Πρόσφατα",
	"GameList_View_SortByRecent": "Ταξινόμηση ανά πρόσφατη δραστηριότητα",
	"GameList_View_ShowOnlyReadyToPlay": "Εμφάνιση μόνο έτοιμων για παιχνίδι",
	"GameList_View_ShowingReadyToPlay": "Εμφάνιση μόνο έτοιμων για παιχνίδι",
	"GameList_View_ShowingOnlyReadyToPlay": "Εμφανίζονται μόνο έτοιμα για παιχνίδι",
	"GameList_View_ShowOnlyVR": "Εμφάνιση μόνο παιχνιδιών VR",
	"GameList_View_Platform_Linux": "Εμφάνιση μόνο παιχνιδιών που τρέχουν σε Linux",
	"GameList_View_Platform_Apple": "Εμφάνιση μόνο παιχνιδιών που τρέχουν σε macOS",
	"GameList_View_MyOwnGames": "Τα παιχνίδια μου",
	"GameList_View_GamesSharedByOther": "Τα παιχνίδια του %1$s",
	"GameList_View_NothingSelected": "Κανένα",
	"GameList_View_NothingSelected_HelpText": "Τίποτα δεν ταιριάζει αυτό το φίλτρο προβολής.",
	"GameList_Search_GamesCheckbox_Link": "Εμφάνιση παιχνιδιών",
	"GameList_View_GroupSharedLibraries": "Ομάδες ανά συλλογή",
	"GameList_View_GroupingDisabled_ToolTip": "Η ομαδοποίηση είναι ανενεργή σε αυτή την προβολή",
	"GameList_View_ReadyToPlay_ToolTip1": "• Εγκατεστημένα σε αυτή τη συσκευή",
	"GameList_View_ReadyToPlay_ToolTip2": "• Μπορούν να μεταδοθούν από άλλη συσκευή",
	"GameList_Entry_ReadyToPlay_ToolTip": "Θα μεταδοθεί από άλλη συσκευή",
	"GameList_Entry_Invalid_OSType": "Το τρέχον macOS (Catalina) σας δεν είναι ικανό να τρέξει παιχνίδια 32-bit. Αυτό το παιχνίδι δεν μπορεί να τρέξει.",
	"GameList_Entry_Invalid_OSType2": "Αυτό το παιχνίδι έχει το Steam Play ενεργοποιημένο, ώστε να μπορείτε να το παίξετε σε Windows μέσω Bootcamp ή χρησιμοποιώντας ένα PC.",
	"GameList_Entry_Invalid_OSType3": "Μάθετε περισσότερα.",
	"Shelf_SectionHeader_ExpandTooltip": "Επέκταση ραφιού για εμφάνιση περισσότερων σειρών",
	"Shelf_SectionHeader_ExpandTooltipFilter": "Επέκταση ραφιού για εμφάνιση περισσότερων σειρών, δεν είναι καταχωρημένα %1$s αντικείμενα λόγω του φίλτρου προβολής σας",
	"GameList_SectionHeader_AppCountToolTip": "%1$s μη καταχωρημένα λόγω του φίλτρου προβολής σας",
	"GameList_SectionHeader_AppCountToolTipAllHidden": "Τίποτα καταχωρημένο λόγω του φίλτρου προβολής σας",
	"CollectionAction_ViewOnlyThis": "Προβολή μόνο αυτής της συλλογής",
	"CollectionAction_ViewOnlyThisFavorites": "Προβολή μόνο αγαπημένων",
	"CollectionAction_ViewOnlyThisUncategorized": "Προβολή μόνο χωρίς κατηγορία",
	"CollectionAction_Collapse": "Σύμπτυξη",
	"CollectionAction_CollapseAll": "Σύμπτυξη όλων",
	"CollectionAction_CollapseAllCollections": "Σύμπτυξη όλων των συλλογών",
	"CollectionAction_Expand": "Επέκταση",
	"CollectionAction_ExpandAll": "Επέκταση όλων",
	"CollectionAction_ExpandAllCollections": "Επέκταση όλων των συλλογών",
	"CollectionAction_Manage": "Διαχείριση",
	"CollectionAction_Edit": "Επεξεργασία φίλτρων συλλογής",
	"CollectionAction_Rename": "Μετονομασία συλλογής",
	"CollectionAction_Delete": "Αφαίρεση συλλογής",
	"CollectionAction_DeleteDialog": "Αφαίρεση συλλογής",
	"CollectionAction_ConfirmDelete": "Θέλετε σίγουρα να αφαιρέσετε μόνιμα τη συλλογή «%1$s»;",
	"CollectionAction_SaveFailed": "Αδυναμία αποθήκευσης της συλλογής «%1$s»",
	"CollectionAction_CannotOverwrite": "Αδυναμία αντικατάστασης της συλλογής «%1$s». Παρακαλούμε επιλέξτε ένα νέο όνομα.",
	"CollectionAction_DeleteFailed": "Αδυναμία αφαίρεσης της συλλογής «%1$s»",
	"LibraryHome_FriendsActivity": "Δραστηριότητα φίλων",
	"LibraryHome_RecentGames": "Πρόσφατα παιχνίδια",
	"LibraryHome_NewUpdates": "Τι νέο υπάρχει",
	"LibraryHome_YourCollection": "Η πλήρης συλλογή σας",
	"LibraryHome_RecentFriendsActivity": "Πρόσφατη δραστηριότητα φίλων",
	"LibraryHome_NewUpdates_LoweredPriority": "Τώρα εμφανίζονται λιγότερες ενημερώσεις για %1$s.",
	"LibraryHome_NewUpdates_RaisedPriority": "Τώρα εμφανίζονται περισσότερες ενημερώσεις για %1$s.",
	"LibraryHome_NewUpdates_Undo": "Αναίρεση",
	"LibraryHome_RecentFriendsActivity_Empty": "Τίποτα δεν είναι νέο ή δημοφιλές στην ομάδα φίλων σας τώρα. Αυτό το ράφι θα κρύβεται αυτόματα όταν δεν υπάρχει δραστηριότητα προς εμφάνιση.",
	"WhatsNewSettings": "Τι νέο υπάρχει - Ρυθμίσεις",
	"WhatsNew": "Τι νέο υπάρχει",
	"WhatsNewFeatureExplainer": "Τι νέο υπάρχει είναι εκεί που οι δημιουργοί των παιχνιδιών σας επικοινωνούν σχετικά με ενημερώσεις, τουρνουά DLC, συμβάντα και άλλα νέα παιχνιδιού. Το Steam θα εμφανίζει τα πιο σχετικά νέα για εσάς με βάση το χρόνο παιχνιδιού σας, δίνοντας προτεραιότητα σε αυτά που παίξατε πρόσφατα.",
	"WhatsNewFeatureExplainer2": "Μερικά παιχνίδια θα αποκλείονται αυτόματα από το Τι νέο υπάρχει αν δεν έχετε παίξει ποτέ περισσότερο από μερικές ώρες και πέρασε πολύ καιρός από την τελευταία δραστηριότητά σας στο παιχνίδι.",
	"WhatsNewVisibilitySettings": "Ρυθμίσεις ορατότητας",
	"WhatsNewSettings_ShowOnlyForRecentlyPlayed": "Εμφάνιση μόνο για παιχνίδια που έχω παίξει τις τελευταίες 90 μέρες",
	"WhatsNewSettings_ShowOnlyForRecentlyPlayed_Explainer": "(Η ατομική συχνότητα κάθε παιχνιδιού μπορεί να οριστεί με δεξί κλικ σε ένα αντικείμενο νέων.)",
	"WhatsNewSettings_ShowOnlyGameUpdates": "Εμφάνιση μόνο ενημερώσεων προϊόντων, όχι άλλους τύπους συμβάντων και νέων",
	"WhatsNewSettings_ShowOnlyGameUpdates_Explainer": "(Η ατομική συχνότητα κάθε παιχνιδιού μπορεί να οριστεί με δεξί κλικ σε ένα αντικείμενο νέων.)",
	"WhatsNewPrioritySettings": "Ρυθμίσεις προτεραιότητας",
	"WhatsNewPriorityExplainer": "(Κάθε παιχνιδιού μπορεί να οριστεί για να δείχνει περισσότερα ή λιγότερα στο Τι νέο υπάρχει, δοκιμάστε δεξί κλικ σε ένα αντικείμενο για επιλογές.)",
	"WhatsNewYouHaveAskedToShowLessFor": "Έχετε ζητήσει να εμφανίζονται λιγότερα στα ακόλουθα παιχνίδια:",
	"WhatsNewYouHaveNothingShowingLess": "Δεν έχετε ζητήσει να εμφανίζονται λιγότερα για κανένα παιχνίδι ακόμα.",
	"WhatsNewYouHaveAskedToShowMoreFor": "Έχετε ζητήσει να εμφανίζονται περισσότερα στα ακόλουθα παιχνίδια:",
	"WhatsNewYouHaveNothingShowingMore": "Δεν έχετε ζητήσει να εμφανίζονται περισσότερα για κανένα παιχνίδι ακόμα.",
	"WhatsNewYouHaveNItemsHidden": "%1$s παιχνίδια είναι κρυμμένα από τη συλλογή σας και ως εκτούτου κρυμμένα από το Τι νέο υπάρχει.",
	"Library_FriendsActivity_HotRightNowHeading": "Καυτά τώρα",
	"Library_FriendsActivity_HotRightNowHover": "Σας δείχνουμε αυτό το παιχνίδι επειδή ένας αριθμός των φίλων σας παίζουν αυτό το παιχνίδι τώρα.",
	"Library_FriendsActivity_TrendingHeading": "Ανοδικό",
	"Library_FriendsActivity_TrendingHover": "Σας δείχνουμε αυτό το παιχνίδι επειδή μερικοί από τους φίλους σας παίζουν αυτό το παιχνίδι περισσότερο την περασμένη εβδομάδα από την προηγούμενη εβδομάδα.",
	"Library_FriendsActivity_BeingDiscussedHeading": "Συζητείται",
	"Library_FriendsActivity_BeingDiscussedHover": "Σας δείχνουμε αυτό το παιχνίδι επειδή οι φίλοι σας αναρτούν στιγμιότυπα ή μηνύματα κατάστασης.",
	"Library_FriendsActivity_RecentlyPurchasedHeading": "Πρόσφατα αγορασμένο",
	"Library_FriendsActivity_RecentlyPurchasedHover": "Σας δείχνουμε αυτό το παιχνίδι επειδή το αγοράσατε πρόσφατα και οι φίλοι σας το παίζουν.",
	"Library_FriendsActivity_UnownedHeading": "Δοκιμάστε κάτι νέο",
	"Library_FriendsActivity_UnownedHover": "Σας δείχνουμε αυτό το παιχνίδι επειδή είναι δημοφιλές μεταξύ των φίλων σας και δεν το κατέχετε.",
	"Library_FriendsActivity_PopularHeading": "Δημοφιλές",
	"Library_FriendsActivity_PopularHover": "Σας δείχνουμε αυτό το παιχνίδι επειδή ένας μεγάλος αριθμός των φίλων παίζουν αυτό το παιχνίδι τον τελευταίο καιρό.",
	"Library_FriendsActivity_DontForgetHeading": "Μη ξεχάσετε",
	"Library_FriendsActivity_DontForgetHover": "Σας δείχνουμε αυτό το παιχνίδι επειδή δεν το έχετε παίξει τελευταία, αλλά οι φίλοι σας το παίζουν.",
	"Library_FriendsActivity_NewToGroupHeading": "Νέο στους φίλους σας",
	"Library_FriendsActivity_NewToGroupHover": "Σας δείχνουμε αυτό το παιχνίδι επειδή οι φίλοι σας άρχισαν να το παίζουν πρόσφατα.",
	"Library_FriendsActivity_ReturnedToGroupHeading": "Ξανά δημοφιλές",
	"Library_FriendsActivity_ReturnedToGroupHover": "Σας δείχνουμε αυτό το παιχνίδι επειδή οι φίλοι σας άρχισαν να το παίζουν ξανά.",
	"Library_FriendsActivity_UnownedBanner": "Προβολή στο κατάστημα Steam",
	"Library_FriendsActivity_UnownedMenu_Store": "Κατάστημα",
	"Library_FriendsActivity_UnownedMenu_Hub": "Κέντρο κοινότητας",
	"Library_FriendsActivity_UnownedMenu_Reviews": "Κριτικές",
	"Library_FriendsActivity_UnownedMenu_Discussions": "Συζητήσεις",
	"Library_Recent_NoRecentGames_GamesOwned": "Έχετε %1$s παιχνίδια.",
	"Library_Recent_NoRecentGames_StoreLink": "Επισκεφτείτε το κατάστημα",
	"Library_Recent_NoRecentGames_SteamStore": "Κατάστημα Steam",
	"Library_Recent_NoRecentGames_FreeToPlay": "Δωρεάν παιχνίδια",
	"Library_Recent_NoRecentGames_GamesOnSale": "Παιχνίδια σε έκπτωση τώρα",
	"Library_Recent_NoRecentGames_NewReleases": "Νέες κυκλοφορίες",
	"Library_Recent_NoRecentGames_ActivateProduct": "Ενεργοποίηση προϊόντος",
	"Library_Recent_NoRecentGames_RedeemCode": "Εξαργύρωση κωδικού πορτοφολιού",
	"Library_SortCollectionBy": "Ταξινόμηση ανά",
	"Library_SortByFavoritesFirst": "Αγαπημένα πρώτα",
	"Library_SortByAlphabetical": "Αλφαβητικά",
	"Library_SortByPctAchievementsComplete": "% ολοκληρωμένα επιτεύγματα",
	"Library_SortByLastUpdated": "Τελευταία ενημέρωση",
	"Library_SortByHoursPlayed": "Παιγμένες ώρες",
	"Library_SortByLastPlayed": "Τελευταίο παιχνίδι",
	"Library_SortByReleaseDate": "Ημερομηνία κυκλοφορίας",
	"Library_SortByAddedToLibrary": "Ημ/νια προσθήκης σε συλλογή",
	"Library_SortBySizeOnDisk": "Μέγεθος στο δίσκο",
	"Library_SortByMetacriticScore": "Βαθμολογία Metacritic",
	"Library_SortByFriendsPlaying": "Φίλοι που το παίζουν",
	"Library_SortBySteamReview": "Κριτική Steam",
	"Library_SortByPctAchievementsComplete_Tag": "%1$s% Ολοκληρώθηκε",
	"Library_SortByPctAchievementsNoAchievements_Tag": "Χωρίς επιτεύγματα",
	"Library_InstalledOnlyCheck": "Εγκατεστημένα μόνο",
	"GridSection_Favorites": "Αγαπημένα",
	"GridSection_EverythingElse": "Όλα τα άλλα",
	"GridSection_Over100Hours": "Πάνω από 100 ώρες",
	"GridSection_Over60Hours": "Πάνω από 60 ώρες",
	"GridSection_Over40Hours": "Πάνω από 40 ώρες",
	"GridSection_Over20Hours": "Πάνω από 20 ώρες",
	"GridSection_Over10Hours": "Πάνω από 10 ώρες",
	"GridSection_Over1Hour": "Πάνω από 1 ώρα",
	"GridSection_LessThan1Hour": "Κάτω από 1 ώρα",
	"GridSection_Over90Metacritic": "Πάνω από 90",
	"GridSection_Over80Metacritic": "Πάνω από 80",
	"GridSection_Over70Metacritic": "Πάνω από 70",
	"GridSection_Over50Metacritic": "Πάνω από 50",
	"GridSection_EverythingElseMetacritic": "Όλα τα άλλα",
	"GridSection_UnknownReleaseDate": "Άγνωστο",
	"GridSection_GreaterThan100GB": "Περισσότερο από 100GB",
	"GridSection_GreaterThan50GB": "Περισσότερο από 50GB",
	"GridSection_GreaterThan20GB": "Περισσότερο από 20GB",
	"GridSection_LessThan20GB": "Λιγότερο από 20GB",
	"GridSection_NoSizeOnDisk": "Χωρίς μέγεθος",
	"GridSection_NotInstalled": "Μη εγκατεστημένα",
	"GridSection_MoreThan10YearsAgo": "πριν 10+ χρόνια",
	"GridSection_Never": "Ποτέ",
	"AppDetails_SectionTitle_Stream": "Μετάδοση δημιουργού",
	"AppDetails_SectionTitle_Activity": "Δραστηριότητα",
	"AppDetails_SectionTitle_Friends": "Φίλοι που παίζουν",
	"AppDetails_SectionTitle_Friends_Software": "Φίλοι που χρησιμοποιούν",
	"AppDetails_SectionTitle_Achievements": "Επιτεύγματα",
	"AppDetails_SectionTitle_TradingCards": "Κάρτες ανταλλαγών",
	"AppDetails_SectionTitle_Screenshots": "Στιγμιότυπα",
	"AppDetails_SectionTitle_AdditionalContent": "Επιπλέον περιεχόμενο",
	"AppDetails_SectionTitle_Updates": "Πρόσφατα συμβάντα και ενημερώσεις",
	"AppDetails_SectionTitle_DLC": "DLC",
	"AppDetails_SectionTitle_LastPlayed": "Τελευταίο παιχνίδι",
	"AppDetails_SectionTitle_LastLaunched": "Τελευταία εκκίνηση",
	"AppDetails_SectionTitle_PlayTime": "Ώρα παιχνιδιού",
	"AppDetails_SectionTitle_UsageTime": "Χρόνος χρήσης",
	"AppDetails_SectionTitle_Workshop": "Εργαστήρι Steam",
	"AppDetails_SectionTitle_Community": "Περιεχόμενο κοινότητας",
	"AppDetails_SectionTitle_Links": "Σύνδεσμοι",
	"AppDetails_SectionTitle_SignIn_Pre": "Συνδεθείτε",
	"AppDetails_SectionTitle_SignIn": "%1$s για να δείτε δραστηριότητα φίλων",
	"AppDetails_SectionTitle_OpenFriends": "Άνοιγμα λίστας φίλων",
	"AppDetails_SectionTitle_OfflineMode": "Λειτ. εκτός σύνδεσης",
	"AppDetails_Broadcast_ViewOnWeb": "Προβολή σε περιηγητή διαδικτύου",
	"AppDetails_Community_Tooltip1": "Αυτή η ενότητα περιέχει στιγμιότυπα, τέχνη, βίντεο, οδηγούς και άλλα, καταχωρημένα από την κοινότητα.",
	"AppDetails_Community_Tooltip2": "Μπορείτε να δηλώσετε ότι σας αρέσει, να σχολιάσετε ή να αναφέρετε αυτό το περιεχόμενο.",
	"AppDetails_Community_Guide": "Οδηγός κοινότητας",
	"AppDetails_Links_Store": "Σελίδα καταστήματος",
	"AppDetails_Links_Community": "Κέντρο κοινότητας",
	"Bbcode_Originally_Posted_By": "Αναρτήθηκε αρχικά από",
	"AppDetails_InOfflineMode": "Το Steam είναι αυτή τη στιγμή σε λειτουργία εκτός σύνδεσης. Σε λειτουργία εκτός σύνδεσης, πολλά χαρακτηριστικά της συλλογής Steam σας, όπως η δραστηριότητα και οι φίλοι, δε θα είναι διαθέσιμα. Συνδεθείτε διαδικτυακά για να δείτε αυτό το περιεχόμενο.",
	"AppDetails_GoOnline": "Συνδεθείτε",
	"AppDetails_PartnerEventFailedLoad": "Αποτυχία φόρτωσης αυτού του συμβάντος",
	"GameAction_Stop": "Διακοπή",
	"GameAction_Cancel": "Άκυρο",
	"GameAction_Install": "Εγκατάσταση",
	"GameAction_Uninstall": "Απεγκατάσταση",
	"GameAction_Play": "Εκκίνηση",
	"GameAction_PlayMusic": "Αναπαραγωγή άλμπουμ",
	"GameAction_Launch": "Εκκίνηση",
	"GameAction_PreLoad": "Προφόρτωση",
	"GameAction_Update": "Ενημέρωση",
	"GameAction_Download": "Λήψη",
	"GameAction_Resume": "Επαναφορά",
	"GameAction_Pause": "Παύση",
	"GameAction_BorrowApp": "Δάνεισμα",
	"GameAction_PurchaseApp": "Αγορά",
	"GameAction_GameProperties": "Ιδιότητες...",
	"GameAction_AddToFavorites": "Προσθήκη στα αγαπημένα",
	"GameAction_RemoveFromFavorites": "Αφαίρεση από τα αγαπημένα",
	"GameAction_AddToHidden": "Απόκρυψη παιχνιδιού",
	"GameAction_RemoveFromHidden": "Αφαίρεση από τα κρυμμένα",
	"GameAction_RemoveGameLicense": "Αφαίρεση από λογαριασμό",
	"GameAction_AddToFamilyGames": "Προσθήκη σε οικογενειακά παιχνίδια",
	"GameAction_RemoveFromFamilyGames": "Αφαίρεση από οικογενειακά παιχνίδια",
	"GameAction_RemoveShortcut": "Αφαίρεση παιχνιδιού εκτός Steam από τη συλλογή σας",
	"GameAction_AddToCollection": "Προσθήκη σε",
	"GameAction_RemoveFromCollection": "Αφαίρεση από",
	"GameAction_CreateDesktopShortcut": "Προσθήκη συντόμευσης επ. εργασίας",
	"GameAction_BackUpFiles": "Αντίγραφο ασφαλείας αρχείων παιχνιδιού...",
	"GameAction_Stream": "Μετάδοση",
	"GameAction_Connect": "Σύνδεση",
	"GameAction_SetCustomArtwork": "Ορισμός προσαρμ. τέχνης",
	"GameAction_ClearCustomArtwork": "Εκκαθάριση προσαρμ. τέχνης",
	"GameAction_ViewCDKeys": "Κλειδιά CD",
	"GameAction_ControllerConfiguration": "Διαμόρφωση χειριστηρίου",
	"GameAction_Launching": "Εκκίνηση",
	"GameAction_RemoveAppFromCollection": "ΣΥΡΕΤΕ ΕΔΩ για αφαίρεση %1$s από τη συλλογή %2$s",
	"GameAction_RemoveAppFromMultipleCollections": "ΣΥΡΕΤΕ ΕΔΩ για αφαίρεση του %1$s από αυτές τις συλλογές",
	"GameAction_RemoveMultipleAppsFromCollection": "ΣΥΡΕΤΕ ΕΔΩ για αφαίρεση αυτών των εφαρμογών από %1$s",
	"GameAction_RemoveMultipleAppsFromMultipleCollections": "ΣΥΡΕΤΕ ΕΔΩ για αφαίρεση αυτών των εφαρμογών από αυτές τις συλλογές",
	"GameAction_NavigateToAllCollectionsWithDrag": "ΣΥΡΕΤΕ και ΚΡΑΤΗΣΤΕ ΕΔΩ για προβολή όλων των συλλογών",
	"GameAction_AddToCollectionOption_NewCollection": "Νέα συλλογή...",
	"GameAction_NewCollectionDialogTitle": "Νέα συλλογή",
	"GameAction_Manage": "Διαχείριση",
	"GameAction_Favorite": "Προσθήκη στα αγαπημένα",
	"GameAction_UnFavorite": "Είναι στα αγαπημένα",
	"GameAction_ViewDetails": "Εμφάνιση περισσότερων λεπτομερειών",
	"GameAction_BrowseLocalFiles": "Περιήγηση τοπικών αρχείων",
	"GameAction_ViewDetails_Collapse": "Εμφάνιση λιγότερων λεπτομερειών",
	"GameAction_ViewDetails_ScrollUp": "Κύλιση στην κορυφή",
	"GameActionPlural_Install": "Εγκατάσταση επιλεγμένων",
	"GameActionPlural_Uninstall": "Απεγκατάσταση επιλεγμένων",
	"GameActionPlural_PreLoad": "Προφόρτωση επιλεγμένων",
	"GameActionPlural_Update": "Ενημέρωση επιλεγμένων",
	"GameActionPlural_Download": "Λήψη επιλεγμένων",
	"GameActionPlural_Resume": "Επαναφορά επιλεγμένων",
	"GameActionPlural_AddToFavorites": "Προσθήκη επιλεγμένων στα αγαπημένα",
	"GameActionPlural_RemoveFromFavorites": "Αφαίρεση επιλεγμένων από αγαπημένα",
	"GameActionPlural_AddToHidden": "Απόκρυψη επιλεγμένων παιχνιδιών",
	"GameActionPlural_RemoveFromHidden": "Αφαίρεση επιλεγμένων από κρυφά",
	"GameActionPlural_AddToFamilyGames": "Προσθήκη επιλεγμένων σε οικογενειακά παιχνίδια",
	"GameActionPlural_RemoveFromFamilyGames": "Αφαίρεση επιλεγμένων από οικογενειακά παιχνίδια",
	"GameActionPlural_RemoveShortcut": "Αφαίρεση επιλεγμένων παιχνιδιών εκτός Steam από τη συλλογή σας",
	"GameActionPlural_AddToCollection": "Προσθήκη επιλεγμένων σε",
	"GameActionPlural_RemoveFromCollection": "Αφαίρεση επιλεγμένων από",
	"GameActionPlural_CreateDesktopShortcut": "Προσθήκη συντομεύσεων επ. εργασίας",
	"GameActionPlural_BackUpFiles": "Αντίγραφο ασφαλείας αρχείων παιχνιδιών...",
	"PrePurchase_Preload_Title": "Το %1$s είναι τώρα έτοιμο για προφόρτωση",
	"PrePurchase_Preload_Desc": "Κατεβάστε τα αρχεία παιχνιδιού τώρα ώστε να μπορείτε να παίξετε αμέσως μόλις ξεκλειδωθεί!",
	"PrePurchase_PreloadComplete_Title": "Το %1$s προφορτώθηκε",
	"PrePurchase_PreloadComplete_Desc": "Μόλις το παιχνίδι ξεκλειδωθεί, θα μπορείτε να ξεκινήσετε να παίζετε!",
	"PrePurchase_Install_Title": "Το %1$s είναι τώρα διαθέσιμο για εγκατάσταση και παιχνίδι",
	"PrePurchase_Install_Desc": "Εγκαταστήστε τώρα για να ξεκινήσετε να παίζετε!",
	"PrePurchase_PlayNow_Title": "Το %1$s είναι τώρα διαθέσιμο για παιχνίδι",
	"PrePurchase_PlayNow_Desc": "Ξεκινήστε να παίζετε τώρα!",
	"DisplayStatus_Launching": "Εκκίνηση...",
	"DisplayStatus_Uninstalling": "Απεγκατάσταση...",
	"DisplayStatus_Installing": "Εγκατάσταση...",
	"DisplayStatus_Running": "Εκτέλεση...",
	"DisplayStatus_Validating": "Επαλήθευση...",
	"DisplayStatus_Updating": "Ενημέρωση...",
	"DisplayStatus_Downloading": "Λήψη...",
	"DisplayStatus_Synchronizing": "Συγχρονισμός με Steam Cloud...",
	"DisplayStatus_ReadyToInstall": "Έτοιμο για εγκατάσταση",
	"DisplayStatus_ReadyToPreload": "Έτοιμα για προφόρτωση",
	"DisplayStatus_ReadyToLaunch": "Έτοιμο για εκκίνηση",
	"DisplayStatus_RegionRestricted": "Μη διαθέσιμο σε τρέχουσα περιοχή",
	"DisplayStatus_PresaleOnly": "Αυτό το αντικείμενο δεν είναι ακόμα διαθέσιμο",
	"DisplayStatus_InvalidPlatform": "Διαθέσιμο για",
	"DisplayStatus_PreloadComplete": "Η προφόρτωση ολοκληρώθηκε",
	"DisplayStatus_BorrowerLocked": "Αυτή η συλλογή δεν είναι αυτή τη στιγμή διαθέσιμη για κοινή χρήση",
	"DisplayStatus_UpdatePaused": "Ενημέρωση σε παύση",
	"DisplayStatus_UpdateQueued": "Ενημέρωση σε σειρά",
	"DisplayStatus_UpdateRequired": "Απαιτείται ενημέρωση",
	"DisplayStatus_UpdateDisabled": "Οι ενημερώσεις απενεργοποιήθηκαν επειδή το Steam είναι σε λειτουργία εκτός σύνδεσης. Συνδεθείτε διαδικτυακά για να ολοκληρώσετε την ενημέρωση αυτού του παιχνιδιού.",
	"DisplayStatus_DownloadPaused": "Λήψη σε παύση",
	"DisplayStatus_DownloadQueued": "Λήψη σε σειρά",
	"DisplayStatus_DownloadRequired": "Απαιτείται λήψη",
	"DisplayStatus_DownloadDisabled": "Οι λήψεις απενεργοποιήθηκαν επειδή το Steam είναι σε λειτουργία εκτός σύνδεσης. Συνδεθείτε διαδικτυακά για να ολοκληρώσετε τη λήψη αυτού του παιχνιδιού.",
	"DisplayStatus_LicensePending": "Η αγορά σας δεν έχει ολοκληρωθεί ακόμα.",
	"DisplayStatus_LicenseExpired": "Η άδεια έληξε",
	"DisplayStatus_AvailForFree": "Διαθέσιμο δωρεάν",
	"DisplayStatus_AvailToBorrow": "Διαθέσιμο για δάνεισμα",
	"DisplayStatus_AvailGuestPass": "Διαθέσιμο πάσο επισκέπτη",
	"DisplayStatus_Purchase": "Διαθέσιμο για αγορά",
	"DisplayStatus_Preallocating": "Δέσμευση χώρου",
	"DisplayStatus_Committing": "Δέσμευση",
	"DisplayStatus_Verifying": "Επαλήθευση",
	"DisplayStatus_Unpacking": "Ξεπακετάρισμα",
	"DisplayStatus_Compact_Launching": "Εκκίνηση...",
	"DisplayStatus_Compact_Uninstalling": "Απεγκατάσταση...",
	"DisplayStatus_Compact_Installing": "Εγκατάσταση...",
	"DisplayStatus_Compact_Running": "Εκτέλεση...",
	"DisplayStatus_Compact_Validating": "Επαλήθευση...",
	"DisplayStatus_Compact_Updating": "Ενημέρωση...",
	"DisplayStatus_Compact_Downloading": "Λήψη...",
	"DisplayStatus_Compact_Synchronizing": "Συγχρονισμός με Steam Cloud...",
	"DisplayStatus_Compact_ReadyToInstall": "Έτοιμο για εγκατάσταση",
	"DisplayStatus_Compact_ReadyToPreload": "Έτοιμα για προφόρτωση",
	"DisplayStatus_Compact_ReadyToLaunch": "Έτοιμο για εκκίνηση",
	"DisplayStatus_Compact_RegionRestricted": "Μη διαθέσιμο σε αυτή την περιοχή",
	"DisplayStatus_Compact_PresaleOnly": "Το παιχνίδι δεν έχει κυκλοφορήσει ακόμα",
	"DisplayStatus_Compact_InvalidPlatform": "Διαθέσιμο για",
	"DisplayStatus_Compact_ParentalBlocked": "Εμποδίζεται από οικογενειακή προβολή Steam",
	"DisplayStatus_Compact_PreloadComplete": "Η προφόρτωση ολοκληρώθηκε",
	"DisplayStatus_Compact_BorrowerLocked": "Η κοινή χρήση δεν είναι διαθέσιμη",
	"DisplayStatus_Compact_UpdatePaused": "Ενημέρωση σε παύση",
	"DisplayStatus_Compact_UpdateQueued": "Ενημέρωση σε σειρά",
	"DisplayStatus_Compact_UpdateRequired": "Απαιτείται ενημέρωση",
	"DisplayStatus_Compact_UpdateDisabled": "Η ενημέρωση είναι απενεργοποιημένη σε λειτουργία εκτός σύνδεσης.",
	"DisplayStatus_Compact_DownloadPaused": "Λήψη σε παύση",
	"DisplayStatus_Compact_DownloadQueued": "Λήψη σε σειρά",
	"DisplayStatus_Compact_DownloadRequired": "Απαιτείται λήψη",
	"DisplayStatus_Compact_DownloadDisabled": "Η λήψη είναι απενεργοποιημένη σε λειτουργία εκτός σύνδεσης.",
	"DisplayStatus_Compact_LicensePending": "Ολοκλήρωση αγοράς...",
	"DisplayStatus_Compact_LicenseExpired": "Η άδεια έληξε",
	"DisplayStatus_Compact_AvailForFree": "Διαθέσιμο δωρεάν",
	"DisplayStatus_Compact_AvailToBorrow": "Διαθέσιμο για δάνεισμα",
	"DisplayStatus_Compact_AvailGuestPass": "Διαθέσιμο πάσο επισκέπτη",
	"DisplayStatus_Compact_Purchase": "Διαθέσιμο για αγορά",
	"DisplayStatus_ReleaseDate": "Προσεχώς %1$s",
	"DisplayStatus_CustomReleaseDate": "Προγρ. ημ/νια κυκλοφορίας: %1$s",
	"Downloads_State_Bytes_Of_Bytes": "%1$s από %2$s",
	"Downloads_State_None": "",
	"Downloads_State_Reconfiguring": "Έναρξη λήψης...",
	"Downloads_State_Validating": "Επαλήθευση αρχείων...",
	"Downloads_State_AddingFiles": "Αντιγραφή αρχείων...",
	"Downloads_State_Preallocating": "Δέσμευση χώρου...",
	"Downloads_State_Downloading": "",
	"Downloads_State_Staging": "",
	"Downloads_State_Committing": "Ολοκλήρωση...",
	"Downloads_State_Verifying": "Επαλήθευση λήψης...",
	"Downloads_State_Stopping": "Διακοπή λήψης...",
	"Downloads_State_Running": "",
	"Downloads_State_SecondsRemaining": "απομένουν %1$s δευτ.",
	"Downloads_State_MinutesRemaining": "απομένουν %1$s λεπτά",
	"Downloads_State_Calculating": "Υπολογισμός...",
	"LaunchApp_Action_UpdatingAppInfo": "Έλεγχος διαμόρφωσης...",
	"LaunchApp_Action_ShowEula": "Εμφάνιση EULA",
	"LaunchApp_Action_DownloadingDepots": "Λήψη περιεχομένου (%1$s%)",
	"LaunchApp_Action_DownloadingWorkshop": "Λήψη εργαστηρίου (%1$s%)",
	"LaunchApp_Action_UpdatingDRM": "Ενημέρωση εκτελέσιμου",
	"LaunchApp_Action_GettingLegacyKey": "Ενημέρωση κλειδιού προϊόντος",
	"LaunchApp_Action_RunningInstallScript": "Εκτέλεση σκριπτ εγκατάστασης (%1$s)",
	"LaunchApp_Action_SynchronizingCloud": "Συγχρονισμός με cloud...",
	"LaunchApp_Action_VerifyingFiles": "Επαλήθευση εκτελέσιμου",
	"LaunchApp_Action_CreatingProcess": "Εκκίνηση εκτελέσιμου",
	"LaunchApp_Action_WaitingGameWindow": "Εκκίνηση εκτελέσιμου",
	"LaunchApp_Action_DelayLaunch": "Καθυστέρηση εκκίνησης (%1$s%)",
	"AppDetails_TitleUpdatedSincePlayed": "Αυτό το παιχνίδι έχει ενημερωθεί από την τελευταία φορά που παίξατε",
	"AppDetails_TitleUpdatedSincePlayedLink": "Διαβάστε τις αλλαγές",
	"AppDetails_BadgeLevel": "Επίπεδο %1$s, Εμπειρία: %2$s",
	"AppDetails_UnearnedBadgeXP": "%1$s εμπειρία",
	"AppDetails_BadgeLevelNoXP": "Επίπεδο %1$s",
	"AppDetails_Review_ViewOrEdit": "Επεξεργασία της κριτικής μου",
	"AppDetails_Review_YourReview": "Η κριτική μου",
	"AppDetails_Review_Ignore_Stale_Reviews": "Να μην υπενθυμίζομαι για ενημέρωση αυτής της κριτικής.",
	"AppDetails_Review_Unignore_Stale_Reviews": "Να επιτρέπονται παλιές κριτικές για αυτό το παιχνίδι.",
	"AppDetails_Review_RecommendGame": "Θα προτείνατε αυτό το παιχνίδι;",
	"AppDetails_Review_RecommendSoftware": "Θα προτείνατε αυτό το λογισμικό;",
	"AppDetails_Review_WriteReview": "Γράψτε μια κριτική για το %1$s",
	"AppDetails_Review_PlayedForTime": "Έχετε παίξει για %1$s",
	"AppDetails_Review_PlayedForTime_Software": "Έχετε χρησιμοποιήσει αυτόν τον τίτλο για %1$s",
	"AppDetails_Review_RecommendGameButton_Yes": "Ναι",
	"AppDetails_Review_RecommendGameButton_No": "Όχι",
	"AppDetails_Review_PlaytimeAtReview": "%1$s παιχνιδιού τη στιγμή κριτικής",
	"AppDetails_Review_PlaytimeAtReview_Software": "%1$s χρήσης τη στιγμή κριτικής",
	"AppDetails_Review_NotRecommended": "Δεν προτείνεται",
	"AppDetails_Review_Recommended": "Προτείνεται",
	"AppDetails_Review_AdditionalPlaytime": "Έχετε παίξει %1$s από τότε που γράψατε αυτή την κριτική.",
	"AppDetails_Review_AdditionalPlaytime_Software": "Έχετε χρησιμοποιήσει αυτό για %1$s από τότε που γράψατε αυτή την κριτική.",
	"AppDetails_Review_ChangedYourMind": "Αλλάξετε άποψη;",
	"AppDetails_Review_IHaveNotChangedMyMind": "Όχι δεν άλλαξα",
	"AppDetails_Review_UpVotes": "«Μου αρέσει»:",
	"AppDetails_Review_Comments": "Σχόλια:",
	"AppDetails_Review_ViewAll": "Προβολή όλων των κριτικών μου",
	"AppDetails_Review_ViewAllByFriend": "Προβολή όλων των κριτικών από %1$s",
	"OverflowBox_Action_Collapse": "Εμφάνιση λιγότερων",
	"OverflowBox_Action_Expand": "Διαβάστε περισσότερα",
	"OverflowBox_More": "(%1$s ακόμα)",
	"AppDetails_FriendsInGameNow": "%1$s φίλος παίζει τώρα",
	"AppDetails_FriendsInGameNow_Plural": "%1$s φίλοι παίζουν τώρα",
	"AppDetails_FriendsPlayedRecently": "%1$s φίλος έχει παίξει πρόσφατα",
	"AppDetails_FriendsPlayedRecently_Plural": "%1$s φίλοι έχουν παίξει πρόσφατα",
	"AppDetails_FriendsPlayedRecentlyExpand": "Εμφάνιση όλων των πρόσφατα παιγμένων",
	"AppDetails_FriendsPlayed": "%1$s φίλος έχει παίξει προηγουμένως",
	"AppDetails_FriendsPlayed_Plural": "%1$s φίλοι έχουν παίξει προηγουμένως",
	"AppDetails_FriendsPlayedExpand": "Εμφάνιση όλων των προηγουμένως παιγμένων",
	"AppDetails_FriendsMore": "(%1$s ακόμα)",
	"AppDetails_FriendsLess": "Εμφάνιση λιγότερων",
	"AppDetails_FriendsWishlisted": "%1$s φίλος έχει το %2$s στη λίστα επιθυμιών του",
	"AppDetails_FriendsWishlisted_Plural": "%1$s φίλοι έχουν το %2$s στη λίστα επιθυμιών τους",
	"AppDetails_FriendsWishlistExpand": "Εμφάνιση όλων σε λίστα επιθυμιών",
	"AppDetails_Friends_ViewAll": "Προβολή όλων των φίλων που παίζουν",
	"AppDetails_GameInfo": "Πληροφορίες",
	"AppDetails_Publisher": "Εκδότης:",
	"AppDetails_Developer": "Δημιουργός:",
	"AppDetails_Franchise": "Franchise:",
	"AppDetails_ReleaseDate": "Ημ/νια κυκλοφορίας:",
	"AppDetails_LastUpdate": "Τελευταία τοπική ενημέρωση:",
	"AppDetails_OriginalReleaseDate": "Αρχική ημ/νια κυκλοφορίας:",
	"AppDetails_Feature_SinglePlayer": "Ενός παίκτη",
	"AppDetails_Feature_MultiPlayer": "Πολλών παικτών",
	"AppDetails_Feature_CoOp": "Συνεργατικό παιχνίδι",
	"AppDetails_Feature_SteamAchievements": "ΕΠΙΤΕΥΓΜΑΤΑ",
	"AppDetails_Feature_SteamCloud": "Αποθηκεύσεις Cloud",
	"AppDetails_Feature_FullController": "Πλήρης υποστήριξη χειριστηρίου",
	"AppDetails_Feature_PartialController": "Μερική υποστήριξη χειριστηρίου",
	"AppDetails_Feature_SteamWorkshop": "Εργαστήρι Steam",
	"AppDetails_Feature_VRSupport": "Υποστήριξη VR",
	"AppDetails_ViewAllUpdates": "Προβολή όλων των ενημερώσεων",
	"AppDetails_ViewAllAchievements": "Προβολή των επιτευγμάτων μου",
	"AppDetails_ViewGlobalAchievements": "Προβολή παγκόσμιων στατιστικών επιτευγμάτων",
	"AppDetails_PlayerUnlockedPercent": "Έχετε ξεκλειδώσει %1$s/%2$s",
	"AppDetails_PlayerUnlockedPercentAll": "Έχετε ξεκλειδώσει όλα τα επιτεύγματα! %1$s/%2$s",
	"AppDetails_Achievements_Unlocked": "Ξεκλειδώθηκε στις %1$s",
	"AppDetails_PctUnlocked": "%1$s% των παικτών έχουν αυτό το επίτευγμα",
	"AppDetails_GlobalCompare": "Αυτό είναι περισσότερο από το %1$s% των παικτών",
	"AppDetails_ViewTradingCards": "Προβολή των καρτών ανταλλαγών μου",
	"AppDetails_Achievements_Locked": "Κλειδωμένα επιτεύγματα",
	"AppDetails_TradingCardsLeft": "απομένει να συλλεχθεί 1 κάρτα ανταλλαγών",
	"AppDetails_TradingCardsLeft_Plural": "απομένουν να συλλεχθούν %1$s κάρτες ανταλλαγών",
	"AppDetails_TradingCardsLevelUp": "Έχετε αρκετές κάρτες ανταλλαγών για αναβάθμιση!",
	"AppDetails_TradingCardsMaxed": "Συγχαρητήρια! Το έμβλημα είναι στο μέγιστο επίπεδο!",
	"AppDetails_TradingCards_Tooltip1": "Οι κάρτες ανταλλαγών πέφτουν καθώς παίζετε. Μπορείτε να ανταλλάξετε με φίλους (ή με την Αγορά κοινότητας Steam) τις κάρτες που δεν έπεσαν για εσάς.",
	"AppDetails_TradingCards_Tooltip2": "Συμπληρώστε ένα πλήρες σετ καρτών ανταλλαγών και κατασκευάστε τις σε Εμβλήματα. Τα εμβλήματα αυξάνουν το επίπεδο Steam σας και ξεκλειδώνουν προνόμια στο προφίλ και στο λογαριασμό σας.",
	"AppDetails_BrowseWorkshop": "Περιήγηση εργαστηρίου",
	"AppDetails_ViewSubscribedItems": "Προβολή των συνδρομών μου",
	"AppDetails_ViewItemInWorkshop": "Προβολή στο εργαστήρι",
	"AppDetails_MoreItemsFrom": "Περισσότερα από αυτόν τον δημιουργό",
	"AppDetails_SubscribeToItem": "Συνδρομή",
	"AppDetails_UnsubscribeFromItem": "Κατάργηση",
	"AppDetails_Subscribed": "Εγγραφήκατε",
	"AppDetails_ViewMoreInWorkshop": "Προβολή περισσότερων στο εργαστήρι",
	"AppDetails_WorkshopSubCount": "Έχετε %1$s συνδρομές εργαστηρίου.",
	"AppDetails_WorkshopVisit": "Επίσκεψη σε αυτό το εργαστήρι",
	"AppDetails_WorkshopLearnMore": "Μάθετε περισσότερα",
	"AppDetails_WorkshopFeaturedHeader": "Ανοδικό αντικείμενο",
	"AppDetails_WorkshopFeaturedItem": "Δημοφιλές αντικείμενο",
	"AppDetails_WorkshopFeaturedMoreInfo": "Διαβάστε περισσότερα",
	"AppDetails_WorkshopFeaturedHideItem": "Απόκρυψη αντικειμένου",
	"AppDetails_WorkshopFileSize": "Μέγεθος αρχείου: %1$s",
	"AppDetails_WorkshopFileSizeBytes": "%1$s byte",
	"AppDetails_WorkshopFileSizeKb": "%1$s KB",
	"AppDetails_WorkshopFileSizeMb": "%1$s MB",
	"AppDetails_WorkshopFileSizeGb": "%1$s GB",
	"AppDetails_WorkshopLastUpdated": "Τελευταία ενημέρωση: %1$s",
	"DLCStatus_installed": "Εγκατεστημένο",
	"DLCStatus_notinstalled": "Μη εγκατεστημένο",
	"DLCStatus_downloading": "Λήψη...",
	"DLC_DateAdded": "Προστέθηκε: %1$s",
	"AppDetails_ManageDLC": "Διαχείριση των %1$s DLC μου",
	"AppDetails_ManageMyDLC": "Διαχείριση του DLC μου",
	"AppDetails_ViewStoreDLC": "Προβολή DLC στο κατάστημα",
	"AppDetails_DLCSpotlight": "Προστέθηκε νεοαποκτούμενο DLC και θα εγκατασταθεί μαζί με το παιχνίδι. Διαχειριστείτε τα DLC σας %1$s.",
	"AppDetails_DLCSpotlight_Installed": "Προστέθηκε νεοαποκτούμενο DLC και εγκαταστάθηκε αυτόματα. Διαχειριστείτε τα DLC σας %1$s.",
	"AppDetails_DLCSpotlight_here": "εδώ",
	"ManageDLC_Title": "Διαχείριση DLC",
	"ManageDLC_Column_Name": "Όνομα",
	"ManageDLC_Column_DateAdded": "Ημερομηνία προσθήκης",
	"ManageDLC_Column_Enabled": "Ενεργό",
	"ManageDLC_Column_Installed": "Εγκατεστημένο",
	"ManageDLC_Search": "Αναζήτηση...",
	"ManageDLC_Installed": "%1$s/%2$s εγκατεστημένα",
	"ManageDLC_ViewMore": "Προβολή περισσότερων στο κατάστημα",
	"ManageDLC_NoResults": "Κανένα αποτέλεσμα δεν ταιριάζει το «%1$s»",
	"AppDetails_ViewBadgePage": "Προβολή σελίδας εμβλήματος",
	"AppDetails_VisitTradeForum": "Επίσκεψη φόρουμ ανταλλαγών",
	"AppDetails_BuyCards": "Αγορά εναπομεινάντων καρτών στην Αγορά",
	"AppDetails_SellCards": "Πώληση αυτών των καρτών στην Αγορά",
	"AppDetails_SearchCard": "Εμφάνιση αυτής της κάρτας στην Αγορά",
	"AppDetails_ShowFriendsList": "Εμφάνιση λίστας φίλων",
	"AppDetails_ViewFriendsWhoPlay": "Εμφάνιση φίλων που παίζουν",
	"AppDetails_Link_Discussions": "Συζητήσεις",
	"AppDetails_Link_FindGroups": "Εύρεση ομάδων",
	"AppDetails_Link_GameHub": "Κέντρο κοινότητας",
	"AppDetails_Link_Guides": "Οδηγοί",
	"AppDetails_Link_Store": "Σελίδα καταστήματος",
	"AppDetails_Link_Support": "Υποστήριξη",
	"AppDetails_Link_Workshop": "Εργαστήρι",
	"AppDetails_Link_Market": "Αγορά",
	"AppDetails_Link_Controller": "Διαμόρφωση χειριστηρίου",
	"AppDetails_SocialMediaLink": "%1$s σε %2$s",
	"AppDetails_SocialMediaType_4": "Twitter",
	"AppDetails_SocialMediaType_5": "Twitch",
	"AppDetails_SocialMediaType_6": "YouTube",
	"AppDetails_SocialMediaType_7": "Facebook",
	"AppDetails_Screenshot": "Στιγμιότυπο",
	"AppDetails_Screenshot_Caption": "Λεζάντα: %1$s",
	"AppDetails_Screenshot_Date": "Ημερομηνία: %1$s",
	"AppDetails_Screenshot_Dimensions": "Διαστάσεις: %1$s x %2$s pixel",
	"AppDetails_Screenshot_Uploaded": "Ανέβασμα: %1$s στις %2$s",
	"AppDetails_OpenScreenshotUploader": "Άνοιγμα μεταφορτωτή στιγμιοτύπων",
	"AppDetails_ViewUploadedScreenshots": "Προβολή ανεβασμένων στιγμιοτύπων",
	"AppDetails_ManageMyScreenshot": "Διαχείριση του στιγμιότυπού μου",
	"AppDetails_ManageMyScreenshot_Plural": "Διαχείριση των %1$s στιγμιοτύπων μου",
	"AppDetails_HowToScreenshot": "Μπορείτε να τραβήξετε ένα στιγμιότυπο πατώντας %1$s εντός παιχνιδιού.",
	"AppDetails_ChangeMyScreenshotKey": "Αλλαγή του πλήκτρου στιγμιοτύπων μου",
	"AppDetails_NoScreenshots": "Δεν έχετε λάβει κανένα στιγμιότυπο ακόμα",
	"AppDetails_Screenshot_SpoilerAlert": "Πιθανά σπόιλερ. Καταδείξτε για αποκάλυψη εικόνας.",
	"AppDetails_Artwork": "Τέχνη",
	"AppDetails_Video": "Βίντεο",
	"AppDetails_CommunityItem": "Περιεχόμενο κοινότητας",
	"AppDetails_CommunityFeed_OutOfContent": "Χωρίς επιπλέον περιεχόμενο",
	"AppDetails_CommunityFeed_Inappropriate": "Το περιεχόμενο μπορεί να μην είναι κατάλληλο για κάθε κοινό",
	"AppDetails_CommunityFeed_ViewContent": "Προβολή περιεχομένου",
	"AppDetails_CommunityFeed_EditPreferences": "Επεξεργασία προτιμήσεων",
	"AppDetails_CommunityFeed_LoadCommunity": "Φόρτωση περιεχομένου κοινότητας",
	"AppBox_NewToLibrary": "Νέο σε συλλογή",
	"AppBox_ComingSoon": "Προσεχώς",
	"AppBox_NewToLibrary_Short": "Νέο",
	"AppBox_ComingSoon_Short": "Σύντομα",
	"AppBox_PlayTimeHeader": "Ώρα παιχνιδιού",
	"AppBox_RecentPlayTime_Hours": "Τελευταίες δύο εβδομάδες: %1$s ώρες",
	"AppBox_RecentPlayTime_Minutes": "Τελευταίες δύο εβδομάδες: %1$s λεπτά",
	"AppBox_TotalPlayTime_Hours": "Συνολικά: %1$s ώρες",
	"AppBox_TotalPlayTime_Minutes": "Συνολικά: %1$s λεπτά",
	"AppActivity_Achieved": " κατόρθωσε",
	"AppActivity_PostedScreenshot": " μοιράστηκε ένα στιγμιότυπο",
	"AppActivity_PostedScreenshot_Plural": " μοιράστηκε %1$s στιγμιότυπα",
	"AppActivity_PostedVideo": " μοιράστηκε ένα βίντεο",
	"AppActivity_PostedVideo_Plural": " μοιράστηκε %1$s βίντεο",
	"AppActivity_ReceivedNewGame": " τώρα κατέχει %1$s",
	"AppActivity_PlayedGameFirstTime": " έπαιξε %1$s για πρώτη φορά",
	"AppActivity_LaunchedSoftwareFirstTime": " εκκινήθηκε %1$s για πρώτη φορά",
	"AppActivity_AddedGameToWishlist": " πρόσθεσε το %1$s στη %2$s του",
	"AppActivity_Wishlist": "λίστα επιθυμιών",
	"AppActivity_Achieved_PlusMore": "…και %1$s περισσότερα επιτεύγματα",
	"AppActivity_Achieved_PlusMore_Label": "Προβολή όλων των επιτευγμάτων του %1$s",
	"AppActivity_NoActivity": "Δεν υπάρχει πρόσφατη δραστηριότητα από τους δημιουργούς αυτού του τίτλου ούτε από τους φίλους σας.",
	"AppActivity_UserStatus_Time": " ανάρτησε μια ενημέρωση κατάστασης στις %1$s",
	"AppActivity_UserStatus": " ανάρτησε μια ενημέρωση κατάστασης",
	"AppActivity_StatusUpdate": "Αναρτήστε μια κατάσταση στους φίλους σας",
	"AppActivity_StatusUpdate_Post": "Πείτε κάτι για αυτό το παιχνίδι στους φίλους σας...",
	"AppActivity_StatusUpdate_Software_Post": "Πείτε κάτι για αυτό το λογισμικό στους φίλους σας...",
	"AppActivity_Comment_Reply": "Προσθέστε μια απάντηση...",
	"AppActivity_PostStatusUpdate": "Ανάρτηση",
	"AppActivity_FetchMore": "Φόρτωση περισσότερης δραστηριότητας",
	"AppActivity_EndofFeed": "Τέλος δραστηριότητας",
	"AppActivity_DeleteUserNews": "Πατήστε για διαγραφή αυτής της ανάρτησης.",
	"AppActivity_ConfirmDeleteTitle": "Διαγραφή ανάρτησης κατάστασης",
	"AppActivity_ConfirmDeleteTitle_Desc": "Θέλετε σίγουρα να διαγράψετε αυτή την ανάρτηση; Αυτό δεν μπορεί να αναιρεθεί.",
	"AppActivity_RecommendedGame": " έγραψε κριτική για αυτό το παιχνίδι",
	"AppActivity_RecommendedGame_ReadMore": "Διαβάστε περισσότερα",
	"AppActivity_RatingDetails": "%1$s το βαθμολόγησαν θετικά",
	"AppActivity_RatingDetails_1Other": "1 άτομο το βαθμολόγησε θετικά, %1$s",
	"AppActivity_RatingDetails_2Others": "%1$s άτομα το βαθμολόγησαν θετικά, συμπεριλαμβανομένων %2$s και %3$s",
	"AppActivity_RatingDetails_User": "Το βαθμολογήσατε θετικά",
	"AppActivity_RatingDetails_User_1Other": "%1$s άτομα το βαθμολόγησαν θετικά, συμπεριλαμβανομένων εσάς και %2$s",
	"AppActivity_RatingDetails_User_2Others": "%1$s άτομα το βαθμολόγησαν θετικά, συμπεριλαμβανομένων εσάς, %2$s και %3$s",
	"AppActivity_RatingDetails_PublishedFile": "%1$s «μου αρέσει»",
	"AppActivity_RateUp": "Μου αρέσει",
	"AppActivity_ConfirmDeleteCommentTitle": "Διαγραφή σχόλιου",
	"AppActivity_ConfirmDeleteCommentTitle_Desc": "Θέλετε σίγουρα να διαγράψετε αυτό το σχόλιο; Αυτό δεν μπορεί να αναιρεθεί.",
	"AppActivity_MakeCommentsVisible": "Προβολή προηγούμενων σχολίων (%1$s)",
	"AppActivity_Settings": "Ρυθμίσεις",
	"AppActivity_ViewComments": "Προβολή σχολίων",
	"AppActivity_AddComments": "Προσθήκη σχόλιου",
	"AppActivity_ContributeComments": "Σχολιάστε σε αυτό",
	"AppActivity_SteamTradingCards_EarnedTradingCards": " κέρδισε κάρτες ανταλλαγών",
	"AppActivity_SteamTradingCards_EarnedTradingCard": " κέρδισε μια κάρτα ανταλλαγών",
	"AppActivity_SteamTradingCards_EarnedBoosterPack": " κέρδισε ένα πακέτο ενίσχυσης",
	"AppActivity_SteamTradingCards_BadgeCrafted": " κατασκεύασε ένα έμβλημα",
	"AppActivity_ViewLatestNews": "Προβολή νεότερων νέων",
	"AppActivity_EventType_GameUpdate": "Ενημέρωση παιχνιδιού",
	"AppSpotlight_PostGameSummary": "Περίληψη λήξης παιχνιδιού",
	"AppDetails_Shortcut_Explanation": "Μερικές λεπτομερείς πληροφορίες για %1$s δεν είναι διαθέσιμες επειδή είναι ένα παιχνίδι ή μια τροποποίηση εκτός Steam. Το Steam θα εξακολουθεί να διαχειρίζεται την εκκίνηση του παιχνιδιού για εσάς και στις περισσότερες περιπτώσεις η επικάλυψη εντός παιχνιδιού θα είναι διαθέσιμη.",
	"AppDetails_Takeover_Update_Header": "Σε περίπτωση που το χάσατε",
	"AppDetails_Takeover_Update_ViewAll": "Προβολή όλων των ενημερώσεων παιχνιδιού %1$s",
	"AppDetails_Takeover_Update_ReadMore": "Διαβάστε περισσότερα",
	"AppDetails_Takeover_DLC_Header": "Προστέθηκαν νέα αντικείμενα",
	"AppDetails_Takeover_DLC_ViewInStore": "Προβολή %1$s στο κατάστημα",
	"AppDetails_Takeover_Achievements_Header": "Παίχτηκαν %2$s, έχετε ένα νέο επίτευγμα...",
	"AppDetails_Takeover_Achievements_Header_Plural": "Παίχτηκαν %2$s, έχετε νέα επιτεύγματα...",
	"AppDetails_Takeover_TradingCards_Header": "Παίξατε %2$s, έχετε ένα νέο αντικείμενο...",
	"AppDetails_Takeover_TradingCards_Header_Plural": "Παίξατε %2$s, έχετε νέα αντικείμενα...",
	"AppDetails_ViewMyInventory": "Προβολή της λίστας αντικειμένων μου",
	"AppDetails_ViewInMyInventory": "Προβολή στη λίστα αντικειμένων μου",
	"AppDetails_Soundtrack_TotalTracks": "%1$s κομμάτια",
	"AppDetails_Soundtrack_DiscNumber": "Δίσκος %1$s",
	"AppDetails_Soundtrack_TrackCount": "%1$s Κομμάτια",
	"AppDetails_Soundtrack_PlayAlbum": "Αναπαραγωγή άλμπουμ",
	"AppDetails_Soundtrack_DownloadAlbum": "Λήψη άλμπουμ",
	"AppDetails_Soundtrack_AddToQueue": "Προσθήκη στην ουρά",
	"AppDetails_Soundtrack_AddToPlaylist": "Προσθήκη σε λίστα αναπαραγωγής",
	"AppDetails_Soundtrack_ViewOnDisk": "Περιήγηση τοπικών αρχείων",
	"AppDetails_Soundtrack_ViewAdditionalArtwork": "Προβολή επιπλέον τέχνης",
	"AppDetails_Soundtrack_ViewStorePage": "Προβολή σελίδας καταστήματος",
	"AppDetails_Soundtrack_Support": "Προβολή σελίδας υποστήριξης",
	"AppDetails_Soundtrack_ParentAppLink": "Soundtrack για %1$s",
	"AppPortraitHover_DownloadStatusTitle": "Λήψη...",
	"AppPortraitHover_DownloadStatusTitle_Update": "Λήψη ενημέρωσης...",
	"AppPortraitHover_DaysSinceLastUpdate": "Ενημερώθηκε %1$s",
	"AppPortraitHover_FriendsPlaying": "%1$s φίλοι παίζουν",
	"MajorUpdate_ViewDetails": "Προβολή λεπτομερειών",
	"MajorUpdate_NextUpdate": "Επόμενη ενημέρωση",
	"MajorUpdate_PostTime": "Αναρτήθηκε %1$s μέρες πριν στις %2$s:%3$s",
	"MajorUpdate_PostTimeToday": "Αναρτήθηκε σήμερα στις %1$s:%2$s",
	"MajorUpdate_WatchNow": "Προβολή σε SteamTV",
	"MajorUpdate_Type0": "Μεγάλη ενημέρωση",
	"MajorUpdate_Type1": "Ζωντανή μετάδοση",
	"MajorUpdate_Type14": "Μεγάλη ενημέρωση",
	"MajorUpdate_Context_RemoveThisUpdate": "Αφαίρεση αυτής της ενημέρωσης",
	"MajorUpdate_Context_ShowMeFewerForApp": "Εμφάνιση λιγότερων από %1$s",
	"MajorUpdate_Context_ShowMeMoreForApp": "Εμφάνιση περισσότερων από %1$s",
	"MajorUpdate_Context_ResetHiddenUpdates": "Εμφάνιση όλων των ενημερώσεων ξανά",
	"MajorUpdate_Context_WhyAmISeeingThis": "Γιατί το βλέπω αυτό;",
	"MajorUpdate_Context_WhyAmISeeingThis_Text": "Αυτή είναι μια μεγάλη ενημέρωση για ένα προϊόν στη συλλογή σας με περισσότερες από 20 ώρες παιχνιδιού.",
	"MajorUpdate_Context_WhyAmISeeingThis_Close": "Κλείσιμο",
	"CustomArt_ErrorTitle": "Σφάλμα",
	"CustomArt_BadFileType": "Το αρχείο σας πρέπει να είναι τύπου JPG ή PNG.",
	"CustomArt_UnknownError": "Παρουσιάστηκε ένα σφάλμα καθώς ρυθμίζαμε την τέχνη σας.",
	"CustomArt_SetCustomBackground": "Ορισμός προσαρμοσμένου φόντου",
	"CustomArt_ClearCustomBackground": "Εκκαθάριση προσαρμοσμένου φόντου",
	"CustomArt_SetCustomLogo": "Ορισμός προσαρμοσμένου λογότυπου",
	"CustomArt_ClearCustomLogo": "Εκκαθάριση προσαρμοσμένου λογότυπου",
	"CustomArt_EditLogoPosition": "Προσαρμογή θέσης λογότυπου",
	"CustomArt_ResetLogoPosition": "Επαναφορά θέσης λογότυπου",
	"CustomArt_DoneEditingLogo": "ΟΚ",
	"AppDetails_LibraryInUse": "Συλλογή σε χρήση από",
	"AppDetails_InSharedLibrary": "Από τη συλλογή του",
	"FriendContextMenu_OpenFriends": "Άνοιγμα φίλων & συνομιλίας",
	"FriendContextMenu_ViewProfile": "Προβολή προφίλ",
	"Generic_ScrollToTop": "Κύλιση σε κορυφή",
	"Generic_ViewGameDetails": "Προβολή παιχνιδιού στη συλλογή",
	"GameDetails_CollectionContext_GoTo": "Μετάβαση στη συλλογή",
	"GameDetails_CollectionContext_Remove": "Αφαίρεση από συλλογή",
	"ArtworkModal_ViewAll": "Προβολή όλων των στιγμιοτύπων",
	"ArtworkModal_FileSize": "Μέγεθος αρχείου",
	"ArtworkModal_Posted": "Αναρτήθηκε",
	"ArtworkModal_Size": "Μέγεθος",
	"ArtworkModal_CreatedBy": "Δημιουργήθηκε από",
	"ArtworkModal_ScrollForMore": "Κυλήστε κάτω για σχόλια",
	"ArtworkModal_ScrollForDetails": "Κυλήστε κάτω για λεπτομέρειες",
	"CommunityItem_Menu_Report": "Αναφορά",
	"ReportItem_Title": "Αναφορά αυτού του αντικειμένου",
	"ReportItem_Description": "Παρακαλούμε περιγράψετε τον τρόπο με το οποίο αυτό το αντικείμενο παραβιάζει τους Όρους χρήσης του Steam. Παρακαλούμε συμπεριλάβετε οποιαδήποτε σχετική πληροφορία ή συνδέσμους. Η συμπλήρωση αυτής της αναφοράς δεν μπορεί να αναιρεθεί.",
	"ReportItem_Description_Line2": "Τα αναφερόμενα αντικείμενα δε θα εμφανίζονται πλέον στη σελίδα συλλογής σας.",
	"ReportItem_DMCA": "Αν θέλετε να αναφέρετε παραβίαση πνευματικών δικαιωμάτων και είστε ο κάτοχος των πνευματικών δικαιωμάτων, παρακαλούμε συνεχίστε στη DMCA φόρμα ειδοποίησης παραβίασης πνευματικών δικαιωμάτων %1$s μας",
	"ReportItem_DMCA_LinkText": "εδώ",
	"ReportItem_Error": "Παρουσιάστηκε ένα πρόβλημα κατά την υποβολή του αιτήματός σας στους διακομιστές μας. Προσπαθήστε ξανά αργότερα.",
	"ReportItem_SubmitReport": "Υποβολή αναφοράς",
	"RemoveFreeApp_Title": "Αφαίρεση από το λογαριασμό σας",
	"RemoveFreeApp_Description": "Το %1$s προστέθηκε στο λογαριασμό σας με μια δωρεάν άδεια. Μπορείτε να το αφαιρέσετε από το λογαριασμό σας ώστε να μην περιλαμβάνετε πλέον στη συλλογή Steam σας και στη λίστα παιχνιδιών που κατέχετε.",
	"RemoveFreeApp_Question": "Θέλετε να αφαιρέσετε το %1$s από το λογαριασμό σας;",
	"RemoveFreeApp_Remove": "Αφαίρεση",
	"RemoveFreeApp_Removing": "Γίνεται αφαίρεση του %1$s",
	"RemoveFreeApp_Error": "Παρουσιάστηκε ένα σφάλμα κατά την αφαίρεση του %1$s",
	"UninstallDialog_Title": "Απεγκατάσταση",
	"UninstallDialog_Uninstall": "Απεγκατάσταση",
	"UninstallDialog_ErrorMessage": "Αποτυχία απεγκατάστασης %1$s επειδή:",
	"UninstallDialog_Busy": "Μια άλλη διαδικασία εγκατάστασης/απεγκατάστασης είναι αυτή τη στιγμή ενεργή. Παρακαλούμε περιμένετε να ολοκληρωθεί αυτή η ενέργεια.",
	"UninstallDialog_SecuROM": "Η απεγκατάσταση αυτής της εφαρμογής απαιτεί μια σύνδεση στο διαδίκτυο.",
	"UninstallDialog_UnknownError": "Παρουσιάστηκε ένα απρόσμενο σφάλμα κατά την απεγκατάσταση αυτής της εφαρμογής.",
	"UninstallDialog_AppUpdateError": "Σφάλμα απεγκατάστασης - %1$s",
	"UninstallDialog_Confirmation_Single": "Θέλετε να απεγκαταστήσετε το %1$s από αυτόν τον υπολογιστή; Θα παραμένει στη συλλογή παιχνιδιών σας, αλλά για να το παίξετε στο μέλλον, θα χρειαστεί πρώτα να ξανακατεβάσετε όλο το περιεχόμενό του.",
	"UninstallDialog_Confirmation_Multiple": "Θέλετε να απεγκαταστήσετε αυτούς τους επιλεγμένους τίτλους από αυτόν τον υπολογιστή; Αυτοί οι τίτλοι θα παραμείνουν στη συλλογή παιχνιδιών σας, αλλά για να τα παίξετε στο μέλλον, θα χρειαστεί πρώτα να ξανακατεβάσετε το περιεχόμενό τους.",
	"UninstallingDialog_Uninstalling": "Απεγκατάσταση",
	"UninstallingDialog_UninstallingApp": "Απεγκατάσταση %1$s",
	"UninstallingDialog_WaitingForPassword": "Αναμονή για κωδικό",
	"Showcase_AddNewShowcase": "Προσθήκη νέου ραφιού",
	"Showcase_DeleteShowcase": "Διαγραφή αυτού του ραφιού",
	"Showcase_SelectCategory": "Επιλέξτε ένα ράφι",
	"Showcase_EmptyShowcaseHint": "Επιλέξτε τι να εμφανίζεται σε αυτό το ράφι. Μπορείτε να αλλάξετε ή να διαγράψετε το ράφι και από εδώ επίσης!",
	"Showcase_GoToCollection": "Μετάβαση στη συλλογή",
	"Showcase_GoToAllCollections": "Μετάβαση σε όλες τις συλλογές",
	"Showcase_AllYourGames": "Όλα τα παιχνίδια",
	"Showcase_AllCollections": "Προβολές συλλογών",
	"Showcase_RecentGames": "Πρόσφατα παιχνίδια",
	"Showcase_DoneReordering": "ΟΚ",
	"Playtime_TwoWeeks_Minutes": "%1$s λεπτά παίχθηκαν πρόσφατα",
	"Playtime_TwoWeeks_Hours": "%1$s ώρες παίχθηκαν πρόσφατα",
	"Playtime_Total_Minutes": "%1$s λεπτά παίχθηκαν συνολικά",
	"Playtime_Total_Hours": "%1$s ώρες παίχθηκαν συνολικά",
	"Playtime_Minutes": "%1$s λεπτά",
	"Playtime_Hours": "%1$s ώρες",
	"Playtime_Recently": "%1$s παίχθηκαν πρόσφατα",
	"Playtime_Total": "%1$s παίχθηκαν συνολικά",
	"GameList_Search_NoResults_Title": "Δεν μπορείτε να βρείτε αυτό που ψάχνετε;",
	"GameList_Search_NoResults_Link": "Αναζητήστε το κατάστημα Steam",
	"StreamingClient_Select_ThisMachine": "Αυτή η μηχανή",
	"StreamingClient_Select_RemotePlayPhone": "Τηλέφωνα",
	"StreamingClient_Select_RemotePlayTablet": "Τάμπλετ",
	"StreamingClient_Select_RemotePlayMobile": "Κινητές συσκευές",
	"StreamingClient_Select_RemotePlayTV": "TV",
	"StreamingClient_Select_RemotePlayTVPhone": "TV & τηλέφωνα",
	"StreamingClient_Select_RemotePlayTVTablet": "TVs & τάμπλετ",
	"StreamingClient_Select_RemotePlayTVMobile": "TVs & κινητές συσκευές",
	"Beta_BetaTag": "ΔΟΚΙΜΗ",
	"Beta_Changelist": "Λίστα αλλαγών",
	"Beta_GiveFeedback": "Αφήστε σχόλια",
	"ContextMenu_SaveScreenshot": "Αποθήκευση στιγμιότυπου ως...",
	"ContextMenu_BrowseScreenshot": "Περιήγηση σε στιγμιότυπα",
	"ContextMenu_ManageScreenshots": "Διαχείριση στιγμιοτύπων",
	"SteamChina_DurationControl_Init_1": "Healthy Gaming Advisory",
	"SteamChina_DurationControl_Init_2": "Boycott harmful games; reject game piracy.",
	"SteamChina_DurationControl_Init_3": "Exercise self-protection; avoid deception.",
	"SteamChina_DurationControl_Init_4": "Moderation promotes brain health; excess play is harmful to the body.",
	"SteamChina_DurationControl_Init_5": "Well-planned use of your time will lead to a healthy lifestyle.",
	"Steam_AppUpdateError_0": "χωρίς σφάλμα",
	"Steam_AppUpdateError_1": "άγνωστο σφάλμα",
	"Steam_AppUpdateError_2": "ενημέρωση σε παύση",
	"Steam_AppUpdateError_3": "η ενημέρωση ακυρώθηκε",
	"Steam_AppUpdateError_4": "η ενημέρωση αναβλήθηκε",
	"Steam_AppUpdateError_5": "χωρίς άδειες",
	"Steam_AppUpdateError_6": "χωρίς σύνδεση στο διαδίκτυο",
	"Steam_AppUpdateError_7": "λήξη χρόνου σύνδεσης",
	"Steam_AppUpdateError_8": "περιεχόμενο ακόμα κρυπτογραφημένο",
	"Steam_AppUpdateError_9": "μη διαθέσιμη διαμόρφωση εφαρμογής",
	"Steam_AppUpdateError_10": "σφάλμα ανάγνωσης δίσκου",
	"Steam_AppUpdateError_11": "σφάλμα εγγραφής δίσκου",
	"Steam_AppUpdateError_12": "χωρίς αρκετό ελεύθερο χώρο στο δίσκο",
	"Steam_AppUpdateError_13": "κατεστραμμένα αρχεία περιεχομένου",
	"Steam_AppUpdateError_14": "αναμονή για δίσκο εγκατάστασης",
	"Steam_AppUpdateError_15": "μη έγκυρη διαδρομή εγκατάστασης",
	"Steam_AppUpdateError_16": "η εφαρμογή εκτελείται",
	"Steam_AppUpdateError_17": "λείπει κοινό περιεχόμενο",
	"Steam_AppUpdateError_18": "μη εγκατεστημένο",
	"Steam_AppUpdateError_19": "απαιτείται ενημέρωση",
	"Steam_AppUpdateError_20": "απασχολημένο",
	"Steam_AppUpdateError_21": "απρόσιτοι διακομιστές περιεχομένου",
	"Steam_AppUpdateError_22": "μη έγκυρη διαμόρφωση εφαρμογής",
	"Steam_AppUpdateError_23": "μη έγκυρη διαμόρφωση ντεπό",
	"Steam_AppUpdateError_24": "μη διαθέσιμο δηλωτικό",
	"Steam_AppUpdateError_25": "η εφαρμογή δεν έχει κυκλοφορήσει",
	"Steam_AppUpdateError_26": "περιορισμός περιοχής",
	"Steam_AppUpdateError_27": "κατεστραμμένη κρυφή μνήμη περιεχομένου",
	"Steam_AppUpdateError_28": "λείπει εκτελέσιμο αρχείο",
	"Steam_AppUpdateError_29": "μη έγκυρη πλατφόρμα",
	"Steam_AppUpdateError_30": "μη υποστηριζόμενο σύστημα αρχείων",
	"Steam_AppUpdateError_31": "κατεστραμμένα αρχεία ενημέρωσης",
	"Steam_AppUpdateError_32": "απενεργοποιημένες λήψεις",
	"Steam_AppUpdateError_33": "κλειδωμένη κοινή συλλογή",
	"Steam_AppUpdateError_34": "εκκρεμεί αγορά",
	"Steam_AppUpdateError_35": "παίζει άλλη συνεδρία",
	"Steam_AppUpdateError_36": "κατεστραμμένη λήψη",
	"Steam_AppUpdateError_37": "κατεστραμμένος δίσκος",
	"Steam_AppUpdateError_38": "λείπουν δικαιώματα αρχείου",
	"Steam_AppUpdateError_39": "κλειδωμένο αρχείο περιεχομένου",
	"Steam_AppUpdateError_40": "μη διαθέσιμο περιεχόμενο",
	"Steam_AppUpdateError_41": "το εκτελέσιμο απαιτεί λειτουργικό σύστημα 64bit",
	"Steam_AppUpdateError_42": "λείπουν ληφθέντα αρχεία",
	"Steam_AppUpdateError_43": "χωρίς αρκετό ελεύθερο χώρο στο δίσκο για χρήστη - ελέγξτε τις ρυθμίσεις ορίου δίσκου του ΛΣ",
	"Steam_AppUpdateError_44": "κλειδωμένη άδεια χώρου",
	"Steam_AppUpdateError_45": "αποκλεισμός από γονικό έλεγχο",
	"Steam_AppUpdateError_46": "αποτυχία δημιουργίας διαδικασίας",
	"Steam_AppUpdateError_47": "μη ενημερωμένη εφαρμογή Steam",
	"ShareDialog_Title": "ΚΟΙΝΟΠΟΙΗΣΗ",
	"ShareUploadScreenshot_Description": "Ανεβάστε αυτό το στιγμιότυπο στο προφίλ Steam και στη ροή δραστηριότητάς σας.",
	"ShareUploadScreenshot_AddCaption": "προσθέστε μια λεζάντα εδώ",
	"ShareUploadScreenshot_CaptionHeader": "Λεζάντα:",
	"ShareUploadScreenshot_TagSpoiler": "Σήμανση ως spoiler",
	"ShareUploadScreenshot_CloudUsage": "Θα χρησιμοποιήσει %1$s από την %2$s εναπομένουσα χωρητικότητα cloud σας (%3$s συνολικά)",
	"ShareUploadScreenshot_Uploading": "Ανεβαίνει στο Steam",
	"ShareUploadScreenshot_PermissionDenied": "Το Steam αδυνατούσε να ανεβάσει αυτό το στιγμιότυπο. Δε σας επιτρέπεται να ανεβάζετε περιεχόμενο λόγω ενός ενεργού αποκλεισμού στο λογαριασμό σας.",
	"ShareUploadScreenshot_UnexpectedError": "Το Steam αδυνατούσε να ανεβάσει αυτό το στιγμιότυπο στο Steam Cloud. Παρακαλούμε προσπαθήστε ξανά.",
	"DeleteScreenshot_Title": "Διαγραφή στιγμιότυπου",
	"DeleteScreenshot_Single": "Θέλετε σίγουρα να διαγράψετε αυτό το στιγμιότυπο από το σκληρό σας δίσκο;",
	"DeleteScreenshot_Failed": "Το Steam αδυνατούσε να διαγράψει το επιλεγμένο στιγμιότυπο από τον σκληρό σας δίσκο.",
	"AppDetailsAchievement_Hidden": "Κρυφό επίτευγμα",
	"AppDetailsAchievement_HiddenDesc": "Συνεχίστε να παίζετε για να ανακαλύψετε αυτό το επίτευγμα.",
	"Demo_SpotlightIntro": "Ελέγξτε το πλήρες παιχνίδι",
	"Demo_VisitStorePage": "Επισκεφτείτε τη σελίδα καταστήματος",
	"SteamReviewScore_9": "Υπερβολικά θετικές",
	"SteamReviewScore_8": "Πολύ θετικές",
	"SteamReviewScore_7": "Θετικές",
	"SteamReviewScore_6": "Κυρίως θετικές",
	"SteamReviewScore_5": "Ανάμεικτες",
	"SteamReviewScore_4": "Κυρίως αρνητικές",
	"SteamReviewScore_3": "Αρνητικές",
	"SteamReviewScore_2": "Πολύ αρνητικές",
	"SteamReviewScore_1": "Υπερβολικά αρνητικές"
}
