{
	"Generic_Okay": "Okay",
	"Generic_Close": "Luk",
	"Generic_Open": "Åbn",
	"Generic_GotIt": "Forstået!",
	"Generic_Share": "Del",
	"Generic_Upload": "Upload",
	"Generic_Delete": "Slet",
	"Privacy_Public": "Offentlig",
	"Privacy_FriendsOnly": "Kun venner",
	"Privacy_Private": "Privat",
	"AppType_0": "Ugyldig",
	"AppType_1": "Spil",
	"AppType_2": "Software",
	"AppType_4": "Værktøjer",
	"AppType_20": "DLC",
	"AppType_800": "Videoer",
	"AppType_2000": "Soundtracks",
	"AppType_Singular_0": "Ugyldig",
	"AppType_Singular_1": "spil",
	"AppType_Singular_2": "applikation",
	"AppType_Singular_4": "værktøj",
	"AppType_Singular_20": "DLC",
	"AppType_Singular_800": "video",
	"AppType_Singular_2000": "musik",
	"AppType_Singular_8000": "tegneserie",
	"AppType_Singular_40000000": "genvej",
	"FilterEdit_SavedFilters": "Gemte filtre",
	"FilterEdit_FirstColumnHeader": "Filtertype",
	"FilterEdit_Customize": "Tilpas",
	"FilterEdit_SearchModeHeader": "Avancerede filtre",
	"FilterEdit_CollectionModeHeader": "Rediger samlingsfiltre",
	"CollectionEdit_CollectionNameField": "Samlingsnavn:",
	"CollectionEdit_RenameButton": "Omdøb samling",
	"Collection_DynamicCollection": "Dynamisk samling",
	"FilterEdit_AdvancedTooltip": "Avancerede filterindstillinger til at sortere din spilliste efter genre, spilfunktioner m.m.",
	"Collection_FreezeDynamicCollection_Button": "Snapshot",
	"Collection_FreezeDynamicCollection_ToolTip": "Konverter denne dynamiske samling til en simpel samling, som låser den nuværende spilliste.",
	"Collection_FreezeDynamicCollection_DialogTitle": "Snapshotsamling",
	"Collection_FreezeDynamicCollection_Confirmation": "Er du sikker på, at du vil konvertere denne samling? Den vil ikke længere blive opdateret dynamisk, når du tilføjer spil, der matcher, til dit bibliotek.",
	"Collection_ResetDialogTitle": "Nulstil samlinger",
	"Collection_ResetConfirmation": "Er du sikker på, at du vil nulstille din samlingsliste og importere dine gamle kategorier igen?",
	"Collection_AfterResetSummary_NoCollections": "Du vil ikke have nogen samlinger efter nulstillingen.",
	"Collection_AfterResetSummary_CountAndNames": "Du vil have de følgende %1$s samlinger efter nulstillingen: %2$s",
	"Collection_ResetFailed": "Kunne ikke nulstille samlinger",
	"FilterEdit_SelectedFilters": "Valgte filtre",
	"FilterEdit_SaveCollectionNameInputPrompt": "Indtast et navn til samlingen",
	"FilterEdit_SaveOverwrite": "Samlingen \"%1$s\" eksisterer allerede. Overskriv?",
	"FilterEdit_SaveCollection": "Gem som samling",
	"FilterEdit_SaveDynamicCollectionWithIcon": "Gem som %1$sdynamisk samling",
	"FilterEdit_SaveDynamicCollectionNoIcon": "Gem som dynamisk samling",
	"FilterEdit_SaveCollectionVerbose": "Gem denne søgning som en samling, så du kan bruge den igen i fremtiden. Du kan altid redigere, omdøbe eller slette samlingen senere eller trække emner ind i eller ud af den.",
	"FilterEdit_SaveStandardCollectionButtonDesc": "En samling er en simpel måde at organisere dit bibliotek på. Træk titler over på samlingen, eller højreklik på en titel for at tilføje den til en eksisterende samling.",
	"FilterEdit_SaveDynamicCollectionButtonDesc": "Dynamiske samlinger anvender filtre til at oprette samlinger, der opdateres, efterhånden som dit bibliotek vokser.",
	"FilterEdit_SelectCollectionType": "Vælg en samlingstype",
	"FilterEdit_SelectCollectionTypeButtonCreate": "Opret samling",
	"FilterEdit_SelectCollectionTypeButtonCreateDynamic": "Opret dynamisk samling",
	"FilterEdit_RequiredField": "(PÅKRÆVET)",
	"FilterEdit_SearchPrompt": "Søg efter navn",
	"FilterEdit_ClearSearch": "Afslut søgning",
	"FilterEdit_SearchResults": "Søgeresultater",
	"FilterEdit_CollectionsHiddenPromptTitle": "Samlinger er skjulte",
	"FilterEdit_CollectionsHiddenPrompt": "Ønsker du at ændre listevisningen, så den nye samling er synlig?",
	"FilterEdit_AcceptGameListViewChange": "Ja, vis samlinger",
	"FilterEdit_RejectGameListViewChange": "Nej, lad visningen være uændret",
	"AdvancedSearch_PaneTitle": "Søg efter type",
	"AdvancedSearch_PlayerSection": "Spillere",
	"AdvancedSearch_HardwareSection": "Hardwaresupport",
	"AdvancedSearch_FeatureSection": "Funktioner",
	"AdvancedSearch_StateSection": "Spilletilstand",
	"AdvancedSearch_GenreSection": "Genre",
	"AdvancedSearch_StoreTagSection": "Butikstags",
	"AdvancedSearch_StoreTagPrompt": "indtast et tag",
	"FilterCategory_1": "Status",
	"FilterCategory_Features": "FUNKTION",
	"FilterCategory_3": "Kategori",
	"FilterCategory_4": "Butikstag",
	"FilterCategory_Type": "TYPE",
	"FilterCategory_Genre": "GENRE",
	"FilterCategory_PlayState": "TILSTAND",
	"FilterElement_VR": "VR",
	"FilterElement_Tooltip_VR": "Inkluder spil, som understøtter virtual reality-hardware.",
	"FilterElement_Installed": "Installeret lokalt",
	"FilterElement_Tooltip_Installed": "Inkluder spil, som er installeret på denne computer.",
	"FilterElement_ReadyToPlay": "Klar til at spille",
	"FilterElement_Tooltip_ReadyToPlay": "Inkluder spil, som du kan spille lokalt eller streame fra en anden computer.",
	"FilterElement_PlayedPreviously": "Spillet",
	"FilterElement_Tooltip_PlayedPreviously": "Inkluder spil, som du allerede har spillet.",
	"FilterElement_Unplayed": "Ikke spillet",
	"FilterElement_Tooltip_Unplayed": "Inkluder spil, som du endnu ikke har spillet.",
	"FilterElement_FullControllerSupport": "Controllere (fuld understøttelse)",
	"FilterElement_Tooltip_FullControllerSupport": "Inkluder spil, som kan spilles fuldstændigt med en spilcontroller.",
	"FilterElement_PartialControllerSupport": "Controllere (delvis understøttelse)",
	"FilterElement_Tooltip_PartialControllerSupport": "Inkluder spil, som kan spilles med en controller, men muligvis kræver et tastatur og en mus under installation eller til enkelte interaktioner.",
	"FilterElement_VRSupported": "VR understøttet",
	"FilterElement_TradingCards": "Byttekort",
	"FilterElement_Tooltip_TradingCards": "Inkluder spil, som har Steam-byttekort.",
	"FilterElement_Workshop": "Værksted",
	"FilterElement_Tooltip_Workshop": "Inkluder spil med Steam-værkstedsintegration.",
	"FilterElement_Achievements": "Præstationer",
	"FilterElement_Tooltip_Achievements": "Inkluder spil med Steam-præstationer.",
	"FilterElement_SinglePlayer": "Singleplayer",
	"FilterElement_Tooltip_SinglePlayer": "Inkluder spil med singleplayer-tilstand.",
	"FilterElement_MultiPlayer": "Multiplayer",
	"FilterElement_Tooltip_MultiPlayer": "Inkluder spil med multiplayertilstand.",
	"FilterElement_CoOp": "Co-op",
	"FilterElement_Tooltip_CoOp": "Inkluder spil med multiplayertilstand, hvor spillere skal samarbejde.",
	"FilterElement_GenreAction": "Action",
	"FilterElement_Tooltip_GenreAction": "Inkluder actionspil.",
	"FilterElement_GenreAdventure": "Eventyr",
	"FilterElement_Tooltip_GenreAdventure": "Inkluder eventyrspil.",
	"FilterElement_GenreCasual": "Casual",
	"FilterElement_Tooltip_GenreCasual": "Inkluder casual spil.",
	"FilterElement_GenreIndie": "Indie",
	"FilterElement_Tooltip_GenreIndie": "Inkluder indiespil.",
	"FilterElement_GenreMMO": "MMO",
	"FilterElement_Tooltip_GenreMMO": "Inkluder MMO-spil.",
	"FilterElement_GenreRacing": "Racer",
	"FilterElement_Tooltip_GenreRacing": "Inkluder racerspil.",
	"FilterElement_GenreRPG": "Rollespil (RPG)",
	"FilterElement_Tooltip_GenreRPG": "Inkluder rollespil.",
	"FilterElement_GenreSimulation": "Simulation",
	"FilterElement_Tooltip_GenreSimulation": "Inkluder simulationsspil.",
	"FilterElement_GenreSports": "Sport",
	"FilterElement_Tooltip_GenreSports": "Inkluder sportsspil.",
	"FilterElement_GenreStrategy": "Strategi",
	"FilterElement_Tooltip_GenreStrategy": "Inkluder strategispil.",
	"FilterElement_Tooltip_StoreTag": "Inkluder spil med tagget \"%1$s\"",
	"FilterElement_SteamCloud": "Steam Cloud",
	"FilterElement_Tooltip_SteamCloud": "Inkluder spil, som gemmer spil i Steam Cloud.",
	"FilterElement_RemotePlayTogether": "Remote Play Together",
	"FilterElement_Tooltip_RemotePlayTogether": "Inkluder spil, som understøtter Remote Play Together.",
	"CollectionViewHeader_Tooltip_ManuallyAddedApp": "Dette spil blev tilføjet til samlingen manuelt.",
	"CollectionViewHeader_Tooltip_ManuallyRemovedApp": "Dette spil blev fjernet fra samlingen manuelt.",
	"CollectionViewHeader_Tooltip_ManuallyRemovedApps_WithCount": "%1$s spil blev fjernet fra denne samling.",
	"CollectionViewHeader_ManuallyRemovedApps_WithCount": "%1$s fjernet",
	"CollectionView_EmptyReadOnlyCollection": "Der er intet at se her",
	"CollectionView_EmptyDynamicCollection_Line1": "Der er ingen spil, der matcher dette filter!",
	"CollectionView_EmptyDynamicCollection_Line2": "Rediger filtret, eller træk spil hertil for at fylde samlingen.",
	"CollectionView_EmptyCollection": "Træk spil hertil for at fylde samlingen.",
	"CollectionView_EmptyCollection_BecauseFilter": "%1$s spil i denne samling bliver ikke vist pga. dit valgte visningsfilter.",
	"CollectionView_EmptyCollection_BecauseFilter_Plural": "%1$s spil i denne samling bliver ikke vist pga. dit valgte visningsfilter.",
	"CollectionView_MissingCollection": "Ingen samling fundet.",
	"CollectionView_GamesExcluded": "+%1$s",
	"CollectionView_GamesExcluded_Desc": "titler er ikke klar til at spille",
	"AllCollectionsView_Title": "Dine samlinger",
	"AllCollectionsView_InfoIcon": "Opret %1$s for at organisere dine titler, som du vil, eller opret %2$s for at gruppere titler efter et sæt af filtre. %3$s",
	"AllCollectionsView_InfoIconCollections": "samlinger",
	"AllCollectionsView_InfoIconDynamicCollections": "dynamiske samlinger",
	"AllCollectionsView_InfoIconFav": "Dine %1$s vil altid blive vist her øverst på siden.",
	"AllCollectionsView_InfoIconFavorites": "favoritter",
	"AllCollectionsView_AddCollection": "Opret en ny samling",
	"AllCollectionsView_DragToAddCollection": "Træk hertil for at oprette en ny samling",
	"GameList_Home": "Startside",
	"GameList_Search": "Søg",
	"GameList_Category_Uncategorized": "Ikke kategoriseret",
	"GameList_Category_Favorites": "Favoritter",
	"GameList_Category_Hidden": "Skjulte",
	"GameList_Category_Hidden_Tooltip": "Skjulte spil bliver ikke vist i dit bibliotek, medmindre du søger efter dem. Du kan se alle skjulte spil i topmenuen \"Vis\".",
	"GameList_Category_YourCollections": "Dine samlinger",
	"GameList_Category_SharedLibraries": "Delte biblioteker",
	"GameList_SectionHeader_SearchResults": "Resultater fra søgning og filter",
	"GameList_SectionHeader_AddedManually": "Tilføjet manuelt",
	"GameList_SectionHeader_RemovedManually": "Fjernet manuelt",
	"GameList_SectionHeader_NoRecentActivity": "Ingen registreret aktivitet",
	"GameList_View_Collections": "Dine samlinger",
	"GameList_View_ThisCollection": "Vis denne samling",
	"GameList_View_OneCollection": "Samlingsvisning",
	"GameList_View_SearchResults": "Søgeresultater",
	"GameList_View_ShowAllCollections": "Vis alle samlinger",
	"GameList_View_GroupByCollections": "Grupper efter samling",
	"GameList_View_ExitSearch": "Afslut søgning",
	"GameList_View_All": "Alle",
	"GameList_View_Recent": "Seneste",
	"GameList_View_SortByRecent": "Sorter efter seneste aktivitet",
	"GameList_View_ShowOnlyReadyToPlay": "Vis kun spil, der er klar til at blive spillet",
	"GameList_View_ShowingReadyToPlay": "Viser kun spil, der er klar til at blive spillet",
	"GameList_View_ShowingOnlyReadyToPlay": "Viser spil, der er klar til at blive spillet",
	"GameList_View_ShowOnlyVR": "Vis kun VR-spil",
	"GameList_View_Platform_Linux": "Vis kun spil, som kan køre på Linux",
	"GameList_View_Platform_Apple": "Vis kun spil, som kan køre på macOS",
	"GameList_View_MyOwnGames": "Mine spil",
	"GameList_View_GamesSharedByOther": "%1$s's spil",
	"GameList_View_NothingSelected": "Ingen",
	"GameList_View_NothingSelected_HelpText": "Intet matcher dette visningsfilter.",
	"GameList_Search_GamesCheckbox_Link": "Vis spil",
	"GameList_View_GroupSharedLibraries": "Grupper efter bibliotek",
	"GameList_View_GroupingDisabled_ToolTip": "Gruppering er slået fra i denne visning",
	"GameList_View_ReadyToPlay_ToolTip1": "• Installeret på denne maskine",
	"GameList_View_ReadyToPlay_ToolTip2": "• Kan streames fra en anden maskine",
	"GameList_Entry_ReadyToPlay_ToolTip": "Vil blive streamet fra en anden maskine",
	"GameList_Entry_Invalid_OSType": "Dit nuværende macOs (Catalina) kan ikke køre 32-bit-spil. Dette spil kan muligvis ikke køre.",
	"GameList_Entry_Invalid_OSType2": "Steam Play er slået til for dette spil, så du kan spille det på Windows via Bootcamp eller ved at bruge en PC.",
	"GameList_Entry_Invalid_OSType3": "Læs mere.",
	"Shelf_SectionHeader_ExpandTooltip": "Udvid hylde for at vise flere rækker",
	"Shelf_SectionHeader_ExpandTooltipFilter": "Udvid hylde for at vise flere rækker, %1$s emner vises ikke pga. dit visningsfilter",
	"GameList_SectionHeader_AppCountToolTip": "%1$s vises ikke pga. dit visningsfilter",
	"GameList_SectionHeader_AppCountToolTipAllHidden": "Ingenting vises ikke pga. dit visningsfilter",
	"CollectionAction_ViewOnlyThis": "Vis kun denne samling",
	"CollectionAction_ViewOnlyThisFavorites": "Vis kun favoritter",
	"CollectionAction_ViewOnlyThisUncategorized": "Vis kun ikke-kategoriserede spil",
	"CollectionAction_Collapse": "Skjul",
	"CollectionAction_CollapseAll": "Skjul alle",
	"CollectionAction_CollapseAllCollections": "Skjul alle samlinger",
	"CollectionAction_Expand": "Udvid",
	"CollectionAction_ExpandAll": "Udvid alle",
	"CollectionAction_ExpandAllCollections": "Udvid alle samlinger",
	"CollectionAction_Manage": "Administrer",
	"CollectionAction_Edit": "Rediger samlingsfiltre",
	"CollectionAction_Rename": "Omdøb samling",
	"CollectionAction_Delete": "Fjern samling",
	"CollectionAction_DeleteDialog": "Fjern samling",
	"CollectionAction_ConfirmDelete": "Er du sikker på, at du vil slette samlingen \"%1$s\" permanent?",
	"CollectionAction_SaveFailed": "Kunne ikke gemme samlingen \"%1$s\"",
	"CollectionAction_CannotOverwrite": "Kunne ikke overskrive samlingen \"%1$s\". Vælg venligst et nyt navn.",
	"CollectionAction_DeleteFailed": "Kunne ikke slette samlingen \"%1$s\"",
	"LibraryHome_FriendsActivity": "Venneaktivitet",
	"LibraryHome_RecentGames": "Seneste spil",
	"LibraryHome_NewUpdates": "Nyheder",
	"LibraryHome_YourCollection": "Dit samlede bibliotek",
	"LibraryHome_RecentFriendsActivity": "Seneste venneaktivitet",
	"LibraryHome_NewUpdates_LoweredPriority": "Viser nu færre opdateringer for %1$s.",
	"LibraryHome_NewUpdates_RaisedPriority": "Viser nu flere opdateringer for %1$s.",
	"LibraryHome_NewUpdates_Undo": "Fortryd",
	"LibraryHome_RecentFriendsActivity_Empty": "Der er intet nyt eller populært i din vennegruppe lige nu. Denne hylde skjules automatisk, når der ikke er nogen aktivitet at vise.",
	"WhatsNewSettings": "Nyhedsindstillinger",
	"WhatsNew": "Nyheder",
	"WhatsNewFeatureExplainer": "Nyheder er stedet, hvor dine spils udviklere snakker om opdateringer, turneringer, DLC, begivenheder og andre spilrelaterede nyheder. Steam viser nyheder, der er mest relevant for dig, baseret på hvad du spiller mest, og prioriterer de spil, du har spillet for nylig.",
	"WhatsNewFeatureExplainer2": "Nogle spil ekskluderes automatisk fra \"Nyheder\", hvis du kun har spillet dem i et par timer, og det er længe siden, at du sidst har været aktiv i spillene.",
	"WhatsNewVisibilitySettings": "Synlighedsindstillinger",
	"WhatsNewSettings_ShowOnlyForRecentlyPlayed": "Vis kun for spil, jeg har spillet i de sidste 90 dage",
	"WhatsNewSettings_ShowOnlyForRecentlyPlayed_Explainer": "(Hyppighed for individuelle spil kan justeres ved at højreklikke på nyhedsemnet).",
	"WhatsNewSettings_ShowOnlyGameUpdates": "Vis kun produktopdateringer, ikke andre begivenheder eller nyheder",
	"WhatsNewSettings_ShowOnlyGameUpdates_Explainer": "(Hyppighed for individuelle spil kan justeres ved at højreklikke på nyhedsemnet).",
	"WhatsNewPrioritySettings": "Prioritetsindstillinger",
	"WhatsNewPriorityExplainer": "(Individuelle spil kan justeres, så der vises mere eller mindre i Nyheder. Højreklik på et emne for at se mulighederne).",
	"WhatsNewYouHaveAskedToShowLessFor": "Du har bedt om at få vist mindre om følgende spil:",
	"WhatsNewYouHaveNothingShowingLess": "Du har ikke bedt om at få vist mindre om nogen spil endnu.",
	"WhatsNewYouHaveAskedToShowMoreFor": "Du har bedt om at få vist mere om følgende spil:",
	"WhatsNewYouHaveNothingShowingMore": "Du har ikke bedt om at få vist mere om nogen spil endnu.",
	"WhatsNewYouHaveNItemsHidden": "%1$s spil er skjult i dit bibliotek og derfor også skjult i Nyheder.",
	"Library_FriendsActivity_HotRightNowHeading": "Populært lige nu",
	"Library_FriendsActivity_HotRightNowHover": "Vi viser dig dette spil, fordi flere af dine venner spiller det lige nu.",
	"Library_FriendsActivity_TrendingHeading": "Trender nu",
	"Library_FriendsActivity_TrendingHover": "Vi viser dig dette spil, fordi nogle af dine venner har spillet det mere i denne uge end i forrige uge.",
	"Library_FriendsActivity_BeingDiscussedHeading": "Bliver diskuteret",
	"Library_FriendsActivity_BeingDiscussedHover": "Vi viser dig dette spil, fordi dine venner har opslået skærmbilleder eller statusbeskeder.",
	"Library_FriendsActivity_RecentlyPurchasedHeading": "Seneste køb",
	"Library_FriendsActivity_RecentlyPurchasedHover": "Vi viser dig dette spil, fordi du har købt det for nylig, og dine venner spiller det.",
	"Library_FriendsActivity_UnownedHeading": "Prøv noget nyt",
	"Library_FriendsActivity_UnownedHover": "Vi viser dig dette spil, fordi det er populært blandt dine venner, og du ikke ejer det.",
	"Library_FriendsActivity_PopularHeading": "Populært",
	"Library_FriendsActivity_PopularHover": "Vi viser dig dette spil, fordi mange af dine venner har spillet det for nylig.",
	"Library_FriendsActivity_DontForgetHeading": "Glem ikke",
	"Library_FriendsActivity_DontForgetHover": "Vi viser dig dette spil, fordi du ikke har spillet det på det seneste, men det har dine venner.",
	"Library_FriendsActivity_NewToGroupHeading": "Nyt for dine venner",
	"Library_FriendsActivity_NewToGroupHover": "Vi viser dig dette spil, fordi dine venner begyndte at spille det for nylig.",
	"Library_FriendsActivity_ReturnedToGroupHeading": "Tilbage i rotation",
	"Library_FriendsActivity_ReturnedToGroupHover": "Vi viser dig dette spil, fordi dine venner er begyndt at spille det igen.",
	"Library_FriendsActivity_UnownedBanner": "Vis i Steam-butikken",
	"Library_FriendsActivity_UnownedMenu_Store": "Butik",
	"Library_FriendsActivity_UnownedMenu_Hub": "Fællesskabshub",
	"Library_FriendsActivity_UnownedMenu_Reviews": "Anmeldelser",
	"Library_FriendsActivity_UnownedMenu_Discussions": "Diskussioner",
	"Library_Recent_NoRecentGames_GamesOwned": "Du har %1$s spil.",
	"Library_Recent_NoRecentGames_StoreLink": "Gå til %1$s for at finde spil, du vil tilføje:",
	"Library_Recent_NoRecentGames_SteamStore": "Steam-butikken",
	"Library_Recent_NoRecentGames_FreeToPlay": "Spil, som er gratis at spille",
	"Library_Recent_NoRecentGames_GamesOnSale": "Spil på udsalg nu",
	"Library_Recent_NoRecentGames_NewReleases": "Nye udgivelser",
	"Library_Recent_NoRecentGames_ActivateProduct": "Aktiver et produkt",
	"Library_Recent_NoRecentGames_RedeemCode": "Indløs en tegnebogskode",
	"Library_SortCollectionBy": "Sorter efter",
	"Library_SortByFavoritesFirst": "Favoritter først",
	"Library_SortByAlphabetical": "Alfabetisk",
	"Library_SortByPctAchievementsComplete": "% af præstationerne gennemført",
	"Library_SortByLastUpdated": "Sidst opdateret",
	"Library_SortByHoursPlayed": "Timer spillet",
	"Library_SortByLastPlayed": "Sidst spillet",
	"Library_SortByReleaseDate": "Udgivelsesdato",
	"Library_SortByAddedToLibrary": "Dato tilføjet til bibliotek",
	"Library_SortBySizeOnDisk": "Størrelse på drev",
	"Library_SortByMetacriticScore": "Metacritic-score",
	"Library_SortByFriendsPlaying": "Venner spiller",
	"Library_SortBySteamReview": "Steam-anmeldelse",
	"Library_SortByPctAchievementsComplete_Tag": "%1$s% gennemført",
	"Library_SortByPctAchievementsNoAchievements_Tag": "Ingen præstationer",
	"Library_InstalledOnlyCheck": "Kun installeret",
	"GridSection_Favorites": "Favoritter",
	"GridSection_EverythingElse": "Alt andet",
	"GridSection_Over100Hours": "Over 100 timer",
	"GridSection_Over60Hours": "Over 60 timer",
	"GridSection_Over40Hours": "Over 40 timer",
	"GridSection_Over20Hours": "Over 20 timer",
	"GridSection_Over10Hours": "Over 10 timer",
	"GridSection_Over1Hour": "Over 1 time",
	"GridSection_LessThan1Hour": "Under 1 time",
	"GridSection_Over90Metacritic": "Over 90",
	"GridSection_Over80Metacritic": "Over 80",
	"GridSection_Over70Metacritic": "Over 70",
	"GridSection_Over50Metacritic": "Over 50",
	"GridSection_EverythingElseMetacritic": "Alt andet",
	"GridSection_UnknownReleaseDate": "Ukendt",
	"GridSection_GreaterThan100GB": "Større end 100GB",
	"GridSection_GreaterThan50GB": "Større end 50GB",
	"GridSection_GreaterThan20GB": "Større end 20GB",
	"GridSection_LessThan20GB": "Mindre end 20GB",
	"GridSection_NoSizeOnDisk": "Ingen størrelse",
	"GridSection_NotInstalled": "Ikke installeret",
	"GridSection_MoreThan10YearsAgo": "10+ år siden",
	"GridSection_Never": "Aldrig",
	"AppDetails_SectionTitle_Stream": "Udviklerbroadcast",
	"AppDetails_SectionTitle_Activity": "Aktivitet",
	"AppDetails_SectionTitle_Friends": "Venner, der spiller",
	"AppDetails_SectionTitle_Friends_Software": "Venner, der bruger",
	"AppDetails_SectionTitle_Achievements": "Præstationer",
	"AppDetails_SectionTitle_TradingCards": "Byttekort",
	"AppDetails_SectionTitle_Screenshots": "Skærmbilleder",
	"AppDetails_SectionTitle_AdditionalContent": "Yderligere indhold",
	"AppDetails_SectionTitle_Updates": "Seneste begivenheder og opdateringer",
	"AppDetails_SectionTitle_DLC": "DLC",
	"AppDetails_SectionTitle_LastPlayed": "Sidst spillet",
	"AppDetails_SectionTitle_LastLaunched": "Sidst startet",
	"AppDetails_SectionTitle_PlayTime": "Spilletid",
	"AppDetails_SectionTitle_UsageTime": "Forbrugstid",
	"AppDetails_SectionTitle_Workshop": "Steam-værksted",
	"AppDetails_SectionTitle_Community": "Fællesskabsindhold",
	"AppDetails_SectionTitle_Links": "Links",
	"AppDetails_SectionTitle_SignIn_Pre": "Log på",
	"AppDetails_SectionTitle_SignIn": "%1$s for at se venneaktivitet",
	"AppDetails_SectionTitle_OpenFriends": "Åbn venneliste",
	"AppDetails_SectionTitle_OfflineMode": "Offlinetilstand",
	"AppDetails_Broadcast_ViewOnWeb": "Vis i webbrowser",
	"AppDetails_Community_Tooltip1": "Denne sektion indeholder skærmbilleder, illustrationer, videoer, guider og meget mere fra fællesskabet.",
	"AppDetails_Community_Tooltip2": "Du kan synes godt om, dele, kommentere på eller rapportere indholdet.",
	"AppDetails_Community_Guide": "Fællesskabsguide",
	"AppDetails_Links_Store": "Butiksside",
	"AppDetails_Links_Community": "Fællesskabshub",
	"Bbcode_Originally_Posted_By": "Oprindeligt indsendt af",
	"AppDetails_InOfflineMode": "Steam er i øjeblikket i offlinetilstand. I offlinetilstand er mange af funktionerne i dit Steam-bibliotek, som eksempelvis Aktivitet og Venner, ikke tilgængelige. Gå online for at se dette indhold.",
	"AppDetails_GoOnline": "Gå online",
	"AppDetails_PartnerEventFailedLoad": "Kunne ikke indlæse denne begivenhed",
	"GameAction_Stop": "Stop",
	"GameAction_Cancel": "Annuller",
	"GameAction_Install": "Installer",
	"GameAction_Uninstall": "Afinstaller",
	"GameAction_Play": "Spil",
	"GameAction_PlayMusic": "Afspil album",
	"GameAction_Launch": "Start",
	"GameAction_PreLoad": "Forudindlæs",
	"GameAction_Update": "Opdater",
	"GameAction_Download": "Download",
	"GameAction_Resume": "Genoptag",
	"GameAction_Pause": "Pause",
	"GameAction_BorrowApp": "Lån",
	"GameAction_PurchaseApp": "Køb",
	"GameAction_GameProperties": "Egenskaber...",
	"GameAction_AddToFavorites": "Tilføj til favoritter",
	"GameAction_RemoveFromFavorites": "Fjern fra favoritter",
	"GameAction_AddToHidden": "Skjul dette spil",
	"GameAction_RemoveFromHidden": "Fjern fra skjulte",
	"GameAction_RemoveGameLicense": "Fjern fra konto",
	"GameAction_AddToFamilyGames": "Tilføj til familiespil",
	"GameAction_RemoveFromFamilyGames": "Fjern fra familiespil",
	"GameAction_RemoveShortcut": "Fjern ikke-Steam-spil fra dit bibliotek",
	"GameAction_AddToCollection": "Tilføj til",
	"GameAction_RemoveFromCollection": "Fjern fra",
	"GameAction_CreateDesktopShortcut": "Tilføj skrivebordsgenveje",
	"GameAction_BackUpFiles": "Sikkerhedskopier spilfiler...",
	"GameAction_Stream": "Stream",
	"GameAction_Connect": "Tilslut",
	"GameAction_SetCustomArtwork": "Angiv tilpasset illustration",
	"GameAction_ClearCustomArtwork": "Ryd tilpasset illustration",
	"GameAction_ViewCDKeys": "CD-nøgler",
	"GameAction_ControllerConfiguration": "Controller-konfiguration",
	"GameAction_Launching": "Starter",
	"GameAction_RemoveAppFromCollection": "TRÆK HERTIL for at fjerne %1$s fra samlingen \"%2$s\"",
	"GameAction_RemoveAppFromMultipleCollections": "TRÆK HERTIL for at fjerne %1$s fra disse samlinger",
	"GameAction_RemoveMultipleAppsFromCollection": "TRÆK HERTIL for at fjerne disse apps fra \"%1$s\"",
	"GameAction_RemoveMultipleAppsFromMultipleCollections": "TRÆK HERTIL for at fjerne disse apps fra disse samlinger",
	"GameAction_NavigateToAllCollectionsWithDrag": "TRÆK og HOLD HER for at se alle samlinger",
	"GameAction_AddToCollectionOption_NewCollection": "Ny samling...",
	"GameAction_NewCollectionDialogTitle": "Ny samling",
	"GameAction_Manage": "Administrer",
	"GameAction_Favorite": "Tilføj til favoritter",
	"GameAction_UnFavorite": "Er i favoritter",
	"GameAction_ViewDetails": "Vis flere oplysninger",
	"GameAction_BrowseLocalFiles": "Gennemse lokale filer",
	"GameAction_ViewDetails_Collapse": "Vis færre oplysninger",
	"GameAction_ViewDetails_ScrollUp": "Rul til toppen",
	"GameActionPlural_Install": "Installer valgte",
	"GameActionPlural_Uninstall": "Afinstaller valgte",
	"GameActionPlural_PreLoad": "Forudindlæs valgte",
	"GameActionPlural_Update": "Opdater valgte",
	"GameActionPlural_Download": "Download valgte",
	"GameActionPlural_Resume": "Genoptag valgte",
	"GameActionPlural_AddToFavorites": "Tilføj valgte til favoritter",
	"GameActionPlural_RemoveFromFavorites": "Fjern valgte fra favoritter",
	"GameActionPlural_AddToHidden": "Skjul valgte spil",
	"GameActionPlural_RemoveFromHidden": "Fjern valgte fra skjulte",
	"GameActionPlural_AddToFamilyGames": "Tilføj valgte til familiespil",
	"GameActionPlural_RemoveFromFamilyGames": "Fjern valgte fra familiespil",
	"GameActionPlural_RemoveShortcut": "Fjern valgte ikke-Steam-spil fra dit bibliotek",
	"GameActionPlural_AddToCollection": "Tilføj valgte til",
	"GameActionPlural_RemoveFromCollection": "Fjern valgte fra",
	"GameActionPlural_CreateDesktopShortcut": "Tilføj skrivebordsgenveje",
	"GameActionPlural_BackUpFiles": "Sikkerhedskopier spilfiler...",
	"PrePurchase_Preload_Title": "%1$s kan nu forudindlæses",
	"PrePurchase_Preload_Desc": "Download spilfilerne nu, så du kan kan spille, så snart spillet er låst op!",
	"PrePurchase_PreloadComplete_Title": "%1$s er blevet forudindlæst",
	"PrePurchase_PreloadComplete_Desc": "Du kan spille, så snart spillet er blevet låst op!",
	"PrePurchase_Install_Title": "%1$s kan installeres og spilles nu",
	"PrePurchase_Install_Desc": "Installer nu for at spille!",
	"PrePurchase_PlayNow_Title": "%1$s kan spilles nu",
	"PrePurchase_PlayNow_Desc": "Spil nu!",
	"DisplayStatus_Launching": "Starter",
	"DisplayStatus_Uninstalling": "Afinstallerer",
	"DisplayStatus_Installing": "Installerer",
	"DisplayStatus_Running": "Kører",
	"DisplayStatus_Validating": "Validerer",
	"DisplayStatus_Updating": "Opdaterer",
	"DisplayStatus_Downloading": "Downloader",
	"DisplayStatus_Synchronizing": "Synkroniserer med Steam Cloud",
	"DisplayStatus_ReadyToInstall": "Klar til installering",
	"DisplayStatus_ReadyToPreload": "Klar til forudindlæsning",
	"DisplayStatus_ReadyToLaunch": "Klar til at starte",
	"DisplayStatus_RegionRestricted": "Utilgængelig i nuværende region",
	"DisplayStatus_PresaleOnly": "Dette emne er ikke tilgængeligt endnu",
	"DisplayStatus_InvalidPlatform": "Til",
	"DisplayStatus_PreloadComplete": "Forudindlæsning gennemført",
	"DisplayStatus_BorrowerLocked": "Dette bibliotek er i øjeblikket ikke tilgængeligt til familiedeling",
	"DisplayStatus_UpdatePaused": "Opdatering sat på pause",
	"DisplayStatus_UpdateQueued": "Opdatering sat i kø",
	"DisplayStatus_UpdateRequired": "Opdatering påkrævet",
	"DisplayStatus_UpdateDisabled": "Opdateringer er slået fra, fordi Steam er i offlinetilstand. Gå online for at gøre opdateringen af dette spil færdig.",
	"DisplayStatus_DownloadPaused": "Download sat på pause",
	"DisplayStatus_DownloadQueued": "Download sat i kø",
	"DisplayStatus_DownloadRequired": "Download påkrævet",
	"DisplayStatus_DownloadDisabled": "Downloads er slået fra, fordi Steam er i offlinetilstand. Gå online for at færdiggøre download af dette spil.",
	"DisplayStatus_LicensePending": "Dit køb er endnu ikke gennemført.",
	"DisplayStatus_LicenseExpired": "Licens udløbet",
	"DisplayStatus_AvailForFree": "Gratis",
	"DisplayStatus_AvailToBorrow": "Kan lånes",
	"DisplayStatus_AvailGuestPass": "Gæstepas tilgængeligt",
	"DisplayStatus_Purchase": "Kan købes",
	"DisplayStatus_Preallocating": "Forudallokerer",
	"DisplayStatus_Committing": "Gennemfører",
	"DisplayStatus_Verifying": "Bekræfter",
	"DisplayStatus_Unpacking": "Pakker ud",
	"DisplayStatus_Compact_Launching": "Starter",
	"DisplayStatus_Compact_Uninstalling": "Afinstallerer",
	"DisplayStatus_Compact_Installing": "Installerer",
	"DisplayStatus_Compact_Running": "Kører",
	"DisplayStatus_Compact_Validating": "Validerer",
	"DisplayStatus_Compact_Updating": "Opdaterer",
	"DisplayStatus_Compact_Downloading": "Downloader",
	"DisplayStatus_Compact_Synchronizing": "Synkroniserer med Steam Cloud",
	"DisplayStatus_Compact_ReadyToInstall": "Klar til installering",
	"DisplayStatus_Compact_ReadyToPreload": "Klar til forudindlæsning",
	"DisplayStatus_Compact_ReadyToLaunch": "Klar til start",
	"DisplayStatus_Compact_RegionRestricted": "Utilgængelig i denne region",
	"DisplayStatus_Compact_PresaleOnly": "Spillet er ikke udgivet endnu",
	"DisplayStatus_Compact_InvalidPlatform": "Til",
	"DisplayStatus_Compact_ParentalBlocked": "Blokeret af Steam-familievisning",
	"DisplayStatus_Compact_PreloadComplete": "Forudindlæsning gennemført",
	"DisplayStatus_Compact_BorrowerLocked": "Familiedeling ikke tilgængelig",
	"DisplayStatus_Compact_UpdatePaused": "Opdatering sat på pause",
	"DisplayStatus_Compact_UpdateQueued": "Opdatering sat i kø",
	"DisplayStatus_Compact_UpdateRequired": "Opdatering krævet",
	"DisplayStatus_Compact_UpdateDisabled": "Opdatering slået fra i offlinetilstand.",
	"DisplayStatus_Compact_DownloadPaused": "Download sat på pause",
	"DisplayStatus_Compact_DownloadQueued": "Download sat i kø",
	"DisplayStatus_Compact_DownloadRequired": "Download påkrævet",
	"DisplayStatus_Compact_DownloadDisabled": "Download slået fra i offlinetilstand",
	"DisplayStatus_Compact_LicensePending": "Gennemfør køb",
	"DisplayStatus_Compact_LicenseExpired": "Licens udløbet",
	"DisplayStatus_Compact_AvailForFree": "Gratis tilgængelig",
	"DisplayStatus_Compact_AvailToBorrow": "Kan lånes",
	"DisplayStatus_Compact_AvailGuestPass": "Gæstepas tilgængeligt",
	"DisplayStatus_Compact_Purchase": "Kan købes",
	"DisplayStatus_ReleaseDate": "Kommer %1$s",
	"DisplayStatus_CustomReleaseDate": "Planlagt udgivelsesdato: %1$s",
	"Downloads_State_Bytes_Of_Bytes": "%1$s af %2$s",
	"Downloads_State_None": "",
	"Downloads_State_Reconfiguring": "Starter download",
	"Downloads_State_Validating": "Validerer filer",
	"Downloads_State_AddingFiles": "Kopierer filer",
	"Downloads_State_Preallocating": "Reserverer plads",
	"Downloads_State_Downloading": "",
	"Downloads_State_Staging": "",
	"Downloads_State_Committing": "Færdiggør",
	"Downloads_State_Verifying": "Bekræfter download",
	"Downloads_State_Stopping": "Stopper download",
	"Downloads_State_Running": "",
	"Downloads_State_SecondsRemaining": "%1$s sek. tilbage",
	"Downloads_State_MinutesRemaining": "%1$s min. tilbage",
	"Downloads_State_Calculating": "Beregner...",
	"LaunchApp_Action_UpdatingAppInfo": "Tjekker konfiguration",
	"LaunchApp_Action_ShowEula": "Viser slutbrugerlicensaftalen",
	"LaunchApp_Action_DownloadingDepots": "Downloader indhold (%1$s%)",
	"LaunchApp_Action_DownloadingWorkshop": "Downloader værksted (%1$s%)",
	"LaunchApp_Action_UpdatingDRM": "Opdaterer eksekverbar",
	"LaunchApp_Action_GettingLegacyKey": "Opdaterer produktkode",
	"LaunchApp_Action_RunningInstallScript": "Kører installationsscript (%1$s)",
	"LaunchApp_Action_SynchronizingCloud": "Synkroniserer sky",
	"LaunchApp_Action_VerifyingFiles": "Bekræfter eksekverbar",
	"LaunchApp_Action_CreatingProcess": "Starter eksekverbar",
	"LaunchApp_Action_WaitingGameWindow": "Starter eksekverbar",
	"LaunchApp_Action_DelayLaunch": "Udskyder opstart (%1$s%)",
	"AppDetails_TitleUpdatedSincePlayed": "Dette spil er blevet opdateret, siden du spillede det sidst",
	"AppDetails_TitleUpdatedSincePlayedLink": "Læs om ændringerne",
	"AppDetails_BadgeLevel": "Level %1$s, XP: %2$s",
	"AppDetails_UnearnedBadgeXP": "%1$s XP",
	"AppDetails_BadgeLevelNoXP": "Level %1$s",
	"AppDetails_Review_ViewOrEdit": "Rediger min anmeldelse",
	"AppDetails_Review_YourReview": "Min anmeldelse",
	"AppDetails_Review_Ignore_Stale_Reviews": "Mind mig ikke om at opdatere denne anmeldelse.",
	"AppDetails_Review_Unignore_Stale_Reviews": "Tillad fremhævninger fra gamle anmeldelser for dette spil.",
	"AppDetails_Review_RecommendGame": "Vil du anbefale dette spil?",
	"AppDetails_Review_RecommendSoftware": "Vil du anbefale denne software?",
	"AppDetails_Review_WriteReview": "Skriv en anmeldelse af %1$s",
	"AppDetails_Review_PlayedForTime": "Du har spillet i %1$s",
	"AppDetails_Review_PlayedForTime_Software": "Du har brugt denne titel i %1$s",
	"AppDetails_Review_RecommendGameButton_Yes": "Ja",
	"AppDetails_Review_RecommendGameButton_No": "Nej",
	"AppDetails_Review_PlaytimeAtReview": "%1$s spillet på anmeldelsestidspunktet",
	"AppDetails_Review_PlaytimeAtReview_Software": "Forbrug på anmeldelsestidspunktet: %1$s",
	"AppDetails_Review_NotRecommended": "Kan ikke anbefales",
	"AppDetails_Review_Recommended": "Kan anbefales",
	"AppDetails_Review_AdditionalPlaytime": "Du har spillet i %1$s, siden du skrev denne anmeldelse.",
	"AppDetails_Review_AdditionalPlaytime_Software": "Du har brugt dette i %1$s, siden du skrev denne anmeldelse.",
	"AppDetails_Review_ChangedYourMind": "Har du skiftet mening?",
	"AppDetails_Review_IHaveNotChangedMyMind": "Nej, det har jeg ikke",
	"AppDetails_Review_UpVotes": "Synes om:",
	"AppDetails_Review_Comments": "Kommentarer:",
	"AppDetails_Review_ViewAll": "Se alle anmeldelser",
	"AppDetails_Review_ViewAllByFriend": "Se alle anmeldelser fra %1$s",
	"OverflowBox_Action_Collapse": "Se færre",
	"OverflowBox_Action_Expand": "Læs mere",
	"OverflowBox_More": "(%1$s flere)",
	"AppDetails_FriendsInGameNow": "%1$s ven spiller lige nu",
	"AppDetails_FriendsInGameNow_Plural": "%1$s venner spiller lige nu",
	"AppDetails_FriendsPlayedRecently": "%1$s ven har spillet for nylig",
	"AppDetails_FriendsPlayedRecently_Plural": "%1$s venner har spillet for nylig",
	"AppDetails_FriendsPlayedRecentlyExpand": "Vis alle spillere, som har spillet dette spil for nylig",
	"AppDetails_FriendsPlayed": "%1$s ven har spillet det før",
	"AppDetails_FriendsPlayed_Plural": "%1$s venner har spillet det før",
	"AppDetails_FriendsPlayedExpand": "Vis alle spillere, som har spillet dette spil før",
	"AppDetails_FriendsMore": "(%1$s flere)",
	"AppDetails_FriendsLess": "Vis færre",
	"AppDetails_FriendsWishlisted": "%1$s ven har %2$s på sin ønskeliste",
	"AppDetails_FriendsWishlisted_Plural": "%1$s venner har %2$s på deres ønskeliste",
	"AppDetails_FriendsWishlistExpand": "Vis alle venner, som har det på deres ønskeliste",
	"AppDetails_Friends_ViewAll": "Vis alle venner, der spiller",
	"AppDetails_GameInfo": "Spiloplysninger",
	"AppDetails_Publisher": "Udgiver:",
	"AppDetails_Developer": "Udvikler:",
	"AppDetails_Franchise": "Franchise:",
	"AppDetails_ReleaseDate": "Udgivelsesdato:",
	"AppDetails_LastUpdate": "Sidst opdateret lokalt:",
	"AppDetails_OriginalReleaseDate": "Oprindelig udgivelsesdato:",
	"AppDetails_Feature_SinglePlayer": "Singleplayer",
	"AppDetails_Feature_MultiPlayer": "Multiplayer",
	"AppDetails_Feature_CoOp": "Samarbejdsspil",
	"AppDetails_Feature_SteamAchievements": "Præstationer",
	"AppDetails_Feature_SteamCloud": "Cloud-understøttelse",
	"AppDetails_Feature_FullController": "Fuld controller-understøttelse",
	"AppDetails_Feature_PartialController": "Delvis controller-understøttelse",
	"AppDetails_Feature_SteamWorkshop": "Steam-værksted",
	"AppDetails_Feature_VRSupport": "VR-understøttelse",
	"AppDetails_ViewAllUpdates": "Vis alle opdateringer",
	"AppDetails_ViewAllAchievements": "Vis mine præstationer",
	"AppDetails_ViewGlobalAchievements": "Vis globale præstationsstatistikker",
	"AppDetails_PlayerUnlockedPercent": "Du har låst op for %1$s/%2$s",
	"AppDetails_PlayerUnlockedPercentAll": "Du har låst op for alle præstationer! %1$s/%2$s",
	"AppDetails_Achievements_Unlocked": "Låst op d. %1$s",
	"AppDetails_PctUnlocked": "%1$s% af spillere har denne præstation",
	"AppDetails_GlobalCompare": "Det er mere end %1$s% af spillere",
	"AppDetails_ViewTradingCards": "Vis mine byttekort",
	"AppDetails_Achievements_Locked": "Låste præstationer",
	"AppDetails_TradingCardsLeft": "1 byttekort mangler at blive samlet",
	"AppDetails_TradingCardsLeft_Plural": "%1$s byttekort mangler at blive samlet",
	"AppDetails_TradingCardsLevelUp": "Du har nok byttekort til at stige i level!",
	"AppDetails_TradingCardsMaxed": "Tillykke! Dit emblem har det højeste level!",
	"AppDetails_TradingCards_Tooltip1": "Byttekort optjenes, efterhånden som du spiller. Du kan bytte med venner (eller Steam-fællesskabet) og få de kort, du mangler.",
	"AppDetails_TradingCards_Tooltip2": "Saml et komplet sæt af byttekort, og smed dem til emblemer. Emblemer øger dit Steam-level og låser op for fordele på din profil og konto.",
	"AppDetails_BrowseWorkshop": "Gennemse værkstedet",
	"AppDetails_ViewSubscribedItems": "Vis mine abonnementer",
	"AppDetails_ViewItemInWorkshop": "Vis i værkstedet",
	"AppDetails_MoreItemsFrom": "Vis emner fra denne skaber",
	"AppDetails_SubscribeToItem": "Abonner",
	"AppDetails_UnsubscribeFromItem": "Opsig abonnement",
	"AppDetails_Subscribed": "Abonneret",
	"AppDetails_ViewMoreInWorkshop": "Vis mere i værkstedet",
	"AppDetails_WorkshopSubCount": "Du har (%1$s) værkstedsabonnementer.",
	"AppDetails_WorkshopVisit": "Besøg dette værksted",
	"AppDetails_WorkshopLearnMore": "Læs mere",
	"AppDetails_WorkshopFeaturedHeader": "Emne, der trender nu",
	"AppDetails_WorkshopFeaturedItem": "Populært emne",
	"AppDetails_WorkshopFeaturedMoreInfo": "Læs mere",
	"AppDetails_WorkshopFeaturedHideItem": "Skjul dette emne",
	"AppDetails_WorkshopFileSize": "Filstørrelse: %1$s",
	"AppDetails_WorkshopFileSizeBytes": "%1$s bytes",
	"AppDetails_WorkshopFileSizeKb": "%1$s KB",
	"AppDetails_WorkshopFileSizeMb": "%1$s MB",
	"AppDetails_WorkshopFileSizeGb": "%1$s GB",
	"AppDetails_WorkshopLastUpdated": "Sidst opdateret: %1$s",
	"DLCStatus_installed": "Installeret",
	"DLCStatus_notinstalled": "Ikke installeret",
	"DLCStatus_downloading": "Downloader",
	"DLC_DateAdded": "Tilføjet: %1$s",
	"AppDetails_ManageDLC": "Administrer mine %1$s DLC'er",
	"AppDetails_ManageMyDLC": "Administrer mit DLC",
	"AppDetails_ViewStoreDLC": "Vis DLC i butikken",
	"AppDetails_DLCSpotlight": "Nyligt erhvervet DLC er blevet tilføjet. Det bliver installeret sammen med spillet. Administrer dit DLC %1$s.",
	"AppDetails_DLCSpotlight_Installed": "Nyligt erhvervet DLC er automatisk blevet installeret. Administrer dit DLC %1$s.",
	"AppDetails_DLCSpotlight_here": "her",
	"ManageDLC_Title": "Administrer DLC",
	"ManageDLC_Column_Name": "Navn",
	"ManageDLC_Column_DateAdded": "Tilføjelsesdato",
	"ManageDLC_Column_Enabled": "Slået til",
	"ManageDLC_Column_Installed": "Installeret",
	"ManageDLC_Search": "Søg...",
	"ManageDLC_Installed": "%1$s/%2$s installeret",
	"ManageDLC_ViewMore": "Vis flere i butikken",
	"ManageDLC_NoResults": "Ingen resultater, der matcher \"%1$s\"",
	"AppDetails_ViewBadgePage": "Vis emblemside",
	"AppDetails_VisitTradeForum": "Besøg bytteforummet",
	"AppDetails_BuyCards": "Køb manglende kort på markedet",
	"AppDetails_SellCards": "Sælg disse kort på markedet",
	"AppDetails_SearchCard": "Vis dette kort på markedet",
	"AppDetails_ShowFriendsList": "Vis venneliste",
	"AppDetails_ViewFriendsWhoPlay": "Vis venner, der spiller",
	"AppDetails_Link_Discussions": "Diskussioner",
	"AppDetails_Link_FindGroups": "Find grupper",
	"AppDetails_Link_GameHub": "Fællesskabshub",
	"AppDetails_Link_Guides": "Guider",
	"AppDetails_Link_Store": "Butiksside",
	"AppDetails_Link_Support": "Support",
	"AppDetails_Link_Workshop": "Værksted",
	"AppDetails_Link_Market": "Marked",
	"AppDetails_Link_Controller": "Controller-konfiguration",
	"AppDetails_SocialMediaLink": "%1$s på %2$s",
	"AppDetails_SocialMediaType_4": "Twitter",
	"AppDetails_SocialMediaType_5": "Twitch",
	"AppDetails_SocialMediaType_6": "YouTube",
	"AppDetails_SocialMediaType_7": "Facebook",
	"AppDetails_Screenshot": "Skærmbillede",
	"AppDetails_Screenshot_Caption": "Billedtekst: %1$s",
	"AppDetails_Screenshot_Date": "Dato: %1$s",
	"AppDetails_Screenshot_Dimensions": "Dimensioner: %1$s x %2$s pixels",
	"AppDetails_Screenshot_Uploaded": "Uploadet: %1$s kl. %2$s",
	"AppDetails_OpenScreenshotUploader": "Åbn skærmbilleduploader",
	"AppDetails_ViewUploadedScreenshots": "Vis uploadede skærmbilleder",
	"AppDetails_ManageMyScreenshot": "Administrer mit skærmbillede",
	"AppDetails_ManageMyScreenshot_Plural": "Administrer mine %1$s skærmbilleder",
	"AppDetails_HowToScreenshot": "Du kan tage skærmbilleder ved at trykke på %1$s i spillet.",
	"AppDetails_ChangeMyScreenshotKey": "Rediger min skærmbilledtast",
	"AppDetails_NoScreenshots": "Du har ikke taget nogen skærmbilleder endnu",
	"AppDetails_Screenshot_SpoilerAlert": "Potentielle spoilere: Hold musen over billedet for at afsløre.",
	"AppDetails_Artwork": "Illustration",
	"AppDetails_Video": "Video",
	"AppDetails_CommunityItem": "Fællesskabsindhold",
	"AppDetails_CommunityFeed_OutOfContent": "Intet yderligere indhold",
	"AppDetails_CommunityFeed_Inappropriate": "Indholdet er muligvis ikke egnet for alle",
	"AppDetails_CommunityFeed_ViewContent": "Vis indhold",
	"AppDetails_CommunityFeed_EditPreferences": "Rediger præferencer",
	"AppDetails_CommunityFeed_LoadCommunity": "Indlæs fællesskabsindhold",
	"AppBox_NewToLibrary": "Biblioteksnyt",
	"AppBox_ComingSoon": "Kommer snart",
	"AppBox_NewToLibrary_Short": "Nyt",
	"AppBox_ComingSoon_Short": "Snart",
	"AppBox_PlayTimeHeader": "Tid spillet",
	"AppBox_RecentPlayTime_Hours": "Sidste to uger: %1$s timer",
	"AppBox_RecentPlayTime_Minutes": "Sidste to uger: %1$s min.",
	"AppBox_TotalPlayTime_Hours": "I alt: %1$s timer",
	"AppBox_TotalPlayTime_Minutes": "I alt: %1$s min.",
	"AppActivity_Achieved": " opnåede",
	"AppActivity_PostedScreenshot": " delte et skærmbillede",
	"AppActivity_PostedScreenshot_Plural": " delte %1$s skærmbilleder",
	"AppActivity_PostedVideo": " delte en video",
	"AppActivity_PostedVideo_Plural": " delte %1$s videoer",
	"AppActivity_ReceivedNewGame": " ejer nu %1$s",
	"AppActivity_PlayedGameFirstTime": " spillede %1$s for første gang",
	"AppActivity_LaunchedSoftwareFirstTime": " startede %1$s for første gang",
	"AppActivity_AddedGameToWishlist": " tilføjede %1$s til sin %2$s.",
	"AppActivity_Wishlist": "ønskeliste",
	"AppActivity_Achieved_PlusMore": "… og %1$s andre præstationer",
	"AppActivity_Achieved_PlusMore_Label": "Vis alle %1$s's præstationer",
	"AppActivity_NoActivity": "Der er ikke nogen nylig aktivitet fra udviklerne af denne titel eller fra dine venner.",
	"AppActivity_UserStatus_Time": " slog en statusopdatering op kl. %1$s",
	"AppActivity_UserStatus": " slog en statusopdatering op",
	"AppActivity_StatusUpdate": "Slå en status op til dine venner",
	"AppActivity_StatusUpdate_Post": "Sig noget om dette spil til dine venner...",
	"AppActivity_StatusUpdate_Software_Post": "Sig noget om denne software til dine venner...",
	"AppActivity_Comment_Reply": "Tilføj et svar...",
	"AppActivity_PostStatusUpdate": "Slå op",
	"AppActivity_FetchMore": "Indlæs mere aktivitet",
	"AppActivity_EndofFeed": "Aktivitet slut",
	"AppActivity_DeleteUserNews": "Klik for at slette dette opslag.",
	"AppActivity_ConfirmDeleteTitle": "Slet statusopslag",
	"AppActivity_ConfirmDeleteTitle_Desc": "Er du sikker på, at du vil slette dette opslag? Dette kan ikke fortrydes.",
	"AppActivity_RecommendedGame": " anmeldte dette spil",
	"AppActivity_RecommendedGame_ReadMore": "Læs mere",
	"AppActivity_RatingDetails": "%1$s personer opvurderede dette",
	"AppActivity_RatingDetails_1Other": "1 person opvurderede dette, %1$s",
	"AppActivity_RatingDetails_2Others": "%1$s personer opvurderede dette, deriblandt %2$s og %3$s",
	"AppActivity_RatingDetails_User": "Du har stemt dette op",
	"AppActivity_RatingDetails_User_1Other": "%1$s personer opvurderede dette, deriblandt dig og %2$s",
	"AppActivity_RatingDetails_User_2Others": "%1$s personer opvurderede dette, deriblandt dig, %2$s og %3$s",
	"AppActivity_RatingDetails_PublishedFile": "%1$s synes godt om",
	"AppActivity_RateUp": "Synes om",
	"AppActivity_ConfirmDeleteCommentTitle": "Slet kommentar",
	"AppActivity_ConfirmDeleteCommentTitle_Desc": "Er du sikker på, at du vil slette denne kommentar? Dette kan ikke fortrydes.",
	"AppActivity_MakeCommentsVisible": "Vis tidligere kommentarer (%1$s)",
	"AppActivity_Settings": "Indstillinger",
	"AppActivity_ViewComments": "Vis kommentarer",
	"AppActivity_AddComments": "Tilføj kommentar",
	"AppActivity_ContributeComments": "Kommenter dette",
	"AppActivity_SteamTradingCards_EarnedTradingCards": " optjente byttekort",
	"AppActivity_SteamTradingCards_EarnedTradingCard": " optjente et byttekort",
	"AppActivity_SteamTradingCards_EarnedBoosterPack": " optjente en boosterpakke",
	"AppActivity_SteamTradingCards_BadgeCrafted": " smedede et emblem",
	"AppActivity_ViewLatestNews": "Vis de seneste nyheder",
	"AppActivity_EventType_GameUpdate": "Spilopdatering",
	"AppSpotlight_PostGameSummary": "Efterspilsopsumering",
	"AppDetails_Shortcut_Explanation": "Visse detaljer om %1$s er utilgængelige, fordi det ikke er en Steam-modifikation eller -genvej. Steam vil stadig stå for at starte spillet for dig, og i de fleste tilfælde vil Steam-overlayet være tilgængeligt.",
	"AppDetails_Takeover_Update_Header": "Hvis du missede det",
	"AppDetails_Takeover_Update_ViewAll": "Se alle %1$s spilopdateringer",
	"AppDetails_Takeover_Update_ReadMore": "Læs mere",
	"AppDetails_Takeover_DLC_Header": "Nye emner tilføjet",
	"AppDetails_Takeover_DLC_ViewInStore": "Vis %1$s i butikken",
	"AppDetails_Takeover_Achievements_Header": "Du har spillet i %2$s og har en ny præstation...",
	"AppDetails_Takeover_Achievements_Header_Plural": "Du har spillet i %2$s og har nye præstationer...",
	"AppDetails_Takeover_TradingCards_Header": "Du har spillet i %2$s og har fået et nyt emne...",
	"AppDetails_Takeover_TradingCards_Header_Plural": "Du har spillet i %2$s og har fået nye emner...",
	"AppDetails_ViewMyInventory": "Vis mit inventar",
	"AppDetails_ViewInMyInventory": "Vis i mit inventar",
	"AppDetails_Soundtrack_TotalTracks": "%1$s numre",
	"AppDetails_Soundtrack_DiscNumber": "Disk %1$s",
	"AppDetails_Soundtrack_TrackCount": "%1$s numre",
	"AppDetails_Soundtrack_PlayAlbum": "Afspil album",
	"AppDetails_Soundtrack_DownloadAlbum": "Download album",
	"AppDetails_Soundtrack_AddToQueue": "Føj til kø",
	"AppDetails_Soundtrack_AddToPlaylist": "Føj til playliste",
	"AppDetails_Soundtrack_ViewOnDisk": "Gennemse lokale filer",
	"AppDetails_Soundtrack_ViewAdditionalArtwork": "Vis flere illustrationer",
	"AppDetails_Soundtrack_ViewStorePage": "Vis butikssiden",
	"AppDetails_Soundtrack_Support": "Vis supportside",
	"AppDetails_Soundtrack_ParentAppLink": "Soundtrack til %1$s",
	"AppPortraitHover_DownloadStatusTitle": "Downloader",
	"AppPortraitHover_DownloadStatusTitle_Update": "Downloader opdatering",
	"AppPortraitHover_DaysSinceLastUpdate": "Opdateret for %1$s",
	"AppPortraitHover_FriendsPlaying": "%1$s venner spiller",
	"MajorUpdate_ViewDetails": "Vis detaljer",
	"MajorUpdate_NextUpdate": "Næste opdatering",
	"MajorUpdate_PostTime": "Slået op for %1$s dage siden kl. %2$s:%3$s",
	"MajorUpdate_PostTimeToday": "Slået op i dag kl. %1$s:%2$s",
	"MajorUpdate_WatchNow": "Se på SteamTV",
	"MajorUpdate_Type0": "Stor opdatering",
	"MajorUpdate_Type1": "Livestream",
	"MajorUpdate_Type14": "Stor opdatering",
	"MajorUpdate_Context_RemoveThisUpdate": "Fjern denne opdatering",
	"MajorUpdate_Context_ShowMeFewerForApp": "Vis mindre fra %1$s",
	"MajorUpdate_Context_ShowMeMoreForApp": "Vis mere fra %1$s",
	"MajorUpdate_Context_ResetHiddenUpdates": "Vis alle opdateringer igen",
	"MajorUpdate_Context_WhyAmISeeingThis": "Hvorfor ser jeg dette?",
	"MajorUpdate_Context_WhyAmISeeingThis_Text": "Dette er en stor opdatering til et produkt i dit bibliotek med mere end 20 timers spilletid (placeholder).",
	"MajorUpdate_Context_WhyAmISeeingThis_Close": "Luk",
	"CustomArt_ErrorTitle": "Fejl",
	"CustomArt_BadFileType": "Din fil skal være i JPG- eller PNG-format.",
	"CustomArt_UnknownError": "Der opstod en fejl under opsætningen af dine illustrationer.",
	"CustomArt_SetCustomBackground": "Indstil tilpasset baggrund",
	"CustomArt_ClearCustomBackground": "Ryd tilpasset baggrund",
	"CustomArt_SetCustomLogo": "Indstil tilpasset logo",
	"CustomArt_ClearCustomLogo": "Ryd tilpasset logo",
	"CustomArt_EditLogoPosition": "Juster logoplacering",
	"CustomArt_ResetLogoPosition": "Nulstil logoplacering",
	"CustomArt_DoneEditingLogo": "Færdig",
	"AppDetails_LibraryInUse": "Bibliotek i brug af",
	"AppDetails_InSharedLibrary": "Fra biblioteket med",
	"FriendContextMenu_OpenFriends": "Åbn venner og chat",
	"FriendContextMenu_ViewProfile": "Vis profil",
	"Generic_ScrollToTop": "Rul til toppen",
	"Generic_ViewGameDetails": "Vis spil i bibliotek",
	"GameDetails_CollectionContext_GoTo": "Gå til samling",
	"GameDetails_CollectionContext_Remove": "Fjern fra samling",
	"ArtworkModal_ViewAll": "Vis alle skærmbilleder",
	"ArtworkModal_FileSize": "Filstørrelse",
	"ArtworkModal_Posted": "Slået op",
	"ArtworkModal_Size": "Størrelse",
	"ArtworkModal_CreatedBy": "Skabt af",
	"ArtworkModal_ScrollForMore": "Rul ned for at se kommentarer",
	"ArtworkModal_ScrollForDetails": "Rul ned for at få flere oplysninger",
	"CommunityItem_Menu_Report": "Rapportér",
	"ReportItem_Title": "Rapportér dette emne",
	"ReportItem_Description": "Beskriv venligst, hvordan dette emne overtræder Steams servicebetingelser. Inkluder venligst alle relevante oplysninger eller links. Indsendelse af denne rapport kan ikke fortrydes.",
	"ReportItem_Description_Line2": "Emner, som er blevet rapporteret, vil ikke længere blive vist på din biblioteksside.",
	"ReportItem_DMCA": "Hvis du ønsker at rapportere en krænkelse af ophavsretten og er indehaver af den relevante ophavsret, så fortsæt venligst til vores DMCA-ophavsretsklageformular %1$s",
	"ReportItem_DMCA_LinkText": "her",
	"ReportItem_Error": "Der var et problem med at indsende din anmodning til vores servere. Prøv igen senere.",
	"ReportItem_SubmitReport": "Indsend rapport",
	"RemoveFreeApp_Title": "Fjern fra din konto",
	"RemoveFreeApp_Description": "%1$s blev tilføjet til din konto med en gratis licens. Du kan fjerne appen fra din konto, så den ikke længere vises i dit Steam-bibliotek og på listen over spil, du ejer.",
	"RemoveFreeApp_Question": "Vil du fjerne %1$s fra din konto?",
	"RemoveFreeApp_Remove": "Fjern",
	"RemoveFreeApp_Removing": "Fjerner %1$s",
	"RemoveFreeApp_Error": "Der opstod en fejl under forsøg på at fjerne %1$s",
	"UninstallDialog_Title": "Afinstaller",
	"UninstallDialog_Uninstall": "Afinstaller",
	"UninstallDialog_ErrorMessage": "Kunne ikke afinstallere %1$s:",
	"UninstallDialog_Busy": "Fordi en anden installations-/afinstallationsproces er aktiv i øjeblikket. Vent, til processen er færdig.",
	"UninstallDialog_SecuROM": "Fordi afinstallation af denne applikation kræver en internetforbindelse.",
	"UninstallDialog_UnknownError": "Fordi der opstod en uventet fejl under afinstallation af denne applikation.",
	"UninstallDialog_AppUpdateError": "Afinstallationsfejl - %1$s",
	"UninstallDialog_Confirmation_Single": "Vil du afinstallere %1$s på denne computer? Det vil stadig være i dit spilbibliotek, men for at spille det skal du først downloade alt indholdet igen.",
	"UninstallDialog_Confirmation_Multiple": "Vil du afinstallere de valgte titler på din computer? Titlerne vil stadig være i dit spilbibliotek, men for at spille dem skal du først downloade alt indholdet igen.",
	"UninstallingDialog_Uninstalling": "Afinstallerer",
	"UninstallingDialog_UninstallingApp": "Afinstallerer %1$s",
	"UninstallingDialog_WaitingForPassword": "Venter på adgangskode",
	"Showcase_AddNewShowcase": "Tilføj hylde",
	"Showcase_DeleteShowcase": "Slet denne hylde",
	"Showcase_SelectCategory": "Vælg en hylde",
	"Showcase_EmptyShowcaseHint": "Vælg, hvad der skal vises på denne hylde. Du kan også redigere eller slette hylden herfra!",
	"Showcase_GoToCollection": "Gå til samling",
	"Showcase_GoToAllCollections": "Gå til alle samlinger",
	"Showcase_AllYourGames": "Alle spil",
	"Showcase_AllCollections": "Samlingsvisning",
	"Showcase_RecentGames": "Seneste spil",
	"Showcase_DoneReordering": "Færdig",
	"Playtime_TwoWeeks_Minutes": "%1$s min. spillet for nylig",
	"Playtime_TwoWeeks_Hours": "%1$s timer spillet for nylig",
	"Playtime_Total_Minutes": "%1$s minutter spillet i alt",
	"Playtime_Total_Hours": "%1$s timer spillet i alt",
	"Playtime_Minutes": "%1$s min.",
	"Playtime_Hours": "%1$s timer",
	"Playtime_Recently": "%1$s spillet for nyligt",
	"Playtime_Total": "%1$s spillet i alt",
	"GameList_Search_NoResults_Title": "Kan du ikke finde det, du leder efter?",
	"GameList_Search_NoResults_Link": "Søg i Steam-butikken",
	"StreamingClient_Select_ThisMachine": "Denne maskine",
	"StreamingClient_Select_RemotePlayPhone": "Mobiltelefoner",
	"StreamingClient_Select_RemotePlayTablet": "Tablets",
	"StreamingClient_Select_RemotePlayMobile": "Mobilenheder",
	"StreamingClient_Select_RemotePlayTV": "TV'er",
	"StreamingClient_Select_RemotePlayTVPhone": "TV'er og mobiltelefoner",
	"StreamingClient_Select_RemotePlayTVTablet": "TV'er og tablets",
	"StreamingClient_Select_RemotePlayTVMobile": "TV'er og mobilenheder",
	"Beta_BetaTag": "BETA",
	"Beta_Changelist": "Ændringsliste",
	"Beta_GiveFeedback": "Giv feedback",
	"ContextMenu_SaveScreenshot": "Gem skærmbillede som...",
	"ContextMenu_BrowseScreenshot": "Gå til skærmbillede",
	"ContextMenu_ManageScreenshots": "Administrer skærmbilleder",
	"SteamChina_DurationControl_Init_1": "Healthy Gaming Advisory",
	"SteamChina_DurationControl_Init_2": "Boycott harmful games; reject game piracy.",
	"SteamChina_DurationControl_Init_3": "Exercise self-protection; avoid deception.",
	"SteamChina_DurationControl_Init_4": "Moderation promotes brain health; excess play is harmful to the body.",
	"SteamChina_DurationControl_Init_5": "Well-planned use of your time will lead to a healthy lifestyle.",
	"Steam_AppUpdateError_0": "ingen fejl",
	"Steam_AppUpdateError_1": "ukendt fejl",
	"Steam_AppUpdateError_2": "opdatering sat på pause",
	"Steam_AppUpdateError_3": "opdatering annulleret",
	"Steam_AppUpdateError_4": "opdatering afbrudt",
	"Steam_AppUpdateError_5": "ingen licenser",
	"Steam_AppUpdateError_6": "ingen internetforbindelse",
	"Steam_AppUpdateError_7": "forbindelsen udløb",
	"Steam_AppUpdateError_8": "indhold stadig krypteret",
	"Steam_AppUpdateError_9": "app-konfiguration utilgængelig",
	"Steam_AppUpdateError_10": "disklæsningsfejl",
	"Steam_AppUpdateError_11": "diskskrivningsfejl",
	"Steam_AppUpdateError_12": "ikke nok ledig diskplads",
	"Steam_AppUpdateError_13": "beskadigede indholdsfiler",
	"Steam_AppUpdateError_14": "venter på installationsdisk",
	"Steam_AppUpdateError_15": "ugyldig installationssti",
	"Steam_AppUpdateError_16": "app kører",
	"Steam_AppUpdateError_17": "mangler delt indhold",
	"Steam_AppUpdateError_18": "ikke installeret",
	"Steam_AppUpdateError_19": "opdatering påkrævet",
	"Steam_AppUpdateError_20": "optaget",
	"Steam_AppUpdateError_21": "indholdsservere er ikke tilgængelige",
	"Steam_AppUpdateError_22": "ugyldig app-konfiguration",
	"Steam_AppUpdateError_23": "ugyldig depotkonfiguration",
	"Steam_AppUpdateError_24": "manifest utilgængeligt",
	"Steam_AppUpdateError_25": "app ikke udgivet",
	"Steam_AppUpdateError_26": "regionsbegrænset",
	"Steam_AppUpdateError_27": "korrupt indholdscache",
	"Steam_AppUpdateError_28": "mangler eksekverbar fil",
	"Steam_AppUpdateError_29": "ugyldig platform",
	"Steam_AppUpdateError_30": "ikke-understøttet filsystem",
	"Steam_AppUpdateError_31": "beskadigede opdateringsfiler",
	"Steam_AppUpdateError_32": "downloads slået fra",
	"Steam_AppUpdateError_33": "delt bibliotek låst",
	"Steam_AppUpdateError_34": "køb under behandling",
	"Steam_AppUpdateError_35": "en anden session spiller",
	"Steam_AppUpdateError_36": "beskadiget download",
	"Steam_AppUpdateError_37": "beskadiget harddisk",
	"Steam_AppUpdateError_38": "manglende filrettigheder",
	"Steam_AppUpdateError_39": "indholdsfil låst",
	"Steam_AppUpdateError_40": "indhold utilgængeligt",
	"Steam_AppUpdateError_41": "den eksekverbare fil kræver et 64-bit operativsystem",
	"Steam_AppUpdateError_42": "manglende downloadede filer",
	"Steam_AppUpdateError_43": "ikke nok ledig diskplads til brugeren – kontrollér operativsystemets diskkvotaindstillinger",
	"Steam_AppUpdateError_44": "site-licensen er låst",
	"Steam_AppUpdateError_45": "blokeret af forældrekontrol",
	"Steam_AppUpdateError_46": "oprettelsesproces mislykkedes",
	"Steam_AppUpdateError_47": "Steam-klienten er forældet",
	"ShareDialog_Title": "Del",
	"ShareUploadScreenshot_Description": "Upload dette skærmbillede til din Steam-profil og aktivitetsfeed.",
	"ShareUploadScreenshot_AddCaption": "tilføj en billedtekst her",
	"ShareUploadScreenshot_CaptionHeader": "Billedtekst:",
	"ShareUploadScreenshot_TagSpoiler": "Tag som spoiler",
	"ShareUploadScreenshot_CloudUsage": "Vil bruge %1$s af %2$s lagerplads, som er tilbage i skyen (%3$s i alt)",
	"ShareUploadScreenshot_Uploading": "Uploader til Steam",
	"ShareUploadScreenshot_PermissionDenied": "Steam kunne ikke uploade dette skærmbillede. Du kan ikke uploade indhold, fordi der er en aktiv udelukkelse på din konto.",
	"ShareUploadScreenshot_UnexpectedError": "Steam kunne ikke uploade dette skærmbillede til Steam Cloud. Prøv igen.",
	"DeleteScreenshot_Title": "Slet skærmbillede",
	"DeleteScreenshot_Single": "Er du sikker på, at du permanent vil slette dette skærmbillede fra din harddisk?",
	"DeleteScreenshot_Failed": "Steam kunne ikke slette det valgte skærmbillede fra din harddisk.",
	"AppDetailsAchievement_Hidden": "Skjult præstation",
	"AppDetailsAchievement_HiddenDesc": "Bliv ved med at spille for at opdage denne præstation.",
	"Demo_SpotlightIntro": "Se hele spillet",
	"Demo_VisitStorePage": "Besøg butikssiden",
	"SteamReviewScore_9": "Overvældende positive",
	"SteamReviewScore_8": "Meget positive",
	"SteamReviewScore_7": "Positive",
	"SteamReviewScore_6": "Flest positive",
	"SteamReviewScore_5": "Blandede",
	"SteamReviewScore_4": "Flest negative",
	"SteamReviewScore_3": "Negative",
	"SteamReviewScore_2": "Meget negative",
	"SteamReviewScore_1": "Overvældende negative"
}
