{
	"Generic_Okay": "Tamam",
	"Generic_Close": "Kapat",
	"Generic_Open": "Aç",
	"Generic_GotIt": "Tamamdır!",
	"AppType_0": "Geçersiz",
	"AppType_1": "Oyunlar",
	"AppType_2": "Yazılımlar",
	"AppType_4": "Araçlar",
	"AppType_20": "DLC",
	"AppType_800": "Videolar",
	"AppType_2000": "Müzikler",
	"AppType_Singular_0": "Geçersiz",
	"AppType_Singular_1": "oyun",
	"AppType_Singular_2": "uygulama",
	"AppType_Singular_4": "araç",
	"AppType_Singular_20": "DLC",
	"AppType_Singular_800": "video",
	"AppType_Singular_2000": "müzik",
	"AppType_Singular_8000": "çizgi roman",
	"AppType_Singular_40000000": "kısayol",
	"FilterEdit_SavedFilters": "Kaydedilmiş Filtreler",
	"FilterEdit_FirstColumnHeader": "Filtre Türü",
	"FilterEdit_Customize": "Özelleştir",
	"FilterEdit_SearchModeHeader": "Gelişmiş Filtreler",
	"FilterEdit_CollectionModeHeader": "Koleksiyon Filtrelerini Düzenle",
	"CollectionEdit_CollectionNameField": "Koleksiyon Adı:",
	"CollectionEdit_RenameButton": "Koleksiyonu Yeniden Adlandır",
	"Collection_DynamicCollection": "Dinamik Koleksiyon",
	"FilterEdit_AdvancedTooltip": "Oyun listenizi türe, oyun özelliklerine, vb. kriterlere göre ayrıştırabileceğiniz gelişmiş filtreleme seçeneği.",
	"Collection_FreezeDynamicCollection": "Dondur",
	"Collection_FreezeDynamicCollection_ToolTip": "Mevcut oyun listesini dondurarak bu dinamik koleksiyonu sade bir koleksiyona dönüştürün.",
	"Collection_ResetDialogTitle": "Koleksiyonları sıfırla",
	"Collection_ResetConfirmation": "Bu koleksiyon listesini sıfırlayıp eski kategorilerinizi getirmek istediğinize emin misiniz?",
	"Collection_AfterResetSummary_NoCollections": "Sıfırladıktan sonra hiç koleksiyonunuz kalmayacaktır.",
	"Collection_AfterResetSummary_CountAndNames": "Sıfırladıktan sonra şu %1$s koleksiyona sahip olacaksınız: %2$s",
	"FilterEdit_SelectedFilters": "Seçili Filtreler",
	"FilterEdit_SaveCollectionNameInputPrompt": "Koleksiyon için bir ad girin",
	"FilterEdit_SaveOverwrite": "\"%1$s\" koleksiyonu zaten var. Üzerine yazılsın mı?",
	"FilterEdit_SaveCollection": "Koleksiyon Olarak Kaydet",
	"FilterEdit_SaveDynamicCollectionWithIcon": "%1$sDinamik Koleksiyon Olarak Kaydet",
	"FilterEdit_SaveDynamicCollectionNoIcon": "Dinamik Koleksiyon Olarak Kaydet",
	"FilterEdit_SaveCollectionVerbose": "Gelecekte tekrar kullanabilmek için bu aramayı bir koleksiyon olarak kaydedin. Bir koleksiyonu istediğiniz zaman düzenleyebilir, yeniden adlandırabilir, silebilir veya içindeki öğeleri çıkarabilir ya da yenilerini ekleyebilirsiniz.",
	"FilterEdit_SaveStandardCollectionButtonDesc": "Koleksiyon oluşturmak kütüphanenizi düzenlemenin basit bir yoludur. İstediğiniz ürünleri koleksiyona sürükleyin veya bir ürüne sağ tıklayarak mevcut bir koleksiyona ekleyin.",
	"FilterEdit_SaveDynamicCollectionButtonDesc": "Dinamik koleksiyonlar, kütüphaneniz büyüdükçe filtreleri kullanarak koleksiyonlar yaratır.",
	"FilterEdit_SelectCollectionType": "Koleksiyon türü seç",
	"FilterEdit_SelectCollectionTypeButtonCreate": "Koleksiyon Yarat",
	"FilterEdit_SelectCollectionTypeButtonCreateDynamic": "Dinamik Koleksiyon Yarat",
	"FilterEdit_RequiredField": "( GEREKLİ )",
	"FilterEdit_SearchPrompt": "İsme göre ara",
	"FilterEdit_ClearSearch": "Aramadan Çık",
	"FilterEdit_SearchResults": "Arama sonuçları",
	"FilterEdit_CollectionsHiddenPromptTitle": "Koleksiyonlar gizlendi",
	"FilterEdit_CollectionsHiddenPrompt": "Oyun listesi görünümünü, koleksiyonları görünür kılacak şekilde değiştirmek istiyor musunuz?",
	"FilterEdit_AcceptGameListViewChange": "Evet, koleksiyonları göster",
	"FilterEdit_RejectGameListViewChange": "Hayır, görünümü değiştirme",
	"AdvancedSearch_PaneTitle": "Türe göre ara",
	"AdvancedSearch_PlayerSection": "Oyuncular",
	"AdvancedSearch_HardwareSection": "Donanım desteği",
	"AdvancedSearch_FeatureSection": "Özellikler",
	"AdvancedSearch_StateSection": "Oynanabilme durumu",
	"AdvancedSearch_GenreSection": "Tür",
	"AdvancedSearch_StoreTagSection": "Mağaza etiketleri",
	"AdvancedSearch_StoreTagPrompt": "bir etiket girin",
	"FilterCategory_1": "Durum",
	"FilterCategory_Features": "ÖZELLİKLER",
	"FilterCategory_3": "Kategori",
	"FilterCategory_4": "Mağaza Etiketi",
	"FilterCategory_Type": "TİP",
	"FilterCategory_Genre": "TÜR",
	"FilterCategory_PlayState": "DURUM",
	"FilterElement_VR": "VR",
	"FilterElement_Tooltip_VR": "Sanal gerçeklik donanımı destekleyen oyunları dahil et.",
	"FilterElement_Installed": "Bilgisayarda yüklü",
	"FilterElement_Tooltip_Installed": "Bu bilgisayarda yüklü olan oyunları dahil et.",
	"FilterElement_ReadyToPlay": "Oynamaya hazır",
	"FilterElement_Tooltip_ReadyToPlay": "Bu bilgisayarda oynanabilen ya da farklı bir bilgisayardan yayınlanabilecek oyunları dahil et.",
	"FilterElement_PlayedPreviously": "Oynanmış",
	"FilterElement_Tooltip_PlayedPreviously": "Oynanmış oyunları dahil et.",
	"FilterElement_Unplayed": "Oynanmamış",
	"FilterElement_Tooltip_Unplayed": "Henüz oynamadığın oyunları dahil et.",
	"FilterElement_FullControllerSupport": "Kontrolcü (Tam)",
	"FilterElement_Tooltip_FullControllerSupport": "Tamamı kontrolcü ile oynanabilen oyunları dahil et.",
	"FilterElement_PartialControllerSupport": "Kontrolcü (Kısmî)",
	"FilterElement_Tooltip_PartialControllerSupport": "Kontrolcü ile oynanabilen ancak yükleme sırasında ya da kısıtlı etkileşimlerde klavye ve fare gerektirebilen oyunları dahil et.",
	"FilterElement_VRSupported": "VR Destekli",
	"FilterElement_TradingCards": "Koleksiyon kartları",
	"FilterElement_Tooltip_TradingCards": "Steam koleksiyon kartlarına sahip oyunları dahil et.",
	"FilterElement_Workshop": "Atölye",
	"FilterElement_Tooltip_Workshop": "Steam Atölyesi entegrasyonuna sahip oyunları dahil et.",
	"FilterElement_Achievements": "Başarımlar",
	"FilterElement_Tooltip_Achievements": "Steam başarımı kazandıran oyunları dahil et.",
	"FilterElement_SinglePlayer": "Tek kişilik",
	"FilterElement_Tooltip_SinglePlayer": "Tek kişilik oyun moduna sahip oyunları dahil et.",
	"FilterElement_MultiPlayer": "Çok oyunculu",
	"FilterElement_Tooltip_MultiPlayer": "Çok oyunculu moduna sahip oyunları dahil et.",
	"FilterElement_CoOp": "Eşli oyun",
	"FilterElement_Tooltip_CoOp": "Eşli oyun moduna sahip oyunları dahil et.",
	"FilterElement_GenreAction": "Aksiyon",
	"FilterElement_Tooltip_GenreAction": "Aksiyon oyunlarını dahil et.",
	"FilterElement_GenreAdventure": "Macera",
	"FilterElement_Tooltip_GenreAdventure": "Macera oyunlarını dahil et.",
	"FilterElement_GenreCasual": "Basit Eğlence",
	"FilterElement_Tooltip_GenreCasual": "Basit eğlence oyunlarını dahil et.",
	"FilterElement_GenreIndie": "Bağımsız",
	"FilterElement_Tooltip_GenreIndie": "Bağımsız oyunları dahil et.",
	"FilterElement_GenreMMO": "MMO",
	"FilterElement_Tooltip_GenreMMO": "Devasa çok oyunculu oyunları dahil et.",
	"FilterElement_GenreRacing": "Yarış",
	"FilterElement_Tooltip_GenreRacing": "Yarış oyunlarını dahil et.",
	"FilterElement_GenreRPG": "RYO",
	"FilterElement_Tooltip_GenreRPG": "Rol yapma oyunlarını dahil et.",
	"FilterElement_GenreSimulation": "Simülasyon",
	"FilterElement_Tooltip_GenreSimulation": "Simülasyon oyunlarını dahil et.",
	"FilterElement_GenreSports": "Spor",
	"FilterElement_Tooltip_GenreSports": "Spor oyunlarını dahil et.",
	"FilterElement_GenreStrategy": "Strateji",
	"FilterElement_Tooltip_GenreStrategy": "Strateji oyunlarını dahil et.",
	"FilterElement_Tooltip_StoreTag": "Steam'de %1$s ile etiketlenmiş oyunları dahil et.",
	"CollectionViewHeader_Tooltip_ManuallyAddedApp": "Bu oyun, koleksiyona manuel olarak eklendi.",
	"CollectionViewHeader_Tooltip_ManuallyRemovedApp": "Bu oyun, bu koleksiyondan kaldırıldı.",
	"CollectionViewHeader_Tooltip_ManuallyRemovedApps_WithCount": "Bu koleksiyondan %1$s oyun kaldırıldı.",
	"CollectionViewHeader_ManuallyRemovedApps_WithCount": "%1$s kaldırıldı",
	"CollectionView_EmptyReadOnlyCollection": "Burada gösterilecek bir şey yok",
	"CollectionView_EmptyDynamicCollection_Line1": "Bu filtreyle eşleşen oyun yok.",
	"CollectionView_EmptyDynamicCollection_Line2": "Filtreyi değiştirin ya da koleksiyon yaratmak için buraya oyun sürükleyin.",
	"CollectionView_EmptyCollection": "Bu koleksiyonu doldurmak için oyunları buraya sürükleyin.",
	"CollectionView_EmptyCollection_BecauseFilter": "Seçili filtrenizden ötürü %1$s oyun bu koleksiyonda gösterilmiyor.",
	"CollectionView_EmptyCollection_BecauseFilter_Plural": "Seçili filtrenizden ötürü %1$s oyun bu koleksiyonda gösterilmiyor.",
	"CollectionView_MissingCollection": "Herhangi bir koleksiyon bulunamadı.",
	"CollectionView_GamesExcluded": "+%1$s",
	"CollectionView_GamesExcluded_Desc": "ürün oynanmaya hazır değil",
	"AllCollectionsView_Title": "Koleksiyonlarınız",
	"AllCollectionsView_InfoIcon": "Ürünlerinizi düzenlemek için %1$s yaratın veya ürünleri bir dizi filtreyi kullanarak gruplandırmak için %2$s yaratın. %3$s",
	"AllCollectionsView_InfoIconCollections": "koleksiyonlar",
	"AllCollectionsView_InfoIconDynamicCollections": "dinamik koleksiyonlar",
	"AllCollectionsView_InfoIconFav": "%1$s her daim bu sayfanın en üstünde gösterilir.",
	"AllCollectionsView_InfoIconFavorites": "Favoriler",
	"AllCollectionsView_AddCollection": "Yeni bir koleksiyon yarat",
	"AllCollectionsView_DragToAddCollection": "Yeni bir koleksiyon yaratmak için buraya sürükleyin",
	"GameList_Home": "Kütüphane Ana Sayfası",
	"GameList_Search": "Ara",
	"GameList_Category_Uncategorized": "Kategorize Edilmemiş",
	"GameList_Category_Favorites": "Favoriler",
	"GameList_Category_Hidden": "Gizlenmiş",
	"GameList_Category_Hidden_Tooltip": "Gizlenen oyunlar, aranmadıkça kütüphanenizde görünmez. Tüm gizlenen oyunlarınızı üstte yer alan \"Görünüm\" menüsünden görüntüleyebilirsiniz.",
	"GameList_Category_YourCollections": "Koleksiyonlarınız",
	"GameList_Category_SharedLibraries": "Paylaşılan Kütüphaneler",
	"GameList_SectionHeader_SearchResults": "Ara ve Filtrele Sonuçları",
	"GameList_SectionHeader_AddedManually": "Manuel Olarak Eklendi",
	"GameList_SectionHeader_RemovedManually": "Manuel Olarak Kaldırıldı",
	"GameList_SectionHeader_NoRecentActivity": "Kaydedilmiş etkinlik yok",
	"GameList_View_Collections": "Koleksiyonlarınız",
	"GameList_View_ThisCollection": "Bu koleksiyonu görüntüle",
	"GameList_View_LibraryList": "Filtrelenmiş Liste",
	"GameList_View_OneCollection": "Koleksiyon görünümü",
	"GameList_View_SearchResults": "Arama sonuçları",
	"GameList_View_ShowAllCollections": "Tüm koleksiyonları göster",
	"GameList_View_GroupByCollections": "Koleksiyona Göre Grupla",
	"GameList_View_ExitSearch": "Aramadan çık",
	"GameList_View_All": "Tümü",
	"GameList_View_SortByRecent": "Son etkinliğe göre sırala",
	"GameList_View_ShowOnlyReadyToPlay": "Yalnızca oynamaya hazır oyunları göster",
	"GameList_View_ShowingOnlyReadyToPlay": "Oynamaya hazır oyunlar gösteriliyor",
	"GameList_View_ShowOnlyVR": "Sadece VR oyunlarını göster",
	"GameList_View_Platform_Linux": "Sadece Linux platformunda çalışan oyunları göster",
	"GameList_View_Platform_Apple": "Sadece Apple platformunda çalışan oyunları göster",
	"GameList_View_ReadyToPlay_ToolTip1": "• Bu makinede yüklü",
	"GameList_View_ReadyToPlay_ToolTip2": "• Başka bir makineden yayın yapılabilir",
	"GameList_Entry_ReadyToPlay_ToolTip": "Başka bir makineden yayın yapılacak",
	"Shelf_SectionHeader_ExpandTooltip": "Daha fazla satır göstermek için rafı genişlet",
	"Shelf_SectionHeader_ExpandTooltipFilter": "Daha fazla göstermek için rafı genişletin, %1$s ürün filtreniz nedeniyle listelenemedi",
	"GameList_SectionHeader_AppCountToolTip": "%1$s ürün görüntüleme filtreniz nedeniyle listelenmedi",
	"GameList_SectionHeader_AppCountToolTipAllHidden": "Görüntüleme filtreniz nedeniyle hiçbir ürün listelenmedi",
	"CollectionAction_ViewOnlyThis": "Sadece bu koleksiyonu görüntüle",
	"CollectionAction_ViewOnlyThisFavorites": "Sadece favorileri görüntüle",
	"CollectionAction_ViewOnlyThisUncategorized": "Sadece kategorisi olmayanları görüntüle",
	"CollectionAction_Collapse": "Daralt",
	"CollectionAction_Expand": "Genişlet",
	"CollectionAction_Manage": "Yönet",
	"CollectionAction_Edit": "Koleksiyon filtrelerini düzenle",
	"CollectionAction_Rename": "Koleksiyonu yeniden adlandır",
	"CollectionAction_Delete": "Koleksiyonu sil",
	"CollectionAction_DeleteDialog": "Koleksiyonu Sil",
	"CollectionAction_ConfirmDelete": "\"%1$s\" koleksiyonunu kalıcı olarak silmek istediğinize emin misiniz?",
	"CollectionAction_SaveFailed": "\"%1$s\" koleksiyonu kaydedilemedi",
	"CollectionAction_CannotOverwrite": "\"%1$s\" koleksiyonunun üzerine yazılamadı. Lütfen yeni bir isim seçin.",
	"CollectionAction_DeleteFailed": "\"%1$s\" koleksiyonu silinemedi",
	"LibraryHome_FriendsActivity": "Arkadaş Aktiviteleri",
	"LibraryHome_RecentGames": "Son Oyunlar",
	"LibraryHome_NewUpdates": "Yenilikler",
	"LibraryHome_YourCollection": "Bütün Kütüphaneniz",
	"LibraryHome_RecentFriendsActivity": "Son Arkadaş Etkinlikleri",
	"Library_FriendsActivity_HotRightNowHeading": "Şu anda popüler",
	"Library_FriendsActivity_HotRightNowHover": "Pek çok arkadaşınız şu anda bu oyunu oynadığı size bunu gösteriyoruz.",
	"Library_FriendsActivity_TrendingHeading": "Yükselişte",
	"Library_FriendsActivity_TrendingHover": "Arkadaşlarınız tarafından geçen haftaya kıyasla daha çok oynandığı için gösteriliyor.",
	"Library_FriendsActivity_BeingDiscussedHeading": "Üzerine konuşuluyor",
	"Library_FriendsActivity_BeingDiscussedHover": "Arkadaşlarınız bu oyunla ilgili ekran görüntüleri ve durum mesajları paylaştığı için gösteriliyor.",
	"Library_FriendsActivity_RecentlyPurchasedHeading": "Yakın zamanda satın alındı",
	"Library_FriendsActivity_RecentlyPurchasedHover": "Yakın zamanda satın aldığınız ve arkadaşlarınız tarafından oynandığı için gösteriliyor.",
	"Library_FriendsActivity_UnownedHeading": "Yeni bir şeyler deneyin",
	"Library_FriendsActivity_UnownedHover": "Arkadaşlarınız arasında popüler olduğu ancak siz sahip olmadığınız için gösteriliyor.",
	"Library_FriendsActivity_PopularHeading": "Popüler",
	"Library_FriendsActivity_PopularHover": "Pek çok arkadaşınız yakın zamanda oynadığı için gösteriliyor.",
	"Library_FriendsActivity_DontForgetHeading": "Unutmayın",
	"Library_FriendsActivity_DontForgetHover": "Son zamanlarda oynamadığınız ancak arkadaşlarınız tarafından oynandığı için gösteriliyor.",
	"Library_FriendsActivity_NewToGroupHeading": "Arkadaşlarınızın yeni oyunları",
	"Library_FriendsActivity_NewToGroupHover": "Yakın zamanda arkadaşlarınız tarafından oynanmaya başlandığı için gösteriliyor.",
	"Library_FriendsActivity_ReturnedToGroupHeading": "Tekrar oynanıyor",
	"Library_FriendsActivity_ReturnedToGroupHover": "Arkadaşlarınız tekrar oynamaya başladığı için gösteriliyor.",
	"Library_FriendsActivity_UnownedBanner": "Steam mağazasında görüntüle",
	"Library_FriendsActivity_UnownedMenu_Store": "Mağaza",
	"Library_FriendsActivity_UnownedMenu_Hub": "Topluluk Merkezi",
	"Library_FriendsActivity_UnownedMenu_Reviews": "İncelemeler",
	"Library_FriendsActivity_UnownedMenu_Discussions": "Tartışmalar",
	"Library_Recent_NoRecentGames_GamesOwned": "%1$s oyununuz var.",
	"Library_Recent_NoRecentGames_StoreLink": "Eklenecek oyun bulmak için %1$s'nı ziyaret edin:",
	"Library_Recent_NoRecentGames_SteamStore": "Steam Mağazası",
	"Library_Recent_NoRecentGames_FreeToPlay": "Oynaması Ücretsiz Oyunlar",
	"Library_Recent_NoRecentGames_GamesOnSale": "İndirimdeki Oyunlar",
	"Library_Recent_NoRecentGames_NewReleases": "Yeni Çıkanlar",
	"Library_Recent_NoRecentGames_ActivateProduct": "Ürün Etkinleştir",
	"Library_Recent_NoRecentGames_RedeemCode": "Steam Cüzdan Kodu Kullan",
	"Library_SortCollectionBy": "Sırala",
	"Library_SortByFavoritesFirst": "Favoriler En Üstte",
	"Library_SortByAlphabetical": "Alfabetik",
	"Library_SortByPctAchievementsComplete": "Tamamlanan Başarım Yüzdesi",
	"Library_SortByLastUpdated": "Son Güncelleme",
	"Library_SortByHoursPlayed": "Oynanan Saat",
	"Library_SortByLastPlayed": "Son Oynama",
	"Library_SortByReleaseDate": "Çıkış Tarihi",
	"Library_SortByAddedToLibrary": "Kütüphaneye Eklenme Tarihi",
	"Library_SortBySizeOnDisk": "Diskteki Boyut",
	"Library_SortByMetacriticScore": "Metacritic Puanı",
	"Library_SortByFriendsPlaying": "Oynayan Arkadaşlar",
	"Library_InstalledOnlyCheck": "Sadece Yüklenmiş",
	"GridSection_Favorites": "Favoriler",
	"GridSection_EverythingElse": "Diğer Her Şey",
	"GridSection_Over100Hours": "100 Saat Üzeri",
	"GridSection_Over60Hours": "60 Saat Üzeri",
	"GridSection_Over40Hours": "40 Saat Üzeri",
	"GridSection_Over20Hours": "20 Saat Üzeri",
	"GridSection_Over10Hours": "10 Saat Üzeri",
	"GridSection_Over1Hour": "1 Saat Üzeri",
	"GridSection_LessThan1Hour": "Bir Saatten Az",
	"GridSection_Over90Metacritic": "90 Üzeri",
	"GridSection_Over80Metacritic": "80 Üzeri",
	"GridSection_Over70Metacritic": "70 Üzeri",
	"GridSection_Over50Metacritic": "50 Üzeri",
	"GridSection_EverythingElseMetacritic": "Diğer Her Şey",
	"GridSection_UnknownReleaseDate": "Bilinmiyor",
	"GridSection_GreaterThan100GB": "100 GB'den Büyük",
	"GridSection_GreaterThan50GB": "50 GB'den Büyük",
	"GridSection_GreaterThan20GB": "20 GB'den Büyük",
	"GridSection_LessThan20GB": "20 GB'den Küçük",
	"GridSection_NoSizeOnDisk": "Boyut Yok",
	"GridSection_NotInstalled": "Yüklü Değil",
	"GridSection_MoreThan10YearsAgo": "10+ yıl önce",
	"GridSection_Never": "Hiçbir Zaman",
	"AppDetails_SectionTitle_Stream": "Geliştirici Yayını",
	"AppDetails_SectionTitle_Activity": "Aktivite",
	"AppDetails_SectionTitle_Friends": "Oynayan arkadaşlar",
	"AppDetails_SectionTitle_Friends_Software": "arkadaşınız şunu kullanıyor:",
	"AppDetails_SectionTitle_Achievements": "Başarımlar",
	"AppDetails_SectionTitle_TradingCards": "Koleksiyon Kartları",
	"AppDetails_SectionTitle_Screenshots": "Ekran görüntüleri",
	"AppDetails_SectionTitle_Updates": "Son Etkinlikler ve Güncellemeler",
	"AppDetails_SectionTitle_DLC": "DLC",
	"AppDetails_SectionTitle_LastPlayed": "Son Oynama",
	"AppDetails_SectionTitle_LastLaunched": "Son Başlatma",
	"AppDetails_SectionTitle_PlayTime": "Oynama Süresi",
	"AppDetails_SectionTitle_UsageTime": "Kullanma Süresi",
	"AppDetails_SectionTitle_Workshop": "Steam Atölyesi",
	"AppDetails_SectionTitle_Community": "Topluluk İçeriği",
	"AppDetails_SectionTitle_Links": "Bağlantılar",
	"AppDetails_SectionTitle_SignIn_Pre": "Giriş Yap",
	"AppDetails_SectionTitle_SignIn": "Arkadaş etkinliğini görmek için %1$s",
	"AppDetails_SectionTitle_OpenFriends": "Arkadaş Listesini Aç",
	"AppDetails_SectionTitle_OfflineMode": "Çevrimdışı Modu",
	"AppDetails_Broadcast_ViewOnWeb": "İnternet tarayıcısında görüntüle",
	"AppDetails_Community_Tooltip1": "Bu bölümde topluluktan gönderilen ekran görüntüleri, çizimler, videolar, rehberler ve daha fazlası bulunur.",
	"AppDetails_Community_Tooltip2": "Bu içeriği beğenebilir, paylaşabilir, şikâyet edebilir veya hakkında yorum yazabilirsiniz.",
	"AppDetails_Community_Guide": "Topluluk Rehberi",
	"AppDetails_Links_Store": "Mağaza Sayfası",
	"AppDetails_Links_Community": "Topluluk Merkezi",
	"Bbcode_Originally_Posted_By": "Gönderen:",
	"AppDetails_InOfflineMode": "Steam şu anda çevrimdışı modda. Aktiviteler ve Arkadaşlar gibi Steam kütüphanesinin pek çok özelliği çevrimdışı modda mevcut değildir. Bu içeriği görüntülemek için çevrimiçi olun.",
	"AppDetails_GoOnline": "Çevrimiçi Ol",
	"GameAction_Stop": "Durdur",
	"GameAction_Cancel": "İptal",
	"GameAction_Install": "Yükle",
	"GameAction_Uninstall": "Kaldır",
	"GameAction_Play": "Oyna",
	"GameAction_Launch": "Başlat",
	"GameAction_PreLoad": "Ön Yükle",
	"GameAction_Update": "Güncelle",
	"GameAction_Download": "İndir",
	"GameAction_Resume": "Devam Et",
	"GameAction_Pause": "Duraklat",
	"GameAction_BorrowApp": "Ödünç Al",
	"GameAction_PurchaseApp": "Satın Al",
	"GameAction_GameProperties": "Özellikler...",
	"GameAction_AddToFavorites": "Favorilere Ekle",
	"GameAction_RemoveFromFavorites": "Favorilerden Kaldır",
	"GameAction_AddToHidden": "Bu oyunu gizle",
	"GameAction_RemoveFromHidden": "Gizlenenlerden Kaldır",
	"GameAction_AddToFamilyGames": "Aile Oyunlarına Ekle",
	"GameAction_RemoveFromFamilyGames": "Aile Oyunlarından Kaldır",
	"GameAction_RemoveShortcut": "Kütüphaneden Steam dışı oyunu kaldır",
	"GameAction_AddToCollection": "Şuraya ekle",
	"GameAction_RemoveFromCollection": "Şuradan kaldır",
	"GameAction_CreateDesktopShortcut": "Masaüstü kısayolu ekle",
	"GameAction_BackUpFiles": "Oyun dosyalarını yedekle...",
	"GameAction_Stream": "Yayınla",
	"GameAction_Connect": "Bağlan",
	"GameAction_SetCustomArtwork": "Özel bir çizim belirle",
	"GameAction_ClearCustomArtwork": "Özel çizimi temizle",
	"GameAction_ViewCDKeys": "CD Anahtarları",
	"GameAction_ControllerConfiguration": "Kontrolcü Yapılandırması",
	"GameAction_RemoveAppFromCollection": "%2$s koleksiyonundan %1$s adlı öğeyi kaldırmak için BURAYA SÜRÜKLEYİN",
	"GameAction_RemoveAppFromMultipleCollections": "Şu koleksiyonlardan %1$s adlı ürünü kaldırmak için BURAYA SÜRÜKLEYİN",
	"GameAction_RemoveMultipleAppsFromCollection": "Bu uygulamaları %1$s koleksiyonundan kaldırmak için BURAYA SÜRÜKLEYİN",
	"GameAction_RemoveMultipleAppsFromMultipleCollections": "Bu uygulamaları şu koleksiyonlardan kaldırmak için BURAYA SÜRÜKLEYİN",
	"GameAction_NavigateToAllCollectionsWithDrag": "Koleksiyonların tamamını görmek için BURAYA SÜRÜKLEYİN ve BIRAKIN",
	"GameAction_AddToCollectionOption_NewCollection": "Yeni koleksiyon...",
	"GameAction_NewCollectionDialogTitle": "Yeni Koleksiyon",
	"GameAction_Manage": "Yönet",
	"GameAction_Favorite": "Favorilere Ekle",
	"GameAction_UnFavorite": "Favorilerde",
	"GameAction_ViewDetails": "Daha fazla ayrıntı göster",
	"GameAction_ViewDetails_Collapse": "Daha az ayrıntı göster",
	"GameAction_ViewDetails_ScrollUp": "En üste git",
	"GameActionPlural_Install": "Seçileni yükle",
	"GameActionPlural_Uninstall": "Hepsini kaldır",
	"GameActionPlural_PreLoad": "Seçileni ön yükle",
	"GameActionPlural_Update": "Seçileni güncelle",
	"GameActionPlural_Download": "Seçileni indir",
	"GameActionPlural_Resume": "Seçilene devam et",
	"GameActionPlural_AddToFavorites": "Seçileni favorilere ekle",
	"GameActionPlural_RemoveFromFavorites": "Seçileni favorilerden kaldır",
	"GameActionPlural_AddToHidden": "Seçilen oyunları gizle",
	"GameActionPlural_RemoveFromHidden": "Seçileni Gizlenenlerden Kaldır",
	"GameActionPlural_AddToFamilyGames": "Seçileni aile oyunlarına ekle",
	"GameActionPlural_RemoveFromFamilyGames": "Seçileni aile oyunlarından kaldır",
	"GameActionPlural_RemoveShortcut": "Seçilen Steam dışı oyunları kütüphaneden kaldır",
	"GameActionPlural_AddToCollection": "Seçileni şuraya ekle",
	"GameActionPlural_RemoveFromCollection": "Seçileni şuradan kaldır",
	"GameActionPlural_CreateDesktopShortcut": "Masaüstü Kısayolları Ekle",
	"GameActionPlural_BackUpFiles": "Oyun Dosyalarını Yedekle...",
	"DisplayStatus_Launching": "Başlatılıyor",
	"DisplayStatus_Uninstalling": "Kaldırılıyor",
	"DisplayStatus_Installing": "Yükleniyor",
	"DisplayStatus_Running": "Çalışıyor",
	"DisplayStatus_Validating": "Doğrulanıyor",
	"DisplayStatus_Updating": "Güncelleniyor",
	"DisplayStatus_Downloading": "İndiriliyor",
	"DisplayStatus_Synchronizing": "Steam Cloud'la Senkronize Ediliyor",
	"DisplayStatus_ReadyToInstall": "Yüklemeye Hazır",
	"DisplayStatus_ReadyToPreload": "Ön Yüklemeye Hazır",
	"DisplayStatus_ReadyToLaunch": "Başlatmaya Hazır",
	"DisplayStatus_RegionRestricted": "Bölgenizde erişilebilir değil",
	"DisplayStatus_PresaleOnly": "Bu öğe henüz erişilebilir değil",
	"DisplayStatus_InvalidPlatform": "Platformlar:",
	"DisplayStatus_PreloadComplete": "Ön Yükleme Tamamlandı",
	"DisplayStatus_BorrowerLocked": "Kütüphane şu anda Aile Paylaşımı için kullanılabilir değil",
	"DisplayStatus_UpdatePaused": "Güncelleme Duraklatıldı",
	"DisplayStatus_UpdateQueued": "Güncelleme Kuyrukta",
	"DisplayStatus_UpdateRequired": "Güncelleme Gerekli",
	"DisplayStatus_UpdateDisabled": "Steam çevrimdışı modda olduğu için güncellemeler kullanılabilir değil. Bu oyunun güncellemesini tamamlamak için çevrimiçi olun.",
	"DisplayStatus_DownloadPaused": "İndirme Duraklatıldı",
	"DisplayStatus_DownloadQueued": "İndirme Kuyruğa Eklendi",
	"DisplayStatus_DownloadRequired": "İndirme Gerekli",
	"DisplayStatus_DownloadDisabled": "Steam çevrimdışı modda olduğu için indirmeler kullanılabilir değil. Bu oyunun indirmesini tamamlamak için çevrimiçi olun.",
	"DisplayStatus_LicensePending": "Satın alımınız henüz tamamlanmadı.",
	"DisplayStatus_LicenseExpired": "Lisans Sona Erdi",
	"DisplayStatus_AvailForFree": "Ücretsiz erişilebilir",
	"DisplayStatus_AvailToBorrow": "Ödünç alınabilir",
	"DisplayStatus_AvailGuestPass": "Deneme kuponu mevcut",
	"DisplayStatus_Purchase": "Satın alınabilir",
	"DisplayStatus_Compact_Launching": "Başlatılıyor",
	"DisplayStatus_Compact_Uninstalling": "Kaldırılıyor",
	"DisplayStatus_Compact_Installing": "Yükleniyor",
	"DisplayStatus_Compact_Running": "Çalışıyor",
	"DisplayStatus_Compact_Validating": "Doğrulanıyor",
	"DisplayStatus_Compact_Updating": "Güncelleniyor",
	"DisplayStatus_Compact_Downloading": "İndiriliyor",
	"DisplayStatus_Compact_Synchronizing": "Steam Cloud'la Senkronize Ediliyor",
	"DisplayStatus_Compact_ReadyToInstall": "Yüklemeye Hazır",
	"DisplayStatus_Compact_ReadyToPreload": "Ön Yüklemeye Hazır",
	"DisplayStatus_Compact_ReadyToLaunch": "Başlatmaya Hazır",
	"DisplayStatus_Compact_RegionRestricted": "Bu bölgede erişilebilir değil",
	"DisplayStatus_Compact_PresaleOnly": "Oyun henüz çıkmadı",
	"DisplayStatus_Compact_InvalidPlatform": "Platformlar:",
	"DisplayStatus_Compact_ParentalBlocked": "Steam Aile Görünümü tarafından engellendi",
	"DisplayStatus_Compact_PreloadComplete": "Ön Yükleme Tamamlandı",
	"DisplayStatus_Compact_BorrowerLocked": "Aile Paylaşımı Kullanılabilir Değil",
	"DisplayStatus_Compact_UpdatePaused": "Güncelleme Duraklatıldı",
	"DisplayStatus_Compact_UpdateQueued": "Güncelleme Kuyrukta",
	"DisplayStatus_Compact_UpdateRequired": "Güncelleme Gerekli",
	"DisplayStatus_Compact_UpdateDisabled": "Çevrimdışı modda güncellemeler devre dışıdır",
	"DisplayStatus_Compact_DownloadPaused": "İndirme Duraklatıldı",
	"DisplayStatus_Compact_DownloadQueued": "İndirme Kuyruğa Eklendi",
	"DisplayStatus_Compact_DownloadRequired": "İndirme Gerekli",
	"DisplayStatus_Compact_DownloadDisabled": "Çevrimdışı modda indirmeler devre dışıdır",
	"DisplayStatus_Compact_LicensePending": "Satın Alım Tamamlanıyor",
	"DisplayStatus_Compact_LicenseExpired": "Lisans Sona Erdi",
	"DisplayStatus_Compact_AvailForFree": "Ücretsiz erişilebilir",
	"DisplayStatus_Compact_AvailToBorrow": "Ödünç alınabilir",
	"DisplayStatus_Compact_AvailGuestPass": "Deneme kuponu mevcut",
	"DisplayStatus_Compact_Purchase": "Satın alınabilir",
	"DisplayStatus_ReleaseDate": "Çıkış Tarihi: %1$s",
	"DisplayStatus_CustomReleaseDate": "Planlanan Çıkış Tarihi: %1$s",
	"Downloads_State_Bytes_Of_Bytes": "%1$s/%2$s",
	"Downloads_State_None": "",
	"Downloads_State_Reconfiguring": "İndirme Başlatılıyor",
	"Downloads_State_Validating": "Dosyalar Doğrulanıyor",
	"Downloads_State_AddingFiles": "Dosyalar Kopyalanıyor",
	"Downloads_State_Preallocating": "Alan Ayrılıyor",
	"Downloads_State_Downloading": "",
	"Downloads_State_Staging": "",
	"Downloads_State_Committing": "Sonlandırılıyor",
	"Downloads_State_Verifying": "İndirme Doğrulanıyor",
	"Downloads_State_Stopping": "İndirme Durduruluyor",
	"Downloads_State_Running": "",
	"Downloads_State_SecondsRemaining": "%1$s saniye kaldı",
	"Downloads_State_MinutesRemaining": "%1$s dakika kaldı",
	"Downloads_State_Calculating": "Hesaplanıyor...",
	"LaunchApp_Action_UpdatingAppInfo": "Yapılandırma kontrol ediliyor",
	"LaunchApp_Action_ShowEula": "EULA (Son Kullanıcı Lisans Anlaşması) Gösteriliyor",
	"LaunchApp_Action_DownloadingDepots": "İçerik indiriliyor (%1$s%)",
	"LaunchApp_Action_DownloadingWorkshop": "Atölye indiriliyor (%1$s%)",
	"LaunchApp_Action_UpdatingDRM": "Yürütülebilir güncelleniyor",
	"LaunchApp_Action_GettingLegacyKey": "Ürün anahtarı güncelleniyor",
	"LaunchApp_Action_RunningInstallScript": "Yükleme komut dosyası çalışıyor (%1$s)",
	"LaunchApp_Action_SynchronizingCloud": "Steam Cloud'la senkronize ediliyor",
	"LaunchApp_Action_VerifyingFiles": "Yürütülebilir doğrulanıyor",
	"LaunchApp_Action_CreatingProcess": "Yürütülebilir başlatılıyor",
	"LaunchApp_Action_WaitingGameWindow": "Yürütülebilir başlatılıyor",
	"LaunchApp_Action_DelayLaunch": "Başlatma geciktiriliyor (%1$s%)",
	"AppDetails_TitleUpdatedSincePlayed": "Bu oyun son oynadığınızdan bu yana güncellenmiş",
	"AppDetails_TitleUpdatedSincePlayedLink": "Değişiklikleri okuyun",
	"AppDetails_BadgeLevel": "%1$s. Seviye, TP: %2$s",
	"AppDetails_UnearnedBadgeXP": "%1$s TP",
	"AppDetails_BadgeLevelNoXP": "%1$s. Seviye",
	"AppDetails_Review_ViewOrEdit": "İncelememi Düzenle",
	"AppDetails_Review_YourReview": "İncelemem",
	"AppDetails_Review_Ignore_Stale_Reviews": "Bu incelemeyi güncellemem için bana hatırlatma yapma.",
	"AppDetails_Review_Unignore_Stale_Reviews": "Bu oyun için inceleme eski uyarısına izin ver.",
	"AppDetails_Review_RecommendGame": "Bu oyunu tavsiye ediyor musunuz?",
	"AppDetails_Review_RecommendSoftware": "Bu yazılımı tavsiye eder misiniz?",
	"AppDetails_Review_WriteReview": "%1$s için bir inceleme yazın",
	"AppDetails_Review_PlayedForTime": "%1$s oynadınız",
	"AppDetails_Review_PlayedForTime_Software": "Bu ürünü %1$s kadar kullandınız",
	"AppDetails_Review_RecommendGameButton_Yes": "Evet",
	"AppDetails_Review_RecommendGameButton_No": "Hayır",
	"AppDetails_Review_PlaytimeAtReview": "İncelemeyi yazarkenki oynama süreniz: %1$s",
	"AppDetails_Review_PlaytimeAtReview_Software": "İncelemeyi yazma sırasında kullanma süreniz: %1$s",
	"AppDetails_Review_NotRecommended": "Tavsiye Edilmiyor",
	"AppDetails_Review_Recommended": "Tavsiye Ediliyor",
	"AppDetails_Review_AdditionalPlaytime": "Bu incelemeyi yazdığınızdan bu yana %1$s oynadınız.",
	"AppDetails_Review_AdditionalPlaytime_Software": "Bu incelemeyi yazdığınızdan bu yana %1$s kullandınız.",
	"AppDetails_Review_ChangedYourMind": "Fikrinizi mi değiştirdiniz?",
	"AppDetails_Review_IHaveNotChangedMyMind": "Hayır",
	"AppDetails_Review_UpVotes": "Beğeniler:",
	"AppDetails_Review_Comments": "Yorumlar:",
	"AppDetails_Review_ViewAll": "Tüm incelemelerimi görüntüle",
	"AppDetails_Review_ViewAllByFriend": "%1$s adlı kullanıcının tüm incelemelerini görüntüle",
	"OverflowBox_Action_Collapse": "Küçült",
	"OverflowBox_Action_Expand": "Daha fazlasını okuyun",
	"OverflowBox_More": "(%1$s daha)",
	"AppDetails_FriendsInGameNow": "Şu anda %1$s arkadaş oynuyor",
	"AppDetails_FriendsInGameNow_Plural": "Şu anda %1$s arkadaş oynuyor",
	"AppDetails_FriendsPlayedRecently": "Yakın zamanda %1$s arkadaş oynadı",
	"AppDetails_FriendsPlayedRecently_Plural": "Yakın zamanda %1$s arkadaş oynadı",
	"AppDetails_FriendsPlayedRecentlyExpand": "En son oynananların tümünü göster",
	"AppDetails_FriendsPlayed": "%1$s arkadaşınız tarafından oynandı",
	"AppDetails_FriendsPlayed_Plural": "%1$s arkadaşınız tarafından oynandı",
	"AppDetails_FriendsPlayedExpand": "Önceden oynananların tümünü göster",
	"AppDetails_FriendsMore": "(%1$s daha)",
	"AppDetails_FriendsLess": "Küçült",
	"AppDetails_FriendsWishlisted": "%2$s, %1$s arkadaşın istek listesinde",
	"AppDetails_FriendsWishlisted_Plural": "%2$s, %1$s arkadaşın istek listesinde",
	"AppDetails_FriendsWishlistExpand": "İstek listesine ekleyenlerin tümünü göster",
	"AppDetails_Friends_ViewAll": "Oynayan arkadaşların tümünü görüntüle",
	"AppDetails_GameInfo": "Oyun Bilgileri",
	"AppDetails_Publisher": "Yayıncı:",
	"AppDetails_Developer": "Geliştirici:",
	"AppDetails_Franchise": "Seri:",
	"AppDetails_ReleaseDate": "Çıkış Tarihi:",
	"AppDetails_OriginalReleaseDate": "İlk Çıkış Tarihi:",
	"AppDetails_Feature_SinglePlayer": "Tek Oyunculu",
	"AppDetails_Feature_MultiPlayer": "Çok Oyunculu",
	"AppDetails_Feature_CoOp": "Eşli Oyun",
	"AppDetails_Feature_SteamAchievements": "Başarımlar",
	"AppDetails_Feature_SteamCloud": "Steam Cloud Kayıtları",
	"AppDetails_Feature_FullController": "Tam Kontrolcü Desteği",
	"AppDetails_Feature_PartialController": "Kısmî Kontrolcü Desteği",
	"AppDetails_Feature_SteamWorkshop": "Steam Atölyesi",
	"AppDetails_Feature_VRSupport": "VR Desteği",
	"AppDetails_ViewAllUpdates": "Tüm Güncellemeleri Görüntüle",
	"AppDetails_ViewAllAchievements": "Başarımlarımı Görüntüle",
	"AppDetails_ViewGlobalAchievements": "Global Başarım İstatistiklerini Görüntüle",
	"AppDetails_PlayerUnlockedPercent": "%1$s/%2$s kazanıldı",
	"AppDetails_PlayerUnlockedPercentAll": "%1$s/%2$s Tüm başarımları kazandınız!",
	"AppDetails_Achievements_Unlocked": "%1$s tarihinde kazanıldı",
	"AppDetails_PctUnlocked": "Oyuncuların %%1$s kadarı bu başarıma sahip",
	"AppDetails_GlobalCompare": "Bu, oyuncuların %%1$s kadarından daha fazla",
	"AppDetails_ViewTradingCards": "Koleksiyon Kartlarımı Görüntüle",
	"AppDetails_Achievements_Locked": "Kazanılmamış Başarımlar",
	"AppDetails_TradingCardsLeft": "Toplanılacak 1 kart kaldı",
	"AppDetails_TradingCardsLeft_Plural": "Toplanılacak %1$s kart kaldı",
	"AppDetails_TradingCardsLevelUp": "Seviye yükseltmeye yetecek kadar kartınız var!",
	"AppDetails_TradingCardsMaxed": "Tebrikler! Rozet son seviyesine ulaştı!",
	"AppDetails_TradingCards_Tooltip1": "Koleksiyon kartları siz oyun oynadıkça düşer. Sahip olmadığınız kartları arkadaşlarınızla takas ederek ya da Topluluk Pazarı'ndan satın alarak elde edebilirsiniz.",
	"AppDetails_TradingCards_Tooltip2": "Tam bir kart setini topladıktan sonra bunlara işleyerek rozet elde edersiniz. Rozetler Steam seviyenizi artırır, profilinize ve hesabınıza çeşitli faydalar sağlar.",
	"AppDetails_BrowseWorkshop": "Atölye'ye Göz At",
	"AppDetails_ViewSubscribedItems": "Aboneliklerimi Görüntüle",
	"AppDetails_ViewItemInWorkshop": "Atölye'de Görüntüle",
	"AppDetails_MoreItemsFrom": "Bu Yaratıcının Öğelerini Görüntüle",
	"AppDetails_SubscribeToItem": "Abone Ol",
	"AppDetails_UnsubscribeFromItem": "Abonelikten Çık",
	"AppDetails_Subscribed": "Abone Olundu",
	"AppDetails_ViewMoreInWorkshop": "Atölye'de daha fazlasını görüntüle",
	"AppDetails_WorkshopSubCount": "%1$s adet Atölye aboneliğiniz var.",
	"AppDetails_WorkshopVisit": "Atölye'yi Ziyaret Et",
	"AppDetails_WorkshopLearnMore": "Daha Fazlasını Öğrenin",
	"AppDetails_WorkshopFeaturedHeader": "Popülerleşen Öğe",
	"AppDetails_WorkshopFeaturedItem": "Popüler Öğe",
	"AppDetails_WorkshopFeaturedMoreInfo": "Daha Fazlasını Okuyun",
	"AppDetails_WorkshopFeaturedHideItem": "Bu Öğeyi Gizle",
	"AppDetails_WorkshopFileSize": "Dosya Boyutu: %1$s",
	"AppDetails_WorkshopFileSizeBytes": "%1$s bayt",
	"AppDetails_WorkshopFileSizeKb": "%1$s KB",
	"AppDetails_WorkshopFileSizeMb": "%1$s MB",
	"AppDetails_WorkshopFileSizeGb": "%1$s GB",
	"AppDetails_WorkshopLastUpdated": "Son Güncelleme: %1$s",
	"DLCStatus_installed": "Yüklü",
	"DLCStatus_notinstalled": "Yüklü Değil",
	"DLCStatus_downloading": "İndiriliyor",
	"DLC_DateAdded": "Eklenme Tarihi: %1$s",
	"AppDetails_ManageDLC": "%1$s DLC'imi Yönet",
	"AppDetails_ManageMyDLC": "DLC'imi Yönet",
	"AppDetails_ViewStoreDLC": "DLC'leri Mağazada Görüntüle",
	"AppDetails_DLCSpotlight": "Yeni alınan DLC eklendi ve oyunla birlikte yüklenecek. DLC'lerinizi %1$s yönetin.",
	"AppDetails_DLCSpotlight_Installed": "Yeni alınan DLC otomatik olarak yüklendi. DLC'lerinizi %1$s yönetin.",
	"AppDetails_DLCSpotlight_here": "buradan",
	"ManageDLC_Title": "DLC'yi Yönet",
	"ManageDLC_Column_Name": "Ad",
	"ManageDLC_Column_DateAdded": "Eklenme Tarihi",
	"ManageDLC_Column_Enabled": "Etkin",
	"ManageDLC_Column_Installed": "Yüklü",
	"ManageDLC_Search": "Ara...",
	"ManageDLC_Installed": "Yüklü: %1$s/%2$s",
	"ManageDLC_ViewMore": "Mağazada daha fazlasını görüntüleyin",
	"ManageDLC_NoResults": "\"%1$s\" ile eşleşen bir sonuç yok",
	"AppDetails_ViewBadgePage": "Rozet Sayfasını Görüntüle",
	"AppDetails_VisitTradeForum": "Takas Forumunu Ziyaret Et",
	"AppDetails_BuyCards": "Kalan kartları Steam Pazarı'ndan satın al",
	"AppDetails_SellCards": "Bu kartları Steam Pazarı'nda sat",
	"AppDetails_SearchCard": "Bu kartı Steam Pazarı'nda göster",
	"AppDetails_ShowFriendsList": "Arkadaş Listesini Göster",
	"AppDetails_ViewFriendsWhoPlay": "Oynayan Arkadaşları Görüntüle",
	"AppDetails_Link_Discussions": "Tartışmalar",
	"AppDetails_Link_FindGroups": "Grup Arayın",
	"AppDetails_Link_GameHub": "Topluluk Merkezi",
	"AppDetails_Link_Guides": "Rehberler",
	"AppDetails_Link_Store": "Mağaza Sayfası",
	"AppDetails_Link_Support": "Destek",
	"AppDetails_Link_Workshop": "Atölye",
	"AppDetails_Link_Controller": "Kontrolcü Yapılandırması",
	"AppDetails_SocialMediaLink": "%1$s - %2$s",
	"AppDetails_SocialMediaType_4": "Twitter",
	"AppDetails_SocialMediaType_5": "Twitch",
	"AppDetails_SocialMediaType_6": "YouTube",
	"AppDetails_SocialMediaType_7": "Facebook",
	"AppDetails_Screenshot": "Ekran Görüntüsü",
	"AppDetails_Screenshot_Caption": "Açıklama: %1$s",
	"AppDetails_Screenshot_Date": "Tarih: %1$s",
	"AppDetails_Screenshot_Dimensions": "Boyut: %1$s x %2$s piksel",
	"AppDetails_Screenshot_Uploaded": "Yüklenme Tarihi: %1$s, %2$s",
	"AppDetails_OpenScreenshotUploader": "Ekran Görüntüsü Yükleyicisini Aç",
	"AppDetails_ViewUploadedScreenshots": "Yüklenen Ekran Görüntüsünü Görüntüle",
	"AppDetails_ManageMyScreenshot": "Ekran görüntümü yönet",
	"AppDetails_ManageMyScreenshot_Plural": "%1$s ekran görüntümü yönet",
	"AppDetails_HowToScreenshot": "Oyundayken %1$s tuşuna basarak ekran görüntüsü alabilirsiniz.",
	"AppDetails_ChangeMyScreenshotKey": "Ekran Görüntüsü Tuşumu Değiştir",
	"AppDetails_NoScreenshots": "Henüz ekran görüntüsü almadınız",
	"AppDetails_Artwork": "Çizimler",
	"AppDetails_Video": "Video",
	"AppDetails_CommunityItem": "Topluluk İçeriği",
	"AppDetails_CommunityFeed_OutOfContent": "Başka içerik yok",
	"AppDetails_CommunityFeed_Inappropriate": "İçerik her yaş grubuna uygun olmayabilir",
	"AppDetails_CommunityFeed_ViewContent": "İçeriği Görüntüle",
	"AppDetails_CommunityFeed_EditPreferences": "Tercihleri Düzenle",
	"AppDetails_CommunityFeed_LoadCommunity": "Daha Fazla Topluluk İçeriği Yükle",
	"AppBox_NewToLibrary": "Kütüphanede yeni",
	"AppBox_ComingSoon": "Pek Yakında",
	"AppBox_NewToLibrary_Short": "Yeni",
	"AppBox_ComingSoon_Short": "Yakında",
	"AppBox_PlayTimeHeader": "Oynama süresi",
	"AppBox_RecentPlayTime_Hours": "Son iki hafta: %1$s saat",
	"AppBox_RecentPlayTime_Minutes": "Son iki hafta: %1$s dakika",
	"AppBox_TotalPlayTime_Hours": "Toplam: %1$s saat",
	"AppBox_TotalPlayTime_Minutes": "Toplam: %1$s dakika",
	"AppActivity_Achieved": " şu başarımları kazandı:",
	"AppActivity_PostedScreenshot": " bir ekran görüntüsü paylaştı",
	"AppActivity_PostedScreenshot_Plural": " %1$s ekran görüntüsü paylaştı",
	"AppActivity_PostedVideo": " bir video paylaştı",
	"AppActivity_PostedVideo_Plural": " %1$s video paylaştı",
	"AppActivity_ReceivedNewGame": " artık %1$s sahibi",
	"AppActivity_PlayedGameFirstTime": " ilk defa %1$s oynadı",
	"AppActivity_LaunchedSoftwareFirstTime": " ilk defa %1$s kullandı",
	"AppActivity_AddedGameToWishlist": " %2$s %1$s ekledi",
	"AppActivity_Wishlist": "istek listesine",
	"AppActivity_Achieved_PlusMore": "… Ve %1$s başarım daha",
	"AppActivity_Achieved_PlusMore_Label": "%1$s adlı kullanıcının tüm başarımlarını görüntüle",
	"AppActivity_NoActivity": "Bu ürün için yakın zamanda geliştiriciler ya da arkadaşlarınız tarafından herhangi bir aktivitede bulunulmamış.",
	"AppActivity_UserStatus_Time": " bir durum güncellemesi yayınladı (%1$s)",
	"AppActivity_UserStatus": " bir durum güncellemesi yayınladı",
	"AppActivity_StatusUpdate": "Arkadaşlarınızla bir durum yazısı paylaşın",
	"AppActivity_StatusUpdate_Post": "Arkadaşlarınıza bu oyun hakkında bir şeyler söyleyin...",
	"AppActivity_StatusUpdate_Software_Post": "Arkadaşlarınıza bu yazılım hakkında bir şeyler söyleyin...",
	"AppActivity_Comment_Reply": "Cevap ekleyin...",
	"AppActivity_PostStatusUpdate": "Yayınla",
	"AppActivity_FetchMore": "Daha Fazla Etkinlik Yükle",
	"AppActivity_EndofFeed": "Aktivitelerin Sonu",
	"AppActivity_DeleteUserNews": "Gönderiyi silmek için buraya tıklayın.",
	"AppActivity_ConfirmDeleteTitle": "Durum Gönderisini Sil",
	"AppActivity_ConfirmDeleteTitle_Desc": "Gönderiyi silmek istediğinizden emin misiniz? Bu eylem geri alınamaz.",
	"AppActivity_RecommendedGame": " bu oyunu inceledi",
	"AppActivity_RecommendedGame_ReadMore": "Daha Fazlasını Okuyun",
	"AppActivity_RatingDetails": "%1$s kişi bunu beğendi",
	"AppActivity_RatingDetails_1Other": "1 kişi bunu beğendi, %1$s",
	"AppActivity_RatingDetails_2Others": "%2$s ve %3$s dahil, %1$s kişi bunu beğendi",
	"AppActivity_RatingDetails_User": "Bunu beğendiniz",
	"AppActivity_RatingDetails_User_1Other": "Siz ve %2$s dahil, %1$s kişi bunu beğendi",
	"AppActivity_RatingDetails_User_2Others": "Siz, %2$s ve %3$s dahil, %1$s kişi bunu beğendi",
	"AppActivity_RatingDetails_PublishedFile": "%1$s beğeni",
	"AppActivity_RateUp": "Beğen",
	"AppActivity_ConfirmDeleteCommentTitle": "Yorumu Sil",
	"AppActivity_ConfirmDeleteCommentTitle_Desc": "Bu yorumu silmek istediğinizden emin misiniz? Bu eylem geri alınamaz.",
	"AppActivity_MakeCommentsVisible": "Önceki Yorumları Görüntüle (%1$s)",
	"AppActivity_Settings": "Ayarlar",
	"AppActivity_ViewComments": "Yorumları Görüntüle",
	"AppActivity_AddComments": "Yorum Ekle",
	"AppActivity_ContributeComments": "Yorum yap",
	"AppActivity_SteamTradingCards_EarnedTradingCards": " koleksiyon kartları kazandı",
	"AppActivity_SteamTradingCards_EarnedTradingCard": " bir koleksiyon kartı kazandı",
	"AppActivity_SteamTradingCards_EarnedBoosterPack": " bir hızlandırma paketi kazandı",
	"AppActivity_SteamTradingCards_BadgeCrafted": " bir rozet işledi",
	"AppActivity_ViewLatestNews": "En Son Çıkan Haberleri Görüntüle",
	"AppActivity_EventType_GameUpdate": "Oyun Güncellemesi",
	"AppSpotlight_PostGameSummary": "Oyun Sonrası Özeti",
	"AppDetails_Shortcut_Explanation": "Steam dışı bir mod ya da kısayol olduğu için %1$s ile ilgili bazı detaylı bilgiler mevcut değil. Steam bu oyunu sizin için başlatmaya devam edecek ve çoğu durumda Steam oyun içi arayüzünü kullanabileceksiniz.",
	"AppDetails_Takeover_Update_Header": "Belki kaçırmışsınızdır diye",
	"AppDetails_Takeover_Update_ViewAll": "%1$s güncellemenin tamamını görüntüle",
	"AppDetails_Takeover_Update_ReadMore": "Daha Fazlasını Okuyun",
	"AppDetails_Takeover_DLC_Header": "Yeni öğeler eklendi",
	"AppDetails_Takeover_DLC_ViewInStore": "%1$s mağaza sayfasını görüntüle",
	"AppDetails_Takeover_Achievements_Header": "%2$s oynadınız ve yeni bir başarım kazandınız...",
	"AppDetails_Takeover_Achievements_Header_Plural": "%2$s oynadınız ve yeni başarımlar kazandınız...",
	"AppDetails_Takeover_TradingCards_Header": "%2$s oynadınız ve yeni bir öğe kazandınız...",
	"AppDetails_Takeover_TradingCards_Header_Plural": "%2$s oynadınız ve yeni öğeler kazandınız...",
	"AppDetails_ViewMyInventory": "Envanterimi Görüntüle",
	"AppDetails_ViewInMyInventory": "Envanterimde görüntüle",
	"AppPortraitHover_DownloadStatusTitle": "İndiriliyor",
	"AppPortraitHover_DownloadStatusTitle_Update": "Güncelleme İndiriliyor",
	"AppPortraitHover_DaysSinceLastUpdate": "Güncelleme: %1$s",
	"AppPortraitHover_FriendsPlaying": "%1$s Arkadaş Oynuyor",
	"MajorUpdate_ViewDetails": "Detayları Görüntüle",
	"MajorUpdate_NextUpdate": "Sonraki Güncelleme",
	"MajorUpdate_PostTime": "%1$s gün önce %2$s:%3$s saatinde yayınlandı",
	"MajorUpdate_PostTimeToday": "Bugün %1$s:%2$s saatinde yayınlandı",
	"MajorUpdate_WatchNow": "SteamTV'de Görüntüle",
	"MajorUpdate_Type0": "Büyük Güncelleme",
	"MajorUpdate_Type1": "Canlı Yayın",
	"MajorUpdate_Type14": "Büyük Güncelleme",
	"MajorUpdate_Context_RemoveThisUpdate": "Bu Güncellemeyi Kaldır",
	"MajorUpdate_Context_ResetHiddenUpdates": "Tüm Güncellemeleri Tekrar Göster",
	"MajorUpdate_Context_WhyAmISeeingThis": "Neden Bunu Görüyorum?",
	"MajorUpdate_Context_WhyAmISeeingThis_Text": "Bu, kütüphanenizde olan ve 20 saatten fazla oynadığınız bir oyun için büyük bir güncellemedir.",
	"MajorUpdate_Context_WhyAmISeeingThis_Close": "Kapat",
	"CustomArt_ErrorTitle": "Hata",
	"CustomArt_BadFileType": "Dosyanız JPG veya PNG formatında olmalıdır.",
	"CustomArt_UnknownError": "Çiziminiz kaydedilirken bir hata meydana geldi.",
	"AppDetails_LibraryInUse": "Kütüphaneyi şu kişi kullanıyor:",
	"AppDetails_InSharedLibrary": "Şu kişinin kütüphanesinden:",
	"FriendContextMenu_OpenFriends": "Arkadaşları ve Sohbeti Aç",
	"FriendContextMenu_ViewProfile": "Profili Görüntüle",
	"Generic_ScrollToTop": "En Üste Git",
	"Generic_ViewGameDetails": "Oyunu kütüphanede görüntüle",
	"GameDetails_CollectionContext_GoTo": "Koleksiyona git",
	"GameDetails_CollectionContext_Remove": "Koleksiyondan kaldır",
	"ArtworkModal_ViewAll": "Tüm ekran görüntülerini görüntüle",
	"ArtworkModal_FileSize": "Dosya Boyutu",
	"ArtworkModal_Posted": "Yayınlandı",
	"ArtworkModal_Size": "Boyut",
	"ArtworkModal_CreatedBy": "Oluşturan:",
	"ArtworkModal_ScrollForMore": "Yorumlar için aşağı kaydırın",
	"CommunityItem_Menu_Report": "Şikâyet Et",
	"ReportItem_Title": "Bu öğeyi şikâyet et",
	"ReportItem_Description": "Lütfen bu öğenin Steam Kullanım Şartlarını ne şekilde ihlâl ettiğini açıklayın. Lütfen, ilgili bilgi ve bağlantıları da eklemeyi unutmayın. Bu işlem geri alınamaz.",
	"ReportItem_Description_Line2": "Şikâyet edilen öğeler kütüphane sayfanızda gösterilmez.",
	"ReportItem_DMCA": "Telif hakkı sahibiyseniz ve telif hakkı ihlâlini bildirmek istiyorsanız DMCA uyumlu telif hakkı ihlâli formuna %1$s ulaşabilirsiniz.",
	"ReportItem_DMCA_LinkText": "buradan",
	"ReportItem_Error": "İsteğiniz sunucularımıza iletilirken bir hata meydana geldi. Lütfen daha sonra tekrar deneyin.",
	"ReportItem_SubmitReport": "Şikâyeti Gönder",
	"Showcase_AddNewShowcase": "Yeni bir raf ekle",
	"Showcase_DeleteShowcase": "Bu rafı kaldır",
	"Showcase_SelectCategory": "Bir raf seç",
	"Showcase_EmptyShowcaseHint": "Bu rafta gösterilecekleri seçin. Rafı aynı şekilde bu kısımdan değiştirebilir veya silebilirsiniz.",
	"Showcase_GoToCollection": "Koleksiyona git",
	"Showcase_GoToAllCollections": "Tüm koleksiyonlara git",
	"Showcase_AllYourGames": "Tüm Oyunlar",
	"Showcase_AllCollections": "Koleksiyon Görünümü",
	"Showcase_RecentGames": "Son Oyunlar",
	"Playtime_TwoWeeks_Minutes": "Yakın zamanda %1$s dakika oynadı",
	"Playtime_TwoWeeks_Hours": "Yakın zamanda %1$s saat oynadı",
	"Playtime_Total_Minutes": "Toplam %1$s dakika oynadı",
	"Playtime_Total_Hours": "Toplam %1$s saat oynadı",
	"Playtime_Minutes": "%1$s dakika",
	"Playtime_Hours": "%1$s saat",
	"Playtime_Recently": "Yakın zamanda %1$s oynadı",
	"Playtime_Total": "Toplam %1$s oynandı",
	"GameList_Search_NoResults_Title": "Aradığınız şeyi bulamıyor musunuz?",
	"GameList_Search_NoResults_Link": "Steam mağazasında arayın",
	"StreamingClient_Select_ThisMachine": "Bu makine",
	"Beta_BetaTag": "BETA",
	"Beta_Changelist": "Değişiklik Listesi",
	"Beta_GiveFeedback": "Geri Bildirimde Bulunun",
	"ContextMenu_SaveScreenshot": "Ekran görüntüsünü farklı kaydet..."
}
