{
	"Generic_Okay": "확인",
	"Generic_Close": "닫기",
	"Generic_Open": "열기",
	"Generic_GotIt": "확인",
	"Generic_Share": "공유",
	"Generic_Upload": "업로드",
	"Generic_Delete": "삭제",
	"Privacy_Public": "전체 공개",
	"Privacy_FriendsOnly": "친구에게만 공개",
	"Privacy_Private": "비공개",
	"AppType_0": "유효하지 않음",
	"AppType_1": "게임",
	"AppType_2": "소프트웨어",
	"AppType_4": "도구",
	"AppType_20": "DLC",
	"AppType_800": "비디오",
	"AppType_2000": "사운드트랙",
	"AppType_Singular_0": "유효하지 않음",
	"AppType_Singular_1": "게임",
	"AppType_Singular_2": "애플리케이션",
	"AppType_Singular_4": "도구",
	"AppType_Singular_20": "DLC",
	"AppType_Singular_800": "비디오",
	"AppType_Singular_2000": "음악",
	"AppType_Singular_8000": "만화",
	"AppType_Singular_40000000": "바로가기",
	"FilterEdit_SavedFilters": "저장된 필터",
	"FilterEdit_FirstColumnHeader": "필터 유형",
	"FilterEdit_Customize": "사용자 지정",
	"FilterEdit_SearchModeHeader": "고급 필터",
	"FilterEdit_CollectionModeHeader": "모음집 필터 수정",
	"CollectionEdit_CollectionNameField": "모음집 이름:",
	"CollectionEdit_RenameButton": "모음집 이름 변경",
	"Collection_DynamicCollection": "동적 모음집",
	"FilterEdit_AdvancedTooltip": "장르, 게임 기능 등으로 게임 목록을 세분화하는 고급 필터링 옵션입니다.",
	"Collection_FreezeDynamicCollection_Button": "스냅샷",
	"Collection_FreezeDynamicCollection_ToolTip": "이 동적 모음집을 간단 모음집으로 변경하고, 현재 게임 목록을 고정시킵니다.",
	"Collection_FreezeDynamicCollection_DialogTitle": "스냅샷 모음집",
	"Collection_FreezeDynamicCollection_Confirmation": "이 모음집을 전환할까요? 라이브러리에 일치하는 게임을 추가해도 더 이상 동적으로 업데이트되지 않게 됩니다.",
	"Collection_ResetDialogTitle": "모음집 초기화",
	"Collection_ResetConfirmation": "모음집 목록을 초기화하고 이전 카테고리를 다시 불러올까요?",
	"Collection_AfterResetSummary_NoCollections": "초기화 시 모음집이 사라집니다.",
	"Collection_AfterResetSummary_CountAndNames": "초기화 시 다음 %1$s개의 모음집이 남습니다: %2$s",
	"Collection_ResetFailed": "모음집을 초기화할 수 없습니다",
	"FilterEdit_SelectedFilters": "선택한 필터",
	"FilterEdit_SaveCollectionNameInputPrompt": "모음집의 이름을 입력하세요",
	"FilterEdit_SaveOverwrite": "'%1$s' 모음집이 이미 존재합니다. 덮어쓸까요?",
	"FilterEdit_SaveCollection": "모음집으로 저장",
	"FilterEdit_SaveDynamicCollectionWithIcon": "%1$s 동적 모음집으로 저장",
	"FilterEdit_SaveDynamicCollectionNoIcon": "동적 모음집으로 저장",
	"FilterEdit_SaveCollectionVerbose": "나중에 다시 사용할 수 있도록 이 검색을 모음집으로 저장하세요. 모음집은 언제든지 수정하거나 이름을 변경하거나 삭제할 수 있으며, 항목을 끌어다 놓거나 뺄 수 있습니다.",
	"FilterEdit_SaveStandardCollectionButtonDesc": "모음집으로 라이브러리를 간단하게 정리할 수 있습니다. 타이틀을 모음집으로 끌어다 놓거나 타이틀을 마우스로 오른쪽 클릭해 기존 모음집에 추가하세요.",
	"FilterEdit_SaveDynamicCollectionButtonDesc": "동적 모음집은 필터를 사용하여 라이브러리의 규모가 커짐에 따라 업데이트되는 모음집을 만듭니다.",
	"FilterEdit_SelectCollectionType": "모음집 유형 선택",
	"FilterEdit_SelectCollectionTypeButtonCreate": "모음집 만들기",
	"FilterEdit_SelectCollectionTypeButtonCreateDynamic": "동적 모음집 만들기",
	"FilterEdit_RequiredField": "(필수)",
	"FilterEdit_SearchPrompt": "이름으로 검색",
	"FilterEdit_ClearSearch": "검색 종료",
	"FilterEdit_SearchResults": "검색 결과",
	"FilterEdit_CollectionsHiddenPromptTitle": "모음집이 숨겨져 있음",
	"FilterEdit_CollectionsHiddenPrompt": "게임 목록 보기를 변경하여 새로운 모음집을 표시할까요?",
	"FilterEdit_AcceptGameListViewChange": "네, 모음집을 표시합니다",
	"FilterEdit_RejectGameListViewChange": "아니요, 변경하지 않습니다",
	"AdvancedSearch_PaneTitle": "유형으로 검색",
	"AdvancedSearch_PlayerSection": "플레이어",
	"AdvancedSearch_HardwareSection": "하드웨어 지원",
	"AdvancedSearch_FeatureSection": "기능",
	"AdvancedSearch_StateSection": "플레이 상태",
	"AdvancedSearch_GenreSection": "장르",
	"AdvancedSearch_StoreTagSection": "상점 태그",
	"AdvancedSearch_StoreTagPrompt": "태그 입력",
	"FilterCategory_1": "상태",
	"FilterCategory_Features": "기능",
	"FilterCategory_3": "카테고리",
	"FilterCategory_4": "상점 태그",
	"FilterCategory_Type": "유형",
	"FilterCategory_Genre": "장르",
	"FilterCategory_PlayState": "상태",
	"FilterElement_VR": "VR",
	"FilterElement_Tooltip_VR": "VR 하드웨어를 지원하는 게임을 포함합니다.",
	"FilterElement_Installed": "로컬로 설치됨",
	"FilterElement_Tooltip_Installed": "이 컴퓨터에 설치된 게임을 포함합니다.",
	"FilterElement_ReadyToPlay": "플레이 준비 완료",
	"FilterElement_Tooltip_ReadyToPlay": "로컬로 플레이할 수 있거나 다른 컴퓨터에서 스트리밍할 수 있는 게임을 포함합니다.",
	"FilterElement_PlayedPreviously": "플레이한 적 있음",
	"FilterElement_Tooltip_PlayedPreviously": "이미 플레이한 적이 있는 게임을 포함합니다.",
	"FilterElement_Unplayed": "플레이한 적 없음",
	"FilterElement_Tooltip_Unplayed": "아직 플레이해 본 적이 없는 게임을 포함합니다.",
	"FilterElement_FullControllerSupport": "컨트롤러(완벽 지원)",
	"FilterElement_Tooltip_FullControllerSupport": "게임 컨트롤러를 완벽 지원하는 게임을 포함합니다.",
	"FilterElement_PartialControllerSupport": "컨트롤러(부분 지원)",
	"FilterElement_Tooltip_PartialControllerSupport": "컨트롤러로 플레이할 수 있지만 설치나 일부 상호 작용에 키보드와 마우스가 필요한 게임을 포함합니다.",
	"FilterElement_VRSupported": "VR 지원",
	"FilterElement_TradingCards": "트레이딩 카드",
	"FilterElement_Tooltip_TradingCards": "Steam 트레이딩 카드 기능이 있는 게임을 포함합니다.",
	"FilterElement_Workshop": "창작마당",
	"FilterElement_Tooltip_Workshop": "Steam 창작마당을 지원하는 게임을 포함합니다.",
	"FilterElement_Achievements": "도전 과제",
	"FilterElement_Tooltip_Achievements": "Steam 도전 과제가 있는 게임을 포함합니다.",
	"FilterElement_SinglePlayer": "싱글플레이어",
	"FilterElement_Tooltip_SinglePlayer": "싱글플레이어 모드를 지원하는 게임을 포함합니다.",
	"FilterElement_MultiPlayer": "멀티플레이어",
	"FilterElement_Tooltip_MultiPlayer": "멀티플레이어 모드를 지원하는 게임을 포함합니다.",
	"FilterElement_CoOp": "협동",
	"FilterElement_Tooltip_CoOp": "협동 멀티플레이어 모드를 지원하는 게임을 포함합니다.",
	"FilterElement_GenreAction": "액션",
	"FilterElement_Tooltip_GenreAction": "액션 게임을 포함합니다.",
	"FilterElement_GenreAdventure": "어드벤처",
	"FilterElement_Tooltip_GenreAdventure": "어드벤처 게임을 포함합니다.",
	"FilterElement_GenreCasual": "캐주얼",
	"FilterElement_Tooltip_GenreCasual": "캐주얼 게임을 포함합니다.",
	"FilterElement_GenreIndie": "인디",
	"FilterElement_Tooltip_GenreIndie": "인디 게임을 포함합니다.",
	"FilterElement_GenreMMO": "MMO",
	"FilterElement_Tooltip_GenreMMO": "대규모 멀티플레이어 게임을 포함합니다.",
	"FilterElement_GenreRacing": "레이싱",
	"FilterElement_Tooltip_GenreRacing": "레이싱 게임을 포함합니다.",
	"FilterElement_GenreRPG": "RPG",
	"FilterElement_Tooltip_GenreRPG": "롤 플레잉 게임을 포함합니다.",
	"FilterElement_GenreSimulation": "시뮬레이션",
	"FilterElement_Tooltip_GenreSimulation": "시뮬레이션 게임을 포함합니다.",
	"FilterElement_GenreSports": "스포츠",
	"FilterElement_Tooltip_GenreSports": "스포츠 게임을 포함합니다.",
	"FilterElement_GenreStrategy": "전략",
	"FilterElement_Tooltip_GenreStrategy": "전략 게임을 포함합니다.",
	"FilterElement_Tooltip_StoreTag": "'%1$s' 상점 태그가 붙은 게임을 포함합니다.",
	"FilterElement_SteamCloud": "Steam 클라우드",
	"FilterElement_Tooltip_SteamCloud": "Steam 클라우드에 저장하는 게임을 포함합니다.",
	"FilterElement_RemotePlayTogether": "Remote Play Together",
	"FilterElement_Tooltip_RemotePlayTogether": "Remote Play Together를 지원하는 게임을 포함합니다.",
	"CollectionViewHeader_Tooltip_ManuallyAddedApp": "모음집에 직접 추가한 게임입니다.",
	"CollectionViewHeader_Tooltip_ManuallyRemovedApp": "모음집에서 직접 제거한 게임입니다.",
	"CollectionViewHeader_Tooltip_ManuallyRemovedApps_WithCount": "이 모음집에서 %1$s개의 게임이 제거되었습니다.",
	"CollectionViewHeader_ManuallyRemovedApps_WithCount": "%1$s개 제거됨",
	"CollectionView_EmptyReadOnlyCollection": "표시할 내용이 없습니다",
	"CollectionView_EmptyDynamicCollection_Line1": "이 필터와 일치하는 게임이 없습니다!",
	"CollectionView_EmptyDynamicCollection_Line2": "이 모음집을 작성하려면 필터를 변경하거나 여기에 게임을 끌어다 놓으세요.",
	"CollectionView_EmptyCollection": "이 모음집을 작성하려면 게임을 끌어다 놓으세요.",
	"CollectionView_EmptyCollection_BecauseFilter": "선택한 보기 필터로 인해 이 모음집에서 %1$s개의 게임이 표시되지 않습니다.",
	"CollectionView_EmptyCollection_BecauseFilter_Plural": "선택한 보기 필터로 인해 이 모음집에서 %1$s개의 게임이 표시되지 않습니다.",
	"CollectionView_MissingCollection": "모음집이 없습니다.",
	"CollectionView_GamesExcluded": "+%1$s",
	"CollectionView_GamesExcluded_Desc": "플레이할 준비가 안 된 타이틀",
	"AllCollectionsView_Title": "내 모음집",
	"AllCollectionsView_InfoIcon": "%1$s을 만들어 게임을 마음대로 정리하거나, %2$s을 만들어 필터별로 게임을 분류하세요. %3$s",
	"AllCollectionsView_InfoIconCollections": "모음집",
	"AllCollectionsView_InfoIconDynamicCollections": "동적 모음집",
	"AllCollectionsView_InfoIconFav": "%1$이 항상 페이지 상단에 표시됩니다.",
	"AllCollectionsView_InfoIconFavorites": "즐겨찾기",
	"AllCollectionsView_AddCollection": "새로운 모음집 만들기",
	"AllCollectionsView_DragToAddCollection": "새로운 모음집을 만들려면 여기에 게임을 끌어다 놓으세요",
	"GameList_Home": "홈",
	"GameList_Search": "검색",
	"GameList_Category_Uncategorized": "카테고리 없음",
	"GameList_Category_Favorites": "즐겨찾기",
	"GameList_Category_Hidden": "숨김",
	"GameList_Category_Hidden_Tooltip": "숨긴 게임은 따로 검색하지 않는 이상 표시되지 않습니다. 숨긴 게임은 상단의 '보기' 메뉴에서 모두 확인할 수 있습니다.",
	"GameList_Category_YourCollections": "내 모음집",
	"GameList_Category_SharedLibraries": "공유된 라이브러리",
	"GameList_SectionHeader_SearchResults": "검색 및 필터링 결과",
	"GameList_SectionHeader_AddedManually": "직접 추가",
	"GameList_SectionHeader_RemovedManually": "직접 제거",
	"GameList_SectionHeader_NoRecentActivity": "기록된 활동 없음",
	"GameList_View_Collections": "내 모음집",
	"GameList_View_ThisCollection": "이 모음집 보기",
	"GameList_View_OneCollection": "모음집 보기",
	"GameList_View_SearchResults": "검색 결과",
	"GameList_View_ShowAllCollections": "전체 모음집 표시",
	"GameList_View_GroupByCollections": "모음집별 그룹",
	"GameList_View_ExitSearch": "검색 종료",
	"GameList_View_All": "전체",
	"GameList_View_Recent": "최근",
	"GameList_View_SortByRecent": "최근 활동별로 정렬",
	"GameList_View_ShowOnlyReadyToPlay": "플레이할 준비가 된 게임만 표시",
	"GameList_View_ShowingReadyToPlay": "플레이할 준비가 된 게임만 표시 중",
	"GameList_View_ShowingOnlyReadyToPlay": "플레이할 준비가 된 게임만 표시",
	"GameList_View_ShowOnlyVR": "VR 게임만 표시",
	"GameList_View_Platform_Linux": "Linux 지원 게임만 보기",
	"GameList_View_Platform_Apple": "macOS 지원 게임만 보기",
	"GameList_View_MyOwnGames": "내 게임",
	"GameList_View_GamesSharedByOther": "%1$s님의 게임",
	"GameList_View_NothingSelected": "없음",
	"GameList_View_NothingSelected_HelpText": "이 보기 필터와 일치하는 결과가 없습니다.",
	"GameList_Search_GamesCheckbox_Link": "게임 표시하기",
	"GameList_View_GroupSharedLibraries": "라이브러리별 그룹화",
	"GameList_View_GroupingDisabled_ToolTip": "이 보기에서는 그룹 짓기를 할 수 없습니다",
	"GameList_View_ReadyToPlay_ToolTip1": "• 이 기기에 설치됨",
	"GameList_View_ReadyToPlay_ToolTip2": "• 다른 기기에서 스트리밍할 수 있음",
	"GameList_Entry_ReadyToPlay_ToolTip": "다른 기기에서 스트리밍 예정",
	"GameList_Entry_Invalid_OSType": "현재 사용하고 계신 macOS(Catalina)에서는 이 게임과 같은 32비트 게임을 실행할 수 없습니다.",
	"GameList_Entry_Invalid_OSType2": "이 게임은 Steam Play를 지원하므로 Bootcamp 또는 PC를 통해 Windows에서 플레이할 수 있습니다.",
	"GameList_Entry_Invalid_OSType3": "더 알아보기.",
	"Shelf_SectionHeader_ExpandTooltip": "더 많은 행을 보려면 전시대를 여세요.",
	"Shelf_SectionHeader_ExpandTooltipFilter": "보기 필터로 인해 %1$s개의 아이템이 표시되지 않습니다. 더 많은 행을 보려면 전시대를 여세요.",
	"GameList_SectionHeader_AppCountToolTip": "보기 필터로 인해 %1$s개가 표시되지 않습니다. ",
	"GameList_SectionHeader_AppCountToolTipAllHidden": "보기 필터로 인해 표시할 아이템이 없습니다.",
	"CollectionAction_ViewOnlyThis": "이 모음집만 보기",
	"CollectionAction_ViewOnlyThisFavorites": "즐겨찾기만 보기",
	"CollectionAction_ViewOnlyThisUncategorized": "카테고리가 없는 항목만 보기",
	"CollectionAction_Collapse": "닫기",
	"CollectionAction_CollapseAll": "모두 닫기",
	"CollectionAction_CollapseAllCollections": "모음집 모두 닫기",
	"CollectionAction_Expand": "열기",
	"CollectionAction_ExpandAll": "모두 열기",
	"CollectionAction_ExpandAllCollections": "모음집 모두 열기",
	"CollectionAction_Manage": "관리",
	"CollectionAction_Edit": "모음집 필터 수정",
	"CollectionAction_Rename": "모음집 이름 변경",
	"CollectionAction_Delete": "모음집 삭제",
	"CollectionAction_DeleteDialog": "모음집 삭제",
	"CollectionAction_ConfirmDelete": "'%1$s' 모음집을 영구적으로 삭제할까요?",
	"CollectionAction_SaveFailed": "'%1$s' 모음집을 저장할 수 없습니다",
	"CollectionAction_CannotOverwrite": "'%1$s' 모음집을 덮어쓸 수 없습니다. 새로운 이름을 고르세요.",
	"CollectionAction_DeleteFailed": "'%1$s' 모음집을 삭제할 수 없습니다",
	"LibraryHome_FriendsActivity": "친구 활동",
	"LibraryHome_RecentGames": "최근 게임",
	"LibraryHome_NewUpdates": "새로운 업데이트",
	"LibraryHome_YourCollection": "내 라이브러리 전체",
	"LibraryHome_RecentFriendsActivity": "최근 친구 활동",
	"LibraryHome_NewUpdates_LoweredPriority": "이제 %1$s에 대한 업데이트를 덜 표시합니다.",
	"LibraryHome_NewUpdates_RaisedPriority": "이제 %1$s에 대한 업데이트를 더 표시합니다.",
	"LibraryHome_NewUpdates_Undo": "취소",
	"LibraryHome_RecentFriendsActivity_Empty": "현재 친구 그룹에서 새롭거나 인기있는 활동이 없습니다. 전시대는 디스플레이할 내용이 없으면 자동 숨김 처리됩니다.",
	"WhatsNewSettings": "새로운 업데이트 설정",
	"WhatsNew": "새로운 업데이트",
	"WhatsNewFeatureExplainer": "새로운 업데이트는 개발자가 업데이트나 토너먼트, DLC, 이벤트, 또는 관련 뉴스를 게임 소유자 여러분과 공유하는 공간입니다. Steam은 여러분의 플레이 시간을 바탕으로, 최근에 플레이한 게임과 가장 관련성 있는 뉴스를 전해드립니다.",
	"WhatsNewFeatureExplainer2": "몇 시간 이상 플레이한 적이 없고 마지막으로 활동한 후 오랜 시간이 지난 일부 게임은 '새로운 업데이트'에서 자동으로 제외됩니다.",
	"WhatsNewVisibilitySettings": "노출 설정",
	"WhatsNewSettings_ShowOnlyForRecentlyPlayed": "최근 90일 이내에 플레이한 게임만 표시하기",
	"WhatsNewSettings_ShowOnlyForRecentlyPlayed_Explainer": "(개별 게임의 빈도는 뉴스 항목을 오른쪽 클릭하여 조정할 수 있습니다.)",
	"WhatsNewSettings_ShowOnlyGameUpdates": "제품 업데이트만 표시하고 다른 유형의 이벤트 및 뉴스는 제외",
	"WhatsNewSettings_ShowOnlyGameUpdates_Explainer": "(개별 게임의 빈도는 뉴스 항목을 오른쪽 클릭하여 조정할 수 있습니다.)",
	"WhatsNewPrioritySettings": "우선 순위 설정",
	"WhatsNewPriorityExplainer": "(개별 게임에 대한 새로운 업데이트 더 보기 또는 덜 보기를 설정할 수 있습니다. 항목을 오른쪽 클릭하면 옵션이 표시됩니다.)",
	"WhatsNewYouHaveAskedToShowLessFor": "덜 보기로 지정한 게임:",
	"WhatsNewYouHaveNothingShowingLess": "아직 덜 보기로 지정하신 게임이 없습니다.",
	"WhatsNewYouHaveAskedToShowMoreFor": "더 보기로 지정한 게임:",
	"WhatsNewYouHaveNothingShowingMore": "아직 더 보기로 지정하신 게임이 없습니다.",
	"WhatsNewYouHaveNItemsHidden": "새로운 업데이트에서 숨김 처리된 결과로 %1$s개의 게임이 라이브러리에서 숨김 처리되었습니다.",
	"Library_FriendsActivity_HotRightNowHeading": "지금 인기 있는 게임",
	"Library_FriendsActivity_HotRightNowHover": "많은 친구들이 지금 플레이하고 있는 게임입니다.",
	"Library_FriendsActivity_TrendingHeading": "떠오르는 게임",
	"Library_FriendsActivity_TrendingHover": "몇몇 친구들이 지난 주에 그 전 주보다 더 많이 플레이하고 있는 게임입니다.",
	"Library_FriendsActivity_BeingDiscussedHeading": "이야기 중인 게임",
	"Library_FriendsActivity_BeingDiscussedHover": "친구들이 스크린샷 또는 상태 메시지를 게시한 게임입니다.",
	"Library_FriendsActivity_RecentlyPurchasedHeading": "최근 구매한 게임",
	"Library_FriendsActivity_RecentlyPurchasedHover": "최근에 구매했으며, 친구들이 플레이하고 있는 게임입니다.",
	"Library_FriendsActivity_UnownedHeading": "새로운 게임",
	"Library_FriendsActivity_UnownedHover": "친구들 사이에서 인기가 있지만 내가 가지고 있지 않은 게임입니다.",
	"Library_FriendsActivity_PopularHeading": "인기 게임",
	"Library_FriendsActivity_PopularHover": "최근에 많은 친구들이 플레이하고 있는 게임입니다.",
	"Library_FriendsActivity_DontForgetHeading": "잊지마세요",
	"Library_FriendsActivity_DontForgetHover": "친구들은 플레이하고 있지만 나는 최근에 플레이하지 않은 게임입니다.",
	"Library_FriendsActivity_NewToGroupHeading": "친구가 새로 플레이하는 게임",
	"Library_FriendsActivity_NewToGroupHover": "최근에 친구들이 플레이하기 시작한 게임입니다.",
	"Library_FriendsActivity_ReturnedToGroupHeading": "다시 차례가 돌아온 게임",
	"Library_FriendsActivity_ReturnedToGroupHover": "친구들이 다시 플레이하기 시작한 게임입니다.",
	"Library_FriendsActivity_UnownedBanner": "Steam 상점에서 보기",
	"Library_FriendsActivity_UnownedMenu_Store": "상점",
	"Library_FriendsActivity_UnownedMenu_Hub": "커뮤니티 허브",
	"Library_FriendsActivity_UnownedMenu_Reviews": "평가",
	"Library_FriendsActivity_UnownedMenu_Discussions": "토론",
	"Library_Recent_NoRecentGames_GamesOwned": "게임이 (%1$s)개 있습니다.",
	"Library_Recent_NoRecentGames_StoreLink": "%1$s에서 게임을 찾아 추가하세요:",
	"Library_Recent_NoRecentGames_SteamStore": "Steam 상점",
	"Library_Recent_NoRecentGames_FreeToPlay": "무료 게임",
	"Library_Recent_NoRecentGames_GamesOnSale": "할인 중인 게임",
	"Library_Recent_NoRecentGames_NewReleases": "신규 출시",
	"Library_Recent_NoRecentGames_ActivateProduct": "제품 활성화",
	"Library_Recent_NoRecentGames_RedeemCode": "지갑 코드 등록",
	"Library_SortCollectionBy": "정렬 기준",
	"Library_SortByFavoritesFirst": "즐겨찾기 우선",
	"Library_SortByAlphabetical": "알파벳 순",
	"Library_SortByPctAchievementsComplete": "도전 과제 %개 완료",
	"Library_SortByLastUpdated": "마지막 업데이트",
	"Library_SortByHoursPlayed": "플레이 시간",
	"Library_SortByLastPlayed": "마지막 플레이",
	"Library_SortByReleaseDate": "출시 날짜",
	"Library_SortByAddedToLibrary": "라이브러리에 추가된 날짜",
	"Library_SortBySizeOnDisk": "디스크 크기",
	"Library_SortByMetacriticScore": "Metacritic 점수",
	"Library_SortByFriendsPlaying": "친구가 플레이하는 게임",
	"Library_SortBySteamReview": "Steam 평가",
	"Library_SortByPctAchievementsComplete_Tag": "%1$s% 완료",
	"Library_SortByPctAchievementsNoAchievements_Tag": "도전 과제 없음",
	"Library_InstalledOnlyCheck": "설치된 게임만",
	"GridSection_Favorites": "즐겨찾기",
	"GridSection_EverythingElse": "그 외 모두",
	"GridSection_Over100Hours": "100시간 이상",
	"GridSection_Over60Hours": "60시간 이상",
	"GridSection_Over40Hours": "40시간 이상",
	"GridSection_Over20Hours": "20시간 이상",
	"GridSection_Over10Hours": "10시간 이상",
	"GridSection_Over1Hour": "1시간 이상",
	"GridSection_LessThan1Hour": "1시간 미만",
	"GridSection_Over90Metacritic": "90 이상",
	"GridSection_Over80Metacritic": "80 이상",
	"GridSection_Over70Metacritic": "70 이상",
	"GridSection_Over50Metacritic": "50 이상",
	"GridSection_EverythingElseMetacritic": "그 외 모두",
	"GridSection_UnknownReleaseDate": "알 수 없음",
	"GridSection_GreaterThan100GB": "100GB 이상",
	"GridSection_GreaterThan50GB": "50GB 이상",
	"GridSection_GreaterThan20GB": "20GB 이상",
	"GridSection_LessThan20GB": "20GB 미만",
	"GridSection_NoSizeOnDisk": "크기 없음",
	"GridSection_NotInstalled": "설치 안 됨",
	"GridSection_MoreThan10YearsAgo": "10년 이상 이전",
	"GridSection_Never": "없음",
	"AppDetails_SectionTitle_Stream": "개발자 방송",
	"AppDetails_SectionTitle_Activity": "활동",
	"AppDetails_SectionTitle_Friends": "플레이한 친구들",
	"AppDetails_SectionTitle_Friends_Software": "사용한 친구들",
	"AppDetails_SectionTitle_Achievements": "도전 과제",
	"AppDetails_SectionTitle_TradingCards": "트레이딩 카드",
	"AppDetails_SectionTitle_Screenshots": "스크린샷",
	"AppDetails_SectionTitle_AdditionalContent": "추가 콘텐츠",
	"AppDetails_SectionTitle_Updates": "최근 이벤트 및 업데이트",
	"AppDetails_SectionTitle_DLC": "DLC",
	"AppDetails_SectionTitle_LastPlayed": "마지막 플레이",
	"AppDetails_SectionTitle_LastLaunched": "마지막 실행",
	"AppDetails_SectionTitle_PlayTime": "플레이 시간",
	"AppDetails_SectionTitle_UsageTime": "사용 시간",
	"AppDetails_SectionTitle_Workshop": "Steam 창작마당",
	"AppDetails_SectionTitle_Community": "커뮤니티 콘텐츠",
	"AppDetails_SectionTitle_Links": "링크",
	"AppDetails_SectionTitle_SignIn_Pre": "로그인",
	"AppDetails_SectionTitle_SignIn": "친구 활동을 보려면 %1$s",
	"AppDetails_SectionTitle_OpenFriends": "친구 목록 열기",
	"AppDetails_SectionTitle_OfflineMode": "오프라인 모드",
	"AppDetails_Broadcast_ViewOnWeb": "웹 브라우저에서 보기",
	"AppDetails_Community_Tooltip1": "이 섹션에는 커뮤니티가 제출한 스크린샷, 아트워크, 비디오, 가이드 등이 포함되어 있습니다.",
	"AppDetails_Community_Tooltip2": "이 콘텐츠를 '좋아요' 표시하고 공유하고 댓글을 남기거나 신고할 수 있습니다.",
	"AppDetails_Community_Guide": "커뮤니티 가이드",
	"AppDetails_Links_Store": "상점 페이지",
	"AppDetails_Links_Community": "커뮤니티 허브",
	"Bbcode_Originally_Posted_By": "원본 게시자:",
	"AppDetails_InOfflineMode": "Steam이 현재 오프라인 모드입니다. 오프라인 모드일 때는 활동이나 친구 등, Steam 라이브러리의 많은 기능들을 사용할 수 없게 됩니다. 이 콘텐츠는 온라인 상태에서 볼 수 있습니다.",
	"AppDetails_GoOnline": "온라인으로 전환",
	"AppDetails_PartnerEventFailedLoad": "이 이벤트를 불러올 수 없습니다",
	"GameAction_Stop": "정지",
	"GameAction_Cancel": "취소",
	"GameAction_Install": "설치",
	"GameAction_Uninstall": "제거",
	"GameAction_Play": "플레이",
	"GameAction_PlayMusic": "앨범 재생",
	"GameAction_Launch": "실행",
	"GameAction_PreLoad": "미리받기",
	"GameAction_Update": "업데이트",
	"GameAction_Download": "다운로드",
	"GameAction_Resume": "계속하기",
	"GameAction_Pause": "일시 정지",
	"GameAction_BorrowApp": "대여",
	"GameAction_PurchaseApp": "구매",
	"GameAction_GameProperties": "속성...",
	"GameAction_AddToFavorites": "즐겨찾기에 추가",
	"GameAction_RemoveFromFavorites": "즐겨찾기에서 제거",
	"GameAction_AddToHidden": "이 게임 숨기기",
	"GameAction_RemoveFromHidden": "숨김 목록에서 제거",
	"GameAction_RemoveGameLicense": "계정에서 제거",
	"GameAction_AddToFamilyGames": "가족 게임에 추가",
	"GameAction_RemoveFromFamilyGames": "가족 게임에서 제거",
	"GameAction_RemoveShortcut": "라이브러리에서 비 Steam 게임 삭제",
	"GameAction_AddToCollection": "추가",
	"GameAction_RemoveFromCollection": "제거",
	"GameAction_CreateDesktopShortcut": "바탕 화면 바로 가기 추가",
	"GameAction_BackUpFiles": "게임 파일 백업...",
	"GameAction_Stream": "스트리밍",
	"GameAction_Connect": "연결",
	"GameAction_SetCustomArtwork": "맞춤 아트워크 설정",
	"GameAction_ClearCustomArtwork": "맞춤 아트워크 지우기",
	"GameAction_ViewCDKeys": "CD 키",
	"GameAction_ControllerConfiguration": "컨트롤러 설정",
	"GameAction_Launching": "시작하는 중",
	"GameAction_RemoveAppFromCollection": "%2$s 모음집에서 %1$s 앱을 제거하려면 여기로 끌어다 놓으세요",
	"GameAction_RemoveAppFromMultipleCollections": "이 모음집에서 %1$s 앱을 제거하려면 여기로 끌어다 놓으세요",
	"GameAction_RemoveMultipleAppsFromCollection": "%1$s에서 제거하려는 앱을 여기로 끌어다 놓으세요",
	"GameAction_RemoveMultipleAppsFromMultipleCollections": "모음집에서 제거하려는 앱을 여기로 끌어다 놓으세요",
	"GameAction_NavigateToAllCollectionsWithDrag": "모음집 전체를 보려면 여기로 끌어다 놓으면서 길게 누르세요",
	"GameAction_AddToCollectionOption_NewCollection": "새 모음집...",
	"GameAction_NewCollectionDialogTitle": "새 모음집",
	"GameAction_Manage": "관리",
	"GameAction_Favorite": "즐겨찾기에 추가",
	"GameAction_UnFavorite": "즐겨찾기에 추가됨",
	"GameAction_ViewDetails": "정보 자세히 보기",
	"GameAction_BrowseLocalFiles": "로컬 파일 보기",
	"GameAction_ViewDetails_Collapse": "정보 간략히 보기",
	"GameAction_ViewDetails_ScrollUp": "맨 위로 스크롤",
	"GameActionPlural_Install": "선택 항목 설치",
	"GameActionPlural_Uninstall": "선택 항목 설치 제거",
	"GameActionPlural_PreLoad": "선택 항목 미리받기",
	"GameActionPlural_Update": "선택 항목 업데이트",
	"GameActionPlural_Download": "선택 항목 다운로드",
	"GameActionPlural_Resume": "선택 항목 다시 시작",
	"GameActionPlural_AddToFavorites": "즐겨찾기에 선택 항목 추가",
	"GameActionPlural_RemoveFromFavorites": "즐겨찾기에서 선택 항목 모두 제거",
	"GameActionPlural_AddToHidden": "선택 게임 숨기기",
	"GameActionPlural_RemoveFromHidden": "숨김 목록에서 선택 항목 모두 제거",
	"GameActionPlural_AddToFamilyGames": "가족 게임에 선택 항목 추가",
	"GameActionPlural_RemoveFromFamilyGames": "가족 게임에서 선택 항목 제거",
	"GameActionPlural_RemoveShortcut": "라이브러리에서 선택한 비 Steam 게임 삭제",
	"GameActionPlural_AddToCollection": "선택 항목 추가",
	"GameActionPlural_RemoveFromCollection": "선택 항목 제거",
	"GameActionPlural_CreateDesktopShortcut": "바탕 화면 바로 가기 추가",
	"GameActionPlural_BackUpFiles": "게임 파일 백업...",
	"PrePurchase_Preload_Title": "%1$s 지금 미리받기 가능",
	"PrePurchase_Preload_Desc": "잠금 해제되는 대로 게임을 플레이할 수 있도록 지금 게임 파일을 다운로드하세요!",
	"PrePurchase_PreloadComplete_Title": "%1$s 미리받기 완료",
	"PrePurchase_PreloadComplete_Desc": "게임이 잠금 해제되면 바로 플레이할 수 있습니다!",
	"PrePurchase_Install_Title": "%1$s 지금 설치 및 플레이 가능",
	"PrePurchase_Install_Desc": "지금 설치하고 플레이하세요!",
	"PrePurchase_PlayNow_Title": "%1$s 지금 플레이 가능",
	"PrePurchase_PlayNow_Desc": "지금 플레이하세요!",
	"DisplayStatus_Launching": "실행 중",
	"DisplayStatus_Uninstalling": "제거 중",
	"DisplayStatus_Installing": "설치 중",
	"DisplayStatus_Running": "실행 중",
	"DisplayStatus_Validating": "확인 중",
	"DisplayStatus_Updating": "업데이트 중",
	"DisplayStatus_Downloading": "다운로드 중",
	"DisplayStatus_Synchronizing": "Steam 클라우드와 동기화 중",
	"DisplayStatus_ReadyToInstall": "설치 준비 완료",
	"DisplayStatus_ReadyToPreload": "미리받기 준비 완료",
	"DisplayStatus_ReadyToLaunch": "실행 준비 완료",
	"DisplayStatus_RegionRestricted": "현재 지역에서 이용할 수 없음",
	"DisplayStatus_PresaleOnly": "이 아이템은 아직 사용할 수 없습니다",
	"DisplayStatus_InvalidPlatform": "지원 플랫폼:",
	"DisplayStatus_PreloadComplete": "미리받기 완료",
	"DisplayStatus_BorrowerLocked": "이 라이브러리는 현재 가족 공유로 이용할 수 없습니다",
	"DisplayStatus_UpdatePaused": "업데이트 일시 정지됨",
	"DisplayStatus_UpdateQueued": "업데이트 대기열에 추가됨",
	"DisplayStatus_UpdateRequired": "업데이트 필요",
	"DisplayStatus_UpdateDisabled": "Steam이 오프라인 모드이므로 업데이트할 수 없습니다. 이 게임의 업데이트를 완료하려면 온라인으로 전환하세요.",
	"DisplayStatus_DownloadPaused": "다운로드 일시 정지됨",
	"DisplayStatus_DownloadQueued": "다운로드 대기열에 추가됨",
	"DisplayStatus_DownloadRequired": "다운로드 필요",
	"DisplayStatus_DownloadDisabled": "Steam이 오프라인 모드이므로 다운로드할 수 없습니다. 이 게임의 다운로드를 완료하려면 온라인으로 전환하세요.",
	"DisplayStatus_LicensePending": "구매가 아직 완료되지 않았습니다.",
	"DisplayStatus_LicenseExpired": "라이선스 만료됨",
	"DisplayStatus_AvailForFree": "무료 이용 가능",
	"DisplayStatus_AvailToBorrow": "대여 가능",
	"DisplayStatus_AvailGuestPass": "게스트 패스 이용 가능",
	"DisplayStatus_Purchase": "구매 가능",
	"DisplayStatus_Preallocating": "공간을 미리 배정하는 중",
	"DisplayStatus_Committing": "확정 중",
	"DisplayStatus_Verifying": "확인 중",
	"DisplayStatus_Unpacking": "설치 중",
	"DisplayStatus_Compact_Launching": "실행 중",
	"DisplayStatus_Compact_Uninstalling": "제거 중",
	"DisplayStatus_Compact_Installing": "설치 중",
	"DisplayStatus_Compact_Running": "실행 중",
	"DisplayStatus_Compact_Validating": "확인 중",
	"DisplayStatus_Compact_Updating": "업데이트 중",
	"DisplayStatus_Compact_Downloading": "다운로드 중",
	"DisplayStatus_Compact_Synchronizing": "Steam 클라우드와 동기화 중",
	"DisplayStatus_Compact_ReadyToInstall": "설치 준비 완료",
	"DisplayStatus_Compact_ReadyToPreload": "미리받기 준비 완료",
	"DisplayStatus_Compact_ReadyToLaunch": "실행 준비 완료",
	"DisplayStatus_Compact_RegionRestricted": "이 지역에서 이용할 수 없음",
	"DisplayStatus_Compact_PresaleOnly": "게임이 아직 출시되지 않음",
	"DisplayStatus_Compact_InvalidPlatform": "이용 가능:",
	"DisplayStatus_Compact_ParentalBlocked": "Steam 자녀 보호 기능에 의해 차단됨",
	"DisplayStatus_Compact_PreloadComplete": "미리받기 완료",
	"DisplayStatus_Compact_BorrowerLocked": "가족 공유 기능을 사용할 수 없음",
	"DisplayStatus_Compact_UpdatePaused": "업데이트 일시 정지됨",
	"DisplayStatus_Compact_UpdateQueued": "업데이트 대기열 추가됨",
	"DisplayStatus_Compact_UpdateRequired": "업데이트 필요",
	"DisplayStatus_Compact_UpdateDisabled": "오프라인 모드에서는 업데이트할 수 없습니다.",
	"DisplayStatus_Compact_DownloadPaused": "다운로드 일시 정지됨",
	"DisplayStatus_Compact_DownloadQueued": "다운로드 대기열에 추가됨",
	"DisplayStatus_Compact_DownloadRequired": "다운로드 필요",
	"DisplayStatus_Compact_DownloadDisabled": "오프라인 모드에서는 다운로드할 수 없습니다.",
	"DisplayStatus_Compact_LicensePending": "구매 완료 중",
	"DisplayStatus_Compact_LicenseExpired": "라이선스 만료됨",
	"DisplayStatus_Compact_AvailForFree": "무료 이용 가능",
	"DisplayStatus_Compact_AvailToBorrow": "대여 가능",
	"DisplayStatus_Compact_AvailGuestPass": "게스트 패스 이용 가능",
	"DisplayStatus_Compact_Purchase": "구매 가능",
	"DisplayStatus_ReleaseDate": "출시 날짜: %1$s",
	"DisplayStatus_CustomReleaseDate": "예정된 출시 날짜: %1$s",
	"Downloads_State_Bytes_Of_Bytes": "%1$s/%2$s",
	"Downloads_State_None": "",
	"Downloads_State_Reconfiguring": "다운로드 시작 중",
	"Downloads_State_Validating": "파일 인증 중",
	"Downloads_State_AddingFiles": "파일 복사 중",
	"Downloads_State_Preallocating": "공간 확보 중",
	"Downloads_State_Downloading": "",
	"Downloads_State_Staging": "",
	"Downloads_State_Committing": "완료 중",
	"Downloads_State_Verifying": "다운로드 확인 중",
	"Downloads_State_Stopping": "다운로드 중지 중",
	"Downloads_State_Running": "",
	"Downloads_State_SecondsRemaining": "%1$s초 남음",
	"Downloads_State_MinutesRemaining": "%1$s분 남음",
	"Downloads_State_Calculating": "계산 중..",
	"LaunchApp_Action_UpdatingAppInfo": "설정 확인 중",
	"LaunchApp_Action_ShowEula": "EULA(최종 사용자 사용권 계약) 표시 중",
	"LaunchApp_Action_DownloadingDepots": "콘텐츠 다운로드 중 (%1$s%)",
	"LaunchApp_Action_DownloadingWorkshop": "창작마당 다운로드 중 (%1$s%)",
	"LaunchApp_Action_UpdatingDRM": "실행 파일 업데이트 중",
	"LaunchApp_Action_GettingLegacyKey": "제품 키 업데이트 중",
	"LaunchApp_Action_RunningInstallScript": "설치 스크립트 실행 중 (%1$s)",
	"LaunchApp_Action_SynchronizingCloud": "클라우드 동기화 중",
	"LaunchApp_Action_VerifyingFiles": "실행 파일 확인 중",
	"LaunchApp_Action_CreatingProcess": "실행 파일 시작 중",
	"LaunchApp_Action_WaitingGameWindow": "실행 파일 시작 중",
	"LaunchApp_Action_DelayLaunch": "실행 지연 중 (%1$s%)",
	"AppDetails_TitleUpdatedSincePlayed": "이 게임은 마지막으로 플레이한 이후로 새롭게 업데이트되었습니다",
	"AppDetails_TitleUpdatedSincePlayedLink": "업데이트 내용 보기",
	"AppDetails_BadgeLevel": "레벨 %1$s, 경험치: %2$s",
	"AppDetails_UnearnedBadgeXP": "%1$sXP",
	"AppDetails_BadgeLevelNoXP": "레벨 %1$s",
	"AppDetails_Review_ViewOrEdit": "평가 수정",
	"AppDetails_Review_YourReview": "내 평가",
	"AppDetails_Review_Ignore_Stale_Reviews": "이 평가를 업데이트하라는 알림을 받지 않습니다.",
	"AppDetails_Review_Unignore_Stale_Reviews": "이 게임에 대한 오래된 평가가 강조 표시되는 것을 허용합니다.",
	"AppDetails_Review_RecommendGame": "이 게임을 추천하시겠어요?",
	"AppDetails_Review_RecommendSoftware": "이 소프트웨어를 추천하시겠어요?",
	"AppDetails_Review_WriteReview": "%1$s에 대한 평가 작성하기",
	"AppDetails_Review_PlayedForTime": "플레이 시간: %1$s",
	"AppDetails_Review_PlayedForTime_Software": "타이틀 사용 시간: %1$s",
	"AppDetails_Review_RecommendGameButton_Yes": "예",
	"AppDetails_Review_RecommendGameButton_No": "아니요",
	"AppDetails_Review_PlaytimeAtReview": "평가 당시 플레이 시간: %1$s",
	"AppDetails_Review_PlaytimeAtReview_Software": "평가 당시 사용 시간: %1$s",
	"AppDetails_Review_NotRecommended": "비추천",
	"AppDetails_Review_Recommended": "추천",
	"AppDetails_Review_AdditionalPlaytime": "이 평가를 작성한 이후로 %1$s 플레이했습니다.",
	"AppDetails_Review_AdditionalPlaytime_Software": "이 평가를 작성한 이후로 %1$s 사용했습니다.",
	"AppDetails_Review_ChangedYourMind": "마음이 바뀌셨나요?",
	"AppDetails_Review_IHaveNotChangedMyMind": "아니요, 바뀌지 않았습니다",
	"AppDetails_Review_UpVotes": "좋아요:",
	"AppDetails_Review_Comments": "댓글:",
	"AppDetails_Review_ViewAll": "나의 모든 평가 보기",
	"AppDetails_Review_ViewAllByFriend": "%1$s의 모든 평가 보기",
	"OverflowBox_Action_Collapse": "간단히 보기",
	"OverflowBox_Action_Expand": "더 보기",
	"OverflowBox_More": "(그 외 %1$s명)",
	"AppDetails_FriendsInGameNow": "친구 %1$s명이 지금 플레이하고 있습니다",
	"AppDetails_FriendsInGameNow_Plural": "친구 %1$s명이 지금 플레이하고 있습니다",
	"AppDetails_FriendsPlayedRecently": "친구 %1$s명이 최근 플레이했습니다",
	"AppDetails_FriendsPlayedRecently_Plural": "친구 %1$s명이 최근 플레이했습니다",
	"AppDetails_FriendsPlayedRecentlyExpand": "최근에 플레이한 친구 모두 보기",
	"AppDetails_FriendsPlayed": "이전에 친구 %1$s명이 플레이함",
	"AppDetails_FriendsPlayed_Plural": "이전에 친구 %1$s명이 플레이함",
	"AppDetails_FriendsPlayedExpand": "이전에 플레이한 친구 모두 보기",
	"AppDetails_FriendsMore": "(그 외 %1$s명)",
	"AppDetails_FriendsLess": "간단히 보기",
	"AppDetails_FriendsWishlisted": "%1$s명의 친구가 찜 목록에 %2$s 추가함",
	"AppDetails_FriendsWishlisted_Plural": "%1$s명의 친구들이 찜 목록에 %2$s 추가함",
	"AppDetails_FriendsWishlistExpand": "찜 목록 추가 제품 모두 표시하기",
	"AppDetails_Friends_ViewAll": "이 게임을 하는 친구들 모두 표시하기",
	"AppDetails_GameInfo": "게임 정보",
	"AppDetails_Publisher": "배급사:",
	"AppDetails_Developer": "개발사:",
	"AppDetails_Franchise": "프랜차이즈:",
	"AppDetails_ReleaseDate": "출시 날짜:",
	"AppDetails_LastUpdate": "마지막 로컬 업데이트:",
	"AppDetails_OriginalReleaseDate": "원래 발매일:",
	"AppDetails_Feature_SinglePlayer": "싱글플레이어",
	"AppDetails_Feature_MultiPlayer": "멀티플레이어",
	"AppDetails_Feature_CoOp": "협동 플레이",
	"AppDetails_Feature_SteamAchievements": "도전 과제",
	"AppDetails_Feature_SteamCloud": "클라우드 저장",
	"AppDetails_Feature_FullController": "컨트롤러 완벽 지원",
	"AppDetails_Feature_PartialController": "컨트롤러 일부 지원",
	"AppDetails_Feature_SteamWorkshop": "Steam 창작마당",
	"AppDetails_Feature_VRSupport": "VR 지원",
	"AppDetails_ViewAllUpdates": "모든 업데이트 보기",
	"AppDetails_ViewAllAchievements": "나의 도전 과제 보기",
	"AppDetails_ViewGlobalAchievements": "전체 도전 과제 통계 보기",
	"AppDetails_PlayerUnlockedPercent": "%1$s/%2$s 달성",
	"AppDetails_PlayerUnlockedPercentAll": "모든 도전 과제를 달성했습니다! %1$s/%2$s",
	"AppDetails_Achievements_Unlocked": "%1$s에 달성",
	"AppDetails_PctUnlocked": "%1$s%의 플레이어가 이 도전 과제를 달성했습니다",
	"AppDetails_GlobalCompare": "이는 전체 플레이어의 %1$s%가 넘습니다",
	"AppDetails_ViewTradingCards": "내 트레이딩 카드 보기",
	"AppDetails_Achievements_Locked": "잠긴 도전 과제",
	"AppDetails_TradingCardsLeft": "수집 가능한 남은 트레이딩 카드: 1개",
	"AppDetails_TradingCardsLeft_Plural": "수집 가능한 남은 트레이딩 카드: %1$s개",
	"AppDetails_TradingCardsLevelUp": "트레이딩 카드가 레벨을 올릴 수 있을 만큼 충분히 있습니다!",
	"AppDetails_TradingCardsMaxed": "축하합니다! 최대 레벨 배지!",
	"AppDetails_TradingCards_Tooltip1": "트레이딩 카드는 게임을 플레이하면 드롭됩니다. 드롭되지 않은 트레이딩 카드는 친구와 거래하거나 Steam 장터에서 거래할 수 있습니다.",
	"AppDetails_TradingCards_Tooltip2": "트레이딩 카드 세트를 완성하고 배지로 제작하세요. 배지로 Steam 레벨을 올릴 수 있고 프로필과 계정에 다양한 혜택을 받을 수 있습니다.",
	"AppDetails_BrowseWorkshop": "창작마당 검색",
	"AppDetails_ViewSubscribedItems": "내 구독 항목 보기",
	"AppDetails_ViewItemInWorkshop": "창작마당에서 보기",
	"AppDetails_MoreItemsFrom": "이 제작자의 아이템 보기",
	"AppDetails_SubscribeToItem": "구독",
	"AppDetails_UnsubscribeFromItem": "구독 취소",
	"AppDetails_Subscribed": "구독 중",
	"AppDetails_ViewMoreInWorkshop": "창작마당에서 더 보기",
	"AppDetails_WorkshopSubCount": "%1$s개의 창작마당을 구독 중입니다.",
	"AppDetails_WorkshopVisit": "이 창작마당 방문하기",
	"AppDetails_WorkshopLearnMore": "자세히 알아보기",
	"AppDetails_WorkshopFeaturedHeader": "떠오르는 아이템",
	"AppDetails_WorkshopFeaturedItem": "인기 아이템",
	"AppDetails_WorkshopFeaturedMoreInfo": "더 알아보기",
	"AppDetails_WorkshopFeaturedHideItem": "이 아이템 숨기기",
	"AppDetails_WorkshopFileSize": "파일 크기: %1$s",
	"AppDetails_WorkshopFileSizeBytes": "%1$s바이트",
	"AppDetails_WorkshopFileSizeKb": "%1$sKB",
	"AppDetails_WorkshopFileSizeMb": "%1$sMB",
	"AppDetails_WorkshopFileSizeGb": "%1$sGB",
	"AppDetails_WorkshopLastUpdated": "마지막 업데이트: %1$s",
	"DLCStatus_installed": "설치됨",
	"DLCStatus_notinstalled": "설치되지 않음",
	"DLCStatus_downloading": "다운로드 중",
	"DLC_DateAdded": "추가됨: %1$s",
	"AppDetails_ManageDLC": "내 %1$s DLC 관리",
	"AppDetails_ManageMyDLC": "내 DLC 관리",
	"AppDetails_ViewStoreDLC": "상점에서 DLC 보기",
	"AppDetails_DLCSpotlight": "새로 획득한 DLC가 추가되었으며, 게임과 함께 설치됩니다. %1$s DLC를 관리하세요.",
	"AppDetails_DLCSpotlight_Installed": "새로 획득한 DLC가 자동 설치되었습니다. %1$s DLC를 관리하세요.",
	"AppDetails_DLCSpotlight_here": "여기",
	"ManageDLC_Title": "DLC 관리",
	"ManageDLC_Column_Name": "이름",
	"ManageDLC_Column_DateAdded": "추가된 날짜",
	"ManageDLC_Column_Enabled": "사용함",
	"ManageDLC_Column_Installed": "설치됨",
	"ManageDLC_Search": "검색...",
	"ManageDLC_Installed": "%1$s/%2$s 설치됨",
	"ManageDLC_ViewMore": "상점에서 더 보기",
	"ManageDLC_NoResults": "'%1$s'에 해당하는 결과 없음",
	"AppDetails_ViewBadgePage": "배지 페이지 보기",
	"AppDetails_VisitTradeForum": "거래 포럼 방문",
	"AppDetails_BuyCards": "장터에서 남은 카드 구매하기",
	"AppDetails_SellCards": "장터에서 이 카드 판매하기",
	"AppDetails_SearchCard": "장터에서 이 카드 표시하기",
	"AppDetails_ShowFriendsList": "친구 목록 표시하기",
	"AppDetails_ViewFriendsWhoPlay": "이 게임을 하는 친구들 보기",
	"AppDetails_Link_Discussions": "토론",
	"AppDetails_Link_FindGroups": "그룹 찾기",
	"AppDetails_Link_GameHub": "커뮤니티 허브",
	"AppDetails_Link_Guides": "가이드",
	"AppDetails_Link_Store": "상점 페이지",
	"AppDetails_Link_Support": "지원",
	"AppDetails_Link_Workshop": "창작마당",
	"AppDetails_Link_Market": "장터",
	"AppDetails_Link_Controller": "컨트롤러 설정",
	"AppDetails_SocialMediaLink": "%1$s의 %2$s 계정",
	"AppDetails_SocialMediaType_4": "Twitter",
	"AppDetails_SocialMediaType_5": "Twitch",
	"AppDetails_SocialMediaType_6": "YouTube",
	"AppDetails_SocialMediaType_7": "Facebook",
	"AppDetails_Screenshot": "스크린샷",
	"AppDetails_Screenshot_Caption": "캡션: %1$s",
	"AppDetails_Screenshot_Date": "날짜: %1$s",
	"AppDetails_Screenshot_Dimensions": "크기: %1$sx%2$s픽셀",
	"AppDetails_Screenshot_Uploaded": "%1$s %2$s에 업로드됨",
	"AppDetails_OpenScreenshotUploader": "스크린샷 업로더 열기",
	"AppDetails_ViewUploadedScreenshots": "업로드된 스크린샷 보기",
	"AppDetails_ManageMyScreenshot": "내 스크린샷 관리",
	"AppDetails_ManageMyScreenshot_Plural": "스크린샷 %1$s개 관리",
	"AppDetails_HowToScreenshot": "게임 중 %1$s키를 누르면 스크린샷을 찍을 수 있습니다.",
	"AppDetails_ChangeMyScreenshotKey": "내 스크린샷 키 바꾸기",
	"AppDetails_NoScreenshots": "아직 스크린샷을 하나도 찍지 않았습니다.",
	"AppDetails_Screenshot_SpoilerAlert": "스포일러일 가능성이 있습니다. 마우스를 올리면 이미지가 드러납니다.",
	"AppDetails_Artwork": "아트워크",
	"AppDetails_Video": "비디오",
	"AppDetails_CommunityItem": "커뮤니티 콘텐츠",
	"AppDetails_CommunityFeed_OutOfContent": "추가 콘텐츠가 없습니다",
	"AppDetails_CommunityFeed_Inappropriate": "콘텐츠가 모든 연령에 적합하지 않을 수 있습니다",
	"AppDetails_CommunityFeed_ViewContent": "콘텐츠 보기",
	"AppDetails_CommunityFeed_EditPreferences": "환경 설정 수정",
	"AppDetails_CommunityFeed_LoadCommunity": "커뮤니티 콘텐츠 불러오기",
	"AppBox_NewToLibrary": "라이브러리 신규 추가",
	"AppBox_ComingSoon": "출시 예정",
	"AppBox_NewToLibrary_Short": "신규",
	"AppBox_ComingSoon_Short": "출시 예정",
	"AppBox_PlayTimeHeader": "플레이 시간",
	"AppBox_RecentPlayTime_Hours": "지난 2주 동안: %1$s시간",
	"AppBox_RecentPlayTime_Minutes": "지난 2주 동안: %1$s분",
	"AppBox_TotalPlayTime_Hours": "합계: %1$s시간",
	"AppBox_TotalPlayTime_Minutes": "합계: %1$s분",
	"AppActivity_Achieved": " 도전 과제를 달성함",
	"AppActivity_PostedScreenshot": " 스크린샷 하나를 공유함",
	"AppActivity_PostedScreenshot_Plural": " 스크린샷 %1$s개를 공유함",
	"AppActivity_PostedVideo": " 비디오 하나를 공유함",
	"AppActivity_PostedVideo_Plural": " 비디오 %1$s개를 공유함",
	"AppActivity_ReceivedNewGame": " 현재 %1$s 게임이 있음",
	"AppActivity_PlayedGameFirstTime": " %1$s 게임을 처음 플레이함",
	"AppActivity_LaunchedSoftwareFirstTime": " %1$s 소프트웨어를 처음 실행함",
	"AppActivity_AddedGameToWishlist": " 자신의 %2$s에 %1$s 추가함",
	"AppActivity_Wishlist": "찜 목록",
	"AppActivity_Achieved_PlusMore": "…그리고 %1$s개의 더 많은 달성 도전 과제",
	"AppActivity_Achieved_PlusMore_Label": "%1$s님이 달성한 도전 과제 모두 보기",
	"AppActivity_NoActivity": "이 타이틀에 대한 개발자나 친구들의 최근 활동이 없습니다.",
	"AppActivity_UserStatus_Time": " %1$s에 상태 업데이트를 게시함",
	"AppActivity_UserStatus": " 상태 업데이트를 게시함",
	"AppActivity_StatusUpdate": "친구에게 상태 게시하기",
	"AppActivity_StatusUpdate_Post": "친구들에게 이 게임에 대해 이야기해 주세요...",
	"AppActivity_StatusUpdate_Software_Post": "친구들에게 이 소프트웨어에 대해 이야기해 주세요...",
	"AppActivity_Comment_Reply": "답장 추가하기...",
	"AppActivity_PostStatusUpdate": "게시하기",
	"AppActivity_FetchMore": "더 많은 활동 불러오기",
	"AppActivity_EndofFeed": "마지막 활동",
	"AppActivity_DeleteUserNews": "이 게시물을 삭제하려면 클릭하세요.",
	"AppActivity_ConfirmDeleteTitle": "상태 게시 삭제하기",
	"AppActivity_ConfirmDeleteTitle_Desc": "이 상태 게시를 삭제할까요? 이 작업은 취소할 수 없습니다.",
	"AppActivity_RecommendedGame": " 이 게임에 대한 평가를 작성함",
	"AppActivity_RecommendedGame_ReadMore": "더 알아보기",
	"AppActivity_RatingDetails": "%1$s명이 긍정적으로 평가함",
	"AppActivity_RatingDetails_1Other": "1명이 긍정적으로 평가함(%1$s님)",
	"AppActivity_RatingDetails_2Others": "%1$s명이 긍정적으로 평가함(%2$s님과 %3$s님 포함)",
	"AppActivity_RatingDetails_User": "본인이 긍정적으로 평가함",
	"AppActivity_RatingDetails_User_1Other": "%1$s명이 긍정적으로 평가함(본인과 %2$s님 포함)",
	"AppActivity_RatingDetails_User_2Others": "%1$s명이 긍정적으로 평가함(본인과 %2$s님과 %3$s님 포함)",
	"AppActivity_RatingDetails_PublishedFile": "%1$s님이 좋아합니다",
	"AppActivity_RateUp": "좋아요",
	"AppActivity_ConfirmDeleteCommentTitle": "댓글 삭제하기",
	"AppActivity_ConfirmDeleteCommentTitle_Desc": "이 댓글을 삭제할까요? 이 작업은 취소할 수 없습니다.",
	"AppActivity_MakeCommentsVisible": "이전 댓글 보기 (%1$s)",
	"AppActivity_Settings": "설정",
	"AppActivity_ViewComments": "댓글 보기",
	"AppActivity_AddComments": "댓글 추가하기",
	"AppActivity_ContributeComments": "이와 관련된 댓글",
	"AppActivity_SteamTradingCards_EarnedTradingCards": " 트레이딩 카드들을 획득함",
	"AppActivity_SteamTradingCards_EarnedTradingCard": " 트레이딩 카드 하나를 획득함",
	"AppActivity_SteamTradingCards_EarnedBoosterPack": " 부스터 팩 하나를 획득함",
	"AppActivity_SteamTradingCards_BadgeCrafted": " 배지 하나를 제작함",
	"AppActivity_ViewLatestNews": "최신 뉴스 보기",
	"AppActivity_EventType_GameUpdate": "게임 업데이트",
	"AppSpotlight_PostGameSummary": "게임 종료 후 요약",
	"AppDetails_Shortcut_Explanation": "Steam이 아닌 다른 모드 또는 바로가기를 사용할 경우, %1$s에 대한 일부 상세 정보가 표시되지 않습니다. Steam에서는 여전히 게임 시작을 관리하며, 대부분의 경우 게임 내 오버레이를 사용할 수 있습니다.",
	"AppDetails_Takeover_Update_Header": "확인 못 하신 분들을 위해",
	"AppDetails_Takeover_Update_ViewAll": "%1$s개의 게임 업데이트 전체 보기",
	"AppDetails_Takeover_Update_ReadMore": "더 알아보기",
	"AppDetails_Takeover_DLC_Header": "새로 추가된 아이템",
	"AppDetails_Takeover_DLC_ViewInStore": "상점에서 %1$s 보기",
	"AppDetails_Takeover_Achievements_Header": "%2$s 플레이 완료. 새로운 도전과제가 있습니다...",
	"AppDetails_Takeover_Achievements_Header_Plural": "%2$s 플레이 완료. 새로운 도전과제들이 있습니다...",
	"AppDetails_Takeover_TradingCards_Header": "%2$s 플레이 완료. 새로운 아이템이 있습니다...",
	"AppDetails_Takeover_TradingCards_Header_Plural": "%2$s 플레이 완료. 새로운 아이템들이 있습니다...",
	"AppDetails_ViewMyInventory": "내 보관함 보기",
	"AppDetails_ViewInMyInventory": "내 보관함에서 보기",
	"AppDetails_Soundtrack_TotalTracks": "총 %1$s트랙",
	"AppDetails_Soundtrack_DiscNumber": "디스크 %1$s",
	"AppDetails_Soundtrack_TrackCount": "%1$s개의 트랙",
	"AppDetails_Soundtrack_PlayAlbum": "앨범 재생",
	"AppDetails_Soundtrack_DownloadAlbum": "앨범 다운로드",
	"AppDetails_Soundtrack_AddToQueue": "대기열에 추가",
	"AppDetails_Soundtrack_AddToPlaylist": "재생 목록에 추가",
	"AppDetails_Soundtrack_ViewOnDisk": "로컬 파일에서 보기",
	"AppDetails_Soundtrack_ViewAdditionalArtwork": "추가 아트워크 보기",
	"AppDetails_Soundtrack_ViewStorePage": "상점 페이지 보기",
	"AppDetails_Soundtrack_Support": "지원 페이지 보기",
	"AppDetails_Soundtrack_ParentAppLink": "%1$s의 사운드트랙",
	"AppPortraitHover_DownloadStatusTitle": "다운로드 중",
	"AppPortraitHover_DownloadStatusTitle_Update": "업데이트 다운로드 중",
	"AppPortraitHover_DaysSinceLastUpdate": "%1$s에 업데이트됨",
	"AppPortraitHover_FriendsPlaying": "%1$s명의 친구가 플레이 중",
	"MajorUpdate_ViewDetails": "자세히 보기",
	"MajorUpdate_NextUpdate": "다음 업데이트",
	"MajorUpdate_PostTime": "%1$s일 전 %2$s:%3$s에 게시됨",
	"MajorUpdate_PostTimeToday": "오늘 %1$s:%2$s에 게시됨",
	"MajorUpdate_WatchNow": "SteamTV에서 보기",
	"MajorUpdate_Type0": "주요 업데이트",
	"MajorUpdate_Type1": "실시간 스트리밍",
	"MajorUpdate_Type14": "주요 업데이트",
	"MajorUpdate_Context_RemoveThisUpdate": "이 업데이트 제거하기",
	"MajorUpdate_Context_ShowMeFewerForApp": "%1$s 업데이트 덜 보기",
	"MajorUpdate_Context_ShowMeMoreForApp": "%1$s 업데이트 더 보기",
	"MajorUpdate_Context_ResetHiddenUpdates": "모든 업데이트 다시 표시하기",
	"MajorUpdate_Context_WhyAmISeeingThis": "왜 나에게 이 내용이 보이나요?",
	"MajorUpdate_Context_WhyAmISeeingThis_Text": "라이브러리에 있는 제품 중에서 플레이 시간이 20시간이 넘는 제품의 주요 업데이트입니다(placeholder).",
	"MajorUpdate_Context_WhyAmISeeingThis_Close": "닫기",
	"CustomArt_ErrorTitle": "오류",
	"CustomArt_BadFileType": "파일은 반드시 JPG 또는 PNG 형식이어야 합니다.",
	"CustomArt_UnknownError": "아트워크를 설정하는 도중 오류가 발생했습니다.",
	"CustomArt_SetCustomBackground": "맞춤 배경 설정",
	"CustomArt_ClearCustomBackground": "맞춤 배경 삭제",
	"CustomArt_SetCustomLogo": "맞춤 로고 설정",
	"CustomArt_ClearCustomLogo": "맞춤 로고 삭제",
	"CustomArt_EditLogoPosition": "로고 위치 조정",
	"CustomArt_ResetLogoPosition": "로고 위치 초기화",
	"CustomArt_DoneEditingLogo": "완료",
	"AppDetails_LibraryInUse": "라이브러리 사용 중인 사람:",
	"AppDetails_InSharedLibrary": "공유받은 라이브러리 주인:",
	"FriendContextMenu_OpenFriends": "친구 목록 및 채팅 열기",
	"FriendContextMenu_ViewProfile": "프로필 보기",
	"Generic_ScrollToTop": "맨 위로 스크롤",
	"Generic_ViewGameDetails": "라이브러리에서 게임 보기",
	"GameDetails_CollectionContext_GoTo": "모음집으로 가기",
	"GameDetails_CollectionContext_Remove": "모음집에서 제거",
	"ArtworkModal_ViewAll": "모든 스크린샷 보기",
	"ArtworkModal_FileSize": "파일 크기",
	"ArtworkModal_Posted": "게시 일시",
	"ArtworkModal_Size": "크기",
	"ArtworkModal_CreatedBy": "작성자",
	"ArtworkModal_ScrollForMore": "댓글을 보려면 아래로 스크롤하세요",
	"ArtworkModal_ScrollForDetails": "자세히 보려면 아래로 스크롤하세요",
	"CommunityItem_Menu_Report": "신고",
	"ReportItem_Title": "이 아이템 신고하기",
	"ReportItem_Description": "이 아이템이 Steam 서비스 약관에 위반되는 이유를 설명해 주세요. 이와 관련된 정보와 링크를 모두 포함해 주세요. 이 신고 제출은 취소할 수 없습니다.",
	"ReportItem_Description_Line2": "신고하신 아이템은 라이브러리 페이지에 더 이상 표시되지 않습니다.",
	"ReportItem_DMCA": "저작권 침해를 신고하시고자 하며 그 저작권의 소유자이신 경우, %1$s에서 저작권 침해의 DMCA 준수 통지 양식을 입력해 주세요.",
	"ReportItem_DMCA_LinkText": "여기",
	"ReportItem_Error": "요청을 서버에 제출하는 도중 문제가 발생했습니다. 나중에 다시 시도해 주세요.",
	"ReportItem_SubmitReport": "신고 제출",
	"RemoveFreeApp_Title": "계정에서 제거",
	"RemoveFreeApp_Description": "%1$s 앱이 무료 라이선스와 함께 계정에 추가되었습니다. 계정에서 제거하면 Steam 라이브러리와 보유 게임 목록에 더 이상 포함되지 않습니다.",
	"RemoveFreeApp_Question": "계정에서 %1$s 앱을 제거할까요?",
	"RemoveFreeApp_Remove": "제거",
	"RemoveFreeApp_Removing": "%1$s 제거 중",
	"RemoveFreeApp_Error": "%1$s 제거 도중 오류가 발생했습니다",
	"UninstallDialog_Title": "설치 제거",
	"UninstallDialog_Uninstall": "설치 제거",
	"UninstallDialog_ErrorMessage": "%1$s을(를) 제거할 수 없는 이유:",
	"UninstallDialog_Busy": "현재 다른 설치 또는 설치 제거 작업이 진행 중입니다. 해당 작업이 완료될 때까지 기다려 주세요.",
	"UninstallDialog_SecuROM": "이 애플리케이션을 제거하려면 인터넷에 연결되어 있어야 합니다.",
	"UninstallDialog_UnknownError": "이 애플리케이션을 설치 제거하는 도중 예상하지 못한 오류가 발생했습니다.",
	"UninstallDialog_AppUpdateError": "설치 제거 오류 - %1$s",
	"UninstallDialog_Confirmation_Single": "이 컴퓨터에 설치된 %1$s 게임을 설치 제거할까요? 제거 시, 게임은 라이브러리에 그대로 남아 있지만 나중에 다시 플레이하려면 먼저 모든 콘텐츠를 다시 다운로드해야 합니다.",
	"UninstallDialog_Confirmation_Multiple": "선택한 게임을 이 컴퓨터에서 제거할까요? 제거 시, 게임은 라이브러리에는 그대로 남아 있지만, 나중에 다시 플레이하려면 먼저 해당 콘텐츠를 다시 다운로드해야 합니다.",
	"UninstallingDialog_Uninstalling": "설치 제거 중",
	"UninstallingDialog_UninstallingApp": "%1$s 설치 제거 중",
	"UninstallingDialog_WaitingForPassword": "비밀번호를 기다리는 중",
	"Showcase_AddNewShowcase": "전시대 추가하기",
	"Showcase_DeleteShowcase": "이 전시대 삭제하기",
	"Showcase_SelectCategory": "전시대 선택하기",
	"Showcase_EmptyShowcaseHint": "이 전시대에 무엇을 전시할지 고르세요.  여기에서 전시대를 수정하거나 삭제할 수도 있습니다!",
	"Showcase_GoToCollection": "모음집으로 가기",
	"Showcase_GoToAllCollections": "전체 모음집으로 가기",
	"Showcase_AllYourGames": "모든 게임",
	"Showcase_AllCollections": "모음집 보기",
	"Showcase_RecentGames": "최근 게임",
	"Showcase_DoneReordering": "완료",
	"Playtime_TwoWeeks_Minutes": "최근 플레이 시간: %1$s분",
	"Playtime_TwoWeeks_Hours": "최근 플레이 시간: %1$s시간",
	"Playtime_Total_Minutes": "총 플레이 시간: %1$s분",
	"Playtime_Total_Hours": "총 플레이 시간: %1$s시간",
	"Playtime_Minutes": "%1$s분",
	"Playtime_Hours": "%1$s시간",
	"Playtime_Recently": "최근 플레이 시간: %1$s",
	"Playtime_Total": "총 플레이 시간: %1$s",
	"GameList_Search_NoResults_Title": "원하는 항목을 찾을 수 없나요?",
	"GameList_Search_NoResults_Link": "Steam 상점 검색",
	"StreamingClient_Select_ThisMachine": "이 기기",
	"StreamingClient_Select_RemotePlayPhone": "휴대전화",
	"StreamingClient_Select_RemotePlayTablet": "태블릿",
	"StreamingClient_Select_RemotePlayMobile": "모바일 기기",
	"StreamingClient_Select_RemotePlayTV": "TV",
	"StreamingClient_Select_RemotePlayTVPhone": "TV 및 휴대전화",
	"StreamingClient_Select_RemotePlayTVTablet": "TV 및 태블릿",
	"StreamingClient_Select_RemotePlayTVMobile": "TV 및 모바일 기기",
	"Beta_BetaTag": "베타",
	"Beta_Changelist": "변경 목록",
	"Beta_GiveFeedback": "피드백 보내기",
	"ContextMenu_SaveScreenshot": "스크린샷 다른 이름으로 저장하기...",
	"ContextMenu_BrowseScreenshot": "스크린샷 둘러보기",
	"ContextMenu_ManageScreenshots": "스크린샷 관리",
	"SteamChina_DurationControl_Init_1": "건전한 게이밍을 위한 조언",
	"SteamChina_DurationControl_Init_2": "유해 게임을 보이콧하고 해적판 게임을 거부하세요.",
	"SteamChina_DurationControl_Init_3": "자기 방어 훈련을 하고 사기 행위에 피해를 입지 않도록 주의하세요.",
	"SteamChina_DurationControl_Init_4": "중용은 두뇌 건강을 촉진하고 과도한 플레이는 건강을 해칩니다.",
	"SteamChina_DurationControl_Init_5": "시간을 잘 계획하여 사용하는 것은 건강한 생활 방식에 도움이 됩니다.",
	"Steam_AppUpdateError_0": "오류 없음",
	"Steam_AppUpdateError_1": "알수 없는 오류",
	"Steam_AppUpdateError_2": "업데이트 일시 정지됨",
	"Steam_AppUpdateError_3": "업데이트 취소됨",
	"Steam_AppUpdateError_4": "업데이트 일시 정지됨",
	"Steam_AppUpdateError_5": "라이선스 없음",
	"Steam_AppUpdateError_6": "인터넷 연결 없음",
	"Steam_AppUpdateError_7": "연결 시간 초과",
	"Steam_AppUpdateError_8": "콘텐츠 암호화가 해제되지 않음",
	"Steam_AppUpdateError_9": "앱 구성 사용 불가",
	"Steam_AppUpdateError_10": "디스크 읽기 오류",
	"Steam_AppUpdateError_11": "디스크 쓰기 오류",
	"Steam_AppUpdateError_12": "디스크 여유 공간 부족",
	"Steam_AppUpdateError_13": "손상된 콘텐츠 파일",
	"Steam_AppUpdateError_14": "설치 디스크 기다리는 중",
	"Steam_AppUpdateError_15": "잘못된 설치 경로",
	"Steam_AppUpdateError_16": "앱 실행 중",
	"Steam_AppUpdateError_17": "공유 콘텐츠 누락",
	"Steam_AppUpdateError_18": "설치되지 않음",
	"Steam_AppUpdateError_19": "업데이트 필요",
	"Steam_AppUpdateError_20": "사용 중",
	"Steam_AppUpdateError_21": "콘텐츠 서버에 연결할 수 없음",
	"Steam_AppUpdateError_22": "잘못된 앱 구성",
	"Steam_AppUpdateError_23": "잘못된 디포 구성",
	"Steam_AppUpdateError_24": "매니페스트 사용 불가",
	"Steam_AppUpdateError_25": "앱이 출시되지 않음",
	"Steam_AppUpdateError_26": "지역 제한",
	"Steam_AppUpdateError_27": "콘텐츠 캐시 손상",
	"Steam_AppUpdateError_28": "실행 파일 누락",
	"Steam_AppUpdateError_29": "플랫폼 오류",
	"Steam_AppUpdateError_30": "지원하지 않는 파일 시스템",
	"Steam_AppUpdateError_31": "업데이트 파일 손상",
	"Steam_AppUpdateError_32": "다운로드 불가",
	"Steam_AppUpdateError_33": "공유 라이브러리 잠김",
	"Steam_AppUpdateError_34": "구매 대기 중",
	"Steam_AppUpdateError_35": "다른 세션 실행 중",
	"Steam_AppUpdateError_36": "다운로드한 파일 손상됨",
	"Steam_AppUpdateError_37": "디스크 손상됨",
	"Steam_AppUpdateError_38": "파일 권한이 없음",
	"Steam_AppUpdateError_39": "콘텐츠 파일 잠김",
	"Steam_AppUpdateError_40": "콘텐츠 사용 불가",
	"Steam_AppUpdateError_41": "이 실행 파일에는 64비트 운영체제가 필요합니다.",
	"Steam_AppUpdateError_42": "다운로드된 파일을 찾을 수 없음",
	"Steam_AppUpdateError_43": "사용자를 위한 디스크 여유 공간이 부족합니다. 운영체제 디스크 할당량 설정을 확인하세요.",
	"Steam_AppUpdateError_44": "사업장 라이선스 잠김",
	"Steam_AppUpdateError_45": "자녀 보호 기능에 의해 차단됨",
	"Steam_AppUpdateError_46": "생성 프로세스 실패",
	"Steam_AppUpdateError_47": "Steam 클라이언트가 최신 버전이 아님",
	"ShareDialog_Title": "공유",
	"ShareUploadScreenshot_Description": "이 스크린샷을 Steam 프로필과 활동 피드에 업로드합니다.",
	"ShareUploadScreenshot_AddCaption": "여기에 설명 추가",
	"ShareUploadScreenshot_CaptionHeader": "캡션:",
	"ShareUploadScreenshot_TagSpoiler": "스포일러로 태그",
	"ShareUploadScreenshot_CloudUsage": "클라우드 용량 중 남은 %2$s의 %1$s이(가) 사용됩니다(총량: %3$s)",
	"ShareUploadScreenshot_Uploading": "Steam에 업로드 중",
	"ShareUploadScreenshot_PermissionDenied": "Steam에서 이 스크린샷을 업로드하지 못했습니다. 고객님의 계정에 현재 적용되어 있는 차단으로 인해 콘텐츠 업로드가 허용되지 않습니다.",
	"ShareUploadScreenshot_UnexpectedError": "Steam에서 이 스크린샷을 Steam 클라우드에 업로드하지 못했습니다. 다시 시도해 주세요.",
	"DeleteScreenshot_Title": "스크린샷을 삭제하시겠습니까",
	"DeleteScreenshot_Single": "이 스크린샷을 영구적으로 하드 디스크에서 삭제할까요?",
	"DeleteScreenshot_Failed": "Steam이 선택하신 스크린샷을 하드 디스크에서 삭제하지 못했습니다.",
	"AppDetailsAchievement_Hidden": "숨겨진 도전 과제",
	"AppDetailsAchievement_HiddenDesc": "계속 플레이하고 이 도전 과제를 찾아내세요.",
	"Demo_SpotlightIntro": "전체 게임 보기",
	"Demo_VisitStorePage": "상점 페이지 방문",
	"SteamReviewScore_9": "압도적으로 긍정적",
	"SteamReviewScore_8": "매우 긍정적",
	"SteamReviewScore_7": "긍정적",
	"SteamReviewScore_6": "대체로 긍정적",
	"SteamReviewScore_5": "복합적",
	"SteamReviewScore_4": "대체로 부정적",
	"SteamReviewScore_3": "부정적",
	"SteamReviewScore_2": "매우 부정적",
	"SteamReviewScore_1": "압도적으로 부정적"
}
