{
	"Generic_Okay": "OK",
	"Generic_Close": "Fermer",
	"Generic_Open": "Ouvrir",
	"Generic_GotIt": "J'ai compris !",
	"AppType_0": "Non valide",
	"AppType_1": "Jeux",
	"AppType_2": "Logiciels",
	"AppType_4": "Outils",
	"AppType_20": "DLC",
	"AppType_800": "Vidéos",
	"AppType_2000": "Musiques",
	"AppType_Singular_0": "Non valide",
	"AppType_Singular_1": "jeu",
	"AppType_Singular_2": "application",
	"AppType_Singular_4": "outil",
	"AppType_Singular_20": "DLC",
	"AppType_Singular_800": "vidéo",
	"AppType_Singular_2000": "musique",
	"AppType_Singular_8000": "BD",
	"AppType_Singular_40000000": "raccourci",
	"FilterEdit_SavedFilters": "Filtres enregistrés",
	"FilterEdit_FirstColumnHeader": "Type de filtre",
	"FilterEdit_Customize": "Personnaliser",
	"FilterEdit_SearchModeHeader": "Filtres avancés",
	"FilterEdit_CollectionModeHeader": "Modifier les filtres de collection",
	"CollectionEdit_CollectionNameField": "Nom de la collection :",
	"CollectionEdit_RenameButton": "Renommer la collection",
	"Collection_DynamicCollection": "Collection dynamique",
	"FilterEdit_AdvancedTooltip": "Options de filtrage avancées pour affiner votre liste de jeux par genres, fonctionnalités, etc.",
	"FilterEdit_SelectedFilters": "Filtres sélectionnés",
	"FilterEdit_SaveCollectionNameInputPrompt": "Nommez cette collection",
	"FilterEdit_SaveOverwrite": "La collection « %1$s » existe déjà. Voulez-vous la remplacer ?",
	"FilterEdit_SaveCollection": "Enregistrer comme collection",
	"FilterEdit_SaveDynamicCollectionWithIcon": "Enregistrer comme %1$scollection dynamique",
	"FilterEdit_SaveDynamicCollectionNoIcon": "Enregistrer comme collection dynamique",
	"FilterEdit_SaveCollectionVerbose": "Enregistrez cette recherche comme collection pour la réutiliser à l'avenir. Vous pourrez toujours la modifier, la renommer, la supprimer, ou encore y ajouter ou en retirer des articles.",
	"FilterEdit_SaveStandardCollectionButtonDesc": "Les collections sont une façon simple d'organiser votre bibliothèque. Faites glisser des titres dans votre collection ou faites un clic droit sur un article pour l'ajouter à une collection existante.",
	"FilterEdit_SaveDynamicCollectionButtonDesc": "Grâce aux filtres, vous pouvez créer des collections dynamiques qui se mettent à jour automatiquement quand votre bibliothèque s'enrichit.",
	"FilterEdit_SelectCollectionType": "Sélectionnez un type de collection",
	"FilterEdit_SelectCollectionTypeButtonCreate": "Créer une collection",
	"FilterEdit_SelectCollectionTypeButtonCreateDynamic": "Créer une collection dynamique",
	"FilterEdit_RequiredField": "(REQUIS)",
	"FilterEdit_SearchPrompt": "Rechercher par nom",
	"FilterEdit_ClearSearch": "Quitter la recherche",
	"FilterEdit_SearchResults": "Résultats de recherche",
	"FilterEdit_CollectionsHiddenPromptTitle": "Vos collections sont masquées",
	"FilterEdit_CollectionsHiddenPrompt": "Voulez-vous changer l'affichage de la liste des jeux pour afficher votre nouvelle collection ?",
	"FilterEdit_AcceptGameListViewChange": "Oui, afficher les collections",
	"FilterEdit_RejectGameListViewChange": "Non, garder cet affichage",
	"AdvancedSearch_PaneTitle": "Rechercher par type",
	"AdvancedSearch_PlayerSection": "Joueurs",
	"AdvancedSearch_HardwareSection": "Prise en charge matérielle",
	"AdvancedSearch_FeatureSection": "Fonctionnalités",
	"AdvancedSearch_StateSection": "État",
	"AdvancedSearch_GenreSection": "Genre",
	"AdvancedSearch_StoreTagSection": "Tags du magasin",
	"AdvancedSearch_StoreTagPrompt": "saisissez un tag",
	"FilterCategory_1": "Status",
	"FilterCategory_Features": "FONCTIONNALITÉ",
	"FilterCategory_3": "Catégorie",
	"FilterCategory_4": "Tag du magasin",
	"FilterCategory_Type": "TYPE",
	"FilterCategory_Genre": "GENRE",
	"FilterCategory_PlayState": "ÉTAT",
	"FilterElement_VR": "VR",
	"FilterElement_Tooltip_VR": "Inclure les jeux qui prennent en charge la réalité virtuelle.",
	"FilterElement_Installed": "Installés localement",
	"FilterElement_Tooltip_Installed": "Inclure les jeux qui sont installés sur cet ordinateur.",
	"FilterElement_ReadyToPlay": "Prêts à être lancés",
	"FilterElement_Tooltip_ReadyToPlay": "Inclure les jeux auxquels vous pouvez jouer localement ou en streaming depuis un autre ordinateur.",
	"FilterElement_PlayedPreviously": "Lancés",
	"FilterElement_Tooltip_PlayedPreviously": "Inclure les jeux auxquels vous avez déjà joué.",
	"FilterElement_Unplayed": "Non lancés",
	"FilterElement_Tooltip_Unplayed": "Inclure les jeux auxquels vous n'avez pas encore joué.",
	"FilterElement_FullControllerSupport": "Manettes (prise en charge complète)",
	"FilterElement_Tooltip_FullControllerSupport": "Inclure les jeux auxquels vous pouvez jouer entièrement avec une manette.",
	"FilterElement_PartialControllerSupport": "Manettes (prise en charge partielle)",
	"FilterElement_Tooltip_PartialControllerSupport": "Inclure les jeux auxquels vous pouvez jouer avec une manette, mais qui peuvent nécessiter un clavier et une souris pendant l'installation ou pour certaines interactions.",
	"FilterElement_VRSupported": "Prise en charge de la VR",
	"FilterElement_TradingCards": "Cartes à échanger",
	"FilterElement_Tooltip_TradingCards": "Inclure les jeux qui ont des cartes à échanger Steam.",
	"FilterElement_Workshop": "Workshop",
	"FilterElement_Tooltip_Workshop": "Inclure les jeux qui intègrent le Steam Workshop.",
	"FilterElement_Achievements": "Succès",
	"FilterElement_Tooltip_Achievements": "Inclure les jeux qui offrent des succès Steam.",
	"FilterElement_SinglePlayer": "Un joueur",
	"FilterElement_Tooltip_SinglePlayer": "Inclure les jeux avec un mode solo.",
	"FilterElement_MultiPlayer": "Multijoueur",
	"FilterElement_Tooltip_MultiPlayer": "Inclure les jeux avec un mode multijoueur.",
	"FilterElement_CoOp": "Coopération",
	"FilterElement_Tooltip_CoOp": "Inclure les jeux avec un mode multijoueur coopératif.",
	"FilterElement_GenreAction": "Action",
	"FilterElement_Tooltip_GenreAction": "Inclure les jeux d'action.",
	"FilterElement_GenreAdventure": "Aventure",
	"FilterElement_Tooltip_GenreAdventure": "Inclure les jeux d'aventure.",
	"FilterElement_GenreCasual": "Casual",
	"FilterElement_Tooltip_GenreCasual": "Inclure les jeux casual.",
	"FilterElement_GenreIndie": "Indépendant",
	"FilterElement_Tooltip_GenreIndie": "Inclure les jeux indépendants.",
	"FilterElement_GenreMMO": "MMO",
	"FilterElement_Tooltip_GenreMMO": "Inclure les jeux massivement multijoueur.",
	"FilterElement_GenreRacing": "Course automobile",
	"FilterElement_Tooltip_GenreRacing": "Inclure les jeux de course.",
	"FilterElement_GenreRPG": "RPG",
	"FilterElement_Tooltip_GenreRPG": "Inclure les jeux de rôle.",
	"FilterElement_GenreSimulation": "Simulation",
	"FilterElement_Tooltip_GenreSimulation": "Inclure les jeux de simulation.",
	"FilterElement_GenreSports": "Sport",
	"FilterElement_Tooltip_GenreSports": "Inclure les jeux de sport.",
	"FilterElement_GenreStrategy": "Stratégie",
	"FilterElement_Tooltip_GenreStrategy": "Inclure les jeux de stratégie.",
	"FilterElement_Tooltip_StoreTag": "Inclure les applications qui portent le tag « %1$s » sur Steam.",
	"CollectionViewHeader_Tooltip_ManuallyAddedApp": "Ce jeu a été ajouté manuellement à cette collection.",
	"CollectionViewHeader_Tooltip_ManuallyRemovedApp": "Ce jeu a été supprimé de cette collection.",
	"CollectionView_EmptyReadOnlyCollection": "Aucun résultat trouvé",
	"CollectionView_EmptyDynamicCollection_Line1": "Aucun jeu ne correspond à ce filtre !",
	"CollectionView_EmptyDynamicCollection_Line2": "Changez de filtre ou faites glisser des jeux ici pour créer cette collection.",
	"CollectionView_EmptyCollection": "Faites glisser des jeux ici pour créer cette collection.",
	"CollectionView_EmptyCollection_BecauseFilter": "%1$s jeu de cette collection est masqué par le filtre d'affichage que vous avez sélectionné.",
	"CollectionView_EmptyCollection_BecauseFilter_Plural": "%1$s jeux de cette collection sont masqués par le filtre d'affichage que vous avez sélectionné.",
	"CollectionView_MissingCollection": "Aucune collection trouvée.",
	"CollectionView_GamesExcluded": "+%1$s",
	"CollectionView_GamesExcluded_Desc": "articles non prêts à être lancés",
	"AllCollectionsView_Title": "Vos collections",
	"AllCollectionsView_InfoIcon": "Créez des %1$s pour organiser vos articles comme vous le souhaitez, ou créez des %2$s pour regrouper vos articles en fonction d'un ensemble de filtres. %3$s",
	"AllCollectionsView_InfoIconCollections": "collections",
	"AllCollectionsView_InfoIconDynamicCollections": "collections dynamiques",
	"AllCollectionsView_InfoIconFav": "Vos %1$s seront toujours affichés ici, en haut de la page.",
	"AllCollectionsView_InfoIconFavorites": "favoris",
	"AllCollectionsView_AddCollection": "Créer une nouvelle collection",
	"AllCollectionsView_DragToAddCollection": "Faites glisser un article ici pour créer une nouvelle collection",
	"GameList_Home": "Accueil de la bibliothèque",
	"GameList_Search": "Rechercher",
	"GameList_Category_Uncategorized": "Sans catégorie",
	"GameList_Category_Favorites": "Favoris",
	"GameList_Category_Hidden": "Masqués",
	"GameList_Category_Hidden_Tooltip": "Les articles masqués n'apparaîtront pas dans votre bibliothèque, à moins de les rechercher. Vous pouvez voir tous les articles que vous avez masqués depuis le menu « Afficher » ci-dessus.",
	"GameList_Category_YourCollections": "Vos collections",
	"GameList_Category_SharedLibraries": "Bibliothèques partagées",
	"GameList_SectionHeader_SearchResults": "Résultats filtrés de recherche",
	"GameList_SectionHeader_AddedManually": "Ajouté manuellement",
	"GameList_SectionHeader_RemovedManually": "Supprimé manuellement",
	"GameList_SectionHeader_NoRecentActivity": "Aucune activité enregistrée",
	"GameList_View_Collections": "Vos collections",
	"GameList_View_ThisCollection": "Afficher cette collection",
	"GameList_View_LibraryList": "Liste filtrée",
	"GameList_View_OneCollection": "Affichage de la collection",
	"GameList_View_SearchResults": "Résultats de recherche",
	"GameList_View_ShowAllCollections": "Afficher toutes les collections",
	"GameList_View_GroupByCollections": "Regrouper par collection",
	"GameList_View_ExitSearch": "Quitter la recherche",
	"GameList_View_All": "Tous",
	"GameList_View_SortByRecent": "Trier par activité récente",
	"GameList_View_ShowOnlyReadyToPlay": "Afficher uniquement les jeux prêts à être lancés",
	"GameList_View_ShowingOnlyReadyToPlay": "Résultats affichés : articles prêts à être lancés",
	"GameList_View_ShowOnlyVR": "Afficher uniquement les jeux VR",
	"GameList_View_ReadyToPlay_ToolTip1": "• Installés sur cette machine",
	"GameList_View_ReadyToPlay_ToolTip2": "• Peuvent être streamés depuis une autre machine",
	"GameList_Entry_ReadyToPlay_ToolTip": "Seront streamés depuis une autre machine",
	"Shelf_SectionHeader_ExpandTooltip": "Développez l'étagère pour afficher plus de rangées",
	"Shelf_SectionHeader_ExpandTooltipFilter": "Développez l'étagère pour afficher plus de rangées. Votre affichage actuel masque %1$s articles",
	"GameList_SectionHeader_AppCountToolTip": "Votre filtre actuel masque %1$s articles",
	"GameList_SectionHeader_AppCountToolTipAllHidden": "Votre filtre actuel masque tous vos articles",
	"CollectionAction_ViewOnlyThis": "Afficher uniquement cette collection",
	"CollectionAction_ViewOnlyThisFavorites": "Afficher uniquement les favoris",
	"CollectionAction_ViewOnlyThisUncategorized": "Afficher uniquement les articles non catégorisés",
	"CollectionAction_Collapse": "Réduire",
	"CollectionAction_Expand": "Développer",
	"CollectionAction_Manage": "Gérer",
	"CollectionAction_Edit": "Modifier les filtres de collection",
	"CollectionAction_Rename": "Renommer la collection",
	"CollectionAction_Delete": "Supprimer la collection",
	"CollectionAction_DeleteDialog": "Supprimer la collection",
	"CollectionAction_ConfirmDelete": "Voulez-vous vraiment supprimer définitivement la collection « %1$s » ?",
	"CollectionAction_SaveFailed": "Impossible d'enregistrer la collection « %1$s »",
	"CollectionAction_CannotOverwrite": "Impossible de remplacer la collection « %1$s ». Veuillez choisir un nouveau nom.",
	"CollectionAction_DeleteFailed": "Impossible de supprimer la collection « %1$s »",
	"LibraryHome_FriendsActivity": "Activité de vos amis",
	"LibraryHome_RecentGames": "Jeux récents",
	"LibraryHome_NewUpdates": "Vos mises à jour",
	"LibraryHome_YourCollection": "Toute votre bibliothèque",
	"LibraryHome_RecentFriendsActivity": "Activité récente de vos amis",
	"Library_FriendsActivity_HotRightNowHeading": "Très populaire en ce moment",
	"Library_FriendsActivity_HotRightNowHover": "Nous vous montrons ce jeu car plusieurs de vos amis y jouent en ce moment.",
	"Library_FriendsActivity_TrendingHeading": "Tendance",
	"Library_FriendsActivity_TrendingHover": "Nous vous montrons ce jeu car certains de vos amis y ont joué la semaine dernière plus que la semaine précédente.",
	"Library_FriendsActivity_BeingDiscussedHeading": "On en parle",
	"Library_FriendsActivity_BeingDiscussedHover": "Nous vous montrons ce jeu car vos amis ont publié des captures d'écran du jeu ou des statuts à son sujet.",
	"Library_FriendsActivity_RecentlyPurchasedHeading": "Acheté récemment",
	"Library_FriendsActivity_RecentlyPurchasedHover": "Nous vous montrons ce jeu car vous l'avez acheté récemment et vos amis y jouent.",
	"Library_FriendsActivity_UnownedHeading": "Découvrez un nouveau jeu",
	"Library_FriendsActivity_UnownedHover": "Nous vous montrons ce jeu car il est populaire parmi vos amis et vous ne le possédez pas.",
	"Library_FriendsActivity_PopularHeading": "Populaire",
	"Library_FriendsActivity_PopularHover": "Nous vous montrons ce jeu car plusieurs de vos amis y ont joué récemment.",
	"Library_FriendsActivity_DontForgetHeading": "Pensez-y",
	"Library_FriendsActivity_DontForgetHover": "Nous vous montrons ce jeu car vous n'y avez pas joué récemment, et vos amis y jouent.",
	"Library_FriendsActivity_NewToGroupHeading": "Nouveau jeu de vos amis",
	"Library_FriendsActivity_NewToGroupHover": "Nous vous montrons ce jeu car vos amis ont commencé à y jouer récemment.",
	"Library_FriendsActivity_ReturnedToGroupHeading": "C'est reparti pour un tour",
	"Library_FriendsActivity_ReturnedToGroupHover": "Nous vous montrons ce jeu car vos amis ont recommencé à y jouer récemment.",
	"Library_Recent_NoRecentGames_GamesOwned": "Vous avez (%1$s) jeux.",
	"Library_Recent_NoRecentGames_StoreLink": "Visitez le %1$s pour trouver des jeux à ajouter :",
	"Library_Recent_NoRecentGames_SteamStore": "magasin Steam",
	"Library_Recent_NoRecentGames_FreeToPlay": "Jeux gratuits",
	"Library_Recent_NoRecentGames_GamesOnSale": "Jeux en solde",
	"Library_Recent_NoRecentGames_NewReleases": "Nouveautés",
	"Library_Recent_NoRecentGames_ActivateProduct": "Activer un produit",
	"Library_Recent_NoRecentGames_RedeemCode": "Activer un code de porte-monnaie",
	"Library_SortCollectionBy": "Trier par",
	"Library_SortByFavoritesFirst": "Favoris d'abord",
	"Library_SortByAlphabetical": "Ordre alphabétique",
	"Library_SortByPctAchievementsComplete": "% de succès obtenus",
	"Library_SortByLastUpdated": "Dernières mises à jour",
	"Library_SortByHoursPlayed": "Heures de jeu",
	"Library_SortByLastPlayed": "Dernière utilisation",
	"Library_SortByReleaseDate": "Date de sortie ",
	"Library_SortByAddedToLibrary": "Date d'ajout à la bibliothèque",
	"Library_SortBySizeOnDisk": "Taille sur le disque",
	"Library_SortByMetacriticScore": "Score Metacritic",
	"Library_SortByFriendsPlaying": "Amis qui jouent à ce jeu",
	"Library_InstalledOnlyCheck": "Installés uniquement",
	"GridSection_Favorites": "Favoris",
	"GridSection_EverythingElse": "Tout le reste",
	"GridSection_Over100Hours": "Plus de 100 heures",
	"GridSection_Over60Hours": "Plus de 60 heures",
	"GridSection_Over40Hours": "Plus de 40 heures",
	"GridSection_Over20Hours": "Plus de 20 heures",
	"GridSection_Over10Hours": "Plus de 10 heures",
	"GridSection_Over1Hour": "Plus d'une heure",
	"GridSection_LessThan1Hour": "Moins d'une heure",
	"GridSection_Over90Metacritic": "Supérieur à 90",
	"GridSection_Over80Metacritic": "Supérieur à 80",
	"GridSection_Over70Metacritic": "Supérieur à 70",
	"GridSection_Over50Metacritic": "Supérieur à 50",
	"GridSection_EverythingElseMetacritic": "Tout le reste",
	"GridSection_UnknownReleaseDate": "Inconnue",
	"GridSection_GreaterThan100GB": "Plus de 100 Go",
	"GridSection_GreaterThan50GB": "Plus de 50 Go",
	"GridSection_GreaterThan20GB": "Plus de 20 Go",
	"GridSection_LessThan20GB": "Moins de 20 Go",
	"GridSection_NoSizeOnDisk": "Pas de taille",
	"GridSection_NotInstalled": "Non installé",
	"GridSection_MoreThan10YearsAgo": "Il y a plus de 10 ans",
	"GridSection_Never": "Jamais",
	"AppDetails_SectionTitle_Activity": "Activité",
	"AppDetails_SectionTitle_Friends": "Amis qui jouent à ce jeu",
	"AppDetails_SectionTitle_Friends_Software": "Amis qui utilisent ce logiciel",
	"AppDetails_SectionTitle_Achievements": "Succès",
	"AppDetails_SectionTitle_TradingCards": "Cartes à échanger",
	"AppDetails_SectionTitle_Screenshots": "Captures d'écran",
	"AppDetails_SectionTitle_Updates": "Mises à jour et événements récents",
	"AppDetails_SectionTitle_DLC": "DLC",
	"AppDetails_SectionTitle_LastPlayed": "Dernière utilisation",
	"AppDetails_SectionTitle_LastLaunched": "Dernier lancement",
	"AppDetails_SectionTitle_PlayTime": "Temps de jeu",
	"AppDetails_SectionTitle_UsageTime": "Temps d'utilisation",
	"AppDetails_SectionTitle_Workshop": "Steam Workshop",
	"AppDetails_SectionTitle_Community": "Contenu de la communauté",
	"AppDetails_SectionTitle_Links": "Liens",
	"AppDetails_SectionTitle_SignIn_Pre": "Connectez-vous",
	"AppDetails_SectionTitle_SignIn": "%1$s pour voir l'activité de vos amis",
	"AppDetails_SectionTitle_OpenFriends": "Ouvrir la liste d'amis",
	"AppDetails_SectionTitle_OfflineMode": "Mode hors ligne",
	"AppDetails_Community_Tooltip1": "Cette section contient des captures d'écran, des illustrations, des vidéos, des guides et bien plus, le tout provenant de la communauté.",
	"AppDetails_Community_Tooltip2": "Vous pouvez aimer, partager, commenter ou signaler ce contenu.",
	"AppDetails_Community_Guide": "Guide de la communauté",
	"AppDetails_Links_Store": "Page du magasin",
	"AppDetails_Links_Community": "Hub de la communauté",
	"Bbcode_Originally_Posted_By": "Publié par",
	"AppDetails_InOfflineMode": "Steam est actuellement en mode hors ligne. En mode hors ligne, de nombreuses fonctionnalités de votre bibliothèque Steam ne sont pas disponibles, comme l’activité et vos amis. Passez en mode en ligne pour voir ce contenu.",
	"AppDetails_GoOnline": "Passer en ligne",
	"GameAction_Stop": "Arrêter",
	"GameAction_Cancel": "Annuler",
	"GameAction_Install": "Installer",
	"GameAction_Uninstall": "Désinstaller",
	"GameAction_Play": "Jouer",
	"GameAction_Launch": "Lancer",
	"GameAction_PreLoad": "Précharger",
	"GameAction_Update": "Mettre à jour",
	"GameAction_Download": "Télécharger",
	"GameAction_Resume": "Reprendre",
	"GameAction_Pause": "Mettre en pause",
	"GameAction_BorrowApp": "Emprunter",
	"GameAction_PurchaseApp": "Acheter",
	"GameAction_GameProperties": "Propriétés...",
	"GameAction_AddToFavorites": "Ajouter aux favoris",
	"GameAction_RemoveFromFavorites": "Retirer des favoris",
	"GameAction_AddToHidden": "Masquer ce jeu",
	"GameAction_RemoveFromHidden": "Ne plus masquer",
	"GameAction_AddToFamilyGames": "Ajouter aux jeux familiaux",
	"GameAction_RemoveFromFamilyGames": "Retirer des jeux familiaux",
	"GameAction_RemoveShortcut": "Supprimer un jeu non Steam",
	"GameAction_AddToCollection": "Ajouter à",
	"GameAction_RemoveFromCollection": "Retirer de",
	"GameAction_CreateDesktopShortcut": "Créer un raccourci sur le Bureau",
	"GameAction_BackUpFiles": "Sauvegarder les fichiers du jeu...",
	"GameAction_Stream": "Streamer",
	"GameAction_Connect": "Se connecter",
	"GameAction_SetCustomArtwork": "Définir une image personnalisée",
	"GameAction_ClearCustomArtwork": "Retirer l'image personnalisée",
	"GameAction_ViewCDKeys": "Clés CD",
	"GameAction_ControllerConfiguration": "Configuration de la manette",
	"GameAction_RemoveAppFromCollection": "FAITES GLISSER L'APPLICATION ICI pour supprimer %1$s de la collection « %2$s »",
	"GameAction_RemoveAppFromMultipleCollections": "FAITES GLISSER L'APPLICATION ICI pour supprimer %1$s de ces collections",
	"GameAction_RemoveMultipleAppsFromCollection": "FAITES GLISSER CES APPLICATIONS ICI pour les supprimer de la collection « %1$s »",
	"GameAction_RemoveMultipleAppsFromMultipleCollections": "FAITES GLISSER CES APPLICATIONS ICI pour les supprimer de ces collections",
	"GameAction_NavigateToAllCollectionsWithDrag": "FAITES GLISSER et MAINTENEZ le jeu ICI pour afficher toutes les collections",
	"GameAction_AddToCollectionOption_NewCollection": "Nouvelle collection...",
	"GameAction_NewCollectionDialogTitle": "Nouvelle collection",
	"GameAction_Manage": "Gérer",
	"GameAction_Favorite": "Ajouter aux favoris",
	"GameAction_UnFavorite": "Dans vos favoris",
	"GameAction_ViewDetails": "Afficher plus de détails",
	"GameAction_ViewDetails_Collapse": "Afficher moins de détails",
	"GameAction_ViewDetails_ScrollUp": "Faire défiler jusqu'en haut",
	"GameActionPlural_Install": "Tout installer",
	"GameActionPlural_Uninstall": "Tout désinstaller",
	"GameActionPlural_PreLoad": "Tout précharger",
	"GameActionPlural_Update": "Tout mettre à jour",
	"GameActionPlural_Download": "Tout télécharger",
	"GameActionPlural_Resume": "Tout reprendre",
	"GameActionPlural_AddToFavorites": "Tout ajouter aux favoris",
	"GameActionPlural_RemoveFromFavorites": "Tout retirer des favoris",
	"GameActionPlural_AddToHidden": "Masquer tous ces jeux",
	"GameActionPlural_RemoveFromHidden": "Ne plus masquer tous ces jeux",
	"GameActionPlural_AddToFamilyGames": "Tout ajouter aux jeux familiaux",
	"GameActionPlural_RemoveFromFamilyGames": "Tout retirer des jeux familiaux",
	"GameActionPlural_RemoveShortcut": "Supprimer tous les jeux non Steam",
	"GameActionPlural_AddToCollection": "Tout ajouter à",
	"GameActionPlural_RemoveFromCollection": "Tout retirer de",
	"GameActionPlural_CreateDesktopShortcut": "Créer des raccourcis sur le Bureau",
	"GameActionPlural_BackUpFiles": "Sauvegarder les fichiers des jeux...",
	"DisplayStatus_Launching": "Lancement",
	"DisplayStatus_Uninstalling": "Désinstallation",
	"DisplayStatus_Installing": "Installation",
	"DisplayStatus_Running": "Lancé",
	"DisplayStatus_Validating": "Vérification",
	"DisplayStatus_Updating": "Mise à jour en cours",
	"DisplayStatus_Downloading": "Téléchargement en cours",
	"DisplayStatus_Synchronizing": "Synchronisation avec Steam Cloud",
	"DisplayStatus_ReadyToInstall": "Prêt à être installé",
	"DisplayStatus_ReadyToPreload": "Prêt à être préchargé",
	"DisplayStatus_ReadyToLaunch": "Prêt à être lancé",
	"DisplayStatus_RegionRestricted": "Non disponible dans votre région",
	"DisplayStatus_PresaleOnly": "Cet article n'est pas encore disponible",
	"DisplayStatus_InvalidPlatform": "Disponible sur",
	"DisplayStatus_PreloadComplete": "Préchargement terminé",
	"DisplayStatus_BorrowerLocked": "Cette bibliothèque n'est pas disponible pour le partage familial.",
	"DisplayStatus_UpdatePaused": "Mise à jour en pause",
	"DisplayStatus_UpdateQueued": "Mise à jour en attente",
	"DisplayStatus_UpdateRequired": "Mise à jour nécessaire",
	"DisplayStatus_UpdateDisabled": "Les mises à jour sont désactivées car Steam est en mode hors ligne. Passez en mode en ligne pour terminer de mettre à jour ce jeu.",
	"DisplayStatus_DownloadPaused": "Téléchargement en pause",
	"DisplayStatus_DownloadQueued": "Téléchargement en attente",
	"DisplayStatus_DownloadRequired": "Téléchargement nécessaire",
	"DisplayStatus_DownloadDisabled": "Les téléchargements sont désactivés car Steam est en mode hors ligne. Passez en mode en ligne pour terminer le téléchargement de ce jeu.",
	"DisplayStatus_LicensePending": "Votre achat n'est pas encore terminé.",
	"DisplayStatus_LicenseExpired": "La licence a expiré",
	"DisplayStatus_AvailForFree": "Disponible gratuitement",
	"DisplayStatus_AvailToBorrow": "Peut être emprunté",
	"DisplayStatus_AvailGuestPass": "Invitation disponible",
	"DisplayStatus_Purchase": "Disponible à l'achat",
	"DisplayStatus_Compact_Launching": "Lancement",
	"DisplayStatus_Compact_Uninstalling": "Désinstallation",
	"DisplayStatus_Compact_Installing": "Installation",
	"DisplayStatus_Compact_Running": "Lancé",
	"DisplayStatus_Compact_Validating": "Vérification",
	"DisplayStatus_Compact_Updating": "Mise à jour en cours",
	"DisplayStatus_Compact_Downloading": "Téléchargement en cours",
	"DisplayStatus_Compact_Synchronizing": "Synchronisation avec Steam Cloud",
	"DisplayStatus_Compact_ReadyToInstall": "Prêt à être installé",
	"DisplayStatus_Compact_ReadyToPreload": "Prêt à être préchargé",
	"DisplayStatus_Compact_ReadyToLaunch": "Prêt à être lancé",
	"DisplayStatus_Compact_RegionRestricted": "Non disponible dans cette région",
	"DisplayStatus_Compact_PresaleOnly": "Ce jeu n'est pas encore disponible",
	"DisplayStatus_Compact_InvalidPlatform": "Disponible sur",
	"DisplayStatus_Compact_ParentalBlocked": "Bloqué par le mode famille",
	"DisplayStatus_Compact_PreloadComplete": "Préchargement terminé",
	"DisplayStatus_Compact_BorrowerLocked": "Partage familial non disponible",
	"DisplayStatus_Compact_UpdatePaused": "Mise à jour en pause",
	"DisplayStatus_Compact_UpdateQueued": "Mise à jour en attente",
	"DisplayStatus_Compact_UpdateRequired": "Mise à jour nécessaire",
	"DisplayStatus_Compact_UpdateDisabled": "Mises à jour désactivées en mode hors ligne",
	"DisplayStatus_Compact_DownloadPaused": "Téléchargement en pause",
	"DisplayStatus_Compact_DownloadQueued": "Téléchargement en attente",
	"DisplayStatus_Compact_DownloadRequired": "Téléchargement nécessaire",
	"DisplayStatus_Compact_DownloadDisabled": "Téléchargements désactivés en mode hors ligne",
	"DisplayStatus_Compact_LicensePending": "Finalisation de l'achat",
	"DisplayStatus_Compact_LicenseExpired": "La licence a expiré",
	"DisplayStatus_Compact_AvailForFree": "Disponible gratuitement",
	"DisplayStatus_Compact_AvailToBorrow": "Peut être emprunté",
	"DisplayStatus_Compact_AvailGuestPass": "Invitation disponible",
	"DisplayStatus_Compact_Purchase": "Disponible à l'achat",
	"DisplayStatus_ReleaseDate": "Disponible le %1$s",
	"DisplayStatus_CustomReleaseDate": "Date de sortie prévue : %1$s",
	"Downloads_State_Bytes_Of_Bytes": "%1$s sur %2$s",
	"Downloads_State_None": "",
	"Downloads_State_Reconfiguring": "Démarrage du téléchargement",
	"Downloads_State_Validating": "Vérification des fichiers",
	"Downloads_State_AddingFiles": "Copie des fichiers",
	"Downloads_State_Preallocating": "Allocation d'espace",
	"Downloads_State_Downloading": "",
	"Downloads_State_Staging": "",
	"Downloads_State_Committing": "Finalisation",
	"Downloads_State_Verifying": "Vérification du téléchargement",
	"Downloads_State_Stopping": "Arrêt du téléchargement",
	"Downloads_State_Running": "",
	"Downloads_State_SecondsRemaining": "%1$s seconde(s) restante(s)",
	"Downloads_State_MinutesRemaining": "%1$s minute(s) restante(s)",
	"Downloads_State_Calculating": "Calcul...",
	"LaunchApp_Action_UpdatingAppInfo": "Vérification de la configuration",
	"LaunchApp_Action_ShowEula": "Affichage du CLUF",
	"LaunchApp_Action_DownloadingDepots": "Téléchargement du contenu (%1$s %)",
	"LaunchApp_Action_DownloadingWorkshop": "Téléchargement du Workshop (%1$s %)",
	"LaunchApp_Action_UpdatingDRM": "Mise à jour de l'exécutable",
	"LaunchApp_Action_GettingLegacyKey": "Mise à jour de la clé CD",
	"LaunchApp_Action_RunningInstallScript": "Exécution du script d'installation (%1$s)",
	"LaunchApp_Action_SynchronizingCloud": "Synchronisation avec Steam Cloud",
	"LaunchApp_Action_VerifyingFiles": "Vérification de l'exécutable",
	"LaunchApp_Action_CreatingProcess": "Lancement de l'exécutable",
	"LaunchApp_Action_WaitingGameWindow": "Lancement de l'exécutable",
	"LaunchApp_Action_DelayLaunch": "Lancement différé (%1$s %)",
	"AppDetails_TitleUpdatedSincePlayed": "Ce jeu a été mis à jour depuis que vous y avez joué pour la dernière fois",
	"AppDetails_TitleUpdatedSincePlayedLink": "Découvrir les changements",
	"AppDetails_BadgeLevel": "Niveau %1$s, points d'XP : %2$s",
	"AppDetails_UnearnedBadgeXP": "%1$s points d'XP",
	"AppDetails_BadgeLevelNoXP": "Niveau %1$s",
	"AppDetails_Review_ViewOrEdit": "Modifier mon évaluation",
	"AppDetails_Review_YourReview": "Mon évaluation",
	"AppDetails_Review_Ignore_Stale_Reviews": "Ne plus me rappeler de mettre à jour cette évaluation.",
	"AppDetails_Review_Unignore_Stale_Reviews": "Me rappeler de mettre à jour cette évaluation.",
	"AppDetails_Review_RecommendGame": "Recommanderiez-vous ce jeu ?",
	"AppDetails_Review_RecommendSoftware": "Recommanderiez-vous ce logiciel ?",
	"AppDetails_Review_WriteReview": "Écrire une évaluation pour %1$s",
	"AppDetails_Review_PlayedForTime": "Vous y avez joué %1$s",
	"AppDetails_Review_PlayedForTime_Software": "Vous avez utilisé ce produit pendant %1$s",
	"AppDetails_Review_RecommendGameButton_Yes": "Oui",
	"AppDetails_Review_RecommendGameButton_No": "Non",
	"AppDetails_Review_PlaytimeAtReview": "Temps de jeu au moment de l'évaluation : %1$s",
	"AppDetails_Review_PlaytimeAtReview_Software": "Temps d'utilisation au moment de l'évaluation : %1$s",
	"AppDetails_Review_NotRecommended": "Non recommandé",
	"AppDetails_Review_Recommended": "Recommandé",
	"AppDetails_Review_AdditionalPlaytime": "Vous y avez joué %1$s depuis que vous avez écrit cette évaluation.",
	"AppDetails_Review_AdditionalPlaytime_Software": "Vous avez utilisé ce produit pendant %1$s depuis que vous avez écrit cette évaluation.",
	"AppDetails_Review_ChangedYourMind": "Avez-vous changé d'avis ?",
	"AppDetails_Review_IHaveNotChangedMyMind": "Non",
	"AppDetails_Review_UpVotes": "Votes positifs :",
	"AppDetails_Review_Comments": "Commentaires :",
	"AppDetails_Review_ViewAll": "Voir toutes mes évaluations",
	"AppDetails_Review_ViewAllByFriend": "Voir toutes les évaluations de %1$s",
	"OverflowBox_Action_Collapse": "Réduire",
	"OverflowBox_Action_Expand": "Développer",
	"OverflowBox_More": "(%1$s de plus)",
	"AppDetails_FriendsInGameNow": "%1$s ami y joue en ce moment",
	"AppDetails_FriendsInGameNow_Plural": "%1$s amis y jouent en ce moment",
	"AppDetails_FriendsPlayedRecently": "%1$s ami y a joué récemment",
	"AppDetails_FriendsPlayedRecently_Plural": "%1$s amis y ont joué récemment",
	"AppDetails_FriendsPlayedRecentlyExpand": "Afficher tous les amis qui ont joué à ce jeu récemment",
	"AppDetails_FriendsPlayed": "%1$s ami y a déjà joué",
	"AppDetails_FriendsPlayed_Plural": "%1$s amis y ont déjà joué",
	"AppDetails_FriendsPlayedExpand": "Afficher tous les amis qui ont déjà joué à ce jeu",
	"AppDetails_FriendsMore": "(%1$s de plus)",
	"AppDetails_FriendsLess": "Réduire",
	"AppDetails_FriendsWishlisted": "%1$s ami a ajouté %2$s à sa liste de souhaits",
	"AppDetails_FriendsWishlisted_Plural": "%1$s amis ont ajouté %2$s à leurs listes de souhaits",
	"AppDetails_FriendsWishlistExpand": "Afficher tous les amis qui ont ajouté ce jeu à leurs listes de souhaits",
	"AppDetails_Friends_ViewAll": "Voir tous les amis qui y jouent",
	"AppDetails_GameInfo": "Informations sur le jeu",
	"AppDetails_Publisher": "Éditeur :",
	"AppDetails_Developer": "Développeur :",
	"AppDetails_Franchise": "Franchise :",
	"AppDetails_ReleaseDate": "Date de sortie :",
	"AppDetails_OriginalReleaseDate": "Date de sortie originale :",
	"AppDetails_Feature_SinglePlayer": "Un joueur",
	"AppDetails_Feature_MultiPlayer": "Multijoueur",
	"AppDetails_Feature_CoOp": "Coopération",
	"AppDetails_Feature_SteamAchievements": "Succès",
	"AppDetails_Feature_SteamCloud": "Sauvegardes sur le Cloud",
	"AppDetails_Feature_FullController": "Prise en charge complète des manettes",
	"AppDetails_Feature_PartialController": "Prise en charge partielle des manettes",
	"AppDetails_Feature_SteamWorkshop": "Steam Workshop",
	"AppDetails_Feature_VRSupport": "Prise en charge de la VR",
	"AppDetails_ViewAllUpdates": "Voir toutes les mises à jour",
	"AppDetails_ViewAllAchievements": "Voir mes succès",
	"AppDetails_ViewGlobalAchievements": "Voir les statistiques de succès générales",
	"AppDetails_PlayerUnlockedPercent": "%1$s/%2$s succès débloqués",
	"AppDetails_PlayerUnlockedPercentAll": "Vous avez débloqué tous les succès ! %1$s/%2$s",
	"AppDetails_Achievements_Unlocked": "Débloqué le %1$s",
	"AppDetails_PctUnlocked": "%1$s % des joueurs ont débloqué ce succès",
	"AppDetails_GlobalCompare": "Vous avez fait mieux que %1$s % des joueurs",
	"AppDetails_ViewTradingCards": "Voir mes cartes à échanger",
	"AppDetails_Achievements_Locked": "Succès verrouillés",
	"AppDetails_TradingCardsLeft": "Il vous reste 1 carte à échanger à récupérer",
	"AppDetails_TradingCardsLeft_Plural": "Il vous reste %1$s cartes à échanger à récupérer",
	"AppDetails_TradingCardsLevelUp": "Vous avez assez de cartes à échanger pour passer au niveau supérieur !",
	"AppDetails_TradingCardsMaxed": "Félicitations ! Votre badge a atteint le niveau maximum !",
	"AppDetails_BrowseWorkshop": "Parcourir le Workshop",
	"AppDetails_ViewSubscribedItems": "Voir mes abonnements",
	"AppDetails_ViewItemInWorkshop": "Voir sur le Workshop",
	"AppDetails_MoreItemsFrom": "Voir les objets de ce créateur",
	"AppDetails_SubscribeToItem": "S'abonner",
	"AppDetails_UnsubscribeFromItem": "Se désabonner",
	"AppDetails_Subscribed": "Abonné(e)",
	"AppDetails_ViewMoreInWorkshop": "En voir plus sur le Workshop",
	"AppDetails_WorkshopSubCount": "Vous êtes abonné(e) à %1$s objets sur le Workshop.",
	"AppDetails_WorkshopVisit": "Consulter le Workshop",
	"AppDetails_WorkshopLearnMore": "En savoir plus",
	"AppDetails_WorkshopFeaturedHeader": "Objet à la une",
	"AppDetails_WorkshopFeaturedItem": "Objet populaire",
	"AppDetails_WorkshopFeaturedMoreInfo": "En savoir plus",
	"AppDetails_WorkshopFeaturedHideItem": "Masquer cet objet",
	"AppDetails_WorkshopFileSize": "Taille du fichier : %1$s",
	"AppDetails_WorkshopFileSizeBytes": "%1$s octets",
	"AppDetails_WorkshopFileSizeKb": "%1$s Ko",
	"AppDetails_WorkshopFileSizeMb": "%1$s Mo",
	"AppDetails_WorkshopFileSizeGb": "%1$s Go",
	"AppDetails_WorkshopLastUpdated": "Dernière mise à jour : %1$s",
	"DLCStatus_installed": "Installé",
	"DLCStatus_notinstalled": "Non installé",
	"DLCStatus_downloading": "Téléchargement en cours",
	"DLC_DateAdded": "Ajouté le %1$s",
	"AppDetails_ManageDLC": "Gérer mes %1$s DLC",
	"AppDetails_ManageMyDLC": "Gérer mon DLC",
	"AppDetails_ViewStoreDLC": "Voir la page du magasin de ce DLC",
	"AppDetails_DLCSpotlight": "Le dernier DLC que vous avez acquis a été ajouté, il sera installé avec le jeu. Vous pouvez gérer vos DLC %1$s.",
	"AppDetails_DLCSpotlight_Installed": "Le dernier DLC acquis a été installé automatiquement. Vous pouvez gérer vos DLC %1$s.",
	"AppDetails_DLCSpotlight_here": "ici",
	"ManageDLC_Title": "Gérer mes DLC",
	"ManageDLC_Column_Name": "Nom",
	"ManageDLC_Column_DateAdded": "Date d'ajout",
	"ManageDLC_Column_Enabled": "Activé",
	"ManageDLC_Column_Installed": "Installé",
	"ManageDLC_Search": "Rechercher...",
	"ManageDLC_Installed": "%1$s/%2$s installés",
	"ManageDLC_ViewMore": "En voir plus sur le magasin",
	"ManageDLC_NoResults": "Aucun résultat trouvé pour « %1$s »",
	"AppDetails_ViewBadgePage": "Voir la page du badge",
	"AppDetails_VisitTradeForum": "Consulter le forum des échanges",
	"AppDetails_BuyCards": "Acheter les cartes restantes sur le marché",
	"AppDetails_SellCards": "Vendre ces cartes sur le marché",
	"AppDetails_SearchCard": "Afficher cette carte sur le marché",
	"AppDetails_ShowFriendsList": "Afficher ma liste d'amis",
	"AppDetails_ViewFriendsWhoPlay": "Voir les amis en jeu",
	"AppDetails_Link_Discussions": "Discussions",
	"AppDetails_Link_FindGroups": "Trouver des groupes",
	"AppDetails_Link_GameHub": "Hub de la communauté",
	"AppDetails_Link_Guides": "Guides",
	"AppDetails_Link_Store": "Page du magasin",
	"AppDetails_Link_Support": "Assistance",
	"AppDetails_Link_Workshop": "Workshop",
	"AppDetails_Link_Controller": "Configurations de la manette",
	"AppDetails_SocialMediaLink": "%1$s sur %2$s",
	"AppDetails_SocialMediaType_4": "Twitter",
	"AppDetails_SocialMediaType_5": "Twitch",
	"AppDetails_SocialMediaType_6": "YouTube",
	"AppDetails_SocialMediaType_7": "Facebook",
	"AppDetails_Screenshot": "Capture d'écran",
	"AppDetails_Screenshot_Caption": "Description : %1$s",
	"AppDetails_Screenshot_Date": "Date : %1$s",
	"AppDetails_Screenshot_Dimensions": "Dimensions en pixels : %1$s x %2$s",
	"AppDetails_Screenshot_Uploaded": "Publié le %1$s à %2$s",
	"AppDetails_OpenScreenshotUploader": "Ouvrir le gestionnaire de captures d'écran",
	"AppDetails_ViewUploadedScreenshots": "Voir les captures d'écran publiées",
	"AppDetails_ManageMyScreenshot": "Gérer ma capture d'écran",
	"AppDetails_ManageMyScreenshot_Plural": "Gérer mes %1$s captures d'écran",
	"AppDetails_HowToScreenshot": "Vous pouvez prendre une capture d'écran en appuyant sur %1$s pendant que vous êtes en jeu.",
	"AppDetails_ChangeMyScreenshotKey": "Définir un nouveau raccourci",
	"AppDetails_NoScreenshots": "Vous n'avez pris aucune capture d'écran",
	"AppDetails_Artwork": "Image",
	"AppDetails_Video": "Vidéo",
	"AppDetails_CommunityItem": "Contenu de la communauté",
	"AppDetails_CommunityFeed_OutOfContent": "Aucun contenu additionnel",
	"AppDetails_CommunityFeed_Inappropriate": "Ce contenu peut ne pas être approprié pour tous les âges",
	"AppDetails_CommunityFeed_ViewContent": "Voir le contenu",
	"AppDetails_CommunityFeed_EditPreferences": "Modifier mes préférences",
	"AppDetails_CommunityFeed_LoadCommunity": "Charger plus de contenu de la communauté",
	"AppBox_NewToLibrary": "Nouveau dans la bibliothèque",
	"AppBox_ComingSoon": "Prochainement",
	"AppBox_NewToLibrary_Short": "Nouveau",
	"AppBox_ComingSoon_Short": "Bientôt",
	"AppBox_PlayTimeHeader": "Temps de jeu",
	"AppBox_RecentPlayTime_Hours": "Deux dernières semaines : %1$s heures",
	"AppBox_RecentPlayTime_Minutes": "Deux dernières semaines : %1$s minutes",
	"AppBox_TotalPlayTime_Hours": "Total : %1$s heures",
	"AppBox_TotalPlayTime_Minutes": "Total : %1$s minutes",
	"AppActivity_Achieved": " a remporté un succès ",
	"AppActivity_PostedScreenshot": " a partagé une capture d'écran ",
	"AppActivity_PostedScreenshot_Plural": " a partagé %1$s captures d'écran ",
	"AppActivity_PostedVideo": " a partagé une vidéo ",
	"AppActivity_PostedVideo_Plural": " a partagé %1$s vidéos ",
	"AppActivity_ReceivedNewGame": " possède maintenant %1$s",
	"AppActivity_PlayedGameFirstTime": " a joué à %1$s pour la première fois",
	"AppActivity_LaunchedSoftwareFirstTime": " a lancé %1$s pour la première fois",
	"AppActivity_AddedGameToWishlist": " a ajouté %1$s à sa %2$s",
	"AppActivity_Wishlist": "liste de souhaits",
	"AppActivity_Achieved_PlusMore": "…et %1$s succès de plus",
	"AppActivity_Achieved_PlusMore_Label": "Voir tous les succès de %1$s",
	"AppActivity_NoActivity": "Aucune activité récente de vos amis ni des développeurs de cet article.",
	"AppActivity_UserStatus_Time": " a publié un statut à %1$s",
	"AppActivity_UserStatus": " a publié un statut",
	"AppActivity_StatusUpdate": "Publiez un statut pour vos amis",
	"AppActivity_StatusUpdate_Post": "Dites quelque chose à propos de ce jeu à vos amis...",
	"AppActivity_StatusUpdate_Software_Post": "Dites quelque chose à propos de ce logiciel à vos amis...",
	"AppActivity_Comment_Reply": "Répondre...",
	"AppActivity_PostStatusUpdate": "Publier",
	"AppActivity_FetchMore": "Charger plus d'activité",
	"AppActivity_EndofFeed": "Fin du flux d'activité",
	"AppActivity_DeleteUserNews": "Cliquez ici pour supprimer cette publication.",
	"AppActivity_ConfirmDeleteTitle": "Supprimer cette publication",
	"AppActivity_ConfirmDeleteTitle_Desc": "Voulez-vous vraiment supprimer cette publication ? Cette action est irréversible.",
	"AppActivity_RecommendedGame": " a évalué ce jeu",
	"AppActivity_RecommendedGame_ReadMore": "En savoir plus",
	"AppActivity_RatingDetails": "%1$s personnes ont évalué positivement ceci",
	"AppActivity_RatingDetails_1Other": "1 personne a évalué positivement ceci, %1$s",
	"AppActivity_RatingDetails_2Others": "%1$s personnes ont évalué positivement ceci, y compris %2$s et %3$s",
	"AppActivity_RatingDetails_User": "Vous avez évalué positivement ceci",
	"AppActivity_RatingDetails_User_1Other": "%1$s personnes ont évalué positivement ceci, y compris vous et %2$s",
	"AppActivity_RatingDetails_User_2Others": "%1$s personnes ont évalué positivement ceci, y compris vous, %2$s et %3$s",
	"AppActivity_RatingDetails_PublishedFile": "%1$s votes positifs",
	"AppActivity_RateUp": "Vote positif",
	"AppActivity_ConfirmDeleteCommentTitle": "Supprimer ce commentaire",
	"AppActivity_ConfirmDeleteCommentTitle_Desc": "Voulez-vous vraiment supprimer ce commentaire ? Cette action est irréversible.",
	"AppActivity_MakeCommentsVisible": "Voir les commentaires précédents (%1$s)",
	"AppActivity_Settings": "Paramètres",
	"AppActivity_ViewComments": "Voir les commentaires",
	"AppActivity_AddComments": "Ajouter un commentaire",
	"AppActivity_ContributeComments": "Répondre",
	"AppActivity_SteamTradingCards_EarnedTradingCards": " a obtenu des cartes à échanger",
	"AppActivity_SteamTradingCards_EarnedTradingCard": " a obtenu une carte à échanger",
	"AppActivity_SteamTradingCards_EarnedBoosterPack": " a obtenu un booster pack",
	"AppActivity_SteamTradingCards_BadgeCrafted": " a fabriqué un badge",
	"AppActivity_ViewLatestNews": "Afficher les dernières actualités",
	"AppActivity_EventType_GameUpdate": "Mise à jour du jeu",
	"AppSpotlight_PostGameSummary": "Résumé post-match",
	"AppDetails_Shortcut_Explanation": "Certaines informations détaillées de %1$s ne sont pas disponibles car il s'agit d'un mod ou d'un raccourci non Steam. Steam vous permettra néanmoins de lancer le jeu et dans la plupart des cas, l'overlay Steam sera disponible en cours de jeu.",
	"AppDetails_Takeover_Update_Header": "Au cas où vous l'auriez manquée",
	"AppDetails_Takeover_Update_ViewAll": "Voir toutes les mises à jour du jeu (%1$s)",
	"AppDetails_Takeover_Update_ReadMore": "En savoir plus",
	"AppDetails_Takeover_DLC_Header": "Nouveaux articles ajoutés",
	"AppDetails_Takeover_DLC_ViewInStore": "Voir la page du magasin de %1$s",
	"AppDetails_Takeover_Achievements_Header": "Vous avez joué %2$s et vous avez déverrouillé un nouveau succès...",
	"AppDetails_Takeover_Achievements_Header_Plural": "Vous avez joué %2$s et vous avez déverrouillé de nouveaux succès...",
	"AppDetails_Takeover_TradingCards_Header": "Vous avez joué à %2$s et vous avez obtenu un nouvel item...",
	"AppDetails_Takeover_TradingCards_Header_Plural": "Vous avez joué à %2$s et vous avez obtenu de nouveaux items...",
	"AppDetails_ViewMyInventory": "Voir mon inventaire",
	"AppDetails_ViewInMyInventory": "Voir dans mon inventaire",
	"AppPortraitHover_DownloadStatusTitle": "Téléchargement en cours",
	"AppPortraitHover_DownloadStatusTitle_Update": "Téléchargement de la mise à jour",
	"AppPortraitHover_DaysSinceLastUpdate": "Mis à jour le %1$s",
	"AppPortraitHover_FriendsPlaying": "%1$s amis jouent",
	"MajorUpdate_ViewDetails": "Voir les détails",
	"MajorUpdate_NextUpdate": "Prochaine mise à jour",
	"MajorUpdate_PostTime": "Publié il y a %1$s jours à %2$s h %3$s",
	"MajorUpdate_PostTimeToday": "Publié aujourd'hui à %1$s h %2$s",
	"MajorUpdate_WatchNow": "Regarder sur SteamTV",
	"MajorUpdate_Type0": "Mise à jour importante",
	"MajorUpdate_Type1": "Diffusion en direct",
	"MajorUpdate_Type14": "Mise à jour importante",
	"MajorUpdate_Context_RemoveThisUpdate": "Masquer cette mise à jour",
	"MajorUpdate_Context_ResetHiddenUpdates": "Revoir toutes les mises à jour",
	"MajorUpdate_Context_WhyAmISeeingThis": "Pourquoi ce message s'affiche-t-il ?",
	"MajorUpdate_Context_WhyAmISeeingThis_Text": "Un article de votre bibliothèque auquel vous avez joué plus de 20 heures a reçu une mise à jour importante.",
	"MajorUpdate_Context_WhyAmISeeingThis_Close": "Fermer",
	"CustomArt_ErrorTitle": "Erreur",
	"CustomArt_BadFileType": "Votre fichier doit être au format JPG ou PNG.",
	"CustomArt_UnknownError": "Une erreur est survenue lors de l’enregistrement de votre image.",
	"AppDetails_LibraryInUse": "Bibliothèque utilisée par",
	"AppDetails_InSharedLibrary": "Provient de la bibliothèque de",
	"FriendContextMenu_OpenFriends": "Ouvrir la liste d'amis et le chat",
	"FriendContextMenu_ViewProfile": "Voir le profil",
	"Generic_ScrollToTop": "Haut de la bibliothèque",
	"Generic_ViewGameDetails": "Voir ce jeu dans la bibliothèque",
	"GameDetails_CollectionContext_GoTo": "Voir la collection",
	"GameDetails_CollectionContext_Remove": "Retirer de la collection",
	"ArtworkModal_ViewAll": "Voir toutes les captures d'écran",
	"ArtworkModal_FileSize": "Taille du fichier",
	"ArtworkModal_Posted": "Publié",
	"ArtworkModal_Size": "Taille",
	"ArtworkModal_CreatedBy": "Créé par",
	"CommunityItem_Menu_Report": "Signaler",
	"ReportItem_Title": "Signaler cet objet",
	"ReportItem_Description": "Veuillez indiquer la raison pour laquelle vous considérez que cet objet ne respecte pas les conditions d'utilisation de Steam. Veuillez inclure toute information ou tout lien pertinent. L'envoi de ce signalement est irréversible.",
	"ReportItem_Description_Line2": "Les objets signalés n'apparaîtront plus sur la page d'accueil de votre bibliothèque.",
	"ReportItem_DMCA": "Si vous souhaitez signaler une violation de vos droits d'auteur pour un article, veuillez remplir notre formulaire DMCA de demande de retrait pour violation des droits d'auteur %1$s",
	"ReportItem_DMCA_LinkText": "ici",
	"ReportItem_Error": "Un problème est survenu lors de l'envoi de votre demande à nos serveurs. Veuillez réessayer ultérieurement.",
	"ReportItem_SubmitReport": "Envoyer le signalement",
	"Showcase_AddNewShowcase": "Ajouter une nouvelle étagère",
	"Showcase_DeleteShowcase": "Supprimer cette étagère",
	"Showcase_SelectCategory": "Sélectionnez une étagère",
	"Showcase_EmptyShowcaseHint": "Choisissez ce que vous voulez mettre en avant sur cette étagère. Vous pouvez également la modifier ou la supprimer depuis ce menu.",
	"Showcase_GoToCollection": "Voir la collection",
	"Showcase_GoToAllCollections": "Voir toutes les collections",
	"Showcase_AllYourGames": "Tous les jeux",
	"Showcase_AllCollections": "Affichage des collections",
	"Playtime_TwoWeeks_Minutes": "Vous avez joué %1$s minutes récemment",
	"Playtime_TwoWeeks_Hours": "Vous avez joué %1$s heures récemment",
	"Playtime_Total_Minutes": "%1$s minutes de jeu au total",
	"Playtime_Total_Hours": "%1$s heures de jeu au total",
	"Playtime_Minutes": "%1$s minutes",
	"Playtime_Hours": "%1$s heures",
	"Playtime_Recently": "Vous avez joué %1$s récemment",
	"Playtime_Total": "%1$s de jeu au total",
	"GameList_Search_NoResults_Title": "Vous ne trouvez pas ce que vous cherchez ?",
	"GameList_Search_NoResults_Link": "Parcourir le magasin Steam",
	"StreamingClient_Select_ThisMachine": "Cette machine",
	"Beta_BetaTag": "BÊTA",
	"Beta_Changelist": "Liste des modifications",
	"Beta_GiveFeedback": "Donner son avis"
}
