{
	"Generic_Okay": "确定",
	"Generic_Close": "关闭",
	"Generic_Open": "打开",
	"Generic_GotIt": "明白了！",
	"AppType_0": "无效",
	"AppType_1": "游戏",
	"AppType_2": "软件",
	"AppType_4": "工具",
	"AppType_20": "DLC",
	"AppType_800": "视频",
	"AppType_2000": "音乐",
	"AppType_Singular_0": "无效",
	"AppType_Singular_1": "游戏",
	"AppType_Singular_2": "应用程序",
	"AppType_Singular_4": "工具",
	"AppType_Singular_20": "DLC",
	"AppType_Singular_800": "视频",
	"AppType_Singular_2000": "音乐",
	"AppType_Singular_8000": "漫画",
	"AppType_Singular_40000000": "快捷方式",
	"FilterEdit_SavedFilters": "已保存的筛选条件",
	"FilterEdit_FirstColumnHeader": "筛选类型",
	"FilterEdit_Customize": "自定义",
	"FilterEdit_SearchModeHeader": "高级筛选条件",
	"FilterEdit_CollectionModeHeader": "编辑收藏筛选条件",
	"CollectionEdit_CollectionNameField": "收藏名称：",
	"CollectionEdit_RenameButton": "重命名收藏",
	"Collection_DynamicCollection": "动态收藏",
	"FilterEdit_AdvancedTooltip": "高级筛选选项，以按类型、游戏功能等优化您的游戏列表。",
	"Collection_FreezeDynamicCollection": "一览",
	"Collection_FreezeDynamicCollection_ToolTip": "Convert this dynamic collection to a simple one, freezing the current game list.",
	"Collection_ResetDialogTitle": "重置收藏",
	"Collection_ResetConfirmation": "Are you sure you want to reset your collection list and re-import your old categories?",
	"Collection_AfterResetSummary_NoCollections": "You will have no collections after reset.",
	"Collection_AfterResetSummary_CountAndNames": "You will have the following %1$s collections after reset: %2$s",
	"FilterEdit_SelectedFilters": "已选择的筛选条件",
	"FilterEdit_SaveCollectionNameInputPrompt": "请输入收藏名称",
	"FilterEdit_SaveOverwrite": "收藏“%1$s”已存在。要覆盖吗？",
	"FilterEdit_SaveCollection": "保存为收藏",
	"FilterEdit_SaveDynamicCollectionWithIcon": "保存为 %1$s 动态收藏",
	"FilterEdit_SaveDynamicCollectionNoIcon": "保存为动态收藏",
	"FilterEdit_SaveCollectionVerbose": "保存此搜索为收藏以便将来再次使用。您未来可以随时编辑、重命名、删除或将项目拖进或拉出此收藏。",
	"FilterEdit_SaveStandardCollectionButtonDesc": "收藏是整理您的库的简易方法。将游戏拖放至收藏，或右键点击游戏，将其添加至现有收藏。",
	"FilterEdit_SaveDynamicCollectionButtonDesc": "动态收藏会使用筛选条件创建收藏，且收藏会随着您的库扩大而更新。",
	"FilterEdit_SelectCollectionType": "选择收藏类型",
	"FilterEdit_SelectCollectionTypeButtonCreate": "创建收藏",
	"FilterEdit_SelectCollectionTypeButtonCreateDynamic": "创建动态收藏",
	"FilterEdit_RequiredField": "（必须）",
	"FilterEdit_SearchPrompt": "按名称搜索",
	"FilterEdit_ClearSearch": "退出搜索",
	"FilterEdit_SearchResults": "搜索结果",
	"FilterEdit_CollectionsHiddenPromptTitle": "收藏已隐藏",
	"FilterEdit_CollectionsHiddenPrompt": "您想改变游戏列表视图以便新收藏可见吗？",
	"FilterEdit_AcceptGameListViewChange": "是的，显示收藏",
	"FilterEdit_RejectGameListViewChange": "不，保持视图不变",
	"AdvancedSearch_PaneTitle": "按类型搜索",
	"AdvancedSearch_PlayerSection": "游戏模式",
	"AdvancedSearch_HardwareSection": "硬件支持",
	"AdvancedSearch_FeatureSection": "特色",
	"AdvancedSearch_StateSection": "游戏状态",
	"AdvancedSearch_GenreSection": "类型",
	"AdvancedSearch_StoreTagSection": "商店标签",
	"AdvancedSearch_StoreTagPrompt": "输入标签",
	"FilterCategory_1": "状态",
	"FilterCategory_Features": "特色",
	"FilterCategory_3": "类别",
	"FilterCategory_4": "商店标签",
	"FilterCategory_Type": "类型",
	"FilterCategory_Genre": "类型",
	"FilterCategory_PlayState": "状态",
	"FilterElement_VR": "VR",
	"FilterElement_Tooltip_VR": "包含支持虚拟现实硬件的游戏。",
	"FilterElement_Installed": "已本地安装",
	"FilterElement_Tooltip_Installed": "包含已在此电脑上安装的游戏。",
	"FilterElement_ReadyToPlay": "准备就绪",
	"FilterElement_Tooltip_ReadyToPlay": "包含您可在本地或从另一台电脑流式传输游玩的游戏。",
	"FilterElement_PlayedPreviously": "已玩过",
	"FilterElement_Tooltip_PlayedPreviously": "包含您已经玩过的游戏。",
	"FilterElement_Unplayed": "未玩过",
	"FilterElement_Tooltip_Unplayed": "包含您尚未玩过的游戏。",
	"FilterElement_FullControllerSupport": "控制器（完全支持）",
	"FilterElement_Tooltip_FullControllerSupport": "包含可完全用游戏控制器游玩的游戏。",
	"FilterElement_PartialControllerSupport": "控制器（部分支持）",
	"FilterElement_Tooltip_PartialControllerSupport": "包含可用控制器游玩，但可能需要键盘和鼠标进行安装或有限交互的游戏。",
	"FilterElement_VRSupported": "支持 VR",
	"FilterElement_TradingCards": "集换式卡牌",
	"FilterElement_Tooltip_TradingCards": "包含提供 Steam 集换式卡牌的游戏。",
	"FilterElement_Workshop": "创意工坊",
	"FilterElement_Tooltip_Workshop": "包含集成了 Steam 创意工坊的游戏。",
	"FilterElement_Achievements": "成就",
	"FilterElement_Tooltip_Achievements": "包含可获得 Steam 成就的游戏。",
	"FilterElement_SinglePlayer": "单人",
	"FilterElement_Tooltip_SinglePlayer": "包含有单人模式的游戏。",
	"FilterElement_MultiPlayer": "多人",
	"FilterElement_Tooltip_MultiPlayer": "包含有多人模式的游戏。",
	"FilterElement_CoOp": "合作",
	"FilterElement_Tooltip_CoOp": "包含有多人合作模式的游戏。",
	"FilterElement_GenreAction": "动作",
	"FilterElement_Tooltip_GenreAction": "包含动作游戏。",
	"FilterElement_GenreAdventure": "冒险",
	"FilterElement_Tooltip_GenreAdventure": "包含冒险游戏。",
	"FilterElement_GenreCasual": "休闲",
	"FilterElement_Tooltip_GenreCasual": "包含休闲游戏。",
	"FilterElement_GenreIndie": "独立",
	"FilterElement_Tooltip_GenreIndie": "包含独立游戏。",
	"FilterElement_GenreMMO": "大型多人在线",
	"FilterElement_Tooltip_GenreMMO": "包含大型多人游戏。",
	"FilterElement_GenreRacing": "竞速",
	"FilterElement_Tooltip_GenreRacing": "包含竞速游戏。",
	"FilterElement_GenreRPG": "角色扮演",
	"FilterElement_Tooltip_GenreRPG": "包含角色扮演游戏。",
	"FilterElement_GenreSimulation": "模拟",
	"FilterElement_Tooltip_GenreSimulation": "包含模拟游戏。",
	"FilterElement_GenreSports": "体育",
	"FilterElement_Tooltip_GenreSports": "包含体育游戏。",
	"FilterElement_GenreStrategy": "策略",
	"FilterElement_Tooltip_GenreStrategy": "包含策略游戏。",
	"FilterElement_Tooltip_StoreTag": "包含 Steam 上带有“%1$s”标签的应用程序。",
	"CollectionViewHeader_Tooltip_ManuallyAddedApp": "此游戏已手动添加至收藏。",
	"CollectionViewHeader_Tooltip_ManuallyRemovedApp": "此游戏已从此收藏移除。",
	"CollectionViewHeader_Tooltip_ManuallyRemovedApps_WithCount": "%1$s 款游戏已从此收藏移除。",
	"CollectionViewHeader_ManuallyRemovedApps_WithCount": "%1$s 款游戏已移除",
	"CollectionView_EmptyReadOnlyCollection": "空空如也",
	"CollectionView_EmptyDynamicCollection_Line1": "没有游戏符合此筛选条件！",
	"CollectionView_EmptyDynamicCollection_Line2": "修改筛选条件，或将游戏拖放到此处以创建此收藏。",
	"CollectionView_EmptyCollection": "将游戏拖放到此处以创建此收藏。",
	"CollectionView_EmptyCollection_BecauseFilter": "根据您选择的视图筛选条件，此收藏中的 %1$s 款游戏当前不显示。",
	"CollectionView_EmptyCollection_BecauseFilter_Plural": "根据您选择的视图筛选条件，此收藏中的 %1$s 款游戏当前不显示。",
	"CollectionView_MissingCollection": "未找到收藏。",
	"CollectionView_GamesExcluded": "+%1$s",
	"CollectionView_GamesExcluded_Desc": "款游戏尚未准备就绪",
	"AllCollectionsView_Title": "您的收藏",
	"AllCollectionsView_InfoIcon": "创建%1$s，按您认为合适的方式整理您的游戏，或创建%2$s，按一系列筛选条件将游戏分组。%3$s",
	"AllCollectionsView_InfoIconCollections": "收藏",
	"AllCollectionsView_InfoIconDynamicCollections": "动态收藏",
	"AllCollectionsView_InfoIconFav": "您的%1$s始终会在页面顶部此处显示。",
	"AllCollectionsView_InfoIconFavorites": "收藏夹",
	"AllCollectionsView_AddCollection": "创建新收藏",
	"AllCollectionsView_DragToAddCollection": "拖放到此处以创建新收藏",
	"GameList_Home": "主页",
	"GameList_Search": "搜索",
	"GameList_Category_Uncategorized": "未分类",
	"GameList_Category_Favorites": "收藏夹",
	"GameList_Category_Hidden": "已隐藏",
	"GameList_Category_Hidden_Tooltip": "除非进行搜索，否则隐藏的游戏不会在您的库显示。您可以从顶部的“视图”菜单查看所有隐藏的游戏。",
	"GameList_Category_YourCollections": "您的收藏",
	"GameList_Category_SharedLibraries": "共享库",
	"GameList_SectionHeader_SearchResults": "搜索和筛选结果",
	"GameList_SectionHeader_AddedManually": "手动添加",
	"GameList_SectionHeader_RemovedManually": "手动移除",
	"GameList_SectionHeader_NoRecentActivity": "无已记录活动",
	"GameList_View_Collections": "您的收藏",
	"GameList_View_ThisCollection": "查看此收藏",
	"GameList_View_LibraryList": "筛选后的列表",
	"GameList_View_OneCollection": "收藏视图",
	"GameList_View_SearchResults": "搜索结果",
	"GameList_View_ShowAllCollections": "显示所有收藏",
	"GameList_View_GroupByCollections": "按收藏分组",
	"GameList_View_ExitSearch": "退出搜索",
	"GameList_View_All": "全部",
	"GameList_View_SortByRecent": "按近期活动排序",
	"GameList_View_ShowOnlyReadyToPlay": "仅显示准备就绪的游戏",
	"GameList_View_ShowingOnlyReadyToPlay": "仅显示准备就绪的游戏",
	"GameList_View_ShowOnlyVR": "仅显示 VR 游戏",
	"GameList_View_Platform_Linux": "Show only games that run on Linux",
	"GameList_View_Platform_Apple": "Show only games that run on Apple",
	"GameList_View_ReadyToPlay_ToolTip1": "• 已在此设备上安装",
	"GameList_View_ReadyToPlay_ToolTip2": "• 可以从另一台设备流式传输",
	"GameList_Entry_ReadyToPlay_ToolTip": "将从另一台设备流式传输",
	"Shelf_SectionHeader_ExpandTooltip": "展开陈列架以显示更多行",
	"Shelf_SectionHeader_ExpandTooltipFilter": "展开陈列架以显示更多行。根据您的视图筛选条件，%1$s 个项目未列出。",
	"GameList_SectionHeader_AppCountToolTip": "根据您的视图筛选条件，%1$s 个项目未列出。",
	"GameList_SectionHeader_AppCountToolTipAllHidden": "根据您的视图筛选条件，未列出任何内容。",
	"CollectionAction_ViewOnlyThis": "仅查看此收藏",
	"CollectionAction_ViewOnlyThisFavorites": "仅查看收藏夹",
	"CollectionAction_ViewOnlyThisUncategorized": "仅查看未分类",
	"CollectionAction_Collapse": "折叠",
	"CollectionAction_Expand": "展开",
	"CollectionAction_Manage": "管理",
	"CollectionAction_Edit": "编辑收藏筛选条件",
	"CollectionAction_Rename": "重命名收藏",
	"CollectionAction_Delete": "删除收藏",
	"CollectionAction_DeleteDialog": "删除收藏",
	"CollectionAction_ConfirmDelete": "您确定要永久删除收藏“%1$s”吗？",
	"CollectionAction_SaveFailed": "无法保存收藏“%1$s”",
	"CollectionAction_CannotOverwrite": "无法覆盖收藏“%1$s”。请选择新名称。",
	"CollectionAction_DeleteFailed": "无法移除收藏“%1$s”",
	"LibraryHome_FriendsActivity": "好友动态",
	"LibraryHome_RecentGames": "最近游戏",
	"LibraryHome_NewUpdates": "最近更新",
	"LibraryHome_YourCollection": "您的完整库",
	"LibraryHome_RecentFriendsActivity": "最近好友动态",
	"Library_FriendsActivity_HotRightNowHeading": "当前火爆",
	"Library_FriendsActivity_HotRightNowHover": "您的许多好友正在玩这款游戏，因此向您显示。",
	"Library_FriendsActivity_TrendingHeading": "热门",
	"Library_FriendsActivity_TrendingHover": "您的部分好友上周玩这款游戏比前一周多，因此向您显示。",
	"Library_FriendsActivity_BeingDiscussedHeading": "讨论焦点",
	"Library_FriendsActivity_BeingDiscussedHover": "您的好友一直在发布此游戏的截图或状态消息，因此向您显示。",
	"Library_FriendsActivity_RecentlyPurchasedHeading": "最近购买",
	"Library_FriendsActivity_RecentlyPurchasedHover": "您最近购买了此游戏，且您的好友正在游玩，因此向您显示。",
	"Library_FriendsActivity_UnownedHeading": "来点新鲜",
	"Library_FriendsActivity_UnownedHover": "这款游戏在您的好友中相当热门，而您尚未拥有，因此向您显示。",
	"Library_FriendsActivity_PopularHeading": "热门",
	"Library_FriendsActivity_PopularHover": "您的许多好友最近一直在玩这款游戏，因此向您显示。",
	"Library_FriendsActivity_DontForgetHeading": "切莫忘记",
	"Library_FriendsActivity_DontForgetHover": "您最近没有玩过此游戏，而您的好友正在游玩，因此向您显示。",
	"Library_FriendsActivity_NewToGroupHeading": "好友新上手",
	"Library_FriendsActivity_NewToGroupHover": "您的好友最近开始玩此游戏，因此向您显示。",
	"Library_FriendsActivity_ReturnedToGroupHeading": "重拾旧爱",
	"Library_FriendsActivity_ReturnedToGroupHover": "您的好友重新开始玩此游戏，因此向您显示。",
	"Library_FriendsActivity_UnownedBanner": "在 Steam 商店中查看",
	"Library_FriendsActivity_UnownedMenu_Store": "商店",
	"Library_FriendsActivity_UnownedMenu_Hub": "社区中心",
	"Library_FriendsActivity_UnownedMenu_Reviews": "评测",
	"Library_FriendsActivity_UnownedMenu_Discussions": "讨论区",
	"Library_Recent_NoRecentGames_GamesOwned": "您有 %1$s 款游戏",
	"Library_Recent_NoRecentGames_StoreLink": "访问 %1$s，查找要添加的游戏：",
	"Library_Recent_NoRecentGames_SteamStore": "Steam 商店",
	"Library_Recent_NoRecentGames_FreeToPlay": "免费游戏",
	"Library_Recent_NoRecentGames_GamesOnSale": "特卖中游戏",
	"Library_Recent_NoRecentGames_NewReleases": "新品",
	"Library_Recent_NoRecentGames_ActivateProduct": "激活产品",
	"Library_Recent_NoRecentGames_RedeemCode": "兑换钱包充值码",
	"Library_SortCollectionBy": "排序方式：",
	"Library_SortByFavoritesFirst": "收藏夹优先",
	"Library_SortByAlphabetical": "按字母顺序",
	"Library_SortByPctAchievementsComplete": "完成成就百分比",
	"Library_SortByLastUpdated": "最后更新",
	"Library_SortByHoursPlayed": "游戏时间",
	"Library_SortByLastPlayed": "最后运行日期",
	"Library_SortByReleaseDate": "发行日期",
	"Library_SortByAddedToLibrary": "添加至库的日期",
	"Library_SortBySizeOnDisk": "磁盘空间大小",
	"Library_SortByMetacriticScore": "Metacritic 分数",
	"Library_SortByFriendsPlaying": "好友正在玩",
	"Library_InstalledOnlyCheck": "仅限已安装",
	"GridSection_Favorites": "收藏夹",
	"GridSection_EverythingElse": "其他",
	"GridSection_Over100Hours": "超过 100 小时",
	"GridSection_Over60Hours": "超过 60 小时",
	"GridSection_Over40Hours": "超过 40 小时",
	"GridSection_Over20Hours": "超过 20 小时",
	"GridSection_Over10Hours": "超过 10 小时",
	"GridSection_Over1Hour": "超过 1 小时",
	"GridSection_LessThan1Hour": "不到 1 小时",
	"GridSection_Over90Metacritic": "90 以上",
	"GridSection_Over80Metacritic": "80 以上",
	"GridSection_Over70Metacritic": "70 以上",
	"GridSection_Over50Metacritic": "50 以上",
	"GridSection_EverythingElseMetacritic": "其他",
	"GridSection_UnknownReleaseDate": "未知",
	"GridSection_GreaterThan100GB": "大于 100 GB",
	"GridSection_GreaterThan50GB": "大于 50 GB",
	"GridSection_GreaterThan20GB": "大于 20 GB",
	"GridSection_LessThan20GB": "小于 20 GB",
	"GridSection_NoSizeOnDisk": "未占据空间",
	"GridSection_NotInstalled": "尚未安装",
	"GridSection_MoreThan10YearsAgo": "超过 10 年",
	"GridSection_Never": "从不",
	"AppDetails_SectionTitle_Stream": "开发者直播",
	"AppDetails_SectionTitle_Activity": "动态",
	"AppDetails_SectionTitle_Friends": "玩过的好友",
	"AppDetails_SectionTitle_Friends_Software": "用过的好友",
	"AppDetails_SectionTitle_Achievements": "成就",
	"AppDetails_SectionTitle_TradingCards": "集换式卡牌",
	"AppDetails_SectionTitle_Screenshots": "屏幕截图",
	"AppDetails_SectionTitle_Updates": "近期活动与更新",
	"AppDetails_SectionTitle_DLC": "DLC",
	"AppDetails_SectionTitle_LastPlayed": "最后运行日期",
	"AppDetails_SectionTitle_LastLaunched": "最后启动日期",
	"AppDetails_SectionTitle_PlayTime": "游戏时间",
	"AppDetails_SectionTitle_UsageTime": "使用时间",
	"AppDetails_SectionTitle_Workshop": "Steam 创意工坊",
	"AppDetails_SectionTitle_Community": "社区内容",
	"AppDetails_SectionTitle_Links": "链接",
	"AppDetails_SectionTitle_SignIn_Pre": "登录",
	"AppDetails_SectionTitle_SignIn": "%1$s以查看好友动态",
	"AppDetails_SectionTitle_OpenFriends": "打开好友列表",
	"AppDetails_SectionTitle_OfflineMode": "离线模式",
	"AppDetails_Broadcast_ViewOnWeb": "在网页浏览器中查看",
	"AppDetails_Community_Tooltip1": "此栏目中包含社区提交的截图、艺术作品、视频、指南，以及更多内容。",
	"AppDetails_Community_Tooltip2": "您可以点赞、分享、留言或举报此内容。",
	"AppDetails_Community_Guide": "社区指南",
	"AppDetails_Links_Store": "商店页面",
	"AppDetails_Links_Community": "社区中心",
	"Bbcode_Originally_Posted_By": "引用自",
	"AppDetails_InOfflineMode": "Steam 当前处于离线模式。Steam 库中的许多功能，例如动态和好友，在离线模式下无法使用。上线以查看此内容。",
	"AppDetails_GoOnline": "上线",
	"GameAction_Stop": "停止",
	"GameAction_Cancel": "取消",
	"GameAction_Install": "安装",
	"GameAction_Uninstall": "卸载",
	"GameAction_Play": "开始游戏",
	"GameAction_Launch": "启动",
	"GameAction_PreLoad": "预先载入",
	"GameAction_Update": "更新",
	"GameAction_Download": "下载",
	"GameAction_Resume": "继续",
	"GameAction_Pause": "暂停",
	"GameAction_BorrowApp": "借用",
	"GameAction_PurchaseApp": "购买",
	"GameAction_GameProperties": "属性…",
	"GameAction_AddToFavorites": "添加至收藏夹",
	"GameAction_RemoveFromFavorites": "从收藏夹中移除",
	"GameAction_AddToHidden": "隐藏此游戏",
	"GameAction_RemoveFromHidden": "从隐藏中删除",
	"GameAction_AddToFamilyGames": "添加到家庭游戏",
	"GameAction_RemoveFromFamilyGames": "从家庭游戏中移除",
	"GameAction_RemoveShortcut": "从您的库中删除非 Steam 游戏",
	"GameAction_AddToCollection": "添加至",
	"GameAction_RemoveFromCollection": "移除出",
	"GameAction_CreateDesktopShortcut": "添加桌面快捷方式",
	"GameAction_BackUpFiles": "备份游戏文件…",
	"GameAction_Stream": "流式传输",
	"GameAction_Connect": "连接",
	"GameAction_SetCustomArtwork": "设置自定义艺术作品",
	"GameAction_ClearCustomArtwork": "清除自定义艺术作品",
	"GameAction_ViewCDKeys": "序列号",
	"GameAction_ControllerConfiguration": "控制器配置",
	"GameAction_RemoveAppFromCollection": "拖放至此处，从 %2$s 收藏中移除 %1$s",
	"GameAction_RemoveAppFromMultipleCollections": "拖放至此处，从这些收藏中移除 %1$s",
	"GameAction_RemoveMultipleAppsFromCollection": "拖放至此处，从 %1$s 中移除这些应用程序",
	"GameAction_RemoveMultipleAppsFromMultipleCollections": "拖放至此处，从这些收藏中移除这些应用程序",
	"GameAction_NavigateToAllCollectionsWithDrag": "拖放至此处并长按，查看所有收藏",
	"GameAction_AddToCollectionOption_NewCollection": "新收藏…",
	"GameAction_NewCollectionDialogTitle": "新收藏",
	"GameAction_Manage": "管理",
	"GameAction_Favorite": "添加至收藏夹",
	"GameAction_UnFavorite": "在收藏夹中",
	"GameAction_ViewDetails": "显示更多详情",
	"GameAction_ViewDetails_Collapse": "显示更少详情",
	"GameAction_ViewDetails_ScrollUp": "滚动到顶部",
	"GameActionPlural_Install": "安装已选游戏",
	"GameActionPlural_Uninstall": "卸载已选游戏",
	"GameActionPlural_PreLoad": "预载已选游戏",
	"GameActionPlural_Update": "更新已选游戏",
	"GameActionPlural_Download": "下载已选游戏",
	"GameActionPlural_Resume": "继续已选游戏",
	"GameActionPlural_AddToFavorites": "添加已选游戏至收藏夹",
	"GameActionPlural_RemoveFromFavorites": "从收藏夹中移除已选游戏",
	"GameActionPlural_AddToHidden": "隐藏已选游戏",
	"GameActionPlural_RemoveFromHidden": "从隐藏中删除已选游戏",
	"GameActionPlural_AddToFamilyGames": "将已选游戏添加至家庭游戏",
	"GameActionPlural_RemoveFromFamilyGames": "将已选游戏从家庭游戏中删除",
	"GameActionPlural_RemoveShortcut": "从您的库中删除已选非 Steam 游戏",
	"GameActionPlural_AddToCollection": "将已选游戏添加至",
	"GameActionPlural_RemoveFromCollection": "将已选游戏移除出",
	"GameActionPlural_CreateDesktopShortcut": "添加桌面快捷方式",
	"GameActionPlural_BackUpFiles": "备份游戏文件…",
	"DisplayStatus_Launching": "正在启动",
	"DisplayStatus_Uninstalling": "正在卸载",
	"DisplayStatus_Installing": "正在安装",
	"DisplayStatus_Running": "正在运行",
	"DisplayStatus_Validating": "正在验证",
	"DisplayStatus_Updating": "正在更新",
	"DisplayStatus_Downloading": "正在下载",
	"DisplayStatus_Synchronizing": "正在与 Steam 云同步",
	"DisplayStatus_ReadyToInstall": "安装准备就绪",
	"DisplayStatus_ReadyToPreload": "预载准备就绪",
	"DisplayStatus_ReadyToLaunch": "启动准备就绪",
	"DisplayStatus_RegionRestricted": "当前地区不可用",
	"DisplayStatus_PresaleOnly": "此项尚未推出",
	"DisplayStatus_InvalidPlatform": "适用于",
	"DisplayStatus_PreloadComplete": "预载完成",
	"DisplayStatus_BorrowerLocked": "此库当前不能进行家庭共享",
	"DisplayStatus_UpdatePaused": "更新已暂停",
	"DisplayStatus_UpdateQueued": "位于更新队列中",
	"DisplayStatus_UpdateRequired": "需要更新",
	"DisplayStatus_UpdateDisabled": "Steam 处于离线模式，因此无法进行更新。上线以完成此游戏更新。",
	"DisplayStatus_DownloadPaused": "下载已暂停",
	"DisplayStatus_DownloadQueued": "位于下载队列中",
	"DisplayStatus_DownloadRequired": "需要下载",
	"DisplayStatus_DownloadDisabled": "Steam 处于离线模式，因此无法进行下载。上线以完成此游戏下载。",
	"DisplayStatus_LicensePending": "您的购买尚未完成。",
	"DisplayStatus_LicenseExpired": "许可已过期",
	"DisplayStatus_AvailForFree": "免费可用",
	"DisplayStatus_AvailToBorrow": "可供借用",
	"DisplayStatus_AvailGuestPass": "玩家通行证可用",
	"DisplayStatus_Purchase": "可供购买",
	"DisplayStatus_Compact_Launching": "正在启动",
	"DisplayStatus_Compact_Uninstalling": "正在卸载",
	"DisplayStatus_Compact_Installing": "正在安装",
	"DisplayStatus_Compact_Running": "正在运行",
	"DisplayStatus_Compact_Validating": "正在验证",
	"DisplayStatus_Compact_Updating": "正在更新",
	"DisplayStatus_Compact_Downloading": "正在下载",
	"DisplayStatus_Compact_Synchronizing": "正在与 Steam 云同步",
	"DisplayStatus_Compact_ReadyToInstall": "安装准备就绪",
	"DisplayStatus_Compact_ReadyToPreload": "预载准备就绪",
	"DisplayStatus_Compact_ReadyToLaunch": "启动准备就绪",
	"DisplayStatus_Compact_RegionRestricted": "此地区不可用",
	"DisplayStatus_Compact_PresaleOnly": "游戏尚未发行",
	"DisplayStatus_Compact_InvalidPlatform": "适用于",
	"DisplayStatus_Compact_ParentalBlocked": "受 Steam 家庭监护屏蔽",
	"DisplayStatus_Compact_PreloadComplete": "预载完成",
	"DisplayStatus_Compact_BorrowerLocked": "家庭共享不可用",
	"DisplayStatus_Compact_UpdatePaused": "更新已暂停",
	"DisplayStatus_Compact_UpdateQueued": "位于更新队列中",
	"DisplayStatus_Compact_UpdateRequired": "需要更新",
	"DisplayStatus_Compact_UpdateDisabled": "离线模式下无法更新",
	"DisplayStatus_Compact_DownloadPaused": "下载已暂停",
	"DisplayStatus_Compact_DownloadQueued": "位于下载队列中",
	"DisplayStatus_Compact_DownloadRequired": "需要下载",
	"DisplayStatus_Compact_DownloadDisabled": "离线模式下无法下载",
	"DisplayStatus_Compact_LicensePending": "正在完成购买",
	"DisplayStatus_Compact_LicenseExpired": "许可已过期",
	"DisplayStatus_Compact_AvailForFree": "免费可用",
	"DisplayStatus_Compact_AvailToBorrow": "可供借用",
	"DisplayStatus_Compact_AvailGuestPass": "玩家通行证可用",
	"DisplayStatus_Compact_Purchase": "可供购买",
	"DisplayStatus_ReleaseDate": "发行日期：%1$s",
	"DisplayStatus_CustomReleaseDate": "计划发行日期：%1$s",
	"Downloads_State_Bytes_Of_Bytes": "%1$s / %2$s",
	"Downloads_State_None": "",
	"Downloads_State_Reconfiguring": "正在开始下载",
	"Downloads_State_Validating": "正在验证文件",
	"Downloads_State_AddingFiles": "正在复制文件",
	"Downloads_State_Preallocating": "正在预留空间",
	"Downloads_State_Downloading": "",
	"Downloads_State_Staging": "",
	"Downloads_State_Committing": "正在完成",
	"Downloads_State_Verifying": "正在验证下载",
	"Downloads_State_Stopping": "正在停止下载",
	"Downloads_State_Running": "",
	"Downloads_State_SecondsRemaining": "剩余 %1$s 秒",
	"Downloads_State_MinutesRemaining": "剩余 %1$s 分钟",
	"Downloads_State_Calculating": "正在计算…",
	"LaunchApp_Action_UpdatingAppInfo": "正在检查配置",
	"LaunchApp_Action_ShowEula": "正在显示最终用户许可协议",
	"LaunchApp_Action_DownloadingDepots": "正在下载内容（%1$s%）",
	"LaunchApp_Action_DownloadingWorkshop": "正在下载创意工坊（%1$s%）",
	"LaunchApp_Action_UpdatingDRM": "正在更新可执行文件",
	"LaunchApp_Action_GettingLegacyKey": "正在更新产品序列号",
	"LaunchApp_Action_RunningInstallScript": "正在运行安装脚本（%1$s）",
	"LaunchApp_Action_SynchronizingCloud": "正在同步云",
	"LaunchApp_Action_VerifyingFiles": "正在验证可执行文件",
	"LaunchApp_Action_CreatingProcess": "正在启动可执行文件",
	"LaunchApp_Action_WaitingGameWindow": "正在启动可执行文件",
	"LaunchApp_Action_DelayLaunch": "正在延迟启动（%1$s%）",
	"AppDetails_TitleUpdatedSincePlayed": "此游戏自您上次游玩之后已更新",
	"AppDetails_TitleUpdatedSincePlayedLink": "了解这些更新",
	"AppDetails_BadgeLevel": "等级 %1$s，经验值：%2$s",
	"AppDetails_UnearnedBadgeXP": "%1$s 经验值",
	"AppDetails_BadgeLevelNoXP": "等级 %1$s",
	"AppDetails_Review_ViewOrEdit": "编辑我的评测",
	"AppDetails_Review_YourReview": "我的评测",
	"AppDetails_Review_Ignore_Stale_Reviews": "不要提醒我更新此评测",
	"AppDetails_Review_Unignore_Stale_Reviews": "允许突出显示此游戏的旧评测",
	"AppDetails_Review_RecommendGame": "您会推荐这款游戏吗？",
	"AppDetails_Review_RecommendSoftware": "您会推荐这款软件吗？",
	"AppDetails_Review_WriteReview": "为 %1$s 撰写评测",
	"AppDetails_Review_PlayedForTime": "您已经玩了 %1$s",
	"AppDetails_Review_PlayedForTime_Software": "您已经使用此产品 %1$s",
	"AppDetails_Review_RecommendGameButton_Yes": "是",
	"AppDetails_Review_RecommendGameButton_No": "否",
	"AppDetails_Review_PlaytimeAtReview": "评论时已玩了 %1$s",
	"AppDetails_Review_PlaytimeAtReview_Software": "评论时已使用了 %1$s",
	"AppDetails_Review_NotRecommended": "不推荐",
	"AppDetails_Review_Recommended": "推荐",
	"AppDetails_Review_AdditionalPlaytime": "自您撰写此评测后已玩了 %1$s。",
	"AppDetails_Review_AdditionalPlaytime_Software": "自您撰写此评测后已使用了 %1$s。",
	"AppDetails_Review_ChangedYourMind": "您改变想法了吗？",
	"AppDetails_Review_IHaveNotChangedMyMind": "不，还没有。",
	"AppDetails_Review_UpVotes": "点赞：",
	"AppDetails_Review_Comments": "留言：",
	"AppDetails_Review_ViewAll": "查看我的所有评测",
	"AppDetails_Review_ViewAllByFriend": "查看 %1$s 的所有评测",
	"OverflowBox_Action_Collapse": "收起",
	"OverflowBox_Action_Expand": "展开阅读",
	"OverflowBox_More": "（还有 %1$s 个）",
	"AppDetails_FriendsInGameNow": "%1$s 位好友正在游玩",
	"AppDetails_FriendsInGameNow_Plural": "%1$s 位好友正在游玩",
	"AppDetails_FriendsPlayedRecently": "%1$s 位好友最近玩过",
	"AppDetails_FriendsPlayedRecently_Plural": "%1$s 位好友最近玩过",
	"AppDetails_FriendsPlayedRecentlyExpand": "显示所有最近玩过的好友",
	"AppDetails_FriendsPlayed": "%1$s 位好友之前玩过",
	"AppDetails_FriendsPlayed_Plural": "%1$s 位好友之前玩过",
	"AppDetails_FriendsPlayedExpand": "显示所有之前玩过的好友",
	"AppDetails_FriendsMore": "（还有 %1$s 位）",
	"AppDetails_FriendsLess": "收起",
	"AppDetails_FriendsWishlisted": "%1$s 位好友愿望单中有 %2$s",
	"AppDetails_FriendsWishlisted_Plural": "%1$s 位好友愿望单中有 %2$s",
	"AppDetails_FriendsWishlistExpand": "显示所有愿望单项目",
	"AppDetails_Friends_ViewAll": "查看玩此游戏的所有好友",
	"AppDetails_GameInfo": "游戏信息",
	"AppDetails_Publisher": "发行商：",
	"AppDetails_Developer": "开发商：",
	"AppDetails_Franchise": "系列：",
	"AppDetails_ReleaseDate": "发行日期：",
	"AppDetails_OriginalReleaseDate": "原定发行日期：",
	"AppDetails_Feature_SinglePlayer": "单人游戏",
	"AppDetails_Feature_MultiPlayer": "多人游戏",
	"AppDetails_Feature_CoOp": "合作游戏",
	"AppDetails_Feature_SteamAchievements": "成就",
	"AppDetails_Feature_SteamCloud": "云存档",
	"AppDetails_Feature_FullController": "完全支持控制器",
	"AppDetails_Feature_PartialController": "部分支持控制器",
	"AppDetails_Feature_SteamWorkshop": "Steam 创意工坊",
	"AppDetails_Feature_VRSupport": "支持 VR",
	"AppDetails_ViewAllUpdates": "查看所有更新",
	"AppDetails_ViewAllAchievements": "查看我的成就",
	"AppDetails_ViewGlobalAchievements": "查看全球成就统计",
	"AppDetails_PlayerUnlockedPercent": "您已解锁 %1$s/%2$s",
	"AppDetails_PlayerUnlockedPercentAll": "您已解锁所有成就！%1$s/%2$s",
	"AppDetails_Achievements_Unlocked": "解锁时间：%1$s",
	"AppDetails_PctUnlocked": "%1$s% 的玩家拥有此成就",
	"AppDetails_GlobalCompare": "相当于超过 %1$s% 的玩家",
	"AppDetails_ViewTradingCards": "查看我的集换式卡牌",
	"AppDetails_Achievements_Locked": "锁定的成就",
	"AppDetails_TradingCardsLeft": "剩余 1 张待收集的卡牌",
	"AppDetails_TradingCardsLeft_Plural": "剩余 %1$s 张待收集的卡牌",
	"AppDetails_TradingCardsLevelUp": "您已有足够的集换式卡牌可以升级！",
	"AppDetails_TradingCardsMaxed": "恭喜！徽章已达最高等级！",
	"AppDetails_TradingCards_Tooltip1": "集换式卡牌会在您游玩过程中掉落。您可以与好友（或在 Steam 社区市场中）交易未掉落的卡牌。",
	"AppDetails_TradingCards_Tooltip2": "集齐一套集换式卡牌并将其合成为游戏徽章。徽章可以提高您的 Steam 等级，并将效果解锁至您的个人资料和帐户。",
	"AppDetails_BrowseWorkshop": "浏览创意工坊",
	"AppDetails_ViewSubscribedItems": "查看我的订阅",
	"AppDetails_ViewItemInWorkshop": "在创意工坊中查看",
	"AppDetails_MoreItemsFrom": "查看此创建者的物品",
	"AppDetails_SubscribeToItem": "订阅",
	"AppDetails_UnsubscribeFromItem": "取消订阅",
	"AppDetails_Subscribed": "已订阅",
	"AppDetails_ViewMoreInWorkshop": "在创意工坊中查看更多",
	"AppDetails_WorkshopSubCount": "您订阅了 %1$s 个创意工坊",
	"AppDetails_WorkshopVisit": "访问此创意工坊",
	"AppDetails_WorkshopLearnMore": "了解更多",
	"AppDetails_WorkshopFeaturedHeader": "热门物品",
	"AppDetails_WorkshopFeaturedItem": "热门物品",
	"AppDetails_WorkshopFeaturedMoreInfo": "了解更多",
	"AppDetails_WorkshopFeaturedHideItem": "隐藏此物品",
	"AppDetails_WorkshopFileSize": "文件大小：%1$s",
	"AppDetails_WorkshopFileSizeBytes": "%1$s 字节",
	"AppDetails_WorkshopFileSizeKb": "%1$s KB",
	"AppDetails_WorkshopFileSizeMb": "%1$s MB",
	"AppDetails_WorkshopFileSizeGb": "%1$s GB",
	"AppDetails_WorkshopLastUpdated": "最后更新于：%1$s",
	"DLCStatus_installed": "已安装",
	"DLCStatus_notinstalled": "尚未安装",
	"DLCStatus_downloading": "正在下载",
	"DLC_DateAdded": "添加于：%1$s",
	"AppDetails_ManageDLC": "管理我的 %1$s 个 DLC",
	"AppDetails_ManageMyDLC": "管理我的 DLC",
	"AppDetails_ViewStoreDLC": "在商店中查看 DLC",
	"AppDetails_DLCSpotlight": "新获得的 DLC 已添加，并将与游戏一起安装。请在%1$s管理您的 DLC。",
	"AppDetails_DLCSpotlight_Installed": "新获得的 DLC 已自动安装。请在%1$s管理您的 DLC。",
	"AppDetails_DLCSpotlight_here": "此处",
	"ManageDLC_Title": "管理 DLC",
	"ManageDLC_Column_Name": "名称",
	"ManageDLC_Column_DateAdded": "添加日期",
	"ManageDLC_Column_Enabled": "已启用",
	"ManageDLC_Column_Installed": "已安装",
	"ManageDLC_Search": "搜索…",
	"ManageDLC_Installed": "%1$s/%2$s 已安装",
	"ManageDLC_ViewMore": "在商店中查看更多",
	"ManageDLC_NoResults": "没有匹配“%1$s”的结果",
	"AppDetails_ViewBadgePage": "查看徽章页面",
	"AppDetails_VisitTradeForum": "查看交易论坛",
	"AppDetails_BuyCards": "在社区市场上购买剩余卡牌",
	"AppDetails_SellCards": "在市场上出售这些卡牌",
	"AppDetails_SearchCard": "在市场上显示此卡牌",
	"AppDetails_ShowFriendsList": "显示好友列表",
	"AppDetails_ViewFriendsWhoPlay": "查看玩此游戏的好友",
	"AppDetails_Link_Discussions": "讨论区",
	"AppDetails_Link_FindGroups": "查找组",
	"AppDetails_Link_GameHub": "社区中心",
	"AppDetails_Link_Guides": "指南",
	"AppDetails_Link_Store": "商店页面",
	"AppDetails_Link_Support": "客服",
	"AppDetails_Link_Workshop": "创意工坊",
	"AppDetails_Link_Controller": "控制器配置",
	"AppDetails_SocialMediaLink": "%1$s 的 %2$s 帐号",
	"AppDetails_SocialMediaType_4": "Twitter",
	"AppDetails_SocialMediaType_5": "Twitch",
	"AppDetails_SocialMediaType_6": "YouTube",
	"AppDetails_SocialMediaType_7": "Facebook",
	"AppDetails_Screenshot": "截图",
	"AppDetails_Screenshot_Caption": "说明文字：%1$s",
	"AppDetails_Screenshot_Date": "日期：%1$s",
	"AppDetails_Screenshot_Dimensions": "尺寸：%1$s x %2$s 像素",
	"AppDetails_Screenshot_Uploaded": "上传于：%2$s %1$s",
	"AppDetails_OpenScreenshotUploader": "打开截图上传工具",
	"AppDetails_ViewUploadedScreenshots": "查看已上传的截图",
	"AppDetails_ManageMyScreenshot": "管理我的截图",
	"AppDetails_ManageMyScreenshot_Plural": "管理我的 %1$s 张截图",
	"AppDetails_HowToScreenshot": "在游戏中按下 %1$s 可进行截图。",
	"AppDetails_ChangeMyScreenshotKey": "更改我的截图键",
	"AppDetails_NoScreenshots": "您还没有进行任何截图",
	"AppDetails_Artwork": "艺术作品",
	"AppDetails_Video": "视频",
	"AppDetails_CommunityItem": "社区内容",
	"AppDetails_CommunityFeed_OutOfContent": "无额外内容",
	"AppDetails_CommunityFeed_Inappropriate": "内容也许不适合所有受众",
	"AppDetails_CommunityFeed_ViewContent": "查看内容",
	"AppDetails_CommunityFeed_EditPreferences": "编辑偏好设置",
	"AppDetails_CommunityFeed_LoadCommunity": "载入更多社区内容",
	"AppBox_NewToLibrary": "库新品",
	"AppBox_ComingSoon": "即将推出",
	"AppBox_NewToLibrary_Short": "新品",
	"AppBox_ComingSoon_Short": "将推出",
	"AppBox_PlayTimeHeader": "游戏时间",
	"AppBox_RecentPlayTime_Hours": "过去两周：%1$s 小时",
	"AppBox_RecentPlayTime_Minutes": "过去两周：%1$s 分钟",
	"AppBox_TotalPlayTime_Hours": "总数：%1$s 小时",
	"AppBox_TotalPlayTime_Minutes": "总数：%1$s 分钟",
	"AppActivity_Achieved": " 已达成",
	"AppActivity_PostedScreenshot": "分享了一张截图",
	"AppActivity_PostedScreenshot_Plural": "分享了 %1$s 张截图",
	"AppActivity_PostedVideo": " 分享了一个视频",
	"AppActivity_PostedVideo_Plural": " 分享了 %1$s 个视频",
	"AppActivity_ReceivedNewGame": "现在拥有 %1$s",
	"AppActivity_PlayedGameFirstTime": "首次游玩 %1$s",
	"AppActivity_LaunchedSoftwareFirstTime": "首次启动 %1$s",
	"AppActivity_AddedGameToWishlist": "将 %1$s 添加至%2$s",
	"AppActivity_Wishlist": "愿望单",
	"AppActivity_Achieved_PlusMore": "…还有 %1$s 个成就",
	"AppActivity_Achieved_PlusMore_Label": "查看 %1$s 的所有成就",
	"AppActivity_NoActivity": "此游戏的开发者或您的好友最近没有动态。",
	"AppActivity_UserStatus_Time": "于 %1$s 发布了状态更新",
	"AppActivity_UserStatus": "发布了状态更新",
	"AppActivity_StatusUpdate": "向您的好友发布状态",
	"AppActivity_StatusUpdate_Post": "将此游戏介绍给您的好友…",
	"AppActivity_StatusUpdate_Software_Post": "将此软件介绍给您的好友…",
	"AppActivity_Comment_Reply": "添加回复...",
	"AppActivity_PostStatusUpdate": "发布",
	"AppActivity_FetchMore": "载入更多动态",
	"AppActivity_EndofFeed": "动态结束",
	"AppActivity_DeleteUserNews": "点击以删除此发布",
	"AppActivity_ConfirmDeleteTitle": "删除状态发布",
	"AppActivity_ConfirmDeleteTitle_Desc": "您确定要删除此发布吗？此操作无法撤销。",
	"AppActivity_RecommendedGame": "已评测此游戏",
	"AppActivity_RecommendedGame_ReadMore": "了解更多",
	"AppActivity_RatingDetails": "共有 %1$s 人点赞",
	"AppActivity_RatingDetails_1Other": "1 人点赞，%1$s",
	"AppActivity_RatingDetails_2Others": "共有 %1$s 人点赞，其中包括 %2$s 和 %3$s",
	"AppActivity_RatingDetails_User": "您已点赞",
	"AppActivity_RatingDetails_User_1Other": "共有 %1$s 人点赞，其中包括您和 %2$s",
	"AppActivity_RatingDetails_User_2Others": "共有 %1$s 人点赞，其中包括您、%2$s 和 %3$s",
	"AppActivity_RatingDetails_PublishedFile": "%1$s 个赞",
	"AppActivity_RateUp": "点赞",
	"AppActivity_ConfirmDeleteCommentTitle": "删除留言",
	"AppActivity_ConfirmDeleteCommentTitle_Desc": "您确定要删除此留言吗？此操作无法撤销。",
	"AppActivity_MakeCommentsVisible": "查看之前的留言（%1$s）",
	"AppActivity_Settings": "设置",
	"AppActivity_ViewComments": "查看留言",
	"AppActivity_AddComments": "添加留言",
	"AppActivity_ContributeComments": "对此留言",
	"AppActivity_SteamTradingCards_EarnedTradingCards": "获得集换式卡牌",
	"AppActivity_SteamTradingCards_EarnedTradingCard": "获得一张集换式卡牌",
	"AppActivity_SteamTradingCards_EarnedBoosterPack": "获得一个补充包",
	"AppActivity_SteamTradingCards_BadgeCrafted": "合成了一枚徽章",
	"AppActivity_ViewLatestNews": "查看最新新闻",
	"AppActivity_EventType_GameUpdate": "游戏更新",
	"AppSpotlight_PostGameSummary": "赛后总结",
	"AppDetails_Shortcut_Explanation": "%1$s 的部分详细信息无法提供，因为这不是 Steam 游戏或模组。Steam 仍会设法为您启动该游戏，大部分情况下也可提供游戏内界面。",
	"AppDetails_Takeover_Update_Header": "如果您错过了",
	"AppDetails_Takeover_Update_ViewAll": "查看 %1$s 的所有游戏更新",
	"AppDetails_Takeover_Update_ReadMore": "了解更多",
	"AppDetails_Takeover_DLC_Header": "已添加的新物品",
	"AppDetails_Takeover_DLC_ViewInStore": "在商店中查看 %1$s",
	"AppDetails_Takeover_Achievements_Header": "已游玩 %2$s，您有一个新成就…",
	"AppDetails_Takeover_Achievements_Header_Plural": "已游玩 %2$s，您有新成就…",
	"AppDetails_Takeover_TradingCards_Header": "已游玩 %2$s，您有一个新物品…",
	"AppDetails_Takeover_TradingCards_Header_Plural": "已游玩 %2$s，您有新物品…",
	"AppDetails_ViewMyInventory": "查看我的库存",
	"AppDetails_ViewInMyInventory": "在我的库存中查看",
	"AppPortraitHover_DownloadStatusTitle": "正在下载",
	"AppPortraitHover_DownloadStatusTitle_Update": "正在下载更新",
	"AppPortraitHover_DaysSinceLastUpdate": "更新于：%1$s",
	"AppPortraitHover_FriendsPlaying": "%1$s 名好友正在玩",
	"MajorUpdate_ViewDetails": "查看详情",
	"MajorUpdate_NextUpdate": "下次更新",
	"MajorUpdate_PostTime": "发布于：%1$s 天前，%2$s:%3$s",
	"MajorUpdate_PostTimeToday": "发布于：今天，%1$s:%2$s",
	"MajorUpdate_WatchNow": "在 SteamTV 上观看",
	"MajorUpdate_Type0": "重大更新",
	"MajorUpdate_Type1": "现场直播",
	"MajorUpdate_Type14": "重大更新",
	"MajorUpdate_Context_RemoveThisUpdate": "移除此更新",
	"MajorUpdate_Context_ResetHiddenUpdates": "再次显示所有更新",
	"MajorUpdate_Context_WhyAmISeeingThis": "我为什么看到此内容？",
	"MajorUpdate_Context_WhyAmISeeingThis_Text": "这是您的库中超过 20 小时游戏时间的产品的重大更新（placeholder）。",
	"MajorUpdate_Context_WhyAmISeeingThis_Close": "关闭",
	"CustomArt_ErrorTitle": "错误",
	"CustomArt_BadFileType": "您的文件必须是 JPG 或 PNG 格式。",
	"CustomArt_UnknownError": "设置您的艺术作品时出错。",
	"AppDetails_LibraryInUse": "正在使用库的用户",
	"AppDetails_InSharedLibrary": "库来源：",
	"FriendContextMenu_OpenFriends": "打开好友和聊天",
	"FriendContextMenu_ViewProfile": "查看个人资料",
	"Generic_ScrollToTop": "滚动到顶部",
	"Generic_ViewGameDetails": "在库中查看游戏",
	"GameDetails_CollectionContext_GoTo": "前往收藏",
	"GameDetails_CollectionContext_Remove": "从收藏中移除",
	"ArtworkModal_ViewAll": "查看所有截图",
	"ArtworkModal_FileSize": "文件大小",
	"ArtworkModal_Posted": "已发布",
	"ArtworkModal_Size": "大小",
	"ArtworkModal_CreatedBy": "创建者：",
	"ArtworkModal_ScrollForMore": "向下滚动，查看留言",
	"CommunityItem_Menu_Report": "举报",
	"ReportItem_Title": "举报此物品",
	"ReportItem_Description": "请描述此物品违反《Steam 服务条款》的形式。请包含所有相关的信息和链接。此举报提交后无法撤销。",
	"ReportItem_Description_Line2": "受到举报的物品将不会再在您的库页面显示。",
	"ReportItem_DMCA": "如果您想举报版权侵权问题，并且是版权所有者，请在%1$s转到我们的 DMCA 版权侵犯通知表格。",
	"ReportItem_DMCA_LinkText": "此处",
	"ReportItem_Error": "将您的请求提交至我们的服务器时出现问题。请稍后重试。",
	"ReportItem_SubmitReport": "提交举报",
	"Showcase_AddNewShowcase": "添加新陈列架",
	"Showcase_DeleteShowcase": "删除此陈列架",
	"Showcase_SelectCategory": "选择一个陈列架",
	"Showcase_EmptyShowcaseHint": "选择在此陈列架展示的内容。您也可以在此处修改或删除陈列架！",
	"Showcase_GoToCollection": "前往收藏",
	"Showcase_GoToAllCollections": "前往所有收藏",
	"Showcase_AllYourGames": "所有游戏",
	"Showcase_AllCollections": "收藏视图",
	"Showcase_RecentGames": "最近游戏",
	"Playtime_TwoWeeks_Minutes": "最近游戏时间：%1$s 分钟",
	"Playtime_TwoWeeks_Hours": "最近游戏时间：%1$s 小时",
	"Playtime_Total_Minutes": "总游戏时间：%1$s 分钟",
	"Playtime_Total_Hours": "总游戏时间：%1$s 小时",
	"Playtime_Minutes": "%1$s 分钟",
	"Playtime_Hours": "%1$s 小时",
	"Playtime_Recently": "最近游戏时间：%1$s",
	"Playtime_Total": "总游戏时间：%1$s",
	"GameList_Search_NoResults_Title": "找不到您要找的游戏吗？",
	"GameList_Search_NoResults_Link": "搜索 Steam 商店",
	"StreamingClient_Select_ThisMachine": "此设备",
	"Beta_BetaTag": "测试版",
	"Beta_Changelist": "改动列表",
	"Beta_GiveFeedback": "提供反馈",
	"ContextMenu_SaveScreenshot": "Save screenshot as..."
}
