{
	"Generic_Okay": "OK",
	"Generic_Close": "Închide",
	"Generic_Open": "Deschide",
	"Generic_GotIt": "Înțeles!",
	"Generic_Share": "Împărtășește",
	"Generic_Upload": "Încarcă",
	"Generic_Delete": "Șterge",
	"Privacy_Public": "Publică",
	"Privacy_FriendsOnly": "Numai prieteni",
	"Privacy_Private": "Privat",
	"AppType_0": "Nevalid",
	"AppType_1": "Jocuri",
	"AppType_2": "Software",
	"AppType_4": "Instrumente",
	"AppType_20": "DLC",
	"AppType_800": "Videoclipuri",
	"AppType_2000": "Coloane sonore",
	"AppType_Singular_0": "Nevalid",
	"AppType_Singular_1": "joc",
	"AppType_Singular_2": "aplicație",
	"AppType_Singular_4": "instrument",
	"AppType_Singular_20": "DLC",
	"AppType_Singular_800": "videoclip",
	"AppType_Singular_2000": "muzică",
	"AppType_Singular_8000": "bandă desenată",
	"AppType_Singular_40000000": "scurtătură",
	"FilterEdit_SavedFilters": "Filtre salvate",
	"FilterEdit_FirstColumnHeader": "Tipul filtrului",
	"FilterEdit_Customize": "Personalizează",
	"FilterEdit_SearchModeHeader": "Filtre avansate",
	"FilterEdit_CollectionModeHeader": "Editează filtrele de colecție",
	"CollectionEdit_CollectionNameField": "Numele colecției:",
	"CollectionEdit_RenameButton": "Redenumește colecția",
	"Collection_DynamicCollection": "Colecție dinamică",
	"FilterEdit_AdvancedTooltip": "Opțiuni avansate de filtrare care te ajută să-ți ordonezi lista de jocuri în funcție de gen, caracteristici ale acestora, etc.",
	"Collection_FreezeDynamicCollection_Button": "Instantaneu",
	"Collection_FreezeDynamicCollection_ToolTip": "Convertește colecția aceasta dinamică într-una simplă, păstrând lista de jocuri actuală.",
	"Collection_FreezeDynamicCollection_DialogTitle": "Colecție de instantanee",
	"Collection_FreezeDynamicCollection_Confirmation": "Sigur dorești să convertești colecția aceasta? Aceasta nu va mai fi actualizată în mod dinamic atunci când adaugi jocuri în biblioteca ta care să corespundă filtrelor acestei colecții.",
	"Collection_ResetDialogTitle": "Resetează colecțiile",
	"Collection_ResetConfirmation": "Sigur dorești să-ți resetezi lista de colecții și să-ți reimportezi categoriile vechi?",
	"Collection_AfterResetSummary_NoCollections": "Nu vei mai avea nicio colecție după resetare.",
	"Collection_AfterResetSummary_CountAndNames": "Vei avea următoarele %1$s colecții după resetare: %2$s",
	"Collection_ResetFailed": "Colecțiile nu au putut fi resetate",
	"FilterEdit_SelectedFilters": "Filtre selectate",
	"FilterEdit_SaveCollectionNameInputPrompt": "Introdu un nume pentru colecție",
	"FilterEdit_SaveOverwrite": "Colecția „%1$s” există deja. O suprascrii?",
	"FilterEdit_SaveCollection": "Salvează ca o colecție",
	"FilterEdit_SaveDynamicCollectionWithIcon": "Salvează ca o %1$scolecție dinamică",
	"FilterEdit_SaveDynamicCollectionNoIcon": "Salvează ca o colecție dinamică",
	"FilterEdit_SaveCollectionVerbose": "Salvează căutarea aceasta drept o colecție, astfel încât s-o poți folosi din nou în viitor. Poți întotdeauna să editezi, să redenumești sau să ștergi o colecție în viitor, cât și să introduci sau să elimini articole din aceasta.",
	"FilterEdit_SaveStandardCollectionButtonDesc": "O colecție este o metodă simplă de a-ți organiza biblioteca. Trage titlurile în colecție sau apasă clic dreapta pe un titlu pentru a-l adăuga într-o colecție existentă.",
	"FilterEdit_SaveDynamicCollectionButtonDesc": "Colecțiile dinamice folosesc filtre pentru a crea colecții care se actualizează în timp ce biblioteca ta se mărește.",
	"FilterEdit_SelectCollectionType": "Selectează un tip de colecție",
	"FilterEdit_SelectCollectionTypeButtonCreate": "Creează o colecție",
	"FilterEdit_SelectCollectionTypeButtonCreateDynamic": "Creează o colecție dinamică",
	"FilterEdit_RequiredField": "( NECESAR )",
	"FilterEdit_SearchPrompt": "Caută după nume",
	"FilterEdit_ClearSearch": "Părăsește căutarea",
	"FilterEdit_SearchResults": "Rezultatele căutării",
	"FilterEdit_CollectionsHiddenPromptTitle": "Colecțiile sunt ascunse",
	"FilterEdit_CollectionsHiddenPrompt": "Ai dori să modifici modul de vizualizare al listei de jocuri astfel încât noua colecție să fie vizibilă?",
	"FilterEdit_AcceptGameListViewChange": "Da, arată colecțiile",
	"FilterEdit_RejectGameListViewChange": "Nu, nu schimba nimic",
	"AdvancedSearch_PaneTitle": "Caută în funcție de tip",
	"AdvancedSearch_PlayerSection": "Jucători",
	"AdvancedSearch_HardwareSection": "Compatibilitate hardware",
	"AdvancedSearch_FeatureSection": "Caracteristici",
	"AdvancedSearch_StateSection": "Starea jocului",
	"AdvancedSearch_GenreSection": "Gen",
	"AdvancedSearch_StoreTagSection": "Etichete din magazin",
	"AdvancedSearch_StoreTagPrompt": "introdu o etichetă",
	"FilterCategory_1": "Stare",
	"FilterCategory_Features": "CARACTERISTICĂ",
	"FilterCategory_3": "Categorie",
	"FilterCategory_4": "Etichetă din magazin",
	"FilterCategory_Type": "TIP",
	"FilterCategory_Genre": "GEN",
	"FilterCategory_PlayState": "STARE",
	"FilterElement_VR": "RV",
	"FilterElement_Tooltip_VR": "Include jocurile care suportă hardware-ul pentru realitate virtuală.",
	"FilterElement_Installed": "Instalate local",
	"FilterElement_Tooltip_Installed": "Include jocurile care sunt instalate pe calculatorul acesta.",
	"FilterElement_ReadyToPlay": "Gata de joacă",
	"FilterElement_Tooltip_ReadyToPlay": "Include jocurile pe care le poți juca local sau pe care le poți transmite de pe un alt calculator.",
	"FilterElement_PlayedPreviously": "Jucate",
	"FilterElement_Tooltip_PlayedPreviously": "Include jocurile pe care le-ai jucat deja.",
	"FilterElement_Unplayed": "Nejucate",
	"FilterElement_Tooltip_Unplayed": "Include jocurile pe care nu le-ai jucat încă.",
	"FilterElement_FullControllerSupport": "Controlere (complet)",
	"FilterElement_Tooltip_FullControllerSupport": "Include jocurile care pot fi jucate în întregime cu un controler de joc.",
	"FilterElement_PartialControllerSupport": "Controlere (parțial)",
	"FilterElement_Tooltip_PartialControllerSupport": "Include jocurile care pot fi jucate cu un controler, dar ar putea solicita o tastatură și un mouse în timpul instalării sau pentru unele interacțiuni limitate.",
	"FilterElement_VRSupported": "Suport RV",
	"FilterElement_TradingCards": "Cartonașe de schimb",
	"FilterElement_Tooltip_TradingCards": "Include jocurile care au cartonașe de schimb Steam.",
	"FilterElement_Workshop": "Atelier",
	"FilterElement_Tooltip_Workshop": "Include jocurile care au integrat atelierul Steam.",
	"FilterElement_Achievements": "Realizări",
	"FilterElement_Tooltip_Achievements": "Include jocurile care acordă realizări Steam.",
	"FilterElement_SinglePlayer": "Un jucător",
	"FilterElement_Tooltip_SinglePlayer": "Include jocurile cu mod pentru un singur jucător.",
	"FilterElement_MultiPlayer": "Mai mulți jucători",
	"FilterElement_Tooltip_MultiPlayer": "Include jocurile cu un mod pentru mai mulți jucători.",
	"FilterElement_CoOp": "Cooperativ",
	"FilterElement_Tooltip_CoOp": "Include jocurile cu un mod cooperativ în mai mulți jucători.",
	"FilterElement_GenreAction": "Acțiune",
	"FilterElement_Tooltip_GenreAction": "Include jocurile de acțiune.",
	"FilterElement_GenreAdventure": "Aventură",
	"FilterElement_Tooltip_GenreAdventure": "Include jocurile de aventură.",
	"FilterElement_GenreCasual": "Casual",
	"FilterElement_Tooltip_GenreCasual": "Include jocurile casual.",
	"FilterElement_GenreIndie": "Indie",
	"FilterElement_Tooltip_GenreIndie": "Include jocurile indie.",
	"FilterElement_GenreMMO": "MMO",
	"FilterElement_Tooltip_GenreMMO": "Include jocurile MMO.",
	"FilterElement_GenreRacing": "Curse",
	"FilterElement_Tooltip_GenreRacing": "Include jocurile cu curse.",
	"FilterElement_GenreRPG": "RPG",
	"FilterElement_Tooltip_GenreRPG": "Include jocurile de rol.",
	"FilterElement_GenreSimulation": "Simulare",
	"FilterElement_Tooltip_GenreSimulation": "Include jocurile de simulare.",
	"FilterElement_GenreSports": "Sporturi",
	"FilterElement_Tooltip_GenreSports": "Include jocurile cu sporturi.",
	"FilterElement_GenreStrategy": "Strategie",
	"FilterElement_Tooltip_GenreStrategy": "Include jocurile de strategie.",
	"FilterElement_Tooltip_StoreTag": "Include aplicațiile etichetate drept %1$s pe Steam.",
	"FilterElement_SteamCloud": "Steam Cloud",
	"FilterElement_Tooltip_SteamCloud": "Include games that save to Steam Cloud.",
	"FilterElement_RemotePlayTogether": "Remote Play Together",
	"FilterElement_Tooltip_RemotePlayTogether": "Include jocurile care suportă Remote Play Together.",
	"CollectionViewHeader_Tooltip_ManuallyAddedApp": "Jocul acesta a fost adăugat manual în colecție.",
	"CollectionViewHeader_Tooltip_ManuallyRemovedApp": "Jocul acesta a fost eliminat din colecția aceasta.",
	"CollectionViewHeader_Tooltip_ManuallyRemovedApps_WithCount": "%1$s jocuri au fost eliminate din colecția aceasta.",
	"CollectionViewHeader_ManuallyRemovedApps_WithCount": "Eliminate: %1$s",
	"CollectionView_EmptyReadOnlyCollection": "Nu-i nimic de văzut aici",
	"CollectionView_EmptyDynamicCollection_Line1": "Niciun joc nu corespunde cu filtrul acesta!",
	"CollectionView_EmptyDynamicCollection_Line2": "Modifică filtrul sau trage jocuri aici pentru a extinde colecția aceasta.",
	"CollectionView_EmptyCollection": "Trage jocuri aici pentru a începe colecția aceasta.",
	"CollectionView_EmptyCollection_BecauseFilter": "%1$s joc din colecția aceasta nu este afișat în prezent datorită modului tău de filtrare selectat.",
	"CollectionView_EmptyCollection_BecauseFilter_Plural": "%1$s jocuri din colecția aceasta nu sunt afișate în prezent datorită modului tău de filtrare selectat.",
	"CollectionView_MissingCollection": "Nu a fost găsită nicio colecție.",
	"CollectionView_GamesExcluded": "+%1$s",
	"CollectionView_GamesExcluded_Desc": "titluri care nu sunt gata de joacă",
	"AllCollectionsView_Title": "Colecțiile tale",
	"AllCollectionsView_InfoIcon": "Creează %1$s pentru a-ți organiza titlurile după bunul plac sau creează %2$s pentru a-ți grupa titlurile conform unui set de filtre. %3$s",
	"AllCollectionsView_InfoIconCollections": "Colecții",
	"AllCollectionsView_InfoIconDynamicCollections": "Colecții dinamice",
	"AllCollectionsView_InfoIconFav": "%1$s tale vor fi afișate întotdeauna aici, în partea superioară a paginii.",
	"AllCollectionsView_InfoIconFavorites": "Preferate",
	"AllCollectionsView_AddCollection": "Creează o colecție nouă",
	"AllCollectionsView_DragToAddCollection": "Trage aici pentru a crea o colecție nouă",
	"GameList_Home": "Pagina principală",
	"GameList_Search": "Caută",
	"GameList_Category_Uncategorized": "Fără categorie",
	"GameList_Category_Favorites": "Preferate",
	"GameList_Category_Hidden": "Ascunse",
	"GameList_Category_Hidden_Tooltip": "Jocurile ascunse nu vor apărea în colecția ta cu excepția cazului în care le-ai căutat. Poți vedea toate jocurile ascunse în partea de sus a meniului de „vizualizare”.",
	"GameList_Category_YourCollections": "Colecțiile tale",
	"GameList_Category_SharedLibraries": "Colecții împărtășite",
	"GameList_SectionHeader_SearchResults": "Rezultate de la căutare și filtru",
	"GameList_SectionHeader_AddedManually": "Adăugat manual",
	"GameList_SectionHeader_RemovedManually": "Eliminat manual",
	"GameList_SectionHeader_NoRecentActivity": "Nicio activitate înregistrată",
	"GameList_View_Collections": "Colecțiile tale",
	"GameList_View_ThisCollection": "Vezi colecția aceasta",
	"GameList_View_OneCollection": "Vederea colecției",
	"GameList_View_SearchResults": "Rezultatele căutării",
	"GameList_View_ShowAllCollections": "Arată toate colecțiile",
	"GameList_View_GroupByCollections": "Grupează în funcție de colecție",
	"GameList_View_ExitSearch": "Părăsește căutarea",
	"GameList_View_All": "Toate",
	"GameList_View_Recent": "Recent",
	"GameList_View_SortByRecent": "Sortează după activitatea recentă",
	"GameList_View_ShowOnlyReadyToPlay": "Afișează numai titlurile gata de joacă",
	"GameList_View_ShowingReadyToPlay": "Showing only ready to play games",
	"GameList_View_ShowingOnlyReadyToPlay": "Se afișează doar cele gata de joacă",
	"GameList_View_ShowOnlyVR": "Afișează numai jocurile pentru RV",
	"GameList_View_Platform_Linux": "Afișează doar jocurile care rulează pe Linux",
	"GameList_View_Platform_Apple": "Afișează doar jocurile care rulează pe macOS",
	"GameList_View_MyOwnGames": "Jocurile mele",
	"GameList_View_GamesSharedByOther": "Jocul lui %1$s",
	"GameList_View_NothingSelected": "Nimic",
	"GameList_View_NothingSelected_HelpText": "Nu s-a găsit nimic care să corespundă cu filtrul acesta de vizualizare.",
	"GameList_Search_GamesCheckbox_Link": "Arată jocurile",
	"GameList_View_GroupSharedLibraries": "Group By Library",
	"GameList_View_GroupingDisabled_ToolTip": "Grouping is disabled in this view",
	"GameList_View_ReadyToPlay_ToolTip1": "• Instalate pe dispozitivul acesta",
	"GameList_View_ReadyToPlay_ToolTip2": "• Pot fi transmise de la un alt dispozitiv",
	"GameList_Entry_ReadyToPlay_ToolTip": "Va fi transmis de pe un alt dispozitiv",
	"GameList_Entry_Invalid_OSType": "Versiunea ta curentă de macOS (Catalina) nu poate rula jocuri pe 32-biți, cum ar fi acesta.",
	"GameList_Entry_Invalid_OSType2": "Acest titlu suportă Steam Play, iar astfel îl poți juca pe Windows utilizând Bootcamp sau un PC.",
	"GameList_Entry_Invalid_OSType3": "Află mai multe.",
	"Shelf_SectionHeader_ExpandTooltip": "Extinde raftul pentru a arăta mai multe rânduri",
	"Shelf_SectionHeader_ExpandTooltipFilter": "Extinde raftul pentru a arăta mai multe rânduri, %1$s articole nu sunt listate din cauza filtrului tău de vizualizare",
	"GameList_SectionHeader_AppCountToolTip": "%1$s nu sunt listate din cauza filtrului tău de vizualizare",
	"GameList_SectionHeader_AppCountToolTipAllHidden": "Aici nu este listat nimic din cauza filtrului tău de vizualizare",
	"CollectionAction_ViewOnlyThis": "Vezi numai colecția aceasta",
	"CollectionAction_ViewOnlyThisFavorites": "Vezi numai preferatele",
	"CollectionAction_ViewOnlyThisUncategorized": "Vezi numai titlurile fără categorii",
	"CollectionAction_Collapse": "Restrânge",
	"CollectionAction_CollapseAll": "Collapse all",
	"CollectionAction_CollapseAllCollections": "Collapse all collections",
	"CollectionAction_Expand": "Extinde",
	"CollectionAction_ExpandAll": "Expand all",
	"CollectionAction_ExpandAllCollections": "Expand all collections",
	"CollectionAction_Manage": "Gestionează",
	"CollectionAction_Edit": "Editează filtrele colecției",
	"CollectionAction_Rename": "Redenumește colecția",
	"CollectionAction_Delete": "Șterge colecția",
	"CollectionAction_DeleteDialog": "Șterge colecția",
	"CollectionAction_ConfirmDelete": "Sigur vrei să ștergi permanent colecția „%1$s”?",
	"CollectionAction_SaveFailed": "Colecția „%1$s” nu a putut fi salvată",
	"CollectionAction_CannotOverwrite": "Colecția „%1$s” nu a putut fi suprascrisă. Te rugăm să alegi un nume nou.",
	"CollectionAction_DeleteFailed": "Colecția „%1$s” nu a putut fi ștearsă",
	"LibraryHome_FriendsActivity": "Activitatea prietenilor",
	"LibraryHome_RecentGames": "Jucate recent",
	"LibraryHome_NewUpdates": "Ce mai e nou",
	"LibraryHome_YourCollection": "Biblioteca ta completă",
	"LibraryHome_RecentFriendsActivity": "Activitatea recentă a prietenilor",
	"LibraryHome_NewUpdates_LoweredPriority": "Now showing fewer updates for %1$s.",
	"LibraryHome_NewUpdates_RaisedPriority": "Now showing more updates for %1$s.",
	"LibraryHome_NewUpdates_Undo": "Anulează",
	"LibraryHome_RecentFriendsActivity_Empty": "Nothing is new or popular in your friend group right now. This shelf will auto-hide when there is no activity to display.",
	"WhatsNewSettings": "What's New Settings",
	"WhatsNew": "What's New",
	"WhatsNewFeatureExplainer": "What's New is where developers of your games communicate about updates, tournaments, DLC, events, and other game news.  Steam will show the most relevant news for you based on your playtime, prioritizing what you've played recently.",
	"WhatsNewFeatureExplainer2": "Some games will be automatically excluded from What's New if you never played more than a couple hours and it's been a long time since you last had any activity in the game.",
	"WhatsNewVisibilitySettings": "Visibility Settings",
	"WhatsNewSettings_ShowOnlyForRecentlyPlayed": "Only show for games I've played in the last 90 days",
	"WhatsNewSettings_ShowOnlyForRecentlyPlayed_Explainer": "(Individual game frequency can be adjusted by right clicking a news item.)",
	"WhatsNewSettings_ShowOnlyGameUpdates": "Only show product updates not other types of events and news",
	"WhatsNewSettings_ShowOnlyGameUpdates_Explainer": "(Individual game frequency can be adjusted by right clicking a news item.)",
	"WhatsNewPrioritySettings": "Priority Settings",
	"WhatsNewPriorityExplainer": "(Individual games can be tunred to show more or less in What's New, try right clicking an item for options.)",
	"WhatsNewYouHaveAskedToShowLessFor": "You have asked to Show Less for the following games:",
	"WhatsNewYouHaveNothingShowingLess": "You haven't asked to Show Less for any games yet.",
	"WhatsNewYouHaveAskedToShowMoreFor": "You have asked to Show More for the following games:",
	"WhatsNewYouHaveNothingShowingMore": "You haven't asked to Show More for any games yet.",
	"WhatsNewYouHaveNItemsHidden": "%1$s games are hidden from your Library and as a result hidden from What's New.",
	"Library_FriendsActivity_HotRightNowHeading": "În vogă acum",
	"Library_FriendsActivity_HotRightNowHover": "Îți arătăm jocul acesta deoarece o parte dintre prietenii tăi îl joacă chiar acum.",
	"Library_FriendsActivity_TrendingHeading": "În trend",
	"Library_FriendsActivity_TrendingHover": "Îți arătăm jocul acesta deoarece o parte dintre prietenii tăi l-au jucat mai mult decât săptămâna anterioară.",
	"Library_FriendsActivity_BeingDiscussedHeading": "În discuții",
	"Library_FriendsActivity_BeingDiscussedHover": "Îți arătăm jocul acesta deoarece o parte dintre prietenii tăi au postat capturi de ecran sau mesaje de stare.",
	"Library_FriendsActivity_RecentlyPurchasedHeading": "Achiziționat recent",
	"Library_FriendsActivity_RecentlyPurchasedHover": "Îți arătăm jocul acesta deoarece l-ai achiziționat recent și prietenii tăi îl joacă de asemenea.",
	"Library_FriendsActivity_UnownedHeading": "Încearcă ceva nou",
	"Library_FriendsActivity_UnownedHover": "Îți arătăm jocul acesta deoarece e popular în grupul tău de prieteni și nu-l deții.",
	"Library_FriendsActivity_PopularHeading": "Popular",
	"Library_FriendsActivity_PopularHover": "Îți arătăm jocul acesta deoarece o mare parte dintre prietenii tăi l-au jucat recent.",
	"Library_FriendsActivity_DontForgetHeading": "Nu uita",
	"Library_FriendsActivity_DontForgetHover": "Îți arătăm jocul acesta deoarece nu l-ai mai jucat recent, dar prietenii tăi l-au jucat.",
	"Library_FriendsActivity_NewToGroupHeading": "Noutate de la prietenii tăi",
	"Library_FriendsActivity_NewToGroupHover": "Îți arătăm jocul acesta deoarece prietenii tăi au început să-l joace recent.",
	"Library_FriendsActivity_ReturnedToGroupHeading": "Înapoi în ordinea de zi",
	"Library_FriendsActivity_ReturnedToGroupHover": "Îți arătăm jocul acesta deoarece prietenii tăi au început să-l joace din nou.",
	"Library_FriendsActivity_UnownedBanner": "Vezi în magazinul Steam",
	"Library_FriendsActivity_UnownedMenu_Store": "Magazin",
	"Library_FriendsActivity_UnownedMenu_Hub": "Centru comunitar",
	"Library_FriendsActivity_UnownedMenu_Reviews": "Recenzii",
	"Library_FriendsActivity_UnownedMenu_Discussions": "Discuții",
	"Library_Recent_NoRecentGames_GamesOwned": "Ai (%1$s) jocuri.",
	"Library_Recent_NoRecentGames_StoreLink": "Vizitează %1$s pentru a găsi jocuri pe care să le adaugi:",
	"Library_Recent_NoRecentGames_SteamStore": "Magazinul Steam",
	"Library_Recent_NoRecentGames_FreeToPlay": "Jocuri gratuite",
	"Library_Recent_NoRecentGames_GamesOnSale": "Jocuri la reducere acum",
	"Library_Recent_NoRecentGames_NewReleases": "Lansări noi",
	"Library_Recent_NoRecentGames_ActivateProduct": "Activează un produs",
	"Library_Recent_NoRecentGames_RedeemCode": "Revendică un cod de portofel",
	"Library_SortCollectionBy": "Sortează după",
	"Library_SortByFavoritesFirst": "Mai întâi preferatele",
	"Library_SortByAlphabetical": "Alfabetic",
	"Library_SortByPctAchievementsComplete": "% de realizări finalizate",
	"Library_SortByLastUpdated": "Ultima actualizare",
	"Library_SortByHoursPlayed": "Ore jucate",
	"Library_SortByLastPlayed": "Jucat ultima dată",
	"Library_SortByReleaseDate": "Data lansării",
	"Library_SortByAddedToLibrary": "Data adăugării în bibliotecă",
	"Library_SortBySizeOnDisk": "Spațiu pe disc",
	"Library_SortByMetacriticScore": "Scor Metacritc",
	"Library_SortByFriendsPlaying": "Ce joacă prietenii",
	"Library_SortBySteamReview": "Steam Review",
	"Library_SortByPctAchievementsComplete_Tag": "%1$s% finalizat",
	"Library_SortByPctAchievementsNoAchievements_Tag": "Nicio realizare",
	"Library_InstalledOnlyCheck": "Numai instalate",
	"GridSection_Favorites": "Preferate",
	"GridSection_EverythingElse": "Orice altceva",
	"GridSection_Over100Hours": "Peste 100 de ore",
	"GridSection_Over60Hours": "Peste 60 de ore",
	"GridSection_Over40Hours": "Peste 40 de ore",
	"GridSection_Over20Hours": "Peste 20 de ore",
	"GridSection_Over10Hours": "Peste 10 ore",
	"GridSection_Over1Hour": "Peste 1 oră",
	"GridSection_LessThan1Hour": "Mai puțin de 1 oră",
	"GridSection_Over90Metacritic": "Peste 90",
	"GridSection_Over80Metacritic": "Peste 80",
	"GridSection_Over70Metacritic": "Peste 70",
	"GridSection_Over50Metacritic": "Peste 50",
	"GridSection_EverythingElseMetacritic": "Orice altceva",
	"GridSection_UnknownReleaseDate": "Necunoscut",
	"GridSection_GreaterThan100GB": "Mai mult de 100GB",
	"GridSection_GreaterThan50GB": "Mai mult de 50GB",
	"GridSection_GreaterThan20GB": "Mai mult de 20GB",
	"GridSection_LessThan20GB": "Mai puțin de 20GB",
	"GridSection_NoSizeOnDisk": "Fără mărime",
	"GridSection_NotInstalled": "Neinstalate",
	"GridSection_MoreThan10YearsAgo": "Acum peste 10 ani",
	"GridSection_Never": "Niciodată",
	"AppDetails_SectionTitle_Stream": "Difuzare de la dezvoltator",
	"AppDetails_SectionTitle_Activity": "Activitate",
	"AppDetails_SectionTitle_Friends": "Prieteni care se joacă",
	"AppDetails_SectionTitle_Friends_Software": "Prieteni care folosesc",
	"AppDetails_SectionTitle_Achievements": "Realizări",
	"AppDetails_SectionTitle_TradingCards": "Cartonașe de schimb",
	"AppDetails_SectionTitle_Screenshots": "Capturi de ecran",
	"AppDetails_SectionTitle_AdditionalContent": "Conținut suplimentar",
	"AppDetails_SectionTitle_Updates": "Evenimente și actualizări recente",
	"AppDetails_SectionTitle_DLC": "DLC",
	"AppDetails_SectionTitle_LastPlayed": "Jucat ultima dată",
	"AppDetails_SectionTitle_LastLaunched": "Ultima lansare",
	"AppDetails_SectionTitle_PlayTime": "Timp petrecut",
	"AppDetails_SectionTitle_UsageTime": "Timp de utilizare",
	"AppDetails_SectionTitle_Workshop": "Atelier Steam",
	"AppDetails_SectionTitle_Community": "Conținut comunitar",
	"AppDetails_SectionTitle_Links": "Linkuri",
	"AppDetails_SectionTitle_SignIn_Pre": "Conectează-te",
	"AppDetails_SectionTitle_SignIn": "%1$s pentru a vedea activitatea prietenilor",
	"AppDetails_SectionTitle_OpenFriends": "Deschide lista de prieteni",
	"AppDetails_SectionTitle_OfflineMode": "Mod offline",
	"AppDetails_Broadcast_ViewOnWeb": "Vezi în browserul web",
	"AppDetails_Community_Tooltip1": "Secțiunea aceasta conține capturi de ecran, ilustrații, videoclipuri, ghiduri și multe alte lucruri create de către comunitate.",
	"AppDetails_Community_Tooltip2": "Poți aprecia, împărtăși, comenta sau raporta conținutul acesta.",
	"AppDetails_Community_Guide": "Ghid comunitar",
	"AppDetails_Links_Store": "Pagină din magazin",
	"AppDetails_Links_Community": "Centru comunitar",
	"Bbcode_Originally_Posted_By": "Postat inițial de",
	"AppDetails_InOfflineMode": "Steam este în prezent în modul offline. Cât timp modul offline este activat, multe caracteristici ale bibliotecii tale Steam, cum ar fi fluxul de activitate și prietenii, nu vor fi disponibile. Treci în modul online pentru a vizualiza conținutul acesta.",
	"AppDetails_GoOnline": "Treci în modul online",
	"AppDetails_PartnerEventFailedLoad": "Failed to load this event",
	"GameAction_Stop": "Stop",
	"GameAction_Cancel": "Anulează",
	"GameAction_Install": "Instalează",
	"GameAction_Uninstall": "Dezinstalează",
	"GameAction_Play": "Joacă",
	"GameAction_PlayMusic": "Redă albumul",
	"GameAction_Launch": "Lansează",
	"GameAction_PreLoad": "Preîncarcă",
	"GameAction_Update": "Actualizează",
	"GameAction_Download": "Descarcă",
	"GameAction_Resume": "Reia",
	"GameAction_Pause": "Întrerupe",
	"GameAction_BorrowApp": "Împrumută",
	"GameAction_PurchaseApp": "Achiziționează",
	"GameAction_GameProperties": "Proprietăți...",
	"GameAction_AddToFavorites": "Adaugă la preferate",
	"GameAction_RemoveFromFavorites": "Elimină din preferate",
	"GameAction_AddToHidden": "Ascunde jocul acesta",
	"GameAction_RemoveFromHidden": "Elimină din ascunse",
	"GameAction_RemoveGameLicense": "Elimină de pe cont",
	"GameAction_AddToFamilyGames": "Adaugă în jocurile de familie",
	"GameAction_RemoveFromFamilyGames": "Elimină din jocurile de familie",
	"GameAction_RemoveShortcut": "Șterge jocul non-Steam din biblioteca ta",
	"GameAction_AddToCollection": "Adaugă în",
	"GameAction_RemoveFromCollection": "Elimină din",
	"GameAction_CreateDesktopShortcut": "Adaugă o scurtătură pe desktop",
	"GameAction_BackUpFiles": "Creează o copie de rezervă a fișierelor jocului...",
	"GameAction_Stream": "Transmite",
	"GameAction_Connect": "Conectează-te",
	"GameAction_SetCustomArtwork": "Setează ilustrația personalizată",
	"GameAction_ClearCustomArtwork": "Șterge ilustrația personalizată",
	"GameAction_ViewCDKeys": "Coduri de activare",
	"GameAction_ControllerConfiguration": "Configurarea controlerului",
	"GameAction_Launching": "Launching",
	"GameAction_RemoveAppFromCollection": "TRAGE AICI pentru a elimina %1$s din colecția %2$s",
	"GameAction_RemoveAppFromMultipleCollections": "TRAGE AICI pentru a elimina %1$s din aceste colecții",
	"GameAction_RemoveMultipleAppsFromCollection": "TRAGE AICI pentru a elimina aplicațiile acestea din %1$s",
	"GameAction_RemoveMultipleAppsFromMultipleCollections": "TRAGE AICI pentru a elimina aplicațiile acestea din aceste colecții",
	"GameAction_NavigateToAllCollectionsWithDrag": "TRAGE și MENȚINE AICI pentru a vedea toate colecțiile",
	"GameAction_AddToCollectionOption_NewCollection": "Colecție nouă...",
	"GameAction_NewCollectionDialogTitle": "Colecție nouă",
	"GameAction_Manage": "Gestionează",
	"GameAction_Favorite": "Adaugă la preferate",
	"GameAction_UnFavorite": "Este în preferate",
	"GameAction_ViewDetails": "Arată mai multe detalii",
	"GameAction_BrowseLocalFiles": "Răsfoiește fișierele locale",
	"GameAction_ViewDetails_Collapse": "Arată mai puține detalii",
	"GameAction_ViewDetails_ScrollUp": "Derulează în sus",
	"GameActionPlural_Install": "Instalează ce este selectat",
	"GameActionPlural_Uninstall": "Dezinstalează ce este selectat",
	"GameActionPlural_PreLoad": "Preîncarcă ce este selectat",
	"GameActionPlural_Update": "Actualizează ce este selectat",
	"GameActionPlural_Download": "Descarcă ce este selectat",
	"GameActionPlural_Resume": "Reia ce este selectat",
	"GameActionPlural_AddToFavorites": "Adaugă ce este selectat în preferate",
	"GameActionPlural_RemoveFromFavorites": "Elimină ce este selectat din preferate",
	"GameActionPlural_AddToHidden": "Ascunde jocurile selectate",
	"GameActionPlural_RemoveFromHidden": "Elimină ce este selectat din ascunse",
	"GameActionPlural_AddToFamilyGames": "Adaugă ce este selectat în jocurile de familie",
	"GameActionPlural_RemoveFromFamilyGames": "Elimină ce este selectat din jocurile de familie",
	"GameActionPlural_RemoveShortcut": "Elimină toate jocurile non-Steam selectate din biblioteca ta",
	"GameActionPlural_AddToCollection": "Adaugă ce este selectat în",
	"GameActionPlural_RemoveFromCollection": "Elimină ce este selectat din",
	"GameActionPlural_CreateDesktopShortcut": "Adaugă scurtături pe desktop",
	"GameActionPlural_BackUpFiles": "Creează o copie de rezervă a fișierelor...",
	"PrePurchase_Preload_Title": "%1$s este pregătit acum pentru preîncărcare",
	"PrePurchase_Preload_Desc": "Descarcă fișierele jocului acum, iar astfel vei putea începe să îl butonezi de îndată ce acesta va fi deblocat!",
	"PrePurchase_PreloadComplete_Title": "%1$s a fost preîncărcat",
	"PrePurchase_PreloadComplete_Desc": "Poți începe să butonezi jocul de îndată ce acesta va fi deblocat!",
	"PrePurchase_Install_Title": "%1$s este disponibil acum pentru instalare și poate fi jucat",
	"PrePurchase_Install_Desc": "Instalează-l acum pentru a începe să te joci!",
	"PrePurchase_PlayNow_Title": "%1$s este disponibil acum pentru a fi jucat",
	"PrePurchase_PlayNow_Desc": "Începe să te joci acum!",
	"DisplayStatus_Launching": "Se lansează",
	"DisplayStatus_Uninstalling": "Se dezinstalează",
	"DisplayStatus_Installing": "Se instalează",
	"DisplayStatus_Running": "Rulează",
	"DisplayStatus_Validating": "Se validează",
	"DisplayStatus_Updating": "Se actualizează",
	"DisplayStatus_Downloading": "Se descarcă",
	"DisplayStatus_Synchronizing": "Se sincronizează cu Steam Cloud",
	"DisplayStatus_ReadyToInstall": "Pregătit de instalare",
	"DisplayStatus_ReadyToPreload": "Pregătit re preîncărcare",
	"DisplayStatus_ReadyToLaunch": "Pregătit de lansare",
	"DisplayStatus_RegionRestricted": "Indisponibil în regiunea din prezent",
	"DisplayStatus_PresaleOnly": "Acest articol nu este încă disponibil",
	"DisplayStatus_InvalidPlatform": "Disponibil pentru",
	"DisplayStatus_PreloadComplete": "Preîncărcare finalizată",
	"DisplayStatus_BorrowerLocked": "Biblioteca aceasta nu este disponibilă în prezent pentru împărtășirea în familie",
	"DisplayStatus_UpdatePaused": "Actualizare întreruptă",
	"DisplayStatus_UpdateQueued": "Actualizare în așteptare",
	"DisplayStatus_UpdateRequired": "Este necesară actualizarea",
	"DisplayStatus_UpdateDisabled": "Actualizările sunt dezactivate, deoarece Steam se află în modul offline. Treci în modul online pentru a finaliza actualizarea acestui joc.",
	"DisplayStatus_DownloadPaused": "Descărcare întreruptă",
	"DisplayStatus_DownloadQueued": "Descărcare în așteptare",
	"DisplayStatus_DownloadRequired": "Descărcare necesară",
	"DisplayStatus_DownloadDisabled": "Descărcările sunt dezactivate, deoarece Steam se află în modul offline. Treci în modul online pentru a finaliza descărcarea acestui joc.",
	"DisplayStatus_LicensePending": "Achiziția ta nu a fost finalizată încă.",
	"DisplayStatus_LicenseExpired": "Licența a expirat",
	"DisplayStatus_AvailForFree": "Disponibil gratuit",
	"DisplayStatus_AvailToBorrow": "Disponibil pentru împrumut",
	"DisplayStatus_AvailGuestPass": "Bilet de vizitator disponibil",
	"DisplayStatus_Purchase": "Disponibil pentru achiziție",
	"DisplayStatus_Preallocating": "Preallocating",
	"DisplayStatus_Committing": "Committing",
	"DisplayStatus_Verifying": "Verifying",
	"DisplayStatus_Unpacking": "Unpacking",
	"DisplayStatus_Compact_Launching": "Se lansează",
	"DisplayStatus_Compact_Uninstalling": "Se dezinstalează",
	"DisplayStatus_Compact_Installing": "Se instalează",
	"DisplayStatus_Compact_Running": "Rulează",
	"DisplayStatus_Compact_Validating": "Se validează",
	"DisplayStatus_Compact_Updating": "Se actualizează",
	"DisplayStatus_Compact_Downloading": "Se descarcă",
	"DisplayStatus_Compact_Synchronizing": "Se sincronizează cu Steam Cloud",
	"DisplayStatus_Compact_ReadyToInstall": "Pregătit de instalare",
	"DisplayStatus_Compact_ReadyToPreload": "Pregătit re preîncărcare",
	"DisplayStatus_Compact_ReadyToLaunch": "Pregătit de lansare",
	"DisplayStatus_Compact_RegionRestricted": "Indisponibil în regiunea aceasta",
	"DisplayStatus_Compact_PresaleOnly": "Jocul încă nu este lansat",
	"DisplayStatus_Compact_InvalidPlatform": "Disponibil pentru",
	"DisplayStatus_Compact_ParentalBlocked": "Blocat de vederea în familie Steam",
	"DisplayStatus_Compact_PreloadComplete": "Preîncărcare finalizată",
	"DisplayStatus_Compact_BorrowerLocked": "Împărtășirea în familie nu este disponibilă",
	"DisplayStatus_Compact_UpdatePaused": "Actualizare întreruptă",
	"DisplayStatus_Compact_UpdateQueued": "Actualizare în așteptare",
	"DisplayStatus_Compact_UpdateRequired": "Este necesară actualizarea",
	"DisplayStatus_Compact_UpdateDisabled": "Actualizarea este dezactivată în modul offline.",
	"DisplayStatus_Compact_DownloadPaused": "Descărcare întreruptă",
	"DisplayStatus_Compact_DownloadQueued": "Descărcare în așteptare",
	"DisplayStatus_Compact_DownloadRequired": "Descărcare necesară",
	"DisplayStatus_Compact_DownloadDisabled": "Descărcarea este dezactivată în modul offline.",
	"DisplayStatus_Compact_LicensePending": "Se finalizează achiziția",
	"DisplayStatus_Compact_LicenseExpired": "Licența a expirat",
	"DisplayStatus_Compact_AvailForFree": "Disponibil gratuit",
	"DisplayStatus_Compact_AvailToBorrow": "Disponibil pentru împrumut",
	"DisplayStatus_Compact_AvailGuestPass": "Bilet de vizitator disponibil",
	"DisplayStatus_Compact_Purchase": "Disponibil pentru achiziție",
	"DisplayStatus_ReleaseDate": "În curând: %1$s",
	"DisplayStatus_CustomReleaseDate": "Data de lansare planificată: %1$s",
	"Downloads_State_Bytes_Of_Bytes": "%1$s din %2$s",
	"Downloads_State_None": "",
	"Downloads_State_Reconfiguring": "Începe descărcarea",
	"Downloads_State_Validating": "Se validează fișierele",
	"Downloads_State_AddingFiles": "Se copiază fișierele",
	"Downloads_State_Preallocating": "Se rezervă spațiul",
	"Downloads_State_Downloading": "",
	"Downloads_State_Staging": "",
	"Downloads_State_Committing": "Se finalizează",
	"Downloads_State_Verifying": "Se verifică descărcarea",
	"Downloads_State_Stopping": "Se oprește descărcarea",
	"Downloads_State_Running": "",
	"Downloads_State_SecondsRemaining": "%1$s secunde rămase",
	"Downloads_State_MinutesRemaining": "%1$s minute rămase",
	"Downloads_State_Calculating": "Se calculează...",
	"LaunchApp_Action_UpdatingAppInfo": "Se verifică configurarea",
	"LaunchApp_Action_ShowEula": "Afișează EULA (acordul de licență pentru utilizatorul final)",
	"LaunchApp_Action_DownloadingDepots": "Se descarcă conținutul (%1$s%)",
	"LaunchApp_Action_DownloadingWorkshop": "Se descarcă atelierul (%1$s%)",
	"LaunchApp_Action_UpdatingDRM": "Se actualizează executabilul",
	"LaunchApp_Action_GettingLegacyKey": "Se actualizează codul de activare",
	"LaunchApp_Action_RunningInstallScript": "Se rulează scriptul de instalare (%1$s)",
	"LaunchApp_Action_SynchronizingCloud": "Se sincronizează cu Steam Cloud",
	"LaunchApp_Action_VerifyingFiles": "Se verifică executabilul",
	"LaunchApp_Action_CreatingProcess": "Se lansează executabilul",
	"LaunchApp_Action_WaitingGameWindow": "Se lansează executabilul",
	"LaunchApp_Action_DelayLaunch": "Amână lansarea (%1$s%)",
	"AppDetails_TitleUpdatedSincePlayed": "Titlul acesta a fost actualizat de când l-ai jucat ultima dată",
	"AppDetails_TitleUpdatedSincePlayedLink": "Află mai multe despre modificări",
	"AppDetails_BadgeLevel": "Nivelul %1$s, EXP: %2$s",
	"AppDetails_UnearnedBadgeXP": "%1$s EXP",
	"AppDetails_BadgeLevelNoXP": "Nivelul %1$s",
	"AppDetails_Review_ViewOrEdit": "Editează recenzia mea",
	"AppDetails_Review_YourReview": "Recenzia mea",
	"AppDetails_Review_Ignore_Stale_Reviews": "Nu-mi reaminti să actualizez recenzia aceasta.",
	"AppDetails_Review_Unignore_Stale_Reviews": "Permite evidențierea recenziilor vechi pentru jocul acesta.",
	"AppDetails_Review_RecommendGame": "Ai recomanda jocul aceasta?",
	"AppDetails_Review_RecommendSoftware": "Ai recomanda software-ul aceasta?",
	"AppDetails_Review_WriteReview": "Scrie o recenzie pentru %1$s",
	"AppDetails_Review_PlayedForTime": "Ai jucat titlul timp de %1$s",
	"AppDetails_Review_PlayedForTime_Software": "Ai folosit titlul acesta timp de %1$s",
	"AppDetails_Review_RecommendGameButton_Yes": "Da",
	"AppDetails_Review_RecommendGameButton_No": "Nu",
	"AppDetails_Review_PlaytimeAtReview": "%1$s jucate la momentul recenziei",
	"AppDetails_Review_PlaytimeAtReview_Software": "Folosit timp de %1$s la momentul recenziei",
	"AppDetails_Review_NotRecommended": "Nerecomandat",
	"AppDetails_Review_Recommended": "Recomandat",
	"AppDetails_Review_AdditionalPlaytime": "Ai mai jucat titlul încă %1$s de când ai scris recenzia aceasta.",
	"AppDetails_Review_AdditionalPlaytime_Software": "L-ai mai folosit încă %1$s de când ai scris recenzia aceasta.",
	"AppDetails_Review_ChangedYourMind": "Ți-ai schimbat părerea?",
	"AppDetails_Review_IHaveNotChangedMyMind": "Nu",
	"AppDetails_Review_UpVotes": "Aprecieri:",
	"AppDetails_Review_Comments": "Comentarii:",
	"AppDetails_Review_ViewAll": "Vezi toate recenziile mele",
	"AppDetails_Review_ViewAllByFriend": "Vezi toate recenziile scrise de %1$s",
	"OverflowBox_Action_Collapse": "Vezi mai puțin",
	"OverflowBox_Action_Expand": "Citește mai multe",
	"OverflowBox_More": "(încă %1$s)",
	"AppDetails_FriendsInGameNow": "%1$s prieten se joacă chiar acum",
	"AppDetails_FriendsInGameNow_Plural": "%1$s prieteni se joacă chiar acum",
	"AppDetails_FriendsPlayedRecently": "%1$s prieten s-a jucat recent",
	"AppDetails_FriendsPlayedRecently_Plural": "%1$s prieteni s-au jucat recent",
	"AppDetails_FriendsPlayedRecentlyExpand": "Arată toate titlurile jucate recent",
	"AppDetails_FriendsPlayed": "%1$s prieten s-a jucat înainte",
	"AppDetails_FriendsPlayed_Plural": "%1$s prieteni s-au jucat înainte",
	"AppDetails_FriendsPlayedExpand": "Arată toate titlurile jucate anterior",
	"AppDetails_FriendsMore": "(încă %1$s)",
	"AppDetails_FriendsLess": "Arată mai puțin",
	"AppDetails_FriendsWishlisted": "%1$s prieten are %2$s în lista sa de dorințe",
	"AppDetails_FriendsWishlisted_Plural": "%1$s prieteni au %2$s în listele lor de dorințe",
	"AppDetails_FriendsWishlistExpand": "Arată toate jocurile din listele de dorințe",
	"AppDetails_Friends_ViewAll": "Vezi toți prietenii care se joacă",
	"AppDetails_GameInfo": "Informațiile jocului",
	"AppDetails_Publisher": "Distribuitor:",
	"AppDetails_Developer": "Dezvoltator:",
	"AppDetails_Franchise": "Franciză:",
	"AppDetails_ReleaseDate": "Data lansării:",
	"AppDetails_LastUpdate": "Last local update:",
	"AppDetails_OriginalReleaseDate": "Data lansării inițiale:",
	"AppDetails_Feature_SinglePlayer": "Un jucător",
	"AppDetails_Feature_MultiPlayer": "Mai mulți jucători",
	"AppDetails_Feature_CoOp": "Joc cooperativ",
	"AppDetails_Feature_SteamAchievements": "Realizări",
	"AppDetails_Feature_SteamCloud": "Salvări în Cloud",
	"AppDetails_Feature_FullController": "Suport complet pentru controler",
	"AppDetails_Feature_PartialController": "Suport parțial pentru controler",
	"AppDetails_Feature_SteamWorkshop": "Atelier Steam",
	"AppDetails_Feature_VRSupport": "Suport pentru RV",
	"AppDetails_ViewAllUpdates": "Vezi toate actualizările",
	"AppDetails_ViewAllAchievements": "Vezi realizările mele",
	"AppDetails_ViewGlobalAchievements": "Vezi statisticile globale pentru realizări",
	"AppDetails_PlayerUnlockedPercent": "Ai deblocat %1$s/%2$s",
	"AppDetails_PlayerUnlockedPercentAll": "Ai deblocat toate realizările! %1$s/%2$s",
	"AppDetails_Achievements_Unlocked": "Deblocat pe %1$s",
	"AppDetails_PctUnlocked": "%1$s% dintre jucători au realizarea aceasta",
	"AppDetails_GlobalCompare": "Asta e mai mult de %1$s% dintre jucători",
	"AppDetails_ViewTradingCards": "Vezi cartonașele mele de schimb",
	"AppDetails_Achievements_Locked": "Realizări blocate",
	"AppDetails_TradingCardsLeft": "1 cartonaș de schimb rămas spre a fi colecționat",
	"AppDetails_TradingCardsLeft_Plural": "%1$s cartonașe de schimb rămase spre a fi colecționate",
	"AppDetails_TradingCardsLevelUp": "Ai suficiente cartonașe de schimb pentru a mări nivelul insignei!",
	"AppDetails_TradingCardsMaxed": "Felicitări! Insigna este la nivelul maxim!",
	"AppDetails_TradingCards_Tooltip1": "Cartonașele de schimb îți pică în timp ce te joci. Poți face schimb cu prietenii (sau pe piața comunitară Steam) pentru a obține cartonașele pe care nu le ai.",
	"AppDetails_TradingCards_Tooltip2": "Completează un set de cartonașe de schimb și vei putea să le fabrici într-o insignă. Insignele îți măresc nivelul tău Steam și vor debloca beneficii pentru profilul și contul tău.",
	"AppDetails_BrowseWorkshop": "Răsfoiește atelierul",
	"AppDetails_ViewSubscribedItems": "Vezi abonamentele mele",
	"AppDetails_ViewItemInWorkshop": "Vezi în atelier",
	"AppDetails_MoreItemsFrom": "Vezi obiecte de la creatorul acesta",
	"AppDetails_SubscribeToItem": "Abonează-te",
	"AppDetails_UnsubscribeFromItem": "Dezabonează-te",
	"AppDetails_Subscribed": "Abonat",
	"AppDetails_ViewMoreInWorkshop": "Vezi mai multe în atelier",
	"AppDetails_WorkshopSubCount": "Ai (%1$s) abonamente de atelier.",
	"AppDetails_WorkshopVisit": "Vizitează acest atelier",
	"AppDetails_WorkshopLearnMore": "Află mai multe",
	"AppDetails_WorkshopFeaturedHeader": "Obiect în trend",
	"AppDetails_WorkshopFeaturedItem": "Obiect popular",
	"AppDetails_WorkshopFeaturedMoreInfo": "Citește mai multe",
	"AppDetails_WorkshopFeaturedHideItem": "Ascunde acest obiect",
	"AppDetails_WorkshopFileSize": "Dimensiunea fișierului: %1$s",
	"AppDetails_WorkshopFileSizeBytes": "%1$s bytes",
	"AppDetails_WorkshopFileSizeKb": "%1$s KM",
	"AppDetails_WorkshopFileSizeMb": "%1$s MB",
	"AppDetails_WorkshopFileSizeGb": "%1$s GB",
	"AppDetails_WorkshopLastUpdated": "Ultima actualizare: %1$s",
	"DLCStatus_installed": "Instalat",
	"DLCStatus_notinstalled": "Neinstalat",
	"DLCStatus_downloading": "Se descarcă",
	"DLC_DateAdded": "Adăugat la: %1$s",
	"AppDetails_ManageDLC": "Gestionează propriile DLC-uri: %1$s",
	"AppDetails_ManageMyDLC": "Gestionează propriile DLC-uri",
	"AppDetails_ViewStoreDLC": "Vezi DLC-ul în magazin",
	"AppDetails_DLCSpotlight": "DLC-ul obținut recent a fost adăugat și va fi instalat împreună cu jocul. Gestionează DLC-ul tău %1$s.",
	"AppDetails_DLCSpotlight_Installed": "DLC-ul obținut recent a fost instalat în mod automat. Gestionează DLC-ul tău %1$s.",
	"AppDetails_DLCSpotlight_here": "aici",
	"ManageDLC_Title": "Gestionează DLC-urile",
	"ManageDLC_Column_Name": "Nume",
	"ManageDLC_Column_DateAdded": "Data adăugării",
	"ManageDLC_Column_Enabled": "Activat",
	"ManageDLC_Column_Installed": "Instalate",
	"ManageDLC_Search": "Caută...",
	"ManageDLC_Installed": "%1$s/%2$s instalate",
	"ManageDLC_ViewMore": "Vezi mai multe în magazin",
	"ManageDLC_NoResults": "Nu a fost găsit niciun rezultat pentru „%1$s”",
	"AppDetails_ViewBadgePage": "Vezi pagina insignei",
	"AppDetails_VisitTradeForum": "Vizitează forumul de schimburi",
	"AppDetails_BuyCards": "Achiziționează restul de cartonașe de pe piață",
	"AppDetails_SellCards": "Vinde cartonașele acestea pe piață",
	"AppDetails_SearchCard": "Arată cartonașul acesta pe piață",
	"AppDetails_ShowFriendsList": "Arată lista de prieteni",
	"AppDetails_ViewFriendsWhoPlay": "Vezi prietenii care se joacă",
	"AppDetails_Link_Discussions": "Discuții",
	"AppDetails_Link_FindGroups": "Găsește grupuri",
	"AppDetails_Link_GameHub": "Centru comunitar",
	"AppDetails_Link_Guides": "Ghiduri",
	"AppDetails_Link_Store": "Pagina din magazin",
	"AppDetails_Link_Support": "Asistență",
	"AppDetails_Link_Workshop": "Atelier",
	"AppDetails_Link_Market": "Piață",
	"AppDetails_Link_Controller": "Configurația controlerului",
	"AppDetails_SocialMediaLink": "%1$s pe %2$s",
	"AppDetails_SocialMediaType_4": "Twitter",
	"AppDetails_SocialMediaType_5": "Twitch",
	"AppDetails_SocialMediaType_6": "YouTube",
	"AppDetails_SocialMediaType_7": "Facebook",
	"AppDetails_Screenshot": "Captură de ecran",
	"AppDetails_Screenshot_Caption": "Descriere: %1$s",
	"AppDetails_Screenshot_Date": "Data: %1$s",
	"AppDetails_Screenshot_Dimensions": "Dimensiuni: %1$s x %2$s pixeli",
	"AppDetails_Screenshot_Uploaded": "Încărcat: %1$s la %2$s",
	"AppDetails_OpenScreenshotUploader": "Deschide instrumentul de încărcare a capturilor de ecran",
	"AppDetails_ViewUploadedScreenshots": "Vezi capturile de ecran încărcate",
	"AppDetails_ManageMyScreenshot": "Gestionează captura mea de ecran",
	"AppDetails_ManageMyScreenshot_Plural": "Gestionează-mi cele %1$s capturi de ecran",
	"AppDetails_HowToScreenshot": "Poți realiza o captură de ecran dacă apeși %1$s în timpul jocului.",
	"AppDetails_ChangeMyScreenshotKey": "Schimbă tasta asociată capturilor de ecran",
	"AppDetails_NoScreenshots": "Nu ai realizat încă nicio captură de ecran",
	"AppDetails_Screenshot_SpoilerAlert": "Potential spoilers. Hover to reveal image.",
	"AppDetails_Artwork": "Ilustrație",
	"AppDetails_Video": "Videoclip",
	"AppDetails_CommunityItem": "Conținut comunitar",
	"AppDetails_CommunityFeed_OutOfContent": "Nu există conținut suplimentar",
	"AppDetails_CommunityFeed_Inappropriate": "Conținutul poate să nu fie adecvat pentru toate segmentele de public",
	"AppDetails_CommunityFeed_ViewContent": "Vezi conținutul",
	"AppDetails_CommunityFeed_EditPreferences": "Editează preferințele",
	"AppDetails_CommunityFeed_LoadCommunity": "Încarcă conținutul comunitar",
	"AppBox_NewToLibrary": "Nou în bibliotecă",
	"AppBox_ComingSoon": "În curând",
	"AppBox_NewToLibrary_Short": "Nou",
	"AppBox_ComingSoon_Short": "Curând",
	"AppBox_PlayTimeHeader": "Timp petrecut",
	"AppBox_RecentPlayTime_Hours": "Ultimele două săptămâni: %1$s ore",
	"AppBox_RecentPlayTime_Minutes": "Ultimele două săptămâni: %1$s minute",
	"AppBox_TotalPlayTime_Hours": "Total: %1$s ore",
	"AppBox_TotalPlayTime_Minutes": "Total: %1$s minute",
	"AppActivity_Achieved": " a realizat",
	"AppActivity_PostedScreenshot": " a împărtășit o captură de ecran",
	"AppActivity_PostedScreenshot_Plural": " a împărtășit %1$s capturi de ecran",
	"AppActivity_PostedVideo": " a împărtășit un videoclip",
	"AppActivity_PostedVideo_Plural": " a împărtășit %1$s videoclipuri",
	"AppActivity_ReceivedNewGame": " deține acum %1$s",
	"AppActivity_PlayedGameFirstTime": " a jucat %1$s pentru prima oară",
	"AppActivity_LaunchedSoftwareFirstTime": " a lansat %1$s pentru prima oară",
	"AppActivity_AddedGameToWishlist": " a adăugat %1$s în %2$s.",
	"AppActivity_Wishlist": "lista de dorințe",
	"AppActivity_Achieved_PlusMore": "…și încă %1$s realizări",
	"AppActivity_Achieved_PlusMore_Label": "Vezi toate realizările lui %1$s",
	"AppActivity_NoActivity": "Nu există nicio activitate recentă de la dezvoltatorii acestui titlu sau de la prietenii tăi.",
	"AppActivity_UserStatus_Time": " a postat o actualizare de stare la %1$s",
	"AppActivity_UserStatus": " a postat o actualizare de stare",
	"AppActivity_StatusUpdate": "Postează o stare pentru prietenii tăi",
	"AppActivity_StatusUpdate_Post": "Spune-le prietenilor ceva despre jocul acesta...",
	"AppActivity_StatusUpdate_Software_Post": "Spune-le prietenilor ceva despre software-ul acesta...",
	"AppActivity_Comment_Reply": "Adaugă un răspuns...",
	"AppActivity_PostStatusUpdate": "Postează",
	"AppActivity_FetchMore": "Încarcă mai multă activitate",
	"AppActivity_EndofFeed": "Sfârșitul activităților",
	"AppActivity_DeleteUserNews": "Apasă pentru a șterge această postare.",
	"AppActivity_ConfirmDeleteTitle": "Șterge postarea",
	"AppActivity_ConfirmDeleteTitle_Desc": "Sigur dorești să ștergi această postare? Aceasta va fi ștearsă permanent.",
	"AppActivity_RecommendedGame": " a recenzat jocul acesta",
	"AppActivity_RecommendedGame_ReadMore": "Citește mai multe",
	"AppActivity_RatingDetails": "%1$s persoane au apreciat asta",
	"AppActivity_RatingDetails_1Other": "1 persoană a apreciat asta, %1$s",
	"AppActivity_RatingDetails_2Others": "%1$s persoane au apreciat asta, printre care %2$s și %3$s",
	"AppActivity_RatingDetails_User": "Ai apreciat asta",
	"AppActivity_RatingDetails_User_1Other": "%1$s au apreciat asta, printre care tu și %2$s",
	"AppActivity_RatingDetails_User_2Others": "%1$s persoane au apreciat asta, printre care tu, %2$s și %3$s",
	"AppActivity_RatingDetails_PublishedFile": "%1$s aprecieri",
	"AppActivity_RateUp": "Apreciază",
	"AppActivity_ConfirmDeleteCommentTitle": "Șterge comentariul",
	"AppActivity_ConfirmDeleteCommentTitle_Desc": "Sigur dorești să ștergi acest comentariu? Acesta va fi șters permanent.",
	"AppActivity_MakeCommentsVisible": "Vezi comentariile anterioare (%1$s)",
	"AppActivity_Settings": "Setări",
	"AppActivity_ViewComments": "Vezi comentariile",
	"AppActivity_AddComments": "Adaugă un comentariu",
	"AppActivity_ContributeComments": "Comentează",
	"AppActivity_SteamTradingCards_EarnedTradingCards": " a obținut cartonașe de schimb",
	"AppActivity_SteamTradingCards_EarnedTradingCard": " a obținut un cartonaș de schimb",
	"AppActivity_SteamTradingCards_EarnedBoosterPack": " a obținut un pachet cu cartonașe",
	"AppActivity_SteamTradingCards_BadgeCrafted": " a fabricat o insignă",
	"AppActivity_ViewLatestNews": "Vezi cele mai recente știri",
	"AppActivity_EventType_GameUpdate": "Actualizare de joc",
	"AppSpotlight_PostGameSummary": "Sumarul la sfârșit de joc",
	"AppDetails_Shortcut_Explanation": "Anumite informații detaliate despre %1$s nu sunt disponibile, deoarece acesta este un joc sau mod non-Steam. Steam va lansa în continuare jocul, iar în cele mai multe cazuri, interfața Steam va fi disponibilă în timpul jocului.",
	"AppDetails_Takeover_Update_Header": "În caz că ai ratat",
	"AppDetails_Takeover_Update_ViewAll": "Vezi toate actualizările jocului %1$s",
	"AppDetails_Takeover_Update_ReadMore": "Citește mai multe",
	"AppDetails_Takeover_DLC_Header": "Obiecte noi adăugate",
	"AppDetails_Takeover_DLC_ViewInStore": "Vezi %1$s în magazin",
	"AppDetails_Takeover_Achievements_Header": "%2$s jucate, ai o realizare nouă...",
	"AppDetails_Takeover_Achievements_Header_Plural": "%2$s jucate, ai realizări noi...",
	"AppDetails_Takeover_TradingCards_Header": "%2$s jucate, ai un obiect nou...",
	"AppDetails_Takeover_TradingCards_Header_Plural": "%2$s jucate, ai obiecte noi...",
	"AppDetails_ViewMyInventory": "Vezi inventarul meu",
	"AppDetails_ViewInMyInventory": "Vezi în inventarul meu",
	"AppDetails_Soundtrack_TotalTracks": "%1$s piste",
	"AppDetails_Soundtrack_DiscNumber": "Discul %1$s",
	"AppDetails_Soundtrack_TrackCount": "%1$s Piste",
	"AppDetails_Soundtrack_PlayAlbum": "Redă albumul",
	"AppDetails_Soundtrack_DownloadAlbum": "Descarcă albumul",
	"AppDetails_Soundtrack_AddToQueue": "Adaugă în coadă",
	"AppDetails_Soundtrack_AddToPlaylist": "Adaugă în lista de redare",
	"AppDetails_Soundtrack_ViewOnDisk": "Browse Local Files",
	"AppDetails_Soundtrack_ViewAdditionalArtwork": "View Additional Artwork",
	"AppDetails_Soundtrack_ViewStorePage": "Vezi pagina din magazin",
	"AppDetails_Soundtrack_Support": "View Support Page",
	"AppDetails_Soundtrack_ParentAppLink": "Coloană sonoră pentru %1$s",
	"AppPortraitHover_DownloadStatusTitle": "Se descarcă",
	"AppPortraitHover_DownloadStatusTitle_Update": "Se descarcă actualizarea",
	"AppPortraitHover_DaysSinceLastUpdate": "Actualizat: %1$s",
	"AppPortraitHover_FriendsPlaying": "%1$s prieteni se joacă",
	"MajorUpdate_ViewDetails": "Vezi detaliile",
	"MajorUpdate_NextUpdate": "Actualizarea următoare",
	"MajorUpdate_PostTime": "Postat cu %1$s zile în urma la %2$s:%3$s",
	"MajorUpdate_PostTimeToday": "Postat astăzi la %1$s:%2$s",
	"MajorUpdate_WatchNow": "Vezi pe SteamTV",
	"MajorUpdate_Type0": "Actualizare importantă",
	"MajorUpdate_Type1": "Transmisiune live",
	"MajorUpdate_Type14": "Actualizare importantă",
	"MajorUpdate_Context_RemoveThisUpdate": "Elimină actualizarea aceasta",
	"MajorUpdate_Context_ShowMeFewerForApp": "Arată mai puține de la %1$s",
	"MajorUpdate_Context_ShowMeMoreForApp": "Arată mai multe de la %1$s",
	"MajorUpdate_Context_ResetHiddenUpdates": "Arată toate actualizările din nou",
	"MajorUpdate_Context_WhyAmISeeingThis": "De ce văd asta?",
	"MajorUpdate_Context_WhyAmISeeingThis_Text": "Aceasta este o actualizare importantă pentru un produs din biblioteca ta care are mai mult de 20 de ore de joc.",
	"MajorUpdate_Context_WhyAmISeeingThis_Close": "Închide",
	"CustomArt_ErrorTitle": "Eroare",
	"CustomArt_BadFileType": "Fișierul tău trebuie să fie în format JPG sau PNG.",
	"CustomArt_UnknownError": "A avut loc o eroare în timp ce se seta ilustrația ta.",
	"CustomArt_SetCustomBackground": "Setează un fundal personalizat",
	"CustomArt_ClearCustomBackground": "Șterge fundalul personalizat",
	"CustomArt_SetCustomLogo": "Setează un logo personalizat",
	"CustomArt_ClearCustomLogo": "Șterge logoul personalizat",
	"CustomArt_EditLogoPosition": "Ajustează poziția logoului",
	"CustomArt_ResetLogoPosition": "Resetează poziția logoului",
	"CustomArt_DoneEditingLogo": "Gata",
	"AppDetails_LibraryInUse": "Biblioteca este folosită de",
	"AppDetails_InSharedLibrary": "Din biblioteca lui",
	"FriendContextMenu_OpenFriends": "Deschide prietenii și chatul",
	"FriendContextMenu_ViewProfile": "Vezi profilul",
	"Generic_ScrollToTop": "Derulează în sus",
	"Generic_ViewGameDetails": "Vezi jocul în bibliotecă",
	"GameDetails_CollectionContext_GoTo": "Accesează colecția",
	"GameDetails_CollectionContext_Remove": "Elimină din bibliotecă",
	"ArtworkModal_ViewAll": "Vezi toate capturile de ecran",
	"ArtworkModal_FileSize": "Dimensiunea fișierului",
	"ArtworkModal_Posted": "Postat",
	"ArtworkModal_Size": "Dimensiune",
	"ArtworkModal_CreatedBy": "Creată de",
	"ArtworkModal_ScrollForMore": "Derulează în jos pentru comentarii",
	"ArtworkModal_ScrollForDetails": "Derulează în jos pentru mai multe detalii",
	"CommunityItem_Menu_Report": "Raportează",
	"ReportItem_Title": "Raportează acest obiect",
	"ReportItem_Description": "Te rugăm să descrii modul în care elementul acesta încalcă condițiile de utilizare Steam. Te rugăm să incluzi orice informație relevantă sau linkuri. Trimiterea acestei raportări este ireversibilă.",
	"ReportItem_Description_Line2": "Obiectele raportate nu vor mai apărea pe pagina ta de bibliotecă.",
	"ReportItem_DMCA": "Dacă dorești să raportezi o încălcare a drepturilor de autor și tu ești deținătorul drepturilor de autor, te rugăm să accesezi formularu nostru DMCA de încălcare a drepturilor de autor %1$s",
	"ReportItem_DMCA_LinkText": "aici",
	"ReportItem_Error": "A apărut o problemă la trimiterea cererii tale către serverele noastre. Te rugăm să încerci din nou mai târziu.",
	"ReportItem_SubmitReport": "Trimite un raport",
	"RemoveFreeApp_Title": "Elimină de pe contul tău",
	"RemoveFreeApp_Description": "%1$s a fost adăugat pe contul tău prin intermediul unei licențe gratuite. Poți elimina acest produs de pe contul tău pentru ca acesta să nu mai fie inclus în biblioteca ta Steam și în lista cu jocurile pe care le deții.",
	"RemoveFreeApp_Question": "Dorești să elimini „%1$s” de pe contul tău?",
	"RemoveFreeApp_Remove": "Elimină",
	"RemoveFreeApp_Removing": "Se elimină %1$s",
	"RemoveFreeApp_Error": "A avut loc e eroare în timp ce s-a încercat să se elimine %1$s",
	"UninstallDialog_Title": "Dezinstalează",
	"UninstallDialog_Uninstall": "Dezinstalează",
	"UninstallDialog_ErrorMessage": "%1$s nu a putut fi dezinstalat:",
	"UninstallDialog_Busy": "O altă operațiune de instalare/dezinstalare are loc în prezent. Te rugăm să aștepți ca aceasta să se finalizeze.",
	"UninstallDialog_SecuROM": "Dezinstalarea aceste aplicații necesită o conexiune la internet.",
	"UninstallDialog_UnknownError": "A intervenit o eroare neașteptată în timpul dezinstalării acestei aplicații.",
	"UninstallDialog_AppUpdateError": "Eroare de dezinstalare - %1$s",
	"UninstallDialog_Confirmation_Single": "Dorești să dezinstalezi %1$s de pe calculatorul acesta? Titlul va rămâne în biblioteca ta de jocuri, dar va trebui să redescarci întregul său conținut dacă dorești să îl joci în viitor.",
	"UninstallDialog_Confirmation_Multiple": "Dorești să dezinstalezi aceste titluri selectate de pe calculatorul tău? Titlurile acestea vor rămâne în biblioteca ta de jocuri, dar va trebui să le redescarci întregul lor conținut dacă dorești să le joci în viitor.",
	"UninstallingDialog_Uninstalling": "Se dezinstalează",
	"UninstallingDialog_UninstallingApp": "Se dezinstalează %1$s",
	"UninstallingDialog_WaitingForPassword": "Se așteaptă parola",
	"Showcase_AddNewShowcase": "Adaugă un raft nou",
	"Showcase_DeleteShowcase": "Șterge raftul acesta",
	"Showcase_SelectCategory": "Alege un raft",
	"Showcase_EmptyShowcaseHint": "Alege ce să afișezi pe raftul acesta. De aici mai poți modifica sau șterge raftul, de asemenea!",
	"Showcase_GoToCollection": "Accesează colecția",
	"Showcase_GoToAllCollections": "Acceseazî toate colecțiile",
	"Showcase_AllYourGames": "Toate jocurile",
	"Showcase_AllCollections": "Vederea colecțiilor",
	"Showcase_RecentGames": "Jucate recent",
	"Showcase_DoneReordering": "Gata",
	"Playtime_TwoWeeks_Minutes": "%1$s minute jucate recent",
	"Playtime_TwoWeeks_Hours": "%1$s ore jucate recent",
	"Playtime_Total_Minutes": "%1$s minute jucate în total",
	"Playtime_Total_Hours": "%1$s ore jucate în total",
	"Playtime_Minutes": "%1$s minute",
	"Playtime_Hours": "%1$s ore",
	"Playtime_Recently": "%1$s jucate recent",
	"Playtime_Total": "%1$s jucate în total",
	"GameList_Search_NoResults_Title": "Nu găsești ceea ce cauți?",
	"GameList_Search_NoResults_Link": "Caută în magazinul Steam",
	"StreamingClient_Select_ThisMachine": "Dispozitivul acesta",
	"StreamingClient_Select_RemotePlayPhone": "Phones",
	"StreamingClient_Select_RemotePlayTablet": "Tablets",
	"StreamingClient_Select_RemotePlayMobile": "Mobile devices",
	"StreamingClient_Select_RemotePlayTV": "TVs",
	"StreamingClient_Select_RemotePlayTVPhone": "TVs & phones",
	"StreamingClient_Select_RemotePlayTVTablet": "TVs & tablets",
	"StreamingClient_Select_RemotePlayTVMobile": "TVs & mobile devices",
	"Beta_BetaTag": "VERSIUNEA BETA",
	"Beta_Changelist": "Lista modificărilor",
	"Beta_GiveFeedback": "Oferă-ne părerea ta",
	"ContextMenu_SaveScreenshot": "Salvează captura de ecran ca...",
	"ContextMenu_BrowseScreenshot": "Browse to screenshot",
	"ContextMenu_ManageScreenshots": "Administrează capturile de ecran",
	"SteamChina_DurationControl_Init_1": "Healthy Gaming Advisory",
	"SteamChina_DurationControl_Init_2": "Boicotează jocurile dăunătoare, respinge piratarea jocurilor.",
	"SteamChina_DurationControl_Init_3": "Practică protecția de sine, evita păcălelile.",
	"SteamChina_DurationControl_Init_4": "Moderation promotes brain health; excess play is harmful to the body.",
	"SteamChina_DurationControl_Init_5": "Well-planned use of your time will lead to a healthy lifestyle.",
	"Steam_AppUpdateError_0": "nicio eroare",
	"Steam_AppUpdateError_1": "eroare necunoscută",
	"Steam_AppUpdateError_2": "actualizare întreruptă",
	"Steam_AppUpdateError_3": "actualizare anulată",
	"Steam_AppUpdateError_4": "actualizare suspendată",
	"Steam_AppUpdateError_5": "nicio licență",
	"Steam_AppUpdateError_6": "nicio conexiune la internet",
	"Steam_AppUpdateError_7": "conexiunea a expirat",
	"Steam_AppUpdateError_8": "conținutul este în continuare criptat",
	"Steam_AppUpdateError_9": "configurația aplicației nu este disponibilă",
	"Steam_AppUpdateError_10": "eroare de citire a discului",
	"Steam_AppUpdateError_11": "eroare de scriere pe disc",
	"Steam_AppUpdateError_12": "nu există suficient spațiu liber pe disc",
	"Steam_AppUpdateError_13": "fișierele cu conținut sunt deteriorate",
	"Steam_AppUpdateError_14": "se așteaptă discul de instalare",
	"Steam_AppUpdateError_15": "calea de instalare nu este validă",
	"Steam_AppUpdateError_16": "aplicația rulează",
	"Steam_AppUpdateError_17": "conținutul partajat lipsește",
	"Steam_AppUpdateError_18": "nu este instalat",
	"Steam_AppUpdateError_19": "este necesară actualizarea",
	"Steam_AppUpdateError_20": "ocupat",
	"Steam_AppUpdateError_21": "serverele cu conținut nu pot fi accesate",
	"Steam_AppUpdateError_22": "configurația aplicației nu este validă",
	"Steam_AppUpdateError_23": "configurația depotului nu este validă",
	"Steam_AppUpdateError_24": "manifestul nu este disponibil",
	"Steam_AppUpdateError_25": "aplicația nu a fost lansată",
	"Steam_AppUpdateError_26": "restricție regională",
	"Steam_AppUpdateError_27": "cache-ul cu conținut este deteriorat",
	"Steam_AppUpdateError_28": "lipsește executabilul",
	"Steam_AppUpdateError_29": "platformă nevalidă",
	"Steam_AppUpdateError_30": "sistemul de fișiere nu este suportat",
	"Steam_AppUpdateError_31": "fișierele pentru actualizare sunt deteriorate",
	"Steam_AppUpdateError_32": "descărcările sunt dezactivate",
	"Steam_AppUpdateError_33": "biblioteca împărtășită este blocată",
	"Steam_AppUpdateError_34": "achiziția se află în așteptare",
	"Steam_AppUpdateError_35": "o altă sesiune utilizează titlul acesta",
	"Steam_AppUpdateError_36": "descărcare deteriorată",
	"Steam_AppUpdateError_37": "discul este deteriorat",
	"Steam_AppUpdateError_38": "missing file privileges",
	"Steam_AppUpdateError_39": "fișierul cu conținut este blocat",
	"Steam_AppUpdateError_40": "conținutul nu este disponibil",
	"Steam_AppUpdateError_41": "executabilul necesită un sistem de operare pe 64 de biți",
	"Steam_AppUpdateError_42": "lipsesc fișierele descărcate",
	"Steam_AppUpdateError_43": "nu există suficient spațiu liber pe disc pentru utilizator - verifică setările de alocare a spațiului pe disc ale sistemului de operare",
	"Steam_AppUpdateError_44": "licența locației este blocată",
	"Steam_AppUpdateError_45": "parental control blocked",
	"Steam_AppUpdateError_46": "procedura de creare a eșuat",
	"Steam_AppUpdateError_47": "clientul Steam nu este actualizat",
	"ShareDialog_Title": "Împărtășește",
	"ShareUploadScreenshot_Description": "Upload this screenshot to your Steam Profile and Activity Feed.",
	"ShareUploadScreenshot_AddCaption": "adaugă un mesaj aici",
	"ShareUploadScreenshot_CaptionHeader": "Descriere:",
	"ShareUploadScreenshot_TagSpoiler": "Tag as spoiler",
	"ShareUploadScreenshot_CloudUsage": "Will use %1$s of your remaining %2$s of cloud storage (%3$s total)",
	"ShareUploadScreenshot_Uploading": "Se încarcă pe Steam",
	"ShareUploadScreenshot_PermissionDenied": "Steam nu a putut încărca captura aceasta de ecran. Nu ai voie să încarci conținut deoarece ai o banare activă pe contul tău.",
	"ShareUploadScreenshot_UnexpectedError": "Steam was unable to upload this screenshot to the Steam Cloud. Please try again.",
	"DeleteScreenshot_Title": "Șterge captura de ecran",
	"DeleteScreenshot_Single": "Sigur vrei să ștergi captura aceasta de ecran de pe hard diskul tău?",
	"DeleteScreenshot_Failed": "Steam nu a putut șterge captura de ecran selectată de pe hard diskul tău.",
	"AppDetailsAchievement_Hidden": "Realizare ascunsă",
	"AppDetailsAchievement_HiddenDesc": "Continuă să te joci pentru a descoperi realizarea aceasta.",
	"Demo_SpotlightIntro": "Check out the full game",
	"Demo_VisitStorePage": "Visit Store Page",
	"SteamReviewScore_9": "Overwhelmingly Positive",
	"SteamReviewScore_8": "Very Positive",
	"SteamReviewScore_7": "Positive",
	"SteamReviewScore_6": "Mostly Positive",
	"SteamReviewScore_5": "Mixed",
	"SteamReviewScore_4": "Mostly Negative",
	"SteamReviewScore_3": "Negative",
	"SteamReviewScore_2": "Very Negative",
	"SteamReviewScore_1": "Overwhelmingly Negative"
}
