import "common_base.proto";

message CMsgFactoryResetState {
	optional bool is_running = 1;
	optional int32 progress = 2;
	optional bool is_restart_pending = 3;
	optional fixed32 rtime_estimated_completion = 4;
}

message CSteamOS_GetUserHasPassword_Request {
}

message CSteamOS_GetUserHasPassword_Response {
	optional bool has_password = 1;
}

message CSteamOS_SetUserPassword_Request {
	optional string current_password = 1;
	optional string new_password = 2;
}

message CSteamOS_SetUserPassword_Response {
}

message CSteamOSManager_ApplyMandatoryUpdate_Request {
}

message CSteamOSManager_ApplyMandatoryUpdate_Response {
}

message CSteamOSManager_CECWakeAndSetActive_Request {
}

message CSteamOSManager_CECWakeAndSetActive_Response {
}

message CSteamOSManager_FactoryReset_Request {
	optional bool reset_os = 1;
	optional bool reset_user_data = 2;
}

message CSteamOSManager_FactoryReset_Response {
}

message CSteamOSManager_GetState_Request {
}

message CSteamOSManager_GetState_Response {
	optional .CSteamOSManagerState state = 1;
}

message CSteamOSManager_GetSteamVRPaths_Request {
}

message CSteamOSManager_GetSteamVRPaths_Response {
	optional string active_path = 1;
	optional .CSteamVRPathRecord default_path = 2;
	optional .CSteamVRPathRecord steam_steamvr_main_path = 3;
	optional .CSteamVRPathRecord steam_steamvr_rel_path = 4;
	repeated .CSteamVRPathRecord sideloaded_paths = 5;
}

message CSteamOSManager_OptOutOfSideloadedClient_Request {
}

message CSteamOSManager_OptOutOfSideloadedClient_Response {
}

message CSteamOSManager_PrepareFactoryImageTest_Request {
	optional bool factory_reset = 1;
}

message CSteamOSManager_PrepareFactoryImageTest_Response {
}

message CSteamOSManager_RefreshScreenReaderAutoLocale_Request {
}

message CSteamOSManager_RefreshScreenReaderAutoLocale_Response {
}

message CSteamOSManager_SetDefaultDesktopSession_Request {
	optional string session_name = 1;
}

message CSteamOSManager_SetDefaultDesktopSession_Response {
}

message CSteamOSManager_SetDesktopAsDefaultLoginMode_Request {
	optional bool is_desktop_default = 1;
}

message CSteamOSManager_SetDesktopAsDefaultLoginMode_Response {
}

message CSteamOSManager_SetSteamVRPath_Request {
	optional string path = 1;
}

message CSteamOSManager_SetSteamVRPath_Response {
}

message CSteamOSManager_StateChanged_Notification {
}

message CSteamOSManager_SwitchToDesktop_Request {
}

message CSteamOSManager_SwitchToDesktop_Response {
}

message CSteamOSManagerState {
	optional bool is_service_available = 1;
	optional string os_version = 2;
	optional bool is_mandatory_update_available = 3;
	optional bool is_status_led_control_available = 5;
	optional .CMsgFactoryResetState factory_reset_state = 6;
	optional bool is_tdp_limit_available = 7;
	optional int32 tdp_limit_min = 8;
	optional int32 tdp_limit_max = 9;
	optional bool is_cec_available = 10;
	optional bool is_wifi_debug_supported = 11;
	optional bool is_wifi_debug_force_disabled = 12;
	optional bool is_wifi_force_wpa_supplicant_supported = 13;
	optional bool is_manual_gpu_clock_available = 14;
	optional int32 manual_gpu_clock_min = 15;
	optional int32 manual_gpu_clock_max = 16;
	repeated string platform_performance_profiles_available = 17;
	optional string platform_performance_profile_default = 18;
	optional bool is_charge_limit_available = 20;
	optional int32 charge_limit_min = 21;
	optional int32 charge_limit_max = 22;
	optional int32 charge_limit_default = 23;
	optional bool is_screen_reader_supported = 24;
	repeated string screen_reader_locales_available = 25;
	optional string screen_reader_locale_default = 26;
	optional bool is_system_tracing_available = 27;
	optional bool is_vrs_available = 28;
	optional bool is_wifi_driver_reload_available = 29;
	optional bool is_password_change_supported = 30;
	optional bool is_session_management_supported = 31;
	repeated string desktop_sessions_available = 32;
	optional string desktop_session_default = 33;
	optional bool is_desktop_default_login_mode = 34;
	optional bool is_extended_cec_available = 35;
	optional bool is_extended_cec_wake_device_supported = 36;
	optional bool is_ec_logging_available = 37;
}

message CSteamVRPathRecord {
	optional string path = 1;
	optional string version = 2;
}

service SteamOSManager {
	// ePrivilege=1, eClientExecutionSite=1
	rpc ApplyMandatoryUpdate (.CSteamOSManager_ApplyMandatoryUpdate_Request) returns (.CSteamOSManager_ApplyMandatoryUpdate_Response);
	// ePrivilege=1, eClientExecutionSite=1
	rpc CECWakeAndSetActive (.CSteamOSManager_CECWakeAndSetActive_Request) returns (.CSteamOSManager_CECWakeAndSetActive_Response);
	// ePrivilege=1, eClientExecutionSite=1
	rpc FactoryReset (.CSteamOSManager_FactoryReset_Request) returns (.CSteamOSManager_FactoryReset_Response);
	// ePrivilege=1, eClientExecutionSite=1
	rpc GetState (.CSteamOSManager_GetState_Request) returns (.CSteamOSManager_GetState_Response);
	// ePrivilege=1, eClientExecutionSite=1
	rpc GetSteamVRPaths (.CSteamOSManager_GetSteamVRPaths_Request) returns (.CSteamOSManager_GetSteamVRPaths_Response);
	// ePrivilege=1, eClientExecutionSite=1
	rpc GetUserHasPassword (.CSteamOS_GetUserHasPassword_Request) returns (.CSteamOS_GetUserHasPassword_Response);
	// ePrivilege=1, eClientExecutionSite=1
	rpc NotifyStateChanged (.CSteamOSManager_StateChanged_Notification) returns (.NoResponse);
	// ePrivilege=1, eClientExecutionSite=1
	rpc OptOutOfSideloadedClient (.CSteamOSManager_OptOutOfSideloadedClient_Request) returns (.CSteamOSManager_OptOutOfSideloadedClient_Response);
	// ePrivilege=1, eClientExecutionSite=1
	rpc PrepareFactoryImageTest (.CSteamOSManager_PrepareFactoryImageTest_Request) returns (.CSteamOSManager_PrepareFactoryImageTest_Response);
	// ePrivilege=1, eClientExecutionSite=1
	rpc RefreshScreenReaderAutoLocale (.CSteamOSManager_RefreshScreenReaderAutoLocale_Request) returns (.CSteamOSManager_RefreshScreenReaderAutoLocale_Response);
	// ePrivilege=1, eClientExecutionSite=1
	rpc SetDefaultDesktopSession (.CSteamOSManager_SetDefaultDesktopSession_Request) returns (.CSteamOSManager_SetDefaultDesktopSession_Response);
	// ePrivilege=1, eClientExecutionSite=1
	rpc SetDesktopAsDefaultLoginMode (.CSteamOSManager_SetDesktopAsDefaultLoginMode_Request) returns (.CSteamOSManager_SetDesktopAsDefaultLoginMode_Response);
	// ePrivilege=1, eClientExecutionSite=1
	rpc SetSteamVRPath (.CSteamOSManager_SetSteamVRPath_Request) returns (.CSteamOSManager_SetSteamVRPath_Response);
	// ePrivilege=1, eClientExecutionSite=1
	rpc SetUserPassword (.CSteamOS_SetUserPassword_Request) returns (.CSteamOS_SetUserPassword_Response);
	// ePrivilege=1, eClientExecutionSite=1
	rpc SwitchToDesktop (.CSteamOSManager_SwitchToDesktop_Request) returns (.CSteamOSManager_SwitchToDesktop_Response);
}

