import "common_base.proto";

message CScreensaver_ActiveStateChanged_Notification {
	optional bool active = 1;
}

message CScreensaver_ForceScreensaver_Request {
	optional bool enabled = 1;
}

message CScreensaver_ForceScreensaver_Response {
}

message CScreensaver_GetActiveState_Request {
}

message CScreensaver_GetActiveState_Response {
	optional bool active = 1;
}

message CScreensaver_GetLocalScreensavers_Request {
}

message CScreensaver_GetLocalScreensavers_Response {
	repeated .CScreensaver_GetLocalScreensavers_Response_Screensaver screensavers = 1;
}

message CScreensaver_GetLocalScreensavers_Response_Screensaver {
	optional string id = 1;
	optional string path = 2;
}

service Screensaver {
	// ePrivilege=1, eClientExecutionSite=1
	rpc ForceScreensaver (.CScreensaver_ForceScreensaver_Request) returns (.CScreensaver_ForceScreensaver_Response);
	// ePrivilege=1, eClientExecutionSite=1
	rpc GetActiveState (.CScreensaver_GetActiveState_Request) returns (.CScreensaver_GetActiveState_Response);
	// ePrivilege=1, eClientExecutionSite=1
	rpc GetLocalScreensavers (.CScreensaver_GetLocalScreensavers_Request) returns (.CScreensaver_GetLocalScreensavers_Response);
	// ePrivilege=1, eClientExecutionSite=1
	rpc NotifyActiveStateChanged (.CScreensaver_ActiveStateChanged_Notification) returns (.NoResponse);
}

