typedef enum EStoreCategory
{
    k_EStoreCategoryCategory_1 = 1, // category_1
    k_EStoreCategoryCategory_2, // category_2
    k_EStoreCategoryCategory_6 = 6, // category_6
    k_EStoreCategoryCategory_7, // category_7
    k_EStoreCategoryCategory_8, // category_8
    k_EStoreCategoryCategory_9, // category_9
    k_EStoreCategoryCategory_10, // category_10
    k_EStoreCategoryCategory_11, // category_11
    k_EStoreCategoryCategory_12, // category_12
    k_EStoreCategoryCategory_13, // category_13
    k_EStoreCategoryCategory_14, // category_14
    k_EStoreCategoryCategory_15, // category_15
    k_EStoreCategoryCategory_16, // category_16
    k_EStoreCategoryCategory_17, // category_17
    k_EStoreCategoryCategory_18, // category_18
    k_EStoreCategoryCategory_19, // category_19
    k_EStoreCategoryCategory_20, // category_20
    k_EStoreCategoryCategory_21, // category_21
    k_EStoreCategoryCategory_22, // category_22
    k_EStoreCategoryCategory_23, // category_23
    k_EStoreCategoryCategory_24, // category_24
    k_EStoreCategoryCategory_25, // category_25
    k_EStoreCategoryCategory_26, // category_26
    k_EStoreCategoryCategory_27, // category_27
    k_EStoreCategoryCategory_28, // category_28
    k_EStoreCategoryCategory_29, // category_29
    k_EStoreCategoryCategory_30, // category_30
    k_EStoreCategoryCategory_31, // category_31
    k_EStoreCategoryCategory_32, // category_32
    k_EStoreCategoryCategory_33, // category_33
    k_EStoreCategoryCategory_34, // category_34
    k_EStoreCategoryCategory_35, // category_35
    k_EStoreCategoryCategory_36, // category_36
    k_EStoreCategoryCategory_37, // category_37
    k_EStoreCategoryCategory_38, // category_38
    k_EStoreCategoryCategory_39, // category_39
    k_EStoreCategoryCategory_40, // category_40
    k_EStoreCategoryCategory_41, // category_41
    k_EStoreCategoryCategory_42, // category_42
    k_EStoreCategoryCategory_43, // category_43
    k_EStoreCategoryCategory_44, // category_44
    k_EStoreCategoryCategory_45, // category_45
    k_EStoreCategoryCategory_46, // category_46
    k_EStoreCategoryCategory_47, // category_47
    k_EStoreCategoryCategory_48, // category_48
    k_EStoreCategoryCategory_49, // category_49
    k_EStoreCategoryCategory_50, // category_50
    k_EStoreCategoryCategory_51, // category_51
} EStoreCategory;
