var _ = `english`,
  _ = `Originally posted by %1$s:`,
  _ = `{LINK REMOVED}`,
  _ = `The URL that was linked here has been removed by our filters.  Usually this is done to prevent phishing and malware attacks.`,
  _ = `(Valve/Mod Only) Click to reveal link`,
  _ = `%1$s Comments`,
  _ = `Showing %1$s-%2$s of %3$s comments`,
  _ = `Add a comment`,
  _ = `Post Comment`,
  _ = `Formatting help`,
  _ = `Insert emoticon`,
  _ = `%1$s Emoticon`,
  _ = `Search`,
  _ = `Recently used`,
  _ = `All emoticons`,
  _ = `No emoticons match your search.`,
  _ = `You do not own any emoticons yet.`,
  _ = `Text Formatting`,
  _ = `These markup tags allow you to add formatting to the text of your comments and posts, similar to HTML.`,
  _ = `Syntax`,
  _ = `Example`,
  _ = `Bold text`,
  _ = `Underlined text`,
  _ = `Italic text`,
  _ = `Strikethrough text`,
  _ = `Spoiler text`,
  _ = `Doesn't parse [b]tags[/b] `,
  _ = `Website link`,
  _ = `Quoted text`,
  _ = `Fixed-width font,
preserves    spaces`,
  _ = `Header text`,
  _ = `Header text`,
  _ = `Header text`,
  _ = `Bulleted list`,
  _ = `Ordered list`,
  _ = `Subscribe to thread`,
  _ = `Unsubscribe from thread`,
  _ = `Subscribe to a thread to receive a comment notification whenever someone posts a new comment.`,
  _ = `You were automatically subscribed to this comment thread because it is associated with your Steam profile.`,
  _ = `There was a problem updating your subscription.  Please try again later.`,
  _ = `Delete`,
  _ = `Hide and report this comment`,
  _ = `Mark Suspicious`,
  _ = `Clear Bannable Content Flag: %1$s`,
  _ = `Not Scanned`,
  _ = `Reset`,
  _ = `Needs Checking`,
  _ = `Very Unlikely`,
  _ = `Unlikely`,
  _ = `Possible`,
  _ = `Likely`,
  _ = `Very Likely`,
  _ = `Unknown( %1$s )`,
  _ = `Open In Moderation Tool`,
  _ = `You've reported this comment`,
  _ = `You've blocked this player`,
  _ = `Undo`,
  _ = `view this comment`,
  _ = `Your support/moderator permissions allow you to see it.`,
  _ = `This comment is awaiting analysis by our automated content check system. It will be temporarily hidden until we verify that it does not contain harmful content (e.g. links to websites that attempt to steal information).`,
  _ = `This comment has been automatically flagged for containing potentially harmful content and has been hidden as a result.`,
  _ = `You wouldn't normally be allowed to post a comment here, but you have additional privileges that allow you to.`,
  _ = `This comment was deleted.`,
  _ = `Your comment is too short.`,
  _ = `Your comment is too long. The maximum length is %1$s characters.`,
  _ = `You are not allowed to post a comment here.`,
  _ = `You must be logged in to post a comment.`,
  _ = `You must own this game to comment on this item.`,
  _ = `You need at least one hour of playtime before you can post a comment.`,
  _ = `Comments are disabled for this item.`,
  _ = `There are no comments yet.`,
  _ = {
    language: _,
    CommentThread_QuoteBlock_Author: _,
    CommentThread_RemovedLink: _,
    CommentThread_RemovedLink_Tooltip: _,
    CommentThread_RemovedLink_Reveal: _,
    CommentThread_NumberOfComments: _,
    CommentThread_ShowingXToYOfTotal: _,
    CommentThread_AddAComment: _,
    CommentThread_PostComment: _,
    CommentThread_FormattingHelp: _,
    CommentThread_InsertEmoticon: _,
    CommentThread_EmoticonHoverApp: _,
    CommentThread_EmoticonSearch: _,
    CommentThread_EmoticonRecentlyUsed: _,
    CommentThread_EmoticonAll: _,
    CommentThread_EmoticonNoResults: _,
    CommentThread_EmoticonNoneOwned: _,
    CommentThread_FormattingHelpHeader: _,
    Discussions_FormattingHelp_Description: _,
    Discussions_FormattingHelp_ColumnSyntax: _,
    Discussions_FormattingHelp_ColumnExample: _,
    Discussions_FormattingHelp_Bold: _,
    Discussions_FormattingHelp_Underline: _,
    Discussions_FormattingHelp_Italic: _,
    Discussions_FormattingHelp_Strike: _,
    Discussions_FormattingHelp_Spoiler: _,
    Discussions_FormattingHelp_Noparse: _,
    Discussions_FormattingHelp_Link: _,
    Discussions_FormattingHelp_Quote: _,
    Discussions_FormattingHelp_Code: _,
    Discussions_FormattingHelp_H1: _,
    Discussions_FormattingHelp_H2: _,
    Discussions_FormattingHelp_H3: _,
    Discussions_FormattingHelp_List: _,
    Discussions_FormattingHelp_OList: _,
    CommentThread_Subscribe: _,
    CommentThread_Unsubscribe: _,
    CommentThread_SubscribeHint: _,
    CommentThread_SubscribeHintOwnThread: _,
    CommentThread_SubscribeError: _,
    CommentThread_DeleteComment: _,
    CommentThread_HideComment: _,
    CommentThread_MarkSpam: _,
    CommentThread_ClearContentCheck: _,
    BanContentCheckResult_NotScanned: _,
    BanContentCheckResult_Reset: _,
    BanContentCheckResult_NeedsChecking: _,
    BanContentCheckResult_VeryUnlikely: _,
    BanContentCheckResult_Unlikely: _,
    BanContentCheckResult_Possible: _,
    BanContentCheckResult_Likely: _,
    BanContentCheckResult_VeryLikely: _,
    BanContentCheckResult_Unknown: _,
    CommentThread_ModerationTool: _,
    CommentThread_HiddenByUser: _,
    CommentThread_HiddenByBlocked: _,
    CommentThread_HiddenUndo: _,
    CommentThread_HiddenViewComment: _,
    CommentThread_ModeratorViewContent: _,
    CommentThread_NeedsContentCheck: _,
    CommentThread_FailedContentCheck: _,
    CommentThread_PermissionOverride: _,
    CommentThread_Deleted: _,
    CommentThread_PostError_TooShort: _,
    CommentThread_PostError_TooLong: _,
    CommentThread_PostError_NotAllowed: _,
    CommentThread_PostError_NotLoggedIn: _,
    CommentThread_PostError_MustOwnApp: _,
    CommentThread_PostError_LimitedUser: _,
    CommentThread_CommentsDisabled: _,
    CommentThread_NoComments: _,
  };
export {
  _ as BanContentCheckResult_Likely,
  _ as BanContentCheckResult_NeedsChecking,
  _ as BanContentCheckResult_NotScanned,
  _ as BanContentCheckResult_Possible,
  _ as BanContentCheckResult_Reset,
  _ as BanContentCheckResult_Unknown,
  _ as BanContentCheckResult_Unlikely,
  _ as BanContentCheckResult_VeryLikely,
  _ as BanContentCheckResult_VeryUnlikely,
  _ as CommentThread_AddAComment,
  _ as CommentThread_ClearContentCheck,
  _ as CommentThread_CommentsDisabled,
  _ as CommentThread_DeleteComment,
  _ as CommentThread_Deleted,
  _ as CommentThread_EmoticonAll,
  _ as CommentThread_EmoticonHoverApp,
  _ as CommentThread_EmoticonNoResults,
  _ as CommentThread_EmoticonNoneOwned,
  _ as CommentThread_EmoticonRecentlyUsed,
  _ as CommentThread_EmoticonSearch,
  _ as CommentThread_FailedContentCheck,
  _ as CommentThread_FormattingHelp,
  _ as CommentThread_FormattingHelpHeader,
  _ as CommentThread_HiddenByBlocked,
  _ as CommentThread_HiddenByUser,
  _ as CommentThread_HiddenUndo,
  _ as CommentThread_HiddenViewComment,
  _ as CommentThread_HideComment,
  _ as CommentThread_InsertEmoticon,
  _ as CommentThread_MarkSpam,
  _ as CommentThread_ModerationTool,
  _ as CommentThread_ModeratorViewContent,
  _ as CommentThread_NeedsContentCheck,
  _ as CommentThread_NoComments,
  _ as CommentThread_NumberOfComments,
  _ as CommentThread_PermissionOverride,
  _ as CommentThread_PostComment,
  _ as CommentThread_PostError_LimitedUser,
  _ as CommentThread_PostError_MustOwnApp,
  _ as CommentThread_PostError_NotAllowed,
  _ as CommentThread_PostError_NotLoggedIn,
  _ as CommentThread_PostError_TooLong,
  _ as CommentThread_PostError_TooShort,
  _ as CommentThread_QuoteBlock_Author,
  _ as CommentThread_RemovedLink,
  _ as CommentThread_RemovedLink_Reveal,
  _ as CommentThread_RemovedLink_Tooltip,
  _ as CommentThread_ShowingXToYOfTotal,
  _ as CommentThread_Subscribe,
  _ as CommentThread_SubscribeError,
  _ as CommentThread_SubscribeHint,
  _ as CommentThread_SubscribeHintOwnThread,
  _ as CommentThread_Unsubscribe,
  _ as Discussions_FormattingHelp_Bold,
  _ as Discussions_FormattingHelp_Code,
  _ as Discussions_FormattingHelp_ColumnExample,
  _ as Discussions_FormattingHelp_ColumnSyntax,
  _ as Discussions_FormattingHelp_Description,
  _ as Discussions_FormattingHelp_H1,
  _ as Discussions_FormattingHelp_H2,
  _ as Discussions_FormattingHelp_H3,
  _ as Discussions_FormattingHelp_Italic,
  _ as Discussions_FormattingHelp_Link,
  _ as Discussions_FormattingHelp_List,
  _ as Discussions_FormattingHelp_Noparse,
  _ as Discussions_FormattingHelp_OList,
  _ as Discussions_FormattingHelp_Quote,
  _ as Discussions_FormattingHelp_Spoiler,
  _ as Discussions_FormattingHelp_Strike,
  _ as Discussions_FormattingHelp_Underline,
  _ as default,
  _ as language,
};
