var _ = `french`,
  _ = `Voir sur le marché de la communauté`,
  _ = `Voir mon offre`,
  _ = `À partir de\xA0: %1$s`,
  _ = `%1$s vendu(s) au cours des dernières 24\xA0heures`,
  _ = `Vendre`,
  _ = `Tags\xA0:`,
  _ = `Protégé contre les échanges`,
  _ = `Les items protégés contre les échanges ne peuvent pas être modifiés, consommés ou transférés.`,
  _ = `%1$s\xA0: %2$s`,
  _ = `Sur le marché`,
  _ = `Tant que cet article est en vente sur le marché, vous ne pouvez ni le modifier ni le consommer.`,
  _ = `Cet item vaut\xA0: %1$s`,
  _ = `%1$s gemmes`,
  _ = `Transformer en gemmes...`,
  _ = `Cet item peut être transformé en gemmes à utiliser pour créer des booster packs. <1>Plus d'informations ici</1>.`,
  _ = `Accessoires`,
  _ = {
    language: _,
    SellOnMarket_View: _,
    SellOnMarket_ViewListing: _,
    SellOnMarket_LowestPrice: _,
    SellOnMarket_Volume: _,
    SellOnMarket_SellThisItem: _,
    ItemDescription_Tags: _,
    ItemDescription_TradeProtected: _,
    ItemDescription_TradeProtectedTooltip: _,
    ItemDescription_AssetPropertyLabelColonValue: _,
    ItemDescription_ListedItem: _,
    ItemDescription_ListedItemTooltip: _,
    ItemDescription_ThisItemIsWorthGems: _,
    ItemDescription_XGems: _,
    ItemDescription_TurnIntoGemsButton: _,
    ItemDescription_GemDescription: _,
    ItemDescription_AccessoriesList_Title: _,
  };
export {
  _ as ItemDescription_AccessoriesList_Title,
  _ as ItemDescription_AssetPropertyLabelColonValue,
  _ as ItemDescription_GemDescription,
  _ as ItemDescription_ListedItem,
  _ as ItemDescription_ListedItemTooltip,
  _ as ItemDescription_Tags,
  _ as ItemDescription_ThisItemIsWorthGems,
  _ as ItemDescription_TradeProtected,
  _ as ItemDescription_TradeProtectedTooltip,
  _ as ItemDescription_TurnIntoGemsButton,
  _ as ItemDescription_XGems,
  _ as SellOnMarket_LowestPrice,
  _ as SellOnMarket_SellThisItem,
  _ as SellOnMarket_View,
  _ as SellOnMarket_ViewListing,
  _ as SellOnMarket_Volume,
  _ as default,
  _ as language,
};
