var _ = `Cari Pasaran Komuniti`,
  _ = `Tetapkan Semula Penapis`,
  _ = `Cari`,
  _ = `Pilih permainan...`,
  _ = `Permainan yang anda mainkan baru-baru ini dengan item`,
  _ = `Permainan popular dengan item`,
  _ = `Kosongkan pilihan`,
  _ = `Cari...`,
  _ = `Cari di %1$s...`,
  _ = `Item Dalam Permainan`,
  _ = `Item Steam`,
  _ = `Jenis Item`,
  _ = `Permainan ini tidak mempunyai penapis Pasaran.`,
  _ = `Klik "Cari" untuk melihat item yang tersedia.`,
  _ = `Ralat telah berlaku semasa memuatkan penapis untuk permainan ini.`,
  _ = `Harga`,
  _ = `Harga Minimum`,
  _ = `Harga Maksimum`,
  _ = `Semua`,
  _ = `Lain-lain`,
  _ = `Tapis...`,
  _ = `Tapis mengikut permainan...`,
  _ = `Ciri Beta - Berikan maklum balas`,
  _ = `Cari di seluruh nama item Pasaran...`,
  _ = `Kotak Senjata, Kapsul Pelekat, Pakej Cenderahati, dll`,
  _ = `Pasaran Komuniti Steam`,
  _ = `Beli dan jual barang dengan ahli komuniti untuk Dana Dompet Steam`,
  _ = `Ketahui Lebih Lanjut`,
  _ = `Cari di Pasaran`,
  _ = `Carian baharu...`,
  _ = `Penapis`,
  _ = `Keluar dari Pasaran Beta`,
  _ = `Beri Maklum Balas`,
  _ = `Item ini ialah komoditi, iaitu semua item individu pada dasarnya adalah sama. Penyenaraian individu tidak boleh diakses. Sebaliknya, anda boleh membuat pesanan untuk membeli pada harga tertentu dan penyenaraian termurah akan dipadankan secara automatik dengan pesanan pembelian tertinggi.`,
  _ = `%1$s hasil ditemui`,
  _ = `%1$s hasil ditemui`,
  _ = `%1$s hasil ditemui untuk:`,
  _ = `%1$s hasil ditemui untuk:`,
  _ = `Hasil untuk:`,
  _ = `%2$s penyenaraian ditemui`,
  _ = `%2$s penyenaraian ditemui`,
  _ = `Populariti`,
  _ = `Nama (A hingga Z)`,
  _ = `Nama (Z hingga A)`,
  _ = `Harga (rendah ke tinggi)`,
  _ = `Harga (tinggi ke rendah)`,
  _ = `Kuantiti (rendah ke tinggi)`,
  _ = `Kuantiti (tinggi hingga rendah)`,
  _ = `%1$s (rendah ke tinggi)`,
  _ = `%1$s (tinggi ke rendah)`,
  _ = `Susun Mengikut:`,
  _ = `Cari`,
  _ = `Cari...`,
  _ = `Beli`,
  _ = `Jual`,
  _ = `Beli Sekarang`,
  _ = `Buat pesanan pembelian...`,
  _ = `Buat pesanan:`,
  _ = `Tutup`,
  _ = `Kuantiti untuk jualan: %1$s`,
  _ = `Kuantiti: %1$s`,
  _ = `Daripada %1$s`,
  _ = `%1$s dilampirkan`,
  _ = `Tapis Keputusan...`,
  _ = `Carian Lanjutan`,
  _ = `Carian Lanjutan`,
  _ = `Cari item...`,
  _ = `Pasaran Utama`,
  _ = `Permainan Popular`,
  _ = `Sertakan penerangan dalam carian`,
  _ = `Sesetengah item lama menggunakan penerangan teks untuk sifat item yang penting dan tidak boleh diakses dengan penapis di bawah. Pilihan ini membolehkan teks carian anda dipadankan dengan teks penerangan penuh, bukan hanya nama item.`,
  _ = `Penapis`,
  _ = `Tetapkan Semula Carian`,
  _ = `Masukkan teks penapis tersuai...`,
  _ = `Selepas pembelian, item ini:`,
  _ = `tidak boleh ditukar selama satu hari`,
  _ = `tidak boleh ditukar selama satu minggu`,
  _ = `tidak boleh ditukar selama %1$s hari`,
  _ = `tidak boleh ditukar`,
  _ = `tidak boleh disenaraikan di Pasaran Komuniti Steam selama satu hari`,
  _ = `tidak boleh disenaraikan di Pasaran Komuniti Steam selama satu minggu`,
  _ = `tidak boleh disenaraikan di Pasaran Komuniti Steam selama %1$s hari`,
  _ = `boleh terus dijual semula di Pasaran Komuniti Steam`,
  _ = `%1$s: %2$s - %3$s`,
  _ = `%1$s: "%2$s"`,
  _ = `Beli item`,
  _ = `Nama`,
  _ = `Harga`,
  _ = `Jumlah kecil:`,
  _ = `Yuran %1$s (%2$s%):`,
  _ = `Yuran permainan (%1$s%):`,
  _ = `Yuran transaksi Steam (%1$s%):`,
  _ = `Cukai jualan tempatan (%1$s):`,
  _ = `Jumlah:`,
  _ = `Kaedah pembayaran:`,
  _ = `Dompet Steam Saya`,
  _ = `Akaun Steam:`,
  _ = `Alamat bil:`,
  _ = `Nama pertama`,
  _ = `Nama keluarga`,
  _ = `Alamat pengebilan`,
  _ = `Alamat pengebilan, baris 2`,
  _ = `Bandar`,
  _ = `Negeri / Wilayah`,
  _ = `Poskod`,
  _ = `Negara`,
  _ = `Simpan alamat saya supaya pembelian lebih mudah pada masa depan`,
  _ = `Tambah Dana`,
  _ = `Pembelian`,
  _ = `Saya bersetuju dengan terma %1$s (kemas kini terakhir pada %2$s)`,
  _ = `Perjanjian Pelanggan Steam`,
  _ = `Anda mesti bersetuju dengan terma Perjanjian Pelanggan Steam untuk melengkapkan transaksi ini.`,
  _ = `Dengan mengklik "Beli", anda bersetuju untuk diberikan akses segera kepada kandungan digital ini. Oleh itu, anda tidak berhak untuk menarik diri daripada pembelian ini lagi – pembelian adalah muktamad.`,
  _ = `Masalah telah berlaku semasa membeli item anda. Penyenaraian mungkin telah dialih keluar. Segarkan semula halaman dan cuba lagi.`,
  _ = `Masalah telah berlaku semasa membeli item anda. Masalah telah berlaku semasa menunggu anda mengesahkan tindakan ini. Segarkan semula halaman dan cuba lagi.`,
  _ = `Medan berikut diperlukan:`,
  _ = `Sila masukkan alamat ketenteraan yang sah`,
  _ = `Sila masukkan poskod yang sah`,
  _ = `Tahniah atas pembelian anda! Anda boleh melihat item baharu anda dalam <1>inventori anda</1>.`,
  _ = `Lihat Inventori`,
  _ = `Pengesahan tambahan diperlukan`,
  _ = `Menunggu anda mengesahkan pembelian ini...`,
  _ = `Beberapa pembelian memerlukan keselamatan tambahan melalui aplikasi Steam Mobile anda.`,
  _ = `Beberapa pembelian memerlukan keselamatan tambahan melalui e-mel Pengawal Steam anda.`,
  _ = `Beberapa pembelian memerlukan keselamatan tambahan melalui aplikasi Steam Mobile atau e-mel anda`,
  _ = `Sahkan melalui apl Steam Mobile untuk melengkapkan pembelian anda...`,
  _ = `Sahkan melalui e-mel untuk melengkapkan pembelian anda...`,
  _ = `Sahkan melalui Steam Mobile App atau e-mel untuk melengkapkan pembelian anda...`,
  _ = `Pembelian berjaya diselesaikan`,
  _ = `Tutup`,
  _ = `Lihat Inventori`,
  _ = `Simpan alamat saya supaya pembelian lebih cepat pada masa depan`,
  _ = `Penyenaraian ini tidak lagi tersedia`,
  _ = `Tidak Tersedia`,
  _ = `Penyenaraian ini sudah tidak tersedia untuk pembelian.`,
  _ = `(My Listing)`,
  _ = `Beli - %1$s`,
  _ = `Buat Pesanan Pembelian`,
  _ = `Apakah jenis item yang anda ingin beli?`,
  _ = `Pilih item...`,
  _ = `Berapakah harga yang anda ingin bayar:`,
  _ = `(setiap item)`,
  _ = `Berapakah jumlah yang anda ingin beli:`,
  _ = `Harga maksimum %1$s:`,
  _ = `This is the most you can end up spending as a result of this buy order. Items will be purchased at the cheapest price available, so the order may end up costing less than this amount.`,
  _ = `Mencari penyenaraian item yang sepadan pada harga pilihan anda...`,
  _ = `Purchase succeeded! Your item is now in your inventory, and your receipt has been emailed to you.`,
  _ = `Success! Your buy order has been placed.`,
  _ = `Anda akan dimaklumkan secara automatik melalui e-mel apabila pembelian selesai. Anda boleh membatalkan pesanan pembelian ini dari bahagian atas halaman ini, atau dari halaman utama pasaran.`,
  _ = `Maaf! Kami menghadapi masalah mendapatkan respons daripada pelayan Steam berhubung pesanan anda. Sila semak jika pesanan anda telah berjaya dibuat atau dipenuhi. Jika belum, sila cuba lagi nanti.`,
  _ = `Harga minimum seunit ialah %1$s`,
  _ = `%1$s atau kurang`,
  _ = `%1$s atau lebih`,
  _ = `Harga`,
  _ = `Kuantiti`,
  _ = `%1$s untuk dijual bermula dari %2$s`,
  _ = `Tiada penyenaraian aktif untuk item ini`,
  _ = `%1$s permintaan untuk membeli pada %2$s atau lebih rendah`,
  _ = `Tiada pesanan pembelian aktif untuk item ini.`,
  _ = `Pilih tab di atas untuk melihat maklumat pesanan pembelian`,
  _ = `Tidak nampak barang atau harga yang anda mahukan?`,
  _ = `Tidak nampak harga yang anda suka?`,
  _ = `Pesanan Pembelian dan Penjualan (kumulatif)`,
  _ = `1 buy order at %2$s or higher`,
  _ = `%1$s buy orders at %2$s or higher`,
  _ = `1 sell order at %2$s or lower`,
  _ = `%1$s pesanan penjualan pada %2$s atau lebih rendah`,
  _ = `1 request to buy at <1>%2$s</1>`,
  _ = `%3$s permintaan untuk membeli pada harga <1>%2$s atau lebih rendah</1>`,
  _ = `Harga Jualan Median`,
  _ = `Minggu`,
  _ = `Bulan`,
  _ = `Tahun`,
  _ = `Seumur Hidup`,
  _ = `%1$s dijual`,
  _ = `Harga`,
  _ = `Volum`,
  _ = `Tiada data untuk julat masa ini`,
  _ = `Tiada data pembelian`,
  _ = `T/B`,
  _ = `NAMA`,
  _ = `HARGA`,
  _ = `KUANTITI`,
  _ = `DISENARAIKAN PADA`,
  _ = `Batal`,
  _ = `Alih Keluar`,
  _ = `Pesanan Aktif Saya`,
  _ = `Pesanan Penjualan`,
  _ = `Pesanan Pembelian`,
  _ = `Membeli - Tawaran Saya`,
  _ = `Menjual - Penyenaraian Saya`,
  _ = `Masalah telah berlaku semasa memuat data pesanan untuk item ini.`,
  _ = `Anda tiada pesanan aktif untuk item ini.`,
  _ = `Anda tiada pesanan pembelian aktif untuk item ini.`,
  _ = `Anda tidak menjual sebarang item ini. Jual item daripada inventori anda atau klik butang "Jual" di halaman ini.`,
  _ = `Kuantiti: %1$s`,
  _ = `Lihat semua %1$s`,
  _ = `Masalah telah berlaku semasa membatalkan pesanan anda. Sila cuba lagi nanti.`,
  _ = `Masalah telah berlaku semasa mengalih keluar penyenaraian anda. Sila cuba lagi nanti.`,
  _ = `Alih keluar penyenaraian`,
  _ = `Adakah anda ingin mengalih keluar penyenaraian untuk %1$s dan mengembalikan item tersebut ke inventori anda?`,
  _ = `Adakah anda ingin mengalih keluar penyenaraian ini dan mengembalikan item tersebut ke inventori anda?`,
  _ = `Ya, alih keluar penyenaraian ini`,
  _ = `Tidak`,
  _ = `Penyenaraian anda telah berjaya dialih keluar`,
  _ = `Pilih item daripada inventori anda`,
  _ = `Apakah pesanan pembelian?`,
  _ = `Tetapkan harga pilihan anda dan pembelian akan dibuat secara automatik apabila item tersedia pada harga tersebut.`,
  _ = `Steam akan memastikan anda mendapat harga terbaik yang tersedia.`,
  _ = `Untuk item ini, pesanan pembelian akan dipadankan dengan pilihan termurah untuk dibeli, tanpa mengambil kira sebarang ciri unik.`,
  _ = `%1$s dan ke atas`,
  _ = `Maaf!`,
  _ = `Ralat telah berlaku semasa memproses permintaan anda:`,
  _ = `Anda telah membuat terlalu banyak permintaan. Sila tunggu sebentar dan cuba permintaan anda semula nanti.`,
  _ = `Kandungan yang Mungkin:`,
  _ = `Masalah telah berlaku semasa memuatkan kandungan ini`,
  _ = `Item yang diminta mungkin tidak wujud, atau mungkin terdapat isu sementara yang menghalang item daripada dimuatkan. Sila cuba lagi nanti.`,
  _ = `Tapis Penyenaraian`,
  _ = `Tiada Penyenaraian Ditemui`,
  _ = `Pilihan lain...`,
  _ = `Tapis...`,
  _ = `Maklumat`,
  _ = `Graf jualan`,
  _ = `Pesanan Pembelian`,
  _ = `Penapis`,
  _ = `Min`,
  _ = `Maks`,
  _ = `Aksesori`,
  _ = `Any`,
  _ = `None`,
  _ = `%1$s: %2$s`,
  _ = `Anda tidak boleh membeli item ini kerana pembelian dan penjualan jenis item ini dilumpuhkan di negara anda.`,
  _ = `Anda tidak boleh membeli item ini kerana pembelian item jenis ini dilumpuhkan di negara anda.`,
  _ = `Penyenaraian ini belum mempunyai imej unik atau dipertingkatkan. Imej yang ditunjukkan di sini mungkin sedikit berbeza daripada item yang disenaraikan.`,
  _ = `Tunjuk latar belakang`,
  _ = `Kesilapan telah berlaku semasa cuba memaparkan penyenaraian ini`,
  _ = `Anda tidak dapat membeli atau menjual item di Pasaran atas sebab berikut:`,
  _ = `Anda tidak dapat membeli atau menjual item di Pasaran atas sebab berikut:`,
  _ = `Lihat Keputusan`,
  _ = `Lihat sebagai grid`,
  _ = `Lihat sebagai senarai`,
  _ = `There was a problem loading results. Please try again later.`,
  _ = `Masalah telah berlaku semasa memuatkan keputusan tambahan. Sila cuba lagi nanti.`,
  _ = `Anda sedang cuba melihat item untuk permainan baharu di Steam yang anda belum pernah mainkan lagi. Hati-hati dengan item ini.`,
  _ = `Klik di sini untuk tetap melihat item ini`,
  _ = `Tapis mengikut permainan`,
  _ = `Lihat semua permainan`,
  _ = `Akaun anda kini dikunci.`,
  _ = `Maklumat tentang penguncian ini boleh didapati dengan mengklik bar merah yang ditunjukkan di penjuru kanan sebelah atas semasa log masuk ke Steam Client. Untuk maklumat tambahan, sila hubungi Sokongan Steam.`,
  _ = `Akaun anda kini dikunci. Maklumat tentang penguncian ini boleh didapati dengan mengklik bar merah yang ditunjukkan di penjuru kanan sebelah atas semasa log masuk ke Steam Client.`,
  _ = `Untuk mengalih keluar sekatan ini...`,
  _ = `Akaun anda kini dilarang untuk membuat pertukaran.`,
  _ = `Akaun ini tidak boleh menggunakan Pasaran Komuniti Steam buat masa ini.`,
  _ = `Tempoh larangan pertukaran boleh berbeza-beza daripada sementara hingga kekal. Untuk melihat bila larangan pertukaran ini luput, sila klik bar merah yang ditunjukkan di penjuru kanan sebelah atas semasa log masuk ke Steam Client.`,
  _ = `Akaun anda telah dilarang daripada membuat pertukaran. Untuk melihat bila larangan pertukaran ini luput, sila klik bar merah yang ditunjukkan di penjuru kanan sebelah atas semasa log masuk ke Steam Client.`,
  _ = `Maklumat lanjut...`,
  _ = `Anda mesti mempunyai pembelian Steam yang sah yang dalam tempoh antara %1$s hari dan setahun tanpa sebarang caj balik atau pertikaian pembayaran baru-baru ini.`,
  _ = `Sila buat pembelian di Steam Store. Kredit dompet, permainan dan DLC ialah pembelian yang sah. Tetapi, CD key dan hadiah tidak dikira. Sokongan Steam tidak dapat mengalih keluar sekatan ini.`,
  _ = `Anda mesti mempunyai pembelian Steam yang dibuat antara tempoh %1$s hari hingga setahun tanpa sebarang caj balik atau pertikaian pembayaran yang terkini Sokongan Steam tidak boleh mengalih keluar sekatan ini.`,
  _ = `Nampaknya anda telah membuat pembelian yang sah di Steam Store, tetapi pembelian tersebut belum lebih daripada %1$s hari lagi.`,
  _ = `Kami memerlukan pembelian Steam yang dibuat dalam tempoh antara %1$s hari dan setahun, tanpa caj balik atau pertikaian pembayaran terkini. Nampaknya anda telah membuat pembelian, tetapi masih belum melebihi %1$s hari lagi. Sokongan Steam tidak dapat mengalih keluar sekatan ini.`,
  _ = `Kata laluan akaun anda baru-baru ini telah ditetapkan semula.`,
  _ = `Sekatan ini akan dialih keluar secara automatik %1$s hari selepas penetapan semula kata laluan terakhir akaun ini. Jika akaun tidak digunakan untuk jangka masa yang lama, sekatan ini mungkin berlarutan sehingga %2$s hari. Hanya proses tetapan semula kata laluan yang mengenakan sekatan ini. Menukar kata laluan akaun sahaja tidak akan dikenakan sebarang sekatan. Sokongan Steam tidak boleh mengalih keluar sebarang sekatan.`,
  _ = `Kata laluan akaun Steam anda telah ditetapkan semula baru-baru ini. Bagi membantu melindungi pengguna yang akaun e-mel atau akaun lain mereka mungkin telah terjejas, akses kepada Pasaran Komuniti dihadkan selama %1$s hari selepas penetapan semula kata laluan.`,
  _ = `Anda baru sahaja menambah dana ke dalam Dompet Steam menggunakan kad kredit yang belum disahkan dan telah menunjukkan peningkatan dalam penggunaan baru-baru ini. Anda boleh cuba untuk <1>mengesahkan dana sekarang</1> atau menuunggu sehingga sekatan dialih keluar secara automatik.

NOTA: Pengesahan dana mungkin tidak berfungsi dengan semua bank atau kad kredit. Jika anda tidak dapat mengesahkan kad anda, anda perlu menunggu sehingga kaedah pembayaran tersebut disahkan oleh Steam. Sokongan Steam tidak dapat menyediakan atau menukar caj pengesahan serta tidak dapat mengalih keluar sekatan ini.`,
  _ = `Anda baru sahaja menambah dana ke dalam Dompet Steam menggunakan PayPal atau kaedah pembayaran yang belum disahkan dan telah menunjukkan peningkatan dalam penggunaan baru-baru ini. Anda tidak boleh menggunakan Pasaran selama beberapa hari sementara dana tersebut sedang disahkan.`,
  _ = `Anda baru sahaja menambah dana ke dalam Dompet Steam menggunakan akaun PayPal baharu atau kaedah pembayaran yang belum disahkan dan menunjukkan peningkatan penggunaan, sejak kebelakangan ini. Anda tidak boleh menggunakan Pasaran selama beberapa hari sementara dana tersebut disahkan.`,
  _ = `Anda baru-baru ini telah menerima kad hadiah digital daripada rakan.`,
  _ = `Anda baru sahaja menerima kad hadiah digital daripada seorang rakan. Anda tidak boleh menggunakan Pasaran Komuniti Steam selama %1$s hari selepas rakan anda membeli kad hadiah tersebut untuk anda.`,
  _ = `Steam menghadapi masalah menggunakan kuki pelayar anda.`,
  _ = `Kuki anda nampaknya tidak sah. Sila cuba log keluar dan kemudian log masuk semula ke Steam. Selain itu, sila pastikan kuki pelayar didayakan dengan betul dan tiada tambahan pelayar yang mengganggu kuki Steam.`,
  _ = `Kuki mungkin tidak didayakan pada pelayar anda. Pastikan semua kuki dibenarkan oleh pelayar anda dan cuba log keluar dan log masuk semula.`,
  _ = `Anda sedang log masuk ke Pasaran daripada peranti yang tidak dilindungi oleh Pengawal Steam selama %1$s hari.`,
  _ = `Jika anda mempunyai peranti yang telah disahkan, anda masih boleh menggunakan Pasaran pada peranti tersebut. Jika tidak, anda mesti menunggu untuk menggunakan Pasaran sementara kami mengesahkan peranti ini.`,
  _ = `Anda telah log masuk daripada peranti atau pelayar web baharu. Untuk melindungi item dalam inventori anda, anda tidak boleh menggunakan Pasaran pada peranti ini selama %1$s hari.`,
  _ = `Anda baru-baru ini telah menerima bayaran balik bagi suatu transaksi ke dalam Dompet Steam anda.`,
  _ = `Anda tidak boleh menggunakan Pasaran selama %1$s hari selepas bayaran balik terkini anda dikembalikan. Sokongan Steam tidak dapat mengalih keluar sebarang sekatan.`,
  _ = `Anda telah membuat bayaran balik bagi transaksi ke Dompet Steam anda baru-baru ini. Anda tidak boleh menggunakan Pasaran selama %1$s hari selepas permintaan bayaran balik terkini anda.`,
  _ = `Akaun anda adalah terhad.`,
  _ = `Akaun anda terhad dan tidak mempunyai akses kepada ciri Steam tertentu, termasuk Pasaran Komuniti Steam.`,
  _ = `Akaun anda terhad dan tidak mempunyai akses kepada ciri Steam tertentu, termasuk Pasaran Komuniti Steam.`,
  _ = `Anda telah menetapkan semula atau mendayakan Steam Guard baru-baru ini. Anda mesti menunggu %1$s hari selepas Steam Guard didayakan.`,
  _ = `Anda mesti menunggu sehingga Pengawal Steam telah didayakan pada akaun anda selama 15 hari. Sokongan Steam tidak dapat mengalih keluar sekatan ini.`,
  _ = `Akaun anda mesti dilindungi oleh Pengawal Steam untuk sekurang-kurangnya %1$s hari.`,
  _ = `Anda mesti mendayakan Pengawal Steam pada akaun anda. Sila pastikan e-mel anda disahkan dan anda telah log masuk ke akaun anda dua kali selepas mendayakan Pengawal Steam.`,
  _ = `Akaun anda mesti dilindungi oleh Pengawal Steam untuk sekurang-kurangnya %1$s hari.`,
  _ = `Jika tiada lagi sekatan yang menyekat akses anda, anda boleh menggunakan Pasaran Komuniti pada %1$s`,
  _ = `Akaun anda sedang dalam cooldown sementara daripada ciri pertukaran dan pasaran.`,
  _ = `Name`,
  _ = `Listed on`,
  _ = `Acted on`,
  _ = `Price`,
  _ = `Action`,
  _ = `Listed for`,
  _ = `Typically sells for`,
  _ = `%1$s (%2$s)`,
  _ = `This is the price the buyer pays.`,
  _ = `This is how much you will receive.`,
  _ = `Quantity purchased`,
  _ = `Desired price`,
  _ = `%1$s / %2$s`,
  _ = `Cancel`,
  _ = `Canceled`,
  _ = `There was a problem canceling your buy order (%1$s). Please refresh the page and try again.`,
  _ = `Cancel`,
  _ = `Canceled`,
  _ = `Cancel a listing`,
  _ = `This listing is awaiting your confirmation and has not yet been posted on the Community Market. Would you like to cancel your listing for %1$s?`,
  _ = `Yes, cancel this listing`,
  _ = `There was a problem canceling your sell listing (%1$s). Please refresh the page and try again.`,
  _ = `Remove`,
  _ = `Removed`,
  _ = `Remove a listing`,
  _ = `Would you like to remove the listing for %1$s and return the item to your inventory?`,
  _ = `Yes, remove this listing`,
  _ = `There was a problem removing your sell listing (%1$s). Please refresh the page and try again.`,
  _ = `Load More`,
  _ = `Change Price`,
  _ = `Modify`,
  _ = `You requested a price change for this listing - see your Steam mobile app or email to approve the change.`,
  _ = `Price change waiting for your approval`,
  _ = `You requested a price change for this listing - see your Steam mobile app or email to approve the change.`,
  _ = `Cancel this request`,
  _ = `Your price change request was canceled.`,
  _ = `There was a problem canceling the price change. Please refresh the page and try again.`,
  _ = `Modify this listing`,
  _ = `Back`,
  _ = `Change the price of this listing`,
  _ = `Currently asking`,
  _ = `Buyer pays`,
  _ = `You receive`,
  _ = `This is the price for one of the %1$s you have listed. All of them together are listed for %2$s.`,
  _ = `For your security, reducing the listing price needs extra confirmation`,
  _ = `Change Price`,
  _ = `Cancel`,
  _ = `This item is now listed at %1$s`,
  _ = `The new listing price is %1$s`,
  _ = `Check your email for a needed price change approval step`,
  _ = `Review and approve the price change request in the Steam Mobile app.`,
  _ = `This listing's price was changed recently. You can change it again in %1$s minutes, or cancel the listing at any time.`,
  _ = `The new price would put more in your Steam Wallet than it can hold. Try a lower price, or spend some of your balance first.`,
  _ = `There was a problem changing the price of this listing. Please refresh the page and try again.`,
  _ = `The price of this listing cannot be changed. You can cancel the listing at any time.`,
  _ = `This listing is busy with another request. Please try again in a moment.`,
  _ = `Changing the price of a listing is not available right now. Please try again later.`,
  _ = `My Sell Listings On Hold`,
  _ = `My Sell Listings Awaiting Confirmation`,
  _ = `My Active Sell Listings`,
  _ = `No results found`,
  _ = `Sold`,
  _ = `Purchased`,
  _ = `My History`,
  _ = `My Listings`,
  _ = `My Buy Orders`,
  _ = `My Market History`,
  _ = `My Sell Listings (%1$s)`,
  _ = `My Active Buy Orders (%1$s)`,
  _ = {
    AdvancedSearch_Heading: _,
    AdvancedSearch_Reset: _,
    AdvancedSearch_Search: _,
    AdvancedSearch_AppSelect_Placeholder: _,
    AdvancedSearch_AppSelect_YourGames: _,
    AdvancedSearch_AppSelect_PopularGames: _,
    AdvancedSearch_AppSelect_Clear: _,
    AdvancedSearch_TextSearch_Placeholder: _,
    AdvancedSearch_TextSearch_PlaceholderWithApp: _,
    AdvancedSearch_TypeSwitch_InGame: _,
    AdvancedSearch_TypeSwitch_SteamItems: _,
    AdvancedSearch_SteamItems_TypeLabel: _,
    AdvancedSearch_NoFacets: _,
    AdvancedSearch_NoFacetsSearch: _,
    AdvancedSearch_FacetLoadError: _,
    AdvancedSearch_PriceFieldLabel: _,
    AdvancedSearch_MinPricePlaceholder: _,
    AdvancedSearch_MaxPricePlaceholder: _,
    AdvancedSearch_CustomFilter_All: _,
    AdvancedSearch_CustomFilter_Other: _,
    AdvancedSearch_FilterGeneric_Placeholder: _,
    AdvancedSearch_AppSelect_FilterPlaceholder: _,
    AdvancedSearch_BetaTag: _,
    AdvancedSearch_TextSearch_Tooltip: _,
    AdvancedSearch_CSContainers_Tooltip: _,
    Header_MarketTitle: _,
    Header_MarketDescription: _,
    Header_LearnMore: _,
    Header_Search_Placeholder: _,
    Header_Search_PlaceholderNew: _,
    Header_Search_Filters: _,
    Header_OptOut: _,
    Header_GiveFeedback: _,
    CommodityExplanation: _,
    Search_AmountFound: _,
    Search_AmountFound_Plural: _,
    Search_AmountFoundFor: _,
    Search_AmountFoundFor_Plural: _,
    Search_ResultsFoundFor: _,
    Search_ListingsFound: _,
    Search_ListingsFound_Plural: _,
    SortBy_Popularity: _,
    SortBy_Name_Asc: _,
    SortBy_Name_Desc: _,
    SortBy_Price_Asc: _,
    SortBy_Price_Desc: _,
    SortBy_Quantity_Asc: _,
    SortBy_Quantity_Desc: _,
    SortBy_AssetProperty_Asc: _,
    SortBy_AssetProperty_Desc: _,
    SortBy_Label: _,
    Search_Button: _,
    Search_Placeholder: _,
    Button_Buy: _,
    Button_Sell: _,
    Button_BuyNow: _,
    Button_BuyOrder: _,
    BuyOrder_PlaceOrderHeader: _,
    Button_Close: _,
    Search_ListingQuantity: _,
    Search_ListingQuantity_Abbreviation: _,
    Bucket_PriceFrom: _,
    AccessorySearch_AttachedAccessoryType: _,
    FilterResults_Placeholder: _,
    AdvancedSearch_Header: _,
    AdvancedSearch_Link: _,
    MarketSearch_Placeholder: _,
    Breadcrumbs_Home: _,
    MarketHome_PopularApps: _,
    AdvancedSearch_IncludeDescriptions: _,
    AdvancedSearch_IncludeDescriptions_Tooltip: _,
    MarketSearch_FilterColumn_Header: _,
    MarketSearch_Reset: _,
    Listings_TextFilter_Placeholder: _,
    Economy_Market_Purchase_Restrictions: _,
    Economy_Market_Purchase_TradableRestriction_1Day: _,
    Economy_Market_Purchase_TradableRestriction_7Days: _,
    Economy_Market_Purchase_TradableRestriction_NDays: _,
    Economy_Market_Purchase_TradableRestriction_Permanent: _,
    Economy_Market_Purchase_MarketableRestriction_1Day: _,
    Economy_Market_Purchase_MarketableRestriction_7Days: _,
    Economy_Market_Purchase_MarketableRestriction_NDays: _,
    Economy_Market_Purchase_MarketableRestriction_None: _,
    AssetPropertyNumberFilterRange: _,
    AssetPropertyStringFilter: _,
    PurchaseDialog_Header: _,
    PurchaseDialog_Details_Column_Name: _,
    PurchaseDialog_Details_Column_Price: _,
    PurchaseDialog_Subtotal_Label: _,
    PurchaseDialog_PublisherFee_Label: _,
    PurchaseDialog_PublisherFee_Label_Generic: _,
    PurchaseDialog_SteamFee_Label: _,
    PurchaseDialog_LocalTax_Label: _,
    PurchaseDialog_Total_Label: _,
    PurchaseDialog_PaymentMethod_Label: _,
    PurchaseDialog_PaymentMethod_Wallet: _,
    PurchaseDialog_SteamAccount_Label: _,
    PurchaseDialog_BillingInfo_Label: _,
    PurchaseDialog_BillingInfo_FirstName: _,
    PurchaseDialog_BillingInfo_LastName: _,
    PurchaseDialog_BillingInfo_Address: _,
    PurchaseDialog_BillingInfo_AddressLine2: _,
    PurchaseDialog_BillingInfo_City: _,
    PurchaseDialog_BillingInfo_StateProvince: _,
    PurchaseDialog_BillingInfo_ZipPostal: _,
    PurchaseDialog_BillingInfo_Country: _,
    PurchaseDialog_BillingInfo_SaveInfo: _,
    PurchaseDialog_Action_AddFunds: _,
    PurchaseDialog_Action_Purchase: _,
    PurchaseDialog_SSA_Link: _,
    PurchaseDialog_SSA_Link_Title: _,
    PurchaseDialog_SSA_Fail: _,
    PurchaseDialog_EU_SSA: _,
    PurchaseDialog_Error_ServerGeneric: _,
    PurchaseDialog_Error_NoConfirmation: _,
    PurchaseDialog_Error_MissingRequired: _,
    PurchaseDialog_Error_InvalidMilitaryCity: _,
    PurchaseDialog_Error_InvalidPostal: _,
    PurchaseDialog_PurchaseComplete: _,
    PurchaseDialog_Button_ViewInventory: _,
    PurchaseDialog_Confirmation_Title: _,
    PurchaseDialog_Confirmation_Title_Wait: _,
    PurchaseDialog_Confirmation_Body_Mobile: _,
    PurchaseDialog_Confirmation_Body_Email: _,
    PurchaseDialog_Confirmation_Body_Unknown: _,
    PurchaseDialog_Confirmation_Description_Mobile: _,
    PurchaseDialog_Confirmation_Description_Email: _,
    PurchaseDialog_Confirmation_Description_Unknown: _,
    PurchaseDialog_Purchase_Successful: _,
    PurchaseDialog_Close: _,
    PurchaseDialog_ViewInventory: _,
    PurhcaseDialog_SaveMyAddress: _,
    Listing_NotAvailable: _,
    Listing_NotAvailable_Short: _,
    Listing_NotAvailable_Long: _,
    Listing_MyListing: _,
    BuyOrderDialog_Header: _,
    BuyOrderDialog_Header_NoItem: _,
    BuyOrderDialog_BucketPicker_Label: _,
    BuyOrderDialog_BucketPicker_Placeholder: _,
    BuyOrderDialog_PriceField: _,
    BuyOrderDialog_PriceField_Suffix: _,
    BuyOrderDialog_QuantityField: _,
    BuyOrderDialog_MaxPrice: _,
    BuyOrderDialog_MaxPrice_Tip: _,
    BuyOrderDialog_Status_Pending: _,
    BuyOrderDialog_Status_Filled: _,
    BuyOrderDialog_Status_Settled: _,
    BuyOrderDialog_Status_Settled_Note: _,
    BuyOrderDialog_Status_GenericError: _,
    BuyOrderDialog_MinPriceError: _,
    OrderBook_Table_PriceOrLess: _,
    OrderBook_Table_PriceOrMore: _,
    OrderBook_Table_Price: _,
    OrderBook_Table_Quantity: _,
    OrderBook_SellOrder_Description: _,
    OrderBook_SellOrder_Description_None: _,
    OrderBook_BuyOrder_Description: _,
    OrderBook_BuyOrder_Description_None: _,
    OrderBook_BuyOrder_NeedBucket: _,
    OrderBook_BuyOrder_Explanation_Unique: _,
    OrderBook_BuyOrder_Explanation_Commodity: _,
    OrderBook_Graph_Title: _,
    OrderBook_Graph_BuyTooltip: _,
    OrderBook_Graph_BuyTooltip_Plural: _,
    OrderBook_Graph_SellTooltip: _,
    OrderBook_Graph_SellTooltip_Plural: _,
    OrderBook_PlaceOrder_BuyRequests: _,
    OrderBook_PlaceOrder_BuyRequests_Plural: _,
    MedianSalePrice_Graph_Title: _,
    Graph_TimeScale_Week: _,
    Graph_TimeScale_Month: _,
    Graph_TimeScale_Year: _,
    Graph_TimeScale_Lifetime: _,
    Graph_NumberSold: _,
    Graph_Label_Price: _,
    Graph_Label_Volume: _,
    Graph_NoData: _,
    Graph_Tooltip_NoPurchaseData: _,
    Graph_Tooltip_NA: `T/B`,
    MyOrders_GridHeader_Name: _,
    MyOrders_GridHeader_Price: _,
    MyOrders_GridHeader_Quantity: _,
    MyOrders_GridHeader_DateListed: _,
    MyOrders_Cancel: _,
    MyOrders_Remove: _,
    MyOrders_Heading: _,
    MyOrders_Heading_Sell: _,
    MyOrders_Heading_Buy: _,
    MyOrders_Heading_MyPurchaseOffers: _,
    MyOrders_Heading_MyListings: _,
    MyOrders_FailedToLoad: _,
    MyOrders_NoActiveOrders_Item: _,
    MyOrders_NoBuyOrders_Item: _,
    MyOrders_NoSellOrders_Item: _,
    MyOrders_QuantityWithValue: _,
    MyOrders_SeeAllN: _,
    CancelBuyOrder_GenericError: _,
    CancelListing_GenericError: _,
    CancelListing_Dialog_Header: _,
    CancelListing_Dialog_Prompt: _,
    CancelListing_Dialog_Prompt_Generic: _,
    CancelListing_Dialog_Yes: _,
    CancelListing_Dialog_No: _,
    CancelListing_Dialog_Success: _,
    SellDialog_Frame_Title: _,
    UniqueBuyOrder_Explanation_Header: _,
    UniqueBuyOrder_Explanation_1: _,
    UniqueBuyOrder_Explanation_2: _,
    UniqueBuyOrder_Explanation_3: _,
    PriceFilter_ValueAndUp: _,
    Error_Sorry: _,
    Error_Encountered: _,
    Error_TooManyRequests_Description: _,
    Container_ContentsLabel: _,
    Error_LoadingContent: _,
    Error_LoadingMarketItem: _,
    ListingFilter_Title: _,
    Listings_NoneFound: _,
    ItemBucketPicker_Overflow_Placeholder: _,
    ItemBucketPicker_Overflow_FilterPlaceholder: _,
    Mobile_InfoSection: _,
    Mobile_GraphSection: _,
    Mobile_BuyOrderSection: _,
    Mobile_FiltersButton: _,
    AssetProperty_Range_MinPlaceholder: `Min`,
    AssetProperty_Range_MaxPlaceholder: _,
    Accessories_FieldSectionLabel: _,
    Accessories_AnyFilter: `Any`,
    Accessories_NoneFilter: _,
    Accessories_TypeAndValue_Breadcrumb: _,
    Item_CountryBuySellRestricted: _,
    Item_CountryBuyRestricted: _,
    Listing_EnhancedAppearance_Missing: _,
    Listing_EnhancedAppearance_ShowBackground: _,
    Listing_SomethingWentWrong: _,
    Unavailable_Header: _,
    Unavailable_Header_Plural: _,
    Filter_ViewResults: _,
    Results_GridView_Tooltip: _,
    Results_ListView_Tooltip: _,
    Results_InitialLoadError: _,
    Results_PageLoadError: _,
    Market_AppUnplayedAndUnvetted: _,
    Market_AppUnplayedAndUnvetted_Dismiss: _,
    Home_GamePicker_Label: _,
    Home_GamePicker_ViewAll: _,
    Economy_Market_TopLevelReason_AccountLocked: _,
    Economy_Market_TopLevelTooltip_AccountLocked: _,
    Economy_Market_HeaderTip_AccountLocked: _,
    Economy_Market_TopLevelTooltip_RemoveRestrictionLink: _,
    Economy_Market_TopLevelReason_AccountTradeBanned: _,
    Economy_Market_TopLevelReason_Unknown: _,
    Economy_Market_TopLevelTooltip_AccountTradeBanned: _,
    Economy_Market_HeaderTip_AccountTradeBanned: _,
    Economy_Market_TopLevelTooltip_MoreInfoLink: _,
    Economy_Market_TopLevelReason_AccountNotTrusted: _,
    Economy_Market_TopLevelTooltip_AccountNotTrusted: _,
    Economy_Market_HeaderTip_AccountNotTrusted: _,
    Economy_Market_TopLevelReason_AccountNotTrusted_Waiting: _,
    Economy_Market_TTopLevelTooltip_AccountNotTrusted_Waiting: _,
    Economy_Market_TopLevelReason_AccountPasswordRecentlyReset: _,
    Economy_Market_TopLevelTooltip_AccountPasswordRecentlyReset: _,
    Economy_Market_HeaderTip_AccountPasswordRecentlyReset: _,
    Economy_Market_HeaderTip_NewPaymentMethod_NoDate: _,
    Economy_Market_HeaderTip_AccountHasNewPaymentMethod: _,
    Economy_Market_TopLevelReason_AccountHasNewPaymentMethod: _,
    Economy_Market_TopLevelReason_AcceptedWalletGift: _,
    Economy_Market_HeaderTip_AcceptedWalletGift: _,
    Economy_Market_TopLevelReason_InvalidCookie: _,
    Economy_Market_TopLevelTooltip_InvalidCookie: _,
    Economy_Market_HeaderTip_InvalidCookie: _,
    Economy_Market_TopLevelReason_NewDevice: _,
    Economy_Market_TopLevelTooltip_NewDevice: _,
    Economy_Market_HeaderTip_NewDevice: _,
    Economy_Market_TopLevelReason_SelfRefund: _,
    Economy_Market_TopLevelTooltip_SelfRefund: _,
    Economy_Market_HeaderTip_SelfRefund: _,
    Economy_Market_TopLevelReason_LimitedUser: _,
    Economy_Market_TopLevelTooltip_LimitedUser: _,
    Economy_Market_HeaderTip_LimitedUser: _,
    Economy_Market_HeaderTip_SteamGuardOnlyRecentlyEnabled: _,
    Economy_Market_TopLevelTooltip_SteamGuardRecentlyEnabled: _,
    Economy_Market_TopLevelReason_NoSteamGuard: _,
    Economy_Market_TopLevelTooltip_SteamGuardDisabled: _,
    Economy_Market_HeaderTip_NoSteamGuard: _,
    Economy_Market_HeaderTip_TimeCanUse: _,
    Economy_Market_TopLevelReason_TradeCooldown: _,
    MyHistory_Title_ItemNameBlock: _,
    MyHistory_Title_ListedAtTime: _,
    MyHistory_Title_ActedOnTime: _,
    MyHistory_Title_TransactedPrice: _,
    MyHistory_Title_Action: _,
    MyListings_Title_ListedPrice: _,
    MyListings_Title_MedianPrice: _,
    MyListings_ListingPrice: _,
    MyListings_Tooltip_BuyerPrice: _,
    MyListings_Tooltip_ReceiveAmt: _,
    MyBuyOrders_Title_Quantity: _,
    MyBuyOrders_Title_BidPrice: _,
    MyBuyOrders_QuantityPurchased: _,
    MyBuyOrders_CancelButton: _,
    MyBuyOrders_CancelButton_Canceled: _,
    MyBuyOrders_Cancel_Error: _,
    MySellListings_CancelButton: _,
    MySellListings_CancelButton_Canceled: _,
    MySellListings_CancelDialog_Title: _,
    MySellListings_CancelDialog_Confirmation: _,
    MySellListings_CancelDialog_AcceptButton: _,
    MySellListings_Cancel_Error: _,
    MySellListings_RemoveButton: _,
    MySellListings_RemoveButton_Removed: _,
    MySellListings_RemoveDialog_Title: _,
    MySellListings_RemoveDialog_Confirmation: _,
    MySellListings_RemoveDialog_AcceptButton: _,
    MySellListings_Remove_Error: _,
    MySellListings_LoadMoreButton: _,
    MySellListings_ChangePriceButton: _,
    MySellListings_ModifyButton: _,
    MySellListings_PendingPriceChange: _,
    PendingPriceChange_Dialog_Header: _,
    PendingPriceChange_Dialog_Explanation: _,
    PendingPriceChange_Dialog_Discard: _,
    PendingPriceChange_Dialog_Discarded: _,
    PendingPriceChange_Dialog_DiscardError: _,
    ManageListing_Dialog_Header: _,
    ManageListing_Dialog_Back: _,
    RepriceListing_Dialog_Header: _,
    RepriceListing_Dialog_CurrentPrice: _,
    RepriceListing_Dialog_BuyerPays: _,
    RepriceListing_Dialog_YouReceive: _,
    RepriceListing_Dialog_PerUnit: _,
    RepriceListing_Dialog_DecreaseNeedsConfirmation: _,
    RepriceListing_Dialog_Submit: _,
    RepriceListing_Dialog_Cancel: _,
    RepriceListing_Dialog_Success: _,
    RepriceListing_Dialog_SuccessPerUnit: _,
    RepriceListing_Dialog_ConfirmByEmail: _,
    RepriceListing_Dialog_ConfirmOnPhone: _,
    RepriceListing_Dialog_Cooldown: _,
    RepriceListing_Dialog_WalletLimit: _,
    RepriceListing_Dialog_GenericError: _,
    RepriceListing_Dialog_CannotReprice: _,
    RepriceListing_Dialog_TryAgain: _,
    RepriceListing_Dialog_Unavailable: _,
    MySellListings_SectionHeader_OnHold: _,
    MySellListings_SectionHeader_PendingConfirmation: _,
    MySellListings_SectionHeader_Active: _,
    MyHistory_NoResults: _,
    MyHistory_Action_Sold: _,
    MyHistory_Action_Purchased: _,
    Breadcrumbs_Label_History: _,
    Breadcrumbs_Label_Listings: _,
    Breadcrumbs_Label_BuyOrders: _,
    MyListings_SectionHeader_Button_History: _,
    MyListings_SectionHeader_Button_Listings: _,
    MyListings_SectionHeader_Button_BuyOrders: _,
  };
export {
  _ as Accessories_AnyFilter,
  _ as Accessories_FieldSectionLabel,
  _ as Accessories_NoneFilter,
  _ as Accessories_TypeAndValue_Breadcrumb,
  _ as AccessorySearch_AttachedAccessoryType,
  _ as AdvancedSearch_AppSelect_Clear,
  _ as AdvancedSearch_AppSelect_FilterPlaceholder,
  _ as AdvancedSearch_AppSelect_Placeholder,
  _ as AdvancedSearch_AppSelect_PopularGames,
  _ as AdvancedSearch_AppSelect_YourGames,
  _ as AdvancedSearch_BetaTag,
  _ as AdvancedSearch_CSContainers_Tooltip,
  _ as AdvancedSearch_CustomFilter_All,
  _ as AdvancedSearch_CustomFilter_Other,
  _ as AdvancedSearch_FacetLoadError,
  _ as AdvancedSearch_FilterGeneric_Placeholder,
  _ as AdvancedSearch_Header,
  _ as AdvancedSearch_Heading,
  _ as AdvancedSearch_IncludeDescriptions,
  _ as AdvancedSearch_IncludeDescriptions_Tooltip,
  _ as AdvancedSearch_Link,
  _ as AdvancedSearch_MaxPricePlaceholder,
  _ as AdvancedSearch_MinPricePlaceholder,
  _ as AdvancedSearch_NoFacets,
  _ as AdvancedSearch_NoFacetsSearch,
  _ as AdvancedSearch_PriceFieldLabel,
  _ as AdvancedSearch_Reset,
  _ as AdvancedSearch_Search,
  _ as AdvancedSearch_SteamItems_TypeLabel,
  _ as AdvancedSearch_TextSearch_Placeholder,
  _ as AdvancedSearch_TextSearch_PlaceholderWithApp,
  _ as AdvancedSearch_TextSearch_Tooltip,
  _ as AdvancedSearch_TypeSwitch_InGame,
  _ as AdvancedSearch_TypeSwitch_SteamItems,
  _ as AssetPropertyNumberFilterRange,
  _ as AssetPropertyStringFilter,
  _ as AssetProperty_Range_MaxPlaceholder,
  _ as AssetProperty_Range_MinPlaceholder,
  _ as Breadcrumbs_Home,
  _ as Breadcrumbs_Label_BuyOrders,
  _ as Breadcrumbs_Label_History,
  _ as Breadcrumbs_Label_Listings,
  _ as Bucket_PriceFrom,
  _ as Button_Buy,
  _ as Button_BuyNow,
  _ as Button_BuyOrder,
  _ as Button_Close,
  _ as Button_Sell,
  _ as BuyOrderDialog_BucketPicker_Label,
  _ as BuyOrderDialog_BucketPicker_Placeholder,
  _ as BuyOrderDialog_Header,
  _ as BuyOrderDialog_Header_NoItem,
  _ as BuyOrderDialog_MaxPrice,
  _ as BuyOrderDialog_MaxPrice_Tip,
  _ as BuyOrderDialog_MinPriceError,
  _ as BuyOrderDialog_PriceField,
  _ as BuyOrderDialog_PriceField_Suffix,
  _ as BuyOrderDialog_QuantityField,
  _ as BuyOrderDialog_Status_Filled,
  _ as BuyOrderDialog_Status_GenericError,
  _ as BuyOrderDialog_Status_Pending,
  _ as BuyOrderDialog_Status_Settled,
  _ as BuyOrderDialog_Status_Settled_Note,
  _ as BuyOrder_PlaceOrderHeader,
  _ as CancelBuyOrder_GenericError,
  _ as CancelListing_Dialog_Header,
  _ as CancelListing_Dialog_No,
  _ as CancelListing_Dialog_Prompt,
  _ as CancelListing_Dialog_Prompt_Generic,
  _ as CancelListing_Dialog_Success,
  _ as CancelListing_Dialog_Yes,
  _ as CancelListing_GenericError,
  _ as CommodityExplanation,
  _ as Container_ContentsLabel,
  _ as Economy_Market_HeaderTip_AcceptedWalletGift,
  _ as Economy_Market_HeaderTip_AccountHasNewPaymentMethod,
  _ as Economy_Market_HeaderTip_AccountLocked,
  _ as Economy_Market_HeaderTip_AccountNotTrusted,
  _ as Economy_Market_HeaderTip_AccountPasswordRecentlyReset,
  _ as Economy_Market_HeaderTip_AccountTradeBanned,
  _ as Economy_Market_HeaderTip_InvalidCookie,
  _ as Economy_Market_HeaderTip_LimitedUser,
  _ as Economy_Market_HeaderTip_NewDevice,
  _ as Economy_Market_HeaderTip_NewPaymentMethod_NoDate,
  _ as Economy_Market_HeaderTip_NoSteamGuard,
  _ as Economy_Market_HeaderTip_SelfRefund,
  _ as Economy_Market_HeaderTip_SteamGuardOnlyRecentlyEnabled,
  _ as Economy_Market_HeaderTip_TimeCanUse,
  _ as Economy_Market_Purchase_MarketableRestriction_1Day,
  _ as Economy_Market_Purchase_MarketableRestriction_7Days,
  _ as Economy_Market_Purchase_MarketableRestriction_NDays,
  _ as Economy_Market_Purchase_MarketableRestriction_None,
  _ as Economy_Market_Purchase_Restrictions,
  _ as Economy_Market_Purchase_TradableRestriction_1Day,
  _ as Economy_Market_Purchase_TradableRestriction_7Days,
  _ as Economy_Market_Purchase_TradableRestriction_NDays,
  _ as Economy_Market_Purchase_TradableRestriction_Permanent,
  _ as Economy_Market_TTopLevelTooltip_AccountNotTrusted_Waiting,
  _ as Economy_Market_TopLevelReason_AcceptedWalletGift,
  _ as Economy_Market_TopLevelReason_AccountHasNewPaymentMethod,
  _ as Economy_Market_TopLevelReason_AccountLocked,
  _ as Economy_Market_TopLevelReason_AccountNotTrusted,
  _ as Economy_Market_TopLevelReason_AccountNotTrusted_Waiting,
  _ as Economy_Market_TopLevelReason_AccountPasswordRecentlyReset,
  _ as Economy_Market_TopLevelReason_AccountTradeBanned,
  _ as Economy_Market_TopLevelReason_InvalidCookie,
  _ as Economy_Market_TopLevelReason_LimitedUser,
  _ as Economy_Market_TopLevelReason_NewDevice,
  _ as Economy_Market_TopLevelReason_NoSteamGuard,
  _ as Economy_Market_TopLevelReason_SelfRefund,
  _ as Economy_Market_TopLevelReason_TradeCooldown,
  _ as Economy_Market_TopLevelReason_Unknown,
  _ as Economy_Market_TopLevelTooltip_AccountLocked,
  _ as Economy_Market_TopLevelTooltip_AccountNotTrusted,
  _ as Economy_Market_TopLevelTooltip_AccountPasswordRecentlyReset,
  _ as Economy_Market_TopLevelTooltip_AccountTradeBanned,
  _ as Economy_Market_TopLevelTooltip_InvalidCookie,
  _ as Economy_Market_TopLevelTooltip_LimitedUser,
  _ as Economy_Market_TopLevelTooltip_MoreInfoLink,
  _ as Economy_Market_TopLevelTooltip_NewDevice,
  _ as Economy_Market_TopLevelTooltip_RemoveRestrictionLink,
  _ as Economy_Market_TopLevelTooltip_SelfRefund,
  _ as Economy_Market_TopLevelTooltip_SteamGuardDisabled,
  _ as Economy_Market_TopLevelTooltip_SteamGuardRecentlyEnabled,
  _ as Error_Encountered,
  _ as Error_LoadingContent,
  _ as Error_LoadingMarketItem,
  _ as Error_Sorry,
  _ as Error_TooManyRequests_Description,
  _ as FilterResults_Placeholder,
  _ as Filter_ViewResults,
  _ as Graph_Label_Price,
  _ as Graph_Label_Volume,
  _ as Graph_NoData,
  _ as Graph_NumberSold,
  _ as Graph_TimeScale_Lifetime,
  _ as Graph_TimeScale_Month,
  _ as Graph_TimeScale_Week,
  _ as Graph_TimeScale_Year,
  _ as Graph_Tooltip_NA,
  _ as Graph_Tooltip_NoPurchaseData,
  _ as Header_GiveFeedback,
  _ as Header_LearnMore,
  _ as Header_MarketDescription,
  _ as Header_MarketTitle,
  _ as Header_OptOut,
  _ as Header_Search_Filters,
  _ as Header_Search_Placeholder,
  _ as Header_Search_PlaceholderNew,
  _ as Home_GamePicker_Label,
  _ as Home_GamePicker_ViewAll,
  _ as ItemBucketPicker_Overflow_FilterPlaceholder,
  _ as ItemBucketPicker_Overflow_Placeholder,
  _ as Item_CountryBuyRestricted,
  _ as Item_CountryBuySellRestricted,
  _ as ListingFilter_Title,
  _ as Listing_EnhancedAppearance_Missing,
  _ as Listing_EnhancedAppearance_ShowBackground,
  _ as Listing_MyListing,
  _ as Listing_NotAvailable,
  _ as Listing_NotAvailable_Long,
  _ as Listing_NotAvailable_Short,
  _ as Listing_SomethingWentWrong,
  _ as Listings_NoneFound,
  _ as Listings_TextFilter_Placeholder,
  _ as ManageListing_Dialog_Back,
  _ as ManageListing_Dialog_Header,
  _ as MarketHome_PopularApps,
  _ as MarketSearch_FilterColumn_Header,
  _ as MarketSearch_Placeholder,
  _ as MarketSearch_Reset,
  _ as Market_AppUnplayedAndUnvetted,
  _ as Market_AppUnplayedAndUnvetted_Dismiss,
  _ as MedianSalePrice_Graph_Title,
  _ as Mobile_BuyOrderSection,
  _ as Mobile_FiltersButton,
  _ as Mobile_GraphSection,
  _ as Mobile_InfoSection,
  _ as MyBuyOrders_CancelButton,
  _ as MyBuyOrders_CancelButton_Canceled,
  _ as MyBuyOrders_Cancel_Error,
  _ as MyBuyOrders_QuantityPurchased,
  _ as MyBuyOrders_Title_BidPrice,
  _ as MyBuyOrders_Title_Quantity,
  _ as MyHistory_Action_Purchased,
  _ as MyHistory_Action_Sold,
  _ as MyHistory_NoResults,
  _ as MyHistory_Title_ActedOnTime,
  _ as MyHistory_Title_Action,
  _ as MyHistory_Title_ItemNameBlock,
  _ as MyHistory_Title_ListedAtTime,
  _ as MyHistory_Title_TransactedPrice,
  _ as MyListings_ListingPrice,
  _ as MyListings_SectionHeader_Button_BuyOrders,
  _ as MyListings_SectionHeader_Button_History,
  _ as MyListings_SectionHeader_Button_Listings,
  _ as MyListings_Title_ListedPrice,
  _ as MyListings_Title_MedianPrice,
  _ as MyListings_Tooltip_BuyerPrice,
  _ as MyListings_Tooltip_ReceiveAmt,
  _ as MyOrders_Cancel,
  _ as MyOrders_FailedToLoad,
  _ as MyOrders_GridHeader_DateListed,
  _ as MyOrders_GridHeader_Name,
  _ as MyOrders_GridHeader_Price,
  _ as MyOrders_GridHeader_Quantity,
  _ as MyOrders_Heading,
  _ as MyOrders_Heading_Buy,
  _ as MyOrders_Heading_MyListings,
  _ as MyOrders_Heading_MyPurchaseOffers,
  _ as MyOrders_Heading_Sell,
  _ as MyOrders_NoActiveOrders_Item,
  _ as MyOrders_NoBuyOrders_Item,
  _ as MyOrders_NoSellOrders_Item,
  _ as MyOrders_QuantityWithValue,
  _ as MyOrders_Remove,
  _ as MyOrders_SeeAllN,
  _ as MySellListings_CancelButton,
  _ as MySellListings_CancelButton_Canceled,
  _ as MySellListings_CancelDialog_AcceptButton,
  _ as MySellListings_CancelDialog_Confirmation,
  _ as MySellListings_CancelDialog_Title,
  _ as MySellListings_Cancel_Error,
  _ as MySellListings_ChangePriceButton,
  _ as MySellListings_LoadMoreButton,
  _ as MySellListings_ModifyButton,
  _ as MySellListings_PendingPriceChange,
  _ as MySellListings_RemoveButton,
  _ as MySellListings_RemoveButton_Removed,
  _ as MySellListings_RemoveDialog_AcceptButton,
  _ as MySellListings_RemoveDialog_Confirmation,
  _ as MySellListings_RemoveDialog_Title,
  _ as MySellListings_Remove_Error,
  _ as MySellListings_SectionHeader_Active,
  _ as MySellListings_SectionHeader_OnHold,
  _ as MySellListings_SectionHeader_PendingConfirmation,
  _ as OrderBook_BuyOrder_Description,
  _ as OrderBook_BuyOrder_Description_None,
  _ as OrderBook_BuyOrder_Explanation_Commodity,
  _ as OrderBook_BuyOrder_Explanation_Unique,
  _ as OrderBook_BuyOrder_NeedBucket,
  _ as OrderBook_Graph_BuyTooltip,
  _ as OrderBook_Graph_BuyTooltip_Plural,
  _ as OrderBook_Graph_SellTooltip,
  _ as OrderBook_Graph_SellTooltip_Plural,
  _ as OrderBook_Graph_Title,
  _ as OrderBook_PlaceOrder_BuyRequests,
  _ as OrderBook_PlaceOrder_BuyRequests_Plural,
  _ as OrderBook_SellOrder_Description,
  _ as OrderBook_SellOrder_Description_None,
  _ as OrderBook_Table_Price,
  _ as OrderBook_Table_PriceOrLess,
  _ as OrderBook_Table_PriceOrMore,
  _ as OrderBook_Table_Quantity,
  _ as PendingPriceChange_Dialog_Discard,
  _ as PendingPriceChange_Dialog_DiscardError,
  _ as PendingPriceChange_Dialog_Discarded,
  _ as PendingPriceChange_Dialog_Explanation,
  _ as PendingPriceChange_Dialog_Header,
  _ as PriceFilter_ValueAndUp,
  _ as PurchaseDialog_Action_AddFunds,
  _ as PurchaseDialog_Action_Purchase,
  _ as PurchaseDialog_BillingInfo_Address,
  _ as PurchaseDialog_BillingInfo_AddressLine2,
  _ as PurchaseDialog_BillingInfo_City,
  _ as PurchaseDialog_BillingInfo_Country,
  _ as PurchaseDialog_BillingInfo_FirstName,
  _ as PurchaseDialog_BillingInfo_Label,
  _ as PurchaseDialog_BillingInfo_LastName,
  _ as PurchaseDialog_BillingInfo_SaveInfo,
  _ as PurchaseDialog_BillingInfo_StateProvince,
  _ as PurchaseDialog_BillingInfo_ZipPostal,
  _ as PurchaseDialog_Button_ViewInventory,
  _ as PurchaseDialog_Close,
  _ as PurchaseDialog_Confirmation_Body_Email,
  _ as PurchaseDialog_Confirmation_Body_Mobile,
  _ as PurchaseDialog_Confirmation_Body_Unknown,
  _ as PurchaseDialog_Confirmation_Description_Email,
  _ as PurchaseDialog_Confirmation_Description_Mobile,
  _ as PurchaseDialog_Confirmation_Description_Unknown,
  _ as PurchaseDialog_Confirmation_Title,
  _ as PurchaseDialog_Confirmation_Title_Wait,
  _ as PurchaseDialog_Details_Column_Name,
  _ as PurchaseDialog_Details_Column_Price,
  _ as PurchaseDialog_EU_SSA,
  _ as PurchaseDialog_Error_InvalidMilitaryCity,
  _ as PurchaseDialog_Error_InvalidPostal,
  _ as PurchaseDialog_Error_MissingRequired,
  _ as PurchaseDialog_Error_NoConfirmation,
  _ as PurchaseDialog_Error_ServerGeneric,
  _ as PurchaseDialog_Header,
  _ as PurchaseDialog_LocalTax_Label,
  _ as PurchaseDialog_PaymentMethod_Label,
  _ as PurchaseDialog_PaymentMethod_Wallet,
  _ as PurchaseDialog_PublisherFee_Label,
  _ as PurchaseDialog_PublisherFee_Label_Generic,
  _ as PurchaseDialog_PurchaseComplete,
  _ as PurchaseDialog_Purchase_Successful,
  _ as PurchaseDialog_SSA_Fail,
  _ as PurchaseDialog_SSA_Link,
  _ as PurchaseDialog_SSA_Link_Title,
  _ as PurchaseDialog_SteamAccount_Label,
  _ as PurchaseDialog_SteamFee_Label,
  _ as PurchaseDialog_Subtotal_Label,
  _ as PurchaseDialog_Total_Label,
  _ as PurchaseDialog_ViewInventory,
  _ as PurhcaseDialog_SaveMyAddress,
  _ as RepriceListing_Dialog_BuyerPays,
  _ as RepriceListing_Dialog_Cancel,
  _ as RepriceListing_Dialog_CannotReprice,
  _ as RepriceListing_Dialog_ConfirmByEmail,
  _ as RepriceListing_Dialog_ConfirmOnPhone,
  _ as RepriceListing_Dialog_Cooldown,
  _ as RepriceListing_Dialog_CurrentPrice,
  _ as RepriceListing_Dialog_DecreaseNeedsConfirmation,
  _ as RepriceListing_Dialog_GenericError,
  _ as RepriceListing_Dialog_Header,
  _ as RepriceListing_Dialog_PerUnit,
  _ as RepriceListing_Dialog_Submit,
  _ as RepriceListing_Dialog_Success,
  _ as RepriceListing_Dialog_SuccessPerUnit,
  _ as RepriceListing_Dialog_TryAgain,
  _ as RepriceListing_Dialog_Unavailable,
  _ as RepriceListing_Dialog_WalletLimit,
  _ as RepriceListing_Dialog_YouReceive,
  _ as Results_GridView_Tooltip,
  _ as Results_InitialLoadError,
  _ as Results_ListView_Tooltip,
  _ as Results_PageLoadError,
  _ as Search_AmountFound,
  _ as Search_AmountFoundFor,
  _ as Search_AmountFoundFor_Plural,
  _ as Search_AmountFound_Plural,
  _ as Search_Button,
  _ as Search_ListingQuantity,
  _ as Search_ListingQuantity_Abbreviation,
  _ as Search_ListingsFound,
  _ as Search_ListingsFound_Plural,
  _ as Search_Placeholder,
  _ as Search_ResultsFoundFor,
  _ as SellDialog_Frame_Title,
  _ as SortBy_AssetProperty_Asc,
  _ as SortBy_AssetProperty_Desc,
  _ as SortBy_Label,
  _ as SortBy_Name_Asc,
  _ as SortBy_Name_Desc,
  _ as SortBy_Popularity,
  _ as SortBy_Price_Asc,
  _ as SortBy_Price_Desc,
  _ as SortBy_Quantity_Asc,
  _ as SortBy_Quantity_Desc,
  _ as Unavailable_Header,
  _ as Unavailable_Header_Plural,
  _ as UniqueBuyOrder_Explanation_1,
  _ as UniqueBuyOrder_Explanation_2,
  _ as UniqueBuyOrder_Explanation_3,
  _ as UniqueBuyOrder_Explanation_Header,
  _ as default,
};
