var _ = `french`,
  _ = `Lien vers la page d'accueil Steam`,
  _ = `Installer Steam`,
  _ = `se connecter\xA0`,
  _ = `Se connecter`,
  _ = `Voir mon profil`,
  _ = `Détails du compte\xA0`,
  _ = `Détails du compte\xA0: <1>%1$s</1>`,
  _ = `Préférences du magasin`,
  _ = `Changer la langue`,
  _ = `langue`,
  _ = `Se déconnecter du compte…`,
  _ = `Voir mon portemonnaie`,
  _ = `Voir mon portemonnaie\xA0: <1>%1$s</1>`,
  _ = `NOUV.`,
  _ = `Panier (%1$s)`,
  _ = `Portemonnaie (%1$s)`,
  _ = `© Valve Corporation. Tous droits réservés. Les marques citées sont la propriété de leurs détenteurs respectifs, aux États-Unis et dans d'autres pays.`,
  _ = `Politique de protection de la vie privée`,
  _ = `Mentions légales`,
  _ = `Accord de souscription Steam`,
  _ = `Remboursements`,
  _ = `Voir version ordi. du site`,
  _ = `Afficher la version mobile du site`,
  _ = `Télécharger l'application mobile Steam`,
  _ = `Changer de compte`,
  _ = `Notifications`,
  _ = `Navigation`,
  _ = `BÊTA`,
  _ = {
    language: _,
    Aria_Steam_Home_Link: _,
    global_menu_install_steam: _,
    global_menu_login: _,
    global_menu_login_caps: _,
    global_menu_view_profile: _,
    global_menu_account_details: _,
    global_menu_account_details_accountname: _,
    global_menu_account_preferences: _,
    global_menu_change_language: _,
    global_menu_language: _,
    global_menu_sign_out: _,
    global_menu_view_wallet: _,
    global_menu_view_wallet_with_amount: _,
    m_ext_new: _,
    Cart_CountWidget: _,
    responsive_menu_wallet_balance: _,
    responsive_footer_copyright: _,
    Common_Footer_PrivacyPolicy: _,
    Common_Footer_Legal: _,
    Common_Footer_SSA: _,
    Common_Footer_Refunds: _,
    global_menu_view_desktop_website: _,
    global_menu_view_mobile_website: _,
    global_menu_getmobileapp: _,
    global_menu_change_user: _,
    SuperNav_Notifications: _,
    Aria_Navigation: _,
    beta_tag: _,
  };
export {
  _ as Aria_Navigation,
  _ as Aria_Steam_Home_Link,
  _ as Cart_CountWidget,
  _ as Common_Footer_Legal,
  _ as Common_Footer_PrivacyPolicy,
  _ as Common_Footer_Refunds,
  _ as Common_Footer_SSA,
  _ as SuperNav_Notifications,
  _ as beta_tag,
  _ as default,
  _ as global_menu_account_details,
  _ as global_menu_account_details_accountname,
  _ as global_menu_account_preferences,
  _ as global_menu_change_language,
  _ as global_menu_change_user,
  _ as global_menu_getmobileapp,
  _ as global_menu_install_steam,
  _ as global_menu_language,
  _ as global_menu_login,
  _ as global_menu_login_caps,
  _ as global_menu_sign_out,
  _ as global_menu_view_desktop_website,
  _ as global_menu_view_mobile_website,
  _ as global_menu_view_profile,
  _ as global_menu_view_wallet,
  _ as global_menu_view_wallet_with_amount,
  _ as language,
  _ as m_ext_new,
  _ as responsive_footer_copyright,
  _ as responsive_menu_wallet_balance,
};
