var _ = `Laporan kandungan`,
  _ = `Diserahkan oleh anda`,
  _ = `Pada kandungan anda`,
  _ = `Kandungan ini nampaknya tidak menyalahi undang-undang atau melanggar syarat perkhidmatan Steam.`,
  _ = `Jika anda percaya ini merupakan satu kesilapan, anda boleh membantah keputusan ini.`,
  _ = `Dibantah: menunggu penyelarasan`,
  _ = `Komunikasi disekat`,
  _ = `%1$s – %2$s`,
  _ = `Penyataan Sebab`,
  _ = `Sekatan keterlihatan`,
  _ = `Fakta dan keadaan yang menjadi asas semasa membuat keputusan`,
  _ = `Asas keputusan`,
  _ = `Asas undang-undang yang menjadi sandaran`,
  _ = `Rujukan kepada asas kontrak`,
  _ = `Penjelasan tentang sebab kandungan dianggap menyalahi undang-undang berdasarkan asas tersebut`,
  _ = `Jenis kandungan`,
  _ = `Sumber maklumat`,
  _ = `Adakah kandungan dikesan/dikenal pasti menggunakan kaedah automatik?`,
  _ = `Adakah keputusan dibuat menggunakan kaedah automatik?`,
  _ = `Kandungan haram`,
  _ = `Kandungan yang menyalahi undang-undang, merupakan tingkah laku yang merupakan kesalahan jenayah, menimbulkan liabiliti sivil atau melanggar mana-mana undang-undang tidak dibenarkan di Steam.`,
  _ = `Kandungan tidak serasi dengan terma dan syarat`,
  _ = `Kandungan di Steam mesti mematuhi terma %1$s dan %2$s.`,
  _ = `Peraturan Tingkah Laku Dalam Talian Steam`,
  _ = `Perjanjian Pelanggan Steam`,
  _ = `Laporan pengguna`,
  _ = `Tiada`,
  _ = `Ya`,
  _ = `Automatik sepenuhnya`,
  _ = `Separa automatik`,
  _ = `Kandungan disembunyikan`,
  _ = `Apabila membuat keputusan tentang kandungan atau akaun, kami mengambil kira kandungan yang terlibat, maklumat akaun yang berkaitan, maklumat yang diberikan melalui mekanisme pelaporan dan siasatan kami sendiri.`,
  _ = `(ruang letak untuk maklumat penyelesaian di luar mahkamah)`,
  _ = `Ya`,
  _ = `Tidak`,
  _ = `Serah`,
  _ = `Batal`,
  _ = `Penyelarasan pertikaian`,
  _ = `Sertakan sebarang maklumat sokongan untuk pertikaian anda:`,
  _ = `Asas bagi pertikaian anda`,
  _ = `Dengan mengklik %1$s, anda mengesahkan bahawa semua maklumat di sini adalah tepat, mengikut pengetahuan anda.`,
  _ = `Diselesaikan pada %1$s`,
  _ = `Diselesaikan pada %1$s, dipertikaikan oleh pemilik pada %2$s`,
  _ = `Diselesaikan pada %1$s, dipertikaikan oleh pemilik pada %2$s, pertikaian diselesaikan pada %3$s`,
  _ = `Dilaporkan pada %1$s`,
  _ = `Dilaporkan pada %1$s, diselesaikan pada %2$s`,
  _ = `Dilaporkan pada %1$s, diselesaikan pada %2$s, dipertikaikan pada %3$s`,
  _ = `Dilaporkan pada %1$s, diselesaikan pada %2$s, dipertikaikan pada %3$s, pertikaian diselesaikan pada %4$s`,
  _ = `mesej sembang daripada %1$s dihantar pada %2$s`,
  _ = `mesej bilik sembang daripada %1$s dihantar pada %2$s`,
  _ = `ID Laporan %1$s`,
  _ = `thread komen`,
  _ = `Laporkan kandungan`,
  _ = `Ini hanya untuk melaporkan spam, pengiklanan, kandungan haram dan siaran bermasalah (gangguan, pergaduhan, atau biadab).`,
  _ = `Apakah jenis isu yang anda laporkan?`,
  _ = `Hantar Laporan`,
  _ = `Laporkan sebagai:`,
  _ = `Kembali`,
  _ = `Sila berikan maklumat tambahan yang berkaitan dengan laporan anda. Dengan menghantar laporan ini, anda mengesahkan bahawa kandungannya benar dan tepat mengikut pengetahuan anda.`,
  _ = `Tambah sebarang maklumat tambahan di sini.`,
  _ = `Pelanggaran hak cipta`,
  _ = `Aduan tanda dagangan`,
  _ = `Nama anda (pilihan)`,
  _ = `Kasar`,
  _ = `Aktiviti komersial`,
  _ = `Pelanggaran maklumat pengguna`,
  _ = `Mengeksploitasi individu bawah umur`,
  _ = `Mengganggu`,
  _ = `Gangguan`,
  _ = `Bahan tanpa persetujuan`,
  _ = `Kebogelan atau kandungan seksual`,
  _ = `Luar Topik`,
  _ = `Pelanggaran perlindungan data dan privasi`,
  _ = `Ulasan tidak sahih/dimanipulasi`,
  _ = `Penipuan dan kecurian`,
  _ = `Keganasan`,
  _ = `Keganasan dan mencederakan diri`,
  _ = `Wacana sivik dan pilihan raya`,
  _ = `Kandungan Mencurigakan`,
  _ = `Kandungan Tidak Sesuai`,
  _ = `Lain-lain`,
  _ = `Pancingan data, penipuan, menyamar sebagai rakan atau Sokongan Steam`,
  _ = `Gangguan, spam, imej yang tidak sesuai`,
  _ = `(Tidak diketahui)`,
  _ = `(Tidak diketahui)`,
  _ = `(Tidak diketahui)`,
  _ = `Gangguan`,
  _ = `Buli dan intimidasi`,
  _ = `Mengintip`,
  _ = `Dedah maya`,
  _ = `Gangguan lain`,
  _ = `Menggalakkan keganasan`,
  _ = `Membincang atau menggalakkan mencederakan diri`,
  _ = `Membincangkan atau menggalakkan bunuh diri`,
  _ = `Keganasan atau mencederakan diri lain`,
  _ = `Ancaman keganasan yang boleh dipercayai`,
  _ = `Petikan kandungan yang diselaraskan`,
  _ = `Memancing data atau kecurian akaun`,
  _ = `Manipulasi pilihan raya atau wacana awam`,
  _ = `Percubaan penipuan`,
  _ = `Pautan ke kandungan berniat jahat`,
  _ = `Penyamaran`,
  _ = `Penipuan atau kecurian lain`,
  _ = `Menggalakkan keganasan`,
  _ = `Menganjurkan keganasan`,
  _ = `Lain-lain berkaitan keganasan`,
  _ = `Penyalahgunaan disasarkan`,
  _ = `Menamakan dan memalukan`,
  _ = `Diskriminasi`,
  _ = `Penyalahgunaan lain`,
  _ = `Hasut Maya`,
  _ = `Mengumpan`,
  _ = `Menyimpang`,
  _ = `Tingkah laku mengganggu lain`,
  _ = `Spam`,
  _ = `Merayu`,
  _ = `Menyiarkan semula`,
  _ = `Luar topik lain`,
  _ = `Kandungan seksual melibatkan individu bawah umur`,
  _ = `Memujuk atau memperdaya individu bawah umur`,
  _ = `Eksploitasi lain terhadap individu bawah umur`,
  _ = `Kebogelan atau kandungan seksual`,
  _ = `Bahan tanpa persetujuan`,
  _ = `Pengiklanan`,
  _ = `Pautan rujukan`,
  _ = `Perjudian`,
  _ = `Cabutan Bertuah`,
  _ = `Aktiviti komersial lain`,
  _ = `Ulasan tidak sahih atau dimanipulasi`,
  _ = `Iklan tersembunyi atau komunikasi komersial`,
  _ = `Maklumat yang mengelirukan tentang ciri-ciri barangan dan perkhidmatan`,
  _ = `Maklumat yang mengelirukan tentang hak pengguna`,
  _ = `Tidak mematuhi peraturan harga`,
  _ = `Hak untuk dilupakan`,
  _ = `Tiada asas sah untuk pemprosesan data`,
  _ = `Pelanggaran lain bagi perlindungan data atau privasi`,
  _ = `Gangguan terhadap wanita`,
  _ = `Buli dan intimidasi terhadap wanita`,
  _ = `Mengintai wanita`,
  _ = `Pendedahan maya terhadap wanita`,
  _ = `Gangguan lain terhadap wanita`,
  _ = `Menggalakkan keganasan terhadap wanita`,
  _ = `Penyalahgunaan yang disasarkan terhadap wanita`,
  _ = `Kandungan seksual deepfake melibatkan individu bawah umur`,
  _ = `Bahan tanpa keizinan terhadap wanita`,
  _ = `Bahan tanpa keizinan deepfake terhadap wanita`,
  _ = `Bahan tanpa keizinan deepfake`,
  _ = `Disasarkan kepada wanita`,
  _ = `Deepfake`,
  _ = `Cetak Rompak`,
  _ = `Melanggar Syarat Perkhidmatan (ToS) Steam`,
  _ = `Salah kategori`,
  _ = `Memintas penapis kata kesat`,
  _ = `Laporan dihantar`,
  _ = `Terima kasih kerana menghantar laporan anda. Laporan ini telah dihantar untuk penyelarasan.`,
  _ = `Terima kasih kerana menghantar laporan anda. Kami telah mengumpulkan sebahagian kecil log sembang dan menghantarnya untuk penyelarasan. Anda tidak perlu mengambil sebarang tindakan tambahan.`,
  _ = `Ralat menghantar laporan`,
  _ = `Ralat telah berlaku semasa menghantar laporan anda. Sila cuba lagi nanti.`,
  _ = `Anda telah dilarang buat sementara waktu daripada melaporkan kandungan.`,
  _ = `Anda boleh mengambil tindakan tambahan untuk mencegah mesej pada masa hadapan:`,
  _ = `Pengguna ini telah disekat secara automatik – anda tidak akan menerima mesej daripada mereka lagi.`,
  _ = `Batalkan sekatan`,
  _ = `Nyahikuti Rakan`,
  _ = `Pengguna ini masih berada dalam Senarai Rakan anda – anda boleh memilih untuk mengalih keluar mereka sebagai rakan. Anda akan hilang daripada Senarai Rakan mereka tanpa sebarang notis.`,
  _ = `Dinyahikuti Rakan`,
  _ = `Ketahui lebih lanjut tentang cara menangani salah laku di Steam`,
  _ = `Thread forum`,
  _ = `Thread komen`,
  _ = `Mesej Sembang Rakan`,
  _ = `Mesej Bilik Sembang`,
  _ = `Kumpulan Sembang`,
  _ = `Imej UGC`,
  _ = `(Tidak diketahui)`,
  _ = `Selesaikan tanpa tindakan`,
  _ = `Menunggu penyelarasan`,
  _ = `Disemak: tiada tindakan diperlukan`,
  _ = `Kandungan dibersihkan dengan segera`,
  _ = `Kandungan dialih keluar`,
  _ = `Kandungan dilabel semula`,
  _ = `Akaun dikunci disebabkan kandungan yang mencurigakan`,
  _ = `Keistimewaan Komuniti Steam digantung`,
  _ = `Dialih keluar dan diberi amaran`,
  _ = `Dialih keluar dan dilarang dari hab`,
  _ = `Dialih keluar dan ditendang dari kumpulan`,
  _ = `Dibenarkan`,
  _ = `Tidak diketahui`,
  _ = `Dibebaskan`,
  _ = `Laporan terbuka terakhir dibatalkan`,
  _ = `Resolution disputed`,
  _ = `Escalated`,
  _ = `Dibenarkan`,
  _ = `Penyelarasan dikekalkan`,
  _ = `Subjek belum diselesaikan`,
  _ = `Butiran Subjek dikemas kini`,
  _ = `Dikunci`,
  _ = `Buka`,
  _ = `Dipadam`,
  _ = `Amaran diisukan`,
  _ = `Dilarang daripada hab kandungan`,
  _ = `Dilarang daripada komuniti Steam`,
  _ = `Pertukaran dilarang`,
  _ = `Kandungan ditandakan sebagai mencurigakan`,
  _ = `Tetapkan semula kandungan pengarang`,
  _ = `Escalated to Valve for CSAM`,
  _ = `Escalated to Valve for terrorism`,
  _ = `Dituntut`,
  _ = `Dikeluarkan`,
  _ = `Mesej peribadi dihantar`,
  _ = `Tindakan tidak diketahui`,
  _ = `Penyelarasan dipertikaikan oleh pemilik`,
  _ = `Nota: %1$s`,
  _ = `Amaran: %1$s`,
  _ = `Larangan: %1$s`,
  _ = `Notis Pengalihan Keluar Kandungan: %1$s`,
  _ = `Penipuan, pancingan data, dan kecurian`,
  _ = `Pancingan data, mencuri, penipuan, memautkan kepada kandungan berniat jahat, mencipta identiti palsu dengan tujuan untuk mengelirukan orang lain`,
  _ = `Privasi`,
  _ = `Dedah maya, memburu, menamakan dan memalukan, pengedaran imej intim tanpa persetujuan`,
  _ = `Keselamatan kanak-kanak`,
  _ = `Mengeksploitasi kanak-kanak di bawah umur, penderaan seksual kanak-kanak, antunan kanak-kanak di bawah umur, penderaan kanak-kanak`,
  _ = `Menggalakkan keganasan`,
  _ = `Menggalakkan atau memudahkan keganasan dunia sebenar, mencederakan diri sendiri, atau bunuh diri, ancaman bahaya, keganasan`,
  _ = `Gangguan, buli, dan tingkah laku mengganggu`,
  _ = `Tingkah laku yang mengganggu forum, termasuk hasut maya, bahasa yang kasar, spam, atau menyiarkan semula kandungan tertutup atau dipadam`,
  _ = `Sensitif atau mengganggu`,
  _ = `Imej bogel atau eksplisit seksual orang sebenar, kandungan dewasa yang tidak dilabel dengan tepat dan sekatan umur, gambaran keganasan atau keganasan yang nyata atau mengganggu`,
  _ = `Pengiklanan dan aktiviti komersial`,
  _ = `Pautan rujukan, peraduan, cabutan bertuah, perjudian, pembelian atau penjualan akaun Steam`,
  _ = `Menipu dan cetak rompak`,
  _ = `Perbincangan atau promosi penipuan, eksploitasi, dan cetak rompak permainan`,
  _ = `Lain-lain`,
  _ = `Kandungan ini adalah haram atau tidak sesuai untuk alasan yang tidak ditunjukkan di sini`,
  _ = `Harta intelek`,
  _ = `Melanggar hak cipta atau tanda dagangan, atau melangkaui sekatan lesen`,
  _ = `Melaporkan kandungan untuk: %1$s`,
  _ = `Anda akan meninggalkan halaman ini dan pergi ke borang laporan hak cipta Steam.`,
  _ = `Anda akan meninggalkan halaman ini dan pergi ke borang laporan tanda dagangan Steam.`,
  _ = `Kami telah menerima laporan anda`,
  _ = `Anda melaporkan %1$s`,
  _ = `Laporan anda telah diselesaikan`,
  _ = `Tiada tindakan diambil ke atas %1$s`,
  _ = `Laporan anda telah diselesaikan`,
  _ = `Tindakan telah diambil pada %1$s`,
  _ = `Kami telah menerima pertikaian anda`,
  _ = `You disputed the moderation of %1$s`,
  _ = `Pertikaian anda telah diselesaikan`,
  _ = `Tiada tindakan diambil ke atas %1$s`,
  _ = `Pertikaian anda telah diselesaikan`,
  _ = `Tindakan telah diambil pada %1$s`,
  _ = `Anda melaporkan %1$s`,
  _ = `Steam's moderation staff will evaluate the content and take action in accordance with Steam's %1$s. You will receive a Steam notification when the report is resolved.`,
  _ = `Peraturan & Garis Panduan Komuniti`,
  _ = `Kami juga mengesyorkan agar anda menyemak maklumat dalam %1$s.`,
  _ = `Kami telah menyelesaikan laporan anda`,
  _ = `Selepas penilaian oleh %1$s, kami mendapati bahawa kandungan tidak melanggar %2$s Steam.`,
  _ = `Anda juga mempunyai hak untuk mendapatkan penyelesaian melalui badan penyelesaian pertikaian luar mahkamah yang disahkan, atau untuk mendapatkan penyelesaian kehakiman di hadapan mahkamah yang cekap.`,
  _ = `Jika anda tidak bersetuju dengan keputusan ini, anda boleh mengemukakan satu %1$s.`,
  _ = `pertikaian`,
  _ = `Menangani penyalahgunaan, gangguan dan salah laku lain di Steam`,
  _ = `Hantar pertikaian`,
  _ = `Sila berikan sebarang maklumat tentang kenapa anda percaya keputusan Steam mengenai kandungan ini adalah salah.`,
  _ = `Anda akan dimaklumkan apabila pertikaian anda telah diselesaikan.`,
  _ = `Ralat telah berlaku. Sila cuba lagi nanti.`,
  _ = `Kami telah mengambil tindakan berdasarkan laporan anda`,
  _ = `Selepas penilaian oleh %1$s, kami mendapati bahawa kandungan tersebut melanggar %2$s Steam.`,
  _ = `Terima kasih kerana membantu kami mengekalkan persekitaran yang selamat di Steam.`,
  _ = `seorang moderator`,
  _ = `sistem pemeriksaan kandungan automatik kami`,
  _ = `seorang moderator dengan bantuan automatik`,
  _ = `Kami telah menerima pertikaian anda`,
  _ = `Kakitangan semakan pertikaian Steam akan menilai semula kandungannya.`,
  _ = `Anda akan menerima pemberitahuan apabila semakan selesai.`,
  _ = `Kami telah menyelesaikan semakan kami`,
  _ = `After evaluation by Steam's dispute review staff, the content was found to not be in violation of Steam's\xA0%1$s. In particular, we found no evidence of: %2$s.`,
  _ = `Jika anda percaya bahawa ini adalah salah, anda mempunyai hak untuk mendapatkan penyelesaian melalui badan penyelesaian pertikaian luar mahkamah yang disahkan, atau untuk mendapatkan ganti rugi kehakiman di hadapan mahkamah yang cekap.`,
  _ = `Kami telah menyelesaikan semakan kami`,
  _ = `After evaluation by Steam's disputes review staff the content you reported was found to be in violation of Steam's\xA0%1$s. In particular, it was found to be: %2$s`,
  _ = `Terima kasih kerana membantu kami mengekalkan persekitaran yang selamat di Steam.`,
  _ = `Butiran Laporan`,
  _ = `Anda menulis:`,
  _ = `siaran forum`,
  _ = `%1$s pada topik '%2$s' pada %3$s Hab`,
  _ = `%2$s di Hab %1$s`,
  _ = `Laporkan Kandungan Ini`,
  _ = `Log masuk ke Komuniti Steam untuk melaporkan kandungan yang tidak sesuai atau haram.`,
  _ = `Jika anda tidak boleh log masuk, anda boleh <1>memfailkan laporan tanpa nama</1>.`,
  _ = `failkan laporan tanpa nama`,
  _ = `Log Masuk`,
  _ = `Sertai Steam`,
  _ = `Cipta Akaun`,
  _ = `%1$s atau %2$s`,
  _ = `Memuatkan cooldown semasa`,
  _ = `Ralat memuatkan cooldown semasa!`,
  _ = `Pelaporan cooldown tamat tempoh pada %1$s`,
  _ = `Tiada cooldown semasa`,
  _ = `hari`,
  _ = `Cooldown baharu untuk pengguna:`,
  _ = `Kosongkan cooldown`,
  _ = `(%1$s hari)`,
  _ = `Tetapkan masa cooldown pelaporan`,
  _ = `Sekat pengguna daripada melaporkan kandungan atau mempertikaikan penyelarasan apabila mereka telah menyalahgunakan sistem.`,
  _ = `Tetapkan masa cooldown`,
  _ = `Kosongkan laporan pengguna ini yang tidak diselesaikan`,
  _ = `Laporan %1$s/%2$s dibebaskan, %3$s/%4$s pada minggu lepas.`,
  _ = ``,
  _ = {
    moderation_contentreports_title: _,
    moderation_submittedbyyou_title: _,
    moderation_onyourcontent_title: _,
    moderation_acquitted_description: _,
    moderation_maydispute_description: _,
    moderation_state_disputed: _,
    moderation_state_communicationblocked: _,
    moderation_sanctioned_for_reason: _,
    moderation_statementofreasons_header: _,
    moderation_statementofreasons_visibilityrestriction: _,
    moderation_statementofreasons_factsandcircumstances: _,
    moderation_statementofreasons_decisionground: _,
    moderation_statementofreasons_legalground: _,
    moderation_statementofreasons_contractualground: _,
    moderation_statementofreasons_explanationwhy: _,
    moderation_statementofreasons_contenttype: _,
    moderation_statementofreasons_informationsource: _,
    moderation_statementofreasons_automatedidentification: _,
    moderation_statementofreasons_automateddecision: _,
    moderation_statementofreasons_decisionground_legal: _,
    moderation_statementofreasons_explanation_legal: _,
    moderation_statementofreasons_decisionground_genericcontractual: _,
    moderation_statementofreasons_explanation_genericcontractual: _,
    moderation_statementofreasons_explanation_genericcontractual_steam_online_conduct_rules:
      _,
    moderation_statementofreasons_explanation_genericcontractual_steam_subscriber_agreement:
      _,
    moderation_statementofreasons_informationsource_report: _,
    moderation_none: _,
    moderation_automateddetection: `Ya`,
    moderation_fullyautomatedresolution: _,
    moderation_partiallyautomatedresolution: _,
    moderation_statementofreasons_visibilityrestriction_removed: _,
    moderation_statementofreasons_factsandcircumstances_text: _,
    moderation_outofcourtsettlement: _,
    moderation_yes: `Ya`,
    moderation_no: _,
    moderation_submit: _,
    moderation_cancel: _,
    moderation_dispute_title: _,
    moderation_dispute_description: _,
    moderation_detailsplaceholder: _,
    moderation_attestation: _,
    moderation_subjectreportedandresolved: _,
    moderation_subjectreporteddisputed: _,
    moderation_subjectdisputeresolved: _,
    moderation_reportedon: _,
    moderation_reportedandresolvedon: _,
    moderation_reportedanddisputed: _,
    moderation_reporteddisputeresolved: _,
    moderation_chatreport_desc: _,
    moderation_chatgroupmsgreport_desc: _,
    moderation_reportid: _,
    moderation_commentthread_desc: _,
    ReportContent_Title: _,
    ReportContent_Description: _,
    ReportContent_PickAReason: _,
    ReportContent_ReportButton: _,
    ReportContent_ReportAs: _,
    ReportContent_Back: _,
    ReportContent_Attestation: _,
    ReportContent_DetailsPlaceholder: _,
    ReportContent_CopyrightInfringement: _,
    ReportContent_TrademarkComplaint: _,
    ReportContent_YourNamePlaceholder: _,
    ContentReportReasonCategory_Abusive: _,
    ContentReportReasonCategory_Commercial: _,
    ContentReportReasonCategory_ConsumerInformation: _,
    ContentReportReasonCategory_CSAM: _,
    ContentReportReasonCategory_Disruptive: _,
    ContentReportReasonCategory_Harassment: _,
    ContentReportReasonCategory_Nonconsensual: _,
    ContentReportReasonCategory_NudityOrSexualContent: _,
    ContentReportReasonCategory_Offtopic: _,
    ContentReportReasonCategory_Privacy: _,
    ContentReportReasonCategory_ReviewManipulation: _,
    ContentReportReasonCategory_ScamsAndTheft: _,
    ContentReportReasonCategory_Terrorism: _,
    ContentReportReasonCategory_ViolenceAndSelfHarm: _,
    ContentReportReasonCategory_CivicDiscourse: _,
    ContentReportReasonCategory_Suspicious: _,
    ContentReportReasonCategory_Inappropriate: _,
    ContentReportReasonCategory_Other: _,
    ContentReportReasonCategoryDesc_Suspicious: _,
    ContentReportReasonCategoryDesc_Inappropriate: _,
    ContentReportReason_Invalid: _,
    ContentReportReason_None: _,
    ContentReportReason_Unknown: _,
    ContentReportReason_Harassment: _,
    ContentReportReason_BullyingAndIntimidation: _,
    ContentReportReason_Stalking: _,
    ContentReportReason_Doxxing: _,
    ContentReportReason_OtherHarassment: _,
    ContentReportReason_EncouragingViolence: _,
    ContentReportReason_EncouragingSelfHarm: _,
    ContentReportReason_EncouragingSuicide: _,
    ContentReportReason_OtherViolenceOrSelfHarm: _,
    ContentReportReason_CredibleThreatOfViolence: _,
    ContentReportReason_QuotesModeratedContent: _,
    ContentReportReason_PhishingOrAccountTheft: _,
    ContentReportReason_NegativeEffectonDiscourseOrElections: _,
    ContentReportReason_AttemptedScamming: _,
    ContentReportReason_LinkingToMaliciousContent: _,
    ContentReportReason_Impersonation: _,
    ContentReportReason_OtherScamsAndTheft: _,
    ContentReportReason_EncouragingTerrorism: _,
    ContentReportReason_OrganizingTerrorism: _,
    ContentReportReason_OtherTerrorism: _,
    ContentReportReason_TargetedAbuse: _,
    ContentReportReason_NamingAndShaming: _,
    ContentReportReason_Discrimination: _,
    ContentReportReason_OtherAbuse: _,
    ContentReportReason_Trolling: _,
    ContentReportReason_Baiting: _,
    ContentReportReason_Derailing: _,
    ContentReportReason_OtherDisruptive: _,
    ContentReportReason_Spam: _,
    ContentReportReason_Begging: _,
    ContentReportReason_Reposting: _,
    ContentReportReason_OtherOffTopic: _,
    ContentReportReason_CSAMSexualContent: _,
    ContentReportReason_CSAMGroomingOrEnticement: _,
    ContentReportReason_CSAMOther: _,
    ContentReportReason_NudityOrSexualContent: _,
    ContentReportReason_NonConsensualMaterial: _,
    ContentReportReason_Advertising: _,
    ContentReportReason_ReferralLinks: _,
    ContentReportReason_Gambling: _,
    ContentReportReason_Raffles: _,
    ContentReportReason_OtherCommercialActivity: _,
    ContentReportReason_InauthenticReview: _,
    ContentReportReason_HiddenAdvertisementOrCommercialCommunication: _,
    ContentReportReason_MisleadingInformationAboutGoodsOrServices: _,
    ContentReportReason_MisleadingInformationAboutConsumerRights: _,
    ContentReportReason_NoncomplianceWithPricingRegulations: _,
    ContentReportReason_RightToBeForgottenViolation: _,
    ContentReportReason_MissingProcessingGroundForData: _,
    ContentReportReason_OtherDataProtectionAndPrivacyViolation: _,
    ContentReportReason_GenderedHarassment: _,
    ContentReportReason_GenderedBullyingAndIntimidation: _,
    ContentReportReason_GenderedStalking: _,
    ContentReportReason_GenderedDoxxing: _,
    ContentReportReason_GenderedOtherHarassment: _,
    ContentReportReason_GenderedEncouragingViolence: _,
    ContentReportReason_GenderedTargetedAbuse: _,
    ContentReportReason_CSAMFakedSexualContent: _,
    ContentReportReason_GenderedNonConsensualMaterial: _,
    ContentReportReason_FakedGenderedNonConsensualMaterial: _,
    ContentReportReason_FakedNonConsensualMaterial: _,
    ContentReportReason_Gendered: _,
    ContentReportReason_Deepfake: _,
    ContentReportReason_Piracy: _,
    ContentReportReason_ToSViolation: _,
    ContentReportReason_Miscategorized: _,
    ContentReportReason_BypassingProfanityFilter: _,
    ContentReportSubmitted_Title: _,
    ContentReportSubmitted_Description: _,
    ContentReportSubmitted_Chat_Description: _,
    ContentReportSubmissionError_Title: _,
    ContentReportSubmissionError_Description: _,
    ContentReportSubmissionOnCooldown_Description: _,
    ContentReport_FriendOptions_CallToAction: _,
    ContentReport_FriendOptions_BlockedDesc: _,
    ContentReport_FriendOptions_Unblock: _,
    ContentReport_FriendOptions_Remove: _,
    ContentReport_FriendOptions_RemoveDesc: _,
    ContentReport_FriendOptions_RemoveSuccess: _,
    ContentReport_LearnMore_Misconduct: _,
    moderation_subjecttype_forumpost: _,
    moderation_subjecttype_commentthread: _,
    moderation_subjecttype_friendchatmsg: _,
    moderation_subjecttype_chatroommsg: _,
    moderation_subjecttype_chatgroup: _,
    moderation_subjettype_ugcfile: _,
    moderation_subjecttype_unknown: _,
    moderation_resolvewithnoaction: _,
    moderation_resolutionstatus_pending: _,
    moderation_resolutionstatus_acquitted: _,
    moderation_resolutionstatus_purged: _,
    moderation_resolutionstatus_removed: _,
    moderation_resolutionstatus_relabelled: _,
    moderation_resolutionstatus_suspicious: _,
    moderation_resolutionstatus_harassmentstrike: _,
    moderation_resolutionstatus_removeandwarn: _,
    moderation_resolutionstatus_removeandban: _,
    moderation_resolutionstatus_removeandkick: _,
    moderation_resolutionstatus_sanctioned: _,
    moderation_resolutionstatus_unknown: _,
    moderationaction_acquitted: _,
    moderationaction_cancelled: _,
    moderationaction_disputed: _,
    moderationaction_escalated: _,
    moderationaction_sanctioned: _,
    moderationaction_sustained: _,
    moderationaction_unresolved: _,
    moderationaction_updated: _,
    moderationaction_locked: _,
    moderationaction_unlocked: _,
    moderationaction_deleted: _,
    moderationaction_warned: _,
    moderationaction_banned_from_hub: _,
    moderationaction_banned_from_community: _,
    moderationaction_trade_banned: _,
    moderationaction_marked_as_suspicious: _,
    moderationaction_reset_content: _,
    moderationaction_escalated_for_csam: _,
    moderationaction_escalated_for_terrorism: _,
    moderationaction_claimed: _,
    moderationaction_released: _,
    moderationaction_privatemessaged: _,
    moderationaction_unknown: _,
    moderationaction_ownerdisputed: _,
    moderatormessage_count_note: _,
    moderatormessage_count_warning: _,
    moderatormessage_count_bannotice: _,
    moderatormessage_count_contentremoval: _,
    reportforumpost_reason_scams: _,
    reportforumpost_description_scams: _,
    reportforumpost_reason_privacy: _,
    reportforumpost_description_privacy: _,
    reportforumpost_reason_childsafety: _,
    reportforumpost_description_childsafety: _,
    reportforumpost_reason_promotingviolence: _,
    reportforumpost_description_promotingviolence: _,
    reportforumpost_reason_disruptive: _,
    reportforumpost_description_disruptive: _,
    reportforumpost_reason_sensitiveordisturbing: _,
    reportforumpost_description_sensitiveordisturbing: _,
    reportforumpost_reason_advertising: _,
    reportforumpost_description_advertising: _,
    reportforumpost_reason_cheating: _,
    reportforumpost_description_cheating: _,
    reportforumpost_reason_notfound: _,
    reportforumpost_description_notfound: _,
    reportforumpost_reason_intellectualproperty: _,
    reportforumpost_description_intellectualproperty: _,
    reportforumpost_reasonforreport: _,
    WarnBeforeNavigatingToCopyrightReportForm: _,
    WarnBeforeNavigatingToTrademarkReportForm: _,
    reportedcontentlist_unresolved_title: _,
    reportedcontentlist_unresolved_body: _,
    reportedcontentlist_acquitted_title: _,
    reportedcontentlist_acquitted_body: _,
    reportedcontentlist_sanctioned_title: _,
    reportedcontentlist_sanctioned_body: _,
    reportedcontentlist_disputed_title: _,
    reportedcontentlist_disputed_body: _,
    reportedcontentlist_disputedenied_title: _,
    reportedcontentlist_disputedenied_body: _,
    reportedcontentlist_disputesanctioned_title: _,
    reportedcontentlist_disputesanctioned_body: _,
    reportedcontent_unresolved_1: _,
    reportedcontent_unresolved_2: _,
    reportedcontent_community_guidelines: _,
    reportedcontent_unresolved_3: _,
    reportedcontent_acquitted_1: _,
    reportedcontent_acquitted_2: _,
    reportedcontent_acquitted_2_eu_addendum: _,
    reportedcontent_dispute_submit_dispute: _,
    reportedcontent_dispute_acquittal: _,
    reportedcontent_harassment_guidance: _,
    reportedcontent_submit_dispute_title: _,
    reportedcontent_submit_dispute_description: _,
    reportedcontent_dispute_acknowledged: _,
    reportedcontent_error: _,
    reportedcontent_sanctioned_1: _,
    reportedcontent_sanctioned_2: _,
    reportedcontent_sanctioned_3: _,
    reportedcontent_moderatedby_human: _,
    reportedcontent_moderatedby_machine: _,
    reportedcontent_moderatedby_assistedhuman: _,
    reportedcontent_disputed_1: _,
    reportedcontent_disputed_2: _,
    reportedcontent_disputed_3: _,
    reportedcontent_disputedenied_1: _,
    reportedcontent_disputedenied_2: _,
    reportedcontent_disputedenied_eu_addendum: _,
    reportedcontent_disputesanctioned_1: _,
    reportedcontent_disputesanctioned_2: _,
    reportedcontent_disputesanctioned_3: _,
    reportedcontent_content_report_breadcrumb: _,
    reportedcontent_you_wrote: _,
    reportedcontent_summary_forumpost: _,
    reportedcontent_summary_forumpost_on: _,
    reportedcontent_summary_forumtopic_in: _,
    anonymousreport_title: _,
    anonymousreport_description: _,
    anonymousreport_footer: _,
    anonymousreport_footer_action: _,
    anonymousreport_signin: _,
    anonymousreport_join: _,
    anonymousreport_createaccount: _,
    anonymousreport_signin_or_join: _,
    setcooldown_loading: _,
    setcooldown_errorloading: _,
    setcooldown_expireson: _,
    setcooldown_nocooldown: _,
    setcooldown_days: _,
    setcooldown_newcooldownlabel: _,
    setcooldown_clearcooldown: _,
    setcooldown_cooldownsummary: _,
    setcooldown_dialogtitle: _,
    setcooldown_dialogdescription: _,
    setcooldown_setbutton: _,
    setcooldown_clearopenreports: _,
    setcooldown_statssummary: _,
    nocomma: ``,
  };
export {
  _ as ContentReportReasonCategoryDesc_Inappropriate,
  _ as ContentReportReasonCategoryDesc_Suspicious,
  _ as ContentReportReasonCategory_Abusive,
  _ as ContentReportReasonCategory_CSAM,
  _ as ContentReportReasonCategory_CivicDiscourse,
  _ as ContentReportReasonCategory_Commercial,
  _ as ContentReportReasonCategory_ConsumerInformation,
  _ as ContentReportReasonCategory_Disruptive,
  _ as ContentReportReasonCategory_Harassment,
  _ as ContentReportReasonCategory_Inappropriate,
  _ as ContentReportReasonCategory_Nonconsensual,
  _ as ContentReportReasonCategory_NudityOrSexualContent,
  _ as ContentReportReasonCategory_Offtopic,
  _ as ContentReportReasonCategory_Other,
  _ as ContentReportReasonCategory_Privacy,
  _ as ContentReportReasonCategory_ReviewManipulation,
  _ as ContentReportReasonCategory_ScamsAndTheft,
  _ as ContentReportReasonCategory_Suspicious,
  _ as ContentReportReasonCategory_Terrorism,
  _ as ContentReportReasonCategory_ViolenceAndSelfHarm,
  _ as ContentReportReason_Advertising,
  _ as ContentReportReason_AttemptedScamming,
  _ as ContentReportReason_Baiting,
  _ as ContentReportReason_Begging,
  _ as ContentReportReason_BullyingAndIntimidation,
  _ as ContentReportReason_BypassingProfanityFilter,
  _ as ContentReportReason_CSAMFakedSexualContent,
  _ as ContentReportReason_CSAMGroomingOrEnticement,
  _ as ContentReportReason_CSAMOther,
  _ as ContentReportReason_CSAMSexualContent,
  _ as ContentReportReason_CredibleThreatOfViolence,
  _ as ContentReportReason_Deepfake,
  _ as ContentReportReason_Derailing,
  _ as ContentReportReason_Discrimination,
  _ as ContentReportReason_Doxxing,
  _ as ContentReportReason_EncouragingSelfHarm,
  _ as ContentReportReason_EncouragingSuicide,
  _ as ContentReportReason_EncouragingTerrorism,
  _ as ContentReportReason_EncouragingViolence,
  _ as ContentReportReason_FakedGenderedNonConsensualMaterial,
  _ as ContentReportReason_FakedNonConsensualMaterial,
  _ as ContentReportReason_Gambling,
  _ as ContentReportReason_Gendered,
  _ as ContentReportReason_GenderedBullyingAndIntimidation,
  _ as ContentReportReason_GenderedDoxxing,
  _ as ContentReportReason_GenderedEncouragingViolence,
  _ as ContentReportReason_GenderedHarassment,
  _ as ContentReportReason_GenderedNonConsensualMaterial,
  _ as ContentReportReason_GenderedOtherHarassment,
  _ as ContentReportReason_GenderedStalking,
  _ as ContentReportReason_GenderedTargetedAbuse,
  _ as ContentReportReason_Harassment,
  _ as ContentReportReason_HiddenAdvertisementOrCommercialCommunication,
  _ as ContentReportReason_Impersonation,
  _ as ContentReportReason_InauthenticReview,
  _ as ContentReportReason_Invalid,
  _ as ContentReportReason_LinkingToMaliciousContent,
  _ as ContentReportReason_Miscategorized,
  _ as ContentReportReason_MisleadingInformationAboutConsumerRights,
  _ as ContentReportReason_MisleadingInformationAboutGoodsOrServices,
  _ as ContentReportReason_MissingProcessingGroundForData,
  _ as ContentReportReason_NamingAndShaming,
  _ as ContentReportReason_NegativeEffectonDiscourseOrElections,
  _ as ContentReportReason_NonConsensualMaterial,
  _ as ContentReportReason_NoncomplianceWithPricingRegulations,
  _ as ContentReportReason_None,
  _ as ContentReportReason_NudityOrSexualContent,
  _ as ContentReportReason_OrganizingTerrorism,
  _ as ContentReportReason_OtherAbuse,
  _ as ContentReportReason_OtherCommercialActivity,
  _ as ContentReportReason_OtherDataProtectionAndPrivacyViolation,
  _ as ContentReportReason_OtherDisruptive,
  _ as ContentReportReason_OtherHarassment,
  _ as ContentReportReason_OtherOffTopic,
  _ as ContentReportReason_OtherScamsAndTheft,
  _ as ContentReportReason_OtherTerrorism,
  _ as ContentReportReason_OtherViolenceOrSelfHarm,
  _ as ContentReportReason_PhishingOrAccountTheft,
  _ as ContentReportReason_Piracy,
  _ as ContentReportReason_QuotesModeratedContent,
  _ as ContentReportReason_Raffles,
  _ as ContentReportReason_ReferralLinks,
  _ as ContentReportReason_Reposting,
  _ as ContentReportReason_RightToBeForgottenViolation,
  _ as ContentReportReason_Spam,
  _ as ContentReportReason_Stalking,
  _ as ContentReportReason_TargetedAbuse,
  _ as ContentReportReason_ToSViolation,
  _ as ContentReportReason_Trolling,
  _ as ContentReportReason_Unknown,
  _ as ContentReportSubmissionError_Description,
  _ as ContentReportSubmissionError_Title,
  _ as ContentReportSubmissionOnCooldown_Description,
  _ as ContentReportSubmitted_Chat_Description,
  _ as ContentReportSubmitted_Description,
  _ as ContentReportSubmitted_Title,
  _ as ContentReport_FriendOptions_BlockedDesc,
  _ as ContentReport_FriendOptions_CallToAction,
  _ as ContentReport_FriendOptions_Remove,
  _ as ContentReport_FriendOptions_RemoveDesc,
  _ as ContentReport_FriendOptions_RemoveSuccess,
  _ as ContentReport_FriendOptions_Unblock,
  _ as ContentReport_LearnMore_Misconduct,
  _ as ReportContent_Attestation,
  _ as ReportContent_Back,
  _ as ReportContent_CopyrightInfringement,
  _ as ReportContent_Description,
  _ as ReportContent_DetailsPlaceholder,
  _ as ReportContent_PickAReason,
  _ as ReportContent_ReportAs,
  _ as ReportContent_ReportButton,
  _ as ReportContent_Title,
  _ as ReportContent_TrademarkComplaint,
  _ as ReportContent_YourNamePlaceholder,
  _ as WarnBeforeNavigatingToCopyrightReportForm,
  _ as WarnBeforeNavigatingToTrademarkReportForm,
  _ as anonymousreport_createaccount,
  _ as anonymousreport_description,
  _ as anonymousreport_footer,
  _ as anonymousreport_footer_action,
  _ as anonymousreport_join,
  _ as anonymousreport_signin,
  _ as anonymousreport_signin_or_join,
  _ as anonymousreport_title,
  _ as default,
  _ as moderation_acquitted_description,
  _ as moderation_attestation,
  _ as moderation_automateddetection,
  _ as moderation_cancel,
  _ as moderation_chatgroupmsgreport_desc,
  _ as moderation_chatreport_desc,
  _ as moderation_commentthread_desc,
  _ as moderation_contentreports_title,
  _ as moderation_detailsplaceholder,
  _ as moderation_dispute_description,
  _ as moderation_dispute_title,
  _ as moderation_fullyautomatedresolution,
  _ as moderation_maydispute_description,
  _ as moderation_no,
  _ as moderation_none,
  _ as moderation_onyourcontent_title,
  _ as moderation_outofcourtsettlement,
  _ as moderation_partiallyautomatedresolution,
  _ as moderation_reportedanddisputed,
  _ as moderation_reportedandresolvedon,
  _ as moderation_reporteddisputeresolved,
  _ as moderation_reportedon,
  _ as moderation_reportid,
  _ as moderation_resolutionstatus_acquitted,
  _ as moderation_resolutionstatus_harassmentstrike,
  _ as moderation_resolutionstatus_pending,
  _ as moderation_resolutionstatus_purged,
  _ as moderation_resolutionstatus_relabelled,
  _ as moderation_resolutionstatus_removeandban,
  _ as moderation_resolutionstatus_removeandkick,
  _ as moderation_resolutionstatus_removeandwarn,
  _ as moderation_resolutionstatus_removed,
  _ as moderation_resolutionstatus_sanctioned,
  _ as moderation_resolutionstatus_suspicious,
  _ as moderation_resolutionstatus_unknown,
  _ as moderation_resolvewithnoaction,
  _ as moderation_sanctioned_for_reason,
  _ as moderation_state_communicationblocked,
  _ as moderation_state_disputed,
  _ as moderation_statementofreasons_automateddecision,
  _ as moderation_statementofreasons_automatedidentification,
  _ as moderation_statementofreasons_contenttype,
  _ as moderation_statementofreasons_contractualground,
  _ as moderation_statementofreasons_decisionground,
  _ as moderation_statementofreasons_decisionground_genericcontractual,
  _ as moderation_statementofreasons_decisionground_legal,
  _ as moderation_statementofreasons_explanation_genericcontractual,
  _ as moderation_statementofreasons_explanation_genericcontractual_steam_online_conduct_rules,
  _ as moderation_statementofreasons_explanation_genericcontractual_steam_subscriber_agreement,
  _ as moderation_statementofreasons_explanation_legal,
  _ as moderation_statementofreasons_explanationwhy,
  _ as moderation_statementofreasons_factsandcircumstances,
  _ as moderation_statementofreasons_factsandcircumstances_text,
  _ as moderation_statementofreasons_header,
  _ as moderation_statementofreasons_informationsource,
  _ as moderation_statementofreasons_informationsource_report,
  _ as moderation_statementofreasons_legalground,
  _ as moderation_statementofreasons_visibilityrestriction,
  _ as moderation_statementofreasons_visibilityrestriction_removed,
  _ as moderation_subjectdisputeresolved,
  _ as moderation_subjectreportedandresolved,
  _ as moderation_subjectreporteddisputed,
  _ as moderation_subjecttype_chatgroup,
  _ as moderation_subjecttype_chatroommsg,
  _ as moderation_subjecttype_commentthread,
  _ as moderation_subjecttype_forumpost,
  _ as moderation_subjecttype_friendchatmsg,
  _ as moderation_subjecttype_unknown,
  _ as moderation_subjettype_ugcfile,
  _ as moderation_submit,
  _ as moderation_submittedbyyou_title,
  _ as moderation_yes,
  _ as moderationaction_acquitted,
  _ as moderationaction_banned_from_community,
  _ as moderationaction_banned_from_hub,
  _ as moderationaction_cancelled,
  _ as moderationaction_claimed,
  _ as moderationaction_deleted,
  _ as moderationaction_disputed,
  _ as moderationaction_escalated,
  _ as moderationaction_escalated_for_csam,
  _ as moderationaction_escalated_for_terrorism,
  _ as moderationaction_locked,
  _ as moderationaction_marked_as_suspicious,
  _ as moderationaction_ownerdisputed,
  _ as moderationaction_privatemessaged,
  _ as moderationaction_released,
  _ as moderationaction_reset_content,
  _ as moderationaction_sanctioned,
  _ as moderationaction_sustained,
  _ as moderationaction_trade_banned,
  _ as moderationaction_unknown,
  _ as moderationaction_unlocked,
  _ as moderationaction_unresolved,
  _ as moderationaction_updated,
  _ as moderationaction_warned,
  _ as moderatormessage_count_bannotice,
  _ as moderatormessage_count_contentremoval,
  _ as moderatormessage_count_note,
  _ as moderatormessage_count_warning,
  _ as nocomma,
  _ as reportedcontent_acquitted_1,
  _ as reportedcontent_acquitted_2,
  _ as reportedcontent_acquitted_2_eu_addendum,
  _ as reportedcontent_community_guidelines,
  _ as reportedcontent_content_report_breadcrumb,
  _ as reportedcontent_dispute_acknowledged,
  _ as reportedcontent_dispute_acquittal,
  _ as reportedcontent_dispute_submit_dispute,
  _ as reportedcontent_disputed_1,
  _ as reportedcontent_disputed_2,
  _ as reportedcontent_disputed_3,
  _ as reportedcontent_disputedenied_1,
  _ as reportedcontent_disputedenied_2,
  _ as reportedcontent_disputedenied_eu_addendum,
  _ as reportedcontent_disputesanctioned_1,
  _ as reportedcontent_disputesanctioned_2,
  _ as reportedcontent_disputesanctioned_3,
  _ as reportedcontent_error,
  _ as reportedcontent_harassment_guidance,
  _ as reportedcontent_moderatedby_assistedhuman,
  _ as reportedcontent_moderatedby_human,
  _ as reportedcontent_moderatedby_machine,
  _ as reportedcontent_sanctioned_1,
  _ as reportedcontent_sanctioned_2,
  _ as reportedcontent_sanctioned_3,
  _ as reportedcontent_submit_dispute_description,
  _ as reportedcontent_submit_dispute_title,
  _ as reportedcontent_summary_forumpost,
  _ as reportedcontent_summary_forumpost_on,
  _ as reportedcontent_summary_forumtopic_in,
  _ as reportedcontent_unresolved_1,
  _ as reportedcontent_unresolved_2,
  _ as reportedcontent_unresolved_3,
  _ as reportedcontent_you_wrote,
  _ as reportedcontentlist_acquitted_body,
  _ as reportedcontentlist_acquitted_title,
  _ as reportedcontentlist_disputed_body,
  _ as reportedcontentlist_disputed_title,
  _ as reportedcontentlist_disputedenied_body,
  _ as reportedcontentlist_disputedenied_title,
  _ as reportedcontentlist_disputesanctioned_body,
  _ as reportedcontentlist_disputesanctioned_title,
  _ as reportedcontentlist_sanctioned_body,
  _ as reportedcontentlist_sanctioned_title,
  _ as reportedcontentlist_unresolved_body,
  _ as reportedcontentlist_unresolved_title,
  _ as reportforumpost_description_advertising,
  _ as reportforumpost_description_cheating,
  _ as reportforumpost_description_childsafety,
  _ as reportforumpost_description_disruptive,
  _ as reportforumpost_description_intellectualproperty,
  _ as reportforumpost_description_notfound,
  _ as reportforumpost_description_privacy,
  _ as reportforumpost_description_promotingviolence,
  _ as reportforumpost_description_scams,
  _ as reportforumpost_description_sensitiveordisturbing,
  _ as reportforumpost_reason_advertising,
  _ as reportforumpost_reason_cheating,
  _ as reportforumpost_reason_childsafety,
  _ as reportforumpost_reason_disruptive,
  _ as reportforumpost_reason_intellectualproperty,
  _ as reportforumpost_reason_notfound,
  _ as reportforumpost_reason_privacy,
  _ as reportforumpost_reason_promotingviolence,
  _ as reportforumpost_reason_scams,
  _ as reportforumpost_reason_sensitiveordisturbing,
  _ as reportforumpost_reasonforreport,
  _ as setcooldown_clearcooldown,
  _ as setcooldown_clearopenreports,
  _ as setcooldown_cooldownsummary,
  _ as setcooldown_days,
  _ as setcooldown_dialogdescription,
  _ as setcooldown_dialogtitle,
  _ as setcooldown_errorloading,
  _ as setcooldown_expireson,
  _ as setcooldown_loading,
  _ as setcooldown_newcooldownlabel,
  _ as setcooldown_nocooldown,
  _ as setcooldown_setbutton,
  _ as setcooldown_statssummary,
};
