var _ = `Dokumentasi`,
  _ = `Utama`,
  _ = `Bermula`,
  _ = `Kehadiran Gedung`,
  _ = `Ciri`,
  _ = `Kewangan`,
  _ = `Jualan & Pemasaran`,
  _ = `Steamworks SDK`,
  _ = `Pelesenan Kafe`,
  _ = `Steam VR`,
  _ = `Lihat semua`,
  _ = `Alat Pentadbir`,
  _ = `Sumber`,
  _ = `Steam VR`,
  _ = `Program PC Café Steam`,
  _ = `Perbincangan Steamworks`,
  _ = `Tutorial Video Steamworks`,
  _ = `Berita & Kemas Kini`,
  _ = `Blog Steamworks`,
  _ = `Blog Steam`,
  _ = `Blog Steam VR`,
  _ = `Blog Steam Deck`,
  _ = `Steam Frame Blog`,
  _ = `Steamworks`,
  _ = `bahasa`,
  _ = `Ubah bahasa`,
  _ = `Log Keluar`,
  _ = `Daftar masuk`,
  _ = `Papan Pemuka`,
  _ = `SteamVR Tracking`,
  _ = `Aplikasi & Pakej`,
  _ = `Semua Aplikasi`,
  _ = `Lihat Pakej`,
  _ = `Bundle`,
  _ = `Harga`,
  _ = `Harga BAHARU!`,
  _ = `Pengurusan Diskaun`,
  _ = `Kelulusan Jualan BAHARU!`,
  _ = `Pendaftaran Acara Jualan & Fest`,
  _ = `Steam Next Fest`,
  _ = `Persediaan Laman Utama Pencipta`,
  _ = `Persediaan URL Tersuai Laman Utama Pencipta`,
  _ = `Alat Pemasaran & Data`,
  _ = `Pengurusan Tawaran Harian`,
  _ = `Keserasian Steam Deck`,
  _ = `Sokongan`,
  _ = `Alat`,
  _ = `Urus Ekonomi`,
  _ = `Pertanyaan Steam Key`,
  _ = `Larang Steam Key`,
  _ = `Lihat Templat Pakej Steam Key`,
  _ = `Trafik Navigasi Gedung & Platform Steam`,
  _ = `Catalog Recommended Actions`,
  _ = `Meet Steam @ Persidangan Industri`,
  _ = `Pengguna & Kebenaran`,
  _ = `Gambaran`,
  _ = `Butiran Syarikat`,
  _ = `Lihat Aplikasi`,
  _ = `Urus Pengguna`,
  _ = `Urus Kumpulan`,
  _ = `Maklumat Kewangan`,
  _ = `Dokumentasi & Bantuan`,
  _ = `Lawati Kumpulan Komuniti Pembangun`,
  _ = `Lawati Forum Pembangun`,
  _ = `Hubungi Steam Publishing`,
  _ = `Hubungi Sokongan Steamworks`,
  _ = `Sokongan Pembangun Steamworks`,
  _ = `Tidak berkaitan`,
  _ = `Cari mengikut Nama Aplikasi atau ID`,
  _ = `Lihat Dokumentasi`,
  _ = `Lihat Arkib Dokumentasi`,
  _ = `Butiran Pakej`,
  _ = `Sejarah Pengguna`,
  _ = `Sejarah Jemputan Pengguna`,
  _ = `Alamat Surat-Menyurat`,
  _ = `Pratonton Dokumentasi Baharu`,
  _ = `Pindahkan Aplikasi`,
  _ = `Kongsi Aplikasi`,
  _ = `Pembelian Langsung`,
  _ = `Lihat Butiran Pembayaran Bank`,
  _ = `Selaraskan Invois Dihantar`,
  _ = `Cipta/Urus Invois`,
  _ = `Store Admin`,
  _ = `Spotlights`,
  _ = `Front Page`,
  _ = `Alat OEM`,
  _ = `Kumpulan Tiket OEM`,
  _ = `Program PC Café`,
  _ = `Manage Sites`,
  _ = `Urus Lesen Komersial`,
  _ = `Sejarah Penggunaan`,
  _ = `Kawalan Kandungan`,
  _ = `Pembiayaan Dompet`,
  _ = `Konfigurasi`,
  _ = `Sejarah Aktiviti`,
  _ = `Kelulusan Pembiayaan`,
  _ = `Tukar Organisasi`,
  _ = `Tukar Organisasi Steamworks`,
  _ = `Akaun Steam anda adalah ahli kepada pelbagai organisasi Steamworks.`,
  _ = `Banyak ciri Steamworks hanya boleh diakses berdasarkan kebenaran anda dalam organisasi Steamworks terpilih sekarang.`,
  _ = `Sila pilih dari menu juntai bawah di bawah untuk menukar:`,
  _ = `Switch`,
  _ = `Batal`,
  _ = `Promosi`,
  _ = `Permainan`,
  _ = `Aplikasi`,
  _ = `Alat`,
  _ = `Demo`,
  _ = `DLC`,
  _ = `Mod`,
  _ = `Panduan`,
  _ = `Konfigurasi`,
  _ = `Muzik`,
  _ = `Pemalam`,
  _ = `Perkakasan`,
  _ = `Video`,
  _ = `Siri`,
  _ = `Episod`,
  _ = `Filem`,
  _ = `Beta`,
  _ = `Season Pass`,
  _ = `Navigasi`,
  _ = {
    Header_Global_Documentation: _,
    Header_Global_Documentation_Home: _,
    Header_Global_Documentation_GettingStarted: _,
    Header_Global_Documentation_StorePresence: _,
    Header_Global_Documentation_Features: _,
    Header_Global_Documentation_Finance: _,
    Header_Global_Documentation_SalesMarketing: _,
    Header_Global_Documentation_SteamworksSDK: _,
    Header_Global_Documentation_PCCafe: _,
    Header_Global_Documentation_SteamVR: _,
    Header_Global_Documentation_Seeall: _,
    Header_Nav_DocumentationAdmin: _,
    Header_Global_Resources: _,
    Header_Global_Resources_SteamVR: _,
    Header_Global_Resources_PCCafe: _,
    Header_Global_Resources_Discussions: _,
    Header_Global_Resources_VideoTutorials: _,
    Header_Global_News: _,
    Header_Global_News_Steamworks: _,
    Header_Global_News_Steam: _,
    Header_Global_News_SteamVR: _,
    Header_Global_News_SteamDeck: _,
    Header_Global_News_SteamFrame: _,
    Steamworks_Logo_Label: _,
    global_menu_language: _,
    global_menu_change_language: _,
    global_menu_sign_out: _,
    global_menu_sign_in: _,
    Header_Nav_Dashboard: _,
    Header_Nav_Lighthouse: _,
    Header_Nav_AppsPackages: _,
    Header_Nav_AppsPackages_All: _,
    Header_Nav_AppsPackages_ViewPackages: _,
    Header_Nav_AppsPackages_Bundles: _,
    Header_Nav_AppsPackages_Pricing: _,
    Header_Nav_AppsPackages_PricingNew: _,
    Header_Nav_AppsPackages_SaleApproval: _,
    Header_Nav_AppsPackages_SaleApprovalNew: _,
    Header_Nav_AppsPackages_Events: _,
    Header_Nav_AppsPackages_NextFestRecaps: _,
    Header_Nav_AppsPackages_CreatorHome: _,
    Header_Nav_AppsPackages_CreatorHome_Vanity: _,
    Header_Nav_PublisherMarketingStats: _,
    Header_Nav_DailyDeal_Management: _,
    Header_Nav_SteamDeck_Compat: _,
    Header_Nav_Support: _,
    Header_Nav_Tools: _,
    Header_Nav_Tools_Economy: _,
    Header_Nav_Tools_QueryCDKey: _,
    Header_Nav_Tools_BanCDKeys: _,
    Header_Nav_Tools_CDKeyRestrictions: _,
    Header_Nav_Tools_NavTraffic: _,
    Header_Nav_Tools_HealthChecks: _,
    Header_Nav_Tools_MeetSteam: _,
    Header_Nav_UsersPermissions: _,
    Header_Nav_UsersPermissions_Overview: _,
    Header_Nav_UsersPermissions_CompanyDetails: _,
    Header_Nav_UsersPermissions_Applications: _,
    Header_Nav_UsersPermissions_Users: _,
    Header_Nav_UsersPermissions_Groups: _,
    Header_Nav_FinancialInfo: _,
    Header_Nav_DocumentationHelp: _,
    Header_Nav_DeveloperCommunity: _,
    Header_Nav_DeveloperForums: _,
    Header_Nav_Contact_Steam: _,
    Header_Nav_Contact_Dev_Support: _,
    Header_Nav_Contact_Dev_Support2: _,
    Header_Nav_Unaffiliated: _,
    Header_Search_By_Appid: _,
    Header_Nav_ViewDocumentation: _,
    Header_Nav_ViewDocumentationArchive: _,
    Header_Nav_PackageDetails: _,
    Header_Nav_UserGroupHistory: _,
    Header_Nav_UserInviteHistory: _,
    Header_Nav_MailingAddresses: _,
    Header_Nav_PreviewNewDocumentation: _,
    Header_Nav_TransferRequests: _,
    Header_Nav_ShareApplications: _,
    Header_Nav_DirectPurchasing: _,
    Header_Nav_DirectPurchasing_Config: _,
    Header_Nav_DirectPurchasing_OpenInvoices: _,
    Header_Nav_DirectPurchasing_CreateInvoices: _,
    Header_Nav_StoreAdmin: _,
    Header_Nav_StoreAdmin_Spotlights: _,
    Header_Nav_StoreAdmin_Frontpage: _,
    Header_Nav_OEM: _,
    Header_Nav_OEM_Ticket_Batches: _,
    Header_Nav_Sites: _,
    Header_Nav_Sites_Edit_Sites: _,
    Header_Nav_Sites_Current_Usage: _,
    Header_Nav_Sites_Historical_Usage: _,
    Header_Nav_Sites_Content_Control: _,
    Header_Nav_WalletFunding: _,
    Header_Nav_WalletFunding_Config: _,
    Header_Nav_WalletFunding_Usage: _,
    Header_Nav_WalletFunding_Approval: _,
    change_partner_link: _,
    change_partner_dialog_title: _,
    change_partner_dialog_desc_part1: _,
    change_partner_dialog_desc_part2: _,
    change_partner_dialog_desc_part3: _,
    change_partner_dialog_submit: _,
    change_partner_dialog_cancel: _,
    AppType_TitleCase_Advertising: _,
    AppType_TitleCase_Game: _,
    AppType_TitleCase_Application: _,
    AppType_TitleCase_Tool: _,
    AppType_TitleCase_Demo: _,
    AppType_TitleCase_DLC: `DLC`,
    AppType_TitleCase_Mod: `Mod`,
    AppType_TitleCase_Guide: _,
    AppType_TitleCase_Config: _,
    AppType_TitleCase_Music: _,
    AppType_TitleCase_PlugIn: _,
    AppType_TitleCase_Hardware: _,
    AppType_TitleCase_Video: _,
    AppType_TitleCase_Series: _,
    AppType_TitleCase_Episode: _,
    AppType_TitleCase_Movie: _,
    AppType_TitleCase_Beta: _,
    AppType_TitleCase_DLC_SeasonPass: _,
    Aria_Navigation: _,
  };
export {
  _ as AppType_TitleCase_Advertising,
  _ as AppType_TitleCase_Application,
  _ as AppType_TitleCase_Beta,
  _ as AppType_TitleCase_Config,
  _ as AppType_TitleCase_DLC,
  _ as AppType_TitleCase_DLC_SeasonPass,
  _ as AppType_TitleCase_Demo,
  _ as AppType_TitleCase_Episode,
  _ as AppType_TitleCase_Game,
  _ as AppType_TitleCase_Guide,
  _ as AppType_TitleCase_Hardware,
  _ as AppType_TitleCase_Mod,
  _ as AppType_TitleCase_Movie,
  _ as AppType_TitleCase_Music,
  _ as AppType_TitleCase_PlugIn,
  _ as AppType_TitleCase_Series,
  _ as AppType_TitleCase_Tool,
  _ as AppType_TitleCase_Video,
  _ as Aria_Navigation,
  _ as Header_Global_Documentation,
  _ as Header_Global_Documentation_Features,
  _ as Header_Global_Documentation_Finance,
  _ as Header_Global_Documentation_GettingStarted,
  _ as Header_Global_Documentation_Home,
  _ as Header_Global_Documentation_PCCafe,
  _ as Header_Global_Documentation_SalesMarketing,
  _ as Header_Global_Documentation_Seeall,
  _ as Header_Global_Documentation_SteamVR,
  _ as Header_Global_Documentation_SteamworksSDK,
  _ as Header_Global_Documentation_StorePresence,
  _ as Header_Global_News,
  _ as Header_Global_News_Steam,
  _ as Header_Global_News_SteamDeck,
  _ as Header_Global_News_SteamFrame,
  _ as Header_Global_News_SteamVR,
  _ as Header_Global_News_Steamworks,
  _ as Header_Global_Resources,
  _ as Header_Global_Resources_Discussions,
  _ as Header_Global_Resources_PCCafe,
  _ as Header_Global_Resources_SteamVR,
  _ as Header_Global_Resources_VideoTutorials,
  _ as Header_Nav_AppsPackages,
  _ as Header_Nav_AppsPackages_All,
  _ as Header_Nav_AppsPackages_Bundles,
  _ as Header_Nav_AppsPackages_CreatorHome,
  _ as Header_Nav_AppsPackages_CreatorHome_Vanity,
  _ as Header_Nav_AppsPackages_Events,
  _ as Header_Nav_AppsPackages_NextFestRecaps,
  _ as Header_Nav_AppsPackages_Pricing,
  _ as Header_Nav_AppsPackages_PricingNew,
  _ as Header_Nav_AppsPackages_SaleApproval,
  _ as Header_Nav_AppsPackages_SaleApprovalNew,
  _ as Header_Nav_AppsPackages_ViewPackages,
  _ as Header_Nav_Contact_Dev_Support,
  _ as Header_Nav_Contact_Dev_Support2,
  _ as Header_Nav_Contact_Steam,
  _ as Header_Nav_DailyDeal_Management,
  _ as Header_Nav_Dashboard,
  _ as Header_Nav_DeveloperCommunity,
  _ as Header_Nav_DeveloperForums,
  _ as Header_Nav_DirectPurchasing,
  _ as Header_Nav_DirectPurchasing_Config,
  _ as Header_Nav_DirectPurchasing_CreateInvoices,
  _ as Header_Nav_DirectPurchasing_OpenInvoices,
  _ as Header_Nav_DocumentationAdmin,
  _ as Header_Nav_DocumentationHelp,
  _ as Header_Nav_FinancialInfo,
  _ as Header_Nav_Lighthouse,
  _ as Header_Nav_MailingAddresses,
  _ as Header_Nav_OEM,
  _ as Header_Nav_OEM_Ticket_Batches,
  _ as Header_Nav_PackageDetails,
  _ as Header_Nav_PreviewNewDocumentation,
  _ as Header_Nav_PublisherMarketingStats,
  _ as Header_Nav_ShareApplications,
  _ as Header_Nav_Sites,
  _ as Header_Nav_Sites_Content_Control,
  _ as Header_Nav_Sites_Current_Usage,
  _ as Header_Nav_Sites_Edit_Sites,
  _ as Header_Nav_Sites_Historical_Usage,
  _ as Header_Nav_SteamDeck_Compat,
  _ as Header_Nav_StoreAdmin,
  _ as Header_Nav_StoreAdmin_Frontpage,
  _ as Header_Nav_StoreAdmin_Spotlights,
  _ as Header_Nav_Support,
  _ as Header_Nav_Tools,
  _ as Header_Nav_Tools_BanCDKeys,
  _ as Header_Nav_Tools_CDKeyRestrictions,
  _ as Header_Nav_Tools_Economy,
  _ as Header_Nav_Tools_HealthChecks,
  _ as Header_Nav_Tools_MeetSteam,
  _ as Header_Nav_Tools_NavTraffic,
  _ as Header_Nav_Tools_QueryCDKey,
  _ as Header_Nav_TransferRequests,
  _ as Header_Nav_Unaffiliated,
  _ as Header_Nav_UserGroupHistory,
  _ as Header_Nav_UserInviteHistory,
  _ as Header_Nav_UsersPermissions,
  _ as Header_Nav_UsersPermissions_Applications,
  _ as Header_Nav_UsersPermissions_CompanyDetails,
  _ as Header_Nav_UsersPermissions_Groups,
  _ as Header_Nav_UsersPermissions_Overview,
  _ as Header_Nav_UsersPermissions_Users,
  _ as Header_Nav_ViewDocumentation,
  _ as Header_Nav_ViewDocumentationArchive,
  _ as Header_Nav_WalletFunding,
  _ as Header_Nav_WalletFunding_Approval,
  _ as Header_Nav_WalletFunding_Config,
  _ as Header_Nav_WalletFunding_Usage,
  _ as Header_Search_By_Appid,
  _ as Steamworks_Logo_Label,
  _ as change_partner_dialog_cancel,
  _ as change_partner_dialog_desc_part1,
  _ as change_partner_dialog_desc_part2,
  _ as change_partner_dialog_desc_part3,
  _ as change_partner_dialog_submit,
  _ as change_partner_dialog_title,
  _ as change_partner_link,
  _ as default,
  _ as global_menu_change_language,
  _ as global_menu_language,
  _ as global_menu_sign_in,
  _ as global_menu_sign_out,
};
