{
	"language": "brazilian",
	"Button_Append": "Anexar",
	"Button_Cancel": "Cancelar",
	"Button_Close": "Fechar",
	"Button_Clone": "Clonar",
	"Button_Confirm": "Confirmar",
	"Button_Copy": "Copiar",
	"Button_CopyClipboard": "Copiar p/ área de transferência",
	"Button_CopyLink": "Copiar link",
	"Button_Continue": "Continuar",
	"Button_Create": "Criar",
	"Button_Delete": "Excluir",
	"Button_Discuss": "Discussão",
	"Button_Dismiss": "Descartar",
	"Button_Edit": "Editar",
	"Button_Learn": "Saiba mais aqui",
	"Button_Publish": "Publicar",
	"Button_Post": "Publicar",
	"Button_OK": "OK",
	"Button_Overwrite": "Substituir",
	"Button_Retry": "Tentar novamente",
	"Button_Remove": "Remover",
	"Button_Save": "Salvar",
	"Button_Saved": "Salvo",
	"Button_Share": "Compartilhar",
	"Button_Update": "Atualizar",
	"Button_SaveAndContinue": "Salvar e continuar",
	"Button_Follow": "Seguir",
	"Button_Followed": "Seguindo",
	"Button_Ignore": "Ignorar",
	"Button_Ignored": "Ignorado",
	"Button_NotifyMe": "Ativar notificações",
	"Button_NotInterested": "Dispensar",
	"Button_RateUp": "Gostei",
	"Button_ViewPage": "Acessar página",
	"Button_Accept": "Aceitar",
	"Button_Reject": "Recusar",
	"ToolTip_CopyLinkToClipboard": "Copiar link para área de transferência",
	"Input_Error_NumberTooSmall": "Número pequeno demais.",
	"Input_Error_NumberTooLarge": "Número grande demais.",
	"Input_Error_MustBeURL": "O campo não inclui um URL válido.",
	"Input_Error_MustBeEmail": "O campo não inclui um e-mail válido.",
	"Input_Error_MustBeNumber": "O campo deve conter um número.",
	"Loading": "Carregando...",
	"Updating": "Atualizando...",
	"Uploading": "Enviando...",
	"Settings": "Configurações",
	"FriendSettings_AlwaysNewChatWindow": "Abrir novas conversas em janelas em vez de abas",
	"g_DisabledOnWeb": "Indisponível na versão web",
	"VoiceTransmissionType_Disabled": "Versão web só é compatível com microfone aberto",
	"VoiceVolume": "Volume",
	"VoiceSetupHeader": "Configuração e teste de voz",
	"VoiceStartLocalMicTest": "Iniciar teste de microfone",
	"VoiceStopLocalMicTest": "Finalizar teste de microfone",
	"VoiceWhenMicIsWorking": "Se o seu microfone estiver funcionando, você ouvirá sua voz e verá que a barra colorida próxima ao seu avatar se move conforme você fala.",
	"VoiceDevice": "Dispositivo de entrada de voz",
	"VoiceOutputDevice": "Dispositivo de reprodução de voz",
	"VoiceInputGain": "Volume/Ganho de entrada",
	"VoiceInputGainExplainer": "(Meu microfone)",
	"VoiceOutputGain": "Volume/Ganho de saída",
	"VoiceOutputGainExplainer": "(Meus amigos)",
	"VoiceTransmissionType": "Pressionar para falar",
	"VoiceTransmissionType_Label": "Tipo de transmissão por voz",
	"VoiceTransmissionType_OpenMic": "Microfone aberto",
	"VoiceTransmissionType_PushToTalk": "Pressionar para falar",
	"VoiceTransmissionType_PushToMute": "Pressionar para silenciar",
	"VoiceClearHotKeyTooltip": "Remover atalho",
	"VoiceTransmissionTypeExplainer": "Pressione uma tecla ou botão definido por você para falar em canais de voz",
	"VoiceTransmissionType_WhenSpeaking": "Automático",
	"VoiceTransmissionType_PushToTalk_Key": "Pressionar para falar: %1$s",
	"VoicePushToTalkPressHotKey": "Pressione uma tecla ou botão para atribuir",
	"VoicePushToTalkAssigned": "Tecla/Botão para pressionar para falar",
	"VoicePushToMuteAssigned": "Tecla/Botão para pressionar para silenciar",
	"VoiceMuteToggleAssigned": "Atalho para ativar/desativar o microfone",
	"VoicePushToSomethingSoundOption": "Reproduzir som ao ativar/desativar o microfone",
	"VoiceTransmisionThreshold": "Limiar para transmissão de voz",
	"VoiceTransmissionThresholdExplainer": "Quando o seu microfone estiver ligado, ruído abaixo desse limite não será transmitido:",
	"VoiceTransmissionThresholdOff": "Desligado",
	"VoiceTransmissionThresholdMedium": "Médio",
	"VoiceTransmissionThresholdHigh": "Alto",
	"VoiceTransmissionThresholdRecommended": "Recomendado",
	"VoiceAdvancedSettings": "Configurações avançadas",
	"VoiceShowAdvancedSettings": "Exibir configurações avançadas",
	"VoiceHideAdvancedSettings": "Ocultar configurações avançadas",
	"VoiceAdvancedSettingsExplainer": "(Estas configurações de microfone são gerenciadas pela sua plataforma ou navegador.)",
	"VoiceEchoCancellation": "Cancelamento de eco",
	"VoiceNoiseCancellation": "Cancelamento de ruído",
	"VoiceAutoGainControl": "Controle automático de volume/ganho",
	"DefaultMic": "Padrão",
	"MicLoading...": "Carregando...",
	"DefaultOutputDevice": "Padrão",
	"OutputDeviceLoading...": "Carregando...",
	"BreadCrumbs_AllEvents": "Todos os eventos",
	"BreadCrumbs_GameEvents": "Eventos de %1$s",
	"CreatorHome_ThisGame": "Sobre este jogo:",
	"CreatorHome_DevelopedBy": "Desenvolvido por:",
	"CreatorHome_PublishedBy": "Distribuído por:",
	"CreatorHome_InFranchise": "Na série:",
	"CreatorHome_Followers": "%1$s<br>seguidores",
	"CreatorHome_JustFollowers": "seguidores",
	"CreatorHome_Follow_tooltip": "Siga este criador para ser notificado por e-mail e na Loja Steam sobre futuros lançamentos. É possível desativar as notificações por e-mail quando quiser.",
	"EventBrowse_MoreEventsTitle": "Mais eventos de %1$s",
	"EventBrowse_MoreEventsBtn": "Ver tudo",
	"EventBrowse_RecentUpdates": "Atualizações recentes",
	"EventBrowse_RecentEvents": "Eventos e anúncios recentes",
	"EventCalendar_Title": "Central de notícias%1$sdo Steam",
	"EventCalendar_FilterSubSection_EventTypeGroups": "Exibir estes tipos de publicações",
	"EventCalendar_FilterSubSection_GameSources": "Exibir publicações destas fontes",
	"EventCalendar_EmptyCalendar": "Nada encontrado. Tente usar outros critérios de busca na barra lateral.",
	"EventCalendar_DisabledFilter_LoginPrompt": "Inicie a sessão para usar estas categorias",
	"EventCalendar_MainLoginPrompt": "Inicie a sessão para ver a sua central de notícias",
	"EventCalendar_NoMoreFutureEvents": "Nenhuma publicação futura encontrada",
	"EventCalendar_NoMorePastEvents": "Nenhuma publicação antiga encontrada",
	"EventCalendar_GameSearch": "Buscar jogos",
	"EventCalendar_GameSearch_NoneFound": "Nenhum encontrado",
	"EventCalendar_GlobalCalendar_Action": "Voltar à central de notícias",
	"EventCalendar_SpecificCalendar": "Central de notícias de%2$s%1$s",
	"EventCalendar_Goto_SpecificCalendar": "Ir para a central de notícias de %1$s",
	"EventCalendar_SingleAppIsMuted": "Aviso: este jogo está silenciado e não será exibido na sua central de notícias personalizada.",
	"SteamLabs": "Laboratório Steam",
	"SteamLabs_ExperimentNumber": "Experimento %1$s",
	"SteamLabs_DiscussionLink": "Discutir experimento",
	"EventCalendar_FutureEventsHint": "Role para cima para ver o que vem por aí",
	"EventCalendar_FutureEventsHeader": "Em breve",
	"EventCalendar_LiveAndRecentEventsHeader": "Acontecendo agora e recentes",
	"EventCalendar_LiveNow": "no ar",
	"EventCalendar_TimeLeft": "encerra em %1$s",
	"EventCalendar_PostedAtTime": "Publicado: %1$s",
	"EventCalendar_StartedAtTime": "Início: %1$s",
	"EventCalendar_Upcoming": "em breve",
	"EventCalendar_WillStartAtTime": "Começa: %1$s",
	"EventCalendar_WillStartAfterDuration": "Começa em %1$s",
	"EventCalendar_LaterToday": "ainda hoje",
	"EventCalendar_Tomorrow": "amanhã",
	"EventCalendar_ThisWeek": "nesta semana",
	"EventCalendar_ThisMonth": "neste mês",
	"EventCalendar_MuchLater": "no futuro",
	"EventCalendar_MuteApp": "Silenciar aplicativo",
	"EventCalendar_MuteApp_Title": "Silenciar %1$s",
	"EventCalendar_Ignore": "Ignorar",
	"EventCalendar_IgnoreApp": "Ignorar %1$s",
	"EventCalendar_IgnoreApp_ttip": "Títulos ignorados não serão recomendados para você, nem aparecerão em áreas de destaque.",
	"EventCalendar_IgnoreApp_newhub": "A central de notícias não exibirá eventos e anúncios de jogos que você tenha ignorado na Loja Steam. Gerencie os seus jogos ignorados aqui:",
	"EventCalendar_UnignoreApp": "Deixar de ignorar %1$s",
	"EventCalendar_UnMuteApp_Title": "Voltar a exibir %1$s",
	"EventCalendar_MuteApp_ttip": "Remove este jogo da sua central de notícias e bloqueia comunicações futuras.",
	"EventCalendar_UnMuteApp_ttip": "Voltar a exibir o jogo na sua central de notícias e desbloquear comunicações futuras.",
	"EventCalendar_MuteApp_details": "Impedir que \"%1$s\" apareça na sua central de notícias e bloquear todas as comunicações futuras. Decisões de silenciamento são reversíveis, basta acessar esta página:",
	"EventCalendar_ManageMutedApps": "Gerenciar aplicativos silenciados",
	"EventCalendar_ManageStorePref": "Gerenciar preferências da loja",
	"EventCalendar_MuteApp_Unknown": "Desconhecido",
	"EVentCalendar_Hide_EventType": "Ocultar publicações do tipo \"%1$s\"",
	"EventCalender_LastPlayed": "Last played %1$s",
	"EventCalender_Reason_recent": "Jogo recém-jogado",
	"EventCalender_Reason_library": "Jogo presente na sua biblioteca",
	"EventCalender_Reason_following": "Jogo seguido por você",
	"EventCalender_Reason_wishlist": "Jogo presente na sua lista de desejos",
	"EventCalender_Reason_recommended": "Jogo recomendado para você",
	"EventCalender_Reason_steam": "Publicação do Steam",
	"EventCalender_Reason_topx": "Jogo entre os mais vendidos",
	"EventCalender_Hide_Reason_recent": "Ocultar publicações de jogos recém-jogados",
	"EventCalender_Hide_Reason_library": "Ocultar publicações sobre jogos na sua biblioteca",
	"EventCalender_Hide_Reason_following": "Ocultar publicações sobre jogos que você segue",
	"EventCalender_Hide_Reason_wishlist": "Ocultar publicações sobre jogos na sua lista de desejos",
	"EventCalender_Hide_Reason_recommended": "Ocultar publicações sobre jogos recomendados para você",
	"EventCalender_Hide_Reason_steam": "Ocultar publicações do Steam",
	"EventCalender_Hide_Reason_topx": "Ocultar publicações de jogos mais vendidos",
	"EventCalendar_ForceDesktopView": "Ver versão para computadores",
	"EventCalendar_ShowResponsiveView": "Ver versão adaptável",
	"EventCalendar_EventTypeGroup_news": "Novidades",
	"EventCalendar_EventTypeGroup_ttip_news": "Inclui notícias, blogs de desenvolvimento e anúncios",
	"EventCalendar_EventTypeGroup_events": "Eventos",
	"EventCalendar_EventTypeGroup_ttip_events": "Inclui eventos no jogo, online, em salas de conversa e no mundo real",
	"EventCalendar_EventTypeGroup_streaming": "Transmissões ao vivo",
	"EventCalendar_EventTypeGroup_ttip_streaming": "Inclui transmissões ao vivo de desenvolvedores, como torneios e demonstrações do jogo",
	"EventCalendar_EventTypeGroup_updates": "Atualizações de conteúdo",
	"EventCalendar_EventTypeGroup_ttip_updates": "Inclui notícias sobre novos conteúdos, expansões, conteúdos adicionais e correções para jogos",
	"EventCalendar_EventTypeGroup_releases": "Lançamentos",
	"EventCalendar_EventTypeGroup_ttip_releases": "Inclui datas de lançamentos de jogos, betas, temporadas e conteúdos adicionais.",
	"EventCalendar_EventTypeGroup_sales": "Promoções",
	"EventCalendar_EventTypeGroup_ttip_sales": "Inclui descontos, promoções e testes gratuitos",
	"EventCalendar_GameSource_recent": "Recém-jogados",
	"EventCalendar_GameSource_ttip_recent": "Incluir publicações sobre jogos que tenha jogado ou comprado nos últimos seis meses",
	"EventCalendar_GameSource_EventExplanation_ttip_recent": "You have played this game in the past six months",
	"EventCalendar_GameSource_library": "Biblioteca",
	"EventCalendar_GameSource_ttip_library": "Incluir publicações sobre jogos na sua biblioteca",
	"EventCalendar_GameSource_EventExplanation_ttip_library": "Jogo presente na sua biblioteca",
	"EventCalendar_GameSource_wishlist": "Lista de desejos",
	"EventCalendar_GameSource_ttip_wishlist": "Incluir publicações sobre jogos na sua lista de desejos",
	"EventCalendar_GameSource_EventExplanation_ttip_wishlist": "Jogo presente na sua lista de desejos",
	"EventCalendar_GameSource_following": "Seguindo",
	"EventCalendar_GameSource_ttip_following": "Incluir publicações sobre jogos que você segue",
	"EventCalendar_GameSource_EventExplanation_ttip_following": "É um jogo que você segue",
	"EventCalendar_GameSource_recommended": "Recomendados",
	"EventCalendar_GameSource_recommended_Verbose": "Jogo recomendado",
	"EventCalendar_GameSource_ttip_recommended": "Incluir publicações sobre jogos que achamos que você vai gostar",
	"EventCalendar_GameSource_EventExplanation_ttip_recommended": "É um jogo que achamos que vai gostar",
	"EventCalendar_GameSource_steam": "Steam",
	"EventCalendar_GameSource_ttip_steam": "Incluir publicações sobre o Steam",
	"EventCalendar_GameSource_topx": "Mais vendidos",
	"EventCalendar_GameSource_ttip_topx": "Incluir publicações sobre jogos que estejam na lista de mais vendidos na região",
	"EventCalendar_GameSource_EventExplanation_ttip_steam": "Publicação sobre o Steam",
	"EventDisplay_Admin_Title": "Administração:",
	"EventDisplay_ViewInLibrary": "Ver na biblioteca",
	"EventDisplay_ViewStorePage": "Ver página da loja",
	"EventDisplay_ViewCommunityPage": "Ver página na comunidade",
	"EventDisplay_CallToAction_LearnMore": "Saiba mais",
	"EventDisplay_CallToAction_InLibrary": "Na biblioteca",
	"EventDisplay_CallToAction_PlayNow": "Jogar agora",
	"EventDisplay_CallToAction_ComingSoon": "Em breve",
	"EventDisplay_CallToAction_FreeToPlay": "Gratuito para jogar",
	"EventDisplay_Events": "Painel administrativo",
	"EventDisplay_SeeOldVersion": "Ver versão exibida a usuários",
	"EventDisplay_SalesPage": "Ver página de promoções da loja",
	"EventDisplay_StatsPage": "(Somente para a Valve) Página de estatísticas",
	"EventDisplay_RightColumnTitle_Game": "Jogo",
	"EventDisplay_RightColumnTitle_Blog": "Blog",
	"EventDisplay_RightColumnTitle_DateAndTime": "Data e hora",
	"EventDisplay_RightColumnTitle_EventType": "Tipo",
	"EventDisplay_PostedBy": "por ",
	"EventDisplay_Reminder_SetReminder": "Agendar lembrete",
	"EventDisplay_Reminder_GetNotification_Via": "Receber notificação",
	"EventDisplay_Reminder_ViaEmail": "por e-mail",
	"EventDisplay_Reminder_ViaMobileApp": "por aplicativo móvel",
	"EventDisplay_Reminder_FollowEvent": "Seguir evento",
	"EventDisplay_Reminder_FollowEvent_ttip": "Siga o evento para ser notificado quando começar.",
	"EventDisplay_Reminder_RemindAtStart": "Quando o evento começar",
	"EventDisplay_Reminder_RemindAtStart_ttip": "Você será notificado no Steam quando o evento começar.",
	"EventDisplay_Reminder_IgnoreEvent": "Ignorar evento",
	"EventDisplay_Reminder_IgnoreStop": "Cancelar lembretes",
	"EventDisplay_Reminder_IgnoreEvent_ttip": "Ignorar um evento fará com que o Steam exclua este evento de sugestões e recomendações futuras.",
	"EventDisplay_Reminder_FollowEvent_Error": "Erro ao seguir evento",
	"EventDisplay_Reminder_FollowEvent_ErrorDesc": "Ocorreu um erro ao tentar seguir o evento:",
	"EventDisplay_Reminder_IgnoreEvent_Error": "Erro ao ignorar evento",
	"EventDisplay_Reminder_IgnoreEvent_ErrorDesc": "Ocorreu um erro ao tentar ignorar o evento:",
	"EventDisplay_Reminder_Toast": "Exibir alerta no Steam quando começar",
	"EventDisplay_Reminder_AddToCalendar": "Adicionar ao calendário/agenda",
	"EventDisplay_Reminder_AddToApple": "Adicionar ao Calendário da Apple",
	"EventDisplay_Reminder_AppleCalendar_Short": "Apple",
	"EventDisplay_Reminder_AddToGoogle": "Adicionar ao Google Agenda",
	"EventDisplay_Reminder_GoogleCalendar_Short": "Google",
	"EventDisplay_Reminder_AddToOutlook": "Adicionar ao Calendário do Outlook",
	"EventDisplay_Reminder_OutlookCalendar_Short": "Outlook",
	"EventDisplay_Reminder_AddToYahoo": "Adicionar ao Yahoo Agenda",
	"EventDisplay_Reminder_Preferences": "Editar preferências de lembretes...",
	"EventDisplay_TimeDisplay": "De %1$s a %2$s",
	"EventDisplay_TimeDisplayNone": "Sem informações de data e hora",
	"EventDisplay_TimeBeginsOn": "Evento começa em",
	"EventDisplay_TimeBeginsOn_Past": "Iniciado",
	"EventDisplay_TimeBeginsOn_StartAndEnd_Past": "Evento começou",
	"EventDisplay_TimeEndsOn": "Termina",
	"EventDisplay_TimeEndsOn_Past": "Terminou",
	"EventDisplay_RunsForDuration": "Dura %1$s",
	"EventDisplay_TimeLeft": "Termina em %1$s",
	"EventDisplay_TimeEndsOn_Ran": "Finalizado",
	"EventDisplay_TimeRange": "Duração do evento",
	"EventDisplay_TimeInPast": "Publicado em",
	"EventDisplay_TimeUpcoming": "Evento começa",
	"EventDisplay_EventUpcoming_WithDateAndTime": "Evento inicia em %1$s, às %2$s",
	"EventDisplay_TimeEventActive": "Evento em andamento",
	"EventDisplay_TimeEventOnNow": "Acontecendo agora!",
	"EventDisplay_Share_Link": "Link: ",
	"EventDisplay_Share_OnMyStatus": "Editar e compartilhar status",
	"EventDisplay_Share_OnMyStatus_Details": "Publique esse status no feed de atividades. O Steam incluirá a mensagem e a pré-visualização exibida abaixo.",
	"EventDisplay_Share_OnMyStatus_Placeholder": "Diga algo sobre isso aos seus amigos...",
	"EventDisplay_Share_OnSteam": "Compartilhar na Comunidade Steam como uma atualização de status",
	"EventDisplay_Share_OnFaceBook": "Compartilhar no Facebook",
	"EventDisplay_Share_OnTwitter": "Compartilhar no Twitter",
	"EventDisplay_Share_OnReddit": "Compartilhar no Reddit",
	"EventDisplay_Share_Success": "Sucesso!",
	"EventDisplay_Share_Failure": "Ocorreu um erro com a seguinte mensagem: ",
	"EventDisplay_Share_Announcement": "Anúncio de %1$s",
	"EventDisplay_Share_Event": "Evento de %1$s",
	"EventDisplay_Share_NotLoggedIn": "Sessão não iniciada",
	"EventDisplay_Share_NotLoggedIn_Description": "Inicie a sessão para usar este recurso",
	"EventDisplay_Share_CommentMigrationInProcess": "As discussões para este evento estão temporariamente inacessíveis enquanto são transferidas para o sistema de eventos. Por favor, volte mais tarde.",
	"EventDisplay_Share_OpenActivityFeed": "Abrir feed de atividade",
	"EventDisplay_AreYouSure": "Tem certeza de que deseja excluir este evento (%1$s)? Esta ação não pode ser desfeita.",
	"EventDisplay_AreYouSure_Visible": "Tem certeza de que deseja excluir este evento (%1$s)? Esta ação não pode ser desfeita. O evento será removido de todos os lugares dentro de alguns minutos.",
	"EventDisplay_DeleteEvent_InProgress": "Exclusão em progresso. Por favor, aguarde.",
	"EventDisplay_DeleteEvent_Error": "Houve um erro ao processar a solicitação de exclusão:",
	"EventDisplay_DeleteEvent_ForumTopicError": "O evento foi excluído com sucesso. No entanto, houve um problema ao excluir o tópico do evento no fórum. É possível tentar novamente no site %1$s. Detalhes do erro:",
	"EventDisplay_DeleteEvent_Success": "O evento foi excluído com sucesso.",
	"EventDisplay_DeleteEvent_Comment": "Também excluir o tópico do evento no fórum?",
	"EventDisplay_SocialTitle": "Saiba mais sobre este jogo",
	"EventDisplay_Sketchfab": "Modelo do Sketchfab",
	"EventDisplay_SketchFab_Error_Network": "Não foi possível contatar o Sketchfab",
	"EventEditor_Publish_VisibleNow": "Tornar visível agora",
	"EventEditor_Publish_VisibleNow_ttip": "O evento ficará visível automaticamente no horário agendado. Este botão força o evento a ficar visível imediatamente.",
	"EventEditor_Edit": "Editar evento",
	"EventDisplay_DeleteEvent": "Excluir evento",
	"EventReminder_InProgress": "(as opções de notificação aqui exibidas são ilustrativas e ainda não funcionam)",
	"EventReminder_NotifyByEmail": "Notifique-me por e-mail",
	"EventReminder_NotifyByEmail_ttip": "O Steam enviará uma notificação para o seu e-mail quando o evento começar.",
	"EventReminder_NotifyByMobile": "Notifique-me no meu celular",
	"EventReminder_NotifyByMobile_ttip": "Quando o evento começar, o Steam enviará uma notificação a todos os dispositivos com o aplicativo móvel do Steam instalado e associado à sua conta.",
	"EventReminder_NotifyByEmail_Missing": "Verifique o seu endereço de e-mail para receber lembretes.",
	"EventReminder_NotifyByEmail_Missing_Add": "Verifique o seu endereço de e-mail.",
	"EventReminder_NotifyByMobile_Missing": "Instale um dos aplicativos do Steam para receber lembretes no seu dispositivo móvel. ",
	"EventReminder_NotifyByMobile_Install": "Conheça-os aqui.",
	"EventEmail_Subject_NewUpdate": "%1$s, nova atualização",
	"EventEmail_Subject_UpcomingLaunch": "%1$s, lançamento futuro",
	"EventEmail_Subject_NowAvailable": "%1$s já disponível",
	"EventEmail_Subject_FreeDemoAvailable": "Demonstração gratuita de %1$s já disponível",
	"EventEmail_Subject_SpecialOffer": "Oferta especial: %1$s",
	"EventEmail_Subject_Tournament_Now": "Torneio de %1$s, assista já",
	"EventEmail_Subject_LiveStream_Now": "Transmissão ao vivo de %1$s, assista já",
	"Email_Wishlist_NewReleaseEA_Subject": "%1$s já está disponível em acesso antecipado no Steam!",
	"EventEmail_Button_ClickForMoreDetails": "Saiba mais",
	"EventEmail_Button_PrepurchaseNow": "Compre já na pré-venda!",
	"EventEmail_Button_BuyNow": "Compre já!",
	"EventEmail_Button_PlayNow": "Jogue agora!",
	"EventEmail_Button_WishlistNow": "+ Lista de desejos",
	"EventEmail_WatchNow": "Assista já",
	"EventEmail_Destination_Store": "Página do Jogo na Loja Steam",
	"EventEmail_Destination_Event": "Página de detalhes do evento",
	"EventEmail_Destination_SalesPage": "Página de promoções da Loja Steam",
	"EventDashBoard_SummaryStats_Admin_Title": "(Visível apenas para administradores)",
	"EventDashBoard_SummaryStats_Title": "Total de impressões e visualizações diferentes",
	"EventDashBoard_SummaryStats_Desc": "(Beta) Estas são as impressões e visualizações dos seus eventos e anúncios por usuários únicos com sessão iniciada. Exibe apenas eventos e anúncios novos criados com este editor.",
	"EventDashBoard_SummaryStats_Link": "Clique aqui para mais detalhes.",
	"EventDashBoard_Summary_LibraryHome_Shown": "Impressões de eventos (imagem de capa):",
	"EventDashBoard_Summary_LibraryHome_Read": "Cliques em um evento para ver mais detalhes:",
	"EventDashBoard_Summary_AppDetailSpotlight_Shown": "Impressões do banner de destaque:",
	"EventDashBoard_Summary_AppDetailSpotlight_Read": "Cliques em um banner de destaque para ver mais detalhes:",
	"EventDashBoard_Summary_AppDetailActivity_Shown": "Impressões de eventos no feed de atividade:",
	"EventDashBoard_Summary_AppDetailActivity_Read": "Cliques em um evento para ver mais detalhes:",
	"EventDashBoard_Summary_StoreAppPage_Shown": "Impressões de eventos (imagem de capa):",
	"EventDashBoard_Summary_StoreAppPage_Read": "Cliques em um evento para ver mais detalhes:",
	"EventDashBoard_Summary_Community_Shown": "Impressões do resumo do evento:",
	"EventDashBoard_Summary_Community_Read": "Cliques no resumo do evento para ver mais detalhes:",
	"EventDashBoard_Summary_NewsHub_Shown": "Impressões de evento na central de notícias:",
	"EventDashBoard_Summary_NewsHub_Read": "Cliques em um evento para ver detalhes:",
	"EventDashBoard_Location_LibraryHome": "Página inicial da biblioteca",
	"EventDashBoard_Location_LibraryDetail": "Página do jogo na biblioteca",
	"EventDashBoard_Location_StoreDetail": "Página do jogo na loja",
	"EventDashBoard_Location_CommunityDetail": "Central da comunidade do aplicativo",
	"EventDashBoard_Location_PopUpViews": "Visualizações do pop-up do evento",
	"EventDashBoard_Location_NewsHubDetail": "Central de notícias",
	"AddToWishlist": "Adicionar à lista de desejos",
	"Wishlisted": "Na lista de desejos",
	"AddToWishlist_ttip": "Seja notificado por e-mail quando itens na sua lista de desejos forem lançados ou estiverem em oferta",
	"Wishlist_Error": "Erro ao atualizar lista de desejos",
	"Wishlist_Error_Desc": "Ocorreu um erro ao adicionar o item à lista de desejos. Por favor, tente novamente mais tarde.",
	"WindowTitle_FriendsList": "Lista de amigos",
	"FriendsList_OfflineTitle": "ERRO",
	"FriendsList_OfflineOrFailure": "Não foi possível conectar-se à rede de amigos",
	"FriendsList_OfflineDetail": "Este erro pode indicar que a sua rede local está offline ou que os servidores da rede de amigos do Steam estão indisponíveis no momento.",
	"FriendsList_SignedOut": "Desconectado da lista e conversas",
	"FriendsList_SignedOut_Detail": "Você está offline. Conecte-se para acessar a sua lista de amigos e conversar.",
	"FriendsList_OfflineMode": "Desconectado da lista e conversas",
	"FriendsList_OfflineMode_Detail": "Não é possível ver a lista de amigos e conversar no modo offline. Por favor, conecte-se para acessá-las.",
	"Friends_RetryLoading": "Tentar novamente",
	"Friends_SignIn": "Iniciar sessão",
	"FriendsList_Offline_Disconnected": "Desconectado",
	"FriendsList_LoadingTitle": "CARREGANDO",
	"FriendsList_StillLoadingSummary": "Carregando rede de amigos...",
	"FriendsList_StillLoadingDetail": "O Steam está tentando conectar-se à rede de amigos, o que pode levar alguns segundos.",
	"Dialog_On": "SIM",
	"Dialog_Off": "NÃO",
	"TimeInterval_XYears": "%1$s anos",
	"TimeInterval_1YearXMonths": "1 ano e %1$s meses",
	"TimeInterval_1Year": "1 ano",
	"TimeInterval_XMonths": "%1$s meses",
	"TimeInterval_1Month": "1 mês",
	"TimeInterval_1MonthX": "1 mês e %1$s dias",
	"TimeInterval_XWeeks": "%1$s semanas ",
	"TimeInterval_1Week": "1 semana",
	"TimeInterval_XDays": "%1$s dias",
	"TimeInterval_1Day": "1 dia",
	"TimeInterval_1DayXHours": "1 dia e %1$s horas",
	"TimeInterval_XHours": "%1$s horas",
	"TimeInterval_1Hour": "1 hora",
	"TimeInterval_1HourXMinutes": "1 hora e %1$s minutos",
	"TimeInterval_LessThanAnHour": "menos de uma hora",
	"TimeInterval_XMinutes": "%1$s minutos",
	"TimeInterval_1Minute": "1 minuto",
	"TimeInterval_LessThanAMinute": "menos de um minuto",
	"TimeSince_XYears": "há %1$s anos",
	"TimeSince_1YearXMonths": "há 1 ano e %1$s meses",
	"TimeSince_1Year": "há 1 ano",
	"TimeSince_XMonths": "há %1$s meses",
	"TimeSince_1Month": "há 1 mês",
	"TimeSince_1MonthXDays": "há 1 mês e %1$s dias",
	"TimeSince_XWeeks": "há %1$s semanas",
	"TimeSince_1Week": "há 1 semana",
	"TimeSince_XDays": "há %1$s dias",
	"TimeSince_1Day": "há 1 dia",
	"TimeSince_1DayXHours": "há 1 dia e %1$s horas",
	"TimeSince_XHours": "há %1$s horas",
	"TimeSince_1Hour": "há 1 hora",
	"TimeSince_1HourXMinutes": "há 1 hora e %1$s minutos",
	"TimeSince_LessThanAnHour": "há menos de uma hora",
	"TimeSince_XMinutes": "há %1$s minutos",
	"TimeSince_1Minute": "há 1 minuto",
	"TimeSince_LessThanAMinute": "há menos de 1 minuto",
	"TimeSince_ThisWeek": "esta semana",
	"Time_Today": "Hoje",
	"Time_Tomorrow": "amanhã",
	"Time_Yesterday": "Ontem",
	"Time_Recent": "Recente",
	"ContextMenu_Copy": "Copiar",
	"ContextMenu_Cut": "Recortar",
	"ContextMenu_Paste": "Colar",
	"ContextMenu_CopyLinkURL": "Copiar link",
	"ContextMenu_OpenLinkInNewWindow": "Abrir link em uma nova janela",
	"ContextMenu_CopyImageURL": "Copiar endereço da imagem",
	"ContextMenu_OpenImageInNewWindow": "Abrir imagem em uma nova janela",
	"Tooltip_Settings": "Gerenciar configurações da lista de amigos",
	"Tooltip_VoiceSettings": "Gerenciar configurações de voz",
	"Tooltip_SearchFriends": "Buscar na minha lista",
	"Tooltip_AddFriend": "Adicionar amigo",
	"Tooltip_FriendRequest": "%1$s pedido de amizade pendente",
	"Tooltip_FriendRequest_Plural": "%1$s pedidos de amizade pendentes",
	"Tooltip_CreateGroupChat": "Criar sala de conversa",
	"Tooltip_InviteToGroup": "Convidar amigos para esta sala de conversa",
	"Tooltip_InviteToGroup_Denied": "Você não tem permissão para convidar usuários para esta sala",
	"Tooltip_GroupChatSettings": "Gerenciar configurações da sala de conversa",
	"Tooltip_MemberCollapse": "Recolher lista de membros",
	"Tooltip_MemberExpand": "Expandir lista de membros",
	"Tooltip_ChatsCollapse": "Recolher lista de conversas",
	"Tooltip_ChatsExpand": "Expandir lista de conversas",
	"Tooltip_MinimizeList": "Recolher lista",
	"Tooltip_ExpandList": "Expandir lista",
	"Tooltip_PinChannelList": "Afixar lista de canais",
	"Tooltip_UnpinChannelList": "Desafixar lista de canais",
	"Tooltip_TextChannel": "Converse por texto com membros da sala",
	"Tooltip_TextChannelCreate": "Criar novo canal de texto",
	"Tooltip_NoPermissionChannelCreate": "Você não tem permissão para criar canais nesta sala",
	"Tooltip_VoiceChannel": "Converse por voz nestes canais",
	"Tooltip_VoiceChannelCreate": "Criar novo canal de voz",
	"Tooltip_DismissVoice": "Recusar convite de voz",
	"Tooltip_MicStatus_Active": "Microfone ativado",
	"Tooltip_MicStatus_Muted": "Microfone desativado",
	"Tooltip_RemoteMicStatus_Muted": "O usuário desativou o microfone",
	"Tooltip_MicStatus_NoMic": "O usuário não conectou um microfone",
	"Tooltip_RemoteOutputStatus_Muted": "O usuário desativou o áudio deste canal",
	"Tooltip_YourMicStatus_Muted": "Você desativou o microfone",
	"Tooltip_YourOutputStatus_Muted": "Você desativou o áudio deste canal",
	"Tooltip_VoiceControlButton_1v1_inactive": "Enviar convite de voz",
	"Tooltip_VoiceControlButton_1v1_active": "Sair do canal de voz",
	"Tooltip_VoiceControlButton_group_create": "Criar um canal de voz",
	"Tooltip_VoiceControlButton_group_leave": "Sair do canal de voz",
	"Tooltip_VoiceControlButton_group_joinsingle": "Entrar no canal de voz",
	"Tooltip_VoiceControlButton_group_joinmultiple": "Escolher uma canal de voz para juntar-se",
	"LanguageTitle": "Idioma",
	"Language_english": "Inglês",
	"Language_german": "Alemão",
	"Language_french": "Francês",
	"Language_italian": "Italiano",
	"Language_korean": "Coreano",
	"Language_spanish": "Espanhol (Espanha)",
	"Language_schinese": "Chinês simplificado",
	"Language_tchinese": "Chinês tradicional",
	"Language_russian": "Russo",
	"Language_thai": "Tailandês",
	"Language_japanese": "Japonês",
	"Language_portuguese": "Português (Portugal)",
	"Language_polish": "Polonês",
	"Language_danish": "Dinamarquês",
	"Language_dutch": "Holandês",
	"Language_finnish": "Finlandês",
	"Language_norwegian": "Norueguês",
	"Language_swedish": "Sueco",
	"Language_hungarian": "Húngaro",
	"Language_czech": "Tcheco",
	"Language_romanian": "Romeno",
	"Language_turkish": "Turco",
	"Language_arabic": "Árabe",
	"Language_brazilian": "Português (Brasil)",
	"Language_bulgarian": "Búlgaro",
	"Language_greek": "Grego",
	"Language_ukrainian": "Ucraniano",
	"Language_latam": "Espanhol (América Latina)",
	"Language_vietnamese": "Vietnamita",
	"Language_koreana": "Coreano",
	"language_selection_english": "English (Inglês)",
	"language_selection_spanish": "Español — España (Espanhol (Espanha))",
	"language_selection_french": "Français (Francês)",
	"language_selection_italian": "Italiano (Italiano)",
	"language_selection_german": "Deutsch (Alemão)",
	"language_selection_greek": "Ελληνικά (Grego)",
	"language_selection_koreana": "한국어 (Coreano)",
	"language_selection_korean": "한국어 (Coreano)",
	"language_selection_schinese": "简体中文 (Chinês Simplificado)",
	"language_selection_tchinese": "繁體中文 (Chinês Tradicional)",
	"language_selection_russian": "Русский (Russo)",
	"language_selection_thai": "ไทย (Tailandês)",
	"language_selection_japanese": "日本語 (Japonês)",
	"language_selection_portuguese": "Português (Portugal)",
	"language_selection_brazilian": "Português (Brasil)",
	"language_selection_polish": "Polski (Polonês)",
	"language_selection_danish": "Dansk (Dinamarquês)",
	"language_selection_dutch": "Nederlands (Holandês)",
	"language_selection_finnish": "Suomi (Finlandês)",
	"language_selection_norwegian": "Norsk (Norueguês)",
	"language_selection_swedish": "Svenska (Sueco)",
	"language_selection_czech": "Čeština (Tcheco)",
	"language_selection_hungarian": "Magyar (Húngaro)",
	"language_selection_romanian": "Română (Romeno)",
	"language_selection_bulgarian": "Български (Búlgaro)",
	"language_selection_pirate": "Yarr! (Inglês Pirata)",
	"language_selection_turkish": "Türkçe (Turco)",
	"language_selection_ukrainian": "Українська (Ucraniano)",
	"language_selection_vietnamese": "Tiếng Việt (Vietnamita)",
	"language_selection_arabic": "العربية (Árabe)",
	"language_selection_spanish_mexican": "Español — Mexicano (Espanhol (México))",
	"language_selection_latam": "Español — Latinoamérica (Espanhol (América Latina))",
	"Bbcode_Originally_Posted_By": "Publicado originalmente por",
	"Bbcode_No_Match": "Não corresponde a BBCode válido",
	"Editor_Bold": "Negrito",
	"Editor_Underline": "Sublinhado",
	"Editor_Italics": "Itálico",
	"Editor_StrikeThrough": "Riscado",
	"Editor_Link": "Inserir link",
	"Editor_Unordered": "Lista não ordenada",
	"Editor_Ordered": "Lista ordenada",
	"Editor_Header": "Cabeçalho",
	"Editor_Header2": "Cabeçalho 2",
	"Editor_Header3": "Cabeçalho 3",
	"Editor_Emoticon": "Inserir emoticon",
	"EventEditor_ConvertHTML_Error": "Não foi possível converter o HTML",
	"EventEditor_ConvertHTML_Error_Desc": "Falha na conversão de HTML para BBCode com o seguinte erro: \"%1$s\"",
	"EventEditor_InsertLinkURL": "Inserir URL",
	"EventEditor_FormattingHelp_GetHelpLink": "Ajuda de formatação",
	"EventEditor_ImportHTML": "Importar HTML",
	"EventEditor_ImportFromHTML": "Importar de HTML",
	"EventEditor_ImportFromHTML_ttip": "Importar de HTML. Converterá automaticamente o seu HTML em marcadores de formatação do Steam.",
	"EventEditor_ImportFromHTML_Instruction": "Digite ou cole o código HTML abaixo.",
	"EventEditor_ImportFromHTML_PreserveNewlines": "Manter quebras de linha",
	"EventEditor_ImportFromHTML_PreserveNewlines_Hint": "Quebras de linha não costumam fazer efeito em HTML, mas em BBCode elas são exibidas como linhas em branco. Caso tenha usado marcadores <p> ou <br>, deixe a caixa desmarcada. Caso costume usar programas que adicionam marcadores <br> de forma automática para quebras de linha, você provavelmente deverá marcar esta caixa.",
	"EventEditor_ImportFromHTML_ConvertToBBCode": "Converter para BBCode:",
	"EventEditor_ImportFromHTML_ConversionInProgress": "Conversão em andamento. Por favor, não feche essa janela.",
	"EventEditor_ImportFromHTML_ConvertFinished": "Conversão concluída. Você pode fechar essa janela com segurança.",
	"EventEditor_InsertYouTube": "Inserir vídeo do YouTube™",
	"EventEditor_InsertYouTube_Left": "Alinhado à esquerda",
	"EventEditor_InsertYouTube_Right": "Alinhado à direita",
	"EventEditor_InsertYouTube_Full": "Largura completa",
	"EventEditor_InsertYouTube_URL": "URL completo",
	"EventEditor_InsertYouTube_Position": "Posição",
	"EventEditor_InsertYouTube_Placholder": "Insira um URL do YouTube™",
	"EventEditor_InsertYouTube_NoURL": "Por favor, insira um URL válido do YouTube™.",
	"EventEditor_InsertYouTube_Summary": "Descrição resumida",
	"EventEditor_InsertImage": "Inserir uma imagem da web",
	"EventEditor_InsertImage_Title": "Inserir imagem",
	"EventEditor_InsertImage_Desc": "Insira o URL de uma imagem (por exemplo .jpg, .gif ou .png) para a incluí-la na publicação.",
	"EventEditor_InsertImage_URL": "URL da imagem",
	"EventEditor_InsertImage_Placeholder": "Informe um URL válido",
	"EventEditor_InsertImage_Anchor": "Opcional: URL a abrir ao clicar na imagem",
	"EventEditor_LinkDescription": "Texto a ser exibido",
	"EventEditor_LinkURL": "URL",
	"EventEditor_YouTubeVideoTitle": "Vídeo do YouTube™: %1$s",
	"EventEditor_YouTubeVideoViews": "Visualizações: %1$s",
	"EventEditor_Author": "Por: %1$s",
	"EventEditor_Comments": "Comentários",
	"EventEditor_UpVotes": "Avaliações positivas",
	"EventEditor_DownVotes": "Avaliações negativas",
	"Error_Message": "Mensagem de erro",
	"Warning_Message": "Mensagem de aviso",
	"Informational_Message": "Mensagem informativa",
	"Error_Description": "Ocorreu um erro (código: %1$s) detalhes: (%2$s)",
	"Error_FailureNotice": "Falha",
	"Error_GenericFailureDescription": "Lamentamos, isso não funcionou.",
	"Image_ErrorTitle": "Falha ao carregar a imagem \"%1$s\", possíveis erros incluem:",
	"Image_Error_msg1": "Confirme se o caminho da imagem está correto.",
	"Image_Error_msg2": "Confirme se o servidor de hospedagem da imagem é compatível com acesso anônimo. O console do navegador pode indicar um erro do tipo \"Access-Control-Allow-Origin\" caso incompatível.",
	"Image_Error_suggestion": "É possível hospedar a imagem no Steam gratuitamente.",
	"Platform_Hint_Mobile": "em dispositivo móvel",
	"Platform_Hint_BigPicture": "no Big Picture",
	"Platform_Hint_VR": "em Realidade Virtual",
	"Hover_SteamLevel": "Nível Steam",
	"Hover_BadgeXP": "%1$s XP",
	"PersonaStateOffline": "Offline",
	"PersonaStateAway": "Ausente",
	"PersonaStateOnline": "Disponível",
	"PersonaStateBlocked": "Bloqueado(a)",
	"PersonaStateInGame": "Em jogo",
	"PersonaStateBusy": "Ocupado(a)",
	"PersonaStateSnooze": "Ausente",
	"PersonaStateInNonSteamGame": "Em jogo não Steam",
	"PersonaStateWatchingBroadcast": "Assistindo à transmissão:",
	"PersonaStateLookingToTrade": "Querendo trocar",
	"PersonaStateLookingToPlay": "Querendo jogar",
	"PersonaStateLastSeen": "Última vez online %1$s",
	"PersonaStateLastSeen_JustNow": "Última vez online agora há pouco",
	"PersonaStateRemotePlayTogether": "Remote Play Together",
	"User_WantsToPlay": "Entrar",
	"User_ToggleDoNotDisturb": "Não perturbe",
	"User_GameInfoHidden": "Os detalhes do jogo estão ocultados devido às suas configurações de privacidade",
	"User_LimitedAccount": "Sua conta não possui os requisitos necessários para usar este recurso. %1$s para mais informações.",
	"User_LimitedAccount_UrlInfo": "Acesse o Suporte Steam",
	"isNickname": "O apelido que você deu a este amigo",
	"Friend_Menu_NotAFriendLabel": "Não são amigos",
	"Friend_Menu_NotAFriendRequesting": "Enviou pedido de amizade",
	"DASHPlayerStats_BytesReceived": "Bytes recebidos:",
	"DASHPlayerStats_BufferingResolution": "Resolução em buffer:",
	"DASHPlayerStats_PlaybackResolution": "Resolução de reprodução:",
	"DASHPlayerStats_HtmlResolution": "Resolução de exibição:",
	"DASHPlayerStats_DroppedFrames": "Quadros descartados:",
	"DASHPlayerStats_VideoBuffered": "Vídeo em buffer:",
	"DASHPlayerStats_AudioBuffered": "Áudio em buffer:",
	"DASHPlayerStats_BandwidthRequired": "Largura de banda necessária (Mbps):",
	"DASHPlayerStats_BandwidthVideo": "Largura de banda do vídeo (Mbps):",
	"DASHPlayerStats_BandwidthNums": "Largura de banda mín./máx./méd. (Mbps):",
	"DASHPlayerStats_DownloadNums": "Segundos p/ DL mín./máx./méd.:",
	"DASHPlayerStats_ContentServer": "Servidor:",
	"DASHPlayerStats_ActiveDownloads": "Downloads ativos:",
	"DASHPlayerStats_StallEvents": "Eventos de espera:",
	"DASHPlayerStats_FailedDownloads": "Eventos de download com falha:",
	"DASHPlayerStats_VideoDownloadProgress": "Progresso de download do vídeo:",
	"DASHPlayerStats_TimeToFirstFrame": "Milissegundos até 1º quadro:",
	"DASHPlayerStats_DroppingFrames": "Quadros perdidos detectados:",
	"DASHPlayerStats_CurrentFPS": "Taxa de quadros atual:",
	"DASHPlayerStats_Tracking": "Coletando dados...",
	"DASHPlayerStats_PlaybackRate": "Velocidade de reprodução:",
	"DASHPlayerStats_VideoBufferRange": "Buffer de vídeo %1$s:",
	"DASHPlayerStats_AudioBufferRange": "Buffer de áudio %1$s:",
	"DASHPlayerStats_VideoNoRangeInformation": "Nenhum segmento de vídeo em buffer",
	"DASHPlayerStats_AudioNoRangeInformation": "Nenhum segmento de áudio em buffer",
	"DASHPlayerControls_GoLive": "Ao vivo",
	"DASHPlayerControls_IsLive": "Ao vivo",
	"DASHPlayerControls_ClickToPlay": "Clique para assistir",
	"DASHPlayerControls_IsReplay": "REPRISE",
	"DASHPlayerControls_Start": "Início",
	"DASHPlayerControls_End": "Fim",
	"Played_Minutes": "%1$s minutos",
	"Played_Hours": "%1$s horas",
	"WriteReview_Dialog_PostReview": "Publicar análise",
	"WriteReview_Dialog_ReviseReview": "Revisar análise",
	"WriteReview_Dialog_Title": "Análise",
	"WriteReview_Dialog_Playtime": "Jogado por %1$s",
	"WriteReview_Dialog_Playtime_Software": "Você usou este título durante %1$s",
	"WriteReview_Dialog_Playtime_Revise": "Você jogou mais %1$s",
	"WriteReview_Dialog_RecommendGame": "Você recomendaria este jogo para outros jogadores?",
	"WriteReview_Dialog_RecommendGame_Software": "Você recomendaria este software para outros jogadores?",
	"WriteReview_Dialog_RecommendGame_Revise": "Deseja revisar a sua análise?",
	"WriteReview_Dialog_GetHelp_Btn": "Obter ajuda com a compra",
	"WriteReview_Dialog_Visibility": "Visibilidade:",
	"WriteReview_Dialog_Public": "Pública",
	"WriteReview_Dialog_Friends": "Só amigos",
	"WriteReview_Dialog_Yes": "Sim",
	"WriteReview_Dialog_No": "Não",
	"WriteReview_Dialog_GetSupport_Btn": "Obter ajuda com a compra",
	"WriteReview_Dialog_GetSupport_Desc": "Obtenha ajuda técnica, suporte ao cliente ou solicite um reembolso.",
	"WriteReview_Dialog_AddReview_Btn": "Publicar análise",
	"WriteReview_Dialog_AddReview_Desc": "Compartilhe a sua opinião com outros jogadores.",
	"WriteReview_Dialog_AddReview_Header": "Deseja publicar uma análise?",
	"WriteReview_Dialog_ReviewInstructions_Link": "regras e diretrizes",
	"WriteReview_Dialog_ReviewInstructions": "Por favor, descreva o que gostou e o que não gostou neste jogo e se você o recomenda a outros. Não se esqueça de ser educado e seguir as %1$s. É preciso uma descrição para publicar a sua recomendação.",
	"WriteReview_Dialog_AllowComments": "Permitir comentários",
	"WriteReview_Dialog_FreeDisclaimer": "Assinale esta caixa caso tenha recebido o produto de graça",
	"WriteReview_Dialog_FreeDisclaimer_Tooltip": "Assinale esta caixa caso tenha recebido o produto de graça; o texto \"Produto recebido de graça\" será exibido junto à análise. Caso tenha sido remunerado para escrever a análise, deixe isso claro no texto.",
	"WriteReview_Dialog_FormattingHelp": "Ajuda de formatação",
	"WriteReview_Dialog_GenericError": "Ocorreu um erro ao publicar a sua análise. Por favor, tente novamente mais tarde.",
	"WriteReview_Dialog_NoTextError": "Por favor, descreva o que gostou ou não neste produto.",
	"WriteReview_Dialog_Delay": "Talvez depois",
	"Broadcast_View_Stack_H": "Exibição horizontal",
	"Broadcast_View_Stack_V": "Exibição vertical",
	"Broadcast_View_Theater": "Modo cinema",
	"Broadcast_View_Fullscreen": "Tela cheia",
	"Broadcast_View_HideChat": "Ocultar conversa",
	"Broadcast_View_ShowBothChats": "Exibir as duas conversas",
	"Broadcast_View_ShowSingleChats": "Exibir só uma conversa",
	"Broadcast_View_ShowChat": "Exibir conversa",
	"Broadcast_Store_FreeToPlay": "Gratuito para jogar",
	"PartnerEvent_1": "Outro evento",
	"PartnerEvent_2": "Evento de jogo",
	"PartnerEvent_3": "Evento de grupos",
	"PartnerEvent_4": "Encontro",
	"PartnerEvent_5": "Causa especial",
	"PartnerEvent_6": "Evento de música e artes",
	"PartnerEvent_7": "Evento esportivo",
	"PartnerEvent_8": "Evento de viagem ao vivo",
	"PartnerEvent_9": "Conversa",
	"PartnerEvent_9_editor": "Conversa / Sessão de perguntas e respostas",
	"PartnerEvent_10": "Lançamento de jogo",
	"PartnerEvent_10_editor": "O jogo já está disponível!",
	"PartnerEvent_11": "Transmissão ao vivo",
	"PartnerEvent_12": "Pequena atualização (detalhes)",
	"PartnerEvent_13": "Atualização",
	"PartnerEvent_14": "Grande atualização",
	"PartnerEvent_15": "Lançamento de conteúdo adicional",
	"PartnerEvent_16": "Lançamento futuro",
	"PartnerEvent_16_editor": "Lançamento em data específica",
	"PartnerEvent_17": "Transmissão de torneio",
	"PartnerEvent_18": "Transmissão dos desenvolvedores",
	"PartnerEvent_19": "Transmissão de celebridade",
	"PartnerEvent_20": "Jogo com desconto",
	"PartnerEvent_20_editor": "Desconto neste jogo",
	"PartnerEvent_21": "Item ou conteúdo adicional com desconto",
	"PartnerEvent_21_editor": "Desconto em itens do jogo ou conteúdo adicional",
	"PartnerEvent_22": "Experiência adicional",
	"PartnerEvent_23": "Evento de itens",
	"PartnerEvent_24": "Evento de benefícios",
	"PartnerEvent_25": "Evento de desafios",
	"PartnerEvent_26": "Concurso",
	"PartnerEvent_27": "Evento no mundo real",
	"PartnerEvent_27_editor": "Encontro em exposição, evento ou convenção",
	"PartnerEvent_28": "Notícias",
	"PartnerEvent_28_editor": "Anúncio / Notícias",
	"PartnerEvent_29": "Lançamento de beta",
	"PartnerEvent_29_editor": "Convite / Novidades do beta",
	"PartnerEvent_30": "Lançamento de conteúdo no jogo",
	"PartnerEvent_31": "Teste gratuito",
	"PartnerEvent_32": "Lançamento de temporada ou passe de batalha",
	"PartnerEvent_33": "Atualização de temporada",
	"PartnerEvent_34": "Promoção cruzada",
	"PartnerEvent_35": "Evento no jogo",
	"PartnerEvent_Other": "Evento de outro tipo",
	"PartnerEvent_SteamAwardNominations": "Solicitação de indicação aos Prêmios Steam",
	"PartnerEvent_SteamAwardVoteRequest": "Pedido de voto para os Prêmios Steam",
	"SocialMedia_Type_ShortName_1": "Steam",
	"SocialMedia_Type_ShortName_2": "Google",
	"SocialMedia_Type_ShortName_3": "Facebook",
	"SocialMedia_Type_ShortName_4": "Twitter",
	"SocialMedia_Type_ShortName_5": "Twitch",
	"SocialMedia_Type_ShortName_6": "YouTube",
	"SocialMedia_Type_ShortName_7": "Facebook",
	"MobileLogin_NoSteamAccount": "Não tem uma conta Steam?",
	"MobileLogin_CreateAccount": "Crie uma conta grátis",
	"MobileLogin_ForgotPassword": "Esqueceu o seu nome de usuário ou senha?",
	"MobileLogin_RefreshCaptcha": "Atualizar",
	"MobileLogin_SignIn": "Iniciar sessão",
	"MobileLogin_SigningIn": "Iniciando a sessão",
	"MobileLogin_AccountName": "Nome de usuário Steam",
	"MobileLogin_Password": "Senha",
	"MobileLogin_CaptchaVerification": "Verificação",
	"MobileLogin_Enter2FA": "Insira o código gerado na aba do Steam Guard no seu aplicativo móvel do Steam.",
	"MobileLogin_Enter2FAHelp": "Não tenho acesso ao meu código do Steam Guard",
	"MobileLogin_EnterSteamguard": "Não recebi o e-mail do código do Steam Guard",
	"MobileLogin_SteamguardCode": "Código do Steam Guard",
	"MobileLogin_SteamguardSubmit": "Enviar e iniciar a sessão",
	"MobileLogin_SentSteamguard_1": "Enviamos uma mensagem para o seu",
	"MobileLogin_SentSteamguard_2": "e-mail. Insira o código fornecido pelo Steam Guard.",
	"MobileLogin_IncorrectSteamGuard": "O código do Steam Guard informado está incorreto. Por favor, confirme o código e tente novamente.",
	"MobileLogin_Error_RateLimitExceeded": "Houve muitas tentativas fracassadas de início de sessão a partir da sua rede em um curto período de tempo. Por favor, aguarde e tente novamente mais tarde.",
	"Login_SignIn": "Iniciar sessão",
	"Login_SigningIn": "Iniciando a sessão",
	"Login_AccountName": "Nome de usuário Steam",
	"Login_Password": "Senha",
	"Login_RememberMe": "Lembrar de mim neste computador",
	"Login_ForgotPassword": "Esqueceu o seu nome de usuário ou senha?",
	"Login_NoSteamAccount": "Não tem uma conta Steam?",
	"Login_CreateAccount": "Cadastre-se gratuitamente",
	"Login_CaptchaVerification": "Por favor, confirme que você é um humano redigitando os caracteres da imagem.",
	"Login_RefreshCaptcha": "Atualizar",
	"Login_Enter2FA": "Insira o código gerado na aba do Steam Guard no seu aplicativo móvel do Steam.",
	"Login_Enter2FAHelp": "Não tenho acesso ao meu código do Steam Guard",
	"Login_EnterSteamguard": "Não recebi um e-mail do Steam Guard",
	"Login_SteamguardSubmit": "Enviar e iniciar a sessão",
	"Login_SentSteamguard": "Enviamos uma mensagem para o seu e-mail @%1$s. Insira o código do Steam Guard fornecido.",
	"Login_SignOut": "Finalizar sessão",
	"Emoticon_Search": "Buscar emoticons",
	"Chat_Settings_Error_ChatFileTooLarge": "%1$s é grande demais (máximo de 10 MB).",
	"Chat_Settings_Error_ChatFileTypeNotSupported": "Não foi possível enviar %1$s. Apenas arquivos JPG, PNG, GIF, WEBM, MPG e OGV são permitidos.",
	"ConnectionTrouble_FailedToConnect": "Ocorreu um erro ao conectar-se ao Steam",
	"Chat_Upload_ErrorCloud": "Ocorreu um erro ao enviar imagem ao servidor em nuvem.",
	"Chat_Settings_Error_ServerError": "Ocorreu um erro no servidor",
	"Broadcast_ViewerCount": "%1$s espectadores",
	"Broadcast_VideoContext_ToggleStats": "Exibir estatísticas",
	"Broadcast_VideoContext_OpenStore": "Página na loja",
	"Broadcast_None": "Nenhuma",
	"BroadcastWatch_MinBrowser": "O navegador atual não possui os recursos necessários para assistir à transmissão",
	"BroadcastWatch_RequestFailed": "Falha ao carregar transmissão",
	"BroadcastWatch_NotAvailable": "Transmissão offline",
	"BroadcastWatch_WaitingForResponse": "Aguardando aprovação para assistir",
	"BroadcastWatch_WaitingForStart": "Transmissão sendo iniciada",
	"BroadcastWatch_WaitingForReconnect": "Reconectando-se à transmissão",
	"BroadcastWatch_ServerLoad": "O Steam está com alta carga de transmissão, não sendo possível reservar um lugar no servidor para iniciar esta transmissão. Por favor, tente novamente em alguns minutos.",
	"BroadcastWatch_SystemNotSupported": "A Transmissão Steam não está disponível no sistema do transmissor",
	"BroadcastWatch_UserRestricted": "Transmissor atualmente suspenso de transmitir no Steam",
	"BroadcastWatch_PoorUploadQuality": "Transmissor incapaz de manter uma conexão de transmissão estável ao Steam",
	"BroadcastChat_Reconnected": "Reconectado à conversa",
	"BroadcastChat_UnableToJoinChat": "Não foi possível entrar na conversa",
	"BroadcastChat_NeverTell": "Nunca revele a sua senha a ninguém",
	"BroadcastChat_EnterResponse": "Digite para conversar",
	"BroadcastChat_InsertEmoticon": "Inserir emoticon",
	"BroadcastChat_Send": "Enviar",
	"BroadcastChat_UserJoined": "%1$s entrou na sala",
	"BroadcastChat_UserLeft": "%1$s saiu da sala",
	"BroadcastChat_UserMuted": "%1$s foi silenciado(a) nesta sala",
	"BroadcastChat_UserMutedLocal": "%1$s foi silenciado(a)",
	"BroadcastChat_UserUnmutedLocal": "%1$s não está mais silenciado(a)",
	"BroadcastChat_UserMuteFailed": "Falha ao silenciar %1$s. Por favor, tente novamente.",
	"BroadcastChat_RemoveMessagesFailed": "Falha ao remover mensagens de %1$s. Por favor, tente novamente.",
	"BroadcastChat_UserUnmuteFailed": "Falha ao remover silêncio de %1$s. Por favor, tente novamente.",
	"BroadcastChat_YouMuted": "Você foi silenciado e não pode enviar mensagens nesta sala",
	"BroadcastChat_FailedToSendMsg": "Falha ao enviar mensagem: %1$s",
	"BroadcastChat_Cooldown": "Você está enviando mensagens rápido demais, tente novamente em %1$s segundo(s).",
	"BroadcastChat_Mute": "Silenciar",
	"BroadcastChat_Unmute": "Remover silêncio",
	"BroadcastChat_MuteLocal": "Silenciar localmente",
	"BroadcastChat_UnmuteLocal": "Remover silêncio",
	"BroadcastChat_Login": "Inicie a sessão para participar",
	"BroadcastChat_LimitedUser": "Acesso limitado",
	"BroadcastChat_RemoveMessages": "Remover mensagens do usuário",
	"BroadcastChat_Blocked": "Só quem possui o jogo tem permissão para participar da conversa durante esta transmissão.",
	"BroadcastChat_half_Mute": "Silenciar usuário por 12 horas",
	"BroadcastChat_day_Mute": "Silenciar usuário por um dia",
	"BroadcastChat_week_Mute": "Silenciar usuário por uma semana",
	"BroadcastChat_perm_Mute": "Silenciar usuário permanentemente",
	"BroadcastChat_half_Shadow": "Silenciar usuário de forma discreta por 12 horas",
	"BroadcastChat_day_Shadow": "Silenciar usuário de forma discreta por um dia",
	"BroadcastChat_week_Shadow": "Silenciar usuário discretamente por uma semana",
	"BroadcastChat_perm_Shadow": "Silenciar usuário de forma discreta permanentemente",
	"BroadcastChat_Add_Moderator": "Promover usuário a moderador",
	"BroadcastChat_Remove_Moderator": "Remover usuário como moderador",
	"BroadcastChat_Change_Moderator_Title": "Alterar moderação da sala",
	"BroadcastChat_Change_Add_Confirm": "Tem certeza de que deseja promover o usuário abaixo a moderador? Ele(a) poderá silenciar outros usuários na sala de conversa da transmissão.",
	"BroadcastChat_Change_Remove_Confirm": "Tem certeza de que deseja remover o usuário abaixo como moderador do canal?",
	"BroadcastChat_Tooltip_Show_Chat_Viewers": "Exibir uma lista de participantes da sala de conversa da transmissão.",
	"BroadcastChat_Tooltip_Minimize_Chat": "Minimizar a janela de conversa",
	"BroadcastChat_Tooltip_Maximize_Chat": "Maximizar a janela de conversa",
	"BroadcastChat_Tooltip_Popout_Chat": "Abrir a conversa em uma janela separada",
	"BroadcastChat_ChatOnly_Title": "Sala de conversa da transmissão",
	"BroadcastChat_DefaultMessage": "Bem-vindo(a) à conversa!",
	"BroadcastChat_Moderator": "Moderador",
	"BroadcastChat_Broadcaster": "Transmissor",
	"ChatEntryButton_Submit": "Enviar",
	"ChatEntryButton_Emoticon": "Menu de emoticons",
	"ChatEntryButton_Flair": "Ícones",
	"ChatEntryButton_SendEmbed": "Enviar especial",
	"Store_AddToCart": "+ Carrinho",
	"YouTubePlayer_Loading": "Carregando YouTube...",
	"home_page_live_broadcast": "No ar",
	"StoreBroadcast_Hide_Tooltip": "Mostrar/ocultar transmissão ao vivo",
	"StoreBroadcast_Detault_popout_Title": "Transmitindo agora",
	"StoreBroadcast_close_broadcast_popup": "Fecha a janela pop-up da transmissão. Não será possível reabri-la durante esta sessão.",
	"StoreBroadcast_Change_store_Broadcast_settings": "Alterar configurações de transmissão",
	"Broadcast_Embedded_viewer": "%1$s espectador",
	"Broadcast_Embedded_viewer_Plural": "%1$s espectadores",
	"BroadcastWatch_View_Broadcast_Page": "Exibir página da transmissão",
	"Broadcast_Embed_Watch_SteamTV": "Assistir na Steam.tv",
	"Broadcast_Embed_Watch_With_Frieds_SteamTV": "Ver e conversar com amigos na Steam.tv",
	"sale_three_section_hide_chat": "Ocultar conversa",
	"sale_three_section_show_chat": "Exibir conversa",
	"btn_live_streams_all": "Ver todas",
	"Broadcast_default_title_dev": "Transmissão ao vivo: assista ao desenvolvedor jogar",
	"Broadcast_default_title_community": "Transmissão ao vivo: assista à comunidade jogar",
	"Broadcast_default_title_comp": "Transmissão ao vivo: assista a esta partida competitiva",
	"Broadcast_default_title_speed": "Transmissão ao vivo: assista a esta corrida contra o tempo",
	"Sale_BundleSave": "Inclui %1$s itens.",
	"Sale_PackageSave": "Inclui %1$s itens.",
	"Sale_ShowContents": "Exibir conteúdo",
	"Sale_ShowMore": "Exibir mais",
	"Sale_ShowLess": "Exibir menos",
	"Sale_OnWishlist": "Na lista de desejos",
	"Sale_InLibrary": "Na biblioteca",
	"Sale_HiddenItems": "Ocultamos %1$s itens devido às %2$s",
	"Sale_HiddenItem_Single": "Ocultamos %1$s item devido às %2$s",
	"Sale_StorePreferences": "suas preferências da loja",
	"Sale_SeeAllSpecials": "Ver todas as promoções",
	"Sale_AddToWishlist": "Adicionar à lista de desejos",
	"Sale_RemoveFromWishlist": "Remover da lista de desejos",
	"Sale_Preferences": "Preferências",
	"Sale_PlaceHolder": "Modo de pré-visualização: esta seção não contém cápsulas e por isso não aparecerá na página do usuário.",
	"Sale_SmartPlaceHolder": "Modo de pré-visualização: esta seção não contém aplicativos para você e por isso não aparecerá na página do usuário.",
	"Sale_default_label": "(sem título)",
	"Sale_default_label_OnSale": "Em oferta",
	"Sale_default_label_TopSellers": "Mais vendidos",
	"Sale_default_label_FreeToPlay": "Gratuitos para jogar",
	"Sale_default_label_HorrorGames": "Jogos de terror",
	"Sale_default_label_HorrorVR": "Terror em RV",
	"Sale_default_label_HorrorFreeToPlay": "Terror gratuito para jogar",
	"Sale_default_label_HalloweenEventsHorror": "Eventos de Dia das Bruxas em jogos de terror",
	"Sale_default_label_HalloweenEventsNonHorror": "Eventos de Dia das Bruxas em jogos que não são de terror",
	"Sale_default_label_MoreHalloweenEvents": "Mais eventos de Dia das Bruxas",
	"Sale_default_label_MoreHalloweenEventsNonHorror": "Mais eventos de Dia das Bruxas em jogos que não são de terror",
	"Sale_default_label_NewAndUpcomingHorror": "Jogos de terror recentes e disponíveis em breve",
	"Sale_default_label_RemotePlay_Together": "Play Together — jogue com amigos remotamente",
	"Sale_default_label_RemotePlay_Phone": "Play Anywhere — jogue pelo seu dispositivo móvel",
	"Sale_default_label_RemotePlay_Tablet": "Play Anywhere — jogue pelo seu tablet",
	"Sale_default_label_RemotePlay_TV": "Play Anywhere — jogue pela sua TV",
	"Sale_default_label_OnYourWishlist": "Na sua lista de desejos",
	"Sale_default_label_RecommendedForYou": "Recomendado para você",
	"Sale_default_label_ComingSoon": "Em breve",
	"Sale_default_label_JustAnnounced": "Recém-anunciados",
	"Sale_default_label_JustUpdated": "Recém-atualizados",
	"Sale_default_label_FreeWeekend": "Fim de semana grátis",
	"Sale_default_label_FreeWeek": "Semana grátis",
	"Sale_default_label_PrePurchase": "Compre já na pré-venda",
	"Sale_default_label_NewReleases": "Lançamentos",
	"Sale_default_label_JustReleased": "Novos lançamentos",
	"Sale_default_label_Highlighted": "Ofertas em destaque",
	"Sale_default_label_BackCat": "Catálogo",
	"Sale_default_label_PlayForFree": "Grátis para jogar!",
	"Sale_defautl_label_FreeToKeep": "Por tempo limitado, baixe agora e jogue para sempre",
	"SalePage_LoginPrompt": "Inicia sessão para ver mais itens selecionados só para você.",
	"SalePage_ParentApp_DLC": "Conteúdo adicional para",
	"SalePage_ParentApp_SoundTrack": "Trilha sonora para",
	"SalePage_WatchForDrop_Minutes_Developer": "Assista à transmissão durante %1$s minutos e obtenha itens do desenvolvedor quando o evento terminar!",
	"SalePage_WatchForDrop_Minutes_CreatorNamed": "Assista à transmissão durante %1$s minutos e obtenha itens da(o) %2$s quando o evento terminar!",
	"SalePage_WatchForDrop_Hours_Developer": "Assista à transmissão durante %1$s horas e obtenha itens do desenvolvedor quando o evento terminar!",
	"SalePage_WatchForDrop_Hours_CreatorNamed": "Assista à transmissão durante %1$s minutos e itens da(o) %2$s quando o evento terminar!",
	"SalePage_WatchForDrop_LearnMore": "Saiba mais sobre os itens aqui.",
	"SalePage_Admin_SaleEventDay": "Visualizar dia %1$s da promoção",
	"Steam_Settings_Compat_Launch_Prefix": "Funciona neste computador via",
	"Steam_Settings_Compat_Launch_Name": "Steam Play.",
	"Steam_Settings_Compat_Launch_Forced": "selecionado por você para este título.",
	"Steam_Settings_Compat_Launch_Wildcard": "selecionado por você para todos os títulos.",
	"Steam_Settings_Compat_Launch_Whitelisted": "selecionado pelos testes da Valve.",
	"SteamAwards_EventMainTitle": "Os Prêmios Steam",
	"SteamAwards_EventMainTitleSecondLine": "Indicado",
	"SteamAwards_EventCallToAction": "Chegando em dezembro",
	"SteamAwards_EventVotingDateTeaser": "Dezembro de 2019",
	"SteamAwards_EventVoteForGamePrompt": "Clique abaixo para votar em %1$s na seguinte categoria:",
	"SteamAwards_EventNominateGamePrompt_Long": "Indique %1$s para a categoria abaixo, conforme sugerido pelos desenvolvedores do jogo, ou selecione uma categoria diferente",
	"SteamAwards_EventNominateGamePrompt_NoCategory": "Clique aqui para indicar %1$s a uma categoria na página dos Prêmios Steam.",
	"SteamAwards_Event_NominationsClosed": "Indicações encerradas. Vote durante a Promoção de Fim de Ano. Os vencedores serão anunciados em 31 de dezembro.",
	"SteamAwards_Event_VotesClosed": "Votações encerradas. Clique aqui para ver os resultados.",
	"SteamAwards_EventNominateGamePrompt_CategoryPrefix": "Indicar para:",
	"SteamAwards_EventNominationAlternativeLinkText": "Ou escolha outra categoria",
	"SteamAward_CategoryTitle_none": "Nenhuma categoria",
	"SteamAward_CategoryDesc_none": "Não sugira uma categoria, deixando que os fãs escolham qual delas acha a mais adequada para o jogo. Mesmo sem uma categoria, o evento incluirá um link para a página de indicações.",
	"SteamAward_CategoryTitle_goty": "Jogo do ano de 2019",
	"SteamAward_CategoryDesc_goty": "Talvez tenha sido por causa da jogabilidade imersiva ou o seu enredo emocionante... os seus personagens que parecem ter vida, design quase perfeito ou multijogador viciante. Seja qual for o motivo, o vencedor do prêmio de \"Jogo do ano\" de 2019 já pode ser considerado um clássico.",
	"SteamAward_CategoryTitle_vrgoty": "Jogo de RV do ano de 2019",
	"SteamAward_CategoryDesc_vrgoty": "Quando o assunto é inovar no mundo dos jogos, não há lugar melhor do que a realidade virtual. Se pudéssemos, premiaríamos todos os desenvolvedores de RV por construir o futuro dos jogos e experiências imersivas inexistentes em qualquer outro meio. Mas como só temos um troféu, cabe a você, membro do Comitê de Seleção dos Prêmios Steam, coroar um deles como o melhor do ano.",
	"SteamAward_CategoryTitle_love": "Feito com amor 2019",
	"SteamAward_CategoryDesc_love": "Este jogo foi lançado tem tempo. A equipe já anunciou o seu bebê criativo há anos, mas, como bons pais, ela continua a nutrir e dar apoio à sua criação. Esta categoria é para o jogo que recebe conteúdo novo mesmo depois de tantos anos.",
	"SteamAward_CategoryTitle_friends": "Melhor com amigos de 2019",
	"SteamAward_CategoryDesc_friends": "Tem jogos que não são a mesma coisa quando se joga a sós. Talvez precise de um amigo para servir de guarda-costas. Talvez precise de um amigo para apunhalar nas costas. De qualquer forma, a diversão espera aqueles que reúnem amigos para jogar estes jogos.",
	"SteamAward_CategoryTitle_gameplay": "Jogabilidade mais inovadora",
	"SteamAward_CategoryDesc_gameplay": "Este jogo está na linha de frente da experimentação, inovando neste meio com interações nunca antes vistas e surpresas impressionantes. Este jogo pensa fora da caixa e leva você junto!",
	"SteamAward_CategoryTitle_storyrich": "Trama excepcional",
	"SteamAward_CategoryDesc_storyrich": "Tem dias que a gente precisa de um jogo com um enredo envolvente, e este é daqueles que nos pegam de jeito, com uma trama tão emocionante como de uma novela, mas afinada como um roteiro premiado. Bravíssimo — pelas emoções que sentimos!",
	"SteamAward_CategoryTitle_yousuck": "Melhor jogo que você joga mal",
	"SteamAward_CategoryDesc_yousuck": "Jogos nos fazem ultrapassar os limites que nos impomos. Como uma história de superação, nós damos duro, treinando os dedos para serem rápidos e leves, dominando o tempo e o espaço durante semanas. Ao fim da missão, somos recompensados com a mais pura beleza e uma sensação de autoaperfeiçoamento - a menos que tenha jogado o seu monitor pela janela já no primeiro dia.",
	"SteamAward_CategoryTitle_visual": "Estilo visual excepcional",
	"SteamAward_CategoryDesc_visual": "Estes desenvolvedores são especialistas em colírios para os olhos. Estilo visual não significa fidelidade gráfica com o mundo real (embora este seja um objetivo nobre)… É um olhar distinto que permeia todo o jogo. Este jogo oferece coesão e expressão visuais que não só pertencem ao mundo dos video games, mas que também fazem o nosso mundo parecer meramente insignificante.",
	"SteamAward_NominationConflictWarning_Title": "Alterar a sua indicação?",
	"SteamAward_NominationConflictWarning_Explanation": "Só é possível indicar um jogo por categoria, e você já indicou %1$s para esta. Mudou de ideia e gostaria de indicar %2$s?",
	"SteamAward_VoteButton_PromptText": "Votar",
	"SteamAward_VoteButton_AlreadyVotedText": "Voto enviado",
	"SteamAward_VoteConflictWarning_Title": "Quer mudar seu voto?",
	"SteamAward_VoteConflictWarning_Explanation": "Só é possível votar em um jogo por categoria, e você já votou em %1$s nesta categoria. Gostaria de trocar o seu voto para %2$s?",
	"Store_VR_Support_OnlyVR": "Apenas para RV",
	"Store_VR_Support_SupportsVR": "Compatíveis com RV",
	"Giveaway_CountDown": "Tempo restante até o próximo sorteio: %1$s!",
	"Giveaway_CountDown2": "Tempo restante até o próximo sorteio.",
	"Giveaway_KeepWatching": "Fique de olho para ter uma chance de ganhar!",
	"Giveaway_RandomDraw": "Sorteio em progresso",
	"Giveaway_Congratulation": "Número de vencedores até o momento!",
	"Giveaway_Closed_NoWinnerInfo": "O sorteio terminou. Agradecemos pela sua participação.",
	"Giveaway_Closed": "O sorteio terminou com %1$s vencedores. Agradecemos pela sua participação.",
	"Giveaway_LearnMore": "Clique para saber mais sobre os prêmios, os vencedores e as regras",
	"Lunar2020_CheckBackEachDay": "Volte a cada dia para obter um novo presente do Imperador!",
	"Lunar2020_CheckBackEachDayForStory": "Volte diariamente para um novo capítulo",
	"Lunar2020_FirstGift": "1º presente",
	"Lunar2020_SecondGift": "2º presente",
	"Lunar2020_ThirdGift": "3º presente",
	"Lunar2020_FourthGift": "4º presente",
	"Lunar2020_GiftWasOpened": "aberto",
	"Lunar2020_RereadStory": "mostrar história",
	"Lunar2020_GiftCanBeOpenedNow": "abrir agora",
	"Lunar2020_GiftCanBeOpenedAfterThePreviousOne": "abrir seguinte",
	"Lunar2020_GiftLockedUntilDate": "abrir em %1$s",
	"Lunar2020_ErrorLoadingVideo": "Utilize um navegador compatível com vídeos HTML para abrir o seu envelope.",
	"Lunar2020_LinkBackToSale": "Retornar à promoção",
	"Lunar2020_LinkFromVideoToMarket": "Visitar o mercado agora",
	"Lunar2020_ReceivedNumberOfTokens": "Você recebeu %1$s fichas",
	"Lunar2020_YourBalancePrefix": "Seu saldo",
	"Lunar2020_BalanceNumberOfTokens": "%1$s fichas",
	"Lunar2020_LimitedUserDialogTitle": "Não foi possível abrir o envelope",
	"Lunar2020_StoryTitle": "A GRANDE CORRIDA DO IMPERADOR",
	"Lunar2020_StorySubTitle": "A Origem do Horóscopo Chinês",
	"Lunar2020_StoryDayOneHeader": "A GRANDE CORRIDA | 1º DIA",
	"Lunar2020_StoryDayTwoHeader": "A GRANDE CORRIDA | 2º DIA",
	"Lunar2020_StoryDayThreeHeader": "A GRANDE CORRIDA | 3º DIA",
	"Lunar2020_StoryDayFourHeader": "A GRANDE CORRIDA | 4º DIA",
	"Lunar2020_StoryDayOne": "A Rata astuta foi a primeira a chegar ao campo celestial. Já que ela não gosta de nadar, pegou uma carona confiável no lombo do Boi e saltou entusiasmadamente para o jardim paradisíaco do Imperador antes que a sua carona chegasse à margem.\n\nO Boi constante atravessou o rio com facilidade, sem se preocupar com os resultados da corrida. O segundo lugar é bom para ele, que ficou feliz com o sucesso da Rata.",
	"Lunar2020_StoryDayTwo": "O Tigre autossuficiente foi cauteloso demais para ultrapassar o Boi e achou melhor ficar em terceiro lugar do que em lugar nenhum.\n\nO Coelho veloz acabou saltando sobre um pedaço de madeira, flutuando rapidamente sem destino. Mas valeu-se da sorte na falta da estratégia quando um vento prestativo acelerou a sua jornada na direção certa. \n\nO ponto de vista privilegiado do Dragão voador revelou alguns necessitados de ajuda, e ele parou sempre que possível, inclusive para presentear um sopro de vento para o Coelho atravessar o rio. A honra importa muito mais do que a vitória, e o quinto lugar satisfez para o Dragão.",
	"Lunar2020_StoryDayThree": "A Cobra sorrateira não estava lá muito interessada no esforço à longa distância, então enroscou-se despercebida no casco do Cavalo. \n\nEnquanto o Cavalo galopava em direção à linha de chegada, a Cobra desenroscou-se e espantou a sua carona por tempo suficiente para esgueirar-se até o sexto lugar, enquanto o Cavalo errante seguiu trotando na sua cola.",
	"Lunar2020_StoryDayFour": "A Cabra, o Macaco e o Galo trabalharam em equipe, mas deixaram a Cabra ficar com o oitavo lugar, já que ela havia feito o maior esforço durante a viagem. O Macaco animado chegou em nono, e o Galo pomposo desfilou em décimo, orgulhoso de tão justa que fora a ordem.\n\nO Cachorro galhofeiro estava mais interessado em brincar na água e concluiu que o décimo-primeiro lugar seria uma boa troca por toda aquela diversão.\n\nEm décimo-segundo, chegou o Porco, que parara para comer e cochilar, pois sabiamente já estava ciente de que todos os animais teriam a sua vez ao lado do Imperador.",
	"SteamChina_PendingPersonaName": "As alterações ao perfil serão aplicadas após análise",
	"Legal_Footer_WithYear": "© %1$s Valve Corporation. Todos os direitos reservados. Todas as marcas registradas são propriedade dos seus respectivos donos nos EUA e em outros países.",
	"shared_dummy": "dont translate"
}
