{
	"language": "polish",
	"Button_Append": "Dołącz",
	"Button_Cancel": "Anuluj",
	"Button_Close": "Zamknij",
	"Button_Clone": "Sklonuj",
	"Button_Confirm": "Potwierdź",
	"Button_Copy": "Kopiuj",
	"Button_CopyClipboard": "Kopiuj do schowka",
	"Button_CopyLink": "Kopiuj link",
	"Button_Create": "Stwórz",
	"Button_Delete": "Usuń",
	"Button_Discuss": "Dyskutuj",
	"Button_Dismiss": "Odrzuć",
	"Button_Edit": "Edytuj",
	"Button_Publish": "Opublikuj",
	"Button_Post": "Opublikuj",
	"Button_OK": "OK",
	"Button_Overwrite": "Nadpisz",
	"Button_Retry": "Ponów",
	"Button_Remove": "Usuń",
	"Button_Save": "Zapisz",
	"Button_Saved": "Zapisano",
	"Button_Share": "Udostępnij",
	"Button_Update": "Zaktualizuj",
	"Button_SaveAndContinue": "Zapisz i kontynuuj",
	"Button_Follow": "Obserwuj",
	"Button_Followed": "Obserwowany",
	"Button_Ignore": "Ignoruj",
	"Button_Ignored": "Ignorowany",
	"Button_NotifyMe": "Powiadom mnie",
	"Button_NotInterested": "Nie interesuje mnie to",
	"Button_RateUp": "Polub to",
	"ToolTip_CopyLinkToClipboard": "Kopiuj link do schowka",
	"Input_Error_NumberTooSmall": "Zbyt mała liczba.",
	"Input_Error_NumberTooLarge": "Zbyt duża liczba.",
	"Input_Error_MustBeURL": "Pole nie jest prawidłowym adresem URL.",
	"Input_Error_MustBeEmail": "Pole nie jest prawidłowym adresem e-mail.",
	"Input_Error_MustBeNumber": "Pole musi być liczbą.",
	"Loading": "Wczytywanie...",
	"Updating": "Aktualizowanie...",
	"Settings": "Ustawienia",
	"FriendSettings_AlwaysNewChatWindow": "Zawsze otwieraj nowe okno czatu zamiast zakładki",
	"g_DisabledOnWeb": "Niedostępne w wersji przeglądarkowej",
	"VoiceTransmissionType_Disabled": "Otwarty mikrofon tylko dla wersji sieciowej",
	"VoiceVolume": "Głośność",
	"VoiceSetupHeader": "Przygotowanie i testowanie głosu",
	"VoiceStartLocalMicTest": "Rozpocznij test mikrofonu",
	"VoiceStopLocalMicTest": "Zakończ test mikrofonu",
	"VoiceWhenMicIsWorking": "Jeśli słyszysz siebie, a kolorowy pasek obok awatara porusza się podczas mówienia, oznacza to, że twój mikrofon działa.",
	"VoiceDevice": "Urządzenie wejścia",
	"VoiceOutputDevice": "Urządzenie wyjścia",
	"VoiceInputGain": "Głośność/wzmocnienie urządzenia wejścia",
	"VoiceInputGainExplainer": "(mój mikrofon)",
	"VoiceOutputGain": "Głośność/wzmocnienie urządzenia wyjścia",
	"VoiceOutputGainExplainer": "(moi znajomi)",
	"VoiceTransmissionType": "Wciśnij, by mówić",
	"VoiceTransmissionType_Label": "Rodzaj transmisji głosu",
	"VoiceTransmissionType_OpenMic": "Otwarty mikrofon",
	"VoiceTransmissionType_PushToTalk": "Wciśnij, by mówić",
	"VoiceTransmissionType_PushToMute": "Wciśnij, by wyciszyć",
	"VoiceClearHotKeyTooltip": "Wyczyść przypisanie klawisza przełączania wyciszenia",
	"VoiceTransmissionTypeExplainer": "Wymaga wciśnięcia określonego klawisza, by mówić na kanałach głosowych",
	"VoiceTransmissionType_WhenSpeaking": "Automatyczne",
	"VoiceTransmissionType_PushToTalk_Key": "Wciśnij, by mówić: %1$s",
	"VoicePushToTalkPressHotKey": "Wciśnij klawisz lub naciśnij przycisk myszy, by przypisać",
	"VoicePushToTalkAssigned": "Klawisz, który należy wcisnąć, by mówić",
	"VoicePushToMuteAssigned": "Klawisz, który należy wcisnąć, by wyciszyć",
	"VoiceMuteToggleAssigned": "Klawisz, który należy wcisnąć, by przełączyć wyciszenie",
	"VoicePushToSomethingSoundOption": "Odtwórz krótki dźwięk podczas włączania lub wyłączania mikrofonu",
	"VoiceTransmisionThreshold": "Próg transmisji głosu",
	"VoiceTransmissionThresholdExplainer": "Gdy twój mikrofon jest włączony, nie będziemy przesyłać szumu poniżej tego progu:",
	"VoiceTransmissionThresholdOff": "Wyłączone",
	"VoiceTransmissionThresholdMedium": "Średni",
	"VoiceTransmissionThresholdHigh": "Wysoki",
	"VoiceTransmissionThresholdRecommended": "(zalecany)",
	"VoiceAdvancedSettings": "Ustawienia zaawansowane",
	"VoiceShowAdvancedSettings": "Pokaż ustawienia zaawansowane",
	"VoiceHideAdvancedSettings": "Ukryj ustawienia zaawansowane",
	"VoiceAdvancedSettingsExplainer": "(są to ustawienia mikrofonu obsługiwane przez twoją platformę lub przeglądarkę)",
	"VoiceEchoCancellation": "Tłumienie echa",
	"VoiceNoiseCancellation": "Tłumienie szumu",
	"VoiceAutoGainControl": "Automatyczna regulacja głośności/wzmocnienia",
	"DefaultMic": "Domyślne",
	"MicLoading...": "Wczytywanie...",
	"DefaultOutputDevice": "Domyślne",
	"OutputDeviceLoading...": "Wczytywanie...",
	"BreadCrumbs_AllEvents": "Wszystkie wydarzenia",
	"BreadCrumbs_GameEvents": "Wydarzenia w %1$s",
	"CreatorHome_ThisGame": "O tej grze:",
	"CreatorHome_DevelopedBy": "Producent:",
	"CreatorHome_PublishedBy": "Wydawca:",
	"CreatorHome_InFranchise": "W serii:",
	"CreatorHome_Followers": "%1$s<br>obserwujących",
	"CreatorHome_JustFollowers": "obserwujących",
	"CreatorHome_Follow_tooltip": "Obserwuj tego twórcę, by otrzymać powiadomienie e-mailem i w Sklepie Steam, gdy wyda on nową grę. Powiadomienia e-mail można wyłączyć w dowolnym momencie.",
	"EventBrowse_MoreEventsTitle": "Więcej wydarzeń od %1$s",
	"EventBrowse_MoreEventsBtn": "Zobacz wszystkie",
	"EventCalendar_Title": "wydarzenia",
	"EventCalendar_SubTitle": "Nadchodzące wydarzenia i aktywność ze strony producentów gier",
	"EventCalendar_LiveNow": "na żywo",
	"EventCalendar_Upcoming": "nadchodzące",
	"EventCalendar_LaterToday": "jeszcze dziś",
	"EventCalendar_ThisWeek": "w tym tygodniu",
	"EventCalendar_ThisMonth": "w tym miesiącu",
	"EventCalendar_MuchLater": "znacznie później",
	"EventCalender_Type_Global": "globalne",
	"EventCalender_Type_Recommended": "polecane",
	"EventCalender_Show": "pokaż",
	"EventCalender_Show_All": "wszystkie",
	"EventDisplay_Admin_Title": "Narzędzia administratora:",
	"EventDisplay_CallToAction_LearnMore": "Więcej informacji",
	"EventDisplay_CallToAction_InLibrary": "W bibliotece",
	"EventDisplay_CallToAction_PlayNow": "Graj teraz",
	"EventDisplay_Events": "Panel główny administratora",
	"EventDisplay_SeeOldVersion": "Zobacz obecną wersję dla klientów",
	"EventDisplay_RightColumnTitle_Game": "Gra",
	"EventDisplay_RightColumnTitle_DateAndTime": "Czas i data",
	"EventDisplay_RightColumnTitle_EventType": "Typ",
	"EventDisplay_PostedBy": "Autor: ",
	"EventDisplay_Reminder_SetReminder": "Ustaw przypomnienie",
	"EventDisplay_Reminder_FollowEvent": "Obserwuj wydarzenie",
	"EventDisplay_Reminder_FollowEvent_ttip": "Obserwuj wydarzenie, by otrzymać powiadomienie o jego rozpoczęciu.",
	"EventDisplay_Reminder_RemindAtStart": "Gdy wydarzenie się rozpoczyna",
	"EventDisplay_Reminder_RemindAtStart_ttip": "W momencie rozpoczęcia wydarzenia Steam wyśle ci powiadomienie.",
	"EventDisplay_Reminder_IgnoreEvent": "Zignoruj to wydarzenie",
	"EventDisplay_Reminder_IgnoreStop": "Zatrzymaj przypomnienia",
	"EventDisplay_Reminder_IgnoreEvent_ttip": "Jeśli zignorujesz wydarzenie, to Steam wykluczy je z przyszłych sugestii i rekomendacji.",
	"EventDisplay_Reminder_FollowEvent_Error": "Błąd podczas obserwowania wydarzenia",
	"EventDisplay_Reminder_FollowEvent_ErrorDesc": "Wystąpił następujący błąd podczas zmiany stanu obserwowania wydarzenia:",
	"EventDisplay_Reminder_IgnoreEvent_Error": "Błąd podczas zignorowania wydarzenia",
	"EventDisplay_Reminder_IgnoreEvent_ErrorDesc": "Wystąpił następujący błąd podczas zmiany stanu zignorowania wydarzenia:",
	"EventDisplay_Reminder_Toast": "Wyskakujące powiadomienie Steam w systemie Windows",
	"EventDisplay_Reminder_AddToCalendar": "Dodaj do kalendarza",
	"EventDisplay_Reminder_AddToApple": "Dodaj do Kalendarza Apple",
	"EventDisplay_Reminder_AddToGoogle": "Dodaj do Kalendarza Google",
	"EventDisplay_Reminder_AddToOutlook": "Dodaj do Kalendarza Outlook",
	"EventDisplay_Reminder_AddToYahoo": "Dodaj do Kalendarza Yahoo",
	"EventDisplay_Reminder_Preferences": "Edytuj preferencje przypomnień...",
	"EventDisplay_TimeDisplay": "Od %1$s do %2$s",
	"EventDisplay_TimeDisplayNone": "Brak informacji o czasie i dacie",
	"EventDisplay_TimeBeginsOn": "Nadchodzące wydarzenie rozpocznie się",
	"EventDisplay_TimeBeginsOn_Past": "Rozpoczęło się",
	"EventDisplay_TimeBeginsOn_StartAndEnd_Past": "Wydarzenie z przeszłości rozpoczęło się",
	"EventDisplay_TimeEndsOn": "Kończy się",
	"EventDisplay_TimeEndsOn_Past": "Zakończyło się",
	"EventDisplay_TimeEndsOn_Ran": "Ran",
	"EventDisplay_TimeRange": "Czas trwania wydarzenia",
	"EventDisplay_TimeInPast": "Zamieszczono",
	"EventDisplay_TimeUpcoming": "Wydarzenie rozpoczyna się",
	"EventDisplay_TimeEventActive": "Wydarzenie właśnie trwa",
	"EventDisplay_TimeEventOnNow": "Trwa teraz!",
	"EventDisplay_Share_Link": "Link: ",
	"EventDisplay_Share_OnMyStatus": "Udostępnij bezpośrednio do mojego statusu",
	"EventDisplay_Share_OnMyStatus_Details": "Opublikuj ten status na twojej stronie aktywności znajomych. Steam dołączy tę wiadomość do podglądu przedmiotu, który jest widoczny poniżej.",
	"EventDisplay_Share_OnMyStatus_Placeholder": "Powiedz coś na ten temat swoim znajomym...",
	"EventDisplay_Share_OnSteam": "Udostępnij w Społeczności Steam jako aktualizacja statusu",
	"EventDisplay_Share_OnFaceBook": "Udostępnij na Facebooku",
	"EventDisplay_Share_OnTwitter": "Udostępnij na Twitterze",
	"EventDisplay_Share_OnReddit": "Udostępnij na Reddicie",
	"EventDisplay_Share_Success": "Sukces!",
	"EventDisplay_Share_Failure": "Wystąpił następujący błąd: ",
	"EventDisplay_Share_Announcement": "Ogłoszenie z %1$s",
	"EventDisplay_Share_Event": "Wydarzenie w %1$s",
	"EventDisplay_Share_NotLoggedIn": "Nie zalogowano",
	"EventDisplay_Share_NotLoggedIn_Description": "Aby użyć tej funkcji, musisz się zalogować na Steam.",
	"EventDisplay_Share_CommentMigrationInProcess": "Dyskusje tego wydarzenia znajdują się w kolejce migracji do systemu wydarzeń i są tymczasowo niedostępne. Wróć później.",
	"EventDisplay_AreYouSure": "Czy na pewno chcesz usunąć to wydarzenie (%1$s)? Tego działania nie można cofnąć.",
	"EventDisplay_AreYouSure_Visible": "Czy na pewno chcesz usunąć to wydarzenie (%1$s)? Tego działania nie można cofnąć. W ciągu kilku minut to wydarzenie zostanie usunięte ze wszystkich miejsc, w których użytkownik może je znaleźć.",
	"EventDisplay_DeleteEvent_InProgress": "Usuwanie w toku. Proszę czekać.",
	"EventDisplay_DeleteEvent_Error": "Wystąpił błąd podczas przetwarzania tego żądania usunięcia:",
	"EventDisplay_DeleteEvent_ForumTopicError": "Wydarzenie zostało pomyślnie usunięte. Nie udało nam się usunąć wątku na forum dla tego wydarzenia. Możesz zawsze ponowić próbę na stronie %1$s. Szczegóły błędu:",
	"EventDisplay_DeleteEvent_Success": "Wydarzenie zostało pomyślnie usunięte.",
	"EventDisplay_DeleteEvent_Comment": "Czy usunąć również wątek na forum dyskusyjnym dla tego wydarzenia?",
	"EventDisplay_SocialTitle": "Więcej o tej grze",
	"EventEditor_Publish_VisibleNow": "Upublicznij teraz",
	"EventEditor_Publish_VisibleNow_ttip": "To wydarzenie zostanie automatycznie upublicznione o wyznaczonym czasie. Ten przycisk wymusi natychmiastowe ujawnienie tego wydarzenia.",
	"EventEditor_Edit": "Edytuj wydarzenie",
	"EventDisplay_DeleteEvent": "Usuń wydarzenie",
	"EventReminder_InProgress": "(pamiętaj, że pokazane tutaj opcje powiadomień są reprezentacyjne i nie są jeszcze funkcjonalne)",
	"EventReminder_NotifyByEmail": "Powiadom mnie e-mailem",
	"EventReminder_NotifyByEmail_ttip": "W momencie rozpoczęcia wydarzenia Steam wyśle ci powiadomienie e-mail na twoje konto.",
	"EventReminder_NotifyByMobile": "Powiadom mnie na moim urządzeniu mobilnym",
	"EventReminder_NotifyByMobile_ttip": "W momencie rozpoczęcia wydarzenia Steam wyśle ci powiadomienie push na wszystkie urządzenia mobilne, na których znajduje się aplikacja mobilna Steam i na których jesteś zalogowany(-a).",
	"EventReminder_NotifyByEmail_Missing": "Brak zweryfikowanego adresu e-mail.",
	"EventReminder_NotifyByEmail_Missing_Add": "Dodaj adres tutaj.",
	"EventReminder_NotifyByMobile_Missing": "Brak zainstalowanej aplikacji mobilnej.",
	"EventReminder_NotifyByMobile_Install": "Zobacz dostępne aplikacje tutaj.",
	"EventEmail_Subject_NewUpdate": "%1$s, nowa aktualizacja",
	"EventEmail_Subject_UpcomingLaunch": "%1$s, nadchodząca premiera",
	"EventEmail_Subject_NowAvailable": "%1$s już dostępne",
	"EventEmail_Subject_FreeDemoAvailable": "Darmowe demo %1$s już dostępne",
	"EventEmail_Button_ClickForMoreDetails": "Kliknij, by uzyskać więcej informacji",
	"EventEmail_Button_PrepurchaseNow": "Zakup w przedsprzedaży już teraz!",
	"EventEmail_Button_BuyNow": "Kup teraz!",
	"EventEmail_Button_PlayNow": "Zagraj teraz!",
	"EventEmail_Button_WishlistNow": "Dodaj do listy życzeń już teraz!",
	"EventEmail_Destination_Store": "Strona w Sklepie Steam",
	"EventEmail_Destination_Event": "Strona szczegółów wydarzenia",
	"AddToWishlist": "Dodaj do swojej listy życzeń",
	"Wishlisted": "Na twojej liście życzeń",
	"AddToWishlist_ttip": "Otrzymaj powiadomienie e-mailem, gdy produkty na twojej liście życzeń zostaną wydane lub otrzymają zniżkę.",
	"Wishlist_Error": "Błąd aktualizacji listy życzeń",
	"Wishlist_Error_Desc": "Wystąpił błąd podczas dodawania produktu do twojej listy życzeń. Spróbuj ponownie później:",
	"WindowTitle_FriendsList": "Lista znajomych",
	"FriendsList_OfflineTitle": "BŁĄD",
	"FriendsList_OfflineOrFailure": "Lista znajomych nieosiągalna",
	"FriendsList_OfflineDetail": "Ten błąd może wskazywać na to, że twoja sieć lokalna lub serwery funkcji znajomych są wyłączone.",
	"FriendsList_SignedOut": "Wylogowano ze znajomych i czatu",
	"FriendsList_SignedOut_Detail": "Jesteś obecnie offline.  Zaloguj się, by uzyskać dostęp do listy znajomych i czatu.",
	"FriendsList_OfflineMode": "Wylogowano ze znajomych i czatu",
	"FriendsList_OfflineMode_Detail": "Znajomi oraz czat nie są dostępni w trybie offline. Przejdź do trybu online, by uzyskać dostęp do tych funkcji.",
	"Friends_RetryLoading": "Ponów próbę połączenia",
	"Friends_SignIn": "Zaloguj się",
	"FriendsList_Offline_Disconnected": "Rozłączono",
	"FriendsList_LoadingTitle": "WCZYTYWANIE",
	"FriendsList_StillLoadingSummary": "Wczytywanie listy znajomych...",
	"FriendsList_StillLoadingDetail": "Steam próbuje połączyć się z siecią znajomych. Może to potrwać kilka sekund dłużej.",
	"Dialog_On": "WŁ.",
	"Dialog_Off": "WYŁ.",
	"TimeInterval_XYears": "%1$s lat(a)",
	"TimeInterval_1YearXMonths": "1 rok i %1$s mies.",
	"TimeInterval_1Year": "1 rok",
	"TimeInterval_XMonths": "%1$s mies.",
	"TimeInterval_1Month": "1 miesiąc",
	"TimeInterval_1MonthX": "1 miesiąc i %1$s dni",
	"TimeInterval_XWeeks": "%1$s tyg. ",
	"TimeInterval_1Week": "1 tydzień",
	"TimeInterval_XDays": "%1$s dni",
	"TimeInterval_1Day": "1 dzień",
	"TimeInterval_1DayXHours": "1 dzień i %1$s godz.",
	"TimeInterval_XHours": "%1$s godz.",
	"TimeInterval_1Hour": "1 godz.",
	"TimeInterval_1HourXMinutes": "1 godz. i %1$s min",
	"TimeInterval_LessThanAnHour": "mniej niż godzina",
	"TimeInterval_XMinutes": "%1$s min",
	"TimeInterval_1Minute": "1 min",
	"TimeInterval_LessThanAMinute": "mniej niż minuta",
	"TimeSince_XYears": "%1$s lat(a) temu",
	"TimeSince_1YearXMonths": "rok i %1$s mies. temu",
	"TimeSince_1Year": "rok temu",
	"TimeSince_XMonths": "%1$s mies. temu",
	"TimeSince_1Month": "miesiąc temu",
	"TimeSince_1MonthXDays": "miesiąc i %1$s dni temu",
	"TimeSince_XWeeks": "%1$s tyg. temu",
	"TimeSince_1Week": "tydzień temu",
	"TimeSince_XDays": "%1$s dni temu",
	"TimeSince_1Day": "wczoraj",
	"TimeSince_1DayXHours": "dzień i %1$s godz. temu",
	"TimeSince_XHours": "%1$s godz. temu",
	"TimeSince_1Hour": "godzinę temu",
	"TimeSince_1HourXMinutes": "godzinę i %1$s min temu",
	"TimeSince_LessThanAnHour": "mniej niż godzinę temu",
	"TimeSince_XMinutes": "%1$s min temu",
	"TimeSince_1Minute": "minutę temu",
	"TimeSince_LessThanAMinute": "mniej niż minutę temu",
	"TimeSince_ThisWeek": "W tym tygodniu",
	"Time_Today": "Dzisiaj",
	"Time_Yesterday": "Wczoraj",
	"Time_Recent": "Recent",
	"ContextMenu_Copy": "Kopiuj",
	"ContextMenu_Cut": "Wytnij",
	"ContextMenu_Paste": "Wklej",
	"ContextMenu_CopyLinkURL": "Kopiuj adres linku",
	"ContextMenu_OpenLinkInNewWindow": "Otwórz link w nowym oknie",
	"ContextMenu_CopyImageURL": "Kopiuj adres obrazu",
	"ContextMenu_OpenImageInNewWindow": "Otwórz obraz w nowym oknie",
	"Tooltip_Settings": "Zarządzaj ustawieniami listy znajomych",
	"Tooltip_VoiceSettings": "Zarządzaj ustawieniami głosu",
	"Tooltip_SearchFriends": "Szukaj w mojej liście znajomych",
	"Tooltip_AddFriend": "Dodaj do znajomych",
	"Tooltip_FriendRequest": "Przychodzące zaproszenia (%1$s)",
	"Tooltip_FriendRequest_Plural": "Przychodzące zaproszenia (%1$s)",
	"Tooltip_CreateGroupChat": "Utwórz czat grupowy",
	"Tooltip_InviteToGroup": "Zaproś znajomego do tego czatu grupowego",
	"Tooltip_InviteToGroup_Denied": "Nie posiadasz uprawnień do zapraszania użytkowników do tej grupy",
	"Tooltip_GroupChatSettings": "Zarządzaj ustawieniami czatu grupowego",
	"Tooltip_MemberCollapse": "Zwiń listę członków",
	"Tooltip_MemberExpand": "Rozwiń listę członków",
	"Tooltip_ChatsCollapse": "Zwiń listę czatów",
	"Tooltip_ChatsExpand": "Rozwiń listę czatów",
	"Tooltip_MinimizeList": "Zminimalizuj listę",
	"Tooltip_ExpandList": "Rozwiń listę",
	"Tooltip_PinChannelList": "Przypnij listę kanałów",
	"Tooltip_UnpinChannelList": "Odepnij listę kanałów",
	"Tooltip_TextChannel": "Czat tekstowy z członkami grupy",
	"Tooltip_TextChannelCreate": "Utwórz nowy kanał tekstowy",
	"Tooltip_NoPermissionChannelCreate": "Nie posiadasz uprawnień do tworzenia kanałów na tym czacie grupowym",
	"Tooltip_VoiceChannel": "Czat głosowy na tych kanałach głosowych",
	"Tooltip_VoiceChannelCreate": "Utwórz nowy kanał głosowy",
	"Tooltip_DismissVoice": "Odrzuć zaproszenie do kanału głosowego",
	"Tooltip_MicStatus_Active": "Mikrofon jest aktywny",
	"Tooltip_MicStatus_Muted": "Mikrofon jest wyciszony",
	"Tooltip_RemoteMicStatus_Muted": "Użytkownik wyciszył swój mikrofon",
	"Tooltip_MicStatus_NoMic": "Użytkownik nie posiada podłączonego mikrofonu",
	"Tooltip_RemoteOutputStatus_Muted": "Użytkownik wyciszył dźwięk z tego kanału",
	"Tooltip_YourMicStatus_Muted": "Twój mikrofon jest wyciszony",
	"Tooltip_YourOutputStatus_Muted": "Wyciszono dźwięk z tego kanału",
	"Tooltip_VoiceControlButton_1v1_inactive": "Wyślij zaproszenie do czatu głosowego",
	"Tooltip_VoiceControlButton_1v1_active": "Opuść kanał głosowy",
	"Tooltip_VoiceControlButton_group_create": "Utwórz kanał głosowy",
	"Tooltip_VoiceControlButton_group_leave": "Opuść kanał głosowy",
	"Tooltip_VoiceControlButton_group_joinsingle": "Dołącz do kanału głosowego",
	"Tooltip_VoiceControlButton_group_joinmultiple": "Wybierz kanał głosowy, do którego chcesz dołączyć",
	"LanguageTitle": "Język",
	"Language_english": "Angielski",
	"Language_german": "Niemiecki",
	"Language_french": "Francuski",
	"Language_italian": "Włoski",
	"Language_korean": "Koreański",
	"Language_spanish": "Hiszpański",
	"Language_schinese": "Chiński uproszczony",
	"Language_tchinese": "Chiński tradycyjny",
	"Language_russian": "Rosyjski",
	"Language_thai": "Tajski",
	"Language_japanese": "Japoński",
	"Language_portuguese": "Portugalski",
	"Language_polish": "Polski",
	"Language_danish": "Duński",
	"Language_dutch": "Holenderski",
	"Language_finnish": "Fiński",
	"Language_norwegian": "Norweski",
	"Language_swedish": "Szwedzki",
	"Language_hungarian": "Węgierski",
	"Language_czech": "Czeski",
	"Language_romanian": "Rumuński",
	"Language_turkish": "Turecki",
	"Language_arabic": "Arabski",
	"Language_brazilian": "Portugalski brazylijski",
	"Language_bulgarian": "Bułgarski",
	"Language_greek": "Grecki",
	"Language_ukrainian": "Ukraiński",
	"Language_latam": "Hiszpański latynoamerykański",
	"Language_vietnamese": "Wietnamski",
	"Language_koreana": "Koreański",
	"language_selection_english": "English (angielski)",
	"language_selection_spanish": "Español-España (hiszpański)",
	"language_selection_french": "Français (francuski)",
	"language_selection_italian": "Italiano (włoski)",
	"language_selection_german": "Deutsch (niemiecki)",
	"language_selection_greek": "Ελληνικά (grecki)",
	"language_selection_koreana": "한국어 (koreański)",
	"language_selection_korean": "한국어 (koreański)",
	"language_selection_schinese": "简体中文 (chiński uproszczony)",
	"language_selection_tchinese": "繁體中文 (chiński tradycyjny)",
	"language_selection_russian": "Русский (rosyjski)",
	"language_selection_thai": "ไทย (tajski)",
	"language_selection_japanese": "日本語 (japoński)",
	"language_selection_portuguese": "Português (portugalski)",
	"language_selection_brazilian": "Português-Brasil (portugalski brazylijski)",
	"language_selection_polish": "Polski",
	"language_selection_danish": "Dansk (duński)",
	"language_selection_dutch": "Nederlands (holenderski)",
	"language_selection_finnish": "Suomi (fiński)",
	"language_selection_norwegian": "Norsk (norweski)",
	"language_selection_swedish": "Svenska (szwedzki)",
	"language_selection_czech": "Čeština (czeski)",
	"language_selection_hungarian": "Magyar (węgierski)",
	"language_selection_romanian": "Română (rumuński)",
	"language_selection_bulgarian": "Български (bułgarski)",
	"language_selection_pirate": "Arrr! (piracki angielski)",
	"language_selection_turkish": "Türkçe (turecki)",
	"language_selection_ukrainian": "Українська (ukraiński)",
	"language_selection_vietnamese": "Tiếng Việt (wietnamski)",
	"language_selection_arabic": "العربية (arabski)",
	"language_selection_spanish_mexican": "Español-Mexicano (hiszpański meksykański)",
	"language_selection_latam": "Español-Latinoamérica (hiszpański latynoamerykański)",
	"Bbcode_Originally_Posted_By": "Oryginalnie zamieścił(a):",
	"Bbcode_No_Match": "Brak wyników dla obsługiwanego BBCode",
	"Editor_Bold": "Pogrubienie",
	"Editor_Underline": "Podkreślenie",
	"Editor_Italics": "Kursywa",
	"Editor_StrikeThrough": "Przekreślenie",
	"Editor_Link": "Wstaw link",
	"Editor_Unordered": "Lista nieuporządkowana",
	"Editor_Ordered": "Lista uporządkowana",
	"Editor_Header": "Nagłówek",
	"Editor_Emoticon": "Wstaw emotikonę",
	"EventEditor_ConvertHTML_Error": "Konwersja HTML nieudana",
	"EventEditor_ConvertHTML_Error_Desc": "Wystąpił następujący błąd podczas konwersji HTML na BBCode: „%1$s”.",
	"EventEditor_InsertLinkURL": "Wstaw adres URL",
	"EventEditor_FormattingHelp_GetHelpLink": "Pomoc z formatowaniem",
	"EventEditor_ImportHTML": "Importuj HTML",
	"EventEditor_ImportFromHTML": "Importuj z HTML",
	"EventEditor_ImportFromHTML_ttip": "Zaimportuj z HTML. Automatycznie skonwertuje to twój kod HTML na tagi formatowania Steam.",
	"EventEditor_ImportFromHTML_Instruction": "Wpisz lub wklej HTML poniżej.",
	"EventEditor_ImportFromHTML_PreserveNewlines": "Zachowaj nowe linie",
	"EventEditor_ImportFromHTML_PreserveNewlines_Hint": "W HTML nowe linie zazwyczaj nie wywierają żadnego efektu, ale w BBCode zostaną one wyświetlone jako puste. Jeśli użyty został tag <p> lub <br>, pozostaw to pole niezaznaczone. Jeśli zwykle korzystasz z oprogramowania do pisania bloga, które automatycznie dodaje tagi <br> dla nowych linii, to pole prawdopodobnie powinno zostać zaznaczone.",
	"EventEditor_ImportFromHTML_ConvertToBBCode": "Skonwertuj na BBCode:",
	"EventEditor_ImportFromHTML_ConversionInProgress": "Konwersja w toku. Nie zamykaj tego okna dialogowego.",
	"EventEditor_ImportFromHTML_ConvertFinished": "Konwersja zakończona. Możesz bezpiecznie zamknąć to okno dialogowe.",
	"EventEditor_InsertYouTube": "Wstaw wideo z YouTube™",
	"EventEditor_InsertYouTube_Left": "Wyrównaj do lewej",
	"EventEditor_InsertYouTube_Right": "Wyrównaj do prawej",
	"EventEditor_InsertYouTube_Full": "Pełna szerokość",
	"EventEditor_InsertYouTube_URL": "Pełny adres URL",
	"EventEditor_InsertYouTube_Position": "Pozycja",
	"EventEditor_InsertYouTube_Placholder": "Wprowadź adres URL YouTube™",
	"EventEditor_InsertYouTube_NoURL": "Wprowadź prawidłowy adres URL YouTube™",
	"EventEditor_InsertYouTube_Summary": "Opisowa wersja podsumowania",
	"EventEditor_InsertImage": "Wstaw obraz z sieci",
	"EventEditor_InsertImage_Title": "Wstaw obraz",
	"EventEditor_InsertImage_Desc": "Wprowadź adres URL obrazu (np. w formacie .jpg, .gif lub .png), by dołączyć ten obraz do swojego posta.",
	"EventEditor_InsertImage_URL": "Adres URL obrazu",
	"EventEditor_InsertImage_Placeholder": "Wprowadź prawidłowy adres URL",
	"EventEditor_InsertImage_Anchor": "Opcjonalne: adres URL, który zostanie otwarty po kliknięciu na obraz",
	"EventEditor_LinkDescription": "Tekst do wyświetlenia",
	"EventEditor_LinkURL": "Adres URL",
	"EventEditor_YouTubeVideoTitle": "Film YouTube™: %1$s",
	"EventEditor_YouTubeVideoViews": "Wyświetlenia: %1$s",
	"EventEditor_Author": "Autor: %1$s",
	"EventEditor_Comments": "Komentarze",
	"EventEditor_UpVotes": "Głosy za",
	"EventEditor_DownVotes": "Głosy przeciw",
	"Error_Message": "Komunikat o błędzie",
	"Warning_Message": "Komunikat z ostrzeżeniem",
	"Informational_Message": "Komunikat informacyjny",
	"Error_Description": "Wystąpił błąd (kod: %1$s) z następującymi szczegółami: (%2$s)",
	"Error_FailureNotice": "Niepowodzenie",
	"Error_GenericFailureDescription": "Przepraszamy, coś poszło nie tak.",
	"Image_ErrorTitle": "Nie udało się wczytać obrazu „%1$s”. Możliwe problemy:",
	"Image_Error_msg1": "Sprawdź, czy ścieżka obrazu jest poprawna.",
	"Image_Error_msg2": "Sprawdź, czy serwer hostujący obraz wspiera anonimowy dostęp. Konsola przeglądarki może wskazać na błąd związany z Access-Control-Allow-Origin, jeśli anonimowy dostęp nie jest wspierany.",
	"Image_Error_suggestion": "Zawsze możesz przesłać obraz na Steam, by hostować treści za darmo.",
	"Platform_Hint_Mobile": "na urządzeniu mobilnym",
	"Platform_Hint_BigPicture": "w trybie Big Picture",
	"Platform_Hint_VR": "w wirtualnej rzeczywistości",
	"Hover_SteamLevel": "Poziom Steam",
	"Hover_BadgeXP": "%1$s PD",
	"PersonaStateOffline": "Offline",
	"PersonaStateAway": "Zaraz wracam",
	"PersonaStateOnline": "Online",
	"PersonaStateBlocked": "Zablokowano",
	"PersonaStateInGame": "W grze",
	"PersonaStateBusy": "Zajęty",
	"PersonaStateSnooze": "Zaraz wracam",
	"PersonaStateInNonSteamGame": "W grze spoza Steam",
	"PersonaStateWatchingBroadcast": "Ogląda transmisję:",
	"PersonaStateLookingToTrade": "Chcę się wymienić",
	"PersonaStateLookingToPlay": "Chcę pograć",
	"PersonaStateLastSeen": "Ostatnio online %1$s",
	"PersonaStateLastSeen_JustNow": "Ostatnio online przed chwilą",
	"User_WantsToPlay": "Dołącz",
	"User_ToggleDoNotDisturb": "Nie przeszkadzać",
	"User_GameInfoHidden": "Twój status gry jest ukryty przed znajomymi z powodu twoich ustawień prywatności",
	"User_LimitedAccount": "Twoje konto nie spełnia wymagań niezbędnych do korzystania z tej funkcji. %1$s, by uzyskać więcej informacji.",
	"User_LimitedAccount_UrlInfo": "Odwiedź stronę Pomocy technicznej Steam",
	"isNickname": "Twój pseudonim dla tego znajomego",
	"Friend_Menu_NotAFriendLabel": "Nieznajomy",
	"Friend_Menu_NotAFriendRequesting": "Prosi o dodanie do znajomych",
	"DASHPlayerStats_BytesReceived": "Odebrane bajty:",
	"DASHPlayerStats_BufferingResolution": "Rozdzielczość buforowania:",
	"DASHPlayerStats_PlaybackResolution": "Rozdzielczość odtwarzania:",
	"DASHPlayerStats_HtmlResolution": "Rozdzielczość ekranu:",
	"DASHPlayerStats_DroppedFrames": "Pominięte klatki:",
	"DASHPlayerStats_VideoBuffered": "Zbuforowane wideo:",
	"DASHPlayerStats_AudioBuffered": "Zbuforowane audio:",
	"DASHPlayerStats_BandwidthRequired": "Wymagana przepustowość łącza (Mb/s):",
	"DASHPlayerStats_BandwidthVideo": "Przepustowość wideo (Mb/s):",
	"DASHPlayerStats_BandwidthNums": "Przepustowość łącza min./max./śr. (Mb/s):",
	"DASHPlayerStats_DownloadNums": "Czas pobrania min./max./śr. (w sekundach):",
	"DASHPlayerStats_ContentServer": "Host:",
	"DASHPlayerStats_ActiveDownloads": "Aktywne pobierania:",
	"DASHPlayerStats_StallEvents": "Przestoje przy pobieraniu:",
	"DASHPlayerStats_FailedDownloads": "Nieudane próby pobrania:",
	"DASHPlayerStats_VideoDownloadProgress": "Postęp pobierania wideo:",
	"DASHPlayerStats_TimeToFirstFrame": "Czas do pierwszej klatki (ms):",
	"DASHPlayerStats_DroppingFrames": "Wykryte stałe pominięcia klatek:",
	"DASHPlayerStats_CurrentFPS": "Obecna liczba kl./s:",
	"DASHPlayerStats_Tracking": "Zbieranie danych...",
	"DASHPlayerStats_PlaybackRate": "Szybkość odtwarzania:",
	"DASHPlayerStats_VideoBufferRange": "Bufor wideo %1$s:",
	"DASHPlayerStats_AudioBufferRange": "Bufor audio %1$s:",
	"DASHPlayerStats_VideoNoRangeInformation": "Brak zbuforowanych segmentów wideo",
	"DASHPlayerStats_AudioNoRangeInformation": "Brak zbuforowanych segmentów audio",
	"DASHPlayerControls_GoLive": "Włącz na żywo",
	"DASHPlayerControls_IsLive": "Na żywo",
	"DASHPlayerControls_ClickToPlay": "Kliknij, aby odtworzyć",
	"DASHPlayerControls_IsReplay": "RETRANSMISJA",
	"DASHPlayerControls_Start": "Rozpocznij",
	"DASHPlayerControls_End": "Zakończ",
	"Played_Minutes": "%1$s min",
	"Played_Hours": "%1$s godz.",
	"WriteReview_Dialog_PostReview": "Zamieść recenzję",
	"WriteReview_Dialog_Title": "Recenzja",
	"WriteReview_Dialog_Playtime": "Twój czas gry: %1$s",
	"WriteReview_Dialog_Playtime_Software": "Twój czas używania: %1$s",
	"WriteReview_Dialog_RecommendGame": "Czy polecasz tę grę innym graczom?",
	"WriteReview_Dialog_RecommendGame_Software": "Czy polecasz ten program innym graczom?",
	"WriteReview_Dialog_GetHelp_Btn": "Uzyskaj pomoc odnośnie twojego zakupu",
	"WriteReview_Dialog_Visibility": "Widoczność:",
	"WriteReview_Dialog_Public": "Publiczna",
	"WriteReview_Dialog_Friends": "Tylko dla znajomych",
	"WriteReview_Dialog_Yes": "Tak",
	"WriteReview_Dialog_No": "Nie",
	"WriteReview_Dialog_GetSupport_Btn": "Uzyskaj pomoc odnośnie twojego zakupu",
	"WriteReview_Dialog_GetSupport_Desc": "Uzyskaj poradę techniczną, oficjalną pomoc lub poproś o zwrot.",
	"WriteReview_Dialog_AddReview_Btn": "Zamieść recenzję",
	"WriteReview_Dialog_AddReview_Desc": "Podziel się swoimi przemyśleniami z innymi graczami.",
	"WriteReview_Dialog_AddReview_Header": "Czy chcesz zamieścić recenzję?",
	"WriteReview_Dialog_ReviewInstructions_Link": "zasad i wytycznych",
	"WriteReview_Dialog_ReviewInstructions": "Opisz, co podobało ci się (lub nie) w tym produkcie i czy polecasz go innym użytkownikom. Pamiętaj o zachowaniu uprzejmości i stosowaniu się do %1$s. Do przesłania twojej rekomendacji wymagany jest opis.",
	"WriteReview_Dialog_AllowComments": "Zezwól na komentarze",
	"WriteReview_Dialog_FreeDisclaimer": "Zaznacz to pole, jeżeli ten produkt został ci przekazany bezpłatnie",
	"WriteReview_Dialog_FreeDisclaimer_Tooltip": "Zaznacz to pole, jeżeli ten produkt został ci przekazany bezpłatnie. Informacja „Produkt otrzymany bezpłatnie” pojawi się w twojej recenzji. Jeżeli przekazano ci dodatkowo wynagrodzenie za recenzję tej gry, musisz podać tę informację w twojej recenzji.",
	"WriteReview_Dialog_FormattingHelp": "Pomoc z formatowaniem",
	"WriteReview_Dialog_GenericError": "Wystąpił problem podczas zamieszczania twojej recenzji. Spróbuj ponownie później.",
	"WriteReview_Dialog_NoTextError": "Opisz, co podobało ci się (lub nie) w tym produkcie.",
	"Broadcast_View_Stack_H": "Widok poziomy",
	"Broadcast_View_Stack_V": "Widok pionowy",
	"Broadcast_View_Theater": "Tryb kinowy",
	"Broadcast_View_Fullscreen": "Pełny ekran",
	"Broadcast_View_HideChat": "Ukryj czat",
	"Broadcast_View_ShowBothChats": "Pokaż obydwa czaty",
	"Broadcast_View_ShowSingleChats": "Pokaż pojedynczy czat",
	"Broadcast_View_ShowChat": "Pokaż czat",
	"Broadcast_Store_FreeToPlay": "Free to Play",
	"PartnerEvent_1": "Inne wydarzenie",
	"PartnerEvent_4": "Wydarzenie ze spotkaniem",
	"PartnerEvent_9": "Czat",
	"PartnerEvent_10": "Wydanie gry",
	"PartnerEvent_11": "Transmisja na żywo lub nagranie",
	"PartnerEvent_12": "Mała aktualizacja/łatka",
	"PartnerEvent_13": "Aktualizacja",
	"PartnerEvent_14": "Ważna aktualizacja",
	"PartnerEvent_15": "Wydanie DLC",
	"PartnerEvent_16": "Przyszłe wydanie",
	"PartnerEvent_17": "Transmisja turnieju e-sportowego",
	"PartnerEvent_18": "Transmisja producenta",
	"PartnerEvent_19": "Transmisja z osobistością",
	"PartnerEvent_20": "Wyprzedaż gry",
	"PartnerEvent_21": "Zniżka na przedmioty w grze",
	"PartnerEvent_22": "Premia PD",
	"PartnerEvent_23": "Wydarzenie z łupami",
	"PartnerEvent_24": "Wydarzenie z atutami",
	"PartnerEvent_25": "Wydarzenie z wyzwaniem",
	"PartnerEvent_26": "Wydarzenie z konkursem",
	"PartnerEvent_27": "Wydarzenie w prawdziwym życiu",
	"PartnerEvent_28": "Aktualności",
	"PartnerEvent_29": "Wydanie wersji beta",
	"PartnerEvent_30": "Wydanie zawartości w grze",
	"PartnerEvent_31": "Darmowy okres próbny",
	"PartnerEvent_32": "Rozpoczęcie nowego sezonu",
	"PartnerEvent_33": "Aktualizacja sezonu",
	"PartnerEvent_34": "Promocja krzyżowa",
	"PartnerEvent_Other": "Inne wydarzenie",
	"SocialMedia_Type_ShortName_1": "Steam",
	"SocialMedia_Type_ShortName_2": "Google",
	"SocialMedia_Type_ShortName_3": "Facebook",
	"SocialMedia_Type_ShortName_4": "Twitter",
	"SocialMedia_Type_ShortName_5": "Twitch",
	"SocialMedia_Type_ShortName_6": "YouTube",
	"SocialMedia_Type_ShortName_7": "Facebook",
	"MobileLogin_NoSteamAccount": "Nie posiadasz konta Steam?",
	"MobileLogin_CreateAccount": "Stwórz darmowe konto",
	"MobileLogin_ForgotPassword": "Nie pamiętasz nazwy konta lub hasła?",
	"MobileLogin_RefreshCaptcha": "Odśwież",
	"MobileLogin_SignIn": "Zaloguj się",
	"MobileLogin_SigningIn": "Logowanie",
	"MobileLogin_AccountName": "Nazwa konta Steam",
	"MobileLogin_Password": "Hasło",
	"MobileLogin_CaptchaVerification": "Weryfikacja",
	"MobileLogin_Enter2FA": "Wprowadź kod wygenerowany w sekcji Steam Guard w twojej aplikacji mobilnej Steam.",
	"MobileLogin_Enter2FAHelp": "Nie mam dostępu do mojego kodu Steam Guard",
	"MobileLogin_EnterSteamguard": "E-mail z kodem Steam Guard nie dotarł do mnie",
	"MobileLogin_SteamguardCode": "Kod Steam Guard",
	"MobileLogin_SteamguardSubmit": "Wyślij i zaloguj się",
	"MobileLogin_SentSteamguard_1": "Wysłaliśmy e-maila na twój adres:",
	"MobileLogin_SentSteamguard_2": ". Wprowadź otrzymany kod Steam Guard.",
	"MobileLogin_IncorrectSteamGuard": "Wprowadzony kod Steam Guard jest niepoprawny. Sprawdź go ponownie i spróbuj jeszcze raz.",
	"MobileLogin_Error_RateLimitExceeded": "Wykryto zbyt wiele nieudanych prób logowania z twojej sieci w krótkim czasie. Poczekaj i spróbuj ponownie później.",
	"Login_SignIn": "Zaloguj się",
	"Login_SigningIn": "Logowanie",
	"Login_AccountName": "Nazwa konta Steam",
	"Login_Password": "Hasło",
	"Login_RememberMe": "Zapamiętaj mnie na tym komputerze",
	"Login_ForgotPassword": "Nie pamiętasz nazwy konta lub hasła?",
	"Login_NoSteamAccount": "Nie posiadasz konta Steam?",
	"Login_CreateAccount": "Stwórz darmowe konto",
	"Login_CaptchaVerification": "Wpisz ponownie znaki w captcha i potwierdź, że nie jesteś robotem.",
	"Login_RefreshCaptcha": "Odśwież",
	"Login_Enter2FA": "Wprowadź kod wygenerowany w sekcji Steam Guard w twojej aplikacji mobilnej Steam.",
	"Login_Enter2FAHelp": "Nie mam dostępu do mojego kodu Steam Guard",
	"Login_EnterSteamguard": "E-mail z kodem Steam Guard nie dotarł do mnie",
	"Login_SteamguardSubmit": "Wyślij i zaloguj się",
	"Login_SentSteamguard": "Wysłaliśmy e-maila na twój adres: %1$s. Wprowadź załączony kod Steam Guard.",
	"Login_SignOut": "Wyloguj się",
	"Emoticon_Search": "Szukaj emotikon",
	"Chat_Settings_Error_ChatFileTooLarge": "Plik %1$s jest za duży (maksymalnie 10 MB).",
	"Chat_Settings_Error_ChatFileTypeNotSupported": "Nie można przesłać pliku %1$s. Obsługiwane są tylko formaty plików jpg, png, gif, webm, mpg i ogv.",
	"ConnectionTrouble_FailedToConnect": "Nie udało się połączyć ze Steam",
	"Chat_Upload_ErrorCloud": "Nie udało się przesłać danych obrazu do serwera w chmurze.",
	"Chat_Settings_Error_ServerError": "Wystąpił błąd serwera",
	"Broadcast_ViewerCount": "%1$s oglądających",
	"Broadcast_VideoContext_ToggleStats": "Przełącz statystyki techniczne",
	"Broadcast_VideoContext_OpenStore": "Odwiedź sklep",
	"Broadcast_None": "Brak",
	"BroadcastChat_Reconnected": "Dołączono ponownie do czatu",
	"BroadcastChat_UnableToJoinChat": "Nie można dołączyć do czatu",
	"BroadcastChat_NeverTell": "Nigdy nie zdradzaj nikomu swojego hasła",
	"BroadcastChat_EnterResponse": "Napisz, aby czatować",
	"BroadcastChat_InsertEmoticon": "Wstaw emotikonę",
	"BroadcastChat_Send": "Wyślij",
	"BroadcastChat_UserJoined": "%1$s dołącza do czatu",
	"BroadcastChat_UserLeft": "%1$s opuszcza czat",
	"BroadcastChat_UserMuted": "Użytkownik %1$s zostaje wyciszony w tym pokoju czatowym",
	"BroadcastChat_UserMutedLocal": "Użytkownik %1$s zostaje wyciszony",
	"BroadcastChat_UserUnmutedLocal": "Użytkownikowi %1$s zostało wyłączone wyciszenie",
	"BroadcastChat_UserMuteFailed": "Nie udało się wyciszyć użytkownika %1$s. Spróbuj ponownie.",
	"BroadcastChat_RemoveMessagesFailed": "Nie udało się usunąć wiadomości użytkownika %1$s. Spróbuj ponownie.",
	"BroadcastChat_UserUnmuteFailed": "Nie udało się wyłączyć wyciszenia użytkownika %1$s. Spróbuj ponownie.",
	"BroadcastChat_YouMuted": "Wyciszono cię i dlatego nie możesz zamieszczać wiadomości na tym czacie",
	"BroadcastChat_FailedToSendMsg": "Nie udało się wysłać wiadomości na czacie: %1$s",
	"BroadcastChat_Cooldown": "Wysyłasz wiadomości zbyt szybko. Spróbuj ponownie za %1$s s.",
	"BroadcastChat_Mute": "Wycisz",
	"BroadcastChat_Unmute": "Wył. wyciszenie",
	"BroadcastChat_MuteLocal": "Wycisz lokalnie",
	"BroadcastChat_UnmuteLocal": "Wyłącz wyciszenie lokalnie",
	"BroadcastChat_Login": "Zaloguj się, aby dołączyć do czatu",
	"BroadcastChat_LimitedUser": "Ograniczony dostęp do czatu",
	"BroadcastChat_RemoveMessages": "Usuń wiadomości tego użytkownika",
	"BroadcastChat_Blocked": "Tylko osoby posiadające daną grę mogą wysyłać wiadomości na czacie podczas tej transmisji.",
	"BroadcastChat_half_Mute": "Wycisz użytkownika na 12 godzin",
	"BroadcastChat_day_Mute": "Wycisz użytkownika na 24 godziny",
	"BroadcastChat_week_Mute": "Wycisz użytkownika na tydzień",
	"BroadcastChat_perm_Mute": "Wycisz użytkownika na stałe",
	"BroadcastChat_half_Shadow": "Wycisz skrycie użytkownika na 12 godzin",
	"BroadcastChat_day_Shadow": "Wycisz skrycie użytkownika na 24 godziny",
	"BroadcastChat_week_Shadow": "Wycisz skrycie użytkownika na tydzień",
	"BroadcastChat_perm_Shadow": "Wycisz skrycie użytkownika na stałe",
	"BroadcastChat_Add_Moderator": "Nadaj temu użytkownikowi rolę moderatora",
	"BroadcastChat_Remove_Moderator": "Odbierz użytkownikowi rolę moderatora",
	"BroadcastChat_Change_Moderator_Title": "Zmień status moderatora użytkownikowi",
	"BroadcastChat_Change_Add_Confirm": "Czy na pewno chcesz przyznać użytkownikowi rolę moderatora? Pozwoli mu to na wyciszanie użytkowników czatu transmisji.",
	"BroadcastChat_Change_Remove_Confirm": "Czy na pewno chcesz odebrać następującemu użytkownikowi rolę moderatora?",
	"BroadcastChat_Tooltip_Show_Chat_Viewers": "Pokaż listę osób, które obecnie znajdują się w oknie czatu.",
	"BroadcastChat_Tooltip_Minimize_Chat": "Zminimalizuj okno czatu",
	"BroadcastChat_Tooltip_Maximize_Chat": "Zmaksymalizuj okno czatu",
	"BroadcastChat_Tooltip_Popout_Chat": "Otwórz czat w nowym oknie",
	"BroadcastChat_ChatOnly_Title": "Tylko czat transmisji",
	"BroadcastChat_DefaultMessage": "Witaj na czacie!",
	"BroadcastChat_Moderator": "Moderator",
	"BroadcastChat_Broadcaster": "Transmitujący",
	"ChatEntryButton_Submit": "Wyślij",
	"ChatEntryButton_Emoticon": "Wybór emotikony",
	"ChatEntryButton_Flair": "Wybór ikony",
	"ChatEntryButton_SendEmbed": "Wysyłanie specjalne",
	"home_page_live_broadcast": "Na żywo",
	"StoreBroadcast_Hide_Tooltip": "Pokaż/ukryj transmisję na żywo",
	"StoreBroadcast_Detault_popout_Title": "Teraz transmitowane",
	"StoreBroadcast_close_broadcast_popup": "Zamyka okno transmisji. Zapobiega jego ponownemu otwarciu podczas tej sesji.",
	"StoreBroadcast_Change_store_Broadcast_settings": "Zmień ustawienia transmisji",
	"Broadcast_Embedded_viewer": "%1$s widz",
	"Broadcast_Embedded_viewer_Plural": "%1$s widzów",
	"BroadcastWatch_View_Broadcast_Page": "Wyświetl stronę transmisji",
	"Broadcast_Embed_Watch_SteamTV": "Oglądaj na Steam.tv",
	"Broadcast_Embed_Watch_With_Frieds_SteamTV": "Oglądaj i czatuj ze znajomymi na Steam.tv",
	"sale_three_section_hide_chat": "Ukryj czat",
	"sale_three_section_show_chat": "Pokaż czat",
	"btn_live_streams_all": "Pokaż wszystko"
}
