import "enums.proto";
import "steammessages_base.proto";
import "webuimessages_base.proto";

option optimize_for = SPEED;
option cc_generic_services = true;

message CScreensaver_GetActiveState_Request {
}

message CScreensaver_GetActiveState_Response {
	optional bool active = 1;
}

message CScreensaver_ActiveStateChanged_Notification {
	optional bool active = 1;
}

message CScreensaver_GetLocalScreensavers_Request {
}

message CScreensaver_GetLocalScreensavers_Response {
	message Screensaver {
		optional string id = 1;
		optional string path = 2;
	}

	repeated .CScreensaver_GetLocalScreensavers_Response.Screensaver screensavers = 1;
}

message CScreensaver_ForceScreensaver_Request {
	optional bool enabled = 1;
}

message CScreensaver_ForceScreensaver_Response {
}

service Screensaver {
	option (webui_service_execution_site) = k_EClientExecutionSiteSteamUI;

	rpc GetActiveState (.CScreensaver_GetActiveState_Request) returns (.CScreensaver_GetActiveState_Response);
	rpc NotifyActiveStateChanged (.CScreensaver_ActiveStateChanged_Notification) returns (.WebUINoResponse);
	rpc GetLocalScreensavers (.CScreensaver_GetLocalScreensavers_Request) returns (.CScreensaver_GetLocalScreensavers_Response);
	rpc ForceScreensaver (.CScreensaver_ForceScreensaver_Request) returns (.CScreensaver_ForceScreensaver_Response);
}
